### ISSUE TITLE
Route parameter casing does not match Laravel behaviour

### ISSUE THREAD

**Issue by adevade** [livewire/livewire#1000]
### Description

Laravel automagically converts route parameters between different casings _(snake, camel)_, but Livewire does not.

### Steps to reproduce

Create some routes: 

```php
// Both of these work
Route::get('/laravel-snake/{big_fish}', function ($bigFish) { return $bigFish; });
Route::get('/laravel-camel/{bigFish}', function ($big_fish) { return $big_fish; });

// Only the first one works
Route::livewire('/livewire-snake/{big_fish}', 'big-fish');
Route::livewire('/livewire-camel/{bigFish}', 'big-fish');
```
_Notice the casing on the parameters_

And catch the parameter in the Livewire component:

```php
namespace App\Http\Livewire;

use Livewire\Component;

class BigFish extends Component
{
    public function mount($big_fish)
    {
        return $big_fish;
    }
}
```

**Context**
- Livewire version: [e.g. 1.1.0]
- Laravel version: [e.g. 7.11.0]

**Comment by calebporzio** [comment]
Valid point.

However, we're going to stick with the current behavior for now.

I recommend making both parameters match. I believe that's reasonable given both the component and the route declaration are under the devs control.

Thanks!
