### ISSUE TITLE
Bootstrap model closing after wire:click action

### ISSUE THREAD

**Issue by trollfalgar** [livewire/livewire#1002]
### Description
When clicking on a button to delete a record, within a modal Bootstrap, the modal disappears, blocking the background screen.
The button refers to a wire:click="delete('id')" where it simply deletes the record.
My intention is that the record is deleted and the modal continues to be displayed for other actions.

![Modal](https://i.imgur.com/CGIQC7h.png)

Does anyone know the trick for this to work?

**Context**
- Livewire version: [e.g. 1.1.0]
- Laravel version: [e.g. 7.12.0]

**Comment by trollfalgar** [comment]
Solved.

**Comment by kamilkozak** [comment]
@trollfalgar How did you deal with it? I have the same problem.

**Comment by trollfalgar** [comment]
> @trollfalgar How did you deal with it? I have the same problem.

The secret is in **wire:ignore**. I added wire:ignore in the first DIV of the modal. And I used javascript to hide the deleted record line.

**Comment by sh6210** [comment]
@trollfalgar you saved my day. Can you tell me where did you find the solution?

**Comment by trollfalgar** [comment]
> @trollfalgar you saved my day. Can you tell me where did you find the solution?

I used the same principle present here for, select2 plugin: https://laravel-livewire.com/docs/2.x/alpine-js#ignoring-dom-changes
But, later I found some treads on Livewire Forum about it.
