### ISSUE TITLE
Livewire validation print @error instead of running it 

### ISSUE THREAD

**Issue by hortigado** [livewire/livewire#1003]
![image](https://user-images.githubusercontent.com/42924254/82721910-84c14c80-9c87-11ea-8212-7a5771d3d33f.png)

Hi i have it error, i am work with livewire validation but it print @error.
Helpme
if i put `<div> @error('name'){{ $message }}@enderror </div>`
Error: Undefined variable: message

**Comment by devcircus** [comment]
Doesn't seem like a livewire issue. @error is a laravel feature. Is your file named with ```.blade.php```

**Comment by hortigado** [comment]
![image](https://user-images.githubusercontent.com/42924254/82722214-3b263100-9c8a-11ea-96ba-dab9552730c1.png)
Hi bro thank, Yes i don't understand what's wrong until i reinstalled livewire

**Comment by hortigado** [comment]
I try both ways to validate and neither works for me

**Comment by devcircus** [comment]
Are you on a version of Laravel older than 5.8? @error was added in 5.8

**Comment by hortigado** [comment]
Loool that must be the problem I use 5.7. Thanks I will upload version to see what happens

**Comment by devcircus** [comment]
Cool. In the meantime, you could use
```php
@if($errors->has('my_field')
    <span>{{ $errors->first('my_field') }}</span>
@endif
```

**Comment by hortigado** [comment]
Thanks friend, you are my angel beacuse you saved my day, it was as simple as raising the laravel to 5.8
