### ISSUE TITLE
Input values flicker when AJAX requests in flight 

### ISSUE THREAD

**Issue by joshhornby** [livewire/livewire#1007]
### Description

First can I just say this library is brilliant! 🎉

If I update an `input` element, quickly tab to the next input and update this as well. Due to the first AJAX request being inflight the 2nd input will update to the original data, then update once it's AJAX request has returned.

This is only noticeable with slow AJAX requests, in my example I'm using my local Docker which is quite slow.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5455767/82748864-17074480-9d9d-11ea-9765-df7521ca0c88.gif)

```
<div>
    <form wire:submit.prevent="submit">
        <input placeholder="Name" type="text" wire:model.lazy="name">
        @error('name') <span class="error">{{ $message }}</span> @enderror

        <input placeholder="Email" type="text" wire:model.lazy="email">
        @error('email') <span class="error">{{ $message }}</span> @enderror

        <button type="submit">Save Contact</button>
    </form>
</div>
```

### Steps to reproduce

- Create a component with two inputs
- Add values to both inputs
- Update the value of input 1
- Before the AJAX request has returned for input 1, update the value of input 2

**Context**
- Livewire version: 1.1
- Laravel version: 7.12
- Browser: Chrome

**Comment by keepanitreel** [comment]
I do not believe this is a bug. 
Use Lazy Loading.
https://laravel-livewire.com/docs/properties#lazy-updating
If you can also add a debouncing value that will produce the result you are looking for.

**Comment by joshhornby** [comment]
I am using lazy loading (see code above) and debouncing doesn't solve the issue unfortunately.

**Comment by ryangjchandler** [comment]
Does adding a `wire:ignore` attribute to your input make any difference?

**Comment by joshhornby** [comment]
Would adding `wire:ignore` mean I wouldn't be able to get the input values though?

I think the issue is more of a conceptual one, if a request is in flight & I edit another field on the form should the in fight request not be cancelled? Is there a reason you'd want the in flight request to update the DOM when you're already updating the DOM again?

**Comment by ryangjchandler** [comment]
`wire:ignore` just ensures that Livewire doesn't swap out the DOM node, on seconds thoughts though `wire:model` is obviously mutating the input values via the JavaScript.

**Comment by khanalpride** [comment]
@joshhornby I think the wire:model.passive which is in the roadmap will fix this issue.
https://github.com/livewire/livewire#roadmap

All the wire:model input are updated on key input on certain debounce obviously, but i feel like when there are 10-12 inputs in a page, going for 10+ round trip to server before submitting all input is not good.

So in my view, wire:model.passive will keep state of variables in javascript, and only submit all at once when user submits, or if it needs in case of events and listeners firing on component.

@calebporzio I hope the description I provided for wire:model.passive is correct. and if its correct and implemented, then that would be awesome. :)

**Comment by calebporzio** [comment]
`wire:model.passive` will be called `wire:model.defer` and will be available in the next version of livewire (V2)

This will fix your issue. Closing this for now!
