### ISSUE TITLE
Getting zero  0 in the  input  model of livewire 

### ISSUE THREAD

**Issue by hemant17** [livewire/livewire#1010]
### Description
When i try to type something in the input model it's somethime return 0 in the box 
### Steps to reproduce
no idea how i were just doing 
public $name;
and in blade 
wire:model="name"
![NextLevelbot](https://user-images.githubusercontent.com/10548023/82757632-56667d00-9dff-11ea-8976-882cd1e51e1d.gif)
**Context**
- Livewire version: Latest
- Laravel version: Latest
- Browser: Chrome,

**Comment by keepanitreel** [comment]
Try wrapping your component in a <div> it may be that Alpine is unable to locate the correct element.
Have you verified that response from your server is not returning 0?

**Comment by hemant17** [comment]
well it's was really strange but that was happening because of this library 
https://appleple.github.io/modal-video/
i removed it now everything working fine as usal for now

**Comment by corbinjurgens** [comment]
I experienced same issue.

By removing the same plugin you mentioned from the page it was fixed. I would have never found the cause! Thank you @hemant17

**Comment by rionjau** [comment]
I do not have that plugin but I still have the issue :(

**Comment by timoisik** [comment]
Hey @rionjau, I had the same issue, but with another library, which caused the problem. In my case it was [https://github.com/rodneyrehm/viewport-units-buggyfill](https://github.com/rodneyrehm/viewport-units-buggyfill).

So check your libraries if there is any, which causes the problem. :)
