### ISSUE TITLE
sweet not working with livewire

### ISSUE THREAD

**Issue by oluwatosinolamilekan** [livewire/livewire#1011]
### Steps to reproduce
![image](https://user-images.githubusercontent.com/29930457/82764583-b8c37b80-9e07-11ea-8aa0-ff9e4f519edf.png)

**Context**
- Livewire version: [e.g. 3.1
- Laravel version: [e.g. 7.12]
- Browser: [e.g. Chrome]

**Comment by devcircus** [comment]
Not really enough information there to know what you're trying to do and what isn't working. Are you talking about sweet alert? If so, checkout out [this thread](https://github.com/livewire/livewire/issues/320).

**Comment by oluwatosinolamilekan** [comment]
when returning a flash message after a task or a function has been completed.. so instead of using a         session()->flash('message', 'Post successfully updated.'), am trying to use a notification package that shows and alert or pop up a notification at the end of my task

**Comment by devcircus** [comment]
This isn't a bug in livewire. You need to emit an event from your Livewire component and pick it up in your javascript. Then you can set the notification information and display it. It works correctly. The only part that Livewire plays is dispatching an event to notify javascript that there is a notification. At that point, your javascript takes over and handles displaying the notification.

**Comment by DanHarrin** [comment]
Hi, I'm going to close this issue for now due to inactivity. Please use the [discussions section](https://github.com/livewire/livewire/discussions) or [Discord server](https://discord.gg/pAMqTCF) for additional support. Many thanks!
