### ISSUE TITLE
error in script url

### ISSUE THREAD

**Issue by riwash** [livewire/livewire#1014]
Hello here is error in script url source is 

<script src="/vendor/livewire/livewire.js?id=2e357e509d45977b1c0d" data-turbolinks-eval="false"></script>
--but we need to work with 

<script src="https://locahost/projecname/vendor/livewire/livewire.js?id=2e357e509d45977b1c0d" data-turbolinks-eval="false"></script>
--
How to fixed this ??

**Comment by lancepioch** [comment]
> Laravel should always be served out of the root of the "web directory" configured for your web server. You should not attempt to serve a Laravel application out of a subdirectory of the "web directory".

https://laravel.com/docs/7.x/installation#directory-configuration
