### ISSUE TITLE
can't use name $file for method parameter because a FileSystem instance is expected

### ISSUE THREAD

**Issue by insology** [livewire/livewire#1017]
### Description
Can't use $file as parameter in method because is expected a FileSystem instance

### Steps to reproduce
create a method like 
```
/**
 * Set the files.
 *
 * @param  array  $files
 */
public function setFiles($files)
{
    $this->files = $files;
}
```
**Context**
- Livewire version: version: 1.1
- Laravel version: 7.0
- Browser: Chrome

**Comment by JohnRoux** [comment]
See PR [958](https://github.com/livewire/livewire/pull/958) 
File uploads are not currently supported but are in the works

**Comment by devcircus** [comment]
There's a PR (#910) that's been open for about a month to fix this. Hoping it'll be fixed soon. I filed an issue a while back concerning the same thing. (#904)

**Comment by devcircus** [comment]
There's several problems with how dependency injection is handled for actions. I've noticed a couple of tweets from Caleb recently that suggest he's working on overhauling how dependency injection works for actions.

**Comment by insology** [comment]
@devcircus , yes is the same problem of the $path "parameter name" 
@JohnRoux i'm not speaking about the upload functionality but only the "parameter name", we are using axios for the files post ;)

**Comment by calebporzio** [comment]
This has been fixed and will be available in the next release.
