### ISSUE TITLE
Turbolinks breaks livewire on initial page load after logging in

### ISSUE THREAD

**Issue by colinmac17** [livewire/livewire#1022]
### Description

note: Not sure if this is related to turbolinks or livewire, but any help or insight as to why this may be happening would be amazing! I could not find anything else in a prior issue or on the forum.

What seems to be the problem:

I have turbolinks working correctly. However there is one catch.
When I logout and login to my laravel application (using standard session based auth) and navigate to a livewire component and start interacting with wired elements, no ajax requests are fired (on all livewire components). After I reload the page, all components work as expected.

Has anyone else ran into this? I am on the latest version of livewire and below is my turbolinks integration (super simple).

const Turbolinks = require("turbolinks")
Turbolinks.start()

Video of issue: https://www.loom.com/share/c851b06d48b04982b2bc50b232a5d1a6
### Steps to reproduce

1. create a laravel project with standard auth
2. install turbo links
3. Create a livewire component
4. Navigate to livewire component after logging in
5. No ajax requests firing

**Context**
- Livewire version: [v1.1.0]
- Laravel version: [v7.13.0]
- Browser: [Chrome]

**Comment by colinmac17** [comment]
Is this the code that is causing this? 

`var firstTime = true;
    document.addEventListener("turbolinks:load", function() {
        /* We only want this handler to run AFTER the first load. */
        if  (firstTime) {
            firstTime = false;
            return;
        }

        window.livewire.restart();
    });`

**Comment by stevebauman** [comment]
I'm getting this too 👍 

Only way I've been able to get around this is by booting turbolinks inside of the `livelier:load` event:

```js
// resources/js/app.js

const turbolinks = require('turbolinks');

document.addEventListener("livewire:load", function(event) {
    turbolinks.start();
});
```

But I honestly don't know if this is proper practice -- or if this breaks anything else... I do wish there was implementation instructions on how to use Turbolinks with Livewire properly.

**Comment by stevebauman** [comment]
Also, for further reference, I have this in the `<head>` of my base layout:

```blade
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Watchdog') }}</title>

    <!-- Scripts -->
    <script src="{{ asset(mix('js/app.js')) }}" defer data-turbolinks-track="reload"></script>
    <livewire:scripts/>
    @stack('scripts')

    <!-- Styles -->
    <link href="{{ asset(mix('css/app.css')) }}" rel="stylesheet" data-turbolinks-track="reload">
    <livewire:styles/>
    @stack('styles')
</head>
```

**Comment by retry19** [comment]
> Also, for further reference, I have this in the `<head>` of my base layout:
> 
> ```
> <head>
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
> 
>     
>     <meta name="csrf-token" content="{{ csrf_token() }}">
> 
>     <title>{{ config('app.name', 'Watchdog') }}</title>
> 
>     
>     <script src="{{ asset(mix('js/app.js')) }}" defer data-turbolinks-track="reload"></script>
>     <livewire:scripts/>
>     @stack('scripts')
> 
>     
>     <link href="{{ asset(mix('css/app.css')) }}" rel="stylesheet" data-turbolinks-track="reload">
>     <livewire:styles/>
>     @stack('styles')
> </head>
> ```

thanks, it's work for me 😁

**Comment by colinmac17** [comment]
@stevebauman awesome, thanks for sharing this! This is fine for now and I guess it does make sense for the livewire use case.

I think this should be considered for the livewire docs possibly?

**Comment by stevebauman** [comment]
Glad I could help @colinmac17!

> I think this should be considered for the livewire docs possibly?

Yeah I think so -- I'll submit a PR to the docs 👍

**Comment by tanthammar** [comment]
I am not sure I agree with this:

resources/js/app.js
```
const turbolinks = require('turbolinks');

document.addEventListener("livewire:load", function(event) {
    turbolinks.start();
});
```

Livewire waits for `turbolinks:before-cache` and `turbolinks:load` so it does not make sense to me.

**Comment by seyed-me** [comment]
> I'm getting this too 👍
> 
> Only way I've been able to get around this is by booting turbolinks inside of the `livewire:load` event:
> 
> ```js
> // resources/js/app.js
> 
> const turbolinks = require('turbolinks');
> 
> document.addEventListener("livewire:load", function(event) {
>     turbolinks.start();
> });
> ```
> 
> But I honestly don't know if this is proper practice -- or if this breaks anything else... I do wish there was implementation instructions on how to use Turbolinks with Livewire properly.

I have the same problem and it does not work for me.

**Comment by colinmac17** [comment]
@seyed-me @tanthammar was there a new update for this? This is the only solution that has worked for me and has worked effortlessly so far (no issues).

**Comment by seyed-me** [comment]
> @seyed-me @tanthammar was there a new update for this? This is the only solution that has worked for me and has worked effortlessly so far (no issues). Personally, I think the documentation just needs to have some more details to clear this up - https://laravel-livewire.com/docs/turbolinks. @calebporzio what do you think of all this? Would love your thoughts.

Also the livewire vue plugin does not work.

**Comment by stevebauman** [comment]
> Also the livewire vue plugin does not work.

Yeah I encountered this as well.

I had to ditch Livewire for a project since I had invested in Vue heavily. At this current time, it doesn’t seem possible to integrate Vue and Livewire together. It’s either Livewire, Turbolinks and Livewire, or Turbolinks and Vue. Waiting for clear instruction on how they should be used together 👍

**Comment by tanthammar** [comment]
@stevebauman 
I have the same opinion, Turbolinks is working with Livewire alone. (after this fix #1005 ). 
But Alpine and/or Vue with Livewire and Turbolinks gives TONS of trouble.
For me it is when browsing back/forward in history that breaks JS.

@seyed-me 
Yes I would love to use livewire directives in vue, but It does not work. like `@this.call()` which is flawless with Alpine.

**Comment by tanthammar** [comment]
Does anyone know of an alternative to Turbolinks. I cannot be without Alpine or Vue. 
And the application page loads are so slow without Turbolinks. 
Really a jam ...

**Comment by seyed-me** [comment]
> > Also the livewire vue plugin does not work.
> 
> Yeah I encountered this as well.
> 
> I had to ditch Livewire for a project since I had invested in Vue heavily. At this current time, it doesn’t seem possible to integrate Vue and Livewire together. It’s either:
> 
> 1. Livewire
> 2. Turbolinks and Livewire
> 3. Or; Turbolinks and Vue.
> 
> Waiting for clear instruction on how they should be used together 👍

To use Livewire with Vue, I added `window.Vue = Vue;` and It works.

**Comment by stevebauman** [comment]
> Does anyone know of an alternative to Turbolinks

@tanthammar The only thing I know of is [Unpoly](https://unpoly.com). Personally going to be giving this a shot my self and see how it performs with Laravel.

**Comment by tanthammar** [comment]
> > > Also the livewire vue plugin does not work.
> > 
> > 
> > Yeah I encountered this as well.
> > I had to ditch Livewire for a project since I had invested in Vue heavily. At this current time, it doesn’t seem possible to integrate Vue and Livewire together. It’s either:
> > 
> > 1. Livewire
> > 2. Turbolinks and Livewire
> > 3. Or; Turbolinks and Vue.
> > 
> > Waiting for clear instruction on how they should be used together 👍
> 
> @tanthammar To use Livewire with Vue, I added `window.Vue = Vue;` and It works.

I had laravel default `window.Vue = require('vue')` your solution works :) Now I can use `@this.call()`

**Comment by tanthammar** [comment]
@stevebauman would be great to hear back, on your progress. Was looking into Unpoly ... not tried yet.

**Comment by stevebauman** [comment]
Playing with it right now actually @tanthammar! There's Laravel package that supports it here:

https://github.com/webstronauts/php-unpoly

I'll comment back with what I find out and its usability / features 👍 . I'm going to be testing basic form stuff, pagination, notifications with sweetalert2, and "turbolinks" capability (navigating pages without full reloads). Basically the building blocks of my web apps. I'm a single-person dev team, so a full backend API using Vue is out of the question for me (shot myself in the foot with this one years ago).

**Comment by seyed-me** [comment]
> > Also the livewire vue plugin does not work.
> 
> Yeah I encountered this as well.
> 
> I had to ditch Livewire for a project since I had invested in Vue heavily. At this current time, it doesn’t seem possible to integrate Vue and Livewire together. It’s either:
> 
> 1. Livewire
> 2. Turbolinks and Livewire
> 3. Or; Turbolinks and Vue.
> 
> Waiting for clear instruction on how they should be used together 👍

I have a solution to fix  Livewire components firing ajax in a Vue component after navigating with Turbolinks:
`
// app.js

turbolinks.start();

function initiateVue() {
         const app = new Vue({
                 el: '#app'
          });
}

document.addEventListener("turbolinks:load", function(event) {
    document.querySelectorAll('[wire\\:id]').forEach(function(el) {
        const component = el.__livewire;
        const dataObject = {
            data: component.data,
            events: component.events,
            children: component.children,
            checksum: component.checksum,
            name: component.name,
            errorBag: component.errorBag,
            redirectTo: component.redirectTo,
        };
        el.setAttribute('wire:initial-data', JSON.stringify(dataObject));
    });
    initiateVue();
    window.livewire.start();
    document.getElementsByTagName('html')[0].classList.remove('overflow-y-hidden');
});

`

**Comment by tanthammar** [comment]
@seyed-me 
Shouldn't you be calling `window.livewire.restart();` ?

Or have you checked how many times `window.livewire.start()`fires?

LiveWire runs `start()` on `DOMContentLoaded` and then does a `restart()` on `turbolinks:load` 

With your script it looks like you are starting it again?

**Comment by seyed-me** [comment]
@tanthammar There is no difference between `start()` and `restart()` because Livewire is stopped after navigating with Turbolinks and I do not know why this happens. Yes, Livewire should be started again in `turbolinks:load` event. Livewire runs with this:
```js
  
    window.livewire = new Livewire();
    window.livewire_app_url = '';
    window.livewire_token = 'i0CUG2NYIkjK4RTg75SSUaThU9YduhuHOxlZ0Siw';

    document.addEventListener("DOMContentLoaded", function () {
        window.livewire.start();
    });

    var firstTime = true;
    document.addEventListener("turbolinks:load", function() {
        /* We only want this handler to run AFTER the first load. */
        if  (firstTime) {
            firstTime = false;
            return;
        }

        window.livewire.restart();
    });

    document.addEventListener("turbolinks:before-cache", function() {
        document.querySelectorAll('[wire\\:id]').forEach(function(el) {
            const component = el.__livewire;

            const dataObject = {
                data: component.data,
                events: component.events,
                children: component.children,
                checksum: component.checksum,
                name: component.name,
                errorBag: component.errorBag,
                redirectTo: component.redirectTo,
            };

            el.setAttribute('wire:initial-data', JSON.stringify(dataObject));
        });
    });
```
`window.livewire.start()` fires only one time at `DOMContentLoaded` by default.

Of course restarting Livewire is only needed for components that are placed in global Vue component that it also mount in `turbolinks:load` event. If you put your Livewire component outside of Vue, there is no need to restart Livewire.

**Comment by jimpeters** [comment]
> Also, for further reference, I have this in the `<head>` of my base layout:
> 
> ```
> <head>
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
> 
>     
>     <meta name="csrf-token" content="{{ csrf_token() }}">
> 
>     <title>{{ config('app.name', 'Watchdog') }}</title>
> 
>     
>     <script src="{{ asset(mix('js/app.js')) }}" defer data-turbolinks-track="reload"></script>
>     <livewire:scripts/>
>     @stack('scripts')
> 
>     
>     <link href="{{ asset(mix('css/app.css')) }}" rel="stylesheet" data-turbolinks-track="reload">
>     <livewire:styles/>
>     @stack('styles')
> </head>
> ```

Just a comment on this. I assume turbolinks is in your app.js bundle.  You should be including <livewire:scripts> BEFORE your app.js bundle containing AlpineJS and/or Turbolinks or it will be unable to properly hook into the libraries.

**Comment by stevebauman** [comment]
Thanks @jimpeters! I am not actually sure if I tried that, but I'll give it a shot and report back 👍

**Comment by altwaireb** [comment]
you can try this in said component :

```
.....


@push('scripts')
        <script>
            Livewire.restart();
        </script>
    @endpush
 </div> 
```

**Comment by calebporzio** [comment]
Turbolinks support has now been moved to a separate repo.

Please re-submit any current issues there: https://github.com/livewire/turbolinks

Thanks!

**Comment by Sofianio** [comment]
@seyed-me 
Thanks a lot, 
I know your solution was for Vue.js 
But I just took the "restart on Turbolinks load" which wasn't happening for some reason
```js
document.addEventListener("turbolinks:load", function(event) {
    window.livewire.restart();
});
```
Now Livewire works fine after going to another page

**Comment by smcnepal** [comment]
facing the similar problem

**Comment by mani1430** [comment]
Yeah !
I have the problem to so many days but today the problem has cleared
I just add the component bottom script. 

<script>
window.livewire.restart();
</script>

**Comment by kamimore** [comment]
Thanks its works for me too, 
adding 
<script> window.livewire.restart(); </script>
into the bottom of the component
