### ISSUE TITLE
$set does not run updated hook

### ISSUE THREAD

**Issue by indigoram89** [livewire/livewire#1024]
### Description
When we call wire:click.prevent="$set('amount', 1)" in the browser it do not run updated($key) hook on server side.

### Steps to reproduce
1 - Set the listener: wire:click.prevent="$set('amount', 1)"
2 - Set the hook: public function updated($key) { info('updated', compact('key')); }
3 - Try to click and check laravel logs.

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.13.0
- Browser: Chrome

**Comment by mblarsen** [comment]
I've made a PR for this already #1009
