### ISSUE TITLE
Microsoft Edge Autofill Error AutoFill_FillEvent

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#1034]
### Description
When doing autofill on Microsoft Edge, the inputs are updating with the proper value then flashing to 'AutoFill_FillEvent'. It only seems to be happening on Microsoft Edge
![Broken](https://i.imgur.com/y7vzNN8.gif "Broken")

### Steps to reproduce
```php
<input type="text" autocomplete="family-name lname" name="lname" wire:model.lazy="a.lname" class="@error('a.lname') error @enderror" />
```

**Context**
- Livewire version: Current
- Laravel version: Current
- Browser: Microsoft Edge

**Comment by nuernbergerA** [comment]
Hey @jjjrmy

since autofill is still a pain to work with, could you try if this works for you?
```blade
<input x-data x-on:AutoFill_FillEvent="$dispatch('change', @this.value)" type="text" autocomplete="family-name lname" name="lname" wire:model.lazy="a.lname" class="@error('a.lname') error @enderror" />
```

**Comment by jjjrmy** [comment]
I must do this on all inputs?

**Comment by nuernbergerA** [comment]
Just for now to test this out

**Comment by jjjrmy** [comment]
@nuernbergerA 
I don't think the `x-on:AutoFill_FillEvent` is firing at all.

**Comment by nuernbergerA** [comment]
Can you share your HTML so I can test it on my windows machine?

**Comment by nkeena** [comment]
I'm experiencing the same issue. My registration form is a Livewire component and the form inputs are blade components. Here's what the input for collecting the user's first name looks like:

```
<x-inputs.text 
    wire:model.lazy="firstName"
    name="firstName" 
    label="First name" 
    placeholder="John"
    required
/>
```

And the markup for the actual input field in the blade component:

```html
<input 
class="..."
value="{{ isset($value) ? old($name, $value) : old($name) }}"
autocomplete="{{ $name }}"
{{ $attributes->merge(['id' => $name]) }}
/>
```

Wondering if the problem is here: `autocomplete="{{ $name}}"` ?

**Comment by calebporzio** [comment]
I'm new to this, but I just put a $200 USD bounty on fixing this issue on BountySource.

Here's the link: https://www.bountysource.com/issues/91607963-microsoft-edge-autofill-error-autofill_fillevent

BountySource already collected the $200 from me, so they are holding it until someone fixes this.

**Comment by nuernbergerA** [comment]
@jjjrmy Is it the new (chromium-based) or old MS Edge?

**Comment by miteshmap** [comment]
@jjjrmy I don't think we can have `autocomplete="family-name lname"` as a value for autocomplete. Autocomplete accepts only on or off value. Am I missing something here?

**Comment by webmasterdro** [comment]
> @jjjrmy I don't think we can have `autocomplete="family-name lname"` as a value for autocomplete. Autocomplete accepts only on or off value. Am I missing something here?

Yes, actually you have a ton of accepted values for the autocomplete field. Check it here: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-field

**Comment by codeduction** [comment]
I got the same results testing it on the latest Edge

**Comment by codeduction** [comment]
It seem's to be an issue with old MS Edge not the Chromium version from my tests.

**Comment by rodrigore** [comment]
I try to replicate the error but I couldn't.  I use  Version 83.0.478.56  (64 bits) of Microsoft on Windows 10.

**Comment by mazedlx** [comment]
> I try to replicate the error but I couldn't.  I use  Version 83.0.478.56  (64 bits) of Microsoft on Windows 10.

I think the problem is with the old Edge not the chromium one.

**Comment by jjjrmy** [comment]
The error is on the older version of MS Edge as @codeduction mentioned. Seems fine on the newest Chromium version.

**Comment by codeduction** [comment]
Oddly mine says "Microsoft Edge 44.18362.449.0" on Windows 10 Pro.

Not entirely sure why my version is nearly half your version, my windows is on the latest version except the feature 2004 update that isn't out fully yet.

**Comment by codeduction** [comment]
Also after looking into it a little bit, it seems the Autofill doesn't seem to trigger a change event at all.

Will keep looking when i get a bit of extra free time.

**Comment by jjjrmy** [comment]
> Also after looking into it a little bit, it seems the Autofill doesn't seem to trigger a change event at all.

There are a few other issues open mentioning the same thing with other autofill events

**Comment by codeduction** [comment]
Thanks @jjjrmy 
Might fully be related then, Will see if they have found any route to fix it.

**Comment by codeduction** [comment]
I have found the area that is causing it to fill with "AutoFill_FillEvent" will try work on a fix for it.

**Comment by codeduction** [comment]
@jjjrmy just did pull request for the fix hopefully, If you want to give it a whirl on your setup also. 

Done tests on chrome, IE11 and IE Edge all seems to work as intended with that fix.

**Comment by calebporzio** [comment]
Thanks @codeduction!!

**Comment by teodoriu** [comment]
Anyone have this issue on the latest chrome version?

**Comment by teodoriu** [comment]
@codeduction I am having this issue in edge 44 (non-chrome version). How can i debug it?

**Comment by codeduction** [comment]
@teodoriu was a case of just deep diving into the code until I figured out where the issue was.

Originally the file I had to make changes to was js/node_initializer.js  you can see in the above commit.

I don't seem to have access to that version atm otherwise I would also give it a test for you.

**Comment by jwohlfert23** [comment]
@teodoriu I'm still having this issue in Edge 44 on Windows 10 as well.  Were you able to solve?

**Comment by f-liva** [comment]
Me too
