### ISSUE TITLE
The custom Livewire directives don't work with view caching

### ISSUE THREAD

**Issue by mgussekloo** [livewire/livewire#1039]
Using Livewire's custom directives (@this) don't work when using view caches. I'm not sure if this is expected behavior, this sort of functionality might simply not be supported by Laravel. https://github.com/laravel/framework/issues/16084)

I hope anyone can look into this, and make it work as expected.

### Steps to reproduce
Use something like

```
@push('scripts')
window.questionFileUploadComplete = function(response) {
				@this.call('addFile', response);
			}
@endpush
```

Then, enable view caching (php artisan view:cache). Now @this is no longer translated in the rendered HTML.

**Context**
- Livewire version: 1.0.0
- Laravel version: 7

**Comment by nuernbergerA** [comment]
Ok, this is a tough one.
There is actually a [test](https://github.com/livewire/livewire/blob/8265ae11d5091db51a81506801c1da2009ad6a11/tests/LivewireDirectivesTest.php#L70) that enforces this behavior.

@calebporzio I see why you just made it available for livewire components.
But the `view:cache` command uses the `BladeCompile` and tasks all blade files in the view directory.

So maybe we need to tell the BladeCompile if he tries to compile files within the `livewire` folder it should use `Blade::directive('this', [LivewireBladeDirectives::class, 'this'])`
I don't see a way to achieve that

After spending 2 hours on this and digging that deep in the compiler stuff - I need a break.

**Comment by nuernbergerA** [comment]
@mgussekloo That's a good catch.

For now, an easy workaround would be to put this in your `AppServiceProvider` under `register`
```php
Blade::directive('this', [LivewireBladeDirectives::class, 'this'])
```

**Comment by tanthammar** [comment]
Why is this issue closed? Is it solved?
Think it should remain open until the blade directive is added to Livewire core or solved in another way.

**Comment by tanthammar** [comment]
@nuernbergerA I tried your suggestion but I get this error:
```
Argument 2 passed to Illuminate\View\Compilers\BladeCompiler::directive() must be callable, array given
```

Any suggestions?

**Comment by nuernbergerA** [comment]
@tanthammar https://github.com/livewire/livewire/issues/1039#issuecomment-637036445

**Comment by tanthammar** [comment]
Sorry my bad. I forgot to import LivewireBladeDirectives::class
