### ISSUE TITLE
Using wire:key without mount method defined

### ISSUE THREAD

**Issue by bomshteyn** [livewire/livewire#1042]
### Description
When livewire component doesn't have mount function it can't accept wire:key assignment
### Steps to reproduce
`<livewire:app.product.import wire:key="import-products-{{Str::random(10)}}"/>`
```
<?php

namespace App\Http\Livewire\App\Product;

use Livewire\Component;

class Import extends Component
{
    public $modalOpen = 'false';

    protected $listeners = ['importProductsModalOpen'];

    public function importProductsModalOpen()
    {
        $this->modalOpen = 'true';
    }

    public function render()
    {
        return view('livewire.app.product.import');
    }
}
```
**getting the following error:**
```
Livewire\Exceptions\MountMethodMissingException
Livewire encountered a missing mount method when trying to initialise the [app.product.import] component. When passing component parameters, make sure you have a mount method.
```

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.13.0

**Comment by bomshteyn** [comment]
Adding an empty mount method like so:
```
public function mount()
    {

    }
```

solves it for me, but would prefer not to have an empty method :-)

**Comment by nuernbergerA** [comment]
Hey Nathan,

as mentioned [here](https://github.com/livewire/livewire/pull/1043#issuecomment-637239593) the correct syntax would be:
```blade
<livewire:app.product.import key="import-products-{{ Str::random(10) }}"/>
```
Or below Laravel 7.x
```blade
@livewire('my-component', [], 'import-products-'. Str::random(10))
```
Please note that the `key` shouldn't be random each time.
It's used to identify the same item,  therefore it should be an `id`

Please make sure to visit the [docs](https://laravel-livewire.com/docs/troubleshooting) for more details.

Have a nice day!

**Comment by bomshteyn** [comment]
@nuernbergerA  thanks
