### ISSUE TITLE
@this does not work with artisan view:cache

### ISSUE THREAD

**Issue by tiago-sb** [livewire/livewire#1046]
### Description
`@this` does not play well with `artisan view:cache`

### Steps to reproduce

1. Use the `@this` directive in your livewire component.
2. Run `artisan view:cache` to clear/recompile your blade views
3. Check the generated view and you'll see `@this` is still in there.
4. A quick check can be done by doing `grep '@this' storage/framework/views/*`

This then generates a javascript error:
```javascript
SyntaxError: illegal character jsdelivr-header.js:5
    evaluateCommandExpression alpine.js:114
    evaluateCommandExpression alpine.js:1541
    w alpine.js:760
    l alpine.js:737
    getDispatchFunction alpine.js:1548
    anonymous alpine.min.js line 7 > Function:3
    evaluateCommandExpression alpine.js:114
    evaluateCommandExpression alpine.js:1541
    w alpine.js:760
    l alpine.js:737
    getDispatchFunction alpine.js:1548
    anonymous alpine.min.js line 7 > Function:3
    evaluateCommandExpression alpine.js:114
    evaluateCommandExpression alpine.js:1541
    w alpine.js:760
    l alpine.js:737
```

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.13
- Browser: Firefox (latest)

**Comment by nuernbergerA** [comment]
Hey Tiago,

Please [use this workaround](https://github.com/livewire/livewire/issues/1039#issuecomment-637036445) for now.

**Comment by tiago-sb** [comment]
Thanks for pointing it out!
... I searched both the foum and the github issues and could find that one.

**Comment by nuernbergerA** [comment]
You are welcome :smile:
