### ISSUE TITLE
Script tag in child component not executed after reload

### ISSUE THREAD

**Issue by cosmospham** [livewire/livewire#1048]
### Description

Script tag in component not executed after livewire reloaded, althought the HTML contains it.

### Steps to reproduce

- Parent livewire component require a child component.
- Console logged for the first time when the script loaded.
- Click the button, Console logged the second time. We can see the network tab (devtool) loads the livewire.
- Click the button again, Console DOES NOT log anymore. We can also see the network tab (devtool) loads the livewire.
- The HTML response contains the script tag but it is not executed.

```
# resources/views/livewire/home/home.blade.php

<div class="home-widgets">
    @livewire( 'date-picker', [], key('date-picker') )
</div>
```

```
# resources/views/livewire/date-picker.blade.php

<div>
    <button wire:click="$refresh">Click</button>
    <script>console.log('refreshed')</script>
</div>
```

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.13.0
- Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- PHP: 7.3

<img width="487" alt="Screen Shot 2020-06-03 at 09 14 45" src="https://user-images.githubusercontent.com/1793245/83588059-c0f38780-a57a-11ea-8495-7d313eac0156.png">
<img width="376" alt="Screen Shot 2020-06-03 at 09 14 52" src="https://user-images.githubusercontent.com/1793245/83588069-c5b83b80-a57a-11ea-8216-5e8d6a9fdd6e.png">
<img width="1356" alt="Screen Shot 2020-06-03 at 09 14 59" src="https://user-images.githubusercontent.com/1793245/83588071-c650d200-a57a-11ea-903f-eb72894be1ca.png">

**Comment by cosmospham** [comment]
fix: onNodeAdded script not executed #1049

**Comment by calebporzio** [comment]
This should be fixed in the next release from this PR: https://github.com/livewire/livewire/pull/1179

**Comment by mdalhagg** [comment]
add {{ }}

in your code like this
` <button wire:click="{{$refresh}}">Click</button>`

**Comment by joshhanley** [comment]
@mdalhagg actually, `wire:click="$refresh"` is the correct syntax as `$refresh` isn't a php/blade variable, so we want the extact string of "$refresh" to be output. 🙂
