### ISSUE TITLE
Doesn't allow binding of the base collection class

### ISSUE THREAD

**Issue by KeironLowe** [livewire/livewire#1052]
### Description
When binding an instance of the base collection to a component property, you get the following error... `Livewire component's public property must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.`

### Steps to reproduce

1. Create a component
2. In the mount method, bind a property to a collection e.g, `collect([1,23])`

**Context**
- Livewire version: [e.g. 1.1.0]
- Laravel version: [e.g. 7.0.0]

**Comment by JuanDeLeon** [comment]
Not a bug, this is stated in the docs:
_Properties can ONLY be either a JavaScript-friendly data types (string, int, array, boolean), OR an eloquent model (or collection of models)._

You can bind an Eloquent\Collection:

`use Illuminate\Database\Eloquent\Collection; 
public $test;
public function mount(){
   $this->test = Collection::make();
}`

**Comment by stevebauman** [comment]
This is because _nested_ Collection instances are created with the `mapToGroups()` method.

Simply call `->toArray()` on the resulting collection and this will work.

**Comment by KeironLowe** [comment]
But using `toArray` also converts the models to arrays, so you loose out on functionality such as being calling relationships.

**Comment by calebporzio** [comment]
Thanks for the good solution @stevebauman !
