### ISSUE TITLE
Using with lumen 6x throw exception

### ISSUE THREAD

**Issue by Jimmea** [livewire/livewire#1059]
### Description
In LivewireServiceProvider.php line 98:
                                                                       
  Call to undefined method Laravel\Lumen\Application::bootstrapPath()  
                                                                       
### Steps to reproduce

**Context**
- Livewire version: [e.g. 1.0.0]
- Laravel version: [e.g. 6x]
- Browser: [e.g. Chrome, Safari]

**Comment by eleimt** [comment]
Livewire may be used in Lumen?

**Comment by calebporzio** [comment]
No plans to support Lumen. Lumen is meant for lightweight backend APIs, not for Livewire type apps. Closing, thanks!
