### ISSUE TITLE
when using in package development not work

### ISSUE THREAD

**Issue by vahidalvandi** [livewire/livewire#1060]
### Description

in package develop like bellow but retuen 

**/media/vahid/projects/laravel/****/app/Http/Livewire**

`        Livewire::component('page-search', SearchPage::class);
`

also how i can use component !!!

`            @livewire('site::search-post')
`
this not work also not work

`            @livewire('site::livewire.search-post')
`
**Context**
- Livewire version: 1.1
- Laravel version: 6.18
- Browser: [e.g. Chrome, Safari]

**Comment by iksaku** [comment]
Currently, there's no way to reference Livewire components by scope. A workaround would be to make your component "extendable" and reference that extended class instead.
You can refer to [Livewire-Select](https://github.com/asantibanez/livewire-select) for reference.

It would be interesting to have this feature implemented. So, not a but, but a feature request IMO.

**Comment by calebporzio** [comment]
Correct me if I'm wrong, but I believe this should work:` Livewire::component('site::page-search', SearchPage::class);`

Closing this.

**Comment by vahidalvandi** [comment]
thank you work fine

**Comment by vahidalvandi** [comment]
i have another issue about work it ... 
my component load successfully  but i need use it in home page , after refresh home page dont display any thing . just show header and footer

    **@include('partial.stage6')**

    @livewire('siteFrontend::livewire.page-search')

for example dont show @include('partial.stage6') after add @livewire('siteFrontend::livewire.page-search')

**Comment by vahidalvandi** [comment]
but i have another problem

`Livewire encountered corrupt data when trying to hydrate the [siteFrontend::livewire.searchPage] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.`

i also read https://github.com/livewire/livewire/pull/401 but cant underestant
