### ISSUE TITLE
redirect doesn't work in updated()

### ISSUE THREAD

**Issue by alewolf** [livewire/livewire#1076]
### Description

When trying to use a redirect (as documented) in an updated() function, nothing happens. The redirect is not being executed and no error is thrown. 

### Steps to reproduce

Put a redirect like the following into an updated() function. It won't work:

`return redirect()->to('/target')`

Luckily, when using `$this->` it will start to work, but chaining is not possible. 

This will **not** work: `return $this->redirect()->to('/target')`

But luckily the following does work: `return $this->redirect('/target')`

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.14.1
- Browser: Chrome

**Comment by snapey** [comment]
you should use

    $this->redirect('/target');

or

    $this->redirect(route('target.name'));

and not return it.
