### ISSUE TITLE
Full URLs to livewire resources

### ISSUE THREAD

**Issue by mityukov** [livewire/livewire#1082]
### Description

When using @livewireScript, it generates code like this:
`<script src="/livewire/livewire.js?id=2e357e509d45977b1c0d" data-turbolinks-eval="false"></script>`

Is it possible to tweak Livewire so it loads livewire.js using fully qualified URL? I'd like to use it in a widget, integrated into 3rd-party site, so it wouldn't work without hostname.

**Comment by mityukov** [comment]
Sorry, it's should not have Bug label…

**Comment by jjsquady** [comment]
Change the `asset_url` option in livewire config. By default its `null` and generates "/livewire/livewire.js..."

Changing this option to `asset_url = 'http://myurl.com/application'` the URL will become `http://myurl.com/application/livewire/livewire.js...`

**Comment by nuernbergerA** [comment]
@mityukov just to make it more clear

1. `php artisan vendor:publish --tag=livewire:config`
2. open `config/livewire.php`
3. replace `'asset_url'  => null,` with `'asset_url'  => 'http://myurl.com/application',`

If you have more questions, feel free to [open a thread](https://github.com/livewire/livewire/discussions/new).
