### ISSUE TITLE
Livewire with Feather Icons

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#1083]
### Description
I am using [Feather Icons](https://feathericons.com/) together with Livewire. To use Feather Icons, I do:

```javascript
#app.js
//Feather Icons
const feather = require('feather-icons');
feather.replace()
```

```html
<!-- Blade view -->
 <i data-feather="user"></i>
```

What the above does is it replaces the icons `<i data-feather...></i>` with the `<svg...` tag. This works fine on the initial page load. 

However, when changing an attribute, it reloads the page, but the `feather.replace()` is not triggered again. 

See the GIF below:

![Skærmoptagelse 2020-06-09 kl  11 24 09](https://user-images.githubusercontent.com/7851696/84130817-04029e80-aa44-11ea-9e4e-10f42efe1c85.gif)

### Steps to reproduce
I have a standard Livewire component with one property `$type`, that gets updated onclick using `wire:model='type'`

When the component refreshes, it reverts the `<svg..` back to `<i data-feather..`

**Context**
- Livewire version: 1.1
- Laravel version: 7
- Browser: Chrome

**Comment by oliverbj** [comment]
I see that I can use `wire:ignore`:

```html
<span wire:ignore><i data-feather="user"></i></span>
```

**Comment by nuernbergerA** [comment]
In addition, you should consider using SVG's instead of letting a js-lib replace them all time

I highly recommend [Dries Package](https://github.com/driesvints/blade-icons)

**Comment by oliverbj** [comment]
@nuernbergerA Following your advice, I decided to use SVG's instead of letting them be replaced by a js-lib. I have created a simple blade component called `Icon`:

```php
class Icon extends Component
{
    public $icon;
    public $viewBox;
    public $fill;
    public $strokeWidth;
    public $id;
    public $class;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(
        $icon = null,
        $class = null
    )
    {
        $this->icon = $icon;
        $this->class = $class ?? '';
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return <<<'blade'
        <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="1rem"
                height="1rem"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
          
                {{ $attributes->merge(['class' => "inline-block w-4 h-4 feather feather-$icon $class"]) }}
                >
              <use xlink:href="/images/feather-sprite.svg#{{ $icon }}"/>
        </svg>
    blade;
    }
}
```

But it still doesn't work with Livewire. Even using `wire:ignore` it doesn't work:

```
<x-icon icon="check-cirlce"></x-icon>
```

See the small gif:

1. The icons that are present on the first initialization works. But if I dynamically check a property, and shows and icon if it changes, it will not be shown:

![Skærmoptagelse 2020-06-12 kl  12 07 58](https://user-images.githubusercontent.com/7851696/84492079-df0d6600-aca5-11ea-93c0-826ffa9e0bea.gif)

The code in question:

```
@if($file)
    <div class="bg-green-100 p-2 px-3 rounded my-2">
        <div wire:ignore>
            <x-icon icon="check-circle"></x-icon>
        </div>
    </div>
@endif
```

So once `$file` is set to `true`, it will not show the icon. However, if I remove the `@if($file)...` the icon is there. But I am only interested in showing the file, if the condition is true.

**Comment by nuernbergerA** [comment]
Don't use svg sprite. just use the entire svg directly.

**Comment by oliverbj** [comment]
Ah, that makes sense! Feathericons is not available in Dries' package, but I have created a PR for it [here](https://github.com/driesvints/blade-icons/pull/11). 😃

**Comment by nuernbergerA** [comment]
@oliverbj https://github.com/brunocfalcao/blade-feather-icons

**Comment by kevin4dhd** [comment]
How did you manage to fix it? I bought the vuexy template and it is bringing me this problem, add wire: ignore and it solved, but I don't know if that is the correct way to do it ...

**Comment by kevin4dhd** [comment]
![image](https://user-images.githubusercontent.com/22886367/120923656-5bf2d600-c695-11eb-8c90-a4788a7253a2.png)

As I expected, add the delete event and this problem is solved, but another appears

![image](https://user-images.githubusercontent.com/22886367/120923692-73ca5a00-c695-11eb-926e-275cb1fab38e.png)

when I remove wire:ignore it works correctly but the icon problem returns

**Comment by kevin4dhd** [comment]
![image](https://user-images.githubusercontent.com/22886367/120923819-28fd1200-c696-11eb-912c-e6e25602740a.png)

I solved it by putting inside a div, I hope there are no more errors

**Comment by kevin4dhd** [comment]
Now there is another error, if on the first page there are 8 elements, and you go to the last one that has 4, when you return to another page where there are 8 again, an error will appear

PAGE 1:
![image](https://user-images.githubusercontent.com/22886367/120923885-898c4f00-c696-11eb-84d7-c422a30145a1.png)

LAST PAGE:
![image](https://user-images.githubusercontent.com/22886367/120923891-91e48a00-c696-11eb-90ff-01f0c26eab3f.png)

RETURN PAGE 1:
![Uploading image.png…]()

**Comment by kevin4dhd** [comment]
This time if I no longer know what to do to fix it, if someone had an idea it would be of great help

**Comment by kevin4dhd** [comment]
I fixed it using https://github.com/brunocfalcao/blade-feather-icons, but now the vuexy template is not adapted to the css that is already designed, I suppose I have to fix it manually :/

in case someone wants the solution
![image](https://user-images.githubusercontent.com/22886367/120924378-218b3800-c699-11eb-960a-1fbd4822274d.png)
