### ISSUE TITLE
updated() doesn't run after an iPhone has filled an input field with a code detected in an SMS

### ISSUE THREAD

**Issue by alewolf** [livewire/livewire#1085]
### Description

I am doing a mobile phone number verification using Nexmo. 

After sending out the verification code to the mobile phone, the iPhone detects the verification code and offers me to fill in the input field for the verification code. 

![image](https://user-images.githubusercontent.com/7146794/84262605-2bc63500-ab1e-11ea-93d7-80a2626f23bc.png)

In the Livewire component class I am using the updated() function to check if the field has been filled with four numbers, and if it has, check Nexmo if the verification code matches. 

But, that only works when I type in the numbers manually. 

When I use the autofill function on the iPhone by clicking on the code (see image above), the code only gets copied, but nothing more happens. The updated() function doesn't run. 

![image](https://user-images.githubusercontent.com/7146794/84262648-3da7d800-ab1e-11ea-9c77-fe6052daf528.png)

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.14.1
- Browser: Chrome

**Comment by alewolf** [comment]
Using Safari's debug environment for the iPhone with `monitorEvents` (https://briangrinstead.com/blog/chrome-developer-tools-monitorevents/) I was able to find out that some events **are** being emitted when using the automatic code input. It's only that `wire:model` is not listening to those I guess. 

![image](https://user-images.githubusercontent.com/7146794/84343831-86f13980-aba9-11ea-8c4b-e615e81a1a1a.png)

**Comment by alewolf** [comment]
There is one more symptom when using the iPhone autofill. 

When trying to autofill an email address into a Livewire input field, the email address gets copied but then immediately deleted from the input again. 

Interestingly, if it is just an autofilled four digit number like in the initial bug report above, it will not be deleted (but also not processed by `updated()`)

(The email address you see in the input field in the image below is just the placeholder which reappears after the autofilled email address got automatically deleted)

![image](https://user-images.githubusercontent.com/7146794/84349813-67add880-abb8-11ea-8fdb-af0373c39060.png)

**Comment by nuernbergerA** [comment]
if change is triggered you can user wire:model.lazy

**Comment by alewolf** [comment]
@nuernbergerA Thanks for the suggestion. But no luck. It doesn't work in both cases. 

Case one with the security code still nothing happens. 
The reason is probably because wire:model.lazy requires a user interaction. 

Case two with the registration email also same behaviour. The email gets still automatically deleted when I use autofill.

**Comment by nuernbergerA** [comment]
I guess it's because they are all CustomEvents and we have some 'hack' for IE11 that maybe interferes with it.

**Comment by alewolf** [comment]
@nuernbergerA Are you actively working on Livewire? If so, can I get you more information to pinpoint the issue?

If you know the Laravel source file where this is handled, please let me know. I'd be happy to try to figure it out myself.

**Comment by nuernbergerA** [comment]
@lancepioch, @DanHarrin and I just help @calebporzio out with issues and other stuff.

I think the code you can look into is [here](https://github.com/livewire/livewire/blob/2799f093d6d5d1faeabffafef490f096b60d389a/js/node_initializer.js#L63)

I already pointed Caleb to some other issues with autofill, so there will be a solution soon (at least I hope so)

**Comment by nuernbergerA** [comment]
If made a little event debug page that not actually covers your case but look at the source maybe it can help you too for debugging your problem

https://nuernbergera.github.io/debug-events/
**Be aware: Password will be shown in cleartext**

**Comment by calebporzio** [comment]
Related to #1081

**Comment by calebporzio** [comment]
This has been fixed in the latest version of Livewire (v2.2.8)
