### ISSUE TITLE
Data Lost (Dropdown) Data binding Select 

### ISSUE THREAD

**Issue by ChrisSantiago82** [livewire/livewire#1092]
### Description
I have a very interesting problem.
I have a couple of dropdowns (Selects) and they are all binded to their own variable (wire:model="variable1")

Sometimes I'm loosing the value of that variable if another drop down changes. The selection in HTML is still there but in Laravel that variable then has null.
If I just echo that string to the blade {{ $variable1 }} then it works without problems. But if the value is only in the dropdown it's getting lost somewhere. That means the solution is to show the value of the variable. But that shouldn't be necessary and it shouldn't make a difference. But it does.
Does anybody has the same issue?

### Steps to reproduce

**Context**
- Livewire version: 1.1.0
- Laravel version: 6.14
- Browser: It happens to all browsers

**Comment by ChrisSantiago82** [comment]
I have updated now to version 1.20 and it seems to work. I'm going to close this.

**Comment by Dimonka2** [comment]
Actually this bug still exists. Basically selects are loosing the value if 1st element was select by suer, otherwise they seems to work.

**Comment by ChrisSantiago82** [comment]
I have reopened the issue then

**Comment by calebporzio** [comment]
This issue is fixed and will be in the next release. Thank you.

**Comment by ChrisSantiago82** [comment]
Thank you very much for the good work.
