### ISSUE TITLE
Property casting to collection - Call to a member function toArray()

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#1093]
### Description
I am trying to cast an array on my Livewire component to a collection, but when loading the page containing the component, below error is thrown:

> Call to a member function toArray() on array

The error is in the following file:
> vendor/livewire/livewire/src/DataCaster.php at line 94:
![image](https://user-images.githubusercontent.com/7851696/84434249-f578da80-ac2f-11ea-9913-5991074a71de.png)

### Steps to reproduce
1. Create a Livewire component, with the property you wish to cast.:

```php
namespace App\Http\Livewire\Containers;

use Livewire\WithFileUploads;

class Create extends Component
{
    use WithFileUploads;

    /**
     * @var Collection
     */
    public $data = [];

    protected $casts = [
        'data' => 'collection',
    ];
}
```

Shouldn't the collection caster look like this in the `uncast` method? 
```php
    public function uncast($value)
    {
        return $value->all();
    }
```
**Context**
- Livewire version: dev-master
- Laravel version: 7.0
- Browser: Chrome

**Comment by nuernbergerA** [comment]
Hey Oliver,

`toArray()` is fine, it's a more robust variant.

```php
public function toArray()
{
    return $this->map(function ($value) {
        return $value instanceof Arrayable ? $value->toArray() : $value;
    })->all();
}
```

The `$cast` is used to convert `component` data between `PHP` and `JS`.

1. PHP Initializes the component with `$data = [];`
2. No casting happens because its still PHP and not JS -> PHP
3. $data is still an array
4. Conversion from PHP to JS happens and tries to call `toArray()`on an `array`

So long story short:
```php
public $data;

protected $casts = [
    'data' => 'collection',
];

public function mount()
{
    $this->data = collect();
}
```

**Comment by oliverbj** [comment]
@nuernbergerA Thank you for a very detailed answer. I definitely learned something new today! 

In the [documentation](https://laravel-livewire.com/docs/properties#casting-properties), would it make sense to include that the property should be mounted as a collection?

**Comment by nuernbergerA** [comment]
Feel free to submit a PR to the [docs](https://github.com/livewire/docs/pulls)

**Comment by SanderMuller** [comment]
Also didn't understand that no casting happens during mount, while the example in the docs make it look like it does. Docs could indeed use an update.

**Comment by calebporzio** [comment]
Thanks for the help @nuernbergerA, @SanderMuller please submit a PR to the documentation to make things more clear. Thank you.

**Comment by SanderMuller** [comment]
I see that there's an open PR (that https://github.com/livewire/docs/pull/172) already makes things more clear.
