### ISSUE TITLE
Can't send string variables with emit event from blade.php file

### ISSUE THREAD

**Issue by sir-radar** [livewire/livewire#1094]
### Description
Emit event throws an error when a string variable is passed to it from a blade.php file
### Steps to reproduce
Try emitting an even from a blade.php and pass a string variable

**Context**
- Livewire version: [e.g. 1.1.0]
- Laravel version: [e.g. 7.0.0]
- Browser: [e.g. Chrome, Safari]

**Comment by nuernbergerA** [comment]
Hey @sir-radar, could you please provide some actual code to make it easier for us to help you?

**Comment by sir-radar** [comment]
Given a child component that emits an event with a string payload **ticket.blade.php**

```
<div class="w-1/2 p-12 bg-gray-200 relative">
        <textarea wire:model.debounce.500="question" class="p-4 w-full h-1/2 max-h-full" name="" id="" placeholder="Write your question"></textarea>
        <div class="flex justify-center mt-10">

            <button wire:click="$emit('submit', {{ $question }})" class="p-2 rounded bg-blue-500 text-white">Submit</button>
        </div>
    </div>
```

**Ticket.php**

```
class Ticket extends Component
{
    public $question = '';

    public function render()
    {
        return view('livewire.ticket');
    }
}
```

Then a parent component
**home.blade.php**
```
<div>
    <livewire:ticket/>
</div>
```

**Home.php**
```
class Tickets extends Component
 {
    protected $listeners = ['submit' => 'storeTicket'];

    public function storeTicket($question){
       // This fails
        SupportTicket::create(['question'=>$question]);
        session()->flash('ticketMessage', 'Ticket created successfully');
    }
 
    public function render()
    {
        return view('livewire.home', [
            'tickets' => SupportTicket::latest()->get()
        ]);
    }
}
```

This fails when the variable passed is a string but works for an integer. 

<img width="1279" alt="Screenshot 2020-06-12 at 14 04 53" src="https://user-images.githubusercontent.com/32741303/84505541-c9a03800-acb5-11ea-8b22-f6074ddb819f.png">

**Comment by nuernbergerA** [comment]
```php
class Ticket extends Component
{
    public $question = '';

    public function save()
    {
        SupportTicket::create(['question' => $this->question]);
        session()->flash('ticketMessage', 'Ticket created successfully');

        $this->emit('new-ticket-created');
    }

    public function render()
    {
        return view('livewire.ticket');
    }
}

class Tickets extends Component
 {
    protected $listeners = ['new-ticket-created' => '$refresh'];
 
    public function render()
    {
        return view('livewire.home', [
            'tickets' => SupportTicket::latest()->get()
        ]);
    }
}
```

```blade
<div class="w-1/2 p-12 bg-gray-200 relative">
        <textarea wire:model.debounce.500="question" class="p-4 w-full h-1/2 max-h-full" name="" id="" placeholder="Write your question"></textarea>
        <div class="flex justify-center mt-10">

            <button wire:click="save" class="p-2 rounded bg-blue-500 text-white">Submit</button>
        </div>
    </div>
```

**Comment by sir-radar** [comment]
@nuernbergerA  I understand that this would work. The issue is if I try to send a string payload with an emit event.

**Comment by nuernbergerA** [comment]
Well then try
```blade
<div class="w-1/2 p-12 bg-gray-200 relative">
        <textarea wire:model.debounce.500="question" class="p-4 w-full h-1/2 max-h-full" name="" id="" placeholder="Write your question"></textarea>
        <div class="flex justify-center mt-10">

            <button wire:click="$emit('submit', '{{ $question }}')" class="p-2 rounded bg-blue-500 text-white">Submit</button>
        </div>
    </div>
```

**Comment by sir-radar** [comment]
> Well then try
> 
> ```
> <div class="w-1/2 p-12 bg-gray-200 relative">
>         <textarea wire:model.debounce.500="question" class="p-4 w-full h-1/2 max-h-full" name="" id="" placeholder="Write your question"></textarea>
>         <div class="flex justify-center mt-10">
> 
>             <button wire:click="$emit('submit', '{{ $question }}')" class="p-2 rounded bg-blue-500 text-white">Submit</button>
>         </div>
>     </div>
> ```

This doesn't work either. It throws an error in the console.

**Comment by nuernbergerA** [comment]
whats the error?

**Comment by sir-radar** [comment]
> whats the error?

**level** is the text typed into the textarea

<img width="1279" alt="Screenshot 2020-06-12 at 15 40 34" src="https://user-images.githubusercontent.com/32741303/84514612-35d56880-acc3-11ea-9ba7-98376261f584.png">

**Comment by nuernbergerA** [comment]
Ah sorry, I didn't notice you are using a textarea.

You have to encode the `$question` like so
```blade
<div class="w-1/2 p-12 bg-gray-200 relative">
    <textarea wire:model.debounce.500="question" class="p-4 w-full h-1/2 max-h-full" placeholder="Write your question"></textarea>
    <div class="flex justify-center mt-10">
        <button wire:click="$emit('submit', '{{ (json_encode$question) }}')" class="p-2 rounded bg-blue-500 text-white">Submit</button>
    </div>
</div>
```
You can also drop `id`and `name`.

I hope this works for you.
Cheers

**Comment by sir-radar** [comment]
@nuernbergerA Thanks. It works now.
