### ISSUE TITLE
redirect with flash data throws an exception

### ISSUE THREAD

**Issue by SanderMuller** [livewire/livewire#1103]
### Description
`return redirect()->route('home')->with('alert-success', 'Redirect worked!');` throws a `BadMethodCallException`

### Steps to reproduce
From a LiveWire component:
`return redirect()->route('home')->with('alert-success', 'Redirect worked!');`

**Context**
- Livewire version: v1.1.0
- Laravel version: 7.15.0

It would be great if the redirect could support flashing data through the fluent with method, just like regular Laravel redirects!

P.s. Livewire is amazing!

**Comment by Braunson** [comment]
This is related to #841

**Comment by stancl** [comment]
It's a duplicate of #841. I think this should be closed.
