### ISSUE TITLE
Can't use wire:model in nested component.

### ISSUE THREAD

**Issue by vittorioe** [livewire/livewire#1105]
### Description
I often used nested components, maybe I'm not able to find my mistake or it's a bug. Let us see. I have 2 Components: CreateRegistrationContact and RegisterDomain. `RegisterDomain` is mounted as a route with `Route::livewire()`. Now I put a `<livewire:create-registration-contact />` to the RegisterDomains blade. If I now bind a value to for example I have at my `CreateRegistraitonContact.php` the property `public $first_name;` and I use it in the `create-registration-contact.blade.php` like this:  `<input wire:model="first_name" class="form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" />` It throws me following error, while updating the field:
``` 
Livewire\Exceptions\PublicPropertyNotFoundException
Unable to set component data. Public property [$first_name] not found on component: [register-domain]
```

But I never used the model or the property in `register-domain.blade.php` 
### Steps to reproduce
See description
**Context**
- Livewire version: v1.2.0
- Laravel version: v7.15.0
- Browser: Chrome latest

**Comment by vittorioe** [comment]
It took a bit to resolve that. This is because I used `<form>` as the surrounding tag instead of a div. Maybe a thing you want to solve. If someone else has this problem also: Just put a div around the component's blade layout.

**Comment by dubcanada** [comment]
What it just a single

`<form>
    ....
</form>`

and you switch it to be

`<div>
    <form>
        ....
    </form>
</div>`

?

**Comment by vittorioe** [comment]
Yeah right. But for example in tables you shouldn't use a wrapping div. If you do so, it crashes with the same error again.

**Comment by calebporzio** [comment]
Wow, this is an interesting bug.

@vittorioe can you please paste in exact, simplified code to reproduce this bug please.

**Comment by iAmKevinMcKee** [comment]
I'm getting a similar bug as well. I've got a nested component (and it's in an html table, not sure if that matters), but I put a wire:click in the nested component and I'm getting an error that the method doesn't exist (because it's looking for the method on the parent component, not the child).

When I get more time I will see if I can reproduce in a new project and paste the code.

**Comment by iAmKevinMcKee** [comment]
Okay, so I figured out why the html table is an issue. I had an outer `div` instead of `tr` and this must have broken some HTML rules and it took the livewire wrapping div out of the table entirely.

**Comment by jeffwhansen** [comment]
I have had the same issue - wrapping with outer div solved it for me.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by adityar15** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by adityar15** [comment]
I am getting the same error for nested components. I m using the wire model on the child component but seems like it is looking for variables in the parent component. I have wrapped it in the outer div but still, it does not solve the problem :(

**Comment by cbka** [comment]
> Yeah right. But for example in tables you shouldn't use a wrapping div. If you do so, it crashes with the same error again.

that is FYI still the case... maybe write this down in the docs under https://laravel-livewire.com/docs/2.x/nesting-components
