### ISSUE TITLE
zip file fails image validation and crashes with temporaryUrl()

### ISSUE THREAD

**Issue by mblarsen** [livewire/livewire#1106]
### Description

When you upload a file that fails validation the file prop is set and you can call `temporaryUrl()` on it which fails.

E.g. say my validation is `'image|size:1024'` then uploading a 20kb zip-file will not fail on `image` validation but because of `temporaryUrl()` isn't supported. 

```
ErrorException: This driver does not support creating temporary URLs. (View: /var/www/resources/views/livewire/avatar.blade.php) in file /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 556
```
Usage

```blade
            @if ($photo) <!-- this is the public file prop on the Livewire component -->
                <img src="{{ $photo->temporaryUrl() }}" alt="{{ $avatarable->initials }}">
            @elseif ($avatarable->avatar)
                <img src="{{ $avatarable->avatar->url }}" alt="{{ $avatarable->initials }}">
            @else
                <span class="flex items-center justify-center w-full h-full text-3xl font-bold text-white bg-primary">
                    <span class="group-hover:opacity-0">{{ $avatarable->initials }}</span>
                </span>
            @endif
```

If by contract I upload a zip-file larger than 1024 then I get a proper validation error as expected.

It seems like it is the image validation that fails, but it could also be that the prop isn't unset in case of validation.

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 7.15.0]
- Browser: any

**Comment by roitto** [comment]
I get similar error if i try to upload anything else than an image. Is there an way to remove the unwanted files before trying to render them?

**Comment by calebporzio** [comment]
yeah, I think this is a userland issue. You can consitionally render ->temporaryUrl() if a file type is not renderable. You can also expand on what temporaryUrl supports in the config.

Closing thanks!

**Comment by thumbtech** [comment]
I'm here with same issue ... not sure I understand resolution, though.

If I am validating file type and an invalid type is not in preview_mimes, I get the error described. If I include the invalid type in preview_mimes, it works. But it is not practical to include every possible invalid type in preview_mimes, right?

**Comment by robertnicjoo** [comment]
Same issue here having issue uploading `zip` `doc` `docx` `xls` `xsv` etc.



> 
> 
> yeah, I think this is a userland issue. You can consitionally render ->temporaryUrl() if a file type is not renderable. You can also expand on what temporaryUrl supports in the config.
> 
> Closing thanks!

Please provide workaround sample if possible.

**Comment by MelchiorKokernoot** [comment]
also experiencing this problem with pdf files. 
Trying to validate for mimes:jpeg,bmp,png'

**Comment by MelchiorKokernoot** [comment]
I know this might not be the best code, but this helped me fix the problem without having to add every mime type to the preview_mimes array.
I placed this in the blade file. Also tried binding to the photoUpdated function which should be called after update, but couldn't get that to work. Maybe this might help someone.

` @if ($photo)
        @php
            try {
               $url = $photo->temporaryUrl();
               $photoStatus = true;
            }catch (RuntimeException $exception){
                $this->photoStatus =  false;
            }
        @endphp
        @if($photoStatus)
            <img src="{{ $url }}">
        @else
            Something went wrong while uploading the file.
        @endif
    @endif
`

**Comment by reniar1** [comment]
I am getting the same error even with jpeg

ErrorException : This driver does not support creating temporary URLs. (View: /Users/reniar/code/LivewireTest/resources/views/livewire/profile.blade.php)

**Comment by mblarsen** [comment]
As I see it. If the validation fails the file property shouldn't be set to a file as if it didn't exist. Or at least It seems like something that doesn't belong in user-land.

When would you want to keep a file that fails validation, besides some form of clean up on the server-side of things?

**Comment by ryanscherler** [comment]
I did this as a fix for the temporary url driver issue:

```php
public $avatar;

//...

public function updatedAvatar()
{
    $extension = pathinfo($this->avatar->getFilename(), PATHINFO_EXTENSION);
    if (!in_array($extension, ['png', 'jpeg', 'bmp', 'gif'])) {
        $this->reset('avatar');
    }

    $this->validate([
        'avatar' => 'mimes:png,jpeg,bmp,gif|max:512', // .5MB Max
    ]);
}
```

**Comment by komen205** [comment]
Same error here when trying to add .txt files

**Comment by mvladimir7** [comment]
For someone who is using real-time validation with several fields, solution might be like this
```php
public $avatar;

protected $rules = [
    'avatar' => 'image|max:1024',
];

//...

/**
 * Real-time validation.
 *
 * @param string $propertyName
 * @throws \Illuminate\Validation\ValidationException
 */
public function updated($propertyName)
{
    try {
        $this->validateOnly($propertyName);
    } catch (ValidationException $e) {
        if ($propertyName == 'avatar') {
            $this->reset($propertyName);
        }

        throw $e;
    }
}
```

Regarding to the @ryanscherler workaround, can be used laravel Validator and code might look like this

```php
use Illuminate\Support\Facades\Validator;

//...

public $avatar;

protected $rules = [
    'avatar' => 'image|max:1024',
];

//...

/**
 * @param \Livewire\TemporaryUploadedFile $value
 */
public function updatedAvatar($value)
{
    $validator = Validator::make(
        ['avatar' => $this->avatar],
        ['avatar' => $this->rules['avatar']],
    );

    if ($validator->fails()) {
        $this->reset('avatar');
        $this->setErrorBag($validator->getMessageBag());
    }
}
```

**Comment by luisangeldev** [comment]
> For someone who is using real-time validation with several fields, solution might be like this
> 
> ```
> public $avatar;
> 
> protected $rules = [
>     'avatar' => 'image|max:1024',
> ];
> 
> //...
> 
> /**
>  * Real-time validation.
>  *
>  * @param string $propertyName
>  * @throws \Illuminate\Validation\ValidationException
>  */
> public function updated($propertyName)
> {
>     try {
>         $this->validateOnly($propertyName);
>     } catch (ValidationException $e) {
>         if ($propertyName == 'avatar') {
>             $this->reset($propertyName);
>         }
> 
>         throw $e;
>     }
> }
> ```
> 
> Regarding to the @ryanscherler workaround, can be used laravel Validator and code might look like this
> 
> ```
> use Illuminate\Support\Facades\Validator;
> 
> //...
> 
> public $avatar;
> 
> protected $rules = [
>     'avatar' => 'image|max:1024',
> ];
> 
> //...
> 
> /**
>  * @param \Livewire\TemporaryUploadedFile $value
>  */
> public function updatedAvatar($value)
> {
>     $validator = Validator::make(
>         ['avatar' => $this->avatar],
>         ['avatar' => $this->rules['avatar']],
>     );
> 
>     if ($validator->fails()) {
>         $this->reset('avatar');
>         $this->setErrorBag($validator->getMessageBag());
>     }
> }
> ```

This solution works for me, thanks :)

**Comment by taher267** [comment]
> I know this might not be the best code, but this helped me fix the problem without having to add every mime type to the preview_mimes array.
> I placed this in the blade file. Also tried binding to the photoUpdated function which should be called after update, but couldn't get that to work. Maybe this might help someone.
> 
> ```
>  @if ($photo)
>         @php
>             try {
>                $url = $photo->temporaryUrl();
>                $photoStatus = true;
>             }catch (RuntimeException $exception){
>                 $this->photoStatus =  false;
>             }
>         @endphp
>         @if($photoStatus)
>             <img src="{{ $url }}">
>         @else
>             Something went wrong while uploading the file.
>         @endif
>     @endif
> ```

it say that Undefined variable $photoStatus, how can it solve it https://prnt.sc/1ipjxkb

**Comment by lundjon** [comment]
> yeah, I think this is a userland issue. You can consitionally render ->temporaryUrl() if a file type is not renderable. You can also expand on what temporaryUrl supports in the config.
> 
> Closing thanks!

For a userland issue this seems to effect a lot of users....

Mine broke when livewire updated. A clear fix would be greatly appreciated.

**Comment by lundjon** [comment]
> > For someone who is using real-time validation with several fields, solution might be like this
> > ```
> > public $avatar;
> > 
> > protected $rules = [
> >     'avatar' => 'image|max:1024',
> > ];
> > 
> > //...
> > 
> > /**
> >  * Real-time validation.
> >  *
> >  * @param string $propertyName
> >  * @throws \Illuminate\Validation\ValidationException
> >  */
> > public function updated($propertyName)
> > {
> >     try {
> >         $this->validateOnly($propertyName);
> >     } catch (ValidationException $e) {
> >         if ($propertyName == 'avatar') {
> >             $this->reset($propertyName);
> >         }
> > 
> >         throw $e;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Regarding to the @ryanscherler workaround, can be used laravel Validator and code might look like this
> > ```
> > use Illuminate\Support\Facades\Validator;
> > 
> > //...
> > 
> > public $avatar;
> > 
> > protected $rules = [
> >     'avatar' => 'image|max:1024',
> > ];
> > 
> > //...
> > 
> > /**
> >  * @param \Livewire\TemporaryUploadedFile $value
> >  */
> > public function updatedAvatar($value)
> > {
> >     $validator = Validator::make(
> >         ['avatar' => $this->avatar],
> >         ['avatar' => $this->rules['avatar']],
> >     );
> > 
> >     if ($validator->fails()) {
> >         $this->reset('avatar');
> >         $this->setErrorBag($validator->getMessageBag());
> >     }
> > }
> > ```
> 
> This solution works for me, thanks :)

This works only for the profile avatar and not for any other images uploaded.

**Comment by mattgreenfield** [comment]
I'm a little confused by this as I'd expect the validation to run before the file is stored.
@calebporzio is the 'fix' to update the documentation here? https://laravel-livewire.com/docs/2.x/file-uploads

**Comment by adddz** [comment]
I've just encountered a similar issue as @mattgreenfield.

Currently, Livewire stores the file before doing validation. In this way, the file is first uploaded and then validated. It would be great if Livewire can at least check file format and file size *before* storing it in the temporary folder.

**Comment by joshhanley** [comment]
@adddz temporary files also have validation, have a look at the global validation in the docs https://laravel-livewire.com/docs/2.x/file-uploads#global-validation

Hope this helps!

**Comment by adddz** [comment]
> @adddz temporary files also have validation, have a look at the global validation in the docs https://laravel-livewire.com/docs/2.x/file-uploads#global-validation
> 
> Hope this helps!

Hi Josh thanks for pointing that out. I've already set those but Livewire still uploads the file first, then checks the validation rules. Is this how it's supposed to act? I am expecting the rules to be checked before the upload of the temporary files, in this way if I'm uploading a 15MB file or an invalid file format, I don't have to wait for the upload to finish before seeing the error. Makes sense?

Happy Holidays!

**Comment by joshhanley** [comment]
@adddz hmm I think it would have to upload the file first before it can check its size/type/etc but I'm not 100% on that. 

Do you know how Laravel handles that, does it upload first then validate? As Livewire should act the same as Laravel does in that instance.

**Comment by adddz** [comment]
> @adddz hmm I think it would have to upload the file first before it can check its size/type/etc but I'm not 100% on that.
> 
> Do you know how Laravel handles that, does it upload first then validate? As Livewire should act the same as Laravel does in that instance.

I am not sure but do you agree with me that it doesn't make sense for the file to be uploaded just to check the size/type? Maybe there's a way that Livewire can check size/type from the browser? No idea to be honest.

**Comment by joshhanley** [comment]
@adddz I'd agree if that's the way Laravel works. But if Laravel uploads before checking validation, then I'd say it's setup the way it should be. My thoughts are, because Livewire makes use of Laravel's validator, we need to make sure it runs in the same way as Laravel so validation is properly supported.

I'm not sure how we could get Livewire to check that from the browser without some form of custom way of telling the frontend what the file type and size should be (aka not in a Laravel validation rule).

How would you imagine it working?

**Comment by adddz** [comment]
@joshhanley to be honest I don't know exactly the ins and outs of how Laravel validation works.

As an "end-user", I expect that Livewire checks if the file I'm trying to upload is bigger and/or of an allowed file type before uploading it to the temporary folder. Are you with me on this?

**Comment by joshhanley** [comment]
@adddz yep makes sense! But as we use Laravel's validation system, the temp file has to be uploaded first for the validation to run against it, so not sure what else we can do about that.

**Comment by ameen121** [comment]
i have issue how we can handle first validation check than upload

**Comment by Sirloko** [comment]
@adddz 's solution worked for me

**Comment by adddz** [comment]
> @adddz 's solution worked for me

I actually didn't have a solution for this. What did you use to validate the file size/type before upload?

**Comment by Sirloko** [comment]
> > @adddz 's solution worked for me
> 
> I actually didn't have a solution for this. What did you use to validate the file size/type before upload?

I edited the global validation provided by livewire, and it worked for me

**Comment by SteelJokers** [comment]
This is quite an old issue that was closed, but I've been wrestling with the problem for a few days - so it is still a bit of a pitfall in late 2024.  For anyone else stumbling on this thread there are some great ideas in here, but I didn't see the following mentioned:

Fully set up your file input as a picket fence to help prevent users from selecting an incorrect or unsupported file type using the **accept** property on your input element:

```blade
<input type="file" id="photo" wire:model="photo" name="photo" accept=".jpg, .jpeg, .png" />
``` 
I've referred to this as a picket fence because the mdn web docs provides the following details on the accept attribute:

"_The accept attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types._"

Next, we can look at triggering something more akin to pre-validation on the selected file using a simple javascript method like:
```javascript
<script>
        function validateFile() {
            const input = document.getElementById('photo-upload');
            const file = input.files[0]; // Get the first selected file
            const maxSizeInMB = 1; // Set the maximum file size in MB
            const allowedTypes = ['image/jpeg', 'image/png']; // Define allowed file types

            const errorElement = document.getElementById('file-error');
            errorElement.textContent = ''; // Reset the error message

            if (file) {
                // Check the file type
                if (!allowedTypes.includes(file.type)) {
                    errorElement.textContent = 'Please upload a JPEG or PNG image.';
                    input.value = ''; // Clear the input
                    return;
                }

                // Check the file size (convert bytes to MB)
                const fileSizeInMB = file.size / (1024 * 1024);
                if (fileSizeInMB > maxSizeInMB) {
                    errorElement.textContent = `File size exceeds ${maxSizeInMB} MB. Please upload a smaller file.`;
                    input.value = ''; // Clear the input
                    return;
                }

                // Add any additional validations you'd like to check here
            }
        }
    </script>
``` 

If you happen to have a preview of the photo on the page, you can use some simple blade directives to handle the type of image you're presenting.  This example will show one of three images in your preview pane.
```blade
@if ($photo instanceof \Livewire\Features\SupportFileUploads\TemporaryUploadedFile)
    <img
        src="{{ $photo->temporaryUrl() }}"
        alt="Profile photo preview"
        class="h-24 w-24 flex-none border rounded-lg bg-white dark:bg-zinc-700 object-cover"
    />
@else
    <img
        src="{{ $profile_photo ? Storage::url($profile_photo) : asset('img/default-avatar.png') }}"
        alt="Profile photo"
        class="h-24 w-24 flex-none border rounded-lg bg-white dark:bg-zinc-700 object-cover"
    />
@endif
```
This checks to see if ```$photo``` is an instance of a ```TemporaryUploadedFile``` and then shows the image as a preview.

The else statement will show one of two photos.  It checks a property on the livewire component to identify if a profile photo already exists for the user.  If it does, it pulls the file from storage as a url and displays it.  If a profile photo doesn't exist for the user, then it shows a default avatar.

I hope this method helps anyone else who may stumble in here.  I'm not saying this is the right way to do it, but this is what worked for me.

**Comment by aabdosai** [comment]
On the input element do this:
File 1: <input type="file" name="file1" onchange="ValidateSingleInput(this);" /><br> />

and add this javascript below the blade file:


var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png"];    
function ValidateSingleInput(oInput) {
    if (oInput.type == "file") {
        var sFileName = oInput.value;
         if (sFileName.length > 0) {
            var blnValid = false;
            for (var j = 0; j < _validFileExtensions.length; j++) {
                var sCurExtension = _validFileExtensions[j];
                if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                    blnValid = true;
                    break;
                }
            }
             
            if (!blnValid) {
                alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                oInput.value = "";
                return false;
            }
        }
    }
    return true;
}

This should solve your problem

**Comment by aabdosai** [comment]
On the input element add this event onchange="ValidateSingleInput(this);" 

and on the blade page add this java script:

var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png"];    
function ValidateSingleInput(oInput) {
    if (oInput.type == "file") {
        var sFileName = oInput.value;
         if (sFileName.length > 0) {
            var blnValid = false;
            for (var j = 0; j < _validFileExtensions.length; j++) {
                var sCurExtension = _validFileExtensions[j];
                if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                    blnValid = true;
                    break;
                }
            }             
            if (!blnValid) {
                alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                oInput.value = "";
                return false;
            }
        }
    }
    return true;
}

I believe this should solve your problem

**Comment by aabdosai** [comment]
On the input onchange event :

onchange="ValidateSingleInput(this);" 



Add this javascript at the end of the blade page .
<script>
    var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png"];
    function ValidateSingleInput(oInput) {
        if (oInput.type == "file") {
            var sFileName = oInput.value;
            if (sFileName.length > 0) {
                var blnValid = false;
                for (var j = 0; j < _validFileExtensions.length; j++) {
                    var sCurExtension = _validFileExtensions[j];
                    if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                        blnValid = true;
                        break;
                    }
                }

                if (!blnValid) {
                    alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                    oInput.value = "";
                    return false;
                }
            }
        }
        return true;
}
</script>


This should solve your problem.

**Comment by aabdosai** [comment]
On the input onchange event :

onchange="ValidateSingleInput(this);"

Add this javascript at the end of the blade page.

	<script>
    var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png"];
    function ValidateSingleInput(oInput) {
        if (oInput.type == "file") {
            var sFileName = oInput.value;
            if (sFileName.length > 0) {
                var blnValid = false;
                for (var j = 0; j < _validFileExtensions.length; j++) {
                    var sCurExtension = _validFileExtensions[j];
                    if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                        blnValid = true;
                        break;
                    }
                }

                if (!blnValid) {
                    alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                     oInput.value = "";
                    return false;
                }
            }
        }
        return true;
}
</script>



This should solve your problem.
