### ISSUE TITLE
.csv files uploads with .txt extension

### ISSUE THREAD

**Issue by HalfBottleOfMind** [livewire/livewire#1107]
### Description

Files with extension .csv uploads as .txt files. I think problem in laravels guessExtension() method.

### Steps to reproduce

Try to upload .csv file. In livewire-tmp folder it will be .txt.

**Context**
- Livewire version: 1.2
- Laravel version: 7.15
- Browser: Chrome v84.0.4147.45

**Comment by calebporzio** [comment]
It looks like this is a problem with Laravel itself. There are simple workarounds described here: https://stackoverflow.com/questions/51569475/how-to-store-csv-file-laravel-5-php

Thanks!

**Comment by nowendwell** [comment]
Using the suggested workaround doesn't work as the extension is already gone by the time it gets to the Livewire component.

If you change the following, you can use getClientOriginalExtension() to get the correct extension.

[TemporaryUploadedFile.php #L128](https://github.com/livewire/livewire/blob/master/src/TemporaryUploadedFile.php#L128)
```php
$extension = '.'.$file->guessExtension();
```
to
```php
$extension = '.'.$file->getClientOriginalExtension();
```

**Comment by bernhardh** [comment]
This ist still an issue. Uploading an csv file leads to a txt file. :(

**Comment by saagoor** [comment]
This issue still remains, not just for .csv file but for .srt, .vtt etc files also.

**Comment by majid-al-saidi** [comment]
I have this issue,

**Comment by NeoLarson** [comment]
Have the same issue in Livewire 3.
