### ISSUE TITLE
Internet Explorer 11 support 

### ISSUE THREAD

**Issue by ChrisSantiago82** [livewire/livewire#1112]
The Internet Explorer support is pretty good. But I' having a problem when I'm working with listeners.
I'm getting a Syntax error in the directive.js file.

I'm not a Javascript expert but I think the Arrow Syntax is not supported by the IE. Could there be another way to write that method that would also work for the ie?

![image](https://user-images.githubusercontent.com/43000085/84784395-3d915780-afb8-11ea-9331-13a48cb252ba.png)

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 6.2.0]
- Browser: [IE11]

**Comment by nuernbergerA** [comment]
Relates to #999
