### ISSUE TITLE
When navigating with Turbolinks, ajax requests will not fire for Livewire components in Vue component.

### ISSUE THREAD

**Issue by seyed-me** [livewire/livewire#1113]
### Description
Livewire components in the Vue component that mounted after `turbolinks:load`  will not fire ajax request after navigating with turbolinks. Only it works when first time that page loaded. (Livewire components outside of Vue component element also work.)

### Steps to reproduce
- Config Turbolinks
- Mount Vue component after `turbolinks:load`
- Put Livewire component somewhere in Vue component.
- Open the page including the livewire component (It will work)
- Navigate between pages
- Back to the page including the livewire component.
- Livewire component will not fire ajax to Laravel.

**Context**
- Livewire version:1.2.0
- Laravel version: 7.16.1
- Browser: Chrome

**Comment by aidan-casey** [comment]
@seyed-me can you post your code? I have seen this issue in the past and I believe it had to do with wrapping the Livewire component in a root element and / or including a wire:init function.

**Comment by calebporzio** [comment]
Turbolinks support has now been moved to a separate repo.

Please re-submit any current issues there: https://github.com/livewire/turbolinks

Thanks!
