### ISSUE TITLE
Returning from a method does not stop rest of the component to execute

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#1117]
### Description
I have a Livewire component, that is calculating the size of an array in order to "walk through the items". If the key is greater than the size of the array, I want to stop, as there is no more items in the array.

### Steps to reproduce
Consider below component:

```php
    public $data;
    public $size;
    public $key = 0;

    public function mount()
    {
        $this->data = ["Some text 1", "Some text 2", "Some text 3"]
        $this->size = count($this->data);
    }

    public function showNextData()
    {
        if ($this->key >= $this->size) {
            return true;
        }

        $this->key += 1;
        $this->text = $this->data[$this->key];

    }

    public function render()
    {
        return view('livewire.my-component, [
            'text' => $this->data[$this->key],
        ]);
    }
```

And then simply a link to trigger it:

```html
<a wire:click="showNextData">Next item In array</a>

The text from the array: {{ $text }}
```

After clicking three times, I get an error:

> Undefined offset: 3

On this specific line:

>  $this->text = $this->data[$this->key];

I am not quite sure why it evens reaches this line, as I return in the `if` statement before.

**Context**
- Livewire version: 1
- Laravel version: 7
- Browser: Chrome

**Comment by acurrieclark** [comment]
At first glance it looks like you won't return at all, as your increment happens after the check?

**Comment by nuernbergerA** [comment]
Hey @oliverbj this is actually not a livewire bug at all.

Let me illustrate what's happening.
```php
public function mount()
{
    $this->data = [
        0 => "Some text 1",
        1 => "Some text 2",
        2 => "Some text 3",
    ];
    $this->size = count($this->data); // equals 3
}

public function showNextData()
{
    // 1st run
    if (0 >= 3) {
        return true;
    }
    $this->key = 1;
    $this->text = $this->data[1]; // "Some text 2"

    // 2nd run
    if (1 >= 3) {
        return true;
    }
    $this->key = 2;
    $this->text = $this->data[2]; // "Some text 3"

    // 3rd run
    if (2 >= 3) {
        return true;
    }
    $this->key = 3;
    $this->text = $this->data[3]; // Undefined offset: 3
}
```
One solution would be ` $this->size = count($this->data) - 1;`

Cheers
