### ISSUE TITLE
Removing the first item from the array of temporary uploaded files results in incorrect serialization

### ISSUE THREAD

**Issue by acurrieclark** [livewire/livewire#1118]
### Description
When using multiple file uploads, I am using a `removeFile($key)` action to allow users to remove specific files from the list of temp files. When `$key` equals `0` this results in the incorrect serialized file data being returned.

### Steps to reproduce

1. Clone and run `git@github.com:acurrieclark/livewire-multiple-fileupload-demo.git`, then visit the root address
2. Upload multiple (at least 4)
3. Click `remove` next to the **last** file on the list
4. check that the `data` response contains the `files` property with a string starting `livewire-files:` (expected behaviour)
5. Click `remove` next to the **first** file on the list.
6. check that the `data` response now contains an list of `{disk: "local"}` objects (not expected)
7. Try to remove another file, and an error will be thrown.

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 7.16.1]
- Browser: Chrome

**Comment by calebporzio** [comment]
Will be fixed in next release.
