### ISSUE TITLE
Table lose state after go back on page

### ISSUE THREAD

**Issue by Algeneralo** [livewire/livewire#1123]
### Description
I have a table with search input that filters table records depend on some attributes, the issue that when I click on back button on the browser, the table is not filtered anymore.
Ex:
Filtered table data:
![image](https://user-images.githubusercontent.com/32073999/85038460-45efbb00-b18f-11ea-89ad-82651522c2a8.png)
After going anywhere, and go back to previous page
![image](https://user-images.githubusercontent.com/32073999/85038538-5b64e500-b18f-11ea-84c5-1f7d4842c49f.png)

**Comment by ninthspace** [comment]
You'll probably need to persist and load the search criteria via Livewire's query string support: https://laravel-livewire.com/docs/properties#query-string

**Comment by calebporzio** [comment]
Thanks for the help @ninthspace  - that is exactly right. Closing this.
