### ISSUE TITLE
File uploader doesn't respect disk root

### ISSUE THREAD

**Issue by stancl** [livewire/livewire#1125]
### Description

The file uploader tells the browser to upload to `/` + the `livewire-tmp/` dir, regardless of what the root disk is.

### Steps to reproduce

Tell Livewire to use the `s3` disk, set `root` in the disk to `/foo`, open dev tools when uploading a file and see that it uses just `/livewire-tmp/` rather than `/foo/livewire-tmp/`.

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 7.0.0]
- Browser: Chrome

**Comment by stancl** [comment]
Also, in parts of my code I use:

```php
Storage::disk('s3')->getAdapter()->setPathPrefix('foo/');
```

If the storage adapter's prefix were respected too (I assume it's initially read from `root` from the FS config & then takes precedence over the config), that would make this even better.

**Comment by DanHarrin** [comment]
Hey @stancl, mind checking out #1152 to see if this solves your issue?
