### ISSUE TITLE
Trigger wire:model programmatically

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#1127]
### Description
I am trying to "trigger" `wire:model` programmatically. Right now I can only get it working by actually clicking the wire:model checkbox.

### Steps to reproduce
I have this public property defined on my Livewire component.:

```php
public $selectedLabels = [];
```

Then in my blade view, I have this:

```html
<input type="checkbox" id="name" value="Oliver" wire:model="selectedLabels"> Name
<script>
    window.onload = () => {
        window.addEventListener("keydown", function (event) {
                if (event.key === "1") {
                    let isChecked = document.getElementById('#name').checked;
                    document.getElementById('#name').checked = !isChecked;
                }      
            }
        );
    }
</script>
```

I then validate the content of `$selectedLabels`, by simply placing this in the blade file: `@json($selectedLabels)`. 

If I click the checkbox, it will successfully add the value `Oliver` to the `$selectedLabels`. However, if I press `1` on the keyboard, thus checking the checkbox programmatically, it will not update the `wire:model`.

**Context**
- Livewire version: 1.2.0
- Laravel version: 7
- Browser: Chrome

**Comment by oliverbj** [comment]
I can work around this "issue" with simply simulating a click on the checkbox:

```javascript
document.getElementById('#name').click();
```

Still wondering if `wire:model` should be programmatically available.

**Comment by mblarsen** [comment]
`wire:model="foo"` is syntactic sugar for listening on an `input` event. 

```js
// Not actual implementation
element.addEventListener('input', (e) => {
  window.livewire.call('$set', 'foo', e.target.value)
})
```

And `wire:model.lazy` is sugar for `change`. 

So you can dispatch an input-event to trigger wire model. E.g. using Alpine.js `$dispatch('input', 'bar')`.

**Comment by calebporzio** [comment]
There is also a `@this.set('property', 'value')` that is basically the way to call `wire:model` programatically

**Comment by jayenne** [comment]
I have a spinner element and I'd like the wire:trigger="loadmore" triggered by javascript rather than an input click.
is this possible? would you have an exmaple please?

my shortcode is..
```
<button id="loadmore" wire:click="loadMore" class="hidden"></button>
<div
	wire:loading
	wire:target="loadMore"
```

and the js is...
```
<script>
            window.onscroll = function(ev) {
                if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
                    document.getElementById('loadmore').click();
                }
            };
</script>
```

FYI: I've tried without a button (as a hidden button just seems pointless) but could get to work...
```
<div
	wire:loading
	wire:target="loadMore"
```

```
 window.onscroll = function(ev) {
                if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
                    Livewire.emit('loadMore');
                }
            };
```

**Comment by imechemi** [comment]
https://laravel-livewire.com/docs/2.x/inline-scripts#accessing-javascript-component-instance

**Comment by Ahrjen** [comment]
> ```js
> livewireComponet
> ```

For anyone interested, in Livewire v3 it's `**$wire**.set('property', 'value')`
