### ISSUE TITLE
Uploads dont work with nested array elements

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#1131]
### Description

**works**
wire:model="asset"

**doesnt work**
wire:model="form.asset"

In the second example the element does not get set to the FILE Object.

**Context**
- Livewire version: [e.g. 1.2.0]
- Laravel version: [e.g. 7.0.0]
- Browser: [e.g. Chrome]

**Comment by merthurturk** [comment]
Related topic in the forum: https://github.com/livewire/livewire/discussions/1102

**Comment by jjjrmy** [comment]
#1222 I think this is the same issue?
Included code to replicate the issue.

**Comment by calebporzio** [comment]
Yeah, this is a known limitation. Sorry, no plans to implement right now.
