### ISSUE TITLE
wire:ignore disable element while validation and it keeps it diabled after render.

### ISSUE THREAD

**Issue by cobraprojects** [livewire/livewire#1135]
### Description
when I use `wire:ignore` with select for example it stays disabled after validation is complete

### Steps to reproduce
```
<form action="" method="post" wire:submit.prevent="save">
    <div>
        <input type="text" wire:model="title" />
    </div>
    <div wire:ignore>
        <select>
            <option>1</option>
            <option>2</option>
        </select>
    </div>
    <button type="submit">Save</button>
</form>
```
in component
```
public function save() {
    $this->validate([
        'title' => 'required',
    ]);
}
```
if I call a save method (`wire:submit.prevent`) with validation (if title is empty) it diabled all form elements and enabled them except the ones inside `wire:ignore` stays disabled

please help

**Context**
- Livewire version: 1.2
- Laravel version: 7.16.1
- Browser:Chrome

**Comment by greenwebsas** [comment]
Got same isue

**Comment by nuernbergerA** [comment]
Hey @cobraprojects and @greenwebsas

this could possibly be fixed by #1166 with the next release.

Please run `composer require livewire/livewire:1.x-dev` and confirm if it's fixed?

Cheers Adrian

**Comment by greenwebsas** [comment]
Seems to be Ok ! 
Thank you :)

**Comment by calebporzio** [comment]
Great, thanks!
