### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@keydown.tab' is not a valid attribute name.

### ISSUE THREAD

**Issue by antoniopaisfernandes** [livewire/livewire#1140]
### Description
It seems there's somewhat of a race condition when setting @keydown.tab listener.

### Steps to reproduce
Replicating the Laracasts series about Livewire (https://github.com/drehimself/laracasts-videogames/commit/dd2aba52d8838860545c05c03d6c461a986d92bf#diff-027a0b5aceb2f4e894aa6e517825cc1eR34) there seems to occur some race condition (or other) that triggers this error:

![image](https://user-images.githubusercontent.com/6171197/85222950-c0e6ea80-b3b6-11ea-9719-ec4a8ff66e33.png)

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.15.0
- Browser: Chrome 83.0.4103.106

**Comment by zusamarehan** [comment]
It is not recommended to add alpine component from the parent div of Livewire component. Wrap another <div> and try adding x-data on it.
Also, try avoiding alpinejs's `@` inside of livewire component use `x-on:`

```
<div>
    <div x-data="{ isVisible: true }" x-on:click.away="isVisible = false">
         ..............
   </div>
</div>
```

**Comment by antoniopaisfernandes** [comment]
Hi @zusamarehan,

Thank you for the help. Unfortunately I'm trying to implement accessibility and so the keyboard usage is mandatory. The ```x-on:click.away``` works fine (https://github.com/drehimself/laracasts-videogames/commit/dd2aba52d8838860545c05c03d6c461a986d92bf#diff-027a0b5aceb2f4e894aa6e517825cc1eR1),

Best regards

**Comment by calebporzio** [comment]
Closing this as it's too difficult to re-produce.

Please re-submit with concise, boiled-down, copy-pastable, complete code.

Thanks!

**Comment by yajra** [comment]
@antoniopaisfernandes were you able to fix this issue? Trying to learn livewire and followed the same laracasts video and encountering exactly the same issue.

**Comment by antoniopaisfernandes** [comment]
Hi,

No, I kind of went away on that problem.

![image](https://user-images.githubusercontent.com/6171197/99874961-aaea8980-2be3-11eb-8ce8-56645e64d61c.png)

**Comment by victoriopui** [comment]
Hope this helps someone, I solved it by changing @click to x-on:click
