### ISSUE TITLE
Vue warn issue

### ISSUE THREAD

**Issue by Algeneralo** [livewire/livewire#1144]
### Description
I'm having an issue when implementing a vue component in livewire, here is the issues: 
`[Vue warn]: Property or method "depositDate" is not defined on the instance but referenced during render. Make sure that this property is reactive`
I already implemented the livewire-vue third party and all things are ok
anyone can help?

**Comment by Algeneralo** [comment]
@calebporzio isn't a bug?

**Comment by nuernbergerA** [comment]
> @calebporzio isn't a bug?

All labels got removed due to restructuring issue categories.

**Comment by devcircus** [comment]
Can u share some code that may help others help you?

**Comment by roitto** [comment]
Do you have the vue instance in the window.Vue object?

**Comment by Algeneralo** [comment]
@devcircus sure, which part you want me to show?

here is the usage of date-picker vue pluing,

```
 <div class="form-group">
            <label>{{ trans("general.date") }}</label>
            <date-picker v-model="depositDate" value-type="format" input-class="form-control"
                         :input-attr="{name:'date',required:'required' }"
                         format="DD.MM.YYYY"></date-picker>
</div>
```

livewire includes 

`@livewire("admin.learner.deposit.index", [ 'learner' => $learner ], key(rand()))
`
vue file

```
new Vue({
    el: ".learner",
    components: { DatePicker},
    data: {
        depositDate: ''
    }
})
```

**Comment by Algeneralo** [comment]
@roitto 
![image](https://user-images.githubusercontent.com/32073999/85554601-beda9100-b62d-11ea-902b-b40933f3b7c0.png)

**Comment by Algeneralo** [comment]
@nuernbergerA any help there?
Thanks

**Comment by nuernbergerA** [comment]
@Algeneralo in order to help you we need a domain free code example to reproduce the bug.

Cheers Adrian
