### ISSUE TITLE
Use wire:target outside livewire component

### ISSUE THREAD

**Issue by joostvanhoof** [livewire/livewire#1147]
### Description
I previously had this:

`<div wire:loading wire:target="date_range"></div>`

where `date_range` was defined by `wire:model` in the same livewire component on a select element.

Because of my app structure, I now update the `date_range` value on a select element through AlpineJS, and this is done _outside_ of the livewire component:
`x-model="date_range" x-on:change="window.livewire.emit('dateRangeChanged', date_range)"`

I then use an event listener in my Livewire component. This all works as expected, but the problem now is that I want to show the loading state of the element mentioned before, _only_ when the `date_range` value is being updated (instead of using `wire:loading` generically) through the global JS event.

Is this possible? `wire:loading wire:target="date_range"` now doesn’t work anymore and I couldn’t find in the docs how to achieve this use case.

The only hacky way I could come up with is that the listener method in the livewire component does something like `$this->date_range_is_loading = true` and set it to `false` at the end of the render method but that doesn’t feel right.

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.16.1
- Browser: any

**Comment by jjjrmy** [comment]
I haven't tried this myself, but try checking out these Javascript hooks
https://github.com/livewire/livewire/blob/1.x/js/HookManager.js
Maybe `interceptWireModelSetValue` or `beforeElementUpdate` could be what you are looking for?

**Comment by joostvanhoof** [comment]
I was wondering if there isn't something that I can apply on the element directly like `wire:target="date_range"` but then something like `wire:target="window.livewire(dateRangeChanged)"`

If I use JS hooks I'd have to write custom JS to intercept the event and based on that apply classes or styles which seems equally hacky compared to doing something like `$this->date_range_is_loading = true`.

**Comment by jjjrmy** [comment]
After re-reading your original post I see what you mean...
`x-model="date_range" x-on:change="window.livewire.emit('dateRangeChanged', date_range)"`
I think instead this can be changed to something like this.
```javascript
let component = window.livewire.find('the-unique-component-id')
component.set('date_range', 'Some Value')
```

**Comment by calebporzio** [comment]
Currently, there are no plans on making wire:loading/target available outside of components.

I'm sure there are lots of workarounds you could do with Alpine, but I will say that I'm considering a JS API that you could use in conjunction with Alpine to hook into a component's loading states. (considering for the next major version)

Closing, Thanks!
