### ISSUE TITLE
Getting 500 error on Vapor, unable to find manifest.json

### ISSUE THREAD

**Issue by leoneparise** [livewire/livewire#1164]
### Description
I'm getting a 500 error when I deploy a livewire application on Laravel vapor. Here is the error messsage:

```
file_get_contents(/var/task/public/vendor/livewire/manifest.json): failed to open stream: No such file or directory (View: /var/task/resources/views/layouts/app.blade.php) (View: /var/task/resources/views/layouts/app.blade.php)
```

Here is the stack trace: https://flareapp.io/share/87nLZDmw#F68

### Steps to reproduce

Deploy the application on a Vapor environment and try to open a Livewire page.

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.17.2
- Browser: Chrome

**Comment by TimothePearce** [comment]
Did you try to publish your assets commit them to your repository before the deployment?

[Docuemntation](https://laravel-livewire.com/docs/installation)

**Comment by leoneparise** [comment]
Yes. Assets are published and uploaded to S3.

**Comment by leoneparise** [comment]
Nevermind. Updated `vapor-cli` to latest version and now it works.
