### ISSUE TITLE
No documentation on pre-filling existing uploads?

### ISSUE THREAD

**Issue by marbuser** [livewire/livewire#1168]
Not really a bug but would like to see it addressed if possible! The docs only show the actual upload section of files. It doesn't show how to prepopulate existing uploads when they already exist in say a show or edit view.

It would be nice to see a "recommended"/"official" approach to do this since this type of functionality has a tendency to take a nice clean and organised code-base and completely mess everything up, and often times like in my situation right now, still not working.

**Comment by mblarsen** [comment]
Was just dealing with this right this moment. Or rather I made a note of that I had to deal with it.

**Comment by devcircus** [comment]
Seems outside the scope of the upload feature. It's left up to the developer how to store the upload in the db. Should just be able to store the url(s) in the db and show them in the page.

**Comment by marbuser** [comment]
@mblarsen Did you ever manage to figure this out? I'm still absolutely clueless about this and it seems the questions around this particular subject are starting to pile up with no real way to do it.

**Comment by austenc** [comment]
@devcircus is right here -- this is dependent on how you want to display them and which storage mechanism your app uses. Since there are so many ways to tackle this, it's probably not within the scope of Livewire's documentation. 

@marbuser if you provide some code or more details about what you're trying to do, I'd be happy to try to help.

**Comment by calebporzio** [comment]
Thanks for weighing in @austenc.

I'm closing this for now.

I agree there should be more info on this story. I'm open to a more detailed proposal or PR for this use case Thanks!
