### ISSUE TITLE
wire:loading.attr not working as expected in combination with wire:poll refresh

### ISSUE THREAD

**Issue by jwktje** [livewire/livewire#117]
**Describe the bug**
First of all, I'm loving livewire so far! Super cool stuff!

I'm using `wire:loading.attr="disabled"` in combination with `wire:poll.3000ms="$refresh"`.
When using the wire:loading.attr="disabled" on a text input, it shows as disabled while waiting for the network round trip to complete. However, after this request completes the component is not rerendered. It only rerenders on the poll interval.

**To Reproduce**
```
<div>
    <div class="messages-wrap" wire:poll.3000ms="$refresh">
       @foreach ($messages as $message)
           <div>{{$message->text}}</div>
       @endforeach
    </div>

    <input id="newMessageInput" type="text"
        wire:loading.attr="disabled"
        wire:keydown.enter="newMessage"
        wire:model.lazy="newMessageText"
    >
    <button id="sendMessage" wire:click="newMessage">Verzenden</button>
</div>
```

**Expected behavior**
I would expect the disabled property to be set on the text-input while loading, and after the network round-trip I'd expect the message to be added and the disabled attribute to clear. 
What happens instead is that it takes the poll interval to trigger before the message appears.

**Additional context**
This might just be me misunderstanding the system.

**Comment by jwktje** [comment]
As an experiment I tried to separate the messages view from the form like so
**chat.blade.php**
```
<div>
    <button wire:click="clearMessages">Clear</button>
    <div class="messages-wrap" wire:poll.2000ms="$refresh">
       @foreach ($messages as $message)
           <div>{{$message->text}}</div>
       @endforeach
    </div>
</div>
```
**chat-form.blade.php**
```
<div>
    <input id="newMessageInput" type="text"
           wire:keydown.enter="newMessage"
           wire:model.lazy="newMessageText"
    >
    <button id="sendMessage" wire:click="newMessage" >Verzenden</button>
</div>
```

This works but creates a now issue. Which is; 
**By using the lazy mode, the model is empty when clicking the button. When not using the lazy mode it sometimes only catches half the sentence in the model**

When typing a longer sentence and pressing enter, it on occasion will have only updated the model half way through typing it. By switching to lazy mode you eliminate this, but this means a change event has only triggered as you click on the button. So you have to click twice.

How would I leverage lazy mode on the input, but still force-update the model when an event happens, like pressing enter or the button?

**Comment by calebporzio** [comment]
Ok @jwktje, there are a couple different things going on in this issue. It would be best to split them out into separate issues.

Let's start with the first problem.

I replicated your code locally and everything seemed to work fine.

Here's the view code:
```html
<div>
    <style>
        input[disabled] {
            border: 1px solid black;
        }
    </style>

    <div wire:poll.5000ms="$refresh"></div>

    <input wire:loading.attr="disabled">
</div>
```
I added a forced `sleep(1)` to the render method so we could see the loading indicator. Here is what showed up on the page:

![Aug-05-2019 23-08-24](https://user-images.githubusercontent.com/3670578/62508617-4fba3b00-b7d6-11e9-88b5-9377f281f95c.gif)

As you can see, the behavior is as expected.

Can you expound on how your experience differs from this?

Also, open a separate issue for the other issue you're experiencing with the half-filled models and lazy "change" event issues. (and when you do put what version of Livewire you're using, because I believe I fixed one of those issues recently)

- Thanks!

**Comment by jwktje** [comment]
I think I might have not explained it correctly so I recorded a video too. Consider the following behaviour; 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4722137/62519210-6c349280-b82b-11e9-81ea-cae33a84dc51.gif)

**What I would want to happen;**
1. Type text
2. Click send (or press enter)
3. Input gets disabled as `sendMessages` action is triggered
4. Input gets enabled when (specifically) this action is done loading
5. Dom gets refreshed with the new message a couple of seconds later as the poll triggers, but this doesn't influence the disabling of the input. 

**What goes wrong;**
When clicking send or pressing enter, it only triggers change then. So at the moment of triggering the action, the property is empty.

### Relevant Code
**chat.blade.php**
```
<div>
    <div class="messages-wrap" wire:poll.2500ms="$refresh">
        @foreach ($messages as $message)
            <div>{{$message->text}}</div>
        @endforeach
    </div>
</div>
```
**chat-form.blade.php**
```
<div>
    <input id="newMessageInput" type="text"
           wire:loading.attr="disabled"
           wire:target="send-message"
           wire:ref="send-message"
           wire:keydown.enter="newMessage"
           wire:model.lazy="newMessageText"
    >
    <button id="sendMessage" wire:click="newMessage" wire:ref="send-message">Send</button>
    <button id="clearMessages" wire:click="clearMessages">Clear</button>
</div>
```
**ChatForm.php**
```
<?php

namespace App\Http\Livewire;

use App\Messages;
use Livewire\Component;

class ChatForm extends Component
{
    public $newMessageText;

    public function render()
    {
        return view('livewire.chat-form');
    }
    public function newMessage()
    {
        if($this->newMessageText) {
            Messages::create(['text' => $this->newMessageText]);
            $this->newMessageText = "";
        }
    }
    public function clearMessages()
    {
        Messages::truncate();
    }
}
```

**Comment by jwktje** [comment]
Just read the newsletter update on Livewire, great update @calebporzio 
I was wondering, could the "Dirty state" lay the groundwork for a solution to this issue somehow?

Because in my situation I would only want the send action to trigger once the component isn't dirty anymore. Meaning; the added message on the server is actually what is in the input.
I think it would be bad UX to disable the send button while the component is dirty.

Ideally the steps would be; 
1. User presses send or enter key
2. Component is dirty so the send action isn't triggered, but input field is still being disabled.
3. Once component isn't dirty anymore, action is triggered
4. Once loading finishes input is enabled

**Comment by jwktje** [comment]
Bump to ask; Anything I could do to help solve this use case?
