### ISSUE TITLE
Route::group - Route Name Prefixes

### ISSUE THREAD

**Issue by pschilly** [livewire/livewire#1175]
### Description
When using Route::Livewire ... it does not cascade the name prefix from the group.

### Steps to reproduce
Example code in: routes/web.php to discover what I think is a bug:

```
Route::group([

        'layout' => 'layouts.backend', 

        'section' => 'body',

        'name' => 'administration.',

        'prefix' => 'administration',

        'middleware' => 'role:administrator'

    ], function () {

        Route::livewire('dashboard', 'backend.dashboard')

        ->name('dashboard');

    });
```

**Context**
- Livewire version: Latest
- Laravel version: Latest

**Comment by abrardev99** [comment]
Can you try uisng this approach, this is totly working for me
```
Route::group(['layout' => 'layouts.admin.app'], function () {
    Route::middleware(['auth', 'IsAdmin'])->group(function () {
        Route::name('admin.')->group(function () {
            Route::get('admin/profile', 'Admin\ProfileController@getProfile')->name('profile');

        });

    });
});
```

and now route name should be

`{{ route('admin.profile') }}`

**Comment by pschilly** [comment]
That does work - but that's not using the Route::livewire() function to route directly to the livewire component

**Comment by DanHarrin** [comment]
Hi @pschilly, unfortunately this isn't an issue with Livewire, Laravel itself doesn't support name prefixing in the group config array.

Try this -
```php
Route::layout('layouts.backend')->section('body')->name('administration.')->prefix('administration')->middleware('role:administrator')->group(function () {
    Route::livewire('dashboard', 'backend.dashboard')->name('dashboard');
});
```

**Comment by pschilly** [comment]
Hey Dan,

I tried that out - works great. Also I found that if i changed the "name" to "as" in the group config array it also worked. Bug in Laravel I suppose?

This is also working in addition to your above clip:

```PHP
Route::group([
        'layout' => 'layouts.backend', 
        'section' => 'body',
        'as' => 'administration.',
        'prefix' => 'administration',
        'middleware' => 'role:administrator'
], function () {
    Route::livewire('dashboard', 'backend.dashboard')
    ->name('dashboard');
});
```
