### ISSUE TITLE
Can't use $attributes in a component

### ISSUE THREAD

**Issue by felixdorn** [livewire/livewire#1176]
### Description
I've just started digging into LW, but I ran into a problem and I guess it's a wanted behavior ?

In a LW component, there's no way to "transfer" attributes from the component declaration to the component itself, unlike Blade components.

### Steps to reproduce

* `php artisan make:livewire ColorInput`
* `<livewire:color-input class="max-w-max-content" />`

In the component,
```
<input {{ $attributes }} />
```

See the exception : `Undefined variable: attributes`

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.17.2
- Browser: Firefox

**Comment by ManojKiranA** [comment]
i think you are talking about blade components  ??

https://laravel.com/docs/7.x/blade#components

**Comment by calebporzio** [comment]
Livewire currently doesn't support $attributes like blade components do.

We will consider adding this in the next major version

**Comment by felixdorn** [comment]
@calebporzio Really nice to hear, thanks!
@ManojKiranA No.

**Comment by forrestedw** [comment]
Yeah this would be so useful to have so that Livewire and blade components can use the same syntax for this!

**Comment by kevin4dhd** [comment]
any solution?

**Comment by bernhardh** [comment]
Yeah. Would love to see one.

**Comment by unarmedwombat** [comment]
Definitely +1 from me - work-around code is ugly

**Comment by RealMrHex** [comment]
this problem still present for over 2 yrs!
Anyone hear us?? :)
we r still waiting for the major update XD @calebporzio

**Comment by SuperHydroman** [comment]
@RealMrHex I agree :( I need this!

**Comment by nkvatadze** [comment]
Is there any update on this?

**Comment by danjdewhurst** [comment]
Will this come with V3?

**Comment by joshhanley** [comment]
@danjdewhurst probably not. It's not an easy problem to solve as Livewire components run on multiple requests, in the first request it would work, we could pass the attributes in from whatever is calling the component, but on subsequent requests, the attributes will no longer be available. So where would they come from?

**Comment by danjdewhurst** [comment]
> @danjdewhurst probably not. It's not an easy problem to solve as Livewire components run on multiple requests, in the first request it would work, we could pass the attributes in from whatever is calling the component, but on subsequent requests, the attributes will no longer be available. So where would they come from?

Any sort of persistent state I'd imagine? I'm not sure how the next component works after the first render, but couldn't each subsequent request just include the attributes or even hold them in the session assuming each subsequent component has reference to the same ID or initial component render?
