### ISSUE TITLE
Keydown event always triggers for some modifiers

### ISSUE THREAD

**Issue by stromgren** [livewire/livewire#1177]
### Description
When using certain modifier (I've tried backspace and escape) together with wire:keydown e.g. wire:keydown.backspace, it triggers for all keydown events.

### Steps to reproduce

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.17.2
- Browser: Chrome 83 on MacOS

Given this Livewire component.

```php
class Test extends Component
{
    public $data;

    public function render()
    {
        return view('livewire.test');
    }

    public function removeLast()
    {
        info('removeLast');
    }
}
```

```
<div>
    <input x-ref="input" wire:model="data" wire:keydown.backspace="removeLast" />
</div>
```

For every keydown event in the input removeLast() is triggered and logs to the log file. This is not the case for all modifiers. Using arrow-down seems to be fine.

**Comment by asantibanez** [comment]
Can also confirm this one. Happened to me with `escape` not so long ago.

**Comment by stromgren** [comment]
I could try to fix it, but I'm not familiar enough with the source to find where to start. If someone could point me in the right direction I'd have a look at this straight away :)

**Comment by ATholin** [comment]
I pushed a fix for this in #1183. Does this resolve the issue for you?

**Comment by stromgren** [comment]
@ATholin I can confirm that this works! Thank you!

**Comment by emaia** [comment]
@ATholin this works for me too. Thks
