### ISSUE TITLE
Temporary filename with "-size:" not supported by Windows

### ISSUE THREAD

**Issue by ATholin** [livewire/livewire#1189]
### Description

A colon ":" is an invalid character for Windows filenames. The temporary files encode the file size in the filename by appending`-size:{$file->getSize()}` during tests. This causes tests to fail since it cannot rename the files.

### Steps to reproduce

**Prerequisite:** Windows

**Livewire/FileUploadComponent:**
```php
class FileUploadComponent extends Component
{
    use WithFileUploads;

    public $file;

    public function render()
    {
        return view('livewire.file-upload-component');
    }
}
```

**Test**
```php
public function testBasicTest()
{
    Storage::fake();

    $file = UploadedFile::fake()->image('image.png', 100, 200);

    Livewire::test(FileUploadComponent::class)
        ->set('file', $file);
}
```

### Context
- Livewire version: 1.2.0
- Laravel version: 7.17.2
- Operating system: Windows

**Comment by calebporzio** [comment]
Ah, got it. I will merge this PR. Thanks!
