### ISSUE TITLE
Memory Heap Issue With FilePond

### ISSUE THREAD

**Issue by andylord56** [livewire/livewire#1196]
### Description
Memory heap increases the more you do the more memory the slower the page as well.
Using the memory tab (Chrome) when browsing with JS files included they are reloaded and reinitialized and put in memory after a short time of browsing and inputting values to inputs the memory can increase from 5Mb to 50Mb.
- Event listeners are duplicated in memory:
![image](https://user-images.githubusercontent.com/2530510/86226870-2b9ce080-bb84-11ea-8fb5-a83721db7c39.png)
all.js includes: var filepond = window.FilePond = require('filepond');
- Graph of the increase
![image](https://user-images.githubusercontent.com/2530510/86227088-79b1e400-bb84-11ea-95c3-58abeccbb269.png)
This continually rises the more you browse or input with JS files on the page

### Steps to reproduce
Stack: Laravel, livewire, alpinejs, turbolinks
Create a form with filepond at the continually edit fields and click away watch the memory rise an rise

**Context**
- Livewire version: [e.g. 1.0.0] 1.0
- Laravel version: [e.g. 7.0.0] 7.0
- Browser: [e.g. Chrome, Safari] all browsers

**Comment by andylord56** [comment]
Looking into this further and debugging commenting out Alpinejs seems to stop all memory leaks
found some references that sound similiar:
https://github.com/alpinejs/alpine/issues/19
https://github.com/alpinejs/alpine/issues/446

**Comment by andylord56** [comment]
I have created a Laravel Playground with an example of this:
https://laravelplayground.com/#/snippets/aeaccf44-b532-4c95-820e-0ed26204b1ec
Keep changing the values in the inputs over and over and watch the memory rise and rise
note the more js on the page the worse it is same goes for inputs 
this with turbolinks give a hell of a memory leak as it never drops

Hats of to Beyond Code for Laravel Playground

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
