### ISSUE TITLE
JS tests fail: Cannot read property 'storeResponse' of null

### ISSUE THREAD

**Issue by ATholin** [livewire/livewire#1200]
### Description

Running JS tests seem to always fail on "polling on root div" for me.

![jest-fail](https://user-images.githubusercontent.com/33940473/86269845-9d981880-bbca-11ea-8911-eb4f9a25821f.png)

Adding a null check for `messageInTransit` on `receiveMessage()` seems to resolve the issue. Is there a reason that it's not there?

**Example:**

```javascript
receiveMessage(payload) {
    if (! this.messageInTransit) return  // <------ adding this makes tests pass

    var response = this.messageInTransit.storeResponse(payload)

    // ....
```

### Steps to reproduce

```
npm run test
```

**Context**
- Livewire version: 1.2.0
- Laravel version: 7.17.2
- Browser: N/A
- OS: Windows
- Node.js: 12.14.0

**Comment by mattharcourt** [comment]
I'm not able to repeat the issue, but is there a possible interaction between tests? It looks like that test doesn't call `onMessage` (and therefore `receiveMessage`), so maybe the preceding test(s) didn't get cleaned up completely. Does it still happen if you run only that one test?

**Comment by ATholin** [comment]
When running only that test using `jest -t 'polling on root div'`, it passes.

**Comment by mattharcourt** [comment]
Try making the first few lines of `mountAsRoot()` look like those in `mountasRootAndReturn()` in `tests/js/utils.js` and see if that helps (add the reset of `document.body.innerHTML`).

**Comment by ATholin** [comment]
Didn't help, unfortunately.

**Comment by mattharcourt** [comment]
And if you also make the same modification to `mount()` in `tests/js/utils.js`? It's also used earlier in the polling test file.

**Comment by ATholin** [comment]
Nope, didn't help. It seems a bit inconsistent. Sometimes these same issue occurs on other tests, specifically in `ignore.spec.js`.

I'm quite new to the source, so It's hard trying to wrap my head around it. Thank you for your help!

**Comment by mattharcourt** [comment]
I think the inconsistency is due to timing. Most (all?) of the tests instantiate and start a new Livewire instance, but then don't stop it which can leave stuff attached to the window and/or document. In the case of polling, each poll calls `setInterval()` and leaves a callback to cleanup when Livewire is stopped. So if Livewire isn't stopped...

Setting the `document.body.innerHTML` is an attempt to clean up (according to the comments), but maybe this isn't effective/reliable. It seems like most tests should have a `window.livewire.stop()` at the end.

It's hard to test, since it's intermittent - and I haven't been experiencing the issue.

**Comment by ATholin** [comment]
Yeah, I tried using the `afterEach()` to stop the instance and clear the innerHTML. This did not help.

It seems to an issue with interference from the `'polling will start if directive is added'` in `polling.spec.js`. Removing this test makes the other one pass.

**Comment by mattharcourt** [comment]
What if you add `window.livewire.stop()` to the end of the `polling will start if directive is added` test? Trying to make sure that whatever is added when the directive is added gets removed before moving on from that test.

**Comment by ATholin** [comment]
Yep, tried that. I'll try some more in a few hours. Thank you for the help Matt, I really appreciate it.

**Comment by ATholin** [comment]
Closing this since it seems really inconsistent and only happens on my Windows machine.
