### ISSUE TITLE
wire:click doesn't work on `option` from a select (works fine only on some browsers)

### ISSUE THREAD

**Issue by simonovski** [livewire/livewire#1206]
### Description
Using `wire:click` on an `option` from a select dropdown to update an item in Cart quantity.

Works perfectly fine on:
- Mac (Chrome, Firefox, Safari, Mobile Safari)
- Windows (Firefox)

Doesn't work on:
- Windows (Chrome)
- Android (Chrome, Firefox)

### Steps to reproduce

```
@for ($i = 0; $i < 50; $i++)
    <option wire:click.prevent="updateItemQuantity({{ $item->getId() }}, {{ $i }})" @if($i == $item->getQuantity()) selected="selected" @endif>
         {{ $i }}
    </option>
@endfor
```

Is there any way to debug this, why doesn't work on Chome for windows only and and on Android, iOS (works fine).
Can someone point me to a direction what else can i try/test to further understand the problem?
On the browser that it doesn't work it is not making any `XHR` request in the browser..

**Context**
- Livewire version: [1.1.0]
- Laravel version: [6.0.0]
- Browser: [Chrome (Windows), Chrome and Firefox (Android)]

**Comment by ryangjchandler** [comment]
Click handlers on `<option>` elements are notoriously unreliable. You're better of using some JavaScript to listen for the `<select>` change event or see if you can use `wire:model` in some way.

**Comment by malikkrehic** [comment]
I think I got some similar issue - inside select option, I wanted to render a list of items from Livewire component variable with Blade's @foreach loop, but this variable isn't accessible inside the <select> element, while it's available everywhere else.

**Comment by calebporzio** [comment]
Thanks Ryan!

**Comment by MasterZydra** [comment]
A workaround that I found without binding it to a property, is using alpine JS:
```HTML
<select x-data="{ value: 0 }}}" x-model="value" x-on:change="$wire.yourLivewireFunction(value)">
	<option value="{{ $item->$id }}">...</option>
</select>
```
