### ISSUE TITLE
Element with wire:loading.remove does not show up again after request error

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#1215]
### Description

Hello!

Now, after Livewire version 1.3.0, form inputs are reenabled if a request error occurs.
But I noticed that elements with wire:loading.remove do not show up again after the error is returned.

### Steps to reproduce

1 - Create a Livewire component
2 - Inside the Livewire component view, create a form with a submit button. Something like this:

```html
<form wire:submit.prevent="submit">
  <button type="submit"
               wire:loading.attr="disabled"
               wire:target="submit">
        <span wire:loading.remove wire:target="submit">
            Save
        </span>
        <span wire:loading wire:target="submit">
            Saving...
        </span>
  </button>
</form>
```

3 - Inside the Livewire component class, add a "submit" method that throws an exception
4 - You can see that the button will not show any text after the error response. The expected behavior is the "Save" text show up again.

**Context**
- Livewire version: 1.3.0
- Laravel version: 7.18.0
- Browser: Chrome

**Comment by mblarsen** [comment]
I can see use cases where you don't want it to show up. But actually ran into the same issue today where I expected that it would return. I.e. only remove during loading.

**Comment by bagwaa** [comment]
I also ran into this recently, I think it's a pretty common occurrence for this behaviour, for example I have an icon that is displayed for a file upload (static svg), and then once the file upload is in progress it animates, if the validation fails I want it to apply the static image back in place.

**Comment by jakjr** [comment]
looks that wire:loading.remove and wire:loading.class.remove are not working on version 1.3.3

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
