### ISSUE TITLE
"Session expire" loops for every page component not refreshing the page.

### ISSUE THREAD

**Issue by MrWeb** [livewire/livewire#1220]
### Description

I've updated Livewire from 1.2 to 1.3.
I opened my website which has many livewire components in the same page and I left the office, I came back and there was an HTML alert saying something like "Your session expired would you like to to refresh the page?"  I clicked "ok" and a new modal showed up, I clicked ok and another one showed up and so on. I think that fired for every component in the page, until I pressed "cancel" and it finally refreshed the page.

### Steps to reproduce

Just place some components on the page an let the session expire.

**Context**
- Livewire version: 1.3.0
- Laravel version: 7.18.0
- Browser: Chrome

**Comment by calebporzio** [comment]
Thanks for the issue. We're on it!

**Comment by DanHarrin** [comment]
Hey @MrWeb, I've just published #1232 if you could please take a look and see if it solves your issue.

**Comment by MrWeb** [comment]
Hi @DanHarrin yes it does!
