### ISSUE TITLE
Deployment optimization not possible, file-upload is a Closure.

### ISSUE THREAD

**Issue by xewl** [livewire/livewire#1223]
### Description
During deployment the `optimize` command failed.

Returning
```
  LogicException 

  Unable to prepare route [laravel-livewire-forms/file-upload] for serialization. Uses Closure.
```

### Steps to reproduce
use `php artisan optimize`

**Context**
- Livewire version: ^1.0
- Laravel version: ^7.0
- Browser: N/A

**Comment by nuernbergerA** [comment]
Please provide code in the most distilled, generic, reproducable representation possible, so we can copy and paste easily.

**Comment by xewl** [comment]
@nuernbergerA It was actually the most distilled and concise way, but I was posting this to the wrong repository.
Ultimately, this is related to `kdion4891/laravel-livewire-forms` and not this repository.

Sorry (:

**Comment by nuernbergerA** [comment]
@xewl no problem
