### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by BrandonKerr** [livewire/livewire#1227]
### Description
Following the example for Select2 integration at https://laravel-livewire.com/docs/third-party-libraries/ (exact copy/paste from the **Ignoring DOM-changes (using wire:ignore) section)** throws the "Cannot read property 'find' of undefined" error to the console.

### Steps to reproduce
* Create a new Livewire component and populate the blade with the contents of the **Ignoring DOM-changes (using wire:ignore)** code snippet from https://laravel-livewire.com/docs/third-party-libraries/.
* Include the component on your Laravel blade, ensuring you have a `@stack('scripts')` and the Select2 JS library included
* In the rendered page, change the component's selection (eg change to Wyoming). Watch the browser's console to see the error: `Uncaught TypeError: Cannot read property 'find' of undefined`

**Context**
- Livewire version: 1.3.0
- Laravel version: 7.15.0
- Browser: Chrome

**Comment by BrandonKerr** [comment]
User error - apologies for the confusion.

**Comment by tomphilpotts** [comment]
@BrandonKerr What was it? Running into the same issue!

**Comment by tomphilpotts** [comment]
Worked out the issue

Anyone with the issue reading this, I ran `php artisan livewire:discover`. I was having the issue on a production site.
