### ISSUE TITLE
Target class [universal] does not exist.

### ISSUE THREAD

**Issue by djoudi** [livewire/livewire#1229]
### Description
Illuminate\Contracts\Container\BindingResolutionException
Target class [universal] does not exist.
https://elearndev.dev/livewire/message/account.users

![image](https://user-images.githubusercontent.com/152725/86710767-984c2b00-c01b-11ea-9dfb-423bf75930af.png)

### Steps to reproduce
all [wire:]    event  in form i see this issue
**Context**
- Livewire version: 1.3
- Laravel version: 7.18.0
- Browser: Chrome

**Comment by lucasgiovanny** [comment]
@djoudi How did you solve this issue?

**Comment by joshhanley** [comment]
@lucasgiovanny are you experiencing this issue?

**Comment by lucasgiovanny** [comment]
Hi, @joshhanley. Yes, I was. 
I'm using [Tenancy for Laravel](https://tenancyforlaravel.com/) alongside with Livewire, and to make this work a needed to activate universal routes feature from Tenancy for Laravel as middleware in Livewire as explained on their [documentation](https://tenancyforlaravel.com/docs/v3/integrations/livewire).
When I removed the universal middleware group from Kernel, Liveware was not able to find it anymore and that caused the error on my case :)

**Comment by joshhanley** [comment]
@lucasgiovanny ah right! Did you manage to sort it? If so was that by putting he universal middleware group back into the Kernel? Or something else? Just asking incase anyone else runs into the issue 🙂

**Comment by lucasgiovanny** [comment]
Yes, I had to put universal middleware group back to Kernel. Other option it was remove it from livewire config.
