### ISSUE TITLE
Upload big videos to S3

### ISSUE THREAD

**Issue by techguydev** [livewire/livewire#1233]
Thanks for this great project @calebporzio 

I need to upload large videos to s3.

Is Livewire uploader intended for this kind of use?

**Comment by edgrosvenor** [comment]
@techguydev I'm using it for that without any trouble.

**Comment by techguydev** [comment]
Hi @edgrosvenor , could you share some code ?


Thanks

**Comment by edgrosvenor** [comment]
@techguydev My only implementation is inside a proprietary project so I can't share any of that code. But the next article I plan to write for my blog (hopefully this week) will be using Livewire to upload videos to S3 to be encoded using Elastic Transcoder.
