### ISSUE TITLE
Pagination not working as Intended on Brave Browser

### ISSUE THREAD

**Issue by lilouch** [livewire/livewire#1253]
### Description
When I try to paginate, instead of getting the total pages, I get "pagination.previous" and "pagination.next".

I think the problem come from the browser I use ([Brave](https://brave.com/ref757)). I tried on Firefox and it is working perflectly.

**On Brave**
![2020-07-10_10-12-14](https://user-images.githubusercontent.com/8614763/87132263-e8cebd00-c295-11ea-8ab7-1dd08b6028a4.jpg)

**On Firefox**
![2020-07-10_10-12-28](https://user-images.githubusercontent.com/8614763/87132285-eff5cb00-c295-11ea-9b1e-c09ac62a7fa7.jpg)

**Context**
- Livewire version: 1.3.1
- Laravel version: 7.*
- Browser: Brave

**Comment by hortigado** [comment]
in my case yes work in brave the pagination.

**Comment by zepfietje** [comment]
@lilouch, could you check if this problem still exists?
Else, please close this issue.

**Comment by lilouch** [comment]
I was not able to make it work in Brave so I use another way to do the pagination...

**Comment by CraftLogan** [comment]
Did you try it with the brave shields down? Were you able to come to the root cause of this issue?

**Comment by lilouch** [comment]
@CraftLogan Yes I deactive the shields to see if it was the problem and as far I remember, it was still not working. As I did not know and did not have the time to inspect this, I change my way to do it.
