### ISSUE TITLE
Livewire starts too late - under some circumstances

### ISSUE THREAD

**Issue by nielspeen** [livewire/livewire#1256]
### Description

Livewire waits for the DOMContentLoaded event. But the end-user may not. If there are slow-loading/timing-out assets on the site there is a period of time where the user can submit forms without Livewire.

Under ideal circumstances this never happens. But in areas where network conditions are poor, or where common 3rd-party assets are blocked, it presents a real problem.

### Steps to reproduce

Add a slow-loading or slow-failing asset to your HTML. For example:

<script type="text/javascript" defer="defer" src="https://8.8.8.0/timeout"></script>

This will delay Livewire from starting and allow the user to submit forms without it.

### Work-around

I've alleviated things by adding the _async_ attribute to most of my script tags. But that's not always an option, and probably shouldn't be a requirement for the safe use of Livewire.

**Comment by edgrosvenor** [comment]
I think the right approach here is to make your forms invisible initially and then toggle them to visible on the DOMContentLoaded event so that they become visible at the same time the javascript they rely on is available. There are some pretty compelling reasons for Livewire to wait until the DOM is fully loaded to do its thing and it's not a terribly hard problem to work around. Just never show anything to the user that needs Livewire until Livewire is ready to go.

**Comment by jimpeters** [comment]
I agree with @edgrosvenor .  This is not a Livewire specific issue.  You could be talking about any Javascript library.  You could easily have a class that uses display: none and removes the class when you feel like you are ready.  Feel like you can close this issue @nielspeen ?

**Comment by jimpeters** [comment]
Another approach would to include alpinejs into your project and add the x-cloak attribute to your <body> tag.  Alpine does not initialize and remove this tag until Livewire starts and then Alpine starts.

```html
<body x-cloak>
```
Don't forget the global style.

```html
<head>
	<style>
    [x-cloak] { display: none; }
	</style>
</head>
```

**Comment by nielspeen** [comment]
Those are good suggestions. I worked around the issue with a similar solution. I hesitate to close the issue because Livewire, different from most other Javascript libraries, aims to bring _dynamic interfaces without leaving the comfort of Laravel_. 

It's also problem that will occur frequently in (parts of) the real world but that many developers, developing locally or having fast access to the servers they work with, won't catch with regular testing.

As @livewireScripts already injects javascript into the page directly, I would argue that it should be extended to prevent form submission until loading has completed.

**Comment by calebporzio** [comment]
Good points, closing this however
