### ISSUE TITLE
Query param with literal + isn't urlencoded correctly

### ISSUE THREAD

**Issue by jhoff** [livewire/livewire#1259]
### Description

When using `updatesQueryString`, a query that contains a literal `+` is lost during navigation because it's not url encoded properly as `%2B`.

### Steps to reproduce

Using the [example in the docs](https://laravel-livewire.com/docs/properties#query-string) if I were to search for `foo+bar` ( which should return 1 result ) it would work as expected up until the page is hard-refreshed or navigated back to.

Initial search: `foo+bar`
Initial url: `?search=foo+bar`
Returns 1 result

If I were to refresh the page, I would get the following:

Refreshed search: `foo bar`
Refreshed url: `?search=foo+bar`
Returns 0 results

However, if I were to navigate away from the initial page and press back in the browser, I would get the following:

Navigated search: `foo+bar`
Navigated url: `?search=foo+bar`
Returns 0 results

**Context**
- Livewire version: 1.3.0
- Laravel version: 7.15.0
- Browser: Chrome, Safari, Firefox, probably more

**Comment by zepfietje** [comment]
@jhoff, I think this issue has been resolved in v2.
Could you confirm and close this issue?

**Comment by austenc** [comment]
Also noticed this with the `#` character. Thanks for reporting @jhoff

**Comment by austenc** [comment]
This is fixed in `2.x` with the much better handling of query string updating. 

https://laravel-livewire.com/docs/2.x/upgrading#query-string

**Comment by calebporzio** [comment]
Thanks pointing this out @austenc  - closing!
