### ISSUE TITLE
Is it possible to use a not persist eloquent model as public property?

### ISSUE THREAD

**Issue by jakjr** [livewire/livewire#1261]
### Description
When using an new eloquent modal that was not perist at database, an error occorus.
This error is in HydrateEloquentModelsAsPublicProperties->restoreModel middleware.
Livewire is trying to restore a modal that was not persisted, so we get an exception from firstOeFail eloquent method.

### Steps to reproduce
Set a public property as a new Model: eg:

$this->user = new User();

**Context**
- Livewire version: [e.g. 1.3.1]
- Laravel version: [e.g. 7.3.0]
- Browser: Chrome

**Comment by ryangjchandler** [comment]
No this isn't possible at the moment. You're better of using an array, then creating the User model from that array later on.
