### ISSUE TITLE
ValidationException not caught in computed properties

### ISSUE THREAD

**Issue by fabricecw** [livewire/livewire#1265]
### Description
When using Livewire's Computed Properties with the Livewire Validation, the `ValidationException` isn't caught by Livewire.
I noticed the pull request #1066 but don't think it covers this behaviour.

If this issue isn't duplicate and can be reproduced by others, I will check the code and submit a PR.

### Steps to reproduce

1. Create a computed property like `getFooProperty` and call it in the template
2. Make some Livewire Validation:

```
public function getFooProperty()
    {
        $this->validate([
            'deliveryDate' => 'required|date|after:now'
        ]);
       
        // Further logic...
    }
```

3. Laravel Livewire doesn't catch the ValidationException like in normal actions and shows the frontend debugging window.

**Context**
- Livewire version: 1.3.1
- Laravel version: 6.15.1
- Browser: Google Chrome

**Comment by ali-alharthi** [comment]
I believe you got it wrong! Computed properties are an easy way to access properties and that is it.

For example, lets say you have an order component (livewire component) as follow

```
use Livewire\Component;

class ShowOrder extends Component
{
    public $orderId;

    public function mount($orderId)
    {
        $this->orderId= $orderId;
    }

    public function getOrderProperty()
    {
        return Post::find($this->orderId);
    }

    public function render()
    {
        return view('livewire.show-order');
    }
}
```
Now, you can access `$this->order` from either the component's class or Blade view:
```
<div>
    ...
    <h1>{{ $this->order->total }}</h1>
    ...
</div>
```

Livewire documentation: "Livewire offers an API for accessing dynamic properties. This is especially helpful for deriving properties from the database or another persistent store like a cache."

Read more: [Computed Properties](https://laravel-livewire.com/docs/properties#computed-properties)

**Comment by ali-alharthi** [comment]
I believe you got it wrong! Computed properties are an easy way to access properties and that is it.

Livewire documentation: "Livewire offers an API for accessing dynamic properties. This is especially helpful for deriving properties from the database or another persistent store like a cache."

For example, lets say you have an order component (livewire component) as follow

```
use Livewire\Component;

class ShowOrder extends Component
{
    public $orderId;

    public function mount($orderId)
    {
        $this->orderId= $orderId;
    }

    public function getOrderProperty()
    {
        return Order::find($this->orderId);
    }

    public function render()
    {
        return view('livewire.show-order');
    }
}
```
Now, you can access `$this->order` from either the component's class or Blade view:
```
<div>
    ...
    <h1>{{ $this->order->total }}</h1>
    ...
</div>
```

Read more: [Computed Properties](https://laravel-livewire.com/docs/properties#computed-properties)

**Comment by zepfietje** [comment]
@fabricecw, as @ali-alharthi commented, this is not a Livewire bug.
If you have no other questions, you can close this issue.

**Comment by fabricecw** [comment]
Sorry for my late feedback.
I'm totally with you, this isn't a bug. But what factors speaks against doing the same exception handling as in actions?
