### ISSUE TITLE
It's so out of control (edit form) keep submitting the form 

### ISSUE THREAD

**Issue by asb6339** [livewire/livewire#1266]
### Description
please don't look for grammar mistakes as you can see from my first name english is not my mother language 
I'm just writing an edit form were I load the data by using the `model:wire="mything"` but what I'm dealing with is I can't edit the form as whenever I change any value the form keep submitting automatically 
I've tried `wire:ignore` and from the documentation it seems the ignore doesn't stop everything only certain libraries
I'm just dealing with regular `text input`s 
what I'm missing here ? 
how to prevent the form from submitting whenever changing any values in any input type ? 

controller 
````
    public $first_name;
    public $last_name;
    



    public function submit()
    {
        // whenever I get here 
    }

    public function render()
    {
        $getUser = app()->make(userRepository::class);
        $user = $getEditUser->find($this->user_id)->getData();
        $this->first_name=$user->first_name;
        $this->last_name=$user->last_name;
        return view('livewire.user-admin-edit',['user'=> $user]);
    }

    public function mount($id)
    {
       $this->user_id = $id;
    }
````

blade view code

````
<h4 class="mb-3">Edit User</h4>
    <form wire:submit.prevent="submit" class="needs-validation">
..
..

 <div class="col-2">

                    <label for="first_name" class="required">First name</label>
                </div>
                <div class="col-3">

                    <input wire:model="first_name" type="text" class="form-control" id="first_name" placeholder="Enter First Name" required>
                </div>
````
and so on with the form inputs 
whatever I change in any field I the form will submit grab the data from the database and re populate the fields with the old data `we're talking less than 2 seconds`

**Comment by calebporzio** [comment]
You’ll need to post stripped down code for reproduction. Otherwise, can’t help

**Comment by asb6339** [comment]
I've added some of the code 
thanks

**Comment by asb6339** [comment]
Thanks for your attention Caleb 
It turned out I just wanted to complain a little bit so I can find out whats wrong with my code.

All:
don't fetch the database in the render function this drove me crazy the form was getting reset the the old value every time .

in my case I'm contacting the database from the  mount() 
don't send anything in the return here that might cause the reset as well and that was my fault I
`return view('livewire.user-admin-edit',['user'=> $user]);` 
this line should be 
`return view('livewire.user-admin-edit');`
I hope this helps someone out there facing this issue 

Thanks again Caleb
