### ISSUE TITLE
Scoped latest relation is not being persisted between requests

### ISSUE THREAD

**Issue by iainco** [livewire/livewire#1272]
### Description
I'm using an `updated` hook to fetch an Eloquent model - when the user types in an autocomplete field the relevant model is fetched.

When fetching the model I'm using a scope function to pull the single most recent related model (using the dynamic relationship solution as documented here https://reinink.ca/articles/dynamic-relationships-in-laravel-using-subqueries).

This all works fine but for some reason the single most recent related model does not seem to persist between Livewire requests, the main Eloquent model does but the `lastEvent` dynamic relation is `null`.

This does not happen when calling "with()" in the updated function, the related model is persisted just fine.

So 

```
  public function updatedToVehicle()
  {
        $this->to =  Vehicle::withLastEvent()
                             ->with('site')
                             ->area($this->area()->id)
                             ->first();
   }
```

When I hit submit on the form  and check for `$this->to->lastEvent` in the Livewire submit handler, `lastEvent` is null, however, $this->to->site is correctly persisted and is an Eloquent model.

```
   public $to;
   public function submit()
   {
        //$this->to->lastEvent === null

        //$this->to->site !== null
   }
```

The scope function:

```
    public function scopeWithLastEvent($query)
    {
        $query
            ->addSelect(['last_event_id' => 
                Event::select('id')
                    ->whereColumn('vehicle_id', 'vehicles.id')
                    ->orderBy('date', 'desc')
                    ->orderBy('created_at', 'desc')
                    ->take(1)])
            ->with('lastEvent');
    }
```

Does anyone have any ideas or have come across this before?

Happy to provide a working repo to demonstrate this issue if it would be useful.

Many thanks.

**Context**
- Laravel version: 7.16.1
- Livewire version: ^1.0 (how do I find out the specific Livewire version?)
- Browser: Chrome

**Comment by almeidafranci** [comment]
I just faced the same issue using the technique suggested by Reinink. Any word on this?

**Comment by zepfietje** [comment]
@iainco, this is not a Livewire bug, as relations will have to be loaded on every Livewire request.
So you should just load your additional relations in e.g. the render method.

**Comment by zepfietje** [comment]
@nuernbergerA, this issue can probably be closed.

**Comment by austenc** [comment]
@zepfietje is correct, this can be closed. 

This is the same behavior as Laravel exhibits with passing models (with relations) to queued jobs. When the public property is a model instance, it only serializes (and restores) the model identifier, not the entire model.   

In fact, Livewire even uses the trait from Laravel's Queue stuff to accomplish this! See here:
https://github.com/livewire/livewire/blob/master/src/HydrationMiddleware/HydratePublicProperties.php#L18

**Comment by calebporzio** [comment]
Yeah, like others have said, this isn't currently supported behavior.

Because Livewire uses the same model serialization system as Laravel queued jobs, we are bound (currently) to the same constraints.

The current system should persist loaded relationships and connection settings, but not a custom ->select type thing.

Anyhow, I'd be open to a PR if it were simple enough to support.

Closing this for now.

Thanks!
