### ISSUE TITLE
File input uploads file twice after changing file when not at root element

### ISSUE THREAD

**Issue by philipnewcomer** [livewire/livewire#1273]
When a file input is not at the root of the form, but nested inside another element like a div, and a file is chosen, and then another file is chosen to replace the first, the second file (which should replace the first) is uploaded twice. However, this behavior only occurs when the file input element is not at the root of the form, i.e. nested inside a div.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithFileUploads;

class FileUpload extends Component
{
	use WithFileUploads;

	public $upload;

	public function render()
	{
		return view('livewire.file-upload');
	}
}
```

```html
<form>
	<!-- without this div, the issue does not occur. -->
	<div>
		<input type="file" id="upload" wire:model="upload">
	</div>
</form>

```

### Steps to reproduce

1. Load page
2. Click "Choose File" button and choose a file.
3. Note in the network panel that `livewire/upload-file` is called once.
    <img width="435" alt="Screen Shot 2020-07-14 at 1 02 12 PM" src="https://user-images.githubusercontent.com/1446874/87454854-901f5d00-c5d2-11ea-8769-299413286ffc.png">
4. Click "Choose File" and choose a new file.
5. Note in the network panel that `livewire/upload-file` is called two more times, for a total of three, although a file was only chosen twice.
    <img width="404" alt="Screen Shot 2020-07-14 at 1 03 26 PM" src="https://user-images.githubusercontent.com/1446874/87454873-94e41100-c5d2-11ea-9c09-15ca3cc64afc.png">

This behavior only occurs when the file input element is NOT at the root of the form, i.e. this works fine:
```html
<form>
    <input type="file" id="upload" wire:model="upload">
</form>
```

**Context**
- Livewire version: 1.3.1
- Laravel version: 7.13.0
- Browser: Chrome 83.0.4103.116

**Comment by martin-ro** [comment]
Experiencing the same behavior.

**Comment by philipnewcomer** [comment]
FWIW, this is still an issue in Livewire v2 (currently using 2.2.9).

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by philipnewcomer** [comment]
REOPEN

**Comment by ahmic** [comment]
@philipnewcomer 

Add `wire:key="foo"` to parent div

```
<form>
	<div wire:key="foo">
		<input type="file" id="upload" wire:model="upload">
	</div>
</form>
```

**Comment by philipnewcomer** [comment]
@ahmic I appreciate the suggestion. However, for whatever reason that doesn't seem to be working for me.

**Comment by SomePlayer** [comment]
I had the same issue. Turned out that the upload button and added image from the upload, had a parent DIV in common. This must have caused the click to be fired several times.

So it does not need to be root element, but must not share an element with anything that changes due to the action of the button

**Comment by austenc** [comment]
@philipnewcomer can you provide an example repo for this and reopen it at that time? This seems like a morphdom issue. 

Appreciate the concise code snippets, but in this case seeing more "real" context from your side will be really helpful to investigate and squash this bug. Thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Enaah** [comment]
Sorry for commenting on a closed Issue, but has anyone solved this (maybe @austenc)?  
I still have this problem, even when I use the structure described here:

**Comment by joydeep-bhowmik** [comment]
This is still an issue in livewire 3

**Comment by naseerr** [comment]
Indeed still its an issue in Livewire v3. But there is a workaround on this issue just include `wire:click.prevent` on the element and it will be fixed.
