### ISSUE TITLE
Livewire won't load when using bepsvpt/secure-headers

### ISSUE THREAD

**Issue by HDVinnie** [livewire/livewire#1279]
### Description
When using https://github.com/bepsvpt/secure-headers package to handle CSP Livewire js fail to load.. Now I know nonce support was added but when I do `@livewireScripts(['nonce' => '{{ Bepsvpt\SecureHeaders\SecureHeaders::nonce() }}'])` if fails to render `{{ Bepsvpt\SecureHeaders\SecureHeaders::nonce() }}` and instead just does an echo of it.

Furthermore its not even adding the nonce to the Livewire.js.

[![Screen-Shot-2020-07-15-at-9-37-59-PM.png](https://i.postimg.cc/gkTNm8n3/Screen-Shot-2020-07-15-at-9-37-59-PM.png)](https://postimg.cc/rK5S9dGp)

### Steps to reproduce
Install fresh Laravel app. Install Livewire. All works. Install https://github.com/bepsvpt/secure-headers. 

**Context**
- Livewire version: `1.3.1`
- Laravel version: `6.18.4`
- Browser: Safari `12.1.2`

**Comment by ryangjchandler** [comment]
You're passing the nonce through incorrectly. You instead need to just call the method without the Blade echo tags. 

`@livewireScripts(['nonce' => Bepsvpt\SecureHeaders\SecureHeaders::nonce()])`

**Comment by HDVinnie** [comment]
Thanks @ryangjchandler
