### ISSUE TITLE
File is not an instance of TemporaryUploadedFile, when there are validation errors

### ISSUE THREAD

**Issue by jyrkidn** [livewire/livewire#1280]
### Description

If there are validation errors, the uploaded file is not serialized properly and the file variable will be a `livewire-file:...` string.
This only happens when there live validation via the `updated` method.

### Steps to reproduce

Check this snippet: https://laravelplayground.com/#/snippets/ea6a9fc5-1b36-4de5-9658-30e217dcea4a

1. Check the checkbox
1. Upload a file
1. Uncheck the checkbox

The dump will now not be an instance of `TemporaryUploadedFile`, but just a string.

**Context**
- Livewire version: 1.3.1
- Laravel version: 7.19.1 (but also on 6.18.25)
- Browser: Firefox, Chrome

My colleague also started a [discussion](https://github.com/livewire/livewire/discussions/1271) about this, but since I can reproduce it on Laravel Playoground, opening an issue seemed correct.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
