### ISSUE TITLE
Conditional content breaks alpine

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1284]
If you have nested Alpine components, that declares the same property - they break when Livewire updates conditional content.

```html
<div x-data="{ modal: false }">
    //livewire form with radio group
    <div x-data="{ modal: false }">
        //button show modal
       <div>
           @if($radioGroup === 'value1')
              //content
           @endif
           @if($radioGroup === 'value2')
              //content
           @endif
           //button close modal
       </div>
    </div>
</div>
```

This is my first time using laravel playground, I hope this link works:
[https://laravelplayground.com/#/snippets/ba0c171b-a395-47fb-9c04-1bde97580e82](https://laravelplayground.com/#/snippets/ba0c171b-a395-47fb-9c04-1bde97580e82)

**Thoughts** (livewire-component.blade)

1. x-data="{ modal: false }" is declared twice.
- First on the root div, and then on the modal div
- But, should it not be allowed to declare the same prop twice? (Like if there are nested modals on the page?)
- removing the declaration on the root div solves the issue

2. It has something to do with the if statements in the modals content
- Replacing all the if statements with a simple p tag also removes the error

**Update**
I removed the `x-data="{ modal: false }"` (on the root div) in my live project, but the problem still occurs sometimes, cannot figure out why. It has something to do with conditional display of data.
Have an input that is conditionally shown based on the value of the radio group.
```
@if($role == 'organizer')
    <input type="text" wire:model="team_name" />
@endif
``` 
If I remove this condition the modal works...

So, there is something fishy with the conditional display in combination with Alpine.

**Comment by tanthammar** [comment]
While waiting for a solution, I had to add this to the page, not nice, but it works...
```js
<script>
    window.livewire.hook('afterDomUpdate',  () => {
        document.querySelectorAll("[x-data]").forEach(function (el) {
            Alpine.initializeComponent(el);
        });
    });
</script>
```

**Comment by lukeraymonddowning** [comment]
We've experienced this too, or at least very similar. We're going to create a separate bug report as its not related to the same key on Alpine, but the results are the same.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
