### ISSUE TITLE
Can't use Livewire routes with new blade components

### ISSUE THREAD

**Issue by edalzell** [livewire/livewire#1285]
### Description

As per the [docs](https://laravel-livewire.com/docs/rendering-components#route-registration), I'd like to use Livewire routes. However they don't seem to work when the livewire component uses the new Blade components, I get a "can't find layouts.app" error.

### Steps to reproduce

Livewire component, /project/index.blade.php:
```
<x-layouts.app>
    <div class="px-4 mx-auto max-w-7xl sm:px-6 md:px-8">
        <h1 class="text-2xl font-semibold text-gray-900">Projects</h1>
    </div>

    <div class="px-4 mx-auto max-w-7xl sm:px-6 md:px-8">
        <div class="py-4">
            <div class="border-4 border-gray-200 border-dashed rounded-lg h-96">
                @foreach ($projects as $project)
                    <p>{{ $project->title }}</p>
                @endforeach
            </div>
        </div>
    </div>
</x-layouts.app>
```

`web.php`:
```
Route::livewire('/projects', 'project.index');

**Context**
- Livewire version: 1.3.1
- Laravel version: 7.19

**Comment by ryangjchandler** [comment]
The `Route::livewire()` method automatically tries to extend from a `layouts.app` file but there's no way to disable that yet. I like using the component layout stuff too, so I normally just use `Route::view()` instead.

**Comment by edalzell** [comment]
@ryangjchandler how does the route/model binding work then? Do you have an example?

**Comment by iAmKevinMcKee** [comment]
I don’t see where you are trying to pass a model ID. You can’t do route model binding without passing an ID. 

Maybe I’m not fully understanding what you are trying to do.

**Comment by edalzell** [comment]
Out of scope of this issue, sorry @iAmKevinMcKee, my fault.

**Comment by iAmKevinMcKee** [comment]
If I am understanding the original issue correctly, then you are correct in that you cannot use a L7 blade template (at least according to the [Route Registration docs](https://laravel-livewire.com/docs/rendering-components#route-registration)). You would have to use the old fashioned `@extends`. I imagine there's a way to use a blade component here but would probably need to be a PR.

**Comment by ryangjchandler** [comment]
@iAmKevinMcKee at a minimum, I think you should be able to pass `false` to the `->layout()` method so that no layout is enforced.

**Comment by edalzell** [comment]
I might PR this once I understand Livewire a bit more.

**Comment by jimpeters** [comment]
@edalzell Livewire v2 has all sorts of component layout vs extends functionality now.  Think this issue might be able to be closed?

**Comment by edalzell** [comment]
I won't have time to check this, I'll close this now and re-open if/when I'm able to review.
