### ISSUE TITLE
Turbolinks back/next page button error Cannot read property 'data' of null livewire

### ISSUE THREAD

**Issue by hortigado** [livewire/livewire#1287]
### Description
When i back to a page with livewire using turbolinks the component livewire no work, only work when open the page with turbolinks but when i open with back o next button not work livewire.
**In console:**
 **Uncaught TypeError: Cannot read property 'data' of null**              livewire.js?id=8dc19763a68e39a1b862:1
    at new Component (livewire.js?id=8dc19763a68e39a1b862:1)
    at livewire.js?id=8dc19763a68e39a1b862:1
    at livewire.js?id=8dc19763a68e39a1b862:1
    at walk (livewire.js?id=8dc19763a68e39a1b862:1)
    at walk (livewire.js?id=8dc19763a68e39a1b862:1)
    at walk (livewire.js?id=8dc19763a68e39a1b862:1)
    at walk (livewire.js?id=8dc19763a68e39a1b862:1)
    at Component.value (livewire.js?id=8dc19763a68e39a1b862:1)
    at Component.value (livewire.js?id=8dc19763a68e39a1b862:1)
    at new Component (livewire.js?id=8dc19763a68e39a1b862:1)

**Comment by tanthammar** [comment]
At the moment you have to add a fix to your LivewireManager, until @calebporzio  implements it.
#1005 

vendor/livewire/livewire/src/LivewireManager.php row 265, wrap const dataObject with an if(component) {} statement.

**Comment by hortigado** [comment]
hello i am the author of that solution but now i have a new problem. I don't know if it's because of the new livewire 1.3.1 update. **Cannot read property 'data' of null** before was **Cannot read property 'data' of undifined** and that if fixed with **if(component)** but this still cannot solve

**Comment by hortigado** [comment]
I just modified the Livewire Manager file again and i finally fix the problem from the back and next button of navigation :)

**Comment by tanthammar** [comment]
@hortigado what did you change this time?
