### ISSUE TITLE
Bad event linking when a component is refreshed

### ISSUE THREAD

**Issue by XaBerr** [livewire/livewire#1290]
### Description
I have a table with multiple rows. For each row I have a delete button. The delete button call a modal (**showModalDelete**) using alpinejs that it ask the delete confirmation passing as parameter **killRowId**. When I click the confirm button I use alpinejs to call a livewire function. The event works, the api request starts and the php-delete-function is invoked and the db-row is deleted. The table is reloaded automatically and I can see that the row is deleted graphically.
When the table is reloaded, all the events are shifted!
For example:
id=1 --> event of id=2
id=2 --> event of id=3
id=3 --> event of id=4
In other word, when I click **x-on:click="killRowId =1;** I read in console **2**.
Here is my code, I hope is enough for repeat the problem.

**Table**
```html
<tbody class="bg-white rounded-lg shadow-lg">
	@foreach ($ambiti as $ambito)
	<tr class="hover:bg-blue-100 text-center">
		@foreach ($titles as $title)
			<td class="border px-4 py-2">{{$ambito[$title]}} {{$ambito["pk_ambito"]}}</td>
		@endforeach
		<td class="border px-4 py-2 text-center">
			<button x-on:click="showModalModify = true" class="bg-yellow-200 hover:bg-yellow-300 text-yellow-700 font-bold py-1 px-1 rounded">
				modify
			</button>
			<button x-on:click="killRowId = {{$ambito["pk_ambito"]}}; console.log(killRowId); showModalDelete = true;" class="bg-red-200 hover:bg-red-300 text-red-700 font-bold py-1 px-1 rounded">
				delete
			</button>
		</td>
	</tr>
	@endforeach
</tbody>
```

**Modal button**
```html
<button x-on:click="console.log(killRowId); @this.call('deleteRow', killRowId); showModalDelete = false;" type="button" >
  delete
 </button>
```

### Steps to reproduce

**Context**
- Livewire version: [1.3.0]
- Laravel version: [7.0.0]
- Browser: Chrome

**Comment by jskorlol** [comment]
Perhaps
https://github.com/livewire/livewire/issues/763#issuecomment-659872849
Is it the same or not?

**Comment by XaBerr** [comment]
> Perhaps
> 
> https://github.com/livewire/livewire/issues/763#issuecomment-659872849
> 
> Is it the same or not?

I think yes, they are really similar, probably the cause is the same 🤔

**Comment by jskorlol** [comment]
> > Perhaps
> > [#763 (comment)](https://github.com/livewire/livewire/issues/763#issuecomment-659872849)
> > Is it the same or not?
> 
> I think yes, they are really similar, probably the cause is the same 🤔

If you click @click instead of x-on, an error will occur.
``
morphAttrs.js:37 Uncaught (in promise) DOMException: Failed to execute'setAttribute' on'Element':'@click' is not a valid attribute name.
``
Strangely, it seems to happen when you put the value used in foreach in the x-on:click event or @click event...

**Comment by XaBerr** [comment]
I’ve tried now, I have the same error if I put @click

**Comment by DanHarrin** [comment]
Cool, I'm gonna close in favor of that issue. Many thanks!
