### ISSUE TITLE
Data pushed to collection gets modified 

### ISSUE THREAD

**Issue by Abdulaziz-almoshen** [livewire/livewire#1292]
### Description
The idea is a simple chat ( user enters a body of text and click send then the message will be at the bottom of the chat)

So far everything works fine till I hit the click send button.

Here is the picture before I click on send enter image description here
https://i.stack.imgur.com/50kvt.png
and here is what happens after I click send
https://i.stack.imgur.com/X0KMU.png

I feel like the issue is in this part of code where I send the message to the live-wire blade

```

  @foreach ($messages as $message)
            @if($message->isYou())
                <livewire:conversations.conversation-message-own :message="$message" :key="$message->id" />
            @else
                <livewire:conversations.conversation-message :message="$message" :key="$message->id" />
            @endif
        @endforeach
```
here is the component

```

public $body= "";
public $conversation;

public function mount(Conversation $conversation)
{
    $this->conversation = $conversation;
}

public function reply()
{
    $this->validate([
        'body' => 'required',
    ]);
    $message = $this->conversation->messages()->create([
        'user_id' => user()->id,
        'body' => $this->body,
    ]);
    $this->emit('message.created',$message->id);
    $this->body = "";
}
public function render()
{
    return view('livewire.conversations.conversation-reply');
}
}

```
last is listening to the event component:

```

 class ConversationMessages extends Component
{

public $messages;

public function mount(Collection $messages)
{
    $this->messages = $messages;
}

public function render()
{
    return view('livewire.conversations.conversation-messages');
}
protected function getListeners()
{
    return [
    'message.created' => 'prependMessage',
    ];
}

public function prependMessage($id)
{
    $this->messages->prepend(Message::find($id));
}
} 
```
the issue in the inspect log is
```

Uncaught (in promise) TypeError: Cannot read property 'data' of null but I think it's not related to the chats data!
Thanks in advance
```

**Context**
- Livewire version: [ 1.0.0]
- Laravel version: [7.0.0]
- Browser: [Chrome]

**Comment by zepfietje** [comment]
@Abdulaziz-almoshen, your code seems invalid for Livewire v1.
Try collections in v2 and reopen this issue if you experience any problems.

**Comment by zepfietje** [comment]
@nuernbergerA, could you close this issue?

**Comment by calebporzio** [comment]
@zepfietje, in what way is this code invalid?

**Comment by zepfietje** [comment]
@calebporzio, I thought `$messages` was a regular collection.
However, now I see it's probably an Eloquent collection.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
