### ISSUE TITLE
Unable to upload with livewire and stancl tenancy package

### ISSUE THREAD

**Issue by t-prod** [livewire/livewire#1296]
Hi,

### Description

Just handling multiples files as the docs described it : https://laravel-livewire.com/docs/file-uploads#multiple-files
I'm using Stancl Tenancy package and I think there's a conflict when trying to upload in local.

`file_put_contents(C:\Users\titin\Documents\laragon\www\saas\storage/tenant2afa6d6d-562b-4b4a-b2b4-292f77bdd8ee\framework/cache/facade-c2f53e2d655810ac111b48d42b34b209861bb985.php): failed to open stream: No such file or directory`

The file where the problem is vendor\livewire\livewire\src\WithFileUploads.php
and this function GenerateSignedUploadUrl::forLocal()

`$this->emitSelf('upload:generatedSignedUrl', $name, GenerateSignedUploadUrl::forLocal()); //<-- here`
If you see the error screenshot I think there's tenant id injection here but I don't know how can I make it work ;)

![image](https://user-images.githubusercontent.com/1824638/87907547-220ce700-ca65-11ea-966a-c5b8edb6a4b5.png)

Any ideas ?

**Comment by ClausMunch** [comment]
You need to create the folders yourself when creating the tenant. It has nothing to do with Livewire.
If you use S3 compatible storage on the other hand, Livewire doesn't work (Only with Amazon S3 storage).

**Comment by stancl** [comment]
See the package docs: https://tenancyforlaravel.com/docs/v3/realtime-facades/#real-time-facades

cc @DanHarrin (yes, tenancy & file uploads work 👌 now)

**Comment by DanHarrin** [comment]
Thank you @stancl!
