### ISSUE TITLE
Using @this with Alpine inside a child component throws an error

### ISSUE THREAD

**Issue by lukeraymonddowning** [livewire/livewire#1300]
### Description
When using child components that make use of the `@this` directive in an Alpine `x-data` or `x-init` declaration inside a conditional, a JS error is thrown:  

```
undefined is not an object (evaluating 'window.livewire.find('pGufnNp9jJXJq1ZFI9p8').get') 
```

I've been burned by this a couple of times now, but can't for the life of me work out why. I've tried all sorts of workarounds but to no avail.

### Steps to reproduce

https://laravelplayground.com/#/snippets/50f13e9d-e414-46cb-a72a-2ac5ddc08dcf

- Open up the inspector on the console tab
- Select an option from the dropdown

**Context**
- Livewire version: [e.g. 1.3.1]
- Laravel version: [e.g. 7.19.0]
- Browser: Edge, Firefox, Safari, Chrome

**Comment by nedwors** [comment]
Here's an additional playground for this issue:
https://laravelplayground.com/#/snippets/b7b216f5-bd77-4e73-bf32-09362540f7d0

The  `non-working-parent-livewire-component` has an `x-data` declared and throws the issue.
The `working-parent-livewire-component` doesn't have an `x-data` declared and `@this` works fine.

**Comment by slaFFik** [comment]
I suspect that id of the livewire component generated by `@this` directive is not correct.
`@this` is actually replaced with `window.livewire.find('ID')`, and that `ID` for some reason is incorrect.

**Comment by lukeraymonddowning** [comment]
So, here is a workaround for this (although it would be nice to not have to workaround).

I created a little `component` function that you can pass an DOM node to, and it returns the nearest Livewire component instance by looking up the `wire:id` attribute.

```javascript
window.component = function(element) {
    let componentId = null;

    while(!componentId) {
        element = element.parentElement
        componentId = element.getAttribute('wire:id')
    }

    return window.livewire.find(componentId);
}
```

Mix that with the `afterDomUpdate` hook so that the component can be updated when a new ID is assigned to the child component, and you have yourself some working code.

```javascript
// Before
@this.on('saved', e => {
        showSavedNotification = true
        setTimeout(() => showSavedNotification = false, 2000)
})

// After
window.livewire.hook('afterDomUpdate', () => {
    component($el).on('saved', e => {
        showSavedNotification = true
        setTimeout(() => showSavedNotification = false, 2000)
    })
})
```

**Comment by lukeraymonddowning** [comment]
Also, found another interesting quirk whilst creating this workaround which is that DOMstrings don't like the `:` character in `wire:id`. Hence the workaround using `parentElement` instead of `$el.closest(['wire:id'])`.

**Comment by jimpeters** [comment]
I ran into what I believe is the same issue today and it drove me nuts.  Here is what it took for me to solve my issue.  This may not be at ALL what you are experiencing but I thought I'd try to help.

If this is your problem I recommend renaming this issue to the Javascript error you received. "Cannot read property $wire of undefined using entangle".  I think this may help many a lost person.

TLDR - Make sure you include @livewireScripts BEFORE you include your app.js bundle containing alpinejs or alpine script tag that contains AlpineJS in your layout template/component.

When you include @livewireScripts in your application layout part of src/LivewireManager.php defines the following method on the browser window.

```php
    /* Make Alpine wait until Livewire is finished rendering to do its thing. */
    window.deferLoadingAlpine = function (callback) {
        window.addEventListener('livewire:load', function () {
            callback();
        });
    };
```

When Alpine is included it calls the following in src/index.js

```javascript
window.Alpine = Alpine

    if (window.deferLoadingAlpine) {
        window.deferLoadingAlpine(function () {
            window.Alpine.start()
        })
   } else {
        window.Alpine.start()
   }
```

This prevents Alpine initializing elements with x-data attributes BEFORE Livewire has completed initializing it's components.

This means if you include Alpine BEFORE Livewire in your script tags Alpine will be trying to call window.Livewire.find(), etc. to "entangle" properties before Livewire knows anything about the component causing an exception when Livewire is asked by Alpine to entangle the variables.

AlpineJS documentation states you should place Alpine in your head tag.  My Laravel practice is to place my app.js bundle at the bottom of the body tag and I just happened to place it BEFORE @livewireScripts not knowing.  This causes crazy issues like this.

I believe the Livewire documentation in the AlpineJS integration page should be updated to prominently highlight to IGNORE the AlpineJS documentation and move your Alpine include after @livewireScripts in your layout to prevent issues like this.  Obviously someone just wanting to use AlpineJS doesn't want to hear about Livewire on the Alpine documentation so I'm not sure anything could be added there except "include it in the head tag except when using 3rd party Libraries that integrate with AlpineJS such as Livewire.".

**Comment by austenc** [comment]
@lukeraymonddowning is this still an issue for you? 

If so, which versions of Livewire and Alpine are you using now?

**Comment by lukeraymonddowning** [comment]
> @lukeraymonddowning is this still an issue for you?
> 
> If so, which versions of Livewire and Alpine are you using now?

@austenc it seems to have been resolved in Livewire v2.
