### ISSUE TITLE
Jquery owl carousel slider not working after the defer loading.

### ISSUE THREAD

**Issue by mhmiton** [livewire/livewire#1301]
Jquery owl carousel slider not working after the defer loading. How can I fix this problem? I'm using the livewire 1.3.

**Comment by nuernbergerA** [comment]
@mhmiton please provide a simplified version (that we can copy&paste) to reproduce your issue

If you want to make our lives easier use https://laravelplayground.com/ to share your example code

**Comment by redbastie** [comment]
Add an event listener which re-initializes the carousel after livewire loads:

```
document.addEventListener('livewire:load', function () {
    window.livewire.hook('afterDomUpdate', () => {
        // owl carousel init code here
    });
});
```

**Comment by mhmiton** [comment]
@redbastie Thank you so much. It's working for me.
