### ISSUE TITLE
Stop Model Refreshing On Hydrate

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#1307]
### Description
I am making changes to my model in the mount method, but when the component hydrates it seems to get refreshed and I lose all my changes. I'd like it to not refresh because the changes I am making come from a remote API so I don't want it pinging the API on every hydrate.

### Steps to reproduce
Here is a simple example ...
```php
public $site;

public function mount () {
  $this->site = Site::find(1);
  $this->site->name = 'Updated';
  // Site.domain = 'test.com'
  // Site.name = 'Updated'
}

public function hydrate () {
  dd($this->site);
  // Site.domain = 'test.com'
  // Site.name = 'test'
}
```

**Comment by dustinfabre** [comment]
#1142

**Comment by n1crack** [comment]
```php
public function mount () {
  $this->site = Site::find(1);
  $this->site->name = 'Updated';

$this->site->save();

  // Site.domain = 'test.com'
  // Site.name = 'Updated'
}
```

**Comment by calebporzio** [comment]
Thanks for submitting. This is the default behavior of Livewire V1 - in V2 - you can make changes to attributes on a model and they will persist between requests. Closing thanks!
