### ISSUE TITLE
Prefetching with an SVG icon inside a button causes multiple fetches

### ISSUE THREAD

**Issue by erikwestlund** [livewire/livewire#1313]
### Description

Prefetching with buttons containing SVGs is unreliable

### Steps to reproduce

Consider a situation where you have a button like this:

```
<button wire:click.prefetch="action">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M216 23.86c0-23.8-30.65-32.77-44.15-13.04C48 191.85 224 200 224 288c0 35.63-29.11 64.46-64.85 63.99-35.17-.45-63.15-29.77-63.15-64.94v-85.51c0-21.7-26.47-32.23-41.43-16.5C27.8 213.16 0 261.33 0 320c0 105.87 86.13 192 192 192s192-86.13 192-192c0-170.29-168-193-168-296.14z"/></svg>
</button>
```

When you hover the button, it will send a prefetch XHR request as expected. However, with SVG icons inside, when you click the button, it fetches again.

If you were to replace the above with:

```
<button wire:click.prefetch="action">
Popular
</button>
```

It works as expected.

If you hover just to the very, very edge of the button, it does not fetch twice.

I've wrapped the icon. I've done wire:ignore on the SVG tag. I've down keys on the elements. Nothing seems to solve it.

I've also done things where I drill down and put the wire:click.prefetch tag deeper into the button, like on a span, and that can obviate the problem, but that leads to other issues.

I've recorded a video reproducing the problem:

https://www.loom.com/share/271c178eaba74418904e52dc0f17881b

My instinct is that it may have to do with SVG fill but I can't nail it down to that. For example, you'll see in the video the "Popular" button has a chevron. If you delicately hover that chevron, it also does the double fetch.

**Context**
- Livewire version: v 1.3.1
- Laravel version: 7.20.0
- Browser: Chrome and Safari

**Comment by austenc** [comment]
@erikwestlund I think this is being caused by the SVG element also accepting pointer events. 

You might be able to use CSS to fix this.  `<svg style="pointer-events: none;" ...>`

If that's the case, this might not be something Livewire can (or should) fix. Let me know how it goes! ✌️

**Comment by calebporzio** [comment]
Yeah, this is a weird one. SVGs behave slightly differently than normal elements so it doesn't surprise me there's some unexpected behavior here.

I'm going to leave this open for now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
