### ISSUE TITLE
Wire:model not working on third party range slider

### ISSUE THREAD

**Issue by vivekraj** [livewire/livewire#1314]
I'm trying to use Ion.Rangeslider. wire:model has no effect and wire:model.lazy doesn't suit my purpose. The range slider has onChange function. Is there any way to emit the wire:model through onChange function?

HTML

```
<input type="text" 
data-type="double" 
data-grid = true 
data-min = "1970" 
data-max = "2020"
data-from = "1970"
data-to = "2020"
wire:model="requested_year_range" 
id="year-range" 
name="year_range" />
```

JS

```
$("#year-range").ionRangeSlider({`                
        onChange: function (data) {
          let component = window.livewire.find('sUXgZzzoI9cNbn9rPxkP');
          //Error : Uncaught TypeError: component is undefined
          component.set('requested_year_range', data.from+'-'+data.to);
            
        }        
    });

```

**Comment by elfeffe** [comment]
You are trying to find a component by Id. Are you sure that’s the id?
Another good idea is to emit an event, and listen from the component

**Comment by vivekraj** [comment]
@elfeffe Yes I'm sure the id is correct (got it fro the inspector), but the code has no effect on the onChange method.

**Comment by elfeffe** [comment]
And if you try this part

let component = window.livewire.find('sUXgZzzoI9cNbn9rPxkP');
          //Error : Uncaught TypeError: component is undefined
          component.set('requested_year_range', data.from+'-'+data.to);


I’m the console, it works?

**Comment by vivekraj** [comment]
@elfeffe Unfortunately no! When I tried logging window.livewire, it is returning undefined

```
$("#year-range").ionRangeSlider({                
        onChange: function (data) {
          console.log(window.livewire.find('sUXgZzzoI9cNbn9rPxkP'));          
         let component = window.livewire.find('sUXgZzzoI9cNbn9rPxkP');
         component.set('requested_year_range', data.from+'-'+data.to);
        }        
    });
```
![Screenshot 2020-07-25 at 2 46 33 PM](https://user-images.githubusercontent.com/1856046/88453562-c2a84000-ce85-11ea-996c-ff04eb295806.png)

**Comment by dustinfabre** [comment]
`<div class="m-b-30" wire:ignore x-data x-init="
    $('#rangeslider').ionRangeSlider({
        skin: 'round',
        type: 'double',
        grid: true,
        min: 0,
        max: 1000,
        prefix: '$',
        onFinish: function(data) {
            @this.set('range', { 'from': data.from, 'to': data.to })
        }
    });
">
    <input type="text" id="rangeslider" />
</div>`

**Comment by dustinfabre** [comment]
ung are calling livewire functions when livewire isn't being loaded yet. try using it with alphineJS and initiate the rangeslider inside x-init

`<div class="m-b-30" wire:ignore x-data x-init="
    $('#rangeslider').ionRangeSlider({
        skin: 'round',
        type: 'double',
        grid: true,
        min: 0,
        max: 1000,
        prefix: '$',
        onFinish: function(data) {
            @this.set('range', { 'from': data.from, 'to': data.to })
        }
    });
">
    <input type="text" id="rangeslider" />
</div>`

**Comment by dustinfabre** [comment]
ung are calling livewire functions when livewire isn't being loaded yet. try using it with alphineJS and initiate the rangeslider inside x-init

```<div class="m-b-30" wire:ignore x-data x-init="
    $('#rangeslider').ionRangeSlider({
        skin: 'round',
        type: 'double',
        grid: true,
        min: 0,
        max: 1000,
        prefix: '$',
        onFinish: function(data) {
            @this.set('range', { 'from': data.from, 'to': data.to })
        }
    });
">
    <input type="text" id="rangeslider" />
</div>
```

**Comment by dustinfabre** [comment]
alternatively you can initialize the ionslider inside

```javascript
document.addEventListener('livewire:load', () => {
            
        });
```

**Comment by austenc** [comment]
You can use Alpine + Livewire and `@entangle` with v2 to bind it to the server-side.

This should solve the issue and allow you to integrate the slider.

**Comment by calebporzio** [comment]
Closing this. Thanks everyone for offering alternative solutions!

**Comment by gabrielgandolfo** [comment]
I have the same problem, how did you solve it?
