### ISSUE TITLE
can't use recaptcha in livewire 

### ISSUE THREAD

**Issue by Hesammousavi** [livewire/livewire#1315]
it's ridiculous that we can't use recaptcha or captcha in livewire easily
it's too hard to use -_-

**Comment by redbastie** [comment]
2nd search result on google: https://laracasts.com/discuss/channels/laravel/using-google-captcha-with-laravel-livewire

**Comment by Hesammousavi** [comment]
@redbasite 
yea i saw that but there is multi problems.
when you use turbolinks with livewire recaptcha v3 just work just one time.
or even you can't use recatpcha v2 as well

**Comment by DanHarrin** [comment]
Hi, please open a Discussion about this. Many thanks.

**Comment by redbastie** [comment]
Heres how I did it using recaptcha v2.

You need to `composer require google/recaptcha`.

You need to add some values to `config/services.php`:

    'recaptcha' => [
        'site_key' => 'paste your site key here',
        'secret_key' => 'paste your secret key here',
    ],

My rule:

	class ReCaptchaRule implements Rule
	{
	    public function passes($attribute, $value)
	    {
	        $recaptcha = new ReCaptcha(config('services.recaptcha.secret_key'));
	        $resp = $recaptcha->verify($value, request()->ip());

	        return $resp->isSuccess();
	    }

	    public function message()
	    {
	        return 'The reCAPTCHA response is invalid.';
	    }
	}

My component:

	class Register extends Component
	{
	    public $name, $password, $password_confirmation, $recaptcha;

	    public function render()
	    {
	        return view('auth.register');
	    }

	    public function register()
	    {
	        $validator = Validator::make(
	            [
	                'name' => $this->name,
	                'password' => $this->password,
	                'password_confirmation' => $this->password_confirmation,
	                'recaptcha' => $this->recaptcha,
	            ],
	            [
	                'name' => ['required', 'alpha_dash', 'max:25', 'unique:users'],
	                'password' => ['required', 'confirmed'],
	                'recaptcha' => ['required', new ReCaptchaRule],
	            ]
	        );

	        if ($validator->fails()) {
	            $this->setErrorBag($validator->errors());
	            $this->emit('resetReCaptcha');

	            return null;
	        }

	        $user = User::query()->create([
	            'name' => $this->name,
	            'password' => $this->password,
	        ]);

	        auth()->login($user, true);

	        return redirect()->intended(RouteServiceProvider::HOME);
	    }
	}

My view:

	@section('title', 'Register')

	<div class="row justify-content-center">
	    <div class="col-md-4">
	        <form class="card" wire:submit.prevent="register">
	            <div class="card-header">
	                Register
	            </div>
	            <div class="card-body">
	                <div class="mb-3">
	                    <label class="form-label">Name</label>
	                    <input type="text" class="form-control @error('name') is-invalid @enderror" wire:model.defer="name">
	                    @error('name')<span class="invalid-feedback">{{ $message }}</span>@enderror
	                </div>

	                <div class="mb-3">
	                    <label class="form-label">Password</label>
	                    <input type="password" class="form-control @error('password') is-invalid @enderror" wire:model.defer="password">
	                    @error('password')<span class="invalid-feedback">{{ $message }}</span>@enderror
	                </div>

	                <div class="mb-3">
	                    <label class="form-label">Confirm Password</label>
	                    <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" wire:model.defer="password_confirmation">
	                    @error('password_confirmation')<span class="invalid-feedback">{{ $message }}</span>@enderror
	                </div>

	                <div class="text-center overflow-hidden mb-3">
	                    <div class="g-recaptcha d-inline-block" data-sitekey="{{ config('services.recaptcha.site_key') }}"
	                         data-callback="reCaptchaCallback" wire:ignore></div>
	                    @error('recaptcha')<span class="invalid-feedback d-block">{{ $message }}</span>@enderror
	                </div>

	                <button type="submit" class="btn btn-primary w-100">Register</button>
	            </div>
	        </form>
	    </div>
	</div>

	@push('scripts')
	    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

	    <script>
	        function reCaptchaCallback(response) {
	            @this.set('recaptcha', response);
	        }

	        Livewire.on('resetReCaptcha', () => {
	            grecaptcha.reset();
	        });
	    </script>
	@endpush

Of course, you'll need to change your properties if you want to use `email` instead of `name` etc.

Hope this helps someone.
