### ISSUE TITLE
resetPage() not working when reset() is in the same method

### ISSUE THREAD

**Issue by ClementN** [livewire/livewire#1317]
### Description

The resetPage is not working when reset() is used in the same method (other then updating/updated)

### Steps to reproduce
```
public function customMethod($value)
{ 
  $this->resetPage();

  $this->reset();

  // code
}
```

**Context**
- Livewire version: 1.3.2
- Laravel version: 7

**Comment by austenc** [comment]
@ClementN I think this has been fixed. If this remains a problem for you, could you provide some more code from your component so we could reproduce it? 

Thank you!
