### ISSUE TITLE
mp3 upload dont't work as expected

### ISSUE THREAD

**Issue by Slowwie** [livewire/livewire#1332]
### Description
On $audiofile->temporaryUrl() I get the error: "This driver does not support creating temporary URLs".

### Steps to reproduce
Upload an audio (mp3) file and try to generate temp url.

### Solution
I digged in. In src/TemporaryUploadedFile.php on line 69 u have to add mpga to the list of $supportedPreviewTypes. 
For me I fixed it this way - but hopefully u will add this also - so I can update livewire without loosing the ability to preview my mp3 ;). 

**Context**
- Livewire version: latest
- Laravel version: latest
- Browser: [e.g. Chrome]

**Comment by stefanriehl** [comment]
As stated in the docs:
https://laravel-livewire.com/docs/file-uploads#preview-urls

> Note: for security reasons, temporary urls are only supported for **image uploads**.

**Comment by Slowwie** [comment]
Ok, than the docs are out of date. Here you can clearly see (line 69) that 'mp3', 'wav', 'm4a', 'wma' are supported. I see no reason why you shouldn't add 'mpga' there to really enable mp3 upload-previews.

**Comment by stefanriehl** [comment]
ok, I see. You're right. The mime type from mp3 audio is mpga. So you should make a PR.

**Comment by Slowwie** [comment]
I never did something like this :D. I guess, I have to create a new project on my lokal machine out of a livewire fork - and then make the change and start a PR? 

Or is there a simple easy way to get around that?

**Comment by DanHarrin** [comment]
@Slowwie you can submit small PRs like this online :)

https://github.com/livewire/livewire/edit/1.x/src/TemporaryUploadedFile.php
