### ISSUE TITLE
Undefined index 'name' when uploading files to S3

### ISSUE THREAD

**Issue by frnc96** [livewire/livewire#1339]
### Description
When uploading an image to Digital Ocean Spaces using S3 driver the name of the file is required:
![image](https://user-images.githubusercontent.com/40387295/88803292-88ec7780-d1ac-11ea-9d39-02b0342bcfa5.png)
When debugging the request it seems that the name is not provided in the $fileInfo array:
![image](https://user-images.githubusercontent.com/40387295/88803542-e54f9700-d1ac-11ea-8db9-89373ca99fbb.png)

### Steps to reproduce
Laravel v7 or above.
Livewire v1.3.2 (in v1.2.0 that method did not recognize the S3 driver for some reason).
Digital Ocean Spaces set up.
Upload image in storage using the WithFileUploads trait.

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.22.4
- Browser: [e.g. Chrome]

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
