### ISSUE TITLE
Disk [tmp-for-tests] does not have a configured driver.

### ISSUE THREAD

**Issue by MarcelWeidum** [livewire/livewire#1341]
### Description
I have the `temporary_file_upload` => `disk` specified. But I still get the error with uploading:

`Disk [tmp-for-tests] does not have a configured driver.`.

### Steps to reproduce

**Context**
- Livewire version: [e.g. 1.3.0]
- Laravel version: [e.g. 7.22.4]
- Browser: x (server side)

**Comment by axit-joost** [comment]
I had this same thing when deploying an app to a Windows server. I ended up defining the following as a workaround:

In `config/filesystems.php`:
```php
// below disks => local

        'tmp-for-tests' => [
            'driver' => 'local',
            'root' => storage_path('app/livewire-tmp'),
        ],
```

After which the file upload problems disappeared.

**Comment by MarcelWeidum** [comment]
@axit-joost this is working for me

**Comment by andreich1980** [comment]
@axit-joost I guess it would be `storage_path('app')`, `livewire-tmp` comes from `config/livewire.php` option `temporary_file_upload.directory`

**Comment by vitoo** [comment]
Another workaround is to add this in your test : 

`Storage::fake('tmp-for-tests');`
