### ISSUE TITLE
DOM updates can erroneously drop nodes

### ISSUE THREAD

**Issue by mpbarlow** [livewire/livewire#1344]
### Description

When identical DOM nodes are separated by a text node, the next update can cause the the text node to be lost.

### Steps to reproduce

- Set up a Livewire component that receives a standard Eloquent paginator. The component doesn't need to display the records, but there does need to be enough records (or few enough records per page) for pagination to kick in.

- Use the following minimum reproducible view for your pagination:

```
@if ($paginator->hasPages())
  <span>{{ $paginator->firstItem() }}</span>
  to
  <span>{{ $paginator->lastItem() }}</span>
  of
  <span>{{ $paginator->total() }}</span>

  @foreach ($elements as $element)
    @foreach ((array)$element as $page => $url)
      <button wire:click="gotoPage({{ $page }})" type="button">{{ $page }}</button>
    @endforeach
  @endforeach
@endif
```

The important thing to note here is that `$paginator->lastItem()` and `$paginator->total()` are both in the same node type, separated by text.

- Navigate to the last page of results. If we have 10 records at 5 per page, it should display "6 to 10 of 10". Note that the values I highlighted earlier are now identical, i.e. `<span>10</span>`

- Navigate back to the previous page. You will see that the text node has been dropped, and the pagination now displays "1 to 510".

This is an easy enough bug to work around (you can just wrap the text node in a span), but obviously this has the potential to cause weird visual bugs in some circumstances.

I have not had a proper chance to look through the source, but it looks like [this modification to morphdom](https://github.com/livewire/livewire/blob/1.x/js/dom/morphdom/morphdom.js#L317) could be the culprit?

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.22.4
- Browser: all

**Comment by calebporzio** [comment]
Thanks for reporting this issue.

Unfortunately, due to inactivity and the lack of reproducible code (you provided the HTML, but nothing else. It's difficult to get this working if I don't know what the "$elements" variable is that is supplied to the view) I'm closing this.

If you want to re-submit, please do, just provide a complete copy-pastable code example.

Thanks!
