### ISSUE TITLE
@this does not pass through blade components in attribute bag

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#1346]
To re-open issue https://github.com/livewire/livewire/issues/911, @this is such a useful feature but it cannot be used with blade components when trying to pass it through within the attribute bag.

An example, take a re-usable modal component where we want to detect when the modal has been closed in alpine and send the event back to livewire.

```html
<!-- components.modal.blade.php -->
<div x-data="{showing = true}" {{ $attributes }}>
    <button x-on:click="showing=false;$dispatch('modal-closed')">Close</button>
    {{ $slot }}
</div>
```

**What we really want**
Add the listener inside or outside of the parent tag.
```html
<x-modal x-on:modal-closed="@this.call('resetItems')">
   <!-- modal content -->
</x-modal>
```

**Workaround 1**
Add the listener inside or outside of the parent tag.
```html
<x-modal>
   <div x-on:modal-closed.window="@this.call('resetItems')"></div>
   <!-- modal content -->
</x-modal>
```

**Workaround 2**
Use livewire emit
```html
<x-modal x-on:modal-closed="window.livewire.emit('resetItems')">
   <!-- modal content -->
</x-modal>
```

**Workaround 3**
Wrap the modal and catch the bubbling event
```html
<div x-data x-on:modal-closed="@this.call('resetItems')">
   <x-modal>
      <!-- modal content -->
   </x-modal>
</div>
```

The workarounds either add extra steps, or do not give the desired result.

**Comment by austenc** [comment]
This probably isn't a Livewire bug, but comes down to how Laravel itself parses the blade components

**Comment by calebporzio** [comment]
Yes, like @austenc said, this is a limitation of Laravel itself, not Livewire. Closing, thanks!
