### ISSUE TITLE
Livewire Checkboxes with integer values behaves strange

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1354]
### Description
If you have a group of checkboxes with initial **integer** values, it is not updated as expected.
It becomes a mixture of integers and strings.

This,
```php
$this->checkboxesInitialValue = [ 1, 2, 5 ];
$this->checkboxOptions = [ 1, 2, 3, 4, 5, 6, 7, 8 ];
```

Can onchange become (example);
```php
$this->checkboxesInitialValue = [ 1, 2, "2"];
```

## Full code example and instructions on how to reproduce in this:
[Link, Laravel Playground](https://laravelplayground.com/#/snippets/a79f70cc-0c55-4df0-944b-e7465309d52b)

**Comment by tanthammar** [comment]
Easy fix until waiting for a response is to convert your initial values to strings in the mount() method
```php
$this->checkboxesInitialValue = array_map('strval', $array_with_integers);
```

Found this related issue: #788

**Comment by tanthammar** [comment]
The behaviour comes from the strict comparison being made in `Array.includes()` where `"2" === 2` would return false.

Source code [from _"Add support for array binding with checkboxes"_ commit](https://github.com/livewire/livewire/blob/10c158cc8f8dc211a572f506ca9e4cc117d4a467/src/js/dom/dom_element.js)
```js
valueFromInput(component) {
        if (this.el.type === 'checkbox') {
            const modelName =  this.directives.get('model').value
            var modelValue = get(component.data, modelName)

            if (Array.isArray(modelValue)) {
                if (this.el.checked) {
                    modelValue = modelValue.includes(this.el.value) ? modelValue : modelValue.concat(this.el.value)
                } else {
                    modelValue = modelValue.filter(item => item !== this.el.value)
                }

                return modelValue
            }

            return this.el.checked
        }
           //...
}
```

A suggestion would be to collect the values of all checkboxes tied to the same `wire:model` just like a multiselect instead of comparing them to the existing data.

```js
valueFromInput(component) {
        if (this.el.type === 'checkbox') {
            const modelName =  this.directives.get('model').value
            var modelValue = get(component.data, modelName)

            if (Array.isArray(modelValue)) {
                    modelValue = Array.from(document.querySelectorAll(
                                  "input[type=checkbox][wire:model=${modelName}]:checked"
                    )).map(e => e.value)
                return modelValue
            }

            return this.el.checked
        }
           //...
}
```

**Comment by MattStrauss** [comment]
I wonder if the [`some` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#:~:text=The%20some()%20method%20executes,Otherwise%2C%20some()%20returns%20false%20.) would be preferable in this case as compared to the `includes` method? `some` gives you granular control of the comparison operator, so you could make it `==` as opposed to the strict `===`. Below is an example:

```
            if (Array.isArray(modelValue)) {
                if (this.el.checked) {
                    modelValue = modelValue.some(val => val == this.el.value) ? modelValue : modelValue.concat(this.el.value)
                } else {
                    modelValue = modelValue.filter(item => item !== this.el.value)
                }
```
I'm not sure if this would have adverse effects under different uses though. I'd be happy to do a PR, but I wanted to comment first to see if anyone else had further insights.

**Comment by tanthammar** [comment]
I tested your suggestion and it works very well. 
I tested both integer and string arrays, as well as mixed, without any issues.

Please make a PR.

Simple console tests:
```js
let modelValue = [1,2,3];
modelValue = modelValue.some(val => val == "3") ? modelValue : modelValue.concat("3") // (3) [1, 2, 3]
modelValue = modelValue.some(val => val == "4") ? modelValue : modelValue.concat("4") // (4) [1, 2, 3, "4"]
modelValue = modelValue.some(val => val == "1") ? modelValue : modelValue.concat("1") // (4) [1, 2, 3, "4"]

let modelValue = ["1",2,3];
modelValue = modelValue.some(val => val == 1) ? modelValue : modelValue.concat(1) // (3) ["1", 2, 3]
```

**Comment by MattStrauss** [comment]
@tanthammar 

I went to do the PR, but when I pulled down the most recent update, **it looks like the issue has already been fixed**, see this -> https://github.com/livewire/livewire/blob/97811b24aac6cf1e829f9dff7d7daac2122b81c7/js/dom/dom_element.js#L138

#### Applicable snippet from above link 
```
else if (this.el.type === 'checkbox') {
            if (Array.isArray(value)) {
                // I'm purposely not using Array.includes here because it's
                // strict, and because of Numeric/String mis-casting, I
                // want the "includes" to be "fuzzy".
                let valueFound = false
                value.forEach(val => {
                    if (val == this.el.value) {
                        valueFound = true
                    }
                })

                this.el.checked = valueFound
            } 
```

**Comment by tanthammar** [comment]
Great!!

**Comment by nuernbergerA** [comment]
@tanthammar so can we close this issue?

**Comment by tanthammar** [comment]
Yes, I answered via my phone and was unable to do it before. Thank you for your help and time.
