### ISSUE TITLE
CorruptComponentPayloadException when properties contains specific UTF-8 characters

### ISSUE THREAD

**Issue by huyby** [livewire/livewire#1356]
### Description
When component properties contains strings with specific UTF-8 characters that are "normalized" by the browser's JS engine, the checksum fails because the requests's payload will differ from the data set through the `wire:initial-data` attribute. 

We bumped into this issue when data contained an alternative character combination for the character (combination) `ë`. Apparently there's two ways of creating the character:

1. A single UTF-8 character `ë` with decimal code 235 and hex format `\u00eb` http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=235&mode=decimal
2. A combination of two characters `e`and `¨` with latter decimal code 776 and hex format `\u0308` http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=776&mode=decimal

The issue is with the second presentation, the combination of two characters. The JS engine of WebKit based browsers, JavascriptCore, will automatically "normalize" this combination into a single `\u00eb` character. Probably this happens when the `wire:initial-data` attribute is parsed, and can be simulated through Safari's Web Inspector console:

```
const test = 'e\u0308'
test.normalize('NFD').charCodeAt(0) // 101
test.normalize('NFD').charCodeAt(1) // 776
test.normalize('NFC').charCodeAt(0) // 235
```

When the parsed data is sent back to the server with the normalized character, the checksum will not match resulting in an `CorruptComponentPayloadException`.

#### Possible solution(s)?

1. We need to normalize our user input, and normalize all UTF-8 strings in our database. Probably most application are not doing this normalize step?
2. When Livewire package is creating the checksum, the normalization is done on all strings using Normalization Form C (NFC) which is default when using [PHP's Normalizer class](https://www.php.net/manual/en/class.normalizer.php)
3. ~~The Livewire JS needs to ensure normalization is consistent in all browsers when parsing the `wire:initial-data` attribute~~ Not an option, as checksum is created on back-end side. This would only emulate JavascriptCore behaviour in V8 (and maybe other) JS engine(s).

References:
https://withblue.ink/2019/03/11/why-you-need-to-normalize-unicode-strings.html
https://www.php.net/manual/en/class.normalizer.php
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

### Steps to reproduce

Create a Livewire component with a property containing `ë` which is using the UTF-8 COMBINING DIAERESIS character (copy paste from here, it's not the same as when you type the combo `e` and `¨` with a keyboard)

Add a second property to the component that will be used to trigger a request to the application.

Create a view for the component, add an `input` (text) element with `wire:model` attribute with the name of the second property as the value.

Use the component on a page in a WebKit based browser (e.g. Safari) and trigger a re-render through using the input element.

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.22.4
- Browser: all using WebKit's JavaScriptCore JS engine (Safari, Mobile Safari, Chrome on iOS, ...)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Sixfifty** [comment]
This is still an issue with Livewire on Safari.

I fixed it on my project by running the fields through `Normalizer::normalize()` before allowing it to be sent.

**Comment by danielbehrendt** [comment]
> This is still an issue with Livewire on Safari.
> 
> 
> 
> I fixed it on my project by running the fields through `Normalizer::normalize()` before allowing it to be sent.

Same problem here. Where did you run the normalize?

**Comment by joshhanley** [comment]
I believe this has been fixed in PR #4942. Can someone pull down master and test it out to see if it works? If so, it will be in the next release 🙂

**Comment by Balsakup** [comment]
@joshhanley, I have pull master and test it with Safari driver, it's works, except for string in collection or array.  
  
`Normalizer::normalize` needs to be executed recursively

**Comment by Okipa** [comment]
@joshhanley, as explained by @Balsakup above, it seems to work only for string properties.

When collection or arrays are containing such characters, it is still breaking, making Livewire currently not full compatible with Safari, which seems to be a quite important issue.

@Balsakup has created a PR putting the issue with an array in evidence here: https://github.com/livewire/livewire/pull/5379

I'm afraid executing a recursive treatment could cause performance issues, don't you think?. Any better ideas?

**Comment by joshhanley** [comment]
@Okipa hmm bugger. Yeah got to love Safari handling things differently 😕 I'm not sure what the implications are of using a recursive function. But if someone wants implement it in a PR (@Balsakup would you be willing to add it to yours?), we'd be happy to have a look at and see if there are any implications.

**Comment by Balsakup** [comment]
@joshhanley, I implement it in my PR https://github.com/livewire/livewire/pull/5379, I improve test and it's work.  
  
/cc @Okipa

**Comment by Okipa** [comment]
I think all cases are handled now 👍🏻

It should fix the Safari compatibility issue.

**Comment by joshhanley** [comment]
@Balsakup thanks for the PR! And @Okipa for the support 🙂 I will pull down and review the PR when I get the chance and then get Caleb to have a look to make sure he is happy (as it he is the one who has to approve merging of PRs).

**Comment by bjornbjorn** [comment]
Found this issue when researching a bug in our app - from what I can tell, what was merged in https://github.com/livewire/livewire/pull/5379 fixes the issue with strings, collections and arrays but not eloquent models (which is fair since that's what it says in the title).

But if you have a `public $myModel` with a `->string` on it you still have this issue in Safari with special characters.

Eloquent models will hit the QueueableEntity block which isn't normalized:

`            } else if ($value instanceof QueueableEntity) {
                static::dehydrateModel($value, $key, $response, $instance);
            } 
`

There are also other instances which might still have the issue (QueueableCollection, Wireable, Stringable) .. not sure.

(tested on 2.12.6 with EloquentModel->$string).
