### ISSUE TITLE
the page is refreshing

### ISSUE THREAD

**Issue by jihadismail8** [livewire/livewire#1360]
i am new to livewire , so am following a tutorial ,its a simple comments form  where you add comment live and with out the page refreshing the comment should appended . but what in fact is happening is that the comment is added and the page is immediately refreshes . 
here is the code of the view  :
`<div>`
`<div>`
    `<form` class="my-4 flex">
        `<input` type="text" class="w-full rounded border shadow p-2 mr-2 my-2" placeholder="What's in your mind.">
        `<div` class="py-2">
            `<button` type="submit" class="p-2 bg-blue-500 w-20 rounded shadow text-white" 
                          `wire:click="AddComment">Add</button>`
        `</div>`
    `</form>`
    `<div>`
    `@foreach($comments` as $comment)
        `<div` class="rounded border shadow p-3 my-2">
            `<div` class="flex justify-between my-2">
                `<div` class="flex">
                    `<p` class="font-bold text-lg">{{$comment['creator']}}</p>
                    `<p` class="mx-3 py-1 text-xs text-gray-500 font-semibold">{{$comment['created_at']}}
                    `</p>`
                `</div>`
                `<iclass="fas` fa-times text-red-200 hover:text-red-600 cursor-pointer"></i>
            `</div>`
            `<p` class="text-gray-800">{{$comment['body']}}</p>

        `</div>`
    `@endforeach`
    `</div>`
`</div><div>`
    `<form` class="my-4 flex">
        `<input` type="text" class="w-full rounded border shadow p-2 mr-2 my-2" placeholder="What's in your mind.">
        `<div` class="py-2">
            `<button` type="submit" class="p-2 bg-blue-500 w-20 rounded shadow text-white" `wire:click="AddComment">Add</button>`
        `</div>`
    `</form>`
    `<div>`
    `@foreach($comments` as $comment)
        `<div` class="rounded border shadow p-3 my-2">
            `<div` class="flex justify-between my-2">
                `<div` class="flex">
                    `<p` class="font-bold text-lg">{{$comment['creator']}}</p>
                    `<p` class="mx-3 py-1 text-xs text-gray-500 font-semibold">{{$comment['created_at']}}
                    `</p>`
                `</div>`
                `<iclass="fas` fa-times text-red-200 hover:text-red-600 cursor-pointer"></i>
            `</div>`
            `<p` class="text-gray-800">{{$comment['body']}}</p>

        `</div>`
    `@endforeach`
    `</div>`
`</div>`
`</div>`

and here is the php code  :

`<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Comments extends Component
{
    public $comments =[
        [
        'body'=>'this a test body asdasd sdfnln fsd fljsdkf ;jsdf lisdcx ',
        'created_at'=>'3 min ago',
        'creator' => ' jihad Ismail'
        ]
    ];

    public function AddComment(){
        array_unshift($this->comments,
            [
                'body'=>'this a a new test body ',
                'created_at'=>'2 seconds ago',
                'creator' => ' jihad Ismail'
            ]
        );

    }

    public function render()
    {
        return view('livewire.comments',compact($this->comments));
    }
}
`

**Comment by xitox97** [comment]
Try changing `<button type="submit" ..` to `<button type="button" ..`

**Comment by jihadismail8** [comment]
it worked , thank you so much
