### ISSUE TITLE
Weird behavior of wire:model and $dispatch

### ISSUE THREAD

**Issue by phuclh** [livewire/livewire#1363]
### Description

I have a searchable dropdown component that using 2 nesting wire:model. One is `query` for the input field (search field), another one is `country` for the selected value from the dropdown.

```
<div>
    <x-searchable wire:model.debounce="country"> // For selected value from the dropdown

        <x-slot name="input">
            <x-searchable.input wire:model.debounce="query"/> // For input field.
        </x-slot>

        @foreach ($countries as $key => $country)
            <x-dropdown.item
                key="{{ $key }}"
                value="{{ $country['code'] }}"
                secondary="{{ $country['code'] }}"
            >
                <x-slot name="prefix">
                    <x-flag country="{{ $country['country_code'] }}" class="text-base mr-2" />
                </x-slot>
                {{ $country['name'] }}
            </x-dropdown.item>
        @endforeach

    </x-searchable>
</div>

```

**input.blade.php**

```
...
<input x-ref="searchInput"
               x-on:keydown.enter.stop.prevent="onOptionSelect()"
               x-on:keydown.space.stop.prevent="onOptionSelect()"
               x-on:keydown.escape="onEscape()"
               x-on:keydown.arrow-up.prevent="onArrowUp()"
               x-on:keydown.arrow-down.prevent="onArrowDown()"
            {{ $attributes->merge(['class' => 'border-2 p-3 rounded h-9 w-full', 'placeholder' => 'Search...']) }}
        >
...
```

**item.blade.php (Item from dropdown list)**

```
...
<li
    x-on:click="$dispatch('input', '{{ $value }}'), value = '{{ $key }}', open = false, selectedValue = '{{ $value }}', selectedLabel = '{{ $slot }}'"
    x-on:mouseenter="selected = '{{ $key }}'"
    x-on:mouseleave="selected = null"
    x-bind:class="{ 'text-white bg-indigo-600': selected == '{{ $key }}', 'text-gray-900': !(selected == '{{ $key }}') }"
    class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9"
    id="listbox-item-{{ $key }}"
    role="option"
>
    ....
</li>
...
```

I only use `$dispatch('input', '{{ $value }}')` on `x-on:click`. I expect that the `country` property should only get the value when I selected an item from the dropdown, but `country` property still gets the value when I was typing the query in the input field. You can see the demonstration below:

![Screen Recording 2020-08-06 at 6 18 47 PM](https://user-images.githubusercontent.com/6707194/89598988-1c5c2300-d813-11ea-9b59-8a6faea63fdf.gif)

**Context**
- Livewire version: 1.3.2
- Laravel version: 7
- Browser: Chrome

**Comment by phuclh** [comment]
Does anyone have any idea on this? Thank you

**Comment by aidan-casey** [comment]
@phuclh events [bubble up](https://medium.com/@vsvaibhav2016/event-bubbling-and-event-capturing-in-javascript-6ff38bec30e). This means the **input** event on `x-searchable.input` is traveling up its parents (including `x-searchable`). A quick fix for this would probably be to add `.stop` to `wire:model.debounce="query"`. See [this](https://laravel-livewire.com/docs/actions#event-modifiers) section of the docs.

**Comment by phuclh** [comment]
> @phuclh events [bubble up](https://medium.com/@vsvaibhav2016/event-bubbling-and-event-capturing-in-javascript-6ff38bec30e). This means the **input** event on `x-searchable.input` is traveling up its parents (including `x-searchable`). A quick fix for this would probably be to add `.stop` to `wire:model.debounce="query"`. See [this](https://laravel-livewire.com/docs/actions#event-modifiers) section of the docs.

Thank you for your response @aidan-casey. I did try to add modifier `.stop` to input component, but it still did propagation.

Moreover, I can't find any information of `wire:model.stop` (https://laravel-livewire.com/docs/api). Is `.stop` a modifier of Alpine or Livewire?

<img width="1292" alt="Screen Shot 2020-08-12 at 6 03 55 PM" src="https://user-images.githubusercontent.com/6707194/90083015-32ac2800-dcc6-11ea-91a1-1d4269dd9758.png">

**Comment by aidan-casey** [comment]
@phuclh I'm sorry, you are correct. `.stop` is a modifier when listening for events with Livewire (e.g. wire:input.stop). When I wrote up my response I forgot you were using Alpine and linked you the wrong documentation. 👎 

I think you are correct in that using `x-on` with `.stop` will resolve this issue for you.

**Comment by zepfietje** [comment]
@phuclh can this issue be closed?

**Comment by zepfietje** [comment]
@nuernbergerA, I think you can close this issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Simoneu01** [comment]
can u share ur full component?
