### ISSUE TITLE
CSP Nonce Not Available On Style Tag

### ISSUE THREAD

**Issue by faradele** [livewire/livewire#1365]
### Description

While the recent version of livewire now supports adding a nonce option to the @livewireScripts directive, there is still no such equivalent support for the @livewireStyles directive.

This generates a style tag that violates csp rules on sites that do not support the **unsafe-inline** keyword for the **style-src** directive.

### Steps to reproduce
Adding ```@livewireStyles(['nonce' => 'somenoncevalue'])``` will result in a <style> tag with no nonce attribute on it.

**Comment by faradele** [comment]
This pull request https://github.com/livewire/livewire/pull/1364 attempt to fix the issue

**Comment by nuernbergerA** [comment]
Due to the conversation in PR, I'm going to close this issue.
