### ISSUE TITLE
wire:model on nested components

### ISSUE THREAD

**Issue by ali-alharthi** [livewire/livewire#1374]
### Description
First I'm not sure if this would be considered as a duplicate of #1105. And I apologize before hand for not being able to show the exact code (NDA).

However, I'm having an issue where wire:model throws an error on my nested component:
` Unable to set component data. Public property [$var] not found on component: [parent] `

1. I have a parent component called `Foo`, and I have a loop within the parent.
2. In that loop I use another livewire component called `Bar`.
3. I use wire:model on the child component `Bar`
4. Livewire throws `Livewire\Exceptions\PublicPropertyNotFoundException` and complain that the parent does not have the public property in `wire:model`.

Again, I apologize for not able to show the exact code. Nevertheless, here is a similar code:

parent `Foo`:
```class Foo extends Component
{
    public $something;

    public function mount(SomethingModel $something)
    {
        $this->something = $something;
    }

    public function render()
    {
        return view('livewire.foo');
    }
}
```

`livewire.foo`:
```
<div>
         ...
         @foreach($something->relation as $single)
                  <livewire:bar :something="$something->id" :one:="$single" :key="'unique-'.$single->id"/>
         @endforeach
         ...
</div>
```

child `Bar`:
```class Bar extends Component
{
    public $something;
    public $one;
    public $two;

    public function mount(SomethingModel $something, OneModel $one)
    {
        $this->something = $something;
        $this->one = $one;
    }

    public function someAction()
    {
         $this->validate([
            'two' => ['uuid'...],
        ]);
        ....
    }

    public function render()
    {
        return view('livewire.bar');
    }
}
```
`livewire.bar`:
```
<div>
         ...
         <input wire:model="two" type="text" name="two" >
         ...
</div>
```

Changing value of input `two` throws a `Livewire\Exceptions\PublicPropertyNotFoundException`.

### Steps to reproduce
1. Create two components.
2. Use one of the components within the other one (inside a loop).
3. Declare some public `variable` within the nested component.
4. Use wire:model on the nested component using the public `variable` you created on step #4 `wire:model="variable"`.

**Context**
- Livewire version: [1.3]
- Laravel version: [7.0]
- Browser: [Chrome, Firefox]

**Comment by ali-alharthi** [comment]
The issue was solve.
It was due to having the nested component within a table (`<tr>`) tag.

I forgot that livewire uses `div` as a wrapper for the components. Therefore, moved it outside the table and it works as it should!

Hope it will help someone, sorry for the inconvenience.

**Comment by ali-alharthi** [comment]
The issue was solved.
It was due to having the nested component within a table (`<tr>`) tag.

I forgot that livewire uses `div` as a wrapper for the components. Therefore, moved it outside the table and it works as it should!

Hope it will help someone, sorry for the inconvenience.

**Comment by nerisonpitogo** [comment]
> nents. Therefore, mov

consumed my  day figuring this out. All I have to do is remove the <div> tag.
