### ISSUE TITLE
Livewire doesn't delete old AlpineJS event listeners

### ISSUE THREAD

**Issue by Frostech0** [livewire/livewire#1380]
### Description

When the morphdom change the DOM element, the Livewire does not delete the old AlpineJS listeners. When the user trigger the event (e.g. onclick), only the old first listener is called. When the element is new, it is called twice.

### Steps to reproduce

- Create a laravel app
- Install livewire
- Create a livewire component
- Add component to routes
- Browse to the component

#### Version 1 - element is already exists in initial DOM
**app/Http/Livewire/Test.php**
```
namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component {
    public $number = 123;

    public function changeNumber() {
        $this->number = rand(1, 100);
    }

    public function render() {
        return view('livewire.test');
    }
}
```
**resources/views/livewire/test.blade.php**
```
<div x-data>
    <button wire:click="changeNumber">Change number</button>
    <button x-on:click="alert({{ $number }})">x-on:click alert({{ $number }})</button>
</div>
```

demo:
![ezgif-6-92178f250ddd](https://user-images.githubusercontent.com/2499115/90330320-38e32280-dfac-11ea-8b55-45c8dabfa545.gif)

#### Version 2 - element is new (is called twice)
**app/Http/Livewire/Test.php**
```
namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component {
    public $number;

    public function changeNumber() {
        $this->number = rand(1, 100);
    }

    public function render() {
        return view('livewire.test');
    }
}
```
**resources/views/livewire/test.blade.php**
```
<div x-data>
    <button wire:click="changeNumber">Change number</button>
    @if($number)<button x-on:click="alert({{ $number }})">x-on:click alert({{ $number }})</button>@endif
</div>
```

demo:
![ezgif-6-29da74d19bc8](https://user-images.githubusercontent.com/2499115/90330500-5c5a9d00-dfad-11ea-859d-af8ce69c5a4b.gif)

**Context**
- Livewire version: 1.3.2
- AlpineJS version: 2.6.0
- Laravel version: 7.25.0
- Browser: all

**Comment by phpyii** [comment]
Is there a solution now

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Sofianio** [comment]
Why is this issue ignored and not fixed until now?
It's a common case to have the x-on:click change behavior after a Livewire action

**Comment by jmas** [comment]
REOPEN
