### ISSUE TITLE
Property casts are not applied when using lifecycle hooks

### ISSUE THREAD

**Issue by IdrisN** [livewire/livewire#1381]
### Description

When properties with casts (e.g. 'date', or 'collection) are used via lifecycle hooks the cast is not applied.

### Steps to reproduce

Create the following livewire component:

```php
use Livewire\Component;

class BugField extends Component
{
    public $check;

    public $date;

    protected $casts = [
        'date' => 'date'
    ];

    public function mount()
    {
        $this->check = false;

        $this->date = now();

    }

    public function updatedCheck()
    {
        $this->subtractDay();
    }

    public function subtractDay()
    {
        $this->date->subDay();
    }

    public function render()
    {
        return view('livewire.bug-field');
    }
}
```

```html
<div>
    <div>
        Checkbox: <input type="checkbox" name="check" id="check" wire:model="check">
    </div>

    <div>
        <span>{{$date->format('Y-m-d')}}</span>
        <button wire:click='subtractDay'>Sub Day</button>
    </div>
</div>
```

The property `$date` is supposed to be a Carbon date and thus casted to a date.
The method `subDay()` is a method for a Carbon object.

You can call the `subtractDay()` method by clicking the 'Sub Day' button which will subtract a day from the carbon date object.
The method will also be called if the property `$check` gets updated. `$check` is wired to the checkbox and the lifecycle hook for the property is implemented. Upon clicking the checkbox an error gets thrown:
**Call to a member function subDay() on string**

The property `$date` seems to be not casted into a date object and the call to the Carbon date objects member function `subDay()` fails.

I've tried this with collections as casted properties as well.

**Context**
- Livewire version: v1.3.2
- Laravel version: v7.21.0
- Browser: Tried is on Chrome, Firefox and Safari

**Comment by calebporzio** [comment]
Thank you for submitting.

In the interest of not causing breakages, I'm going to close this issue. Also because Livewire version 2 removed the concept of casters.

I recommend viewing the casters section of the upgrade guide for better alternatives: https://laravel-livewire.com/docs/2.x/upgrading

Thanks!
