### ISSUE TITLE
Prefetch and Pagination misbehave

### ISSUE THREAD

**Issue by adddz** [livewire/livewire#1382]
### Description

I am using pagination and modified the pagination view to use the prefetch on the previous and next page button.

```
<button wire:click.prefetch='nextPage' rel="next">
    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
    </svg>
</button>
```

On mouse hover, the component prefetches the same URL and not the actual previous or next URL.
I guess it's because the `previousPage` and `nextPage` actions just decrement and increment the page?

**Comment by adddz** [comment]
@mitchjam This is how my component look like. I really cannot understand why the prefetch is not working with the pagination view.

`class ItemsTable extends Component
{
    use WithPagination;

    public $search = '';
    public $perPage = 10;
    public $sortField = 'created_at';
    public $sortAsc = false;

    protected $updatesQueryString = [
        'search' => ['except' => ''],
        'perPage',
        'sortField',
        'sortAsc'
    ];

    public function mount()
    {
        $this->fill(request()->only('search', 'perPage', 'sortField', 'sortAsc'));
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingPerPage()
    {
        $this->resetPage();
    }

    public function render()
    {
        $user = auth()->user();
        $search = $this->search;

        if ($this->search) {
            $items = Item::where('user_id', $user->id)->where(function ($q) use ($user, $search) {
                $q->where('name', 'LIKE', "%$search%")->orWhere('address', 'LIKE', "%$search%");
            });
        } else {
            $items = $user->items();
        }

        $items->orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc');

        return view('livewire.items-table', [
            'items' => $items->paginate($this->perPage)
        ]);
    }

    public function paginationView()
    {
        return 'vendor/pagination/tailwind';
    }
}
`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment]
REOPEN

**Comment by austenc** [comment]
I believe this is now fixed. Closing for now. 

For anyone who experiences this, feel free to reopen, but **please provide a repository so we can reproduce it.**

Thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
