### ISSUE TITLE
Problem with PHP opcache / view cache and @this

### ISSUE THREAD

**Issue by stromgren** [livewire/livewire#1384]
When using PHP opcache and / or view:cache the @this shorthand does not work. 

My livewire component looks like this:

```php
<div
    wire:ignore
    x-data
    x-init="
        FilePond.setOptions({
            allowMultiple: {{ isset($attributes['multiple']) ? 'true' : 'false' }},
            server: {
                process:(fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                    @this.upload('{{ $attributes['wire:model'] }}', file, load, error, progress);
                }
            },

            revert: (filename, load, error) => {
                @this.removeUpload('{{ $attributes['wire:model'] }}', filename, load);
            }
        });

        FilePond.create($refs.input);
    ">
    <input type="file" x-ref="input">
</div>
```

This gives an error like the one below for @this. Seems @this is never replaced with the reference to the livewire component.

```
Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at u (app.js?id=b2376aef9a3d8db673e2:2)
    at new ct (app.js?id=b2376aef9a3d8db673e2:2)
    at Object.initializeComponent (app.js?id=b2376aef9a3d8db673e2:2)
    at app.js?id=b2376aef9a3d8db673e2:2
    at app.js?id=b2376aef9a3d8db673e2:2
    at NodeList.forEach (<anonymous>)
    at Object.discoverComponents (app.js?id=b2376aef9a3d8db673e2:2)
    at Object.start (app.js?id=b2376aef9a3d8db673e2:2)
```

When clearing the view cache or disabling opcache everything works as intended.

### Steps to reproduce

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.25.0
- Browser: Tested in chrome, but is present in other browsers as well.

**Comment by ryangjchandler** [comment]
@stromgren - Livewire views that use `@this` aren't compatible with `view:cache` at the moment due to how it registers the `@this` directive. I can't speak on whether or not this will be solved as part of the changes in v2, but for now, you will need to stop using `view:cache`.

**Comment by nuernbergerA** [comment]
Actually there is a [way](https://github.com/livewire/livewire/issues/1039#issuecomment-637036445) to make it work

**Comment by ryangjchandler** [comment]
True, this is how I handle the problem at the moment but I'd advise against Jerry rigging a fix - also, it should technically go under the `boot()` method of the service provider.

**Comment by stromgren** [comment]
@ryangjchandler Thank you for your answer. If this isn't in the documentation it would be a nice addition that could save people a little time :) I'll close this issue for now.

**Comment by ryangjchandler** [comment]
> @ryangjchandler Thank you for your answer. If this isn't in the documentation it would be a nice addition that could save people a little time :) I'll close this issue for now.

We'll see what happens with v2, there might be a fix for this so that a userland workaround isn't needed. In the meantime, feel free to send in a PR to [livewire/docs](https://github.com/livewire/docs) repo.
