### ISSUE TITLE
wire:offline.attr="disabled" is not working after refreshing the component

### ISSUE THREAD

**Issue by bigint** [livewire/livewire#1385]
### Description

`wire:offline.attr="disabled"` is not working after refreshing the component

**Before offline**

![Screenshot](https://user-images.githubusercontent.com/69431456/90518355-33c1d700-e156-11ea-8b98-7453847a6041.png)

**During offline**

![Screenshot](https://user-images.githubusercontent.com/69431456/90518471-5d7afe00-e156-11ea-9826-becbcb87dac3.png)

**After clicking the button and went offline (see the 👏 it is active even in offline)**

![Screenshot](https://user-images.githubusercontent.com/69431456/90518355-33c1d700-e156-11ea-8b98-7453847a6041.png)

### Steps to reproduce

https://www.loom.com/share/ae39bd44b4c5493385882fa90b8d4864

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.25.0
- Browser: Chrome, Firefox, Brave and Tor Browser

`single-task.blade.php`

```html
<button
    type="button"
    class="btn btn-task btn-outline-success mr-1"
    wire:click="togglePraise"
    wire:loading.attr="disabled"
    wire:offline.attr="disabled"
>
    {{ Emoji::clappingHands() }}
    @if ($task->likes()->count('id') !== 0)
    <span class="small text-dark font-weight-bold">
        {{ number_format($task->likes()->count('id')) }}
    </span>
    @endif
</button>
```

**Comment by bigint** [comment]
Yes @xitox97, Again the same behavior!

```html
<span>
    <button type="button" class="btn btn-task btn-outline-success mr-1" wire:click="togglePraise" wire:loading.attr="disabled" wire:offline.attr="disabled" wire:key="{{ $task->id }}">
        {{ Emoji::clappingHands() }}
        @if ($task->likes()->count('id') !== 0)
        <span class="small text-dark font-weight-bold">
            {{ number_format($task->likes()->count('id')) }}
        </span>
        <span class="avatar-stack ml-1">
        @foreach($task->likers->take(5) as $user)
        <img class="praise-avatar rounded-circle {{ $loop->last ? 'mr-0' : '' }}" src="{{ $user->avatar }}" />
        @endforeach
        </span>
        @endif
    </button>
</span>
```

![Annotation 2020-08-23 232325](https://user-images.githubusercontent.com/69431456/90985153-ad632600-e597-11ea-9c35-27a88c9b974e.png)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
