### ISSUE TITLE
WithPagination removes element from custom paginator template

### ISSUE THREAD

**Issue by MaxGiting** [livewire/livewire#1387]
When using a custom pagination template I have seen strange behaviour. Below are three images in chronological order. When I go from page 1 -> 3 -> 1 the word `to` is removed from the custom paginator template. I have linked an example repo below that is a fresh Laravel install with livewire a custom pagination template and nothing else.

**Start on page 1**
<img width="200" alt="page1-correct" src="https://user-images.githubusercontent.com/9828591/90559774-039a2880-e196-11ea-82e1-44605c56f94f.png">

**Click to page 3**
<img width="200" alt="page3-correct" src="https://user-images.githubusercontent.com/9828591/90559781-05fc8280-e196-11ea-91cf-4b6db39685fb.png">

**Click back to page 1 and the word `to` has been removed**
<img width="200" alt="page1-wrong" src="https://user-images.githubusercontent.com/9828591/90559790-09900980-e196-11ea-91d2-0f728f2421ec.png">

I have narrowed it down to the [`custom-paginator.blade.php`](https://github.com/MaxGiting/Livewire-Pagination-Issue/blob/d189055691dc4e89e5934a490bd0639a3ddd4d83/resources/views/custom-paginator.blade.php#L3-L9) file I have used for the pagination.
```
    Showing
    <span>{{ $paginator->firstItem() }}</span>
    to
    <span>{{ $paginator->lastItem() }}</span>
    of
    <span>{{ $paginator->total() }}</span>
    results
```

If I remove the `<span>` tags then the word `of` does not disappear. It does disappear if the word `of` is between any element tags.

### Steps to reproduce
 - Clone [my example repo](https://github.com/MaxGiting/Livewire-Pagination-Issue)
 - `composer install`
 - Connect to a database in `.env`
 - `artisan migrate`
 - `php artisan db:seed --class=ItemSeeder` to populate the database
 - `artisan serve` and open browser
 - Click on the final page number link
 - Now click on any other page link and the word `to` will be removed from the string.

**Context**
- Livewire version: [e.g. 1.3.2]
- Laravel version: [e.g. 7.25.0]
- Browser: [Chrome]

**Comment by JayBizzle** [comment]
Also, when you go from `1` to `3`, if you notice, the space between the `1 and the `2` button disappears

**Comment by mpbarlow** [comment]
This is the same issue as #1344. If there are two identical DOM nodes separated by text, the text will go missing on the next render. You can get around it by wrapping your text nodes in `<span>`s.

**Comment by MaxGiting** [comment]
Yes @mpbarlow the exact same issue. Thank you for linking and the "fix". You mention in your issue this https://github.com/livewire/livewire/blob/1.x/js/dom/morphdom/morphdom.js#L317

Has the file changed since you linked to it? Which line in particular did you think should be investigated?

**Comment by mpbarlow** [comment]
@MaxGiting I don't believe it's changed since I linked to it. I didn't look too far into it, but based on the description in the comment block it sounded likely that that was the cause of the bug.

**Comment by MaxGiting** [comment]
#1473 closes this issue
