### ISSUE TITLE
Set Variables On Submit !

### ISSUE THREAD

**Issue by deepaksp** [livewire/livewire#139]
Hi,
I don't know this feature is possible or it already exist.
Normally I only validate few fields in a form.

eg. if i have a form with 10 or 12 field including mutiselect options, i generally check name, slug or author.

livewire set variable via model (thr is also better way with lazy i know) but i am not coming in agreement with my self that i have to allot memory to fields which are optional and dont require validation.

i like to see the way to set all form field variable on form submit which will be great.
You might be thinking you can do it normal way but i am talking about this use case at time of editing form and not creating

**Comment by jwktje** [comment]
I'm pretty sure my issue would also be resolved when you could trigger the modal update upon triggering a submit action.

https://github.com/calebporzio/livewire/issues/117
