### ISSUE TITLE
Dependency Injection Interface (Repository pattern)

### ISSUE THREAD

**Issue by SEFkiss** [livewire/livewire#1390]
### Description
Hi, I have a problem.
the mount() method is executed once. When rendering again, the Dependency Injection Interface is NULL. 
How can I use the Repository pattern in the Livewire component?
### Steps to reproduce
This is work for first rendering.
`use App\Repositories\Interfaces\OfficeLoggerInterface; ` 
 `use Livewire\Component;  `
`class Office extends Component  `
`{`
    `private $officeLogger;`
    `public function mount(OfficeLoggerInterface $officeLogger) : void`
    `{`
       ` $this->officeLogger = $officeLogger;`
`//        dd($officeLogger->createFolderForThisOffice());`
` }`
`

I need after store data, use interface 
` public function storeCreate() : void`
   ` {`
        `dd($this->officeLogger->createFolderForThisOffice());`
`}`

**Context**
- Livewire version: 1.3.2
- Laravel version: 7.20.0
- Browser: Chrome

**Comment by ryangjchandler** [comment]
@SEFkiss - since the `mount()` method is only called for the initial render, you should either inject the dependency directly into your action method, or inside of a `hydrate()` method, use the `app()` helper to resolve it from the container.

```php
public function storeCreate(OfficeLoggerInterface $officeLogger): void
{
    $officeLogger->createFolderForThisOffice();
}
```

**Comment by SEFkiss** [comment]
I tried it again,
```php
public function storeCreate(OfficeLoggerInterface $officeLogger): void
{
    $officeLogger->createFolderForThisOffice();
}
```
Getting an error: 
**ArgumentCountError**
Too few arguments to function App\Http\Livewire\Console\Manage\Company\Office::storeCreate(), 0 passed in C:\OpenServer\domains\lift.office\app\Http\Livewire\Console\Manage\Company\Office.php on line 127 and exactly 1 expected

How I can use the app() helper to resolve it from the container?

**Comment by SEFkiss** [comment]
It seems, I was success ^_^
```php
    public function hydrate()
    {
        $this->officeLogger = app('App\Repositories\Interfaces\OfficeLoggerInterface');
    }
```
However, it should be understood that hydrate is called literally always, whenever a field in the form is updated. Is it harmful?

**Comment by SEFkiss** [comment]
I can use app() helper without hydrate() method.
```php
public function storeCreate() : void
    {
        $this->officeLogger = app('App\Repositories\Interfaces\OfficeLoggerInterface');
        dd($this->officeLogger->createFolderForThisOffice());
}
```
