### ISSUE TITLE
Custom pagination page name not being allowed

### ISSUE THREAD

**Issue by Jam0r85** [livewire/livewire#1394]
Using a custom pagination page name does not follow through to livewire.

`$model->paginate($this->limit, ['*'], 'payments_page');`

However it still uses ?page= in the paginator links.

Is this meant to be like this? The only reason I ask is that if you were to have two different livewire components on a single page when entering the URL with ?page=32 for example, it will trigger both of those components to that page.

**Comment by austenc** [comment]
Related to #1209

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
