### ISSUE TITLE
File upload not cleaning errorBag

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1402]
Livewire v1.3.3

I have a component with an  ` <input type="file" ` that allows `multiple` file uploads.

1. If I select a file that does **not pass** validation, the error is displayed.
2. If I then select another file that **passes** validation **the error from the first file remains** in the error bag.
3. Uploading another invalid file appends to the error bag with **the same loop index.**
4. Uploading a valid file does not delete the previous error message, **error for index.0 is never removed.**

```php
    public function updatedPhotos()
    {
        $this->validate([
            'photos.*' => 'image|max:1024', 
        ]);
    }
```

If I show all errors, I can see that the error remains with **duplicate loop index**.
![image](https://user-images.githubusercontent.com/21239634/90944161-79fc8c00-e41d-11ea-8728-c1033c2d2608.png)

```blade
    @error('photos.*')
        @foreach($errors->all() as $error)
        <p>{{ $message }}</p>
        @endforeach
    @enderror
```

**Comment by wira-sandy** [comment]
Did u have try it without foreach?
Something like 
`@error('photos.*')`
`<p>{{ $message }}</p>`
`@enderror`

**Comment by zepfietje** [comment]
@tanthammar, I think https://github.com/livewire/livewire/pull/1615 will solve your issue.

**Comment by tanthammar** [comment]
@zepfietje I tested #1615, it allows me to manually clear the error bag using wildcards - BUT, it does not solve this issue.

**In Livewire v2 the error bag is not cleared when uploading new files.** 

The problem exists for both single and multiple file uploads.

My temporary solution is to manually clearing the error bag using Alpine + implementing #1615 in Livewire for multiple file uploads.

In component
```php
    public function clearFileUploadError(string $field)
    {
        $this->resetErrorBag($field);
    }
````

in blade file
```blade
x-on:livewire-upload-start="$wire.clearFileUploadError('{{ $field->multiple ? $field->name.'.*': $field->name }}');"
```

**Comment by zepfietje** [comment]
@tanthammar, could that be related to https://github.com/livewire/livewire/pull/1615#issuecomment-694149855?

**Comment by tanthammar** [comment]
@zepfietje I am not sure, don't know how to test that case in my app.

**Comment by zepfietje** [comment]
@tanthammar, could you pull in the latest version of https://github.com/livewire/livewire/pull/1615 and give it a try? Curious if it fixes your issue.

**Comment by tanthammar** [comment]
I pulled in this one: https://github.com/zepfietje/livewire/tree/error-bag-except-wildcard.
Sadly the error remains. Livewire does not clean the errorbag when a new file (that passes validation) is uploaded.
I have to use your pull request to be able to clear it manually with Alpine.

**Comment by zepfietje** [comment]
Okay, clear. Let's hope @calebporzio merges https://github.com/livewire/livewire/pull/1615 ASAP.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
