### ISSUE TITLE
Programmatically adding text to wire:model does not work

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#1406]
### Description
I have multiple input fields, that have some values appended using `wire:model`:

This is my component file:
```php
protected $listeners = ['textAddedToInput' => 'updateFieldRegion'];

public $fields = [];
public function mount()
{
        $this->fields = ['number' => '1000'];
}
public function updateFieldRegion(array $attributes = [])
{       
}
```

Below is my HTML:

```html
<input id="number" wire:model.lazy="fields.number">
```

Now, whenever I edit the `fields.number` content in the input field manually (by writing something other than "1000"), it successfully updates the page and the new number is still visible.

However, I need to update the input fields programmatically:

```html
<div x-on:click="addTextToInput('5000')">Change value to 5000</div>
```

When the above is clicked, it will fire off a function using JavaScript (AlpineJs):

```javascript
addTextToInput(text) {
    let input = document.getElementById('number');
    input.value = text;
    window.livewire.emit('textAddedToInput');
}
```
Now the above function successfully updates the `#number` input field with the value of `5000`, but as soon as the `window.livewire.emit('textAddedToInput');` gets triggered, it will reset the input value to the default of `1000`

As of right now, the method that `textAddedToInput` triggers doesn't even return anything.

I am suspecting this to be because the actual `wire:model` is never updated. If I set in a timeout of a few seconds before emitting from the JavaScript to Livewire, and append a space and delete that from the input field, the value of `5000` will be saved.

What am I doing wrong?

**Context**
- Livewire version: ^1.2.0
- Laravel version: 7.24.0
- Browser: Chrome

**Comment by iksaku** [comment]
Could you verify with [Debugbar](https://github.com/barryvdh/laravel-debugbar) if your Livewire requests are being reset?

If you cannot use Debugbar, could you try to `dd()` in `updating()` and `updated()` functions like described in [Lifecycle Hooks](https://laravel-livewire.com/docs/lifecycle-hooks)?

**Comment by austenc** [comment]
@oliverbj This is **much** easier in Livewire v2, so I'd really suggest upgrading to that. With v2, you could `@entangle` the property between the backend and javascript to make this sort of thing easier (and get rid of your `addTextToInput` function). 

I really wouldn't recommend doing it this way, but if you wanted to trigger livewire to refresh the property, you change your function to fire an `input` event instead of triggering the livewire event. _You will also have to remove `.lazy`_
```
function addTextToInput(text) {
    let input = document.getElementById('number');
    input.value = text;
    input.dispatchEvent(new Event('input'));
}
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
