### ISSUE TITLE
Form input changes on high latency connections

### ISSUE THREAD

**Issue by skyronic** [livewire/livewire#1408]
### Description

I've noticed that the form inputs erratically change value to old states temporarily (and sometimes permanently) when values are changed very often on a high-latency connection.

https://i.imgur.com/F69G62P.mp4

I am using `wire:model.lazy` on all input elements.

This seems to happen when the text has changed before `syncInput` completes. This only seems to happen when latencies are >500ms.

### Steps to reproduce

1. Force high latency via chrome devtools or moving somewhere with a terrible internet connection.
2. Edit a form, tabbing from one control to another

**Context**
- Livewire version: 1.3
- Laravel version: 7
- Browser: Chrome

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
