### ISSUE TITLE
redirect method problem with wire:loading

### ISSUE THREAD

**Issue by inuryyev** [livewire/livewire#1411]
### Description

I have button component and when it loading it shows spinner (`wire:loading`) and when not loading it shows icon (`wire:loading.remove`).

Problem is:   when button calls redirect method this button shows nothing. It is like redirect disables component. 

```
<button wire:click="trigger" title="{{$text}}" class="btn btn-{{$color}}   float-right " >
    <div >
        <div wire:loading>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        </div>
        <div wire:loading.remove>
            @if ($icon)
                <i class="fas {{$icon}}"></i>
            @endif
        </div>
    </div>
</button>
```

```
  public function trigger(){

        if(!empty($this->event)){
            $this->emit('show-modal');
            $this->emit($this->event, $this->params);
        }

        if($this->url !== null){
            return redirect()->to($this->url);
        }


    }
```

### Steps to reproduce

**Context**
- Livewire version: [v1.3.3]
- Laravel version: [v6.18.35]
- Browser: [Chrome]

**Comment by iksaku** [comment]
Could you try again but specifying the [Target Action](https://laravel-livewire.com/docs/loading-states#targeting-actions) to which your loading spinner must load?

I remember hitting this issue before, but that solved it for me, and it looks like specifying the target action should solve yours as well.

**Comment by inuryyev** [comment]
> Could you try again but specifying the [Target Action](https://laravel-livewire.com/docs/loading-states#targeting-actions) to which your loading spinner must load?
> 
> I remember hitting this issue before, but that solved it for me, and it looks like specifying the target action should solve yours as well.

I tried. But same result .

**Comment by iksaku** [comment]
I see that you’re using FontAwesome. Do you call `i2svg()` or `watch` function?

Make sure that you’re using the `watch` function

**Comment by iksaku** [comment]
Also, I would recommend you to use livewire’s `redirect` function (without returning it), and pass your route as a parameter:
```php
if ($this->url !== null) {
    $this->redirect($this->url);
}
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
