### ISSUE TITLE
Scroll To First Validation Error

### ISSUE THREAD

**Issue by djoks** [livewire/livewire#1415]
When I submit my form and there are validation errors. The page does not scroll back up to the first validation error. Is there anyway I can do this in laravel?

This is important because otherwise it gives the user the impression that nothing happened after loading was completed.

**Comment by iksaku** [comment]
You could assign a specific property to your validation message container (`div` element or whatever you're using) and use an [Inline Script](https://laravel-livewire.com/docs/inline-scripts) to search for all elements that contain that property once your actions has failed, and just use vanilla JS to either scroll to the element, or focus it.

**Comment by zepfietje** [comment]
What @iksaku commented should fix your issue @djoks.
I don't think this opinionated behavior is within the scope of Livewire.
If you have no further questions, this issue can be closed.

**Comment by zepfietje** [comment]
@nuernbergerA, you can close this one.

**Comment by jakubjo** [comment]
## Simple & universal solution

In case someone finds this through search engine, here's a simple and universal solution.

Put the following JS in your global app.js or something similar. Replace `your-optional-prefix` with something like `app` or a more appropriate prefix.

The solution uses `element.scrollIntoView`. See https://caniuse.com/?search=scrollintoview for browser support.

```js
window.addEventListener('your-optional-prefix:scroll-to', (ev) => {
  ev.stopPropagation();

  const selector = ev?.detail?.query;

  if (!selector) {
    return;
  }

  const el = window.document.querySelector(selector);

  if (!el) {
    return;
  }

  try {
    el.scrollIntoView({
      behavior: 'smooth',
    });
  } catch {}

}, false);
```

Than all you need to do is to dispatch an event from your Livewire component.
Keep in mind, the element specified in 'query' must be findable through `document.querySelector`. In this case, you would need an HTML `<section id="section-billing-address">...</section>`

```php
$this->dispatchBrowserEvent('your-optional-prefix:scroll-to', [
    'query' => '#section-billing-address',
]);
```

**Comment by juanCure** [comment]
@jakubjo where is the correct place in the Livewire component to dispatch the event?

I have called after $this->validate() but It no worked.

**Comment by jakubjo** [comment]
@juanCure `$this->validate()` throws an exception if validation fails. So you need a try-catch-block.
I'm using a macro:

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\ValidationException;
use Livewire\Component;

class MacrosServiceProvider extends ServiceProvider
{
/**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        Component::macro('scrollOnFail', function (string $query, callable $closure) {
            /* @var Component $this */

            try {
                $closure();
            } catch (ValidationException $e) {
                $this->dispatchBrowserEvent('your-optional-prefix:scroll-to', [
                    'query' => $query,
                ]);

                throw $e;
            }
        });
    }
}
```

And then, in my component I wrap the validation with the macro:

```php
$this->scrollOnFail('form', function () {
    $this->validate();
});
```

**Comment by ingmontoya** [comment]
hI @jakubjo, maybe a dump question, I'm using your solution but it isn't scrolling to the fields, my question is : that first parameter "form" should be named like that?  need to add that "form" into some place in my code? 

Thanks

**Comment by jakubjo** [comment]
The first parameter is a DOM query selector. So you need to have a `form` element.
If you want to scroll, eg. to the first section, you would use `section` instead of `form`.

Other possibilities:

- `#my-id` scrolls to an element which you've given the id `my-id`
- `.my-class` scrolls to an element which you've given the class `my-class`

It's just an ordinary DOM query selector: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector 

Please, keep in mind, [the post](https://github.com/livewire/livewire/issues/1415#issuecomment-779694859) was a follow up. You'd need to also integrate the JavaScript part as highlighted in my [previous post](https://github.com/livewire/livewire/issues/1415#issuecomment-734894165).

**Comment by avinash403** [comment]
Here's an easy solution:

If you are using `<x-jet-input-error/>` component for displaying errors, you can just modify `resources/views/vendor/jetstream/components/input-error.blade.php` (make sure you have published livewire views) file to below code:

```
@props(['for'])

<span x-data="{hasError: '{{$errors->get($for)[0] ?? ''}}' }"
     x-init="()=> { $watch('hasError', (value)=> {
            let errorDiv = document.getElementsByClassName('invalid-feedback')[0];
            if(errorDiv){
                errorDiv.scrollIntoView({behavior: 'smooth', block: 'center', inline: 'nearest'});
            }
    })}">
    @error($for)
        <span {{ $attributes->merge(['class' => 'invalid-feedback d-block']) }} role="alert" style="font-size: inherit">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</span>
```

**Explanation** : we use alpine to watch for changes in the validation message for the "$for" field. As soon as it changes (validation message shows up or vanishes), it look for the error block and scrolls to it

**Comment by mikemand** [comment]
@avinash403's solution was brilliant but didn't work for me. It wouldn't scroll up for some reason. I changed it to be like this instead (ignore the different classes because of Bootstrap vs Tailwind):

```blade
@props(['for'])

@error($for)
<div
    x-init="$nextTick(() => {
        let errorDiv = document.getElementsByClassName('invalid-feedback')[0];
        if (errorDiv) {
            errorDiv.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
        }
    })"
>
    <p {{ $attributes->merge(['class' => 'invalid-feedback text-sm text-red-600']) }}>{{ $message }}</p>
</div>
@enderror
```

**Comment by RishabSwift** [comment]
I didn't want to edit any of my existing Livewire methods on the server side, so this is how I did it.

It also only scrolls to the error message if it's not visible in the viewport.

```
// hook to catch after every livewire request 
Livewire.hook('message.processed', (message, component) => {

    let errors = message.response.serverMemo.errors;

    // Only scroll if we have an error bag with validation messages
    if (Object.keys(errors).length > 0) {

        let errorDiv = document.getElementsByClassName('invalid-feedback')[0];

        // if we have an error element and it's not visible in viewport
        if (errorDiv && !isScrolledIntoView(errorDiv) {
            errorDiv.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
        }
    }
})

// function to determine if an element is currently in viewport
function isScrolledIntoView(el) {
    let rect = el.getBoundingClientRect();
    let elemTop = rect.top;
    let elemBottom = rect.bottom;

    // return true if element visible in viewport
    return elemTop < window.innerHeight && elemBottom >= 0
}

```

**Comment by gbrits** [comment]
Maybe not ideal for some, but I found my solution to be the quickest to add:
```
@error('client.first_name')
<span x-init="() => { var first = document.getElementsByClassName('validation-error').item(0); window.scroll({
    top: first.getBoundingClientRect().top,
    behavior: 'smooth',
})  }" class="validation-error text-sm text-red-600">{{ $message }}</span>
@enderror
```

**Comment by eduardichim** [comment]
I know this has been closed, but there is a simpler, more intuitive way of coding this, for anyone who might need it in the future

Go into your App service provider and add a listener for failed-validation on livewire, because of 
https://github.com/livewire/livewire/blob/7795843505d4f8f3819bae7cae2a200f414d9658/src/LifecycleManager.php#L112-L120

```
// inside app/Providers/AppServiceProvider.php

public function boot()
{
  Livewire::listen('failed-validation', function ($validator, Component $instance) {
    $instance->dispatchBrowserEvent('scrollToError');
  });
}
```

Now all you need to do is catch `scrollToError` in your javascript, if you use the livewire as your "controllers" you might have to load those event listeners before livewire scripts are loaded,  so what I do:

I have a class on all the inputs with errors `input-error` for ease of access.

1. create a resources/js/livewire-events.js
```
document.addEventListener('scrollToError', function () {
    document.getElementsByClassName('input-error')[0].scrollIntoView();
});
```

2. add it to the mix
```
mix.js('resources/js/app.js', 'public/js')
    .js('resources/js/livewire-events.js', 'public/js')
```

3. load it before livewire scripts and also make sure it's not defer, notice defer on `app.js`
```
<script src="{{ asset('js/app.js') }}" defer></script>
<script src="{{ asset('js/livewire-events.js') }}" async></script>
@livewireScripts
```

Now modify your `livewire-events.js` to be as cool as you want it to be.

**Comment by gbrits** [comment]
> 

Hi @eduardichim, I'm trying to use your method as it seems like a better alternative, however I've run into an issue with it. As you haven't stated the `use` dependencies I assumed the following at the top of the AppServiceProvider:

```
use Livewire\Livewire;
use Livewire\Component;
```

Unfortunately, when firing (on saving with an invalid input), the following error is appearing:

![Screen Shot 2022-02-06 at 6 26 39 pm](https://user-images.githubusercontent.com/14840021/152676659-63bd353e-b03b-4a8f-beb1-2091424c7a40.png)

**Comment by eduardichim** [comment]
Hello @gbrits , you have an older version of livewire than required, hopefully my edit clears it up.

**Comment by jonathanorlen** [comment]
@gbrits it work on you? i just have same problem and i still confuse with the code. The point is add code in AppServiceProvider and give code eventlistener right?

**Comment by theChaosCoder** [comment]
@RishabSwift  Thx for your code, it is working great. You have a missing **)** after !isScrolledIntoView(errorDiv)  😉
Here's my working code with the latest livewire version. I use "is-invalid" as my css error class.

```
<script>
    document.addEventListener('livewire:load', function() {

        // hook to catch after every livewire request
        Livewire.hook('message.processed', (message, component) => {

        let errors = message.response.serverMemo.errors;
            // Only scroll if we have an error bag with validation messages
            if (Object.keys(errors).length > 0) {

                let errorDiv = document.getElementsByClassName('is-invalid')[0];

                // if we have an error element and it's not visible in viewport
                if (errorDiv && !isScrolledIntoView(errorDiv)) {
                    errorDiv.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
                }
            }
        })

        // function to determine if an element is currently in viewport
        function isScrolledIntoView(el) {
            let rect = el.getBoundingClientRect();
            let elemTop = rect.top;
            let elemBottom = rect.bottom;

            // return true if element visible in viewport
            return elemTop < window.innerHeight && elemBottom >= 0
        }
    });
</script>
```

**Comment by Beaudinn** [comment]
@RishabSwift Looks good,
Unfortunately it doesn't work with custom validators (Validator::make) to make this work you can add this bit of code to your `ServiceProvider`
    
    Livewire::listen('component.dehydrate', function ($component, $response) {
	    $errors = $component->getErrorBag()->toArray();
    
	    // Persist all errors that were born including custom validators (Validator::make).
	    $response->memo['errors'] = collect($errors)->toArray();
    });

This wil overwrite default configurations inside `Livewire\Features\SupportValidation` that in fact excluded the custom validators errors from the serverMemo response.

**Comment by wrabit** [comment]
> document.addEventListener('livewire:load', function() {
> 
>         // hook to catch after every livewire request
>         Livewire.hook('message.processed', (message, component) => {
> 
>         let errors = message.response.serverMemo.errors;
>             // Only scroll if we have an error bag with validation messages
>             if (Object.keys(errors).length > 0) {
> 
>                 let errorDiv = document.getElementsByClassName('is-invalid')[0];
> 
>                 // if we have an error element and it's not visible in viewport
>                 if (errorDiv && !isScrolledIntoView(errorDiv)) {
>                     errorDiv.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
>                 }
>             }
>         })
> 
>         // function to determine if an element is currently in viewport
>         function isScrolledIntoView(el) {
>             let rect = el.getBoundingClientRect();
>             let elemTop = rect.top;
>             let elemBottom = rect.bottom;
> 
>             // return true if element visible in viewport
>             return elemTop < window.innerHeight && elemBottom >= 0
>         }
>     });

@theChaosCoder the problem with this, and the version from @RishabSwift is if the user chooses to continue to complete the rest of the form, i.e. simply updating another field, it causes further scrolls to erroneous field until the user wants to resolve the error.

**Comment by theChaosCoder** [comment]
Yes, it's not a perfect solution. I had to reset validation on some interactive components because of this.

**Comment by RishabSwift** [comment]
@theChaosCoder Yes, it is.

I have updated the original code to resolve that issue. Basically I am checking if the user is TYPING in the textarea/textbox, and only scrolling to the next issue if they're not currently focused on those elements.

https://github.com/livewire/livewire/issues/1415#issuecomment-1003798465

**Comment by RishabSwift** [comment]
@theChaosCoder You're right, I had the same issue.

I have updated the original code to resolve that issue. Basically I am checking if the user is TYPING in the textarea/textbox, and only scrolling to the next issue if they're not currently focused on those elements.

https://github.com/livewire/livewire/issues/1415#issuecomment-1003798465

**Comment by neindk** [comment]
You can access validator instance according to[ docs](https://laravel-livewire.com/docs/2.x/input-validation#access-validator-instance). So you can do like this, I think.
```
$this->withValidator(function (Validator $validator) {
            if ($validator->fails()) {
                $this->emit('scrollToElement'); // or dispatch browser event here
            }
        })->validate();
```
And listen for the event dispatched from livewire at view side.
 ```
<script>
        window.onload = () => {
            Livewire.on('scrollToElement', () => {
                const element = document.querySelector("#element");
                element.scrollIntoView();
            });
        }
    </script>
```

**Comment by burfbari** [comment]
> @theChaosCoder the problem with this, and the version from @RishabSwift is if the user chooses to continue to complete the rest of the form, i.e. simply updating another field, it causes further scrolls to erroneous field until the user wants to resolve the error.

My approach to solving this was to scroll only when the Submit button was clicked. For this I declared and set the value of a property on click of the Submit button.

Then check if the value is set or not like so.

Declare the property
```
public $save = false;
```

I've got a listener that updates the value of the field where I change the value to `false`
```
$this->save = false;
```

Set the value to `true` in the blade on Submit button click
```
wire:click="$set('save', true)"
```

And check the value in the hook
```
if (Object.keys(errors).length > 0 && message.response.serverMemo.data.save == true)
```

**Comment by alejo9054** [comment]
> Livewire::listen('failed-validation', function ($validator, Component $instance) {
>             $instance->dispatchBrowserEvent('scrollToError');
>         });

the only one that works for me

**Comment by alejo9054** [comment]
> Maybe not ideal for some, but I found my solution to be the quickest to add:
> 
> ```
> @error('client.first_name')
> <span x-init="() => { var first = document.getElementsByClassName('validation-error').item(0); window.scroll({
>     top: first.getBoundingClientRect().top,
>     behavior: 'smooth',
> })  }" class="validation-error text-sm text-red-600">{{ $message }}</span>
> @enderror
> ```

The only one that works for me, thanks so much!
