### ISSUE TITLE
Implicit (Optional) Route Model Binding

### ISSUE THREAD

**Issue by Braunson** [livewire/livewire#1416]
### Description

Laravel allows optional route model bindings, in this case Livewire does not. When providing a "invitation token" it binds the Model class properly, when no token is provided, the page is rendered but when I try to change any field it'll call the backend `/livewire/message/broker-auth.register` and return the modal with a 404 / the `ModelNotFoundException` exception is thrown. Shouldn't it instead follow the default Laravel behavior due to the optional flag and return either a `null` or empty instance of the `Broker` model?

### Steps to reproduce

**Context**
- Livewire version: v1.3.3
- Laravel version: 7.25.0
- Browser: Chrome

**Code**

Routes:

```php
Route::livewire('brokers/register/{broker:invitation_token?}', 'broker-auth.register')
    ->name('broker-auth.register');
```

Livewire Component Class:

```php
public function mount(Broker $broker = null)

// Also tried

public function mount(?Broker $broker)
```

**Comment by Braunson** [comment]
Looks like a solution may be to update this class `Livewire\HydrationMiddleware\HydrateEloquentModelsAsPublicProperties` in the method `hydrate`.

It's not ideal but a check before calling `ModelIdentifier` would solve the issue but remove the default behavior of throwing an `ModelNotFoundException` in the use-case that it is actually needed (and not just my use-case of it being optional).

**Comment by tanthammar** [comment]
I had the same issue, testing v2 now and that problem is gone.

**Comment by tanthammar** [comment]
The method looks different in v2, maybe we can close this issue?

https://github.com/livewire/livewire/blob/master/src/HydrationMiddleware/HydrateEloquentModelsAsPublicProperties.php

**Comment by zepfietje** [comment]
@calebporzio, this issue can probably be closed.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
