### ISSUE TITLE
ModelNotFoundException is not caught in computed properties

### ISSUE THREAD

**Issue by arttemiuss43** [livewire/livewire#1417]
### Description

Livewire doesn't catch `ModelNotFoundException` when throwing inside computed properties while Laravel does: 

```php
public function getProductProperty()
{
   return Product::findOrFail('not-existing-id');
}
```

### Steps to reproduce

1. Create a computed property
2. Make it throw a `ModelNotFoundException`
3. You should see a Server error with the exception details instead of 404 page

A temporary solution is to catch this exception in the `App\Exceptions\Handler::render()` method

**Comment by calebporzio** [comment]
It seems to be working properly for me:

![image](https://user-images.githubusercontent.com/3670578/94846132-a4634100-03ee-11eb-8bc8-ab3c38777cf1.png)

Closing this. Thanks.
