### ISSUE TITLE
7.4 Typed Properties & Route Param Binding

### ISSUE THREAD

**Issue by calebporzio** [livewire/livewire#1429]
This is an outline for two Livewire features:

## #1: Directly assign properties from route parameters without the `mount()` method:

```php
Route::get('/post/{post}, ShowPost::class)
```
```php
class ShowPost extends Component
{
    public Post $post;

    // Notice no mount method needed.
}
```

## #2: Mutate the browser URL at runtime if a route parameter's property changes.

* Given:
```php
Route::get('/post/{post}, ShowPost::class)
```
```php
class ShowPost extends Component
{
    public Post $post;

    public function changePost(Post $newPost)
    {
        $this->post = $newPost;
    }
}
```

A user visits `/post/1`, and then clicks a Livewire button that calls "changePost(2)", the URL now says `/post/2` without ever changing pages. (using pushState).

This should work with ANY route parameters no matter if they are route model bound or not.

**Comment by DanielCoulbourne** [comment]
We just had a long call with @calebporzio, @inxilpro and myself about these features and we're going to be implementing them on our end.

**Comment by tanthammar** [comment]
Just tested it AWESOME!!!
