### ISSUE TITLE
Issue in Tags in Repo

### ISSUE THREAD

**Issue by scrothers** [livewire/livewire#1436]
This is going to sound really petty, but I'm starting to track my application dependancies a bit more in detail that previously before.

Livewire has a tag of `1.3.0` that doesn't match the format of the `1.2.*` tags and the other `1.3.*` tags, which are prefixed with v, as in `v1.3.1`.

Also, you got a `tmp` tag that hasn't been updated since March.

I have no idea if your OCD is as bad as mine, but that popped up in my dependency version tracking. I'm hoping for the outcome of renaming `1.3.0` to `v1.3.0` and the removal of `tmp` on the repo, if not though, I totally understand.

Thanks!

Also, thank you for all you do, Livewire is absolutely my favorite front end development package.

**Comment by roni-estein** [comment]
I can't effect a change but I happened to be looking at Github as this came in, and I just wanted to say. Your OCD has defeated my own. :)

**Comment by calebporzio** [comment]
Lol, good catch. Fixed!
