### ISSUE TITLE
A non-obvious problem causing error: Livewire encountered corrupt data when trying to hydrate

### ISSUE THREAD

**Issue by edgrosvenor** [livewire/livewire#1438]
### Description

This isn't a bug in Livewire per se, but maybe an opportunity to improve the documentation or maybe even error handling.

I assigned an array to a public property that resulted from calling toArray() on an eloquent model. That model has a POINT column in the database, but I don't have any traits on the model to handle geometry data because I don't actually use that column in Laravel (at least not in this particular app). So the column just sits there innocently holding a latitude and longitude and trying its best to behave.

The problem is that when a POINT column encounters Eloquent's toArray() method, it vomits. And this vomit somehow messes with Livwire's data checksum so when the component tries to hydrate it thinks someone's been up to no good.

All I had to do to fix the problem was hide the column from toArray(). So not really a Livewire problem, but this does illustrate how POINT columns (and maybe some other lesser used column types) could, if left in an array, mess with Livewire's checksum.

### Steps to reproduce

```php
public $college = College::find(2197)->toArray();

/** Results in
$this->college = [ 'id' => 2197, 
  'name' => 'Agnes Scott College', 
   'unitid' => '138600', 
   'city' => 'Decatur', 'state' => 'GA', 
   'location' => "\0\0\0\0".''."\0\0\0".'p��R�U��)s��@@', // <--- The problem 
   'governing_body' => 'NCAA', 'division' => '3', 
   'etc' => 'blah blah blah',
 ]
*/
```

**Context**
- Livewire version: 1.3.3
- Laravel version: 7.26.1
- Browser: Any

**Comment by tanthammar** [comment]
Have you tried to $cast the point column to decimal or double on the model?

**Comment by edgrosvenor** [comment]
I'm sure those things would work. I don't need the data in the array though. Honestly I didn't even know it was there. That column was added by someone else for a totally unrelated project. Which is why hitting the generic error message really slowed me down. My hope is that we can come up with a way to catch this sort of error more specifically in Livewire or at least add this scenario to the troubleshooting section of the docs.

**Comment by tanthammar** [comment]
I do understand your frustration, I've been there many times myself. 

My thought on this particular problem is that this kind of error doesn't fall into the Livewire package responsibility.

Livewire cannot cover for the models composition.

If you think about Livewire as a replacement for a Controller and a view, I suppose you wouldn't blame the Controller for not being able to parse your model?

**Comment by edgrosvenor** [comment]
I said at the beginning that this isn't a Livewire bug per se. But Livewire aspires, I am led to believe, to deliver an exceptional developer experience. What tripped me up is something that could be detected and handled in Livewire or at least documented so other developers don't run into the same problem. 

When focusing on developer experience, you can't limit your thinking to just what is within the specific domain of the package. You have to think about how the package interacts with the larger world around it and always try to make that package a better citizen of the universe in which it lives.

Anyway, Caleb already has a troubleshooting guide for this specific error. If there's no other path forward on this I'll happily submit this scenario as a possible cause int he troubleshooting section with the mixed key arrays and other documented causes of the error. I just opened the issue to see if there's an appetite to try to get to some more specific and actionable error handling to reduce the number of ways people can hit this generic error.

**Comment by davidpiesse** [comment]
This has been PR'd into the docs.
livewire/docs#209

**Comment by calebporzio** [comment]
Closing as you can now bind to model properties in v2
