### ISSUE TITLE
v2 Model hydration not working with array field

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1444]
Livewire v2@dd54352

### Default model hydration does not work with array fields.
I cannot offer a solution but if this is not fixable before the release of v2, the **documentation** needs to clearly state that the default model hydration doesn't work with array fields.

### HydrateEloquentModelsAsPublicProperties.php `row: 40` 
The problem is that Livewire tries to populate the model with `$keys`  that comes from the `$rules`,  in this example they contain `'*'` and `'.'`  which blows up `data_set()` helper. 

Error: 
```
PHP Notice:  Indirect modification of overloaded element of App/User has no effect in /Users/tina/Sites/tallforms/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 216
```

![image](https://user-images.githubusercontent.com/21239634/91713123-74274900-eb89-11ea-90a4-1a5989c60ea4.png)

**Comment by nuernbergerA** [comment]
Good catch Tina.

We will fix it before launch.

**Comment by nuernbergerA** [comment]
To illustrate the problem a bit better
https://web.tinkerwell.app/#/snippets/0f91222a-120b-40c8-92a9-7545e62b91ae

**Comment by nuernbergerA** [comment]
@tanthammar can you check out #1445 and see if it works?

make sure rules are prefixed with `modelVariableName.`

**Comment by tanthammar** [comment]
Tested #1445 but I get a new error.

![image](https://user-images.githubusercontent.com/21239634/91884666-c306d880-ec86-11ea-97dd-4632afbc71f1.png)

**Comment by tanthammar** [comment]
```php
use App\User;
use Livewire\Component;

class BlankComponent extends Component
{

    public $user;

    protected $rules = [
        'user.name' => 'required',
        'user.email' => 'required|email',
        'user.friends.*.first_name' => 'required',
        'user.friends.*.last_name' => 'required',
        'user.opening_hours.day' => 'required',
        'user.opening_hours.time' => 'required',
    ];

    public function mount(?User $user)
    {
        $this->user = $user;
    }

    public function submit()
    {
        $this->validate();
        dd($this->user);
    }
```
In blade
```blade
@foreach($field->fields as $array_field)
@php
    $key = $field->type == 'array'
        ? "$field->key.$loop->index.$array_field->name" //nested array
        : "$field->key.$array_field->name"; // else key=>val array
@endphp
//...
```

**Comment by nuernbergerA** [comment]
@tanthammar Updated

**Comment by tanthammar** [comment]
Yes this issue is resolved, but there is something wrong with the error bag.

Will open a new issue on that topic, because I tested it with the latest commit as well.
New issue #1454
