### ISSUE TITLE
[2.0] wire:model.defer chain breakout

### ISSUE THREAD

**Issue by timrspratt** [livewire/livewire#1446]
### Description

Given the following login form, that has the `email` and `password` wire:model inputs set to use the new `defer`, upon submitting the form, the `callMethod` isn't being triggered (to carry out the validation).

I believe this is due to the `return;` within the `hydrate` method of the `HydrationMiddleware` steps from this refactor: https://github.com/livewire/livewire/commit/9faa3253167f27b007be837a1d6f6d672f08aec2#diff-e4a38b0ee99f1cbf22db0335055df882

If I modified the email, and then submitted the form, the `updates` array in the livewire fetch/post would be:

```
...
updates: [
  {type: "syncInput", payload: {name: "email", value: "jon@example.com"}},
  {type: "callMethod", payload: {method: "login", params: []}},
],
...
```

When the hydrate runs for each of these updates, the for loops are detecting if they aren't of the particular type, and `return`-ing, thus in the case of the above, the hydrate for `PerformActionCalls` will first check `updates[0]` which the type is not `callMethod` and so will return, resulting in the `updates[1]` never been checked or called.

Whilst **swapping the `return` to a `continue` seems to sort this behavior**, I haven't gone as far as putting in a PR, as I'm not sure this is actually the correct way – since looping inside each `hydrate` means the actions aren't actually being fired in the order they were carried out. @calebporzio if this doesn't matter, and the `PerformDataBindingUpdates` always runs to update the data before the `PerformActionCalls` fire, then changing these to continue will be ok. However, I'm not sure if the events in `PerformEventEmissions` all running after all the `PerformActionCalls`, may result in any method that fires a `ValidationException` preventing the events in the `update` chain from firing at all either?

For context: the "bug" if that on submitting the below, with only email filled in, the error bag is empty and the password required error doesn't show. This is due to the `login` method never actually being called.

#### login.blade.php
```blade
<form wire:submit.prevent="login" action="#" method="post">
    <x-input.group label="Email" for="email" :error="$errors->first('email')">
        <x-input.text type="email" id="email" wire:model.defer="email" autofocus />
    </x-input.group>

    <x-input.group label="Password" for="password" :error="$errors->first('password')">
        <x-input.text type="password" id="password" wire:model.defer="password" />
    </x-input.group>

    <button type="submit">Login</button>
</form>
```

#### Login.php
```php
class Login extends Component
{
    public string $email = '';
    public string $password = '';

    protected array $rules = [
        'email' => 'required|email',
        'password' => 'required|min:6',
    ];
    
    public function login()
    {
        $credentials = $this->validate();

        if (! auth()->attempt($credentials)) {
            $this->addError('email', trans('auth.failed'));

            return;
        }

        return redirect()->intended('/');
    }

    public function render()
    {
        return view('livewire.auth.login');
    }
}
```

**Context**
- Livewire version: 2 (dev-master)
- Laravel version: 8.x-dev
- Browser: Chrome

**Comment by calebporzio** [comment]
Ooof good catch. I changed the `return`s to `continue`s. Should work great now. Re-open if not.

**Comment by redbastie** [comment]
@calebporzio when is 2.0 being released? i really want to utilize model deferring.
