### ISSUE TITLE
livewire is not Respecting the "config/livewire.php" file values

### ISSUE THREAD

**Issue by Shadief** [livewire/livewire#1447]
### Description

i have done the following configurations to the `config/livewire.php` file : 

```
return [
    'temporary_file_upload' => [
        'disk' => 's3',  
        'rules' => null,
        'directory' => 'tmp', 
        'middleware' => null,
    ],
];
```

the app still saves the temporary file locally , inside the folder "livewire-tmp" which is the default, and when i try to run the clean up command `php artisan livewire:configure-s3-upload-cleanup` in the terminal i get an error with this message : 

`Configuration ['livewire.temporary_file_upload.disk'] is not set to a disk with an S3 driver.`

i have checked the code, and yours, everything seems fine but still didn't work, i have restarted apache and the whole server and still didn't work, i have tried to run the app locally on my computer also got the same results.

the upload to s3 works fine.

what's wrong ?

and i also receive an 422 error (ajax) whenever i try to upload a large file (>10mb) to s3.
my server php.ini limitations are good, also tried locally its the same problem.
it's just with livewire, my other apps work just fine an can upload 5GB without any problem.
also you should probably implement stream uploading/downloading.

**Comment by edgrosvenor** [comment]
@Shadief As for the error on large files, is it over 10mb or over 12 mb where you're running into the error? I ask because there is a default validation limit that Livewire sets. From the docs:

`By default, Livewire will validate ALL temporary file uploads with the following rules: file|max:12288 (Must be a file less than 12MB).`

Is that maybe what's happening on those? To find out, look for a validation error on the field after you try to do a large upload.

**Comment by Shadief** [comment]
yes, over 12mb. but that's not a problem for me anymore.

but the first problem with the temporary file location still exists.

**Comment by dennisvandalen** [comment]
> yes, over 12mb. but that's not a problem for me anymore.
> 
> but the first problem with the temporary file location still exists.

Did you wait 24 hours? Did you check the bucket to see if the rules are applied? It's in the magagement -> lyfecycle rules section of your s3 bucket.

**Comment by calebporzio** [comment]
Closing as the original problem has been resolved. Thanks everyone!

**Comment by mohamedsst3** [comment]
Just Run This in your Project And Thanks me Later php artisan livewire:publish --config
