### ISSUE TITLE
v2 honor wire:model.defer on file input

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1461]
v2 d5660dd

The .`defer` directive is not honored on input `type="file"`

```php
<input wire:model.defer="image" type="file" />
```

**Comment by calebporzio** [comment]
Hey Tina, good call.

Currently, there are no plans to support this. I'll add a note to the docs!

**Comment by tanthammar** [comment]
Ok @calebporzio, 

If it will not be supported, can you help me with how to tell Livewire to wait with the file upload until AlpineJS has done its thing. 

Tried `@entangle` and `@this.set()` but it didn't work.
```blade
<input
    wire:model.defer="{{ $field->name }}"
    x-data="{ files: null}"
    x-on:change.prevent="

        tell livewire to wait

        let alpine do its thing.then(go ahead livewire, upload the file/files) 
    }"
/>
```

**Comment by redbastie** [comment]
@tanthammar you figure it out?

**Comment by tanthammar** [comment]
No sadly not.

**Comment by iamprincesly** [comment]
Do i understand that you are trying to preview image before upload? If so use wire:ignore on the img preview element <img src="someimage.jpg" wire:ignore />

**Comment by asantibanez** [comment]
Hey @tanthammar good afternoon!

Would it help to remove `wire:model` from the file input and handle the upload manually on Alpine with `@this.upload`?

https://laravel-livewire.com/docs/2.x/file-uploads#js-api

Hope it helps.

**Comment by tanthammar** [comment]
Yes @asantibanez that is perfect :)

**Comment by halabe15** [comment]
@asantibanez / @tanthammar ,

Do you have any example of how to use the file upload JS API?

I'm trying to have a multiple file uploader but it's an 3rd-party lib, which works well, but when I write `wire:model` I don't have anymore the previews or the functionality, so I'm trying to connect it through `@this.uploadMultiple` but how to call this method and when?

**Comment by gtim04** [comment]
same.. would love to have an example.
