### ISSUE TITLE
Lifecycle Hooks updated/updating dont work

### ISSUE THREAD

**Issue by PH7-Jack** [livewire/livewire#1465]
### Description
If modification was fired by from a emitter, this hooks dont work

### Steps to reproduce
fire event from componentA to componentB, and set value to one property 

Create 2 components called Form and Input respectively.

Create an "address" model in the Form component, a listener and a function that sets a value for that model

Component A
```
Form.php
<?php

namespace App\Http\Livewire;
 
class Form extends Component
{
     public $address;

    protected $listeners = ['setAddress'];

    public function render()
     {
         return view('livewire.form');
     }

     function setAddress($value) 
     {
          $this->address = $value;
     }

     function updatedAddress($value) 
     {
          $this->address = "{$value} - this pass";
     }
}

form.blade.php

<div>
   {{ $address }}
  <br>
  <livewire:input />
</div>

```

Component B

```
Input.php
<?php

namespace App\Http\Livewire;
 
class Input extends Component
{
    public function render()
     {
         return view('livewire.input');
     }
}

input.blade.php

<div>

<button wire:click="$emit('setAddress', '33rd avenue')">set address = 33rd avenue</button>

</div>
```

In the Input component, create a button that sends an event to the Form component, this will update the value of the model "address"

**Comment by stevebauman** [comment]
Hi @PH7-Jack,

Please post some example code and actual steps to reproduce. Thanks!

**Comment by PH7-Jack** [comment]
Updated

**Comment by stevebauman** [comment]
The `$listeners` property must be a key => value pair. The key must be the event name, and the value must be the method name to call.

Try updating that, and give it a shot. I’m not at a computer right now, but I don’t think you’re able to use only values in the `$listeners` component property.

**Comment by PH7-Jack** [comment]
It is possible to use the listeners without needing a key, as long as it has the same name as the function.
But my problem is not with it, because it works, the problem is with the updatedFoo or updatingFoo hook, when the variable changes, it is not called, except if I change this variable by the component itself, an example of this is by a wire:model in an input, the method is called, but it doesn't work when modifying it by an event

**Comment by stevebauman** [comment]
Oh okay I understand now, my apologies @PH7-Jack.

Since you're modifying the property itself, Livewire won't detect this and call the `updating` and `updated` methods. You will have to use the `syncInput` method:

```php
namespace App\Http\Livewire;
 
class Form extends Component
{
     public $address;

    protected $listeners = ['setAddress'];

    public function render()
     {
         return view('livewire.form');
     }

     public function setAddress($value) 
     {
           $this->syncInput('address', $value);
     }

     public function updatedAddress($value) 
     {
          $this->address = "{$value} - this pass";
     }
}
```

The `syncInput` method calls these methods and then sets the property on the component:

https://github.com/livewire/livewire/blob/a64275714875450a7e77a018dc3aa2d9d3593ac8/src/ComponentConcerns/HandlesActions.php#L21-L42

Give that a shot 👍

**Comment by calebporzio** [comment]
Yep Steve nailed it, Thanks @stevebauman!
