### ISSUE TITLE
Laravel Jetstream throwing livewire error on visiting account settings

### ISSUE THREAD

**Issue by LewisLarsen** [livewire/livewire#1467]
### Description
When visiting the `user/profile` route with Laravel Jetstream livewire configured, the application throws an error as a method relating to Livewire cannot be found. Wiping the application and starting anew has no bearing and continues to error.

I have managed to reproduce this consistently, even deleting the docker container and starting completely fresh still produces this.

`Method Illuminate\View\ComponentAttributeBag::wire does not exist.` (Log below)

Shared Log from app: https://flareapp.io/share/4m4lRJmM#F56

### Steps to reproduce
Install a copy of Laravel 8 with composer
```
composer require laravel/sanctum livewire/livewire laravel/jetstream
php artisan jetstream:install livewire
npm install && npm run dev
php artisan migrate
```
Log in and proceed to visit the `user/profile` route.
**Context**
- Livewire version: [1.3]
- Laravel version: [8.x-dev]
- Jetstream version: [0.6.4]
- PHP version: [7.3.22]
- Browser: [Chrome]

Let me know if there is any other information that may be helpful, I'll do my best and dig it up for you!

Lewis

**Comment by nuernbergerA** [comment]
Currently, only `<live:` works in dev-master. This will change **before** v2 release

**Comment by nuernbergerA** [comment]
Hey Lewis,

i assume you installed livewire wrong in this context.

```bash
php artisan jetstream:install livewire
```
or
```bash
composer require livewire/livewire:^2.0
```

**Comment by calebporzio** [comment]
Yep, Jetstream only supports Livewire version 2 or greater. Upgrade and you should be all set!
