### ISSUE TITLE
(Jetstream) Route::livewire() not work

### ISSUE THREAD

**Issue by ClementN** [livewire/livewire#1469]
### Description

Route::livewire() not work on routes/web.php

```Route::livewire('/test', 'test');```

I get the following error:

```
InvalidArgumentException
Attribute [livewire] does not exist.
```

### Steps to reproduce

1. ```laravel new test8 --dev```
1. ```composer require laravel/jetstream```
1. ```php artisan jetstream:install livewire --teams```
1. ```npm install && npm run dev```
1. ```php artisan make:livewire test```
1. edit routes/web.php
```Route::livewire('/test', 'test')->name('test');```

**Context**
- Livewire version: 1.3
- Laravel version: 8.x-dev
- Jetstream version: 0.6.4
- Browser: Chrome

**Comment by nuernbergerA** [comment]
See laravel/jetstream#57
