### ISSUE TITLE
SupportBrowserHistory error with query string array

### ISSUE THREAD

**Issue by SRWieZ** [livewire/livewire#1483]
### Description

> json_decode() expects parameter 1 to be string, array given
>vendor/livewire/livewire/src/RenameMe/SupportBrowserHistory.php on line 32
> http://myproject.local/nouveautes?f%5B1%5D%5B0%5D=1

I'm encountering an issue when query string parameter is an array.

```
    public $f = [];

    protected $queryString = [
        'f'                => ['except' => false],
    ];
```

In mount()
```
        $this->fill($request->only(array_keys($this->queryString)));
```

And the checkbox : 
```
 wire:model="f.{{ $option_id  }}.{{ $loop->index }}"
```

### Steps to reproduce
- Make a Full-Page Component with a checkbox data binded and querystring updated to a public property 
- Check the box
- Reload the page (with the new url)

**Context**
- Livewire version: 2.0.0
- Laravel version: 7.27.0
- Browser: Chrome

**Comment by calebporzio** [comment]
Thanks for the issue. It's fixed and pushed in version 2.0.2

**Comment by rtconner** [comment]
Thank you, this fix worked.

**Comment by luchaos** [comment]
Query string array syntax seems to be broken in 2.2.4 again?

`.../user/test/comments?page%5Bnumber%5D=1&page%5Bsize%5D=10`
