### ISSUE TITLE
No error when multiple root tags are used

### ISSUE THREAD

**Issue by Roboroads** [livewire/livewire#1493]
### Description
I have been guessing for hours why my app wasn't working - until I remembered that Vue.JS wasn't happy with more than one root tag - wrapping everything in a div resolved the issue. Unsure if this is intended or not since I haven't found this yet in the documentation (or read over it 15 times - in which case excuse me). If this is intended, there should be some kind of error/warning.

### Steps to reproduce
Create a new livewire component with multiple root tags like so:

```php
// Reproduce.php
class Reproduce extends Component
{
    /** @var string */
    public $someText = '';
}
```

This works:
```html
<!--reproduce.blade.php-->
<div>
    <div>
        <input wire:model="someText">
    </div>
    <div>
        <input wire:model="someText">
    </div>
</div>
```

This does not:
```html
<!--reproduce.blade.php-->
<div>
    <input wire:model="someText">
</div>
<div>
    <input wire:model="someText">
</div>
```

**Context**
- Livewire version: 2.0.3
- Laravel version: 7.27.0
- Browser: Chrome

Note: I do have some time to look into creating a warning for this and PR-ing it - but would like to know what is intended before I put time into it :smile:

**Comment by mblarsen** [comment]
Yes, this is a known limitation. I'm not sure that anything has changed for version 2; but I think that it is being addressed. You need to have a single root for now.

**Comment by nuernbergerA** [comment]
It's still unsupported

**Comment by damms005** [comment]
As long as this remains unsupported, it will be helpful if livewire throws an exception message when there are more than one root tags.

Also, it will be more helpful if the exception message says "...read more at https://laravel-livewire.com/docs/1.x/rendering-components#returning-blade"

This will help debug issues faster, as I slept on a bug and just waking up to see this multi-root tag issue was the thing

**Comment by Roboroads** [comment]
Ah!! There it is, i was sure it should have been somewhere in the docs and i read over it. I will see if i have some time today to create a PR to add a warning.

**Comment by calebporzio** [comment]
Closing (See my comment on the PR) - Thanks!
