### ISSUE TITLE
[Question] Pagination

### ISSUE THREAD

**Issue by adevade** [livewire/livewire#150]
I read [Branick Weixs post on Medium about pagination with Livewire](https://medium.com/@branick/search-with-laravel-livewire-cb6dcd4ad541) and thought that I'd try to make a PR borrowing some ideas. 

I dove into the source and found that Livewire already supports pagination! By adding the trait `Livewire\WithPagination` to your component it just works.
It's not documented anywhere (I think). Is the implementation here to stay?

**Comment by bdweix** [comment]
Hey @adevade! I just noticed the same thing. Looks like Caleb already had it built in 👍. There is a [repo here](https://github.com/calebporzio/livewire-docs) for the docs and I was going to work on a PR to add it in. Feel free to go ahead and add it. I'd like to add support for all the default Laravel pagination view styles here as well.

**Comment by calebporzio** [comment]
Ooops yeah, that's a feature I added and never documented.

It's definitely here to stay. I'd love a PR to the docs and a PR for the default styles would be great too! Thanks!

**Comment by adevade** [comment]
Looks like it's [in the docs](https://laravel-livewire.com/docs/pagination/) now! Closing! 👀

**Comment by calebporzio** [comment]
Thanks!
