### ISSUE TITLE
[V2] JS hook afterDomUpdate has no alternative in the new version

### ISSUE THREAD

**Issue by Dimonka2** [livewire/livewire#1500]
### Description
I need to initialize a Bootstrap Select after a button click in a sub component and in the V1 it was pretty strait forward:

```js
        document.addEventListener("livewire:load", function(event) {
            window.livewire.hook('afterDomUpdate', () => {
                initBSPickers(); // this is initialization
            });
```

Now I tried all combinations of possible hooks and there is no identical result. All of them firing at wrong time point. 
'component.initialized' - no bs initialization
'element.initialized' - too early, no selected elements
'element.updated' - no bs initialization

Why V2 has to break such useful basic functionality?

**Context**
- Livewire version: 2.0.4
- Laravel version: 7.27.0
- Browser: Firefox

**Comment by ninthspace** [comment]
According to the docs, `message.processed` is the replacement for `afterDomUpdate`.

**Comment by Dimonka2** [comment]
Thanks, this works! Found it in documentation, not obvious what is meant by "message".
