### ISSUE TITLE
$queryString and back button bug

### ISSUE THREAD

**Issue by deanzod** [livewire/livewire#1501]
Possible bug.

I have some checkboxes used to filter some results from an eloquent query.

- If I click checkbox1, filter works,
- then checkbox2, filter works,
- then back button, filter works and checkbox2 unchecks,
- then back button, filter works but checkbox1 doesn’t uncheck.

This is very consistent behaviour where it seems it doesn’t like the first checkbox clicked but is happy to re-render all subsequent ones even though the url looks correct and a page refresh unchecks the box as expected.

### Steps to reproduce

In the livewire view-file:

```

<input id="chk1" type="checkbox" wire:model="type" value="one">
<input id="chk2" type="checkbox" wire:model="type" value="two">
<?php var_dump($type)?>

```

In the livewire class:

```

 protected $queryString = ['type'];
 public function render() {
      // eloquent query here
      return view('livewire.view-file');
 }

```

Load page, click one checkbox, then the next then click back then back again. First one checked will not be unchecked. var_dump shows correct output though. This applies to any form input, not just checkboxes.

**Context**
- Livewire version: 2.0
- Laravel version: 7.26.1
- Browser: Chrome

**Comment by ryatkins** [comment]
I also have this issue where radio buttons aren't showing as they were selected after I hit back through a form wizard.

**Comment by deanzod** [comment]
UPDATE: I was starting to think maybe this isn't the responsibility of Livewire and maybe just default behaviour of form elements with the back button. But testing this again with a text input I...

I added a text input to filter my query by the name typed in the text input. Like before, I load the page, type a name, it filters as expected & includes search in url. Type a 2nd name, same again. Click back and the filter results update correctly but again the form field is stuck on the last thing I typed.

Next I added a couple of buttons to the page to update the search instead of using the text input.

e.g.

```

            <button wire:click="$set('search', 'Frank')">A name</button>
            <button wire:click="$set('search', 'Bill')">Another name</button>


```

If I click those one after another the filter works and the text in the input updates along with it. If I click back button it works perfectly and does update the text in the input. (although the 3rd and last back click does not empty the input back to its initial state)

At the moment it feels like a solution would be to hide form elements on blur and replace with the values or fake css checkboxes. Or do we need to fire events and write some js to update the form fields to match the state? It is at that point I wonder if maybe this _should_ be the responsibility of Livewire

**Comment by DanielCoulbourne** [comment]
@calebporzio this is probably the same cause as what we were hacking on earlier where `excepts` was failing. The fix from before should close this as well

**Comment by deanzod** [comment]
@DanielCoulbourne unfortunately not. The update did fix the `excepts` issue but not this one :(

**Comment by almazdanilov** [comment]
Livewire V3.4.4 now has this bug again.
