### ISSUE TITLE
@entange not updating from Livewire for array

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#1502]
```html
<div x-data="{ address: @entangle('a.address').defer }">
    <input type="text" x-model="address" />
</div>
```

```php
public $a = [];

public function updated($field) {
    if ($field='a.address') { $a['address'] = rand(); }
}
```

The data will save to Livewire fine, but the data returned in the response does not change the `address` data.

**Comment by jimpeters** [comment]
This should be fixed in v2.2.0 which came out today!  Hooray for @calebporzio !

**Comment by jimpeters** [comment]
Also, in your example code you are using an assignment (=) instead of a comparison (==) operator.

```php
if ( $field='a.address' )
```

Should be

```php
if ( $field == 'a.address' )
```

**Comment by jjjrmy** [comment]
> Also, in your example code you are using an assignment (=) instead of a comparison (==) operator.
> 
> ```
> if ( $field='a.address' )
> ```
> 
> Should be
> 
> ```
> if ( $field == 'a.address' )
> ```

My mistake, typo - this was just some example code, not what I'm actually using.

**Comment by zepfietje** [comment]
Has this bug been fixed already? I think I'm running into something similar.

**Comment by jjjrmy** [comment]
Closed
