### ISSUE TITLE
[2.x] Eloquent Collection using ->select() is emptied while component is re-rendering

### ISSUE THREAD

**Issue by YannickYayo** [livewire/livewire#1503]
### Description
When using an Eloquent Collection as a public property, i can initialize it like below :
``` php
$this->users = User::query()
        ->orderBy('email')
        ->get();
```
This Collection is kept over component re-rendering.

But if i use a `->select()` on it : 
``` php
$this->users = User::query()
        ->select('name')
        ->orderBy('email')
        ->get();
```
Now when the component is re-rendering after a request, I got an empty Collection, my users disappear.

### Steps to reproduce

1. Create a Livewire component, ex: collection-test
2. CollectionTest.php : 
``` php
<?php

namespace App\Http\Livewire;

use App\User;
use Illuminate\Support\Collection;
use Livewire\Component;

class CollectionTest extends Component
{
    public Collection $users;

    public function mount(): void
    {
        $this->users = User::query()
            //->select('name')
            ->orderBy('email')
            ->get();
    }

    public function render()
    {
        return view('livewire.collection-test')
            ->extends('layouts.base');
    }
}
```
3. collection-test.blade.php : 
```  html
<div>
    @dump($users)
    <button wire:click="$refresh">
        Refresh
    </button>
</div>
```
4. Click on the button to refresh the Livewire Component, see that `$users` still an Eloquent Collection with records.
5. Uncomment the `->select()` line on the `CollectionTest.php` file : 
``` php
<?php

namespace App\Http\Livewire;

use App\User;
use Illuminate\Support\Collection;
use Livewire\Component;

class CollectionTest extends Component
{
    public Collection $users;

    public function mount(): void
    {
        $this->users = User::query()
            ->select('name') // Uncomment this line
            ->orderBy('email')
            ->get();
    }

    public function render()
    {
        return view('livewire.collection-test')
            ->extends('layouts.base');
    }
}
```
6. Click on the button to refresh the Livewire component, see now that `$users` is an empty Eloquent Collection.

**Context**
- Livewire version: 2.0.4
- Laravel version: 7.27.0
- Browser: Brave

**Comment by calebporzio** [comment]
Off hand it looks like the issue is that you aren't adding `id` to the list of `->select()`s.

Try using: `->select('id', 'name')` instead and see if the problem still persists. If it does, re-open this issue. Thanks!

**Comment by YannickYayo** [comment]
I've updated my `->select()` to include the `id`, the collection is not empty when refreshing the Livewire component now, but I have another issue :( 
When refreshing, Models on my collection don't care about the `->select()` and take all the attributes.

CollectionTest.php : 

``` php
<?php

namespace App\Http\Livewire;

use App\User;
use Illuminate\Support\Collection;
use Livewire\Component;

class CollectionTest extends Component
{
    public Collection $users;

    public function mount(): void
    {
        $this->users = User::query()
            ->select('id', 'name')
            ->orderBy('email')
            ->get();
    }

    public function render()
    {
        return view('livewire.collection-test');
    }
}
```

collection-test.blade.php
``` html
<div>
    @dump($users)
    <button wire:click="$refresh">
        Refresh
    </button>
</div>
```
Before clicking on the Refresh button : 
![livewire_collection_1](https://user-images.githubusercontent.com/9850323/92603940-307ebe80-f2b0-11ea-8907-be7ecd289b11.png)

After clicking on the Refresh button : 
![livewire_collection_2](https://user-images.githubusercontent.com/9850323/92603965-3b395380-f2b0-11ea-8030-0ee2f230c59e.png)

It is important to me to have the `->select()` because sometimes i need to rename the column like `->select('id', 'name as value')`.

**Comment by YannickYayo** [comment]
PS : Seems like I can't re-open this issue.

**Comment by forgng** [comment]
I'm experiencing a similar behaviour. In the mount method i'm making a query to fetch some models, with select and count. 
```php
public $packs;
 public function mount()
    {

        $this->packs = Pack::select('id', 'name')
            ->withCount('likes')
            ->take(9)
            ->get();
    }
```
When the component is re rendered the query executed is:
```sql
select * from `packs` where `packs`.`id` in (1, 2, 3, 4, 5, 6, 7, 8, 9)
```
losing the select and count.

**Comment by austenc** [comment]
@YannickYayo 

Does using a [Computed Property](https://laravel-livewire.com/docs/2.x/properties#computed-properties) allow you to work around this issue?

**Comment by redbastie** [comment]
+1

I'm losing all model counts on re-render.

**Comment by YannickYayo** [comment]
@austenc Yes, using computed property is the way right now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
