### ISSUE TITLE
[2.x] @entangle seems to not working

### ISSUE THREAD

**Issue by YannickYayo** [livewire/livewire#1505]
### Description
I used the new `@entangle` blade directive with the example provided in the [doc](https://laravel-livewire.com/docs/2.x/alpine-js).
The modal is not closing when the `$showDropdown` property is set to `false` from Livewire.

### Steps to reproduce
1. Make a new Livewire component. Ex : dropdown
2. Dropdown.php : 
``` php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Dropdown extends Component
{
    public $showDropdown = false;

    public function archive()
    {
        $this->showDropdown = false;
    }

    public function delete()
    {
        $this->showDropdown = false;
    }

    public function render()
    {
        return view('livewire.dropdown');
    }
}
```
2. dropdown.blade.php : 
``` html
<div x-data="{ open: @entangle('showDropdown').defer }">
    <button @click="open = true">Show More...</button>

    <ul x-show="open" @click.away="open = false">
        <li><button wire:click="archive">Archive</button></li>
        <li><button wire:click="delete">Delete</button></li>
    </ul>
</div>
```
3. Click on "Show More...", you will see the two buttons "Archive" and "Delete" appears.
4. Click on the button "Archive" or "Delete", the dropdown should closes, but nothing happen. Seems like the `open` data on Alpinejs is still `true` and doesn't reflect the value from Livewire's `$showDropdown`.

**Context**
- Livewire version:2.0.4
- Laravel version: 7.27.0
- Browser: Brave

**Comment by calebporzio** [comment]
Ok, I think I know the problem.

This should work without .defer added.

I will look into solving this though

**Comment by YannickYayo** [comment]
Yes I confirm that without `.defer` this is working.

**Comment by fontenele** [comment]
Here did not worked, with and without `.defer`

**Comment by jjjrmy** [comment]
Think this is same issue as mine #1502

**Comment by austenc** [comment]
@YannickYayo is this still an issue for you with version `2.3.0`?

If so, which version of Alpine are you using?

**Comment by danielreales7** [comment]
Hi,

I have a problem with somtehing like this. I have a live search:

`<div x-data="{ sh: @entangle('autocomplete') }" class="flex justify-between p-6 px-2 sm:px-5 bg-white border-b border-gray-200 rounded-lg">
        <div>
            <label for="from" class="block text-sm leading-5 font-medium text-gray-700">From</label>
            <div class="mt-1 relative rounded-md shadow-sm">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <span class="text-gray-500 sm:text-sm sm:leading-5">
                    <svg class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
                      />
                    </svg>
                  </span>
                </div>
                <input id="from" name="from" wire:model.debounce.500ms="search" @click.away="sh = false" @close.stop="sh = false" class="form-input block w-full pl-10 pr-12 sm:text-sm sm:leading-5" placeholder="Madrid">
                @if(count($searchResults) > 0)
                    <div x-show="sh" class="origin-top-left absolute left-0 mt-2 w-60 rounded-md shadow-lg">
                        <div class="rounded-md bg-white shadow-xs">
                            <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                                @foreach($searchResults as $result)
                                    <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900" role="menuitem">{{ $result->name }}</a>
                                @endforeach
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>`

If I write  2 letters, it search correctly and show the modal, but if I use `@click.away` and I try to write again, the modal not show again. I think the property in the component is not updating.

My component is this:

`class Search extends Component
{
    protected $tournaments;
    protected $airports;
    public $adults = 1;
    public $childs = 0;
    public $rooms = 1;
    public $names = [];
    public $date;
    public $search;
    public $autocomplete = false;

    public function render(Tournaments $tournaments, Flights $airports)
    {
        $this->tournaments = $tournaments->all();
        $searchResults = [];
        if(strlen($this->search) >= 2) {
            $this->autocomplete = true;
            $searchResults = $airports->findAirports($this->search);
        }

        return view('livewire.search', [
            'tournaments' => $this->tournaments,
            'searchResults' => $searchResults
        ]);
    }`

What am I doing wrong?

Thank you so much!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
