### ISSUE TITLE
WithPagination focus remains when clicking previous or next

### ISSUE THREAD

**Issue by MaxGiting** [livewire/livewire#1509]
If you navigate to page 3 or higher and then click the previous page button in the pagination, this button will retain focus until you click back all the way to page 1 when the previous button is changed to a <span> element.
<img width="177" alt="Screenshot 2020-09-08 at 21 41 41" src="https://user-images.githubusercontent.com/9828591/92525635-1abfb980-f21c-11ea-96a6-038be36cf186.png">

@timrspratt I wonder if you have any thoughts on this. In the end I tried adding wire:key to everything, but cannot figure out how to stop this.

**Context**
- Livewire version: 2.1.0
- Laravel version: 7.21.0
- Browser: Chrome

**Comment by timrspratt** [comment]
@MaxGiting is this your custom view or the livewire version? If it's a custom, are you able to share the blade file?

**Comment by MaxGiting** [comment]
Sorry should have mentioned. This is with the default pagination. I moved to it with v2 😄

**Comment by timrspratt** [comment]
Bootstrap or tailwind? I've just tried the tailwind version and all seems ok, the focus doesn't remain once page navigation occurs

**Comment by timrspratt** [comment]
It may be related to the changes here: https://github.com/livewire/livewire/commit/dc436f3b8246e6b69af08f1cd5a5acd22feda956

**Comment by timrspratt** [comment]
@calebporzio with the changes in https://github.com/livewire/livewire/commit/dc436f3b8246e6b69af08f1cd5a5acd22feda956 the issue where words disappear has sprung back up. Were the `wire:key` attributes removed on purpose?

**Comment by MaxGiting** [comment]
Upgraded to v2.1.4 using default tailwind pagination
Yes the words are disappearing again and I am still seeing the back and forward arrows stay highlighted when moving to pages other than the first or last ones.

**Comment by calebporzio** [comment]
Hey there, can you make sure these issues are occurring on v2.1.1 or greater?

Also, what do you mean by "words disappearing".

I would love a Gif and a simplified blade view to recreate this issue.

Thanks!

**Comment by timrspratt** [comment]
@calebporzio hey! I've just created one (before even seeing this reply!)

https://github.com/livewire/livewire/issues/1558

I just paginated my data set by 3 per page and had 15 entries. It's using the stock tailwind view. Thanks!

**Comment by MaxGiting** [comment]
@timrspratt in #1558 the gif you provided shows the same behaviour as my original issue. The previous and next arrows stay highlighted until you get to each respective end.

For example when your mouse hovers over the missing "of" the previous button is still highlighted.

**Comment by timrspratt** [comment]
One for @calebporzio since I'm not sure it's a bug. I agree that there is now a difference between one of the page links being clicked (since they switch to spans when the active page and so will lose the focus), but the previous/next buttons only do that when at "the end of the line" as they switch from being buttons. Therefore, they remain buttons and unchanged on the dom

**Comment by MaxGiting** [comment]
Thanks @timrspratt glad you understand my initial issue 😃  and I completely agree with why it is hard to get them to unfocus, due to the dom not changing on these buttons between most page changes.

I guess obviously I would think it is a bug as I reported it, but yeah not a huge one and can't easily see how it would be fixed either.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
