### ISSUE TITLE
Error in console after loading page

### ISSUE THREAD

**Issue by SystemApp-scrl** [livewire/livewire#1511]
### Description
I have the following error in the console when loading the page and after that i have to close the tab, and reopen the pagein another tab.
This is the error:

`Uncaught 
Exception
​
columnNumber: 0
​
data: null
​
filename: "http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f"
​
lineNumber: 13
​
message: ""
​
name: "NS_ERROR_ILLEGAL_VALUE"
​
result: 2147942487
​
stack: "SyncBrowserHistory/<@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:124905\nvalue/<@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:2029\nvalue@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:1992\ncall@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:2783\ncallHook@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:6255\nComponent@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:104576\nvalue/<@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:127400\nvalue@http://192.168.0.34:8080/livewire/livewire.js?id=d3352e4f7c3be3e22a1f:13:127348\n@http://192.168.0.34:8080/anagrafiche:56:25\nEventListener.handleEvent*@http://192.168.0.34:8080/anagrafiche:55:14\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
livewire.js:13
    SyncBrowserHistory SyncBrowserHistory.js:12
    value MessageBus.js:17
    forEach self-hosted:216
    value MessageBus.js:16
    call HookManager.js:36
    callHook Store.js:120
    Component index.js:45
    value index.js:77
    forEach self-hosted:216
    value index.js:76
    <anonima> anagrafiche:56
    (Asinc.: EventListener.handleEvent)
    <anonima> anagrafiche:55
`

### Steps to reproduce
Reload two or three times the page and the error pops up.

**Context**
- Livewire version: 2.1.2
- Laravel version: 7.28.0
- Browser: Firefox

**Comment by andybeesee** [comment]
Same thing here on Firefox 80.0 - it does not seem to happen in Chrome or Safari.

**Comment by michele-grifa** [comment]
I have the same error on Firefox 78.0. All of the livewire component become unresponsive after that.

**Comment by kendaniels** [comment]
Same error here, Firefox 80.0.1 on Mac.

It happens seemingly randomly after refreshing the page, but not on every refresh. It's random. Once I get the error after a refresh, the error then happens on every subsequent refresh.

Clicking a link within my application (even a link for the same page) gets rid of the error and Livewire components work again. Refresh x number of times and the error happens again, rendering Livewire components inoperable.

**Comment by jimpeters** [comment]
Have you upgraded to the latest version of Livewire and re-tested?  I also had issues in firefox until he released v2.1.4 yesterday with the following update.

"In firefox, there was a history.state storage max that was causing errors, moved storage to sessionStorage"

**Comment by kendaniels** [comment]
> Have you upgraded to the latest version of Livewire and re-tested? I also had issues in firefox until he released v2.1.4 yesterday with the following update.
> 
> "In firefox, there was a history.state storage max that was causing errors, moved storage to sessionStorage"

That fixed it for me, thank you. 

Can't keep up with all of the releases although I should have checked before posting.

Thanks for your help!

**Comment by jimpeters** [comment]
It's been a fun wild ride this week.  Just put a cron job in your system to composer upgrade livewire/livewire every 60 minutes and you may save yourself some headaches :)

I would highly recommend going to the Github repo webpage for livewire/livewire and 'Watching' releases only to get an email when a new version comes out.  They always have very good release notes.  It's helped me a ton this week to make sure I'm not going crazy sometimes when I encounter something weird.

**Comment by SystemApp-scrl** [comment]
After the update 2.1.4 the problem seems fixed. Thanks.
