### ISSUE TITLE
Turbolinks full reload on successful form submit with redirect response (ver 2.0)

### ISSUE THREAD

**Issue by khanalpride** [livewire/livewire#1514]
### Description
On Livewire 1.0, it was all good. 

After upgrade from 1.0 => 2.0, turbolinks behavior was a bit different.
With upgrade guide, I was able to use turbolinks without any issue. everything seems working.
But,
On form submit, turbolinks does full browser reload, if there is redirect response. For eg.
When form has error, and we return validate response using `$this->validate()`, it works fine, no full reload.

When form is successful, data is saved, and I redirect to other page using `return redirect()->route('dashboard');`
it reloads whole browser.

### Steps to reproduce
- Install livewire in clean laravel project.
- Add turbolinks
- Check 1.0 => 2.0 upgrade guide, and used the code from `https://github.com/livewire/turbolinks`
- create a simple livewire component with form
- submit form `wire:submit.prevent="formSubmit"`

**Context**
- Livewire version: [e.g. 2.0]
- Laravel version: [e.g. 7.0]
- Browser: [e.g. Chrome]

**Comment by calebporzio** [comment]
Ok, I think there was an issue with the snippet from the upgrade guide (it's fixed now)

Try adding the script tag with the following snippet: (notice the new `data-turbolinks-eval` attribute)
```html
<script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js" data-turbolinks-eval="false"></script>
```

This should fix everything (and also do a `composer update livewire/livewire` and  a hard refresh to get the new javascript version)

If this doesn't fix your problem, you can re-open this issue.

Thanks!
