### ISSUE TITLE
I got a lot of ErrorException(code: 0): Undefined index: fingerprint

### ISSUE THREAD

**Issue by wira-sandy** [livewire/livewire#1520]
### Description
I got ErrorException(code: 0): Undefined index: fingerprint at class Request
### Steps to reproduce
Updating livewire to V2
**Context**
- Livewire version: [e.g. 2.0.0]
- Laravel version: [e.g. 7.0.0]
- Browser: [e.g. Chrome, Safari]

**Comment by aaronmyatt** [comment]
I suspect I am experiencing the same issue, it seems an injected property `wire:initial-data` could be mangling it's json:

```
<div wire:id="ov5eHeoSeFdasepIHHh7" wire:initial-data="{&quot;fingerprint&quot;:{&quot;id&quot;:&quot;ov5eHeoSeFdasepIHHh
```

**Comment by calebporzio** [comment]
@wira-sandy  - are you using Turbolinks in your application? (Or the livewire/vue adapter?)

If not, have you `artisan view:clear`ed?

Thanks!

**Comment by aaronmyatt** [comment]
@calebporzio please excuse my naive laravel/php understanding, but after a little more digging I've tested my way to:

`htmlspecialchars(User::all()->first())`
`"{&quot;id&quot;:1,&quot;name&quot;:&quot;Trent Koelpin IV&quot;,&quot;email&quot;:&quot;email@gmail.com&quot;,&quot;email_verified_at&quot;:&quot;2020-09-09T16:09:32.000000Z&quot;,&quot;created_at&quot;:&quot;2020-09-09T16:09:32.000000Z&quot;,&quot;updated_at&quot;:&quot;2020-09-09T16:09:32.000000Z&quot;,&quot;slug&quot;:null,&quot;github_id&quot;:null,&quot;github_token&quot;:null}"`

Not parsable by `JSON.parse`. 
`SyntaxError: Unexpected token & in JSON at position`

https://github.com/livewire/livewire/blob/38efc158e227a864c21bac907a94d80128d50fbf/src/HydrationMiddleware/AddAttributesToRootTagOfHtml.php#L43

![Screenshot 2020-09-11 at 00 25 17](https://user-images.githubusercontent.com/11920225/92762556-4a5df580-f3c5-11ea-9f88-5024f08a69e8.png)

Or it just comes out `null` ☝️

**Comment by aaronmyatt** [comment]
FWIW, after removing a nested component and instead triggering an update via `$emit`, it resolved my issue.

**Comment by imliam** [comment]
If you're adding new components (ie. nested ones) dynamically to the page, #1560 should have fixed the problem for you by not trying to re-initialise existing components.

**Comment by calebporzio** [comment]
Great, I'd love to know what the issue was though still! Something tells me there were some weird characters stored in a variable passed into the nested component.

Anyhow, I'd love to know more so we can fix this for future cases. Thanks!

**Comment by stancl** [comment]
@calebporzio Are you using dynamic components here?

Might be related to https://github.com/laravel/framework/issues/34346

**Comment by calebporzio** [comment]
Closing this as it it's been resolved for now.

**Comment by iaK** [comment]
This can also happen if you don't have "http://" in the APP_URL value in your .env. 
```
# WRONG!
APP_URL=localhost

# RIGHT
APP_URL=http://localhost
```
