### ISSUE TITLE
Incorrect validation attribute for model keys

### ISSUE THREAD

**Issue by zepfietje** [livewire/livewire#1524]
### Description

When validating model keys such as `user.first_name`, the validation attribute in the error message becomes `first_name`.
`The first_name field is required.`

However, when validating a non-model value e.g. `first_name`, the validation attribute does correctly show `first name`.
`The first name field is required.`

Also, when validating model keys, validation attribute localization (defined in e.g. `resources/lang/en/validation.php`) is not taken into account.

### Steps to reproduce

**Context**
- Livewire version: 2.1.3
- Laravel version: 8.0.3
- Browser: Firefox

**Comment by zepfietje** [comment]
Livewire's automatic nested model attribute stripping uses Laravel's [custom validator attributes](https://github.com/livewire/livewire/blob/master/src/ComponentConcerns/ValidatesInput.php#L133). However, Laravel skips the [attribute processing](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/FormatsMessages.php#L236) (getting translations, adding spaces) for custom attributes. This results in e.g. `user.first_name` to be displayed as `first_name` and also doesn't allow you to translate it. What do you think would be the best solution @calebporzio?

**Comment by isaackearl** [comment]
+1 also seeing this issue in 2.2.3 

the validation messages are ugly.  I managed to fix them in SOME situations by adding a custom messages block to my livewire component like so:

`    public function messages()
    {
        return [
            'user.first_name.required' => 'First name is required',
            'user.last_name.required' => 'Last name is required',
            'user.last_name' => 'please',
            'region.id.required' => 'Please select a region',
        ];
    }`

However these messages don't seem to apply anymore once you try and use the "validateOnly($propertyName)" method.  So in other words, I found a workaround for regular validation with $this->validate(), but not for $this->validateOnly... which I need.

**Comment by calebporzio** [comment]
Yes, this was an oversight. Livewire intelligently removes the model name from the model attribute for validation messages.

This is fine except for when you want to register custom attributes to change something like `post.title` in a custom attribute.

The next version will have this fixed and you can properly set global attribute overrides: c8d1e37

**Comment by overdrive2** [comment]
What I tried and it worked.
//--------------------------------------------------------//
protected $attributes = [
            'user.first_name' => 'First name',
            'user.last_name' => 'Last name',
            'region.id' => 'region',
        ];
public function submit()
{
    $this->validate($this->rules(),null, $this->attributes);
}

**Comment by bnqtoan** [comment]
@overdrive2 change it to `$validationAttributes`
https://laravel-livewire.com/docs/2.x/input-validation
