### ISSUE TITLE
"DOMException: The operation is insecure" on HTTPS

### ISSUE THREAD

**Issue by orkhanahmadov** [livewire/livewire#1529]
### Description

Livewire page throws "DOMException: The operation is insecure" error when page is loaded over HTTPS.

### Steps to reproduce

You can visit this page to see the error: [https://staging.godiscoverazerbaijan.com/tours/frederic-reynolds](https://staging.godiscoverazerbaijan.com/tours/frederic-reynolds)

Same page over IP address (without HTTPS): [http://207.154.200.15/tours/frederic-reynolds](http://207.154.200.15/tours/frederic-reynolds)

**Context**
- Livewire version: 2.1.3
- Laravel version: 8.0.3
- Browser: Firefox and Chrome

Firefox shows cryptic error:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/7041590/92779869-baa74f80-f3a2-11ea-814b-ee0e0b9bac0e.png">

Chrome show better error info:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/7041590/92778633-a44cc400-f3a1-11ea-81f1-cbf577593cb7.png">

This is my scripts/styles I'm using on my main layout file:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/7041590/92777967-00fbaf00-f3a1-11ea-8097-bce54922cdb7.png">

And this is what I have in `app.js`
<img width="343" alt="image" src="https://user-images.githubusercontent.com/7041590/92778135-2e485d00-f3a1-11ea-8162-722b68e7ae2f.png">

Also I'm using new [livewire/turbolinks](https://github.com/livewire/turbolinks)

**Comment by matter3** [comment]
I was running into this issue and it was due to the response from `url()->current()` in `SupportBrowserHistory.php` having a `http` prefix as opposed to `https`. I was able to fix this by the second snippet to my `AppServiceProvider.php`, although would like to know if there is a better way.

```
        Livewire::listen('component.dehydrate.initial', function (Component $component, Response $response) {
            $queryParams = $this->mergeComponentPropertiesWithExistingQueryParamsFromOtherComponentsAndTheRequest($component);

            $response->effects['path'] = url()->current().$this->stringifyQueryParams($queryParams);
        });
```

```
if ($this->app->environment('production')) {
    URL::forceScheme('https');
}
```

**Comment by orkhanahmadov** [comment]
@matter3 Yep, can confirm, forcing the scheme to https fixed the issue. But it feels more like a workaround @calebporzio

**Comment by orkhanahmadov** [comment]
UPDATE

Following the other issue, @calebporzio [mentions](https://github.com/livewire/livewire/issues/1537#issuecomment-690861216) 2.1.4 should the issue. Just upgraded to 2.1.4, issue still exists.

**Comment by calebporzio** [comment]
Hey @orkhanahmadov, based on this report, I'm assuming that calling `url()->current()` and dumping it from your `https://` hosted site will spit out a `http://` url?

Can you verify this?

Then we can start to investigate why `url()->current()` isn't showing `https`. Maybe you're using a proxy? Or maybe it's a header thing? Or idk, thanks

**Comment by orkhanahmadov** [comment]
@calebporzio Yes, `url()->current()` outputs `http://` URL.

Yes, the application is behind Cloudflare proxy, which always forces HTTPS. I think that explains this behavior. In this situation, HTTPS is on the DNS level, application web server is not aware of the certificate. This is kind of a demo, an early preview of the project, I did not set up HTTPS on webserver level for it. But nevertheless, the "operation is insecure" error was hard to understand what might be the issue.

You can close this issue if you think there's nothing that can be done on Livewire level, on how it works, and thank you for your help.

**Comment by calebporzio** [comment]
Ok, I am now only using server-generated paths AFTER the origin (https://some-url.com) so that we shouldn't run into this anymore.

Try this in v2.2.2, if it's not fixed re-open. Thanks!
