### ISSUE TITLE
Url duplication in v2

### ISSUE THREAD

**Issue by pixsolution** [livewire/livewire#1530]
Hi! my url is duplicated eg. domain/country1/country1
my case is a multi-country website (same code but with DB per country) so we have a function to handle url per country eg. domain/country1 domain/country2... and so based on the url it connects to the database below I attach the function
<img width="590" alt="2" src="https://user-images.githubusercontent.com/47191848/92780806-d95a1600-f3a3-11ea-9c50-fc019d82386c.PNG">

well in livewire 1.3 it does not duplicate me work well but in last v2 it duplicated :s
I'm using laravel 7.

What do you thing is the cause?

Regards

**Comment by lancepioch** [comment]
Can you please paste the full but minimal reproducible code for us to check? It's not apparent what is actually wrong. Also some friendly advice is that you should actively avoid using PHP superglobals such as $_SERVER and instead use the Request instance's methods.

**Comment by calebporzio** [comment]
Also, things have been updated in V2.2.2 to hopefully resolve some of these issues, please let us know if you still have this issue after upgrading to v2.2.2 - thanks!

**Comment by pixsolution** [comment]
Hello @calebporzio @lancepioch 

I have updated to the version ^2.0
following your documentation https://laravel-livewire.com/docs/2.x/upgrading

And the error persists
<img width="339" alt="1" src="https://user-images.githubusercontent.com/47191848/94933749-1c9f3480-04cb-11eb-8d7d-ee86ed44fdc2.png">

Why?

I appreciate your help

Regards

**Comment by pixsolution** [comment]
I share the code of the function that I am using to handle url directory by country as indicated above, that is, it is the same domain but directory by country eg. /country1   /country2    and so on with database by country
```php
<?php
function pais(){
  $valor="";
  $url=!empty($_SERVER['REQUEST_URI'])?$_SERVER['REQUEST_URI']:"/";
  $urlexplotada=explode('/',$url);
  if(is_array($urlexplotada) && @count($urlexplotada)>=2){
    $valor=trim($urlexplotada[1],'_');
    if(in_array($valor,["panama","ecuador","colombia"])) {
      return $valor;
    }else {
      return "mysql";
    }
  }else {
    return "mysql";
  }
}
function pais2(){
  $url=!empty($_SERVER['REQUEST_URI'])?$_SERVER['REQUEST_URI']:"/";
  $urlexplotada=explode('/',$url);
  if(is_array($urlexplotada) && @count($urlexplotada)>=2){
    $valor=trim($urlexplotada[1],'_');
    if(in_array($valor,["panama","ecuador","colombia"])){
      return '/'.$valor;
    }else {
      return "";
    }
  }else {
    return "";
  }
}
function solo_pais(){
  return trim(pais2(),'/');
}
function url_root($url_enviada){
  $url=config('app.url');
  return $url.$url_enviada;
}
function url_public($url_enviada){
  $url=Request::root();
  return $url.'/public'.$url_enviada;
}
```

**Comment by pixsolution** [comment]
Hi!

I fixed part of the problem and managed to remove the REQUEST_URI at the end of the url but the duplication persists
<img width="265" alt="1" src="https://user-images.githubusercontent.com/47191848/95372555-008d0000-08dc-11eb-9233-de79f48e7f3e.png">
 I have read that Livewire has a push state that makes it reload the view or something like that and it is what I see causing the duplication... is there any way to disable it or something like that? to see if this is how this issue is solved...or if you can also tell me the location of that function on the package? to see what can be done

Regards

**Comment by calebporzio** [comment]
Thanks for updating this issue.

However, I'm going to close it as it is impossible for us to reproduce given the code you've provided.

Please reproduce the problem as simply as possible and paste in the FULL code needed to reproduce (including Livewire component class and view)

Thank you.
