### ISSUE TITLE
Uncaught DOMException: Failed to execute 'replaceState' on 'History'

### ISSUE THREAD

**Issue by oozman** [livewire/livewire#1537]
### Description
I'm getting this error on my production. But in my local, it's working fine.
I'm using AWS Application Loadbalancer too #fyi

Is this something with the https vs http?

### Steps to reproduce
I don't know really, since my local is working fine and this error won't pop up. I've attached a picture of the error in my console.

<img width="793" alt="https://i.imgur.com/SlVOi9L.png" src="https://i.imgur.com/SlVOi9L.png">

**Context**
- Livewire version: 2.1.0
- Laravel version: 7.28.0
- Browser: Chrome / Brave

**Comment by calebporzio** [comment]
Ah yes, it seems you're running into a bug related to mixing http with https in replaceState

**Comment by calebporzio** [comment]
We've just pushed a fix for things related to this. Can you upgrade Livewire to version 2.1.4 and see if it's fixed. Please close this if so!

**Comment by calebporzio** [comment]
Ok, this should be fixed in v2.2.2

Closing for now. Re-open if I'm wrong. Thanks!
