### ISSUE TITLE
UnexpectedValueException Invalid route action

### ISSUE THREAD

**Issue by cuatao** [livewire/livewire#1538]
### Description
UnexpectedValueException
Invalid route action: [App\Http\Controllers\App\Http\Livewire\ShowPosts].

Error:
![Foo](https://s3.anh.im/2020/09/11/Screen-Shot-2020-09-11-at-09.07.29ce29a479f73da716.png)
### Steps to reproduce
I have followed these steps and have an error:
1. Install fresh laravel project `v7.28.1`
2. Install livewire `v2.1.3`
3. Create a new component: `php artisan make:livewire ShowPosts`
4. Add to `web.php`
```php
Route::get('/post', ShowPosts::class);
```
**Context**
- Livewire version: [v2.1.3]
- Laravel version: [v7.28.1]
- Browser: [Chrome]

**Comment by cuatao** [comment]
I have just edited `RouteServiceProvider.php` from 
```php
protected $namespace = 'App\Http\Controllers';
```
to
```
protected $namespace = '';
```
and it seem be working.

**Comment by dev-mtshikomba** [comment]
This worked for me too. Thank
