### ISSUE TITLE
laravel 8 with jetstream

### ISSUE THREAD

**Issue by sathivel1985** [livewire/livewire#1539]
Currently I had install the laravel 8 with Jetstream  , LiveWire all . 

I had created the Livewire Component which is "test". So I tried to link from web route as follows

**Route::livewire('/test', 'test')->name('test');**

Its not working and throwing the error 

Attribute [livewire] does not exist.

### Steps to reproduce

**Context**
- Livewire version: [e.g. 2.0.0]
- Laravel version: [e.g.8.0.0]
- Browser: Chrome

**Comment by calebporzio** [comment]
Laravel 8 and Jetstream use Livewire 2.0 which has replaced the syntax `Route::livewire` with something else `Route::get()`.

Please check out the upgrade guide and the new docs for 2.0: https://laravel-livewire.com/docs/2.x/upgrading

**Comment by sathivel1985** [comment]
Thanks so much and its working fine .
