### ISSUE TITLE
Morphdom Bug

### ISSUE THREAD

**Issue by calebporzio** [livewire/livewire#1540]
This is a note for myself.

The following snippet doesn't morphdom properly because of the `wire:key` arrangement:

```html
                <div>
                    @if ($page == 2)
                        <h1 wire:key="post-1">Post #1</h1>
                    @else
                        <h1 wire:key="post-2">Post #4</h1>
                        <h1 wire:key="post-3">Post #5</h1>
                    @endif

                    <span>
                        <button wire:click="nextPage">
                            Tiny
                        </button>
                    </span>
                </div>
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
