### ISSUE TITLE
Pagination doesnt works!!

### ISSUE THREAD

**Issue by LfJohnVo** [livewire/livewire#1541]
I already create a project test with livewire and its works, but in this project it doesn't

![1](https://user-images.githubusercontent.com/32848900/92896085-ab93c200-f3e1-11ea-8ed1-1338655b9767.png)

and i get this error!

![2](https://user-images.githubusercontent.com/32848900/92896130-b9e1de00-f3e1-11ea-81b4-a6c6841bd63f.png)

what im doing bad????

Livewire component:
`<?php

namespace App\Http\Livewire;

use App\Models\PartesInt;
use Livewire\Component;
use Livewire\WithPagination;

class PartesComponent extends Component
{

    use WithPagination;

    public function render()
    {
        $posts = PartesInt::orderBy('id', 'desc')->paginate(5);

        return view('livewire.partes-component')->with('partesInts', $posts);
    }
}
`

livewire view
`<div>
    <div class="row">
        <div class="col s12 m12">
            <div style="padding: 35px;" align="center" class="card">
                <div class="row">
                    <div class="left card-title">
                        <h4>Partes interesadas</h4>
                        <input type="text" placeholder="Search...">
                    </div>
                    <div class="pull-right" style="text-align: right; margin-bottom: 2%;">
                        <a class="waves-effect waves-light btn modal-trigger" href="#modalCreate">Crear nuevo registro</a>
                    </div>
                </div>

                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-block lighten-5 green-text">
                        <button type="button" class="close green-text" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                @endif

                <div class="row">
                    <div>
                        <table id="scrooll" class="centered responsive-table">
                            <thead>
                            <tr>
                                <strong><th class="text-center"><font size=3>No</font></th></strong>
                                <strong><th class="text-center"><font size=3>Parte interesada</font></th></strong>
                                <strong><th class="text-center"><font size=3>Requisitos</font></th></strong>
                                <strong><th class="text-center"><font size=3>Clausuala que satisface el requisito de la parte interesada</font></th></strong>
                                <th class="text-center"><font size=3>Editar</font></th>
                                <th class="text-center"><font size=3>Eliminar</font></th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($partesInts as $partesInt)
                                <tr>
                                    <td>{{ $partesInt ->id }}</td>
                                    {{-- paginación --}}
                                    {{-- <td>{{ ++$i }}</td> --}}
                                    <td>{{ $partesInt->parte_int }}</td>
                                    <td>{{ $partesInt->requisitos }}</td>
                                    <td>{{ $partesInt->clausula }}</td>

                                    <td>
                                            <a class="btn btn-primary" ><i class="material-icons">edit</i></a>

                                        </form>
                                    </td>
                                    <td>
                                            <button type="submit" class="btn btn-danger" value="submit"><i type="submit" class="material-icons">delete</i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                {{-- <div class="row">
                @include('iso27001-2013.contexto')
                </div> --}}
            </div>
        </div>
    </div>
    {!! $partesInts->links() !!}
</div>
`

**Comment by coolsam726** [comment]
1. Have you run `php artisan livewire:publish`
Are you serving your project form a sub-path(e.g http://myurl.com/my-app) or from a root domain?

Take a look at #1535 and #1482 , they might help

**Comment by LfJohnVo** [comment]
> 1. Have you run `php artisan livewire:publish`
> Are you serving your project form a sub-path(e.g http://myurl.com/my-app) or from a root domain?
> 
> Take a look at #1535 and #1482 , they might help

Yes!!! But stills give me an error

**Comment by calebporzio** [comment]
Hey @LfJohnVo, are you running your project on a sub-domain? or from a non-root path?

**Comment by calebporzio** [comment]
Ok, try this again with Livewire v2.2.2 I believe issues like these are fixed now, but want to make sure.

Closing this for now, re-open if not. Thanks!
