### ISSUE TITLE
livewire is not using Custom Validation Attributes language from validation.php

### ISSUE THREAD

**Issue by falconeri** [livewire/livewire#1546]
### Description
I have an array component ```<input type="file" name="directors[{{ $index }}][passport_image_front]"/>``` and want to change error message attribute to custom name, but livewire not using validation.php language.

### Steps to reproduce

1. i have set a rules in temporary_file_upload livewire config. 
2. If I select a file that does not pass validation, the error is displayed.
2. Because it is an array, it will shows array attribute error message ```directors.0.passport_image_front```
3. I have set a Custom Validation Attributes inside validation.php ```'directors.*.passport_image_front' => 'Company Name'```
4. Livewire not respected / not using custom validation attributes

### Screenshots
![Screenshot 1](https://user-images.githubusercontent.com/9047407/92921127-b3914780-f45d-11ea-8546-cc2f57ef2783.png)
![Screenshot 2](https://user-images.githubusercontent.com/9047407/92921136-b9872880-f45d-11ea-9a70-f7fe9b5a4980.png)

**Context**
- Livewire version: 2.1.3
- Laravel version: [7.28.1
- Browser: Chrome, Firefox

**Comment by zepfietje** [comment]
Could be related to #1524.

**Comment by zepfietje** [comment]
@falconeri, could you show the parts of your code related to validation?

**Comment by falconeri** [comment]
> @falconeri, could you show the parts of your code related to validation?

I am using temporary rules inside config/livewire.php, so not using my own custom validation but validation rules from livewire

Here https://laravel-livewire.com/docs/2.x/file-uploads#configuration

**Comment by zepfietje** [comment]
Okay, not sure if this is the exact same issue as #1524, but maybe it is related to https://github.com/livewire/livewire/issues/1524#issuecomment-691506776.

**Comment by calebporzio** [comment]
This will be fixed in the next release. See comment here: https://github.com/livewire/livewire/issues/1524#issuecomment-692904182
