### ISSUE TITLE
[v2] Model binding not working with optional route parameters

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1547]
Livewire v2.1.4
Laravel 7.28.1
php 7.4.4

### Livewire routes with optional parameters, where none is passed.

The "new" model binding, where you can omit the `mount()` method only works if a model exists.
Not sure if this is can be labelled as a "bug" but It would be nice if it worked.

```php
Route::get('/user/{user?}', LivewireComponentName::class);
```

The "new" way, where you omit the` mount()` method, gives an error if _no model key is passed to the route_

```php
public ?User $user;
public $foo;

public function mount()
{
    $this->foo = $this->user->bar;  // error
}
```
Error
```
$user must not be accessed before initialization
```

With the "old" way you get a new model instance
```php

public $user;
public $foo;

public function mount(?User $user)
{
    $this->user = $user; // = new User()
    $this->foo = $this->user->bar;  //no error
}
```

**Comment by imliam** [comment]
Using the "old" way as you've shown above is still incorrect, you've clearly got a case where you're trying to access a property of "user" even if there is no user set, it's just implicitly casting it to `null`.

If you turn on notices, you're probably getting one:

```
PHP Notice:  Trying to get property 'bar' of non-object
```

Typehinting the property with `User` is just making this more obvious by raising it to an error - but it's still a problem wither way.

**Comment by tanthammar** [comment]
Yes, that is sloppy of me, copy/pasted the properties, also bad naming of "old/new" :)

What I am trying to say is that I get a new model instance with this:

```php
public function mount(?User $user) //$user = null
{
    dd($user); // a User instance
}
```

Whereas this declaration gives an error.

```php
public ?User $user; //$user = null

public function mount()
{
    dd($this->user);  // $user must not be accessed before initialization
}
```

And that it, if possible, would be nice if they could work the same.

**Comment by calebporzio** [comment]
Tina, are you sure the `$this->user` INSIDE the `dd()` is causing this error giving you a false negative?

I just want to make sure we've rules everything else out. Thanks for helping out with this @imliam

**Comment by tanthammar** [comment]
Apart from the previous mentioned, these are the scenarios I tried:

They are all based on a Livewire route with optional parameter, where no model key is passed. 
```php
Route::get('/user/{user?}', LivewireComponentName::class);
```
```
https://testsite.test/user/
```
Error: Typed property App\Http\Livewire\TestComponent::$user must not be accessed before initialization
```php
    public ?User $user;
    public $otherProp;

    public function mount()
    {
        $this->otherProp = $this->user; //$user must not be accessed before initialization
    }
```

Error: Typed property App\Http\Livewire\TestComponent::$user must not be accessed before initialization
```php
    public ?User $user;
    public function mount()
    {
        $this->some_other_method($this->user);
    }

    public function some_other_method()
    {
        //
    }
```

I guess this is the core of the issue.
Error: Cannot auto-initialize an stdClass inside property App\Http\Livewire\ExampleComponent::$user of type ?App\User
```php
    public ?User $user;
    public function mount()
    {
        $this->user->name = 'Caleb';
    }
```

Why do I care?
When people read in the Livewire docs that they can type hint a model in combination with the `$rules` property, I am certain that they will want to use it. 

- Everything is so much easier if one doesn't have to think "Will I ALWAYS pass a $key to this route or ... ". If I'm not 100% sure I cannot use this cool way of model binding. I mean that's why the optional route parameters exist.
- I am trying to make a package where I want to support this way of declaring the model binding. Of course there are simple ways around it. I could document that they have to do it in the `mount()` method. But that feels pretty sad :)
- There might also be cases where users will want to pass the model instance in the mount method like `SomeClass::staticMethod($this->user)`. 

Just thought that if possible, it would be great if Livewire could support optional route parameters using the same syntax.

**Comment by tanthammar** [comment]
This is the stack trace for the last error: 
Error: Cannot auto-initialize an stdClass inside property App\Http\Livewire\ExampleComponent::$user of type ?App\User
[https://flareapp.io/share/OmVVB3m8#F54](https://flareapp.io/share/OmVVB3m8#F54)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by heyjoe1984** [comment]
REOPEN

would be nice it livewire could allow for nullable route model binding,  could we just use `firstOrNew`?

right now i'm having to do this:

    public function mount ($id = null)
    {
        $this->sensor = Sensor::firstOrNew(['id' => $id]);

        $this->fill($this->sensor);
    }

instead of this:

    public function mount (Sensor $sensor = null)
    {
        $this->sensor = $sensor;

        $this->fill($this->sensor);
    }

**Comment by joshhanley** [comment]
@heyjoe1984 Livewire actually allows nullable route model binding already.

You probably need to change your mount sensor property to accept nulls like `mount(?Sensor $sensor = null)`.

Hope this helps.

**Comment by turboMagneTT** [comment]
@joshhanley is this work? I can't get it to work here. I'm getting a 404 and I was thinking about opening an issue.

**Comment by joshhanley** [comment]
@turboMagneTT works fine for me. But feel free to open a discussion with any relevant code and we can have a look to see if we can get it running 🙂

**Comment by jorr-it** [comment]
With V3 of Livewire, I still experience this issue.

`Route::get('/paragraphs/create/{parent?}', App\Livewire\Paragraph\Create::class);`

with

`public function mount(?Paragraph $parent = null)`

ends up in an 404 when clicked on

`<a href="/paragraphs/create" wire:navigate>New paragraph</a>`

**Comment by Enaah** [comment]
V3 might never get this feature with full-age components:

https://github.com/livewire/livewire/discussions/6939
