### ISSUE TITLE
Livewire 2.0 query string state management alphabetizes query strings even when no query string manipulation is happening; causes SEO errors

### ISSUE THREAD

**Issue by erikwestlund** [livewire/livewire#1549]
### Description

In Livewire 2.0, if you have a livewire component on a page, even if you are not manipulating query strings in any way, Livewire will alphabetize query strings on page load. 

Unless Livewire is working with query strings, I do not think it should be manipulating them. I also do not think it should be alphabetizing for SEO reasons. I work on a legacy message board which we've incorporated Livewire into where query strings are used for both pagination and for differentiating threads. Therefore, query string order is important for SEO, as we have concerns over duplicate content if the order changes.

Our links look like this. They are generated using Laravel's standard pagination (Not Livewire's)

domain.com/forum?thread=1&page=2

When you load that page, even though we do nothing with the query string, Livewire changes it to:

domain.com/forum?page=2&thread=1

The change is also visible.

**I can also confirm that Google is able to learn about these different query string-ordered URLs, as we have already received duplicate content errors in our dashboard. As this could affect SEO of users, I think this should be high priority to fix.** 

Regardless, the changing order of query strings without clicking is distracting and makes it feel like something is broken. I do not think it should be re-ordering query strings by default, especially when we're not using the $queryString property in any of the loaded Livewire components.

Video attached shows this in action.

### Potential fix

In SyncBrowserHistory.js, these two methods:

```
    store.registerHook('component.initialized', component => {
        let state = generateNewState(component, generateInitialFauxResponse(component))
        let url = initializedPath ? undefined : component.effects.path

        history.replaceState(state, '', url)
        initializedPath = true
    })

    store.registerHook('message.processed', (message, component) => {
        if (message.replaying) return

        let { response } = message
        let effects = response.effects || {}

        if ('path' in effects && effects.path !== window.location.href) {
            let state = generateNewState(component, response)

            history.pushState(state, '', effects.path)
        }
    })
```

get run once a component is initialized and/or a message is processed.

If I remove the `history.replaceState`  and `history.pushState` code from the published vendor assets, this problem goes away. Obviously, this also breaks page tracking. 

Of note, I need to remove *both* of those lines to make it stop doing this. I believe this is because any time a livewire message gets received, the query state gets pushed.

I think the only solution as currently architected is to make the `component.effects.path` property not alphabetize query strings.

I believe the code tries not to replace query strings when the URL hasn't changed:

`if ('path' in effects && effects.path !== window.location.href) `

However, the alphabetization breaks this idea too.

*Update*

After doing some research, I believe the culprit is here in

`Livewire\RenameMe\SupportBrowserHistory`

```
    protected function mergeComponentPropertiesWithExistingQueryParamsFromOtherComponentsAndTheRequest($component)
    {
        $excepts = $this->getExceptsFromComponent($component);

        $this->mergedQueryParamsFromDehydratedComponents = collect(request()->query())
            ->merge($this->mergedQueryParamsFromDehydratedComponents)
            ->merge($this->getQueryParamsFromComponentProperties($component))
            ->reject(function ($value, $key) use ($excepts) {
                return isset($excepts[$key]) && $excepts[$key] === $value;
            })
            ->map(function ($property) {
                return is_bool($property) ? json_encode($property) : $property;
            })
            ->sortKeys();
        
        return $this->mergedQueryParamsFromDehydratedComponents;
    }
```

Removing sortKeys() from the collection pipeline resolves the issue.

I will submit a PR to remove.

### Steps to reproduce

**Context**
- Livewire version: 2.0.0
- Laravel version: 8.0
- Browser: Chrome, Safari, etc.

https://www.loom.com/share/fb260c06804d427cb09ff46db06a3b1e

**Comment by calebporzio** [comment]
Fixed in version 2.1.1 - Thanks for the PR Erk!

**Comment by calebporzio** [comment]
Also, @erikwestlund - we're now only messing with the url when we need to.

**Comment by erikwestlund** [comment]
Nice! Thanks for all you do.
Naveen Kumar <notifications@github.com> wrote:
“Also, @erikwestlund - we're now only messing with the url when we need to.”

**Comment by erikwestlund** [comment]
@all-contributors please add erikwestlund for code
