### ISSUE TITLE
make:livewire Foo\\Bar doesn't work as expected

### ISSUE THREAD

**Issue by zack6849** [livewire/livewire#1550]
### Steps to reproduce

**Context**
- Livewire version: 1.3.3
- Laravel version: 7.28.1
- Browser: N/A

when using make:livewire, it doesn't behave as expected, in-line with how other laravel commands work, for example:

laravel@6e074f7324b3:/var/www/html$ php artisan make:model Foo\\Bar\\Baz
Model created successfully.

Creates 

App\\foo\\Bar\\Baz.php

Livewire, on the other hand:

laravel@6e074f7324b3:/var/www/html$ php artisan make:livewire Foo\\Bar\\Baz
 COMPONENT CREATED  🤙

CLASS: app/Http/Livewire/Foo\Bar\Baz.php
VIEW:  resources/views/livewire/foo\-bar\-baz.blade.php

This is pretty weird, and i'm not sure if this has been reported before or not, but wanted to point it out.

It also can lead to some pretty fun things, if, for example, you're on windows and using WSL for your dev environment

On the dev environment, the filename is what you expect, but in my ide, it shows up like this, which is neat.

![phpstorm screenshot](https://www.zcraig.me/files/m4L2a0mkOllZPO2wnUho4iehK.png)

**Comment by zepfietje** [comment]
@zack6849 I can't reproduce your issue.
Both `php artisan make:model` and `php artisan make:livewire` seem to require double backslashes for nesting.

So I guess what you want is the following:
```console
php artisan make:livewire Foo\\Bar\\Baz
```

**Comment by zack6849** [comment]
Weird, i'm not sure if i'm having a stroke, or if this was changed, or if i'd been typing the double backslashes the entire time.

Nonetheless, like you said, it seems to be working now..

🤔
