### ISSUE TITLE
Problem resetting wire:model with array

### ISSUE THREAD

**Issue by AugustBurnsRed** [livewire/livewire#1554]
### Description
Hi, i think that there is a problem when we try to reset an input that uses a wire:model data from an array.

### Steps to reproduce

```
@dump($state)
<input id="title" type="text" wire:model="state.title"/>
<input id="test" type="test" wire:model="test"/>
```
```
public $test = 'test';
public $state = [];

$this->state = [];
$this->reset();
```

So if i try to reset $test after i submit my form, it's working perfectly. With the $state array, the value is being resetted in the @dump but not the input. I tried by manually resetting the array and with reset() but neither are working

**Context**
- Livewire version: 2.0
- Laravel version: 8.0
- Browser: Chrome

**Comment by calebporzio** [comment]
Thanks for submitting. I found the bug and it will be fixed in the next release!

**Comment by calebporzio** [comment]
Here's the code for your notes: https://github.com/livewire/livewire/commit/1cb6e76b69c838f5da6943e8ac7e689600106e61
