### ISSUE TITLE
Wildcard Validation Rules on Collections not working

### ISSUE THREAD

**Issue by obrunsmann** [livewire/livewire#1556]
### Description
I have a form to edit an array:
```
$types = [
    ['title' => 'foo'],
    ['title' => 'bar'],
];
```

and the corresponding validation rule:
```
protected $rules = [
    'types.*.title' => 'required|max:2',
];
``` 

But when calling `$this⇢validate()` it does not work as expected when the title as more than 2 chars.

I tried changing this to

```
protected $rules = [
    'types.0.title' => 'required|max:2',
];
``` 

And now the first row get correctly validated.

### Steps to reproduce

**Context**
- Livewire version: v2.1.4
- Laravel version: v7.26.1

**Comment by zepfietje** [comment]
I just ran into this too.

**Comment by jimpeters** [comment]
Seems to work for me just fine.  Without your code it's hard to tell but here is a working example of the validation in action.  Maybe this will help.

TestComponent.php

```php
class TestComponent extends Component
{
    public $types = [
        ['title' => 'foo'],
        ['title' => 'bar'],
        ['title' => 'ab'],
    ];

    protected $rules = [
        'types.*.title' => 'required|max:2',
    ];

    public function updated()
    {
        $this->validate();
    }

    public function render()
    {
        return view('test');
    }
}
```

test.blade.php
```blade
<div>
    @foreach($types as $index => $type)
        <div>
            <input wire:model.debounce.500ms="types.{{$index}}.title" type="text">
            @error('types.' . $index . '.title')
                <div>ERROR: {{ $message }}</div>
            @enderror
        </div>
    @endforeach
    <div>END OF LIST</div>
</div>
```

Here is a screenshot

<img width="551" alt="Screen Shot 2020-09-13 at 10 53 03 PM" src="https://user-images.githubusercontent.com/1263441/93038800-eed57700-f613-11ea-9772-ed9b82b098dc.png">

**Comment by obrunsmann** [comment]
@jimpeters Okay... I tried so much the day before yesterday that I was quite far away from my original code.

What I originally wanted to achieve: I have a "Group" model with HasMany "Type". My form is now the editing of the types.

**GroupEditTypes.php**:
```
class GroupsEditTypes extends Component
{
    public $group;

    protected $rules = [
        'group.types.*.title' => 'required|max:2',
    ];

    public function add()
    {
        $this->group->types()->create([
...
        ]);

        $this->group->refresh();
    }

    public function delete($id)
    {
        $type = Type::findOrFail($id);

        $type->delete();
        $this->group->refresh();

        $this->emit('success', "{$type->title} wurde gelöscht.");
    }

    public function render()
    {
        return view('livewire.groups-edit-types');
    }
}
```


**group-edit-types.blade.php**
```
            @foreach($group->types as $i => $type)
            <tr>
...
                <td>
                    <input type="text" wire:model="group.types.{{ $i }}.title">
                </td>
...
                    @if($type->logs()->count() === 0)
                    <button type="button" wire:click="delete({{ $type->id }})">
                        <i class="typcn typcn-trash"></i>
                    </button>
                    @endif
                </td>
            </tr>
            @endforeach
```

As soon as I start typing in the form I get get Issue
> Cannot bind property [group.types.0.title] without a validation rule present in the [$rules] array on Livewire component: [groups-edit-types].


So when I change the rules like
```
protected $rules = [
    'group.types.0.title' => 'required|max:2',
];
```

I partially works. Besides that it looks like my model is now an array instead of an instance of my model class 🙄


So I think there is some issue with binding to relations.. I also tried around with putting my types in an array after mounting but so correctly I did not come on the trace to the problem on the one hand yet and I found also still no solution for my form 😬

**Comment by zepfietje** [comment]
From what I've found, this issue occurs with collections.
@jimpeters, as your example shows, validation works as expected for arrays.
However, nested values don't get validated when using collections instead of arrays.
Try the follow component and you'll see validation errors for the array items and not for the collection.

```php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Collection;
use Livewire\Component;

class WildcardValidation extends Component
{
    public array $array = [
        ['foo' => 'a'],
        ['foo' => 'b'],
    ];

    public Collection $collection;

    protected array $rules = [
        'array.*.foo' => 'numeric',
        'collection.*.foo' => 'numeric',
    ];

    public function mount(): void
    {
        $this->collection = collect($this->array);
    }

    public function check(): void
    {
        $this->validate();
    }
}
```

```blade
<div>
  <button wire:click="check">Validate</button>
  @dump($errors)
</div>
```

**Comment by zepfietje** [comment]
This just appears to be how Laravel handles validation of collections.
I understand the behavior, since normally (without Livewire) you wouldn't validate collections but arrays.
However, I would expect Livewire to handle this for me.

For now, you can work around this issue by defining the following `prepareForValidation` method on your Livewire component:

```php
protected function prepareForValidation(array $data): array
{
    return collect($data)
        ->map(
            fn ($value) => $value instanceof Collection
                ? $value->all()
                : $value
        )
        ->all();
}
```

where `Collection` is `Illuminate\Support\Collection`.

This could potentially be similar to the fix on the Livewire side.
What do you think @calebporzio?

**Comment by zepfietje** [comment]
Just found that my proposed solution breaks `@entangle()` in certain situations. Not sure what's the cause.

**Comment by iksaku** [comment]
There seems to be an issue with Wildcard Validation for models as well, and as far as I can tell, it was introduced in the following commit:

https://github.com/livewire/livewire/commit/0313887e8c355bac985a87a7580b0bee5533edc5#diff-13d0c883643367d8306b4ff4bdbe48f3L81-R89

**Comment by zepfietje** [comment]
> There seems to be an issue with Wildcard Validation for models as well

@iksaku, not sure if that's related to this issue.

> This just appears to be how Laravel handles validation of collections.
> I understand the behavior, since normally (without Livewire) you wouldn't validate collections but arrays.
> However, I would expect Livewire to handle this for me.

**Comment by iksaku** [comment]
After little more research, I can see that it is indeed a separate issue, while the problem is technically the same as the issue describes, it is entirely based on livewire, not on Laravel validator. I'll open a separate issue for this.

Thanks @zepfietje

**Comment by joowdx** [comment]
> Seems to work for me just fine. Without your code it's hard to tell but here is a working example of the validation in action. Maybe this will help.
> 
> TestComponent.php
> 
> ```
> class TestComponent extends Component
> {
>     public $types = [
>         ['title' => 'foo'],
>         ['title' => 'bar'],
>         ['title' => 'ab'],
>     ];
> 
>     protected $rules = [
>         'types.*.title' => 'required|max:2',
>     ];
> 
>     public function updated()
>     {
>         $this->validate();
>     }
> 
>     public function render()
>     {
>         return view('test');
>     }
> }
> ```
> 
> test.blade.php
> 
> ```
> <div>
>     @foreach($types as $index => $type)
>         <div>
>             <input wire:model.debounce.500ms="types.{{$index}}.title" type="text">
>             @error('types.' . $index . '.title')
>                 <div>ERROR: {{ $message }}</div>
>             @enderror
>         </div>
>     @endforeach
>     <div>END OF LIST</div>
> </div>
> ```
> 
> Here is a screenshot
> 
> <img alt="Screen Shot 2020-09-13 at 10 53 03 PM" width="551" src="https://user-images.githubusercontent.com/1263441/93038800-eed57700-f613-11ea-9772-ed9b82b098dc.png">


Tried this just to confirm validation rules are working but this really is just working fine. 
However in my case I have nested array on a json column

Component
```
<?php

namespace App\Http\Livewire\RSP;

use App\Models\Person;
use Livewire\Component;

class PersonalData extends Component
{
        protected $rules = [
                'person.personal_data.family_background.children.*.name.first' => 'string',
                'person.personal_data.family_background.children.*.name.middle' => 'string',
                'person.personal_data.family_background.children.*.name.last' => 'string',
                'person.personal_data.family_background.children.*.name.extension' => 'string',
                'person.personal_data.family_background.children.*.birth_date' => 'string|date',
        ];

        public function mount()
        {
                $this->person = Person::first();
        }

        public function render()
        {
                return view('livewire.r-s-p.personal-data');
        }

        public function updatingPerson()
        {
                $this->validate();
        }
}
```

Model
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
        use HasFactory;

        protected $casts = [
                'application_date' => 'date',
                'birth_date' => 'date',
                'personal_data' => 'array' //just changed from object to array but still is not working
        ];

        protected $fillable = [
                'first_name', 'middle_name', 'last_name', 'sex', 'personal_data'
        ];
}
```

Blade
```
@foreach ($person->personal_data['family_background']['children'] as $no => $child)
        <div class="w-full sm:w-2/4 xl:w-1/4 px-3 mb-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-semi-light dark:text-gray-300 mb-2">
                        First Name
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="text" wire:model.debounce.1000ms="person.personal_data.family_background.children.{{$no}}.name.first">
                <x-jet-input-error for="person.personal_data.family_background.children.{{$no}}.name.first" class="mt-2" />
        </div>
@endforeach
```

Screenshot

![image](https://user-images.githubusercontent.com/27247592/94103765-f98bd980-fe67-11ea-8ad7-2d20f3c08bec.png)

**Comment by zepfietje** [comment]
@joowdx, your issue is unrelated to this bug report.

**Comment by joowdx** [comment]
@zepfietje, I'm sorry. I didn't know if it's related or not but I think it we have just a similar issue where wildcard validation isn't working as expected.

**Comment by zepfietje** [comment]
@joowdx, let's keep this issue scoped to this particular problem: https://github.com/livewire/livewire/issues/1556#issuecomment-691908544.
I think your bug is the one reported by @iksaku: https://github.com/livewire/livewire/issues/1667.

**Comment by zepfietje** [comment]
@obrunsmann, could you maybe update the issue title to clarify the actual bug (that it's about collections).

**Comment by calebporzio** [comment]
Fixed: https://github.com/livewire/livewire/commit/98679691d546a2b0acbdde6eaf23e3185a2f3368

Will be available in the next release.
