### ISSUE TITLE
Question for $queryString - ?_url

### ISSUE THREAD

**Issue by SEFkiss** [livewire/livewire#1557]
### Description
I write the code according to the example https://laravel-livewire.com/docs/2.x/query-string
But I get an extra _url parameter in the URL
### Steps to reproduce
```php
Route::get('show', App\Http\Livewire\Show::class);
```
```html
<div class="flex flex-col items-center justify-center h-full p-10 bg-white">
    <div class="font-thin text-gray-500 text-2xl">Random string: {{ $randomString }}</div>
    <button class="mt-5 bg-red-200 border border-red-500 shadow px-5 py-2 text-gray-400" 
            wire:click="updateQuery()">QueryString Change</button>
</div>
```
```php
namespace App\Http\Livewire;

use Livewire\Component;

class Show extends Component
{
    public $randomString = '';  

    protected $queryString = ['randomString' => ['except' => '']];

    public function updateQuery()
    {
        $this->randomString = \Str::random(16);
    }

    public function render()
    {
        return view('livewire.show');
    }
}
```
When changing $randomString I expect URL: **mysite.ru/show?randomString=njksdnfjnkn3**
But, I get next URL:  **mysite.ru/show?_url=%2Fshow&randomString=KWqN29PNNgQKqeMc**
Why does the line have **?_url=%2Fshow**
**Context**
- Livewire version: [e.g. 2.2.1]
- Laravel version: [e.g. 8.1.0]
- Browser: [Chrome]

**Comment by jimpeters** [comment]
This sounds like you have a web server configuration appending the _url parameter at first glance.  If you are using a web server like nginx I would search your configuration files for "_url" to verify.

**Comment by SEFkiss** [comment]
> This sounds like you have a web server configuration appending the _url parameter at first glance. If you are using a web server like nginx I would search your configuration files for "_url" to verify.

Oh my god! Really, it so.
```nginx
Then:
try_files $uri $uri/ /index.php?_url=$uri&$args;

Now:
try_files $uri $uri/ /index.php;
```
All works! Fine! Thank you ^_^
