### ISSUE TITLE
Morphdom issue with tailwind pagination

### ISSUE THREAD

**Issue by timrspratt** [livewire/livewire#1558]
### Description

When navigating pages, the wording is being lost.

### Steps to reproduce

Note the word "of" vanishes when returning from the final page. It seems to only be certain numbers it triggers on though.

![Screen Recording 2020-09-12 at 09 37 31](https://user-images.githubusercontent.com/20431294/92991519-3fe24f80-f4dc-11ea-869f-9075d76b5751.gif)

(Apologies for the gif being super slow 🙈)

**Context**
- Livewire version: 2.2.1
- Laravel version: 8.1.0
- Browser: Chrome 85

**Comment by ninthspace** [comment]
In the pagination template, you need to wrap the text in `span` tags, like this:

```html
{!! __('Showing') !!}
<span class="font-medium">{{ $paginator->firstItem() }}</span>
<span>{!! __('to') !!}</span>
<span class="font-medium">{{ $paginator->lastItem() }}</span>
<span>{!! __('of') !!}</span>
<span class="font-medium">{{ $paginator->total() }}</span>
{!! __('results') !!}
```
