### ISSUE TITLE
Pagination and browser history issue

### ISSUE THREAD

**Issue by timrspratt** [livewire/livewire#1559]
### Description

When navigating through pages from a paginated data set, then refreshing the page, and then using the browser history (back button) to return to the previous page, the component isn't updated.

### Steps to reproduce

Navigate through pages, click refresh, use the browser back button. The component data doesn't update.

![Screen Recording 2020-09-12 at 10 05 28](https://user-images.githubusercontent.com/20431294/92992114-4672c600-f4e0-11ea-8466-8330da7bead8.gif)

**Context**
- Livewire version: 2.2.1
- Laravel version: 8.1.0
- Browser: Chrome 85

**Comment by GertjanRoke** [comment]
If you change it in the url it self and press enter it works?

**Comment by TheArKaID** [comment]
> 
> 
> If you change it in the url by hand and press enter it works?

Mine is fail in the second page,
![image](https://user-images.githubusercontent.com/35050722/93000666-1402b080-f554-11ea-92e6-08ffe6e1a6da.png)

But after go back to the first page, it works, for all history pages
![image](https://user-images.githubusercontent.com/35050722/93000690-3bf21400-f554-11ea-8267-3fb4b0917fe1.png)

![image](https://user-images.githubusercontent.com/35050722/93000717-5deb9680-f554-11ea-937e-4094b30ddf11.png)

And....uh, when I refresh it again in the second page, it's not showing the data of the first page.

**Comment by calebporzio** [comment]
This should be fixed in Livewire v2.2.2

I spent the weekend working on the .pushState functionality in Livewire with this bug driving the work. I think it should be resolved, but I'm eager to know.

Closing this for now, please still comment here though. Thanks!
