### ISSUE TITLE
File Uploads, .vcf File gets automatically changed to .vcard after upload to S3

### ISSUE THREAD

**Issue by SahibSinghBanga** [livewire/livewire#1561]
### Steps to reproduce
I am using Livewire with Laravel.
Just choose the " mimes: vcf  " in the validation and simply you can duplicate this bug.

**Context**
- Livewire version: Tried with both 1.x & 2.x
- Laravel version: 7.5+
- Browser: Chrome

**Comment by calebporzio** [comment]
Hey @SahibSinghBanga, I'm wondering if this is a Laravel bug. Do you mind testing this upload with plain Laravel to S3? If you don't get this behavior, please re-open this issue. Thanks!
