### ISSUE TITLE
Update hooks not run for collection properties

### ISSUE THREAD

**Issue by zepfietje** [livewire/livewire#1566]
### Description

It seems that the `updating()`, `updated()`, as well as `updatingFoo()` and `updatedFoo()` hooks are not run when adding items to or removing items from a collection property `foo`. Even though the hooks are not triggered, the updated data is correctly sent to the front end. Also, the hooks do work when modifying an item in the collection.

### Steps to reproduce

1. Create a collection property named `foo`.
2. Write an action method `add()` that pushes an item to the collection `foo`.
3. Write the `updated($field)` method which does something like `dd($field)`.
4. Call the `add` action.
5. Watch the `updated` hook not being triggered.

```php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Collection;
use Livewire\Component;

class Foo extends Component
{
    public Collection $foo;

    public function mount(): void
    {
        $this->foo = new Collection;
    }

    public function updated($field): void
    {
        dd($field);
    }

    public function add(): void
    {
        $this->foo->push('bar');
    }
}
```

```blade
<div>
  <button wire:click="add">Add</button>
  <div>{{ $foo->join(', ') }}</div>
</div>
```

**Context**
- Livewire version: 2.2.1
- Laravel version: 8.1.0
- Browser: Firefox

**Comment by jimpeters** [comment]
I believe this is normal.  The user did not update the foo collection.  You did.  

All the user did was call a method on your class, which you can handle in your method declaration.

The update() helper is more for "a user has updated this property's value" handlers coming from the front end using wire:model bindings, etc.

Your example is just you using PHP to set variables in a class, so there is no need to notify update().

I believe this behavior is consistent across all property types, not just collections.
 
Hope that helps.

**Comment by jimpeters** [comment]
Here is an example of the difference.  Run this and add some collection entries.  Then go and edit one of them using the form fields as the user to see the behavior.

```php
<?php
namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Collection;

class Foo extends Component
{
    public Collection $foo;

    public function mount(): void
    {
        $this->foo = new Collection;
    }

    public function updated($field): void
    {
        dd($field);
    }

    public function add($number): void
    {
        $this->foo->push($number);
    }

    public function render()
    {
        return view('test');
    }
}
```

```blade
<div>
    <button wire:click="add({{ rand(0,500) }})">Set name to random(0,500)</button>
    <div>
        @foreach($foo as $index => $f)
            <div>
                foo.{{ $index }} : <input wire:model="foo.{{$index}}"/>
            </div>

        @endforeach
        <div>
            <button wire:click="add">Add</button>
        </div>
        <div>{{ $foo->join(', ') }}</div>
    </div>
</div>
```

**Comment by zepfietje** [comment]
@jimpeters, you're right, this behavior is indeed consistent across types.

However, I still feel it's kind of misleading, especially since the documentation reads:
updated | Runs after any update to the Livewire component's data
-- | --

That being said, I do understand why the current behavior probably is what we want.
I do think it deserves a note in the docs though.
