### ISSUE TITLE
[v2.2.2] value not shown using wire:model with eloquent collection

### ISSUE THREAD

**Issue by masterix21** [livewire/livewire#1585]
![example](https://user-images.githubusercontent.com/6555012/93079397-59c29480-f68c-11ea-8eb7-a5512361cc6a.gif)

### Description

*Preamble:* the bug isn't present using the version 2.2.1

*Component:*
```php
class Setup extends Component
{
    public Company $company;
    public Collection $sections;

    protected $listeners = [
        'refresh-setup' => 'refresh',
    ];

    public function mount()
    {
        $this->refresh();
    }

    public function refresh()
    {
        $this->sections = CompanyAccountingDaySection::query()
            ->whereCompanyId($this->company->id)
            ->orderBy('name')
            ->get();
    }
}
```

```blade
@foreach ($sections as $key => $section)
    <input type="text" wire:key="cads-id-{{ $section->id }}" wire:model.lazy="sections.{{$key}}.name" value="{{$section->name}}" />
@endforeach
```

###  Differences with the previous 2.x versions
The previous version only has the bug of `value="{{$section->name}}"` attribute: without, doesn't show the initial data.

### Steps to reproduce

**Context**
- Livewire version: 2.2.2
- Laravel version: 8.1.0
- Browser: Chrome

**Comment by calebporzio** [comment]
You need to have a `$rules` property to specify keys in the nested collection that should be made available to the front-end.

If THAT doesn't work, please re-submit an issue for that bug.

Thanks!

**Comment by masterix21** [comment]
@calebporzio, I have tried already to use `$rules = ['sections.*.name' => 'required']`, but doesn't work.

**Comment by austenc** [comment]
This should be fixed with `2.3.0`

**Comment by masterix21** [comment]
Yes, seems to be fixed.

Thanks

**Comment by calebporzio** [comment]
Wooot!
