### ISSUE TITLE
Storage Exceeds Quota

### ISSUE THREAD

**Issue by jetwes** [livewire/livewire#1586]
### Description
In the last couple of days i had several error of this type: **"Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'nnz7zumaz2r' exceeded the quota."**

This happens in my testing development after a couple of reloads of my app (always reloading the page with the same livewire component".
After manually deleting the local session storage the error is gone and the component works as expected.

### Steps to reproduce
Create a new livewire component and reload your page a couple of times (eg. 20x for example)

**Context**
- Livewire version: 2.2.2
- Laravel version: 7.28.1
- Browser: Chrome

**Comment by elsuterino** [comment]
Have same issue with chrome and firefox. It saves full responses in session and doesn't clean up, after 50-100 it just reaches limits and breaks.

**Comment by masterix21** [comment]
I have the same error:

```log
SyncBrowserHistory.js:66 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '9krvubvjzsa' exceeded the quota.
    at generateNewState (http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:125214)
    at http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:125465
    at http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:2029
    at Array.forEach (<anonymous>)
    at MessageBus.value (http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:1992)
    at Object.call (http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:2822)
    at Object.callHook (http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:6294)
    at new Component (http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:104800)
    at http://myproject.test/vendor/livewire/livewire.js?id=591698dbd067627ac4cf:13:128539
    at Array.forEach (<anonymous>)
generateNewState @ SyncBrowserHistory.js:66
(anonymous) @ SyncBrowserHistory.js:14
(anonymous) @ MessageBus.js:17
value @ MessageBus.js:16
call @ HookManager.js:38
callHook @ Store.js:120
Component @ index.js:46
(anonymous) @ index.js:77
value @ index.js:76
(anonymous) @ setup:1178
```

**Comment by calebporzio** [comment]
Ok, thanks I will look into this today

**Comment by nuernbergerA** [comment]
Related https://github.com/livewire/livewire/discussions/1587

**Comment by masterix21** [comment]
The problem goes away if you clear the session storage

**Comment by calebporzio** [comment]
Ok v2.2.3 only uses sessionStorage if it HAS to, and even then there is a system to clean up old entries if the storage has exceeded the maximum

Closing this. Re-open if persists. Thanks!

**Comment by KenLewis** [comment]
Thank you Caleb! You rock! I'm going to test the hell out of it tomorrow.
