### ISSUE TITLE
Passed properties are nullified when using wire:click inside component.

### ISSUE THREAD

**Issue by alecritson** [livewire/livewire#1598]
### Description

When using `wire:click` in a component that sets a property on `mount` it gets nullified.

### Steps to reproduce

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Tester extends Component
{
    protected $foo;

    public function mount($foo)
    {
        $this->foo = $foo;
    }

    public function bar()
    {
        //
    }

    public function render()
    {
        return view('livewire.tester', [
            'foo' => $this->foo,
        ]);
    }
}
```

```html
<livewire:tester foo="Foo" />
```

```html
<div>
    {{ $foo }}
    <button wire:click="bar">Bar</button>
</div>
```

On render, `$foo` is `Foo` then when you click the button `$foo` is null and the text disappears.

**Context**
- Livewire version: 2.2.2
- Laravel version: 7.28.1
- Browser: Chrome

**Comment by calebporzio** [comment]
It's because foo is a protected property, and those are not tracked between requests
