### ISSUE TITLE
Cannot filter search results

### ISSUE THREAD

**Issue by BinWang01** [livewire/livewire#1599]
### Description
I created a search component and several filter buttons. The filter buttons are able to filter articles by category if I don't enter any keywords in the search input box. But after I enter a keyword and some search results are returned, I cannot use those filter buttons to filter search results by category.

Code in blade 'livewire.search-articles' :

```
<input wire:model.live="search" class="form-control" type="text" placeholder="Search Articles...">
<a wire:click.prevent="filterBy('')" role="button" href="#">All</a><br/>
<a wire:click.prevent="filterBy('networking')" role="button" href="#">Category</a>
```

Each Article model has a Category via a one-to-many relationship. Code in Article model:
    
```
public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

public static function search($query)
    {
        return empty($query) ? static::query()
            : static::where('title', 'like', '%'.$query.'%')
                ->orWhere('body', 'like', '%'.$query.'%');
    }
```

Code in livewire component:

    ```
    public $search = '';
    public $filterBy = '%';

    public function filterBy($field)
    {
        if($field != '')
        {
            $this->filterBy = $field;
        }
        else
        {
            $this->filterBy = '%';
        }
    }

    public function render()
    {
        return view('livewire.search-articles', [
        'articles' => Article::search($this->search)
                                ->whereHas('category', function (Builder $query) {
                                       $query->where('slug', 'like', $this->filterBy);})
                                ->paginate($this->perPage)
        ]);
    }
```

This is the response I received. Looks like after the filterBy function was executed, the request didn't query the database again to get new data or return filtered result based on existing data.

{"effects":{"html":null,"dirty":["filterBy"]},"serverMemo":
{"data":{"filterBy":"networking"},
"checksum":"91a05ee86958e4e280203ebb9c37ee1bfd024deb1794e02b72aefb24d7da7bd6"
}}

Thank you for your help!

### Steps to reproduce

**Context**
- Livewire version: [2.2.2]
- Laravel version: [8.2.0]
- Browser: [Chrome]

**Comment by iksaku** [comment]
I don't thinks this is a Livewire issue, more like a logic issue while using Eloquent.

Did you try using [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) to see if your queries are actually executed?

**Comment by BinWang01** [comment]
> I don't thinks this is a Livewire issue, more like a logic issue while using Eloquent.
> 
> Did you try using [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) to see if your queries are actually executed?

It was caused by the Eloquent query. I have updated the query and it's working now. Thank you!
