### ISSUE TITLE
Uncaught TypeError: Cannot read property '$wire' of undefined

### ISSUE THREAD

**Issue by gpanos** [livewire/livewire#1600]
### Description
I get this error when following the docs to add an inline script with a listener inside. The error is thrown because of the `@this` directive which tries to find a component by id. The component somehow is not found. 

```js
find(componentId) {
    return this.components.componentsById[componentId].$wire
}
```

### Steps to reproduce
1) Create a fresh Laravel application 
2) Install Livewire 
3) Add the styles and the scripts in your template

```html 
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        @livewireStyles
    </head>
    <body class="antialiased">
        <div>
            <livewire:foo/>
        </div>

        @livewireScripts
    </body>
</html>
```
4) Generate a Livewire component `php artisan livewire:make Foo`
5) Edit the generated template 
```html
<div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Run a callback when an event ("foo") is emitted from this component
            @this.on('foo', () => {})
        })
    </script>
</div>
```
6) Open your console to see the error

**Context**
- Livewire version: 2.2
- Laravel version: 8
- Browser: Chrome

**Comment by nuernbergerA** [comment]
Hey @gpanos 

can you please try to listen for `livewire:load` instead of `DOMContentLoaded`?

**Comment by gpanos** [comment]
@nuernbergerA  yes this works maybe the docs need to be updated ? https://laravel-livewire.com/docs/2.x/inline-scripts

**Comment by nuernbergerA** [comment]
Can you PR that to the docs?

**Comment by gpanos** [comment]
Yep thanks a lot for your help cheers.
