### ISSUE TITLE
iOS Safari cannot download files

### ISSUE THREAD

**Issue by jimpeters** [livewire/livewire#1605]
### Description

iOS Safari cannot download files.  Inspecting a simulator of iPad/iPhone in Safari I see the following when Livewire Javascript attempts to create the hidden link containing the createObjectURL.

Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.)

I have attempted to find solutions to this and am unable to come up with a competent answer.

### Steps to reproduce

https://laravelplayground.com/#/snippets/d29b28f0-fefb-4567-90d1-2fbeba8ab8a3

Try to download the file on an iOS device.

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 7.27.0]
- Browser: [iOS Safari]

**Comment by calebporzio** [comment]
Fixed in merged PR
