### ISSUE TITLE
Array reindexing with nested arrays not always working right

### ISSUE THREAD

**Issue by austenc** [livewire/livewire#1607]
### Description

Sometimes when an array public property is reindexed on the PHP side things go haywire. I was working with an array of cities and noticed that they weren't in perfect alphabetical order in the dropdown (select) field I was building.  

From what I can tell it's caused by the `reindexArrayWithNumericKeysOtherwiseJavaScriptWillMessWithTheOrder` method. It has something to do with the `uksort` being called recursively with `array_map`. I would've preferred to submit a PR but haven't figured it out yet!

Here's the line: 
https://github.com/livewire/livewire/blob/master/src/HydrationMiddleware/NormalizeDataForJavaScript.php#L25

In `1.x` it's here:
https://github.com/livewire/livewire/blob/1.x/src/Component.php#L175

### Steps to reproduce
In the example, you'll notice the array is alphabetized in the component definition, but when it gets to the view it is all jumbled.

https://laravelplayground.com/#/snippets/ccd2908b-0f16-422f-998f-18f2c82118e8

**Context**
- Livewire version: 1.3.4 (likely 2.x also)
- Laravel version: 7.x
- Browser: Brave

**Comment by austenc** [comment]
So this actually comes down to how javascript doesn't care about the ordering of keys within objects.

Even though it's reordered on the PHP side before hitting JS, it gets reordered again after JS gets ahold of it anyway. 

The _solution_ is to use numerically keyed arrays when you need order to matter. Not associative ones. 

Every solution (on the livewire side) that I can think of is **really gross.** So given that, I'm closing this issue.

**Comment by calebporzio** [comment]
Thanks for following up @austenc !
