### ISSUE TITLE
nested boolean not working

### ISSUE THREAD

**Issue by adrian-ub** [livewire/livewire#1608]
### Description

I am using an array and in it a boolean and it always returns null

### Steps to reproduce
```
public $slider = [];

<input type="checkbox" wire:model="slider.published" class="block mt-1 form-checkbox">
```
**Context**
- Livewire version: ^2.2
- Laravel version: ^8.0
- Browser: Brave (Chromium)

**Comment by massimodellarovere** [comment]
Check if in your application exist a middleware with trim string and set to NULL
