### ISSUE TITLE
Fingerprint exception insted of AuthorizationException when testing exceptions inside mount method

### ISSUE THREAD

**Issue by jcergolj** [livewire/livewire#1613]
### Description
_ErrorException: Undefined index: fingerprint_ exception is thrown when testing throw exception inside mount method.

### Steps to reproduce

```
 /**
     * Component mount.
     *
     * @return void
     */
    public function mount()
    {
        if ($this->user->isHimself(auth()->user())) {
            throw new AuthorizationException();
        }
    }
```

```
 Livewire::actingAs($this->admin)
            ->test(EditUserComponent::class, ['user' => $this->admin])
            ->call('update')
            ->assertForbidden();
```
**Context**
- Livewire version: 2.2.3
- Laravel version: 8.0
- Browser: irrelevant

**Comment by austenc** [comment]
Here's a fully copy and pastable component class and test class to reproduce this:

**Example.php**
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Auth\Access\AuthorizationException;

class Example extends Component
{
    public function mount($user)
    {
        throw new AuthorizationException();
    }
    
    public function update()
    {
    }
 
    public function render()
    {
        return view('livewire.example');
    }
}
```

**ExampleTest.php**
```
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Livewire\Livewire;
use App\Http\Livewire\Example;
use App\Models\User;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_livewire_bug()
    {
        $user = User::factory()->create();
        Livewire::actingAs($user)
            ->test(Example::class, ['user' => $user])
            ->call('update')
            ->assertForbidden();
    }
}
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
