### ISSUE TITLE
Refreshing form

### ISSUE THREAD

**Issue by aminireza-ir** [livewire/livewire#1616]
There is a bug in Livewire with Turbolink.
When we open a form with <a> tag in a Project with Livewire and Turbolink the form will be refreshed (with wire:submit.prevent).
But if we try to open the form without <a> tag in the project and open it directly in Browser it will be solved.

**Comment by austenc** [comment]
@aminireza-ir can you perhaps create an example repo so this can easily be reproduced?

**Comment by calebporzio** [comment]
Closing this because there isn't enough info to assist. Please re-submit with source code and more info if it persists!
