### ISSUE TITLE
How to handle authorization via middlewares

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#162]
Today I noticed an issue with Livewire and routes that are protected by authorization middlewares.

The component will initially load as defined by the policy that is enforced by the middleware. Now where the issue kicks in is when I trigger any action that causes a request to the server which will result in a 403.

**Route**
https://github.com/convertlog/convertlog/blob/master/routes/dashboard.php#L91-L93

**View**
https://github.com/convertlog/convertlog/blob/master/resources/views/livewire/notification-settings/email.blade.php#L40

**Components**
https://github.com/convertlog/convertlog/blob/master/app/Http/Livewire/NotificationSettings/NotificationSettings.php

What would currently be the recommended way of handling cases where Livewire components are pages and protected by middlewares for authentication and authorization?

**Comment by faustbrian** [comment]
The issue seems to be that `getGateArguments` in this line https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/Middleware/Authorize.php#L43 returns an empty array because it runs against `/livewire/message` instead of the URL of the page/component which would contain the model.

That seems like a tricky one to solve as this is the direct result of how Livewire works overall.

**Comment by faustbrian** [comment]
@calebporzio What do you think would be the best approach here?

1. Make authorization middlewares work nicely together with components which requires some changes to how requests are send due to missing route bindings.
2. Decouple Livewire from middlewares for authorization and introduce a `authorize` method on components that would be called as `abort_unless($this->authorize(), 403)` before a component is rendered.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ShowPost extends Component
{
    public function authorize(): View
    {
        return Gate::allows('update', Post::first());
    }
}
```

**Comment by wsamoht** [comment]
I am also curious on this. I just made a "hacky" work around.

I have a route like this using a Policy:
```php
Route::get('organizations/{type}/{number}/edit')
    ->middleware('can:update,Models\Organization');
```

My middleware loads the organization based on `type` and `number` by pulling them from the route.

```php
$organization = Organization::getByTypeAndNumberOrFail(
    request()->route('type'),
    request()->route('number')
);
```

As @faustbrian mentioned, when Livewire calls this middleware, the route values are `null` as the request is a Livewire request.

For the time being, I set two public properties of `type` and `number` on the component and in the middleware first checking the route and then `request()->data['type|number']`.

I am looking for a better solution. I could store the `Organization` model in Livewire's State Management when the page initially loads and trust that they still have access to that organization on subsequent requests by Livewire but I don't like that. I like to explicitly check auth on every request.

I think @faustbrian idea of an `authorize` method on the Component is a good alternative.

Open to other suggestions and best practice for this in Livewire!

**Comment by calebporzio** [comment]
@faustbrian - yeah, I think you're right. An "->authorize()" method is best.

The middleware mimicking in livewire used to make sense before other security measures were in place. I think I'll remove it. It just causes more headaches and doesn't even really make sense anymore.

**Comment by calebporzio** [comment]
@faustbrian / @wsamoht -> mind checking over this PR: https://github.com/livewire/livewire/pull/309

I want to make sure I'm not messing anything up.

Are we safe to just assign the default `web` middleware group to the `livewire/message/` route?

**Comment by wsamoht** [comment]
I am not yet familiar enough with the inter-workings of Livewire to comment on whether or not you are messing things up :) But, it does make sense to remove the middleware mimicking and add a `->authorize()` method so the developer can have full control of any required authorization. Are you thinking of adding the `authorize` option in this PR or with the release of this change? Just wondering as I am using Livewire in an admin panel so I need some sort of authentication. Can you also elaborate on the "other security" measures that are in place?

Thinking about assigning the default `web` middleware group, I think that works. Livewire is always going to be used with a GUI/frontend so it makes sense to apply that just like any other web page/route. Maybe though, a config option could be added, like `middleware_group` if someone wanted to override it?

**Comment by wsamoht** [comment]
Just had an idea in that why not use the `Illuminate\Foundation\Auth\Access\AuthorizesRequests` trait like Laravel controllers do. I added the trait and am calling `$this->authorize` in my Livewire component `save` method. Works great!

Maybe just remove the middleware logic, add the `web` middleware group, and document that if you need authorization, use the `AuthorizesRequests` trait and Laravel's standard gates/policies.

**Example:**
```php
use Livewire\Component;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class OrganizationEdit extends Component
{
    use AuthorizesRequests;

    public $type;
    public $number;

    public function mount(Organization $organization)
    {
        $this->type = $organization->type;
        $this->number = $organization->number;
    }

    public function render()
    {
        return view('livewire.app.organization-edit');
    }

    public function save()
    {
        $organization = Organization::getByTypeAndNumberOrFail($this->type, $this->number);

        $this->authorize('update', $organization);

        // Do saving stuff
    }
}
```

**Comment by calebporzio** [comment]
Solid! I changed livewire to not mimic middleware, default to `"web"`, and added a config option for the middleware group called: `config('livewire.middleware_group')`.

Also, I added documentation describing your solution:
https://laravel-livewire.com/docs/authorization/

Great work on this! Thanks a bunch all the great help!

**Comment by ragulka** [comment]
I'm curious whether this pattern can/should also be used for scoping? I mean something like this: https://forum.laravel-livewire.com/t/scoping-component-data-based-on-url-path/322

Where you have a route like: app.com/{company}/products, you'd normally want to scope the list of products to the company, also making sure the current user can even access the company in the first place. Easy enought with standard Laravel, but when Livewire fetches the component via AJAX, the scoping is gone, because there is no {company} in the livewire endpoint path.

I got it to work by passing `$company` as a public prop to the `ProductsList` component, but I'm a little concerned that since Livewire simply passes this via AJAX back to the server, it can be tampered with and changed. 

I would normally just use a middleware on those company-scoped paths, but Livewire only uses a single middleware group. This makes it impossible to use the middleware for company-scoped components only. 

This made me think whether I should forego the middleware in my controllers for ensuring proper scope completely, and simpply use Policies, which would always check if the user has access to the company in question, and only then check if they can for example, update a product for that company.
