### ISSUE TITLE
[2.x] Alpine $wire.emit, $wire.emitTo, $wire.emitUp not working

### ISSUE THREAD

**Issue by timrspratt** [livewire/livewire#1621]
### Description

Using Alpine inside an Livewire component to emit events results in errors like:

<img width="537" alt="Screenshot 2020-09-17 at 00 23 53" src="https://user-images.githubusercontent.com/20431294/93402420-99e86980-f87c-11ea-939b-8a018c079dcb.png">

### Steps to reproduce

```blade
{{-- views/resources/livewire/parent-component.blade.php --}}
<div>
    <div x-data>
        <button @click="setTimeout(() => $wire.emitTo('child-component', 'something'), 350)">Click</button>
        @livewire('child-component')
    </div>
</div>
```

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.3.0
- Browser: Chrome

**Comment by timrspratt** [comment]
@calebporzio should https://github.com/livewire/livewire/blob/master/js/component/index.js#L651 be:

```js
return store[property].apply(store, args)
```

**Comment by austenc** [comment]
@timrspratt Looks like this may be fixed in the latest version. 

https://github.com/livewire/livewire/blob/master/js/component/index.js#L654
