### ISSUE TITLE
v2 Model binding initializing and unique validation errors

### ISSUE THREAD

**Issue by 3alampro** [livewire/livewire#1628]
### Description
I can't use the new feature where we bind directly to model I'm not sure why i keep getting errors and if I try to fix it on the mount method the unique validation not working out of the box 

### Exact steps to reproduce
in my Livewire Form class 

I set $user to User Model

```php
public User $user;
```

and adjusted my `protected $rules` property to include the `user.` into each rules for it to work

if I submit the form this what I get 

```
TypeError
Typed property App\Http\Livewire\Back\User\Form::$user must be an instance of App\Models\User, null used
```

and if I try to set the user property in the mount method to initiate new User Model like this
 
```php
public function mount()
    {
        $this->user = isset($this->user) ? $this->user : new User;
    }
```

every thing work except when I try to use unique rules validation on any field I get this error

```
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.email' in 'where clause' (SQL: select count(*) as aggregate from `users` where `user`.`email` = admin@admin.test)
```

to fix it I needed to adjust the validation rules to include the correct column name like this

```php
'user.email' => [
            'required',
            'unique:users,email',
            'email',
        ]
```

**Context**
- Livewire version: [2.2.3]
- Laravel version: [8.2.0]
- Browser: [Chrome]

**Comment by 3alampro** [comment]
and for some reason the `same ` validation rules isn't working 

```php
'user.passwordConfirmation' => [
            'required',
            "same:password",
            'min:8',
        ]
```

I need to dig more but I keep getting 

`The passwordConfirmation and password must match.`

even tried `same:user.password` but nothing change keep getting the same error

**Comment by isaackearl** [comment]
Hello, I've been having the same issues, but wanted to point out that you can temporarily workaround the first issue in another way by not using strong typing
```
public User $user; // change this to just public $user 
```

My theory on this is that most of the development on livewire has happened while using slightly older versions of php that don't have the recent addition of strong typing for the public properties.  It just hasn't been changed to work properly with that yet.

**Comment by iksaku** [comment]
As a little note, since you're trying to use typed properties, I assume that you're using PHP 7.4. In this case, and for the future, you can assign a *new model instance* using the [Null Coalescing Assignment](https://wiki.php.net/rfc/null_coalesce_equal_operator):

```php
public User $user;

public function mount()
{
    $this->user ??= new User();
}
```

It may not provide much of a fix to the issue, but could help you clean a little bit the mount line :wink:

**Comment by iKlsR** [comment]
Yh can confirm model binding not working either, on latest everything. I can see the model with just `{{ $user }}` and access data but I can't bind to it.

**Comment by iksaku** [comment]
Oh yeah! That's it @iKlsR.

@3alampro, in order to use model bindings, make sure to define a `protected $rules` property containing the validation rules needed for your model's properties to be saved.

For more information, [please refer to Model Binding Docs[(https://laravel-livewire.com/docs/2.x/properties#binding-models).

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
