### ISSUE TITLE
Error on deleting an item after creating that item without refreshing the page(f5)

### ISSUE THREAD

**Issue by w99910** [livewire/livewire#1629]
In 'Purchase' livewire component, I create the **Cart**(which is the model) and refresh the component. And I wanna delete the created cart .. So I use wire:click with the **Cart** id to delete the cart. 
$cart=Cart::find($id); 
and I dd($cart); It has value but when I do $cart->delete(); , I got 404 error . 
![Screenshot (97)](https://user-images.githubusercontent.com/65523475/93488869-d4a9da80-f92c-11ea-9b3e-8aefbfa5dd0c.png)
![Screenshot (98)](https://user-images.githubusercontent.com/65523475/93488876-d7a4cb00-f92c-11ea-9aa4-2b79e2bcc886.png)
![Screenshot (99)](https://user-images.githubusercontent.com/65523475/93488880-d96e8e80-f92c-11ea-8b8d-60952b99d21e.png)

**Comment by MiracleInNutShell** [comment]
Can someone help me ?😅

**Comment by w99910** [comment]
Solved! It's because I set the 'id' to the div element. So the livewire seems that it cannot be updated properly to that div.
Thanks :)
