### ISSUE TITLE
v2.0 is adding query string to the url that I did not define in the component

### ISSUE THREAD

**Issue by aimensasi** [livewire/livewire#1634]
### Description

When the component is mounted, Livewire takes special request parameters and add them to the url of the page.

### Exact steps to reproduce

Add new data to the request object using `$request->merge([ 'currency' => '1' ])` from a middleware.

Once the component loads the url is updated with the request data. Note that I am not using Livewire `queryString`. Also this seems to happen only when adding the following the component.

```
<?php

namespace App\Http\Livewire\Library;

use App\Models\Library\Chapter;
use Livewire\Component;

class ViewChapterComponent extends Component {

	public Chapter $chapter;


	public function mount(Chapter $chapter) {
		$this->chapter = $chapter;
	}

	public function render() {
		return view('library.view-chapter-component');
	}
}
```

```
https://app.test/library/2/chapter?currency=1
```

If I remove the `mount` method and the property initialisation, everything is back to normal.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: v2.2.3
- Laravel version: v8.4.0
- Browser: Chrome

**Comment by iksaku** [comment]
It sounds to me more like a Laravel routing logic issue.

Could you provide the route definition (from your `web.php` file) to your Livewire component and paste the HTML tag you're using to navigate to this component? It may be an `<a>` tag.

**Comment by avr** [comment]
I have this same issue.

I believe it was introduced in 861b683 - in [SupportBrowserHistory](https://github.com/livewire/livewire/blob/1cb6e76b69c838f5da6943e8ac7e689600106e61/src/RenameMe/SupportBrowserHistory.php#L141). Instead of limiting params to the keys of the `$queryString` property, we're now just getting any input from the request - including anything merged in via another middleware or service provider.

I'm not sure if it's a great solution, but I solved it by just passing an empty array.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by avr** [comment]
@calebporzio - Would you be open to a PR that does something like this (similar to your current `$excepts` in `mergeComponentPropertiesWithExistingQueryParamsFromOtherComponentsAndTheRequest`

```
$ignores = $this->getIgnoresFromComponent($component);
```

```
->reject(function ($value, $key) use ($ignores) {
    return in_array($key, $ignores);
})
```

My use case is that I'm merging some data into the request via a Middleware. Ideally, I don't want this additional data exposed via any query params. I've gotten around a few merged in items by refactoring - but I can't get around these last items.

**Comment by ultrasamad** [comment]
I'm facing the exact same issue right now. I am adding data to the request in  a middleware and Livewire is displaying this data in the URL.
I'm not using livewire query strings either.
@avr Have you found a solution yet?

**Comment by robmcvey** [comment]
Overwrite `getQueryString` in your component, and use the `except` key in your query 

```php
public function getQueryString()
{
    return [
        'page',
        'currency' => [
            'except' => 1
        ]
    ];
}
```

**Comment by NerdOfLinux** [comment]
REOPEN

**Comment by VictorMLima98** [comment]
> Ok, we found a solution that matches our requirements.
> 
> Instead of
> 
> ```
> $request->merge([ 'currency' => '1' ]);
> 
> // access
> $request->input('currency');
> ```
> 
> we used attributes:
> 
> ```
> $request->attributes->add([ 'currency' => '1' ]);
> 
> // access
> $status = $request->attributes->get('currency');
> ```

Thank you very much man! It helped a lot.
