### ISSUE TITLE
404 error with published

### ISSUE THREAD

**Issue by emadalslahi** [livewire/livewire#1651]
### Cannot getting response 

**Context**
- Livewire version: [ 2.x]
- Laravel version: [7.x or 8.x 
- Browser: [e.g. Chrome, Safari]
.......

when try to publish livewire,  and run my app without artisane serve 
try any click action 
it shows error as **404 not found** 
however i put asset_url correct,  and reqest get access my method but the result not ther 
....
eg.  the counter example from docs 
when click button + result is **404 not found**
but with change in code if i run 
php artisan serve 
it will work good.. 
?!!

**Comment by ryanmortier** [comment]
Might be related to https://github.com/laravel/jetstream/issues/236

**Comment by danharrin** [comment]
Hey, please move this to a Discussions thread, with a minimal code example. Many thanks.
