### ISSUE TITLE
[Typed returns conflict] "should return Livewire\Redirector but returns Illuminate\Http\RedirectResponse"

### ISSUE THREAD

**Issue by johanvanhelden** [livewire/livewire#1658]
### Description
I am using typed returns in my code and both my IDE and Larastan are detecting errors if I use the actual class that is being returned by Livewire.

### Exact steps to reproduce

Simply apply a typed return to a method that performs a redirect, like so:

```php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use Livewire\Redirector;

class SubscriptionForm extends Component
{
    public function unsubscribe(): Redirector
    {
        return redirect()->route('page.home'));
    }
}

```

This code will work flawlessly but both my IDE and Larastan are complaining:
![Screenshot from 2020-09-21 19-18-28](https://user-images.githubusercontent.com/19389981/93799289-40e35180-fc3f-11ea-8898-7e089afba317.png)

![Screenshot from 2020-09-21 19-19-02](https://user-images.githubusercontent.com/19389981/93799351-55bfe500-fc3f-11ea-9995-cd85ef4e34a9.png)

If you use the actual class that the IDE and Larastan expect, a RedirectResponse, you get the following error:
`Return value of App\Http\Livewire\SubscriptionForm::unsubscribe() must be an instance of Illuminate\Http\RedirectResponse, instance of Livewire\Redirector returned `

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.2.0
- Browser: Firefox

**Comment by bensherred** [comment]
Livewire's `Redirector` class extends `Illuminate\Routing\Redirector` so you could change the typed return to use this class instead. Alternativaly setting the returned type to `Livewire\Redirector` will still work as well.

**Comment by johanvanhelden** [comment]
@bensherred you are correct that setting the return type to `Livewire\Redirector` will work, as in, not break the code. 

However, static analyzers and my IDE will spit out errors. In my opinion this should be fixed in the Livewire side to be less magical.

Setting it to `Illuminate\Routing\Redirector` will not work however. This will give the same issue. Because a RedirectResponse does not extend that Illuminate Redirector:
![Screenshot from 2020-09-22 15-33-30](https://user-images.githubusercontent.com/19389981/93889010-00401280-fce9-11ea-90d6-5996b0d2c907.png)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by johanvanhelden** [comment]
REOPEN

**Comment by calebporzio** [comment]
Closing this. I don't consider this a bug. If you find a simple, safe, tested, elegant solution to this please PR. Otherwise, closing.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mwamodo** [comment]
Passed thought here while trying to fix a similar issue. Figured you are using php8.0 you could use union types. Something like

```php

public function login(): RedirectResponse|Redirector
{
	return redirect()->intended('dashboard');
}

```

**Comment by benjibee** [comment]
> Closing this. I don't consider this a bug. If you find a simple, safe, tested, elegant solution to this please PR. Otherwise, closing.

@calebporzio could you provide just a little guidance here as to how to properly type-hint the return value here?

I'm still scratching my head over this as returning a class like `\Livewire\Redirector` seems very odd instead of something like `\Illuminate\Http\RedirectResponse`. Maybe it's something simple I'm missing?

**Comment by BrianHannay** [comment]
I'm still wondering about this too. I can define the function like
```
public function exampleFunction() : \Livewire\Redirector
```

And that works at runtime, but I'm still getting errors during static analysis ([PHPStan](https://phpstan.org/) + [larastan](https://github.com/larastan/larastan)) that I can't seem to resolve.

Since then, I changed the function to:
```
/**
 * @return \Livewire\Redirector|\Illuminate\Http\RedirectResponse|null
 */
private function exampleFunction()
```

I've even tried writing a `DynamicFunctionReturnTypeExtension` to return a `UnionType` of `RedirectResponse` and `Redirector`, but I'm still seeing warnings in some places:
```
  333    Method App\Http\Livewire\ExampleFile::exampleFunction() never returns Livewire\Redirector so it can be removed from the return type. 
```

I've checked the return type for this function, and it returns Livewire\Redirector at runtime. It returns `redirect()->to('page');`.

If anyone has some idea on how to resolve this, please let me know!

```
<?php

namespace PHPStanExtensions;

use function count;
use PhpParser\Node\Expr\FuncCall;
use PHPStan\Analyser\Scope;
use PHPStan\Reflection\FunctionReflection;
use PHPStan\Type\DynamicFunctionReturnTypeExtension;
use PHPStan\Type\ObjectType;
use PHPStan\Type\UnionType;
use PHPStan\Type\Type;

/**
 * @internal
 */
final class RedirectExtension implements DynamicFunctionReturnTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function isFunctionSupported(FunctionReflection $functionReflection): bool
    {
        return $functionReflection->getName() === 'redirect';
    }

    /**
     * {@inheritdoc}
     */
    public function getTypeFromFunctionCall(
        FunctionReflection $functionReflection,
        FuncCall $functionCall,
        Scope $scope
    ): Type {
        if (count($functionCall->getArgs()) === 0) {
            return new UnionType(array(
                new ObjectType(\Illuminate\Routing\Redirector::class),
                new ObjectType(\Livewire\Redirector::class),
            ));
        }

        return new UnionType(array(
            new ObjectType(\Illuminate\Http\RedirectResponse::class),
            new ObjectType(\Livewire\Redirector::class),
        ));
    }
}
```

**Comment by delboy1978uk** [comment]
@calebporzio This is absolutely a bug and should be re-opened. The code is telling us it is will return a redirect response, but it does not.

<img width="922" alt="Image" src="https://github.com/user-attachments/assets/d67b3983-fd17-453f-95ef-67432fe07108" />

**Comment by delboy1978uk** [comment]
REOPEN

**Comment by benjibee** [comment]
> REOPEN

I agree this issue should be reconsidered but this is not an okay tone to use.

**Comment by johanvanhelden** [comment]
> > REOPEN
> 
> @delboy1978uk I agree this issue should be reconsidered but this is not an okay tone to use. 

I was also shocked to read it, but this is a reply to get the bot to reopen the ticket. See: https://github.com/livewire/livewire/issues/1658#issuecomment-719031858

But I think after 4 years, it's no longer working.

**Comment by delboy1978uk** [comment]
> > REOPEN
> 
> [@delboy1978uk](https://github.com/delboy1978uk) I agree this issue should be reconsidered but this is not an okay tone to use.

Apologies if there was any confusion, I noticed someone else issued this command as a comment and a bot re-opened the ticket. Although it didn't work for me when I tried.

**Comment by benjibee** [comment]
> > > REOPEN
> > 
> > 
> > [@delboy1978uk](https://github.com/delboy1978uk) I agree this issue should be reconsidered but this is not an okay tone to use.
> 
> Apologies if there was any confusion, I noticed someone else issued this command as a comment and a bot re-opened the ticket. Although it didn't work for me when I tried.

Sorry, I've been reading through issues on OS projects with some really rude comments lately so the all-caps just triggered something. False alarm :)

**Comment by delboy1978uk** [comment]
No worries man. But OK so no  one is disagreeing, this should be reopened? :-) Who can  we ask to make that happen?

**Comment by joshhanley** [comment]
> Closing this. I don't consider this a bug. If you find a simple, safe, tested, elegant solution to this please PR. Otherwise, closing.

@delboy1978uk see this comment from Caleb above. If you want to fix it, PR's are welcome 🙂

**Comment by delboy1978uk** [comment]
But he's wrong, it _is_ a bug. I'll consider a PR if there is an open ticket.

**Comment by joshhanley** [comment]
@delboy1978uk no it's not going to be reopened as we are now using discussions to track bugs and ideas.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423. You're more than welcome to open a new bug discussion but that won't change Caleb's response above. But as has been stated a few times, PRs to fix it are welcome and that's the best way to get Caleb to review it.

**Comment by delboy1978uk** [comment]
@joshhanley thanks, i had no idea that the issues tab was no longer being used, indeed I have found the bug in the discussions tab https://github.com/livewire/livewire/discussions/9245
