### ISSUE TITLE
Better Serverless support (LivewireManager::javaScriptAssets() should be more configurable, care taken for component auto-discovery)

### ISSUE THREAD

**Issue by ralphschindler** [livewire/livewire#1662]
### Description

In attempting to make Livewire work in a Serverless / AWS Lambda environment (specifically Bref, which I assume is similar in scope to Vapor), it is hard to achieve a deployment where assets are located in S3 and the application is served from Lambda.

The problem is that LivewireManager::javaScriptAssets() is trying to compute and detect too many values. Typically I would want assets delivered from S3 which is generally configurable (typically at the env `ASSET_URL` / config value `app.asset_url` and the app's base URL for routes is at the configured location (typically at env `APP_URL` or config value `app.url`).

Currently, `javaScriptAssets()` is trying to deduce the *`appUrl`* from the *assets url*:

https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L168

This value is later used on the rendered javascript:

https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L209

Generally, people will actually [publish their js vendor file, so then the Vapor detection](https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L179-L184) would be expected to run to change some of these values.

I've made this work by hacking `isOnVapor()`, and then configuring `livewire.asset_url` to use the `APP_URL` value (in `config/livewire.php`: `'asset_url'  => env('APP_URL', null),`):

```php
    public function isOnVapor()
    {
        return ($_ENV['SERVER_SOFTWARE'] ?? null) === 'vapor'
            || ($_ENV['SERVER_SOFTWARE'] ?? null) === 'bref';
    }
```

But this then further causes issue b/c in a serverless environment you need to be able to write a file to `/tmp` at a deep location, so this is also required in bootstrap.php (to facilities component auto-discovery caching):

```php
if (isset($_ENV['SERVER_SOFTWARE'])
    && $_ENV['SERVER_SOFTWARE'] === 'bref'
    && !file_exists('/tmp/storage/bootstrap/cache'))
{
    mkdir('/tmp/storage/bootstrap/cache', 0777, true); // recursive create directories
}
```

#### Proposed Solutions?

I hesitate to make a PR because there is a range of solutions, but I don't mind taking a stab at it if you had a preferred direction.

My best advice for a PR would be more specific (optional) config keys that when set will also disable some of the code-paths that do some of the more auto-magic discovery (eg: `isOnVapor()`).

### Exact steps to reproduce

I have an app running that demonstrates the issues I can share.

**Context**
- Livewire version: 2.2.5
- Laravel version: 8
- Browser: all

**Comment by ragulka** [comment]
It seems to me that the current `asset_url` / `$appUrl` implementation is not only confusing, but has flaws in it. The [documentation](https://laravel-livewire.com/docs/2.x/installation#publish-assets) states:

> By default, Livewire serves its JavaScript portion (livewire.js) from the following route in your app: /livewire/livewire.js.
> 
> The actual script tag that gets generated defaults to:
> `<script src="/livewire/livewire.js"></script>`
>
> There are two scenarios that will cause this default behavior to break:
> 
> 1. You publish the Livewire assets and are now serving them from a sub-folder like "assets".
> 
> 2. Your app is hosted on a non-root path on your domain. For example: https://your-laravel-app.com/application. In this case, the actual assets will be served from `/application/livewire/livewire.js`, but the generated script tag, will be trying to fetch `/livewire/livewire.js`.

**First scenario above**

If you publish the assets to a `public/assets` (for whatever reason), but the rest of your app is still available on the root path (`/`), it does serve the livewire/livewire.js file from the correct URL (`/assets/livewire/livewire.js`), but all the other Livewire routes are now also prefixed with `/asset`, for example `/assets/livewire/message` etc.

Some thoughts here:
* Under this scenario, using `asset_url` configuration value actually breaks Livewire. 
* Livewire routes should _not_ use the `asset_url` at all.
* If using Vapor, `app.asset_url` is used instead. Why not use it regardless if using Vapor? Why provide a separate configuration value for Livewire's published assets? Is there a legitimate use-case where Livewire assets are not served from the same place where all other assets are served from (including other vendor assets)?

**Second scenario above**

The `livewire.asset_url` configuration option seems to only serve the second scenario where the app is in a non-root path. In this case, however, isn't `APP_URL` ENV variable enough/a more suitable option? After all, this will need to be set anyway when the app is installed in a subfolder/non-root path.

**Comment by ralphschindler** [comment]
@ragulka - very succinct, thanks!

Regarding:

> If using Vapor, app.asset_url is used instead. Why not use it regardless if using Vapor? Why provide a separate configuration value for Livewire's published assets? Is there a legitimate use-case where Livewire assets are not served from the same place where all other assets are served from (including other vendor assets)?

I have to guess that @calebporzio's intention was that the library "just work" whether you've published the assets or not. If you have not, then the livewire.js file would be delivered via php from a route served from the `app.app_url`-ish path. Put another way, if you don't publish your assets (basically a `file_exists(public_path('vendor/livewire'))` is tested), then `/livewire/livewire.js` is served, otherwise it will attempt to serve `/vendor/livewire/livewire.js`.

Here is the best PR I currently have thought out:

* Fix the JS line to read `window.livewire_app_url = '{$appUrl}';` where that value is the actual `app.url`.
* If `livewire.asset_url` is `null`, check to see if assets have been published, if they have use `app.asset_url` to serve assets from that path, if they have not been published, build the route to the asset serving route (which in turn will internally use `app.url` anyway in the route generation)

Thoughts @ragulka?

**Comment by ragulka** [comment]
> I have to guess that @calebporzio's intention was that the library "just work" whether you've published the assets or not

@ralphschindler sure, that makes a lot of sense. It just seems that the implementation has some quirks.

> * Fix the JS line to read `window.livewire_app_url = '{$appUrl}';` where that value is the actual `app.url`.

That makes a lot of sense to me. The only thing with this approach is that since Laravel defaults `app_url` to `http://localhost`, the script tag and `window.livewire_app_url` would not be using an absolute path (`/`) anymore, but rather the full URL. So something like `<script src="http://localhost.com/livewire/livewire.js">` (depending on the configured app URL, of course). Do you see any potential issues there?

> If livewire.asset_url is null, check to see if assets have been published, if they have use app.asset_url to serve assets from that path, if they have not been published, build the route to the asset serving route (which in turn will internally use app.url anyway in the route generation)

I'm not sure we need to have the `livewire.asset_url` `null` check, unless I'm missing something? Otherwise, the existing logic should work fine, with the exception of always using the configured `app.asset_url` or `livewire.asset_url`when serving published assets.

Do you think `livewire.asset_url` could be done away with completely and `app.asset_url` be used instead? Any scenarios where these might be different on purpose? Skimming through the past issues below it seems to me that the Livewire-specific `asset_url` was added as a kind of workaround to handle the 2 scenarios mentioned in the docs - but it seems like it can't work for both cases.

* https://github.com/livewire/livewire/issues/1082
* https://github.com/livewire/livewire/issues/338

I actually have failing tests almost ready to test the above assertions, just got stuck on the 2 questions above.

**Comment by marvinosswald** [comment]
@ralphschindler i have issues with bref as well, i just found this error when i started using livewire:
`The /var/task/bootstrap/cache directory must be present and writable. at /var/task/vendor/livewire/livewire/src/LivewireComponentsFinder.php:58`

could this be related to / fixable by your proposed fix for the `bootstrap.php` ?

**Comment by ralphschindler** [comment]
I think the fewer configuration values that can support the max scenarios is always the best path :D

It sounds like you're ahead of me @ragulka 

@marvinosswald see my note above about having to create the deeply nested cache directory inside `/tmp` to ensure this will work in a serverless environment.

all- I have an app running here I am willing to test anyone's PR on:

https://54gvxi7cyh.execute-api.us-east-1.amazonaws.com/production/

if you want the current debug information for my app (with hacks in place and odd configurations):

https://54gvxi7cyh.execute-api.us-east-1.amazonaws.com/production/debug

Source code:

https://github.com/ralphschindler/laravel-livewire-serverless-demo

**Comment by marvinosswald** [comment]
I think the addition to `isOnVapor` would be very useful. 
I now figured why the asset url didn't pose an issue for me, i have cloudfront so they are just on a subpath for me and not a different domain.

But i found another solution to forcing isOnVapor to true for livewire:

### Workaround (given you have the assets within the same domain):

- `php artisan config:cache` - this generates services / packages cache files
- `php artisan livewire:discover` - **this generates the livewire cache file**
- `php artisan config:clear` - this removes the config cache as it has faulty paths in it.

**Comment by ragulka** [comment]
@ralphschindler @marvinosswald I've created a PR to address the asset/app URL. lmk your thoughts and whether my proposed changes would fix some of the issues you're having with serverless environments?

**Comment by calebporzio** [comment]
I agree, the whole "asset_url" config thing is confusing as it's used for more than that.

I think in the next major version we should move to an "app_url" config like you have in the PR.

I've added this to the roadmap for v3 in the future (as we shouldn't mess with the current config in this version)

I'm going to close this for now as I believe users of Bref are the minority and there seem to be workarounds for now.

Re-submit if I'm wrong.

Thanks!

**Comment by michaelaguiar** [comment]
Sorry, what is the workaround for this? Still can't seem to get it working.

**Comment by ralphschindler** [comment]
There is not a great workaround. I think we're waiting for the next version to get a better implementation of the `asset_url` handling and detection (rather configuration would be better) of when the app is deployed in such a way that the `app_url` and `asset_url` are hosted on separate top level places.

**Comment by michaelaguiar** [comment]
Found a good solution. ‘manifest_url’ in livewire config can be changed to “/tmp/storage/livewire-components.php”

Looks like this is the only writable directory we can use. Would need to create the bootstrap/cache directory here if you wanted to keep that structure, or just cut it out.

**Comment by agracia-foticos** [comment]
Is the problem solved?

When I use asset_url automatically all javascript requests use this asset_url variable as root.
