### ISSUE TITLE
Can't validate values from an array attribute in Models

### ISSUE THREAD

**Issue by iksaku** [livewire/livewire#1667]
### Description
If you have a Model, which has an 'array' casted attribute, Livewire is unable to validate its nested values.

### Exact steps to reproduce
Take for example the provided Model and Component below.

You surely can change the Name of your actual Super Hero, and you should be able to bind (`wire:model`) into the values of each Super Hero contact and modify its name and rank values, however, once you start modifying contact values, validation messages will start popping from livewire, telling you:

`Cannot bind property [superHero.contacts.0.name without a validation rule present in the [$rules] array on Livewire component: [super-hero.list].`

But, we do have a validation rule set... Oh, but our validation rule uses an `*` for array, instead of a numerical index as the error output said.

After doing some research, it looks like a [regression was implemented](https://github.com/livewire/livewire/commit/0313887e8c355bac985a87a7580b0bee5533edc5#diff-13d0c883643367d8306b4ff4bdbe48f3L81-R89).

### Stripped-down, copy-pastable code snippets
```php
// Model
class SuperHero extends Model {
    protected $casts = [
        'contacts' => 'array'
    ];
}
```

```php
// Component
class SuperHeroList extends Livewire\Component {
    public SuperHero $superHero;

    protected $rules = [
        'superHero.name' => ['required'],
        'superHero.contacts.*.name' => ['required', 'distinct'],
        'superHero.contact.*.rank' => ['required', 'integer']
    ];

    public function save() {
        $this->validate();
        $this->superHero->save();
    }

    public function render() {
        return view('super-hero.list');
    }
}
```

**Context**
- Livewire version: 2.2.6
- Laravel version: 8.6.0
- Browser: Firefox

**Comment by joowdx** [comment]
Hi. I just wanna ask if this fix was implemented along with the most recent version of livewire coz I'm still facing the same issue😫

```
composer show -i | awk '/laravel\/framework|livewire\/livewire/'
laravel/framework                  v8.7.1    The Laravel Framework.
livewire/livewire                  v2.2.9    A front-end framework for Laravel.
```

**Comment by iksaku** [comment]
It has been fixed on master, no release yet for it. Maybe Caleb is waiting for another feature implementation to tag a 2.3 minor release.

**Comment by joowdx** [comment]
@iksaku so far are you having any problems regarding the validation rules set? It doesn't seem to respect what's set on the rules like date, date_format, numeric, etc.. The validation just passes despite the rules. Or is it just me?

**Comment by iksaku** [comment]
@joowdx This is more of a DateTime object thing. Since Livewire passes the date formats directly, if you're casting to date objects, the DateTime PHP object will interpret the date with the given casted format.

You could intercept the value on an `updatingProperty` hook, and validate there.

**Comment by joowdx** [comment]
Thanks for the response @iksaku. But other validation rules doesn't seem to work either e.g. numeric, max:1, distinct, email etc.

**Comment by iksaku** [comment]
@joowdx I think this is now turning into your end... I'm currently able to validate this code (which is `dev-master` at the moment) with my own models...

Remember that the `numeric` rule only compares against `is_numeric()` function, and for the other rules, they actually work as intended for me.

I don't think this will PR affects any other rules, besides date ones (as I mentioned previous).

Could you open a new Issue stating your Livewire Version and some Code snippets to test against?

**Comment by joowdx** [comment]
Hi @iksaku, I think this issue only occurs when an attribute is casted as object. Tried casting it as array, just like your example, and it turns out okay.

```
composer show | awk '/laravel\/framework|livewire\/livewire/'
laravel/framework                  v8.10.0                           The Laravel Framework.
livewire/livewire                     dev-master 7961b04     A front-end framework for Laravel.
```

This seems to be a another issue unrelated to this.

**Comment by iksaku** [comment]
@joowdx Then this do only affect object casting as I mentioned. Maybe something to consider as well as a documentation note @calebporzio?

**Comment by joowdx** [comment]
I'll try this for the meantime.
> You could intercept the value on an `updatingProperty` hook, and validate there.

Thanks @iksaku.
