### ISSUE TITLE
Undefined index: emits in ->assertEmitted()

### ISSUE THREAD

**Issue by iMusicJJ** [livewire/livewire#1673]
### Description
Assert Emitted throws an undefined Index error

### Exact steps to reproduce
Attempt to test a Livewire component that emits an event

### Stripped-down, copy-pastable code snippets
Livewire::test(Car::class)
            ->set('registration', "XXXXXXXX")
            ->call('render')
            ->assertSet('make', 'Toyota')
            ->assertSet('year', '2010')
            ->assertEmitted('car');

**Context**

- Laravel Framework 7.28.2
- Livewire version: 2.2.6
- Browser: Chrome

**Comment by iMusicJJ** [comment]
<details>
<summary>Console stacktrace</summary>

  at vendor/livewire/livewire/src/Testing/Concerns/MakesAssertions.php:150
    146▕             });
    147▕ 
    148▕             $test = $event && $params[0]($event['event'], $event['params']);
    149▕         } else {
  ➜ 150▕             $test = (bool) collect($this->payload['effects']['emits'])->first(function ($item) use ($value, $params) {
    151▕                 return $item['event'] === $value
    152▕                     && $item['params'] === $params;
    153▕             });
    154▕             $encodedParams = json_encode($params);
</details>

**Comment by iMusicJJ** [comment]
I am also experiencing a bug in ->assertDontSee('String') where it always checks for an empty string instead of what I typed in.

Maybe my Livewire instance is corrupt, or the ISO-8859-1 charset is causing some havoc?

**Comment by vitalii-mv** [comment]
Same issue. Can be fixed by replacing `$this->payload['effects']['emits']` to `$this->payload['effects']['emits'] ?? []`

**Comment by zepfietje** [comment]
I'm getting this exception with `assertNotEmitted()`.

**Comment by zepfietje** [comment]
Also encountering this issue with `assertEmitted()`. Not sure yet under what conditions this bug comes up.
