### ISSUE TITLE
Nested component alpine entangle problem

### ISSUE THREAD

**Issue by marksalmon** [livewire/livewire#1677]
### Description

I have a form inside a modal-type component that is shown and hidden with alpine and livewire entangle. The form is used to edit a relation of a model. The relation may or may not exist.

One of my form inputs is a custom alpine time-input with buttons to set the current time or clear the time. This input is wire:modelled to the component.

The form is wrapped in a blade @if statement so that if the relation does not exist the form does not throw errors for wire:model properties that do not exist.

If I create a relation after the initial page load, the form is correctly displayed, but the input component does not trigger livewire updates.

I have tried every combination of wrapping divs and keys that I can think of.

### Exact steps to reproduce

[Laravel Playground](https://laravelplayground.com/#/snippets/4d9321e5-6bd3-4c92-9d2a-bc3251495b58)

**Context**
- Livewire version: 2.2.5
- Laravel version: 8.5.0
- Browser: Chrome

**Comment by iksaku** [comment]
Looks like when rendering nested components, the `@entangle` directive is not resolved.

I've got it working in my main component view, but when nesting components, the directive is treated as a literal:

![image](https://user-images.githubusercontent.com/4632429/94355691-d6ba1a80-004b-11eb-9972-24de4b7eac35.png)

**Comment by iksaku** [comment]
After some research, I found that `@entangle` is a normal Laravel Directive, I thought it was an Alpine directive.

So, now the question is: **Does this implies that the directive rendering failure is a Laravel issue instead of a Livewire one?**

This directive is defined in `LivewireServiceProvider::registerBladeDirectives()`.

https://github.com/livewire/livewire/blob/master/src/LivewireServiceProvider.php#L231-L238

**Comment by calebporzio** [comment]
Thanks for submitting a Playground @marksalmon.

I pinpointed the issue and fixed it in the following commit: https://github.com/livewire/livewire/commit/e69d9d2bb28eeb55278f191e06963cca4f6cb643

Will be available in the next release. Thanks!
