### ISSUE TITLE
Error with Pagination

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [livewire/livewire#1679]
Context

Livewire version: 2.2.6
Laravel version: 8.0
Browser: Chrome, Firefox

![livewire](https://user-images.githubusercontent.com/1152426/94050017-119e2300-fdac-11ea-9531-15b9236b18ba.png)

![livewire](https://user-images.githubusercontent.com/1152426/94050756-157e7500-fdad-11ea-9fc0-2ea2366d433e.png)

```
<?php
  
namespace App\Http\Livewire\Posts;
  
use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Post;
  
class Posts extends Component
{
    use WithPagination;

    public $searchTerm;
    public $postsx, $title, $body, $post_id;
    public $isOpen = 0;

    public function mount()
    {
        $query = '%'.$this->searchTerm.'%';

		// Perfect 
        //$this->postsx = Post::all(); 

		// With Error
        $this->postsx = Post::where(function($sub_query){
             $sub_query->where('title', 'like', '%'.$this->searchTerm.'%')
             ->orWhere('body', 'like', '%'.$this->searchTerm.'%');
         })->paginate(10);
    }

    public function render()
    {
        return view('livewire.posts.posts', [
            'posts' => $this->postsx
        ]);

    }

```

**Comment by breadthe** [comment]
Can you try this:
- remove `public $postsx`
- move the `$this->postsx = ...` statement inside the `render()` function and make it a local variable `$postsx`

So `render()` becomes:

```
public function render()
    {
        $postsx = Post::where(function($sub_query){
             $sub_query->where('title', 'like', '%'.$this->searchTerm.'%')
             ->orWhere('body', 'like', '%'.$this->searchTerm.'%');
         })->paginate(10);

        return view('livewire.posts.posts', [
            'posts' => $postsx
        ]);
    }
```

**Comment by redbastie** [comment]
What @breadthe said. You can't use collections in your component properties.

**Comment by calebporzio** [comment]
Yeah, Livewire (and actually Laravel itself), doesn't currently support serializing paginated lists of models. You should instead pass the paginated object to the view like @breadthe said.

Thanks for pitching in everyone!

If you're REALLY interested, you could PR/submit issue to Laravel itself to support this scenerio.
