### ISSUE TITLE
component.initialized and element.initialized hooks don't run

### ISSUE THREAD

**Issue by gjm** [livewire/livewire#1680]
### Description

If I define a `component.initialized` or `element.initialized` hooks, they aren't run.

### Exact steps to reproduce

Add this Javascript code:

```javascript
document.addEventListener('livewire:load', () => {
    Livewire.hook('component.initialized', (component) => {
        console.log('component initialized');
    });
    Livewire.hook('element.initialized', (el, component) => {
        console.log('element initialized');
    });
});
```

When the Livewire components run, no output is shown on the console.

**Context**
- Livewire version: 2.2.5
- Laravel version: 7.28.3
- Browser: Chrome, Firefox

**Comment by calebporzio** [comment]
Sorry about this, this is an issue with the documentation. Fixed now.

Because `'livewire:load` only fires AFTER Livewire has been initialized, these hooks will never get run. You need to use `DOMContentLoaded` instead:

```js
        document.addEventListener('DOMContentLoaded', () => {
            Livewire.hook('component.initialized', (component) => {
                console.log('component initialized');
            });
            Livewire.hook('element.initialized', (el, component) => {
                console.log('element initialized');
            });
        });
```

Thanks!

**Comment by darmen** [comment]
Hey @calebporzio sorry for bumping this up,

But it seems I'm missing something out here.

Using the same example:

```javascript
<script>
         document.addEventListener("DOMContentLoaded", () => {
            Livewire.hook('component.initialized', (component) => {
                console.log('component initialized');
            });
        });
</script>
```

It just doesn't work. I'm injecting this directly into the blade template of my component and I can see the code in the page source.

**Comment by rlidev** [comment]
It will only work if the script is inside the livewire html component, if it's somewhere else it doesn't seem to work.

**Comment by digitall-it** [comment]
Ok it would be enough, once you subscribe to those events from inside the livewire html component, you can call more functions. I have to try.
