### ISSUE TITLE
$wire.entangle updating the wrong Alpine property

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1684]
### Description
I am making a `tags` input field with auto-complete. When the user types a word in the `search` input, a query is executed and returns a list with `options` from the database.

- When the `options` are updated in php **_Livewire entangles the wrong Alpine property_**.
- This is a nested (child) Livewire component, don't know if it matters.

#### Compare: `search`,  `options` and `tags` in the screen shots

The user types **jens** into the `search` input
![image](https://user-images.githubusercontent.com/21239634/94133665-3e604200-fe61-11ea-8fd7-fce10ecf7125.png)

I can see in chrome dev tools that the correct property is returned from Livewire, ...
![image](https://user-images.githubusercontent.com/21239634/94133516-0953ef80-fe61-11ea-9bc9-97e27bae1ea4.png)

...but entangled to the wrong Alpine property. 
- `search` is suddenly empty
- `tags` has become `search`
- `options` is empty

![image](https://user-images.githubusercontent.com/21239634/94134013-bcbce400-fe61-11ea-8500-48749e9bb9fc.png)

### Code
All properties are entangled.
```blade
<div x-data="{
    search: $wire.entangle('search'),
    tags: $wire.entangle('tags'),
    options: $wire.entangle('options') }">
    <div>
        <template x-for="(tag, index) in tags" :key="index">
            <span>
                <span x-text="tag"></span>
                <button x-on:click.prevent="$wire.removeTag(index)" type="button">
                    &times;
                </button>
            </span>
        </template>
        <input x-model="search" x-on:keydown.space.prevent="if(search !=' ') $wire.addFromSearch(search)" />
    </div>
    <div>
        <template x-for="(option, index) in options" :key="index">
            <button wire:click.prevent="addFromOptions(option)" type="button">
                <span x-text="option"></span>
            </button>
        </template>
    </div>
</div>
```

**Context**
- Livewire version: v2.2.6
- Laravel version: 7
- Alpine v2.7.0

**Comment by tanthammar** [comment]
I also tried:
```blade
<div x-data="{
    search: @entangle('search'),
    tags: @entangle('tags'),
    options: @entangle('options') }"
```

**Comment by calebporzio** [comment]
This issue doesn't have sufficiently reproducible code:

Please re-submit with exactly copy-pastable code for both the component's class and view.

Also, include screenshots of the AJAX payload or console logs rather than the DevTools as we don't maintain the DevTools and can't verify it works correctly and isn't reporting missinformation.

Thanks!
