### ISSUE TITLE
Missing dusk test for wire:loading.delay

### ISSUE THREAD

**Issue by nuernbergerA** [livewire/livewire#1698]
I assume not many people know that `wire:loading.delay` even exists because its [undocumented](livewire/docs#252) and not covered by tests.

There is already a good amount of tests in [tests/Browser/Loading/view.blade.php](https://github.com/livewire/livewire/blob/238723003436a56d3a727fc255aa53a4a2c21f86/tests/Browser/Loading/view.blade.php), so it should be easy to extend it.

**Expected tests:**
1. Loading takes less than `200ms` and assume it didn't show up
2. Loading takes longer than `200ms` and assume it did show up

**Comment by manelgavalda** [comment]
Hi @nuernbergerA 👋,
I just created a PR for this by adding the 2 expected tests.
Let me know what you think, and I'll probably create another PR to add this directive to docs 😀.
