### ISSUE TITLE
Maybe issue when loading component from package using full page component

### ISSUE THREAD

**Issue by thewebartisan7** [livewire/livewire#1700]
### Description

I am having issue when use a livewire component inside package. 
Everything works fine when using [inline rendering](https://laravel-livewire.com/docs/2.x/rendering-components#inline-components).
The issue happen when trying to load using [full page rendering](https://laravel-livewire.com/docs/2.x/rendering-components#page-components).

First time the page load, the component is successfully loaded, but when make ajax request it point to wrong url and appear error modal. The ajax url point to `http://livewire.test/livewire/message/package.namespace.http.livewire.auth.register`  and error in modal show  `The "/Users/me/Projects/livewire/app/Http/Livewire" directory does not exist`.  

I set up simple component as per doc. Below are my route in package:

Route::get('/register', Package\Namespace\Http\Livewire\Auth\Register::class)->name('auth.register');

And this is component class:

<img width="568" alt="Screenshot 2020-09-26 at 11 35 23" src="https://user-images.githubusercontent.com/57477934/94339988-92545d80-fffe-11ea-983c-eed030da6bb6.png">

### Exact steps to reproduce

1) Create a package 
2) Create a component inside package and register in service provider as explained in [doc](https://laravel-livewire.com/docs/2.x/package-dev)
3) Set route to load component as full page

### Stripped-down, copy-pastable code snippets

As you can see below, the payload in `LifecycleManager::fromSubsequentRequest($payload)` set name of component to `package.namespace.http.livewire.auth.register` and not as alias like when using inline loading.

```php
array:3 [▼
  "fingerprint" => array:3 [▼
    "id" => "OkrZcS9nz64vAipHyneg"
    "name" => "package.namespace.http.livewire.auth.register"
    "locale" => "en"
  ]
  "serverMemo" => array:6 [▼
    "children" => []
    "errors" => []
    "htmlHash" => "115563aa"
    "data" => array:3 [▶]
    "dataMeta" => []
    "checksum" => "2410abe332e96c66fefe91f0a5dc66793b51031a6128a41e8f3a3ad3015c9419"
  ]
  "updates" => array:1 [▼
    0 => array:2 [▶]
  ]
]
```

While inline use correct alias name:

```php
array:3 [▼
  "fingerprint" => array:3 [▼
    "id" => "x47lZidkanW3udNF5HHj"
    "name" => "register"
    "locale" => "en"
  ]
  "serverMemo" => array:6 [▼
    "children" => []
    "errors" => []
    "htmlHash" => "88ba5c63"
    "data" => array:3 [▶]
    "dataMeta" => []
    "checksum" => "6b6dce775f2326d06c1384aad9a6ef1a31a559faaaccc501ef91d38272e7265f"
  ]
  "updates" => array:1 [▼
    0 => array:2 [▶]
  ]
]
```

**Context**

- Livewire version: [2.2.3]
- Laravel version: [8.3.1]
- Browser: [any]

I just start play with Livewire so maybe I am missing something.

**Comment by booni3** [comment]
I have got a similar issue. I moved many of my livewire components into custom directories and registered them through a custom service provider, adding to the boot method i.e. `Livewire::component('register', Team\Components\Register::class);`

Since Livewire 2 upgrade, these components were found on the initial get request but then any requests from this point (i.e. submitting a form) resulted in a `500 error, component not found`.

For now, I have moved all my components back to the `App/Http/Livewire` namespace and it all works. I might have missed something on the L7 -> L8 upgrade, which was made along with Livewire 1 -> 2...

**Comment by thewebartisan7** [comment]
Thanks for your confirmation, almost now I know that is not something wrong on my end only.

I think that it must be an issue on client side by because the `fingerprint` sent to the server already has wrong alias of component, composed by component FQN, example:

```
fingerprint | {…}
-- | --
id | PlmTIKWrJfCKhWESYyDA
locale | en
name | package.namespace.http.livewire.register
```

Since that alias doesn't exist, the LivewireComponentsFinder try to auto-discovery it from FQN of component.

**Comment by calebporzio** [comment]
Good catch,

This should be fixed in the next release. Here's the commit: https://github.com/livewire/livewire/commit/96db3539f5d0aaaba7cb4e7f14ced21f9819007e

Thanks!
