### ISSUE TITLE
Model variable resets or doesn't carry the state after every request

### ISSUE THREAD

**Issue by vincenzoraco** [livewire/livewire#1702]
### Description
A Model variable resets at every request / attempt to add attributes to it.

### Exact steps to reproduce
I have a User model stored in a public variable `$user`. I set the initial value from the mount method.

On a different function, that is called using $listeners, I would add some properties, such as a relationship, a database value, etc. No matter what I add (or even do nothing to it), the variable clears the previous state and re-initialise again. This is an issue only with variables that are used for Models.

### Stripped-down, copy-pastable code snippets

```php
<?php

class Create extends Component
{
    public User $user;

    public $userArray = [];

    protected $listeners = [
        'step1:completed' => 'setStep1Data',
        'step2:completed' => 'setStep2Data',
        'step3:completed' => 'setStep3Data',
        'step4:completed' => 'setStep4Data',
    ];

    public function aNormalFunctionCalledDirectlyFromTheComponentPage()
    {
        // Whatever you do here, the variable $this->user re-initialise itself with an empty object.
    }

    public function setStep1Data( $contact )
    {
        // This works, it sets the contact relation...
        $this->user->setRelation('contact', new Contact($contact));
        
        // The state of userArray is not getting reset. It works fine, as intended.
        // For a moment, the user variable state is working fine
        $this->userArray = array_merge($this->user->toArray(), $this->userArray);
        
        // BUT once the function terminates, it will have ONLY the contact relation set, 
        // the name property set by the mount() method is gone.
    }

    public function setStep2Data( $email )
    {
        // This works, it sets the email property
        $this->user->email = $email;
    
        // The state of userArray is not getting reset. It works fine, as intended.
        // For a moment, the user variable state is working fine
        $this->userArray = array_merge($this->user->toArray(), $this->userArray);
    
        // BUT once the function terminates, it will have ONLY the email property set, 
        // the contact relation set by the setStep1Data() method is gone.
    }

    public function setStep3Data( $data )
    {
        // ...
    }

    public function setStep4Data( $data )
    {
        // ...
    }

    public function mount()
    {
        $this->user = new User();
        $this->user->name = 'John Doe';

        $this->userArray = array_merge($this->user->toArray(), $this->userArray);
    }

    public function render()
    {
        return view('livewire.users.create');
    }
}
```

**Context**
- Livewire version: [2.2.7]
- Laravel version: [8.6.0]
- Browser: [Chrome, Safari]

**Comment by vincenzoraco** [comment]
Is it a default behaviour? Reading the docs - https://laravel-livewire.com/docs/2.x/properties#important-notes - it should be working fine as long as it's set as a public property.

**Comment by iksaku** [comment]
Looks like you're missing your `protected $rules` attribute, defining the `$user` validation properties. It is [specified in Livewire's Documentation](https://laravel-livewire.com/docs/2.x/properties#binding-models) that you need to provide a `$rules` property for your component, otherwise, errors may arise.

In your example, you want to keep the name and email of the user, so your `$rules` property should be specified like:
```php
protected $rules = [
    'user.name' => ['required'],
    'user.email' => ['required', 'email']
];
```

Could you try this and comment if it works?

**Comment by vincenzoraco** [comment]
Hi! Thank you so much for trying to help me!

So, you're solution helped - however, the reason why I wasn't using it, it's because my data is not directly bind to an input, but it's manually saved based on some factors.

Although it's working, it has a limitation, it doesn't store the relationships, the index (ex. contacts) is present, but the data is an empty array.

I believe that this behaviour is normal. It's the way backend code works, there is no state (unless you store it in the session), but Caleb is cleverly saving it using the JS request?

I believe though that there is a bug of not storing the data properly in the (JS) state if the Collection is in a nested array (or another Collection).

**Comment by iksaku** [comment]
Alright, so, how are you syncing your data to the backend?

Could you provide a snipped of the HTML/JS you're using?

**Comment by iksaku** [comment]
BTW: Please also state your Livewire and Laravel versions, as well as the browser you're using ;)

**Comment by vincenzoraco** [comment]
> Alright, so, how are you syncing your data to the backend?
> 
> Could you provide a snipped of the HTML/JS you're using?

I have a creation process in place. I'm using User as an example to keep it simple. The creation is divided in different steps, and each step is on a different livewire component.

```php
@if($current_step === 0)
    <livewire:users.creation-steps.step1/>
@endif

@if($current_step === 1)
    <livewire:users.creation-steps.step2/>
@endif
```

To complete the step, the user will call a function which emits an event.

```php
public function completeStep()
{
    $this->emit('step1:completed', $this->someData);
}
```

... and on the main component, there are listeners that grab the data and store it in the User object.

```php
protected $listeners = [
    'step1:completed' => 'setStep1Data',
    'step2:completed' => 'setStep2Data',
    'step3:completed' => 'setStep3Data',
    'step4:completed' => 'setStep4Data',
];
```

Everything works as expected, the `public $this->currentStep` value is kept on the state, and the sub-components emit the data correctly. The issue is when I try to store the User model in state, it just resets after each request (whether is from a listener or a direct call to a method).

**Comment by vincenzoraco** [comment]
> BTW: Please also state your Livewire and Laravel versions, as well as the browser you're using ;)

Sorry, I've wrote them I just forgot to remove the `e.g.` before the version numbers.

**Comment by vincenzoraco** [comment]
As a temporary solution (I might leave it for good though), I'm saving the user model on the session driver - and it works perfectly.

```php
protected $queryString = [ 'identifier' ];

public function mount()
{
    if ( !$this->identifier ) {
        $this->identifier = $this->generate_numeric_code();
    }
    
    $this->user = new User();
    
    session()->put("user:{$this->identifier}", $this->user);
}

public function setStep1Data( $contact )
{
    $this->user = session()->get("user:{$this->identifier}");

    $this->user->setRelation('contact', new Contact($contact));

    $this->setStepData(0, $contact);

    session()->put("user:{$this->identifier}", $this->user);
}
```

**Comment by iksaku** [comment]
Its strange that your model is being reset each time you call an action. It should "sync" the input data (even if you're just calling from JS).

By any change, are you using `@this` directive in your creation processes?

I see now that you're loading different Livewire components whenever the user changes from step to step. That may be the issue, since each Livewire component has its own data, and that data is not reactive between siblings not children components.

**Comment by vincenzoraco** [comment]
> Its strange that your model is being reset each time you call an action. It should "sync" the input data (even if you're just calling from JS).
> 
> By any change, are you using `@this` directive in your different process steps?
> 
> I see now that you're loading different Livewire components whenever the user changes from step to step. That may be the issue, since each Livewire component has its own data, and that data is not reactive between siblings not children components.

It is indeed strange. My main livewire component blade view looks like this (don't mind the identifier, it's my hack to get the ticket instance between components).

```blade
@if($current_step === 0)
    <livewire:users.creation-steps.step1 :identifier="$identifier"/>
@endif

@if($current_step === 1)
    <livewire:users.creation-steps.step2 :identifier="$identifier"/>
@endif

@if($current_step === 2)
    <livewire:users.creation-steps.step3 :identifier="$identifier"/>
@endif
```

I've created a playground and you can clearly see that it does reset the user model (object) at each request.

https://laravelplayground.com/#/snippets/30f7f2d5-aced-4419-9261-1a97ab07697d

At this point I think it's a bug.

**Comment by vincenzoraco** [comment]
```php
<?php

use Livewire\Component;
use App\User;

class LivewireComponent extends Component
{
    public $name = 'Laravel Playground';

    public $email = '';

    public User $user;

    protected $rules = [
        'name',
        'email',
    ];

    public function setName()
    {
        // at this point, $this->user is an empty Model obejct.
        $this->user->name = $this->name;
    }

    public function setEmail()
    {
        // at this point, $this->user is an empty Model obejct.
        $this->user->email = $this->email;
    }

    public function mount()
    {
        $this->user = new User();
    }

    public function render()
    {
        return view('livewire-component');
    }
}
```

**Comment by vincenzoraco** [comment]
Also look at the behaviour of the `$user->users` collection when a different request has been made

https://laravelplayground.com/#/snippets/4fca7562-7f62-48d7-9fb0-37cfe4fdbc29

# Steps
- Click "Add New User" button
- Type something in the name field

The `$user->users` collection is converted to an array and each item inside is also converted into an array.

**Comment by vincenzoraco** [comment]
Most likely the last test for today:

I've done another test and it seems that livewire loose the object state before each request,

https://laravelplayground.com/#/snippets/44dca2c7-1bbb-4314-802d-269bdd648acc

Clicking "Add New User" will push a new User object into the array, but if you click it again, it coverts the previous entries in arrays, and only the last entry is an object.

**Comment by iksaku** [comment]
Well, about collections, Livewire does translate everything into JSON, so that Javascript can parse it and properly work with.

It looks like you're using multiple Livewire Component inside a root Livewire Component for the example code you gave before the Playgrounds. Just remember that [Parameters on nested components don't act reactively](https://laravel-livewire.com/docs/2.x/nesting-components), if you opted to use separate components to not have a long HTML, then it'll be better for you to use [Laravel Blade Components](https://laravel.com/docs/8.x/blade#components) (they're intended for that type of use).

If you would also like to keep your component as small as possible, then you can opt to use [PHP's Traits](https://www.php.net/manual/en/language.oop5.traits.php) and separate each step into a Trait, and just `use` it in your Livewire component. (But keep in mind that function and property names may collide, so make sure to name them accordingly on each trait).

Now, about property manipulation. If you're working with a User model, then you don't need to have a separate action for "setting its attributes", Livewire can directly bind to them and validate accordingly. [Here's a Playground using Livewire's model-binding](https://laravelplayground.com/#/snippets/a7be78a0-b2c5-4202-b20e-1289d6e8ffd2).

**Comment by iksaku** [comment]
> Most likely the last test for today:
> 
> I've done another test and it seems that livewire loose the object state before each request,
> 
> https://laravelplayground.com/#/snippets/44dca2c7-1bbb-4314-802d-269bdd648acc
> 
> Clicking "Add New User" will push a new User object into the array, but if you click it again, it coverts the previous entries in arrays, and only the last entry is an object.

Now I got what you're trying to achieve. Arrays don't save information on model data. If you're planning to keep information for multiple models, then your only option at the moment is to save that information as a normal array, and later on process it as a model for DB persistence.

[Checkout this example playground](https://laravelplayground.com/#/snippets/e4afb182-6457-42d2-bc35-d37c96038ff0).

**Comment by vincenzoraco** [comment]
> Now, about property manipulation. If you're working with a User model, then you don't need to have a separate action for "setting its attributes", Livewire can directly bind to them and validate accordingly. [Here's a Playground using Livewire's model-binding](https://laravelplayground.com/#/snippets/a7be78a0-b2c5-4202-b20e-1289d6e8ffd2).

I am aware of this, the reason why I've wrote a specific function to change the property value is to show how Livewire resets the `$user` model before each request. I believe this is an unintended behaviour, but I might be wrong and this is the way it is.

> If you would also like to keep your component as small as possible, then you can opt to use PHP's Traits and separate each step into a Trait, and just use it in your Livewire component. (But keep in mind that function and property names may collide, so make sure to name them accordingly on each trait).

Thanks for the advise, I might struggle a bit as I love working with Objects rather than arrays, especially when there is a relationship involved.

My scope was to build the Model object step by step (don't look at the examples, it's more complex than that), such as adding properties and relationships of any type (hasOne, hasMany, etc). and at the end, create it in one go.

Thank's so much for your help though, you've been amazing trying to help me. Hopefully this thread is going to be helpful for others too.

**Comment by jhgeluk** [comment]
Hi, I'm also experiencing this bug(?). Is there an upcoming fix for this? 

From reading this issue I understand that you need to store the "model state" as an array, since a model won't work.

This is however quite the workaround when you want to create multistep forms for example.

**Comment by iksaku** [comment]
> Hi, I'm also experiencing this bug(?). Is there an upcoming fix for this?

As you may have read, there’s no bug in this case, it’s more of a implementation detail.
Multi-step forms are not part of Livewire’s implementation (as they’re not part of Laravel’s either).

> From reading this issue I understand that you need to store the "model state" as an array, since a model won't work.

That’s not actually the case, in the contrary, my suggestion is to bind the model data into an actual model class.

But now, if you really need to achieve the “multi-step” part, then you need to “make an illusion of it being multi-part”. You could achieve this using JS (and/or Alpine).

Another option would be to checkout [Laravel Arcanist](https://laravel-arcanist.com/), but I’m afraid I don’t know if it’s compatible with Livewire or not (but if it works for pure Laravel, it should be compatible somehow with Livewire as well).

**Comment by Forsakenrox** [comment]
This talk about multispet form, and i agree with this behaviour, but in my case i meet with regular situation. Just example:

```
public $images = [];

function mount()
{
    $this->images = Image::all();
}

function setNameForFirstImage()
{
     $this->images->first()->name 'Ola qe pasa';
    //if i dump $this->images at this step - everything being fine, the name was changed, but not saved (e.g ->save() method)
}
function dumpImages()
{
    dd($this->images) //first image is a grand new, without changed name.
}
```

I'm confused, if this is the usual behavior of live wire, then it definitely should not to be so
