### ISSUE TITLE
Undefined variable slot in app.blade.php

### ISSUE THREAD

**Issue by MUHAMMADSiyab** [livewire/livewire#1707]
I am using `livewire 2.2` with `laravel 7.24` in my laravel project. When i load component using 
`Route::get('/path', ComponentClassPath);`
it works, but when i load my livewire component inside a blade view. For instance, **test.blade.php** like this
```
@extends('layouts.app')

@section('content')
    @livewire("my-livewire-component")
@endsection
```
it doesn't work and shows the below error:

**Undefined variable: slot (View: E:\xampp\htdocs\lw\resources\views\layouts\app.blade.php)** .

Any solution ?

- Livewire version: 2.2
- Laravel version: 7.24

**Comment by iksaku** [comment]
As [stated in Livewire's Documentation], when rendering a component, you need to provide the base template, be it using a `$slot

**Comment by mblarsen** [comment]
If you want to use a template that uses @yield (sections) you can use the 'extended' method in your component instead:

```php
public function render()
{
    return view(...)
        ->extends('layouts.app') // the default is layout('layouts.app')
        ->section('content');
}
```

https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout

**Comment by MUHAMMADSiyab** [comment]
> If you want to use a template that uses @yield (sections) you can use the 'extended' method in your component instead:
> 
> ```
> public function render()
> {
>     return view(...)
>         ->extends('layouts.app') // the default is layout('layouts.app')
>         ->section('content');
> }
> ```
> 
> https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout

I got it solved by using `extends` method. Thanks @mblarsen

**Comment by RomainMazB** [comment]
For those who care, [I've submitted a PR](https://github.com/livewire/livewire/pull/1807) which describe the problem and could have solved it but had not been merged :/

**Comment by keongbalap757** [comment]
thank you for the information I came to know about [slot online](http://128.199.202.211/)

**Comment by keongbalap757** [comment]
hank you for the information I came to know about[ slot online](https://www.lisinopril0.com/)

**Comment by beactriclaura** [comment]
<a href="https://bit.ly/slotpulsaonlineterbaik"<game-online-play</a>

thank you for the information

**Comment by beactriclaura** [comment]
<a href="https://bit.ly/slotpulsaonlineterbaik
good

**Comment by beactriclaura** [comment]
<a href="https://bit.ly/slotpulsaonlineterbaik
good

**Comment by bolarolet88muh** [comment]
<a href="https://twitter.com/liemenawu">MISI</a>
<a href="https://www.facebook.com/profile.php?id=61551636658292">MISI</a>
<a href="https://www.linkedin.com/in/liemena-wu-897622292/">MISI</a>
<a href="https://medium.com/@join188rtp">MISI</a>
<a href="https://heylink.me/join188login/">MISI</a>
<a href="https://join188alternatif.company.site/">MISI</a>
<a href="https://www.behance.net/join188link">MISI</a>
<a href="https://teletype.in/@join188loginalternatif">MISI</a>
<a href="https://flickr.com/people/join188apk/">MISI</a>
<a href="https://join188.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436024">MISI</a>
<a href="https://sebangsa.com/join188login">MISI</a>
<a href="http://join188alternatif.wikidot.com/">MISI</a>
<a href="https://www.linkedin.com/posts/liemena-wu-897622292_httpsjoin188site-join188-adalah-daftar-activity-7110318437423308800-zfXl?utm_source=share&utm_medium=member_desktop">MISI</a>
<a href="https://medium.com/@join188rtp/about">MISI</a>
<a href="https://medium.com/@join188rtp/tips-bermain-slot-gacor-hari-ini-di-join188-rtp-608078eee23b">MISI</a>
<a href="https://teletype.in/@join188loginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865920">MISI</a>
<a href="https://twitter.com/Ruslili723011">MISI</a>
<a href="https://www.facebook.com/profile.php?id=61551346100091">MISI</a>
<a href="https://medium.com/@zeus99rtp">MISI</a>
<a href="https://heylink.me/zeus99login/">MISI</a>
<a href="https://zeus99alternatif.company.site/">MISI</a>
<a href="https://www.behance.net/zeus99link">MISI</a>
<a href="https://teletype.in/@zeus99loginalternatif">MISI</a>
<a href="https://www.flickr.com/people/zeus99apk/">MISI</a>
<a href="https://zeus99.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436025">MISI</a>
<a href="https://sebangsa.com/zeus99login">MISI</a>
<a href="http://zeus99alternatif.wikidot.com/">MISI</a>
<a href="https://medium.com/@zeus99rtp/about">MISI</a>
<a href="https://medium.com/@zeus99rtp/tips-bermain-slot-gacor-hari-ini-di-zeus99-rtp-86d4cef2e9e3">MISI</a>
<a href="https://teletype.in/@zeus99loginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865922">MISI</a>
<a href="https://twitter.com/taniwanhen2446">MISI</a>
<a href="https://www.facebook.com/profile.php?id=61551653037405">MISI</a>
<a href="https://medium.com/@qqzeusrtp">MISI</a>
<a href="https://heylink.me/qqzeuslogin/">MISI</a>
<a href="https://store92589513.company.site/">MISI</a>
<a href="https://www.behance.net/qqzeuslinkalternatif">MISI</a>
<a href="https://teletype.in/@qqzeusloginalternatif">MISI</a>
<a href="https://www.flickr.com/people/qqzeusapk/">MISI</a>
<a href="https://qqzeustan.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436026">MISI</a>
<a href="https://sebangsa.com/qqzeusrtp">MISI</a>
<a href="http://qqzeuslogin.wikidot.com/">MISI</a>
<a href="https://medium.com/@qqzeusrtp/about">MISI</a>
<a href="https://qqzeusrtp.medium.com/tips-bermain-slot-gacor-hari-ini-di-qqzeus-rtp-8b64b28adba8">MISI</a>
<a href="https://teletype.in/@qqzeusloginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865921">MISI</a>
<a href="https://twitter.com/susantiliu10959">MISI</a>
<a href="https://www.facebook.com/profile.php?id=61551724553912">MISI</a>
<a href="https://medium.com/@slotsultanlogin">MISI</a>
<a href="https://heylink.me/slotsultanalternatif/">MISI</a>
<a href="https://slotsultanlinkalternatif.company.site/">MISI</a>
<a href="https://www.behance.net/rtpslotsultan">MISI</a>
<a href="https://teletype.in/@slotsultanloginalternatif">MISI</a>
<a href="https://www.flickr.com/people/slotsultan/">MISI</a>
<a href="https://slotsultanlogin.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436027">MISI</a>
<a href="https://sebangsa.com/slotsultanlinkalternatif">MISI</a>
<a href="http://rtpslotsultan.wikidot.com/">MISI</a>
<a href="https://medium.com/@slotsultanlogin/about">MISI</a>
<a href="https://slotsultanlogin.medium.com/tips-bermain-slot-gacor-hari-ini-di-slotsultan-login-34ce4af0cf2f">MISI</a>
<a href="https://teletype.in/@slotsultanloginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865919">MISI</a>
<a href="https://twitter.com/verawat10466323">MISI</a>
<a href="https://www.facebook.com/ruslan.setiawan.90410">MISI</a>
<a href="https://fafafalogin.medium.com/">MISI</a>
<a href="https://heylink.me/fafafaalternatif/">MISI</a>
<a href="https://fafafalinkalternatif.company.site/">MISI</a>
<a href="https://www.behance.net/rtpfafafa">MISI</a>
<a href="https://teletype.in/@fafafaloginalternatif">MISI</a>
<a href="https://www.flickr.com/people/fafasu/">MISI</a>
<a href="https://fafalogin.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436028">MISI</a>
<a href="https://sebangsa.com/fafalinkalternatif">MISI</a>
<a href="http://rtpfafa.wikidot.com/">MISI</a>
<a href="https://fafafalogin.medium.com/about">MISI</a>
<a href="https://fafafalogin.medium.com/tips-bermain-slot-gacor-hari-ini-di-fafafa-login-14df8d048159">MISI</a>
<a href="https://teletype.in/@fafafaloginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865923">MISI</a>
<a href="https://twitter.com/SintaJojo36841">MISI</a>
<a href="https://www.facebook.com/ackykamaru">MISI</a>
<a href="https://medium.com/@olimpus88login">MISI</a>
<a href="https://heylink.me/olimpus88alternatif/">MISI</a>
<a href="https://olimpus88linkalternatif.company.site/">MISI</a>
<a href="https://www.behance.net/rtpolimpus88">MISI</a>
<a href="https://teletype.in/@olimpus88loginalternatif">MISI</a>
<a href="https://www.flickr.com/people/olimpus88/">MISI</a>
<a href="https://olimpus88login.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436029">MISI</a>
<a href="https://sebangsa.com/olimpus88linkalternatif">MISI</a>
<a href="http://rtpolimpus88.wikidot.com/">MISI</a>
<a href="https://medium.com/@olimpus88login/about">MISI</a>
<a href="https://olimpus88login.medium.com/tips-bermain-slot-gacor-hari-ini-di-olimpus88-login-2e2e20ff77db">MISI</a>
<a href="https://teletype.in/@olimpus88loginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865925">MISI</a>
<a href="https://twitter.com/imutbudi9916431">MISI</a>
<a href="https://www.facebook.com/dwi.adrianto.37">MISI</a>
<a href="https://medium.com/@slotuuslogin">MISI</a>
<a href="https://heylink.me/slotuusalternatif/">MISI</a>
<a href="https://slotuuslinkalternatif.company.site/">MISI</a>
<a href="https://www.behance.net/rtpslotuus">MISI</a>
<a href="https://teletype.in/@slotuusloginalternatif">MISI</a>
<a href="https://www.flickr.com/people/slotuus/">MISI</a>
<a href="https://slotuuslogin.contently.com/">MISI</a>
<a href="https://www.hackathon.io/users/436030">MISI</a>
<a href="https://sebangsa.com/slotuuslinkalternatif">MISI</a>
<a href="http://rtpslotuus.wikidot.com/">MISI</a>
<a href="https://medium.com/@slotuuslogin/about">MISI</a>
<a href="https://slotuuslogin.medium.com/tips-bermain-slot-gacor-hari-ini-di-slotuus-login-4d6d1b1357a2">MISI</a>
<a href="https://teletype.in/@slotuusloginalternatif/FiturGacorSlotOnlinePragmaticPlayTerpopuler">MISI</a>
<a href="https://sebangsa.com/detail/1865926">MISI</a>

**Comment by vatsal-zwt** [comment]
This Error is occurred because in your normal page livewire slot variable is not found so here is the solution you may try with your code.

```
@if (!empty($slot))
  {{ $slot }}
@else
  @yield('content')
@endif
```
In my case i wanted to load content if slot is not found.
