### ISSUE TITLE
File upload preview image 404 when nginx cache configured

### ISSUE THREAD

**Issue by michaellatham** [livewire/livewire#1713]
I have the same application deployed on the same server, the only difference is that on the production, I have the browser cache control settings listed below in the nginx configuration. The server is ubuntu on forge.

When I have these cache settings, I get a 404 on the file preview, example link below. The file in question is a jpeg.

`https://{DOMAIN}/livewire/preview-file/tUG8lcYD8VdVCrZMgA8QumcZ3e45LC-metadG9waWMuanBn-.jpeg?expires=1601321025&signature=abe49b269e72fce3f7d816eda6bd348f2d0abcb22b40b1afc96ce6b73c5788bb`

```
    # browser cache control
    location ~* \.(ico|css|js|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot)$ {
        expires 30d;
        access_log off;
        add_header Pragma public;
        add_header Cache-Control "public, max-age=86400";
    }
```

Is there something wrong with my cache settings, or is this an issue? If I remove all the cache settings, the issue is gone. Do I need to exclude the Livewire preview file from the cache settings somehow? All other static files are cached correctly.

**Context**
- Livewire version:2.2.7
- Laravel version: 8.6.0
- Browser: Chrome
- Developer Version: Tired 2.0

**Comment by calebporzio** [comment]
Lol, "Tired 2.0"

Livewire file preview URLs pretend to be actual assets, but they are actually normal Laravel routes that spoof a file response.

I'm guessing this is somehow causing the issue, or maybe for some reason nginx is stripping the signature and making it invalid resulting in a 404.

I'm going to close this because it's not necessarily an issue with Livewire itself.

If you (or anyone else) do more investigating and discover there's something Livewire can do with it's preview URL generation or handling to prevent this, please re-submit and we can look into a fix.

Thank you

**Comment by v1ncen** [comment]
I have this exact same issue with almost the same nginx config ;-( Previews are not found (404).
When I deactivate the nginx location directive, it works

`https://my-app.com/livewire/preview-file/cdlnUohN2vH3lL6g779m2cfUAJe5aV-metaYW5nb3QtYWxkcmljXzV4NS5qcGc=-.jpeg?expires=1601922124&signature=745a946f3b763b61af807d77610a532baf93cff8b4b8e1be8e56e758a77a197a`

My nginx config:
```
location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff)$ { 
        expires 10d;
        add_header Pragma public;
        add_header Cache-Control "public";
        try_files $uri =404;
}
```

### Context
- Livewire v2.2.2
- nginx/1.10.3 (Ubuntu)
- Laravel 7.22.4
- Safari, Chrome, Firefox

**Comment by v1ncen** [comment]
I think I found what is happening.

Livewire use Laravel [signed routes](https://laravel.com/docs/7.x/urls#signed-urls) for preview urls and it cannot work with an nginx location directive that targets all images. Livewire previews images requests needs to be passed to Laravel.

Here's a workaround.

Livewire preview urls looks like this:
`https://my-app.com/livewire/preview-file/{temp-file-name}.png?expires={some-hash}`

So we can target every request uri that contains /livewire (or /preview-file) and pass them to Laravel. 
And then cache all other static files as you were doing before.

```shell
# Pass request to Laravel for any file in a livwire dir.

location ^~ /livewire {
    try_files $uri $uri/ /index.php?$query_string;
}


# Cache static files as usual

location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff)$ {
    expires 10d;
    access_log off;
    add_header Cache-Control "public";
}
```

**Comment by aerni** [comment]
@v1ncen Thank you so much for this solution! Was tripping over this today.

**Comment by blackcortex** [comment]
@v1ncen
i use apache
plz write this code for apache server

**Comment by helturkey** [comment]
for those who use octane

```
location ^~ /livewire {
    try_files $uri $uri/ @octane;
}
```

**Comment by fabiorcamargo** [comment]
For anyone looking for a way for Livewire to work on NGINX, I spent a lot of time looking for a solution and there was an example in Laravel's own documentation.
https://laravel.com/docs/10.x/deployment#nginx

Adapt the model to your server and be happy!!!

**Comment by edulazaro** [comment]
For those who are looking into this issue, if you are using Apache to handle standard HTTP requests but use nginx as a proxy for static files, which will be the case if you use VestaCP other variants of this panel, then you'll need to ad this into your nginx config or template:

```
 location /livewire/preview-file/ {
        proxy_pass https://%ip%:%web_ssl_port%$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
        add_header Cache-Control 'no-cache, no-store, must-revalidate';

        # Pass the full request URI to Apache
        proxy_redirect off;
        proxy_pass_request_headers on;
    }

```

There's no need for the `try_files` directive; hope it helps!
