### ISSUE TITLE
File uploads to arrays cause numbers and other input types to be lost

### ISSUE THREAD

**Issue by stancl** [livewire/livewire#1714]
### Description

Parts of the data are lost when a file is uploaded "into" an array.

Text inputs don't lose values. Numbers do, checkboxes do.

### Exact steps to reproduce

1. Visit page
2. Upload a file
3. Change one of the text inputs
4. See number disappear

Interestingly:

1. Visit page
2. **Change the first number input's value**
3. Upload a file
4. Change one of the text inputs
5. See **unchanged number** disappear

The one that was changed remains.

### Stripped-down, copy-pastable code snippets

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithFileUploads;

class ImageUpload extends Component
{
    use WithFileUploads;

    public $values = [];

    public function mount()
    {
        $this->fill([
            'values' => [
                'foo' => 'Hello',
                'bar' => 'world',

                'number1' => 1,
                'number2' => 2,
                'file' => null,
            ]
        ]);
    }

    public function render()
    {
        return view('livewire.image-upload');
    }
}
```

```html
<div>
    <input type="text" wire:model="values.foo">
    <input type="text" wire:model="values.bar">

    <input type="number" wire:model="values.number1">
    <input type="number" wire:model="values.number2">

    <input type="file" wire:model="values.file">

    <hr>

    <pre>
    Foo: {{ $values['foo'] }}
    Bar: {{ $values['bar'] }}

    Number1: {{ $values['number1'] }}
    Number2: {{ $values['number2'] }}
    File: {{ $values['file'] }}
    </pre>
</div>

```

**Context**
- Livewire version: 2.2.7
- Laravel version: 8.6.0
- Browser: Chrome

**Comment by stancl** [comment]
I'm stupid, this happens even after removing the typehint. Will investigate more.

**Comment by calebporzio** [comment]
I don't think Livewire currently supports storing file uploads inside nested properties.

If you are able, would you mind PRing a note to the Livewire docs.

If more issues like this come up, maybe we'll consider supporting deep nesting.

Thanks

**Comment by stancl** [comment]
I see, thanks for the reply!

**Comment by ChristianAdrian** [comment]
Currently facing the same issues

**Comment by stancl** [comment]
As Caleb said, this is not really an issue because it's not meant to be supported.

That said, if @calebporzio could provide me with any pointers on how to implement this, I'd be more than glad to submit a PR.

**Comment by astr0naugh7** [comment]
> As Caleb said, this is not really an issue because it's not meant to be supported.
> 
> That said, if @calebporzio could provide me with any pointers on how to implement this, I'd be more than glad to submit a PR.

I'm having this same issue myself. I have a few text inputs and 2 checkboxes in my wizard and then a file upload with Livewire. It resets my checkboxes. Please support this!

**Comment by stancl** [comment]
I'd be willing to pay $100 + gift a 1 year lean-admin.dev license to anyone who can implement this.

**Comment by astr0naugh7** [comment]
> I'd be willing to pay $100 + gift a 1 year lean-admin.dev license to anyone who can implement this.

I'll contribute $10 of that $100

**Comment by iantasker** [comment]
@calebporzio This is a bug as file uploads in a nested array are supported as they are covered by file upload tests.
 
I have submitted the PR #2078 (with tests) which resolves the issue.
