### ISSUE TITLE
databinding

### ISSUE THREAD

**Issue by parisaprhg** [livewire/livewire#1717]
I want to be able to type something in that input box and have it be printed on the outside
 <input wire:model="name" type="text" style="border: 2px red solid "> But this is not 

![Screenshot (163)](https://user-images.githubusercontent.com/66860919/94520594-6218e480-01e1-11eb-8d1b-d2e39b9aa98e.png)

**Comment by ryangjchandler** [comment]
@parisaprhg Firstly, you need to have a single root element. If that `<input>` is bound to a `$name` property on the component class, you can just do:

```blade
<div>
    <input wire:model="name">
    {{ $name }}
</div>
```

**Comment by danharrin** [comment]
Hi, please continue this thread on the [Discussions feature](https://github.com/livewire/livewire/discussions) or [Discord server](https://discord.gg/livewire). Many thanks!
