### ISSUE TITLE
Event fires only once

### ISSUE THREAD

**Issue by Webakula** [livewire/livewire#1720]
### Description
Javascript event fires only once
### Stripped-down, copy-pastable code snippets

In JS file:

```
Livewire.on('changeUrl', url=>{
    console.log(url); //this fires always on **changeUrl**
    history.pushState(null, null, `${url.url}`); //this too...
    Livewire.emit('test', {data:url});//this fires only once
});
```

In component:
```
class CatalogCategoryItems extends Component
{

    protected $listeners = [ 'test'=>'test'];


    public function test($data) {
        \Log::debug($data);
    }
}
```
Maybe I'm doing something wrong?

**Context**
- Livewire version: 2.2.7
- Laravel version: 8.6.0
- Browser: Chrome  85.0.4183.121

**Comment by calebporzio** [comment]
The code provided isn't enough to reproduce the issue.

My guess is that there is something deeper going on with your setup.

If you can narrow the issue down further by testing more bits in isolation, please re-submit. Thanks!
