### ISSUE TITLE
Livewire.emitTo return undefined

### ISSUE THREAD

**Issue by michele-grifa** [livewire/livewire#1725]
### Description
Calling Livewire.emitTo results in an undefined return value and the event is not called on the destination component

### Exact steps to reproduce
Call Livewire.emitTo

### Stripped-down, copy-pastable code snippets
```
Livewire.emitTo('E4Zf6sGLAKTWQ3sdA1Dj','eventName');
```

**Context**
- Livewire version: 2.2.6
- Laravel version: 8.6.0
- Browser: Firefox

**Comment by calebporzio** [comment]
emitTo's first parameter should be the component name, not the component ID: 
![image](https://user-images.githubusercontent.com/3670578/94696171-bd8fc300-0304-11eb-9f61-a65e73dbd022.png)
