### ISSUE TITLE
Cannot read property 'fingerprint' of null

### ISSUE THREAD

**Issue by jasontxf** [livewire/livewire#1726]
@amaelftah  I think I've figured it out. 

I noticed when the result is returning properly, this happened

<img width="1001" alt="Screenshot 2020-09-25 at 2 03 36 AM" src="https://user-images.githubusercontent.com/1124731/94182574-ca12b680-fed3-11ea-9722-8f1003b79230.png">

and when the error appear, this is what I see
<img width="1005" alt="Screenshot 2020-09-25 at 2 03 46 AM" src="https://user-images.githubusercontent.com/1124731/94182655-e3b3fe00-fed3-11ea-97eb-918e21fbe8a2.png">

So I'm guessing the nested component for some reason is being generated twice.
It might be because it has the same id for key.

So I tried this hacky method to always generate a different key 

```html
@php
    $randomKey = time().$watchedFile->id;
@endphp
<livewire:files-table-actions :watched-file="$watchedFile" :key="$randomKey"/>
```

and I'm no longer facing the issue.

I'm not sure why is the previous nested component not clearing itself. 

Perhaps @calebporzio could point us to what are we doing wrongly :)

_Originally posted by @jasontxf in https://github.com/livewire/livewire/issues/1686#issuecomment-698503788_

Hello @calebporzio I'm sorry to reopen this, but the original issue wasn't resolved.
Is the intended behavior to always generate a different key (by appending time()) when using nested component?

Thank you for your time!

**Comment by calebporzio** [comment]
Please post this issue as if it were brand new, with a thorough explanation of the issue, boiled down copy/pastable code and what not.

There's not enough context in this issue to make it easy for contributers to help.

I'll leave this open for a bit because it was posted so recently, but otherwise will close soon. Thanks!

**Comment by jasontxf** [comment]
Hello @calebporzio! 

The main issue is that when a nested component is included in a component, when used together with wire:model that dynamically reload data from the component, I will receive **index.js:31 Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null** after a few searches.

Here are some snippets of my code

**Files.php**
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class Files extends Component
{
	use WithPagination;

        public $orderName = null;

	public function render()
	{
		if ($this->orderName !== null && $this->orderName !== '') {
			$files->where('shopify_order_name', 'LIKE', '%' . $this->orderName . '%');
		}
		
		$files = $files->paginate(5);
		
		return view('livewire.files', ['files' => $files,])->extends('layouts.app');
	}
}
```

**files.blade.php**
```html

<input wire:model="orderName" type="text" />

<table>
  <thead><tr>...</tr></thead>
    <body>
      @foreach($files as $watchedFile)
          <tr>
            <td>
                <livewire:files-table-actions :watched-file="$watchedFile" :key="$watchedFile->id"/>
	    </td>
	</tr>
      @endforeach
      </tbody>
</table>
```

Now when I use wire:model to search for the first time, it will work. 
When I tried to search again with another keyword, this error will appear.

It's definitely hard to explain the underlying issue so I've made a short video.
https://www.dropbox.com/s/4fdnt1cuqi08ttt/livewire-bug.mov?dl=0

In my video, I noticed that when the issue occur, I will see this in the UI
<img width="1213" alt="Screenshot 2020-10-01 at 2 21 27 PM" src="https://user-images.githubusercontent.com/1124731/94774992-83e8b600-03f1-11eb-8235-8c1996c20995.png">

instead of this
<img width="1275" alt="Screenshot 2020-10-01 at 2 30 39 PM" src="https://user-images.githubusercontent.com/1124731/94775615-c1017800-03f2-11eb-960a-85ec1f14501e.png">

*Notice the trash icon appeared twice* (That is the nested component)

The <files-table-actions> component was generated twice. This leads me to believe perhaps the previously generated component wasn't cleared for some reason and thus there's no fingerprint on the DOM since it has already been parsed.

I've made another video to prove my point.
https://www.dropbox.com/s/mn844z5kxbzusx8/livewire-proof.mov?dl=0

Knowing I was right, the workaround for this issue for me is to always generate a different key for nested component like this:
```html
<livewire:files-table-actions :watched-file="$watchedFile" :key="time().$watchedFile->id"/>
```
*append **time()** to my :key*

I hope I've managed to explain the issue clearly to you. Please let me know if it's still unclear.

Thank you!

**Comment by zgabievi** [comment]
I've the same issue. I'm using multiple `<template x-if="XX">` and this XX is dynamic. It can be changed on user actions. There are livewire components inside `template` elements. I have unique key for each of them, but as @jasontxf said, it doesn't help at all. I had to add `time()` in each key.

![image](https://user-images.githubusercontent.com/1515299/94852052-5ffd9280-043a-11eb-9197-2e1e117a7b43.png)

**Comment by goddas** [comment]
I think I have the same issue and it is pretty consistent. 
The only solution for me is to have the time() hack AND include the vuejs plugin. Note that I do not have any vue components on the page, but vue is registered globally from the default laravel 7 install (I've migrated to Laravel 8 manually), adjusted per livewire vue plugin specifications.

I have a simple (scout w/algolia) search, which filters the instructors. Simply triggering a search so that some instructors would appear/disappear would trigger this error.

The search component blade
```
...
 @foreach($instructors as $instructor)
         ...
        <livewire:favourite :instructor="$instructor" :key="time().$instructor->id"/>
         ...
 @endforeach
...
```

The search component:
```
class InstructorSearch extends Component
{
    public $searchQuery;
    public $instructors;

    public function render()
    {
        return view('livewire.instructor-search');
    }

    public function mount()
    {
        $this->instructors = Instructor::all()->loadMissing('user');
    }

    public function search()
    {
        $this->instructors = Instructor::search($this->searchQuery)->get()->loadMissing('user');
        $this->searchQuery = '';
    }
}
```

The nested component blade:
```
<button class="favourite-star" wire:click="toggleFavourite">
    <span class="iconify-inline {{ auth()->user()->isFavouriteInstructor($instructor) ? 'd-block' : 'd-none'}}" data-icon="custom:star"></span>
    <span class="iconify-inline {{ auth()->user()->isFavouriteInstructor($instructor) ? 'd-none' : 'd-block'}}" data-icon="custom:star-outline"></span>
</button>
```

**Comment by detygon** [comment]
Hello ! I had the same issue but the cause was different. I included a blade component in my Livewire view to show validation errors. When I submitted the form with invalid fields, the component showed up and then caused this error. After hours of debugging I found out that it was because the blade component had multiple root elements. After wrapping them in a `div` the error disappeared. Hope it helps.

Before: 

```html
@props(['field' => null, 'title' => 'Whoops! Une erreur est survenue.'])

@if ($field && $errors->has($field))
    <x-alert title="{{ $title }}" type="danger" {{ $attributes }}>
        <ul class="mt-3 list-disc list-inside text-sm leading-tight">
            @foreach ($errors->get($field) as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </x-alert>
@endif

@if(! $field && $errors->any())
    <x-alert title="{{ $title }}" type="danger" {{ $attributes }}>
        <ul class="mt-3 list-disc list-inside text-sm leading-tight">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </x-alert>
@endif
```

After:

```html
@props(['field' => null, 'title' => 'Whoops! Une erreur est survenue.'])

<div>
@if ($field && $errors->has($field))
    <x-alert title="{{ $title }}" type="danger" {{ $attributes }}>
        <ul class="mt-3 list-disc list-inside text-sm leading-tight">
            @foreach ($errors->get($field) as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </x-alert>
@endif

@if(! $field && $errors->any())
    <x-alert title="{{ $title }}" type="danger" {{ $attributes }}>
        <ul class="mt-3 list-disc list-inside text-sm leading-tight">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </x-alert>
@endif
</div>
```

**Comment by evanbarter** [comment]
[Here's a repo](https://github.com/evanbarter/livewire-1726-repro) to reproduce the issue for me. 

It is abstracted from an app I am working so it might not be the most minimal reproduction, but the list.blade.php (blade component) file has a couple of failing examples and one that works. If you punch in a number 1-6 then clear the input it will trigger the issue, in the current state of the repo.

I've been fairly judicious with wire:key properties after reading the docs on nesting and troubleshooting in an attempt to rule that out.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by evanbarter** [comment]
REOPEN

**Comment by calebporzio** [comment]
This problem arrises because of the lack of a `wire:key` within the @foreach loop: `@foreach <div wire:key="???"`

Morphdom is tripping up because of the lack of it

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ajthinking** [comment]
Im getting this error when sending an **event** from child to parent container. I am using `wire:key` as described but get the error `Cannot read property 'fingerprint' of null`.

### Container
```
class Container extends Component
{
    public $listeners = [
        'submit'
    ];

    public function render()
    {
        return view('livewire.container');
    }

    public function submit()
    {
        //dd("The child says wow - it works!");
    }
}
```
with view
```
<div>
    <h1>Im the container</h1>
    @foreach([1,2,3] as $nbr)
        @livewire('child', compact('nbr'))
    @endforeach
</div>
```

### Child
```
class Child extends Component
{
    public $nbr;

    public function mount($nbr)
    {
        $this->nbr = $nbr;
    }

    public function render()
    {
        return view('livewire.child');
    }

    public function submit()
    {
        $this->emit('submit', 'wow!');
    }
}
```
with view
```
<div wire:key="{{ $nbr }}">
    Hey im a child
    <button wire:click="submit">submit</button>
</div>
```

**Comment by ajthinking** [comment]
REOPEN

**Comment by ajthinking** [comment]
CLOSE

**Comment by delta1186** [comment]
@calebporzio I am curious to know if @jasontxf is using VueJS in their project.  The reason I ask is I chased an issue I was having for the past few days without luck until today.  I created a new repo and could not reproduce the issue.  I had already implemented :key="rand()" for my looped nested child components which did get rid of the fingerprint issue, but I was still seeing a strange issue where only the first nested child component would emit an event to self and some UI thing would show on that component (think of a saved message) using Alpine to listen for the event from self.  The strange behavior is that the message would work on subsequent Livewire requests for that 2nd and on nested components.  I am also using <livewire:  /> format for my components.  Below is a screenshot showing this behavior.  When user changes date the the icon shows a checkmark and then goes back to a calendar.  

![image](https://user-images.githubusercontent.com/421307/98874950-d67daf00-2440-11eb-904b-b9b218f4d1eb.png)

Couple of environment details:
Livewire 2.3.1
Laravel 8x
Alpine 2.7.3
VueJS 2.6x

Looking at my two projects I realized that my production app was using VueJS.   I remembered seeing something about it in the docs.  I then install the https://github.com/livewire/vue plugin from npm and added the imports as shown on the referenced url and now problems are gone.

I will mention that in my sample app each of the nested child components would get the wire:initial-data attribute after the event was sent back, but in my production app only the first child gets this attributes.  Don't know if that's a big deal or not, but just wanted to point it out.  Each of my nested child components now work as expected!

**Comment by jasontxf** [comment]
Hello,

I am not using Vue JS (for the first time ever!) :) 

> This problem arrises because of the lack of a `wire:key` within the @foreach loop: `@foreach <div wire:key="???"`
> 
> Morphdom is tripping up because of the lack of it

I don't really understand what @calebporzio is saying considering in my examples I do have a wire:key in the foreach.

```html
      @foreach($files as $watchedFile)
          <tr>
            <td>
                <livewire:files-table-actions :watched-file="$watchedFile" :key="$watchedFile->id"/>
	    </td>
	</tr>
      @endforeach
```

But in any case, my workaround using rand works well for me. So it's no big deal :) 

Do open a new ticket if anyone still have issues so that Caleb don't have to keep closing this issue haha.

Thanks!!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by christianjburger** [comment]
> Looking at my two projects I realized that my production app was using VueJS. I remembered seeing something about it in the docs. I then install the https://github.com/livewire/vue plugin from npm and added the imports as shown on the referenced url and now problems are gone.
> 
> I will mention that in my sample app each of the nested child components would get the wire:initial-data attribute after the event was sent back, but in my production app only the first child gets this attributes. Don't know if that's a big deal or not, but just wanted to point it out. Each of my nested child components now work as expected!

Thanks @delta1186 for this comment. +1 that installing the Livewire Vue Plugin solved this issue for me.

**Comment by iambateman** [comment]
For what it's worth, I had this issue because I tried to do `wire:key="$transaction->id"` instead of `wire:key="{{ $loop->index }}"`

**Comment by Icrmsoftware** [comment]
Install Livewire vue cdn

`@livewireScripts
<script src="https://cdn.jsdelivr.net/gh/livewire/vue@v0.3.x/dist/livewire-vue.js"></script>`

Also in my scenario i was facing this issue because there was one livewire component with the wire:click event i was using wire:key so remove key from wire:click event

**Comment by Mitcal** [comment]
Thank you @iambateman

**Comment by espradley** [comment]
Old post, but ran into this issue.  

I had an event page with fields that you could edit by clicking a pencil, which opened a modal with a child form field element.   First time triggering modal, updating, clicking save worked.   Subsequent requests failed with 
Cannot read properties of null (reading 'fingerprint')

A quick work around was in my foreach loop, I just added time() to it.  

Changed: 
key('field'.$field->id)

to 
key('field'.$field->id.time())

Seems refreshing parent will still confuse the key...?   Anyway, worked for me and hope it helps someone

**Comment by hfmiguel** [comment]
> Im getting this error when sending an **event** from child to parent container. I am using `wire:key` as described but get the error `Cannot read property 'fingerprint' of null`.
> 
> ### Container
> ```
> class Container extends Component
> {
>     public $listeners = [
>         'submit'
>     ];
> 
>     public function render()
>     {
>         return view('livewire.container');
>     }
> 
>     public function submit()
>     {
>         //dd("The child says wow - it works!");
>     }
> }
> ```
> 
> with view
> 
> ```
> <div>
>     <h1>Im the container</h1>
>     @foreach([1,2,3] as $nbr)
>         @livewire('child', compact('nbr'))
>     @endforeach
> </div>
> ```
> 
> ### Child
> ```
> class Child extends Component
> {
>     public $nbr;
> 
>     public function mount($nbr)
>     {
>         $this->nbr = $nbr;
>     }
> 
>     public function render()
>     {
>         return view('livewire.child');
>     }
> 
>     public function submit()
>     {
>         $this->emit('submit', 'wow!');
>     }
> }
> ```
> 
> with view
> 
> ```
> <div wire:key="{{ $nbr }}">
>     Hey im a child
>     <button wire:click="submit">submit</button>
> </div>
> ```
> 
> ## Fixed
> By passing key in directive. Using syntax `@livewire('component', [], key($str))`. Note `key()` here is not php key() but magic syntax provided by livewire 🚀

You save my bacon . Thanks

**Comment by gbrits** [comment]
Fixed everything for me:

```
@livewire('your-component', [], key(uniqid()))
```
