### ISSUE TITLE
File Uploads Not Working Behind a Proxy

### ISSUE THREAD

**Issue by coolsam726** [livewire/livewire#1731]
I have tried everything to make file uploads work for my app which is in a docker container and is proxied on the host using Apache Proxy. All I get is a 401 error response which seems to be related to CSRF or verification. That is why I though it could be related to #1216. 

When I try file uploads without docker containerization or Proxying, it seems to work right.

Any help on this will be much appreciated.

**Comment by austenc** [comment]
@coolsam726 I agree, this is a duplicate of #1216. 

Looks like there's a bug or two to be fixed! :)
