### ISSUE TITLE
Issue when Redirect between Pages can't search or paginate 

### ISSUE THREAD

**Issue by baselrabia** [livewire/livewire#1732]
### Description
when I am trying to switch pages in my app I found that pagination or my search box don't respond seem disabled 
and also when I switch to add form I found that real-time validation not working too and if I want to make it work I should refresh the page, and I don't wanna that I wanna still in the page and don't have to refresh it every time I change or switch between pages, so I hope I did something wrong and it's not a bug .. so can u explain to me why this happens ...

### Exact steps to reproduce

1. open "/projects" -- it the index data-table with search and pagination (everything is working)
2. Add new record by add form component still everything is working validation is working 
3. after submitting the form it redirects to the index page, errors happen can't search or use paginate 
4. if returned to add new record without making a refresh also validation is not working 
5. if I just move and switch between pages search and pagination in other pages not working too 

##when everything is working 

![12](https://user-images.githubusercontent.com/27627958/94804925-e048d700-03eb-11eb-94e7-73f9d59c472d.PNG)

##when I redirect to another page or submit the form 

![33](https://user-images.githubusercontent.com/27627958/94804929-e343c780-03eb-11eb-8e2e-7a563f9cf7e6.PNG)

### Stripped-down, copy-pastable code snippets

**Routes**
`
Route::get('projects', Projects::class)->name('projects');
Route::get('add-project', ProjectsAdd::class)->name('add-projects');

`
**my add form** 

`<?php

namespace App\Http\Livewire;

use App\Models\ActivityType;
use App\Models\City;
use App\Models\Devolper;
use App\Models\Project;
use Livewire\Component;

class ProjectsAdd extends Component
{
    public $name_ar;
    public $name_en;
    public $description_ar;
    public $description_en;
    public $devolper_id;
    public $city_id;
    public $activity_type_id;
    public $finished;
    public $delivery;
    public $link;
    public $price;
    public $status;
    public $successMessage;

    protected $rules = [
        'name_ar' => 'required',
        'name_en' => 'required',
        'status' => 'required',
        'description_ar' => 'required',
        'description_en' => 'required',
        'devolper_id' => 'required',
        'city_id' => 'required',
        'activity_type_id' => 'required',

        'price' => 'required',
        'finished' => 'required',
        'delivery' => 'required',
        'link' => '',
    ];

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function submit()
    {
        $validatedDate = $this->validate();
        sleep(1);

        Project::create($validatedDate);

        $this->successMessage = 'successfully ';

        $this->dispatchBrowserEvent(
            'alert',
            ['type' => 'success', 'title' => 'Create Project' , 'message' => 'Project successfully Saved','footer' => '']
        );

        // $this->emit('alert', ['type' => 'success', 'message' => 'Project successfully Created.']);

        $this->resetForm();
        return redirect()->to('/admin/projects?active=true&priority=true&sortAsc=true');
    }

    private function resetForm()
    {
        $this->name_ar = '';
        $this->name_en = '';
    }

    public function render()
    {
        return view('livewire.projects-add', [
            'developers' => Devolper::all(),
            'activity_types' => ActivityType::all(),
            'cities' => City::all(),
        ])->extends('admin.layouts.app')
            ->section('content');
    }
}
`
**my index component** 

`<?php

namespace App\Http\Livewire;

use App\Models\Project;
use Livewire\Component;
use Livewire\WithPagination;

class Projects extends Component
{
    use WithPagination;
    public $active = true;
    public $priority = false;
    public $search;
    public $sortField;
    public $sortAsc = true;
    protected $queryString = ['search', 'active', 'priority', 'sortAsc', 'sortField'];

    public function mount(): void
    {
        $this->search = request()->query('search', $this->search);
    }

    public function paginationView()
    {
        return 'custom-pagination-links-view';
    }
    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = !$this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        return view('livewire.projects', [
            'projects' => Project::where(function ($query) {
                $query->where('name_ar', 'like', '%' . $this->search . '%')
                    ->orWhere('name_en', 'like', '%' . $this->search . '%');
                })
                ->where('status', $this->active)
                ->where('priority', $this->priority)
                ->when($this->sortField, function ($query) {
                    $query->orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc');
                })
                ->paginate(5),
            'rowsName'  => [
                'NAME ARABIC'=> 'name_ar',
                'NAME ENGLISH'=>'name_en',
                'PRICE' => 'price',
                'FINISHED'=>'finished',
                'DELIVERY' => 'delivery',
                'VIEWS'=>'VIEWS'],
            ]
            )
            ->extends('admin.layouts.app')
            ->section('content');

    }
}
`

**Context**
- Livewire version: [2.2.5]
- Laravel version: [7.28.3]
- Browser: [ Chrome ]

**Comment by wasitmirani** [comment]
You have found any solution of this issue if you find any solution of this bug please kindly share me. 
thank you dear

**Comment by austenc** [comment]
@baselrabia could you make an example repo to help reproduce this?
