### ISSUE TITLE
realtime validate with updatedEmail()

### ISSUE THREAD

**Issue by SurfJunky** [livewire/livewire#1733]
### Description
When is updatedEmail() method to check if the email already exists or not it uses the default database connection instead of the DB connection of the used model.

### Exact steps to reproduce

1- Create 2 different databases.
2- Set the first database as default connection.
3- Create a table user or whatever you want in the database 2.
4- Create the user model and set the database connection to database 2.
5- Create a registration form and try to validate the email with updatedEmail().

here it should throw an error like this
SQLSTATE[42S02]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'Login'. (SQL: select count(*) as aggregate from [Login] where [email] = 21312) 

### Stripped-down, copy-pastable code snippets

`    public function updatedEmail()
    {
        $this->validate(['email' => 'unique:Login']);
    }`

```
env connection strings.
DB_CONNECTION=sqlsrv
DB_HOST=xxxxxxxx
DB_PORT=
DB_DATABASE=database1
AUTH_DATABASE=database2
DB_USERNAME=xxxxxx
DB_PASSWORD=xxxxx
```

I've solved this problem by setting the default connection to database2.

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Browser: [e.g. Chrome, Safari]

**Comment by ninthspace** [comment]
Are you specifying the connection in the User model via the `$connection` property or `getConnectionName()` method?

Laravel 8 should honour the latter in such validations.

Alternatively you can specify the connection name inside the validation, as per the Laravel docs., e.g.

`'email' => 'unique:connection.users,email_address'`

**Comment by SurfJunky** [comment]
its already specified in the model
like this 
`protected $connection = 'auth_database';`

**Comment by SurfJunky** [comment]
> 'email' => 'unique:connection.users,email_address'

this works aswell :+1:
