### ISSUE TITLE
Making Full SPA easier.

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#1734]
Hi
About getting CSRF : https://github.com/livewire/livewire/blob/b8a1e77ed68012df6ce755a1568ffcac2b837e7a/js/util/getCsrfToken.js#L2

I think if you get CSRF with https://laravel.com/docs/8.x/sanctum#spa-authenticating then we can have full SPA.
What do you think about it?
@calebporzio

**Comment by calebporzio** [comment]
No plans at the moment for this. Thank you though.
