### ISSUE TITLE
Exception: CannotAddEloquentModelsAsPublicPropertyException

### ISSUE THREAD

**Issue by brocorp-dev** [livewire/livewire#174]
Hi @calebporzio, 

Since 0.2.5 release (and same issue with 0.2.6), I'm not able to retrieve data from a Model and I'm stuck with this Exception message:
`Livewire \ Exceptions \ CannotAddEloquentModelsAsPublicPropertyException`

### Code

**app / Http / Controllers / CustomerController.php**
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CustomerController extends Controller
{
    public function index()
    {
        return view('modules.customers.index');
    }
}
```

**app / Http / Livewire / CustomerIndexList.php**
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Customer;

class CustomerIndexList extends Component
{
	public $customers;

	public function mount() 
	{
		$customers = Customer::all();
		$this->customers = $customers;
	}

    public function render()
    {
        return view('livewire.customer-index-list');
    }
}
```

**resources / views / livewire / customer-index-list.blade.php**
```
<ul class="mt-12">
	@foreach($customers as $customer)
		<li>{{ $customer->uuid }} - {{ $customer->name }}</li>
	@endforeach
</ul>
```

**resources / views / modules / customers / index.blade.php**
```
@extends('layouts.app')

@section('content')
	@livewire('customer-index-list')
@endsection
```

I don't have this issue with 0.2.4.

**Comment by 2kodes** [comment]
@brocorp-dev 

from this conversation https://github.com/calebporzio/livewire/issues/27#issuecomment-521732931    
and [the release information for v0.2.5](https://github.com/calebporzio/livewire/releases)   livewire currently does not support eloquent models in the blade view and only allows arrays. @calebporzio  said its temporary until a permanent solution is found to the issues people seem to be having with using eloquent models with livewire in blade views

**Comment by calebporzio** [comment]
Hi @brocorp-dev, the best thing for you to do right now is:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Customer;

class CustomerIndexList extends Component
{
    public function render()
    {
        return view('livewire.customer-index-list', ['customers' => Customer::all()]);
    }
}
```

**Comment by brocorp-dev** [comment]
Hi @calebporzio and @2kodes, 

Has seen in [https://github.com/calebporzio/livewire/issues/27#issuecomment-521040661](this comment), that the option we used now for our dev test! 

Thanks for your replies guys! ;)

**Comment by faustbrian** [comment]
@lancepioch @calebporzio should no longer be relevant after https://github.com/livewire/livewire/commit/133d0910601cd1d6940809378eb58c55dc80758a?

**Comment by lancepioch** [comment]
Thanks guys, eloquent models (and collections) are now available as public properties. See https://laravel-livewire.com/docs/properties/#important-notes
