### ISSUE TITLE
When calling an action to modify public properties of a livewire component, input and change events aren't fired/captured on the modified inputs

### ISSUE THREAD

**Issue by isaackearl** [livewire/livewire#1743]
### Description

There are times I want to detect a change on an input with alpine using x-on:change or x-on:input or something like that.  However there are situations where these are ignored entirely.  If you call an "action" on a livewire component that changes the value of a public property that is bound to an input, then it will change the value without firing the event.  This is a problem because there are many interactions on various inputs that happen on the javascript side based on values changing etc.

Also I understand that modifying a public property on the component side will avoid firing the "updated" lifecycle hooks on the component side... but changes to inputs should still trigger input and change events on the javascript side, so I feel like this is definitely a bug.

### Exact steps to reproduce

Here is a very simple laravel playground setup to show the issue.  Instructions included (very simple)
https://laravelplayground.com/#/snippets/c5522bc8-06d5-48c3-8e9d-0e6beef5d3f4

### Stripped-down, copy-pastable code snippets

see laravel playground link

**Context**
- Livewire version: v2.2.9
- Laravel version: v8.8.0
- Browser: Chrome (any)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
