### ISSUE TITLE
Undefined variable $attributes with default layout

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1748]
### Description
In my `layouts.app` I have `$attributes` on the `body` tag, to be able to pass `Alpine.js` or `class` attributes when using the layout.
If I use the Livewire shorthand for my `route` I get the error:
```
Undefined variable $attributes
```
And I have to do this to fix it:
```php
public function render()
{
    return view('livewire.component-page')->layout('layouts.app', [ 'attributes' => '' ]);
}
```

### Exact steps to reproduce
1. Put `{{ $attributes }}` in your `layouts.app`
2. Use shorthand routing with Livewire

**Context**
- Livewire version: latest
- Laravel version: latest
- Browser: Chrome

**Comment by RomainMazB** [comment]
@mokhosh 
Maybe I'm facing the same problem, and I'm currently trying to fix it.

Are you using an AppLayout class and blade "x-tag" to render your "basic" views?

Like so:
```html
<x-app-layout>
    
</x-app-layout>
```

**Comment by mokhosh** [comment]
Yes I am

**Comment by RomainMazB** [comment]
So the problem is described and solved in the PR I've made https://github.com/livewire/livewire/pull/1807

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
