### ISSUE TITLE
Store View Templates

### ISSUE THREAD

**Issue by intellow** [livewire/livewire#175]
Would you accept a PR that does the following:

`php artisan make:livewire counter --view=my_template`

And instead of scaffolding the standard view, it would look for an use a template of a view that stored in views/livewire/templates/my_template.blade.php as the template for the new component view.

This would allow people to store any customization they like for their component views.

**Comment by calebporzio** [comment]
Ah, very interesting.

I love the concept. Will want to brainstorm on the specifics.

Something I've always wanted in Laravel is the ability to customize the stubs that `make:` commands use.

I would love the same for Livewire. I'm not sure of the best way to accomplish this though.

Here are some options that come to mind:

A) Provide some sort of configuration option (weather in a service provider or config file) for overriding the class and view stubs.
B) Provide some sort of config for different template options
```
return ['templates' => [
    ['admin' => ['class' => 'App\Livewire\Templates\AdminStub', 'view' => 'livewire.templates.admin-stub']
];
```
Then this would be used like: `artisan make:livewire --template=admin` or something
C) Do what you are proposing and provide `--view` and `--class` options to use files as a template. The questions I have about that approach are: 1) what about class templates? they will need to have the right class name and namespace 2) I'm not sure about the `livewire/templates/foo` naming convention (probably the best option, just not sure if relying on a convention here is best) 3) People like me have a hard time remembering command options and especially don't want to type all that extra text in the command (maybe there's a way to make it more memorable / intuitive)

Those are my thoughts, let's get the conversation going.

**Comment by intellow** [comment]
I like option B a lot, but I know you were trying to avoid publishing a config file, which is why I proposed the options in the command.

I like having a first step where you run a command like `livewire:publish-stubs` to publish your current stubs for both class and view in `App\Livewire\Templates\StandardStub` and `livewire.templates.standard-stub`. If you haven't run this, `livewire:make` scaffolds from the livewire core. If you have run this, then `livewire:make` scaffolds out every new component based on these files instead of the files in the livewire core, and the user can customize the standard stubs. This allows some customization without needing a config file.

Step two is the config file where the user can add new templates and pass the template name through in the `make:livewire NewComponent --template=admin` command, just like you described.

**Comment by edgrosvenor** [comment]
@calebporzio At work I have our test stubs set up as blade templates (I was drinking when I came up with the idea but hear me out). It allows me to pull in a package to our projects, publish the assets, and tweak how I want the default tests to be created. This idea, expanded out a bit, would allow a user to publish assets and then edit the stubs for both the PHP and the blade of the component because they'd just be blade templates published as views.

**Comment by davidpiesse** [comment]
A nice easy first step would be configuring the defaults...
A command like ```php artisan livewire:publish ``` would be ideal for this.
LW would need a check in the builder command to looks for the presence of these in a specific location (/resources/vendor/livewire/stubs/view.blade.php & component.php ).

This then sets up the next step of custom templates via command line args. 
I think the hardest thing is naming & knowing where these templates should be put :)

**Comment by calebporzio** [comment]
## Stub Make Command
`artisan livewire:stub foo`
- this would make two files:
* `app/Http/Livewire/Stubs/Foo.stub`
* `resources/views/livewire/stubs/foo.stub`

You can reference the stub like so:
`artisan make:livewire some-component --stub=foo`

You can override the default stub by making `Default.stub` and `default.stub` files in their respective directories.

Packages can contribute stubs (and you can publish them? if you want to modifiy them?), and local stubs will override them. (may run into namespacing problems, but maybe cross that bridge when we come to it.)

These should be 3 seperate PRs I think. Not sayin they all need to happen, just that they can/should be broken out.

**Comment by calebporzio** [comment]
To make a default stub: `artisan livewire:stub default`

**Comment by lancepioch** [comment]
@intellow Does this new command work similar to how you were expecting?

**Comment by intellow** [comment]
> @intellow Does this new command work similar to how you were expecting?

Yeah, everything works great. It's all documented here: https://laravel-livewire.com/docs/making-components/
