### ISSUE TITLE
Can't emit event on select change

### ISSUE THREAD

**Issue by RomkaLTU** [livewire/livewire#1752]
### Description
Can't emit event on `<select>` change. The problem exist when property set to bool value. for example `public $showTable = false;`

### Stripped-down, copy-pastable code snippets
html
```
<select id="hall" wire:model="hall_id">
...
</select>
```

Component 1
```
public $hall_id = '';
...
public function updatedHallId($value)
    {
        $this->emit('hallChanged', $value);
    }
```

Component 2
```
protected $listeners = ['hallChanged'];
public $showTable = false;
...
public function hallChanged()
    {
        $this->showTable = true;
    }
```

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.7.1
- Browser: Chrome

**Comment by RomkaLTU** [comment]
So it's turns out that if when receiving event, property value must be string, 

This will not work:

```
public $showTable = false;
...
public function hallChanged()
    {
        $this->showTable = true;
    }
```

This will work

```
public $showTable = 0;
...
public function hallChanged()
    {
        $this->showTable = 1;
    }
```

**Comment by austenc** [comment]
@RomkaLTU could you be more specific about what is not working? I tested this and am able to set the property in the listener function, so we'll need some more information about what's wrong or how to reproduce this to investigate. 

Thank you!

**Comment by calebporzio** [comment]
Thanks @austenc - closing this as it has not been reproduced reliably.

Please re-submit if the issue persists and can be reproduced in a Laravel Playground or something distinct.

Thanks!

**Comment by Acatecatl** [comment]
public function change()
    {
        $this->emit('hallChanged'); 
    }
