### ISSUE TITLE
How can I change page title when I use full page components

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [livewire/livewire#1756]
### Description

    <head>
          <title>dynamic title here - {{ config('app.name') }}</title>
    </head>

**Context**
- Livewire version: [e.g. 2.x]
- Laravel version: [e.g. 8.x]

**Comment by uteq** [comment]
@ShekhSaifuddin007 What exactly are you trying to accomplish?

If I understand it properly you would like to change the app title depending on the Livewire component that is loaded. I would do it like this:

Livewire component
```blade
@push('page-title')
dynamic title here
@endpush
```

app.blade.php
```
<head>
    <title>@yield('page-title') - {{ config('app.name') }}</title>
</head>
```

**Comment by kadershaikh** [comment]
understood...but which file is app.name here?

**Comment by ShekhSaifuddin007** [comment]
@kadershaikh it will look into your `app/config/app.php` PHP file's this line `'name' => env('APP_NAME', 'Laravel'),`

**Comment by marispro** [comment]
I think this must be explained in documentation.

**Comment by sifouneAissa** [comment]
**kj;lk;lkj;kj;kj**
`_kljljhklkjhlkj_`

`duffffff`

**Comment by iamodao** [comment]
Using Livewire3 can I change page title from a component's method?
Also, can one component (SiteComponent)  load different views? - I am guessing No
