### ISSUE TITLE
Interaction with alpinejs triggers twice when using @keydown.backspace="$wire.popTag()"

### ISSUE THREAD

**Issue by Slowwie** [livewire/livewire#1758]
### Description
In my select component I want to pop the items when hitting backspace. This works just fine while using `wire:click="popTag()"`.

But at the moment I want to use @keydown.backspace="$wire.popTag()" it just runs twice and pops the two last items. 

### Exact steps to reproduce
I created a [Playground](https://laravelplayground.com/#/snippets/36fa0364-84f0-441e-8427-5ec80d1a98d5) with descriptions for the occuring problem.

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.8.0
- Browser:  tested with Chrome

**Comment by Slowwie** [comment]
I created a workaround with an alpine fuction: 

`              deleteLast() {

                    const tags = this.$wire.subject;
                    if (tags[tags.length - 1]) {
                        console.log('pop')
                        this.removeTag(tags.length - 1)
                    }
                }`

And call it with: 

`x-on:keydown.backspace="deleteLast()"`

But the problem with the event getting fired two times should be fixed anyway.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
