### ISSUE TITLE
Route::currentRouteName() returns empty

### ISSUE THREAD

**Issue by dluague** [livewire/livewire#1760]
### Description
I have a comparison statement and an input in my livewire component blade file like so.
```html
<a 
   class="list-item @if(Route::currentRouteName() === 'settings.profile') list-item-active @endif" 
   href="{{ route('settings.profile') }}"
>Profile {{ Route::currentRouteName() }}</a>

<input 
    type="text" 
    class="form-control" 
    wire:keydown.debounce.1000ms="searchCity($event.target.value)"
    value="{{ $city }}"
>
```
After typing in the input and successful ajax request the `Route::currentRouteName()` returns empty.

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.8.0
- Browser: Chrome

**Comment by lefuex** [comment]
I have the same error occurring when I hit a component refresh via an laravel echo event:

```php
public function getListeners()
{
    return [
        "echo-private:channel,Event" => '$refresh',
    ];
}
```
Also `request()->routeIs('routeName')` is returning `null` after the refresh.

#### Context
- Livewire version: 2.2.9
- Laravel version: 8.6.0
- Browser: Chrome

**Comment by austenc** [comment]
I believe this is a limitation of how Livewire works. The initial page load will be your route, but any further AJAX requests Livewire makes will be sent to an "internal" livewire route like `/livewire/message/...` which has no name.

**Comment by uteq** [comment]
Maybe you could set the Route::currentRouteName() as a public property in your component during mount. Something like this:

```php
public $currentRouteName;

public functio mount()
{
    $this->currentRouteName = Route::currentRouteName();
}
```

This way the current route name stays as it was when you visited the component. Mount is only called the first time the component is build.

**Comment by da-mask** [comment]
> 

Any Idea how you would set the route when writting tests for a component that grabs the route name like this?

**Comment by sayedsadat344** [comment]
> ```
> public $currentRouteName;
> ```

remember to include the **Route** from **use Illuminate\Support\Facades\Route;**

**Comment by sayedsadat344** [comment]
remember to include the Route from use Illuminate\Support\Facades\Route;

**Comment by sayedsadat344** [comment]
`public $currentRouteName;

public function mount()
{
    $this->currentRouteName = Route::currentRouteName();
}`


remember to include the Route from use Illuminate\Support\Facades\Route;

**Comment by sayedsadat344** [comment]
```
use Illuminate\Support\Facades\Route;

public $currentRouteName;

public function mount()
{
    $this->currentRouteName = Route::currentRouteName();
}
```


remember to include the Route from use Illuminate\Support\Facades\Route;

**Comment by krvirus** [comment]
@sayedsadat344  I had the same problem, your method worked for me. thanks
