### ISSUE TITLE
Make TDD a little easier by creating tests with components

### ISSUE THREAD

**Issue by edgrosvenor** [livewire/livewire#177]
**Is your feature request related to a problem? Please describe.**
When creating a Livewire component, I always do php `aritsan make:livewire SomeCoolNewThing` and then immediately do `php aritsan make:test TestSomeCoolNewThing --unit`. I don't like typing and am therefore sad that I have to do this in two commands.

**Describe the solution you'd like**
`php artisan make:livewire SomeCoolNewThing --unit` (Makes usual stuff + unit test)
`php artisan make:livewire SomeCoolNewThing --test` (Makes usual stuff + feature test)

I'm happy to take feedback re the flag names. I'm just riffing on the Laravel "feature tests are the default and --unit means you want a unit test" thing.

**Describe alternatives you've considered**
I've considered continuing to use two commands as described at the top and decided that I don't like that alternative.

**Additional context**
I'm happy to do a PR to make this happen if it's the sort of thing you and the community would be into. Otherwise, I'm fine continuing to just use my own homespun command that does both.

**Comment by faustbrian** [comment]
@calebporzio would this be something that is wanted/needed?

**Comment by calebporzio** [comment]
Hey @edgrosvenor, yeah, I could totally see that use case.

For now, I'll say let's hold off because I don't see a clear "best way" and I don't want to add and maintain too many hidden command options that only a couple people use.

I'll keep this in mind though - thanks for checking first! And for bubbling it up to the top of my notifications @faustbrian

**Comment by edgrosvenor** [comment]
@calebporzio I get it. Hidden options are a pain. I created my own command that includes this and the ability for me to choose which of my own little library of stubs to use for everything. So even though I suggested it, I wouldn't personally have a use for it since my own need is already covered. If I can find a good way to make what I've done for myself useful to others, I'll release it myself.

**Comment by calebporzio** [comment]
Sounds perfect @edgrosvenor, thansk!
