### ISSUE TITLE
Model attributes cast to date do not work with date inputs

### ISSUE THREAD

**Issue by philipnewcomer** [livewire/livewire#1771]
When a model has an attribute that is cast as a date, the attribute binding is broken in Livewire components. The value is not filled into the date input on initial load, and when a date is chosen, the date appears in the control for a moment, but when the component is refreshed the value disappears.

If I remove `'date_field'` from the model's $dates property, everything works as expected. However, I don't want to give up Laravel's date casting and I was under the impression based on https://laravel-livewire.com/docs/2.x/properties#important-notes that dates should work out of the box.

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    protected $dates = [
        'date_field'
    ];
}
```

```php
<?php

namespace App\Http\Livewire;

use App\Models\MyModel;
use Livewire\Component;

class DateTest extends Component
{
    public $model;

    protected $rules = [
        'model.date_field' => 'date'
    ];

    public function mount(MyModel $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        return view('livewire.date-test');
    }

    public function save()
    {
        $this->validate();
        $this->model->save();
    }
}
```

```html
<form wire:submit.prevent="save">
    <input type="date" wire:model="model.date_field">

    <button type="submit">
        Save
    </button>
</form>
```

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.8.0
- Browser: Chrome

**Comment by basepack** [comment]
Also see this comment for a complete example how to get it working on the affected pull request: https://github.com/livewire/livewire/pull/1665#issuecomment-704541547

**Comment by philipnewcomer** [comment]
Thanks all. I'll close out this issue since 2.3 has been released.
