### ISSUE TITLE
BUG: Livewire + Alpine entangle.defer

### ISSUE THREAD

**Issue by deanzod** [livewire/livewire#1774]
If you use entangle and defer in Alpine it causes an issue where every second submit is ignored by livewire. When doing this with a more complex form using arrays it causes the "Livewire encountered corrupt data when trying to hydrate the ['x'] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests." error

See video for example with requests in dev tools:
https://www.youtube.com/watch?v=uJhY9Wv5KDw

Steps to reproduce:

Create component:

```php
class Test extends Component
{
    public $testing;
    public function submit()
    {
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

View:

```html
<div>
    <div x-data="{ testing:  @entangle('testing').defer }">
        <input type="text" x-model="testing">
        <p>Alpine: <span x-text="testing"></span></p>
        <p>Livewire: {{$testing}}</p>
        <button wire:click.prevent="submit">Submit</button>
    </div>
</div>
```

Then type a letter, click submit, type another click submit etc...

Removing defer works perfectly but sends a request with every keystroke

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.8.0
- Browser: Chrome

**Comment by deanzod** [comment]
To add to this, after a bit more testing it seems the bug is only present if I change a single character.

**So if I:**

type: 'a' -> submit -> livewire result =  'a' (correct)
append another 'a' -> submit -> livewire result = 'a' (incorrect)

**But if I:**

type: 'a' -> submit -> livewire result = 'a' (correct)
append another 'ab' -> submit -> livewire result = 'aab' (correct)

All of this behaviour is very consistent. It has become a major issue for me now as it happens every time after failing validation and it just doesn't seem feasible to exclude `defer` and allow a request with every key stroke on a large form

**Comment by zepfietje** [comment]
Hi @deanzod, could you include the validation part of your code? I believe I've been running into this issue too.

**Comment by deanzod** [comment]
@zepfietje  Ok, here is a video of the other issue which I believe is related to the core issue:
https://youtu.be/xvIN6kc8cYw

Component:

```php
class Test extends Component
{

    public $testing = ['', ''];
    public function submit()
    {
        $this->validate(['testing.1' => 'required']);
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

View

```html
<div>
    <div x-data="{ testing:  @entangle('testing').defer }">

        <input type="text" x-model="testing[0]">
        <input type="text" x-model="testing[1]">
        @error('testing.1') <span class="error">{{ $message }}</span> @enderror

        <p>Alpine: <span x-text="testing[0]"></span></p>
        <p>Livewire: {{$testing[0]}}</p>
        <button wire:click.prevent="submit">Submit</button>
    </div>
</div>

```

**Comment by zepfietje** [comment]
@deanzod the video you just posted is set to private.

**Comment by deanzod** [comment]
@zepfietje sorry - should show now

**Comment by zepfietje** [comment]
> @zepfietje Ok, here is a video of the other issue which I believe is related to the core issue:
> [youtu.be/xvIN6kc8cYw](https://youtu.be/xvIN6kc8cYw)

Okay, so this one is about the `CorruptComponentPayloadException`.

**Comment by zepfietje** [comment]
> If you use entangle and defer in Alpine it causes an issue where every second submit is ignored by livewire.
> 
> See video for example with requests in dev tools:
> [youtube.com/watch?v=uJhY9Wv5KDw](https://www.youtube.com/watch?v=uJhY9Wv5KDw)

@deanzod, but is there any validation present in this issue?

**Comment by deanzod** [comment]
I've included the exact code along with each video. First one there is no validation but it shows some sort of bug where at least 2 keypresses are needed in order for entangle to work on every other request. 

The 2nd example is what triggered me to open the issue and when I wrote the most stripped down code (op) I spotted that issue. I am assuming they are related in some way but the validation error does seem to only be when using arrays.

**Comment by zepfietje** [comment]
@deanzod, I think that could very well be the case. IIRC, I ran into both issues you described in the same situation when using array properties.

**Comment by zepfietje** [comment]
Not sure if it's related, but I also ran into an issue when using 2 inputs entangled to `ranges.*.start` and `ranges.*.end`. When updating the Livewire side after filling both inputs, the input you first updated gets cleared. If I'm correct, this only happened when validating on 'submit' and not when commenting out the validation part.

**Comment by deanzod** [comment]
Sorry @calebporzio not sure if this should have actually been on the Alpine GitHub issues or here? I've been trying to get to the bottom of this for over a week now and I just can't figure out the root cause.

If it is a Livewire problem I can keep trying to figure it out and and hopefully fix. But if it's Alpine I wouldn't know where to start

**Comment by deanzod** [comment]
After simplifying the array/validate issue above I can confirm the error is still thrown every time.

Simplified copy/paste code:

```php

class Test extends Component
{
    public $testing = ['', ''];
    public function submit()
    {
    }

    public function render()
    {
        return view('livewire.test');
    }
}

```


```html

<div>
    <div x-data="{ testing:  @entangle('testing').defer }">
        <input wire:key="a1" type="text" x-model="testing[0]">
        <input wire:key="v2" type="text" x-model="testing[1]">
        <button wire:click.prevent="submit">Submit</button>
    </div>
</div>

```

Type a letter->submit, type another->submit -> _"Livewire encountered corrupt data when trying to hydrate the [test] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests."_

**Comment by basepack** [comment]
Seems a bit related with this issue of mine (also an array): https://github.com/livewire/livewire/issues/1762

**Comment by deanzod** [comment]
Was super hopeful with all the patches in v2.3.0 but sad to say both issues above still exist :(

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by deanzod** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by deanzod** [comment]
Updated to 2.3.1 and issue still exists. :(

**Comment by deanzod** [comment]
REOPEN

**Comment by joshhanley** [comment]
@deanzod I was experiencing this issue too, but upgrading to 2.3.1 and also upgrading Alpine to 2.7.3 fixed my issue. Did you also update Alpine?

**Comment by deanzod** [comment]
@joshhanley I just made sure alpine was also updated to latest version and it still has the same bug with the stripped down code. A bit worrying as I'm using livewire/alpine in production

**Comment by joshhanley** [comment]
@deanzod ok thanks, good to know. I've created a failing test in PR #1947 which replicates the issue.

I understand it can be concerning when trying to use this and it doesn't work as expected, but keep in mind \@entangle is a new feature as of Livewire 2 and as such isn't fully battle tested. 

But @calebporzio has been pretty amazing with his responses, getting a lot of these issues fixed quickly once he has a failing test.

I would recommend using your own watchers if your running something critical in production in the meantime.

Hope this helps! (And if it's any consolation I'm also running this in production 😬)

**Comment by calebporzio** [comment]
Thanks @joshhanley for the PR. This has been fixed and is on `master` - will be tagged soon

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
