### ISSUE TITLE
fill() method doesn't work with model-properties binding

### ISSUE THREAD

**Issue by zofe** [livewire/livewire#1776]
### Description
I'm trying to set property that is binded to a model:

```
...
class PartnerRegistration extends Component
{
    public $company;

    protected $listeners = [
        'set:address' => 'setAddress'
    ];

    protected $rules = [
        'company.address' => 'required',
    ];

    public function mount($rid = null)
    {
        $this->company = new Company();
    }

    public function setAddress($address)
    {
        $this->fill(['company.address'=>$address]);
    }
...

```

set:address is called via `window.livewire.emit('set:address', 'my new address')` 
from a vue component (i've also livewire-vue 0.3.1).
the problem is inside livewire, because setAddress is called, but "company.address" doesn't change.

- Livewire  2.2.9
- Laravel 8.8.0
- Chrome 85.0.4183.121

**Comment by moonofmylife** [comment]
Use $this->syncInput

**Comment by austenc** [comment]
@zofe couldn't you just use $this->company->address = $address?

Or, even better, use `wire:model`?

**Comment by zofe** [comment]
@austenc wire:model is absolutely the best choice, but in my case the "component" where address  handled is a vue component (with google places address api interactions, so a complex stuff to use direct wire:model binding)

and yes $this->company->address it's a smarter way to do it, thanks.
Anyway `$this->fill(['company.address'=>$address]);` doesn't seem to work, so  I decided to create this issue report.

**Comment by moonofmylife** [comment]
@zofe have you tried using sync Input? 
`$this->syncInput('company.address', $address);`

**Comment by zofe** [comment]
@moonofmylife really thanks, 
tested now  this->syncInput('company.address', $address);  and it works, and seems smarter than `$this->company->address `  because i need to fill  multiple fields (address, streetnumber, etc..)

There is a docs about  **syncInput** ?  I did not find on livewire site

**Comment by moonofmylife** [comment]
@zofe binding (wire:model) uses this function. I found it when I was looking at the source code. It was also very necessary for me in Vue

**Comment by calebporzio** [comment]
Hmm I think `$this->fill()` should work for this case.

I consider this a bug.

The current implementation of `$this->fill()` doesn't support dot notation.

I think this would be a fairly simple PR

**Comment by zofe** [comment]
ok
https://github.com/livewire/livewire/pull/1872

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by iksaku** [comment]
REOPEN

**Comment by iksaku** [comment]
Although the PR was closed, this is still an issue. Will send another PR later today for this. Until then, this should remain open

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
