### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST in Laravel livewire

### ISSUE THREAD

**Issue by al-kadafi** [livewire/livewire#1779]
Sorry, I have a routes problem in laravel livewire. I want to test my login form validation on my website by sending empty input and continuously clicking the submit button (after giving a response of course), and on the fifth (5) click I have a problem "The GET method is not supported for this route. Supported methods: POST". Does anyone know about this problem? Because I also tried it on a simple form on localhost and there was no error.

I use laravel livewire 2.2

This is the code on my website,

Blade
```
<form wire:submit.prevent="check">
   <div class="form-group">
      <label class="label">Email</label>
      <div class="input-group">
         <input wire:model.defer="email" type="email" class="form-control" placeholder="xxx@xxx.xx">
         <div class="input-group-append">
            <span class="input-group-text">
            <i class="mdi mdi-check-circle-outline"></i>
            </span>
         </div>
      </div>
      @error('email')<label class="text-danger">{{ $message }}</label> @enderror
   </div>
   <div class="form-group">
      <label class="label">Password</label>
      <div class="input-group">
         <input wire:model.defer="password" type="password" class="form-control" placeholder="**********">
         <div class="input-group-append">
            <span class="input-group-text">
            <i class="mdi mdi-check-circle-outline"></i>
            </span>
         </div>
      </div>
      @error('password')<label class="text-danger">{{ $message }}</label> @enderror
   </div>
   <div class="form-group">
      <button class="btn btn-success submit-btn btn-block" wire:loading.attr="disabled" >
         <div wire:loading.remove>Login</div>
         <div wire:loading>
            <div class="loading-bar bg-white"></div>
            <div class="loading-bar bg-white"></div>
            <div class="loading-bar bg-white"></div>
            <div class="loading-bar bg-white"></div>
         </div>
      </button>
   </div>
</form>
```
Controller
```
class Login extends Component
{
    
    public $password;
    public $email;

    protected $rules = [
            'password' => 'required',
            'email' => 'required|email',
        ];
        
    public function check()
    {
    
        $this->validate($this->rules);

        if (Auth::attempt(['email' => $this->email, 'password' => $this->password]))
        {
            
            redirect()->to('livewire/add');
            
        }else
        {   
            
            $this->dispatchBrowserEvent('alert', ['type' => 'error', 'title' => 'Error','message' => 'Credential not valid']);

        }
        
    }
    
    public function render()
    {
        return view('livewire.login')->extends('backend.v2.master');
    }
}
```
Routes
```
Route::group(['prefix' => 'livewire'], function() {
       Route::get('/login',Login::class);
       Route::get('/add',Add::class);
});
```
First submit result
![image](https://user-images.githubusercontent.com/20838827/95432854-64b1d180-0979-11eb-99e9-395143b18c89.png)

Error result after the fifth click

![image](https://user-images.githubusercontent.com/20838827/95430217-a80a4100-0975-11eb-82d4-502f7dc093fd.png)

Thanks for your help.

**Comment by ayoub-bousetta** [comment]
Same error, works fine on php artisan serve but shows this error on a real server

**Comment by al-kadafi** [comment]
@ayoub-bousetta thanks for your response, do you have an idea to solve that problem?

**Comment by mokhosh** [comment]
I'd say don't use Livewire for logging the user in. You just need it for validation, so just do that with Livewire. Let the login process be a normal form submit, you're redirecting the user and changing the page anyways.

**Comment by austenc** [comment]
@al-kadafi Wondering if the problem is a conflict with Livewire's internal routes? 

Try to use another prefix for your routes (so there's no `/livewire` in the URL) and see if the issue still occurs.

**Comment by al-kadafi** [comment]
@mokhosh Thanks for your suggestion, I just wanted to know if I did wrong or it's a livewire bug. I think this is an important issue, especially for version 1.x because there is no wire:model.defer feature in the input field.

**Comment by al-kadafi** [comment]
@austenc I've tried to use another prefix but still having same problem. Thanks btw

**Comment by ayoub-bousetta** [comment]
Tried another Server and it works, don't know if it's a miss of extension on my server or something else but i change the server and it's working like a charm...

You can also try to separate the 2 livewire comp if you have them nested...

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by WaelMz** [comment]
i have same issue when i use livewire in contact form while typing form automatically send GET request and return with exception 
The GET method is not supported for this route. Supported methods: POST.  i can not figure out whats happens ...
![Untitled](https://user-images.githubusercontent.com/33140498/100799228-6950ae80-342d-11eb-864a-7d7d042ab6b7.png)

**Comment by ideadx** [comment]
Having the same issue while navigating using $records->links() for pagination for the records.

**Comment by austenc** [comment]
@ideadx did you forget to use the `WithPagination` trait by chance?

**Comment by magic-thomas** [comment]
Every time I join new projects, this error bugs me so much. 

In my case this error comes with pagination. 

It waste my 2~3 days for fixing.  and it goes ok without proper maintenance. 

I can not understand why.

I just wish no more bugging for next project.

**Comment by Fredericld** [comment]
I am having the same issue. fine on php artisan serve and not working on remote server.
If the server is missing something does anyone know what it is?

**Comment by Fredericld** [comment]
@al-kadafi @WaelMz  @ayoub-bousetta 

I am having the same bug. 5 clicks and it fails. Can you please share how you fixed the problem? Or do we know what makes it fail with some server? 
I do not use pagination. It fails with every component I create, even with simple ones like this one (https://laravelplayground.com/#/snippets/a256d1e5-0581-4710-abc1-d8a60205b598)

**Comment by webakademia** [comment]
> 
> 
> @al-kadafi @WaelMz @ayoub-bousetta
> 
> I am having the same bug. 5 clicks and it fails. Can you please share how you fixed the problem? Or do we know what makes it fail with some server?
> I do not use pagination. It fails with every component I create, even with simple ones like this one (https://laravelplayground.com/#/snippets/a256d1e5-0581-4710-abc1-d8a60205b598)
> 
> Laravel 8
> Livewire 2.4.0

Hi, I modified the bootstrap pagination. It goes like this:

@if ($paginator->hasPages())
    <ul class="pagination" role="navigation">
        {{-- Previous Page Link --}}
        @if ($paginator->onFirstPage())
            <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                <span class="page-link" aria-hidden="true">
                    <span class="d-none d-md-block">&lsaquo;</span>
                    <span class="d-block d-md-none">@lang('pagination.previous')</span>
                </span>
            </li>
        @else
            <li class="page-item">
                <button type="button" class="page-link" wire:click="previousPage" rel="prev" aria-label="@lang('pagination.previous')">
                    <span class="d-none d-md-block">&lsaquo;</span>
                    <span class="d-block d-md-none">@lang('pagination.previous')</span>
                </button>
            </li>
        @endif

        {{-- Pagination Elements --}}
        @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
                <li class="page-item disabled d-none d-md-block" aria-disabled="true"><span class="page-link">{{ $element }}</span></li>
            @endif

            {{-- Array Of Links --}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="page-item active d-none d-md-block" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                    @else
                        <li class="page-item d-none d-md-block"><button type="button" class="page-link" wire:click="gotoPage({{ $page }})">{{ $page }}</button></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        {{-- Next Page Link --}}
        @if ($paginator->hasMorePages())
            <li class="page-item">
                <button type="button" class="page-link" wire:click="nextPage" rel="next" aria-label="@lang('pagination.next')">
                    <span class="d-block d-md-none">@lang('pagination.next')</span>
                    <span class="d-none d-md-block">&rsaquo;</span>
                </button>
            </li>
        @else
            <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                <span class="page-link" aria-hidden="true">
                    <span class="d-block d-md-none">@lang('pagination.next')</span>
                    <span class="d-none d-md-block">&rsaquo;</span>
                </span>
            </li>
        @endif
    </ul>
@endif

Then I reference it: {{ $whatever->links('vendor.pagination.bootstrap-4-livewire') }}

It works fine. I only have to use it with livewire pagination.

**Comment by Fredericld** [comment]
Hi,

My issue was coming from my ISP. They were using an Apache SPAM module that was blocking the request. After removing the module, all was working fine.

**Comment by Redemple332** [comment]
The GET method is not supported for this route. Supported methods: POST in Laravel livewire
#1779

**Comment by xtreme2020** [comment]
Same error, i made this little fix to the route and seems to be working. i use full page components.
                  **Allow method, Route, Livewire component**
Route::match(['get','post'],'/',\App\Http\Livewire\Users\Userindex::class)->name('users.index');

**Comment by jimfromtexas** [comment]
> @ideadx did you forget to use the `WithPagination` trait by chance?

This did the trick

**Comment by GiovaneVerbinnen** [comment]
I have the same bug, i use 'use WithPagination;', but have several times the bug comes.

**Comment by damms005** [comment]
Also, in my experience, cache buildup can cause this routing error. So, simply clearing the cache fixed it for me:

```php artisan optimize:clear```

**Comment by jimfromtexas** [comment]
Cool thanks

James Henderson
https://jameshenderson.online<https://jameshenderson.online/>
Developer
Mobile Applications
API Services
***@***.***
832-338-2926
________________________________

**Comment by Imanuddin77** [comment]
I solved the problem by using:

`<div wire:click="gotoPage($page)"></div>`

instead of:

`<a href="{{ $pageLink }}"></a>`.

Just like in the documentation (Using Custom Pagination View):

https://laravel-livewire.com/docs/2.x/pagination

**Comment by AngelDevSw** [comment]
public $search = '';
    use WithPagination;
    //lo solucióne incorporando el paginador de livewire y sin problema funciona

    public function render()
    {
         // Obtenemos todos los usuarios con su nivel
         $users = User::with('level')
         ->where('name', 'LIKE', '%'.$this->search.'%')
         ->paginate(5);

         
        

        return view('livewire.users.index',compact('users'));
    }

**Comment by jamesautodude** [comment]
For me, it was a mistake within my view file. I was missing a </div>

**Comment by jamesautodude** [comment]
For me personally, there's something wrong when trying to use empty/not set checks like:

```
{{ !empty($user->profile->city) ? $user->profile->city : 'City not set' }}
```

I have this on a livewire setup where you choose what you want to do (edit profile, view profile) and it loads a certain view. If you switch between the 2, I get the error saying POST is the only supported method. This only happens with the above code. If I remove that code, the error goes away and I can switch normally. Odd

**Comment by zilef2** [comment]
Everything works perfectly fine on my local environment, but upon uploading the application to the server, I'm facing the following error:

The GET method is not supported for route livewire/message/actualizacionBD. Supported methods: POST.

I've double-checked my code, and I'm certain that I'm using the correct method in my application. It seems to be a server-specific problem as I'm not encountering this error locally. It only happends when I try to upload a excel file with (laravel Excel ext)  https://laravel-excel.com/

**Comment by Yondalne** [comment]
> i have same issue when i use livewire in contact form while typing form automatically send GET request and return with exception The GET method is not supported for this route. Supported methods: POST. i can not figure out whats happens ... ![Untitled](https://user-images.githubusercontent.com/33140498/100799228-6950ae80-342d-11eb-864a-7d7d042ab6b7.png)

Hi,
Have the same issue there, somehow the first time I'm going to my login page and try to enter some information I have this error.
But after a reload, it goes away but it is still happening everytime I'm trying with a new browser or if i completely close the tab.
Any idea of how to solve it ?

**Comment by WaelMz** [comment]
I think this issue is caused by something in the server
Maybe it's because of mod security, sometimes the server limits requests to 5 or 6 requests per second, I don't know why, I think the issue is not from LiveWire

I hope someone can follow up on the server errors related to this issue, find out the reason, and tell us the main reason, I get the issue repeatedly even on the latest Livewire version

**Comment by hugoaf** [comment]
I was biten by this yesterday when publishing to a shared server, and after several hours of troubleshooting (including mod security checks) I've found that the php version of the public directory had a .htaccess with a cPanel `AddHandler application/x-httpd-ea-php83 .php .php8 .phtml`, so Laravel was detecting php8.3, BUT my main Laravel repo directory which is outside of public directory was running the default php 8.1.

After forcing the main laravel repo to run the php 8.3 version, the Livewire GET method complaint is gone.
