### ISSUE TITLE
wire:target for action + parameter

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#1780]
I'm trying to having a loading state for a specific action with a specific parameter.

I've tried this:

`wire:target="myAction(22)"`

Which does not work. However, just using `myAction` works, but effects all buttons with that action.

How do I target an action AND parameter for loading states?

**Comment by iksaku** [comment]
Not possible at the momento, but you could try and PR that feature, I'm pretty sure it'll come in handy for more people

**Comment by austenc** [comment]
@redbastie another option may be to make a new child component?

**Comment by danharrin** [comment]
This is on the [roadmap](https://github.com/livewire/livewire#roadmap) 👍

**Comment by calebporzio** [comment]
Yep! Good to know there's more demand for it thought. Thanks @danharrin !
