### ISSUE TITLE
The shortenModelAttributes does handle properties with underscores

### ISSUE THREAD

**Issue by aromer** [livewire/livewire#1783]
### Description
When using model binding, with keys like `model.property` there is a method that removes the model prefix. When properties have underscores like `model.snake_case_property` these are skipped, resulting in error messages like "The model.snake case property is required."

### Exact steps to reproduce
Create a component with a validation rule like:
```php
    protected array $rules = [
        'post.snake_case_property' => 'required',
    ];
```
Submit the form and fail the validation, you should see an improperly formatted message.

### Stripped-down, copy-pastable code snippets
https://github.com/livewire/livewire/blob/90f12fee988f5084758c514b77eb87c9306fedb7/src/ComponentConcerns/ValidatesInput.php#L191-L205

The comparison ` if ($key === $validator->getDisplayableAttribute($key))` converts the key to remove underscores in the getDisplayableAttribute() method causing the comparison to fail.

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Browser: [e.g. Chrome, Safari]

**Comment by zepfietje** [comment]
I think I ran into this issue with nested array properties too.

**Comment by zepfietje** [comment]
@calebporzio, I suppose this issue can be closed now?

**Comment by danharrin** [comment]
Thanks @zepfietje!

**Comment by aromer** [comment]
Thank you everyone. I can confirm this works in the original reported application.
