### ISSUE TITLE
LastPass autofill on Safari still not working as of v2.2.9

### ISSUE THREAD

**Issue by sunlight** [livewire/livewire#1784]
### Description
It seems that the issues with Safari and auto-filling passwords still stands (see #1081 and #1440). I am using the TALL stack with the latest Livewire & Laravel versions. I have run `php artisan view:clear` and cleared Safari's cache but this still happens:

![](https://sunlightdigital.net/livewire.gif)

The auto-fill triggers the "required" errors and attempting to submit the form clears the inputs (presumably meaning the class's properties are not being populated).

### Exact steps to reproduce
This happens with the out-of-the-box auth pages that ship with the TALL stack. Replacing `wire:model.lazy` with `wire:model` also did not help.

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.9.0
- Browser: Safari 14

**Comment by Tuginho** [comment]
Same for me. Tried like everything 2-3 hours, but I guess thats some high level stuff to solve this.

**Comment by sunlight** [comment]
It looks like PR #1721 was designed to fix autofill on Safari, however I'm guessing this was aimed at Safari's own autofill rather than 3rd-party apps. Unfortunately I've no idea what LastPass & Safari do behind the scenes when autofilling.

**Comment by glaesser** [comment]
Indeed, it was working previously in v2.2.8 (tested autofill in safari iOS w/ 1Password), but as of 2.2.9 doesn't work anymore. @calebporzio would you mind having another look at this issue?

**Comment by iksaku** [comment]
v2.3.0 has been released with another Safari fix. Could you try again?

**Comment by glaesser** [comment]
> v2.3.0 has been released with another Safari fix. Could you try again?

It appears to have been fixed (again), great :)

**Comment by f-liva** [comment]
Still present in 2.3.18
