### ISSUE TITLE
Implicit model binding in mount() should not work for null values

### ISSUE THREAD

**Issue by gjm** [livewire/livewire#1788]
### Description

If I have a (nullable) model instance as a parameter in `mount()` and pass `null` as a parameter it tries to read the row where id is `null`.

### Exact steps to reproduce

1. Add a `mount()` method with a model type hint
1. Pass `null` as a parameter

### Stripped-down, copy-pastable code snippets

```php
public function mount(?SomeModel $model)
{
    if ($model) {
        // ... do stuff ...
    }
}
```

```html
<livewire:some-component :model="$model" />
```
**note**: `$model` is `null`

**Context**
- Livewire version: 2.2.5
- Laravel version: 7.28.3
- Browser: Chrome

**Comment by austenc** [comment]
@gjm Livewire has the same behavior as Laravel when using a regular controller with implicit binding. If you try to do this with a Laravel controller / route, it also throws a `ModelNotFoundException`. That being said, Livewire probably shouldn't change the implementation to support this.

If you want to achieve this sort of "optional" functionality, you may have to live with _not using implicit binding_. Here's an example:
```
    public function mount($user)
    {
        $model = $user ?? new User;
    }
```
