### ISSUE TITLE
Cannot find Livewire component inside Alpine template

### ISSUE THREAD

**Issue by zepfietje** [livewire/livewire#1791]
### Description

When rendering a Livewire component inside an Alpine `<template>`, the Livewire component instance cannot be found e.g. when using `@entangle()` or `$wire.entangle()`.

### Exact steps to reproduce

Copy the example below and see the following error in the console:
- Chrome: `Uncaught TypeError: Cannot read property '$wire' of undefined`
- Firefox: `Uncaught TypeError: wireEl.__livewire is undefined`
- Safari: `TypeError: undefined is not an object (evaluating 'wireEl.__livewire.$wire')`

#### `routes/web.php`

```php
Route::view('/foo', 'foo');
```

#### `resources/views/foo.blade.php`
```blade
<!DOCTYPE html>
<html>
  <head>
    <livewire:styles />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  </head>
  <body>
    <div x-data="">
      <template x-if="true">
        <livewire:foo />
      </template>
    </div>
    <livewire:scripts />
  </body>
</html>
```

#### `app/Http/Livewire/Foo.php`

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Foo extends Component
{
    public bool $foo = true;
}
```

#### `views/livewire/foo.blade.php`

```blade
<div x-data="{ foo: $wire.entangle('foo') }"></div>
```

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.9.0
- Browser: Chrome, Firefox & Safari

**Comment by austenc** [comment]
@zepfietje Does the error still occur if you use the `@entangle` directive instead of `$wire.entangle`?

Seems like the directive is the recommended way of using entangle.

**Comment by zepfietje** [comment]
@austenc, yes, the issue occurs when using both `@entangle()` and `$wire.entangle()` as I described in the original issue description.

**Comment by austenc** [comment]
@zepfietje sorry, I somehow missed that! Entangle seems to be doing some weird stuff for a lot of folks lately, I've been checking out other `entangle` related issues to see if they're related too. 

Will see if I can reproduce with your code and figure it out :)

**Comment by zepfietje** [comment]
@austenc, let me know!
Would be cool if we could actively solve these annoying bugs.
Thanks for your effort!

**Comment by austenc** [comment]
I was able to reproduce this, but now I'm wondering if it's a bug or just a limitation of how `x-if` and `x-for` work within Alpine?

Guessing here (because I don't know enough about Alpine under the hood), but doesn't `x-if` remove the element from the main DOM? Somehow it seems that this removes the contents of `<template>` from the scope where the `$wire` variable is. Perhaps Caleb or one of the dudes who are more familiar with Alpine could shed some light on this.

**Comment by zepfietje** [comment]
@marin246, `@this` is a Blade directive which compiles to the same thing as `$wire`.

**Comment by marin246** [comment]
interesting, because @this works for me and $wire does not.

**Comment by zepfietje** [comment]
> interesting, because @this works for me and $wire does not.

Are you talking about the specific case of this issue? If so, please elaborate on what you're experiencing.

**Comment by marin246** [comment]
Yes, i have the following:
```
<div x-data="">
   <select x-on:change="@this.updatePerPage($event.target.value)">
      @foreach($perPageOptions as $perPageOption)
          @if ($perPageOption != $perPage)
               <option value="{{ $perPageOption }}">{{ $perPageOption }}</option>
          @endif
      @endforeach
   </select>
</div>
```

I tried to use $wire instead of @this and it did not work as in the initial post. (yes, i know, livewire is supposed to handle selects automatically with a model but my actual code is more complicated)

**Comment by zepfietje** [comment]
@marin246, not sure if that's at all related to this issue, which has to do with **rendering a Livewire component inside an Alpine `<template>`**.

**Comment by marin246** [comment]
mmh, yeah, i don't have a template, that's correct. Just Blade. But maybe it's not related to the template? I don't know.. I just get the same errors. I am sorry, if this is not helpful 😅

**Comment by zepfietje** [comment]
Maybe have a look at other issues on this repo, as I don't think your problem is the same as this issue.

**Comment by calebporzio** [comment]
This is a limitation of x-for in Alpine.

Blade templating (`<livewire:...`) happens BEFORE the browser loads the page, and Alpine templating happens AFTER the browser loads the page.

I would encourage you to use Blade's `@foreach` in areas you need looping in templates.

**Comment by zepfietje** [comment]
> This is a limitation of x-for in Alpine.
> 
> Blade templating (`<livewire:...`) happens BEFORE the browser loads the page, and Alpine templating happens AFTER the browser loads the page.
> 
> I would encourage you to use Blade's `@foreach` in areas you need looping in templates.

@calebporzio, do you mean it's a limitation with Alpine's `<template>` in general? I wasn't talking about `x-for` but `x-if`.

**Comment by austenc** [comment]
@zepfietje This is what I was mentioning above, although Caleb explained it much better than I did. 😅 

Both `x-for` and `x-if` are templating done by Alpine, so due to the order of operations that Caleb mentioned (Livewire before, then Alpine after the page loads), what you're trying to do will not work.

**Comment by zepfietje** [comment]
Yeah I understand @austenc, just wanted to be sure since Caleb mentioned x-for (which could have other reasons why it wouldn't work).

**Comment by calebporzio** [comment]
Thanks for clarifying. @austenc is correct

**Comment by samjurriaans** [comment]
I'm not sure if this even is an issue anymore like it was back then, but We managed to solve this problem by triggering Livewire.rescan(); after the <template x-if="true">, which ended up in something like <template x-if="condition"> {{ do Livewire.rescan(); here somewhere in javascript }} <livewire:foo-bar /> </template>.
