### ISSUE TITLE
Weird intermittent issue with $this->reset() on form

### ISSUE THREAD

**Issue by mrdigitalau** [livewire/livewire#1794]
### Description

I am building a login form. Both of my inputs (email,password) are wire:model.defer.

When I submit and check the credentials, if they are correct, user is directed to dashboard, if not, error is returned.

I have also made it reset the password field so that they can re-type their password. The issue is when using wire:model.defer, a strange thing occurs. The actual email field gets removed and the password is moved into the email field, revealing the password that was typed. Extremely weird.

It's an intermittent problem as you'll see in the video link:

See the video here: http://somup.com/cY66fZlv7S

### Exact steps to reproduce

- Type username and incorrect password
- Hit submit
- Error returns and the password field is erased but it them some reason moves to the email field with the password now being visible.

### Stripped-down, copy-pastable code snippets

`   
        <div class="form-group mb-3">
            <label for="inputEmail" class="visually-hidden">Email address</label>
            <input type="email" wire:model.lazy="email" class="form-control" placeholder="Email address" autofocus>
            @error('email') <span class="error">{{ $message }}</span> @enderror
        </div>

        <div class="form-group mb-3">
            <label for="inputPassword" class="visually-hidden">Password</label>
            <input type="password" wire:model.lazy="password" class="form-control" placeholder="Password">
            @error('password') <span class="error">{{ $message }}</span> @enderror
        </div>
`

```

class Login extends Component
{

    public $email;
    public $password;
    public $attempts;

    public function render()
    {
        $attempt = 0;

        return view('livewire.login');
    }

    public function submit()
    {

        $this->validate([
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $credentials = [

            'email' => $this->email,
            'password' => $this->password,
        ];

        if (auth()->attempt($credentials, true)) {
            return redirect(route('dashboard'));
        }

        if ($this->attempts >= 3) {

            $this->addError('error', 'Too many attempts. Please refresh to try again.');

        } else {

            $this->addError('error', 'Your credentials are incorrect');

        }

        $this->attempts++;

        $this->reset('password');

    }
}
```

**Context**
- Livewire version: [e.g. 2.2.3]
2.2.9

- Laravel version: [e.g. 8.3.1]
Laravel 8.9.0

- Browser: [e.g. Chrome, Safari]
Chrome

**Comment by zepfietje** [comment]
@mrdigitalau, have you tried wrapping the `@error` Blade directive in an element?
https://laravel-livewire.com/docs/2.x/troubleshooting

**Comment by danharrin** [comment]
Hey @mrdigitalau, if this is still an issue, please post a Laravel Playground with an example of the issue so we can reproduce it. If not, feel free to close the thread. Many thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
