### ISSUE TITLE
Download response breaks component

### ISSUE THREAD

**Issue by snapey** [livewire/livewire#1796]
### Description
With a working Livewire component - a datatable with filters and pagination - implementing the download response as indicated in the docs breaks the component.  Clicking on any wire:model bound element creates the error;
```
Uncaught (in promise) TypeError: Cannot read property '$wire' of undefined
    at Livewire.value (index.js:29)
    at eval (eval at saferEval (alpine.js:115), <anonymous>:3:78)
    at saferEval (alpine.js:115)
    at new Component (alpine.js:1411)
    at alpine.js:1556
    at alpine.js:1538
    at walk (alpine.js:87)
    at walk (alpine.js:91)
    at Component.walkAndSkipNestedComponents (alpine.js:1532)
    at Component.initializeElements (alpine.js:1549)
```
### Exact steps to reproduce

Create button with wire:click, linked to export function and return a download response as described in the docs.

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.8.0
- Browser: Chrome
Project is based on Jetstream with Livewire, and the view is a full-page component

**Comment by snapey** [comment]
Workaround implemented is to perform download via a 'dumb' listener component 

Export the Excel to a file in a temp folder.
Emit a livewire event for ‘downloadready’ and pass the filepath with the event

Create a component and include it in the page.
Have the component listen for ‘downloadready’ events
grab the path and perform the download.

This process seems to stop the main component from breaking.

component;
```
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Storage;
use Livewire\Component;

class DownloadReady extends Component
{

    public $listeners=['downloadready'];

    public function downloadready($file)
    {
        return Storage::download($file);
    }

    public function render()
    {
        return view('livewire.download-counts');
    }
}
```
view
```
<div></div>
```

**Comment by snapey** [comment]
I was having further issues with this component such as simply saving the view file (with no changes) would break the component at the next request with the same error as for the file downloads.

Removing x-data from the root of the component fixed the issue and allowed me to implement downloads without the workaround.  Puzzled why initialising alpine on the component view would cause this issue.  I have seen comments elsewhere about problems associated with the loading order of alpine and livewire scripts but don't know what this is based on.

**Comment by rawilk** [comment]
I had the same issue, but I didn't have `x-data` on the root element of the component. In my case, I had the button that triggered the export inside of a dropdown menu, which has `x-data` on it. Adding a `wire:ignore` to the dropdown seems to fix the issue for now, but it's not ideal if you need to have dynamic content inside of the dropdown or whatever element you have it in.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
