### ISSUE TITLE
Uncaught ModelNotFoundException on hydrate

### ISSUE THREAD

**Issue by aqib47** [livewire/livewire#1805]
### Description
Seems like livewire doesn't catch ModelNotFoundException. 
It's using `Illuminate\Queue\SerializesAndRestoresModelIdentifiers` trait(for hydrating models) which uses `findOrFail()` on its `restoreMode` method(Line 98). ```findOrFail``` method causes 404 page.

### Exact steps to reproduce

- Assign model instance on property.

- Delete that item from the database and interact with other inputs. 

- On subsequent request, it would use the same ID to retrieve item which no longer exists, results in 404.

### Stripped-down, copy-pastable code snippets
**Component:**
```
public $findProduct = null;

public function findProduct($id) {
  $this->findProduct = Product::find($id);
}

public function addToCart($id) {
  $this->cartAdd($id);
}

public function render() {
  return view('livewire.products');
}
```
**View:**
```
<div>
  <div class="form-group">
    <label for="product_id">Product ID:</label>
    <input type="text" class="form-control" id="product_id" wire:keyup="findProduct($event.target.value)">
  </div>

  @if($findProduct!=null)
    <p>Name: {{ $findProduct->name }}</p>
    <button type="button" class="btn btn-primary" wire:click="addToCart({{ $findProduct->id }})">Add to Cart</button>
  @else
    No Product found.
  @endif
</div>
```
**It throws an exception when we load product by ID. Then delete that product from the database and add that product to the cart.**

Catching that exception did the trick and no 404 modal appears. Here's how I did that:

Class ```Livewire\HydrationMiddleware\HydratePublicProperties``` Method ```Hydrate```:

**Replace this:**
```
if (isset($serialized['id'])) {
  $model = (new static)->getRestoredPropertyValue(
    new ModelIdentifier($serialized['class'], $serialized['id'], $serialized['relations'], $serialized['connection'])
  );
} else {
  $model = new $serialized['class'];
}
```
**With:**
```
if (isset($serialized['id'])) {
  try {
    $model = (new static)->getRestoredPropertyValue(
      new ModelIdentifier($serialized['class'], $serialized['id'], $serialized['relations'], $serialized['connection'])
    );
  }catch (\Exception $exception) {
    $model = null;
    //Maybe sending exception back to component?
  }
} else {
  $model = new $serialized['class'];
}
```
**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Browser: [e.g. Chrome, Safari]

**Comment by iksaku** [comment]
Until more discussion is provided, I think your best option is to emit an event once a Model is removed, that way you can handle it in your cart component, preventing this type of error.

**Comment by aqib47** [comment]
I don't think that would work unless we actually catch an exception. 

The model item would be deleted by admin, how would we emit an event to visitors' session?

**Comment by iksaku** [comment]
Alright, got your point now.

Difficult implementation to manage... What comes to mind is to use something like `SoftDeletes` to mark as removed, but that will introduce another type of complexity.

Not sure how to handle that properly, but let's wait for other opinions on the matter :)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by aqib47** [comment]
REOPEN
This issue was not resolved, I'm still waiting for somebody to address this.
Thanks!

**Comment by koost89** [comment]
I am actually experiencing the same issue and your proposed solution fixed my issue aswell!
Hope this gets reopened as i would also love for a way to figure this problem out.

**Comment by seche** [comment]
Encountered this issue when dealing with multiple livewire components that query the same model. As soon as you delete one item it throws the error in the subsequent hydrate. Tried to make sure the component had updated values (even overriding them in the boot method) with no luck. The changes applied above did "fix" or hide the issue.

The only other option I haven't tried yet is using Synthesizers to modify the way the model is serialized?
