### ISSUE TITLE
wire:loading.attr="disabled" causes first submit of a form to not do anything. (simple example w/ Laravel playground)

### ISSUE THREAD

**Issue by isaackearl** [livewire/livewire#1806]
### Description

If you have a form that uses wire:submit.prevent and has a submit button etc, and you try to disable the button during loading via wire:loading.attr="disabled" it causes the first submit to not do anything... you have to hit it twice.

### Exact steps to reproduce

Follow instructions here:  (VERY SIMPLE EXAMPLE)
https://laravelplayground.com/#/snippets/9938c747-6cc5-4c90-bc65-b19fbfcc5fa4

### Stripped-down, copy-pastable code snippets

see laravel playground above.

**Context**
- Livewire version: v2.2.9
- Laravel version: v.8.9.0
- Browser: Chrome

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by isaackearl** [comment]
REOPEN

**Comment by isaackearl** [comment]
I re-opened because this is a very simple bug to reproduce and also I think very common, even though alot of people don't notice it because it's not easy to catch.

Imagine wanting to disable a submit button any time the page is loading so that you can't submit while another request is happening... well, that currently makes the submit button not work on first click.

**Comment by isaackearl** [comment]
I'm re-closing this because after running my example on the latest version of livewire, it seems that this has been fixed.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
