### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#181]
**Describe the bug**
When I use the `wire:click` method, I get below error:

> Uncaught (in promise) DOMException: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/2000/xmlns/' is an invalid namespace for attributes.

**To Reproduce**
I have a normal anchor tag:

```html
<a wire:click="prevPage">
Previous Page
</a>
```

When I click it, the method `prevPage` is fired. However, I also get below error in the console log:

> Uncaught (in promise) DOMException: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/2000/xmlns/' is an invalid namespace for attributes.

**Comment by oliverbj** [comment]
OK so a bit more debugging. I figured out the cause of this error: `<svg>` icons!

If I remove all `<svg>` icons from the blade view, the error does not appear and I can use LiveWire as expected.

I am not sure what is causing it to interfere with svg elements?

**Comment by kennyhorna** [comment]
> OK so a bit more debugging. I figured out the cause of this error: `<svg>` icons!
> 
> If I remove all `<svg>` icons from the blade view, the error does not appear and I can use Livewire as expected.
> 
> I am not sure what is causing it to interfere with svg elements?

I'm experiencing the same.. I'm using inline SVG so I played around commenting things and it turned out being the ```<defs>``` attributes of the SVGs. I removed those from my SVG (a simple logo in my case, so it had any impact on the output) and it worked again. 

All of this happened to me after upgrading Tailwind from 0.7 to 1.*. It was working before. Really weird :/

**Comment by oliverbj** [comment]
I’m also using TailwindCSS 1.*.

Unfortunately I can’t modify the svg attributes as easily, as I’m using a Laravel blade directive from a 3rd party package to generate the svg’s.

**Comment by Summonshr** [comment]
I removed id attribute from parent element of svg and it seems to work as it should.
