### ISSUE TITLE
Automatic 'selected' attribute does not work in <select> when <option>'s innerhtml is changed

### ISSUE THREAD

**Issue by marin246** [livewire/livewire#1810]
### Description
I have a dropdown, where the innerhtml of the currently selected \<option\> is different from all other \<option\>s. After selecting another \<option\>, nothing is selected anymore.

### Exact steps to reproduce
In the example below, i use a \<select\> to choose how many rows should be displayed in a table. $perPage stores the currently selected amount of rows to display (e.g. 20). $perPageOptions stores all the available options (e.g. 10,20,50,100).
After the first update to $perPage, nothing is selected anymore.

### Stripped-down, copy-pastable code snippets

```
<select wire:model="perPage">
   @foreach($perPageOptions as $perPageOption)
      @if ($perPage == $perPageOption)
         <option value="{{ $perPageOption }}">Elements {{ $rows->firstItem() }}-{{ $rows->lastItem() }} of {{ $rows->total() }}</option>
      @else
         <option value="{{ $perPageOption }}">{{ $perPageOption }} Elements</option>
      @endif
   @endforeach
</select>
```

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.9.0
- Browser: Firefox, Safari, probably Chrome

**Comment by xtfer** [comment]
I have the same issue, FWIW.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
