### ISSUE TITLE
temporaryUrl breaks until you refresh if they upload non image

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1811]
### Description
If you do the basic upload based on the docs, and put a tempUrl preview on the page, the file upload control breaks until you refresh the page, even if you validate this property on updated.

### Stripped-down, copy-pastable code snippets
Just do the file upload docs and upload a zip file.

I think this kind of malicious behaviour by user shouldn't break the page, and should be handles with a validation message.

**Context**
- Livewire version: latest
- Laravel version: latest

**Comment by danharrin** [comment]
Hey @mokhosh, please open a Discussions thread for this. Many thanks.

**Comment by mokhosh** [comment]
This is a bug, not a question to be discussed in a forum, right?
