### ISSUE TITLE
Customizing The Validation Attributes does not working using a public property.

### ISSUE THREAD

**Issue by NickJorens** [livewire/livewire#1812]
### Description
The method described in the Laravel documentation, [here](https://laravel.com/docs/8.x/validation#customizing-the-validation-attributes), does not work when using inside of a Livewire component.

### Exact steps to reproduce
Add a input field with name 'companystate'. 
Insert this into a Livewire component.
`   public function attributes()
    {
        return [
            'companystate' => 'state',
            'companyname' => 'company name',
        ];
    }`

It will not display the correcft name for the error message. 
Another method does work, but is much uglier.:

` public function updated($propertyName)
    {
        $this->validateOnly($propertyName,$this->rules,[],[
            'companystate' => 'state',
            'companyname' => 'company name',
        ]);
    }`

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.9
- Browser: All

**Comment by iksaku** [comment]
Custom Attribute names are not yet available.

On the upcoming 2.3.0 release you'll be able to specify a `customAttributes` function that will allow you to specify the attribute names for your validation strings 😉

**Comment by calebporzio** [comment]
Great call @NickJorens! Because of this point, I'm going to change the `customAttributes` to just `attributes` so this will work in the next version. (`2.3.0`)

Thanks!
