### ISSUE TITLE
Cannot read property 'fingerprint' of null - Cloudflare

### ISSUE THREAD

**Issue by tnylea** [livewire/livewire#1818]
### Description

Hey Caleb, hope you're doing well. I've checked out many of the other issues where users are experiencing this same issue and I think that I've gotten closer to resolving it.

I'm getting the error:

```
Cannot read property 'fingerprint' of null
```

This happens when Livewire tries to perform an XHR request to the server; however, it works totally fine on my local machine and it works fine if I turn off Cloudflare and only use Cloudflare as a DNS to my server.

I've also added:

```
protected $proxies = '*';
```

To my TrustProxy middleware, but I'm not having any luck.

You can see that everything seems to be working fine on my site at https://devdojo.com, but the moment I enable cloudflare, I will start getting these errors.

It's definitely a Proxy/Cloudflare issue with the fingerprint, but none of the other solutions seemed to work for me.

### Exact steps to reproduce

If you wanted to hit me up on twitter https://twitter.com/tnylea, I would be more than happy to enable cloudflare and let you see the error happening on production. I can also grant you access to my code repo if you would like.

Anyway, just wanted to open this up and see if you or anyone else has any more ideas for me to try.

Here is a quick screenshot of the exact error:

 
<img width="979" alt="Screen Shot 2020-10-14 at 7 35 51 PM" src="https://user-images.githubusercontent.com/601261/96071581-4fe0ac80-0e57-11eb-9d85-62c072ca9829.png">

Really appreciate any response, and I'm really loving Livewire.

Keep it up.

Talk to you soon.

**Context**
- Livewire version: [e.g. 2.2.9]
- Laravel version: [e.g. 7.28.4]
- Browser: Chrome

**Comment by theonly27** [comment]
Im also having the issue, any work around for this?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by acacha** [comment]
See https://github.com/livewire/livewire/issues/2465 about issues related to cloudflare cache an Livewire.
