### ISSUE TITLE
Keyed collection, using keyBy, loses keys on submit

### ISSUE THREAD

**Issue by notflip** [livewire/livewire#1819]
### Description

When I set a variable to a collection that uses keyBy, on a submit the keys are lost.

### Exact steps to reproduce

- in mount() set a variable to a keyed collection using `$this->allProducts = Product::all()->keyBy('id');`
- add a submit handler to a form using `<form wire:submit.prevent="submitForm">`
- dd() $this->allProducts in the submitForm() method
- it returns a collection without the keys

### Stripped-down, copy-pastable code snippets

```
public function mount()
{
    $this->allProducts = Product::all()->keyBy('id');
}

public function submit()
{
    dd($this->allProducts);
}

```

**Context**
- Livewire version: 1.3.5
- Laravel version: 6.18
- Browser: Irrelevant

**Comment by Jamesking56** [comment]
Just got this without the submit part, simply referring to the collection in the view shows the keys missing as well. I think it must be to do with how Collections are serialised in component data.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Jamesking56** [comment]
REOPEN

I can probably build at least a failing test for this, I'll add it to my list

**Comment by Jamesking56** [comment]
REOPEN

**Comment by Jamesking56** [comment]
>  Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: [twitter.com/calebporzio/status/1321864801295978497](https://twitter.com/calebporzio/status/1321864801295978497))

REOPEN

**Comment by glaesser** [comment]
> Just got this without the submit part, simply referring to the collection in the view shows the keys missing as well. I think it must be to do with how Collections are serialised in component data.

Just ran into this as well...seems like it's not possible to to use keyBy on a collection at all, as the keys are stripped in the view?

**Comment by glaesser** [comment]
@calebporzio would it be possible to address this in the next release?

FYI, this issue applies to latest Livewire version (2.3.1) and Laravel 8.

**Comment by austenc** [comment]
@notflip @Jamesking56 @glaesser 

Is this still happening for you folks on the latest version of Livewire (`2.3.6`)?
