### ISSUE TITLE
Data binding not working

### ISSUE THREAD

**Issue by vlcya** [livewire/livewire#1821]
### Description: 

- the 2 way data binding does not work, the value of the variable doesn't update.

### Exact steps to reproduce

- clean laravel installtaion

- livewire install

- livewire:make test

### Stripped-down, copy-pastable code snippets

- livewire/Test.php

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $text;

    public function render()
    {
        return view('livewire.test');
    }
}
```

- livewire/test.blade.php

```
<input type="text" wire:model="text">
{{$text}}

```
- welcome.blade.php
```

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <livewire:styles />
        <style>
            body {
                font-family: 'Nunito';
            }
        </style>
    </head>
    <body class="antialiased">
        <livewire:test/>
        <livewire:scripts />
    </body>
</html>
```

- Request Ppayload

```
{fingerprint: {id: "p2OSso56TqMjMT4XN4Oo", name: "test", locale: "en"},…}
   fingerprint: {id: "p2OSso56TqMjMT4XN4Oo", name: "test", locale: "en"}
      id: "p2OSso56TqMjMT4XN4Oo"
      locale: "en"
      name: "test"
   serverMemo: {children: [], errors: [], htmlHash: "b6eb143a", data: {text: "te"}, dataMeta: [],…}
      checksum: "1949b7cded0c349a39cb3f8d9d36a92bd88d5c3a1b676544851ddd229d157c4c"
      children: []
      data: {text: "te"}
         text: "te"
      dataMeta: []
      errors: []
      htmlHash: "b6eb143a"
   updates: [{type: "syncInput", payload: {name: "text", value: "test"}}]
      0: {type: "syncInput", payload: {name: "text", value: "test"}}
      payload: {name: "text", value: "test"}
         name: "text"
         value: "test"
         type: "syncInput"
```

**Context**
- Livewire version: 2.2
- Laravel version: 8.10
- Browser: [Edge, Chrome, Opera]

**Comment by vlcya** [comment]
livewire/Test.php

<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $text;

    public function render()
    {
        return view('livewire.test');
    }
}

**Comment by rbcunhadesign** [comment]
On your `livewire/test.blade.php` file you have to wrap your code into a `div`.

https://laravel-livewire.com/docs/2.x/rendering-components#returning-blade

**Comment by austenc** [comment]
Yep, @rbcunhadesign is correct here. 

This is the part from the link that applies:
![image](https://user-images.githubusercontent.com/575421/96146469-8ce28880-0ec3-11eb-8f65-a725e1bfa381.png)

**Comment by calebporzio** [comment]
Thanks for weighing in folks!

**Comment by JoelLauret** [comment]
I know this is a old, but in case u have a error with the data binding, try to update the php to 7.4
