### ISSUE TITLE
Vimeo error when trying to view screencasts

### ISSUE THREAD

**Issue by jeffchown** [livewire/livewire#1825]
Hello,

Not sure where else to post this...  I just started receiving Vimeo errors when trying to view the Livewire screencasts. Anyone having the same issue?

Jeff

**Comment by austenc** [comment]
@jeffchown any chance you could paste in the error message and/or a screenshot of the error?

Ping @jasonlbeggs 🙇

**Comment by jasonlbeggs** [comment]
Vimeo was having issues affecting other sites like Laracasts earlier today. @jeffchown can you try again to see if it's working now? I'm going to guess and say that was probably the issue.

**Comment by calebporzio** [comment]
Closing this. Thanks!
