### ISSUE TITLE
[2.3.0] @entangle cannot get a computed property (copy pastable)

### ISSUE THREAD

**Issue by basepack** [livewire/livewire#1827]
### Description
Having a component with a `getShowProperty() { return true; }` will not work if you try to entangle that.

### Exact steps to reproduce
Create component:
```php
class LivewireComponent extends Component
{
    public function getShowProperty(){
        return true; 
    }
}
```

Create view:
```blade
<div x-data="{ show: @entangle('show') }">
  
  <!-- this input should be shown, but is not -->
  <input 
    x-show="show"
    x-init="console.log(show)" {{-- no console output --}}
    type="text"><br>

  <div class="flex flex-col space-y-4">
    <div>alpine show output: <span x-text="show"></span></div> <!-- empty -->
    <div>wire show output: <span x-text="$wire.show"></span></div> <!-- some code printed-->
    <div>blade show output: {{ json_encode($this->show) }}</div> <!-- true -->
  </div>
</div>
```

### Stripped-down, copy-pastable code snippets
https://laravelplayground.com/#/snippets/1850e591-3c8d-4a3d-9906-026099601e94

**Context**
- Livewire version: 2.3.0
- Laravel version: latest
- Browser: Chrome

**Comment by calebporzio** [comment]
Unfortunately, entangle will not work with a computed property. Those are for backend only
