### ISSUE TITLE
php artisan livewire:publish --assets should not copy the config over

### ISSUE THREAD

**Issue by AdamKyle** [livewire/livewire#1831]
### Description

Running: `php artisan livewire:publish --assets` then generated:

```
Copied File [/vendor/livewire/livewire/config/livewire.php] To [/config/livewire.php]
Publishing complete.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
```

You just overwrote my config forcing me to set it up again - or in the future - make backups before publishing new assets after updates.

### Exact steps to reproduce

- Run: `php artisan livewire:publish --assets`
- See: 

```
Copied File [/vendor/livewire/livewire/config/livewire.php] To [/config/livewire.php]
Publishing complete.
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
```

- Should see:

```
Copied Directory [/vendor/livewire/livewire/dist] To [/public/vendor/livewire]
Publishing complete.
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [2.3.0]
- Laravel version: [8.10.0]
- Browser: N/A - **Command issue**.

**Comment by isaackearl** [comment]
when I run 
```
php artisan vendor:publish --force --tag=livewire:assets --ansi
```
It only publishes the assets (not the config).  Try that out.

**Comment by santiag0712** [comment]
Please, How to eliminate the pubished in the config file in livewire ?
