### ISSUE TITLE
Setting wire:model array value to empty string resets the entire array

### ISSUE THREAD

**Issue by rawilk** [livewire/livewire#1832]
There seems to be an issue with using wire:model on multi-dimensional arrays. If you set the value of one of the keys on the array to an empty string (""), it will set all of the keys to an empty string as well. For example, in an import component that is based off your import screencast from your datatable series:

In the component:

```php
public $fieldColumnMap = [
      'name' => '',
      'date' => '',
];

public $columns;

public function rules()
{
     return [
         'fieldColumnMap.name' => 'required',
     ];
}

public function import()
{
     dd($this->fieldColumnMap);

     // If an empty value is set to either key, it will return ['name' => '', 'date' => ''] no matter what.
}
```

In the view:

```html
<form ...>
      <select wire:model.defer="fieldColumnMap.name">
              <option value="">Not mapped</option>
              @foreach ($columns as $column)
                    <option>{{ $column }}</option>
              @endforeach
      </select>

      <select wire:model.defer="fieldColumnMap.date">
              <option value="">Not mapped</option>
              @foreach ($columns as $column)
                    <option>{{ $column }}</option>
              @endforeach
      </select>
</form>
```

It doesn't seem to matter if I use `wire:model`, or `wire:model.defer`, the end result is still the same if I select the "Not mapped" option for either field. Also, as a note, it seems to reset the entire component's state if I just use `wire:model` on either of the selects, which in turn clears out the uploaded file value and hides the modal. If I use defer, it just waits to do that until I call the import method.

Also, if I change that "Not mapped" option value to anything else, such as `<option value=" ">Not mapped</option>`, it works as expected; it just seems to have the issue with an empty string.

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.10.0
- Browser: Chrome

**Comment by rawilk** [comment]
Also may be worth noting that this didn't appear to be happening when I was using livewire v2.29.0.

**Comment by uteq** [comment]
Maybe adding a wire:key to both selects is worth a try. Also see the troubleshooting section of the documentation.

**Comment by rawilk** [comment]
@uteq I tried that but no luck. I even added a unique wire:key on each of the options on each select, but the same thing happened.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
