### ISSUE TITLE
Can't change html title dynamically

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1835]
I have this in the dafule layout: `layouts.app`'s head tag:
```html
<title>{{ $title ?? config('app.name', 'TITLE') }}</title>
```

And this in my Livewire component:
```html
<x-slot name="title">mywebsite | search | {{ Str::lower($scope) }}</x-slot>
```

But it doesn't change the title of the page when `scope` is updated.

**Context**
- Livewire version: latest
- Laravel version: latest
- Browser: Chrome

**Comment by isaackearl** [comment]
is $scope a public property?  Can you show your livewire component code?

**Comment by mokhosh** [comment]
I'm ok with pasting it here, but the whole thing is about 200 lines.
The relevant part is, yes, scope is a public property and you can change it by changing a select box on the page `wire:model`ed to `scope`.

**Comment by uteq** [comment]
Maybe this answers your question

https://github.com/livewire/livewire/issues/1756

Else make sure title is defined as a property for your layout/app or something like that. If you could elaborate on how you are using your layout exactly I can offer a more precise solution.

**Comment by mokhosh** [comment]
@uteq Thanks for your answer, did you see the first post? I'm using blade component syntax, and I have a `title` slot on my AppLayout component.

**Comment by uteq** [comment]
I saw your first post. Still there are several ways to use the app layout. If I am correct there is a LayoutApp class that should also have the title property for it to be recognised by the Blade Component View.

**Comment by uteq** [comment]
Just so I have all the details. How do you use your Livewire Component?
The layout for example, do you implement it like this:

```blase
<app-layout>
   <x-slot name="title">mywebsite | search | {{ Str::lower($scope) }}</x-slot>

   The rest of my Livewire Component.
</app-layout>
```

If not I would either advise you to use this approach: https://github.com/livewire/livewire/issues/1756

Or give it to your layout during render:

```php
class ShowPosts extends Component
{
    ...
    public function render()
    {
        return view('livewire.show-posts')
            ->layout('layouts.base', [
                    // this is how to pass params to the layout blade component
                    'title' => 'your title' 
            );
    }
}
```

Both approaches have their benefits and pitfalls.

**Comment by mokhosh** [comment]
I'm using the first one, except I'm not writing `<app-layout>` because that's handled by livewire itself i think.

**Comment by uteq** [comment]
Than  for as far as I know only this approach would work:

```php
class ShowPosts extends Component 
{ 
    ... 
    public function render() 
    {   
        return view('livewire.show-posts')
             ->layout('layouts.base', [ 
                  // this is how to pass params to the layout blade 
                  component 'title' => 'your title' 
             ]); 
    }
}
```

**Comment by mokhosh** [comment]
So you can't use slots to change it?

**Comment by uteq** [comment]
I do not know everything about Livewire there is to know.
That said. I believe Livewire does not actually use the Blade Component approach to extend/use the app layout. So you cannot use slot to push data to the layout. 

As a possible alternative. Although I am very certain this will not work, you could give ```@push()``` and ```@yield()``` a try. But I think that would only push the code once. So if you use a variable to change the title when the state of your component changes it will not detect that change.

Hope this makes some sense to you 😁

**Comment by ShekhSaifuddin007** [comment]
@mokhosh when you are using full page component, you just use `@section('title', 'your title')`. in your title tag `<title>@yield('title') ?? config('app.name', 'TITLE') }}</title>` and your component class use `->extends('layouts.app')` instead of `->layout('layouts.app')` and you are good to go.

```php
public function render()
{
    return view('livewire.show-posts')->extends('layouts.base');
}
```

**Comment by mokhosh** [comment]
Thanks, so not possible with component syntax at all, right?

**Comment by ShekhSaifuddin007** [comment]
@mokhosh yes..😊

**Comment by mokhosh** [comment]
I'm not sure why you closed this @danharrin shouldn't this be fixed?

**Comment by danharrin** [comment]
Hey @mokhosh, I don't believe this is a bug, pretty sure that this behaviour has just not been implemented in the way you suggested. At the moment, you should be able to pass parameters to the layout exactly as @uteq and @ShekhSaifuddin007 have mentioned, is there a case whereby this approach is not viable? Happy to reopen if I'm missing something 😁

**Comment by mokhosh** [comment]
Yes, I think the Laravel community is moving away from the old blade layout syntax towards the new component syntax, and I don't see why we shouldn't expect to have the same functionality with the new syntax.

**Comment by danharrin** [comment]
@mokhosh so the reason why we can't have layout slots updating within Livewire component views like you suggested (at the moment) is that Livewire is "bound" to the main slot in your layout component, not the entire compiled view. If the whole view was sent back each time, this would create an unnecessary performance overhead, and changing the way full-page components work behind the scenes could break component nesting as well. So, when `$scope` changes and the view is recompiled, only the main slot is sent back to the browser, thus the layout slot does not update.

I'd suggest one of two options...
- Mount the entire layout as an Alpine component, bind the title with `x-text`, and use `dispatchBrowserEvent()` to issue updates to the title.
- Refresh the page each time your layout needs to update (not ideal, but combined with Turbolinks could look pretty seamless).

Hope this helps!
