### ISSUE TITLE
Livewire throws out unpersisted Models.

### ISSUE THREAD

**Issue by Slowwie** [livewire/livewire#1842]
When you create a collection of Models: 

`public $subject;`

```
public function mount()
{
    $this->subject = Subject::where('id', $this->card->subject_id)->get();
}
```

Then you can add new models to it inside an Action:
```
$subject = Subject::where('uuid', $tag['uuid'])
   ->where('language', app()->getLocale())
   ->first();
```

That works perfectly fine. **BUT** this only works with persisted data. 
In the moment I don't want to save the new category immediately into the database it has **no id** and that messes things up. - Livewire throws out this unpersisted Models on next interaction.

So this won't work:
```
 // if not found create it
  if (!$subject) {

     $subject = Subject::make([
         'uuid' => Str::uuid()->toString(),
          'language' => app()->getLocale(),
          'created_by_id' => auth()->user()->id,
          'name' => $tag['name']
      ]);

    }
```
As you can see here - the models get referenced by id. And for new ones (not persisted ones) there is no id. 
![GFxW1kEQ](https://user-images.githubusercontent.com/4937572/96403325-629d0d80-11d8-11eb-9235-a7b13faf7562.png)

So, I guess it's a pretty common thing to save models on submit (not on when model is created).
Maybe it could be usefull to have any kind of handler for setting the id property. (In my case any Subject has an uuid).

**Context**
- Livewire version: [e.g. 2.2.9]
- Laravel version: [e.g. 8.8.0]

**Comment by danharrin** [comment]
Hi, I'm afraid that this is intended behaviour, as Livewire is stateless, so relies on the database to hydrate model state in this case. I'd recommend using an array to store this data temporarily before you write it to your database. If you have any further questions, please open a Discussions thread or visit the Discord server. Many thanks!
