### ISSUE TITLE
Rules property requires foreign key validation.

### ISSUE THREAD

**Issue by zyxxyzyxz** [livewire/livewire#1843]
### Description
When directly binding to a model's properties, if a foreign key is set inside the mount function, it will not be persisted unless you have included the foreign key inside the `$rules` array. The below example will not work, but as soon as you add `'model.model_id' => 'required'`, it will work. This is regardless of whether or not the property is fillable on the model. So even if `model_id` is inside fillable on the model, it still wont be persisted. I suspect this is because `$this->validate()` is disposing of the foreign keys because they are not included in the validation rules.

This is pretty annoying and can really junk up your code, especially if you are working on a form that works with 10-20+ relationships because that would result in;
```php
    protected $rules = [
        'model.model_id' => 'required',
        'model.model1_id' => 'required',
        'model.model2_id' => 'required',
        'model.model3_id' => 'required',
        'model.model4_id' => 'required',
        ...
        'model.model100_id' => 'required',
        etc...
    ];
```

Not sure if this is a bug or intended, but I understand there are probably some security concerns to take into account with this.

### Stripped-down, copy-pastable code snippets
```php
class Create extends Component
{
    public Model $model;

    protected $rules = [
        'model.title' => 'required',
    ];

    public function mount()
    {
        $this->model = Auth::user()->models()->make();
    }

    public function submit()
    {
        $this->validate();

        $this->model->save();

        return $this->redirectRoute('index');
    }
}
```
**Context**
- Livewire version: 2.3.0
- Laravel version: 8.10
- Browser: Chrome

**Comment by danharrin** [comment]
This is not intended behaviour, the `$rules` array is used to restrict which model properties can be updated from the frontend, and should not affect mounting behaviour. Please post a link to a Laravel Playground so that we can more easily reproduce your issue. Many thanks!

**Comment by zyxxyzyxz** [comment]
Hey @danharrin 
Sorry for the late reply I'm super busy on some projects at the moment.

I did actually manage to find some time to replicate this inside the sponsor Surge codebase since I didn't have time to throw my own together. I tried getting in contact via Discord to figure out how I should get that code to you since it's a non-public repo. 

If you can let me know how I can share that code to you without making it public, I can get that to you ASAP so you can see the issue. 😅

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by zyxxyzyxz** [comment]
REOPEN

**Comment by calebporzio** [comment]
This makes sense. Model data is not persisted between Livewire requests unless it is either:

A) Persisted in the database
B) Has a validation rule key

This is the reason for your issue.

My first recommendation is to store a the foreign model as a property and then set it's relationship after validation when you save the model.

Otherwise, you will be exposing the forign_key to front-end and making it modifiable by users. Which is OK as long as you authorize the foreign key before storing it.

I can see how this seems like a bug for you, but it's actually a feature given the way Livewire works - the current set up helps people understand that persisting model data on the front-end is vulnerable to users changing data and you MUST validate/authorize anything before persisting just like you would in a controller.

Anyhow, closing this. Thank you.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
