### ISSUE TITLE
Query string not updated when using $set

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#1844]
When I use `$set` in `wire:click` the query string is not updated. I've specified the property to update the query string when this property changes and it isn't working.

Is there a workaround?

**Comment by uteq** [comment]
@redbastie can you provide some code to easily reproduce this?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
