### ISSUE TITLE
Snake case naming convention

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#185]
**Describe the bug**
Consider below Livewire component and view:

```
php artisan make:livewire text_replace
```
This will create two files:

```
-> [TextReplace.php]
-> [text_replace.blade.php]
```

When trying to render the view file:
```
@livewire('text_replace')
```

It will result in an error:

> Unable to find component: [text_replace]

However, if I change the view name to follow the kebab naming convention like: `text-replace.blade.php`

Then the view can load just fine, without error.

**Expected behavior**
I am following the snake convention when naming my blade views and would like to follow the same convention for my Livewire views as well.

**Comment by calebporzio** [comment]
Would love a PR for this - it shouldn't be too hard.

**Comment by oliverbj** [comment]
Will take a look at this!
