### ISSUE TITLE
Broken out of the box using jetstream

### ISSUE THREAD

**Issue by Bjern** [livewire/livewire#1854]
### Description
Using laravel jetstream following the directions exactly on a brand new clean project one cannot build a working livewire component.   Unless something is missing from the docs.

### Exact steps to reproduce
`composer create-project --prefer-dist laravel/laravel gravity`
`cd gravity`
`composer require laravel/jetstream`
`php artisan jetstream:install livewire`
`npm install && npm run dev`

Create or copy in a migration for use.  In my case a simple contacts migration.

```php
class CreateContactsTable extends Migration
{
    public function up()
	{
		Schema::create('contacts', function(Blueprint $table)
		{
			$table->increments('id');
			$table->string('title')->nullable();
			$table->string('first_name')->nullable();
			$table->string('last_name')->nullable();
            $table->string('company')->nullable();
            $table->string('position')->nullable();
            $table->decimal('travel_rate', 9, 2)->default(0);
            $table->decimal('travel_hourly_rate', 9, 2)->default(0);
            $table->timestamps();
            $table->softDeletes();
		});
	}
```

Then run the migrations.
`php artisan migrate`

I serve up the website using xampp.  Go to register and register a new user.  Login as new user.  Laravel works no problem as expected with new laravel 8 dashboard.  All Laravel routes work without hitch.

Next create a livewire component as per docs.
`php artisan make:livewire contacts`
The 2 files are created as expected.

Add a simple route for testing component.  routes -> web.php
`Route::get('contacts', Contacts::class);` uses `use App\Http\Livewire\Contacts;`

untouched Contacts component reads...
```php
class Contacts extends Component
{
    public function render()
    {
        return view('livewire.contacts');
    }
}
```

Contacts blade content:
```html
<div>
    <h3>Contacts</h3>
</div>
```

Hit that route /contacts and the error occurs.
`Undefined variable: header (View: F:\xampp_73\htdocs\gravity\resources\views\layouts\app.blade.php)`

This is the standard laravel 8 template. The problem...
```html
<header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
```

This only fails on livewire components.  Others are experiencing this too. 
[https://stackoverflow.com/questions/64045010/laravel-8-and-tailwindcss-undefined-variable-header](url)

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: ^2.0
- Laravel version: 8.11.0
- Browser: Chrome

**Comment by uteq** [comment]
This is probably not exactly Livewire related, because the reason this error is thrown is because of the way Jetstream setup the AppLayout.

You can fix this by doing the following, change your Contacts component render to:
```php
public function render()
{
    return view('livewire.contacts')
        ->layout('layouts.app', ['header' => 'The title of your page']);
}
```

**Comment by danharrin** [comment]
Thanks @uteq! Any more issues, please open a discussion thread.

**Comment by Bjern** [comment]
Thanks, I will try this out in the morning.  While this may work I'm still not satisfied with the answer for reasons... 

1.  If you're building a package how would you know what variables have been set in the developers layouts blade?

2.  Not mentioned in my example but I originally used the same slot name="header" in the blade that laravel uses but that didn't work either, which is why I restarted the project and followed the instructions line by line.  This means that the variable must always be included in the render as @uteq suggests?  it works on the other blades (not livewire) as a slot name="header".

3.  This works if I am the developer of a project and know that layouts.app is the name of the blade file and that it hasn't been changed.

4.  If the variable name changes from header to something else one has to go through every livewire component written to change it.

Need to give this some thought.

**Comment by devcircus** [comment]
Although this is something that probably should be changed, it is unrelated to the livewire repository itself. This is due to the way the app.blade.php layout is designed in Jetstream. The issue should be brough up there. I fixed this in my app by updating the layout file to check for the existence of the $header before attempting to utilize it.
