### ISSUE TITLE
select tags with more than 16 elements and strings as keys render shuffled

### ISSUE THREAD

**Issue by bzarzuela** [livewire/livewire#1858]
### Description
So I have an array that serves as a list of choices for a `<select>`. The keys are strings and the values are strings. If the number of choices is 16 and below, no issues at all. But as soon as I use more than 16 choices, the <option> values are shuffled on initial render and in every update.

### Exact steps to reproduce
Create a component with this code below and try to view it in the browser. You'll see all the options are shuffled and when you select a different option, the options are shuffled again.

### Stripped-down, copy-pastable code snippets
```blade
<div>
    <select name="provinces" id="provinces" wire:model="choice">
        @foreach ($choices as $key => $value)
            <option value="{{ $key }}">{{ $key }}: {{ $value }}</option>
        @endforeach
    </select>

    <div>Choice: {{ $choice }}</div>
</div>

```

```php
class Provinces extends Component
{
    public $choices;

    public $choice;

    public function mount()
    {
        $this->choices = [
            'a' => 'A',
            'b' => 'B',
            'c' => 'C',
            'd' => 'D',
            'e' => 'E',
            'f' => 'F',
            'g' => 'G',
            'h' => 'H',
            'i' => 'I',
            'j' => 'J', // 10
            'k' => 'K',
            'l' => 'L',
            'm' => 'M',
            'n' => 'N',
            'o' => 'O', // 15
            'p' => 'P',
            'q' => 'Q',
        ];

        $this->choice = 'c';
    }

    public function render()
    {
        return view('livewire.provinces');
    }
}
```

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Browser: Chrome

**Comment by danharrin** [comment]
Wow... great catch. I'll investigate further now.

**Comment by danharrin** [comment]
After a long investigation, I've reduced this down to **incredibly** odd behaviour from PHP itself, not Livewire. It's the `uksort()` function, used in `NormalizeDataForJavaScript`.

Arrays with more than 16 items are not passed to `uksort()` in the correct order. Check this behaviour in [Laravel Playground](https://laravelplayground.com/#/snippets/42551d50-cf83-42f3-a8c1-0cece947d353).

**Comment by bzarzuela** [comment]
Thanks! I'll try and implement an alternative without using uksort

**Comment by alan614** [comment]
Hi,

I've taken a look at this an noticed something in the NormalizeDataForJavaScript abstract.

In this block

`uksort($normalizedData, function ($a, $b) {
            if (is_numeric($a) && is_numeric($b)) return $a > $b;

            if (! is_numeric($a) && ! is_numeric($b)) return 0;

            if (! is_numeric($a)) return 1;
        });`

if you change

` if (! is_numeric($a) && ! is_numeric($b)) return 0;`

to 

`if (! is_numeric($a) && ! is_numeric($b)) return strcasecmp($a, $b);`

it appears to behave much better

**Comment by danharrin** [comment]
@alan614 unfortunately that's not viable, the original array order needs to be preserved here, else we'd just use `ksort()`.

**Comment by danharrin** [comment]
@bzarzuela just opened #1859, which fixes this issue 👍
