### ISSUE TITLE
Issue with Trait Lifecycle Hooks

### ISSUE THREAD

**Issue by colinhall17** [livewire/livewire#1860]
When applying multiple traits to a Livewire Component the mount lifecycle hooks will only run on the last trait with a lifecycle hook in the 'use' list.

Create a component and multiple traits and add to the use statement of the component.  Within the traits add the MountTraitName function.

When the component is mounted only the last declared trait will run the mountTratName lifecycle hook.

**Case 1**

```
class Resource extends Component

    use WithSort, WithSearch;

trait WithSort

    public function mountWithSort(){
          // Do Something
    }

trait WithSearch

    public function mountWithSearch(){
          // Do Something
    }
```

In the above only mountWithSearch will get called.  mountWithSort is not called.

**Case 2**

```
class Resource extends Component

    use WithSearch, WithSort;

trait WithSort

    public function mountWithSort(){
          // Do Something
    }

trait WithSearch

    public function mountWithSearch(){
          // Do Something
    }
```

In the above only mountWithSort will get called.  mountWithSearch is not called.

Livewire Version 2.3.0
Laravel Version 8.11.2

**Comment by austenc** [comment]
Thanks for reporting this @colinhall17 -- it does seem like multiple traits should be supported. I'll take a look at this today.
