### ISSUE TITLE
assertHasErrors not working on the latest V1 version

### ISSUE THREAD

**Issue by nnerijuss** [livewire/livewire#1879]
assertHasErrors validation test not working on the latest V1 version.

### Exact steps to reproduce
- Create component
- Add validation component method
- Create test that should not pass validation
- test validation with arrertHasError()
- result: Component has no errors. Failed asserting that false is true.

If it helps i am using custom captcha validator:

```php
     Validator::make(
           [
                'captcha' => $captchaToken
            ],
            [
                'captcha' => 'required|recaptcha',
            ],
            [
                'captcha.recaptcha' => 'You have not passed recaptcha test.'
            ]
        )->validate();
```

Until today, when i upgraded Laravel 7 to latest 7 version and livewire to latest v1 version, everything works just fine.

**Versions**
- Livewire version: v1.3.5
- Laravel version: 7.28.4
- PHP 7.4

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
