### ISSUE TITLE
$validationAttributes not working?

### ISSUE THREAD

**Issue by dominiced** [livewire/livewire#1887]
### Description
I'm trying to use $validationAttributes to improve attribute names when binding to model properties in a form, because otherwise it has ugly errors such as "The user.name field is required". However, it didn't work. I suspected maybe it's because I opted to use a rules() method rather than a $rules property, since I need to create the rules based on the currently selected model. I also thought perhaps it was struggling because it couldn't recognise "user.name", since there's no $user.name property, just a $user property in the component. So, I created a little test snippet, but it still didn't work!

### Exact steps to reproduce
Create a model, use the snippet below, try to get validationAttributes working.

### Stripped-down, copy-pastable code snippets
```
protected $validationAttributes = [
        'test' => 'Test Property',
    ];

    protected $rules = [
        'test' => 'required',
    ];
```

**Context**
- Livewire version: 2.2.5
- Laravel version: 8
- Alpine version: 
- Browser: Chrome

**Comment by austenc** [comment]
@dominiced the `validationAttributes` stuff wasn't added until Livewire version `2.3.0`.
