### ISSUE TITLE
nextPage and previousPage method exceed page range

### ISSUE THREAD

**Issue by michele-grifa** [livewire/livewire#1889]
### Description
I'm using Livewire Pagination, and in my pagination component i use `wire:click="nextPage"` and `wire:click="previousPage"` to navigate the pages. 
If i rapidly click the pagination links before the component refresh, the method exceed upper and bottom limit, for example:

- I click rapidly previous page link and in my url i see "**page=-1**", loading no items, and the same happen for the upper bound

In the blade component i always check for `$paginator->onFirstPage()` and `$paginator->hasMorePages()`, but the click happen so quickly and the view not refresh in time.

### Exact steps to reproduce
Rapidly call nextPage and previousPage in a pagination component

### Stripped-down, copy-pastable code snippets
```
<div class="ui pagination menu">
                @if(!$paginator->onFirstPage())
                    <div wire:click="gotoPage(1)" class="link item"> << </div>
                    <div wire:click="previousPage" class="link item"> < </div>
                @endif

                {{-- Pagination Elements --}}
                @foreach ($elements as $element)
                    {{-- "Three Dots" Separator --}}
                    @if (is_string($element))
                        <div class="disabled item"> ... </div>
                    @endif

                    {{-- Array Of Links --}}
                    @if (is_array($element))
                        @foreach ($element as $page => $url)
                            @if ($page == $paginator->currentPage())
                                <div class="active link item"><span style="font-weight:bold"> {{ $page }} </span></div>
                            @else
                                <div wire:click="gotoPage({{ $page }})" class="link item"> {{ $page }} </div>
                            @endif
                        @endforeach
                    @endif
                @endforeach

                @if($paginator->hasMorePages())
                    <div wire:click="nextPage" class="link item"> > </div>
                    <div wire:click="gotoPage({{ $paginator->lastPage() }})" class="link item"> >> </div>
                @endif
            </div>
```

**Context**
- Livewire version: 2.2.9
- Laravel version: 8.10.0
- Alpine version: 2.3.0
- Browser: Firefox

**Comment by austenc** [comment]
Thanks for reporting this @michele-grifa! 

I was able to replicate it by turning down the connection speed to "Slow 3G" in the Network tab of devtools, then clicking furiously. I'll make sure this gets fixed.

**Comment by michele-grifa** [comment]
> 
> 
> Thanks for reporting this @michele-grifa!
> 
> I was able to replicate it by turning down the connection speed to "Slow 3G" in the Network tab of devtools, then clicking furiously. I'll make sure this gets fixed.

Thanks
