### ISSUE TITLE
Select2 problem with wire:ignore derective

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [livewire/livewire#1890]
### Description
For easy work and make users happy, we have to use select2 library but there is a problem and I searched a lot but don't find a solution when we use `wire:ignore` the select2 options are not refreshing at all in my case I want to create `Category` when I create category I want to refresh my dropdown at the bottom of the form I have an example in [**Laravel playground**](https://laravelplayground.com/#/snippets/c3de2547-081f-4ed7-afae-bf47e03b1d45) here you can see when I create a category it not refresh my select2 dropdown if I do not use the `wire:ignore` it refreshes but I lose the select2 functionality how can I force to refresh that select2 options? if I want that category what I just created, I have to reload the page to get that category.

1. Another problem is when I go edit it not selected whatever the `parent_id` in the select option.
2. It does not show the validation error also.

I also tried [**this comment**](https://github.com/livewire/livewire/issues/883#issuecomment-620181049) but nothing happens. 😒

@calebporzio have any suggestions on this.?

#### Exact steps to reproduce

- Need to refresh when we use `wire:ignore`.

#### Stripped-down, copy-pastable code snippets

```html
<div class="col-12 mt-2">
   <h6 class="mb-2">Add as a sub category of</h6>
   <div class="form-group">
      <select class="select2 form-control" id="parentId">
      <option selected value="null">Select parent</option>
       @foreach ($dropdownCategories as $category)
          <option value="{{ $category->id }}">{{ $category->name }}</option>
       @endforeach
    </select>
    <x-jet-input-error for="parent_id" />
   </div>
</div>

@push('scripts')
   <script>
     $(document).ready(function () {
          $(document).on('change', '#parentId', function (e) {
               @this.set('parent_id', e.target.value)
           });
      });

      document.addEventListener('livewire:load', function (event) {
         @this.on('openModal', function () {
             $('#modal').modal('show');
          });

         @this.on('closeModal', function () {
              $('#modal').modal('hide');
          });
      })
  </script>
@endpush
```

**Context**
- Livewire version: 2.x
- Laravel version: 8.x
- Browser: all

**Comment by ShekhSaifuddin007** [comment]
When the category created I fired an `event` to refresh the dropdown without `wire:ignore` it works but when change options it back to normal `select` 😒 I can't anything with it please somebody help


### component

```php
public function store()
{
   $this->validate();

   Category::create([
      'name' => $this->name,
      'description' => $this->description,
      'parent_id' => $this->parent_id
   ]);

   $this->emit('refreshDropdown');

   session()->flash('message', 'Category create successfully.');

   $this->clearForm();
}
```

### Blade

```blade
@push('scripts')
   <script>
       $(document).ready(function () {
          $(document).on('change', '#parentId', function (e) {
              @this.set('parent_id', e.target.value);
           });
       });

       document.addEventListener('livewire:load', function (event) {
          @this.on('refreshDropdown', function () {
              $('.select2').select2();
          });
     })
   </script>
@endpush
```

**Comment by joshhanley** [comment]
This isn't an issue with Livewire. Select2 loads up the options and adds elements into the dom below the select box, hence why you need the wire:ignore. 

As such, livewire won't touch any of the options after the first render. But even if it did, select2 won't pick up the changes as it has the options loaded into javascript.

You will need to use javascript to override the existing options with new ones. Maybe do this as part of the modal open event listener. 

Have a [look here](https://stackoverflow.com/questions/33626690/replacing-select2-options/33629425) for how to replace options using javascript.

Hope this helps!

**Comment by ShekhSaifuddin007** [comment]
@joshhanley I just refresh my dropdown when I create Category, I don't want to close the modal every time I create a category, but `wire:ignore` block every event whatever fire. 😢

**Comment by uteq** [comment]
I've got this working on several of my projects. I am currently not able to provide examples so I leave this comment to remind myself to provide this somewhere tomorrow 😀

**Comment by ShekhSaifuddin007** [comment]
@uteq great if share the idea it would help me and others.

**Comment by joshhanley** [comment]
I have got it working for you, check this out https://laravelplayground.com/#/snippets/aeab070a-a385-4b90-ac5b-81ba57f45ddb

The problem is accessing collections from javascript isn't working properly, so it's easier to convert the collection to array and save that to a public property that you can then access from @this.propertyArray

Hope this helps!

**Comment by ShekhSaifuddin007** [comment]
@joshhanley wow, it's working like charm, I gona closed this issue, I have one request to brother when I edit the category the `parent_id` not selected in the select box, suppose I create ***category1*** then I create ***category2*** and I give this ***category1*** as a parent when I go to edit ***category2***, ***category1*** should be selected but it's not

**Comment by joshhanley** [comment]
No worries! You will need to populate it when you show your modal. Add something like this

```js
$('.select2').val(@this.parent_id).trigger('change');
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by molnarjg** [comment]
> I have got it working for you, check this out https://laravelplayground.com/#/snippets/aeab070a-a385-4b90-ac5b-81ba57f45ddb
> 
> The problem is accessing collections from javascript isn't working properly, so it's easier to convert the collection to array and save that to a public property that you can then access from @this.propertyArray
> 
> Hope this helps!

Could you please paste the code here? Cheers

**Comment by nathanjansen** [comment]
I have found another approach that uses slightly less javascript. The reason I found this solution was because I had to work with more than one select box and they where also depending on each other.

https://user-images.githubusercontent.com/73473323/108538710-61dbcb80-72df-11eb-8f4c-e954b2bfb6d6.mov

It is a combination between the answer of @joshhanley and this Snapey's answer at: https://laracasts.com/discuss/channels/code-review/livewire-force-a-re-render-for-a-div-with-wireignore.

This is what I did (this is a very simplified and not complete version, for specifics, feel free to ask):

```blade
<div>
    <select style="width: 100%" wire:ignore>
        @foreach ($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endforeach
    </select>
</div>

<div wire:key="select-field-subcategories-version-{{ $subcategoriesVersion }}">
    <select style="width: 100%" wire:ignore>
        @foreach ($subcategories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endforeach
    </select>
</div>

<script>
// Listen to changes of select2 and push them to Livewire
//  The wire:key makes sure the select will be re-generated completely when the parent category is changed.
</script>
```

This is all you have to do in your php. 
This makes sure that whenever another 'parent' category is selected, the subcategory gets refreshed.
```php
$subcategoriesVersion = $category->id;
```

**Comment by joshhanley** [comment]
@nathanjansen nice! You could simplify it even more, instead of using a specific subcategory property, just output the category ID in the key instead (I've reordered it and change the name a bit so it's more readable.
```html
<div wire:key="select-field-category-{{ $category->id ?? 'none' }}-subcategories">
```

**Comment by nathanjansen** [comment]
> ```
> <div wire:key="select-field-category-{{ $category->id ?? 'none' }}-subcategories">
> ```

Love it!

**Comment by leviroberto** [comment]
En una ocasion que tuve que usar un select2 tuve que aplicar estas lineas script y mantener hidratado ese select2 y no usaba wire:ignore para nada
en el blade

<select class="form-control col-sm-6" id="selectCompany">   
 //do your stuff here
</select>

<script>

        $(document).ready(function() {
            window.initSelectCompanyDrop=()=>{
                $('#selectCompany').select2({
                    placeholder: '{{ __('locale.Select a Company') }}',
                    allowClear: true});
            }
            initSelectCompanyDrop();
            $('#selectCompany').on('change', function (e) {
                livewire.emit('selectedCompanyItem', e.target.value)
            });
            window.livewire.on('select2',()=>{
                initSelectCompanyDrop();
            });

        });

    </script>


en el componente

protected $listeners = [
        'selectedCompanyItem',
    ];
public function hydrate()
    {
        $this->emit('select2');
    }
public function selectedCompanyItem($item)
    {
        if ($item) {
           //do the other stuff here
        }
            
    }


dime si entiendes esto y pruebalo

**Comment by leviroberto** [comment]
En una ocasion que tuve que usar un select2 tuve que aplicar estas lineas script y mantener hidratado ese select2 y no usaba wire:ignore para nada
en el blade

<select class="form-control col-sm-6" id="selectCompany">   
 //do your stuff here
</select>

<script>

        $(document).ready(function() {
            window.initSelectCompanyDrop=()=>{
                $('#selectCompany').select2({
                    placeholder: '{{ __('locale.Select a Company') }}',
                    allowClear: true});
            }
            initSelectCompanyDrop();
            $('#selectCompany').on('change', function (e) {
                livewire.emit('selectedCompanyItem', e.target.value)
            });
            window.livewire.on('select2',()=>{
                initSelectCompanyDrop();
            });

        });

    </script>

en el componente

protected $listeners = [
        'selectedCompanyItem',
    ];
public function hydrate()
    {
        $this->emit('select2');
    }
public function selectedCompanyItem($item)
    {
        if ($item) {
           //do the other stuff here
        }
            
    }

dime si entiendes esto y pruebalo

**Comment by ArifulSikder** [comment]
@ShekhSaifuddin007 
Same problem with me, Can you solved your problem? If yes please help me!

**Comment by niyozbek** [comment]
Guys, try not to use <form> tag. It interfered with my wire:ignore. I solved the issue by replacing form tag with div tag. And if you have a submit button use wire:click="save".
