### ISSUE TITLE
Livewire modals are closing abruptly on dismiss

### ISSUE THREAD

**Issue by adddz** [livewire/livewire#1891]
Livewire Version: 2.3.0
Laravel Version: 8.11.2
PHP Version: 7.4.6

**Description:**

When dismissing a modal by pressing the Cancel button (or the Save action), the modal is abruptly dismissed without respecting the animation. It should behave the same as when the modal is dismissed for a background click.

**Steps To Reproduce:**
I slowed down the connection to show the issue.

https://www.loom.com/share/ac244139980848b087ce83a26406ef22

Issue on Jetstream repo: https://github.com/laravel/jetstream/issues/384

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
