### ISSUE TITLE
@entangle not syncing correctly.

### ISSUE THREAD

**Issue by joshhanley** [livewire/livewire#1893]
### Description

When you have an array that is @entangled with livewire and an input field that is also @entangled. 

Changes in the input are synced back to livewire, which filters down the array, which should sync it back to alpine but it doesn't.

### Exact steps to reproduce

I have created a demo repo here: https://github.com/joshhanley/EntangleArrayBug

1. Pull down the repo
2. Composer install
3. Open browser and go to site, its in the base route

I have just replaced the contents of welcome.blade.php and added a Livewire component called ListTest

**Screenshot**

![EntangleArrayBug](https://user-images.githubusercontent.com/882837/97065547-e2244580-15f9-11eb-9eae-241289af4888.gif)

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Alpine version: 2.x.x (from CDN, so I think 2.7.1)
- Browser: Chrome

**Comment by vladrusu** [comment]
+1
I also run into this bug. I don't think it is array-specific, but I think that @entagle is somewhere broken. Consider this code:
`<div x-data="{ open: @entangle('showDropdown') }">
	<p>Dropdown: {{ (int)$showDropdown }}</p>
	<input class="selection form-control" type="text"
	    	x-on:keydown.arrow-down.prevent="open = true"
	    	x-on:keydown.arrow-up.prevent="open = false"
	/>
</div>
<div class="ac-dropdown" x-show.transition="open" x-on:click.away="open = false">
... dropdown contents ...
</div>
`
No matter if you press arrow up or down, $showDropdown will stay false. I expected "Dropdown" to show 0/1 when pressing arrow up/down.

**Comment by joshhanley** [comment]
I have tested this with 2.3.1 and the issue is still happening. I have rebased my PR #1894  to pull in the new changes

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
REOPEN

**Comment by calebporzio** [comment]
The original issue has been fixed in #1894 

If other issues discussed here still persist (on the master branch for now as I haven't tagged a new version yet), please re-submit them as separate issues with their own full descriptions and such.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
