### ISSUE TITLE
Using Vue components, not viewable in Vue Devtools

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#190]
**Describe the bug**
If I include a Vue component inside a nested Livewire view file, like:

```html
<!-- livewire/example.blade.php -->
@livewire('another-example')
```

And then inside the nested view:

```html
<!-- livewire/another-example.blade.php -->
<text-replace></text-replace>
```

The Vue devtools only show the `root` component:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/fYrlq.png

If I place the Vue component `<text-replace></text-replace>` in the first Livewire view, it shows up in the Devtools.

I would love to assist with this problem - I have tried checking the code, but I am not quite sure what is causing this to only happen in a nested view.

**Additional Context:**
In my `app.js` file, this is how I declare Vue:

```javascript
require('./bootstrap');
window.Vue = require('vue');
```

**Comment by oliverbj** [comment]
> Does the component in the nested view work fine? (like if it has functionality is it working?)
Yes the Vue component still work, even though it is not visible in Vue DevTools.

**Comment by yashiroiori** [comment]
Hi.
Goo joob.
I have a vue component into a livewire component to show list of registers
![image](https://user-images.githubusercontent.com/17031855/67544055-96268400-f6b9-11e9-909a-4d692b40d90d.png)

But its not render
![image](https://user-images.githubusercontent.com/17031855/67544079-b1918f00-f6b9-11e9-8c40-4f1b3db8869d.png)

Into devtools not appear <root>
![image](https://user-images.githubusercontent.com/17031855/67544152-f3223a00-f6b9-11e9-9c19-a3caefb77aad.png)


This is my app.js
![image](https://user-images.githubusercontent.com/17031855/67544087-bbb38d80-f6b9-11e9-91f9-6e95f8500996.png)


And in app.blade.php
![image](https://user-images.githubusercontent.com/17031855/67544113-d554d500-f6b9-11e9-905a-836e5bf0d282.png)

what is the correct way to initialize vue??

Thanks.

**Comment by lancepioch** [comment]
@calebporzio 

oliverbj he says the component is working even though it doesn't show up in the Vue Chrome extension. Could possibly be a bug with either side.

yashiroiori seems to have a separate question/issue where the vue component itself isn't working, but this might be due to an incorrect (Vue) project setup.

**Comment by calebporzio** [comment]
Vue support has been moved to the following third-party package: https://github.com/livewire/vue

Please re-open this issue there if it's still an issue.

Thanks!
