### ISSUE TITLE
Select input with model binding has readonly attribute applied

### ISSUE THREAD

**Issue by dniccum** [livewire/livewire#1906]
### Description

Select input that is utilizing model binding is automatically having readonly attribute applied to it, even though no loading state or other attributes have been applied.

### Exact steps to reproduce

1. Utilizing the [Laravel Enum](https://github.com/BenSampo/laravel-enum) package, the 4 properties that are to be modified use an enumeration type casting/validation
2. Create a Livewire component with a form within it and then place a select input like the one below.
3. Add the component as a full page component
4. Setup model binding for the form, again like below. I have tested this on both a create form (with an empty eloquent object) and an existing model instance with the same results.
5. The result is that the form will render on the page with the select inputs greyed out. This **ONLY** happens to the select inputs.

*Note: Not sure if it matters, but this is within a tailwind pop over that slides over the page.*

#### Template

```blade
<form wire:submit.prevent="updateProductType">

<x-jet-label for="location_indoors">Indoors</x-jet-label>
<select id="location_indoors"
    class="form-control form-control-select form-select"
    wire:model.lazy="productType.location_indoors"
>
    @foreach(\App\Enums\LocationPreference::asSelectArray() as $value => $option)
        <option value="{{ $value }}">{{ $option }}</option>
    @endforeach
</select>

</form>
```

#### Component

```php
/**
 * @var ProductType|null
 */
public ProductType $productType;

protected $rules = [
    'productType.name' => 'required|string|min:6',
    'productType.active' => 'boolean',
    'productType.description' => 'string|nullable|max:500',
    'productType.location_indoors' => 'required|string',
    'productType.location_indoors_buried' => 'required|string',
    'productType.location_outdoors' => 'required|string',
    'productType.location_outdoors_buried' => 'required|string',
];

/**
 * @param array|string[] $payload
 */
public function showEdit(array $payload)
{
    $this->fill([
        'productType' => ProductType::find($payload['id']),
        'availableProducts' => ProductType::where('id', '<>', $payload['id'])
            ->select(['id', 'name', 'key'])
            ->get()
    ]);
    $this->mode = 'edit';
    $this->show = true;
}

public function updateProductType()
{
    $this->productType->save();
    $this->show = false;
}
```

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Alpine version: 2.7.0
- Browser: Chrome

**Comment by dniccum** [comment]
User error.

**Comment by slakbal** [comment]
Hi I'm getting this also. As soon as I have readonly="readonly" or disabled="disabled" on a select then it adds that input's as a property to a model. E.g. on an update form when the method that the form is calling is making use of route model binding that property is also added to the model, which then sits in the update sql and then causes an error. What was your solution here?
