### ISSUE TITLE
Internet Explorer 11 error Object.entries()

### ISSUE THREAD

**Issue by theChaosCoder** [livewire/livewire#1910]
### Description
Simple click event triggers error in ie11. Works in other browsers.

### Exact steps to reproduce
on button click

### Stripped-down, copy-pastable code snippets

`<button wire:click="setDate('2020-11-03 23:04:00')">setdate</button>`

in livewire "controller"
```
public function setDate($date)
{
        $this->date_register = Carbon::parse($date);
}
```

**Context**
- Livewire version: [2.3.0] 
- Laravel version: [ 8.11.2]
- Browser: [ie11]

**ie11 complains with SCRIPT438: Object doesn't support property or method  "entries" in index.js (204,9)**

See Object.entries()
```
   fireMessage() {
        if (this.messageInTransit) return

        Object.entries(this.deferredActions).forEach(([modelName, action]) => {
            this.updateQueue.unshift(action)
        })
        this.deferredActions = {}

        this.messageInTransit = new Message(this, this.updateQueue)

        let sendMessage = () => {
            this.connection.sendMessage(this.messageInTransit)
```

**Comment by jordyvanderhaegen** [comment]
I've made a [PR](https://github.com/livewire/livewire/pull/1907) that fixes this issue.

**Comment by calebporzio** [comment]
Merged, thanks!
