### ISSUE TITLE
TypeError: Cannot read property '$wire' of undefined

### ISSUE THREAD

**Issue by psos** [livewire/livewire#1914]
### Description
Nested livewire compontents if use @entangle, throw following error while rerender

index.js:127 Uncaught (in promise) TypeError: Cannot read property '$wire' of undefined
    at Livewire.value (index.js:127)
    at eval (eval at u (alpine.js:118), <anonymous>:5:42)
    at u (alpine.js:118)
    at new ve (alpine.js:1423)
    at alpine.js:1574
    at alpine.js:1556
    at l (alpine.js:90)
    at l (alpine.js:94)
    at l (alpine.js:94)
    at l (alpine.js:94)

### Exact steps to reproduce
Make root component rendering set of nested compontents (ex. inline-edit compontent in datatable).
Use @entangle in inline-edit nested compontent.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.x
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by Jubeki** [comment]
Try registering AlpineJS after Livewire Scripts

**Comment by psos** [comment]
Yes, I'm registering alpinejs after livewire

**Comment by psos** [comment]
Current workaround:
1/ wrap root <div x-data={}>  with root div (for livewire component)
2/ add wire:key with random value to ensure that div $el with __x is rerendered. 
<div  wire:key="random-{{ time() }}" x-data="{ entangleProperty: @entangle('property')">.... </div>


I'll try to put this case into laravel playground, but Im getting error in playground with nested components :-)
https://laravelplayground.com/#/snippets/886c855b-694c-4e6f-8f3c-cdb01e531ac4

**Comment by joshhanley** [comment]
Even thought the playground isn't loading nested components, can you make one with as much code as it needs to replicate the issue, so I can copy it down to a local test site and see if I can get the same issue?

**Comment by psos** [comment]
New insights,
Test.php
`<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $name = 'test parent';
    
    public $showNested = false;
    public function render()
    {
        return view('livewire.test');
    }
}
`

NestedTest.php
`
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class NestedTest extends Component
{
    public $name = 'test entangle property';
    public $value;

    public function render()
    {
        return view('livewire.nested-test');
    }
}
`


test.blade.php
`
<div>
    <div>
        <button wire:click="$set('showNested', 1)">insert nested compontent</button>
        <button wire:click="$set('showNested', 2)">change id to rerender nested compontent</button>
    </div>

    @if($showNested)
        <livewire:nested-test :key="$showNested" :value="$showNested" />
    @endif
</div>
`

`
<div x-data="{
    name : @entangle('name')
}">
    <div>
        Entangle: <span x-text="name"></span>
    </div>
    <div>
        Livewire: {{ $name }} - {{ $value }}
    </div>
</div>
`


In above click buttons cause no errors with insert or rerender nested compontent.
But if you change and add x-data to root compontent:
test.blade.php
`<div x-data="{ noMatterVariable: false }">
    <div>
        <button wire:click="$set('showNested', 1)">insert nested compontent</button>
        <button wire:click="$set('showNested', 2)">change id to rerender nested compontent</button>
    </div>

    @if($showNested)
        <livewire:nested-test :key="$showNested" :value="$showNested" />
    @endif
</div>`

clicking: button 1 or 2 breaks page:
index.js:148 Uncaught (in promise) TypeError: Cannot read property '$wire' of undefined
    at Livewire.value (index.js:148)
    at eval (eval at l (alpine.js:115), <anonymous>:4:29)
    at l (alpine.js:115)
    at new fe (alpine.js:1411)
    at alpine.js:1556
    at alpine.js:1538
    at e (alpine.js:87)
    at e (alpine.js:91)
    at fe.walkAndSkipNestedComponents (alpine.js:1532)
    at fe.initializeElements (alpine.js:1549)

**Comment by joshhanley** [comment]
So it looks like it is a race condition. What is happening is the nested alpine component is booting before the nested livewire component has finished loading into the DOM.

Under the hood @entangle calls find on the global Livewire class and it cannot find the new componentId yet, and as such when it then calls $wire on nothing, that is why the error is occurring.

**Comment by psos** [comment]
but I dont know why global x-data makes a difference and conditions are different.
In my case i must use global x-data entangle (datatable, modals) and nested entangles (inline edits)

I debug livewire/js/compontent/SupportAlpine.js  fn SupportEntangle()

**Comment by joshhanley** [comment]
Yeah, as you said, it works fine when there is no parent alpine component wrapping it. 

What I suspect is happening, is it is the parent alpine component calling `@entangle` instead of the child, as the child hasn't booted yet, but as the component doesn't exist in the DOM yet, the error occurs.

**Comment by psos** [comment]
My workaround to is to change x-data to defer-x-data on nested component and handle events.

    document.addEventListener("livewire:load", function(event) {
      Livewire.hook('component.initialized', (component) => {
            requestAnimationFrame(() => {
              component.el.setAttribute('x-data', component.el.getAttribute('defer-x-data'));
              Alpine.initializeComponent(component.el);
            });
      });
    });

----

Livewire code to discuss, 
I think that  root compontent causes tree component.updateElements, before  nested component is initialized.
I don't know why subcomponents doesn't send hook component.initialized.

refreshAlpineAfterEveryLivewireRequest() 
``php
..
function refreshAlpineAfterEveryLivewireRequest() {
    if (! window.Alpine.onComponentInitialized) return

    window.Alpine.onComponentInitialized(component => {
        let livewireEl = component.$el.closest('[wire\\:id]')

        if (livewireEl && livewireEl.__livewire) {
            store.registerHook('message.processed', (message, livewireComponent) => {
                if (livewireComponent === livewireEl.__livewire) {
                    component.updateElements(component.$el)
                }
            })
        }
    })
}
..

compares  (livewireComponent === livewireEl.__livewire)  root component, not nested compontent.

**Comment by psos** [comment]
```js
    x-data="{
        name: 'name'
    }"
    x-init="
        requestAnimationFrame(() => {
            name = $wire.name
            $watch('name', (v) => @this.set('name', v));
        });
    "
``

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by psos** [comment]
REOPEN

**Comment by psos** [comment]
@calebporzio  help with solution for overall alpine mutation observer racing with morphdom.
I'm tooo small for give solution, but know the reason.

Regards Caleb 
&& squishy bot! ;-)

**Comment by psos** [comment]
blade x-component wrapper to delayed  initializing alpine inside nested component.

<div x-data="{ delayed : 0 }" x-init="requestAnimationFrame(() => delayed = 1)">
    <template x-if="delayed">
        {{ $slot }}
    </template>
</div>

**Comment by austenc** [comment]
Going to close for now, please reopen if you'd like to present additional information or provide an example repository we can clone to reproduce and investigate this issue, thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@austenc and @psos this issue is the same as #1611 I believe. I've investigated that issue and reduced it down to the bare minimum. I have submitted a failing test PR #2517, so the cause can be investigated.

I suggest not reopening this and keeping all comments to #1611 or on the PR #2517, unless you think they are different.

Hope this helps!

**Comment by nathanjansen** [comment]
I bumped into this as wel, what I did as a quick fix, using [this example ](https://github.com/livewire/livewire/issues/1914#issuecomment-718180012)was:

```blade
<div x-data="{ noMatterVariable: false, showNested: @entangle('showNested') }">
    <div>
        <button x-on:click="showNested = 1">insert nested compontent</button>
        <button x-on:click="showNested = 2">change id to rerender nested compontent</button>
    </div>

    <div x-show="showNested">
        <livewire:nested-test :key="{{ \Illuminate\Support\Str::random() }}" :value="$showNested" />
    </div>
</div>
```

The `\Illuminate\Support\Str::random()` makes sure the component is re-rendered every time. Not very efficient, but for a quick fix I think it is ok.

Also note the `showNested: @entangle('showNested')` in x-data and the `x-on:click="showNested = 1"` in stead of wire:click.

The upside of this implementation is that it is even faster than wire:click=

I did not test the code, but it should work.

**Comment by psos** [comment]
@nathanjansen try using @entangle in nested-test component.

**Comment by nathanjansen** [comment]
> @nathanjansen try using @entangle in nested-test component.

If I understand your answer correctly, using @entangle in the nested-test component would not work in my example?

**Comment by vlados** [comment]
If you have **__construct()** function in the component, make sure you added
```php
parent::__construct()
```

**Comment by ssang** [comment]
> ```
> parent::__construct()
> ```

Thank you! I had the same issue and this fixed it for me.

**Comment by joshhanley** [comment]
@vlados @ssang It's not recommended to use the constructor, as it's not considered part of the public API and as such could change at any point potentially causing breaking changes. It's recommended to use `mount()` instead.

> In Livewire components, you use mount() instead of a class constructor __construct() like you may be used to.

https://laravel-livewire.com/docs/2.x/rendering-components#parameters:~:text=In%20Livewire%20components%2C%20you%20use%20mount(),like%20you%20may%20be%20used%20to.

Hope this helps!

**Comment by ssang** [comment]
> @vlados @ssang It's not recommended to use the constructor, as it's not considered part of the public API and as such could change at any point potentially causing breaking changes. It's recommended to use `mount()` instead.
> 
> > In Livewire components, you use mount() instead of a class constructor __construct() like you may be used to.
> 
> https://laravel-livewire.com/docs/2.x/rendering-components#parameters:~:text=In%20Livewire%20components%2C%20you%20use%20mount(),like%20you%20may%20be%20used%20to.
> 
> Hope this helps!

If I need a non-public property instantiated on every request, is it better to use `mount()` and `hydrate()`? As I understand it, `mount()` only runs on the instantiation of the component so whenever I send a request to the component (ie: type into a textbox that has a wire:model) an error is thrown because the property is null.

**Comment by thumbtech** [comment]
> If I need a non-public property instantiated on every request, is it better to use `mount()` and `hydrate()`? As I understand it, `mount()` only runs on the instantiation of the component so whenever I send a request to the component (ie: type into a textbox that has a wire:model) an error is thrown because the property is null.

Only just saw this last post, but quickly depending on how your property is used, you may be able to handle it in a [dynamic rules() function](https://laravel-livewire.com/docs/2.x/input-validation) (vs. the $rules property), which is reliably run every time inputs are handled ... ?

**Comment by nathanjansen** [comment]
@ssang the `render()` method is fine as well :)
The render method is instantiated on every request, 
and I believe the most logical place to update protected properties.

As a curiosity, why would you want to update a protected property on every request?

**Comment by ssang** [comment]
@nathanjansen For whatever reason, when I'm using Vanilo PHP modules for checkout and cart and I pull in the cart using `app(vanilo.cart)` I get an error saying public properties need to be of a certain type so I'm assuming it's unable to convert the PHP object to JSON but pulling it in as a protected property and using `getCartProperty()` seems to work so I've gone that route.

Maybe I'm doing something completely wrong and dangerous?

**Comment by gitRup-ca** [comment]
So I ended up here searching for help with my console error. 
AlpineJS ... "Cannot read property 'find' of undefined" when using Laravel 8/ Livewire Jetstream.
Symptom: The first modal on the page would show without activation.

It seems that you can get away with a Laravel Blade component with no start and ending DIV's.  
Once the component  reaches a certain size the error occurs.  

Wrapping code properly fixed the issue.  

Starting DIV on very first line. Ending DIV on very last line.

Three days to solve that issue - wow - cheers!

PS: Maybe some better error messaging?

**Comment by tcox-enrollfirst** [comment]
Every time I've come across this error, the same two common denominators existed:

1. Was trying to use `@entangle`
2. Livewire component did not have a `public function mount()`

Defining a `mount()` method has fixed the issue for me every time.

**Comment by DaviMenezes** [comment]
don't use constructor, use mount method
