### ISSUE TITLE
Update wire:model from a vue component

### ISSUE THREAD

**Issue by atefrihane** [livewire/livewire#1915]
Hey artisans
I'm trying to set a value from vue  to livewire but it's not working..

Value get displayed but not processed unless if I type it manually..

Livewire component 

```
     <div class="col">
   <input wire:model.debounce.300ms="search" class="form-control" type="text"
      placeholder="Search Batches..." id="search">
</div>
```

Vue js code

```
    onDecode (result) {
      this.result = result
      $('#search').val(result)
    },

```

how can I solve this?

**Comment by uteq** [comment]
I never worked with Livewire combined with VueJS, but I guess it should be somewhere similar to how for example communication with Alpine works.
What you can try is the follow

In your Vue template:
```javascript
onDecode (result) {
  this.result = result
  Livewire.emit('updatedSearch', result);
},
```

And add this to your Livewire component:

```php
protected $listeners = ['updatedSearch'];
```

If this does not work change Livewire emit to for example
```javascript
Livewire.emit('updateSearch', result);
```

And your Livewire component to:
```php
protected $listeners = ['updateSearch'];

public function updateSearch($value)
{
    $this->search = $value;
}
```

**Comment by atefrihane** [comment]
@uteq  Yeah that's exactly what I did later !
Thank you :))
