### ISSUE TITLE
Binding Directly To Model Properties not working

### ISSUE THREAD

**Issue by tvch** [livewire/livewire#1918]
### Description
I tried to recreate the example from the docs
https://laravel-livewire.com/docs/2.x/properties#binding-models

### Exact steps to reproduce
I had to adopt the model path for laravel 8.

i get the error:
**Typed property App\Http\Livewire\PostForm::$post must not be accessed before initialization**

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.11.2
- Browser: Chrome, Safari

**Comment by uteq** [comment]
Can you show my your route or how you implement your component?

**Comment by tvch** [comment]
Route::get('/', \App\Http\Livewire\CreateInvoice::class);

**Comment by tvch** [comment]
Route::get('/', \App\Http\Livewire\PostForm::class);

**Comment by uteq** [comment]
Thank you, Livewire expects a Post model in this case. So for example:

Route::get('/my-component/{post}', \App\Http\Livewire\PostForm::class);

Than when you visit your application this would be your url:
https://myapp.test/my-component/1

Where 1 is the id of the post.

Livewire utilizes Automatic Dependency Injection for this: https://laravel.com/docs/8.x/container#automatic-injection

**Comment by tvch** [comment]
Thanks
Okay then you cant use it to add a new post?
Maybe this has to be clarified in the docs?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by uteq** [comment]
> Maybe this has to be clarified in the docs? Okay i changed my project in the meantime to use an array. I did try to make an instance in the mount method but this dint work in my project (Laravel 7) but in the new (Laravel 8) it works. Thank you!

I think that this part already pretty wel explains it: https://laravel-livewire.com/docs/2.x/rendering-components#route-params

**Comment by latwelve** [comment]
REOPEN !

I've followed the docs and I'm using the latest versions but I'm having an issue with my route trying to set my livewire class incorrectly as a controller:

``Route::get('/test/{booking_family_member}', \App\Http\Livewire\EditFamilyMember::class);``

Invalid route action: [App\Http\Controllers\App\Http\Livewire\EditFamilyMember].

So I'm not sure why it's trying to prefix the namespace with a controllers namespace.. I rechecked the docs and it looks pretty simple what I'm trying to do and I can't see any registering of livewire I've missed to handle routes in L8

Sorry if it's just me being dumb!

**Comment by joshhanley** [comment]
@latwelve if you’ve upgraded your app from L7 to L8, you will need to change your route prefixes. Check here https://laravel.com/docs/8.x/upgrade#automatic-controller-namespace-prefixing

Hope this helps!

**Comment by latwelve** [comment]
> @latwelve if you’ve upgraded your app from L7 to L8, you will need to change your route prefixes. Check here https://laravel.com/docs/8.x/upgrade#automatic-controller-namespace-prefixing
> 
> Hope this helps!

You absolute dream boat! I even put a @todo comment by it in that file to remove the namespace :/ sorry - working too many hours.. thanks again.

**Comment by joshhanley** [comment]
@latwelve no worries!
