### ISSUE TITLE
Livewire Bot Tester

### ISSUE THREAD

**Issue by calebporzio** [livewire/livewire#1926]
You might wanna turn off notifications for this issue lol

**Comment by calebporzio** [comment]
test

**Comment by calebporzio** [comment]
test

**Comment by calebporzio** [comment]
IM AUTOMATED!

**Comment by calebporzio** [comment]
I'm automated. Reply with "REOPEN" to re-open this issue.

**Comment by calebporzio** [comment]
REOPEN

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
I'm automated. Reply with "REOPEN" to re-open this issue.

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
I'm automated. Reply with "REOPEN" to re-open this issue.

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
I'm automated. Reply with "REOPEN" to re-open this issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues for Caleb.

It looks like this issues has been closed. If for any reason you think it should be re-opened, no problem!

Just reply to this comment with "REOPEN", and I'd be happy to re-open it for you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues for Caleb.

I see this issue has been closed.

Here in the Livewire repo, we have a "freely open and close issue" policy to make the issues tab more manageable.

If for ANY reason you think this issue should be re-opened, go for it!

Reply "REOPEN" and I'll happily re-open this issue for you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "everyone can close issues guilt-free" policy.

If for ANY reason you think this issue should be re-opened, go for it!

(More info: https://twitter.com/calebporzio/status/1321864801295978497)

Reply "REOPEN" and we'll happily re-open this issue for you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel free to re-open it.

Reply "REOPEN" and we'll happily re-open it for you!

(More info on this philosophy: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by nuernbergerA** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
REOPEN

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by nuernbergerA** [comment]
REOPEN

**Comment by asantibanez** [comment]
HAHA. This is fun. Just got all of this notifications in my inbox.

**Comment by ddevdreamer** [comment]
Well it was fun to go through the entire thread. LOL.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by m1guelpf** [comment]
REOPEN, and then maybe more text?
