### ISSUE TITLE
Object is converted to Array

### ISSUE THREAD

**Issue by harshitpeer** [livewire/livewire#1931]
Hi,

I'm facing a weird issue with Laravel Livewire and I'm not sure what is going on here. Below is the scenario:

File - app/Http/Controllers/AppController.php

This file contains a function which is calling the main view and passing an object to it.
```
public function app() {
	$messages = [];
	for($i = 0; $i < 5; $i++) {
		$object = new \stdClass;
		$object->number = $i;
		$object->product = $i * $i;
		array_push($messages, $object);
	}
	return view('app')->with('messages', $messages);
}
```

File - resources/views/app.blade.php

This file is the main view file which basically calls the Livewire Component and pass the messages array to it,

```
@livewire('app', ['messages' => $messages])
```

File - app/Http/Livewire/App.php

This is the livewire component file which has a change function to change SOMETHING ELSE and NOT the messages variable.

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class App extends Component {

    public $messages;
    public $messageId = 0;

    public function change() {
        $this->messageId++;
    }

    public function render() {
        return view('components.app');
    }

}
```

File - resources/views/components/app.blade.php

This is the view file for the Livewire Component with following code

```
	{{ $messageId }}
        <button wire:click="change" class="bg-gray-600 p-4 rounded">Change</button>
        @foreach($messages as $message)
            	@if(isset($message->number))
            		number available
            	@else
            		number not available
            	@endif
        @endforeach
```

Here comes the surprise. The first time when I load the website, it shows 'number available' and the moment I click on that button "Change" which calls the Livewire action, it for some reason CHANGES the OBJECT inside $messages to ARRAY 

Because of this, I can't call the object functions. 

Is this a default behaviour of Livewire? OR a bug OR I'm doing something wrong?

**Comment by joshhanley** [comment]
This is default behaviour of livewire, have a look at this page https://laravel-livewire.com/docs/2.x/properties#important-notes 

> 2. Properties can ONLY be either JavaScript-friendly data types (string, int, array, boolean), OR one of the following PHP types: Stringable, Collection, DateTime, Model, EloquentCollection.

The reason is Livewire has to serialise the data into Javascript and as such doesn't know how to do it for standard objects.

But you can customise this. What you can do is rehydrate the array into the standard class object in a custom hydrate method on the component class. The method should be named `hydrate{PropertyName}() {}`. See `hydrateFoo` in https://laravel-livewire.com/docs/2.x/lifecycle-hooks

So your example would look something like

```php
public function hydrateMessages($value) {
// Do your code here to convert the array in $value back to your stdClass objects
// Then manually save it to $this->messages
}
```

Hope this helps!

**Comment by harshitpeer** [comment]
Thanks Josh!
That's really helpful.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
