### ISSUE TITLE
 Livewire Doesnt let work realrashid/sweet-alert 

### ISSUE THREAD

**Issue by uyanik13** [livewire/livewire#1945]
I'm using Laravel 8 and laravel 7 I faced with the same error. I added this repository to my project "realrashid/sweet-alert" and I'm using this. But also I'm using livewire too as a shopping cart, real-time search inputs, etc.

The Alerts doesn't show on the blade templates. I tried to remove "@livewire('shopping-cart')" this livewire component from my view and it's working but when it's in the blade doesn't work alerts.

Also, I tried to remove everything in the livewire blade component but still doesn't work.

Then I remove everything in the livewire blade component and in the livewire Class but its still doesn't work as well as the default.

Did you face this problem or do you know any solutions?

FOR testing composer require realrashid/sweet-alert and install laravel livewire (composer require livewire/livewire) and then create a livewire component. so you can test the alerts.

https://www.loom.com/share/5a0b432363fa4d6bba124300bb7b2158

**Comment by austenc** [comment]
@uyanik13 given what you have here it's not easy for us to reproduce the issue. 

You may want to try this integration out -- https://github.com/jantinnerezo/livewire-alert

**Comment by uyanik13** [comment]
this package useful on the livewire components but how can I use on the normal methods?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by uyanik13** [comment]
I jsut modified some packages and now that can be used with livewire also normal methods :
https://github.com/uyanik13/Laravel-7-8-Sweet-Alert-
maybe you can suggest for people
