### ISSUE TITLE
Multiple paginations in one component

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#1951]
In laravel you can `setPageName` on a paginated query so you can have multiple paginations on one page without collision.
But Livewire doesn't respect the set name and uses `page` for all paginated queries.

**Comment by mokhosh** [comment]
Anyone?

**Comment by calebporzio** [comment]
Closing for reasons in the PR

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
