### ISSUE TITLE
Weird behavior using @entangle on Laravel model

### ISSUE THREAD

**Issue by vgsystems** [livewire/livewire#1952]
### Description
I'm experiencing a weird behavior using @entangle on Laravel model.

Seems to be a gap between Alpine change and model update. The weird thing is that it's only happening when I try to update model properties(i.e. user.active) but doesn't when I try to update Livewire properties.

I'm going to share my code trying to explain the issue.

IMO @entangle seems to lost the model reference or doesn't fire the change event from Alpine to Livewire by an unknown problem on the first shot.

### Exact steps to reproduce

Create two Livewire properties, one Laravel model one standalone. 

The standalone property it's reactive and works as expected. The laravel model property is not reactive to the first change. No errors are shown on the browser console.

If I switch to a native HTML component like a checkbox, everything works as expected. 

### Stripped-down, copy-pastable code snippets

**File: app\Models\User.php**

```
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory;
    
    protected $fillable = [
       'active'
    ];

    protected $casts = [
        'active' => 'boolean'
    ];
}
```

**File: app\Http\Livewire\Users.php**

```
namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Users extends Component
{
    use AuthorizesRequests;
    
    public User $user;
    public $active = false;
    
    public function rules()
    {
        return [
        'user.active' => 'required|boolean',
        'active' => 'required|boolean',
        ];
    }
    public function mount()
    {
        $this->user = User::make(['active' => false]);
    }
}
```

**File: resources\views\livewire\users.blade.php**

```
<div>
    <x-input.group for="user.active" label="Active user?" :error="$errors->first('user.active')" toggle>
        <x-input.toggle wire:model="user.active" color="red" />
    </x-input.group>
    <x-input.group for="active" label="Active user?" :error="$errors->first('active')" toggle>
        <x-input.toggle wire:model="active" color="red" />
    </x-input.group>
</div>
```

**File: resources\views\components\input\toggle.blade.php**

```
@props([
	'color' => 'green',
	'background' => [
		'blue' => 'bg-blue-900',
		'light-blue' => 'bg-blue-500',
		'green' => 'bg-green-600',
		'red' => 'bg-red-600',
		'orange' => 'bg-orange-400',
		'yellow' => 'bg-yellow-300',
		'gray' => 'bg-gray-700'
	],
])
<div
	x-data="{ on: @entangle($attributes->wire('model')) }"
>
	<span
		x-on:click="on = !on"
		x-on:keydown.space.prevent="on = !on"
		x-bind:class="{ 'bg-gray-300': !on, '{{ $background[$color] }}': on }"
		class="relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none bg-gray-200">
		<span x-bind:class="{ 'translate-x-5': on, 'translate-x-0': !on }" class="translate-x-0 relative inline-block h-5 w-5 rounded-full bg-white shadow transform transition ease-in-out duration-200">
			<span x-bind:class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !on }" class="opacity-100 ease-in duration-200 absolute inset-0 h-full w-full flex items-center justify-center transition-opacity">
				<svg class="h-3 w-3 text-gray-400" fill="none" viewBox="0 0 12 12">
					<path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
				</svg>
			</span>
			<span x-bind:class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !on }" class="opacity-0 ease-out duration-100 absolute inset-0 h-full w-full flex items-center justify-center transition-opacity">
				<svg class="h-3 w-3 text-indigo-600" fill="currentColor" viewBox="0 0 12 12">
					<path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
				</svg>
			</span>
		</span>
	</span>
</div>
```

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.12.3
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@vgsystems I have copied your code down into a local test and it all seems to be working fine for me, see screenshot. 

All I added was outputting the Livewire results to the screen just to confirm it is actually running correctly, and remove the surrounding input group in users.blade.php as I didn't have that.

I'm testing on livewire 2.3.1 and alpine 2.7.3.

Can you double check you don't have something else going on?

@vgsystems or @danharrin can you move this to discussions for now until we can confirm if this a bug in livewire?

![recording (1)](https://user-images.githubusercontent.com/882837/97931899-c6235f80-1dc2-11eb-9ad3-56262fee8075.gif)

**Comment by vgsystems** [comment]
Hi @joshhanley, thanks for taking the time to review the problem. As far as I experienced the same issue in other models, I'm going to isolate the code and publish a full project in a Github repo to check the issue. Give me some hours to publishing it.
