### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST

### ISSUE THREAD

**Issue by xtreme2020** [livewire/livewire#1953]
### Description
After saving form getting random error 500, sometimes works without any problem then randomly appears error 500
### Exact steps to reproduce
Route::middleware(['auth:sanctum', 'verified'])->prefix('visitors')->group(function () {
    Route::get('/reserva', \App\Http\Livewire\Booking\CreateBooking::class)->name('create_booking');
});

the save method
$booking=$this->validate();
 DB::transaction(function() use($booking){
            $booked=Booking::create($booking['form']);
            $this->alert('success','Reserva Exitosa');
            event(new NewBooking($booked));
            $this->form['book_time']="";
            $this->mount();
            $this->updatedFormVisittypeuser();
        });

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [2.2.9]
- Laravel version: [8.7.1]
- Browser: [Chrome, Brave]

**Comment by austenc** [comment]
You shouldn't be re-calling `mount()` from within your save method.

**Comment by xtreme2020** [comment]
> You shouldn't be re-calling `mount()` from within your save method.

there was a method in mount that were called twice during the process and was causing random issue.
i'm still using mount but i will make some refactor to move some code from there.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
