### ISSUE TITLE
Trait lifecycle method syntax not working

### ISSUE THREAD

**Issue by rickwest** [livewire/livewire#1954]
I have a `WithSorting` Trait exactly as in the documentation https://laravel-livewire.com/docs/2.x/traits and I am trying to use the Livewire syntax to make use of Livewire's lifecycle hooks inside the trait. However, no method seems to be called other than on the `initialize` event.

For example, adding the following to my `WithSorting` Trait and only the `initializeWithSorting` method is ever called.  

```   
    // Works as expected
    public function initializeWithSorting()
    {
        dump('initialise');
    }

    // Doesn't seem to work 🤷‍♂️
    public function updatingWithSorting()
    {
        dump('updating');
    }
```

Seemingly it's the syntax that doesn't work with any other event. Adding the below in my `WithSorting` trait works as expected.

```
    public function updating()
    {
        dump('updating');
    }
```

**Context**
- Livewire version: 2.2.7
- Laravel version: 8.6.0

Livewire is mega by the way, really enjoying it and a big thanks for all you do! This has me stumped though, so hopefully it's not just me!

**Comment by austenc** [comment]
Thanks for reporting this @rickwest, I'll take a look!

**Comment by austenc** [comment]
@rickwest updating to `2.3.x` should fix your issue. Sorry I didn't notice that before! 

Support for hooking into the lifecycle with the (trait) class name suffix was added [in 2.3.0](https://github.com/livewire/livewire/releases/tag/v2.3.0)

**Comment by rickwest** [comment]
Awesome, all sorted! Thanks for looking into this for me! Will close this issue :+1:

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
