### ISSUE TITLE
BelongsToMany relations pivot fields are null in wire:click function events

### ISSUE THREAD

**Issue by manojo123** [livewire/livewire#1955]
### Description
BelongsToMany relations pivot fields are null in wire:click function events. 

### Exact steps to reproduce

> Livewire Component:
```
public $shop_products;
public $products;

public function mount()
{
    ... 

    // Simple NxN Relationship between product and shop
    $this->shop_products =  $this->products = Shop::find(1)->products;

    // 100% till here.. if you dump you see pivot fields with values
}

public filterProducts() {
    ...

    //Here is where you lose pivots
    $this->products = $this->shop_products;
}
```

> view
```
<div>
   <a href="#" wire:click="filterProducts">Filter Products </a>
</div>
```

**Context**
- Livewire version: [last stable]
- Laravel version: [last stable]
- Alpine version: [Doesn't Matter]
- Browser: [Doesn't Matter]

**Comment by austenc** [comment]
Hello @manojo123, this has to do with the way models are serialized -- the same limitations as when using Laravel's queue system.

For more information, the following related issue:
https://github.com/livewire/livewire/issues/1272#issuecomment-710157923

**Comment by calebporzio** [comment]
Yep, thanks @austenc!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
