### ISSUE TITLE
`wire:poll` continues after removing elements

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#1957]
### Description

I have a component where certain data is being polled until it is no longer empty. When this data stops to be empty the 250ms `wire:poll` interval should be stopped because the element disappeared and a new element with `wire:poll.5s` takes its place to poll every 5 seconds after the initial data has been received.

Currently I can observe in the chrome devtools that the 250ms `wire:poll` is continuing to poll data even though it is no longer present in the DOM. I would expect it to clear the interval and stop as soon as the element that triggered it is removed from the DOM.

Is there a way to intentionally clear the interval for a given element or is this a bug and the interval for elements that are removed from the DOM should be cleared and removed? I briefly dug around the JavaScript code and there seem to be `clearInterval` calls for the tear down of an element but adding console logs to those they never seem to be triggered when the element disappears from the DOM.

### Exact steps to reproduce

Create a component and view that look like the below. Check the devtools after the initial data has been loaded. The `wire:poll="pollEntries"` will continue to send requests every 250ms even after it has been removed from the DOM.

#### Component

```php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use Illuminate\Support\Collection;
use Illuminate\View\View;
use Livewire\Component;

final class EntryTable extends Component
{
    private ?Collection $entries = null;

    public function render(): View
    {
        return view('livewire.entry-table', ['entries' => $this->entries]);
    }

    public function pollEntries(): void
    {
        $this->entries = SomeModel::limit(10)->get();
    }
}
```

#### View

```blade
@if($entries->isEmpty())
    <div wire:poll="pollEntries">
        // Show this 
    </div>
@else
    <div wire:poll.5s="pollEntries">
        // Print records here and stop polling every 250ms
    </div>
@endif
```

### Context

- Livewire version: 2.3.1
- Laravel version: 8.12.3
- Alpine version: 2.7.0
- Browser: Chrome

**Comment by joshhanley** [comment]
@faustbrian having a look at your example, can you try adding wire:key to each of the divs and giving each one a different key. 

And then see if the issue is still happening?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
