### ISSUE TITLE
Strange DOM issue with nested component and wire:click (Unhandled Promise Rejection: TypeError: null is not an object)

### ISSUE THREAD

**Issue by glaesser** [livewire/livewire#1961]
### Description
Nested components 'jump' around the page when wire:click is triggered, even though no code is being run (the triggered function is empty). Seems like a dom diffing issue since nothing is being run/modified. No amount of wrapping divs or wire:key on parent or nested components makes any difference.

### Error message in JS Console
`[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'initialData.fingerprint') Component (livewire.js:13:108859) onNodeAdded (livewire.js:13:117538) handleNodeAdded (livewire.js:13:83712) (anonymous function) (livewire.js:13:87130) morphEl (livewire.js:13:87663) (anonymous function) (livewire.js:13:85849) morphEl (livewire.js:13:87663) (anonymous function) (livewire.js:13:88731) value (livewire.js:13:115909) value (livewire.js:13:113855) value (livewire.js:13:113417) value (livewire.js:13:72245) (anonymous function) (livewire.js:13:73115) promiseReactionJob`

![recording](https://user-images.githubusercontent.com/3802939/98004352-cce5bd00-1e2a-11eb-89bc-908e7e17c387.gif)

### Exact steps to reproduce
Create parent component with a foreach loop (in my example populated from a simple multi-dimensional array). Inside the foreach loop place another component. Add a button with wire:click="test" to the parent component and create an empty function test(). Click the button and observe the nested components jumping out of order even though no code is being run (except for the empty test() function). Again - no data is being intentionally touched/changed here.

### Code snippets
Laravel Playground link: https://laravelplayground.com/#/snippets/cf11e5f8-8277-41fe-b407-f550d161cd2a

**ParentComponent.php**
```
<?php
namespace App\Http\Livewire;
use Livewire\Component;

class ParentComponent extends Component
{
    public $categories;

    public function mount()
    {
        $this->categories = [
            ["name" => "Category 1", "products" => ["foo", "foo"]],
            ["name" => "Category 2", "products" => ["foo"]]
        ];
    }
  
    public function test() { }
    
    public function render()
    {
        return view('livewire.parent-component');
    }
}
```

**NestedComponent.php**
```
<?php
namespace App\Http\Livewire;
use Livewire\Component;

class NestedComponent extends Component
{
    public function render()
    {
        return view('livewire.nested-component');
    }
}
```

**welcome.blade.php**
```
<!DOCTYPE html>
<html>
    <head>
        @livewireStyles
    </head>

    <body>
        <livewire:parent-component />

        @livewireScripts
    </body>
</html>
```

**parent-component.blade.php**
```
<div>    
    @foreach($categories as $category_id => $category)
    <div wire:key="{{ $category_id }}">
        <br><strong>{{ $category['name'] }}</strong>

        <div>
        @foreach($category['products'] as $product_id => $product)
            <livewire:nested-component :key="$product_id">
        @endforeach
        </div>
    </div>
    @endforeach

    <br><input type="button" wire:click="test" value="Click Me">
</div>
```

**nested-component.blade.php**
```
<div>
    I'm a product
</div>
```

**Context**
- Livewire version: 2.3.1
- Laravel version: 7, 8
- Browser: Chrome, Safari

**Comment by joshhanley** [comment]
@glaesser can you can create a https://laravelplayground.com/ with the issue so we can have a look?

**Comment by glaesser** [comment]
@joshhanley I'm unable to reproduce in laravelplayground, but can reproduce in a fresh Laravel 7/8 installation (<3 minutes using my pastebin snippets.

One thing I forgot to mention, the javascript console error: 

`[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'initialData.fingerprint')
	Component (livewire.js:13:108859)
	onNodeAdded (livewire.js:13:117538)
	handleNodeAdded (livewire.js:13:83712)
	(anonymous function) (livewire.js:13:87130)
	morphEl (livewire.js:13:87663)
	(anonymous function) (livewire.js:13:85849)
	morphEl (livewire.js:13:87663)
	(anonymous function) (livewire.js:13:88731)
	value (livewire.js:13:115909)
	value (livewire.js:13:113855)
	value (livewire.js:13:113417)
	value (livewire.js:13:72245)
	(anonymous function) (livewire.js:13:73115)
	promiseReactionJob`

**Comment by glaesser** [comment]
@joshhanley here's the laravelplayground anyways, this same code run on a fresh Laravel 7/8 installation causes the DOM issue: https://laravelplayground.com/#/snippets/9b37acaf-b2b8-44bd-a0f8-3032712666d6

**Comment by glaesser** [comment]
@joshhanley here's a [laravelplayground link](https://laravelplayground.com/#/snippets/cf11e5f8-8277-41fe-b407-f550d161cd2a). Also added snippets above with which I was able to easily reproduce on a fresh Laravel 7/8 install.

One thing I forgot to mention, the javascript console error: 
`[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'initialData.fingerprint')
	Component (livewire.js:13:108859)
	onNodeAdded (livewire.js:13:117538)
	handleNodeAdded (livewire.js:13:83712)
	(anonymous function) (livewire.js:13:87130)
	morphEl (livewire.js:13:87663)
	(anonymous function) (livewire.js:13:85849)
	morphEl (livewire.js:13:87663)
	(anonymous function) (livewire.js:13:88731)
	value (livewire.js:13:115909)
	value (livewire.js:13:113855)
	value (livewire.js:13:113417)
	value (livewire.js:13:72245)
	(anonymous function) (livewire.js:13:73115)
	promiseReactionJob`

**Comment by joshhanley** [comment]
@glaesser ok it seems like it is a dom diffing issue. Have a look here at my changes https://laravelplayground.com/#/snippets/fe2a0ae8-b55b-472f-8e51-e10ab608adbc

A couple of things I changed, firstly, when you add wire:key to something make sure it is unique each time, see how I prepended each with a name. Having one key being `$category_id` and the other `$product_id` was meaning there was two elements with the key `0` and `1`, etc. on the screen which causes issues.

The other thing I changed, is I moved the wire:key off the nested component and put it on a wrapping div inside the foreach loop.

Not sure why the key being directly on the nested component directly isn't working property.

Give that a test and let me know how it goes, be interested to see if everything works ok for you inside your nested components if you move the key to a wrapping div.

Hope this helps!

**Comment by glaesser** [comment]
@joshhanley thanks for your efforts! Unfortunately i'm still getting exactly the same behavior in my fresh laravel 8 app, using the updated code as you provided. Any chance you can try on your local machine? Is there any explanation for laravelplayground behaving differently?

**Comment by joshhanley** [comment]
@glaesser no worries!

Ok so I have pulled it down and tested it locally, and yep, same issue happens. But I know why.

As I mentioned before it is definitely a key issue but I advised wrong, the key I suggested for products wasn't unique!
Have a look at the changes I made here: https://laravelplayground.com/#/snippets/69b1733f-8121-4976-857b-b60ff2c4d72c

Basically, what I did, was passed product_id down to the nested component, and got it to output it, so I could watch to see how it moved around on the page. That's when I noticed there was two products with an id of `0` due to using the index of the arrays (instead of say an id from a database which would actually be unique).

So I then prepended the category id to the product key and moved it back to the nested component (it does need to be on the component or it doesn't work). Thats when it all worked. And you don't need the extra wrapping div inside the foreach loop.

Re: Playground - no idea haha, I think it is kept reasonably up to date. Also there is a fair lag, so if you do click things, give it a few seconds (at least) to complete each time.

**Comment by glaesser** [comment]
@joshhanley argh, you are absolutely right, I don't know why I didn't catch that earlier! Thank you very much for helping me track this down, I think we can close now.

One thing that hasn't been helpful here is laravelplayground - why would it have worked there (with the "wrong" code) and not in a local installation? We may never know...!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@glaesser all good! No worries!

Yeah not sure, that does seem strange, probably something complicated to do with it being able to run in the browser 🤣
