### ISSUE TITLE
Setting nested properties form js using '@this' throws corrupted data error

### ISSUE THREAD

**Issue by Artessan** [livewire/livewire#1966]
### Description
setting nested properties form js using '@this' throws corrupted data error as you can see  in the playground
if is not possible to handle nested properties maybe and update on docs can be made

### Exact steps to reproduce
check the playground

### Stripped-down, copy-pastable code snippets
[playground](https://laravelplayground.com/#/snippets/2f989237-4bd4-46d0-b835-22a77a349560
)
**Context**
- Livewire version: [2.3.1]
- Laravel version: [8.12.3]
- Alpine version: [2.0.6]
- OS windows
- Browser: [chrome 88.0.4314.0, edge 88.0.688.0, firefox dev edition 83.0b4 (64-bit)]

**Comment by joshhanley** [comment]
@Artessan I have had a look at your playground and it seems that you have a validation property of `address.latitude`, but you are trying to assign to `address.lat`.

I would also recommend using the set method for nested properties `@this.set('address.latitude', 3)`.

Any PR's to improve the docs are welcome! https://github.com/livewire/docs

**Comment by Artessan** [comment]
Hi, thanks for look at it yes, was a type in the play ground but the error is not that typo even with the correct data the error still exists

**Comment by joshhanley** [comment]
No worries. Did you give the set function a try?

**Comment by Artessan** [comment]
Hey @joshhanley  thanks for the help as you said the $set methdo work like a charm. 
Thanks again.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
