### ISSUE TITLE
Browser back not refreshing component model

### ISSUE THREAD

**Issue by stuartcusackie** [livewire/livewire#1970]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/20210934/98247948-34575600-1f6c-11eb-97e1-46da932487d6.gif)

### Description

**I have two components:**
- **Component A**: Simple form with a select that allows a Counsellor to be assigned to a Client.
- **Component B**: A table component that outputs client->counsellors as rows

1. Component A saves the new counsellor relationship then **emits** a refresh request which is picked up by the table.
2. Component B refreshes successfully with the new counsellor.

**The Problem:**
If I navigate to any other page and then use the browser's back button the refreshed data is not show. See GIF.

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.12.3
- Browser: Chrome

**Comment by stuartcusackie** [comment]
Hmmm.. No idea how this got duplicated! Closing now...

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
