### ISSUE TITLE
Browser back is not rendering latest component model relationships

### ISSUE THREAD

**Issue by stuartcusackie** [livewire/livewire#1971]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/20210934/98249015-a67c6a80-1f6d-11eb-9756-948f856c76b8.gif)

### Description

**Setup:**
- Component A - a simple form with a select input to assign a counsellor to a client
- Component B - a simple table that renders the client->counsellor relationships.

Component A emits a refresh event to Component B after a new counsellor is assigned to a client and the table refreshes successfully.

**The Problem:**
As you can see in the GIF, If I navigate to another page and then use the browser back button, the latest "refreshed" relationships are not shown. Instead the originally rendered table with outdated relationships are displayed. I have to perform a manual refresh to retrieve the latest data.

I don't see this covered in the docs or in any issues. Is this expected behaviour? I am Polling as a temporary solution but that doesn't seem ideal.

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.12.3
- Browser: Chrome

**Comment by austenc** [comment]
@stuartcusackie mind providing a repo so this is easier to reproduce?

**Comment by joshhanley** [comment]
@stuartcusackie can you please explain the difference between issue #1970 and this one? If they are the same, can you close that one and we will investigate it on this issue?

When you click the back button, the councillor history doesn't show up, but if you then refresh the page manually does the history then show up?

**Comment by stuartcusackie** [comment]
I've closed the duplicate issue.

Yes, you are correct. This is my problem. I'm guessing that the Laravel cache isn't aware of the component being re-rendered (counsellor history) from the emit event. If I disable Laravel's cache using a custom middleware then the problem doesn't present.

**Comment by joshhanley** [comment]
Thanks!

Hmm yeah that is strange. I wonder whats different between the parent updating vs the child just refreshing, in terms of the cache.

Maybe it's something to do with refresh. 

Can you try passing some data to the child component from the parent when it updates and just adding that data to the screen somewhere in the child view, and then try you edit>back and see if the passed data shows up?

**Comment by stuartcusackie** [comment]
Unfortunately that doesn't change anything. This old outdated counsellor list is still showing, even after passing a parameter via the listener and showing it on the template using isset().

I have also tried a couple of other things:
- Make the $client property 'protected', assign it on mounted(), and pass it to the template as a parameter
- Pass $client->counsellors directly instead of calling the relationship in the template (this one makes it very difficult to work with the relationships and pivot data.

Sticking with cache-disabling for now...

**Comment by austenc** [comment]
Hi @stuartcusackie, what sort of cache disabling are you doing to "fix" this? Is it the browser cache or something related to Laravel's cache driver? 

Since it seems like there is quite a bit of app-specific context going on here, a repo with instructions on how to reproduce it will be the way to go if we're to investigate this further on the Livewire side. 

Please reopen at that time, thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by bastinald** [comment]
REOPEN

This is a huge issue. I've found that if you want any type of persisting state between non-component specific requests you need to use query strings, and even then that is limited to simple properties.

**Comment by calebporzio** [comment]
@bastinald , Please recreate the issue you are experiencing in the simplest form and open a new issue with a link to the repo so others can help.
