### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Netway-Warithar** [livewire/livewire#1978]
### Description
Uncaught SyntaxError: Unexpected end of JSON input

Data render to view result :
![Screenshot from 2020-11-06 09-26-43](https://user-images.githubusercontent.com/52729676/98318909-38d64a00-2012-11eb-86ba-158ec1d74df5.png)

**Because**   
Html parse data from json `&quot;` to `"` thus misrepresents the syntax. 
![Screenshot from 2020-11-06 08-48-32](https://user-images.githubusercontent.com/52729676/98316398-ec3c4000-200c-11eb-84da-279d25fddec0.png)

**Real data not parse** 
![Screenshot from 2020-11-06 09-25-09](https://user-images.githubusercontent.com/52729676/98318836-062c5180-2012-11eb-9bb4-b23485773018.png)

### Exact steps to reproduce

**Component view** 
```
<div class="card-body">
            {{ $body }}
        </div>
```
i think problem :
https://github.com/livewire/livewire/blob/dfb8844f9a7f72c53760509be2d18cd8ff0e75ca/src/HydrationMiddleware/AddAttributesToRootTagOfHtml.php#L15

i triend to set a value: 
```php 
return sprintf("%s='%s'", $key, $value);
```

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.13.0
- Alpine version: 2.7.0
- Browser: Chrome 86.0.4240.75

**Comment by joshhanley** [comment]
Can you provide some more information? What were you calling that caused this to happen? Can you share your component class and full view, and where the data comes from?

If you can, make a https://laravelplayground.com with an example of the issue happening, as it makes it easier to troubleshoot.

**Comment by Netway-Warithar** [comment]
i use vendor https://github.com/rappasoft/laravel-boilerplate 
i use component class  same this boilerplate in  https://github.com/rappasoft/laravel-boilerplate/blob/master/resources/views/components/backend/card.blade.php

It's okay I use this instead in component 
```php
<div class="card-body">
            {{ e($body) }}
        </div>
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
