### ISSUE TITLE
Model hydration

### ISSUE THREAD

**Issue by mrahmadt** [livewire/livewire#1979]
### Description

- Model Properties with selected column will be ignored in the Model hydration and select the full row
- Livewire documentation doesn't mention anything about Model Hydration feature (retrieving the rows from database with every call of the component)

### Exact steps to reproduce

https://github.com/livewire/livewire/discussions/1975

**Context**
- Livewire version: 2.0
- Laravel version: 8.12

**Comment by iksaku** [comment]
I think this should be discussed in the existing #1975 discussion. As I just commented there, this is more of a "feature" than a bug itself, but we could brainstorm some ways to have a new feature that allow you to manually query your model data from DB.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
