### ISSUE TITLE
Custom validation attribute w array field and validateOnly()

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1981]
### Description
- I have a form with an array field.
- I define a custom validation attribute with `protected function validationAttributes()`
- The custom attribute is **ignored in `validateOnly()`** but **respected in `validate()`**

I took some screen shots where I `dd()` from within Livewire `ValidatesInput validateOnly()` function.
As you can see the `$validator` has the custom validation `$attributes` but that is not what is sent to the error bag.

## `$validator` instance
<img width="616" alt="Skärmavbild 2020-11-06 kl  14 03 11" src="https://user-images.githubusercontent.com/21239634/98371026-cb3f1380-203b-11eb-96b1-5d4cd6bd749c.png">

## Message bag
<img width="530" alt="Skärmavbild 2020-11-06 kl  14 05 19" src="https://user-images.githubusercontent.com/21239634/98371108-ef9af000-203b-11eb-83fe-d19ac531119b.png">

## This is where I `dd()` the `$validator`
<img width="666" alt="Skärmavbild 2020-11-06 kl  14 04 22" src="https://user-images.githubusercontent.com/21239634/98371230-1d803480-203c-11eb-9349-f32bcead39a9.png">

## This is where I `dd()` the `$messages`
<img width="581" alt="Skärmavbild 2020-11-06 kl  14 06 36" src="https://user-images.githubusercontent.com/21239634/98371315-3f79b700-203c-11eb-937b-3737d5050f46.png">

### Exact steps to reproduce
The weird thing is that I can't reproduce it in the provided Laravel playground, I don't know which Livewire version that is.
Laravel playground - WITHOUT ISSUE
https://laravelplayground.com/#/snippets/b0cd04dc-330f-48e2-a6ca-0bba17c60ba4

### Stripped-down, copy-pastable code snippets
See playground.

**Context**
- Livewire version: dev-master#dfb8844
- Laravel version: 7
- Alpine version: 2.7.2
- Browser: Chrome

**Comment by tanthammar** [comment]
Sorry, nothings wrong! the field name passed was incorrect.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
