### ISSUE TITLE
commit #956d1b5 breaks my component

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#1982]
### Commit #956d1b5 breaks my component.
**Reverting back to `return [\Str::camel($key) => $value];` and all is working again.**

I have no idea where the `LivewireTagCompiler` `compileLivewireSelfClosingTags()` is used and what it's for.
And I don't know the difference between `[str($key)->camel() => $value];` and `return [\Str::camel($key) => $value];`.
The only thing i can say, it breaks something.

If I `dd($attributes)` when the source is `return [\Str::camel($key) => $value];`

<img width="636" alt="Skärmavbild 2020-11-06 kl  21 09 06" src="https://user-images.githubusercontent.com/21239634/98410107-56d49680-2074-11eb-8bad-7b6601ee4ecc.png">

I get this:
```php
[
  "model" => "$model",
  "field" => "$field->fieldToArray()",
  "tags" => "data_get($form_data, $field->name, '')",
]
```

### Here is a link to the stacktrace.
https://flareapp.io/share/LPlWyzam#F55
```
ErrorException, Illegal offset type
```

And here are images from the commit that breaks:

<img width="1244" alt="Skärmavbild 2020-11-06 kl  20 20 06" src="https://user-images.githubusercontent.com/21239634/98406006-7f0cc700-206d-11eb-903a-3678104d5179.png">

<img width="1244" alt="Skärmavbild 2020-11-06 kl  20 14 12" src="https://user-images.githubusercontent.com/21239634/98405833-410fa300-206d-11eb-9a3f-ec026f962361.png">

**Comment by joshhanley** [comment]
Yeah there is an open PR to fix that. Check out here https://github.com/livewire/livewire/pull/1974

**Comment by tanthammar** [comment]
Closing this because I expect PR #1974 to be accepted.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
