### ISSUE TITLE
wire:loading delay on slow internet connection

### ISSUE THREAD

**Issue by slider23** [livewire/livewire#1990]
### Description

wire:loading works with lags on slow internet connection (or on slow http-server - docker without docker-sync on mac or windows, or php for windows - on any solution with big response time). If you press the button immediately after filling in the form field, the loading indicator does not appear immediately.

As seen on gif below, Livewire waits for the end of wire:model http-request and only then starts http-request of wire:click and starts wire:loading event. But why? wire:loading must be starts immediately like on second button in gif below.

Fast dirty solution - using wire:model.defer. But then we lose realtime validation.

### Exact steps to reproduce

Demo: <img src='https://i.gyazo.com/ec0792dc46ce7460c782decebf24d0e7.gif'>

Code: https://laravelplayground.com/#/snippets/401fbc3a-4416-4f6c-9cb2-d5e2824309f3
Go to Chrome Developer Tool - Network - set Slow 3G instead Online 

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.4.0
- Alpine version: 2.3.0
- Browser: any

**Comment by calebporzio** [comment]
Ok, the reason this is happening, is that your inputs are using `wire:model.lazy`

Here's the breakdown:
- type into first input, tab away to second
- now a network request is out to update that first input
- while the request is out, you type into the second and tab away
- now a second network request is QUEUED for when the first one returns
- now you click a button
- Livewire has to wait until BOTH requests have returned to send this button request and THEN it will show the loading indicator

As you mentioned `.defer` is one solution to this problem.

Anything beyond that would require changing of Livewire's core.

The change would have to be something like this:

Start the loading indicators NOT when a request goes out, but when it is QUEUED. This way you would get the loading indicators immediately.

I'm open to this, but I think it calls for a rewrite of the message queueing system (or at least a refactor)

I'm going to close this for now until others express a desire for it.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
