### ISSUE TITLE
level child for wire:ignore

### ISSUE THREAD

**Issue by HASSANDL** [livewire/livewire#1993]
I want ignore only 2 level of childs no all.
```
<div wire:ignore>
    <div class="level1">
        <div class="level2">
            <div class="level3">
```

**Comment by joshhanley** [comment]
Answered in discussion #1992.

Please don't open an issue and a discussion at the same time.
If you need help, please just open a discussion.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
