### ISSUE TITLE
change default layouts.app to another filename default layout

### ISSUE THREAD

**Issue by MahdiPishguy** [livewire/livewire#1998]
in my current application which i want to migrate to `LiveWire` default layout is `layouts.app` and i want to change it to `layouts.backend.main`, because of having `Admin` dashboard and `Frontend` views

how can i change in route? i can do it something like adding `layout` inside `render` function:

```php
public function render()
{
    return view('livewire.administrator.categories')->layout('layouts.backend.main');
}
```

my route with `layout` with it doesn't work and i get error:

```php
Route::group(['prefix' => 'panel',
    'middleware' => ['auth'],
    'layout'=>'layouts.backend.main'
], function () {
    Route::group(['prefix' => 'administrator',
    ], function () {
        Route::get('categories', Categories::class)
            ->middleware('can:can-have-category-menu')
            ->name('categories');

    });
});
```

**Comment by whizzrd** [comment]
Please see PR #1973 to determine if that would work in your situation

**Comment by joshhanley** [comment]
Caleb has opened an issue regarding this. See #2000 

Could you close this issue and continue the discussion there so it is all in one place?

**Comment by calebporzio** [comment]
Yeah, I agree there should be a story for this. Please weigh in on the matter in #2000

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
