### ISSUE TITLE
File mime type and extension gets changed after uploading to temp directory

### ISSUE THREAD

**Issue by FrancisMawn** [livewire/livewire#1999]
### Description
I'm having trouble with the file upload functionality. When I try to upload a **SRT** file, I noticed that its extension was rename to **.txt** and mime type was also changed to **application/octet-stream** once its been uploaded to the tmp directory.

This makes it impossible for me to validate the mime type. Any idea why it would do that?

### Exact steps to reproduce
1. Create a component that uses the WithFileUploads trait.
2. Add a validation rule like that: `'captions' => 'mimes:text,text/srt,text/plain',`
3. Upload a SRT file.
4. Validation always fail since the file mimetype gets changed during the upload process.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: ^2.0
- Laravel version: 8.11.2
- Alpine version: [e.g. 2.3.0]
- Browser: Chrome

**Comment by FrancisMawn** [comment]
In the meantime, I removed the mime type validation rule and added this to my save method:
```
$renamed = str_replace('.txt', '.srt', $this->captions->getRealPath());
rename($this->captions->getRealPath(), $renamed);
```

I would still like to get some of your feedback around this issue. 

Thanks.

**Comment by calebporzio** [comment]
Yeah, sometimes there are issues because our file upload system uses Symfony's (I believe) "guessExtension" feature to name the extension. This method is innacurate sometimes.

Because it's untenable for me to address these edge cases with unpopular file types, I'll close this and request that you PR support for that file type or stick with your solution.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by leonnicklas** [comment]
REOPEN

**Comment by leonnicklas** [comment]
Hi there, 

i'm having the same problem as @FrancisMawn with the file types: .stl .stp .step
.stl files are renamed to .bin files, .step files are also renamed to .txt files.

Is there a proper way to stick with the original filetype of the file which was uploaded by the user?

Best regards
Leon

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by virendra-maurya** [comment]
REOPEN

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, @virendra-maurya please open a discussion with details and link to this issue if you are having problems.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
