### ISSUE TITLE
 protected props get null value  after submit or any action

### ISSUE THREAD

**Issue by devscript-abdo** [livewire/livewire#2001]
### Description
if I declare a protected var like  ::  protected $categories;
-------------------------------------
 protected $categories;
 public function mount(Category $categorie )
    {
        $this->categories= $categorie;

    }

in render method $this->categories still has data 
    public function render()
    {
        
        return view('livewire.product.products', [
             'categories'=>   $this->categories->all(),

        ]);
    }
when I call  {{dd($categories)}} in blade view('livewire.product.products') … Data it's still no problem here 💯 

but when I call a method from submit Form example : <button wire:click.prevent="submit()"></button>

and inside submit() function I need  $this->categories     example ::

 public function submit()
   {
        dd($this->categories );  return null
 }
$this->categories  return null after any action !!!
### Exact steps to reproduce
solution I use is inject Model in function again  but i don't like it !!!
 public function submit(Category $categorie)
   {
        dd($categorie->all() );  return data
 }
### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by joshhanley** [comment]
That is how it works, only public properties are accessible between requests. So you have to make $categories public if you want it accessible in your submit method. 

See here in the docs https://laravel-livewire.com/docs/2.x/properties#important-notes
> protected and private properties DO NOT persist between Livewire updates. In general, you should avoid using them for storing state.

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Thanks Josh!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by brentonmaas** [comment]
public function mount(Category $categories)
{
	$this->categories = $categories;
}

public function hydrate()
{
	// Reinstantiate the var between calls
	$this->categories = Category::getCategories(); //or whatever method you are using
}

if you need params to your Category::getCategories(); you just need to pass them through to your component
