### ISSUE TITLE
Undefined property $dom on some livewire pages

### ISSUE THREAD

**Issue by atymic** [livewire/livewire#2002]
### Description

Will flesh this more out later, I can't seem to figure out exact repro steps ATM.

```
Undefined property: Livewire\Response::$dom (View: /Users/user/code/fluxbucket/tag-therapy/resources/views/home/library.blade.php)
```

![image](https://user-images.githubusercontent.com/50683531/98598545-c2498d00-232e-11eb-9389-f68766d05d68.png)

### Exact steps to reproduce
Load livewire page.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 7.29.3
- Browser: Any

**Comment by joshhanley** [comment]
Did you recently update? Run `php artisan view:clear` and see if it still happens. It was refactored from `->dom` to `->html()` at some point.

Hope this helps!

**Comment by atymic** [comment]
Great catch, thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
No worries!

**Comment by andymnewhouse** [comment]
Why do I get this when publishing to production but NOT on my machine?

**Comment by joshhanley** [comment]
@andymnewhouse did you try running `php artisan view:clear` on your production system?

**Comment by andymnewhouse** [comment]
Yup! And 

php artisan cache:clear
php artisan config:clear
php artisan livewire:discover
php artisan livewire:publish

But the only thing that worked was redeploying from Laravel Forge 🤷

**Comment by joshhanley** [comment]
Strange! The other one to throw in there is `composer dump-autoload` I'd probably do that after the clear calls and before discover.

So did it work after you redeployed? I'm using Envoyer, so don't tend to run into those issues as it creates a new directory on deploy and symlinks the new directory after everything has been loaded and installed.
