### ISSUE TITLE
realation not working on updated model

### ISSUE THREAD

**Issue by arbabi2010** [livewire/livewire#2004]
### Description
I use relation in mount . 
`$this->post = Post::with('comments')->find(1);`

when I update input model with  wire:model , in updatedFoo i change a data and i dd $this->post the relation is empty and i have to use ` $this->post->load('comments')` again. 
what`s wrong with my code ? 

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.11.1]

- Browser: [e.g. Chrome, Safari]

**Comment by devscript-abdo** [comment]
In update method  you should define  the relation because livewire forget instance of vars  on every request 
public function update($id)
{
$post = Post::with('comments')->find($id);
}

**Comment by arbabi2010** [comment]
@devscript-abdo . Tanx. I'm doing like this

**Comment by calebporzio** [comment]
Livewire should honor eager loaded relationships.

I just tested this locally and it worked for me.

Can you post something more copy/pastable (in the problems SIMPLEST form)?

Re-open when you've done so.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
