### ISSUE TITLE
LiveWire Offline State doesn't work when i change connectin State

### ISSUE THREAD

**Issue by MahdiPishguy** [livewire/livewire#2006]
In [this link][1] of `LiveWire` documentation i simply added this line in `header` of our web application

    <div wire:offline>
        You are now offline.
    </div>

when i refresh the page, it doesn't appear on `header` and when i disconnected internet connection same as `Aire plane mode` in `Windows` i expect to see `You are now offline.`. but it doesn't any change, i check that by refreshing multiple page.

this part of `LiveWire` how's it work? 

**playground link:**

https://laravelplayground.com/#/snippets/9de397f8-0182-4176-9bd6-4d15ba49d3f2

  [1]: https://laravel-livewire.com/docs/2.x/offline-state

**Comment by joshhanley** [comment]
@MahdiPishguy is the header of your application inside a Livewire component? If not, then this won't work.

You need to make sure that this is somewhere inside your Livewire component, or make a Livewire component just for this that you put into your header.

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy is the header of your application inside a Livewire component? If not, then this won't work.
> 
> You need to make sure that this is somewhere inside your Livewire component, or make a Livewire component just for this that you put into your header.

i created this `component`:

```php
<?php

namespace App\Http\Livewire\Administrator\Partials;

use Livewire\Component;

class Header extends Component
{
    public function render()
    {
        return view('livewire.administrator.partials.header');
    }
}
```

and i used in `layouts.app`:

```php
<body>

@livewire('administrator.partials.header')

<div class="page-content">
...
...
```

**Comment by joshhanley** [comment]
Can you show the contents of your blade file 'livewire.administrator.partials.header'?

**Comment by MahdiPishguy** [comment]
> 
> 
> Can you show the contents of your blade file 'livewire.administrator.partials.header'?

Yes, sure

```html
<div class="navbar navbar-expand-lg navbar-dark">
    <div class="navbar-brand">
        <a href="/" class="d-inline-block">
            <img src="{{ URL::asset('theme/backend/')}}/assets/global_assets/images/logo_light.png" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">

        <span class="navbar-text ml-md-3">
        <span class="badge badge-mark border-orange-300 mr-2"></span>
            @if(auth()->check())
               Hello
            @endif
	</span>


        <div wire:offline>
            You are now offline.
        </div>

    </div>
</div>
```

**Comment by joshhanley** [comment]
That looks ok, does it work now that you have a header component?

**Comment by MahdiPishguy** [comment]
@joshhanley 

`header` component works fine and i'm using it in my web application, but `wire:offline` doesn't work when i change internet connection and it doesn't appearance

**Comment by joshhanley** [comment]
I have created a working example on a playground, have a look here: https://laravelplayground.com/#/snippets/43c511d8-fda4-46a9-8411-5c0e53b52a9d

**Comment by MahdiPishguy** [comment]
@joshhanley 

yes you right, i found out which part of my code cause of problem, after removing this line of code, `offline` work fine

```css
<style>
    .navbar-brand img {
        height: 1.5rem !important;
    }
</style>
```

i have another question, in initial loaded page when we don't have internet connection, i can see `offline` state, now i'm refreshing the page again which that cause of disappear `offline` state, in this time i don't have internet connection and `offline` state should shown again

is this right? do you agree?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
Cool!

Hmm, I'm not exactly sure what you mean? If it's already offline and you refresh, then nothing would happen, the page shouldn't even load. Or do you have a button with a refresh method or something that updates the livewire component?

**Comment by MahdiPishguy** [comment]
@joshhanley why `offline` state doesn't show again such as `you are offline` when device doesn't have connection? every use can refresh page when it doesn't have any internet connection

my mean is when we don't have any internet connection and we refreshing page or switch between web application other pages, offline state should shown `you don't have internet connection` til we connected to the internet, it doesn't happen now

Do you understand what I mean? thanks in advance

**Comment by joshhanley** [comment]
Yep, that's because Livewire isn't an SPA, so therefore any form of navigation while offline will cause the default browser offline message rather than your custom one.

SPA's can work different, as all the logic is in javascript, that way the app can be saved to the users browser, so even if they navigate or refresh, it can run from the local storage.

**Comment by MahdiPishguy** [comment]
i got it, thanks so much
