### ISSUE TITLE
Trix Editor: Changing the styling of content

### ISSUE THREAD

**Issue by qdz90** [livewire/livewire#2009]
### Description
Using trix editor and updating the content of the field Livewire does not recognize changes in styling. While It does recognize changes to text.

### Exact steps to reproduce
When having a trix editor with content change for example: 

**WRONG:** 
If the content of the trix field is: `<b>Hello</b>` and change it to `<i>Hello</i>` Livewire posts `<b>Hello</b> `on save.

**GOOD:** 
If the content of the trix field is: `<b>Hello</b>` and change it to `<i>Bye</i>` Livewire posts `<i>Bye</i>` on save.
If the content of the trix field is: `<b>Hello</b>` and change it to `<b>Bye</b>` Livewire posts `<b>Bye</b>` on save.

### Stripped-down, copy-pastable code snippets
edit.blade.php

```
<input id="trix-description-text" type="hidden" wire:model.defer="person.description">

<div wire:ignore>
    <trix-editor
        class="h-64"
        input="trix-description-text"
        wire:model.debounce.999999ms="person.description"
        wire:key="descriptionKey"
    ></trix-editor>
</div>

<button wire:click="save()">Save</button>

@push('scripts')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
@endpush

```

Edit.php

```
public Person $person;

public function save()
{
   $this->person->save();
}

public function render()
{
   return view('livewire.edit');
}
```

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.13.0
- Browser: Chrome, Safari

**Comment by joshhanley** [comment]
`wire:model` listens for an input event, but for Trix it fires a `trix-change` event. So you need to listen for a `trix-change` event and then get its results and fire off a normal input event. 

Have a look here https://github.com/basecamp/trix#observing-editor-changes

As this isn't a bug with livewire, we will move this over to discussions to keep working through it there.
@danharrin can you move this to discussions?

Hope this helps!

**Comment by qdz90** [comment]
@joshhanley Thank you for your help!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Thanks for weighing in @joshhanley !!
