### ISSUE TITLE
Livewire directives not rendered (correctly) in production

### ISSUE THREAD

**Issue by bblumenfelder** [livewire/livewire#2012]
### Description
I'm really desperate here since I cannot get my component working in production. 
To get to the bottom of the problem I tried to rebuild the simple counter-component as described in the Livewire-docs.
On my local server everything's working. There seems to be a problem with livewires directives

**The following I have tried:**
- @livewireStyles, @livewireScripts and @livewire('counter') ▶ Works in local dev; In production the page renders "@livewireStyles", "@livewireScripts" and "@livewire('counter')" within `<pre>`-tags
- `<livewire:styles/>`, `<livewire:scripts />` and `<livewire:counter />` ▶ Works in local dev; In production self-closing tags include each other (see screenshot)

![Screenshot 2020-11-11 190213](https://user-images.githubusercontent.com/22280509/98847375-73941400-2450-11eb-9320-61c9ef58e138.png)

- Publishing the assets, manually setting the path to assets in livewire.config and including the assets in my blade view ▶ Works in local dev; In production the assets are correctly loaded but my component is not rendered.

Is there an alternate syntax to livewires self-closing tags?
All my blade-directives and self-closing tags of html are working, not Livewires though.

### Stripped-down, copy-pastable code snippets

**My component:** 

```
namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public $count = 0;

    public function increment()
    {
        $this->count++;
    }

    public function render()
    {
        return view('livewire.counter');
    }
}

```

**My template**
```
<div>
    <button wire:click="increment">+</button>
    <h1>{{ $count }}</h1>
</div>
```

**My view that includes the component:**
```
<html>
<head>
    <livewire:styles/>
</head>
<body>
<livewire:counter/>
<livewire:scripts/>
</body>
</html>
```

**Context**
- Livewire version:  2.3.1
- Laravel version: 7.4
- Production server: Ubuntu 16.04.6 LTS with nginx and PHP 7.4.9
- Browser: [Chrome, Firefox]

**Comment by joshhanley** [comment]
@bblumenfelder Using either @livewireStyles or <livewire:styles /> should work fine as your on Laravel 7. It sounds like the LivewireServiceProvider isn't loading.

I would double check that all your dependencies are installed correctly in production run `composer show -D` on your production server and ensure Livewire is listed there and Livewire and Laravel's versions match your local versions.

The other thing to do is to ensure you have cleared blade's view cache using `php artisan view:clear`.

I would also avoid publishing the assets if you can get away with it, otherwise you need to keep them manually updated anytime you update Livewire.

If the above couple of options don't work, I would be investigating to see if the service provider is loading and if not working out why it's not loading in production.

Hope this helps!

**Comment by bblumenfelder** [comment]
Hi Josh,
thanks a lot for your answer! You got me on the right track. 
I could not solve the original issue with the service-provider, but after upgrading to Laravel 8, my component is now rendering in production. 
I'll leave it to the contributors to close the issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by meshackvictor** [comment]
I did run into the same problem, Spent time looking for solutions, found half of it, made half of mine

Under the folder bootstrap/cache delete the following cached files, packages.php and services.php
Open the files that you have called the blade/livewire directives i.e. @livewireStyles() and @livewireScripts() Change anything in the file and save it.

**Comment by squatto** [comment]
I wanted to also add what worked for me when I ran into this today on my dev environment. The `<livewire>` tag wasn't being rendered as a component and was instead being output as-is. What fixed it was to run `php artisan view:clear` to clear the compiled view files 👍🏻 Thanks @joshhanley for pointing me in the right direction!

**Comment by amiralidev** [comment]
remove every space after or before @livewireStyles & @livewireScripts,
if doesn't work, make manual change in production code
