### ISSUE TITLE
Cant cell middleware from controller

### ISSUE THREAD

**Issue by Ulyev-ad** [livewire/livewire#2014]
I can't call middleware from the controller.
```
 public function __construct()
    {
        $this->middleware('captcha.log')->only('index');
    }
```

Returned "Method App\Http\Livewire\FormValidation::middleware does not exist.".

This call is not provided or is there an error? Laravel has such a call.

**Comment by joshhanley** [comment]
Middlewares don't work inside Livewire components, you will need to implement the logic inside the component or extract it into a trait https://laravel-livewire.com/docs/2.x/traits

Also you shouldn't be using the constructor on Livewire components, you need to put any initialisation stuff in the mount method.

Hope this helps!

**Comment by calebporzio** [comment]
Thanks @joshhanley - yeah, you can't use constructors in Livewire components, but you can use lifecycle hooks to apply your middleware logic on every request.

Maybe adding an API for setting middleware on a per component basis is a good idea, but let's keep an eye on the demand for it first.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
