### ISSUE TITLE
Method_exists error in PHP 8

### ISSUE THREAD

**Issue by Ceepster14** [livewire/livewire#2016]
In the process of setting up a Laravel / Livewire application on a new client server that's running PHP 8.0.0.RC3. Previously we've had the application running without issue under PHP 7.4.

One of the Livewire components we use polls for new notifications. It functions OK when the page is first rendered, but when the first poll event is triggered it errors with the following:

```
TypeErrorPOST /livewire/message/mobile.reminders-widget
method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given
```

and the stack trace gives the offending code as in the HydrationMiddleware/HashDataPropertiesForDirtyDetection.php:49

```
public static function hash($value)
    {
        if (! is_null($value) && ! is_string($value) && ! is_numeric($value)) {
            $value = method_exists($value, '__toString')
                ? (string) $value
                : json_encode($value);
        }
```

in PHP 8 method_exists now throws a Type Error if it encounters an unexpected value, which it didn't do previously

This is using livewire version v2.3.1

Is Livewire currently viable for PHP 8 or should we rebase the environment to PHP 7.4 for the interim?

**Comment by joshhanley** [comment]
Have a look at this PR #1933 for PHP8 support. Currently waiting on a dev dependency to be updated so Livewire tests can be run using PHP8 to see if anything breaks.

Hope this helps!

**Comment by Ceepster14** [comment]
Thanks for the clarification, makes sense. I think maybe the PHP8 move is a bit premature, so I'll drop back to 7.4 for now and monitor developments.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by hermescortesm** [comment]
I reopen this because in my system i've installed PHP 8.0 and obtain this error but now i am in PHP 7.3 installed by brew and the error is the same.

I tried all like  php artisan optimize:clear but the problem stills, help please guys

**Comment by amiralidev** [comment]
just run composer update
