### ISSUE TITLE
MessageBag.js:34 Uncaught (in promise) TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by daylightstudio** [livewire/livewire#2018]
### Description
The following error message is displayed after calling `wire:click.prevent="removeUpload('data.file', '{{ $file->getFilename() }}')"`:
```
MessageBag.js:34 Uncaught (in promise) TypeError: Cannot read property 'shift' of undefined
    at MessageBag.value (MessageBag.js:34)
```
### Exact steps to reproduce
I have a livewire form component that uses the `WithFileUploads` trait. When a file is uploaded it uses the `temporaryUrl()` method to display a preview of the image and has a `removeUpload(...)` function to remove the image. Clicking the button does remove the image but returns the above error to the javascript console.

### Stripped-down, copy-pastable code snippets
```
<button wire:click.prevent="removeUpload('data.file', '{{ $file->getFilename() }}')">
      Remove
</button>
<img src="{{ $file->temporaryUrl() }}">
```

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by calebporzio** [comment]
Is this because the upload is nested? In "data.file"? 

Try putting the upload property at the root level, like just `public $file` and see if this persists.

If it does, re-open.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by daylightstudio** [comment]
REOPEN

I realized my example stated above had some inaccuracies because I was trying to simplify the example (and yes, I had a data array in which form entries were being saved). However, I've essentially recreated it with the following simplified example that doesn't use the data array and instead just uses a `$file` public variable as the model of the input and the javascript error still persists after deleting (although it does successfully remove the preview image):
```
<input type="file"  name="file" wire:model="file">

@if (!empty($file))
    <div class="flex">
        <div>
            <button wire:click.prevent="removeUpload('file', '{{ $file->getFilename() }}')">
                 <x-icon-minus-circle class="text-gray-400 w-4 w-4 ml-1 mt-2"/>
            </button>
            <img src="{{ $file->temporaryUrl() }}">
        </div>
    </div>
@endif
```

**Comment by softmixt** [comment]
I have same issue here , any solution ?

**Comment by softmixt** [comment]
I discovered  that if I comment out the line 73 in WithFileUploads trait works .

```php


    public function removeUpload($name, $tmpFilename)
    {
        $uploads = $this->getPropertyValue($name);

        if (is_array($uploads) && isset($uploads[0]) && $uploads[0] instanceof TemporaryUploadedFile) {
            //$this->emit('upload:removed', $name, $tmpFilename)->self();

            $this->syncInput($name, array_values(array_filter($uploads, function ($upload) use ($tmpFilename) {
                if ($upload->getFilename() === $tmpFilename) {
                    $upload->delete();
                    return false;
                }

                return true;
            })));
        } elseif ($uploads instanceof TemporaryUploadedFile) {
            $uploads->delete();

            $this->emit('upload:removed', $name, $tmpFilename)->self();

            if ($uploads->getFilename() === $tmpFilename) $this->syncInput($name, null);
        }
    }

```

is this line : 

``` php 
//$this->emit('upload:removed', $name, $tmpFilename)->self();
```
what i actually did is:  I added this function on my livewire component with that line commented out ,is not the best solution and hope i didn't break something else .

if someone has a better solution please  write it down here, thanks

**Comment by daylightstudio** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by ThomasLaveto** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by ThomasLaveto** [comment]
Looks like this issue is caused because by the MessageBag (this.removeBag) not having the key/ property of the Livewire property where we store our files in. I think removeUpload in UploadManager.js is not called after removeUpload from WithFileUploads.php is called?

**Comment by dopesky** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN

**Comment by p-andrey** [comment]
For correct work, need to call Livewire js method 'removeUpload'. 

Simple way, when your project include alpine:

`
<button x-data @click="@this.removeUpload('{{ $fieldName }}', '{{ $file->getFilename() }}')">remove</button>
`

**Comment by sertxudev** [comment]
REOPEN

**Comment by sertxudev** [comment]
### Problem

If we try to delete a recently uploaded file using the following code:

```blade
<button wire:click.prevent="removeUpload('files', '{{ $file->getFilename() }}')">Delete</button>
```

The following error is shown on the console.

> MessageBag.js:34 Uncaught (in promise) TypeError: Cannot read property 'shift' of undefined

This occurs due to an "upload:removed" event emitted inside the "removeUpload" method.

--------

### Workarounds

A workaround is to modify the button and use Alpine.JS.

```blade
<button x-data @click="@this.removeUpload('files', '{{ $file->getFilename() }}')">Delete</button>
```

Another workaround is to override the removeUpload method inside the component.

```diff
public function removeUpload($name, $tmpFilename)
{
    $uploads = $this->getPropertyValue($name);

    if (is_array($uploads) && isset($uploads[0]) && $uploads[0] instanceof TemporaryUploadedFile) {
-        $this->emit('upload:removed', $name, $tmpFilename)->self();

        $this->syncInput($name, array_values(array_filter($uploads, function ($upload) use ($tmpFilename) {
            if ($upload->getFilename() === $tmpFilename) {
                $upload->delete();
                return false;
            }

            return true;
        })));
    } elseif ($uploads instanceof TemporaryUploadedFile && $uploads->getFilename() === $tmpFilename) {
        $uploads->delete();

-        $this->emit('upload:removed', $name, $tmpFilename)->self();

        $this->syncInput($name, null);
    }
}
```

---------

### Posible solution

A possible solution could be to add a null-safe property access to the "removeBag" property.
This way the error could not appear 'cause the instruction will end before trying to access the undefined property.

But I don't know how to implement the "finishCallback" method with the null-safe property.

https://github.com/livewire/livewire/blob/020ad095cf1239138b097d22b584e2701ec3edfb/js/component/UploadManager.js#L30

```diff
- this.component.on('upload:removed', (name, tmpFilename) => this.removeBag.shift(name).finishCallback(tmpFilename))
+ this.component.on('upload:removed', (name, tmpFilename) => this.removeBag.get(name)?.shift().finishCallback(tmpFilename))
```

**Comment by altwaireb** [comment]
it work with me

@if (!empty($file))
    <div class="flex">
        <div>
            <button x-on:click="@this.removeUpload('file', '{{ $file->getFilename() }}')">
                 <x-icon-minus-circle class="text-gray-400 w-4 w-4 ml-1 mt-2"/>
            </button>
            <img src="{{ $file->temporaryUrl() }}">
        </div>
    </div>
@endif

**Comment by ThomasLaveto** [comment]
Ik ben afwezig tot maandag 9 januari. Neem bij spoed contact op met ***@***.***
