### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null.

### ISSUE THREAD

**Issue by jprangenbergde** [livewire/livewire#2019]
### Description

I have a table which is searchable. Every row have actions. Every action is an own component (nested components).
It does not matter if I have only one component in a row or several.

I got this error: ```Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null.```

### Exact steps to reproduce

What I have noticed so far: If I have a table of two rows with row "A" (first one) and "B" (second one) and I search for A (B disappears), and I delete the search again (B is added again) then everything works. If I search for B and A disappears, and I delete the search again (A is added again) then i got the error. 

### Stripped-down, copy-pastable code snippets

https://gist.github.com/jprangenbergde/6c3b65e3188de8c26d7f2ce94709612e

**Context**
- Livewire version: v2.3.1
- Laravel version: 8.11.2
- Browser: Version 86.0.4240.183

**Comment by jprangenbergde** [comment]
![screen-capture](https://user-images.githubusercontent.com/5179743/99062888-f7aae080-25a3-11eb-9303-77f9826481c1.gif)

**Comment by jprangenbergde** [comment]
I have found the error. I have to assign an unique id for each row: https://laracasts.com/discuss/channels/livewire/laravel-livewire-fingerprint-error?page=1#reply=664293.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
