### ISSUE TITLE
Binary string saved in model causes Livewire crash "Uncaught SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#2021]
### Description

- I have a model that saves a PDF within a binary database field.

```
  #attributes: array:14 [▼
    "id" => 1670
    "label_format" => "pdf_44"
    "raw_label" => b"%PDF-1.7\n1 0 obj\n<< /Type /Catalog\n/Outlines 2 0 R\n/Pages 3 0 R >>\nendobj\n2 0 obj\n<< /Type /Outlines /Count 0 >>\nendobj\n3 0 obj\n<< /Type /Pages\n/Kids ▶"
    "created_at" => "2020-11-13 11:40:04"
    "updated_at" => "2020-11-13 11:40:04"
  ]
```

- In livewire, this model is passed into a component.

```blade
<livewire:my-component :model="$model"/>
```

- We get a console error:

```
VM16585:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new Component (index.js:29)
    at index.js:73
    at index.js:502
    at walk (walk.js:5)
    at walk (walk.js:10)
    at walk (walk.js:10)
    at Component.value (index.js:493)
    at Component.value (index.js:69)
    at new Component (index.js:49)
Component @ index.js:29
(anonymous) @ index.js:73
(anonymous) @ index.js:502
walk @ walk.js:5
walk @ walk.js:10
walk @ walk.js:10
value @ index.js:493
value @ index.js:69
Component @ index.js:49
(anonymous) @ index.js:73
(anonymous) @ index.js:502
walk @ walk.js:5
walk @ walk.js:10
walk @ walk.js:10
walk @ walk.js:10
walk @ walk.js:10
value @ index.js:493
value @ index.js:69
Component @ index.js:49
(anonymous) @ index.js:78
value @ index.js:77
(anonymous) @ 60001590:1868
connector.js:3 console.re [error] Uncaught TypeError: Cannot read property '$wire' of undefined in /js/app.js?id=13c4212679e15112fdcd Line: 2
n @ connector.js:3
(anonymous) @ connector.js:3
e @ connector.js:3
t @ connector.js:3
d._dispatch @ connector.js:3
d.error.d.e @ connector.js:3
handleError @ connector.js:3
window.onerror @ index.js:1
error (async)
(anonymous) @ index.js:1
(anonymous) @ index.js:1
n @ index.js:1
(anonymous) @ index.js:1
MrTr @ index.js:1
n @ bootstrap:19
bUC5 @ app.js?id=13c4212679e15112fdcd:2
n @ bootstrap:19
0 @ app.js?id=13c4212679e15112fdcd:2
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ app.js?id=13c4212679e15112fdcd:2
alpine.js:1855 Uncaught TypeError: Cannot read property '$wire' of undefined
    at Livewire.value (index.js:30)
    at eval (eval at u (alpine.js:115), <anonymous>:5:25)
    at u (alpine.js:115)
    at de.evaluateReturnExpression (alpine.js:1694)
    at new de (alpine.js:1454)
    at alpine.js:1556
    at alpine.js:1538
    at e (alpine.js:87)
    at e (alpine.js:91)
    at e (alpine.js:91)
```

**Fix**

- To fix this outside of livewire, we can add this as a hidden attibribute:

```php
protected $hidden = ['raw_label'];
```

Maybe this is just what should be done to make it work in livewire?

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.6
- Browser: Chrome

**Comment by austenc** [comment]
@booni3 does this happen with any PDF or just certain ones? 

Would you be willing to make an example repository that we could use to easily reproduce the problem?

**Comment by austenc** [comment]
Your suggestion of making the attribute hidden is a good one. You wouldn't want Livewire to be passing around a serialized PDF in each request anyway. Something to note is that if a string is not [UTF-8 compatible in length](https://symfony.com/doc/current/components/var_dumper.html#dump-examples-and-output), Symfony's var dumper (which Laravel uses) will prefix the field's value with a `b`. This is shown in your example too -- `raw_label" => b"....` 

Not sure we can make Livewire serialize this in a predictable fashion, so I'm going to close this issue for now, and suggest making the attribute hidden (as you mentioned) for a workaround.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
