### ISSUE TITLE
Stripe Js disappear during validation

### ISSUE THREAD

**Issue by chokies** [livewire/livewire#2023]
### Description
if a field fails validation stripe js disappears

### Stripped-down, copy-pastable code snippets
`<form wire:submit.prevent="submit">
    <div class="mb-10">
        <div class="flex items-center mb-5">
            <div
                class="bg-blue-gray-darker font-bold text-xl text-center w-8 h-8 rounded-full mr-4 leading-8">
                1</div>
            <h3 class="text-xl tracking-tighter leading-none font-bold">How much would you like to
                donate?</h3>
        </div>

        <div class="flex items-center px-3">
            <h3 class="text-3xl font-bold mr-3">$</h3>
            <input
                wire:model="amount"
                class="text-3xl mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary font-bold"
                type="number" placeholder="5">
            <p>
        </div>
        @error('amount') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
    </div>

    <div class="mb-10">
        <div class="flex items-center mb-5">
            <div
                class="bg-blue-gray-darker font-bold text-xl text-center w-8 h-8 rounded-full mr-4 leading-8">
                2</div>
            <h3 class="text-xl tracking-tighter leading-none font-bold">Personal Information</h3>
        </div>

        <div class="flex flex-col lg:flex-row lg:space-x-5">
            <div class="mb-4 w-full">
                <label class="form-label" for="firstname">
                    First Name
                </label>
                <input wire:model="first_name"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                    id="firstname" type="text" placeholder="">
                @error('first_name') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
            </div>

            <div class="mb-4 w-full">
                <label class="form-label" for="lastname">
                    Last Name
                </label>
                <input wire:model="last_name"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                    id="lastname" type="text" placeholder="">
                    @error('last_name') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
            </div>
        </div>

        <div class="mb-4 w-full">
            <label class="form-label" for="email">
                Email Address
            </label>
            <input wire:model="email"
                class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                id="email" type="text" placeholder="">
            @error('email') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
        </div>

    </div>

    <div class="mb-10">
        <div class="flex items-center mb-5">
            <div
                class="bg-blue-gray-darker font-bold text-xl text-center w-8 h-8 rounded-full mr-4 leading-8">
                3</div>
            <h3 class="text-xl tracking-tighter leading-none font-bold">Payment Information</h3>
        </div>

        {{--  <div class="mb-4 w-full">
            <label class="form-label" for="address">
                Payment Method
            </label>
            <div class="inline-block relative w-full">
                <select name="country" id="country"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary">
                    <option value="Bank Account">Bank Account</option>
                    <option value="Credit Card">Credit Card</option>
                </select>
                <div
                    class="pointer-events-none absolute inset-y-0 right-0 flex items-center pt-2 px-3 text-gray-700">
                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20">
                        <path
                            d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                    </svg>
                </div>
            </div>
        </div>  --}}

        <div class="flex flex-col lg:flex-row lg:space-x-5">
            
        </div>

        <div class="flex flex-col lg:flex-row lg:space-x-5">
            <div class="mb-4 w-full">
                    <div id="card-element">
                            
                        </div>
                <label class="form-label" for="expirationmonth">
                    Expiration Month *
                </label>
                <input wire:model="expiry_month"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                    id="expirationmonth" type="text" placeholder="">
                    @error('expiry_month') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
            </div>

            <div class="mb-4 w-full">
                <label class="form-label" for="expirationyear">
                    Expiration Year *
                </label>
                <input wire:model="expiry_year"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                    id="expirationyear" type="text" placeholder="">
                    @error('expirationyear') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
            </div>

            <div class="mb-4 w-full">
                <label class="form-label" for="cvv">
                    CVV *
                </label>
                <input wire:model="cvv"
                    class="mt-2 appearance-none border rounded w-full py-3 px-5 text-gray-700 leading-tight focus:outline-none focus:border-blue-primary"
                    id="cvv" type="text" placeholder="">
                    @error('cvv') <span class="text-red-500 text-sm italic">{{ $message }}</span> @enderror
            </div>
        </div>
    </div>

    <div class="mb-10">
        <div class="w-full mt-5 mb-5 px-3">
            <p class="text-sm text-gray-400">By continuing, you agree to the terms and
                acknowledge receipt of our <a href="#" class="underline">privacy policy</a>.</p>
        </div>

        <div class="w-full mt-10 mb-5 px-3 text-right">
            <button
                class="bg-red-500 rounded-lg font-bold py-3 px-20 text-center text-white focus:outline-none w-full lg:w-auto">Donate
                Now</button>
        </div>

    </div>
</form>

@push('js')
<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe('pxxx');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
    base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
        color: '#aab7c4'
        }
    },
    invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
    }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
</script>
@endpush`
**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by chokies** [comment]
okay solved this by using wire:ignore

**Comment by joshhanley** [comment]
@chokies yep, was going to suggest wire:ignore.

If you have solved this, can you please close the issue?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
