### ISSUE TITLE
Livewire component disappears after attribute updates

### ISSUE THREAD

**Issue by ju5t** [livewire/livewire#2024]
### Description

I have a component that I want to use to edit a Laravel model. To make things easier, this model is a Quote, also because it literally is one.

On the QuoteEdit component I have two separate components:

```
<div>
    <x-input.group for="customer" label="Customer" borderless paddingless>
        <input wire:model="quote.customer_id" type="hidden">
        <livewire:select.customer :id="$quote->customer_id" />
    </x-input.group>
</div>

<div class="mt-5">
    <x-input.group for="user" label="User" borderless paddingless>
        <input wire:model="quote.user_id" type="hidden">
        <livewire:select.user :id="$quote->user_id" :parent="$quote->customer_id" />
    </x-input.group>
</div>
```

The idea being that you have two dropdown menu's; one with all the customers - the second a list of users who are employed by this customer. I'm not sure if this is the approach I should be after or if this could work, but this is out of scope for this issue.

Whenever the customer is updated, an event is triggered: `livewire-customer-updated` with an ID. The QuoteEdit component has a listener and it will set `$quote->customer_id` to the selected Customer ID.

As soon as this happens the content of the second component is gone.

I checked the response of the request coming back from Livewire and it does contain two objects, but there is something weird, the div container with mt-5 has a `style='display: none'`.

It doesn't matter what you do. The container that holds the second component gets that style attribute added onto it.

### Exact steps to reproduce

I will try to rebuild this into a small reproducible setup soon.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3
- Laravel version: 8.0
- Alpine version: 2.7.3
- Browser: Chrome and Safari

**Comment by ju5t** [comment]
🤦 

Sorry, forgot a closing tag somewhere, can't blame Livewire for losing it for a moment. All good now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
