### ISSUE TITLE
After installing livewire, Stack trace showing errors in cached php files, not in original blade.php views

### ISSUE THREAD

**Issue by almazdanilov** [livewire/livewire#2025]
### Description
If we have error inside View, Laravel shows blade.php file in Stack trace.
But after installing livewire, Laravel shows cached php file in Stack trace.

### Exact steps to reproduce
Install livewire according to documentation:
```
composer require livewire/livewire
```
After that make little mistake in welcome.blade.php, f.e. put {{$unknownVariable}} at the beginning of the file. Open website and in Stack trace you will see **Illuminate\View\Engines\CompilerEngine::handleViewException** in cached php file located in storage/framework/views/. But before installing Livewire, Laravel was showing **Illuminate\Foundation\Bootstrap\HandleExceptions::handleError** in welcome.blade.php. It's impossible to quickly trace errors when Stack trace shows them in cached files. Cached view files absolutely different than their source blade.php files.

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.10.0
- PHP Version: 7.4.12
- Browser: Chrome

**Comment by austenc** [comment]
Thanks for reporting this @almazdanilov. It's related to https://github.com/livewire/livewire/issues/711. 

The reason you're seeing this happen is that Ignition's (the Laravel error page) main compiler engine is not running.

Livewire registers a compiler engine override, and so does Ignition. Currently, Laravel only allows one of these, so Livewire is taking precedence and the extra nice stuff from Ignition isn't working. Unfortunately, it's not a simple fix. We'll leave this open and investigate it more as we explore other options.

**Comment by freekmurze** [comment]
We'll continue this in #2160 

Thanks for addressing this @austenc

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
