### ISSUE TITLE
PHP 8 Gives Type Error

### ISSUE THREAD

**Issue by elijahcruz12** [livewire/livewire#2030]
### Description
While testing out a website I created for being able to use PHP 8 on November 27th, U came across a type error. I was using PHP8.0.0RC3 and tried to use a livewire component that is just a form that creates A Client on my website. I'm okay with sharing actual code examples from this site to get things fixed.

### Exact steps to reproduce

On my staging version of my site, create an account, and try to create a client. [site](https://staging.ecfreelance.net)

Upon creating the client, it will throw a TypeError of:

````
TypeError
method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given
````

It appears to show the issue comes from `/livewire/livewire/src/HydrationMiddleware/HashDataPropertiesForDirtyDetection.php:49` which because I don't truly know livewire's actual code or how it works fully (know how to use, just not how it really works) I'd rather leave this to the contributors of Livewire.

### Stripped-down, copy-pastable code snippets

Here's some snippets of my code thta I used to create the client:

Client-Create.php (Inside the class)
````
        public $name;
        public $email;
        public $client;
        public $slug;

        protected $rules = [
            'name' => 'required|min:4',
            'email' => 'required|email',
        ];

        public function updated($propertyName)
        {
            $this->validateOnly($propertyName);
        }

        public function saveClient()
        {
            $validatedData = $this->validate();

            $this->client = Clients::create([
                'name' => $this->name,
                'user_id' => Auth::id(),
                'email' => $this->email,
                'slug' => hash('sha512', 'client' . $this->name . 'user' . Auth::id() . rand()),
            ]);

            session()->flash('clientcreated', 'Successfully have added: ' . $this->name . ' to your client list.');

            return redirect()->to('/clients');
        }

        public function render()
        {
            return view('livewire.dashboard.component.forms.client-create');
        }
````

client-create.blade.php
````
<form wire:submit.prevent="saveClient" class="mt-3">

    <div>
        <label for="name" class="block text-sm leading-5 font-medium text-gray-700">Name</label>
        <div class="mt-1 relative rounded-md shadow-sm">
            <input type="text" id="name" wire:model="name" class="form-input block w-full sm:text-sm sm:leading-5"
                   placeholder="John Doe">
            @error('name') <span class="error mt-1 mb-2 text-red-300">{{ $message }}</span> @enderror
        </div>
    </div>

    <div class="my-2">
        <label for="email" class="block text-sm leading-5 font-medium text-gray-700">Email</label>
        <div class="mt-1 relative rounded-md shadow-sm">
            <input type="text" inputmode="email" id="email" wire:model="email"
                   class="form-input block w-full sm:text-sm sm:leading-5" placeholder="john.doe@example.com">
            @error('email') <span class="error mt-1 mb-2 text-red-300">{{ $message }}</span> @enderror
        </div>
    </div>

    <div>
        <button type="submit"
                class="bg-indigo-600 hover:bg-blue-dark text-white font-bold py-3 px-3 rounded-lg hover:bg-indigo-500 transition ease-in-out duration-300 mt-3">
            Submit
        </button>
    </div>

</form>
````

**Context**
- Livewire version: [2.3.1]
- Laravel version: [8.14.0]
- Alpine version: [2.7.3]
- Browser: [Chrome Latest & Chrome Canary]

**Comment by joshhanley** [comment]
@elijahcruz12 Livewire doesn't fully support PHP 8. Please see this duplicate issue #2016.

My response on that threat is below for convenience. 

Hope this helps!

>Have a look at this PR #1933 for PHP8 support. Currently waiting on a dev dependency to be updated so Livewire tests can be run using PHP8 to see if anything breaks.

**Comment by elijahcruz12** [comment]
Alright sounds good. I'll just wait to update my PHP versions on my server until then.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by LordByron2019** [comment]
REOPEN

**Comment by joshhanley** [comment]
@LordByron2019 can you let us know why you reopened this? Are you having issues with Livewire and PHP 8? 

This issue was from before Livewire support for PHP 8 was tagged. If you are having issues on the latest 2.3.5 with PHP 8, please raise an issue.

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
