### ISSUE TITLE
Bind to accessor always keep the initial value

### ISSUE THREAD

**Issue by ClementN** [livewire/livewire#2031]
### Description

When I bind the input to an accessor (even a hardcoded array) the input always reloads the initial value of the accessor after typing any new value into the input.

Anyone else encountered this problem?

### Exact steps to reproduce ( the simplified context )

**In the model file, I created an accessor to be used by Livewire to bind an input.**

```
    public function getProductColorsNamesAttribute()
    {
        return ['red', 'yellow'];
    }  
```

**In the Livewire component, the property is defined as a bound Model:**

```public Product $currentProduct;```

**I added a rule to validate the input**

```    
public function rules() { return [
        'currentProduct.product_colors_names.*' => 'min:2',
    ]; }
```

**The input field in the livewire component view**

```
    <div>

        <input type="text" wire:model="currentProduct.product_colors_ids.0" />

        @if($errors->has('currentProduct.product_colors_ids.0'))
            <span>{{ $errors->first('currentProduct.product_colors_ids.0') }}</span>
        @endif

    </div>
```

### The problem 

is that the input always keeps the initial ```'red``` value doesn't matter what I type in.  

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.11.2
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by austenc** [comment]
Hi @ClementN, 

You'd need to use an actual model attribute (preferably one that maps to a database field) to do something like this. This isn't a bug with Livewire, it's just how accessors work. You cannot set them directly like you're trying.  

Here's an example. Say your database has a `products.colors` attribute. You could use a combination of an accessor and mutator to accomplish some "casting":

```
function getProductColorsAttribute() {
    // notice that this is mapping to the database field
    return $this->colors; // you could do additional manipulation or work here if you'd like 
}

function setProductColorsAttribute($value) {
    $this->colors = $value;
}
```

Caleb did something similar in the Surge data tables series with the `dateForEditing` variable. If you're sponsoring him, you might check out those videos!

**Comment by ClementN** [comment]
Thank you very much, @austenc . 

I will close the issue as it is not a bug 
and I will look into the Surge videos. 

Once again, thank you for your time.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by austenc** [comment]
@ClementN Hopefully that works for you, cheers! 🍻

**Comment by Bakusedu** [comment]
I also fell into this bug and unfortunately i haven't still found my way through it, i am mutating my models attribute using mutators but its not updating in my blade file, when i dump the attribute everything i am able to see the new value but my blade file still retains the attributes original value
