### ISSUE TITLE
Bootstrap pagination not working 

### ISSUE THREAD

**Issue by greatsami** [livewire/livewire#2032]
@calebporzio 
Hi

Today I updated Laravel 8 with bootstrap and I used livewire pagination 
Also I set in AppServiceProvider Paginator::useBootstrap()

But not implemented with livewire 

I updated it manually in WithPagination class

Best regards

**Comment by austenc** [comment]
@greatsami please provide more information about the error you're receiving, or a repository we can clone to reproduce the issue, thank you!

**Comment by greatsami** [comment]
@austenc 
Thank you for your reply 

Actually , No errors found. but when I using bootstrap as I mention in my post.

I wrote in AppServiceProvider.php in boot function 
Paginator::useBootstrap();

In posts.php livewire component
I add  use WithPagination;

when I run the code 
everything is Ok, but pagination load tailwind code

I updated lines 30 and 35 from tailwind to bootstrap in this file in my project.
https://github.com/livewire/livewire/blob/master/src/WithPagination.php

and it is working with bootstrap pagination files.

Thank you

**Comment by luisangeldev** [comment]
I got, the same error. If i remove `use WithPagination;` works but without the livewire power ups!

**Comment by calebporzio** [comment]
Thanks for the heads up.

According to the Livewire docs, you can use a "$paginationTheme = 'bootstrap'" property to set this in Livewire.

Livewire currently doesn't honor the global Laravel paginator settings.

Here's the bit from the docs. Thanks

https://laravel-livewire.com/docs/2.x/pagination#custom-pagination-view

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
