### ISSUE TITLE
Echo listener with custom broadcastAs() not working

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2033]
### Description
If you set a custom name for your event using `broadcastAs()` then the `echo:{channel},{event}` listener does not work.

### Exact steps to reproduce
1) Make an event
2) Change the name of the event using broadcastAs(), for example:

```
public function broadcastAs(){
        return 'myeventname';
    }
```

3) Setup listener in your Livewire component, for example:

```
protected $listeners = ["echo:channelname,myeventname" => 'doSomething'];
```

It does not work and `doSomething` is never triggered.

### Workaround

Remove your custom event name from the event and use the default only, it now works.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.13.0
- Browser: Chrome

**Comment by MiracleInNutShell** [comment]
Hey try adding dot(.) Before your event name like this "echo:channel,.event"
