### ISSUE TITLE
Files count validation didn't work (File uploads)

### ISSUE THREAD

**Issue by juno-w** [livewire/livewire#2038]
### Description
I want to validate user upload maximum of 2 files but unable to validate `$files` array property using `array|max:2` and custom validation. Validation for single file is working when the property rules is `files.*` but not `files`. I even tried to create custom rule from `artisan make:rule` to just `dd()` the `$value` passed in upon validation. It shows an array of files but the validation will just pass no matter what. Yes, I purposely `return false;` on the custom rule just to fail the validation but it passed.
### Exact steps to reproduce
1. Validate `'files' => 'array|max:2'`
2. Validate using custom rule, purposely `return false;`
3. Validate using `count($value) <= 2` in the passes method.
### Stripped-down, copy-pastable code snippets
```php
// Livewire component
public $files = [];

public function updatedFiles()
{
    $this->validate($this->rules);
}

public function getRulesProperty()
{
    return [
        'files' => [new MaxItems], // Custom rule
        'files.*' => ['nullable', 'file', 'max:1024'],
    ];
}
```
```php
// Custom rule to fail the validation
public function passes($attribute, $value)
{
    return false;
}
```
```html
// Blade
<input type="file" wire:model="files" multiple />
```
Validation rules above will just pass no matter what. Expected to fail.

**Context**
- Livewire version: [e.g. 2.3.1]
- Laravel version: [e.g. 8.14.0]
- Alpine version: [e.g. 2.7.3]
- Browser: Chrome

**Comment by juno-w** [comment]
Problem solved, it's my mistake didn't display error validation.

It should be
```blade
@error('files.*')...@enderror
@error('files')...@enderror
```

instead of 
```blade
@error('files.*')...@enderror
```

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
