### ISSUE TITLE
Version 2.3.2 strips keys when saving json arrays

### ISSUE THREAD

**Issue by erikwestlund** [livewire/livewire#2042]
### Description

I have a data structure where I key arrays using numbers that align with indices.

For example, here's some JSON that gets saved:

```
{"grid_content": {"1": [628], "2": [687], "3": [631], "4": [632, 694], "5": [634], "6": [635], "7": [636], "8": [637], "9": [642, 643], "10": [644], "11": [648, 649], "12": [650], "13": [651], "14": [652]}, "primary_content": {"1": [685]}}
```

Notice how I rely on those keys to line up the arrays with specific IDs.

On version 2.3.2, when I save this data, it strips out the keys, and I get something like this:

```
{"grid_content": [[745], [746]]}
```

Notice how the "1" and "2"s are gone.

This is a problem if you want to use a JSON object to save a data structure where the key numbers matter.

The culprit is the changes to NormalizeDataForJavascript. There is an assumption here -- I think -- that numeric keys won't be meaningful, but I do not think that is a good baseline assumption as it restricts you from being able to use numeric keys in a precise way, or having gapped keys that are meaningful. 

My old way of managing this was if I wanted to get rid of the keys, I'd explicitly do `values()` on a collection before it gets serialized. If I wanted to keep the keys, I wouldn't, and it'd save the keys.  My intuition is that it's better to keep that flexibility.

### Exact steps to reproduce

In 2.3.1, save a keyed array in a property, then save to database.

Try again 2.3.2.

Alternatively, just swap the contents of NormalizeDataForJavaScript from 2.3.1 to 2.3.2 and try. 

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.11.2

**Comment by danharrin** [comment]
Hey Erik, I authored the changes to NormalizeDataForJavaScript for v2.3.2.

If you would like to help fix your issue, check out [this commit](https://github.com/livewire/livewire/pull/1859/files#diff-95cc0b5b4811dc26b81481ccfa60688a86119df67739808c04b63c11096d2300), and try and tweak my refactor to better align to the original `uksort()` behaviour. Also, submitting a PR that contains a failing test would be great, since this is an edge case.

Many thanks!

**Comment by olivM** [comment]
i got the exact same issue.
and the fact it appears for a patch release is very problematic

**Comment by erikwestlund** [comment]
Dan,
Can you explain the purpose of the commit? can you show me desired
behavior of data in and data out?


On November 17, 2020, Naveen Kumar <notifications@github.com> wrote:
> Hey Erik, I authored the changes to NormalizeDataForJavaScript for
> v2.3.2.
>
> If you would like to help fix your issue, check out this commit
> <https://github.com/livewire/livewire/pull/1859/files#diff-
> 95cc0b5b4811dc26b81481ccfa60688a86119df67739808c04b63c11096d2300>, and

> try and tweak my refactor to better align to the original uksort()
> behaviour. Also, submitting a PR that contains a failing test would be

> great, since this is an edge case.
>
> Many thanks!
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/livewire/livewire/issues/2042#issuecomment-
729265376>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABRWPMPNV4IICGXVLEBALKDSQL6BLANCNFSM4TZAARIA>.

**Comment by adamthehutt** [comment]
+1 This broke my code as well.

**Comment by nuernbergerA** [comment]
Hey guys,

can you try my fix and see if the problem is gone?

**Comment by olivM** [comment]
your patch is working well for me !

**Comment by danharrin** [comment]
Hey @erikwestlund, firstly, apologies for any issues the change caused you. To answer a few of your questions...

> Can you explain the purpose of the commit? can you show me desired behavior of data in and data out? Is the goal to solve the checksum issue with key re-ordering?

The changes I made fixed a very weird issue with arrays of greater than 16 items, losing their order when reindexed.

> Were I to take a crack at this, would there be any reason to stick to base php? This seems easiest solved using a collection pipeline and that would probably be more readable.

I originally used a collection for this fix, but I encountered quite a few performance issues with larger arrays, so stuck to using built-in PHP functions.

> Also, I don't think this qualifies as an edge case. Using numbers as keys is a perfectly sensible thing to do. [...] I think it's justifiable to argue that we *shouldn't* use numbers as keys in public properties, especially because PHP handles keys as part of an array natively, whereas JS you need to use an object. This is one of the reasons we get the checksumming issue. However, this is not to my knowledge an official stance.

Completely agree with you here and you're correct, using custom numeric array keys is justifiable but probably not a "best practice", and does lead to other issues as you mention. Personally, I'd argue that using arrays of greater than 16 items is probably more common than using arrays with custom numeric keys, but that's definitely up for debate. 😁

Adrian's solution looks perfect here, good job 👏

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
