### ISSUE TITLE
URL friendly notation for array model as queryString

### ISSUE THREAD

**Issue by jochemgruter** [livewire/livewire#2043]
When I use array nested data binding, and I use this data field as a queryString, then Livewire makes an unfriendly URL notation.

### Example
HTML data model
`<input type="text" wire:model="filter.type">`

Setup the query string in the component:
`protected $queryString = ['filter'];`

URL Result:
`/orders?filter%5Btype%5D=order`

My suggestion is to make this a friendly URL. For example, make filter.type as filter-type= in the URL query.

**Comment by mdavis1982** [comment]
@calebporzio I opened a discussion about what this could look like in a component if you've got time to have a look at all? The discussion is here: https://github.com/livewire/livewire/discussions/2036

**Comment by calebporzio** [comment]
Thanks, let's keep the discussion to the discussion page.

Personally this isn't too big of a deal to me.

I'd be good with a clean PR that makes things prettier if someone put the leg work in to make sure there are no edge cases and all browsers are good with the URLs.

It's too low of a priority for me to do anything about it though right now.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
