### ISSUE TITLE
Cannot read property 'fingerprint' of null, fixed with `:key="time()"` 

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#2044]
### Description

As in the title, this is coming from a nested component when calling "$refresh" after a model has been updated.

### Exact steps to reproduce

I am working on a way to reproduce this. My setup is a few nested components that are causing the issue. It may well be that I have another error in the general layout but adding the `time()` key does fix it, so I think that shows there is maybe scope for making things more durable?

### Fix

As in https://github.com/livewire/livewire/issues/1686#issuecomment-699140799, adding `time()` to the component key fixes the issue... but I am unsure why.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.2
- Laravel version: 8.3
- Browser: Chrome

**Comment by erikwestlund** [comment]
This is a diffing issue. it's often caused when a div is added or removed based upon a condition in your component. Do you have any conditionally displayed HTML in your component? If so, try wrapping it in divs and/or adding wire:keys to those divs.

**Comment by booni3** [comment]
Thanks Eric. 

Yes I am aware of the diffing issues. By standard, I always wrap every `@if` in a set of DIV's and also try to avoid using `@if @else` because they cannot be wrapped. I have not tried adding `wire:keys` to these divs but I do generally add an `id=""` to them which I found did a similar thing.

Maybe I should try keys...

**Comment by RoccoHoward** [comment]
It's a common issue - and lands at the top of https://laravel-livewire.com/docs/2.x/troubleshooting when dealing with any type of dom refresh.

**Comment by calebporzio** [comment]
Closing this. Thanks for helping everyone! (I plan on making improvements to morphdom in the future that should hopefully eliminate things like this)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
