### ISSUE TITLE
Blade convert array keys if key is number as string.

### ISSUE THREAD

**Issue by lao9s** [livewire/livewire#2049]
Example:

```
 public function mount()
 {
       $this->blocks = ['6' => 'Hero', '15' => 'Contact'];
 }
```

In blade will be:

`[0 => 'Hero', 1 => 'Contact']`

**Comment by ahinkle** [comment]
Also seeing this from latest 2.3.1 -> 2.3.2 update. Pretty obscure bug for those using value => label pairs.

**Comment by jochemgruter** [comment]
Noticed the same. Since version 2.3.2

**Comment by psos** [comment]
Same, need to revert  to 2.3.1.

2.3.2 unstable.

**Comment by nuernbergerA** [comment]
Hey guys,

can you try my fix and see if the problem is gone?

**Comment by kendalltristan** [comment]
@nuernbergerA Works for me.

**Comment by ahinkle** [comment]
Thanks, @nuernbergerA ! Works for me

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
