### ISSUE TITLE
window.livewire.devTools is not a function

### ISSUE THREAD

**Issue by quaidesbalises** [livewire/livewire#2050]
### Description

Since last update (2.3.2) when debug mode is enable, I've got this console error and nothings work :  

```Uncaught TypeError: window.livewire.devTools is not a function```  

<img width="633" alt="Capture d’écran 2020-11-18 à 21 15 20" src="https://user-images.githubusercontent.com/25004867/99583046-39dc8380-29e3-11eb-9955-f7cf0a692b59.png">

<img width="438" alt="Capture d’écran 2020-11-18 à 21 15 32" src="https://user-images.githubusercontent.com/25004867/99583043-3812c000-29e3-11eb-9eac-1a57df6403a8.png">

**Context** 
- Livewire version: 2.3.2
- Laravel version: 8.15.0
- Alpine version 2.7.3
- Browser: Chrome

**Comment by albertorsesc** [comment]
Facing the same issue.

**Comment by albertorsesc** [comment]
Fixed it by publish the assets and add the post-autoload-dump key (I guess this is why it is suggested lol). 

See https://laravel-livewire.com/docs/2.x/installation under **_Publishing Frontend Assets_**

**Comment by joshhanley** [comment]
@quaidesbalises can you try @albertorsesc solution and let us know if it fixes your issue?

**Comment by calebporzio** [comment]
This seems fixed, closing. Thanks everyone

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by quaidesbalises** [comment]
Hi everyone, thanks for your feedback. @albertorsesc you're right, my apologies, didn't notice this part of the install section

**Comment by albertorsesc** [comment]
@quaidesbalises no problem mate, we both missed it.

**Comment by BikerYamaha** [comment]
Same problem with upgred from v1.3.5 to v1.3.7.

![image](https://user-images.githubusercontent.com/6223111/113355006-649af900-9340-11eb-8cd0-b0e19a172dc0.png)

Also nothing works.
