### ISSUE TITLE
TrimString middleware causing checksum issues

### ISSUE THREAD

**Issue by julienarcin** [livewire/livewire#2059]
### Description

I traced back a checksum problem when my public properties are string containing spaces at the beginning/end.

### Exact steps to reproduce

```
class Component {

    public $test;

    public function mount() {
        $this->test = '    my string     ';
    }
}
```

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.15.0
- Alpine version: ?
- Browser: Tested on Chrome + Safari

**Comment by julienarcin** [comment]
Seems like the TrimString middleware is the source of the problem.

Reference: https://github.com/livewire/livewire/issues/354#issuecomment-552514576

**Comment by julienarcin** [comment]
I found the origin of the problem.

My Laravel Middlewares (including TrimStrings) are in App\Http\Middleware\Template

And in LivewireServiceProvider, line 78 :

```
// Bypass specific middlewares during Livewire requests.
// These are usually helpful during a typical request, but
// during Livewire requests, they can damage data properties.
$this->bypassTheseMiddlewaresDuringLivewireRequests([
    TrimStrings::class,
    ConvertEmptyStringsToNull::class,
    // If the app overrode "TrimStrings".
    \App\Http\Middleware\TrimStrings::class,
]);
```

So in my specific case, the Middleware is not bypassed by Livewire.

**Comment by julienarcin** [comment]
I created a PR here: https://github.com/livewire/livewire/pull/2060

**Comment by austenc** [comment]
Closing this issue for now (and for reasons mentioned in #2060), but please reopen if you'd like to continue the discussion or propose another approach for making Livewire respect middleware in atypical locations. 

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
