### ISSUE TITLE
Datepicker With livewire model

### ISSUE THREAD

**Issue by permadi123qwe** [livewire/livewire#206]
**Hello , My name Riyan**

I have new uses for livewire and I just made <input wire: model = "datebuat" type = "text">

then I use datepicker bootraps, and I get a problem after I set the datepicker and fill in another input form with wire: model = "plu" which occurs after filling in wire: model = "plu" ,

value in the <input wire: model = "datebuat" type = "text"> missing and  iam set with validate   a some eror  meesage colom require, I'm confused about how to use datepicker + livewire +laravel because here there are some computers still using old browsers mozilla version 52.es09 that don't support html5,how to fix that  thanks

**Comment by lancepioch** [comment]
Is this still an issue? If it is, could you help provide more information and some code so that this can be reproduced?

**Comment by suretarget** [comment]
Livewire working fine with bootstrap datepicker.  You need to set **wire:ignore**
[https://laravel-livewire.com/docs/third-party-libraries/](https://laravel-livewire.com/docs/third-party-libraries/)

**Comment by bryanbelardo** [comment]
Hi. I have the same problem on datepicker on laravel livewire it seems that livewire model can't get the data from datepicker plugin.
I solve it by using the normal input type="date".
Hope this helps. 👍

**Comment by snapey** [comment]
I got the component working by triggering an input event
```
<input 
    wire:model="taskduedate"
    type="text" class="form-control datepicker" placeholder="Due Date" autocomplete="off"
    data-provide="datepicker" data-date-autoclose="true" data-date-format="mm/dd/yyyy" 
    data-date-today-highlight="true"                        
    onchange="this.dispatchEvent(new InputEvent('input'))"
>
```

**Comment by Richard2012** [comment]
I can confirm that snapey's solution works on Laravel 11 with Bootstrap 5 and jquery-ui.css
