### ISSUE TITLE
Previewing uploaded SVG image does not work

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [livewire/livewire#2061]
Trying to preview an uploaded svgfile with $img->temporaryUrl() doesn't work.
The response generated by the FilePreviewHandler always contains the header Content-Type: application/javascript 
For a png or jpg, this is no problem because Chrome or Edge will render it regardless.
But when used with an svg the image is not rendered.

Tested on Laravel 8.14 and livewire 2.3.2

**Comment by austenc** [comment]
This should be fixed in the next version, thanks for reporting it!

See #2230

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
