### ISSUE TITLE
Laravel Package Development - Livewire assets don't load

### ISSUE THREAD

**Issue by jeroenvanrensen** [livewire/livewire#2062]
### Description

I'm creating a Laravel Package and I want to use Livewire. But the blade directive (`@livewireStyles`) do not get replaced with a CSS file in my browser.

### What I did

1. `composer install`
2. `composer require livewire/livewire`
3. Add `@livewireStyles` to `layouts/app.blade.php`

### Stripped-down, copy-pastable code snippets

Head section of `layouts/app.blade.php`

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@yield('title') - MoonPHP</title>

    <link href="{{ asset('moonphp/css/app.css') }}" rel="stylesheet" />
    @livewireStyles
</head>
```

### Context
- Livewire version: [2.3]
- Laravel version: [8.12]
- Alpine version: [2]
- Browser: [Firefox]

**Comment by jeroenvanrensen** [comment]
Okay so I forgot to run `composer update`...

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
