### ISSUE TITLE
Dynamic loading of Alpine component function

### ISSUE THREAD

**Issue by IP-Developer** [livewire/livewire#2063]
### Description
I'm trying to implement a multi-step checkout component that uses dynamic livewire components based on selected step (that is present in query string): `@livewire('checkout.steps.'.$step)`.  The main thing I'm trying to achieve is separation of Alpine functions per component. A typical checkout step looks like this:
```
<div x-data="step1()">

    <a wire:click.prevent="previousStep()">Return</a>

    <a wire:click.prevent="nextStep()">Continue</a>

</div>

<script>
function step1() {
    return {};
}
</script>
```

It works well on initial load, but when loaded dynamically Alpine can't find the function used in x-data, no matter where I place it.

### Exact steps to reproduce
https://laravelplayground.com#/snippets/92a8e1b7-10ef-4e2b-a7bf-aff374f2ee7f

Try clicking "Next step" and watch the browser console.

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.15.0
- Alpine version: CDN latest
- Browser: any

**Comment by IP-Developer** [comment]
Okay, I think I found a solution. Assigning the Alpine component functions directly to `window` seems to solve the problem. Working example: https://laravelplayground.com/#/snippets/357a711c-00b8-4c8c-a2db-c2e8c0b45618

**Comment by joshhanley** [comment]
@IP-Developer if you have found a solution, can you please close your issue? In future, I would suggest opening up a discussion for things like this first as the isn't a bug with Livewire and more of an implementation issue.

If you're still having troubles, please let us know!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by sahakyanArt** [comment]
Not working with alpinejs@3.9 and livewire@2
