### ISSUE TITLE
Entangle not updates everytime

### ISSUE THREAD

**Issue by Javierko** [livewire/livewire#2064]
### Description
Hey, I was trying to setup a Pikaday as Caleo has in his surge project. But now I found out a problem that the value is updated first time, second time it's not working (no XHR request is sent) and for the third time it works fine as in first time. Fourth time is same as second time, nothing is sent.

I also tried another events that Pikaday provides, `onClose` which was the same as `onOpen`, and `onSelect`, but that one ruined it completely.

### Exact steps to reproduce
Just open Pikaday, click for first time, value updates, second time, not updates, third time, updates as normally.

### Stripped-down, copy-pastable code snippets`
Component
```html
<div
    x-data="{ date: @entangle($attributes->wire('model')) }"
    x-init="new Pikaday({ field: $refs.input, format: 'MM/DD/YYYY', onOpen() { this.setDate($refs.input.value) } });"
    x-on:change="date = $event.target.value"
>
    <input
        {{ $attributes->whereDoesntStartWith('wire:model') }}
        x-ref="input"
        x-bind:value="date"
        class="form-control"
    />
</div>
```
Livewire page
```html
<x-input.group>
    <x-input.date wire:model="filter" placeholder="MM/DD/YYYY" autocomplete="off" />
</x-input.group>
```
Livewire page controller
```php
public $filter = '';
```

**Context**
- Livewire version: [e.g. 2.3.2]
- Laravel version: [e.g. 8.11.2]
- Alpine version: [e.g. 2.7.3]
- Browser: [e.g. Edge (running on Chromium)]

**Comment by joshhanley** [comment]
There is a bug with the new version please see PR #1968

**Comment by lightwalkernet** [comment]
Can confirm - If I revert to Livewire version 2.3.1 then @entangle work consistently. But 2.3.2 @entangle is intermittent

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
