### ISSUE TITLE
Listening for events on presence channel: Echo.join(...)[event_name] is not a function

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#2065]
Trying to listen for an event on a presence channel and get this error:

> LaravelEcho.js:38 Uncaught TypeError: Echo.join(...)[event_name] is not a function

Here is my code:

    protected $listeners = [
        'echo-presence:lobby,MatchMade' => 'matchMade',
    ];

If this is incorrect, how do I properly listen for events on a presence channel via the listeners property?

**Comment by joshhanley** [comment]
I've investigated this issue and will try to summarise the main problem here as it has been raised a few times (listed for reference) #1845, #1075, #1074. 

I also found an article where they had to work around this issue using Alpine to implement the listen events, which doesn't feel very clean to me: https://medium.com/@zachvv11/real-time-chat-room-with-larasocket-tailwind-alpine-livewire-and-laravel-406a8c5e680d 

## Problem

Laravel Echo currently has 4 main methods when interacting with a presence channel:
- here
- joining
- leaving
- listen

For the first three methods, the signature is only one parameter which is a closure, which we can currently use in Livewire using the listeners property:
```php
protected $listeners = [
        'echo-presence:demo,here' => 'here',
        'echo-presence:demo,joining' => 'joining',
        'echo-presence:demo,leaving' => 'leaving',
    ];
```

But the method signature for `listen` has two parameters, the first is the event class name, and the second is a closure. So currently, you cannot do the below with a presence channel as listen is not specified anywhere:
```php
protected $listeners = [
        'echo-presence:demo,SomeCustomEventClass' => 'newMethod',
];
```
Which is what is then causing this error as (using the above example) it is trying to call:
```js
Echo.join(...)['SomeCustomEventClass']
```
> LaravelEcho.js:38 Uncaught TypeError: Echo.join(...)[event_name] is not a function

What it should call is:
```js
Echo.join(...)['listen']('SomeCustomEventClass', (e) => {...})
```

## Proposed Solutions

The echo-presence signature should be changed to be able to specify when is it both the listen method and what event it should listen for.

One option is to append the event name to the end of the signature after appending listen like:
```php
'echo-presence:demo,listen,SomeCustomEventClass' => ...
```

The problem with that is the current signature special syntax is `'echo:{channel},{event}' => '{method}'`
Which then would change just for this action and look like `'echo:{channel},{action},{event}' => '{method}'` which is inconsistent.

Or another potential option is to actually have a new "channel" defined specifically for presenceListen, such as:
```php
'echo-presenceListen:demo,SomeCustomEventClass' => ...
```

This would also be easier to implement as you don't need to change the way the event parts are constructed, instead just add another conditional for the new channel type.

@calebporzio I'm happy to PR a fix for this, but would like some feedback as to what would be preferable.

Hope this helps!

**Comment by redbastie** [comment]
Or we can just detect the default presence listener names in the codebase and use the existing syntax for those, otherwise use the `listen` syntax. This is the simplest and cleanest solution.

**Comment by joshhanley** [comment]
@redbastie good idea, that's much cleaner!

**Comment by davidpiesse** [comment]
Hey all,
When I wrote the Echo code this was the biggest issue I hit.

It seems this code is wrong.
```js
  } else if (channel_type == 'presence') {
      Echo.join(channel)[event_name](e => {
          store.emit(event, e)
      })
  }
```
In the Laravel docs it has
```js
Echo.join(`chat.${roomId}`)
    .here(...)
    .joining(...)
    .leaving(...)
    .listen('NewMessage', (e) => {
        //
    });
```
So the code cannot currently understand the listen part of a presence channel...
IIRC I tried to get this working but never did...

**Comment by Wulfheart** [comment]
Any update on this?
/sparkle
