### ISSUE TITLE
How do I customize validation rules that except "Required, String" and so on?

### ISSUE THREAD

**Issue by carveybunt** [livewire/livewire#2073]
- Livewire version: 2.3
- Laravel version: 8.12

guys, I need to customize some rules of validation, but I did not find some solution on the document of Livewire. For example, I need to customize the rule as a mobile phone number by regex，I already had the regex how can I realize that. Thanks a lot for who will help me!

**Comment by thatsenam** [comment]
```
 $this->validate([
            'phone' => 'required|regex:/(01)[0-9]{9}/',
      ]);
```
Hope that would help you.

**Comment by carveybunt** [comment]
> ```
>  $this->validate([
>             'phone' => 'required|regex:/(01)[0-9]{9}/',
>       ]);
> ```
> 
> Hope that would help you.

Thanks a lot, that is working. But I got the error:  "preg_match(): No ending delimiter '/' found" by the regex: " /(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|17[0-9]|18[0-9])\d{8}/ " . Also, I mean can make some rules like the method of Laravel by the command with make: rule, because I will use the rule on other validation files.

**Comment by thatsenam** [comment]
@carveybunt you may remove the '/' at the end of regex

**Comment by carveybunt** [comment]
> @carveybunt you may remove the '/' at the end of regex

I yet tried that got the error: `preg_match(): No ending matching delimiter ')' found
`. I can't remove the ')' because it's a whole.

**Comment by thatsenam** [comment]
Since your regex has a pipe in it, you have to use an array:

public static $rules_save = [
    'class_subjects' => ['required', 'regex:/[0-9]([0-9]|-(?!-))+/'],
];
From the docs:

When using the regex pattern, it may be necessary to specify rules in an array instead of using pipe delimiters, especially if the regular expression contains a pipe character.

**Comment by carveybunt** [comment]
> Since your regex has a pipe in it, you have to use an array:
> 
> ```
> public static $rules_save = [
>     'class_subjects' => ['required', 'regex:/[0-9]([0-9]|-(?!-))+/'],
> ];
> ```
> 
> From the docs:
> 
> When using the regex pattern, it may be necessary to specify rules in an array instead of using pipe delimiters, especially if the regular expression contains a pipe character.

Can you have any method to use or require some files to realize that? Because I can't found any way for a solution on docs, and I need to use the regex for validation on other components of livewire too.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
