### ISSUE TITLE
Session Expired in Laravel Package Development

### ISSUE THREAD

**Issue by thatsenam** [livewire/livewire#2074]
### Description
I am using livewire in a laravel package that will plug into a laravel project. I succefully integrated Livewire in my package. The error i am fetching is **This page has expired due to inactivty** when i click a button that is binded to a component method.
I added csrf token in my base file like  `<meta name="csrf-token" content="{{ csrf_token() }}" />`

### Exact steps to reproduce

- Create a package inside a laravel project.
- Just Render a Component From Package Route(Follow the normal implementation of livewire).
- Render from packages route file  `Route::get('/acc/test', VoucherComponent::class);`
- While Rending template from livewire php component make sure to add packagename before the view name like this 

```
public function render()
    { 
        return view('acc::livewire.voucher-component')->layout('acc::layouts.app'); 
    }
```

### Stripped-down, copy-pastable code snippets

**Dependencies**
```
        "php": "^7.3|^8.0",
        "illuminate/support": "^8.15",
        "livewire/livewire": "^2.3",
        "fruitcake/laravel-cors": "^2.0"
```
- Browser: [ Chrome,]

**Comment by austenc** [comment]
@thatsenam Using package views should work fine, but without seeing your layout, it's hard to tell what you might be doing wrong. 

Please provide more code (`acc::layouts.app`) and/or a public repository to help us reproduce this.

**Comment by austenc** [comment]
Closing until more information is given on how to reproduce the issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
