### ISSUE TITLE
Blade Component  not updated after event trigger

### ISSUE THREAD

**Issue by SystemApp-scrl** [livewire/livewire#2083]
### Description
I have the following component and i want to show the updated data, after i call the **changeTipo** event. The event is triggered using global Javascript, and the render method is called. Dev tools show the updated data returned from server, but visually nothing change.

### Stripped-down, copy-pastable code snippets
```html
<div>
    <div id="modal-generazione-doc" class="ui modal">
        <div class="header">Genera Documento in Mexal</div>
        <div class="content">
            <form class="ui form" method="post">
                @csrf

                <div class="inline nine fields">
                    <div class="three wide field">
                        <select id="select-tipi-doc" class="ui selection dropdown" name="tipi-documenti">
                            <option value="">Sigla Doc.</option>
                            @foreach($tipiDocumenti as $tipo)
                                <option value="{{ $tipo["value"] }}">{{ $tipo["value"] }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="two wide field">
                        <div class="ui input">
                            <input type="number" placeholder="Sezionale" name="sezionale">
                        </div>
                    </div>

                    <div class="two wide field">
                        <div class="ui checkbox disabled @if($currentTipo['numAuto']) checked @endif">
                            <input type="checkbox" name="num-auto" @if($currentTipo['numAuto']) checked="checked" @endif>
                            <label>Num. Auto</label>
                        </div>
                    </div>

                    @if(!$currentTipo['numAuto'])
                        <div class="two wide disabled field">
                            <div class="ui input">
                                <input type="number" placeholder="Numero" name="numero">
                            </div>
                        </div>
                    @endif
                </div>
            </form>
        </div>
        <div class="actions">
            <div class="ui approve button">Genera</div>
            <div class="ui cancel button">Annulla</div>
        </div>
    </div>
</div>
```

```php
<?php

namespace App\Http\Livewire;

use App\Repository\ImpostazioniRepositoryInterface;
use Livewire\Component;

class ModalGenerazioneDoc extends Component
{
    private ImpostazioniRepositoryInterface $impostazioniRepository;
    public $tipiDocumenti;
    public array $currentTipo;

    protected $listeners = ['changeTipo'];

    public function mount(ImpostazioniRepositoryInterface $impostazioniRepository) {
        $this->impostazioniRepository = $impostazioniRepository;
        $this->tipiDocumenti = $impostazioniRepository->getList("tipi_doc")->map(function ($el) { return json_decode($el, true); });
        $this->currentTipo = array('value' => '', 'numAuto' => true, 'tipo' => 'C');
    }

    public function changeTipo() {
        $this->currentTipo = $this->tipiDocumenti->first(function($el) {
            return $el['value'] == $this->currentSigla;
        });
    }

    public function render()
    {
        return view('livewire.modal-generazione-doc');
    }
}
```

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.15.0
- Alpine version: 2.7.0
- Browser: Firefox

**Comment by iksaku** [comment]
Livewire doesn't listen for Javascript-sent events, unless you manually specify it.

As per your description, you're firing the `changeTipo` event form JS directly, but do you do it via Livewire's event emitters or do you fire a traditional JS event?

For more information on firing events to Livewire, please [refer to Livewire's Documentation on Events](https://laravel-livewire.com/docs/2.x/events#from-js)

**Comment by michele-grifa** [comment]
> 
> 
> Livewire doesn't listen for Javascript-sent events, unless you manually specify it.
> 
> As per your description, you're firing the `changeTipo` event form JS directly, but do you do it via Livewire's event emitters or do you fire a traditional JS event?
> 
> For more information on firing events to Livewire, please [refer to Livewire's Documentation on Events](https://laravel-livewire.com/docs/2.x/events#from-js)

I use Livewire.emit

**Comment by iksaku** [comment]
Could you provide the snippet where you fire that event? It is not included in your reference snippets.

Also, providing a [Laravel Playground](https://laravelplayground.com/#/) with a reproducible snippet of this bug could help tracking down your issue :wink:

**Comment by SystemApp-scrl** [comment]
I resolved. The problem was that the component contains a modal, i removed the html for the modal and it worked

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
