### ISSUE TITLE
property does not refresh in the internal components

### ISSUE THREAD

**Issue by mrtdeh** [livewire/livewire#2086]
Take a look at the following examples:

showPost.blade.php:
```
<div>
    <livewire:content-box :content="$post"/>

    <button wire:click="nextPost" >Next Post >></button>
</div>
```

and
content-box.blade.php :

```
<div>
    <h1>{{ $content->title }}</h1>
    <p>{{ $content->content }}</p>
</div>
```

So far, it is completely clear what is going to happen ...: First, the information of the content to be viewed is received through **showPost** and passed to the **contentBox**, and everything is OK ..

Well now I want to get the information of the next content via the account through the button I put and calling the **nextPost** method:

```

class ShowPost extends Component
{
    public Post $post;

    public function render()
    {

        return view('livewire.show-post');
    }

    public function nextPost()   
    {
        $id = $this->post->id;
        $nextPost = Post::where('id', '>', $id)->first();
        $this->post = $nextPost;
    }

...

```
But nothing happens and the **contentBox** component has no reaction .... Has anyone had this problem ???!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
