### ISSUE TITLE
syncInput ran twice per request

### ISSUE THREAD

**Issue by Francismori7** [livewire/livewire#2088]
### Description
It seems that the syncInput updates are ran twice

### Exact steps to reproduce
Update property that is wire:model.

### Stripped-down, copy-pastable code snippets
```
{
// ...
"updates":[{"type":"syncInput","payload":{"name":"divisionContext","value":"02"}},{"type":"syncInput","payload":{"name":"divisionContext","value":"02"}}]
}
```

Not so sure what's going on, Livewire sends twice the same data in each request.

**Comment by joshhanley** [comment]
@Francismori7 can you provide some more information and code?

What Livewire and Laravel versions are you using? Are you using Alpine and if so what version?

If you are using Alpine and using @entangle directives, there can be some issues with it doubling up on requests depending on which versions you are using.

**Comment by calebporzio** [comment]
Closing due to no response. Thanks Josh for following up!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
