### ISSUE TITLE
Wire:loading with wire:target not working correctly after multiple clicks

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2092]
There appears to be a problem with wire:loading and wire:target.

For example see my code below, in this example it is expected that when clicking the "Pause" or "Resume" button the normal icon disappears and the *spinner* icon will appear during load, but this only happens on the first time of clicking.  For subsequent clicks the icon either doesn't hide, or the spinner doesn't appear.

```
@if($package->hasStatus('Active'))
    <button type="button" class="btn btn-warning" wire:click="pause" wire:loading.attr="disabled"> <i class="icon-pause mr-1" wire:loading.remove wire:target="pause"></i> <i class="icon-spinner spinner mr-1" wire:loading wire:target="pause"></i> Pause Package</button>
@elseif($package->hasStatus('Paused'))
    <button type="button" class="btn btn-success" wire:click="resume" wire:loading.attr="disabled"><i class="icon-play mr-1" wire:loading.remove wire:target="resume"></i> <i class="icon-spinner spinner mr-1" wire:loading wire:target="resume"></i> Resume Package</button>
@endif

```

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.3.1]
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@AdvancedStyle it sounds like it could be a morphdom issue, try adding wire:key="active" to the first button and wire:key="pause" to the second button and see if that fixes the issue.

If that doesn't work, can you make a laravelplayground.com to demonstrate the issue?

**Comment by AdvancedStyle** [comment]
Here is an example on laravelplayground: https://laravelplayground.com/#/snippets/d7445841-af0f-4346-a7d9-e2de06bc6c53

**Comment by joshhanley** [comment]
@AdvancedStyle thanks! That really helps!

Have a look here for working demo https://laravelplayground.com/#/snippets/36471994-595c-473d-8062-2444ab464cfe

Basically what I had to change was a couple of things:
1. Wire:loading won't work on `<i>` tags, as they need to be on block level elements like divs, p, etc. So I wrapped them in divs and that works.
2. I had to add wire:key to each of the buttons, as the wire:loading worked fine for pause (after the above changes) but wouldn't work for resume. This is due to morphdom thinking it was the same button and not re-registering the listeners properly. But adding wire:key it tells morphdom that those buttons are different with different actions.

Hope this helps!

**Comment by AdvancedStyle** [comment]
Thanks, i've now got it working using your tips, but it seems like such a lot of extra markup just to make something relatively simple work.  Having wire:loading work on all elements would make a lot more sense.  Here is my final **bulky** code for just 3 buttons; it does work but talk about bloated...:

```
@if($package->hasStatus('Active'))
    <button type="button" class="btn btn-warning" wire:click="pause" wire:loading.attr="disabled" wire:key="pause">
        <div wire:loading.remove wire:target="pause" class="float-left"><i class="icon-pause mr-1"></i></div>
        <div wire:loading wire:target="pause" class="float-left"><i class="icon-spinner spinner mr-1"></i></div>
        Pause Package
    </button>
@elseif($package->hasStatus('Paused'))
    <button type="button" class="btn btn-success" wire:click="resume" wire:loading.attr="disabled" wire:key="resume">
        <div wire:loading.remove wire:target="resume" class="float-left"><i class="icon-play mr-1"></i></div>
        <div wire:loading wire:target="resume" class="float-left"><i class="icon-spinner spinner mr-1"></i></div>
        Resume Package
    </button>
    <button type="button" class="btn btn-danger" wire:click="cancel"  wire:loading.attr="disabled" wire:key="cancel">
        <div wire:loading.remove wire:target="cancel" class="float-left"><i class="icon-stop mr-1"></i></div>
        <div wire:loading wire:target="cancel" class="float-left"><i class="icon-spinner spinner mr-1"></i></div>
        Cancel Package
    </button>
@endif
```

**Comment by joshhanley** [comment]
@AdvancedStyle Cool! 

In that instance I would be making a blade component which could clean that up quite a bit. 

Have a look at the `$attributes->wire('click')` method for getting the action of wire:click to populate in your component. See it here https://laravel-livewire.com/docs/2.x/alpine-js under `Accessing Livewire Directives From Blade Components` section

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
