### ISSUE TITLE
@entangle not firing Livewire network request each time the checkbox is clicked

### ISSUE THREAD

**Issue by jeffchown** [livewire/livewire#2095]
### Description
Further to multiple posts I've read here regarding the issue when using `@entangle` with a custom checkbox input control, I thought I'd try to help with an example that recreates the issue I am experiencing.

### Exact steps to reproduce
Whenever I try to use @entangle with AlpineJS in a custom checkbox input, I'm finding:
- the first time I click on the checkbox, everything works as expected
- the second click, no Livewire network request is fired
- the 3rd click, no Livewire network request is fired
- the 4th click, the network request is fired and everything is once again in sync
- this pattern seems to remain consistent e.g. every 3rd click the checkbox works

### Stripped-down, copy-pastable code snippets
Http/Livewire/TestForm.php
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class TestForm extends Component
{
    public $no_entangle;
    public $with_entangle;


    public function render()
    {
        return view('livewire.test-form');
    }
}
```

views/livewire/test-form.blade.php
```html
<div>
    <form>

        {{-- example of custom checkbox using Livewire V1.x method (no @entangle) --}}
        <div
            wire:model="no_entangle"
            x-data="{ checked: $wire.get('no_entangle') }"
            @click="
                checked = ! checked;
                $dispatch('input', checked); 
            " 
            class="flex items-center h-6"
        >
            <input 
                type="checkbox"
                :checked="checked"
                class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
            />
            <div class="ml-3 text-sm font-medium text-gray-700">
                    No Entangle 
                    (
                        Livewire value =  {{ $no_entangle ? 'true' : 'false' }}, 
                        Alpine value =  <span x-text="checked ? 'true' : 'false'"></span>
                    )
            </div>
        </div>

        {{-- example of custom checkbox using Livewire V2.x method (*with* @entangle) --}}
        <div
            x-data="{ checked: @entangle('with_entangle') }"
            @click="checked = ! checked" 
            class="flex items-center h-6"
        >
            <input 
                type="checkbox"
                :checked="checked"
                class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
            />
            <div class="ml-3 text-sm font-medium text-gray-700">
                    With Entangle 
                    (
                        Livewire value =  {{ $with_entangle ? 'true' : 'false' }}, 
                        Alpine value =  <span x-text="checked ? 'true' : 'false'"></span>
                    )
            </div>
        </div>
    </form>
</div>
```

Screenshot when 2nd checkbox is out-of-sync:

![image](https://user-images.githubusercontent.com/42819001/100288910-bae8cd00-2f45-11eb-9be8-6372e578c759.png)

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.15.0
- Alpine version: 2.7.3
- Browser: Brave

### Thoughts

I haven't done a deep-dive into the Livewire code, but noticed the network requests that are fired for each scenario are different:

- for no_entangle, the payload = `updates: [{type: "syncInput", payload: {name: "no_entangle", value: true}}]`
- for with_entangle, the payload = `updates: [{type: "callMethod", payload: {method: "$set", params: ["with_entangle", true]}}]`

The more I use Livewire, the more I enjoy working with it (Thanks @calebporzio !) and I'm looking forward to using `@entangle` throughout my code as it provides a much simpler and cleaner way to code custom inputs that utilize Alpine JS.  I hope there's a way to make it work reliably in the scenario I've shown here.

Thanks.

**Comment by joshhanley** [comment]
@jeffchown thanks for taking the time to detail the problem properly!

There is a regression in the way entangle works in 2.3.2, so I'd recommend using 2.3.1 if you need it for the moment. See PR #1968

**Comment by jeffchown** [comment]
You're welcome, @joshhanley - and thanks for the quick response!

I had seen that PR, but unfortunately, after downgrading my livewire to 2.3.1 and the problem still occurs (after clearing all caches - browser and Laravel, and doing a hard refresh)

**Comment by jeffchown** [comment]
@joshhanley I just tried both livewire 2.3.0 and 2.2.9 as well with the same (incorrect) results.  If you were able to get my example to work, could you please provide your config/context versions?

**Comment by joshhanley** [comment]
I have a test app that's running 2.3.2, so I copied your code in and, yep, get the same, error. But then I downgraded it to 2.3.1 and it works fine.

So to downgrade I ran this and that worked:
```
composer require livewire/livewire:2.3.1
php artisan view:clear
composer dump-autoload
```

You probably don't need the composer dump-autoload, but I like to throw it in there just incase!

**Comment by jeffchown** [comment]
@joshhanley Thanks for the confirmation that you got it to work.  Very strange on my end - those are exactly the steps I took (and just tried again) and I still have the same problem even when using 2.3.1.  I tried it on multiple browsers all with clean caches.

Looks like I'll have to try it on a clean Laravel app.  Won't have time to do that tonight, so I'll be in touch again tomorrow.  Any idea when the regression will be fixed and merged to master?

**Comment by joshhanley** [comment]
@jeffchown do you publish your assets? As I don't. But if you do, try republishing the assets after the downgrade and see if that fixes it.

I've pushed up my repo here if you want to have a play with that https://github.com/joshhanley/LivewirePlayground/tree/entangleDowngrade

Not sure, I'm not smart enough to fully wrap my head around the entangle watchers, so it's something Caleb will have to fix. I've tried a couple of times to understand it, but there's just too much going on, that I wouldn't want to unintentionally break!

**Comment by jeffchown** [comment]
@joshhanley I couldn't wait until tomorrow ;)  I do, and I did (republish my assets)

I just created a brand new Laravel app and can confirm that the problem exists in livewire 2.3.2 and that reverting to livewire 2.3.1 **does** fix the problem.  Thanks for your help with this.! Now I just have to figure out why the downgrade to 2.3.1 didn't work in my main app...

I hear you re the entangle watchers... if I have time to do a deep-dive and am able to find anything, I'll let you know.

**Comment by joshhanley** [comment]
@jeffchown haha nice! 

Bugger! I wonder what's going on, so strange. 

Also not sure if you use discord, but if you do, jump on the Livewire discord, can be easier for trying to troubleshoot strange issues like this, just post up in the help channel https://discord.gg/livewire

Cool! Will be good to understand it better. My handle is hanley on discord, if you do end up having a look, send me a message! I've got a an idea of whats causing it, just not how to fix it.

**Comment by jeffchown** [comment]
@joshhanley Definitely strange...

Thanks for the tip re: discord.  Going to step back from it for a bit (probably missing something obvious) - will post an update if/when I figure it out.

Will do! (re: discord)

**Comment by jeffchown** [comment]
Morning @joshhanley - I finally got my reversion back to livewire 2.3.1 to work.

I took the 'kitchen sink' approach and:
- `rm -rf public/vendor/`
- `rm -rf vendor/`
- `composer require livewire/livewire:2.3.1`
- `composer install`
- `composer dump-autoload`
- `composer cc`
- `php artisan view:clear`
- *did not re-publish livewire assets
- cleared browser cache

Voila.  The example from my original post now works within my main app.

I do suspect it had something to do with published assets per one of your previous comments - I must have missed something the first couple of times around.

Thanks again for your help.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@jeffchown morning for me now here 😬

Good to hear you got it working! Haha if in doubt, nuke everything, and start again.

Yeah that's why I personally don't publish the assets as that is just another thing you need to make sure that gets updated each time, when theres no real benefit to publishing the Livewire scripts and styles.

**Comment by jeffchown** [comment]
@joshhanley which puts you where?  Australia?

Thanks.  I normally try not to publish assets either but did earlier in this app as part of my evaluation of Livewire.

I'm still experiencing some inconsistent behaviour in my custom checkbox inputs (using Tailwind UI elements and Alpine) but believe I've now moved onto the issue with booleans that has been described in another Livewire issue post...

**Comment by joshhanley** [comment]
@jeffchown yup! 😁

Ah yeah fair enough. So there is a bug with checkboxes and booleans that are assigned to a model property, that I am going to submit a failing test for (it's written), but ran into this bug on master. Hence can't create and run the new test against master, to confirm it fails as I expect it to fail, as it fails due to this issue anyway 😆

This is a thread with that problem https://github.com/livewire/livewire/discussions/1952

If what your experiencing is similar, have a look here as to what's happening https://github.com/livewire/livewire/issues/1761#issuecomment-722066719

**Comment by jeffchown** [comment]
UPDATE: Per my comment on #1761 , I just tested Livewire 2.3.4 with my @entangle'd version of my custom Livewire checkbox/toggle input component and all seems to be working now 👍 😄 

After a bit more testing, looking forward to the convenience of creating more custom inputs using @entangle + wire:model!

Thanks @joshhanley for your help and Thanks @calebporzio for the updates!
