### ISSUE TITLE
Table binding data be deleteed record then add new reocrd again, wire fingerprint lose again.

### ISSUE THREAD

**Issue by sueboy19** [livewire/livewire#2098]
### Description
Table binding Data like order. Have add and delete function.

1. Only Add action is OK.
2. Only Delete action is OK.
3. Add then Delete is OK.

4. Delete then Add have problems.
  4.1 Delete finish. Component have run mount and render. Add record, Data binding show get problem: Lost fingerprint.
  4.2 Delete finish. Component have run mount and render. Refresh Page again. Component still and run mount and render. Add record, Data binding show is OK.

Try to add wire:key in test.blade.php, still get error.

```php
<tr data-entry-id="{{ $part->id }}" wire:key="part{{ $part->id }}"> 
```

### Exact steps to reproduce

web.php
```php
Route::group(['prefix' => 'order', 'as' => 'order.', 'middleware' => ['auth']], function () {
    Route::get('/test', App\Http\Livewire\Part\TestForm::class);
});
```

TestForm.php
```php
<?php

namespace App\Http\Livewire\Part;

use App\Models\Part;
use Gate;
use Livewire\Component;
use Symfony\Component\HttpFoundation\Response;

class TestForm extends Component
{
    public function mount()
    {

    }

    public function render()
    {
        return view('livewire.part.testform');
    }
}
```
TestForm.blade.php
```php
@extends('layouts.app')
@section('content')
    @livewire('part.test')
@endsection
```
Test.php
```php
<?php

namespace App\Http\Livewire\Part;

use App\Models\Order;
use App\Models\Part;
use Livewire\Component;
use Illuminate\Session\SessionManager;

class Test extends Component
{
    public $order;

    public function mount(SessionManager $session)
    {
        info('test mount');
        $session->put("backUrl", '/client/test');
    }

    public function render()
    {
        info('test render');
        $this->order = Order::findOrFail(7);

        return view('livewire.part.test');
    }

    public function addrec()
    {
        info('addrec');

        $part = Part::Create([
            'order_id' => 7,
            'qty' => 1,
        ]);
        $part->no = strtoupper('TOTC'.str_pad(dechex($part->id), 3, '0', STR_PAD_LEFT));
        $part->save();
    }
}
```
test.blade.php
```php

<div>
    <button class="btn btn-info  m-1" wire:click="addrec">
        {{ trans('global.add') }} 
    </button>
    
    @if (session()->has('message'))
        <div class="alert alert-success" role="alert">
            <div class="flex">
                <div>
                    <p class="text-sm">{{ session('message') }}</p>
                </div>
            </div>
        </div>
    @endif
    <div class="stable2">
    <!-- <div class="table-responsive"> -->
        <table class="table table-borderless table-striped table-hover datatable datatable-order">
            <thead>
                <tr>
                    <th>
                        NO <br /> Name <br /> Number 
                    </th>
                    <th>
                        &nbsp; <!-- action -->
                    </th>
                </tr>
            </thead>
            <tbody>
            @foreach($order->parts as $key => $part)
            <tr data-entry-id="{{ $part->id }}" wire:key="part{{ $part->id }}"> {{-- wire:key="{{ $part->id }}" --}}
                <td>
                    <div data-title="NO">{{ $part->no ?? '' }}</div>
                    <div data-title="Name">{{ $part->name ?? '' }}</div>
                    <div data-title="Number">{{ $part->qty ?? '' }}</div>
                </td>
                <td>
                    <div data-title="action" class="action">
                        <div>
                            @livewire('part.delete', ['id' => $part->id, 'path' => 'path', 'path_arr' => ['path']], key('delete'.$part->id))
                        </div>
                    </div>
                </td>
                
            </tr>
            @endforeach
            </tbody>
        </table>          
    <!-- </div> -->
    </div>
</div>
```
![delete_add_error](https://user-images.githubusercontent.com/6514381/100300567-42c7e900-2fd1-11eb-9123-255d8b62e8c9.png)

01 Add
![01_add](https://user-images.githubusercontent.com/6514381/100302154-aef81c00-2fd4-11eb-945f-d37e58c0d4ff.gif)

02 Delete
![02_delete](https://user-images.githubusercontent.com/6514381/100302663-c2f04d80-2fd5-11eb-82c0-998364f61278.gif)

03 delete -> add
![03_delete_add](https://user-images.githubusercontent.com/6514381/100302234-d353f880-2fd4-11eb-83a0-6971ee90d546.gif)

04 delete -> refresh page -> add
![04_delete_refreshPage_add](https://user-images.githubusercontent.com/6514381/100302457-54ab8b00-2fd5-11eb-9272-a43e5e54a5ad.gif)

### Stripped-down, copy-pastable code snippets

**Context**
- PHP version: 7.4.11
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Alpine version: -
- Browser: Chrome 86.0.4240.111

**Comment by sueboy19** [comment]
Find out solution. Use span replace div.

```php
<div class="stable2">
```

```php
<span class="stable2">
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
