### ISSUE TITLE
Uncaught TypeError: Cannot read property '$wire' of undefined

### ISSUE THREAD

**Issue by didaputraa** [livewire/livewire#2104]
- Livewire version: [e.g. 2.3.1]
- Laravel version: [e.g. 7.29.3]

- Browser: [e.g. Chrome]

first , i visit page X and secondary visit page Y. this is showing error $wire of undefined index line 30 from livewire.

why is that ?

the livewire old version 1 ,there are no problem.

**Comment by joshhanley** [comment]
@didaputraa make sure that Livewire scripts (which are at the end of the body tag) are first before any other JavaScript libraries.

If you can't get that to work, can you share your layout file?

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
