### ISSUE TITLE
Changing Default Class Namespace to "App" is getting error in livewire.php config

### ISSUE THREAD

**Issue by theonly27** [livewire/livewire#2107]
### Description
I want to change the Default Livewire Directory from `"App\\Http\\Livewire" ` to "App" but it is getting error

### Exact steps to reproduce
Go to livewire.php in config folder.
Change the default value of class_namespace to "App"
and execute the command below

`php artisan livewire:discover`

and this error will show

The "C:\laragon\www\my_project\app/App" directory does not exist.

if I change it to null or empty string, the generated class namespace will also be 

`namespace \Component\Component;`

any work around for this? Thank you.

**Context**
- Livewire version: [e.g. 2.3.1]
- Laravel version: [e.g. 8.3.1]
- Browser: [MS Edge]

**Comment by xyNNN** [comment]
I've an identical issue. I've moved my Laravel kernel/application from app/ to src/App ... all works fine. But resolving the Livewire components give an error.

The "src/App/Http/Livewire" directory does not exist. (View: /app/resources/views/website/index.blade.php)

The directory exists, the autoloading is correct. I don't know why this happen. it's weird.

Any one knows why?

Thanks!

**Comment by nathanjansen** [comment]
A workaround I applied is overwriting the LivewireComponentsFinder:

```php
class LivewireServiceProvider extends ServiceProvider
{
    public function register()
    {
        // Rather than forcing users to register each individual component,
        // we will auto-detect the component's class based on its kebab-cased
        // alias. For instance: 'examples.foo' => App\Http\Livewire\Examples\Foo

        // We will generate a manifest file so we don't have to do the lookup every time.
        $defaultManifestPath = $this->app['livewire']->isOnVapor()
            ? '/tmp/storage/bootstrap/cache/livewire-components.php'
            : app()->bootstrapPath('cache/livewire-components.php');

        $this->app->singleton(LivewireComponentsFinder::class, function () use ($defaultManifestPath) {
            return new LivewireComponentsFinder(
                new Filesystem,
                config('livewire.manifest_path') ?: $defaultManifestPath,
                static::generatePathFromNamespace(
                    config('livewire.class_namespace', 'Support\\Livewire')
                )
            );
        });
    }

    public static function generatePathFromNamespace($namespace)
    {
        return app('path') . DIRECTORY_SEPARATOR . str_replace('\\', DIRECTORY_SEPARATOR, $namespace);
    }
}
```

**Comment by theonly27** [comment]
> A workaround I applied is overwriting the LivewireComponentsFinder:
> 
> ```
> class LivewireServiceProvider extends ServiceProvider
> {
>     public function register()
>     {
>         // Rather than forcing users to register each individual component,
>         // we will auto-detect the component's class based on its kebab-cased
>         // alias. For instance: 'examples.foo' => App\Http\Livewire\Examples\Foo
> 
>         // We will generate a manifest file so we don't have to do the lookup every time.
>         $defaultManifestPath = $this->app['livewire']->isOnVapor()
>             ? '/tmp/storage/bootstrap/cache/livewire-components.php'
>             : app()->bootstrapPath('cache/livewire-components.php');
> 
>         $this->app->singleton(LivewireComponentsFinder::class, function () use ($defaultManifestPath) {
>             return new LivewireComponentsFinder(
>                 new Filesystem,
>                 config('livewire.manifest_path') ?: $defaultManifestPath,
>                 static::generatePathFromNamespace(
>                     config('livewire.class_namespace', 'Support\\Livewire')
>                 )
>             );
>         });
>     }
> 
>     public static function generatePathFromNamespace($namespace)
>     {
>         return app('path') . DIRECTORY_SEPARATOR . str_replace('\\', DIRECTORY_SEPARATOR, $namespace);
>     }
> }
> ```

Thank you for the response, but I think it's not recommended to change or edit the livewire core because every release, it may remove the changes.

**Comment by nathanjansen** [comment]
No problem, this is actually not so much changing the core. You can simply add this as a ServiceProvider in your own codebase and it will only change the filesystems settings.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joserick** [comment]
I have had the same problem so I have created a package which allows you to load components from different namespaces, note that this is only for livewire 3.

[Laravel Livewire Discover - https://github.com/joserick/laravel-livewire-discover](https://github.com/joserick/laravel-livewire-discover)

``` php
public function boot(): void
{
	// Load multiples namespace for Livewire components.
	Livewire::discover('Namespace\\Livewire', 'my-components');
	Livewire::discover('User\\Repository\\Livewire', 'new-components');
	...
}
```
``` html
<livewire:my-components-devices />
<livewire:new-components-devices-table />
```
