### ISSUE TITLE
Update version at packagist

### ISSUE THREAD

**Issue by FoksVHox** [livewire/livewire#2108]
### Description
At packaigst.org it says that Livewire needs 7.2.5, and that makes Composer fail when you try to install Livewire on PHP8
### Exact steps to reproduce
- Go on to packagist.org
- Search for livewire
- Find the PHP version on the package
- See that it says 7.2.5

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.16.0

**Comment by joshhanley** [comment]
@FoksVHox that's correct as PHP8 support was only merged into master a couple of days ago, but it hasn't been tagged yet. It will get tagged with the next release of Livewire.

You can use composer to pull dev-master in the meantime to test it. If you do, please report your findings!

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
The latest version has been tagged and supports PHP 8
