### ISSUE TITLE
How can I set default value inside loop and calculate them?

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [livewire/livewire#2110]
### Description
My scenario is you can see the image

![prob](https://user-images.githubusercontent.com/48278861/100398931-f5a05180-307a-11eb-8db2-839ac728de4f.PNG)

here, how can I set the default value in the `quantity` field? and I want when I change the `quantity` the total amount will be updated how can I achieve this? here you can see my quantity field is an array I catch it like `addComboProductsInTable.{{ $comboKey }}.quantity`  help me, please

### blade

```blade
@foreach ($addComboProductsInTable as $comboKey => $comboProduct)
    <tr>
      <td class="p-1">
         {{ $comboProduct['name'] }}
      </td>
      <td class="p-1">
        <input type="text" wire:model.defer="addComboProductsInTable.{{ $comboKey }}.quantity" class="form-control" placeholder="Qty" style="width: 50%">
        <br>
        <span class="badge badge-primary">{{ $comboProduct['unit']['name'] }}</span>
      </td>
      <td>
        @php($total += $comboProduct['selling_price'])
         $ {{ $comboProduct['selling_price'] }}
      </td>
      <td class="p-1">
          $ 700
      </td>
      <td class="p-1">
        <button type="button"  wire:click.prevent="removeComboProductFromTable({{ $comboKey }})" class="btn btn-xs btn-danger">
           <i class="bx bx-plus rotate-45"></i>
        </button>
      </td>
   </tr>
@endforeach
```

### component

```php
public $addComboProductsInTable = [];
```

**Comment by joshhanley** [comment]
@ShekhSaifuddin007 I've replied in your discussion #2106 🙂 . Can you please close this issue and we will work on it there?

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
