### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by ju5t** [livewire/livewire#2111]
PHP 8 support is in master. Is this tested enough to make it to a release or can I help test some things? Let me know if I can do anything.

**Comment by joshhanley** [comment]
@ju5t can never have enough testing! If you have the time, can you pull master and see if it's doing everything you expect? I believe it's all ready to go, so just depends on when Caleb is ready to tag the next version.

Would be great to hear how you go if you do test it!

**Comment by syntafin** [comment]
Any ETA there when this will released?

**Comment by joshhanley** [comment]
Not sure when Caleb will tag the next release, but it will be in the next one.

**Comment by calebporzio** [comment]
Thanks @ju5t , it's tagged now

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ju5t** [comment]
> Thanks @ju5t , it's tagged now

Awesome, thanks!
