### ISSUE TITLE
2.3.2 version issue in arrays

### ISSUE THREAD

**Issue by mik3Angel** [livewire/livewire#2112]
Hi, I have a issue that happen when I update to the version 2.3.2 that is I have a group a foreach of checkbox when I mark one of them I save that value using wire:model in the last version I don't have any problem but in new update I mark a checkbox and change to unchecked and the firt element of my initial set is now checked and when I check another one the second element of my set of checkbox is now checked is like the model that I assign the values of my set of checkbox now count the total of values that I have in that array

I put a screenshot part of my code, I change de version of livewire 2.3.1 and the behavior of that part of my code works fine
I just want to know if is a issue that is resolve or it will be in next release

![captura](https://user-images.githubusercontent.com/33241284/100489405-a0475d00-30d9-11eb-9bfa-72e09de66903.png)

**Comment by nuernbergerA** [comment]
Try `dev-master` and see if it's fixed by  #2058

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Fix has been tagged, thanks @nuernbergerA!
