### ISSUE TITLE
While trying to update a form, if a file is selected, the radio and select tag values are set back to NULL

### ISSUE THREAD

**Issue by mesushanta** [livewire/livewire#2113]
### 
I tried to update a row which has an image. If I do not select new image to update and make changes only in other fields, then there is no problem, But If i select image then, the radio and option select fields are set back to NULL. 

### 
```
      if(!$this->form['img']) {
          $image = $this->img_name;
        }
        else {
          $imgname = Str::random(40);
          $image = $imgname.'.png';
          $this->form['img']->storeAs('public', 'uploads/'.$image);
        }

```
```
         <div class="my-3">
            <label class="mb-2 text-md text-gray-500" for="">Image</label>
            <input wire:model="form.img" class="block my-2" type="file">
            @error('form.img')
            <span class="text-red-700 text-sm font-light">{{ $message }}</span>
            @enderror
          </div>

```

  
      <div class="mt-8">
            <label class="mb-2 text-md text-gray-500 block" for="">Supplement</label>
            <select wire:model="form.supplement" class="my-2 px-4 py-3 w-64 h-12 border border-gray-400 outline-none focus:border-blue-400">
              <option value="1">Available</option>
              <option value="0">Not Available</option>
            </select>
          </div>

          <div class="mt-8">
            <label class="mb-2 text-md text-gray-500" for="">Eat In</label>
            <div class="flex mt-3">
              <div class="flex items-center  mr-4 mb-4">
                <input id="eatin1" type="radio" name="eat" wire:model="form.eat" value="1" class="hidden" />
                <label for="eatin1" class="flex items-center cursor-pointer">
                 <span class="w-4 h-4 inline-block mr-1 border-blue-900 rounded-full border border-grey"></span>
                 Available</label>
               </div>

               <div class="flex items-center mr-4 mb-4">
                <input id="eatin0" type="radio" name="eat" wire:model="form.eat" value="0" class="hidden" />
                <label for="eatin0" class="flex items-center cursor-pointer">
                 <span class="w-4 h-4 inline-block mr-1 border-blue-900 rounded-full border border-grey"></span>
                 Not Available</label>
               </div>
            </div>
          </div>
```
**Context**
- Livewire version: [e.g. 2.3]
- Laravel version: [e.g. 8.12]
- Browser: [Chrome, Safari]

**Comment by austenc** [comment]
@mesushanta Could you please provide code that we can copy-and-paste to immediately reproduce this bug? Alternatively, creating a public repository that we could clone would be very helpful.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
