### ISSUE TITLE
Stale action after redirecting back

### ISSUE THREAD

**Issue by rodrigopedra** [livewire/livewire#2114]
### Description

When an action returns a redirect, if a user clicks the browser's back button, and click the button to trigger the action again, nothing happens.

Works fine in Chrome. Fails in Firefox (Developer 84.0b5) and Safari (iOS 14).

### Exact steps to reproduce

1. Create a component and add an action that returns a redirect to any other page
2. On the component's view  add a `<button>` that triggers that action
3. Navigate to the page that renders the component
4. Click the button and wait for redirect
5. Click browser's back button
6. Click the button again, nothing happens, there is no network tab activity

### Stripped-down, copy-pastable code snippets

~~~bash
laravel new livewire-test
cd livewire-test
composer require livewire/livewire
php artisan livewire:publish --assets
php artisan make:livewire Home
~~~

Add this routes:

~~~php
<?php

// ./routes/web.php

use Illuminate\Support\Facades\Route;

Route::get('/', \App\Http\Livewire\Home::class);
Route::get('/redirected', fn() => 'ok');
~~~

Component's code:

~~~php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Home extends Component
{
    public function redirectMe()
    {
        return redirect()->to('/redirected');
    }
    
    public function render()
    {
        return view('livewire.home');
    }
}
~~~

Component's template:

~~~
<div>
    <button wire:click="redirectMe">redirect me</button>
</div>
~~~

Add this layout view `./resources/views/layouts/app.blade.php`

~~~
<head>
    @livewireStyles
</head>
<body>
{{ $slot }}

@livewireScripts
</body>
~~~

Same as from docs: https://laravel-livewire.com/docs/2.x/rendering-components#page-components

**Context**
- Livewire version: v2.3.2
- Laravel version: v8.16.1
- Alpine version: N/A
- Browser: Firefox (Developer 84.0b5) and Safari (iOS 14). works on Chrome.

**Comment by rodrigopedra** [comment]
I tested with updated dependencies.

- On Chrome it never fails.
- On Safari it always fail. 
- On Firefox it works most of the times, if you click the button and the browser's back button repeatedly, it will eventually fails.
  - From the network tab it sees that when the history back action loads from cache it will fail. If it reloads it won't. 
  - Maybe adding a `performance` javaScript event and try to reset the state when loading from history should do the trick.
  - Unfortunately I am not familiar with Livewire's JavaScript codebase to have a hint on how to fix this. If someone could shed some light I could give a try and work a PR.

**Context (updated)**

-  Livewire version: v2.3.5
-  Laravel version: v8.20.0
-  Alpine version: N/A
- Browser: Firefox (Developer 85.0b5) and Safari (iOS 14). works on Chrome.

**Comment by RobertCordes** [comment]
This is actually a huge deal. Does anybody have an idea how to fix this?

**Comment by joshhanley** [comment]
I've experimented with this and can confirm the issue happens on Safari even with v2.3.8 (see screenshot).

![recording (8)](https://user-images.githubusercontent.com/882837/105661023-816e1700-5f20-11eb-8fa7-9a17933f3d33.gif)

So it looks like this isn't actually a Livewire problem, it's an issue with how Safari handles browser cache and how it loads from cache when you hit the back button, even if you have set no-cache headers (like my comment here https://github.com/livewire/livewire/issues/2334#issuecomment-759114918).

The way to work around this for Safari specifically, is to put this at the top of your head tag

```html
<head>
    <script>
        (function() {
            window.onpageshow = function(event) {
                if (event.persisted) {
                    window.location.reload();
                }
            };
        })();
    </script>
    <!-- Rest of head stuff here -->
</head>
```

See these links for details:
https://gomakethings.com/fixing-safaris-back-button-browser-cache-issue-with-vanilla-js/
https://stackoverflow.com/a/46714639/14909455
    
Hope this helps!

**Comment by RobertCordes** [comment]
Thanks @joshhanley this is working great!

**Comment by calebporzio** [comment]
Thanks @joshhanley !

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
