### ISSUE TITLE
mount lifecycle hooks not working in multiple traits

### ISSUE THREAD

**Issue by ClementN** [livewire/livewire#2115]
### Description

When mount lifecycle hooks are used in multiple traits, only the last one is executed.

### Exact steps to reproduce

First Trait

```
trait WithFirstTrait
{
    public function mountWithFirstTrait() { 
      // first action   
   }
}
```

Second Trait
```
trait WithSecondTrait
{
    public function mountWithSecondTrait() { 
      // second action   
   }
}
```

Livewire Component

```
class MyComponent extends Component
{
    use WithFirstTreat;
    use WithSecondTreat;
```

**In this scenario, the "first action" code isn't executed. only the "second action" code.**

If the Treats order is changed in component 

```
class MyComponent extends Component
{
    use WithSecondTreat;
    use WithFirstTreat;
```

now,  the "first action" code from WithFirstTreat IS executed and the "second action" isn't.

**Context**
- Livewire version: [2.3.0]
- Laravel version: [8.11.2]
- Alpine version: [2.7.3]
- Browser: [Chrome]

**Comment by austenc** [comment]
@ClementN 

Please update to Livewire 2.3.2+

Support for multiple traits was added in that release. See here: https://github.com/livewire/livewire/releases/tag/v2.3.2

**Comment by ClementN** [comment]
Thank you very much, @austenc

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
