### ISSUE TITLE
Livewire model is not working when updating input field from javascript?

### ISSUE THREAD

**Issue by vgavrilovikj** [livewire/livewire#2116]
I have a text input field which works great if I update it myself when typing inside it, however, what I need is to have this input field be populated with data from javascript, rather than the user.

This is what happens if I type "123" in the input field, I get this for the input field's value:
![image](https://user-images.githubusercontent.com/29601489/100525320-18884e00-31c0-11eb-883f-6d2770eea9b0.png)

However when I update it using javascript, `document.getElementById("images").value = "Hello"`
The input field is populated with the new data:
![image](https://user-images.githubusercontent.com/29601489/100525326-32299580-31c0-11eb-9fff-6958f5405ba6.png)

But it doesn't make a new fetch call to get the data and the last one is with the "123" data that was inserted without javascript..
![image](https://user-images.githubusercontent.com/29601489/100525334-45d4fc00-31c0-11eb-9f43-bdc9740f2177.png)

Any idea of how it can get the data after updating the input's value from javascript?

**Comment by joshhanley** [comment]
@vgavrilovikj you can't manipulate the input field directly using JavaScript, instead you need to interact with the Livewire component. 

For example, if you input has `wire:model="test"` on it, then you will have a public property called `$test`. 
To interact with that from JavaScript you can use `@this.test = "Hello"`.

See here for the @this directive https://laravel-livewire.com/docs/2.x/inline-scripts
To see more options that you can call on @this, see here (note $this referenced here will only work from Alpine so just use @this) https://laravel-livewire.com/docs/2.x/alpine-js

Hope this helps!

**Comment by austenc** [comment]
Thanks, @joshhanley. That is correct! The best way to do this sort of thing is to interact with the Livewire component from the javascript side. 

Closing since this isn't a Livewire bug. Use the javascript version of the Livewire component via `@this` and you should be good! Please reopen if not. Thanks!

> Note: the `@this` directive compiles to the following string for JavaScript to interpret: `Livewire.find([component-id])`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by nicko170** [comment]
I needed a way to do this also for a telephone input field, but I am not sure how hacky this actually is or if it's going to work long term - so it's going to do for now.

In my case, I was not about to use `@this` as it was built in javascript bundles.

`phoneInput` is a hidden field that gets changed by intl-tel-input, but was not updating the hidden field in the backend unless another field was changed also.

If finds the closest livewire component that has the field as a child, then adds a syncInput action for that component to update the state in PHP.

```js
const phoneInput = document.getElementById(this.dataset.phoneInput);
if (phoneInput && phoneInput.isLivewireModel) {
  phoneInput.value = itiPhone.getNumber();
  
  // This finds the livewire model to update
  const wireModel = phoneInput
      .getAttributeNames()
      .filter(name => name.includes('wire:model'))[0];
  
  // This finds the livewire parent component dynamically and creates an action to update the model.
  window.Livewire
      .components
      .components()
      .filter(c => c.el.contains(phoneInput))[0]
      .set(phoneInput.getAttribute(wireModel), phoneInput.value);
}```

**Comment by madurapa** [comment]
@nicko170 You can get the component from either Livewire hook or like this https://stackoverflow.com/questions/69143703/how-to-use-livewire-component-inside-of-javascript
