### ISSUE TITLE
Livecycle Hooks not working in nested Component with an abstract method. 

### ISSUE THREAD

**Issue by Slowwie** [livewire/livewire#2118]
### Description

I created a [searchable-multi-autocomplete component](https://laravelplayground.com/#/snippets/3405ff5a-8c4a-4843-80e3-17ac87c77619).  

For being reuseable. A developer has to create an new Livewire component and extend the base component (Autocomplete.php). This Class requires an abstract method 'query': 

```
abstract class Autocomplete extends Component
{
    public $results;

    /** @var $selected Collection */
    public $selected;

    abstract public function query(string $term);

```

So, whenever the developer needs a searchable-multi-autocomplete field. He can extend it like that: 

```

class SubjectAutocomplete extends Autocomplete
{

    protected $listeners = ['valueChanged'];

    public function valueChanged(Category $category)
    {
        $this->emitUp('subjectChanged', $category);
    }

    public function query(string $term)
    {
        return Subject::findByName($term)->toArray();
    }
```

And in the base template or LivewireComponent he can react onto the 'subjectChanged' event. 

So far so good. But the events are not triggered at all. 

Hydrate and Mount works well, bot none of the updated, update and so on. 
So its not possible to fetch the selected data and actually use it.

### Exact steps to reproduce
I created a [Laravelplayground ](https://laravelplayground.com/#/snippets/3405ff5a-8c4a-4843-80e3-17ac87c77619)for this.

**Context**
I updated Livewire and Alpine on the latest versions. But I don't know wich versions Laravelplayground are using.

But the 'bug' - if it is one. Is the same anyway.

- Browser: [e.g. Chrome, Safari]

**Comment by Slowwie** [comment]
Note: I rewrote it now to use a simple array for the `public $selected;`property. Nothing changed even without the collection Class. The weird thing is, the component updates, but no events are fired. It would be great if someone can tell me, what is going on there.

**Comment by Slowwie** [comment]
This works: 

When I call the method `updatedSelected` manually after I added an item. It works. So I can fire the emitUp to the final class listenter: 

```
   public function addItem(string $string, ?string $uuid = null)
    {
        $string = trim($string);
        if (!$string) {
            return false;
        }

        if (!$uuid) {
            $uuid = Str::uuid()->toString();
        }

        if (empty(Arr::where($this->selected, fn($item) => $item['name'] === $string))) {
            $this->selected[] = $this->makeItem($uuid, $string);
        }

        $this->updatedSelected();

        return true;
    }
```

I am not sure if this is a bug or intended. 

Maybe events get only fired when it is changed directly by userinput?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
