### ISSUE TITLE
livewire 2.3.2 incompatible with PHP 8 and Composer 2.0.7

### ISSUE THREAD

**Issue by SadiBakhshi** [livewire/livewire#2120]
### Description
After I installed new version of PHP and Composer I got the following error:

[InvalidArgumentException]
Package livewire/livewire at version 2.3.2 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
![livewire issue](https://user-images.githubusercontent.com/45330609/100552816-be11ef00-329e-11eb-8b84-9d968f0c826e.JPG)

- Livewire version: [2.2.3]

**Comment by owenvoke** [comment]
I think this is just PHP 8 not being compatible, we're waiting for a release with ac8321905c32dcea5e5fde89fef93d59109570ab 👍🏻

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
PHP 8 support has been tagged. Thanks!
