### ISSUE TITLE
Firefox bug: browser validation triggered when rendering form

### ISSUE THREAD

**Issue by gdebrauwer** [livewire/livewire#2124]
### Description

In firefox, the browser validation is triggered even when the form is just being rendered. In other browsers this is not the case

### Exact steps to reproduce

Create a livewire component:

```php
class FirefoxFormBug extends Component
{
    public $name;

    public function save()
    {
        // save something
    }

    public function render()
    {
        return view('livewire.firefox-form-bug');
    }
}
```

```blade
<form wire:submit:prevent="save">
    <!-- Bug: validation triggered -->
    <div style="margin-bottom: 0.5rem;">
        <input type="text" wire:model="name" required placeholder="wire:model name" style="background-color: rgb(229, 231, 235)"/>
    </div>

    <!-- Bug: validation triggered -->
    <div style="margin-bottom: 0.5rem;">
        <input type="text" wire:model.defer="name" required placeholder="wire:model.defer name" style="background-color: rgb(229, 231, 235)"/>
    </div>

    <!-- Bug: validation triggered -->
    <div style="margin-bottom: 0.5rem;">
        <input type="text" wire:model.lazy="name" required placeholder="wire:model.lazy name" style="background-color: rgb(229, 231, 235)"/>
    </div>

    <!-- Correct: validation not triggered -->
    <div style="margin-bottom: 0.5rem;">
        <input type="text" required placeholder="no wire.model" style="background-color: rgb(229, 231, 235)"/>
    </div>
</form>
```

Then register that component as a route:

```php
Route::get('firefox-form-bug', \App\Http\Livewire\FirefoxFormBug::class);
```

If you now just visit this URL, you will see that the default "required" browser validation has been triggered:

![image](https://user-images.githubusercontent.com/22586858/100591301-d52ffb80-32f5-11eb-9a01-e15cf5414c2b.png)

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.16.1
- Alpine version: 2.7.3
- Browser: Firefox

**Comment by austenc** [comment]
Thanks for reporting this @gdebrauwer. This comes down to browser default styling, and Firefox uses `:-moz-ui-invalid` to show that style. Chrome would show something similar if you added an `input:invalid` CSS style. 

You could add your own styles to prevent this, but I'm not sure it's something Livewire should be responsible for. The styles Livewire provides are minimal, so adding corner-case browser prefixes like this may not be within their scope. Caleb will have to decide. 👍

**Comment by gdebrauwer** [comment]
@austenc but in other browsers this invalid state is only triggered if you submit the form.
It seems to be related to the `wire:model` attribute as the input-tag without `wire:model` (see in my example) is not marked as invalid by the browser

**Comment by austenc** [comment]
@gdebrauwer that's the thing -- the invalid state IS triggered, but the default browser styles just don't show it.  

If you load your example in chrome, and add a style like this in the inspector, you'll see what I mean. 
```
input:invalid { border: 5px solid red; }
```

Strange, indeed! Not sure if this is something Livewire can fix, but I'll look into what's causing that on the first page load, because it does seem weird.

**Comment by calebporzio** [comment]
Interesting, yeah I imagine this has something to do with `wire:model` setting `.value` on the input elements when Livewire initializes.

If this is a big issue for you, please look into the problem and PR a tested solution if a clean one exists.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
