### ISSUE TITLE
Select box not resized after repopulate if <select> is open

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2125]
```
Basically if you have a dynamic <select> and you have it open during a change in the select options then the select box does not correctly resize, so it looks as if there is no data in the list.

Please see example of the problem:
https://laravelplayground.com/#/snippets/d1741558-a7a0-4536-9ca7-009782fdf413

Note that in my example I have added a 2 second sleep before select data population, so that you have ample time to open the select before the data gets populated.

- Livewire version: 2.2.3
- Browser: Chrome

```

**Comment by joshhanley** [comment]
@AdvancedStyle works ok for me, see screenshot 
![recording](https://user-images.githubusercontent.com/882837/100674914-0c67e080-33ba-11eb-8be3-0b59d8245b3b.gif)

**Comment by AdvancedStyle** [comment]
Maybe it is not actually a livewire bug and just a bug with my specific version of chrome, I'm using: Version 87.0.4280.66 (Official Build) (64-bit)

I've just tested it in Firefox and it works normally.

I guess can close this issue and mark it down to a Chrome problem.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@AdvancedStyle Yeah maybe, for reference I'm using 87.0.4280.67
