### ISSUE TITLE
Click handler called twice when items are dynamically added

### ISSUE THREAD

**Issue by dvic** [livewire/livewire#2126]
### Description

Adding children that have a click handler to a parent that has `x-data` results in the click handlers being executed twice (when clicked).

Repo demonstrating the issue: https://github.com/dvic/hello-livewire
Originally reported in: https://github.com/alpinejs/alpine/issues/756

### Exact steps to reproduce
1. Open the JS console in your browser.
2. On the home page, click on the button *first click here*.
3. A new item is added to the `ul`.
4. Click on the added `li`.
5. The console shows that the handler is called twice (printing the text `i was clicked` twice).

### Stripped-down, copy-pastable code snippets
Full demo in https://github.com/dvic/hello-livewire

**Context**
- Livewire version: 2.3
- Laravel version: 2.5
- Alpine version: 2.7.3
- Browser: Firefox, Chrome

**Comment by joshhanley** [comment]
@dvic yeah there is a bug with any x-on that are assigned inside of a blade conditional. See this open PR that submits a failing test for this issue https://github.com/livewire/livewire/pull/1995.

This is the issue for more details #763 and see my comment specifically on how I worked around it https://github.com/livewire/livewire/issues/763#issuecomment-719002595

Can I suggest closing this issue and adding your comment to the existing issue, so it's all contained in one place?

Hope this helps!

**Comment by dvic** [comment]
@joshhanley Thanks! I have added this issue as a comment, this one can be closed then.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by dvic** [comment]
This problem is fixed with v2.8.1.
