### ISSUE TITLE
Bug: New script tag with src-attribute not loaded/executed on component update

### ISSUE THREAD

**Issue by gdebrauwer** [livewire/livewire#2127]
### Description

If the livewire component contains a new script tag with a src-attribute that was not present on the initial component load, then that script will not be loaded and executed

### Exact steps to reproduce

Create a new component

```php
class ScriptNotLoadedBug extends Component
{
    public $showScript = false;

    public function render()
    {
        return view('livewire.script-not-loaded-bug');
    }
}
```

```blade
<div>
    <button type="button" wire:click="$set('showScript', true)">show script</button>
    @if ($showScript)
       <script src="https://cdn.jsdelivr.net/npm/mp3-mediarecorder@4.0.3/dist/index.umd.min.js"></script>
    @endif
</div>
```

Then register the component as a route:

```php
Route::get('/script-not-loaded-bug', \App\Http\Livewire\ScriptNotLoadedBug::class);
```

If you now go that route and click on the button, you will see that no http-request was executed to load this script based on its src-attribute.

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.16.1
- Alpine version: 2.7.3
- Browser: All browsers

**Comment by joshhanley** [comment]
@gdebrauwer I don't think that will work as I'm pretty sure morphDOM doesn't evaluate scripts, see this https://github.com/patrick-steele-idem/morphdom/issues/178

Looks like Caleb has a solution for inline scripts, but not sure if there was anything implemented for loading a script via src attribute.

**Comment by calebporzio** [comment]
Yeah, good call Josh.

I added behavior to handle inline script tags, not `src=""` references from tags.

I don't think it's wise to support that ATM.

A) I actually don't know how off hand
B) It's likely not secure because of CSP/cross-origin issues

Closing this. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
