### ISSUE TITLE
405 after submitting a form

### ISSUE THREAD

**Issue by marast78** [livewire/livewire#2128]
### Description

Sometimes when a user clicks a submit button a weird error occurs. The form data should be sent by POST method and ajax but there is used GET without AJAX. After it, I get 405.

### Exact steps to reproduce

It's difficult to reproduce the not permanent error. I'm sure that my code is correct and similar to docs.
I guess that problem can be with the loading of livewire but why there isn't sent a submission form with POST method :thinking: 

**Context**
- Livewire version: 2.3.1
- Laravel version: 8.14
- Browser: modern browsers

**Comment by jhosepharaujo** [comment]
I did have the same problem and my solution was add blank div arround the component.

**component.blade.php**
```
<div>
  <!-- content component -->
</div>
```

**Comment by marast78** [comment]
@jhosepharaujo My code below

`<section id="contact-us" class="ats_contact">
    <div class="container mx-auto">
        <livewire:landing-page.footer-form />
    </div>
</section>`

It looks fine :thinking:

**Comment by jhosepharaujo** [comment]
Post code of component. <livewire:landing-page.footer-form>

**Comment by joshhanley** [comment]
@marast78 double check you only have one root component (ie a DIV) wrapping all your code inside `footer-form.blade.php` as suggested by @jhosepharaujo. If you can share your `footer-form.blade.php` code that will help!

**Comment by marast78** [comment]
@joshhanley  as below

```html
<div class="w-full py-4">
    <form id="step-1" class="form " wire:submit.prevent="submitEmailForm" method="POST"
        action="{{ route('landingpage.ats-contact-us') }}">
         // some code
    </form>
</div>

@push('scripts')
// some code
@endpush
```

**Comment by joshhanley** [comment]
@marast78 that all looks ok! I would remove method and action for the form element though as they’re not needed. 

If that doesn’t fix it, the other thing to check is your livewire scripts are actually running correctly. In your browser and open up your console. There should be a global `Livewire` object which you should be able to access. Can you confirm that’s working ok?

**Comment by marast78** [comment]
@joshhanley Livewire object is working ok. I can access it via console. My issue occurs not permanent. It's hard to repeat it.

The method and action are needed to send the correct request.
I guess that sometimes Livewire object isn't loaded correctly and It can make that issue, though.

**Comment by joshhanley** [comment]
@marast78 maybe I’m missing something, but generally if you are using livewire, you don’t want the form to post the request as livewire handles all that for you, hence why I suggested removing action and method.

Can you explain what your trying to achieve? If your using livewire to do form validation and then still submitting it manually, can you share your component class code as well, so we can try and debug what’s going on.

**Comment by marast78** [comment]
@joshhanley ok I'll try with the form without the method's attribute. I'm new with Livewire and haven't known good practices yet.

But what will happen, when I'll remove the action? It'll be working correctly? Will Livewire locate where is located my method?

**Comment by joshhanley** [comment]
@marast78 no worries!

Yeah so how livewire works is through the wire:submit action. Instead of doing a full post request (like you would normally do), it actually just calls that method directly. So any data you need to save, you just do in your `submitEmailForm` method. That’s why action and method attributes aren’t needed on the form tag. 

If you haven’t already, I strongly recommend watching the Livewire screencasts that are free on the website and if you can sponsor Caleb and go through the rest of the videos. They are really invaluable for understanding how Livewire works as it’s a bit different than probably what your used to.

**Comment by marast78** [comment]
@joshhanley  thanks for your feedback :+1:  and advice. I'll use your tips and now I'm closing my issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@marast78 no problems! If you use discord, jump on the Livewire help channel, plenty of good people there that are happy to help with any questions you may have! https://discord.com/invite/livewire
