### ISSUE TITLE
hidden attribute get cleared on realtime validation

### ISSUE THREAD

**Issue by gastonsoua** [livewire/livewire#2129]
### Description
im trying to use the real time validation give it by livewire, the Lazy Updating  and the method updated in component class.
the input type password  get cleared when the validation start.

### Exact steps to reproduce
1. the user model containe 3 attributes: 
-name
-password
-email

the password attribute is hidden 
2. create the user component and defining the $rules 
and the other methode for the component 
3. define the view for this component
  on the view i make an input for the password and another for the confirme 
when i enter the password and i move to type the confirme password the passwor filed get cleared.

my conclusion on the real time validation the password can't be get cause its declared hidden in the model and a big probleme if we unset the attribue from the $hidden

### Stripped-down, copy-pastable code snippets
- THE MODEL:

```
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $fillable = [
        'name',
        'email',
        'password',
    ];
    protected $hidden = [
          'password',
    ];
}
```

- THE COMPONENT:

```
<?php

namespace App\Http\Livewire\User;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;

class Create extends Component
{
    public User $user;

    protected array $rules = [
        'user.name' => ['required', 'max:24'],
        'user.email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
        'user.password' => ['required', 'string', 'min:8'],
        'user.password_confirmation' => ['required', 'same:user.password',]

    ];

    public function mount(User $user)
    {
        $this->user = $user;
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function create()
    {
        $this->validate();
        $user = User::create(
            [
                'name' => $this->user->name,
                'email' => $this->user->email,
                'password' => Hash::make($this->user->password),
            ]
        );
    }
}
```

- THE VIEW:

```
<form wire:submit.prevent="create">
    <div>
      <div>
         <x-jet-input type="text" wire:model.lazy="user.name"/>
        <x-jet-input-error for="user.name"/>
       </div>
       <div>
         <x-jet-input type="email" wire:model.lazy="user.email"/>
        <x-jet-input-error for="user.email"/>
       </div>
       <div>
        <x-jet-input type="password" wire:model.lazy="user.password"/>
        <x-jet-input-error for="user.password"/>
       </div>
       <div>
        <x-jet-input type="password" wire:model.lazy="user.password_confirmation"/>
        <x-jet-input-error for="user.password_confirmation"/>
       </div>
    </div>
    <div">
        <x-jet-button>create</x-jet-button>
    </div>
</form>
```

**Context**
- Livewire version: [e.g. 2.3.2]
- Laravel version: [e.g. 8.16.0]
- Alpine version: [e.g. 2.7.3]
- Browser: [e.g. Chrome, firefox]

**Comment by joshhanley** [comment]
@gastonsoua I would recommend creating two public properties, `$password` and `$password_confirmation` and binding to them instead, and then use `$this->password` inside your hash when saving your user.

I would also consider using the `confirmed` validation rule for your password https://laravel.com/docs/8.x/validation#rule-confirmed.

Hope this helps!

**Comment by austenc** [comment]
Thanks @joshhanley. Yeah, this is intended behavior since you wouldn't want the password being passed in plaintext back and forth with ajax requests.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
