### ISSUE TITLE
Update livewire model from JavaScript?

### ISSUE THREAD

**Issue by vgavrilovikj** [livewire/livewire#2130]
How can I update the livewire model from Javascript?

I have the following input field:
`<input type="text" id="test" wire:model="test">`

Whose value should be changed from a javascript function:
`function updateField () {
                let field = document.getElementById("test");
                field.value = "Hello";
            }`

However, when the function is called I can see the changes on the site but livewire makes no fetch call to update the field... This function should be available in livewire, I mean this is a very simple javascript...

**Comment by joshhanley** [comment]
@vgavrilovikj see my response on your other issue #2116. Can you please make sure you just update the same issue in future instead of opening a second issue?

Please close this one, and we will keep working on your issue in #2116.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
