### ISSUE TITLE
Entangled Property Not Calling Updated Hook in Livewire

### ISSUE THREAD

**Issue by iAmKevinMcKee** [livewire/livewire#2131]
### Description

I am building a selectpicker in Livewire and Alpine. Specifically, dependent selectpickers where when you make a choice in the first, it updates the available choices in the second.

In my contrived example, I have states and cities. Two states and four cities (two cities that belong to each state). I have stripped everything down as far as I can in a Laravel Playground and don't know where to go from here.

When I change the value on the first selectpicker, the alpine `value` is updates. There is also a call made to Livewire with the updated entangled value:

![image](https://user-images.githubusercontent.com/4503765/100690653-9c6f4100-334c-11eb-9138-c35dc8a91bed.png)

You can also see that both the alpine and and Livewire properties are updated with the selected value.

The `updatedState()` method on the Livewire class is called, and if you uncomment the `dd($this->cities)` on line 39, you'll see it's working as expected in the component. The cities are changed based on the selected state.

However, on the UI, the second selectpicker still has all 4 cities as options even though the Livewire component is only showing the 2 related to the chosen state.

**So for some reason, alpine is not updating the UI even though an entangled property has changed value.**

One additional, very strange twist here, is that I tried to set the value of `state` via alpine whenever the value was updated. I did this by adding the following on line 76 of the `livewire-component.blade.php` file: `$wire.set('state', value);` and when I do this, the alpine update works. When you look in the dev tools, it is sending an exact duplicate of the instructions that are sent from the model changing. While this does work as a workaround, it shouldn't be necessary.

![image](https://user-images.githubusercontent.com/4503765/100692520-aa26c580-3350-11eb-94ed-8dd00f564bbc.png)

### Exact steps to reproduce

Go to the Laravel Playground: https://laravelplayground.com/#/snippets/962d508e-fc18-40d3-aefb-9ee25b8fd219

Click in the first input box, click on a state, and then click on the second input box and see that the cities are not updated on the UI.

To see the `updatedState()` hook being called, uncomment line 39 of `LivewireComponent.php`

To see it working as expected, add the following line of code to line 76 of `livewire-component.blade.php`: `$wire.set('state', value);`

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.15.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@iAmKevinMcKee there is a bug with entangle in 2.3.2 where every second change with entangled variables isn't processed by the watchers. I would recommend downgrading to 2.3.1 and testing it on that version.

There is a PR with a failing test here but I can't work out how to fix it yet https://github.com/livewire/livewire/pull/1968

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
fixed in release v2.3.4

**Comment by iAmKevinMcKee** [comment]
Just checked locally and this fix seems to work! Thanks @calebporzio 🎊
