### ISSUE TITLE
Entangle sucks from 2.3.2

### ISSUE THREAD

**Issue by psos** [livewire/livewire#2132]
* Entangle still doesn't work in nested livewire components (dont try to make select2 like dropdown)
* Entangle don't fire update hook in master livewire compontent for 2.3.3 for second request. Don't know why, but this is second unstable release reverted to 2.3.1

Regards.
Pawel

**Comment by austenc** [comment]
@psos Please try with version 2.3.4 which was released today.

**Comment by psos** [comment]
entangle property  firing update livewire properly as 2.3.1.

**Comment by psos** [comment]
#1914 still issue.

How to contribute test case ? 
I cannot use nested components in laravel playground


Regards

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
