### ISSUE TITLE
404 Not Found Modal after delete

### ISSUE THREAD

**Issue by ighmouraceneb** [livewire/livewire#2135]
### Description

I encountered a problem while deleting an element in an array.
After deleting a newly created element a 404 error is displayed instead of an add modal.
I saw that the problem has already been asked and that with version 2 of livewire the problem should be fixed but unfortunately it persists.

![image](https://user-images.githubusercontent.com/17543179/100732858-a2f1cd00-33cd-11eb-9705-1086260a7a8d.png)

### Exact steps to reproduce

Here is the structure of my components

     Index.php (Parent component)
                 CreateContentForme.php
                 DeleteContentForme.php

### Stripped-down, copy-pastable code snippets
index.blade.php

 ```
<x-back.input.button wire:click="addNewContentType" @click="modalOpen = true" >
           {{__('Add new content type')}}
</x-back.input.button>

<!--MODAL DELETE CONTENT-->
  @livewire('back.structure.content.delete-content-form')

 <!--MODAL CREATE NEW CONTENT TYPE-->
@livewire('back.structure.content.create-content-form')
```

Index.php

```
class Index extends Component
{

  
    protected $listeners = [
        'save'              => '$refresh',
        'removeContentType' => '$refresh'
    ];

    public function addNewContentType()
    {
        $this->emit('addNewContentType');
    }

    public function edit($id)
    {
        $this->emit('editContentType', $id);
    }

    public function delete($id)
    {
        $this->emit('deleteContentType', $id);
    }

 

    public function render()
    {
        return view('livewire.back.structure.content.index',  [
            'contentTypes' => ContentType::all(),
        ]);
    }
}

```

DeleteContentForm.php 

```
class DeleteContentForm extends Component
{

    public $showDeleteModal = false;
    public $contentType;
    public $contentTypeId;


    protected $listeners = [
        'deleteContentType' => 'deleteContentType'
    ];


    public function deleteContentType($contentTypeId)
    {
        $this->contentType = ContentType::findOrFail($contentTypeId);
        $this->showDeleteModal = true;
    }

    public function removeContentType()
    {
        $this->contentType->delete();
        $this->showDeleteModal = false;
        $this->emit('removeContentType');

    }

    public function render()
    {
        return view('livewire.back.structure.content.delete-content-form');
    }
```
CreateContentForm.php
```
class FormCreate extends Component
{

    public $showAddModal = false;
    public ContentType $content;


    protected $rules = [
        'content.name' => ['required', 'string', 'max:255'],
        'content.description' => 'string|max:500',
        'content.config.label' => 'required',
        'content.config.help' => 'string',
        'content.config.publishing' => 'boolean',
        'content.config.promoted' => 'boolean',
        'content.config.mainNavigation' => 'boolean',
        'content.config.footer' => 'boolean',
        'content.config.administration' => 'boolean',
    ];
   protected $listeners = [
        'addNewContentType' => 'create',
        'editContentType' => 'editContentType',
    ];
  public function editContentType($conteentTypeId)
    {
        $this->content = ContentType::findOrFail($conteentTypeId);
        $this->showAddModal = true;
    }

    public function create()
    {
        $this->showAddModal = true;
    }
   public function save()
    {
        $this->validate();
        $this->content->user_id = auth()->id();
        $this->content->save();

        $this->addNewField();
        $this->emit('save');
    }
  public function render()
    {
        return view('livewire.back.structure.content.create-content-form');
    }

```

**Context**
- Livewire version: [e.g. 2.3.2]
- Laravel version: [e.g. 8.16.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by ighmouraceneb** [comment]
so far I have found this solution. What do you think?


CreateContentForm.php :


`  public function render()  {
        $this->content = ContentType::make();

        if($this->contentTypeId) {

            $this->content = ContentType::findOrFail($this->contentTypeId);
        }

        return view('livewire.back.structure.content.create-content-form');
    }`

**Comment by zynth17** [comment]
i have the same problem using livewire on modal 
after delete the model it return 404 not found

**Comment by ighmouraceneb** [comment]
Livewire hydrates all the models including the one deleted because it always keeps it in memory and since it does not exist in the database so it sees this 404 error again

**Comment by zynth17** [comment]
> Livewire hydrates all the models including the one deleted because it always keeps it in memory and since it does not exist in the database so it sees this 404 error again

so how do we make it not hydrating the deleted variable? because it is nested component

**Comment by ighmouraceneb** [comment]
you have to make blank the model : `$this->model = Model::make();`

**Comment by ighmouraceneb** [comment]
> > Livewire hydrates all the models including the one deleted because it always keeps it in memory and since it does not exist in the database so it sees this 404 error again
> 
> so how do we make it not hydrating the deleted variable? because it is nested component

you have to make blank the model : `$this->model = Model::make();`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Thanks for helping @zynth17

**Comment by redbastie** [comment]
I fixed this by calling `$this->reset()` in my modal when it gets hidden.

Example:

```
class ModalComponent extends Component
{
    public $hidden = true;
    protected $listeners = ['show'];

    public function toggle()
    {
        $this->hidden = !$this->hidden;

        if ($this->hidden) {
            $this->reset();
        }

        $this->emit($this->hidden ? 'bodyScrollUnlock' : 'bodyScrollLock');
    }
}
```

**Comment by shashistack** [comment]
I have faced the similar issue, and the above solutions did not work for me. So I opted for soft delete.. just updating the status column on the DB table to 0, instead of completely deleting it. It is a work-around for me.

**Comment by andreasmatu** [comment]
Same issue here. By calling `$this->reset()` you reset all values of the component and you probably do not want that behavior.

In my case i called `$product->delete()` in my Livewire Component and in the view i had a foreach loop with `$products as $product`. Although `$product` was not a public value within the Livewire Component, this was somehow buggy.
My solution was to change the name in the Livewire Component to `$product_to_delete->delete()`.

**Comment by division-by-zero** [comment]
I had the same issue. This happens because the component is kept alive after closing. Define destroyOnClose() as shown below.

```
public static function destroyOnClose(): bool
{
    return true;
}
```
