### ISSUE TITLE
wire:model on select does not fire until select option change

### ISSUE THREAD

**Issue by monzer15** [livewire/livewire#2138]

**Comment by monzer15** [comment]
component:
   <select class="form-control" id="exam_type" name="premium" wire:model="premium">
              <option value="0">Free</option>
              <option value="1">Premium</option>
   </select>

dd($this->premium);  // returns null

**Comment by iksaku** [comment]
This is intended behavior. Only value changes will be fired back to your component.

**Comment by monzer15** [comment]
is there any way to get the current option in select without being changed?

**Comment by iksaku** [comment]
If you need to do it via JS, you can always [Checkout the Docs for Livewire + Javascript](https://laravel-livewire.com/docs/2.x/inline-scripts).

Other wise, if you need to access the value via PHP, then you can certainly do it in the way that PHP already works: Using Object Oriented Programming:
```php
class MyComponent extends Component
{
    public string $selectedOption;

    public function myFunction()
    {
        dd($this->selectedOption);
    }
}
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
