### ISSUE TITLE
Release v2.3.4 - code missing from dist/livewire.js

### ISSUE THREAD

**Issue by hicksy** [livewire/livewire#2139]
### Description

v2.3.4 includes the following fix [(#2055)](https://github.com/livewire/livewire/pull/2055/commits/36ca73c16f2f7cb057a6bddf3394b503e365097b) relating to file inputs. It updates the `clearFileInputValue` to use `el` rather than `this`

While this PR has been merged and changes are present in`FileUploads.js`, it hasn't been rolled-up into `dist/livewire.js` 

![Screenshot 2020-12-01 at 19 35 43](https://user-images.githubusercontent.com/785770/100789332-3814b600-340e-11eb-8f91-cb3a5f4642c4.png)

Manually running `npm install`, and `npx rollup -c` within `/vendor/livewire/livewire` was required. 

![Screenshot 2020-12-01 at 19 38 13](https://user-images.githubusercontent.com/785770/100789345-3d720080-340e-11eb-9fcd-a834de982fd7.png)

### Exact steps to reproduce

- Update to v.2.3.4
- Click on a file input 
- Observe the error `TypeError: undefined is not an object (evaluating '_this.value=null')`

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.4
- Laravel version: 8.17.0
- Alpine version: 2.7.0
- Browser: Safari

**Comment by nuernbergerA** [comment]
Checkout v2.3.5

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
