### ISSUE TITLE
Lazy binding does not work as expected for input, checkbox, select

### ISSUE THREAD

**Issue by ERFOLGswerkzeug** [livewire/livewire#2145]
### Description
Data binding does not work as expected for input, checkbox, and select multiple using the `.lazy` modifier.
Clicking away from a text input directly into a checkbox or a select multiple does not bind the value of the text input to the underlying property. The text input field is cleared instead.

### Exact steps to reproduce
1. Create a text input using `wire:model.lazy` modifier, bind it to a property
2. Create e.g. a checkbox or a select multiple with using `wire:model.lazy`, bind it to a property
3. Input text into the text input and check the checkbox immediately, without focusing any other element in between
4. The checkbox value is bound, the text input will be cleared or at least flicker

### Stripped-down, copy-pastable code snippets

Component:
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Form extends Component
{
    public $title;

    public $enabled;

    public $selected;

    public function mount()
    {
        $this->enabled = false;
        $this->selected = [];
    }

    public function render()
    {
        return view('livewire.form');
    }
}
```

Template:
```blade
<div>
    <div>
        Title:
        <input type="text" wire:model.lazy="title">
    </div>
    <div>
        Enabled:
        <input type="checkbox" wire:model.lazy="enabled">
    </div>
    <div>
        Options:
        <select wire:model.lazy="selected" multiple>
            <option value="A">Option A</option>
            <option value="B">Option B</option>
            <option value="C">Option C</option>
        </select>
    </div>
    <hr>
    <div>
        Title: {{ $title }} <br>
        Enabled: {{ $enabled }} <br>
        Options: {{ json_encode($selected) }}
    </div>
</div>

```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.17.1
- Alpine version: -
- Browser: Chrome, Firefox, Safari

**Comment by jeffchown** [comment]
I can confirm.  Very strange.  When I clicked on the checkbox, Livewire fired two events but in the reverse order I would have expected.  I expected:
- 1st event to `syncInput` the `title` text input
- 2nd event to `syncInput` the `enabled` checkbox

Instead, they fired per the screenshots below - losing/clearing the `title` input in the process:
![image](https://user-images.githubusercontent.com/42819001/100904598-2b877080-3495-11eb-9700-e2990c99dc40.png)

![image](https://user-images.githubusercontent.com/42819001/100904633-3510d880-3495-11eb-8c34-6952d1924d5d.png)

**Comment by isaackearl** [comment]
+1 to this issue. 

What I've found is that if you use the .lazy modifier and you don't navigate away to trigger the change event, then the next time you "submit" or do something similar to that, the syncInput is not guaranteed to happen before the next update, so you can lose your input.  

For me this always happens if I trigger an update on a different livewire component on the same page.  For example let's say you have 2 forms right next to each other... and you hit submit on the second form after filling in a text input on the first form... When you inspect the network requests you'll see the syncInput request happen after the submit of the second form... this breaks things for me sometimes as you'd expect the input to sync before firing the action on the other component.

**Comment by lucasromanojf** [comment]
I can confirm this bug too, mainly after 2.3.0. If I type something in a field and directly click on the submit button, the submit request is sent before the syncInput one.

**Comment by joshhanley** [comment]
Can someone test this against dev-master and let us know if it's still happening? There were bugs with .lazy that have been merged but not yet tagged.

**Comment by lucasromanojf** [comment]
> Can someone test this against dev-master and let us know if it's still happening? There were bugs with .lazy that have been merged but not yet tagged.

Still happening on 2.3.6. It is working fine on 2.2.9. After 2.3.0 it started happening and still happens.

**Comment by joshhanley** [comment]
Thanks @lucasromanojf.

I have tested it with a lazy input and a checkbox, and can confirm there is still an issue.

The .lazy on the checkbox won't make any difference as the checkbox fires a change event with or without lazy. Probably same with the select. 

But the input change should still be batched up properly with either one of those change events.

I have submitted a PR #2340 with a failing test demonstrating the issue.

**Comment by austenc** [comment]
Thanks for the test @joshhanley !

**Comment by calebporzio** [comment]
Thanks for submitting, will be fixed in the next release.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
