### ISSUE TITLE
lazy inputs fire extra `syncInput` next time form is used if initial form is submitted while edited lazy input still has focus

### ISSUE THREAD

**Issue by jeffchown** [livewire/livewire#2148]
### Description
When (re-)using a form (in a modal) to edit multiple models (e.g. transactions), when saving the form it fires `syncInput` events for `.lazy` inputs that were edited during the form's previous use(s) - *only* when the Save button is clicked when focus is still in the edited input (e.g. lazy hasn't fired yet on loss of the input's focus)

### Exact steps to reproduce
- using Surge as an example
- login to Surge
- open browser's devtools to Network
- in Surge's dashboard, click `Edit` for one of the transactions
- edit the `Title` field, *without* moving to another input or using the tab key etc.
- click `Save`, examine the payload in devtools for Save event (e.g. see screenshot below):
![image](https://user-images.githubusercontent.com/42819001/100901529-e9106480-3491-11eb-9bcc-d43d404134bc.png)
- now, click `Edit` for a different Transaction
- edit the `Amount` field *again, without leaving the field*
- click `Save`, examine payload in devtools (see below):
![image](https://user-images.githubusercontent.com/42819001/100901648-0c3b1400-3492-11eb-9a17-4a3c96c1ce91.png)

- what seems to be happening is, in the 2nd edit, Livewire sees both the `Title` *and* `Amount` fields as dirty when only the `Amount` field was edited.  Looks like it is remembering the `Title` field's edit from the first `Transaction's` edit.

### Stripped-down, copy-pastable code snippets
- easiest way is to use the Surge repo and follow above steps

**Context**
- Laravel v8.16.1
- Livewire v2.3.4
- Alpine.js v2.7.3
- browsers tested = Brave, Chrome, Safari

I'd also like to make a suggestion - a method/function to enable the manual clearing of the 'dirty' state (and, therefore, I assume the related pending syncInput events) related to a Livewire component's attribute(s) used in a form (e.g. `public $editing` in Surge) might be useful.  It would enable a more thorough resetting between a form's usages (vs. `$this->reset($editing)` + `$this->resetValidation()`).

Thanks!

**Comment by jeffchown** [comment]
UPDATE: This has become an issue in multiple places in my current app - wherever I use `.lazy` in a form, the 'lazy input' has the potential to fire a duplicate `syncUpdate` *after* the form has been submitted and reset, thus setting the form's next iteration/usage's same input field to the incorrect value.

@joshhanley Have you had a look at this?  Any and all help would be appreciated.

**Comment by joshhanley** [comment]
@jeffchown not yet, but it does sound like a race condition.

I'd be curious to know what happens with an input and a button not using Livewire and Alpine, just using plain javascript, whether the same issue would occur or not. It sounds like the button click handler is firing before the input change event happens (which is what lazy listens for).

**Comment by joshhanley** [comment]
Ah sorry ignore my comment, I didn't re-read it properly, for some reason I thought the submit was happening before the input change.

Hmm that is strange that the old sync inputs are not being cleared. I've pulled down the surge repo and tested (FYI have to add .lazy to the modal inputs, it was working fine for me and I couldn't work out why 🤣).

I'll keep digging and see if I can find anything.

**Comment by jeffchown** [comment]
Thanks, @joshhanley.  Looking forward to your findings.

**Comment by jeffchown** [comment]
@joshhanley A quick update/note - the problem only seems to occur when using `wire:model.lazy`.  A normal `wire:model` or one with `wire:model.defer` works just fine.

**Comment by jeffchown** [comment]
one more update, @joshhanley - looks like something has changed (maybe in Livewire update since my original posting of this issue, so now (still using Surge per the steps I described above) the duplicate `syncInput` (from the previous edit) is fired as part of the next `edit`'s event payload - but nonetheless, a duplicate is still fired.

**Comment by joshhanley** [comment]
@jeffchown yeah that's what I found too. I think it has something to do with the actions not being cleared after the response has come back. I've dug through the code, am slowly starting to understand how it works, but can't pin point where it should clear the actions.

It's still shouldn't be firing the syncInput title on the second time around if all you have changed is the amount, but at least it is firing with the correct data.

Is your system now working as expected though after the update?

**Comment by jeffchown** [comment]
Hey @joshhanley Exactly (re: actions not being cleared).  I'm doing a little digging too - getting to know the codebase a little better.

Agreed - it shouldn't be firing the 2nd syncInput 2nd time around.  

As for 'firing with the correct data' - it is only the correct data if you edit the same record the 2nd time, otherwise it is the data edited from the 1st record, so it is incorrect re: the 2nd record's edit.

And, if this is the case, editing a different record the 2nd time, the duplicate event has the potential of overwriting valid data with incorrect data - which is what happened in my app and brought this issue to my attention.

So, when the user uses form in the way described in this issue, it is still causing unexpected data-overwrites/issues in my app which of course can lead to data integrity errors.

**Comment by joshhanley** [comment]
@jeffchown I cracked it! Have a look at PR #2245 😁

**Comment by jeffchown** [comment]
Nice catch, @joshhanley !  Just had a look at the PR - can't wait to take it for a spin! 👍    Thanks for the deep dive.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
