### ISSUE TITLE
Getting an error when I am trying to filter retrieved data, through advanced search

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2149]
As I am following Caleb Porzio's screencast. I am building a data table, currently I am trying to imply advanced search facility, as I am following the complete series step by step, I'm currently stuck with applying search filters, or using advanced search option.

https://laravel-livewire.com/screencasts/s7-advanced-search

I'm getting the following error, whenever, I try to search users by using advanced search criteria i.e. email. Its filters the data, but throws the error bellow in loop, if incase I try to search the user with the wrong email, which is not available in the database. It throws me end number of instances of the same error, which is mentioned below.

```
Uncaught TypeError: Cannot read property 'split' of null
    at LoadingStates.js:174
    at Array.forEach (<anonymous>)
    at startLoading (LoadingStates.js:172)
    at setLoading (LoadingStates.js:143)
    at LoadingStates.js:39
    at MessageBus.js:17
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16)
    at Object.call (HookManager.js:38)
    at Object.callHook (Store.js:120)
```
**How The Error Is Produced**

![Advanced Search - Error Loop](https://user-images.githubusercontent.com/65024122/100915540-80a99d80-34fa-11eb-9fbc-ba07c78cb0eb.gif)

**App/Http/Livewire/UserController**
```
public $showFilters = false;
public $filters = [
    'email' => null
];

public function render() {
    $users = User::query() 
        -> when($this -> filters['email'], fn($query, $email) => $query -> where('email', $email))
        -> search('name', $this -> search)
        -> paginate(5);
    $roles = Role::all();
    return view('livewire.user-controller', ['users' => $users, 'roles' => $roles]);
}
```

**resources/views/livewire/user-controller**
```
<div>
    @if ($showFilters)
    <div class="bg-cool-gray-200 p-6 rounded shadow-inner flex relative">
        <div class="w-1/2 pr-2 space-y-4">
            <x-input.group inline for="filter-email" label="Email">
                <x-input.text wire:model.lazy="filters.email" id="filter-email" placeholder="Enter Email" />
            </x-input.group>
        </div>
    </div>
    @endif
</div>
```

**Comment by joshhanley** [comment]
@toxifiedmatrix what version of Livewire/Laravel/Alpine/Browser are you using? 

Also can you share you code for x-input.text? 

Seems strange as your using .lazy modifier, so it shouldn't be firing anything at all until you tab away from the input

**Comment by toxifiedmatrix** [comment]
That's what, I'm just unable to rectify or debug the same. Please check the code below.

```
@props([
    'leadingAddOn' => false,
])

<div class="flex rounded-md shadow-sm">
    @if ($leadingAddOn)
        <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
            {{ $leadingAddOn }}
        </span>
    @endif

    <input {{ $attributes->merge(['class' => 'flex-1 form-input border-cool-gray-300 block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' . ($leadingAddOn ? ' rounded-none rounded-r-md' : '')]) }}/>
</div>
```

**Comment by austenc** [comment]
@toxifiedmatrix this seems to have something to do with a `wire:loading` and/or `wire:target` directive somewhere. Do you happen to have a public github repository we could check out to help debug this?

**Comment by toxifiedmatrix** [comment]
> @toxifiedmatrix this seems to have something to do with a `wire:loading` and/or `wire:target` directive somewhere. Do you happen to have a public github repository we could check out to help debug this?

@austenc Here is the repository for the same. https://github.com/toxifiedmatrix/laravel-advanced-search

**Comment by joshhanley** [comment]
@toxifiedmatrix I've pull down down your repo, can I suggest adding seeders to any demo's you post, didn't realise I had to add roles before I could register a user 😆

This issue is to do with where you have your wire:key setup.

In `users-controller.blade.php` at line 67/68 you should put the wire:key on the table row rather than the table cell.
The reason is, morphdom isn't removing the loading handler when there are no results, hence why the error is being thrown.
Moving the wire:key to the row fixes that issue.

Change it from this:
```blade
<x-table.row wire:loading.class.delay="opacity-50">
    <x-table.cell wire:key="row-{{ $user->id }}" class="pr-0">
```

To this:
```blade
<x-table.row wire:key="row-{{ $user->id }}" wire:loading.class.delay="opacity-50">
    <x-table.cell class="pr-0">
```

Hope this helps!

**Comment by toxifiedmatrix** [comment]
@joshhanley Ohh, I'll surely do remember that, and thanks a lot for pointing out the error, it's working flawlessly! 😄

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
