### ISSUE TITLE
Support Page Visibility API

### ISSUE THREAD

**Issue by tillkruss** [livewire/livewire#215]
It would be incredible if `wire:poll` would support the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API), maybe even by default.

That would reduce unnecessary server load, as well as make transitions occur when the user is looking at the page.

**Comment by tillkruss** [comment]
Additionally, the polling could stop of the document is offline.

https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event

**Comment by tillkruss** [comment]
~1000 unnecessary requests, I think this PR would be a huge win @calebporzio.

<img width="355" alt="Screen Shot 2019-09-13 at 10 08 20 AM" src="https://user-images.githubusercontent.com/665029/64881018-832a8980-d60e-11e9-8696-f9235426e164.png">

**Comment by fgilio** [comment]
Yes! Never thought about this, but it makes perfect sense.
Maybe even slow down the interval 10x when the page is not visible. But I don't feel this would be required.

**Comment by tillkruss** [comment]
Slowing it down might be interesting @calebporzio.

Example 1:

I want to **stop** fetching of new messages when the window is inactive. When the user switches back to the tab it will fetch new messages and show and animation for new ones.

Example 2:

I want to **slow down** fetching of notifications from every `2s` to every `30s`, because of the server load. Animations won't matter it's just a little red dot.

**Comment by calebporzio** [comment]
Yeah, slowing them down would be interesting. For now, I just disabled them when the tab is in the background: #281

**Comment by fgilio** [comment]
Amazing!

**Comment by calebporzio** [comment]
So, slowing them down would be kind of hard to implement.

Instead, I just added this bit of code, which will act as a lottery to let 10% of tried background requests through. This way, if there's some state like a "new-notifications" bubble, it will get set at some point.

```js
        setInterval(() => {
            if (livewireIsInBackground && Math.random() < .9) return

            // Fire the ajax request
        }, [polling duration]);
```

**Comment by calebporzio** [comment]
Here's a screenshot of the requests happening sparsely, then happening sequentially (when I focused the browser):

![image](https://user-images.githubusercontent.com/3670578/65297927-8d311880-db37-11e9-8435-756ddc8e736e.png)

**Comment by calebporzio** [comment]
I think I might pull this down to 5% though.

**Comment by fgilio** [comment]
What concerns me about 5% is that the chance of not getting any request doubles, form 10%. That said, as soon as the page is visible again we're getting fresh updates... so it may be alright.




<details>
  <summary>Also, related:</summary>
  
  ![3b1w2v](https://user-images.githubusercontent.com/6857732/65300044-6f1fe400-db48-11e9-8b2b-d5cdbb71c754.jpg)
</details>
