### ISSUE TITLE
i have same issue when i use livewire in contact form while typing form automatically send GET request and return with exception

### ISSUE THREAD

**Issue by WaelMz** [livewire/livewire#2151]
i have same issue when i use livewire in contact form while typing form automatically send GET request and return with exception 
The GET method is not supported for this route. Supported methods: POST.  i can not figure out whats happens ...
![Untitled](https://user-images.githubusercontent.com/33140498/100799228-6950ae80-342d-11eb-864a-7d7d042ab6b7.png)

_Originally posted by @WaelMz in https://github.com/livewire/livewire/issues/1779#issuecomment-736833716_

**Comment by joshhanley** [comment]
@WaelMz can you share your composer class and blade view, and also what versions of Livewire/Laravel/Alpine/Browser you are using?

**Comment by austenc** [comment]
As @joshhanley suggested, the versions you're using would be helpful. Let us know how we can reproduce the error and we'll be happy to fix it. Closing this issue until there's more reproduction info, but feel free to reopen at that point, thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ideadx** [comment]
Having the same issue while navigating using $records->links() for pagination for the records.

**Comment by joshhanley** [comment]
@ideadx I have noticed there are some issues when using pagination in a child component trigger this error. Is your pagination setup in a child component?

**Comment by jarsoff** [comment]
http://127.0.0.1:8000/livewire/message/livewire-ui-modal <-   ???? De donde sale este get cuando se dispara el componente?
