### ISSUE TITLE
Getting an error when trying to type hint class properties and route-model bind

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2152]
I have successfully created crud operations using the type hint with route model binding, but I am unable to do so after updating the livewire. I need to store the input in the database, but its throwing me a weird error.

> Typed property App\Http\Livewire\Backend\UserManagement\InvitationController::$invitation must not be accessed before initialization

**App\Http\Livewire\InvitationController**
```
<?php

namespace App\Http\Livewire\Backend\UserManagement;

use Livewire\Component;
use Livewire\WithPagination;

use App\Models\Invitation;

class InvitationController extends Component
{
    use WithPagination;

    public $showEditModal = false;
    public Invitation $invitation;

    protected $rules = [
        'invitation.email' => 'required | email | max:255 | unique:invitations,email',
    ];

    public function render()
    {
        $invitations = Invitation::where('registered_at', null)->get();
        return view('livewire.backend.user-management.invitation-controller', ['invitations' => $invitations]);
    }

    public function create()
    {
        $this->showEditModal = true;
    }

    public function save()
    {
        $this->validate();
        $this->invitation->save();
        $this->invitation->generateInvitationToken();
        $this->showEditModal = false;
    }
}
```

**resources\views\livewire\invitation-controller**
```
<form wire:submit.prevent="save">
    <x-modal.dialog wire:model.defer="showEditModal">
        <x-slot name="title">Edit User</x-slot>

        <x-slot name="content">
            <x-input.group for="email" label="Email" :error="$errors->first('invitation.email')">
                <x-input.text wire:model="invitation.email" id="email" placeholder="Enter Email" />
            </x-input.group>
        </x-slot>

        <x-slot name="footer">
            <x-button.secondary wire:click="$set('showEditModal', false)">Cancel</x-button.secondary>
            <x-button.primary wire:click.prevent="save">Save</x-button.primary>
        </x-slot>
    </x-modal.dialog>
</form>
```

**Comment by joshhanley** [comment]
@toxifiedmatrix can you please make sure you don't delete the issue template when you submit an issue, and fill out the information it requests (like versions)? That can help with debugging as sometimes there are known issues on specific version.

In this instance, I believe you need to initialise $this->invitation with an empty object. So in your mount method put `$this->invitation = new Invitation();` otherwise binding directly to the model properties won't work.

Hope this helps!

**Comment by toxifiedmatrix** [comment]
Yes @joshhanley I'll surely keep that in mind. Thanks alot it worked perfectly!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
