### ISSUE TITLE
wire:model to model attribute that has mutator and accessor

### ISSUE THREAD

**Issue by kreierson** [livewire/livewire#2153]
### Description
I have an input that is bound to a price attribute on my model. I have an accessor and mutator set up for this attribute to convert the price to cents. If the I try to edit the price input and make it blank I receive the error "A non numeric value encountered"
 
### Exact steps to reproduce
Create model with accessor and mutator
```
	public function getPriceAttribute($value)
	{
		return $value / 100;
	}

	public function setPriceAttribute($value)
	{
		$this->attributes['price'] = $value * 100;
	}
```
Create a livewire component with collection of models
```
class EditPricingRuleModal extends BaseComponent
{
	public $prices;

	public function mount($pricingRuleId)
	{
		$this->prices = ActivityPrice::where('activity_pricing_rule_id', $pricingRuleId)->get()->sortBy('number_of_people');
	}
}
```

Create an input and wire it up to the price
```
@foreach ($this->prices as $index => $price)
<x-form.text-input wire:model="prices.{{$index}}.price" type="tel" placeholder="Price" class="w-full"/>
@endforeach
```

### Stripped-down, copy-pastable code snippets

See above

I find it odd that livewire even hits the model before I even call save on the model?

**Context**
- Livewire version: 2.0
- Laravel version: 8.12
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by jeffchown** [comment]
@kreierson Have you tried changing your setter to first cast the passed `$value` to an integer? (a blank value would become 0) e.g.:

```
public function setPriceAttribute($value)
{
	$this->attributes['price'] = (int) $value * 100;
}
```

**Comment by kreierson** [comment]
@jeffchown yep that was my exact workaround :)

In addition i added .lazy to my wire:model because as soon as the input goes blank a zero comes up immediately. So if a  user wanted edit a value and cleared the input a zero would keep populating and they would have to be quick to enter in the new value.

I just find it odd that the mutator is even getting run when updating the form input. I'm not sure if this is a bug or not, but figured others would run into this so I posted it.

If I'm not mistaken, in standard Laravel, mutators don't get called until save is called on the model. I feel like it shouldn't get run when simply updating an input bound to the model.

Thanks for your reply.

**Comment by jeffchown** [comment]
@kreierson Glad to hear you got it working 👍 

To my understanding, when Livewire performs a syncInput to sync the input’s value with the model attribute named in your wire:model, it performs an assignment to your Livewire component class’s public var containing the model (e.g. your $yourModel->price).  In doing so, it will use any setters you have created in your model’s class definition in your regular Laravel code.

The same would happen in ‘standard Laravel’ if you had a line of code such as `yourModel->price = 123` (even before a save), it would still call your `setPriceAttribute` method to perform the assignment.

**Comment by kreierson** [comment]
@jeffchown  Oh, that's interesting. Then I suppose everything is technically working as intended. I'll close this. Thanks for your explanations.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by jeffchown** [comment]
You’re welcome, @kreierson
