### ISSUE TITLE
Cannot test if model attribute is set when hidden 

### ISSUE THREAD

**Issue by xfudox** [livewire/livewire#2161]
### Description
Already opened a [SO question](https://stackoverflow.com/questions/65107519/cannot-test-laravel-livewire-model-hidden-attribute-with-assertset) about it.

Long story short: testing if a model attribute is set trough `set('model.attribute')` with `assertSet('model.attribute')` when the attribute is listed in `$hidden` model's array result in a failure because `set` access models attribute as an array index, therefore it is masked.
I've also tested that removing the attribute entry from the `$hidden` array make the test succeed.

E.g.: `User` with its hidden `password` attribute in a registration form.

### Exact steps to reproduce
 - create a Livewire component with a public `Model` variable
 - the model have an attribute listed in the `$hidden` array
 - create a test that try to set the model attribute and check if it is set.

#### User model:
```php
class User extends Model
{
    protected $fillable = [
        'password',
    ];

    protected $hidden = [
        'password',
    ];
}
```

#### Livewire component:
```php
class Registration extends Component
{
    public User $user;

	public function mount()
	{
		$this->user = new User();
	}
}
```

#### The test:
```php
public function testCanSetUserPassword()
    {
        Livewire::test(Registration::class)
            ->set('user.password', 'new_password')
            ->assertSet('user.password', 'new_password');
    }
```

**Context**
- livewire/livewire: 2.3.5
- laravel/framework: 8.17.5
- phpunit/phpunit: 9.5.0

**Comment by xfudox** [comment]
### Update \#1
**My fault**, I've stripped down my actual code too much for this issue without before testing it: in my original test code I set and check more model attributs, not a single one, and the problem depicted arise, but after a small refactor and splitting the original test into separate ones (i.e.: one test per model attribute) the single test on the hidden attribute succeed.

The failure now has moved to a new test where I need to set all the model data anche check that it is correctly created and persisted.  
And again, the test succed if I remove the culprit attribute from the `$hidden` array.

**Comment by joshhanley** [comment]
@xfudox due to the hidden attribute, it won't be accessible by Livewire.

As it is for a password anyway, I wouldn't recommend binding to the password field directly.
I would recommend adding a property on your Livewire component class called $password and binding your input to that. Then when you go to save your user attach the new password then using `$this->user->password = $this->password`.

Hope this helps!

**Comment by austenc** [comment]
Thanks, @joshhanley! Closing since it seems this is now resolved (and your suggestion is a better practice)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
