### ISSUE TITLE
Unable to sort data table according to the selected field

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2174]
### Description
I am trying to sort user data, according to the field name. I am unable to attain the basic sorting function to achieve the said results. I am following the [Livewire Screencasts - Basic Sorting](https://laravel-livewire.com/screencasts/s7-sorting) episode. Event after following it thoroughly, an unknown error is being displayed.

### Exact steps to reproduce
Whenever I try to visit the route, to access the data table, the below mentioned error is being thrown.

**Error**
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `users` order by `` asc limit 5 offset 0)
```

### Stripped-down, copy-pastable code snippets

**App\Http\Livewire\UserController**
```
public $sortField;
public $sortDirection = 'asc';

protected $queryString = ['sortField', 'sortDirection'];

public function sortBy($field)
    {
        $this->sortDirection = $this->sortField === $field
            ? $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc'
            : 'asc';

        $this->sortField;
    }

$users = User::query()
            ->when($this->filters['search'], fn($query, $search) => $query->where('name', 'like', '%'.$search.'%'))
            ->orderBy($this->sortField, $this->sortDirection)
            ->paginate(5);
        return view('livewire.backend.user-management.user-controller', ['users' => $users]);
```

**resources\views\livewire\user-controller**
```
<x-table>
    <x-slot name="head">
        <x-table.heading class="pr-0 w-8">
            <x-input.checkbox />
        </x-table.heading>
        <x-table.heading sortable wire:click="sortBy('id')" :direction="$sortField === 'id' ? $sortDirection : null">ID</x-table.heading>
        <x-table.heading sortable wire:click="sortBy('name')" :direction="$sortField === 'name' ? $sortDirection : null">Name</x-table.heading>
        <x-table.heading sortable wire:click="sortBy('email')" :direction="$sortField === 'email' ? $sortDirection : null">Email</x-table.heading>
        <x-table.heading sortable wire:click="sortBy('role')" :direction="$sortField === 'role' ? $sortDirection : null">Role</x-table.heading>
        <x-table.heading sortable wire:click="sortBy('created_at')" :direction="$sortField === 'created_at' ? $sortDirection : null">Creation</x-table.heading>
        <x-table.heading></x-table.heading>
    </x-slot>

    <x-slot name="body">
        @forelse($users as $key => $user)
        <x-table.row wire:key="row-{{ $user->id }}" wire:loading.class.delay="opacity-50">
            <x-table.cell class="pr-0">
                <x-input.checkbox wire:model="selected" value="{{ $user->id }}" />
            </x-table.cell>
            <x-table.cell>{{ $users->firstitem() + $key }}</x-table.cell>
            <x-table.cell>{{ $user->name }}</x-table.cell>
            <x-table.cell>{{ $user->email }}</x-table.cell>
            <x-table.cell>
                @foreach($user->roles as $role)
                {{ $role->name }}
                @endforeach
            </x-table.cell>
            <x-table.cell>{{ $user->date_for_humans }}</x-table.cell>
            <x-table.cell>
                <x-button.link wire:click="edit({{ $user->id }})">Edit</x-button.link>
            </x-table.cell>
        </x-table.row>
        @empty
        <x-table.row>
            <x-table.cell colspan="7">
                <div class="flex justify-center items-center">
                    <span class="font-medium py-8 text-cool-gray-400 text-xl">No Results Found</span>
                </div>
            </x-table.cell>
        </x-table.row>
        @endforelse
    </x-slot>
</x-table>
```

To debug the above error, here is the repository, https://github.com/toxifiedmatrix/laravel-project. Please seed the database before you proceed. The default credentials are:

Email: administrator@localhost.com
Password: password

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.17.2
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@toxifiedmatrix you are missing the field assignment at the end of your sortBy method, currently you have
```php
$this->sortField;
```
But it should be
```php
$this->sortField = $field;
```

In terms of the unknown column error, you need to set an initial property e.g. `public $sortField = 'name';` or if you want $sortField to be blank initially, you can change you eloquent query to wrap order by in a when method
```php
->when($this->sortField, fn($query) => $query->orderBy($this->sortField, $this->sortDirection))
```

Hope this helps!

**Comment by joshhanley** [comment]
@toxifiedmatrix can I suggest creating discussions ([new discussion](https://github.com/livewire/livewire/discussions/new)) for these implementation problems rather than opening an issue?
That way issues a left for Livewire bugs.

Thanks!

**Comment by toxifiedmatrix** [comment]
Thanks a lot, its working perfectly. Surely, I'll do remember that, will create discussion for such problems.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
