### ISSUE TITLE
Morphed fields errors

### ISSUE THREAD

**Issue by ju5t** [livewire/livewire#2182]
### Description

I have a `Quote` model with a morphed field called `detail` (we store details in a separate model). As soon as I start to use a morphed model in a Livewire component and trigger any action (either a model update or a specific model with `click`) it returns an error.

The line below is what raises the error.

```php
public function detail()
{
    return $this->morphOne($this->detailable_by, 'detailable');
}
``` 

The error being `Class name must be a valid object or a string`.

I set a public property in `mount()`. This is named `$detail`. This is the culprit as without it we get no error either. I do this with:

```
$this->detail = $this->quote->detail->toArray();
```

The reason for this is that we want to prevent duplicate html and swap things easily with Blade components. For example, if the `detailable_by` equals to paint, we would do:

```html
<x-product-type.paint :detail=$detail />
```

It also allows us to dynamically include the rules for `detail.color` or other properties, instead of including all rules for all types in a single component.

### Exact steps to reproduce

Change anything that triggers a model update.

### Stripped-down, copy-pastable code snippets

Our `mount()`:

```php
public function mount()
{
    $this->items = $this->quote->items->map(function ($item) {
        return [
            'id' => $item->id,
            'quantity' => $item->quantity,
            'price' => $item->price,
            'tooling' => $item->tooling,
            'leadtime' => $item->leadtime,
            'subtotal' => $item->subtotal,
        ];
    })->collect();

    $this->detail = $this->quote->detail->toArray();
}
```

Our `quote` model includes:

```
public function detail()
{
    return $this->morphOne($this->detailable_by, 'detailable');
}
```

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.0

**Comment by ju5t** [comment]
I haven't found a solution and pretty stuck right now. I am happy to pay for either a solution in Livewire if this is a bug or help to solve this in our code base.

**Comment by Gustavinho** [comment]
Hi @ju5t, i read your post on twitter, Quick question, what is the value of `$this->detailable_by` ?

**Comment by ju5t** [comment]
Thanks for the reply! `detailable_by` is a polymorphic relationship and its value is the class of a model. `App\Models\Paint` could be a possible value.

**Comment by ItsMalikJones** [comment]
The following line should get you back up and running:

`$this->detail = $this->quote->detail()->first()->toArray();`

**Comment by ju5t** [comment]
Cool, that works!

Do you know why `$this->quote->detail->toArray()` doesn't? This should be exactly the same. Is this a bug or missing feature in Livewire?

**Comment by ItsMalikJones** [comment]
I spent some more time looking at this _this_ morning and I don't think this is a Livewire issue. The error you're mentioning happens during hydration when trying to load the relations during the `restoreModel` method in `SerializesAndRestoresModelIdentifiers.php`. However, with that being said, I don't think Livewire isn't doing anything out of the ordinary here. If you open up Tinkerwell and try to load the relation normally(without Livewire), the error occurs there as well. This makes me think it could have something to do with how the data is structured.

**Comment by ju5t** [comment]
Ok, not sure what to do about that, but I’m very happy with a working solution so definitely not complaining haha. Thanks so much @ItsMalikJones.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
