### ISSUE TITLE
Unable to ignore email of the user, when updating a selected user, in case of model property binding.

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2183]
### Description
As I'm implying model property binding, by type hinting. I am unable to ignore the email of the user selected to edit, when updating user details from the admin panel. I am using the `$rules` property, to validated the rules.

### Exact steps to reproduce
Whenever I am trying to add the rule to the email input to ignore the email of the selected user, it gives a syntax error.
```
    protected $rules = [
        'user.name' => ['required','string','max:255'],
        'user.email' => ['required','string','email','max:255','unique:users,email'.$user->id],
        'role' => ['required'],
    ];
```

### Stripped-down, copy-pastable code snippets
**App\Http\Livewire\UserController**
```
    public $role;
    public User $user;

    protected $rules = [
        'user.name' => ['required','string','max:255'],
        'user.email' => ['required','string','email','max:255','unique:users,email'],
        'role' => ['required'],
    ];

    public function mount()
    {
        $this->user = $this->resetUserForm();
    }

    public function resetUserForm()
    {
        return User::make();
    }
```
**resources\views\livewire\user-controller**
```
    <form wire:submit.prevent="save">
        <x-modal.dialog wire:model.defer="showEditModal">
            <x-slot name="title">Edit User</x-slot>

            <x-slot name="content">
                <x-input.group for="name" label="Name" :error="$errors->first('user.name')">
                    <x-input.text wire:model="user.name" id="name" placeholder="Enter Name" />
                </x-input.group>

                <x-input.group for="email" label="Email" :error="$errors->first('user.email')">
                    <x-input.text wire:model="user.email" id="email" placeholder="Enter Email" />
                </x-input.group>

                <x-input.group for="role" label="Role" :error="$errors->first('role')">
                    <x-input.select wire:model="role" id="role">
                        @foreach ($roles as $role)
                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                        @endforeach
                    </x-input.select>
                </x-input.group>

                <x-input.group for="delete" label="Delete">
                    <x-button.secondary wire:click="delete">Delete Account</x-button.secondary>
                </x-input.group>
            </x-slot>

            <x-slot name="footer">
                <x-button.secondary wire:click="$set('showEditModal', false)">Cancel</x-button.secondary>
                <x-button.primary type="submit">Save</x-button.primary>
            </x-slot>
        </x-modal.dialog>
    </form>
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.17.2
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@toxifiedmatrix that won't work as PHP won't evaluate $user->id inside a property definition.

You can instead use a rules method and return this array from there, and remove the $rules property all together.

```php
protected function rules()
{
    return [
        'user.name' => ['required','string','max:255'],
        'user.email' => ['required','string','email','max:255','unique:users,email'.$user->id],
        'role' => ['required'],
    ];
}
```

But that also has issues, see this issue #2070, and this PR #2077

**Comment by toxifiedmatrix** [comment]
As I am using the below piece of code, It's throwing me an error, saying "Typed property App\Http\Livewire\Backend\UserManagement\UserController::$user must not be accessed before initialization"
```
protected function rules()
    {
        return [
            'user.name' => ['required','string','max:255'],
            'user.email' => ['required','string','email','max:255','unique:users,email'.$this->user->id],
            'role' => ['required'],
        ];
    }
```

**Comment by joshhanley** [comment]
@toxifiedmatrix yeah there is also an issue with that as I mentioned above. Did you have a look at the issue and PR I linked?

If you could add your support to the PR #2077 that this feature is required, that would be great!

There is another work around though, I was thinking this morning, can you share your whole method where you run `$this->validate();`

**Comment by toxifiedmatrix** [comment]
@joshhanley Yes, I did see, but I wasn't able to reach to the conclusion. Yes, surely, below is the piece of code, for validation.
```
    public function edit(User $user)
    {
        $this->resetValidation();
        $this->user = $user;
        $this->role = $user->roles->pluck('id');
        $this->showEditModal = true;
    }

    public function save()
    {
        $this->validate();
        $this->user->roles()->sync($this->role);
        $this->user->save();
        $this->showEditModal = false;
    }
```

**Comment by joshhanley** [comment]
@toxifiedmatrix ok try this

Change your rules method to this (I have just removed the unique rule)
```php
protected function rules()
{
    return [
        'user.name' => ['required','string','max:255'],
        'user.email' => ['required','string','email','max:255'],
        'role' => ['required'],
    ];
}
```

And update your save method to this
```php
public function save()
{
    $this->validate();
    $this->validate([
        'user.email' => 'unique:users,email'.$user->id,
    ]);
    $this->user->roles()->sync($this->role);
    $this->user->save();
    $this->showEditModal = false;
}
```

Basically what is happening, is the first validate should run the rules from the rules method, and the second validate should only run that one unique rule.

Let me know how it goes!

**Comment by toxifiedmatrix** [comment]
@joshhanley I followed as you said. When I was using ` 'user.email' => 'unique:users,email'.$user->id`, I was getting undefined user variable, so I changed it to ` 'user.email' => 'unique:users,email'.$this->user->id`. After that its throwing me the following error.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email1' in 'where clause' (SQL: select count(*) as aggregate from `users` where `email1` = administrator@localhost.com)

**Comment by joshhanley** [comment]
@toxifiedmatrix sorry, there was an error in the syntax, I just copied what you had pasted. It's missing the comma `,` after email. Change it to

```php
'user.email' => 'unique:users,email,'.$user->id,
```

**Comment by toxifiedmatrix** [comment]
Its working perfectly now. Thanks a lot for this! How come its working down there but not within the rules function.

**Comment by joshhanley** [comment]
@toxifiedmatrix no worries!

The current order of how a component is hydrated means the rules property/method are accessed before the model is populated. If merged #2077 will fix that. 

So hopefully it gets merged!

**Comment by toxifiedmatrix** [comment]
Ohh okay I see. So will there be a fix for this in the future version of livewire?

**Comment by joshhanley** [comment]
@toxifiedmatrix it's not guaranteed, but if #2077 gets merged, then it will be. So hopefully it gets merged! 🙂

**Comment by toxifiedmatrix** [comment]
@joshhanley I know right. I myself, am waiting too. 😄

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
