### ISSUE TITLE
table cell colspan ignored in wire:loading

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2185]
Here example of the problem here: https://laravelplayground.com/#/snippets/0db3cdab-9bc0-495c-9160-6c1b103d7a2a

If you put a wire:loading on a row (so table row only shows during load), then the colspan attribute is ignored.

Click the button in the example to see the problem.

**Comment by jeffchown** [comment]
@AdvancedStyle I tried the following change in your playground, and while not ideal, it worked:

```
        <td colspan="4" style="text-align: center;">
          <div wire:loading>
            <b>We are loading something</b>
          </div>
        </td>
```

By moving the `wire:loading` to a div inside the `<td>`, morphdom doesn't have to deal with the `<td>` tag.

**Comment by joshhanley** [comment]
Yeah wire:loading by default sets `display: inline-block;`, which doesn't work for a table row, as it should be `display: table-row;`.

Livewire has built in displays for flex, grid, inline and table, but not table row.

You can still do this manually yourself, for example (if you use tailwind classes) you could control classes added instead
```
<tr wire:loading.class="table-row" wire:loading.remove.class="hidden" class="hidden">
```

https://laravelplayground.com/#/snippets/6e1e4582-11c0-4bae-b11a-f17470ccd5fc

Hope this helps!

**Comment by AdvancedStyle** [comment]
Thanks for the work around solutions.

**Comment by joshhanley** [comment]
@AdvancedStyle no worries! Can you close this issue?

**Comment by joshhanley** [comment]
@AdvancedStyle it would be nice, but I don't think it's likely Livewire will handle all potential variations as that is more code to maintain. I can't close your issue only you or the maintainer can 🙂

**Comment by austenc** [comment]
Closing since this is easily resolved via @joshhanley's suggestion. It would likely be straightforward to submit a PR for this, so feel free to do that if you think it should belong in Livewire's core. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
