### ISSUE TITLE
php artisan livewire:publish --pagination

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2194]
In the documentation (https://laravel-livewire.com/docs/2.x/pagination) is says you can publish the pagination view by doing:

```php artisan livewire:publish --pagination```

This does not actually work (results in error below):

```                                            
  The "--pagination" option does not exist.  
                                            
```

**Comment by austenc** [comment]
@AdvancedStyle please try using the latest version of Livewire. 

In the future please include the Livewire version you're using as suggested by the issue template.

**Comment by AdvancedStyle** [comment]
Sorry i was using 2.3.1 (instead of 2.3.5).

No longer a problem.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by austenc** [comment]
Thanks @AdvancedStyle! 👍
