### ISSUE TITLE
Pagination table component inside a component not working because of Query String

### ISSUE THREAD

**Issue by pascallieverse** [livewire/livewire#2195]
### Description
If you want to create a table component with inside of it a pagination using the WithPagination trait provided by Livewire and use it in another component it breaks the page url and all click events are resulting in a 405 method not allowed.

### Exact steps to reproduce
Create a table component:

```
class UserTableComponent extends Component
{
    use WithPagination;

    public function render()
    {

        return view('livewire.users-table-component', [
            'users' => Users::paginate(10)
        ]);
    }
}
```

And the view:
```
<div>
    <table>
        <thead>
        <tr>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td>
                        {{$user->name}}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $users>links() }}
</div>
```
Then create another livewire component and include the component inside the component view and the click events will all break. This is caused because of the getQueryString function inside the LiveWire WithPagination trait.

```
    public function getQueryString()
    {
        return array_merge(['page' => ['except' => 1]], $this->queryString);
    }
```

My solution for now is just to create a custom trait without this function.

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.17.2

**Comment by austenc** [comment]
Does your other component manipulate the query string? I would expect this to work.

**Comment by pascallieverse** [comment]
No, the upper component does not contain a function that changes the query string. It contains only 1 eloquent item that is a firstOrFail. So a empty test component would do if you want to reproduce it.

**Comment by austenc** [comment]
@pascallieverse do you have a repository that illustrates this? I just tried it on an example repo and having the pagination in a child component worked.

**Comment by DanielSpravtsev** [comment]
Same issue. Tested from 2.3.6 to latest version.
WithPagination trait, something that uses return of function getQueryString changes query to http://example.com/livewire/message/admin.home and get 405 error
@calebporzio

**Comment by DanielSpravtsev** [comment]
Same issue. Tested from 2.3.6 to latest version.
WithPagination trait, something that uses return of function getQueryString changes query to http://example.com/livewire/message/admin.home and get 405 error

Founded issue "fix" #1816 (comment)
@pascallieverse @calebporzio

**Comment by joshhanley** [comment]
@pascallieverse can you try the fix @DanielSpravtsev linked above (https://github.com/livewire/livewire/issues/1816#issuecomment-764409404) by putting the `WithPagination` trait also on the parent component?

I'm going to close this and follow it on the other issue, but if you test it and it doesn't work, please let me know or reopen it and we can investigate it further.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
