### ISSUE TITLE
Input model binding does not work as expected.

### ISSUE THREAD

**Issue by thatsenam** [livewire/livewire#2206]
### Suppose i have a simple input field that is binded to $text. and a simple p tag that displays that input $text. When i type through keyboard it does works. but if i change the input value from jquery programatically it does not updates the p tag. [In my scenario i had to change the value through a virtual number pad created with jquery/js]. when i update the input value programatically it does update the value in input field but not the actual $text that is binded to <p> tag. 

Simple Code.
```
<input type="text"  wire:model="text">
<p> {{ $text }}</p>
```

Jquery part

```
                if ($(':focus').is('input')) {
                    $(':focus').trigger("input") // you can trigger keypress like this if you need to..
                        .val(function (i, val) {
                            return "I am from jquery";
                        });
                 }
```

Let me know if anyone is unable to figure out the situation.

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by joshhanley** [comment]
@thatsenam that won't work, if you need to set the values programmatically, use the `@this` directive, see here https://laravel-livewire.com/docs/2.x/inline-scripts

Hope this helps!

**Comment by thatsenam** [comment]
@joshhanley It does not sync with backend variable.

**Comment by joshhanley** [comment]
@thatsenam yeah triggering an input using Javascript won't change the backend properties, you need to do that manually.

Using @this will sync the backend variable, so if you want to update `$text` backend property, you would call `@this.text = "<new data here>"` inside your jquery function, replacing \<new data here> with whatever value you want to set it to.

**Comment by thatsenam** [comment]
It does not works for nested data (assoc array).

**Comment by joshhanley** [comment]
@thatsenam ok sorry, your original post didn't mention anything about nested data 🙂

To set nested data you can use the set method with dot notation for the key `@this.set('array.key', "new value goes here")`

If that doesn't work for what you need, can you share a more information and be specific about what you are trying to achieve and code with the correct properties in it, so we can provide a more accurate response?

Hope this helps!

**Comment by austenc** [comment]
Thanks, @joshhanley. Closing since this is not a Livewire bug and `@this.set` should work as Josh suggested.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by parthkapatel** [comment]
Hello @joshhanley ,
     I tried your suggested solution for update data from backed using jQuery like [this](https://github.com/livewire/livewire/issues/2206#issuecomment-744066235)  but after that I faced one another problem that when this line of code is run then form submitted automatically without clicking on the submit button and page data is load accordingly.

   I want to update the multiple dropdown value from the backend and when I'll click on submit button then filter the data according
