### ISSUE TITLE
Arrays lose keys if keys are integers

### ISSUE THREAD

**Issue by shortbrownman** [livewire/livewire#2207]
### Description
Using `wire:model="model.{{ $id }}"`, the keys will be lost and the array will just start from 0.

### Exact steps to reproduce
Set up an array, `$model` to use for `wire:model`. Loop through a collection of Models and use these items' id as the key for `$model`. Dump out and see that the array keys are lost and start from 0.

### Stripped-down, copy-pastable code snippets
```
Component.php

public ?array $model = [];

public function render()
{
    $collection = Model::all();

    return view('livewire.component', ['collection' => $collection])->layout('layouts.base');
}
```

```
component.blade.php

@php
var_dump($model);
@endphp

@foreach($collection as $item)
<div>
    <input type="checkbox" name="model-{{ $item->id }}" value="{{ $item->id }}" id="model-{{ $item->id }}" wire:model="model.{{ $item->id }}" wire:key="{{ $item->id }}">{{ $item->id }}
</div>
@endforeach
```

**Context**
- Livewire version: [e.g. 2.2.3]
v2.3.2

- Laravel version: [e.g. 8.3.1]
Laravel Framework 8.16.0

- Alpine version: [e.g. 2.3.0]
N/A

- Browser: [e.g. Chrome, Safari]
Chrome

**Comment by joshhanley** [comment]
@shortbrownman can you upgrade Livewire to 2.3.5 and test it again, as there was some bugs fixed to do with arrays?

But using `wire:model="model.{{ $item->id }}"` won't work anyway, the key needs to be the collection index.

So try changing your foreach loop to `@foreach($collection as $index => $key)`
And set your model to `wire:model="model.{{ $index }}"`

Hope this helps!

**Comment by shortbrownman** [comment]
2.3.5 does indeed fix the array issue. `$model` is a separate array that isn't associated with `$item` or `$collection`. It's just an array that's keeping track of the `$id`s from the `$collection` array.

**Comment by joshhanley** [comment]
@shortbrownman cool! Ah ok fair enough. Is everything working that you were trying now?

**Comment by shortbrownman** [comment]
Yes, it's working as expected now. Thanks!

**Comment by joshhanley** [comment]
@shortbrownman Great 🙂 No worries! Can you please close this issue?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
