### ISSUE TITLE
FileUploads.js : _this is undefined

### ISSUE THREAD

**Issue by gaetan-hexadog** [livewire/livewire#2208]
### Description
Every time I use a standard file input to handle uploads I get the following JavaScript issue:
```javascript
Uncaught TypeError: _this is undefined
    clearFileInputValue FileUploads.js:37
    FileUploads FileUploads.js:38
    value MessageBus.js:17
    value MessageBus.js:16
    call HookManager.js:38
    callHook Store.js:120
    attachModelListener node_initializer.js:63
    initialize node_initializer.js:24
    initialize node_initializer.js:15
    value index.js:71
    value index.js:507
    walk walk.js:5
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    walk walk.js:10
    value index.js:493
    value index.js:69
    Component index.js:49
    value index.js:83
    value index.js:82
    <anonymous> edit:1593
    EventListener.handleEvent* edit:1592
FileUploads.js:37:41
```

The issue is not raised when using filepond.

### Exact steps to reproduce
Add a file input in the component view (withUploadFiles trait is added to the component):
```
<input type="file" wire:model="uploads" />
```

Just click on the file input "browse" button and look at the browser console.

**Context**
- Livewire version: 2.32
- Laravel version: 8.13
- Alpine version: [e.g. 2.3.0]
- Browser: Firefox mac 83.0

**Comment by joshhanley** [comment]
@gaetan-hexadog can you upgrade to 2.3.5 and see if your issue is still happen? There was some bugs fixed in the recent version to do with file uploads.

Hope this helps!

**Comment by gaetan-hexadog** [comment]
Upgrading to 2.3.5 fixed it :-) Thanks a lot.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
