### ISSUE TITLE
Patreon link?

### ISSUE THREAD

**Issue by tillkruss** [livewire/livewire#221]
Are they any business/enterprise support plans?

**Comment by faustbrian** [comment]
@calebporzio any update on ways of supporting the development?

**Comment by calebporzio** [comment]
Hey @faustbrian, thanks for asking. I've been trying to get GitHub Sponsors set up, but having trouble with one of the steps:

![image](https://user-images.githubusercontent.com/3670578/70665635-f908b600-1c3a-11ea-8abf-d878b39faee4.png)

(It's stuck on that pending step (I've added the extra details a bunch of times already))

Don't really know where to go from here. I really want to use GH sponsors and not patreon or anything. Maybe I'll see if there's some kind of support to reach out to.

**Comment by calebporzio** [comment]
Ok, I tried again, let's see...
![image](https://user-images.githubusercontent.com/3670578/70665859-792f1b80-1c3b-11ea-95de-a67f5dcca141.png)

**Comment by calebporzio** [comment]
Ok, @faustbrian, so I got a GitHub sponsors page set up: https://github.com/sponsors/calebporzio

Should be live and all set. Feedback on tiers and rewards is welcomed!

**Comment by calebporzio** [comment]
Thanks for the support!
