### ISSUE TITLE
Pagination + div + wire:key (in any combination) won't work

### ISSUE THREAD

**Issue by slava-vishnyakov** [livewire/livewire#2214]
### Description

I know that I'm supposed to use `wire:key` inside the foreach, but in my case it just doesn't seem to work in any combination. The problem is that I need a div wrapping an inner component, like this:

```
@foreach($this->users as $user)
    <div wire:key="$user->id">
        <livewire:user-one :user="$user">
    </div>
@endforeach
```

I tried this:
```
@foreach($this->users as $user)
    <div wire:key="$user->id">
        <livewire:user-one :user="$user" :key="$user->id">
    </div>
@endforeach
```

and this (magic suggested in other issue):

```
@foreach($this->users as $user)
    <div wire:key="time().$user->id">
        <livewire:user-one :user="$user" :key="$user->id">
    </div>
@endforeach
```

and this:

```
@foreach($this->users as $user)
    <div>
        <livewire:user-one :user="$user" :key="$user->id">
    </div>
@endforeach
```

I always seems to get `Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null` and then everything breaks.

### Exact steps to reproduce

```
php artisan make:livewire UserList --inline
php artisan make:livewire UserOne --inline
```

UserList:
```
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Support\Str;
use Livewire\Component;

class UserList extends Component
{
    public function render()
    {
        $this->users = User::orderByDesc('created_at')->paginate(1000);
        return <<<'blade'
            <div>
                <button wire:click="more">create more</button>
                @foreach($this->users as $user)
                    <div wire:key="$user->id">
                        <livewire:user-one :user="$user" :key="$user->id">
                    </div>
                @endforeach
            </div>
        blade;
    }

    public function more()
    {
        User::create([
            'name' => Str::random(10),
            'email' => Str::random(10) . '@gmail.com',
            'password' => Str::random(10),
        ]);

    }
}
```

UserOne:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class UserOne extends Component
{
    public $user;

    public function render()
    {
        return <<<'blade'
            <div>
                userid: {{ $this->user->id }}
            </div>
        blade;
    }
}
```

then paste `@livewire('user-list')` somewhere visible (home.blade.php?) and click `create more` a few times.

However, this same code WILL work, if you set `paginate()` to a small number such that a second page appears. Then it'll work. So it seems it only fails when a new div is created, not when the number of them doesn't change.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.18.1
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@slava-vishnyakov try changing to the below, move the button outside of the div that wraps the foreach, so the only thing inside that div is data from the foreach.

Then with your keys, you need to make them unique, I suggest adding some context to each of the keys
Also keep in mind, when you use wire:key you need to use the blade echo syntax to get a value `{{}}`, where as when you use `:key` on a component that is a bound property so anything inside of it gets executed as php, so you don't need the echo syntax.

```blade
<button wire:click="more">create more</button>
<div>

@foreach($this->users as $user)
    <div wire:key="UserWrapper{{ $user->id }}">
        <livewire:user-one :user="$user" :key="'UserOne' . $user->id">
    </div>
@endforeach
</div>
```

If that doesn't get it working, can you make a https://laravelplayground.com with your issue?

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Heqma** [comment]
I have same problem, pagination isn't work

```
use Livewire\WithPagination;
 
class ShowPosts extends Component
{
    use WithPagination;
 
    public function render()
    {
        return view('livewire.show-posts', [
            'posts' => Post::paginate(10),
        ]);
    }
}
```

```
<div>
    @foreach ($posts as $post)
        ...
    @endforeach
 
    {{ $posts->links() }}
</div>
```

There is any response from buttons in pagination

**Comment by robogito** [comment]
We need a really **unique** ID, for me it works with
`wire: key = "{{ rand() . $entity->id }}"`
