### ISSUE TITLE
[1.3.x] Prefer jpg instead of jpeg in $supportedPreviewTypes

### ISSUE THREAD

**Issue by snake03** [livewire/livewire#2220]
### Description

Since simfony/mime changed the result of guessMimeTypes for jpg, the method temporaryUrl() doesn't work anymore with uploaded jpg files. 

See simfony/mime commit: https://github.com/symfony/mime/commit/aa1d922a7c32aedc10f6647ded250535ee3c6346#diff-4c364e5d2541a4bac059585732656923bc4d26cab31241b4aef092f7d584cfbb

Changing "jpeg" in "jpg" (or adding it, that's better) in $supportedPreviewTypes in TemporaryUploadedFile.php should be enough to fix.

I can do a PR if can help.

**Context**
- Livewire version: [1.3.5]

**Comment by snake03** [comment]
"Solved" pulling in composer "1.x-dev" instead of a tagged version, because i've seen that there's a config variable in the last commit of branch 1.x (https://github.com/livewire/livewire/commit/adb5a1210fb6802cd276a9e74e7e49b6176739b5).

I don't know if in the future this will be tagged as a minor version patch.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
