### ISSUE TITLE
Accessing Component Data Outside of Livewire with Alpine .find() Not Working in v2

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#2228]
https://laravelplayground.com/#/snippets/858a44c4-89cf-4ece-9efb-9c988b0c8092

I am using Alpine to access data from outside of a Livewire component with `.find()`.
It is getting the data properly and updating the data on the browser event. You can see this in the console because it is outputting the name. The issue is that the `x-text` is not updating with the data even though it is being updated in Alpine. 
(You have to open the iframe in it's own tab to see the console.)

1. When it's only Alpine, without the `.find()` it updates the `x-text` fine.
2. When you click the 'Update' button it updates the Livewire data but not the `x-text` (I don't think this should be happening)
3. When you type in the Input it updates the Livewire data but not the `x-text`
4. If you click the 'Update' button then click the 'Alpine Only' button **both** the `x-text`s will update.

It seems like the "magic" is working backwards.

**Expected Behavior:**
When the event is fired and the `quiz` object is updated by the `.find()`, the `x-text` should update with the data.

This issue was previously working in v1.3.1, now this code is no longer working:
```js
x-data="{ quiz: window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).data }"
x-on:next-step.document="quiz = window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).data"
```

**Comment by austenc** [comment]
@jjjrmy Is there some reason you're not wrapping all of this in an outer component? That way you could use `$wire` and it'd be much easier.

**Comment by jjjrmy** [comment]
> Is there some reason you're not wrapping all of this in an outer component? That way you could use `$wire` and it'd be much easier.
@austenc

I'm already using multiple levels of child components with this quiz component, why add another one.

**Comment by jjjrmy** [comment]
> In your event listener, you can then update the property you need. I would also suggest passing the properties in the dispatched event rather than reading them from the livewire internals because, as you noticed, they might change at any time.
@SimoTod 

I ended up going with this solution, passing the data back with the event.

I'm going to leave this issue open here because even though my original solution is not officially supported, I think something is not functioning right in my example. And maybe there is another solution for accessing component data from outside.

**Comment by joshhanley** [comment]
@jjjrmy I had a bit of a dig around and the reason `.data` is no longer accessible is because the data property is on the base component, but find returns `component.$wire`.

You can still access it by `window.livewire.components.componentsById['<putcomponentidhere>'].data` but I don't know if that is recommended.

Your playground example probably won't update as you don't have any watchers setup to monitor if any of the livewire data has updated. I'd recommend binding name to an alpine property `name`, and setup a watcher, that monitors the livewire `name` property and updates the alpine `name` property.

Hope this helps!

**Comment by jjjrmy** [comment]
> You can still access it by `window.livewire.components.componentsById['<putcomponentidhere>'].data` but I don't know if that is recommended.
> 
> Your playground example probably won't update as you don't have any watchers setup to monitor if any of the livewire data has updated. I'd recommend binding name to an alpine property `name`, and setup a watcher, that monitors the livewire `name` property and updates the alpine `name` property.
@joshhanley 


This is the error I get when I use your suggestion:
```js
x-data="{ quiz: window.livewire.components.componentsById[document.getElementById('Quiz').getAttribute('wire:id')].data }"
x-on:update-event.document="quiz = window.livewire.components.componentsById[document.getElementById('Quiz').getAttribute('wire:id')].data;"
```
```
Livewire encountered corrupt data when trying to hydrate the [hello-world] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

**Comment by joshhanley** [comment]
@jjjrmy yeah I didn't think it would be recommended 😆 I don't think binding to the base data is a good idea anyway.

I would be creating an alpine property `name` and binding to it using
```js
name: window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).name
```

And then setup a alpine watcher in your init function which watches livewire `name`, something like:
```js
$watch(window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).name, value => name = value)
```

Note: I have just put this down off the top of my head, I don't know if it will run, you may need to get the syntax right.

**Comment by austenc** [comment]
Closing as this doesn't appear to be a Livewire bug and several good solutions have been proposed. 

Would not recommend reading data from Livewire internals for this sort of thing, using events seems like a great solution @jjjrmy. Regardless, thanks for bringing up the discussion.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
