### ISSUE TITLE
Getting error "Uncaught TypeError: Cannot read property 'fingerprint' of undefined" along with turbolinks.

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2231]
### Description
I am getting the below error when I am using turbolinks along with the livewire turbolinks plugin.

> Uncaught TypeError: Cannot read property 'fingerprint' of undefined
    at livewire-turbolinks.js:24
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (livewire-turbolinks.js:21)
    at Object../node_modules/turbolinks/dist/turbolinks.js.e.dispatch (app.js:21191)
    at r.notifyApplicationBeforeCachingSnapshot (app.js:21192)
    at r.cacheSnapshot (app.js:21192)
    at r.cacheSnapshot (app.js:21191)
    at r.<anonymous> (app.js:21191)
    at app.js:21191

### Exact steps to reproduce
This is happening when I am clicking multiple times on the links and routes as shown in the gif below.

![Livewire - Turbolink Error Loop](https://user-images.githubusercontent.com/65024122/102410295-5ede0980-4016-11eb-8d08-b2ebf92712f2.gif)

### Stripped-down, copy-pastable code snippets
- layouts/app.blade.php
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    @livewireStyles

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script>

</head>

<body class="font-sans antialiased">
    <div class="min-h-screen bg-gray-100">
        @livewire('navigation-dropdown')

        <!-- Page Heading -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                {{ $header }}
            </div>
        </header>

        <!-- Page Content -->
        <main>
            {{ $slot }}
        </main>
    </div>

    <x-notification />

    @stack('modals')

    @livewireScripts
    <script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js" data-turbolinks-eval="false"></script>

</body>

</html>
```

- js/app.js
```
require('./bootstrap');

require('alpinejs');

var Turbolinks = require("turbolinks")
Turbolinks.start()
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.19.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by christophrumpel** [comment]
It seems to be an issue with Livewire and Livewire Turbolinks. I have a similar error and could fix it by downgrading Livewire to 2.3.1.

**Comment by toxifiedmatrix** [comment]
@christophrumpel This means there is a bug with livewire when used along with turbolinks. They should put up a discussion on here to fix it.

**Comment by toxifiedmatrix** [comment]
Hey there, is any one having the same issue? Please help me with this, as its a very uncommon error.

**Comment by christophrumpel** [comment]
From what I read the problem was fixed, you just have to publish assets again. Worked for me.

`php artisan livewire:publish --assets`

**Comment by toxifiedmatrix** [comment]
@christophrumpel Ohh okay, thanks for this, it fixed it., but can I ask what does it actually do? What's the difference between using livewire out of the box and using livewire along with published assets? Thanks already! 😃

**Comment by christophrumpel** [comment]
If you publish the assets you have more control over the assets since they now live in your app instead of the vendor directory. Most of the time you do not need it in my opinion. But if you have published them once, you need to that regularly to receive updates on the script. (some notes are here https://laravel-livewire.com/docs/2.x/installation)

**Comment by toxifiedmatrix** [comment]
@christophrumpel Okay, I see. Thanks alot mate for your valuable time.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
