### ISSUE TITLE
Livewire styles directive doesn't accept nonce parameter

### ISSUE THREAD

**Issue by RomaDomor** [livewire/livewire#2232]
### Current behavior
Livewire allows specify nonce field for scripts, but not for styles.

### Expected behavior
Ability to specify nonce field for Livewire styles

**Comment by joshhanley** [comment]
@RomaDomor see this closed PR #1364. Have a look at Caleb's comments as to why it was closed. If you have any other ideas as to why it's needed, please share 🙂

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
