### ISSUE TITLE
Unexpected livewire output displayed, when component starts with HTML comments

### ISSUE THREAD

**Issue by Navusas** [livewire/livewire#2240]
### Description
When `<component-name>.blade.php` starts with HTML comment (in example: `<!--Summary-->` it displays an unexpected output to the screen. It does not look like an error and the rest of the component/view is still displayed correctly, however, it does not disappear until comment is manually removed. 

### Exact steps to reproduce
1. Create Livewire component (Model and View?Blade component)
2. In the view component (i.e. `<name>.blade.php` add `<!-- Any Comment Here-->` and save (the rest of the content can stay, or you can add more)
3. Refresh the page

_Note: I am using PhpStorm Laravel-Idea plugin to automatically create livewire components_
### Stripped-down, copy-pastable code snippets
**Unformatted Output**
```
< wire:id="HmYAuDpDEGg9Ps2sAJTv" wire:initial-data="{"fingerprint":{"id":"HmYAuDpDEGg9Ps2sAJTv","name":"timesheet-summary","locale":"en"},"effects":{"listeners":[]},"serverMemo":{"children":[],"errors":[],"htmlHash":"f647b628","data":[],"dataMeta":[],"checksum":"8044bccffcc8ef74f4a7c267eb1bf45d50f14ee7347ab6f368dcc05176904496"}}"!-- Timesheet summary-->
```

**Formatted Code:**
```
<wire:id="HmYAuDpDEGg9Ps2sAJTv"
    wire:initial-data="{
        "fingerprint":{
        "id":"HmYAuDpDEGg9Ps2sAJTv",
        "name":"timesheet-summary",
        "locale":"en"},
    "effects":{
        "listeners":[]
    },
    "serverMemo": {
        "children":[],
        "errors":[],
        "htmlHash":"f647b628",
        "data":[],
        "dataMeta":[],
        "checksum":"8044bccffcc8ef74f4a7c267eb1bf45d50f14ee7347ab6f368dcc05176904496"
    }
}"!-- Timesheet summary--> 
```
**Context**
![livewire_error](https://user-images.githubusercontent.com/32360417/102665212-54d61b00-417c-11eb-8869-c9f0fd2bbb72.png)
_Note: the "Week's Summary" is my components content, not the unexpected output_
- Livewire version: 2.0
- Laravel version: 8.12
- Laravel Jetstream version: 1.6
- Alpine version: 7.3
- Browser: Mozilla Firefox

**Comment by joshhanley** [comment]
@Navusas that's actually expected as you should only have one root element. Html comments are actually classified as an element, hence why Livewire is injecting it's data on it.

I would recommend removing that and using blade comments instead `{{-- comment --}}`.

Hope this helps!

**Comment by Navusas** [comment]
Oh, apologies for that.

Thanks for letting me know!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
No worries!
