### ISSUE TITLE
Bootstrap DataTable not working with Livewire action

### ISSUE THREAD

**Issue by chamkhangwey** [livewire/livewire#2241]
I have one part in my project which is using bootstrap data table to display receipt status. In the table, I want to enable user to click on the red cross to verify the receipt.

The table is initially working properly as show in picture 1. But when I clicked on the red cross and trigger the livewire action, it become a normal plain table after livewire refresh (picture 2).

I wonder if I missed out some settings that need to be there in order for bootstrap data table to work? Or is it a bug which caused this issue?

Simplified blade.php:
```
<form action="{{ route(Constant::RECEIPT_ROUTE_STORE) }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mt-4">
                <table id="receipt_table" class="{{ Constant::BOOTSTRAP_DATA_TABLE_STYLE }}">
                    <thead>
                        <tr class="border bg-gray-200">
                            ...
                            <th class="p-2 border">Receipt Uploaded?</th>
                            <th class="p-2 border">Verified?</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($purchases as $purchase)
                            <tr class="border text-center">
                                    @if (Auth::user()->has_permission(Constant::RECEIPT_ROUTE_EDIT))
                                        @if (!is_null($purchase->receipt))
                                            @if ($purchase->receipt->is_verified)
                                                <td class="p-2 border"><span class="fas fa-check-circle text-green-400"></span></td>
                                            @else
                                                <td wire:click="toggle_verification({{ $purchase->receipt->id }})" class="p-2 border cursor-pointer"><span class="fas fa-times-circle text-red-400"></span></td>
                                            @endif
                                        @else
                                            <td class="p-2 border"><span class="fas fa-times-circle text-red-400"></span></td>
                                        @endif
                                    @endif
                            </tr>
                        @endforeach
                    </tbody>
                </table>
              </div>
        </form>
```

Liviwire class:
```
class LivewireReceipt extends Component
{
    public $purchase_id = 0;
    public function render()
    {
        return view(Constant::LIVEWIRE_RECEIPT_BLADE);
    }
    public function mount($purchase_id = 0)
    {
        $this->purchase_id = $purchase_id;
    }
    public function toggle_verification($id)
    {
        Receipt::toggle_verification($id);
    }
}
```

Receipt class:
```
class Receipt extends Model
{
    public $timestamps = true;
    use HasFactory;

    protected $fillable = [
        'name',
        'url',
        'user_id',
        'purchase_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function purchase()
    {
        return $this->belongsTo(Purchase::class);
    }

    public static function toggle_verification($id)
    {
        $receipt = Receipt::where('id', $id)->get()->first();
        if(!is_null($receipt))
        {
            $receipt->is_verified = !$receipt->is_verified;
            $receipt->update();
        }
    }
}
```

Picture 1 (before action):
![截圖 2020-12-19 下午4 28 58](https://user-images.githubusercontent.com/43119724/102685137-40942b80-4219-11eb-96e2-8b963f2a65b1.png)

Picture 2 (after action):
![截圖 2020-12-19 下午4 29 28](https://user-images.githubusercontent.com/43119724/102685146-4d188400-4219-11eb-9085-4567573201e9.png)

- Livewire version: [2.0]
- Laravel version: [8.0]
- Browser: [Chrome]

**Comment by ItsMalikJones** [comment]
I'm assuming you have another library that is modifying the DOM, so you'll need to explicitly tell Livewire to ignore changes to a subset of your HTML using `wire:ignore`.

More information on `wire:ignore`:
[Livewire Docs: AlpineJS](https://laravel-livewire.com/docs/2.x/alpine-js#creating-a-datepicker)  - **Scroll down to 'Ignoring DOM-changes' section**
[LIvewire Docs: Reference](https://laravel-livewire.com/docs/2.x/reference)

**Comment by chamkhangwey** [comment]
@ItsMalikJones Thanks for the feedback. I am not quite understand on wire:ignore and wire:key mean after reading the documentation. Where should I add these directives? In <table> tag?

**Comment by GertjanRoke** [comment]
> @ItsMalikJones Thanks for the feedback. I am not quite understand on wire:ignore and wire:key mean after reading the documentation. Where should I add these directives? In <table> tag?

wire:ignore should be placed on the tag that contains html that should not be changed by Livewire. Like this:
`<div wire:ignore>...</div>`

And wire:key is needed for a foreach loop so Livewire can use that to know which element should be added or removed. Make sure this is unique for each element your rendering in foreah.
Like this:
```blade
<ul>
@foreach($items as $item)
<li wire:key="{{ $item->id }}">...</li>
@endforeach
</ul>
```

**Comment by chamkhangwey** [comment]
@GertjanRoke Thanks for the clarification on wire:ignore. I have tried it in my code, it is working.

But for wire:key, i couldn't find the use/purpose of this feature. What should i do with it after i have assigned a key to each loop item? I think the Livewire documentation should provide more example, just my thought. :)

**Comment by GertjanRoke** [comment]
@chamkhangwey well the wire:key is not for you but for Livewire to know which dom node it should remove, add or update. So you will not get strange thinks happening to the wrong item in the foreach.

**Comment by chamkhangwey** [comment]
@GertjanRoke Thanks again for the explanation.

I have another situation that I need to repopulate the data table based on a dropdown component (<select wire:model="log_name">...</select>). But adding wire:ignore to <div> makes it not renew the content of the table. In this case, what should be the better approach?

**Comment by GertjanRoke** [comment]
Maybe the discord is a better place then, a lot of active users there and you will get a quicker answer.

Here is a link: https://discord.gg/Z862sPAU

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by MathieuB27** [comment]
@chamkhangwey Did you found a way to make it work. I'm a similar situation where I would prefer to continue working with Bootstrap-datatable and livewire

**Comment by chamkhangwey** [comment]
> @chamkhangwey Did you found a way to make it work. I'm a similar situation where I would prefer to continue working with Bootstrap-datatable and livewire

Hi, I was referred to their Discord group and the expert there told me livewire is not compatible with bootsrap datatable. So far I haven't find a way for them to work together.

Maybe you can try the Discord group stated above, maybe they are able to solve this problem now.

**Comment by zakaria-lagouader** [comment]
Hi, it's 2022 and I faced the same issue too.
Luckily I found a solution to this problem

The trick is by adding a key to the main table like this:

```html
<table ... wire:key={{ uniqid() }}>
    ...
</table>
```

and then dispatch an event in livewire:

```php
$this->dispatchBrowserEvent('table-updated');
```

finally use an event listener to re-render your table

```js
window.addEventListener('table-updated', event => {
      $('#table_id').DataTable({});
})
```

**Comment by Yogabayu** [comment]
what is "table-updated" ?

**Comment by zakaria-lagouader** [comment]
it's the name of the event that you dispatched with
`$this->dispatchBrowserEvent('table-updated');`

**Comment by Yogabayu** [comment]
i see, but in live wire 3 do not support dispatchbrowserevent anymore

**Comment by Loukili-Rachid** [comment]
in my case i was just  refresh the component and reRenderParent component also i jsut remove reRendring the parent component and now data-table + livewire working fine

 $this->emit('refreshManageComponent');
 //$this->emit('reRenderParent');

**Comment by joshhanley** [comment]
@Yogabayu is V3 it's just `$this->dispatch('table-updated');`

**Comment by sawantops** [comment]
is it necessary $table_id same as wire:key={{ uniqid() }} ?

Because I have a problem too when I render composer at that time **data table** not working

window.addEventListener('table-updated', event => {
      $('#table_id').DataTable({});
})
e
which things is better is I add the code in composer or create new js file & that file add in app.blade.php (Layout file)?
Because I already tried it but not working that's why.
