### ISSUE TITLE
Call to a member function getFilename() on array ( Livewire re-render component)

### ISSUE THREAD

**Issue by im-denny** [livewire/livewire#2244]
### Description
I have file upload (using [Livewire fileuploads][1]) functionality with rotation and sorting (using [Livewire/sortable][2]), below is more explanation over it.

[Here is my Livewire component blade code screenshot][3]

In this blade I have for loop over a variable named `$fileuploads`, this variable has two types of data in it, as its edit page, so there will be already existing images and user can upload new ones also. So `$fileuploads` variable have two types of data in it one being `Livewire\TemporaryUploadedFile` another being simple `array` (fetched with toArray() eloquent query). In the image tag's `src` attribute I have ternary based on which it'll either display image from `asset('storage/path...')` or Livewire `temporaryUrl()`

[$fileuploads variable values screenshot][4]

Uploading new images and sorting is working fine. When user sorts the images, I have `wire:sortable="changeOrder"`, and this function will simply swap the index of the values in `$fileupload` variable.But there is one edge case in which if user tries to put `Livewire\TemporaryUploadedFile` image on the first place by drag and drop(sorting) then it throws error stating [`Call to a member function getFilename() on array`][5] and component doesn't re-renders, if I try sorting it on other than first place then it works fine, while if I sort the `asset('storage/path...')` images on any places then it works fine also. 

[Here is sneak peek into UI][6]

  [1]: https://laravel-livewire.com/docs/2.x/file-uploads#preview-urls
  [2]: https://github.com/livewire/sortable
  [3]: https://i.stack.imgur.com/GV5A3.png
  [4]: https://i.stack.imgur.com/bsN7Y.png
  [5]: https://i.stack.imgur.com/bJRkN.png
  [6]: https://drive.google.com/file/d/1o_clLx0isS19rPSqGONdQQIqbgl5W0U6/view?usp=sharing
    
**Context**
- Livewire version: [2.3.5]
- Laravel version: [7.30.0]
- Alpine version: [2.7.0]
- Browser: [Chrome]

Kind Regards
Denish

**Comment by joshhanley** [comment]
@im-denny please don't open both an issue and a discussion with the same problem.
This should just be a discussion until a bug can be confirmed.

Can you please close this issue and we will investigate in discussion #2243?

Thanks!

**Comment by im-denny** [comment]
@joshhanley yes, sorry for that, I am closing this issue. 

Reference #2243

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
