### ISSUE TITLE
html comments breaks blade template.

### ISSUE THREAD

**Issue by ildyria** [livewire/livewire#2262]
### Description

Starting a livewire view with a html comment breaks the view.
![2020-12-24_1920x1080_17:26:15](https://user-images.githubusercontent.com/627094/103111421-1abdbb00-464d-11eb-811d-282f8747d8d4.png)

### Exact steps to reproduce

- create a livewire component with a view **which starts with an html comment.**

### Stripped-down, copy-pastable code snippets

This will not be a MWE but this should give good enough intuition of what is going on.

`App\Http\Livewire\Albums.php`
```php
class Albums extends Component
{
	public $albums;
	public $smartalbums;
	public $shared_albums;

	public function mount() {
	}

	public function render()
	{
		return view('livewire.albums');
	}
}
```

`livewire.albums`:
```blade
<!-- content -->
<div class="content">
@isset($smartalbums)
<div class='divider'><h1>{{ Lang::get('SMART_ALBUMS') }}</h1></div>
@foreach ($smartalbums as $data)
	@include('livewire.parts.album')
@endforeach
@endisset

@if(count($albums) > 0)
<div class='divider'><h1>{{ Lang::get('ALBUMS') }}</h1></div>
@foreach ($albums as $data)
	@include('livewire.parts.album')
@endforeach
@endif

@if(count($shared_albums) > 0)
<div class='divider'><h1>{{ Lang::get('SHARED_ALBUMS') }}</h1></div>
@foreach ($shared_albums as $data)
	@include('livewire.parts.album')
@endforeach
@endif
</div>
```

`layout.app`
```blade
<!DOCTYPE HTML>
<html>
<head>@livewireStyles
</head>
<body>
	{{ $slot }}
@livewireScripts
</body>
</html>
```

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: unknown
- Browser: Chrome

**Comment by nuernbergerA** [comment]
What happens if you put the comment inside the div. I assume this is because you don't have only one root element.

**Comment by ildyria** [comment]
> you don't have only one root element.

I do, don't I: `<div class="content">`

Anyway, comment inside the div is fine.

**Comment by nuernbergerA** [comment]
1st element: `<!-- content -->`
2nd element : `<div class="content">...</div>`

**Comment by ildyria** [comment]
This is working fine:
```html
<div class="content">
<!-- content -->
```

**Comment by joshhanley** [comment]
I'm not sure if this is a bug, the reason is, a html comment is actually classified as a DOM element, as such, putting a comment then a div is technically considered as having two root elements and Livewire is initialising on the first (the comment), hence why you are getting that output.

I'd suggest either only having the div as the only root element, or use blade comments if you need it before the div 
```blade
{{-- Blade comment--}}
<div>
    ...
</div>
```

**Comment by austenc** [comment]
Yeah, an HTML comment is technically a DOM node, so Livewire gets tripped up and thinks there's more than one root element as @nuernbergerA mentioned. 

Thanks, Josh and Adrian!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
