### ISSUE TITLE
Livewire component duplicated when two sibling component extend same blade file.

### ISSUE THREAD

**Issue by 1sps** [livewire/livewire#2263]
### Description

When two livewire components extend same blade file, the content of livewire component is duplicated. Both of them have same content.

### Exact steps to reproduce

1. Create a blade file with @yield directives.
2. Create two livewire component.
3. Make both livewire component use @extends directive and extend the same blade file.
4. Use both livewire component as sibling component inside parent component.
5. View the result in firefox.

### Stripped-down, copy-pastable code snippets

File: resources/views/card.blade.php

```
<div>
  <div>@yield('title')</div>
  <div>@yield('content')</div>
</div>
```
File: resources/views/livewire/foo.blade.php

```
@extends('card')

@section('title')
  foo
@endsection

@section('content')
  A B C D
@endsection
```

File: resources/views/livewire/bar.blade.php

```
@extends('card')

@section('title')
  bar
@endsection

@section('content')
  1 2 3 4
@endsection
```

File: resources/views/livewire/parent.blade.php

```
<div>
  @livewire('foo')
  @livewire('bar')
</div>
```

**Context**
- Livewire version: 2.x
- Laravel version: 7.x
- Browser: Firefox

**Comment by joshhanley** [comment]
@1sps can you provide any screenshots of it happening?

**Comment by 1sps** [comment]
How do I attach screenshot here? I see no options. Could you please help.

**Comment by joshhanley** [comment]
You can just copy and paste images in and they should show up, or drag and drop, or if you click on this bar at the bottom it should open up a file upload window 🙂 
![image](https://user-images.githubusercontent.com/882837/103147818-df3a0280-47ac-11eb-8305-f7b481d91479.png)

**Comment by 1sps** [comment]
Ok thanks. Here is the screenshot.

![livewire-duplicate](https://user-images.githubusercontent.com/11844170/103151090-02f84b00-47a3-11eb-8ca0-05dd15074f54.png)

**Comment by 1sps** [comment]
Has anyone looked into it?

**Comment by joshhanley** [comment]
@1sps I believe the reason is extends shares state between php files but you don't want that to happen with Livewire.

I'd recommend using components for this https://laravel.com/docs/8.x/blade#components

Create your card in resources/views/components/card.blade.php

```blade
<div class="card">
    <div>{{ $title }}</div>
    <div>{{ $slot }}</div>
</div>
```

And then change foo to use it resources/views/livewire/foo.blade.php
```blade
<x-card>
    <x-slot name="title">
        foo
    </x-slot>

    A B C D
</x-card>
```

And in resources/views/livewire/bar.blade.php
```blade
<x-card>
    <x-slot name="title">
        bar
    </x-slot>

    1 2 3 4
</x-card>
```

Comes up like this 
![image](https://user-images.githubusercontent.com/882837/103245823-7d001e00-49b5-11eb-824c-93b00bfa0769.png)

Hope this helps!

**Comment by austenc** [comment]
@joshhanley is right. 

I don't think this is a Livewire problem. Rather, it's how template inheritance works in Blade. Using components with slots would be the recommended way to solve this. Feel free to reopen if you find a Livewire-specific bug that exists. Thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
