### ISSUE TITLE
livewire double prefixes the temporary_file_upload path

### ISSUE THREAD

**Issue by marvinosswald** [livewire/livewire#2265]
### Description

It appears as livewire prefixes the directory twice, once for the real subdirectory and once the full absolute path.

```
File not found at path: livewire-tmp/Users/marvinosswald/dev/livewire-test/storage/app/livewire-tmp/oDGBguwvuXHPwB5kkcjuxltXBLx7w3-metaU2NyZWVuc2hvdCAyMDIwLTEyLTIzIGF0IDE1LjEwLjMzLnBuZw==-.png
```

The file exists just fine without the `livewire-tmp` in the beginning of the path.

### Exact steps to reproduce
- setup new laravel project with jetstream
- get the path from one `TemporaryUploadedFile` instance
- instance new `TemporaryUploadedFile` with path and disk `local`
- call store on it

### Stripped-down, copy-pastable code snippets

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\TemporaryUploadedFile;
use Livewire\WithFileUploads;

class FumItem extends Component
{
    use WithFileUploads;

    public string $path;
    public $file;

    public function mount()
    {
        $this->file = new TemporaryUploadedFile($this->path, 'local');
        $this->file->store('/project/1');
    }

    public function render(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Contracts\Foundation\Application
    {
        return <<<'blade'
            <div>
                <div wire:loading wire:target="file">Loading</div>
            </div>
        blade;
    }
}
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.20.1
- Alpine version: 2.8.0
- Browser: Brave (Chromium)

**Comment by marvinosswald** [comment]
my bad - the reason the double prefix happend was because i used the path from the original `TemporaryUploadedFile` and created a new instance from this path, which thereby prefixed the path again

**Comment by marvinosswald** [comment]
my bad - the reason the double prefix happend was because i used the path from the original `TemporaryUploadedFile` and created a new instance from this path, which thereby prefixed the path again

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
