### ISSUE TITLE
Livewire 404: GET http://localhost/livewire/livewire.js file not found

### ISSUE THREAD

**Issue by omanbuluatie** [livewire/livewire#2266]
### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [2.x]
- Laravel version: [8.1.2]
- Browser: [firefox]

I just installed laravel 8 with a fresh installation and livewire, but when I run the application,and display web developer from the browser it shows that there is an error 404 for the livewire.js is not found.
i did run the php artisan livewire:publish and php artisan vendor:publish --force --tag=livewire:assets

http://localhost:99/vendor/livewire/livewire.js?id=eb510e851dceb24afd36

when i search for the files, i found that the file is in the ..\vendor\livewire\livewire\dist\livewire.js

I'm following official docs and screencasts, I tried to follow step-by-step all the instructions but it didin't work either. Maybe I did something wrong during installation, but I don't think so, because I just hit:

    composer require livewire/livewire
can you help me?

[https://imgur.com/FrU5AKN](https://imgur.com/FrU5AKN)
[https://imgur.com/ug5srvb](https://imgur.com/ug5srvb)

**Comment by code-runner-2017** [comment]
I might be wrong, but I guess it's because the root of your Laravel app is /public, whereas it is supposed to be / (root) by default.
If this is your dev env setup, you can force a non-default path defining:

`LIVEWIRE_ASSET_URL=/public`

in your .env, and make sure that you have:

`'asset_url'  => env('LIVEWIRE_ASSET_URL'),`

in your `config/livewire.php` file.

Pls let me know if this solves the issue.

**Comment by dejanmeznarc** [comment]
I had same problem when trying to host it using PHPstorm's build-in web server.  Try `php artisan livewire:publish`

**Comment by austenc** [comment]
@omanbuluatie Livewire expects the javascript assets to be available to the web root, but as @code-runner-2017 mentioned it looks like you don't have the usual web root. What are you using to host your application in development? You might try the suggestions above and see if they fix it for you.

If that doesn't work, please REOPEN this and provide some more info about your setup, thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Zweaky** [comment]
REOPEN
I have applied all solutions listed above and still have this problem in development environment.

**Comment by raul-gabriel** [comment]
agregar los scrit y stilos
 @livewireStyles
@livewireScripts



//agregar parametro en el archivo .env
ASSET_URL=http://localhost/proyecto/public


//buscar el archivo livewire.php
mi_proyecto\vendor\livewire\livewire\config\livewire.php


//modificar parametro
'asset_url' => env('ASSET_URL'),


//refrescar 
php artisan livewire:publish --config
php artisan livewire:publish --assets
