### ISSUE TITLE
Data binding issue

### ISSUE THREAD

**Issue by selecteg** [livewire/livewire#2278]
### I tried to use form data binding when entering text in text field it's given me error on console and validation not working 
and it's giving me an error when entering text the input in HTML
getCsrfToken.js:7 Uncaught Error: Whoops, looks like you haven't added a "csrf-token" meta tag
    at getCsrfToken (getCsrfToken.js:7)
    at Connection.value (index.js:34)
    at sendMessage (index.js:221)
    at Component.value (index.js:231)
    at later (debounce.js:8)

**Context**
- Livewire version: [e.g. ^2.3]
- Laravel version: [e.g. ^8.12]
- Browser: [e.g. Chrome]
<img width="1435" alt="Screen Shot 2020-12-30 at 1 02 19 AM" src="https://user-images.githubusercontent.com/75253357/103319508-ccd4f880-4a3a-11eb-98d4-594dd1e4535d.png">

**Comment by joshhanley** [comment]
@selecteg can you share your blade code?

**Comment by austenc** [comment]
Seems like your HTML is missing the CSRF token. https://laravel.com/docs/8.x/csrf#csrf-x-csrf-token

Try adding this to between your `<head></head>` tags:
`<meta name="csrf-token" content="{{ csrf_token() }}">`

If the issue persists, please reopen **and provide more info on how to reproduce the error**, thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
