### ISSUE TITLE
Testing: Non-static method Facade\Ignition\Views\Engines\PhpEngine::handleViewException() should not be called statically

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2286]
I have a test that used to work, that no longer works.  This seems to have started since upgrade my Livewire/Laravel to latest versions.

Here is my test:

    public function testLivewireCreateBusiness()
    {
        $livewire = Livewire::test(\App\Http\Livewire\Business\Create::class);
        $livewire->lastResponse->assertStatus(403);
    }

**Context**
- Livewire version:  dev-master
- Laravel version: 8.20.1
- Phpunit: 9.5.0

Gives error:

```
ErrorException : Non-static method Facade\Ignition\Views\Engines\PhpEngine::handleViewException() should not be called statically
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
