### ISSUE TITLE
Firing Twice Event with korean char + TAB or ENTER

### ISSUE THREAD

**Issue by jaeheeship** [livewire/livewire#2291]
### Description
After typing some Korean char in INPUT[type=text] and Press Tab then Browser Focus Third Input not Second Input.
If typing char is English , It dosen't occur. 

I try Input Text In Korean after disabled JS , It has no problem. 

### Exact steps to reproduce
1. Prepare 3 Inputs. 
2. Type Some Korean Char in First Input
3. Press Tab
4. Then Browser Focus Third Input Box not Second Input Box. 

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version:  2.2.3
- Laravel version: 8.19
- Alpine version: not installed
- Browser: Chrome

**Comment by jaeheeship** [comment]
[I think this link is similar issue in vue.](https://github.com/vuejs/vue/issues/10277)

**Comment by jaeheeship** [comment]
Oh... I'm Sorry .

It's my mistake.

I found about Tab Event Listener in Component. 
But Chrome has a bug about  Triggering Keydown with Korean . 

I use keypress event instead of keydown event. 

Thank you.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
