### ISSUE TITLE
IE 11 Support?

### ISSUE THREAD

**Issue by jwohlfert23** [livewire/livewire#2293]
Using inline scripts in IE 11 doesn't seem to work.  

For example, this script:
```html
<script>
 document.addEventListener('livewire:load', function() {
        document.getElementById('payment-form').addEventListener('submit', function (ev) {
              ev.preventDefault();
              @this.submit(); 
        });
});
</script>
```
Produces the following error:
`Object doesn't support property or method 'submit'`

This same error occurs when trying to use `@entangle`.  It seems like any time a method is being called via an inline script on a livewire component, it produces this error.

`window.livewire.find('componentId').anyMethodHere()` => `Object doesn't support property or method 'anyMethodHere'`

I've tried pretty much anything you can think of:
- Including ES5/ES6 Polyfills
- With/Without Alpine
- Loading Alpine Before/After

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.20.1
- Alpine version: 2.8.0
- Browser: Internet Explorer 11

**Comment by jwohlfert23** [comment]
After doing some more digging, it appears this is likely due to the fact that the `$wire` property of a Livewire component is implemented using a `Proxy` which isn't supported in IE 11.

**Comment by marispro** [comment]
+1
Also some project required IE1, and for my surprise this is only thing that doesn't work

![Screenshot_1](https://user-images.githubusercontent.com/5610414/104330829-b1fc8c80-54ee-11eb-9e11-afdfd12cc51a.png)
.

**Comment by joshhanley** [comment]
@marispro yeah it's a Livewire issue, as @jwohlfert23 pointed out, $wire is a Livewire object that is a proxy and window.Livewire.find just returns the underlying $wire proxy.

@jwohlfert23 when you say you tried polyfills, how did you try it? Did you compile Livewire's javascript assets from the source or try to run a polyfill over the compiled assets?

**Comment by jwohlfert23** [comment]
I ended up finding a workaround for this without having to recompile Livewire's JS:

```js
import ProxyPolyfillBuilder from 'proxy-polyfill';

const proxyProps = [
  'entangle',
  ...otherFunctionNamesYouWantToCallInJS
];

const ProxyPolyfill = ProxyPolyfillBuilder();
window.Proxy = function (target, handler) {
  if (!Array.isArray(target)) {
    proxyProps.forEach(function (key) {
      if (!target.hasOwnProperty(key)) {
        Object.assign(target, { [key]: null });
      }
    });
  }
  return new ProxyPolyfill(target, handler);
};
```

It's not a great solution, but it works.  In my opinion, this should be included in Livewire or IE 11 support should be dropped, because using inline scripts 100% does not work in IE 11.

Here
