### ISSUE TITLE
Components clearing flash data set elsewhere (e.g. controller)

### ISSUE THREAD

**Issue by pyr0hu** [livewire/livewire#2294]
### Description

If a flash message is set in the session store from the controller, the data won't be available after rendering a LiveWire component.

### Exact steps to reproduce
Attached a playground snippet.

After opening the snippet, the view should show "Hello from component". If you comment out the rendering (`<livewire:hello-world />`), it will say "hello from session flash".

I also dumped the session data and you can see that the _flash.new still contains a key reference to the "danger" key, but the actual value is missing.

### Stripped-down, copy-pastable code snippets
https://laravelplayground.com/#/snippets/3bd10c5e-6833-409f-89ce-08bc47499e66

**Comment by pyr0hu** [comment]
I tracked down the line that causes this: https://github.com/livewire/livewire/blob/master/src/RenameMe/SupportRedirects.php#L37

but I can understand why it's there, but this way we cannot set flash messages from a different controller or anywhere else except the component.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
