### ISSUE TITLE
Getting error "Typed property must not be accessed before initialization" 

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2300]
### Description
I am type hinting model properties and trying to delete the invitation data. Here is the error which its throwing me back.

> Typed property App\Http\Livewire\Backend\UserManagement\FormComponent\InvitationManagementModal::$invitation must not be accessed before initialization

### Stripped-down, copy-pastable code snippets
- Livewire\InvitationManagementModal.php
```
<?php

namespace App\Http\Livewire\Backend\UserManagement\FormComponent;

use Livewire\Component;

use Livewire\WithPagination;
use App\Http\Livewire\Backend\DataTable\WithCachedRows;

use App\Models\Invitation;

class InvitationManagementModal extends Component
{
    use WithPagination, WithCachedRows;
    
    public $showInvitationManagementModal = false;
    public Invitation $invitation;

    protected $listeners = ['manageInvitation'];

    public function manageInvitation()
    {
        $this->showInvitationManagementModal = true;
    }

    public function deleteInvitation(Invitation $invitation)
    {
        $this->invitation->delete();
    }

    public function getInvitationRowsProperty()
    {
        return $this->cache(function () {
            $invitations = Invitation::where('registered_at', null)->paginate(5);
            return $invitations;
        });
    }

    public function render()
    {
        return view('livewire.backend.user-management.form-component.invitation-management-modal', ['invitations' => $this->invitationRows]);
    }
}
```
- livewire\invitation-management-modal.blade.php
```
<div>
    <x-modal.stacked wire:model.defer="showInvitationManagementModal" id="scroll-lock">
        <x-slot name="title">Manage Invitation</x-slot>
        <x-slot name="description">Manage all the invitations which are yet to be accepted.</x-slot>
        <x-slot name="content">
            <div class="p-8 space-y-4">
                <ul class="flex flex-col divide divide-y w-full bg-white rounded-lg shadow">
                    @forelse($invitations as $key => $invitation)
                        <li class="flex flex-row">
                            <div class="flex flex-1 items-center px-8 py-4">
                                <div class="flex-1 mr-16">
                                    <div class="text-sm dark:text-white">
                                        {{ $invitation->email }}
                                    </div>
                                </div>
                                <button wire:click="deleteInvitation" class="text-right flex justify-end">
                                    <x-icon.trash />
                                </button>
                            </div>
                        </li>
                    @empty
                    @endforelse
                </ul>
                <div>
                    {{ $invitations->links() }}
                </div>
            </div>
        </x-slot>
        <x-slot name="footer">
            <x-button.secondary wire:click.defer="$set('showInvitationManagementModal', false)">Cancel</x-button.secondary>
        </x-slot>
    </x-modal.stacked>
</div>
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.20.1
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by jeffchown** [comment]
Hi @toxifiedmatrix - in your Blade, looks like you need to pass the `$invitation` to your method, e.g.:

```
<button wire:click="deleteInvitation($invitation)" class="text-right flex justify-end">
    <x-icon.trash />
</button>
```

**Comment by toxifiedmatrix** [comment]
> Hi @toxifiedmatrix - in your Blade, looks like you need to pass the `$invitation` to your method, e.g.:
> 
> ```
> <button wire:click="deleteInvitation($invitation)" class="text-right flex justify-end">
>     <x-icon.trash />
> </button>
> ```

Hey, I already tried that, no luck, after clicking `deleteInvitation($invitation)` nothing happens, its not getting deleted. Any idea what can be the issue? I can create a repository for the same if you need to debug.

**Comment by jeffchown** [comment]
@toxifiedmatrix - when you tried that, were you checking your db to see if the invitation had been deleted?  Or just the screen?  

In your component code, you've cached the invitationRows property and in your delete() method, you don't refresh the invitationRows to re-read the db, which should then no longer include the deleted invitation.

**Comment by toxifiedmatrix** [comment]
@jeffchown I already checked the database, the entries are still there, I am unable to delete the data, its just nothing is happening, I am checking for the request in the telescope as well, but no request is been sent out for that. I tried removing the cache function as well, still its the same.

**Comment by jeffchown** [comment]
@toxifiedmatrix - Just had another look at your delete() method... looks like you are trying to delete the class property (`public Invitiation $invitiation`) instead of the passed `$invitation`.  Try changing:

```
public function deleteInvitation(Invitation $invitation)
{
    $this->invitation->delete();
}
```

to:

```
public function deleteInvitation(Invitation $invitation)
{
    $invitation->delete();
}
```

and then still calling it from your Blade like this: `deleteInvitation($invitation)`

**Comment by toxifiedmatrix** [comment]
@jeffchown Thanks alot buddy, what a silly mistake I made 😅. Its working as it should.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by jeffchown** [comment]
You're welcome @toxifiedmatrix 👍 
It's happened to all of us :)
