### ISSUE TITLE
500 error: This action is unauthorized.

### ISSUE THREAD

**Issue by AdvancedStyle** [livewire/livewire#2308]
In previous versions of Livewire authorize worked like this:

```
class MyClass extends \Livewire\Component
{
    use AuthorizesRequests;

    public function mount()
    {
        $this->authorize('some-permission');
    }
}
```

Would return a **403** code and show forbidden page.

It the current dev-master branch it instead throws an exception with "This action is unauthorized." and so is considered a 500 error.

To prevent it you'd have to do something like this:

```
class MyClass extends \Livewire\Component
{
    use AuthorizesRequests;

    public function mount()
    {
        try {
            $this->authorize('some-permission');
        }catch(Exception $e){
            abort(403);
        }
    }
}
```

This looks a mess and also prevents you through throwing 'real' exceptions (should they happen to occur).

**Context**
- Livewire version: dev-master (d2ed682)
- Laravel version: 8.20.1

## Note

It looks like this was previously addressed, but must have been removed at some point in the current repo: https://github.com/livewire/livewire/pull/843

**Comment by joshhanley** [comment]
Yep can confirm this is happening. Before with app debug on or off, both would should this
![image](https://user-images.githubusercontent.com/882837/103695021-f9b37d80-4fef-11eb-84fd-a2dc12f36db9.png)

But running on dev-master:

It's interesting, with app debug on, it shows the correct exception
![image](https://user-images.githubusercontent.com/882837/103694915-d1c41a00-4fef-11eb-973c-83dad8919a7e.png)

But with app debug off, it's throwing a 500 error
![image](https://user-images.githubusercontent.com/882837/103694951-de487280-4fef-11eb-8045-dc78242816fc.png)

**Comment by austenc** [comment]
Hey @AdvancedStyle @joshhanley does the route you're testing this with have the `auth` middleware applied by chance? Any other details that might help me to replicate this?

I haven't been able to replicate it, but hopefully I'm just missing something simple. I did see your PR @AdvancedStyle but I think that may break some of Ignition's data collection features in debug mode.

**Comment by AdvancedStyle** [comment]
Yes the routes have `['auth:sanctum', 'verified']` middleware.

However the problem also occurs without using a route at all.  Using livewire tests also triggers the Exception inside of a 403 status code.

For example here is a test (`Transaction` class has an `authorize()` that causes this to be denied):

    public function testLivewireAccountTransactionsAuthorization()
    {
        $livewire = Livewire::test(\App\Http\Livewire\Business\Transactions::class);
        $livewire->lastResponse->assertStatus(403);
    }

In Livewire v2.3.5 this test passes.  In dev-master is fails because Exception is thrown.  

With my PR https://github.com/livewire/livewire/pull/2309 the test passes.

**Comment by austenc** [comment]
Thanks again for the PR @AdvancedStyle! Closing this since it's in the new release (`2.3.6`)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
