### ISSUE TITLE
create:893 Livewire: The published Livewire assets are out of date

### ISSUE THREAD

**Issue by Neeraj1005** [livewire/livewire#2320]
### Description
A few days ago in my localhost livewire was properly working. But today I run my project and check my console the livewire is not working.
In console it show some message like this
```
create:893 Livewire: The published Livewire assets are out of date
 See: https://laravel-livewire.com/docs/installation/
```
My composer json file is updated..
- Livewire version: [2]
- Laravel version: [8]
- Alpine version: [2.3.0]
- Browser: [Chrome updated]

**Comment by Neeraj1005** [comment]
Issue Solved:
>To keep the assets up-to-date and avoid issues in future updates, we highly recommend adding the command to the post-autoload-dump scripts in your composer.json file:
```
{
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan vendor:publish --force --tag=livewire:assets --ansi"
        ]
    }
}
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by darviscommerce** [comment]
Thanks al lot :)

**Comment by joshhanley** [comment]
Generally I wouldn't publish the assets incase you have a specific need to, that way you don't need to worry about this!

But incase anyone else is trying to find it, the composer script that @Neeraj1005 is using for updating the assets can be found here https://laravel-livewire.com/docs/2.x/installation#publish-assets

**Comment by gavinhewitt** [comment]
REOPEN

**Comment by gavinhewitt** [comment]
Having the same issue. Or at least locally.

I've added the above code to composer.json, and after a `dump-autoload` the issue disappears nicely from devtools. However, after a while (this could be 15 mins) the issue returns. I'm not sure why or how this would happen since no changes are made that would make the assets outdated. The only thing I can do to fix it is `composer du` again.

- Livewire version: [2.6.3]
- Laravel version: [8 latest]
- Alpine version: [2.3.0]
- Browser: [Chrome latest]

**Comment by Flobbos** [comment]
I have experienced the same issue as described by @gavinhewitt. Publishing the assets again seems to get rid of the problem.

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open https://github.com/livewire/livewire/discussions/3769.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
