### ISSUE TITLE
Using Livewire in Blade named component

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#2322]
### Description
I am trying to use Livewire's functionality inside a named blade view component. However, as soon as I place code with `wire:click` *inside* the named blade view component, it does not trigger the Livewire method.

### Exact steps to reproduce
I have a basic `app.blade.php` file, that contains the below:
```html
<div>
@if(isset($header))
   <div class="w-full">
      {{$header}}
   </div>
@endif
</div>
```

Then I have a Livewire component `Actions/Index.php`:

```php
class Index extends Component{
    public function alert()
    {
         dd("Hey. I was called from a named blade component.");
    }
}
 ```

In my Livewire view file `actions/index.blade.php`, I am trying to call the `alert` method like so:

```html
<div>
     <x-slot name="header">
          <a wire:click="alert()">Alert!</a>
     </x-slot>
</div>
```   

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.12
- Browser: Chrome

**Comment by jeffchown** [comment]
@oliverbj Can you show the code that is calling the livewire component? E.g. where is the ` <livewire:actions.index />` statement?

**Comment by oliverbj** [comment]
@jeffchown Ah, sorry I forgot to include that.

This is a "full-page" component, and is therefore registered in my `web.php` file:

```php
Route::get('actions', \App\Http\Livewire\Actions\Index::class)->name('actions.index');
```

**Comment by jeffchown** [comment]
@oliverbj Played with it a bit and can confirm your findings.

When using:
```
<div>
     <x-slot name="header">
          <a wire:click="alert()">Alert!</a>
     </x-slot>
</div>
```
in your `actions/index.blade.php` view, the following code is generated (from Dev. Tools) in the layout: 
```
<div>
    <a wire:click="alert()">Alert!</a>
</div>
```

When using (e.g. default slot in layout):
```
<div>
    <a wire:click="alert()">Alert!</a>
</div>
```
the following code is generated:
```
<div wire:id="puklDgO5xICxXx1xnedi">
    <a wire:click="alert()">Alert!</a>
</div>
```

So, based on the above, when assigning your livewire component's output to a named slot in the layouts.app, the component is not properly initialized as is indicated by the missing wire:id in the resulting code.

I'm not sure why this is the case and will dig deeper when I have a chance.  @joshhanley, are you able to provide any insight/ideas?

**Comment by jeffchown** [comment]
@oliverbj I did a little digging and found this previous issue: https://github.com/livewire/livewire/issues/1707

Based on that info, when I changed the code in `layouts/app.blade.php` to:
```
<div>
    @yield('header')

    @yield('slot')
</div>
```

and the code in `actions/index.blade.php` to:
```
<div>
    <a wire:click="alert()">Alert!</a>
</div>
```

and the `render()` method in `Livewire/Actions/index.php` to:
```
public function render()
{
    return view('livewire.actions.index')
            ->extends('layouts.app')
            ->section('header');
}
```

then everything worked as expected.

Hope that helps.

**Comment by oliverbj** [comment]
I tried the above, but unfortunately it creates another myriad of issues for me, as I am no longer able to reference specific Blade view components (thus my main content, is not showing and neither is the header).

**Comment by jeffchown** [comment]
@oliverbj Maybe if you provide a more comprehensive description/example of your desired result/happy path, people might be able to come up with some ideas/options.

**Comment by jeffchown** [comment]
> I tried the above, but unfortunately it creates another myriad of issues for me, as I am no longer able to reference specific Blade view components (thus my main content, is not showing and neither is the header).

Also, based on your reply, it sounds like using full-page components may not be the best solution, so further information will help in understanding what you are trying to accomplish.

**Comment by joshhanley** [comment]
@oliverbj and @jeffchown the issue is when the div, that inside the header slot, is rendered, it is rendered outside of the Livewire component bounds, as it's in a totally different section in the layout. Hence why the button doesn't work.

There are a couple of ways around that, the simplest and most crude is to make a livewire component for your header that has the action button in it, that emits the action trigger to the other component, and then pass that through the slot. Also any x-slot tags can be at the root level as they aren't passed into that component anyway (which makes it all cleaner).

Please note I've typed this off the top of my head, in theory should run, but it may not 🙂

Hope this helps!

actions/index.blade.php
```blade
<x-slot name="header">
    <livewire:alert-component />
</x-slot>

<div>
    <!-- index component details here -->
</div>
```
Actions/Index.php
```php
class Index extends Component{
    protected $listeners = ['alert'];

    public function alert()
    {
         dd("Hey. I was called from the emitted alert event.");
    }

    public function render() {
        return view('actions.index.blade.php');
    }
}
```

actions/alert-component.blade.php
```blade
<a wire:click="$emit('alert')">Alert!</a>
```

Actions/AlertComponent.php
```php
class AlertComponent extends Component{
    public function render() {
        return view('actions.alert-component.blade.php');
    }
}
```

**Comment by oliverbj** [comment]
Thanks, both for your assistance! Highly appreciated. I think for my use case, the best approach will be using the `$emit` feature.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by patrickmaciel** [comment]
REOPEN

**Comment by joshhanley** [comment]
@patrickmaciel please don't reopen without giving a reason. 

This issue has been closed again as we are now using discussions to track bugs and ideas, so please open a discussion with your problem and link to this issue if required.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
