### ISSUE TITLE
File response always initiates download

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#2327]
### Description
In Laravel you can send a `download` response or a `file` response. The first one initiates a download in your browser, and the second one opens the file inside the browser, and is used for PDFs and images mostly.
But Livewire initiates the download regardless:

### Stripped-down, copy-pastable code snippets
Just paste these two into two controller methods, and two Livewire actions:
```php
// This initiates download in Laravel and Livewire
return response()->download(public_path('index.php'), 'downloaded', [
    'Content-Type' => 'application/pdf',
    'Content-Disposition' =>  'attachment; filename="downloaded"'
]);

// This opens the file in browser in Laravel but initiates download in Livewire
return response()->file(public_path('index.php'), [
    'Content-Type' => 'application/pdf',
    'Content-Disposition' =>  'inline; filename="in-browser"'
]);
```

**Context**
- Livewire version: latest
- Laravel version: latest

**Comment by satoved** [comment]
Would like to know if the solution is possible. This is probably against the LiveWire architecture. But maybe it can generate a temporary link in an new tab or something.

**Comment by calebporzio** [comment]
Yeah, possibly. I'm going to close this for now though unless someone wants to dig in and find a solution.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
