### ISSUE TITLE
Why the screen begins to flicker after installing the latest livewire?

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2328]
### Description
The screen has begun to flicker, whenever I try visiting a route, this wasn't the case before the update was released. Whenever it happens, it kinds of feels glitchy, and not at all solid.

### Exact steps to reproduce
To reproduce the above, visit the routes or reload the page by hitting enter from the URL bar.

![Livewire Flicker 2](https://user-images.githubusercontent.com/65024122/104122028-9a939700-5368-11eb-87f5-15adf7447a57.gif)

**Context**
- Livewire version: 2.3.6
- Laravel version: 8.21.0
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by GertjanRoke** [comment]
@toxifiedmatrix Did you also tried it on existing websites? Seems to be a Chrome issue to me.

**Comment by toxifiedmatrix** [comment]
Yep, its not happening if I am updating the existing laravel site. It's only happening with clean installation, with the latest version of tailwind, livewire, alpine and laravel. I am just not able to check what is causing this kind of problem. This thing is happening with edge browser as well.

**Comment by stevebauman** [comment]
Have you inspected the DOM to see what may be going on? Are there any console errors appearing?

You will likely have to take a dive into the DOM tree in the console to start debugging, as there don’t appear to be other reports of this same issue.

**Comment by toxifiedmatrix** [comment]
No console error, one thing I have noticed, its the closed state of the hamburger menu i.e. the close button then it shifts back to navigation for desktop.

![Close Button Show Hide](https://user-images.githubusercontent.com/65024122/104286826-963bbb00-54db-11eb-97da-aefd63b7aef1.gif)

**Comment by NickJorens** [comment]
I don't see how this could be a Livewire issue. It's probably Tailwind or Alpine.
Maybe the `cloak` CSS feature is working, causing the element to be hidden after Alpine is initialized?

https://github.com/alpinejs/alpine#x-cloak

**Comment by toxifiedmatrix** [comment]
@NickJorens I already tried that, but no luck, can you please create a new Laravel project to check if this is actually happening?

**Comment by stevebauman** [comment]
@toxifiedmatrix I'm not able to reproduce this at all on a brand new Laravel Jetstream instance:

https://user-images.githubusercontent.com/6421846/104381671-d199b200-54fa-11eb-916c-3779414b16d4.mov

**Comment by joshhanley** [comment]
@toxifiedmatrix looking at your screenshot you have `x-show="show && message"` with `show: true` and `message: null`, so the flash you are getting is when alpine kicks in and hides the element. It's hiding because message is null.

I would put an `x-cloak` on that div and make sure you have this in your styles somewhere 

```html
<style>
    [x-cloak] { display: none; }
</style>
```

Hope this helps!

**Comment by toxifiedmatrix** [comment]
@joshhanley @stevebauman It's the `<x-jet-banner />` in the `app.blade.php` layout. When I removed it, the flash stopped. What does this  `<x-jet-banner />` do?

```
    <body class="font-sans antialiased">
        <x-jet-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        <x-notification />

        @stack('modals')

        @livewireScripts
    </body>
```

**Comment by joshhanley** [comment]
@toxifiedmatrix looks like there was a patch for this issue https://github.com/laravel/jetstream/pull/599 and it was tagged 7 hours ago 😆

In terms of what it does, I'm guessing it's so you can display notifications or something to the user.

**Comment by toxifiedmatrix** [comment]
@joshhanley I used the `x-cloak` on `banner.blade.php`, its all back to normal. 😄

**Comment by joshhanley** [comment]
@toxifiedmatrix ok great! Glad we got it sorted 🙂

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
