### ISSUE TITLE
Unexpected behavior caused by constructor leading to "TypeError: Cannot read property '$wire' of undefined" error.

### ISSUE THREAD

**Issue by thumbtech** [livewire/livewire#2329]
### Description

Use of a constructor in my component class unexpectedly caused the "TypeError: Cannot read property '$wire' of undefined" (with use of entangle) to be raised. I went down the rabbit hole of all the undefined $wire & entangle issues when it was just the constructor that caused the issue. Maybe a "feature" I just don't understand ... ?

### Exact steps to reproduce

Easiest way to reproduce is to use https://github.com/livewire/surge demo project source, then place constructor in App\Http\Livewire\Dashboard.php component. Then click "edit" button on a row in dashboard to view error in console.

### Stripped-down, copy-pastable code snippets

Place "empty" constructor in App\Http\Livewire\Dashboard.php class:

`
    function __construct()
    {
        parent::__construct();
    }
`

**Context**
- Livewire version:  dev-master 8663232
- Laravel version: 8.21.0
- Alpine version: 2.8.0
- Browser: Chrome Edge etc.

**Comment by joshhanley** [comment]
@thumbtech you shouldn't be using the constructor, instead you should be using the mount method.

Check out this section in the docs https://laravel-livewire.com/docs/2.x/rendering-components#parameters
> In Livewire components, you use mount() instead of a class constructor __construct() like you may be used to.

Hope this helps!

**Comment by thumbtech** [comment]
Thanks Josh yes I definitely use mount as documented. I was using constructor to automagically populate $this->rules array to support model binding (grabbed goodies from the model, etc.) and it worked great EXCEPT for error noted.

The issue was that you need to handle the parameter to the Component constructor in the parent, so it needs to be:

`function __construct($id = null) { parent::__construct($id); }`

Why no error? From PHP docs:

> Unlike with other methods, PHP will not generate an E_STRICT level error message when __construct() is overridden with different parameters than the parent __construct() method has.

Back in business!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@thumbtech ah right! You can use a method called rules, to return the array of rules, instead to do that and delete the $rules property all together 🙂

```php
protected function rules() {
    return [
        'someproperty' => 'rules',
        'user.email' => 'unique:users,email,'.$user->id,
    ];
}
```

**Comment by thumbtech** [comment]
Oh nice!  Let's say you had a dynamic "rules builder" and you can be sure constructor runs it once per class (and essentially caches to rules property) ... would you be at risk banging your rules() method repeatedly in downstream code (hydration, etc.)? ... in which case constructor-to-set-property seems more efficient ... ?

**Comment by joshhanley** [comment]
@thumbtech hmm that's an interesting one. I'd still avoid the constructor if possible as it's considered bad practise to use it in Livewire, as it's not supported as part of the public api.

What you could do is use the rules method and property together. Under the hood, Livewire checks for a rules method first, and if that doesn't exist then it checks for the rules property.

You could generate rules inside your rules method and manually save them to the rules property. Then at the top of the rules method, check to see if the rules property has been populated or not, and if it has, just return that instead of recalculating.

Essentially using the rules property inside the rules method to memoize your rules.

Let me know what you think!

**Comment by thumbtech** [comment]
Yes that is a clean solution & think it should work well!

I appreciate your help!

**Comment by thumbtech** [comment]
For reference, it looks like:

```
    protected $rules;

    protected function rules()
    {
        $this->rules ??= ['model.field' => 'rule']; // your custom rules-builder here
        return $this->rules;
    }
```
