### ISSUE TITLE
Pagination causes problems on nested Livewire components | The GET method is not supported for this route. Supported methods: POST

### ISSUE THREAD

**Issue by gjsman** [livewire/livewire#2333]
### Description
If you have a root Livewire component with essentially a mode-based "tabs" element that switches between Livewire views, having pagination on any of the subviews will cause Livewire to crash with an error: "The GET method is not supported for this route. Supported methods: POST."

**This problem started occurring on an upgrade to Livewire V2 and did not occur on Livewire V1.**

### Exact steps to reproduce
Create a Livewire component (which is basically clickable tabs) with a mode variable for which tab you are on. Put a Livewire component in one of those tabs and make it import pagination. A crash will occur.

### Additional Information

GIF credit @joshhanley who managed to reproduce the bug
![recording_6](https://user-images.githubusercontent.com/29414519/104205307-d7f13680-53f3-11eb-8ca9-56b030400748.gif)

Video from me:

https://user-images.githubusercontent.com/29414519/104205603-34ecec80-53f4-11eb-9ddb-0c081df61e6a.mov

**Discord conversation and discovery:** https://discord.com/channels/698229985755791471/748070864720756788/795698890954506260

### Stripped-down, copy-pastable code snippets
Credit to @joshhanley on the Discord for helping me simplify the code to simplest form that can cause the bug.

Root Component:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Main extends Component
{
    // Admin Index Page. Not Course Index System

    public $mode = 0;

    public function render()
    {
        return view('livewire.main');
    }
}
```

Blade for the Root Component:
```
<div>
    {{-- If your happiness depends on money, you will never be happy with yourself. --}}
    <div class="flex border-b space-x-4">
        <a class="{{ $mode === 0 ? 'font-bold' : '' }}" href="#" wire:click.prevent="$set('mode', 0)">
            Home
        </a>
        <a class="{{ $mode === 1 ? 'font-bold' : '' }}" href="#" wire:click.prevent="$set('mode', 1)">
            Nested
        </a>
        <a class="{{ $mode === 99 ? 'font-bold' : '' }}" href="#" wire:click.prevent="$set('mode', 99)">
            Other
        </a>
    </div>
    <div class="tab-content">
        @if ($mode === 0)
            <div>
                Home
            </div>
        @elseif($mode === 1)
            @livewire('nested-one')
        @elseif($mode === 99)
            <div>
                Other
            </div>
        @endif
    </div>
</div>
```

Nested Component:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class NestedOne extends Component
{
    use WithPagination;
    
    public function render()
    {
        return view('livewire.nested-one');
    }
}
```
Removing the `use WithPagination` from the above code resolves the bug... but then we don't have pagination. This worked in V1 and broke in V2.

Nested Component Blade:
```
<div>
    Nested One
</div>
```

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.21.0
- Alpine version: 2.8.0
- Browser: Safari, Chrome, occurs in any browser

**Comment by dalehurley** [comment]
Hi 

I had this issue.

You need to have a unique key for each of the nested Livewires, so Livewire knows the object is the same.

e.g.  <livewire:nested-one  :key="'nested_1">

https://laravel-livewire.com/docs/2.x/nesting-components#keyed-components

**Comment by joshhanley** [comment]
@dalehurley  yeah I tried that when helping @gjsman narrow down the issue.

Was yours using pagination in a nested component? Did you manage to get it all running?

![image](https://user-images.githubusercontent.com/882837/104505625-4cb4b280-5638-11eb-9c86-24b7d8b410e3.png)

**Comment by dalehurley** [comment]
Hi 

Yes it was pagination with nested table rows, same case study.

/app/Http/Livewire/ParentDataTable.php

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ParentDataTable.php extends Component
{

    protected $listeners = [
        'refreshParentDataTable' => 'render',
    ];

    public function render()
    {
        return view('livewire.parent-data-table');
    }
}
```

/app/Http/Livewire/TableRow.php
```php

<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Users;
use Illuminate\Support\Facades\Auth;

class TableRow.php extends Component
{
    public $user;
    public $name;
    public $email;

    public function mount(Users $user)
    {
        $this->user = $user;
        $this->name = $user->name;
        $this->email = $user->email;
    }

    public function render()
    {
        return view('livewire.table-row');
    }
}
```

/resources/views/livewire/parent-data-table.blade.php
```php
<table class="table w-full table-auto ">
    <thead>
         <tr>
              <th>Name</th>
               <th>Email</th>
         </tr>
     </thead>
     <tbody>
       @foreach(App\Models\Users::get() as $user)
           <livewire:table-row : user ="$user"  :key="'user-'.$user->id">
       @endforeach
   </tbody>
</table>
```

resources/views/livewire/table-row.blade.php
```php
<tr class="">
    <td>{{ $user->name }}</td>
    <td>{{ $user->email }}</td>
</tr>
```

**Comment by joshhanley** [comment]
@dalehurley thanks for sharing! I will test that 🙂

**Comment by joshhanley** [comment]
@gjsman some suggested elsewhere if you also use the `withPagination` trait also on the parent component, it fixes this issue.

I have tested this with the code we refined and it works!

I'm going to close this, but if you test it and it doesn't work, please let me know or reopen it and we can investigate it further.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
