### ISSUE TITLE
Unable to bust cache on a component that has updated data

### ISSUE THREAD

**Issue by roni-estein** [livewire/livewire#2334]
### Description
I have a series of global components that related to user status, that work fine on page, but "ghost reappear" if you use the back button. When I say ghost re-appear, the functions that would be re-performed like submitting a form, or updating a queried object will fail if you actually attempt to submit them or refresh them. In my case, I need to pull notifications from the database, as they are stored and logged.

Here is a video demo

https://user-images.githubusercontent.com/8517475/104217679-50122900-5401-11eb-9dc9-ee6d0a05a567.mov

### Exact steps to reproduce

Stripping this down but keeping it sufficiently realistic actually turned out incredibly long, if you don't mind, I'll just make a public repository, that can be pulled in, and edit this. I'll post it shortly.

This may be similar to issue https://github.com/livewire/livewire/issues/1971

**Context**
- Livewire version: [e.g. 2.3.6]
- Laravel version: [e.g. 8.21.0]
- Alpine version: [e.g. 2.8.0]
- Browser: [e.g. Chrome, Safari]

**Comment by roni-estein** [comment]
test project created and working and simply demonstrates the above

https://github.com/roni-estein/livewire-2334

**Comment by roni-estein** [comment]
I think the behavior that would solve this issue might be to to allow an opt in method of letting a component bust the cache on a "Full Page" reload. It's an edge cases that represents a small fraction of the traffic livewire handles and if it's opt in, you would only include it in troublesome components. Perhaps a setting that could be turned on or a trait included that might help middleware detect when to bust cache.

**Comment by stevebauman** [comment]
Hi @roni-estein,

Unfortunately there isn't much we can do in terms of cache busting, because the cache control header isn't even used (to my knowledge) when loading a page from the back button. The browsers back button is a tricky beast to deal with.

The only way we could manage this is by hooking into the browsers navigation and detecting if the page has been loaded from a back/forward request.

Can you try placing this inside of your `app.js` file?

```js
require('./bootstrap');

if (window.performance && window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
    // Restart livewire on back or foward.
    Livewire.restart();
}

require('alpinejs');
```

Let me know if that works!

I'm going to do some more experimenting with this myself and see what I can come up with.

**Comment by joshhanley** [comment]
I've been experimenting with this too, and if you create a middleware like described here https://stackoverflow.com/a/60671771/14909455 

```php
<?php

class DisableRouteCache
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return $next($request)->withHeaders([
            "Pragma" => "no-cache",
            "Expires" => "Fri, 01 Jan 1990 00:00:00 GMT",
            "Cache-Control" => "no-cache, must-revalidate, no-store, max-age=0, private",
        ]);
    }
}
```

Add that middleware to your Kernel.php file as a route middleware

```php
protected $routeMiddleware = [
        ...,
        'disable-route-cache' => \App\Http\Middleware\DisableRouteCache::class,
    ];
```

Then apply that middleware to your routes that have Livewire, then it fixes the issue.

So from Roni's example app, the routes would look like:

```php
Route::middleware('disable-route-cache')->get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified', 'disable-route-cache'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
```

Not sure whether that should be made as a default to disable caching for Livewire components or not?

Can you guys experiment and see what you think?

For more insight, check here https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers

**Comment by roni-estein** [comment]
> Hi @roni-estein,
> 
> Unfortunately there isn't much we can do in terms of cache busting, because the cache control header isn't even used (to my knowledge) when loading a page from the back button. The browsers back button is a tricky beast to deal with.
> 
> The only way we could manage this is by hooking into the browsers navigation and detecting if the page has been loaded from a back/forward request.
> 
> Can you try placing this inside of your `app.js` file?
> 
> ```js
> require('./bootstrap');
> 
> if (window.performance && window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
>     // Restart livewire on back or foward.
>     Livewire.restart();
> }
> 
> require('alpinejs');
> ```
> 
> Let me know if that works!
> 
> I'm going to do some more experimenting with this myself and see what I can come up with.

Steve, This solution is a fantastic start and isolates the exact behaviour! However, Livewire.restart() doesn't change the outcome at all. I broke it out further just so I could look at what was happening

```js
require('./bootstrap');

if (window.performance){

	console.log(window.performance.navigation.type);
	console.log(window.performance.navigation.TYPE_BACK_FORWARD);
	if(window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
	    // Restart livewire on back or foward.
	    Livewire.restart();
	}
}

require('alpinejs');
```

So you have nailed the exact situation. The question is where to take it from here. @calebporzio any thoughts?

**Comment by joshhanley** [comment]
@roni-estein and I we're talking about the requirements, and disabling cache, like I suggested, could be an issue for a large site.

What would be interesting to know is, does the browser cache make any difference, or does the server handle the request anyway? If it does handle it anyway, then it wouldn't make any difference disabling the browser cache for Livewire full-page components, as the load will still be on the server regardless.

Not sure how to try and test that out, so if anyone has any ideas?

**Comment by stevebauman** [comment]
@roni-estein Ok I got it:

```js
require('./bootstrap');

document.addEventListener('livewire:load', function () {
    if (window.performance && window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
        Livewire.all().map((component) => {
            component.call('render');
        });
    }
})

require('alpinejs');
```

I tested this inside of your posted test project, and pressing the forward or back button will now iterate through all Livewire components and re-render them from the server, causing the dismissed notification to disappear. 👍 

I think this could be a cool feature to integrate into Livewire? Maybe a `wire:refresh-on-navigation` directive that would add the component inside of an array that will be iterated through and re-rendered upon a browser back/forward event?

Thoughts?

**Comment by stevebauman** [comment]
@roni-estein Oh I forgot to note, don't forget to adjust the `webpack.mix.js` file to re-version your assets (at least to test), or clear your cache after adding the above code. I was scratching my head for a bit as to why my changes weren't being reflected on front-end:

**Before**:
```js
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);

if (mix.inProduction()) {
    mix.version();
}
```

**After**:

```js
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]).version();
```

**Comment by roni-estein** [comment]
Thanks @stevebauman but no joy, I if it's working for you I feel like I'm on crazy pills! A little zoolander for the end of the day. Here is a state breakdown.

### webpack.mix
```js
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]).version();

```

### app.js
```js
require('./bootstrap');

if (window.performance){

	console.log(window.performance.navigation.type);
	console.log(window.performance.navigation.TYPE_BACK_FORWARD);
	if(window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
	    // Restart livewire on back or foward.
	    console.log('restarting...');
	    Livewire.restart();
	}
}

require('alpinejs');
```

### And a video for good measure.

https://user-images.githubusercontent.com/8517475/104543333-dd64a180-55ea-11eb-9e50-87819129b73c.mov

**Comment by roni-estein** [comment]
Josh DM'd me telling me I'm a moron and too tired. Posting here for posterity's sake. I didn't see that sneaky change.. trying it now.

**Comment by norbybaru** [comment]
> @roni-estein Ok I got it:
> 
> ```js
> require('./bootstrap');
> 
> document.addEventListener('livewire:load', function () {
>     if (window.performance && window.performance.navigation.type === window.performance.navigation.TYPE_BACK_FORWARD) {
>         Livewire.all().map((component) => {
>             component.call('render');
>         });
>     }
> })
> 
> require('alpinejs');
> ```
> 
> I tested this inside of your posted test project, and pressing the forward or back button will now iterate through all registered Livewire components on the page and re-render them from the server, causing the dismissed notification to disappear. 👍
> 
> I think this could be a cool feature to integrate into Livewire? Maybe a `wire:refresh-on-navigation` directive that would add the component inside of an array that will be iterated through and re-rendered upon a browser back/forward event?
> 
> Thoughts?

This implementation was life saving. Couldn't figure out issue for weeks.

**Comment by stevebauman** [comment]
Really glad it's working for you @norbybaru! Did it end up working for you @roni-estein?

**Comment by roni-estein** [comment]
@stevebauman It did! There is a flash, but I can live with that, perhaps hide the component for a second before showing it! But for now, this is a great start! It is a double render, but I believe it's only done in a rare set of circumstances. I'm going to close this issue for now, but if someone has a different approach or an official livewire way gets added like the wire attribute mentioned above, it can always be re-opened 

Thanks for your help.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ryanmortier** [comment]
Thanks @stevebauman your solution worked for me as well. Like @roni-estein said there is a flash but I'll live with it.

**Comment by fawzanm** [comment]
@stevebauman thanks a lot of the tip. I had issues when navigating back & forward while a form is filled. I kept getting 500 Error. This helped me fix issue.

**Comment by scottzirkel** [comment]
If you do implement this, be sure to explicitly set render functions in your components. I had taken them out (since the docs say they are optional) and got 500 errors when I went back.

**Comment by s1x** [comment]
Interestingly this didn't work for me in Firefox 86.0.1 but #2603 worked for me. 
The reason is Bfcache (back/forward cache), maybe I can safe someone some time to figure this out.

My implementation looks like the following now as I just need this for one specific component. (#2603) example will introduce it for all pages.

```php
    @push('head-scripts')
        <script>
            window.addEventListener('pageshow', function(event) {
                if (event.persisted) {
                    console.log('This page was restored from the bfcache.');
                    window.location.reload();
                } else {
                    console.log('This page was loaded normally.');
                }
            });
        </script>
    @endpush
```

A good overview can also be found here by https://web.dev/bfcache/
