### ISSUE TITLE
Livewire does not work in production: Uncaught ReferenceError: Livewire is not defined

### ISSUE THREAD

**Issue by pazitron1** [livewire/livewire#2339]
### Description
I have no issues on my localhost, though when I deploy live I get the following error:

```
Uncaught ReferenceError: Livewire is not defined

Uncaught Livewire Vue Plugin: window.livewire is undefined. Make sure @livewireScripts is placed above this script include
```

I am using Vue inside a livewire component

**livewire component:**
```
<div>
    
            @forelse($jobs as $job)
                <a
                    href="{{route('jobs.show', [$job->category->slug, $job->slug])}}">
                    ...
                </a>
            @empty
                <p>No jobs found... 😞 Try different search/filter parameters...</p>
            @endforelse
            <div>
                {{$jobs->links()}}
            </div>
        </div>
        <sidebar></sidebar>
    </div>
</div>
```

my livewire component sits inside a blade view, **welcome.blade.php**

```
@extends('layouts.app')

@section('css')
    <livewire:styles />
@endsection

@section('content')
    <div class="px-4 py-3">
        <livewire:job-index/>
    </div>
@endsection

@section('scripts')
    <livewire:scripts />
    <script src="https://cdn.jsdelivr.net/gh/livewire/vue@v0.3.x/dist/livewire-vue.js"></script>
@endsection

```

As you can see livewireScripts are about the vue plugin. What is the cause of the error on production? It works fine on localhost. I tried removing cache - no luck.

**Context**
- Livewire version: 2.3
- Laravel version: 7
- Browser: Chrome

**Comment by stevebauman** [comment]
Hi @pazitron1,

This is related to the issue I just posted (#2338). I'm assuming you're using nginx for your production environment?

A quick way to resolve this is to publish the `livewire.js` file using `php artisan livewire:publish --assets`:

https://laravel-livewire.com/docs/2.x/installation#publish-assets

Give that a shot and let me know if you're successful 👍

**Comment by pazitron1** [comment]
> Hi @pazitron1,
> 
> This is related to the issue I just posted (#2338). I'm assuming you're using nginx for your production environment?
> 
> A quick way to resolve this is to publish the `livewire.js` file using `php artisan livewire:publish --assets`:
> 
> https://laravel-livewire.com/docs/2.x/installation#publish-assets
> 
> Give that a shot, and then attempt to access your application again. Let me know if you're successful or not! 👍

Thank you, yes the site is on nginx and publishing assets worked! Ta

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by pazitron1** [comment]
Resolved by publishing the livewire.js vendor assets.

**Comment by aamirkhan37557** [comment]
not working i tried

**Comment by stevebauman** [comment]
@aamirkhan37557 You're going to have to create a separate issue with your own environment details so we can assist you. Would be happy to help you get up and running 👍

**Comment by aichasalhi** [comment]
I have same error but publishing livewire.js vendor assets doesn't change anything , any ideas ??

**Comment by joshhanley** [comment]
@aichasalhi can you please open your own discussion with details of what you have tried plus any other environment details and screenshots of any errors you are getting? Thanks!

**Comment by aichasalhi** [comment]
> @aichasalhi can you please open your own discussion with details of what you have tried plus any other environment details and screenshots of any errors you are getting? Thanks!

I already did, please help me here#4282

**Comment by aichasalhi** [comment]
Resolved by edited  `'asset_url' => null,` to `'asset_url' => '/public',` in livewire.php

**Comment by mejiam** [comment]
I had the same problem and I solved it in the following way:
1. publish livewire <pre>assets : php artisan livewire:publish --force</pre><br/>here select publish livewire cofing and livewire js
2. Add the following line in the composer.json file in the post-autoload-dump section <pre> "@php artisan vendor:publish --force --tag=livewire:assets --ansi"</pre>
3. 
I have modified the 'asset_url' variable in the livewire.php file (published)<pre> 'asset_url'  => '/my_project_base_path/public',</pre><br>I have then restarted the web service.
This has worked well for me in a published production project. With this I have solved the problem of Livewire.<br>The reference to this solution is found on the Livewire official site https://laravel-livewire.com/docs/2.x/installation#publish-assets.
I have only added a few variants.<br><br>Greetings

**Comment by fxalin** [comment]
En mi caso, el problema fue la versión de livewire-sortable en el archivo package.json. Para livewire 3, se requiere la versión 1.0.0.
https://github.com/livewire/sortable

Espero le sirva a alguien.
