### ISSUE TITLE
temporarySignedRoute is hardcoded to 5 minutes and causes requests to return 401 

### ISSUE THREAD

**Issue by FrancisMawn** [livewire/livewire#2344]
### Description
When uploading large videos files, we noticed a strange behaviour where requests returned 401 instead of 200. After some investigation, it appears that the problem is caused by the handle logic in the `FileUploadHandler` class.

Digging a bit more, I found this code in the `GenerateSignedUploadUrl` class:
```
public function forLocal()
{
    return URL::temporarySignedRoute(
        'livewire.upload-file', now()->addMinutes(5)
    );
}
```

This invalidates any uploads that would require more than 5 minutes. There are currently no ways to override this behaviour (as far as I know). Manually changing the value to 30 minutes fixed the issue, but that's hardly a solution. Would it be possible to make this value configurable just like we have configurations for maximum file size? Maybe something like:

```
'temporary_file_upload' => [
   'max_upload_time' => 5,
];
```

### Exact steps to reproduce
1. Upload a file that would take more than 5 minutes to upload
2. Request returned a 401 status code. 

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.0
- Laravel version: 8.11.2
- Browser: Chrome

**Comment by joshhanley** [comment]
@FrancisMawn yeah my opinion would be that it should be configurable. Any chance you could submit a PR for that config option?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
