### ISSUE TITLE
Redirect Not Working in 2.3.6

### ISSUE THREAD

**Issue by iAmKevinMcKee** [livewire/livewire#2348]
### Description

I just upgraded to 2.3.6 and my redirect doesn't work. The view does not render and the redirect does not happen.

### Exact steps to reproduce

Create a new laravel project, install livewire, create a component, put `$this->redirect('https://laravel-livewire.com')` in the mount method on the component. Put the component on a page and load the browser.

### Stripped-down, copy-pastable code snippets

```
public function mount()
    {
        $this->redirect('https://google.com');
    }
```

One other thing to note is that I've tried to `dd` in the `PerformsRedirects` class and it never even gets there.

**Context**
- Livewire version: 2.3.6
- Laravel version: 8.22.1
- Alpine version: N/A
- Browser: Chrome

**Comment by nuernbergerA** [comment]
@iAmKevinMcKee found it

**Comment by nuernbergerA** [comment]
Hey @iAmKevinMcKee please confirm if this fixes everything.

Thanks and sorry for the inconvenience.

**Comment by iAmKevinMcKee** [comment]
Seems to work. There is a little flash where the page with just the empty div is rendered before doing the actual redirect.

I'm wondering if there's any way to perform the redirect without having to load anything in the DOM.

**Comment by nuernbergerA** [comment]
This actually is the case if you use `Route::get('/some-url', Component::class)`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
