### ISSUE TITLE
Loading a livewire component inside a modal

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#2358]
### Description
I am trying to dynamically load a Livewire component inside a modal, using Livewire. I can successfully load the HTML content in the modal, but any Javascript on the "target" component is not executed.

### Exact steps to reproduce

```blade
{{-- index.blade.php --}}
<a onclick="showTask(1)">Open task #1</a>
@includeWhen($openTask, 'partials.tasks._task_modal')
```

```php
//Index.php 
function showTask(int $taskId){
        $this->managingTask = true;
        $this->openTask = Task::firstWhere('id', $taskId);
}
```

So in the above code, when a user clicks the `a` tag, it will open the modal, placed in:

```html
<!-- _task_modal.blade.php -->
<x-jet-dialog-modal wire:model="managingTask">
    <x-slot name="content">
        @livewire('tasks.show', ['task' => $openTask])
    </x-slot>
</x-jet-dialog-modal>
```

As you can see, the modal component simply refers to another Livewire component called `tasks.show`. Inside this, I have the following in the view file:

```blade
{{-- show.blade.php --}}
<a onclick="test()">Test</a>
@push('scripts')
    <script type="text/javascript">
        function test(){
            alert("It works!")
        }
       document.addEventListener('livewire:load', function () {
          console.log("Livewire Loaded");
      });
  </script>
@endpush
```

Now, when clicking on the `a` link inside the `show.blade.php` Livewire component, I get the following error:

> Uncaught ReferenceError: test is not defined

Further, I do not see the "Livewire Loaded" in my console.

**Context**
- Livewire version:  2.3.6
- Laravel version: 8.12
- Browser: Chrome

**Comment by marispro** [comment]
I don't think that dynamically `@push('scripts')` will push your script into some scripts section.
I see following solutions:
1. script should be pushed on initial page render
2. just remove `@push('scripts')` and `@endpush` to keep it under component
3. use alpinejs and move javascript into `x-init `directive.

**Comment by oliverbj** [comment]
How would I accomplish #1?

In regards to #2:
I tried to remove @push('scripts'), and move the `<script>` inside the component root div element, but no change unfortunately. 

When I open the modal, and inspect the HTML, I do see the <script> being appended, but it seems like it is not executed. 

I am actually already using Alpine.js in my project (forgot to add that to my original post). 

How would I go about adding all my javascript code into `x-init`?

**Comment by oliverbj** [comment]
BTW, I just tried to append the script to my `<head>` dynamically with the below, from the `show.blade.php` component:

```javascript
<script>
const inlineScript = document.createElement('script')
inlineScript.innerHTML = `<script>var actionSelected = false; ...... `
document.head.append(inlineScript)
</script>
```

This work - to some point. `livewire:load` is still not being called. If I remove the event listener for `livewire:load`, everything work when I open the show component in the modal. However, when I open the show component outside the modal (direct link), it doesn't because it requires `livewire:load`...
This does work - to some po

**Comment by marispro** [comment]
```
{{-- show.blade.php --}}
<div x-data="{ test(){alert('It works!'); } }"
x-init="alert('I loaded');"
>
	<a x-on:click="test()">Test</a>
</div>
```
This should work.
Anyway, still not sure about dynamically livewire:load

**Comment by oliverbj** [comment]
My issue is that `livewire:load` is still not being fired if loading the component dynamically.

**Comment by oliverbj** [comment]
I opened a new, more re-produceable, issue over at #2359.

**Comment by mahmoudelshenawy** [comment]
can any one help me with this issue 
The whole form is dispearing once i start typing in any of them in livewire model bind , i have tried using wire:ignore and it stops that behavior but the validation errors did not show

**Comment by austenc** [comment]
@mahmoudelshenawy Please don't hijack unrelated issues asking for support. The "Issues" tab is for reporting and discussing bugs. 

If you find a bug, please open your own issue with specific reproduction info.

**Comment by mahmoudelshenawy** [comment]
actually it was related to that issue but i wont blame you you didn't see
my code to judge
apparently after some digging i found that typing in the field remove the
active class from the parent element making it fade out so i rewrite it
with alpine js and the problem is solved , about wire:ignore it prevent
this behavior and also prevent showing the validation errors but now it is
fixed

في الجمعة، ١٥ يناير، ٢٠٢١ ١٠:١٤ م Austen Cameron <notifications@github.com>
كتب:

**Comment by joshhanley** [comment]
@oliverbj if you have opened another issue with better reproducibility, is there any reason this issue shouldn't be closed?Otherwise we will use #2359 to investigate and close this one.

**Comment by oliverbj** [comment]
@joshhanley No, you are correct. I'll close this and we should continue the discussion in #2359 👍🏽

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by manhthang2504** [comment]
> 

This.
I have the same issue. Then using the solution suggested here, I move the inline script into `x-data` (before that, `x-data=extractedFunction()`, then put my extractedFunction() in to inline <script> tag, now I transfer all the code into `x-data`) and it works like charm.
