### ISSUE TITLE
Nesting components inline javascript not working

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#2359]
### Description
I have a "parent-child" situation, which I am trying to use Livewire for.  My issue is that any inline Javascript written on the child component is not working.

### Exact steps to reproduce
Consider the two components `Master` and `Child`:
```blade
<!-- master.blade.php -->
<div>
    <a wire:click="$set('task', true)">Open Task</a>
    @if($task)
        <livewire:test.child :task="$task"></livewire:test.child>
    @endif
</div>
```

```php
//Master.php
class Master extends Component
{
    public $task;

    public function render()
    {
        return view('livewire.test.master');
    }
}
```

In the above master component, whenever I click on "Open Task", the `$task` variable will be set to true. This will make the `child` component render. The child component looks like this:

```blade

<!-- child.blade.php -->
<div class="p-4">
    The task is set.<br />
    <a onclick="showName('Test Task')">Show task</a>

    <script type="text/javascript">
        function showName(name){
                    alert("Task name is: " + name);
            }
    </script>
</div>
```

```php
//Child.php
class Child extends Component
{
    public $task;

    public function render()
    {
        return view('livewire.test.child');
    }
}
```

When clicking on `Show Task` in the child, I get the following error:

> Uncaught ReferenceError: showName is not defined at HTMLAnchorElement.onclick (<anonymous>:2:1)

Further, on the child component, I would like to know when Livewire has finished loading on that specific component, thus adding:

```javascript
//child.blade.php
document.addEventListener('livewire:load', function () { 
    console.log("Livewire finished loading in child.")
});
```

The the above is never fired off either.

### Stripped-down, copy-pastable code snippets
See above.

**Context**
 - Alpine version: 2.7.3
 - Livewire version: 2.3.6
 - Laravel version: 8.12
 - Browser: Chrome

**Comment by joshhanley** [comment]
@oliverbj is there any reason you're not using Alpine for this? Alpine would work best in this situation as it was designed to work like this.

Otherwise what I suspect is happening is morphDOM is adding the button html to the DOM and trying to register the click handler before the script tag has been added to the DOM, so you would probably need to put the script tag before the button. You may also need to register the function to the window `window.showName = function (name) {...}` as the scope probably won't work as expected due to morphDOM

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
