### ISSUE TITLE
Missing singleton instance in action

### ISSUE THREAD

**Issue by edwinvdpol** [livewire/livewire#2364]
### Description
Not sure whether this is a bug, or it is by design, but when I create a singleton instance in the `AppServiceProvider`, it is missing when an action is fired. It is available in the `mount()` method. If this isn't a bug, can someone tell me what to do to get the instance?

### Exact steps to reproduce
* Create a component and blade template which is loaded.
* Create a class with some properties (I had it in the `App\Services` folder / namespace).
* Create a singleton in the `register()` method of the `AppServiceProvider`.

```php
public function register()
{
    $this->app->singleton(CustomClass::class, function () {
        return new CustomClass();
    });
}
```

* Put `ddd(app())` in the _mount_ method of the component
* Visit the page with the new component.
* Find the class in the `instances` section of the output. You will find the instance of your class.

It all works, until I do the following:

* Create an action and **move** the `ddd(app())` to this method.
* Refresh the page, and call the action in your blade template with `wire:click="youraction"`.
* Checkout the `instances` section again, and you'll see that it is missing.

```php
public function youraction()
{
    ddd(app());
}
```

For this reason also, dependency injection is not working.

**Context**
- Livewire version: 2.3.6
- Laravel version: 8.21.0
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by stevebauman** [comment]
Hi @edwinvdpol,

Looking at the livewire docs, you should be able to dependency inject your bound container instances by supplying a type-hint in the actions method:

```php
public function youraction(CustomClass $class)
{
    // Perform the action and utilize the injected class.
}
```

From the docs:

https://laravel-livewire.com/docs/2.x/actions#action-parameters

```php
public function addTodo(TodoService $todoService, $id, $name)
{
    //...
}
```

Can you give that a shot?

**Comment by edwinvdpol** [comment]
Hi @stevebauman,

Thank you for your response.

Unfortunately, I already tried that but I'm getting an empty instance of the class.
So basically Laravel knows the class I'm injecting, but doesn't give the the _singleton_ instance.
Now, I don't know exactly which route Livewire is taking on an action, so I thought somebody here might know the solution.

Does it work for you when you replicate the steps described? If so, I'm doing something wrong but I really don't know what 😕

**Comment by stevebauman** [comment]
Happy to help @edwinvdpol!

> Unfortunately, I already tried that but I'm getting an empty instance of the class.

There's test cases validating the dependency injection feature:

https://github.com/livewire/livewire/blob/master/tests/Unit/ComponentDependencyInjectionTest.php

Namely this test:

https://github.com/livewire/livewire/blob/8663232c198ef12964b62559e9bb2023eb86701d/tests/Unit/ComponentMethodBindingsTest.php#L91-L101

How are validating that the class is "empty"? Can you post your real singleton code? Whereabouts in your application are you instantiating the singleton and modifying the instance? It seems that could be the culprit -- as the livewire component may not be following the application flow you're expecting and thus not touching the singleton instance you're expecting.

**Comment by edwinvdpol** [comment]
Hi again @stefanbauer,

I checked it again with a fresh set of eyes, and I know what I did 'wrong', or better yet, didn't do at all.
Long story short, I forgot to initialize the class in the action itself.
I kept thinking, but it is working in `mount()` but then I realised that it is an seperate call to the action.
The whole method which initialzed the class, wasn't called at all, but it does at the initial page load. 🙈 

Still working on adjusting to this "new" way of programming (in my head).

Thank you for your patience, stay safe! 👍

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
