### ISSUE TITLE
No rules when binding to a model = no errors

### ISSUE THREAD

**Issue by SwiTool** [livewire/livewire#2374]
### Description

When you are trying to load properties from a model inside a Component without any rules, the fields value blinks and you are not able to display and/or modify the field

### Exact steps to reproduce

* Create a Component with `php artisan livewire:make MyComponent`
* Add a public User type variable
* Mount it with a user from the database

### Stripped-down, copy-pastable code snippets

```php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Auth;

class MyComponent extends Component
{
    public User $user;

    public function mount()
    {
        $this->user = Auth::user();
    }

    public function render()
    {
        return view('livewire.profile.show');
    }
}
```

View:
```html
<div>
    <input wire:model="user.email" type="email"/>
</div>
```

### What should it do ?

- Either throw an error because no `$rules` have been defined
- Or ignore the `$rules` variable

**Context**
- Livewire version: 2.3.5
- Laravel version: 8.16.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by marispro** [comment]
I am getting error as should (version 2.3.6), can you try it after update?

`Cannot bind property [user.email] without a validation rule present in the [$rules] array on Livewire component: [my-component].`

**Comment by SwiTool** [comment]
> I am getting error as should (version 2.3.6), can you try it after update?
> 
> `Cannot bind property [user.email] without a validation rule present in the [$rules] array on Livewire component: [my-component].`

I upgraded to 2.3.6, i did `php artisan clear-compiled`, `php artisan optimize`, I still have the issue.

My component is a page, extending a layout file. Don't know if it can be related.

By the way, when no `$rules` are set, my page loads but fields aren't filled in, and the data passed down via entangle seem to be `undefined`, as I get this error on JS side:
![image](https://user-images.githubusercontent.com/8834915/105019714-ace79200-5a46-11eb-917a-a6fb025f72b4.png)

Here is my route:
```php
    Route::get('/user/profile', App\Http\Livewire\Profile\Show::class)->name('profile.show');
```

And my Component:
```
<?php

namespace App\Http\Livewire\Profile;

use App\Models\User;
use Livewire\Component;
use Auth;

class Show extends Component
{
    public User $user;

    // protected $rules = [
        // 'user.email' => 'required|max:255',
        // 'user.firstname' => 'required|max:255',
        // 'user.lastname' => 'required|max:255',
        // 'user.address' => 'required|max:255',
        // 'user.address_comp' => 'required|max:255',
        // 'user.zip_code' => 'required|max:20',
        // 'user.city' => 'required|max:255',
        // 'user.notification_email' => 'nullable',
    // ];

    public function mount()
    {
        $this->user = Auth::user();
    }

    public function render()
    {
        return view('livewire.profile.show');
    }
}
```

**Comment by austenc** [comment]
@SwiTool I also just tested this and from what I can tell, it's working properly. Make sure you are not on version `2.3.7` as that version contains a bug.

**Here's what I found in my testing:**
- If you don't have any rules, it will not bind the input correctly on the initial page load. The input will be blank and no error will be thrown. This is consistent with older versions of Livewire `2.x` too. 
- Once you type into the input, you should get the error*

_*this error requires a server roundtrip, so if you have a javascript problem with your use of @entangle, you probably wouldn't see the error, since the javascript would probably error before the ajax request completes_

If you could provide us with a public repository to check it out we may be able to help further. This may be a case of user error (rather than a Livewire bug), but until we have more context we can't be sure.

**Comment by SwiTool** [comment]
Thanks for the clarification, i'll get back soon (within 3 days) to tell if it was because of the js error.

**Comment by SwiTool** [comment]
Yes, you are right, and on my side, it didn't throw any error because i had the `.defer` modifier. If i remove it, it throws when input is typed. So everything is alright. Sorry for my mistake.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by JoelLauret** [comment]
I know its a little late, but for someone that is having the error in the model data binding try to update your php version to 7.4, livewire v2 use some of the improvements that php have made from version 7.4 +
