### ISSUE TITLE
Detach role from the user and delete the user in bulk along with livewire traits

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2378]
### Description
I have a "belongsToMany" eloquent relationship between users and roles . I am creating a CRUD system with capability to do bulk actions. I followed the Livewire Screencasts [Bulk Export/Delete](https://laravel-livewire.com/screencasts/s7-bulk-actions) and [Refactoring For Re-Usability](https://laravel-livewire.com/screencasts/s7-refactoring). I have created a trait for the bulk actions, so I'm able to use it out of the box.

I need to detach the role from the user and then delete the user in bulk. I am unable to call `roles` relationship on a public method property and detach the same. This is how I detach the role for a single user `$this->user->roles()->detach();` but I'm unable to do it with `$this->selectedRowsQuery->roles()->detach();` in case of bulk user deletion.

### Stripped-down, copy-pastable code snippets
- Livewire/Backend/UserController
```
public $showUserBulkDeletionModal = false;

public function confirmDeleteBulk()
{
    $deleteCount = $this->selectedRowsQuery->count();
        
    $this->selectedRowsQuery->roles()->detach();
    $this->selectedRowsQuery->delete();
    $this->showUserBulkDeletionModal = false;

    $this->notify('You\'ve deleted '.$deleteCount.' users');
}

public function getRowsQueryProperty()
{
    $query = User::query()
        ->when($this->filters['email'], fn($query, $email) => $query->where('email', 'like', '%'.$email.'%'))
        ->when($this->filters['role'], fn($query, $role) => $query->whereHas('roles', fn ($query) => $query->where('id', $role)))
        ->when($this->filters['search'], fn($query, $search) => $query->where('name', 'like', '%'.$search.'%'))
        ->when($this->filters['date-min'], fn($query, $created_at) => $query->where('created_at', '>=', Carbon::createFromFormat('d/m/Y', $created_at)))
        ->when($this->filters['date-max'], fn($query, $created_at) => $query->where('created_at', '<=', Carbon::createFromFormat('d/m/Y', $created_at)));
        
    return $this->applySorting($query);
}
```

- Livewire/Traits/WithBulkActions
```
trait WithBulkActions
{
    public $selectPage = false;
    public $selectAll = false;
    public $selected = [];

    public function renderingWithBulkActions()
    {
        if ($this->selectAll) $this->selectPageRows();
    }

    public function updatedSelected()
    {
        $this->selectAll = false;
        $this->selectPage = false;
    }

    public function updatedSelectPage($value)
    {
        if ($value) return $this->selectPageRows();

        $this->selectAll = false;
        $this->selected = [];
    }

    public function selectPageRows()
    {
        $this->selected = $this->rows->pluck('id')->map(fn($id) => (string) $id);
    }

    public function selectAll()
    {
        $this->selectAll = true;
    }

    public function getSelectedRowsQueryProperty()
    {
        return (clone $this->rowsQuery)
            ->unless($this->selectAll, fn($query) => $query->whereKey($this->selected));
    }
}
```

**Context**
- Livewire version: 2.3.6
- Laravel version: 8.23.1
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by toxifiedmatrix** [comment]
![Role Detach Bulk](https://user-images.githubusercontent.com/65024122/105073750-785af100-5aad-11eb-802c-48c78eae5e10.gif)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
