### ISSUE TITLE
Better way to access checkbox state

### ISSUE THREAD

**Issue by evergreenwebsystems** [livewire/livewire#238]
I have an ```@foreach``` loop which outputs some checkboxes. I want to store the id of the checkboxes which have been selected in a pivot table. The below code is working fine but it seems a little hacky in terms of how I reference the specific checkbox which has been clicked.

Specifically I use ```preg_replace``` to access the checkbox ```id``` like this, ``` preg_replace('/\D/', '', $name) ```. This might be a wrong assumption, but I find that if I do not use the full model reference which includes the ```id``` and the ```checked``` key then Livewire won't update the state of the checkbox. So, as a result I am having to extract the actual ```id``` from within this string.

Blade:
```html
    @foreach ($labels as $index => $label)
    <div class="w-full mb-2 p-3 rounded text-white {{ $label['color'] }}">
        <input type="checkbox" wire:model="labels.{{ $label['id'] }}.checked" name="labels"
            @if($task->labels->contains($label['id'])) checked @endif>
        <span class="ml-2 text-sm">{{ $label['name'] }}</span>
    </div>
    @endforeach
```

Component:
```php
    public function updated($name)
    {
        $task = Task::findOrFail($this->id);

        $labels = collect($this->labels)->where('id', preg_replace('/\D/', '', $name))->map(function ($item) {
            return [
                'task_id' => $this->id,
                'label_id' => $item['id'],
                'owner_id' => auth()->id()
            ];
        });
        $task->labels()->toggle($labels);
    }
```

Does anyone know of a better way I can do this?

**Comment by calebporzio** [comment]
You can have multiple of the same `wire:model`s on different checkboxes:
```html
<input type="checkbox" value="A" wire:model="foo">
<input type="checkbox" value="B" wire:model="foo">
```

Now, when you check both, the value of `$foo`, should be `[A,B]`

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
@calebporzio 
i do that but i get as boolean in back-end

![image](https://user-images.githubusercontent.com/29556066/82849918-bf97de80-9f2c-11ea-8fe1-fd04a1201faa.png)

so $this->userPermissions gives true or false in backend

**Comment by Elshaden** [comment]
@calebporzio
Hi
I tired this solution, OK it does send back the checkbox change state, but it does not tell me if its checked or not, it just tells you the state changed only.

How can i do the above and get the state of the checkbox. if its true or false.

**Comment by GertjanRoke** [comment]
@Elshaden I also just ran into the same problem and like Caleb said works just fine.
The only problem I had was that my `for` and `id` were the same for every checkbox so then it will update all checkboxes.

**Also it's imported that the place where you want to store the selected values is an array.**

This is how my code looks:
```blade
@forelse($property['values'] as $key => $value)
    <label for="{{ $loop->index }}" class="cursor-pointer flex items-center">
        <input wire:model="properties.2.value.value" id="{{ $loop->index }}" type="checkbox" value="{{ $key }}">
        {{ $value }}
    </label>
@endforeach
```

And I'm working with an attribute value structured system so I have a public property called `properties` and it's an array with arrays that looks like this:
```php
[
  [
    "attribute_id" => 52
    "element_type" => "checkbox"
    "name" => "Label..."
    "values" => [...]
    "value" => array:2 [
      "attribute_id" => 52
      "value" => []
    ],
    ...
]
```

**Comment by jdhamaniya** [comment]
> You can have multiple of the same `wire:model`s on different checkboxes:
> 
> ```
> <input type="checkbox" value="A" wire:model="foo">
> <input type="checkbox" value="B" wire:model="foo">
> ```
> 
> Now, when you check both, the value of `$foo`, should be `[A,B]`

How to make Select all checkbox for multiple checkboxes ?

**Comment by ayoub-bousetta** [comment]
> You can have multiple of the same `wire:model`s on different checkboxes:
> 
> ```
> <input type="checkbox" value="A" wire:model="foo">
> <input type="checkbox" value="B" wire:model="foo">
> ```
> 
> Now, when you check both, the value of `$foo`, should be `[A,B]`

Not working... the model ended selecting both even if you select only one

**Comment by alucard29** [comment]
> 
> 
> > You can have multiple of the same `wire:model`s on different checkboxes:
> > ```
> > <input type="checkbox" value="A" wire:model="foo">
> > <input type="checkbox" value="B" wire:model="foo">
> > ```
> > 
> > 
> > Now, when you check both, the value of `$foo`, should be `[A,B]`
> 
> Not working... the model ended selecting both even if you select only one

Not working for me too @calebporzio

**Comment by poldixd** [comment]
@ayoub-bousetta and @alucard29 Are you working with integers? With strings I don't have any issues, but when I switch the values to integers, I have issues.

**Comment by itepifanio** [comment]
This is not working for me either. Using the 2.3.0 version. 
@poldixd weird, I'm using string here, but the bug keep going. Which livewire version are you using?

**Comment by poldixd** [comment]
> This is not working for me either. Using the 2.3.0 version.
> @poldixd weird, I'm using string here, but the bug keeps going. Which livewire version are you using?

I'm using v2.3.0. @calebporzio also convert the integers in strings. You can see it in his screencast: https://laravel-livewire.com/screencasts/s7-select-all (6m30s)

**Comment by itepifanio** [comment]
Got it @poldixd, actually, I was having a js conflict here, works fine. Sorry for you time :sweat_smile:

**Comment by rizkhal** [comment]
how to make it selected?
in my case, i want to set selected checkbox when id exists in array
my view
```blade
@foreach ($allPermissions as $p)
  <div class="form-check">
      <input class="form-check-input" type="checkbox" value="{{ $p->id }}" id="{{ $loop->index }}"
          {{ in_array($p->id, $roleHavePermissions) ? 'checked' : '' }}>
      <label class="form-check-label" for="{{ $loop->index }}">
          {{ $p->name }}
      </label>
  </div>
@endforeach
```
my component
```php
public function render()
{
    return view('setting::livewire.permission.setting', [
        'allPermissions' => Permission::query()->select(['id', 'name'])->get(),
        'roleHavePermissions' => DB::table("role_has_permissions")->where("role_has_permissions.role_id", $this->roleId)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')->all(),
    ]);
}
```

if i remove wire:model and name the checkbox is selected but when i add wire:model and name the checkbox selected not working...

Sorry my english so bad.

**Comment by chamilapj** [comment]
I tried, when i check one chckbox other checkboxes are automatically get checked.

**Comment by bendadamohamed** [comment]
> I tried, when I check one checkbox other checkboxes are automatically get checked.

put a different values to value ,like: value="a"value="b"value="c"

**Comment by bendadamohamed** [comment]
> I tried, when I check one checkbox other checkboxes are automatically get checked.

good exampl for you:
```
 @foreach ($categories as $category)
                    <div class="my-2 text-xl">
                        <div>
                            <input type="checkbox" wire:model="box", name="check" value="{{ $category->id }}">
                            {{ $category->name }}
                        </div>
                    </div>
                @endforeach
```
```
 public $box =[];
 
    public function render()
    {
        $categories =[]; 
        $products =[]; 
        $categories = Category::all();
        $products = Product::when($this->box,function($query){
            $query->whereIn('Category_id',$this->box);
        })->get();
       
        return view('livewire.checkboox',[
            'categories'=>$categories ,
            'products'=>$products ,
        ]);
    }
```

**Comment by Mohsing511** [comment]
> > You can have multiple of the same `wire:model`s on different checkboxes:
> > ```
> > <input type="checkbox" value="A" wire:model="foo">
> > <input type="checkbox" value="B" wire:model="foo">
> > ```
> > 
> > 
> > Now, when you check both, the value of `$foo`, should be `[A,B]`
> 
> How to make Select all checkbox for multiple checkboxes ?

i need help[ i wants to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
```
<button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
 <td class="px-6 py-4 whitespace-nowrap">
                            <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
                        </td>
```
and function is empty so please guide me 
 ```
public function selectAll(){
}

```

**Comment by bendadamohamed** [comment]
> I need help I want to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
> 
> ```
> <button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
>  <td class="px-6 py-4 whitespace-nowrap">
>                             <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
>                         </td>
> ```
> 
> and function is empty so please guide me
> 
> ```
> public function selectAll(){
> }
> ```

**Comment by bendadamohamed** [comment]
> I need help I want to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
> 
> ```
> <button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
>  <td class="px-6 py-4 whitespace-nowrap">
>                             <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
>                         </td>
> ```
> 
> and function is empty so please guide me
> 
> ```
> public function selectAll(){
> }
> ```
 
```
class Select extends Component
{
    public $checked= [];
    public $selectAll= false;
    public function render()
    {
        return view('livewire.select' , [
            'posts'=>$this->posts
        ]);
    }
    public function updatedSelectAll($value){
    //  dd($value);
     if ($value) {
        // map(fn ($query)=>(string) $query) this part her for convert each post id to string
         $this->checked =$this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() ;
        //  dd($this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() );
     }else {
         $this->checked=[];
     }
    }
    public function getPostsProperty(){
        return Post::all();
        //this function for watch (if one of the input checkboxs are checked) ->(the selectall checkbox unchecked)
    }public function updatedChecked(){
        $this->selectAll=false;
    }
    // public function isChecked($post_id){
    //     // Checks if post_id  exists in an checked[]
    //    return in_array($post_id,$this->checked);
    // }
}
```
select.blade.php

```
<div class="shadow overflow-hidden rounded border-b border-gray-200 w-1/5">
    <div class="py-3 px-4 mt-5 uppercase font-semibold text-sm bg-gray-200 rounded">
        select all
        <input type="checkbox" wire:model="selectAll" class="form-checkbox focus:outline-none focus:shadow-outline">
    </div>
    <table class="min-w-full bg-white">
        <thead class="bg-purple-500 text-blackF">
            <tr>
                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Last name</th>

            </tr>
        </thead>
        @foreach ($posts as $post)

            <tbody class="text-gray-700">
                <tr>
                    <td class="w-1/3 text-left py-3 px-4">{{ $post->name }}</td>
                    <td class="w-1/3 text-left py-3 px-4">
                        <input type="checkbox" wire:model="checked" id="" value="{{ $post->id }}">
                    </td>

                </tr>

            </tbody>
        @endforeach


        {{-- @json($selectAll) --}}
    </table>
</div>
```

**Comment by bendadamohamed** [comment]
> > I need help I want to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
> > ```
> > <button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
> >  <td class="px-6 py-4 whitespace-nowrap">
> >                             <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
> >                         </td>
> > ```
> > 
> > 
> > and function is empty so please guide me
> > ```
> > public function selectAll(){
> > }
> > ```
> 
> ```
> class Select extends Component
> {
>     public $checked= [];
>     public $selectAll= false;
>     public function render()
>     {
>         return view('livewire.select' , [
>             'posts'=>$this->posts
>         ]);
>     }
>     public function updatedSelectAll($value){
>     //  dd($value);
>      if ($value) {
>         // map(fn ($query)=>(string) $query) this part her for convert each post id to string
>          $this->checked =$this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() ;
>         //  dd($this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() );
>      }else {
>          $this->checked=[];
>      }
>     }
>     public function getPostsProperty(){
>         return Post::all();
>         //this function for watch (if one of the input checkboxs are checked) ->(the selectall checkbox unchecked)
>     }public function updatedChecked(){
>         $this->selectAll=false;
>     }
>     // public function isChecked($post_id){
>     //     // Checks if post_id  exists in an checked[]
>     //    return in_array($post_id,$this->checked);
>     // }
> }
> ```
> 
> select.blade.php
> 
> ```
> <div class="shadow overflow-hidden rounded border-b border-gray-200 w-1/5">
>     <div class="py-3 px-4 mt-5 uppercase font-semibold text-sm bg-gray-200 rounded">
>         select all
>         <input type="checkbox" wire:model="selectAll" class="form-checkbox focus:outline-none focus:shadow-outline">
>     </div>
>     <table class="min-w-full bg-white">
>         <thead class="bg-purple-500 text-blackF">
>             <tr>
>                 <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
>                 <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Last name</th>
> 
>             </tr>
>         </thead>
>         @foreach ($posts as $post)
> 
>             <tbody class="text-gray-700">
>                 <tr>
>                     <td class="w-1/3 text-left py-3 px-4">{{ $post->name }}</td>
>                     <td class="w-1/3 text-left py-3 px-4">
>                         <input type="checkbox" wire:model="checked" id="" value="{{ $post->id }}">
>                     </td>
> 
>                 </tr>
> 
>             </tbody>
>         @endforeach
> 
> 
>         {{-- @json($selectAll) --}}
>     </table>
> </div>
> ```



> I need help I want to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
> 
> ```
> <button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
>  <td class="px-6 py-4 whitespace-nowrap">
>                             <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
>                         </td>
> ```
> 
> and function is empty so please guide me
> 
> ```
> public function selectAll(){
> }
> ```

if that you need / let me see your feedback :)

<?php

namespace App\Http\Livewire;

use App\Models\Post;
use Livewire\Component;

class Select extends Component
{
    public $checked= [];
    public $selectAll= false;
    public function render()
    {
        return view('livewire.select' , [
            'posts'=>$this->posts
        ]);
    }
    public function updatedSelectAll($value){
    //  dd($value);
     if ($value) {
        // map(fn ($query)=>(string) $query) this part her for convert each post id to string
         $this->checked =$this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() ;
        //  dd($this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() );
     }else {
         $this->checked=[];
     }
    }
    public function getPostsProperty(){
        return Post::all();
        //this function for watch (if one of the input checkboxs are checked) ->(the selectall checkbox unchecked)
    }public function updatedChecked(){
        $this->selectAll=false;
    }
}

**Comment by bendadamohamed** [comment]
> I need help I want to use a button (select all) but don't know how to check all checkboxes using a function please guide me. thanks in advance.
> 
> ```
> <button wire:click="selectAll()" class="transform hover:scale-110 border-4 text-xl bg-red-500 hover:bg-red-700">Select All</button>
>  <td class="px-6 py-4 whitespace-nowrap">
>                             <input type="checkbox" name="checkbox" id="checkbox" value="{{ $staff->id }}" wire:model="recordSelected">{{ $staff->id }}
>                         </td>
> ```
> 
> and function is empty so please guide me
> 
> ```
> public function selectAll(){
> }
> ```

////  you just now need to create posts table after copy this code and i do some comments for you for more understand my code
```
<?php

namespace App\Http\Livewire;

use App\Models\Post;
use Livewire\Component;

class Select extends Component
{
    public $checked= [];
    public $selectAll= false;
    public function render()
    {
        return view('livewire.select' , [
            'posts'=>$this->posts
        ]);
    }
    public function updatedSelectAll($value){
    //  dd($value);
     if ($value) {
        // map(fn ($query)=>(string) $query) this part her for convert each post id to string
         $this->checked =$this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() ;
        //  dd($this->posts->pluck('id')->map(fn ($query)=>(string) $query)->toArray() );
     }else {
         $this->checked=[];
     }
    }
    public function getPostsProperty(){
        return Post::all();
        //this function for watch (if one of the input checkboxs are checked) ->(the selectall checkbox unchecked)
    }public function updatedChecked(){
        $this->selectAll=false;
    }
}
```
select.blade.php

```
<div class="shadow overflow-hidden rounded border-b border-gray-200 w-1/5">
    <div class="py-3 px-4 mt-5 uppercase font-semibold text-sm bg-gray-200 rounded">
        select all
        <input type="checkbox" wire:model="selectAll" class="form-checkbox focus:outline-none focus:shadow-outline">
    </div>
    <table class="min-w-full bg-white">
        <thead class="bg-purple-500 text-blackF">
            <tr>
                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Last name</th>

            </tr>
        </thead>
        @foreach ($posts as $post)

            <tbody class="text-gray-700">
                <tr>
                    <td class="w-1/3 text-left py-3 px-4">{{ $post->name }}</td>
                    <td class="w-1/3 text-left py-3 px-4">
                        <input type="checkbox" wire:model="checked" id="" value="{{ $post->id }}">
                    </td>

                </tr>

            </tbody>
        @endforeach


        {{-- @json($selectAll) --}}
    </table>
</div>
```

**Comment by abhiburk** [comment]
For mainting state when you have array data type please try to convert the array elements to string
`$ids = array_map('strval', [1,2,3])`

**Comment by RadhaKishan143** [comment]
> For mainting state when you have array data type please try to convert the array elements to string
> `$ids = array_map('strval', [1,2,3])`

its worked :) :) :) :100: 
,Thank Q so much,

**Comment by claushellsing** [comment]
> I tried, when I check one checkbox other checkboxes are automatically get checked.

exactly my same issue

**Comment by cluzstudio** [comment]
> Not working... the model ended selecting both even if you select only one

just initialize the variable in the component as an array ... $ foo = []

**Comment by HamzataBarrie** [comment]
> how to make it selected? in my case, i want to set selected checkbox when id exists in array my view
> 
> ```
> @foreach ($allPermissions as $p)
>   <div class="form-check">
>       <input class="form-check-input" type="checkbox" value="{{ $p->id }}" id="{{ $loop->index }}"
>           {{ in_array($p->id, $roleHavePermissions) ? 'checked' : '' }}>
>       <label class="form-check-label" for="{{ $loop->index }}">
>           {{ $p->name }}
>       </label>
>   </div>
> @endforeach
> ```
> 
> my component
> 
> ```
> public function render()
> {
>     return view('setting::livewire.permission.setting', [
>         'allPermissions' => Permission::query()->select(['id', 'name'])->get(),
>         'roleHavePermissions' => DB::table("role_has_permissions")->where("role_has_permissions.role_id", $this->roleId)
>             ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')->all(),
>     ]);
> }
> ```
> 
> if i remove wire:model and name the checkbox is selected but when i add wire:model and name the checkbox selected not working...
> 
> Sorry my english so bad.

/

I Have the same problem, i need a help
