### ISSUE TITLE
Funny duplication issue when rendering a form in a foreach loop

### ISSUE THREAD

**Issue by devingray** [livewire/livewire#2385]
### Description

When displaying a form inside a foreach loop. Updating the state does not remove the form element from the page. 

In the example below you can see that the Delete button is a `<form>` element

![livewire](https://user-images.githubusercontent.com/11573528/105209053-f84f8c80-5b7b-11eb-9525-f25447c30dc5.gif)

When changing the element from a form `<form>` to anchor `<a .. />` it does not do this any more

### Exact steps to reproduce

Class

```php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Test extends Component
{
    use WithPagination;

    public $search = '';
    public $perPage = 5;
    public $orderDirection = true;  // DESC = true
    public $orderBy = 'id';
    public $users;

    public function updatingSearch()
    {
        $this->render();
    }

    public function render()
    {
        $query = '%' . $this->search . '%';

        $this->users = User::where('name', 'like', $query)
            ->orWhere('email', 'like', $query)
            ->orderBy($this->orderBy, $this->orderDirection ? 'DESC' : 'ASC')
            ->limit(5)->get();

        return view('livewire.test');
    }
}

```

Component

```html

<div class="z-50">
    <input
        x-data
        wire:model.debounce.300ms="search"
        type="search"
        class="appearance-none block w-full bg-blue-100 border border-gray-300 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none"
        placeholder="Search users..."
        autocomplete="off">
    <table>
        @forelse($users as $user)
        <td class="w-full lg:w-auto p-1 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
            {{ $user->name }}
            <div>
                <a
                    class="bg-white-200 text-gray-700 rounded-md px-2 py-1 m-1 hover:no-underline transition duration-500 ease  hover:bg-blue-400 hover:text-white"
                    href="/users/{{ $user->id }}/edit">
                    Edit
                </a>
                <form style="display:inline;" action="/users/delete/{{ $user->id }}" method="POST">
                    <input type="hidden" name="id" value="{{ $user->id }}">
                    <button
                        type="button"
                        class="bg-white-200 text-gray-700 rounded-md px-2 py-1 m-1 transition duration-500 ease hover:bg-red-700 hover:text-white">
                        Delete
                    </button>
                </form>
            </div>
        </td>
            @empty
                <p>no results</p>
        @endforelse
    </table>
</div>

```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [latest]
- Laravel version: [latest]
- Alpine version: [latest]
- Browser: [Safari]

**Comment by jongravois** [comment]
On the TD after a @forelse you need a wire:key

> On Jan 20, 2021, at 11:05 AM, Devin Gray <notifications@github.com> wrote:
> 
> @forelse($users as $user)
>         <td class="w-full lg:w-auto p-1 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
>             {{ $user->name }}

For example
@forelse ($records as $record)

    <x-table.row wire:loading.class.delay="opacity-50"
                 wire:key="row-{{$record->id}}">
Else the Dom-Sniffer or Differ gets confused

**Comment by joshhanley** [comment]
@devingray yeah that is a morphdom issue. As @jongravois suggested, you need to add a `wire:key` to your `<tr>` tag so morphdom can distinguish one row from the nest when it changes them. It's the same reason you need a key on a loop in VueJs.

Check out "Dom Diffing Issues" here https://laravel-livewire.com/docs/2.x/troubleshooting

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by devingray** [comment]
@joshhanley @jongravois 

Of course.. Thank you!
