### ISSUE TITLE
Problem with encoding $set() function

### ISSUE THREAD

**Issue by crrack** [livewire/livewire#2390]
### Description
When i try to send in javascript with $set() function some special char like "řěšč" i will get error 
`Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.` And livewire start sending every second new request to `http://webdo.test/livewire/message/...`, but what is interesting is that if i look into variable value i get a right value with special chars. So i think it will be only something with the nonending requests. 

### Stripped-down, copy-pastable code snippets
There is no needed so long code to show. Just try in blade component add this into <script></script>
`@this.set('variable', 'žžž');`

**Context**
- Livewire version: [2.3.6]
- Laravel version: [8.3.1]
- Alpine version: [2.3.0]
- Browser: [Chrome, Firefox]

**Comment by altercode** [comment]
I have the same problem!

**Comment by crrack** [comment]
Only wire:model works. @entangle and wire:click with calling function do it too :/

**Comment by altercode** [comment]
This one works for me. Add third parameter to set function that indicates to defer the request. But you will lost reactivity with this field.

`@this.set('variable', 'žžž', true);`

**Comment by jskorlol** [comment]
$wire.emitSelf('addShopping','한글'); :: No problem
$wire.call('addShopping','한글'); :: Same error occurred

**Comment by wrabit** [comment]
Also getting this

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
This should be fixed now, THANK!
