### ISSUE TITLE
lssuse When Back To Previous Page

### ISSUE THREAD

**Issue by mohammadmahdi04** [livewire/livewire#2394]
Hi 
I Have Some Pages With Livewire
For Example :
In Blog List Page When I Click On A blog , Page Will Move To Single Blog Page
After That When I Back To Previous Page(Blog List Page) Livewire Dosen't Working!!!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
