### ISSUE TITLE
X-Amz-Expires must be non-negative while file upload since 2.3.7

### ISSUE THREAD

**Issue by stefro** [livewire/livewire#2395]
### Description
I've upgraded from Livewire 2.3.6 to 2.3.7 (also tried to 2.3.8, same result).
My file upload (to S3) suddenly stopped working. When I open de network tab in my browser I can this request with a 400 status:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AuthorizationQueryParametersError</Code>
    <Message>X-Amz-Expires must be non-negative</Message>
    <RequestId>784898D8C4E388F4</RequestId>
    <HostId>vPRsnfz9YMKe0FXpF4Nk513SP4VNff8hszxRdZArjhXrZM2k2p6QdyfXM1vT1t4Pwtfu8dKOEwY=</HostId>
</Error>
```
When I go back to Livewire 2.3.5 it works.

### Exact steps to reproduce
In my blade file I've stripped down all fancy styling stuff to a bare minimum:
```html
<input type="file" id="newImage" name="newImage" wire:model="newImage">
```
### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.6
- Laravel version:8.24.0
- Alpine version: 2.3.5
- Browser: Safari & Chrome

**Comment by tarikhagustia** [comment]
same result

**Comment by eqxDev** [comment]
Same issue here

**Comment by heruputra** [comment]
[This addition](https://github.com/livewire/livewire/commit/ca2ca53963de5574271af08021f329f44a1cae07) to the config file need to be added manually to your config file.

Looks like an undocumented breaking changes.

**Comment by felixsc** [comment]
> [This addition](https://github.com/livewire/livewire/commit/ca2ca53963de5574271af08021f329f44a1cae07) to the config file need to be added manually to your config file.
> 
> Looks like an undocumented breaking changes.

Fixed it for me! Thank you @heruputra

**Comment by stefro** [comment]
> [This addition](https://github.com/livewire/livewire/commit/ca2ca53963de5574271af08021f329f44a1cae07) to the config file need to be added manually to your config file.
> 
> Looks like an undocumented breaking changes.

Works for me too! Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by StephenGillCoop** [comment]
@calebporzio I think this is worth highlighting to others if there's a way to do that - I spent all afternoon on this, was getting 400 errors from S3 in the console and only discovered this was the problem when testing the signed URL via POSTMAN which brought me here.

**Comment by joshhanley** [comment]
I believe this was an unintentional breaking change.

I've submitted a PR #2413 that fixes this issue. It should have fallen back to a default if the config option was missing, but it wasn't.

Hope this helps!
