### ISSUE TITLE
Route model binding for actions not working with custom bindings

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#2402]
### Description
Since this PR https://github.com/livewire/livewire/pull/1142 we can do this:
```php
public function showPost(Post $post)
```
and it will fetch the post model for you. In a normal Laravel app you can also create custom bindings in `RouteServiceProvider` like this:
```php
$this->bind('postBySlug', function($slug) {
    return Post::whereSlug($slug)->firstOrFail();
});
```
and use `Route::get('post/{postBySlug}', function(Post $postBySlug))` to retrieve the post with the custom binding, but you can't currently do this in livewire.

### Steps to reproduce
- Add a custom binding in `RouteServiceProvider`
- Try to retrieve the model using the same variable name you bound in your provider

**Context**
Latest version of everything

**Comment by wrabit** [comment]
I've read somewhere that only the mount() can pick up route bound models.

**Comment by mokhosh** [comment]
That might have been the case in some version. But I'm pretty sure you can inject models and services with any method right now.

**Comment by calebporzio** [comment]
Mmm interesting. Yeah, I don't think non-mount methods support custom bindings.

Going to close this until there is more demand for it. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment]
@calebporzio I would be happy to work on it and submit a PR if you could give me a little direction.

**Comment by calebporzio** [comment]
Thanks for offering, but I'm going to pass until others voice a need for it. Thanks though!

**Comment by hxnk** [comment]
@calebporzio: I believe the need is voiced ;)

See #2508
