### ISSUE TITLE
How a public property, which is defined in a trait, and used in a component can be passed to a nested component which is using the same trait?

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2407]
### Description
How an array of selected users assigned to a public property i.e. `$selected = []`, which is defined in a trait i.e. `WithBulkActions` and used in the component i.e. `UserController`, can be passed to a nested component i.e. `UserBulkDeletion` which is using the same trait i.e. `WithBulkActions`?

[![1]][1]

### Application structure
1. **App\Http\Livewire**
    - *Component*
        * UserController - App/Http/Livewire/Backend/UserManagement/UserController
        * UserBulkDeletion - App/Http/Livewire/Backend/UserManagement/LogicalComponent/UserBulkDeletion
    - *Trait*
        * WithBulkActions - App/Http/Livewire/Traits/WithBulkActions

### Stripped-down, copy-pastable code snippets
* UserController
```
class UserController extends Component
{
    use WithCachedRows, WithSorting, WithBulkActions, WithPerPagePagination;

    public User $user;
    public $showFilters = false;
    public $filters = [
        'search' => "",
        'email' => null,
        'role' => '',
        'date-min' => null,
        'date-max' => null,
    ];

    protected $listeners = ['sectionRefresh' => '$refresh'];

    public function toggleShowFilters()
    {
        $this->useCachedRows();

        $this->showFilters = ! $this->showFilters;
    }

    public function resetFilters() 
    {
        $this->reset('filters'); 
    }

    public function updatedFilters() 
    {
        $this->resetPage();
    }
    
    public function getRowsQueryProperty()
    {
        $query = User::query()
            ->when($this->filters['email'], fn($query, $email) => $query->where('email', 'like', '%'.$email.'%'))
            ->when($this->filters['role'], fn($query, $role) => $query->whereHas('roles', fn ($query) => $query->where('id', $role)))
            ->when($this->filters['search'], fn($query, $search) => $query->where('name', 'like', '%'.$search.'%'))
            ->when($this->filters['date-min'], fn($query, $created_at) => $query->where('created_at', '>=', Carbon::createFromFormat('d/m/Y', $created_at)))
            ->when($this->filters['date-max'], fn($query, $created_at) => $query->where('created_at', '<=', Carbon::createFromFormat('d/m/Y', $created_at)));
        
        return $this->applySorting($query);
    }

    public function getRowsProperty()
    {
        return $this->cache(function () {
            return $this->applyPagination($this->rowsQuery);
        });
    }

    public function getRolesProperty()
    {
        $roles = Role::all();
        return $roles;
    }
    
    public function render()
    {
        return view('livewire.backend.management.audience-management.user-controller', ['users' => $this->rows, 'roles' => $this->roles]);
    }
}
```

* UserBulkDeletion
```
class UserBulkDeletion extends Component
{
    use WithCachedRows, WithBulkActions, WithSorting;
    
    public $showUserBulkDeletionModal = false;
    public User $user;
    public $filters = [
        'search' => "",
        'email' => null,
        'role' => '',
        'date-min' => null,
        'date-max' => null,
    ];

    protected $listeners = ['deleteUserBulk'];

    public function deleteUserBulk()
    {
        $this->useCachedRows();

        $this->showUserBulkDeletionModal = true;
    }

    public function confirmDeleteBulk()
    {
        $deleteCount = $this->selectedRowsQuery->count();
        
        foreach ($this->selectedRowsQuery->get() as $queryRow) {
            $queryRow->roles()->detach();
        }

        $this->selectedRowsQuery->delete();
        $this->showUserBulkDeletionModal = false;

        $this->notify('You\'ve deleted '.$deleteCount.' users');
        $this->emit('sectionRefresh');
    }

    public function getRowsQueryProperty()
    {
        $query = User::query()
            ->when($this->filters['email'], fn($query, $email) => $query->where('email', 'like', '%'.$email.'%'))
            ->when($this->filters['role'], fn($query, $role) => $query->whereHas('roles', fn ($query) => $query->where('id', $role)))
            ->when($this->filters['search'], fn($query, $search) => $query->where('name', 'like', '%'.$search.'%'))
            ->when($this->filters['date-min'], fn($query, $created_at) => $query->where('created_at', '>=', Carbon::createFromFormat('d/m/Y', $created_at)))
            ->when($this->filters['date-max'], fn($query, $created_at) => $query->where('created_at', '<=', Carbon::createFromFormat('d/m/Y', $created_at)));
        
        return $this->applySorting($query);
    }

    public function render()
    {
        return view('livewire.backend.management.audience-management.logical-component.user-bulk-deletion');
    }
}
```

* WithBulkActions
```
trait WithBulkActions
{
    public $selectPage = false;
    public $selectAll = false;
    public $selected = [];

    public function renderingWithBulkActions()
    {
        if ($this->selectAll) $this->selectPageRows();
    }

    public function updatedSelected()
    {
        $this->selectAll = false;
        $this->selectPage = false;
    }

    public function updatedSelectPage($value)
    {
        if ($value) return $this->selectPageRows();

        $this->selectAll = false;
        $this->selected = [];
    }

    public function selectPageRows()
    {
        $this->selected = $this->rows->pluck('id')->map(fn($id) => (string) $id);
    }

    public function selectAll()
    {
        $this->selectAll = true;
    }

    public function getSelectedRowsQueryProperty()
    {
        return (clone $this->rowsQuery)
            ->unless($this->selectAll, fn($query) => $query->whereKey($this->selected));
    }
}
```

### Context
- Livewire version: 2.3.8
- Laravel version: 8.24.0
- Alpine version: 2.8.0
- Browser: Chrome

  [1]: https://i.stack.imgur.com/eCxke.gif

**Comment by wrabit** [comment]
Why does UserBulkDeletion need to be concerned with so much? Its job is to just confirm and carry out the delete. Surely it just needs the user ID's to delete, which could be passed in as a property like `:users-to-delete="$selected"` as an array. I think the child component will need to re-render when receiving new props so make sure the key updates on each add / remove. ie `:key="count($selected)"`

**Comment by toxifiedmatrix** [comment]
@wrabit I am trying to make everything look alike and structure accordingly. I have already added `:selected="$selected"` and also added `:key="count($selected)"` to the component. Then added mount() lifecycle hook to the `UserBulkDeletion` component. Still the output is the same. Please help me here, I am trying to make it work, but its of no use.

- resources/views/livewire/user-management/user-controller
```
<div class="space-x-4 flex items-center">
    <x-dropdown label="Bulk Actions">
        <x-dropdown.item type="button" wire:click="$emit('deleteUserBulk')" class="flex items-center space-x-2">
            <x-icon.trash class="text-cool-gray-400" /> <span>Delete</span>
        </x-dropdown.item>
    </x-dropdown>
</div>

@push('modals')
<!-- Delete User Bulk Modal -->
<livewire:backend.management.audience-management.logical-component.user-bulk-deletion :selected="$selected" :key="count($selected)" />
@endpush
```

- App/Http/Livewire/Backend/UserManagement/LogicalComponent/UserBulkDeletion
```
    public function mount($selected)
    {
        $this->selected = $selected;
    }
```

**Comment by toxifiedmatrix** [comment]
@joshhanley Mate, can you throw some light on this? Its a bug I think as the data isn't being passed to the 2nd component.

**Comment by joshhanley** [comment]
@toxifiedmatrix it was hard to tell just from the component files alone, but looking at your blade snippet above, you will find it's because you are pushing the child component to the modals stack. I'm assuming your modal stack is at the bottom of your app layout, which puts it outside of the parent Livewire component in the DOM, so it won't have access to the parent state.

You will need to make sure that the child Livewire component stays inside of the parent's html.

I personally probably wouldn't have the UserBulkDeletion as it's own component, instead I'd just have it as trait on your users component.

Hope this helps!

**Comment by toxifiedmatrix** [comment]
@joshhanley Okay, that's the reason, but I tried as per you said.

- I'm emitting the event `deleteBulkUser` to display the child component i.e. `UserBulkDeletion`.
```
<x-dropdown.item type="button" wire:click="$emit('deleteUserBulk')" class="flex items-center space-x-2">
    <x-icon.trash class="text-cool-gray-400"/> <span>Delete</span>
</x-dropdown.item>
``` 

- Shifted the child livewire component from modals stack to the parent's html.
```
<livewire:backend.management.audience-management.logical-component.user-bulk-deletion :selected="$selected" />
```

- Added mount method to the child component.
```
public function mount($selected)
{
    $this->selected = $selected;
}
```

Still it isn't passing the `$selected` array from the parent component to the child component. What can be the issue, please help me as I have been trying to figure this out since 2 weeks straight. Thanks for your time! 😃

**Comment by toxifiedmatrix** [comment]
It started working when I added `:key="count($selected)"` to the child component.

**Comment by joshhanley** [comment]
@toxifiedmatrix hmm ok that sounds better, maybe the key isn't triggering morphdom to remove and re-add the child component, as count just returns an integer and probably isn't unique enough.

I've had success in the past with making a public prop for the key, say `childKey`, and populating it with `uniqid()` on load `$this->childKey = uniqid();`

Then whenever your selected list changes, update the key prop with a new `uniqid()`, so that way it forces the child prop to evaluate fresh. So the key on the child component would look like `:key="$this->childKey"`

If you use discord, can I suggest jumping on the Livewire discord, as we can work through the issue quicker https://discord.gg/livewire

Hope this helps!

**Comment by toxifiedmatrix** [comment]
Okay I'll start using discord, as of now that's a nice way to implement it. I will surely give it a try and what about `:key="base64_encode(count($selected))"` as this works seamlessly. The way I did above, It isn't resource intensive, right? Because I want to keep the application as light and as fast as possible.

**Comment by joshhanley** [comment]
@toxifiedmatrix base64 might work but it may run into the same issues as using count as there's not guarantee it will be unique.

For example your count might be `3` so it encodes it to `Mw==`, then count might change to `4` which encodes to `NA==`. But when your count goes back to `3` again, it again encodes it to `Mw==`, which is a previously used key and therefore not unique, so could cause problems, as you may have 3 different items selected than the first time.

By using `uniqid()` each time a change happens it ensures it is a new unique key each time.

I'm not sure what you mean by:
> The way I did above, It isn't resource intensive, right? Because I want to keep the application as light and as fast as possible.

If you're talking about having the bulk delete component. I'd argue that's adding overhead as you now have to deal with communication between components, which will be marginally slower, plus theres a technical overhead where developers looking at that have to look at multiple components to understand what's going on plus understand how the communication between them works (not to mention the key hack we have been talking about to regenerate the child component), which to me is all heavier rather than lighter.

**Comment by toxifiedmatrix** [comment]
@joshhanley Okay, I see, thanks alot mate, it was pretty descriptive. I will rather shift to `uniqid()` method.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
