### ISSUE TITLE
Getting error "Undefined offset: 0" when de-selecting select all.

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2410]
### Description
When I am de-selecting the data by using select all checkbox i.e. `$selectPage`, its throwing me the following error. 

> ErrorException
Undefined offset: 0 (View: C:\xampp\htdocs\Management\resources\views\livewire\backend\management\audience-management\user-controller.blade.php)

![Select All Undefined](https://user-images.githubusercontent.com/65024122/105870482-54079300-601e-11eb-80d4-fa3c24712c98.gif)

### Stripped-down, copy-pastable code snippets
- Livewire/Traits/WithBulkActions
```
trait WithBulkActions
{
    public $selectPage = false;
    public $selectAll = false;
    public $selected = [];
    
    public function renderingWithBulkActions()
    {
        if ($this->selectAll) $this->selectPageRows();
    }
    
    public function updatedSelected()
    {
        $this->selectAll = false;
        $this->selectPage = false;
    }
    
    public function updatedSelectPage($value)
    {
        if ($value) return $this->selectPageRows();
    
        $this->selected = [];
    }
    
    public function selectPageRows()
    {
        $this->selected = $this->rows->pluck('id')->map(fn($id) => (string) $id);
    }
    
    public function selectAll()
    {
        $this->selectAll = true;
    }
    
    public function getSelectedRowsQuery()
    {
        return (clone $this->rowsQuery)
            ->unless($this->selectAll, fn($query) => $query->whereKey($this->selected));
    }
}
```

- view/livewire/user-management/user-controller
```
<x-table>
    <x-slot name="head">
        <x-table.heading class="pr-0 w-8">
            <x-input.checkbox wire:model="selectPage" />
        </x-table.heading>
    </x-slot>
    <x-slot name="body">
        @forelse($users as $key => $user)
        <x-table.row wire:key="row-{{ $user->id }}" wire:loading.class.delay="opacity-50">
            <x-table.cell class="pr-0">
                <x-input.checkbox wire:model="selected" value="{{ $user->id }}" />
            </x-table.cell>
        </x-table.row>
        @endforelse
    </x-slot>
</x-table>
```

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.24.0
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
