### ISSUE TITLE
Emitting an event beforeunload

### ISSUE THREAD

**Issue by redbastie** [livewire/livewire#2414]
I'm getting this error:

> Fetch API cannot load http://dio-ccg.test/livewire/message/partials.play due to access control checks.

Here is my JS:

    window.addEventListener('beforeunload', () => {
      console.log('leaveGameQueue');
      Livewire.emit('leaveGameQueue');
    });

Here is my component:

    class Play extends Component
    {
        public function getListeners()
        {
            return [
                'leaveGameQueue',
            ];
        }
  
        public function render()
        {
            return view('livewire.partials.play');
        }
  
        public function leaveGameQueue()
        {
            Auth::user()->gameQueue()->delete();
        }
    }

Is it possible to emit an event `beforeunload`? In this example, I'm making a simple game, and the user can "queue up" for matchmaking. When the person leaves the page, it should automatically remove them from the queue.

I just want to emit that event when they leave the page.

**Comment by redbastie** [comment]
Looks like this only happens in Safari. Chrome is working fine. :/

**Comment by calebporzio** [comment]
Because `Livewire.emit()` will submit an AJAX request for the listening Livewire components, this is not ideal.

"beforeunload" and "unload" event listeners should not be used for sending ajax requests.

The "Beacon" API is intended for cases like these.

I'm not sure how this fits into Livewire exactly, but I'd recommend reading up on the "send beacon" functionality here: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

Then maybe handle this behavior in a normal request outside of a Livewire component. Not really sure tbh.

Going to close this issue, but please report your findings here for others to reference.

Thanks!

**Comment by joshhanley** [comment]
Closing this as per Caleb's comment above 🙂

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by 27pchrisl** [comment]
REOPEN

Reopened for feedback on #2439

**Comment by 27pchrisl** [comment]
REOPEN

**Comment by 27pchrisl** [comment]
Reopened for feedback on #2439

**Comment by 27pchrisl** [comment]
Fixed the tests on that PR, hadn't realised you needed to commit a build.

**Comment by calebporzio** [comment]
Closing this as something that is better left to user-land implementations until there is greater demand. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
