### ISSUE TITLE
Docs: Usage of inline script WITH Alpine.js

### ISSUE THREAD

**Issue by SwiTool** [livewire/livewire#2416]
### Description

As seen [here](https://laravel-livewire.com/docs/2.x/inline-scripts), the usage of inline scripts is pretty straightforward.

But as we can see in the [Alpine.js section](https://laravel-livewire.com/docs/2.x/alpine-js), under the `Color-picker Blade Component Definition` section, the code looks like this :

```html
<div
    x-data="{ color: '#ffffff' }"
    x-init="
        // Wire up to show the picker when clicking the 'Change' button.
        picker = new Picker($refs.button);
        // Run this callback every time a new color is picked.
        picker.onDone = rawColor => {
            // Set the Alpine 'color' property.
            color = rawColor.hex;
            // Dispatch the color property for 'wire:model' to pick up.
            $dispatch('input', color)
        }
    "
    // Vanilla Picker will attach its own DOM inside this element, so we need to
    // add `wire:ignore` to tell Livewire to skip DOM-diffing for it.
    wire:ignore
    // Forward the any attributes added to the component tag like `wire:model=color`
    {{ $attributes }}
>
    <!-- components HTML -->
</div>
```

Is it possible to use inline scripts with Alpine.JS ? Indeed when the content of the `x-data` property is not "as simple" as that, writing the code inside quotes is overkill and unconvenient.

### Stripped-down, copy-pastable code snippets

```html
<div>
    <div x-data="myFunc()" x-init="init()"></div>

    <script>
        function myFunc() {
            return {
                init: () => console.log('init')
            }
        }
    </script>
</div>
```

`Uncaught ReferenceError: myFunc is not defined`

**Context**
- Livewire version: 2.3.6
- Laravel version: 8.22.1
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by SwiTool** [comment]
I should have looked in [the docs of Alpine.JS](https://github.com/alpinejs/alpine#x-data) : 

> For bundler users, note that Alpine.js accesses functions that are in the global scope (window), you'll need to explicitly assign your functions to window in order to use them with x-data for example window.dropdown = function () {} (this is because with Webpack, Rollup, Parcel etc. function's you define will default to the module's scope not window).

```html
<div>
    <div x-data="myFunc()" x-init="init"></div>

    <script>
        window.myFunc = function() {
            return {
                init: () => console.log('init')
            }
        }
    </script>
</div>
```

works fine.

Hope it helps anybody.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@SwiTool your first example should work if it's an inline script (see my screenshot below), the window assignment is only necessary if you are wanting your function to be bundled with your assests (like app.js).

![image](https://user-images.githubusercontent.com/882837/106054803-a4771180-6140-11eb-9959-1ea5968be336.png)

**Comment by SwiTool** [comment]
@joshhanley Yes in your case it works because your script is loaded with the window I guess. But in my case, I have a multi-step form, and it seemed not to work until I put the `myFunc` in the window scope.

**Comment by SwiTool** [comment]
I managed to make it work by putting all the scripts on the main component file (add.blade.php)

and by adding this :
```js
Livewire.on('cancellation.step6', () => {
    Alpine.initializeComponent(document.getElementById('cancellation-payment'))
})
Livewire.on('cancellation.step7', () => {
    Alpine.initializeComponent(document.getElementById('cancellation-payment-3d-secure'))
})
```

and on Component side:
```php
    public function updatedStep()
    {
        $this->emit("cancellation.step{$this->step}");
    }
```
