### ISSUE TITLE
When the select all checkbox is checked, why the span breaks when the per page value changes?

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2418]
### Description
I have been implementing Livewire's screencast to make data table with bulk actions capability. As when the application loads, default per page is set to 10. As I go forward by selecting the rows visible, by checking the select all checkbox. It shows me a notification showing `You have selected 10 users, do you want to select all 12? Select All`. At this time when I change the per page value from 10 to 25 then back to 10 the notification which was being displayed before breaks into `You have selected 1012? Select All`. What can be causing this sort of error?

### Exact steps to reproduce
![Select All Notification](https://user-images.githubusercontent.com/65024122/106041799-49262e80-6102-11eb-88be-ce504895aed5.gif)

### Stripped-down, copy-pastable code snippets
- views/livewire/user-controller
```
@if ($selectPage)
<x-table.row class="bg-cool-gray-200" wire:key="row-message">
    <x-table.cell colspan="7">
        @unless ($selectAll)
        <div>
            <span>You have selected <strong>{{ $users->count() }}</strong> users, do you want to select all <strong>{{ $users->total() }}</strong>?</span>
            <x-button.link wire:click="selectAll" class="ml-1 text-blue-600">Select All</x-button.link>
        </div>
        @else
        <div>
            <span>You are currently selecting all <strong>{{ $users->total() }}</strong> users.</span>
        </div>
        @endif
    </x-table.cell>
</x-table.row>
@endif
```

- Livewire/Traits/WithBulkActions
```
trait WithBulkActions
{
    public $selectPage = false;
    public $selectAll = false;
    public $selected = [];

    public function renderingWithBulkActions()
    {
        if ($this->selectAll) $this->selectPageRows();
    }

    public function updatedSelected()
    {
        $this->selectAll = false;
        $this->selectPage = false;
    }

    public function updatedSelectPage($value)
    {
        if ($value) return $this->selectPageRows();

        $this->selectAll = false;
        $this->selected = [];
    }

    public function selectPageRows()
    {
        $this->selected = $this->rows->pluck('id')->map(fn($id) => (string) $id);
    }

    public function selectAll()
    {
        $this->selectAll = true;
    }

    public function getSelectedRowsQueryProperty()
    {
        return (clone $this->rowsQuery)
            ->unless($this->selectAll, fn($query) => $query->whereKey($this->selected));
    }
}
```

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.25.0
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by raliqala** [comment]
you still need help with this issue?
