### ISSUE TITLE
Query strings not working in Microsoft Edge 44 (non-Chrome) 

### ISSUE THREAD

**Issue by almazdanilov** [livewire/livewire#2420]
### Description
Sometimes it's useful to update the browser's query string when your component state changes.
For example, if you were building a "search posts" component, and wanted the query string to reflect the current search value like so: https://your-app.com/search-posts?search=some-search-string
But on Microsoft Edge 44 we have:
https://your-app.com/undefined
Pagination also doesn't work because it uses query string to mark current position.
Even more, it is not just not working, but also overrides route history and makes website use impossible.

### Exact steps to reproduce
Create livewire component and add to it's class
`protected $queryString = ['search'];`
or
`use WithPagination;`
After that put this component to view and attach that view to 'search-posts' route.
Running your site in Edge 44 will not be as expected 
https://your-app.com/search-posts?search=some-search-string
It will overwrite your current route like so:
https://your-app.com/undefined

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.25.0
- Browser: Microsoft Edge 44

**Comment by austenc** [comment]
I suspect this might be a bug in that version of Edge. @almazdanilov is it possible you could test with prior Edge versions?

Did you get any javascript console errors when testing this?

Unfortunately I can't find a public bug tracker for Edge, the best I found was that [they're working on it](https://twitter.com/MSEdgeMissy/status/1276545933367406592?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1276545933367406592%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Ftechdows.com%2F2020%2F07%2Fmicrosoft-edge-public-issue-tracker.html)

**Comment by almazdanilov** [comment]
Yes indeed. It's a bug of Edge 44. Older IE11 doesn't have this problem. I thought that it will be easy to make some kind of patch for Edge. But at this time I've solved problem by updating user's web browser. I suppose that there will be no other users with such browser anymore.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
