### ISSUE TITLE
v2.3.7 breaks file uploads to S3

### ISSUE THREAD

**Issue by SebastianSchoeps** [livewire/livewire#2422]
### Description
https://github.com/livewire/livewire/pull/2347 introduced a new config parameter `livewire.temporary_file_upload.max_upload_time`. However, if this parameter is not set in the configuration file (that's the case when you update from 2.3.6), file uploads to S3 do not work anymore (at least for me).
That's because the header `X-Amz-Expires` of the upload request to S3 is set to a negative value.

### Exact steps to reproduce
Any upload for me.

### Solution
Add the config parameter to your config. 
```
'temporary_file_upload' => [
        'disk' => 's3',        // Example: 'local', 's3'              Default: 'default'
        [...]
        'max_upload_time' => 5
    ],
```

`X-Amz-Expires` is than correctly set to e.g. 5 * 60 = 300.

**Context**
- Livewire version: 2.3.7+

@FrancisMawn Is that only for me? Strange.

**Comment by SebastianSchoeps** [comment]
Just realized that there is already a PR that fixes this: https://github.com/livewire/livewire/pull/2413

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Closing because I merged the fix PR
