### ISSUE TITLE
Why mount lifecycle hook has been mounting all the rows with its 'id' which has been selected and has ever been passed to the child component?

### ISSUE THREAD

**Issue by toxifiedmatrix** [livewire/livewire#2423]
### Description
I have two components, one parent and one child. I am passing the `id` of number of rows selected from the parent component to the child component. And in the child component I am using `mount()` lifecycle hook to pass the selected ids to the child component and later on display the confirmation modal to delete the number of rows selected.

At first when the parent component renders for the first time along with the child component, I select the rows and pass it to the child component. The child component is a modal, which asks the user to confirm the action and delete the selected number of rows with the passed `id`.

The problem is even after I delete the selected number of rows when the component loads for the first time. The selected number of rows with their `id` which were deleted are still mounted to the component, even after being deleted. How can I overcome this issue, please help me?

### Exact steps to reproduce
[![enter image description here][1]][1]

### Stripped-down, copy-pastable code snippets
- Livewire/Traits/WithBulkActions
```
trait WithBulkActions
{
    public $selectPage = false;
    public $selectAll = false;
    public $selected = [];

    public function renderingWithBulkActions()
    {
        if ($this->selectAll) $this->selectPageRows();
    }

    public function updatedSelected()
    {
        $this->selectAll = false;
        $this->selectPage = false;
    }

    public function updatedSelectPage($value)
    {
        if ($value) return $this->selectPageRows();

        $this->selectAll = false;
        $this->selected = [];
    }

    public function selectPageRows()
    {
        $this->selected = $this->rows->pluck('id')->map(fn($id) => (string) $id);
    }

    public function selectAll()
    {
        $this->selectAll = true;
    }

    public function getSelectedRowsQueryProperty()
    {
        return (clone $this->rowsQuery)
            ->unless($this->selectAll, fn($query) => $query->whereKey($this->selected));
    }
}
```

- Livewire/ChildComponent
```
class UserBulkDeletion extends Component
{
    use WithCachedRows, WithSorting, WithBulkActions, WithPerPagePagination;
    
    public User $user;
    public $showUserBulkDeletionModal = false;
    public $filters = [
        'search' => "",
        'email' => null,
        'role' => '',
        'date-min' => null,
        'date-max' => null,
    ];

    protected $listeners = ['deleteUserBulk'];

    public function mount($selected)
    {
        $this->selected = $selected;
    }

    public function deleteUserBulk()
    {
        $this->useCachedRows();

        $this->showUserBulkDeletionModal = true;
    }

    public function confirmDeleteBulk()
    {
        $deleteCount = $this->selectedRowsQuery->count();

        $this->selectedRowsQuery->delete();
        $this->showUserBulkDeletionModal = false;

        $this->notify(($deleteCount <= 1) ? 'You\'ve deleted '.$deleteCount.' user' : 'You\'ve deleted '.$deleteCount.' users');
        $this->emit('sectionRefresh');
    }

    public function getRowsQueryProperty()
    {
        $query = User::query()
            ->select('id')
            ->when($this->filters['search'], fn($query, $search) => $query->where('name', 'like', '%'.$search.'%'))
            ->when($this->filters['email'], fn($query, $email) => $query->where('email', 'like', '%'.$email.'%'))
            ->when($this->filters['role'], fn($query, $role) => $query->where('role_id', $role))
            ->when($this->filters['date-min'], fn($query, $created_at) => $query->where('created_at', '>=', Carbon::createFromFormat('d/m/Y', $created_at)))
            ->when($this->filters['date-max'], fn($query, $created_at) => $query->where('created_at', '<=', Carbon::createFromFormat('d/m/Y', $created_at)));
        
        return $this->applySorting($query);
    }

    public function getRowsProperty()
    {
        return $this->cache(function () {
            return $this->applyPagination($this->rowsQuery);
        });
    }

    public function render()
    {
        return view('livewire.backend.management.audience-management.logical-component.user-bulk-deletion', ['users' => $this->rows]);
    }
}
```

- ParentComponent Blade
```
@if ($selected)
<x-dropdown label="Bulk Actions">
    <x-dropdown.item type="button" wire:click="$emit('deleteUserBulk')" class="flex items-center space-x-2">
        <x-icon.trash class="text-cool-gray-400"/> <span>Delete</span>
    </x-dropdown.item>
</x-dropdown>
@endif
```

- ChildComponent Blade
```
<div>
    <form wire:submit.prevent="confirmDeleteBulk">
        <x-modal.confirmation wire:model.defer="showUserBulkDeletionModal">
            <x-slot name="title">Delete User</x-slot>

            <x-slot name="content">
                @json($selected)
                Are you sure you want to delete users? This action is irreversible!
            </x-slot>

            <x-slot name="footer">
                <x-button.secondary wire:click="$set('showUserBulkDeletionModal', false)">Cancel</x-button.primary>

                <x-button.primary type="submit">Delete</x-button.primary>
            </x-slot>
        </x-modal.confirmation>
    </form>
</div>
```

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.25.0
- Alpine version: 2.8.0
- Browser: Chrome

[1]: https://i.stack.imgur.com/aQdGa.gif

**Comment by AbdelrahmanIbrahim447** [comment]
I think you need to reset the $selected variable in Livewire/Traits/WithBulkActions to make it empty after deleting the rows instead of adding more ids to it.

**Comment by toxifiedmatrix** [comment]
@AbdelrahmanIbrahim447 I tried calling `$this->reset('selected');` in public function `confirmDeleteBulk()`, but was unable to reset it. How can I put that logic in the trait, as the trait is responsible to select multiple items and child component is responsible to execute the `delete` method.

**Comment by AbdelrahmanIbrahim447** [comment]
@toxifiedmatrix  
You may declare resetSelected function on the WithBulkActions trait and call it on the child component in the delete method.

**Comment by toxifiedmatrix** [comment]
I tried that, its still the same thing. I am just ain't able to find the solution to this problem. Would you mind looking at my ParentComponent as well, as I am using the same trait `WithBulkActions` within the ParentComponent as well as ChildComponent, and pass an array of data within `selected` variable which is defined in the trait, and pass it to the ChildComponent.

![Child Mount error](https://user-images.githubusercontent.com/65024122/106327618-727ec000-62a4-11eb-985e-44f923f2b7e9.gif)

- WithBulkActions
```
    public function resetSelected()
    {
        $this->selected = [];
    }
```

- ChildComponent
```
    public function confirmDeleteBulk()
    {
        $deleteCount = $this->selectedRowsQuery->count();

        $this->selectedRowsQuery->delete();
        $this->showUserBulkDeletionModal = false;
        $this->resetSelected();

        $this->notify(($deleteCount <= 1) ? 'You\'ve deleted '.$deleteCount.' user' : 'You\'ve deleted '.$deleteCount.' users');
        $this->emit('sectionRefresh');
    }
```

**Comment by toxifiedmatrix** [comment]
@joshhanley Hey bro, can you please have a look to this, as you have already seen my controllers. According to you its better to use `confirmDeleteBulk` public function in the traits itself, but in this case I have maintained separated components with their separate logic, please have a look why such kind of behavior is happening, is it a bug or is this the way it works?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
