### ISSUE TITLE
Tests fail on missing attributes

### ISSUE THREAD

**Issue by ju5t** [livewire/livewire#2429]
### Description

Testing one of our components doesn't work as expected. It's best illustrated with an example.

```php
Livewire::actingAs($user)
    ->test(Administrators::class, ['editing', $admin])
    ->set('editing.disabled', 1)
    ->call('save');

$admin->refresh();

$this->assertTrue($admin->disabled === 1);
```

`editing` is a public property in our component that we use. The `$admin` object is a an existing admin user with the property `disabled` set to 0. We want to explicitly test that we can change this property.

This test fails as disabled is still set to 0. The reason for this is that our validation fails. For example, we have a rule that validates the email address. This fails even though the `$admin` has a valid email address.

Would `test(Administrators::class, ['editing', $admin])` make sure `editing` is set? Because it seems like it isn't?

**Context**
- Livewire version: 2.3.8
- Laravel version: 8
- Alpine version: 2.7.3

**Comment by austenc** [comment]
@ju5t Could you provide more context please? Without seeing your component and blade view, we have to make too many assumptions when trying to reproduce this. 

Thanks!

**Comment by ju5t** [comment]
@austenc I initially thought that posting parts of the component wouldn't be necessary as I thought it wouldn't be related. I had copied extensive parts of the component in this reply when it suddenly clicked. Yea, assumptions. I know.

We use the `mount()` method to set up `$editing` but as this component can edit multiple items, we set it using `edit(User $user)`. This means I shouldn't use 

```php
['editing', $admin])
``` 

In the `test` method, but

```php
->call('edit', $admin)
```

 instead.

It all works now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by austenc** [comment]
Thanks for following up and closing the issue! 🤝
