### ISSUE TITLE
Using abort(403) in mount()

### ISSUE THREAD

**Issue by evergreenwebsystems** [livewire/livewire#243]
Previously I used to be able to use ```abort(403)``` in a mount function. Since upgrading recently to 0.3.3 it no longer works.

I just see the following error:
![image](https://user-images.githubusercontent.com/8020291/64458919-ec823800-d0f6-11e9-97bf-eb294b9467e2.png)

Should I be able to do this or not?
```php
    public function mount()
    {
        abort(403);
    }
```

**Comment by evergreenwebsystems** [comment]
It definitely is not working for me. I have updated Livewire to 0.3.14 and using the basic counter example I simply add:

```
    public function mount()
    {
        abort(403);
    }
```

I don't understand why this won't work? It used to work in previous versions of Livewire. @calebporzio  are you able to tell me why this wont work and what I should do instead if I want to use this method?

**Comment by calebporzio** [comment]
It's currently working for me locally. Here is the bit of code that makes this possible:

https://github.com/livewire/livewire/blob/3e91c0fcd41c7bee85be44563376b44033b92d70/src/LivewireServiceProvider.php#L49

The problem has something to do with that not working properly.

For some reason, the override isn't being applied.

Maybe there is a package that presents a conflict or something.

If someone who is experiencing the issue could dig deeper, it would be a big help.

Thanks.

**Comment by evergreenwebsystems** [comment]
So I created a clean install of Laravel 6.0.4 and added only Livewire, no other packages. As per my earlier example I use the counter example and simply added:

```php
    public function mount()
    {
        abort(403);
    }
```

Again, I get the exact same error response.

**Comment by dylanmichaelryan** [comment]
Still not working for me

**Comment by lancepioch** [comment]
Just tested that this works correctly with the following steps:

1. Install Laravel: `composer create-project --prefer-dist laravel/laravel lw`
2. Install Livewire: `composer require livewire/livewire`
3. Install UI: `composer require laravel/ui --dev`
4. Generate UI: `php artisan ui vue --auth`
5. Generate LW Component: `php artisan make:livewire foo`
6. Content of LW Component (App\Http\Livewire\Foo):

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Foo extends Component
{
    public function render()
    {
        return view('livewire.foo');
    }

    public function mount()
    {
        abort(403);
    }
}
```

Success!

**Comment by calebporzio** [comment]
Thanks @lancepioch !
