### ISSUE TITLE
Dynamically changing Laravel Echo channel listeners doesn't work

### ISSUE THREAD

**Issue by waterbuckit** [livewire/livewire#2432]
### Description
If for example, you want to switch between a set of channels all matched by an ID, for example : `channel.{$channel_id}`, using getListeners(), it will not switch to the other channels, it seems only to care about listening on the first call over the getListeners() method. Perhaps I'm doing something wrong but checking the return value of the getListeners() as the ID changes shows that it does indeed change the array, but the channels it's listening on do not seem to change.

### Exact steps to reproduce
1. Make an event `php artisan make:event ActivityLogged`
2. Set it to broadcastAs `activity-logged` and to broadcast on the desired channel with the ID appended.
3. Make a variable in your livewire component which changes dynamically (modelled by a select, perhaps)
4. Set up the getListeners method to generate the array of listeners with the ID of the desired channel selected
5. Dispatch the event

### Stripped-down, copy-pastable code snippets
(I hope these are concise enough)
Event:
```
<?php

class ActivityLogged implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $id;

    public function broadcastAs()
    {
        return 'activity-logged';
    }
  
    public function __construct($id)
    {
        $this->id = $id;
    }

    public function broadcastOn()
    {
        return new PrivateChannel('activity-log.'.$this->id);
    }
}
```
Component:
```
<?php
use Livewire\Component;

class ActivityLog extends Component{

    public $selectedChannelId;

    public function getListeners()
    {
        return isset($this->selectedChannelId) ? [
            "echo-private:activity-log.{$this->selectedChannelId},.activity-logged" => "refresh"
             ] : [];
    }
    public function refresh(){
    }

    public function addActivityLog(){
        event(new ActivityLogged($this->selectedChannelId));
    }
    public function render(){
        return view('livewire.activity-log');
    }
}
```
**Context**
- Livewire version: 2.0 (according to composer.json)
- Laravel version: 8.25.0
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by ArtMin96** [comment]
I think it would be better to use the ```php $refresh ``` method instead of ```php refresh ``` and not create a new method.

**Comment by ArtMin96** [comment]
Have you tried use ``` echo-private:activity-log.{$this->selectedChannelId}, activity-logged ``` instead of ``` echo-private:activity-log.{$this->selectedChannelId},.activity-logged ```

**Comment by ArtMin96** [comment]
You are going to have to look at the active channels and then add/remove as you make changes.

Something like this.
```
protected function getListeners() 
{
    return [
        "echo-private:activity-log.{$this->selectedChannelId},joining" => 'joining',
        "echo-private:activity-log.{$this->selectedChannelId},leaving" => 'leaving',
    ];
}
```

Take a look at this one, maybe it can help you.
https://stackoverflow.com/questions/63795123/catching-event-in-laravel-with-livewire-and-echo

**Comment by waterbuckit** [comment]
> I think it would be better to use the `$refresh` method instead of `refresh` and not create a new method.

This is just a demonstration of doing something on an event so doesn't really have bearing on anything.

I'd also like to note that `selectedChannelId` is not necessarily set at the time of mounting, as the example shows in the docs. Because I need to jump between channels.

In the end, I've used this as a work around, whereby I leave the channel previously on when a new one is chosen but it's pretty unpleasant to have a script sitting on the page, I'd much rather that livewire's echo listeners could be reactive:

Blade Component: 

```html
<div>
       {{-- some input modelling the selected channel --}}
       
        <script>
        window.addEventListener("activity-log-channel-chosen", (e)=> {
            if(e.detail){
                
                if(e.detail.previous){
                    window.Echo.leave(`activity-log.${e.detail.previous}`);
                }

                window.Echo.private(`activity-log.${e.detail.new}`)
                    .listen('.activity-logged', (e) => {
                        console.log('activity-logged');
                        Livewire.emit('activity-logged');
                    })

             }
        })
       </script>
</div>
```
Livewire Component:
```php
class ActivityLog extends Component {

    public $selectedChannelId;
    public $previousChannelId;

    protected $listeners = [
        "activity-logged" => "refresh",
        "activity-log-responded-to" => "refresh"
    ];

    public function updatedSelectedChannelId(){
        $this->previousChannelId = $this->selectedChannelId;
    }

    public function updatingSelectedChannelId($id){
            $this->dispatchBrowserEvent("activity-log-channel-chosen", 
                    ["new" => $id, "previous" => $this->previousChannelId ??  null]);
    }

    public function refresh(){
    }

}
```

**Comment by renepardon** [comment]
I think I have a similar problem. I create an item and then I want to listen to all those item changes/events as well in the same component:

```php
    public function getListeners()
    {
        /** @var User $user */
        $user = auth()->user();

        // This will reload the table after an item X was created/deleted
        $listeners = [
            "echo-private:settings.{$user->id},.XCreated" => 'refetch',
            "echo-private:settings.{$user->id},.XDeleted" => 'refetch',
        ];

        // TODO getListeners should be called again to register new server events:
        foreach ($user->settingsX->pluck('id') as $xId) {
            $listeners["echo-private:provisioning.{$xId},.XReadyForProvisioning"] = 'refetch';
            $listeners["echo-private:provisioning.{$xId},.ProvisioningCreated"] = 'refetch';
            $listeners["echo-private:provisioning.{$xId},.XCreated"] = 'refetch';
        }

        return $listeners;
    }
```

But looks like **getListeners()** is only called on inital render/mount. Is there a way to trigger getListeners again to update the listeners also in the frontend?
