### ISSUE TITLE
The wire:ignore directive does not allow displaying error messages

### ISSUE THREAD

**Issue by mccarlosen** [livewire/livewire#2433]
### Description

when I use wire: ignore no error messages are displayed.

### Exact steps to reproduce

**I have this example:**
- I have created a datepicker with flatpicker as a component of alpinejs.
- The property is intertwined with `@entangle`
- In the date picker I have a css class that will be displayed when an error occurs with `@error ('date') text-red-400 @ enderror`
- In the parent element I have the directive `wire:ignore`

### Stripped-down, copy-pastable code snippets

```php
// FormComponent.php

use Livewire\Component;

class FormComponent extends Component
{
    public $date;

    protected $rules = [
        'date' => 'required|date_format:d/m/Y'
    ];

    public function save()
    {
        $this->validate();
    }
  
    public function render()
    {
        return view('form-component');
    }
}
```

```html
<!-- form-component.php -->

<div x-data="{
  date: @entangle('date')
}" x-init="
  flatpickr($refs.date);
">
  <form wire:submit.prevent="save" class="flex flex-col">
    <label class="label mb-0">date</label>
    <div class="mt-1" wire:ignore>
      <input 
        x-model="date" 
        x-ref="date" 
        class="py-3 px-4 bg-white text-gray-900 border border-gray-400 rounded-lg shadow-md w-full block focus:outline-none @error('date') border-red-400 @enderror" type="text" placeholder="{{ date('d/m/Y') }}"
      >
    </div>
    @error('date') <p class="text-sm text-red-700">{{ $message }}</p> @enderror
    <button type="submit" class="py-3 px-4 bg-green-400 text-white rounded-lg mt-2">Save</button>
  </form>
</div>
```

Here my Playground:

[https://laravelplayground.com/#/snippets/fdbb5848-02fb-4d54-b91f-69cec6f1220e](https://laravelplayground.com/#/snippets/fdbb5848-02fb-4d54-b91f-69cec6f1220e)

**Context**
- Livewire version: 2.2.3
- Laravel version: 8
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by jeffchown** [comment]
@mccarlosen I just tried your playground and submitted the form with an empty date field and the error message appeared OK for me.  Is there a specific case that is not working?  Or further details that apply to your original post?

**Comment by mccarlosen** [comment]
Hi Yes.
The out-of-element error with the `wire: ignore` directive works fine.
`@error('date') <p class="text-sm text-red-700">{{ $message }}</p> @enderror`

The problem is with the `@error ('date') border-red-400 @ enderror` which is inside the element with the directive` wire: ignore`
```html
<input 
        x-model="date" 
        x-ref="date" 
        class="py-3 px-4 bg-white text-gray-900 border border-gray-400 rounded-lg shadow-md w-full block focus:outline-none @error('date') border-red-400 @enderror" type="text" placeholder="{{ date('d/m/Y') }}"
      >
```

**Comment by jeffchown** [comment]
Gotcha - didn't see that as it was off the right of the screen.
`wire:ignore` is doing its job and telling Livewire/morphdom *not* to update that div.

I haven't used flatpickr - I use pikaday per the Livewire screencasts (https://github.com/Pikaday/Pikaday) and have been happy with it - so I don't have any insights/suggestions as to a specific workaround re: flatpickr, but if this helps, this is my Datepicker component code and it uses very similar validation styling as yours:

```
<div
    x-data="{ value: @entangle($attributes->wire('model')) }"
    x-init="new Pikaday({ 
        field: $refs.input, 
        format: 'YYYY-MM-DD',
        minDate: moment('{{ $minDate }}').toDate(),
        maxDate: moment('{{ $maxDate }}').toDate(),
        onOpen() { this.setMoment($refs.input.value) },
    })"
    @change="value = $event.target.value"
    class="flex rounded-md shadow-sm"
>
    <span 
        @click="picker.show()" 
        {{ $attributes->whereStartsWith('class')->merge([
                'class' => 'inline-flex items-center px-3 rounded-l-md border border-r-0 text-gray-500 sm:text-sm' . 
                (
                    $errors->first($attributes->whereStartsWith('wire:model')->first()) ? 
                        ' border-red-500 focus:ring-red-500 focus:border-red-500 ' : 
                        ' border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 '
                )
            ]) }}
    >
        <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M6 2C5.44772 2 5 2.44772 5 3V4H4C2.89543 4 2 4.89543 2 6V16C2 17.1046 2.89543 18 4 18H16C17.1046 18 18 17.1046 18 16V6C18 4.89543 17.1046 4 16 4H15V3C15 2.44772 14.5523 2 14 2C13.4477 2 13 2.44772 13 3V4H7V3C7 2.44772 6.55228 2 6 2ZM6 7C5.44772 7 5 7.44772 5 8C5 8.55228 5.44772 9 6 9H14C14.5523 9 15 8.55228 15 8C15 7.44772 14.5523 7 14 7H6Z"/>
        </svg>
    </span>

    <input
        {{ $attributes->whereDoesntStartWith('wire:model')->merge([
                'class' => 'shadow-sm block w-full sm:text-sm border-gray-300 rounded-r-md' . 
                (
                    $errors->first($attributes->whereStartsWith('wire:model')->first()) ? 
                        ' border-red-500 focus:ring-red-500 focus:border-red-500 ' : 
                        ' border-gray-300 focus:ring-indigo-500 focus:border-indigo-500 '
                )
            ]) }}
        type="text"
        placeholder="yyyy-mm-dd"
        x-ref="input"
        x-bind:value="value"
    />
</div>
```

it creates a form field like this:

![image](https://user-images.githubusercontent.com/42819001/106405981-e97f9a00-6405-11eb-81c3-c3a92e40f60f.png)

and this when the form is invalid:

![image](https://user-images.githubusercontent.com/42819001/106405997-f4d2c580-6405-11eb-9579-958801b20d8a.png)

**Comment by jeffchown** [comment]
@mccarlosen I had a closer look at your playground and tried a couple of things.  When I add the `dateFormat` config to your `flatpickr` initialization (to set your d/m/Y format) and then removed the `wire:ignore`, everything seems to work for me.

How does omitting the `wire:ignore` break flatpickr?

**Comment by mccarlosen** [comment]
@jeffchown Yes, it does work.

I added the `wire:ignore` directive because I thought that flatpicker would modify the element like Select2 does for example. But I see that the flatpicker calendar is out and just positioning itself.

So I removed the `wire:ignore` directive and changed `x-model` to `wire:model.defer` and it still works for me.

```html
<div x-data="{}" x-init="
  flatpickr($refs.date);
">
  <form wire:submit.prevent="save" class="flex flex-col">
    <label class="label mb-0">date</label>
    <div class="mt-1">
      <input 
        wire:model.defer="date" 
        x-ref="date" 
        class="py-3 px-4 bg-white text-gray-900 border border-gray-400 rounded-lg shadow-md w-full block focus:outline-none @error('date') border-red-400 @enderror" type="text" placeholder="{{ date('d/m/Y') }}"
      >
    </div>
    @error('date') <p class="text-sm text-red-700">{{ $message }}</p> @enderror
    <button type="submit" class="py-3 px-4 bg-green-400 text-white rounded-lg mt-2">Save</button>
  </form>
</div>
```
[https://laravelplayground.com/#/snippets/ea8e5521-020a-4c98-96f7-fa4ef5790daf](https://laravelplayground.com/#/snippets/ea8e5521-020a-4c98-96f7-fa4ef5790daf)

Thanks for the support, you have helped me.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by jeffchown** [comment]
That's great, @mccarlosen.  Glad you've got it working.
You're welcome. Happy to help.
