### ISSUE TITLE
problem on ubuntu 18.04.05: Call to a member function name() on array

### ISSUE THREAD

**Issue by ravenshill** [livewire/livewire#2440]
### Upgrade to 2.3.9, 
run :   composer install --no-interaction --prefer-dist --optimize-autoloader

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [2.3.8] 
- is ok
- Laravel version: [2.3.9]
- @php artisan package:discover --ansi

   Error 

  Call to a member function name() on array

  at vendor/livewire/livewire/src/LivewireServiceProvider.php:129
    125▕     protected function registerRoutes()
    126▕     {
    127▕         RouteFacade::post('/livewire/message/{name}', HttpConnectionHandler::class)
    128▕             ->middleware(config('livewire.middleware_group'))
  ➜ 129▕             ->name('livewire.message');
    130▕ 
    131▕         RouteFacade::post('/livewire/upload-file', [FileUploadHandler::class, 'handle'])
    132▕             ->middleware(config('livewire.middleware_group'))
    133▕             ->name('livewire.upload-file');

      +8 vendor frames 
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by ravenshill** [comment]
This is the relevant diff

    protected function registerRoutes()
    {
##removed 
        RouteFacade::post('/livewire/message/{name}', HttpConnectionHandler::class)->name('livewire.message');
##replaced with 
        RouteFacade::post('/livewire/message/{name}', HttpConnectionHandler::class)
            ->middleware(config('livewire.middleware_group'))
            ->name('livewire.message');

**Comment by calebporzio** [comment]
Yeah, the previous release contained this:
![image](https://user-images.githubusercontent.com/3670578/106674423-35a31980-6581-11eb-8ca0-a2510ae0d1a1.png)

And the current release (like you saw) adds a fluent `->name()` call at the end.

A can't see why this would break anything though? Why is `->middleware()` returning an array in your error message?

I tried `artisan package:discover` locally with success.

Is there something possibly custom about your setup that would cause this? What's your Laravel version?

Thanks!

**Comment by cg0012** [comment]
Hi Caleb, I am seeing the same on the latest Laravel build. I ran composer update:

```
λ composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Call to a member function name() on array

  at C:\laragon\www\cca2\vendor\livewire\livewire\src\LivewireServiceProvider.php:129
    125▕     protected function registerRoutes()
    126▕     {
    127▕         RouteFacade::post('/livewire/message/{name}', HttpConnectionHandler::class)
    128▕             ->middleware(config('livewire.middleware_group'))
  ➜ 129▕             ->name('livewire.message');
    130▕
    131▕         RouteFacade::post('/livewire/upload-file', [FileUploadHandler::class, 'handle'])
    132▕             ->middleware(config('livewire.middleware_group'))
    133▕             ->name('livewire.upload-file');

  1   C:\laragon\www\cca2\vendor\livewire\livewire\src\LivewireServiceProvider.php:62
      Livewire\LivewireServiceProvider::registerRoutes()

  2   C:\laragon\www\cca2\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Livewire\LivewireServiceProvider::boot()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```


and package discover won't run, I get the same error. 

However, I was able to run in production which had not been updated, otherwise identical:

```
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/breeze
Discovered Package: laravel/sail
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-permission
Discovered Package: spatie/laravel-ray
Package manifest generated successfully.
```
Please let me know if I can provide more info. It seems others are seeing the same and are downgrading livewire -[https://laracasts.com/discuss/channels/laravel/composer-updatecall-to-a-member-function-name-on-array](url)

[https://stackoverflow.com/questions/66017681/composer-updatecall-to-a-member-function-name-on-array](url)

**Comment by joshhanley** [comment]
@cg0012 what does your config/livewire.php file look like, specifically, what is in your 'middleware_group'?

**Comment by calebporzio** [comment]
Ah, so it looks like if `null` is passed to the `->middleware()` method, an array gets returned.

I see, because the middleware method is used as both a getter and setter.

I'll get a fix out stat.

![image](https://user-images.githubusercontent.com/3670578/106683822-3cd32300-6593-11eb-8d79-0fd2a2675cf8.png)

**Comment by lloricode** [comment]
same issue as mine, working in local (homestead)

PHP: 7.4.8
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```
```
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 3 updates, 0 removals
  - Downloading laravel/framework (v8.26.1)
  - Downloading livewire/livewire (v2.3.10)
  - Downloading phpunit/phpunit (9.5.2)
  - Upgrading laravel/framework (v8.25.0 => v8.26.1): Extracting archive
  - Upgrading livewire/livewire (v2.3.8 => v2.3.10): Extracting archive
  - Upgrading phpunit/phpunit (9.5.1 => 9.5.2): Extracting archive
Generating optimized autoload files
Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In LivewireServiceProvider.php line 129:
                                             
  Call to a member function name() on array  
                                             

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> @php -r "file_exists('composer.phar') || exec('bash .bash/composer.sh');"
> @php composer.phar dump-autoload --no-interaction --ansi --optimize
Generating optimized autoload files
Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In LivewireServiceProvider.php line 129:
                                             
  Call to a member function name() on array  
                                             

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Script @php composer.phar dump-autoload --no-interaction --ansi --optimize handling the clear-all-live event returned with error code 1

In LivewireServiceProvider.php line 129:
                                             
  Call to a member function name() on array  
                                             

```

**Comment by mertasan** [comment]
I created a PR related to this issue. #2444

**Comment by calebporzio** [comment]
Ok, thanks - I fixed it and tagged a release: v2.3.11

Thanks for the fix @mertasan, I threw one together myself before I saw yours, so thanks for being willing!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mertasan** [comment]
@calebporzio you're welcome. please turn on desktop notifications. 😂
