### ISSUE TITLE
Model update gives error in latest update

### ISSUE THREAD

**Issue by ekandreas** [livewire/livewire#2441]
### Description
When using an input with wire:model.debounce.300ms="variableName" the request fails with the following message:
ErrorException
strstr() expects parameter 1 to be string, object given

### Exact steps to reproduce
Create an input with debounce in a component.
When using v2.3.8 everything works just fine.

**Context**
- Livewire version: 2.3.9
- Laravel version: 8.26.1
- Browser: Chrome

ErrorException: strstr() expects parameter 1 to be string, object given in file /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 115

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'strstr() expect...', '...', 115, Array)
#1 /vendor/laravel/framework/src/Illuminate/Support/Str.php(115): strstr(Object(Closure), ':', true)
#2 /vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(39): Illuminate\Support\Str::before(Object(Closure), ':')
#3 [internal function]: Livewire\Controllers\HttpConnectionHandler->Livewire\Controllers\{closure}(Object(Closure), 5)
#4 /vendor/laravel/framework/src/Illuminate/Collections/Arr.php(664): array_filter(Array, Object(Closure), 1)
#5 /vendor/laravel/framework/src/Illuminate/Collections/Collection.php(344): Illuminate\Support\Arr::where(Array, Object(Closure))
#6 /vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(40): Illuminate\Support\Collection->filter(Object(Closure))
...

**Comment by calebporzio** [comment]
Thanks for submitting this.

It looks like I'm not supporting closure middleware here and assuming all are strings.

Just pushed a fix, will tag shortly, thanks!

**Comment by calebporzio** [comment]
Tagged: v2.3.10

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
