### ISSUE TITLE
Model attribute not showing inside input in a list

### ISSUE THREAD

**Issue by marcoT89** [livewire/livewire#2446]
### Description
My `wire:model` seems not working when using in a listed child component.

### Exact steps to reproduce

I have a simple tasks list component that does something like this:
```blade
<ul>
    @foreach($this->tasks as $task)
        @livewire('task-item', ['task' => $task], key($task->id))
    @endforeach
</ul>
```
And this is my blade inside my `task-item` component:
```blade
<li>
    <input wire:model="task.name"/>

    <button>remove</button>
</li>
```
In my PHP component I'm mounting the task like this:
```php
public Task $task;

public function mount(Task $task) {
    $this->task = $task;
}
```
My input is not showing the name of the task on mount. We can only see the placeholder text.
Like this:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/3236791/106696664-f2b26780-65bb-11eb-9bc1-495b0ac7ea7a.png">

I added a simple span below the input and it works like below:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/3236791/106696715-0c53af00-65bc-11eb-801e-5d0a3b4c1f5d.png">

It only works when I use a public `name` property instead of a model property:
```php
public $name;
```
and
```blade
<input wire:model="name" />
```

I think this is not the expected behavior right? Did I do something wrong?

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: v2.3.11
- Laravel version: v8.26.1
- Alpine version: 2.8.0
- Browser: Safari

**Comment by cg0012** [comment]
set your validation rules, this will allow livewire to $fillable on the model:

```
protected $rules = [
        'task.name' => 'required|string',
    ];
```
because this model is within a form.

also, no need to type hint on the mount method or even call for $this->task in mount. As long as its type hinted in your public declaration it knows $this->task is there. No big deal.

**Comment by austenc** [comment]
@marcoT89 as the other commenter noted, you're missing an entry in `$rules` for that property. 

> Note: For this to work, you have a validation entry in the `$rules` property for any model attributes you want to bind to. 

See here:
https://laravel-livewire.com/docs/2.x/properties#binding-models

If that fixes your problem, would you mind closing this issue? Thanks!

**Comment by marcoT89** [comment]
Thank you everyone! That fixes my problem! Thank you thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
