### ISSUE TITLE
Getting Str::replaceFirst() error on v2.3.11

### ISSUE THREAD

**Issue by byyoutree** [livewire/livewire#2447]
### Description
Too few arguments to function Illuminate\Support\Str::replaceFirst(), 2 passed in ../vendor/livewire/livewire/src/helpers.php on line 12 and exactly 3 expected

i downgraded to 2.3.8 and it seems fine..

### Exact steps to reproduce
Just access any page that uses livewire

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: v2.3.11
- Laravel version: v8.5.9
- Alpine version: -
- Browser: any

**Comment by RJFares** [comment]
The laravel framework pushed some changes to its string helpers which clashed with my custom macros.
Could be same issue happening in this lib.

**Comment by calebporzio** [comment]
I imagine it has something to do with the new change to Livewire that uses ->mergeConfig in the service provider instead of hardcoded defaults. 

@byyoutree, can you post your config file contents and re-open? Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by dgironella** [comment]
I have same error and solve it recreating livewire config file

`php artisan livewire:publish --config`
`php artisan config:cache`

**Comment by byyoutree** [comment]
> I have same error and solve it recreating livewire config file
> 
> `php artisan livewire:publish --config`
> `php artisan config:cache`

Oke have tried this solution and it works... thank you... :)

**Comment by SousaV90** [comment]
> I have same error and solve it recreating livewire config file
> 
> `php artisan livewire:publish --config`
> `php artisan config:cache`

I had the same error after update and this worked for me too! Thanks a lot! :)

**Comment by underdpt** [comment]
Hi,

I too faced this problem, and was able to solve it publishing the config as @byyoutree stated. To bring more light to this issue:

- I'm on laravel 7
- This only happens when testing with pest. Manually testing the site works correctly

It would be good if @byyoutree, @dgironella and @SousaV90 gave some more background info.

**Comment by shibbirweb** [comment]
I solved this issue by running
`php artisan optimize:clear`

**Comment by ahmedgamal1254** [comment]
php artisan livewire:publish --config
php artisan config:cache
