### ISSUE TITLE
Unable to prepare route [livewire/message/{name}] for serialization. Another route has already been assigned name [livewire.message]

### ISSUE THREAD

**Issue by dgironella** [livewire/livewire#2449]
### Description
After upgrade livewire to 2.3.12 all livewire component stop working. If i try to php artisan route:cache this error appear.

`Unable to prepare route [livewire/message/{name}] for serialization. Another route has already been assigned name [livewire.message].`

I my php artisan route:list have two 

'POST     | {locale}/livewire/message/{name} | livewire.message      | Livewire\Controllers\HttpConnectionHandler              | web  '

### Exact steps to reproduce
Upgrade a working project from 2.2

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [2.3.12]
- Laravel version: [8.26.1]
- Alpine version: [2.7.3]
- Browser: [Chrome]

**Comment by danharrin** [comment]
Hey folks, I hope #2450 fixes this for you both?

**Comment by dgironella** [comment]
> Hey folks, I hope #2450 fixes this for you both?

Yes, thanks this work.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by danharrin** [comment]
Great, gonna reopen this for now until a fix has been merged... otherwise people may not realise that it's a known issue and will open other threads.

**Comment by calebporzio** [comment]
Fixed and tagged: v2.3.13

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
