### ISSUE TITLE
Cannot use Livewire Components within Custom Error / 404 Pages

### ISSUE THREAD

**Issue by Chazza** [livewire/livewire#2451]
### Description
When using a livewire component within a custom 404 page, Livewire will trigger a "It's too early in the request to call Livewire::isDefinitelyLivewireRequest()" error. 

### Exact steps to reproduce
1. Create a views/errors/404.blade.php file.
2. Create a livewire component.
3. Include this component within your 404.blade.php file.

### Stripped-down, copy-pastable code snippets
May not be applicable here.

**Context**
- Livewire version: Latest (At time of post)
- Laravel version: (At time of post)
- Alpine version: (At time of post)
- Browser: Chrome

**Comment by joshhanley** [comment]
I have worked with @Chazza to narrow this down.

If you are using a custom 404 page and it makes use of your app layout (for example), and that layout has a Livewire component in it, it's throwing the exception as described above.

![image](https://user-images.githubusercontent.com/882837/106814562-b3bd0880-66c6-11eb-82ed-0138fcf06880.png)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
