### ISSUE TITLE
Video file upload

### ISSUE THREAD

**Issue by xtrem13** [livewire/livewire#2452]
### Exact steps to reproduce
Create.php file:

I have tried uploading video file with livewire, but somehow the stored file gets extension .bin . With images it worked fine.

Here is my code Create.php

```
class Create extends Component
{
    use WithFileUploads;


    
    public $file;

    
    
    public function save(){
        
        
        if($this->file){
            $this->file->store('media');
        }
        
   
    }
    public function render()
    {
        
        return view('livewire.media.create');
    }
}
```

create.blade.php
   ```     
    <form wire:submit.prevent="save" >
        
       
       

        <div class="form-group">
            <label>FILE</label>
            <input wire:model="file" class="form-control" type="file"/> 
            @error('file')
                <span class="alert alert-danger">
                    {{ $message }}
                </span>
            @enderror
            @if($file)
                {{'uploaded'}}
            @endif
            <div wire:loading wire:target="file">
                Uploading...
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-success">
                SAVE
            </button>
        </div>
    </form>
```

When I try uploading mp4 file it is stored as something like this: HYgPgyY58UxNn3AxkC7nx79Fwm9sq03Bhz9Fcdh6.bin
Did I miss something?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
