### ISSUE TITLE
Cannot test polymorphic relation in livewire

### ISSUE THREAD

**Issue by dm-brands-consulting** [livewire/livewire#2454]
### Description
I have a polymorphic relation between Task and Note (where Note is noteable and has a noteable_type and noteable_id field). Now, as a parameter, the Notes component can get any model which has a Notes relation (in my case a Task, which has many Notes). 

Example (in my task show view I call the component like this):
`<livewire:notes :model="$task" />`

Everything works great in the browser, so that I can store Notes on the Task. But when I am trying to test it, it does not work. 

The error I get is: 

`Cannot bind property [model] without a validation role present in the [$rules] array on Livewire component: [notes]`

### Stripped-down, copy-pastable code snippets
Notes component:

```
class Notes extends Component
{
    public $model;
    public $body;

    protected $rules = [
        'body' => 'required|min:3'
    ];

    public function submitNote()
    {
        $this->validate();
        $this->model->notes()->create([
            'user_id'   => Auth::user()->id,
            'body'      => $this->body
        ]);

        $this->refresh();
        $this->resetInputField();
    }

    public function render()
    {
        return view('livewire.notes');
    }

    private function refresh(){
        $this->model = $this->model->find($this->model->id);
    }

    private function resetInputField()
    {
        $this->body = '';
    }
}
```

Test case:
```
public function test_note_can_be_created_on_tasks()
    {
        $this->withExceptionHandling();

        $this->loginAs(User::factory()->create());
        $tenant = Tenant::factory()->create();
        $user = User::factory()->create(['tenant_id' => $tenant->id]);
        $category = TaskCategory::factory()->create();

        $task = Task::create([
            'tenant_id' => $tenant->id,
            'task_category_id' => $category->id,
            'receiver_id' => $user->id,
            'title' => 'a title',
            'description' => 'A Description',
            'contact_person_intern' => 'A Person',
            'contact_person_extern' => 'Another Person',
            'deadline' => now()
        ]);

        #dd($task->notes);

        Livewire::test(Notes::class)
            ->set('model', $task)
            ->set('body', 'This is a test note')
            ->call('submitNote')
            ->assertSee('This is a test note');
    }
```

Error message:
```
  FAIL  Tests\Feature\NoteLivewireTest
  ✓ tasks contains note livewire component
  ⨯ note can be created on tasks

  ---

  • Tests\Feature\NoteLivewireTest > note can be created on tasks
   Livewire\Exceptions\CannotBindToModelDataWithoutValidationRuleException 

  Cannot bind property [model] without a validation rule present in the [$rules] array on Livewire component: [notes].

  at vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php:25
     21▕         $propertyName = $this->beforeFirstDot($name);
     22▕ 
     23▕         throw_if(
     24▕             ($this->{$propertyName} instanceof Model || $this->{$propertyName} instanceof EloquentCollection) && $this->missingRuleFor($name),
  ➜  25▕             new CannotBindToModelDataWithoutValidationRuleException($name, $this::getName())
     26▕         );
     27▕ 
     28▕         $this->callBeforeAndAfterSyncHooks($name, $value, function ($name, $value) use ($propertyName, $rehash) {
     29▕             throw_unless(

      +27 vendor frames 
  28  tests/Feature/NoteLivewireTest.php:55
      Livewire\Testing\TestableLivewire::set("model", Object(App\Models\Task))


  Tests:  1 failed, 1 passed
  Time:   1.67s

```

**Context**
- Livewire version: 2.3
- Laravel version: 8.12

Any suggestions on this?

**Comment by joshhanley** [comment]
@dm-brands-consulting the reason is, in the browser, you have already passed the task model into your component so it's there when it's mounted.

Where as in your test you are trying to set test using Livewire's set method, which setting models and model properties requires validation rules as protection.

Try changing your test from

```php
Livewire::test(Notes::class)
            ->set('model', $task)
            // Other test actions here
```

To this which replicates what you are doing, by passing the task into the component

```php
Livewire::test(Notes::class, ['model => $task])
            // Other test actions here
```

Hope this helps!

**Comment by dm-brands-consulting** [comment]
@joshhanley great, that worked for me. Thank you a lot. Spend at least 2 hours for that.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@dm-brands-consulting no worries! Glad it worked
