### ISSUE TITLE
Undefined index: url from LivewireManager.php

### ISSUE THREAD

**Issue by Braunson** [livewire/livewire#2455]
### Description

Seeing errors coming in to Sentry/Laravel log

```jsx
Error: Undefined index: url
Page: http://www.site.com/livewire/message/create-account
User: Not Logged In
Line: 316
File: /app/vendor/livewire/livewire/src/LivewireManager.php
```

### Exact steps to reproduce
Not able to re-create it, but it keeps happening on production on login. Using login example from the TALL stack example which uses Livewire.

**Context**
- Livewire version: 2.3.9
- Laravel version: 8.26.1
- Alpine version: 2.8.0
- Browser: Mixed

Looks like this happened after an update from Livewire 2.3.8 to 2.3.9

**Comment by calebporzio** [comment]
@Braunson, can you upgrade to the latest release (v2.3.15) and confirm that this is still happening?

**Comment by Braunson** [comment]
@calebporzio Will update and follow up.

**Comment by okaufmann** [comment]
Hi

I have the same problem when using the `$refresh` handler when listening on echo events:

```php
protected $listeners = ['echo-private:sync,Synced' => '$refresh'];
```

This happens in all components, where this listener is registered.

The error is thrown here https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L313.

I don't know what's causing this problem though....

Context:
- PHP: 7.4.13
- Laravel: 8.26.1
- Alpine version: 2.7
- Livewire: 2.3.15

**Comment by okaufmann** [comment]
Ok, my problem was solved as another user had the page open in a later version causing this problem.

Maybe a Update to 2.3.15 has fixed this! Can you confirm @Braunson ?

**Comment by calebporzio** [comment]
Ah, I see the problem now.

This update now includes a new JSON key called `url` in the original Livewire payload and is passed back and forth every Livewire request.

The reason you are getting errors:

People loaded the page with an older version of Livewire, then you upgraded, and while their pages are loaded they are triggering Livewire AJAX requests that hit your updated server, but the page they were submitting from had stale Livewire JS.

So these should disappear after users refresh their pages, or you clear all the sessions.

**Comment by Braunson** [comment]
@calebporzio I figured this was the issue, as I've had a similar issue in the past and after updating it tapered off after some time. So far it looks to be tapering off, closing this as it seems to be resolved for now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by calebporzio** [comment]
Thanks for following up @Braunson!
