### ISSUE TITLE
Expose event element on root

### ISSUE THREAD

**Issue by tillkruss** [livewire/livewire#246]
> I WOULD like to pass the element that fired the event and/or the component instance or root el. There’s a lot of opportunity for exposing a component’s object to listeners like this and giving the developers access to hooks and data, etc…

![7AAA8741-DA94-49F8-8889-B7E4B091535C](https://user-images.githubusercontent.com/665029/64477072-e5394980-d14b-11e9-8883-acfbc9443312.jpeg)

**Comment by calebporzio** [comment]
Yeah, I could see this being useful. Closing this for now though, as it would be a breaking change I believe and no one else has requested it.
