### ISSUE TITLE
Livewire turbolinks form submit

### ISSUE THREAD

**Issue by denizozturk** [livewire/livewire#2460]
There is a error in Livewire with Turbolink. When I use Turbolink, livewire components (click actions) and form submission do not work unless I refresh the page. Has anyone found a solution on this issue?

Same: https://github.com/livewire/livewire/issues/1616

**Comment by denizozturk** [comment]
@calebporzio

**Comment by joshhanley** [comment]
@denizozturk can you please provide some more information?

What versions of Laravel, Livewire, Livewire-Turbo plugin are you using? Are you using TurboLinks or Turbo and what version of that?

How are you adding turbo/turbolinks and livewire-turbolinks to your app? If you can provide an example repo or sample code that you are using so we can test it, that would be great.

**Comment by denizozturk** [comment]
@joshhanley 

Thank you for your attention, I found the solution. When using Livewire and Turbolinks, livewire data gets crushed on page change and reboot is required.

`
document.addEventListener("turbolinks:load", function() {
    window.livewire.start()
});
`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@denizozturk Ah right. Are you using the Livewire/Turbolinks adapter package? It should be doing that for you. https://github.com/livewire/turbolinks

**Comment by Freddyqt** [comment]
var Turbolinks = require("turbolinks")
Turbolinks.start()
document.addEventListener("turbolinks:load", function() { window.livewire.start() });

coloque ese codigo en el app.js y luego npm install && npm run dev y funciono!
