### ISSUE TITLE
wire:click result is like calling the component again

### ISSUE THREAD

**Issue by RicardoRamirezR** [livewire/livewire#2462]
Good day, this is VERY basic issue.

### Description

Loading the page show the two names, then after doing click over any name it generates an error: Trying to get property 'id' of non-object

![Captura de Pantalla 2021-02-05 a la(s) 12 58 25 p  m](https://user-images.githubusercontent.com/6526545/107070867-e4c63780-67b1-11eb-84e3-385597872195.png)

### Exact steps to reproduce

1. ```Laravel new l8```
2. ```cd l8```
3.  ```composer require livewiere/livewiere```
4. ```php artisan make:livewire Pupa```
5. Add to welcome view ```<livewire:pupa />```
6. go to l8 website
7. click on any name, i.e. pepe

### Stripped-down, copy-pastable code snippets
```php
<!DOCTYPE html>
<html>
    <head>
        <livewire:styles />
    </head>
    <body class="antialiased">

        <livewire:pupa />

        <livewire:scripts />
    </body>
</html>

```
```app/Http/Livewire/Pupa.php```
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Pupa extends Component
{
    public $vets;

    public function mount()
    {
        $this->vets = [
            (object) ['id' => 1, 'first_name' => 'pepe', 'last_name' => 'ganga'],
            (object) ['id' => 2, 'first_name' => 'juan', 'last_name' => 'perez'],
        ];
    }

    public function lola() {}

    public function render()
    {
        return view('livewire.pupa');
    }
}
```

```resources/views/livewire/pupa.blade.php```
```php
<div>
    @foreach($vets as $vet)

        <div
            wire:click="lola({{ $vet->id }})"
            wire:key="{{ $loop->index }}"
            class="first"
        >
            {{ $vet->first_name }}
        </div>

    @endforeach
</div>
```

Code inspector
```html
<div wire:id="Qp7kDilPbwyXZq0tMxcr">

    <div wire:click="lola(1)" wire:key="0" class="first">
        pepe
    </div>
    
    <div wire:click="lola(2)" wire:key="1" class="first">
        juan
    </div>

</div>
```

**Context**
- Livewire version: v2.3.16
- Laravel version: v8.26.1/v7.30.4
- Alpine version: 2.8.0
- Browser: Chrome, Safari

**Comment by denizozturk** [comment]
`
    public function lola($id) {
        return dd($id);
    }

`When I use the "lola" method it did not give any error

**Comment by RicardoRamirezR** [comment]
Thank you @denizozturk for the time.

if we add a public property ```public $currentVet = null;```and then update the ```lola``` method, it generate the error.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Pupa extends Component
{
    public $vets;

    public $currentVet = null;

    public function mount()
    {
        $this->vets = [
            (object) ['id' => 1, 'first_name' => 'pepe', 'last_name' => 'ganga'],
            (object) ['id' => 2, 'first_name' => 'juan', 'last_name' => 'perez'],
        ];
    }

    public function lola($id) {
        $this->currentVet = $id;
    }

    public function render()
    {
        return view('livewire.pupa');
    }
}
```

**Comment by jeffchown** [comment]
On quick glance, if you add a `@php dd($vet) @endphp` right after `@foreach($vets as $vet)` in `resources/views/livewire/pupa.blade.php`, does it show `$vet` as an array or object?

**Comment by RicardoRamirezR** [comment]
@jeffchown thank you. First time, object, on click array

**Comment by RicardoRamirezR** [comment]
I mean
```php
<div>
    @foreach($vets as $vet)
        @if (is_array($vet))
            {{ dd($vet) }}
        @endif

        <div
            wire:click="lola({{ $vet->id }})"
            wire:key="{{ $loop->index }}"
            class="first"
        >
            {{ $vet->first_name }}
        </div>

    @endforeach
</div>
```
gives
```
array:3 [▼
  "id" => 1
  "first_name" => "pepe"
  "last_name" => "ganga"
]
```

**Comment by joshhanley** [comment]
@RicardoRamirezR standard objects aren't supported, only eloquent models or eloquent collections. I'd recommend changing this to an array (removing `(object)`) or saving the records to the database:

```php
$this->vets = [
            (object) ['id' => 1, 'first_name' => 'pepe', 'last_name' => 'ganga'],
            (object) ['id' => 2, 'first_name' => 'juan', 'last_name' => 'perez'],
        ];
```

Hope this helps!

**Comment by joshhanley** [comment]
@RicardoRamirezR there are ways you can manually rehydrate array to objects, so if you do need that, let me know and I'll show you how you can do it.

But if you are just testing and this stuff will be in the database anyway, I'd just say set it up now and get it running from the database 🙂

**Comment by RicardoRamirezR** [comment]
@joshhanley thank you.

Actually I've tried to prepare a small version. The real one has a collection of Eloquent models and it fails also.

**Comment by RicardoRamirezR** [comment]
@joshhanley Oh man, getting the records from the database actually works! thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@RicardoRamirezR no worries!
