### ISSUE TITLE
Livewire not working on raspberry browsers

### ISSUE THREAD

**Issue by SchuBu** [livewire/livewire#2468]
### Description
I started a project with livewire on my raspberry - unfortunately livewire is not working neither on chromium-browser nor on firefox-esr.
Any suggestions on it?

### Exact steps to reproduce
Made a simple app polling actual time every 2s. And also added a "refresh" button. neither wire:click nor wire:poll seems to work.

**Context**
- Livewire version: latest
- Laravel version: latest
- Alpine version: latest
- Browser: chromium-browser and firefox-esr

**Comment by calebporzio** [comment]
Please re-open this issue with more information and discovery effort. (and also check that Livewire's JavaScript is loading alright in the devtools). Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
