### ISSUE TITLE
LivewireManager::$isLivewireRequestTestingOverride causing subsequent tests to fail

### ISSUE THREAD

**Issue by fuelingtheweb** [livewire/livewire#2489]
### Description
With Livewire v2.3.9 and above, running my entire test suite causes tests that rely on the ConvertEmptyStringsToNull middleware to fail when they run after a Livewire test that sets data.

```
        Livewire::actingAs($admin)
            ->test(FilterUsers::class)
            ->set('sort', 'first_name')
            ->assertViewHas('users');
```

All tests are green when `->set()` is omitted, but tests that rely on ConvertEmptyStringsToNull fail when `->set()` is included.

When I remove `LivewireManager::$isLivewireRequestTestingOverride = true;` from `TestableLivewire@pretendWereSendingAComponentUpdateRequest()`, all tests pass. I'm not sure if anything else is relying on that code. Can that safely be removed?

**Context**
- Livewire version: >=2.3.9
- Laravel version: 8.27.0

**Comment by austenc** [comment]
Can you please provide more context so we can reproduce this without guessing? The test that fails, the livewire component, etc...

An example repository would be super helpful here. Thanks!

**Comment by fuelingtheweb** [comment]
@austenc Here's a sample Laravel application that replicates the issue: https://github.com/benholmen/livewire-test-issue

If you run the entire test suite, `tests/Feature/OtherTest.php@testShouldPassButFailsWhenAlsoTestingLivewire` fails because `Livewire@set` in `tests/Feature/LivewireTest.php@testSettingPropertyBreaksOtherTests` is disabling middleware. When run in isolation, all tests pass.

If Livewire testing needs to disable middleware, could it just reset the middleware when the Livewire test is finished?

**Comment by aleahy** [comment]
I've been finding the same thing. As @fuelingtheweb said, it only happens if the livewire version installed is 2.3.9 or greater.

The livewire component is not complicated - it just has a single property.
I've also created a separate, unrelated Post model with a controller to store new posts.

Here is an example of a livewire test that causes the fail:
```
public function test_it_can_update_value()
{
    Livewire::test(Something::class)
        ->set('textValue', 'Some value')
        ->assertViewHas('Some value');
}
```

Here is an example of a test that fails:
```
public function test_a_post_can_be_created_with_no_url()
{
    $this->post(route('posts.store'), [
            'title' => 'Some title',
            'url' => '',
            'message' => 'Some message',
        ])->assertSuccessful();

        $this->assertDatabaseHas('posts', [
            'title' => 'Some title',
            'url' => null,
            'message' => 'Some message'
        ]);
}
```

The reported reason for the test failing is that url has an empty string in the database, which suggests the middleware `ConvertEmptyStringsToNull` is being ignored.

Run independently, both tests pass.

**Comment by austenc** [comment]
Thanks folks, I'll check this out tomorrow.

**Comment by benholmen** [comment]
Thanks Austen!

**Comment by tomwelch** [comment]
Hi all,

I've stumbled across this too. As a workaround at the moment I'm resetting `$isLivewireRequestTestingOverride` to `false` in the `tearDown` method on any test class that interacts with Livewire's test helpers.

```php
protected function tearDown(): void
{
    LivewireManager::$isLivewireRequestTestingOverride = false;
}
```

Resetting after every test may be a bit excessive if your test class only tests a Liverwire component, at which point you can reset in the `tearDownAfterClass` method.

```php
public static function tearDownAfterClass(): void
{
    LivewireManager::$isLivewireRequestTestingOverride = false;
}
```

**Comment by nvahalik** [comment]
We just ran into this problem as well. @tomwelch's fix works as expected!

**Comment by GC-Mark** [comment]
We've just come across this issue, @tomwelch solution works for now, but hopefully this will be fixed internally at some point 👍
