### ISSUE TITLE
Bug in File Upload cleanup on high traffic websites

### ISSUE THREAD

**Issue by bzarzuela** [livewire/livewire#2491]
### Description
We use Laravel Livewire on a very busy website. In some cases, the file upload code is triggered with a race-condition that causes errors like this to be logged.

File not found at path: livewire-tmp/paeevOyI4gyBawMcQeRfOT3NX5A6WhmetaU2VsZmllIHdpdGggZ292dCBJRC5qcGc=-.jpg

### Exact steps to reproduce
Hard to reproduce but the stack trace gives a good confirmation.

`{
    "class": "League\\Flysystem\\FileNotFoundException",
    "message": "File not found at path: livewire-tmp/nUOOk8NDKbXX1ugfIdaUmoFd6GOXzp-metacmVjZWl2ZWRfMTcxNjIwOTE3ODAwODY5LmpwZWc=-.jpg",
    "code": 0,
    "file": "/home/forge/psahelpline.ph/vendor/league/flysystem/src/Filesystem.php:389",
    "trace": [
        "/home/forge/psahelpline.ph/vendor/league/flysystem/src/Filesystem.php:298",
        "/home/forge/psahelpline.ph/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:427",
        "/home/forge/psahelpline.ph/vendor/livewire/livewire/src/WithFileUploads.php:100",
        "/home/forge/psahelpline.ph/vendor/livewire/livewire/src/WithFileUploads.php:29",
        "/home/forge/psahelpline.ph/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",`

Line 100 of WithFileUploads is within this code block.

```
foreach ($storage->allFiles(FileUploadConfiguration::path()) as $filePathname) {
                $yesterdaysStamp = now()->subDay()->timestamp;
                if ($yesterdaysStamp > $storage->lastModified($filePathname)) {
                    $storage->delete($filePathname);
                }
        }
```

My idea is to add an exists() check there so that the error is not triggered when lastModified is called.

Maybe it won't completely eliminate the race condition. 

**Context**
- Livewire version: v2.3.6
- Laravel version: v8.23.1
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by bzarzuela** [comment]
I have this fix running on our website for several days now and it has eliminated all of these error messages from our logs.

**Comment by austenc** [comment]
@bzarzuela would you mind making a PR for this with an explanation? Including tests would also improve the likelihood of such a PR getting merged. Thank you!

**Comment by Abhi0725** [comment]
I was just wondering about how Livewire handles local temporary uploaded file deletes. Pardon my ignorance but I feel it's weird to handle file delete (for all the old files) in the same request as file upload. Wouldn't it be good idea to move this to a cron job or at least make it async (with laravel queue)?

@bzarzuela your thoughts?

**Comment by bzarzuela** [comment]
> I was just wondering about how Livewire handles local temporary uploaded file deletes. Pardon my ignorance but I feel it's weird to handle file delete (for all the old files) in the same request as file upload. Wouldn't it be good idea to move this to a cron job or at least make it async (with laravel queue)?
> 
> @bzarzuela your thoughts?

I think it would be nice if we can override this behavior entirely. By default, I think it’s good because it makes file uploads convenient. 

If we can turn it off via .env then do a scheduled artisan command to clean up old files, it would be good for high traffic websites.

**Comment by nuernbergerA** [comment]
Fixed by https://github.com/livewire/livewire/pull/2492

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
