### ISSUE TITLE
Missing `use` operator

### ISSUE THREAD

**Issue by hferradj** [livewire/livewire#2497]
https://github.com/livewire/livewire/blob/1a1d43ff365301ae99ed7f0ccf02c553d4eeba03/src/Component.php#L192

`use Illuminate\Database\Eloquent\Collection as EloquentCollection;` is missing in this file, making this line check if value is an instance of `Livewire\EloquentCollection`, which does not exist.

**Comment by austenc** [comment]
Nice catch, I'll PR this soon.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
