### ISSUE TITLE
$wire.emit gives TypeError: this.listeners.call is undefined

### ISSUE THREAD

**Issue by angauber** [livewire/livewire#2498]
**Context**
- Livewire version: 2.3.17
- Laravel version: 8.27.0
- Alpine version: 2.8.0
- Browser: Firefox 85.0.1 (64-bit)]
 
### Description

When adding a component with:
```
<div x-data="{}">
    <button @click="$wire.emit('testEvent')">Test $wire.emit</button>
</div>
```
Clicking the element gives the following error:
```
Uncaught (in promise) TypeError: this.listeners.call is undefined
    emit Store.js:51
```

This issue is solved by using
```
<div x-data="{}">
    <button @click="Livewire.emit('testEvent')">Test $wire.emit</button>
</div>
```

The [events](https://laravel-livewire.com/docs/2.x/events#firing-events) documentation section indicate that you should use `Livewire.emit` in this case
But in the [alpine](https://laravel-livewire.com/docs/2.x/alpine-js) integration documentation you can read in the `$wire` API section:
```
// Emitting a Livewire event called "some-event" with two parameters
$wire.emit('some-event', 'foo', 'bar')
```

If `$wire.emit` cannot be used in this case, what is it made for ?

**Comment by adeiming** [comment]
same issue..

**Comment by glugox** [comment]
This happens when you call $wire.emit from a non livewire component.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
