### ISSUE TITLE
Receiving HTTP 500 for modified input field

### ISSUE THREAD

**Issue by renepardon** [livewire/livewire#2500]
### Description

When opening the developer tools and changing the input field name to something else and submitting this form, I receive a 500 HTTP error.

### Exact steps to reproduce

Create an input form:

```html
<input class="w-full" id="field-whatever" type="email" required="required" wire:loading.attr="disabled" wire:model.lazy="field.whatever">
```

Create a property in your component:

```php
public array $field = [];
```

Submit. Everything works. Change `wire:model.lazy="manipulated"` and you receive a 500 error instead of "you tampered with our tool":

```bash
[2021-02-15 05:10:00] production.ERROR: Property [$manipulated] not found on component: [settings.servers.stack.section] {"userId":1,"exception":"[object] (Livewire\\Exceptions\\PropertyNotFoundException(code: 0): Property [$manipulated] not found on component: [settings.servers.stack.section] at /var/www/html/vendor/livewire/livewire/src/Component.php:227)
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: ^2.0
- Laravel version: ^8.12
- Alpine version: ^2.7.3
- Browser: Google Chrome Version 88.0.4324.96 (Offizieller Build) (x86_64)

**Comment by austenc** [comment]
For this to work, Livewire would have to compare the submitted field name to every component field _in each request_. Otherwise, it would be tough to differentiate between tampering and a user error when coding. 

This might not be worth the extra work just for a specialized exception. 

What would you expect to happen here?

**Comment by marispro** [comment]
Just idea - would be nice that instead of 500 error - Livewire could refresh the page automatically if this error appears (when app.debug = false).

**Comment by renepardon** [comment]
Yeah, a refresh would be nice, if a special exception would be too much work ;)

There are three different cases right now:

- you tampered with data (you didn't but inside a public property array you use an object which causes livewire to fail with "tampered" exception)
- you didn't do anything for a long time. then livewire wants to reload the page and informs with a browser confirm dialog
- a 500 server error is thrown as soon as user modifies the property names

Instead of an exception we might want to have a callback method so we can handle this case in the component itself or in the application logic somewhere else?

**Comment by nathanjansen** [comment]
Isn't this something you can do in your Laravel Exceptions handler (app/Exceptions/Handler.php)?

I was able to find this exception for example:
- Livewire\Exceptions\CorruptComponentPayloadException

**Comment by renepardon** [comment]
Yeah, you're right @nathanjansen ... long time I had no need to think about and adjust the Exception handler ;)

Of course the Exception in this case would be `Livewire\\Exceptions\\PropertyNotFoundException`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
