### ISSUE TITLE
Public functions no longer work 

### ISSUE THREAD

**Issue by virgiltu** [livewire/livewire#2501]
This works 
![image](https://user-images.githubusercontent.com/7761519/107912426-4fdedf00-6f13-11eb-80a4-be769daadd8e.png)

This does not work 

![image](https://user-images.githubusercontent.com/7761519/107912454-5ff6be80-6f13-11eb-9df4-c2e589f78433.png)

![image](https://user-images.githubusercontent.com/7761519/107912504-73a22500-6f13-11eb-8347-114aed261ba9.png)

I did install this last version of livewire Jetstream package with Laravel 8 
also i have this module installed https://spatie.be/docs/laravel-multitenancy/v1/introduction

**Comment by austenc** [comment]
Working fine when I test it -- make sure you have the latest version of Livewire installed.

Please specify your Livewire version number as noted in the issue template, thank you!

**Comment by virgiltu** [comment]
I found the issue. I was watching this video https://codecourse.com/courses/custom-laravel-jetstream-routes
 
if you copy the jetstream.php as your routes for some reason it stops working and you can use livewire public vars. I tried and test it on a new project and same result. 

 So not a bug.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
