### ISSUE TITLE
Livewire assertSeeHtml test helper isn't stackable

### ISSUE THREAD

**Issue by jeroenvanrensen** [livewire/livewire#2507]
I want to use this code:

```php
Livewire::test(Create::class, ['resourceSlug' => $resource->slug()])
    ->assertStatus(200)
    ->assertSee('Body')
    ->assertSee('textarea')
    ->assertSeeHtml('rows="3"')
    ->assertDontSeeHtml('rows="6"');
```

But I get this error message:

```
Method Illuminate\Http\Response::assertSeeHtml does not exist.
```

So the `assertSee` helper returns an `Illuminate\Http\Response` instance, so I can't stack `assertSeeHtml` on it.

Fortunately I found a simple workaround:

```php
Livewire::test(Create::class, ['resourceSlug' => $resource->slug()])
    ->assertStatus(200)
    ->assertSee('Body')
    ->assertSee('textarea');

Livewire::test(Create::class, ['resourceSlug' => $resource->slug()])
    ->assertSeeHtml('rows="3"')
    ->assertDontSeeHtml('rows="6"');
```

But it would still be nice if it gets fixed.

Thank you! Jeroen

**Comment by austenc** [comment]
Hello @jeroenvanrensen, which version of Livewire are you using? 

I just tested this and the `assertSeeHtml` and `assertSee` methods are chainable as you would expect. Perhaps you have modified versions in your `TestCase` class or something like that?

You can see that both methods return an instance of `$this` here:
https://github.com/livewire/livewire/blob/master/src/Testing/Concerns/MakesAssertions.php#L53

**Comment by jeroenvanrensen** [comment]
Well, that's strange. I'm getting an `Illuminate\Http\Response` instance. I ran `composer update` and `composer dump-autoload`.

### Context (might be useful)

 - Laravel v8.x-dev
 - Livewire v2.3.17

**Comment by joshhanley** [comment]
@austenc I had a quick look at this, I think it's actually `assertStatus` that is causing the issue. It's returning a normal response, which `assertSee` is a standard method on, but `assertSeeHtml` isn't that's why it's erroring out when it gets to there.

In the `TestableLivewire` clas the catch all `__call` method doesn't return an instance of the TestableLivewire `$this`, when it probably should, which I think would potentially fix the issue.

**Comment by jeroenvanrensen** [comment]
@joshhanley yeah that makes sense

**Comment by joshhanley** [comment]
@jeroenvanrensen Can you confirm, if you remove assertStatus that everything else runs as expected in your original test?

**Comment by jeroenvanrensen** [comment]
@joshhanley yes this code does work:

```
Livewire::test(Create::class, ['resourceSlug' => $resource->slug()])
    ->assertStatus(200);

Livewire::test(Create::class, ['resourceSlug' => $resource->slug()])
    ->assertSee('Body')
    ->assertSee('textarea')
    ->assertDontSeeHtml('rows="3"')
    ->assertSeeHtml('rows="6"');
```

**Comment by joshhanley** [comment]
@jeroenvanrensen Ok great, thanks for confirming! 

Also you can save the `Livewire::test` call to a variable and then call assertStatus on the variable on its own. And do the same for the second block. 

Hope that makes sense, on mobile at the moment. Saves you having to initialise it twice.

**Comment by jeroenvanrensen** [comment]
Yeah, that's smart I guess.  Would still be nice if it gets fixed

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by jeroenvanrensen** [comment]
@calebporzio I would like to get into open source, so would you accept a PR for this bug?

**Comment by joshhanley** [comment]
@jeroenvanrensen check out this PR #2536 by @austenc he has already submitted a fix 🙂

**Comment by jeroenvanrensen** [comment]
@joshhanley well, that's unfortunate. Better luck next time!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by austenc** [comment]
Hi @jeroenvanrensen if you'd like to submit a new PR with the fix and an associated test (per Caleb's comments in my PR) you are welcome to, and I will close mine. Let me know!

**Comment by jeroenvanrensen** [comment]
@austenc I don't think I would be able to write a test for this. I guess it's better if you do this!
