### ISSUE TITLE
Should `livewire-components.php` be tracked?

### ISSUE THREAD

**Issue by fgilio** [livewire/livewire#252]
This is not a bug nor a feature request. Should `livewire-components.php` be tracked in git?

Just had an error while deploying a project because Livewire couldn't find a component. I had a gut feeling that it was something in `livewire-components.php` and indeed it was. The file was outdated and that component was missing.
I tried running `php artisan livewire:discover` but it failed, I guess it was a file permissions error (using Laravel Forge).

Ended up fixing it by telling git to track the file and deploying again.

**EDIT 2019-09-14:**
The permissions errors when running `php artisan livewire:discover` where 100% on my side. So I guess nobody has to worry about that.

**Comment by intrepidws** [comment]
Or maybe we should be adding `php artisan livewire:discover` to our deploy scripts?

**Comment by intrepidws** [comment]
Interesting that it failed. I had the same exact issue as you but was able to run `php artisan livewire:discover` just fine. I'm using Laravel Forge as well.

**Comment by ninthspace** [comment]
I've had this too, usually when I switch between development machines and then pull down new content from a repo. To work around, I've updated composer.json:

```json
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi",
      "@php artisan livewire:discover"
    ],
```

**Comment by tillkruss** [comment]
@ninthspace: That seems to be a reasonable solution to accelerate the first request and to cache the components on ephemeral filesystems.

`LivewireComponentsFinder::getManifest()` will build and save the `livewire-components.php` if it doesn't exist.

**Comment by fgilio** [comment]
\* The permissions errors when running `php artisan livewire:discover` where 100% on my side. So I guess nobody has to worry about that 😅

**Comment by lancepioch** [comment]
@fgilio Can the issue be closed?

**Comment by intellow** [comment]
I will submit a PR later today that will automatically regenerate the manifest if Livewire cannot find a component. This will eliminate the ComponentNotFoundException from being thrown unless it is valid (the component does not exist or is in the wrong namespace).

Of course, this still wouldn't help if the regeneration of the manifest file is blocked by server permissions. 😄

**Comment by fgilio** [comment]
> @fgilio Can the issue be closed?

I thinks so, yep


> I will submit a PR later today that will automatically regenerate the manifest if Livewire cannot find a component...

Amazing!
