### ISSUE TITLE
404 Errors with various Livewire actions

### ISSUE THREAD

**Issue by Jusdon** [livewire/livewire#2524]
### Description
I get 404 errors with various Livewire actions.
In my case: Upload photo, Modal window save

### Exact steps to reproduce
Try to upload a photo or Save data with modal windows

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.17
- Laravel version: 8.27.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by nathanjansen** [comment]
This sounds like an error in your routes. 

If it has nothing to do with routes.
Did you manually register your Livewire component? 
Sometimes that helps.

**Comment by Jusdon** [comment]
Sorry it was my mistake! I found the error. I had an error in on of my Observers. But I am confused that‘s fires an 404 Error and no 500 Error

**Comment by Jusdon** [comment]
Please close :)

**Comment by nathanjansen** [comment]
It appears more people are having 404 problems:
https://github.com/livewire/livewire/issues/2445

**Comment by joshhanley** [comment]
@Jusdon if you can share the error you made, we might be able to explain why it was responding with a 404.

I'm going to close this as requested, but post up what was wrong and what you did to fix it, incase others run into a similar issue.

Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Jusdon** [comment]
@joshhanley okay i try to explain,

In my user model I have a BelongsTo relationship with a model which can also be null. For example, if I log out as a logged-in user, the observer is executed and tries to access an attribute of the null relationship in order to process this. The same goes for uploading the profile photo. I only came across the error through the Laravel Debugbar.

**Comment by joshhanley** [comment]
@Jusdon oh interesting! Yeah a 404 seems strange. Might be something in the auth layer triggering that, not sure though.

One thing you can do though, is for calls like that, use the optional helper, that way it won't error if the relation is missing. https://laravel.com/docs/8.x/helpers#method-optional

**Comment by Jusdon** [comment]
@joshhanley Ah thanks for the tip I didn't even know this helper method

so far I've always solved it that way
for example

if(Auth::user()->relation()->exists()) {
         dd(Auth::user()->relation->attribute);
}

so can I just write it like that

dd(optional(Auth::user()->relation)->attribute);

?

**Comment by joshhanley** [comment]
@Jusdon yep exactly! Much cleaner
