### ISSUE TITLE
Showing error when triggering a method when the Component is loaded via jquery/js

### ISSUE THREAD

**Issue by theonly27** [livewire/livewire#2529]
### Description
Im getting error `The POST method is not supported for this route. Supported methods: GET, HEAD` when the component is loaded via js/jquery.

### Exact steps to reproduce
1.) Create Simple Blade and Livewire Component
2.) Put the @livewire('component') directive inside the blade and create a simple post ajax to call that blade and to make livewire component work, add window.livewire.restart() after appending html to the dom.

`        success: function(data) {
                $('#container').append(data);
                if (window.livewire) {
                    window.livewire.restart();
                }
        }
`

3.) Trigger a wire:click inside the component.

In the previous version 2.3.8, it was working properly.
any work around or fix for this? Thank you.

**Context**
- Livewire version: 2.3.18
- Laravel version: 8.28.1
- Browser: Brave, Chrome and Edge

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
