### ISSUE TITLE
Cannot use 2 @entangle

### ISSUE THREAD

**Issue by PH7-Jack** [livewire/livewire#2532]
### Description
Not is possible to use 2 @entangle() in same x-data

error:

> Uncaught SyntaxError: Unexpected token u in JSON at position 0

### Exact steps to reproduce
```
<div x-data="{ open: @entangle('open'), name: @entangle('name') }">
        <button @click="open = true" x-text="name"></button>

        <ul x-show="open" @click.away="open = false">
            <li><button wire:click="archive">Archive</button></li>
            <li><button wire:click="delete">Delete</button></li>
        </ul>
    </div>
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.18
- Laravel version: 8.28.1
- Alpine version: 2.8.0
- Browser: Chrome

**Comment by joshhanley** [comment]
@PH7-Jack I tried to replicated it but it works fine for me on the versions you've listed above. Can you provide any more details or an example repo that demonstrates the issue? 

This is the component I setup 
```php
class TestComponent extends Component
{
    public $open = false;
    public $name = 'test';

    public function render()
    {
        return view('livewire.test-component');
    }
}
```

```html
<div x-data="{ open: @entangle('open'), name: @entangle('name') }">
    <button @click="open = true" x-text="name"></button>

    <ul x-show="open" @click.away="open = false">
        <li><button wire:click="archive">Archive</button></li>
        <li><button wire:click="delete">Delete</button></li>
    </ul>
</div>
```
And this is it running 
![recording (10)](https://user-images.githubusercontent.com/882837/108566985-71005f00-735b-11eb-9883-1851aa6610b9.gif)

**Comment by PH7-Jack** [comment]
@joshhanley 
After a while looking at it, I noticed that you are in the same error as the issue2531

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
