### ISSUE TITLE
Pagination view is shown twice?

### ISSUE THREAD

**Issue by ju5t** [livewire/livewire#2534]
### Description

I have two pagination views. And I don't understand why it only happens on production and not in development. This shouldn't be able to go wrong, should it?

![image](https://user-images.githubusercontent.com/3635751/108521561-271c6800-72cc-11eb-8116-de4ebbfcf36d.png)

### Exact steps to reproduce

```php
public function applyPagination($query)
{
    return $query->paginate($this->perPage);
}
```

This is what creates the pagination. In the blade view I got:

```blade
<div class="overflow-hidden text-gray-600">
    {{ $quotes->links() }}
</div>
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.28.1
- Alpine version: 2.7.3
- Browser: Chrome, but Safari too (don't think this is the cause)

**Comment by ju5t** [comment]
Ah got it. It has something to do with our purging rules in Tailwind. As this is a resource within the vendor folder we ignore it in our purge actions.

Hm, not sure what to do about this as I'm a bit reluctant to scan the entire vendor folder.

**Comment by austenc** [comment]
You could do `vendor/livewire` instead?

Or, alternatively, publish the pagination assets.

**Comment by ju5t** [comment]
I have added Livewire to the locations that we purge. That's probably the easiest.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
