### ISSUE TITLE
Broken component on GET pages, works on GET+POST (any/resource)

### ISSUE THREAD

**Issue by naszybko** [livewire/livewire#2535]
> B) Perform a check if a route is not found, to scan again with a "POST" version of the route.
> 
> I think B is a decent idea. There is already a precedence for this kind of thing with the recent locale re-lookup.
> 
> If we do B, do you see any implications? Like could someone use that behavior as a way around the persistent middleware system?

Guys, did you just killed by accident my installation?
Since the last update I started to get following errors while trying to open sliding panel with livewire component:
![Zrzut ekranu 2021-02-19 o 15 46 39](https://user-images.githubusercontent.com/459266/108519182-b2482e80-72c9-11eb-8640-7127ba721565.png)

So it works with following route (because there exists GET and POST for /offers):
```
Route::resource('offers', OffersController::class);
```
And it doesn't with this one (GET only):
```
Route::get('offers/show/w/11/1/1/2', [OffersController::class, 'showsample']);
```
If I however change the second to 
```
Route::any('offers/show/w/11/1/1/2', [OffersController::class, 'showsample']);
```
or ugly, but for test purposes:
```
Route::get('offers/show/w/11/1/1/2', [OffersController::class, 'showsample']);
Route::post('offers/show/w/11/1/1/2', [OffersController::class, 'showsample']);
```

Then it works without errors.
Looks like Livewire is checking if the POST exists and if doesn't - it throws an error, but hey, my GET was there and I don't use POST on the url. How are you deciding if GET is not found?!? I have pretty complex route path before the /offers part, with multiple domains and two parameters processed by middlewares, but it worked perfectly two days ago.

_Originally posted by @naszybko in https://github.com/livewire/livewire/issues/2461#issuecomment-782127485_

**Comment by joshhanley** [comment]
@naszybko please don't open duplicate issues. Lets keep it on the original issue #2461.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
