### ISSUE TITLE
wire:loading Bug - Cannot read property 'split' of null

### ISSUE THREAD

**Issue by sfilzek** [livewire/livewire#2537]
### Description

I have a page with a search field and simple results table. The table uses wire:loading to set the opacity during refresh.

The first search works as expected. Any subsequent update of the search which returns no matches (by adding new characters) will cause a repeating error:
```javascript
LoadingStates.js:192 Uncaught (in promise) TypeError: Cannot read property 'split' of null
    at LoadingStates.js:192
    at Array.forEach (<anonymous>)
    at startLoading (LoadingStates.js:190)
    at setLoading (LoadingStates.js:161)
    at LoadingStates.js:50
    at MessageBus.js:17
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16)
    at Object.call (HookManager.js:38)
    at Object.callHook (Store.js:120)
```
I believe this is caused by the `@forelse` in the table replacing the `<tr>` which contained the original wire:loading with a new `<tr>` in the `@empty`

If I place an additional wire:loading on the `<tr>` in the `@empty` then everything works fine, but I only want to affect the table result rows.

I believe this is the same issues as https://github.com/livewire/livewire/issues/574

### Exact steps to reproduce

Type a value into the search box, wait for 'No Results' to refresh, then add an additional character to the search box.

### Stripped-down, copy-pastable code snippets

**Livewire component**

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ReproduceError extends Component
{
    public $search;
    
    public function render()
    {
        if ($this->search == "") {
            $results = ['one', 'two', 'three'];
        }
        else {
            $results = [];
        }

        return view('livewire.reproduce-error', compact('results'));
    }
}

```
**Livewire template**

```html
<div>
    <input type="search" wire:model.debounce.250ms="search" />
    <table>
        @forelse ($results as $result)
            <tr wire:loading.class="opacity-50">
                <td>{{ $result }}</td>  
            </tr>
        @empty
            <tr>
                <td>No results</td>
            </tr>
        @endforelse
    </table>
</div>
```

**Context**
- Livewire version: 2.3.17
- Laravel version: 8.27.0
- Browser: Chrome

**Comment by theonly27** [comment]
Try to add this in your loop

`
   <tr wire:key="{{$loop->index}} wire:loading.class="opacity-50">
                <td>{{ $result }}</td>  
            </tr>
`

**Comment by sfilzek** [comment]
That fixed it, thanks! :)

I then did some googling and found this: https://laravel-livewire.com/docs/2.x/troubleshooting which explains why I needed to add wire:key, rtfm kids :)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by chrisrhymes** [comment]
I was getting the same JavaScript error, which then triggered an exception `Property [$] not found on component`. I followed the [troubleshooting](https://laravel-livewire.com/docs/2.x/troubleshooting) advice, adding a div around the blade `@if` statement and adding `wire:key=""` to the inputs and it resolved the error for me.
