### ISSUE TITLE
Serve Assets from CDN results in CORS errors

### ISSUE THREAD

**Issue by greimers** [livewire/livewire#2548]
### Description
I thought it would be elegant to serve the livewire assets JS over my CDN. 
So I set the `asset_url` in the config to `https://cdn.mydomain.com`. This works fine regarding the loading of the JS files. The CDN will grab the latest version from the server and then serve this to the browser.

But when I get CORS errors in the console as soon as I trigger a LiveWire action because LiveWire now sends POST XHR requests also to `https://cdn.mydomain.com/livewire/message/something` instead of `https://mydomain.com/livewire/message/something`.

Am I totally misunderstanding something or is this a bug? I'm not deep into the internals of how LiveWire does its magic.
I would naively expect LiveWire to use the `APP_URL` for the XHR requests and not the asset URL. 

**Context**
- Livewire version: v2.3.17
- Laravel version: 8.0
- Browser: Firefox

**Comment by hectordommo** [comment]
I have a similar problem, where Im serving my app over https, but all "post" request trying to upload files are send via http, so I can't upload files. Wonder if problems are similars. Have you find a workaround your problem ?

Livewire 2.4
Laravel 8.33
Chrome bowser 89.0.438

**Comment by greimers** [comment]
@hectordommo  No. I'm now serving the LiveWire assets from the default path (so without CDN). 
I haven't tried uploads with LiveWire yet. So unfortunately I can't give you any hint for your HTTP/HTTPS issue. 
Have you tried resetting any LiveWire config modifications you might have made?

**Comment by hectordommo** [comment]
@greimers Thank you for your response. I did clear all configuration, and caches. I think some new version mess up my installation, since every time I deploy everything gets reinstalled. Before last week It was working. I'll try to figure out what happend and report back.

**Comment by jskorlol** [comment]
@hectordommo same problem...
Call upload-file to http.. How can I solve this?
