### ISSUE TITLE
Pagination links onEachSide() method not working

### ISSUE THREAD

**Issue by mrcage** [livewire/livewire#2549]
### Description

The method onEachSide() on pagination links seems to have no effect. There are always (given enough results) 10 buttons shown on each side of the paginator. The selected theme (I am using bootstrap) seems also not to have an effect.

Livewire documentation: https://laravel-livewire.com/docs/2.x/pagination
Laravel documentation: https://laravel.com/docs/8.x/pagination#adjusting-the-pagination-link-window

### Stripped-down, copy-pastable code snippets

`{{ $orders->onEachSide(3)->links() }}`

![image](https://user-images.githubusercontent.com/1665428/108771736-bcd22480-7564-11eb-8a85-43f5e212e086.png)

**Context**
- Livewire version: 2.3.18
- Laravel version: 8.28.1
- Bootstrap version: 5.0-beta2
- Browser: Edge Chromium

**Comment by joshhanley** [comment]
@mrcage this got me the first time too.

`onEachSide` doesn't work like that. What it defines is: when you are on, say page 8 for example, that there is 3 (as per your example) numbers on each side of the 8, but **between** the `...` on each side.

In this example, I have it set to 5
![image](https://user-images.githubusercontent.com/882837/108811739-e68d5900-7601-11eb-9470-05a6eb74348c.png)


Where as this one is 2
![image](https://user-images.githubusercontent.com/882837/108811758-f5740b80-7601-11eb-8544-f64854a91895.png)

I'm going to close this as it's working fine for me. Please reopen if you are still having an issue with it.

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
