### ISSUE TITLE
Strange behavior when rendering a view containing a Vue Component

### ISSUE THREAD

**Issue by AdrianBav** [livewire/livewire#255]
(This is hard to explain, please see code examples.) When data is passed down to a vue component, it is not rendering on change. I also found some strange behavior when rendering a different variable in various places.

**To Reproduce**
1. app\Http\Livewire\Foo.php
```
class Foo extends Component
{
    public $search;
    protected $users;

    public function render()
    {
        $this->users = User::select('*')
                        ->when($this->search, function ($query, $search) {
                            return $query->where('name', 'like', "%{$search}%");
                        })
                        ->get();

        return view('livewire.foo', [
            'users' => $this->users,
        ]);
    }
}
```
2. foo.blade.php
```
<div>
    <input type="text" wire:model="search">

    <render-users :users='@json($users)'></render-users>
</div>
```

**Expected behavior**
Before introducing RendersUsers.vue, everything worked as expected. After moving the render loop to a component, I would expect it to continue to work. It however stopped working, in that correct DOM looks to be coming back from the server, but the page is not re-rendering.
Strange behavior: It does however work when $search is rendered in position (1). It does not work when $search is rendered in position (2) or (3).
```
<div>
    {{-- (1) {{ $search }} --}}
    <input type="text" wire:model="search">

    {{-- (2) {{ $search }} --}}

    <render-users :users='@json($users)'></render-users>

    {{-- (3) {{ $search }} --}}
</div>
```

**Desktop (please complete the following information):**
 - Chrome, Windows
 - "Out of the Box" Laravel 6 app

**Additional context**
RenderUsers.vue
```
<template>
    <ul>
        <li v-for="(user, i) in users">{{ user.name }}</li>
    </ul>
</template>

<script>
    export default {
        props: [
            "users",
        ],
    };
</script>
```

**Comment by robsontenorio** [comment]
Got similar issue. Sometimes props passed down to Vue component are not “reactive”.

**Comment by almeidafranci** [comment]
Any updates on this? I have experienced the same issue.

**Comment by ScripTech** [comment]
Same issue

**Comment by calebporzio** [comment]
Closing this. Vue support has been moved to a third-party package in Livewire >1.0

Please create the issue here if it still persists: https://github.com/livewire/vue
