### ISSUE TITLE
404 Errors Related to Illuminate\Routing\Middleware\SubstituteBindings

### ISSUE THREAD

**Issue by daylightstudio** [livewire/livewire#2562]
### Description
3.8 to 3.9 introduces `Livewire::getPersistentMiddleware()` in `HttpConnectionHandler` which is causing 404 errors to appear when I call a `save()` method on my Livewire Component. It seems to be related to the `\Illuminate\Routing\Middleware\SubstituteBindings::class` middleware. The original route is using a substitution binding like so `admin/team/{resource}/edit`. The `$filteredMiddleware` variable contains:
```
array:1 [▼
  5 => "Illuminate\Routing\Middleware\SubstituteBindings"
]
``` 
Just a guess, but it seems like the `$request` object is based on the original URL but the one being used in the SubstituteBindings is using the Livewire URL and so the substitution doesn't work (note the `uri` property in the Route object below):
```
Illuminate\Routing\Route {#300 ▼
  +uri: "livewire/message/{name}"
  +methods: array:1 [▶]
  +action: array:4 [▶]
  +isFallback: false
  +controller: Livewire\Controllers\HttpConnectionHandler {#460}
  +defaults: []
  +wheres: []
  +parameters: array:1 [▶]
  +parameterNames: array:1 [▶]
  #originalParameters: array:1 [▶]
  #lockSeconds: null
  #waitSeconds: null
  +computedMiddleware: array:1 [▶]
  +compiled: Symfony\Component\Routing\CompiledRoute {#468 ▶}
  #router: Illuminate\Routing\Router {#26 ▶}
  #container: Illuminate\Foundation\Application {#2 ▶}
  #bindingFields: []
}
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by joshhanley** [comment]
@daylightstudio I don't think it's the persistent middleware method that's causing the issue, as I make use of it in conjunction with route parameters (like your {resource}) and it works fine.

There has been some issues with localisation packages though, are you running any of them?

If you can provide some more detail, like what your full route looks like in your routes file (including any groups or prefixes that you may have). Also whether the component you are using is a full page component, or whether it's a nested component or component inside a traditional controller, that would be great.

Also can you please make sure you test on the latest version 2.4.0 as there were quite a few bugs fixed between 2.3.8 and 2.3.17.

Hope this helps!

**Comment by daylightstudio** [comment]
Thanks for the follow up. I think I found the issue on my end in a custom route binding that no longer works the way it was setup now with the Livewire change so will fix it on my end and close the issue. As an FYI:

- I'm not using any localization packages.
- The route is under an `admin` group and is `/team/{resource}/edit` so the full route is `admin/team/{resource}/edit`
- The component calling the `save()` function is not nested and is the main Livewire component on the page.
- I actually discovered the issue because I updated to 2.4.0 and worked backwards to find the version that caused the issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
