### ISSUE TITLE
Disk used for file uploaded is hardcoded in testing environments

### ISSUE THREAD

**Issue by kajgies** [livewire/livewire#2566]
The disk used in testing environments is currently hardcoded with no override possible:
FileUploadConfiguration.php Line 27:
```
    public static function disk()
    {
        if (app()->environment('testing')) {
            return 'tmp-for-tests';
        }

        return config('livewire.temporary_file_upload.disk') ?: config('filesystems.default');
    }
```
This means that in a testing environment you have no choice to add a 'tmp-for-tests' disk to your filesystems config, otherwise file uploads will give an error.

I think it would be a good idea to remove this hardcoded requirement and make the disk environment specific in the config using env(),

**Comment by kajgiesbersflavour** [comment]
Also the cause of this issue:  #1341

**Comment by kajgies** [comment]
Also the cause of this issue:  #1341

**Comment by PhiloNL** [comment]
@kajgies could you leave a comment at https://github.com/livewire/livewire/pull/2571#issuecomment-788035594 with some more information why this is something you would like to see? 😄
