### ISSUE TITLE
Many-to-many relationships on a component public property of type model are not hydrated

### ISSUE THREAD

**Issue by penagos** [livewire/livewire#2574]
### Description
Relationships on a public property on a Livewire Component of type Model are not treated as Laravel Collections after a Component is updated, they are treated as arrays.

### Goal
What I'd like to achieve is to add a new child to MyModel (without triggering a commit to the DB) on clicking a button. The actual commit of the children will be done elsewhere by a different action.

### Relevant Issue
https://github.com/livewire/livewire/issues/27 is similar to this issue, though the problem I am hitting is through one additional layer of indirection. I.e. instead of the topmost property on the Container not being re-interpreted as a Model, it's a relationship on the Model that's not being hydrated back to a Collection.

### Exact steps to reproduce
Create a model with a many-to-many relationship to another existing model (`SomeOtherModel`):
```
class MyModel extends Model
{
    use HasFactory;
    public function children()
    {
        return $this->belongsToMany(SomeOtherModel::class);
    }
}
```

Create a Livewire component containing the model as a public property and an action method `foo`:
```
class MyComponent extends Component
{
    public MyModel $m;

    public function mount($id)
    {
        $this->m = MyModel::findOrFail($id);
    }

    public function foo()
    {
        // Will error on subsequent update
        $this->m->children->add(new MyModel());
    }
}
```
Lastly, create a view to hit the `foo` action:
```
<ul>
@foreach ($m->children as $child)
    <li>{{ $child->name }}</li>
@endforeach
</ul>
<button wire:click.prevent="foo" class="btn btn-primary">Add Child</button>
````

Clicking on the button will result in:
```
Call to a member function add() on array 
```

It seems that in the process of sending the children data back serverside, the children property on m is kept as an array and not hydrated back to be a Laravel collection. Do I need to perform such hydration myself? It seems the topmost (`MyModel`) type property is hydrated, but it's relationship to `SomeOtherModel` is not hydrated back to a collection. Is the explicit hydration a design choice? Or should the Livewire framework recursively hydrate?

### Workaround
For the time being, I have manually hydrated the collection in question in `MyComponent` with:
```
public function hydrateM()
{
    $this->m->children = SomeOtherModel::hydrate($this->m->children);
}
```
This seems to circumnavigate the issue for me, but it would be great if the framework did this out of the box.

**Context**
- Livewire version: 2.4
- Laravel version: 8.17.2
- Browser: Firefox
- OS: Linux

**Comment by joshhanley** [comment]
@penagos it should re-hydration relations properly. But maybe you need to call load on it first, so in mount change it to
```php
$this->m = MyModel::with('children')->findOrFail($id);
```

Or you could do 
```php
$this->m = MyModel::findOrFail($id);
$this->m->load('children');
```

Can you try that and let us know if that works or not?

**Comment by penagos** [comment]
@joshhanley that seemed to do the trick; thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by torian257x** [comment]
is this still a thing?
