### ISSUE TITLE
Livewire redirects the page to /livewire/message/<component-name>

### ISSUE THREAD

**Issue by jochemgruter** [livewire/livewire#2576]
### Description
After my app does an oauth, the user will be redirected to a page with a livewire component. But instead of displaying the page, the user will be redirected to: `/livewire/message/<component-name>`. And this page returns the error:

`The GET method is not supported for this route. Supported methods: POST.`

The strange thing is that this is only the case when there is a function added in my component. When I remove the `detachMailchimp` function, then there is no redirect.

```
class ExportMailchimpForm extends Component
{
    public function render(Organisation $organisation, MailchimpClient $mailchimp)
    {
        return view('cp.livewire.export-mailchimp-form',  [
            'organisation' => $organisation,
            'mailchimpLogin' => $mailchimp->oauthLoginUrl(),
        ]);
    }

    public function detachMailchimp(Organisation $organisation)
    {
        $organisation->mailchimp_access_token = null;
        $organisation->save();
    }
}
```

### Exact steps to reproduce
It's a bit complex to reproduce I guess.

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.4.0
- Laravel version: 8.21
- Alpine version: 2.7.3
- Browser: chrome

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
