### ISSUE TITLE
Possible solution for some diffing / patching issues

### ISSUE THREAD

**Issue by ncharalampidis** [livewire/livewire#2578]
I was experiencing strange behaviour when toggling a checkbox and I realised that the problem was because of multiple events attached to the element.

After playing around with the livewire's js files I found out that even when I had set an explicit wire:key to the checkbox, the morphdom's "onNodeAdded" event was called and that caused the duplicate event to be registered.

I found out this [bug fix](https://github.com/patrick-steele-idem/morphdom/pull/194/files) in the original morphdom repository and when I applied it to livewire the problems gone.

Can someone with deep knowledge on livewire check it out? It may be a bug fix that should be merged.

**Comment by austenc** [comment]
Hi @ncharalampidis I'm curious if you were using Alpine as well when you saw this behavior?

**Comment by ncharalampidis** [comment]
No it is not related to Alpine. Check the pull request #2580. I added a test that reproduces the issue.

**Comment by austenc** [comment]
Was investigating another issue last week and wanted to double check. Thank you!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
