### ISSUE TITLE
input inline-edit with Chinese character, the wire:blur event will triggered in a loop

### ISSUE THREAD

**Issue by guoxiangke** [livewire/livewire#2590]
### Description
I use input with wire:blur for inline-edit, but it's not working with collections(models load from laravel)
it enters a loop. 
![2021-03-05_07-52-49 (1)](https://user-images.githubusercontent.com/1160703/110047184-61840b80-7d88-11eb-922e-106ecf74c5de.gif)

### Exact steps to reproduce
![image](https://user-images.githubusercontent.com/1160703/110046535-2d5c1b00-7d87-11eb-901a-4532211e4a48.png)
![image](https://user-images.githubusercontent.com/1160703/110046559-3816b000-7d87-11eb-8064-c888113b4523.png)

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: ^2.0
- Laravel version: ^8.12
- Browser:  Chrome

**Comment by guoxiangke** [comment]
But it works with a static model like this:
![image](https://user-images.githubusercontent.com/1160703/110044512-3992a900-7d84-11eb-9c57-ca6556e4bd1e.png)

**Comment by guoxiangke** [comment]
The bug is the value.  @calebporzio 
if I use Chinese, the event  triggered in a loop.
![image](https://user-images.githubusercontent.com/1160703/110199099-9b8d0480-7e91-11eb-9a62-93690f7c6123.png)

**Comment by joshhanley** [comment]
@guoxiangke can you please let us know specifically which versions of Livewire and Laravel you are using?

To find out, run `composer show -D` and it should tell you the current major, minor and patch versions you are running.

Thanks!

**Comment by guoxiangke** [comment]
composer show -D
```
appstract/laravel-options         5.2.0   Global options loaded from the database
barryvdh/laravel-debugbar         v3.5.2  PHP Debugbar integration for Laravel
beyondcode/laravel-query-detector 1.4.0   Laravel N+1 Query Detector
dragonmantank/cron-expression     v3.1.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
facade/ignition                   2.5.11  A beautiful error page for Laravel applications.
fakerphp/faker                    v1.13.0 Faker is a PHP library that generates fake data for you.
fideloper/proxy                   4.4.1   Set trusted proxies for Laravel
fruitcake/laravel-cors            v2.0.3  Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
guzzlehttp/guzzle                 7.2.0   Guzzle is a PHP HTTP client library
laravel/framework                 v8.27.0 The Laravel Framework.
laravel/horizon                   v5.7.0  Dashboard and code-driven configuration for Laravel queues.
laravel/jetstream                 v2.1.4  Tailwind scaffolding for the Laravel framework.
laravel/sail                      v1.3.1  Docker files for running a basic Laravel application.
laravel/sanctum                   v2.9.0  Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
laravel/tinker                    v2.6.0  Powerful REPL for the Laravel framework.
livewire/livewire                 v2.3.17 A front-end framework for Laravel.
mockery/mockery                   1.4.2   Mockery is a simple yet flexible PHP mock object framework
mvdnbrk/laravel-model-expires     v1.8.1  A package to assign expiration dates to Eloquent models
nunomaduro/collision              v5.3.0  Cli error handling for console/command-line PHP applications.
phpunit/phpunit                   9.5.2   The PHP Unit Testing framework.
plank/laravel-metable             5.0.0   A package for attaching arbitrary data to Eloquent models
predis/predis                     v1.1.6  Flexible and feature-complete Redis client for PHP and HHVM
spatie/laravel-activitylog        3.16.1  A very simple activity logger to monitor the users of your website or application
spatie/laravel-medialibrary       8.10.1  Associate files with Eloquent models
spatie/laravel-permission         4.0.0   Permission handling for Laravel 6.0 and up
spatie/laravel-tags               3.0.2   Add tags and taggable behaviour to your Laravel app
```

**Comment by guoxiangke** [comment]
Here is my code for test: same as Japanese. 
and if I put Chinese/Japanese on the input for update of 3 or 4, the same error.
```
public $models;

    public function mount()
    {
        $this->models = [
            ['id'=>1,'remark'=>'中文'], // not work! enter loops
            ['id'=>2,'remark'=>'Chinese'], //works
            ['id'=>3,'remark'=>'たていす'], // not work! enter loops
            ['id'=>4,'remark'=>'japanese'], //works
        ];   
    }
```

```
@foreach ($models as $contact)
        <input type='text' class="mt-2 text-sm sm:text-base pl-2 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" 
            wire:blur.stop="updateRemark($event.target.value)" 
            wire:key="contact-{{ $contact['id'] }}" 
            value="{{ $contact['remark'] }}" />
    @endforeach
```

**Comment by joshhanley** [comment]
@guoxiangke not sure if it is related, but this PR #2437 was merged in 2.3.18 which has to do with non-latin characters.

Can you try upgrading Livewire to the latest version (2.4.0) and testing it, and let us know how you go?

**Comment by guoxiangke** [comment]
Good job, fixed! thanks very much. @joshhanley

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
