### ISSUE TITLE
TemporaryUploadedFile getPath() method returns tmp path

### ISSUE THREAD

**Issue by daylightstudio** [livewire/livewire#2598]
I'm using Spatie's Media Library package and that package uses the `getPath()` method:
https://github.com/spatie/laravel-medialibrary/blob/227b47bd001df05a7f3fdc7c7e5d801def61be27/src/MediaCollections/FileAdder.php#L104

However, the `getPath()` method is returning a path to a file that doesn't exist and is causing upload errors:
```
/private/var/tmp/qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif
```

I noticed that the `TemporaryUploadedFile` class isn't overwriting that method like the others to create the correct path and it seems like it should?
https://github.com/livewire/livewire/blob/b647ac63378ea02bdac975f70a4e57aea84bda0b/src/TemporaryUploadedFile.php#L21

Suggestion would be to add the something like the following:
```
public function getPath()
{
    return dirname($this->storage->path($this->path));
}
```

**Comment by tahirafridi** [comment]
I'm facing the same problem. Medialibrary can not read the temp file from livewire, as livewire made it protected and hashed so it can not be accessible by other libraries. Anyone here can provide work around?

**Comment by tahirafridi** [comment]
> I'm using Spatie's Media Library package and that package uses the `getPath()` method:
> https://github.com/spatie/laravel-medialibrary/blob/227b47bd001df05a7f3fdc7c7e5d801def61be27/src/MediaCollections/FileAdder.php#L104
> 
> However, the `getPath()` method is returning a path to a file that doesn't exist and is causing upload errors:
> 
> ```
> /private/var/tmp/qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif
> ```
> 
> I noticed that the `TemporaryUploadedFile` class isn't overwriting that method like the others to create the correct path and it seems like it should?
> https://github.com/livewire/livewire/blob/b647ac63378ea02bdac975f70a4e57aea84bda0b/src/TemporaryUploadedFile.php#L21
> 
> Suggestion would be to add the something like the following:
> 
> ```
> public function getPath()
> {
>     return dirname($this->storage->path($this->path));
> }
> ```

I make it work
Because using livewire, file already uploaded to livewire-tmp directory, so here I used
`
$row->addMedia($this->image->path())->toMediaCollection('original');
`

Notice addMedia() method, and also the path() method from livewire. Before I was trying to addMediaFromRequest() and it was failing, because the $this->image has uploaded file not the requested file. I hope it will help you some how!

**Comment by daylightstudio** [comment]
Thanks @tahirafridi, that did the trick for me! Much appreciated.

Seems like that method should still probably be updated unless it was excluded for some reason.

**Comment by tahirafridi** [comment]
I'm glad that it works for you @daylightstudio
