### ISSUE TITLE
Nested Component problem

### ISSUE THREAD

**Issue by doaaAbdelfatah** [livewire/livewire#2604]
### Description
Hi, I have a problem with nested component when add nested component inside another livewire component and I set for the nested component different keys 
but when I use the main component for example search or the nested component it stop livewire and need refresh to resume working it seams as hanging livewire
please help me to know that 
Thanks

![problem](https://user-images.githubusercontent.com/55490863/110236837-bd919000-7f40-11eb-8e6c-585eab10b38d.png)

**Comment by ncharalampidis** [comment]
Try this PR #2580

I had a similar issue with keyed component inside a table and this patch fixed my issue.

**Comment by joshhanley** [comment]
@doaaAbdelfatah and @ncharalampidis I used nested components in tables without any issues. Would one of you be able to provide a sample repo that demonstrates the problem so we can have a look?

Ideally, if @ncharalampidis' patch in PR #2580 fixes the issue and is merged, that'd be great. But in the meantime we can see if there is a work around.

**Comment by ncharalampidis** [comment]
The work around in my case was to wrap the if statement in a <div>

In this case maybe @doaaAbdelfatah could try to wrap the "can" statement in a <div>.

**Comment by samhk222** [comment]
for me wapping around a div didn't work ... when livewire updates, all my child components are gone! (it's a TR by the way). I'm looking for the merge of this PR

**Comment by joshhanley** [comment]
@doaaAbdelfatah or @samhk222 do you get can console errors? Livewire stopping suggests a JS issue. If you have console errors, can you share a screenshot?

@samhk222 if you can share a repo that demonstrates the issue, I'd be happy to have a look for you.

**Comment by calebporzio** [comment]
Ok, just merged #2580 - closing this. Thanks everyone!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
