### ISSUE TITLE
Implicit route-model parameters don't work in query strings

### ISSUE THREAD

**Issue by nihilsen** [livewire/livewire#2605]
### Description
The query string functionality supports named route parameters.

However, when these are implicitly bound route-model parameters, it breaks down and the following error is thrown: `ErrorException: "Array to string conversion"`.

This is because we don't convert implicitly bound route-model parameters back into their route key equivalents when we update the query string, so in `Illuminate/Routing/RouteUrlGenerator::replaceNamedParameters()` we try to pass the model directly, which fails.

### Exact steps to reproduce
- Use any implicit route model parameters in your Livewire component.
- Include that in your `$queryString` property.
- Attempt to update the property.

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by nihilsen** [comment]
It turns out this issue affects only optional route parameters, and specifically going from changing an optional route parameter from null to not-null. Otherwise, history sync of route parameters appears to be working fine.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
