### ISSUE TITLE
@entangle won't work with array property "Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

### ISSUE THREAD

**Issue by turboMagneTT** [livewire/livewire#2611]
I have a forelse and for every element I must have 2 datepickers and other text fields that I will omit for now. I'm using pikaday, Laravel blade component and Alpine to make everything work. The solution work when i'm not in a foreach, in fact, I got the problem everytime I send a string with dots to the @entangle blade directive.

The exact error I get is "Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" and the pikaday doesn't work. I guess it just break the JS.

First, my blade loop (my index here is simply an incrementing int) :
```
@foreach ($anomalies as $index => $anomaly)

    <div wire:key="anomalies_{{ $index }}">

        // Some texts fields

        <x-input.group label="Date" for="anomalies.{{ $index }}.timelineDate" required>
            <x-input.date wire:model="anomalies.{{ $index }}.timelineDate"
                          name="aontributoryAnomalies.{{ $index }}.timelineDate"
            />
        </x-input.group>

    </div>

@endforeach
```

And here is my blade component for the date  picker: 
```
@props([
    'min' => null,
    'max' => null,
])

<div
    x-data="{ value: @entangle($attributes->wire('model')) }"
    x-init="
        new Pikaday({
            field: $refs.datetimeInput,
            format: 'YYYY-MM-DD',
            @if ($min) minDate: new Date('{{ $min }}'), @endif
            @if ($max) maxDate: new Date('{{ $max }}'), @endif
            i18n: {
                previousMonth : 'Mois précédent',
                nextMonth     : 'Mois prochain',
                months        : ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
                weekdays      : ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
                weekdaysShort : ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam']
            }
        });
    "
    x-on:change="value = $event.target.value"
    class="flex input-group"
>

    <div class="input-group-prepend">
        <span class="input-group-text"><i class="fas fa-calendar"></i></span>
    </div>

    <input
        {{ $attributes->whereDoesntStartWith('wire:model') }}
        x-ref="datetimeInput"
        x-bind:value="value"
        type="text"
        placeholder="AAAA-MM-JJ"
        class="form-control"
    />

</div>
```

I tried using 'anomalies.0.timelineDate' instead of $attributes->wire('model') in the @entangle directive but it doesn't work.

**Context**
- Livewire version: 2.3.18
- Laravel version: 8.28.1
- Alpine version: [e.g. 2.3.0]
- Browser: Firefox

**Comment by joshhanley** [comment]
@turboMagneTT can you also share what your component class looks like?

**Comment by turboMagneTT** [comment]
@joshhanley Thank you for looking in this issue.

I'm not sure what I should include because my component is already 250+ lines. I think the interesting part is probably the property declaration.

```
/*** Other imports ***/
use Livewire\Component;
use Livewire\WithFileUploads;

class AccidentInvestigationWizard extends Component
{
    use WithFileUploads;

    public $testMode = false;

    public $currentStep = 1;
    public $steps       = [
        'Identification',
        'L\'accident',
        'L\'analyse',
        'Précision des faits',
    ];

    public $incidentReport;

    // Step 1
    public $applicantFirstname;
    public $applicantLastname;
    public $applicantEmail;
    public $applicantService;
    public $applicantDivision;
    public $applicantTitle;

    // Step 2

    // Step 3
    public $investigators      = [];
    public $accidentHasEnvironmentImpact;
    public $realCategory;
    public $potentialCategory;
    public $incidentLocation;
    public $incidentType;
    public $incidentInBriefExplanation;
    public $investigationFiles = [];

    // Step 4
    public $accidentFacts   = [];
    public $anomalies       = [];

    public function render()
    {
        return view(
            'accidentInvestigation.accidentInvestigationWizard',
            [
                'cityServiceTypes'       => CityServiceType::keyValues(),
                'incidentTypes'          => IncidentType::keyValues(),
                'accidentFactCategories' => AccidentFactCategory::keyData(),
            ]
        );
    }

   public function addAnomaly(string $accidentFactCause = '')
    {
        $this->anomalies[] = [
            'cause' => $accidentFactCause,
        ];
    }

    public function removeAnomaly($index)
    {
        unset($this->anomalies[$index]);
    }

    public function verifyIfFactIsContributoryAnomaly($accidentFactType, $factIndex)
    {
        $fact = $this->accidentFacts[$accidentFactType][$factIndex];

        if ($fact['isAnomaly'] && $fact['isContributory']) {
            $this->addAnomaly($fact['description']);
        }
    }

  /*** Other functions ***/

 }
```

**Comment by joshhanley** [comment]
@turboMagneTT are you looping through a collection or just an array? Maybe try adding a rules array and see if that works. 

Otherwise, you could try and pull my PR in from here PR #2592, and see if it gives you a better/ more helpful error message.

Hope this helps!

**Comment by turboMagneTT** [comment]
@joshhanley Thank you for the response. I now understand what was the problem. I wasn't instantiating every properties of my array each time I had a new one. 

Just to be super clear for other people that might get this problem : Be sure that your property exist on your Livewire component especially if it is in a array.

**Comment by joshhanley** [comment]
@turboMagneTT no worries. Glad you worked it out!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
