### ISSUE TITLE
Chrome autofill values on non-lazy fields are immediately cleared out

### ISSUE THREAD

**Issue by divspace** [livewire/livewire#2612]
### Description

The fix for #2340 is what introduced this bug, because in Livewire 2.3.17 this bug does not exist.

When you autofill in Chrome, the values are immediately stripped out if they are called with `wire:model` or `wire:model.defer`.

Anything called with `wire:model.lazy` will keep the autofill values.

> In Safari, this will actually break because when you use autofill on a field that is lazy, the hydration process will set that value to `null` (so you can no longer type-hint), so it will fail validation as well even though there's a value "set." Once you fix the type-hinting by removing it or allowing for `null` too, auto-complete works. This doesn't seem to happen in Chrome though, I can only do this in Safari autofill with lazy fields that are type-hinted without accounting for `null` even though they are set to empty strings on mount.

### Exact steps to reproduce

Add three text fields to a form, one with `wire:model`, one with `wire:model.defer`, and one with `model:wire.lazy` and make sure they are fillable by the browser (so `name`, `email`, `zip_code`, etc.). Open the page and try to autofill the values, you'll see them get filled then stripped.

**Context**
- Livewire version: > 2.3.17
- Laravel version: 8.31.1
- Browser: Chrome, Safari

I'm currently tracking down what actually fixes this (besides staying on `2.3.17`).

**Comment by divspace** [comment]
This file on line 70 is the issue:

    js/node_initializer.js

Here's the difference:

```bash
@@ -70,7 +70,7 @@
             || directive.modifiers.includes('lazy') ? 'change' : 'input'

         // If it's a text input and not .lazy, debounce, otherwise fire immediately.
-        let handler = debounceIf(hasDebounceModifier || (DOM.isTextInput(el) && !isLazy), e => {
+        let handler = debounceIf(hasDebounceModifier || (DOM.isTextInput(el) && (!isLazy || !el.wasRecentlyAutofilled)), e => {
             let model = directive.value
             let el = e.target
```

When you revert this line back, autofill works again on both browsers, and you can change the type-hint to just `string` instead of `?string` to avoid the PHP error in Safari.

**Comment by leitom** [comment]
Thank you for finding a solution to this @divspace It was a "mind boggling" issue :)
