### ISSUE TITLE
Couldnt open laravel-livewire.com site

### ISSUE THREAD

**Issue by SadeghPM** [livewire/livewire#2614]
Hi @calebporzio 
I could not open https://laravel-livewire.com/ from iran.
Im using manjaro linux with gnome desktop:

```shell
~  wget https://laravel-livewire.com/                                                                                                                                                                     
--2021-03-10 09:48:36--  https://laravel-livewire.com/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving laravel-livewire.com (laravel-livewire.com)... 2606:4700:3033::6815:4810, 2606:4700:3036::ac43:adbf, 104.21.72.16, ...
Connecting to laravel-livewire.com (laravel-livewire.com)|2606:4700:3033::6815:4810|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
```

```shell
~  curl laravel-livewire.com
curl: (52) Empty reply from server
```

**Comment by SomePlayer** [comment]
It is working fine for me right now. Can you access through a vpn?

**Comment by SadeghPM** [comment]
> It is working fine for me right now. Can you access through a vpn?

Works fine with vpn! Maybe ISP problem.

**Comment by SomePlayer** [comment]
Could be many things, eager filter for certain words comes to mind. Take care

**Comment by danharrin** [comment]
Hey! Gonna close this issue, looks like a false censorship problem unfortunately.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
