### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by Fredericld** [livewire/livewire#2617]
Hello,

I keep getting this error on my remote staging server when interacting with my component. 
The GET method is not supported for this route. Supported methods: POST.

Request URL: https://www.mywebsite.co.uk/livewire/message/admin.add-edit-client-users
Request Method: POST
Status Code: 405 

I can interact with the component a little and after a few clicks it fails. The strange things is I can interact with the component on my local machine and I get not errors at all.

I have commented out pretty much all my code

the php
```
namespace App\Http\Livewire\Admin;

use Livewire\Component;

public $activeTab;

public function mount()
{
     $this->activeTab = "user-details";
}

public function updateTab($tabName)
    {
        $this->activeTab = $tabName;
    }

    public function render()
    {
        return view('livewire.admin.add-edit-client-users');
    }
}
```

blade
```
<div>

    <form wire:submit.prevent="submit">

        <ul class="nav nav-tabs mydir-tabs" role="tablist">

            <li class="nav-item">
              <a class="nav-link @if ($activeTab == "user-details") active @endif" data-toggle="tab" href="#user-details" wire:click="updateTab('user-details')">User details</a>
            </li>
            <li class="nav-item">
              <a class="nav-link @if ($activeTab == "additional-information") active @endif" data-toggle="tab" href="#additional-information" wire:click="updateTab('additional-information')">Additional information</a>
            </li>
            <li class="nav-item">
              <a class="nav-link @if ($activeTab == "institution") active @endif data-toggle="tab" href="#institution" wire:click="updateTab('institution')">Institution</a>
            </li>

        </ul>


        <!-- Tab panes -->
        <div class="tab-content">
                ...
        </div>

    </form>

</div>
```

clicking on the tabs wire:click triggers a functions that updates 1 variable. it works for 4, 5 clicks but fails after that.... It is quite frustrating because I don't understand the issue. Why does it work for the first few clicks and then fails?

Is it my code that is wrong is there something else not quite working with livewire.

Tested with
- Livewire version: [e.g. 2.4.0]
- Laravel version: [e.g. 8.32.1]
- Alpine version: [e.g. 2.8.0]
- Browser: Chrome, Firefox

**Comment by divspace** [comment]
My only thought is if it's working locally but not remotely, that maybe you need to check [this file](https://github.com/laravel/laravel/blob/177e05beec2d1e35b48baad59441050644eecd2c/app/Http/Middleware/TrustProxies.php#L15), particularly the `$proxies` property. If you set that property to (I have to do this on every project):

```php
protected $proxies = '*';
```

And clear the cache, does that resolve the issue? Otherwise, it'd be helpful to see your routes file as well (also stack trace).

**Comment by Fredericld** [comment]
Hi,

Updating the proxy has not made fixed the issue.
I think the issue has more something to do with livewire not working quite right. As I said the component works for a little while but as it fails after a few clicks

Here is the strack trace

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: The GET method is not supported for this route. Supported methods: POST. in file /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php on line 117

#0 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php(103): Illuminate\Routing\AbstractRouteCollection-&gt;methodNotAllowed(Array, 'GET')
#1 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php(40): Illuminate\Routing\AbstractRouteCollection-&gt;getRouteForMethods(Object(Illuminate\Http\Request), Array)
#2 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/CompiledRouteCollection.php(144): Illuminate\Routing\AbstractRouteCollection-&gt;handleMatchedRoute(Object(Illuminate\Http\Request), NULL)
#3 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\Routing\CompiledRouteCollection-&gt;match(Object(Illuminate\Http\Request))
#4 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router-&gt;findRoute(Object(Illuminate\Http\Request))
#5 /home/web/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#6 /home/web/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#7 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#8 /home/web/site/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /home/web/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /home/web/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /home/web/site/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/web/site/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /home/web/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/web/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#20 /home/web/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /home/web/site/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#22 {main}

**Comment by divspace** [comment]
Wrap your Blade `@if` conditionals in `<div>` tags, per the [troubleshooting docs](https://laravel-livewire.com/docs/2.x/troubleshooting). Also, a copy of the routes file if that fails.

**Comment by Fredericld** [comment]
@divspace 

I have many many routes but the one we are interested in are
```
Route::prefix('/admin/')->middleware('web','auth:admin','admin')->name('admin.')->namespace('Admin')->domain('www.'.$domain)->group(function(){

   Route::resource('users', 'UserController', ['except' => ['show']]);

});
```

and the auto created livewire routes 
```
                                     | GET|HEAD  | livewire/livewire.js                                    | generated::ggwF1Yy225ckxCTo                      | Livewire\Controllers\LivewireJavaScriptAssets@source                            |                                                        |
|                                     | GET|HEAD  | livewire/livewire.js.map                                | generated::zWZOuh8ss1bkloXT                      | Livewire\Controllers\LivewireJavaScriptAssets@maps                              |                                                        |
|                                     | POST      | livewire/message/{name}                                 | livewire.message                                 | Livewire\Controllers\HttpConnectionHandler                                      | web                                                    |
|                                     | GET|HEAD  | livewire/preview-file/{filename}                        | livewire.preview-file                            | Livewire\Controllers\FilePreviewHandler@handle                                  | web                                                    |
|                                     | POST      | livewire/upload-file                                    | livewire.upload-file                             | Livewire\Controllers\FileUploadHandler@handle                                   | web                                                    |

```

I reduced the template to 
```
<div>

<a class="nav-link active" data-toggle="tab" href="#additional-information" wire:click="updateTab('additional-information')">Additional information</a>
</div>
```

and I still get the issue...

**Comment by divspace** [comment]
My only other suggestion is to add `.stop` to this: `wire:click` so you have `wire:click.stop`. This will stop the propagation.

**Comment by Fredericld** [comment]
The issue has been solved!
The Apache Module: Evasive was the issue

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
