### ISSUE TITLE
many request sends

### ISSUE THREAD

**Issue by doaaAbdelfatah** [livewire/livewire#2629]
### Hello first , I have a problem when I send request to do action using livewire wire: click  and the internet connection cutting the requests cached and all of them send after internet recover  if any one can help me about this issue I want send the request only one time even the internet on  or off

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

**Comment by s1x** [comment]
Hey @doaaAbdelfatah 

for me its unclear what the specific use case is, but assuming that we're talking about a form you might be able to solve what you're looking for via utilising the [offline state](https://laravel-livewire.com/docs/2.x/offline-state) and the [deferred] properties. (https://laravel-livewire.com/docs/2.x/properties#deferred-updating).

That way you could only send a form prevent submitting the data when its offline while sending everything in batch as soon its back.

**Comment by nuernbergerA** [comment]
Hey @doaaAbdelfatah 

if I understand you, you are talking about user experience with a bad internet connection.

My advice would be to use `.defer` or `.lazy` as much as you can so you reduce the number of requests sent.
You can use `wire:offline` and `wire:dirty` to indicate the state to users.

---
https://laravel-livewire.com/docs/2.x/properties#deferred-updating
https://laravel-livewire.com/docs/2.x/offline-state
https://laravel-livewire.com/docs/2.x/dirty-states

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by doaaAbdelfatah** [comment]
Please i  have the same problem the request send many times and i uses dirty and offline attributes
Can any one help me?
