### ISSUE TITLE
can't access a new(not by Model::create) public model in mount

### ISSUE THREAD

**Issue by guoxiangke** [livewire/livewire#2630]
![image](https://user-images.githubusercontent.com/1160703/111226678-711f1200-861c-11eb-8a20-b3e2b0624523.png)
I can't access the $this->wechatContent in send method.
And even line 56 has value, I also couldn't use $wechatContent->name in the template.  
THANKS

**Comment by guoxiangke** [comment]
If I changed to an exsit one like this, 
`$this->wechatContent = WechatContent::find(1);`
it works.

**Comment by joshhanley** [comment]
@guoxiangke as the model hasn't been persisted yet, it won't have an ID that Livewire can deserialise it with (like when you are using `find(1)`).

You need to add a rules array and list all of the properties that you want Livewire to keep track of for you, before you persist it.

Hope this helps!

**Comment by guoxiangke** [comment]
@joshhanley thanks a lot， fixed with 
```
    public function rules() { 
        return [
            'editing.name' => 'required|min:3',
            'editing.type' => 'required',
            'editing.wechat_bot_id' => 'required',
            'editing.content' => 'required',
        ];
    }



        $this->editing = new WechatContent([
            'name'=>'请输入发送内容...', 
            'type' => $type,
            'wechat_bot_id' => 1,
            'content'=>compact('data')
        ]);
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
