### ISSUE TITLE
How to trigger an action with a condition?

### ISSUE THREAD

**Issue by guoxiangke** [livewire/livewire#2631]
here is my code:
`wire:keydown.enter="attachTag({{$wechatBotContact->id}}, $event.target.value)"`
I want CHECK before send action like this:
`$event.target.value!=''` &&  attachTag({{$wechatBotContact->id}}, $event.target.value)`

thanks.

**Comment by joshhanley** [comment]
@guoxiangke I'd suggest using Alpine to handle the click for you. `$event` is an Alpine helper.

Then you can call the Livewire method from Alpine using `@this.call('attachTag', {{$wechatBotContact->id}})` once the expression is true.

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
