### ISSUE TITLE
livewire:load event aren't triggered on nested component

### ISSUE THREAD

**Issue by yadounis** [livewire/livewire#2636]
### Description
When you add a conditional nested component and when the component is loaded (the condition is true) the event "livewire:event" is not triggered inside the child component.

### Exact steps to reproduce
- Parent component
![Screen Shot 2021-03-16 at 10 06 17](https://user-images.githubusercontent.com/306859/111283291-41cdcc80-863f-11eb-93aa-062d3dc1ebba.png)

- Child component
![Screen Shot 2021-03-16 at 10 06 52](https://user-images.githubusercontent.com/306859/111283370-5611c980-863f-11eb-9987-c853cd68d6b8.png)

**Context**
- Livewire version: 2.4.0
- Laravel version: 8.32.1
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@yadounis livewire:load only runs when the Livewire JS framework boots, not everytime a component is initialised. 

For that you need to use `component.initialized` check it out here
https://laravel-livewire.com/docs/2.x/lifecycle-hooks#js-hooks:~:text=component.initialized,-Called

Hope this helps!

**Comment by yadounis** [comment]
@joshhanley Just tested it but not firing too ... 

![Screen Shot 2021-03-18 at 09 40 04](https://user-images.githubusercontent.com/306859/111596884-eda52280-87cd-11eb-9eac-3ecb56494278.png)

Is it maybe because i'm conditioning the call to the child component ?

![image](https://user-images.githubusercontent.com/306859/111597028-162d1c80-87ce-11eb-9edf-118667acf362.png)

Thank you.

**Comment by joshhanley** [comment]
@yadounis can you share your code (enough so the issue can be replicated) or provide an example repo so I can get a better idea of how you have structured it all?

Please copy and paste the code and put it in code blocks instead of the screenshots, so someone else can copy the code and potentially run it.

\```php
// Php code here
\```

\```html
// HTML and blade code here
\```

**Comment by nuernbergerA** [comment]
Closed due to inactivity

Thanks @joshhanley for your fantastic help (as always)!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
