### ISSUE TITLE
Livewire re-render call x-init always

### ISSUE THREAD

**Issue by PH7-Jack** [livewire/livewire#2638]
### Description
When livewire renders the page again, the alpine child components are initialized again
If you do not use **requestAnimationFrame** in x-init, components are initialized in reverse order

### Exact steps to reproduce
When testing, do a test by removing the **requestAnimationFrame** function, to see the x-init happening in reverse
https://laravelplayground.com/#/snippets/ed3be8b0-ef46-46c8-8781-67ce7796d297

**SOLUTION** for x-init when re-render: https://github.com/alpinejs/alpine/pull/1160 

**Context**
- Livewire version: 2.4.0
- Laravel version: 8.33.1
- Alpine version: 2.8.1
- Browser: Chrome

**Comment by PH7-Jack** [comment]
@jayhealey resolved this issue in https://github.com/alpinejs/alpine/pull/1160

**Comment by joshhanley** [comment]
I believe recent `$wire` fix also applies to this issue. Please update Alpine to 2.8.2 to get the fix (there is no Livewire update needed).

Let me know if it doesn't and I will reopen 🙂

Hope this helps!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
