### ISSUE TITLE
Pagination Published Views - not being used

### ISSUE THREAD

**Issue by journeyman73** [livewire/livewire#2640]
I have published the views for pagination and made the changes in the tailwind view to match my design and the published view is not being used with {{ $users->links() }}

Also if i use {{ $users->links('vendor.livewire.tailwind') }} to call the view, the links are not being populated correctly. 

I have changed nothing else in the file.
I am doing something wrong or is there an issue?
  <div>
                      <span class="relative z-0 inline-flex shadow-sm">
                          <span>
                              {{-- Previous Page Link --}}
                              @if ($paginator->onFirstPage())
                                  <span aria-disabled="true" aria-label="{{ __('pagination.previous') }}">
                                      <span class="relative inline-flex items-center px-2 py-2 text-sm font-normal text-vitalfluid-blue-200 bg-white border border-vitalfluid-gray-400 cursor-default rounded-l-md leading-5" aria-hidden="true">
                                          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                              <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                                          </svg>
                                      </span>
                                  </span>
                              @else
                                  <button wire:click="previousPage" dusk="previousPage.after" rel="prev" class="relative inline-flex items-center px-2 py-2 text-sm font-normal text-vitalfluid-blue-500 bg-white border border-vitalfluid-gray-400 rounded-l-md leading-5 hover:text-vitalfluid-blue-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-vitalfluid-blue-500 transition ease-in-out duration-150" aria-label="{{ __('pagination.previous') }}">
                                      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                          <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                                      </svg>
                                  </button>
                              @endif
                          </span>
  
                          {{-- Pagination Elements --}}
                          @foreach ($elements as $element)
                              {{-- "Three Dots" Separator --}}
                              @if (is_string($element))
                                  <span aria-disabled="true">
                                      <span class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-normal text-vitalfluid-blue-700 bg-white border border-vitalfluid-gray-400 cursor-default leading-5">{{ $element }}</span>
                                  </span>
                              @endif
  
                              {{-- Array Of Links --}}
                              @if (is_array($element))
                                  @foreach ($element as $page => $url)
                                      <span wire:key="paginator-page{{ $page }}">
                                          @if ($page == $paginator->currentPage())
                                              <span aria-current="page">
                                                  <span class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-normal text-vitalfluid-blue-500 bg-white border border-vitalfluid-gray-400 cursor-default leading-5">{{ $page }}</span>
                                              </span>
                                          @else
                                              <button wire:click="gotoPage({{ $page }})" class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-normal text-vitalfluid-blue-700 bg-white border border-vitalfluid-gray-400 leading-5 hover:text-vitalfluid-red-500 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-vitalfluid-blue-700 transition ease-in-out duration-150" aria-label="{{ __('Go to page :page', ['page' => $page]) }}">
                                                  {{ $page }}
                                              </button>
                                          @endif
                                      </span>
                                  @endforeach
                              @endif
                          @endforeach
  
                          <span>
                              {{-- Next Page Link --}}
                              @if ($paginator->hasMorePages())
                                  <button wire:click="nextPage" dusk="nextPage.after" rel="next" class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-normal text-vitalfluid-blue-500 bg-white border border-vitalfluid-gray-400 rounded-r-md leading-5 hover:text-vitalfluid-blue-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-vitalfluid-blue-500 transition ease-in-out duration-150" aria-label="{{ __('pagination.next') }}">
                                      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                                      </svg>
                                  </button>
                              @else
                                  <span aria-disabled="true" aria-label="{{ __('pagination.next') }}">
                                      <span class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-normal text-vitalfluid-blue-200 bg-white border border-vitalfluid-gray-400 cursor-default rounded-r-md leading-5" aria-hidden="true">
                                          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                                          </svg>
                                      </span>
                                  </span>
                              @endif
                          </span>
                      </span>
                  </div>

- Livewire version: 2.4.0
- Laravel version: 8.33.1
- Alpine version: 2.8.1
- Browser: Chrome

**Comment by s1x** [comment]
Hello @journeyman73 

can you also post the code of your component who is responsible for populating the pagination?
Also, maybe debug the pagination variables with a ```dd()``` or ```dump()```, that way we can quickly see what has been populated.

PS: In general I would not change the published views but rather create your own variant.

**Comment by nuernbergerA** [comment]
Closed due to inactivity

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
