### ISSUE TITLE
Order of array is changed on livewire refresh by wire:poll.5000ms 

### ISSUE THREAD

**Issue by guoxiangke** [livewire/livewire#2649]
I have a complex array send to template with render().
![image](https://user-images.githubusercontent.com/1160703/111863641-c1d59880-8997-11eb-9561-9a8180b5b447.png)

the init array order with key is [640,676,101,667,677,675]
but after inited, the follows array's order changed to: [101,640,667,675,676,677]
![image](https://user-images.githubusercontent.com/1160703/111863695-209b1200-8998-11eb-9deb-7b4567fbb1a2.png)

I use wire:poll  to refresh after init.
but the order changed after init.
![2021-03-22_10-16-22 (1)](https://user-images.githubusercontent.com/1160703/111932363-36bfe400-8af8-11eb-85d0-e35a534c685d.gif)

**Context**
- Livewire version: "livewire/livewire": "2.3.18",
- Laravel version: "laravel/framework": "^8.12",
- Alpine version: "alpinejs": "^2.8.1",
- Browser: Chrome

the array was loaded from laravel Model and processed with groupBy, and load from the database when having new items.
```
            $messages = WechatMessage::latest()
                ->take(100)
                ->get()
                ->keyBy('id')
                ->groupBy('conversation')->toArray();
```

same as https://github.com/livewire/livewire/issues/160 but a different situation.
here is my code: https://github.com/guoxiangke/wescrm/blob/6adc96b9a9358c11aa10c2266b4668470d1ecac4/app/Http/Livewire/WebChat.php#L260

new debug info:
![image](https://user-images.githubusercontent.com/1160703/111931891-3541ec00-8af7-11eb-907b-3cb60f459718.png)

**Comment by joshhanley** [comment]
@guoxiangke that is a known limitation. Any arrays that use an integer keys that aren't ordered in ascending order, when it gets loaded into javascript, the javascript will sort the array in ascending order.

Not a lot we can do about that as it is how javascript handles arrays. The work around is to convert the keys to strings so it won't re-order them.

Hope this helps!

**Comment by guoxiangke** [comment]
> @guoxiangke that is a known limitation. Any arrays that use an integer keys that aren't ordered in ascending order, when it gets loaded into javascript, the javascript will sort the array in ascending order.
> 
> Not a lot we can do about that as it is how javascript handles arrays. The work around is to convert the keys to strings so it won't re-order them.
> 
> Hope this helps!

thank you very much. I'll try.

**Comment by joshhanley** [comment]
No worries 🙂

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
