### ISSUE TITLE
Emit event only works if I call it from render but not from template

### ISSUE THREAD

**Issue by victorelec14** [livewire/livewire#2652]
### Description

hi, I am trying to create a component that shows the counter when clicking on "Show Counter", this did not work with the Emit event or with the Click event in my template but it does work if I put the event inside the component render.

_@livewireStyles_ are loaded in before closing header and _@livewireScripts_ before closing the body

What I can do? Thanks!

### Exact steps to reproduce

![livewire_problem](https://user-images.githubusercontent.com/543450/112032856-1ebe8380-8b3d-11eb-8b1d-9f9942d151b9.gif)

### Stripped-down, copy-pastable code snippets

App\Http\Livewire\Counter.php
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public $isOpen = false;
    public $count = 123;

    protected $listeners = ['showCounter' => 'open', 'hideCounter' => 'close'];

    public function showFromRender()
    {
        //$this->isOpen = true; //this run
    }

    public function open()
    {
        $this->isOpen = true;
    }

    public function close()
    {
        $this->isOpen = false;
    }

    public function render()
    {
        return view('livewire.counter');
    }
}

```

resources\views\liwevire\counter.blade.php
```
<div>

    {{-- <button wire:click="showCounter">Show From Render</button> --}}
    <button wire:click="$emit('showCounter')">Show From Renderr</button>
    @if($isOpen)
        <h1>{{ $count }}</h1>
    @else
        <h1>is Closed</h1>
    @endif
    {{-- {{ var_dump($is_open) }} --}}
    
</div>
```

index.blade.php

```
<x-app-layout>

    <button wire:click="$emit('showCounter')">Show Counter</button>
    {{-- <button wire:click="showCounter">Show Counter</button> --}}
    <livewire:counter />


</x-app-layout>

```

**Context**
- Livewire version: [e.g. 2.2.3] 2.4.1
- Laravel version: [e.g. 8.3.1] 8.33.1
- Alpine version: [e.g. 2.3.0]  ^2.7.3
- Browser: [e.g. Chrome, Safari] Chrome

**Comment by nuernbergerA** [comment]
That's not how events work in Livewire.

```blade
<button wire:click="open">Show From Render</button>
```

**Comment by victorelec14** [comment]
@nuernbergerA  hi, i used the emit to test, but I also wanted to pass more parameters. Using click or emit does not work from the outside, it only works when I click on the button that is generated in the render.

It is a problem that the button outside is inside "<x-app-layout>" button "</x-app-layout>"  ???

Thank you !

**Comment by s1x** [comment]
@victorelec14 If the index.blade.php is not par of the livewire component, yes. But maybe - just try it? :)

**Comment by victorelec14** [comment]
I just tried making a simple html without any extra JS or CSS and it remains the same, it only loads when I click on a button that was generated within the render.

I also do not see any error in the console and I only see request when I click the component button.

```
Route::get("/test", function(){
    return view('test'); 
});
```

test.blade.php
```
<!DOCTYPE html>
<html> 
    <head>
        @livewireStyles
    </head>
    <body>
        <button wire:click="open">Show From Render</button>
        <button wire:click="$emit('showCounter')">Show Counter</button>
        <button wire:click="showCounter">Show Counter</button>
        <livewire:counter />

        @livewireScripts  
    </body>
</html>
```

Result:

![livewire_problem2](https://user-images.githubusercontent.com/543450/112185593-a9b48200-8c00-11eb-98bc-e9f769ffe81d.gif)


Thanks

**Comment by s1x** [comment]
@victorelec14 Yes, your three buttons are not part of any livewire component that's why it doesn't work. You cannot use the any livewire functionality without using the livewire component itself.

To make this work, you would have to create a new component e.g. ```livewire/test.php```, 


```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{

    public function render()
    {
        return view('livewire.counter');
    }
}
```

**Comment by victorelec14** [comment]
@s1x  ohhh i understand now, I was mixing the events and it only works from the component. 

Thank you very much for the help :D , i close the Issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by burfbari** [comment]
> @s1x ohhh i understand now, I was mixing the events and it only works from the component.
> 
> in case you want to use an event from outside the component you could use:
> 
> ```
> <button onclick="window.livewire.emit('showCounter')">Show Counter</button>
> ```
> 
> Thank you very much for the help :D , i close the Issue.

Excellent! This should be a part of the official Livewire documentation.

**Comment by sasafister** [comment]
Is something changed here? Still can't reach the `Livewire` in blade outside of Livewire component.

```@extends('layouts.app')

@section('content')
    <div class="flex items-center justify-center w-screen h-screen">
        <button onclick="window.Livewire.emit('openModal','hello-modal')"
                class="px-3 py-2 text-sm border border-gray-200 rounded-md">Open Modal</button>
    </div>
@endsection
```

`Uncaught TypeError: window.Livewire.emit is not a function`
