### ISSUE TITLE
Pagination removes URL path

### ISSUE THREAD

**Issue by HepplerDotNet** [livewire/livewire#2660]
I have this component to render paginated results:
```php
<?php

namespace App\Http\Livewire\Accounts;

use App\Models\Account;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    public $search;
    public $accounts;

    public function render()
    {
        if ($this->search) {
            $this->resetPage();
            $this->accounts = Account::search($this->search)
                ->orWhere('fullname', 'LIKE', '%'.$this->search.'%')
                ->orWhere('email', 'LIKE', '%'.$this->search.'%')->orderBy('fullname')->paginate(12);
        } else {
            $this->accounts = Account::orderBy('fullname')->paginate(12);
        }

        return view('livewire.accounts.index', ['accounts' => $this->accounts]);
    }
}
```

Within the Blade Template I have `{{ $accounts->links('pagination.tailwind') }}`
The Pagination View is a copy of vendor/livewire/tailwind.blade.php

The URL is htttp://mydomain.com/accounts.

When I click a pagination link, the URL becomes htttp://mydomain.com/?page=2 instead of htttp://mydomain.com/accounts/?page=2

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.33.1
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by joshhanley** [comment]
@HepplerDotNet can you share an example repo that demonstrates the issue so we can investigate it?

**Comment by HepplerDotNet** [comment]
@joshhanley now it's getting really weird. I setup a new laravel app and copied the relevant parts (Model, Controller etc.), to provide a repo.

In the new App it works like expected but in the old it behaves like reported.

Doing a `dd($this->accounts->nextPageUrl());` within the controller returns the correct URL.

**Comment by joshhanley** [comment]
@HepplerDotNet hmm that is strange! 

Are you using nested components that use pagination by any chance? 

I know if you hare a parent component and a child component, with pagination in the child, that you also need to put `use WithPagination;` in the parent class as well as the child otherwise strange things happen.

The other thing to test, is using the default pagination view and seeing if the same issue happens, maybe theres something going on in your custom view?

**Comment by HepplerDotNet** [comment]
@joshhanley I don't use nested components. Also tried `{{ $accounts->links() }}` which renders the default view. Same issue.
I had to change my code to:
```php
<?php

namespace App\Http\Livewire\Accounts;

use App\Models\Account;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    public $search;
    public $accounts;

    public function render()
    {
        if ($this->search) {
            $this->accounts = Account::search($this->search)->paginate(12);
        } else {
            $this->accounts = Account::orderBy('fullname')->paginate(12);
        }

        return view('livewire.accounts.index', ['accounts' => $this->accounts]);
    }

    public function updatingSearch(): void
    {
        $this->resetPage();
    }
}
```
`Account::search($this->search)` combined with `orWhere` lead to wrong pagination count. 
And I moved `$this->resetPage();` to `updatingSearch`

**Comment by joshhanley** [comment]
@HepplerDotNet ah right! Sorry completely missed the reset page call in the render function before.

Yeah I think the way you have changed it now is a better idea, as it makes sense to reset it if something has changed that can impact the number of results.

So have you resolved this issue now or were you still having issues?

**Comment by HepplerDotNet** [comment]
Unfortunately not. It only solved an other issue with pagination. Still missing path in url, even with default template

**Comment by joshhanley** [comment]
@HepplerDotNet bugger!

I know trying to replicate the issue didn't work. Would there be any chance of just copying that route and any components into a new repo (and configuring any needed models, tables and seeders) so that I can pull down to test it for you and see if we can get to the bottom of it?

**Comment by HepplerDotNet** [comment]
@joshhanley https://github.com/HepplerDotNet/livewire-issue-2660
Just clone it, run migrations & seeder and hit http://127.0.0.1:8000/accounts
As said, with this repo it works

**Comment by HepplerDotNet** [comment]
@joshhanley I got it!
I was lazy, so I ran the test repo only with `php artisan serv`
The real issue was nginx!
`add_header 'Referrer-Policy' 'same-origin';` fixed it!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@HepplerDotNet ah good find! I never would have thought of that haha as I use Valet 😬

**Comment by HepplerDotNet** [comment]
@joshhanley I was working on something different and had to use `url()->previous()` where the path was missing too
