### ISSUE TITLE
No Parameter Event triggers Fingerprint Error

### ISSUE THREAD

**Issue by Chazza** [livewire/livewire#2664]
### Description
When triggering an event without any parameters, Livewire triggers an error.
```
index.js:32 Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null
    at new Component (index.js:32)
    at onNodeAdded (index.js:476)
    at callHook (morphdom.js:35)
    at handleNodeAdded (morphdom.js:140)
    at morphdom.js:407
    at morphEl (morphdom.js:219)
    at morphdom.js:463
    at Component.value (index.js:366)
    at Component.value (index.js:277)
    at Component.value (index.js:248)
```

### Exact steps to reproduce
1. Create an event without any parameters.
2. Fire this event.
3. Listen to the event on Livewire.
### Stripped-down, copy-pastable code snippets
Info above.

**Context**
- Livewire version: Latest
- Laravel version Latest
- Alpine version: Latest
- Browser: Chrome & Safari (Tested both)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Brouilles** [comment]
Same here in production (only). 
Even with `php artisan livewire:publish --assets` command. 
How have you fix that @heychazza ?

Thanks.
