### ISSUE TITLE
$this->resetPage() sometimes works, somtimes not

### ISSUE THREAD

**Issue by HepplerDotNet** [livewire/livewire#2668]
I have this component to render paginated results:

```php
<?php

namespace App\Http\Livewire\Accounts;

use App\Models\Account;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    public $search;
    public $accounts;

    public function render()
    {
        if ($this->search) {
            $this->resetPage();
            $this->accounts = Account::search($this->search)
                ->orWhere('fullname', 'LIKE', '%'.$this->search.'%')
                ->orWhere('email', 'LIKE', '%'.$this->search.'%')->orderBy('fullname')->paginate(12);
        } else {
            $this->accounts = Account::orderBy('fullname')->paginate(12);
        }

        return view('livewire.accounts.index', ['accounts' => $this->accounts]);
    }

    public function updatingSearch(): void
    {
        $this->resetPage();
    }
}
```
If I search for Accounts, sometimes the resetPage() works and the pagination links get adjusted/removed, but sometimes it ends up with "Showing 1 to 4 of 11 Results" and pagination links for 2 pages, but there are only 4 results.

Context

Livewire version: 2.4.1
Laravel version: 8.33.1
Alpine version: 2.7.3
Browser: Chrome

**Comment by denizozturk** [comment]
Doc: https://laravel-livewire.com/docs/2.x/pagination#resetting-pagination

You can see the correct usage in the document. Also "updating+Param" runs before any update to the component's data. "updating+Param" is a lifecycle hook, you don't need to call it in function. After updating the field in which you called the method, there should be no problems. If you deleting the reset page method in the render function, it will work correctly

**Comment by HepplerDotNet** [comment]
The issue is caused by the Full Text Search Trait I'm using. If combined with `orWhere()`, it returns wrong count.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by davidkaban** [comment]
> I have this component to render paginated results:
> 
> ```
> <?php
> 
> namespace App\Http\Livewire\Accounts;
> 
> use App\Models\Account;
> use Livewire\Component;
> use Livewire\WithPagination;
> 
> class Index extends Component
> {
>     use WithPagination;
>     public $search;
>     public $accounts;
> 
>     public function render()
>     {
>         if ($this->search) {
>             $this->resetPage();
>             $this->accounts = Account::search($this->search)
>                 ->orWhere('fullname', 'LIKE', '%'.$this->search.'%')
>                 ->orWhere('email', 'LIKE', '%'.$this->search.'%')->orderBy('fullname')->paginate(12);
>         } else {
>             $this->accounts = Account::orderBy('fullname')->paginate(12);
>         }
> 
>         return view('livewire.accounts.index', ['accounts' => $this->accounts]);
>     }
> 
>     public function updatingSearch(): void
>     {
>         $this->resetPage();
>     }
> }
> ```
> 
> If I search for Accounts, sometimes the resetPage() works and the pagination links get adjusted/removed, but sometimes it ends up with "Showing 1 to 4 of 11 Results" and pagination links for 2 pages, but there are only 4 results.
> 
> Context
> 
> Livewire version: 2.4.1 Laravel version: 8.33.1 Alpine version: 2.7.3 Browser: Chrome

use return $this->resetPage()
