### ISSUE TITLE
Component or View not found if 'App' part of path other than the beginning

### ISSUE THREAD

**Issue by wsamoht** [livewire/livewire#267]
### Issue
If you make a component with `App` in the path, it causes the Component and View to not be found due to `Component->getName()` removing `App` too aggressively.

### Run
`php artisan make:livewire app.foo.livewire-is-awesome`

#### Creates the following in `livewire-components.php`
```php
<?php return array (
  'foo.livewire-is-awesome' => 'App\\Http\\Livewire\\App\\Foo\\LivewireIsAwesome',
);
```
*when it should create...*
```php
<?php return array (
  'app.foo.livewire-is-awesome' => 'App\\Http\\Livewire\\App\\Foo\\LivewireIsAwesome',
);
```

Also, if you remove the override `render()` function from the `LivewireIsAwesome` component so it uses the the base `render()` function in `Component`, Livewire tries to load the view `livewire.foo.livewire-is-awesome` instead of `livewire.app.foo.livewire-is-awesome`.

```php
<?php

namespace App\Http\Livewire\App\Foo;

use Livewire\Component;

class LivewireIsAwesome extends Component
{
    // public function render()
    // {
    //     return view('livewire.app.foo.livewire-is-awesome');
    // }
}
```

### Cause
The cause of this is the `getName()` method in `Component` being too aggressive. It is removing all instances of `App` in the path instead of just the first one.

```php
public function getName()
{
    return collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->diff(['App', 'Http', 'Livewire'])
        ->map([Str::class, 'kebab'])
        ->implode('.');
}
```

#### Option 1
```php
public function getName()
{
    return collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->slice(3)
        ->map([Str::class, 'kebab'])
        ->implode('.');
}
```
#### Option 2
```php
public function getName()
{
    $name = collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->map([Str::class, 'kebab'])
        ->implode('.');

    if (Str::startsWith($name, 'app.http.livewire.')) {
        return Str::replaceFirst('app.http.livewire.', '', $name);
    }

    return $name;
}
```

#### Option 3
And to accommodate https://github.com/calebporzio/livewire/pull/235 something like:

```php
public function getName()
{
    $name = collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->map([Str::class, 'kebab'])
        ->implode('.');

    $namespace = Str::kebab(config('livewire.namespace'));

    if (Str::startsWith($name, $namespace . '.http.livewire.')) {
        return Str::replaceFirst($namespace . '.http.livewire.', '', $name);
    }

    return $name;
}
```

**Comment by wsamoht** [comment]
I was thinking of a better solution and this is even better than the three options above. Find `.livewire.` in the string and get everything after it.

```php
public function getName()
{
    $name = collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->map([Str::class, 'kebab'])
        ->implode('.');

    return Str::substr($name, strpos($name, '.livewire.') + 10);
}
```

**Comment by calebporzio** [comment]
Is this still an issue after upgrading to v0.3.6?

**Comment by wsamoht** [comment]
Thanks for checking! I tried it in v0.3.6 and it is still an issue. The removal of each part of the path is too aggressive. The code is currently splitting the path by each part/segment and then removing each of those anywhere in the path.

**Example**
- Component path: `App\\Http\\Livewire\\App\\Test`
- Namespace: `App\\Http\\Livewire`
- Namespace segments: `['App', 'Http', 'Livewire']`
- Using `diff` removes all instances of `App` in the path giving us: `Test`  instead of `App\\Test`

**Recommended Change**  
```php
public function getName()
{
    $namespace = collect(explode('.', str_replace(['/', '\\'], '.', config('livewire.class_namespace', 'App\\Http\\Livewire'))))
        ->map([Str::class, 'kebab'])
        ->implode('.');

    $name = collect(explode('.', str_replace(['/', '\\'], '.', static::class)))
        ->map([Str::class, 'kebab'])
        ->implode('.');

    return Str::substr($name, strlen($namespace) + 1);
}
```
I'd be glad to do a pull request with some tests. Let me know!
