### ISSUE TITLE
Public big integers with ~17-20 length gets corrupted data error

### ISSUE THREAD

**Issue by Edgarborras94** [livewire/livewire#2671]
### Description

I have been in trouble with a livewire component for some hours, trying to adding removing everything because i was having a 
```Livewire encountered corrupt data when trying to hydrate the [livewire-component] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.``` error.

### Exact steps to reproduce

This seems to be with a exact integer (don't know if it's because exact length or certain pattern). Tested with random larger ints and no problem but with similar lengths it does break :(

### Stripped-down, copy-pastable code snippets

Just put a integer similar to this:
```
public $large_id = 815289915557675120;
```

And then fire anything that rehydrates the component, like ```wire:poll``` or ```wire:init```

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.33.1
- Alpine version: 2.3.0
- Browser: Chrome

**Workaround**
if you convert that int to a string storing it and then parse again to int when necessary, it doesn't lose the corrupt data error

**Comment by jeffchown** [comment]
H @Edgarborras94 - the largest integer that JavaScript can safely store is (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).  As your 815,289,915,557,675,120 is > the MAX_SAFE_INTEGER of 9,007,199,254,740,991 this would explain the error you are receiving.

Your workaround of converting the value to a string looks like the best option if you need to work with numbers this large on a regular basis.

**Comment by Edgarborras94** [comment]
thanks for the appointment @jeffchown ! I keep forgetting that there is javascript under the hood :)

**Comment by jeffchown** [comment]
You're welcome, @Edgarborras94 !

**Comment by joshhanley** [comment]
Yep @jeffchown is right. 

I'm going to close this as per Caleb's comments here https://github.com/livewire/livewire/pull/1938#issuecomment-720640123

But if someone can come up with an elegant solution, PR's are welcome!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by seabasss** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

REOPEN
