### ISSUE TITLE
Getting 404 response on all request on v2.4

### ISSUE THREAD

**Issue by enayusuf** [livewire/livewire#2672]
All my livewire component show the 404 messages when I add a language prefix to my web.php route like this:

`Route::group(["prefix" => "{language}"], function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('dashboard');
});`

![image](https://user-images.githubusercontent.com/66288149/112568604-4a7b8b00-8e15-11eb-9515-b9fca2093b64.png)
![image](https://user-images.githubusercontent.com/66288149/112568641-5cf5c480-8e15-11eb-96c6-548b83e4b380.png)

it's working fine when I remove the language prefix of my route.

**Comment by IP-Developer** [comment]
Try setting `window.livewire_app_url` to your app's url with the current language prefix. If this doesn't fix the problem entirely, try defining livewire routes inside your localized route group. In our case, it was enough to define the livewire.message route:
```php
Route::group($this->localizationGroup(), function()
{
    Route::post('/livewire/message/{name}', HttpConnectionHandler::class)
        ->name('livewire.message')
        ->middleware(config('livewire.middleware_group', ''));
});
```

**Comment by joshhanley** [comment]
@enayusuf what versions of Livewire and Laravel are you using? There were issues to do with this in some versions that got patched.

**Comment by nuernbergerA** [comment]
Close due to inactivity

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
