### ISSUE TITLE
Getting 404 on modal handled with wire:model

### ISSUE THREAD

**Issue by rinodrummer** [livewire/livewire#2674]
### Description
I'm having a bug which I struggle to reproduce that never showed until last 2 releases of Livewire and the last of Alpine.js: I have a modal with which is binded to a Livewire property that toggles it.
The first time I open the modal, it works without problems, but the next times I get a 404 Not Found response with this stack trace:

![Uncaught (in promise) TypeError: Cannot read property 'reject' of null at Component.value (index.js:238) at Connection.value (index.js:11) at index.js:72](https://user-images.githubusercontent.com/6603220/112618429-62a7d600-8e26-11eb-9659-3fbc568c81bf.png)

It references to this snippet on the file `vendor/js/component/index.js`:

```js
messageSendFailed() {
    store.callHook('message.failed', this.messageInTransit, this)

    this.messageInTransit.reject() // <--- This is the line

    this.messageInTransit = null
}
```

I'm extremely sorry of the low details on the issue, but if I can help providing other hints, write me what is needed.

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.34.0
- Alpine version: 2.8.2
- Browser: Chrome 89.0.4389.90

**Comment by joshhanley** [comment]
@rinodrummer can you please share some code or an example repo that demonstrates the issue so we can look into it? Thanks!

**Comment by nuernbergerA** [comment]
Closed due to inactivity

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
