### ISSUE TITLE
Datatable disappers when the component rerenders

### ISSUE THREAD

**Issue by Darkhackit** [livewire/livewire#2675]
This is my component

?php

namespace App\Http\Livewire;
use Spatie\Permission\Models\Permission;
use Livewire\Component;

class Permissions extends Component
{
    public $permissions;
    public $name;

    public function updatedName()
    {
        $this->validate(['name' => 'required|unique:permissions']);
    }

    public function mount()
    {
        $this->permissions = Permission::all();
    }

    public function save()
    {

    }
    public function render()
    {
        return view('livewire.permissions')
                  ->extends('layouts.app')
                  ->section('content');
    }
}

And this is my view

<div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
   <a href="javascript:;" data-toggle="modal" data-target="#new-order-modal" class="btn btn-primary shadow-md mr-2 mb-3">New Permission</a> 
                        <table  id="myTable" class="table table-report -mt-2">
                            <thead>
                                <tr>
                                    <th class="whitespace-nowrap">IMAGES</th>
                                    <th class="whitespace-nowrap">PRODUCT NAME</th>
                                    <th class="whitespace-nowrap">STOCK</th>
                                    
                                </tr>
                            </thead>
                            <tbody>

                            @foreach ($permissions as $permission)
                                  <tr class="intro-x" wire:key="{{$loop->index}}">
                                   
                                  
                                    <td>{{$permission->id}}</td>
                                    <td class="w-40">
                                        {{$permission->name}}
                                    </td>
                                    <td class="table-report__action w-56">
                                        <div class="flex justify-center items-center">
                                            <a class="flex items-center mr-3" href="javascript:;"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                                            <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                                        </div>
                                    </td>
                                </tr>
                               
                            @endforeach
                              
                            </tbody>
                        </table>
                <div id="new-order-modal" class="modal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                       
                            <div class="modal-header">
                                <h2 class="font-medium text-base mr-auto">
                                    New Permission {{$name}}
                                </h2>
                            </div>
                       <form  wire:submit.prevent="save">
                            <div class="modal-body grid grid-cols-12 gap-4 gap-y-3">
                           
                                <div class="col-span-12">
                                    <label for="pos-form-1" class="form-label">Name</label>
                                    <input wire:model="name" type="text" class="form-control flex-1" placeholder="Name">
                                  @error('name')
                                      <div class="text-danger">{{$message}}</div>
                                  @enderror  
                                </div>                            
                            </div>
                            <div class="modal-footer text-right">
                                <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-32 mr-1">Cancel</button>
                                <button type="button" class="btn btn-primary w-32">Create</button>
                            </div>
                             </form>
                        </div>
                    </div>
                </div>
                            <script>
        document.addEventListener('livewire:load', function () {
             $(document).ready( function () {
                $('#myTable').DataTable();
            } );
        })
    </script>
                    </div>

**Comment by denizozturk** [comment]
View:

```
<script type="text/javascript" data-turbo-eval="true" data-turbolinks-eval="true">
    document.addEventListener('livewire:load', function () {
        $('#myTable').DataTable();
    });

    window.addEventListener('refreshComponent', event => {
        $(event.detail.componentName).DataTable()
        console.log('Updated table : ' + event.detail.componentName)
    })
</script>
```

Livewire component:

```
public function save()
{
        $this->dispatchBrowserEvent('refreshComponent', ['componentName' => '#myTable']);
}
```

**Comment by nuernbergerA** [comment]
Closed due to inactivity

Thanks, @denizozturk for your help!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by rodgeldantes0216** [comment]
REOPEN
