### ISSUE TITLE
Vuejs component events inside livewire component not worked

### ISSUE THREAD

**Issue by abdosaeedelhassan** [livewire/livewire#2676]
### Description
i am calling vuejs component inside livewire component, passing data correctly, but vuejs component events like @click not fired 

### Exact steps to reproduce
vuejs template:
`
<template>
    <div>
        <div class="row">
            <div class="col-md-3" v-for="(image, i) in paths">
                <img class="image" :src="image" @click="displayImage(i)">
                <p style="text-align: center;cursor: pointer" @click="displayImage(i)">{{names[i]}}</p>
            </div>
        </div>
        <vue-gallery-slideshow :images="paths_alt" :index="index" @close="index = null"></vue-gallery-slideshow>
    </div>
</template>
`

this component called inside livewire component, when clicking on the image of paragraph the event not fired, when calling the vuejs component outside livewire component the event fired correctly.

**Context**
- Livewire version: [2.4]
- Laravel version: [8.12]
- Alpine version: [2.3.5]
- Browser: [Chrome]

**Comment by abdosaeedelhassan** [comment]
it worked for me, thank you

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
