### ISSUE TITLE
wire:model textbox binding to accessor leaves textbox empty

### ISSUE THREAD

**Issue by effem** [livewire/livewire#2681]
### Description
When using wire model to bind an accessor to a text input the text field get cleared event though the value is passed back to the controller and is updated etc.
It seems like it could be related to this issue: https://github.com/livewire/livewire/issues/1841

### Exact steps to reproduce
https://laravelplayground.com/#/snippets/26fd98ea-997e-4e04-9577-07bb588bf731
See the first text input vs. the second one

### Stripped-down, copy-pastable code snippets
https://laravelplayground.com/#/snippets/26fd98ea-997e-4e04-9577-07bb588bf731

**Context**
Whatever version the laravelplayground is using...
- Livewire version: ? (latest I would guess)
- Laravel version: ? (latest I would guess)
- Alpine version: ? (latest I would guess)
- Browser: Firefox, Chrome, ...

**Comment by joshhanley** [comment]
@effem try adding `protected $appends = ['test_modified'];` to your user model in the playground. That should get it to work.

Hope this helps!

**Comment by effem** [comment]
@joshhanley yeah that was the problem! Thanks for pointing that out!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
