### ISSUE TITLE
Entanglement via this.$wire does not work

### ISSUE THREAD

**Issue by IP-Developer** [livewire/livewire#2682]
### Description
Entangling Alpine properties using `this.$wire` doesn't seem to work. The Proxy object is created, but the value is never retrieved or set. To add to this, entanglement doesn't work with `@entangle` directive if set in x-init. The only way entanglement works is when setting with `@entangle` directly on property definition, which is pretty limiting, considering that all my Alpine components are bundled with Mix.

### Exact steps to reproduce
[Laravel Playground](https://laravelplayground.com/#/snippets/6d02ebac-f251-41b0-8b0a-3b92479d32fa)

**Context**
- Livewire version: [e.g. 2.4.1]
- Laravel version: [e.g. 8.32.1]
- Alpine version: [e.g. 2.8.2]
- Browser: Any

**Comment by zepfietje** [comment]
I believe this has been an issue for quite some time already.

**Comment by joshhanley** [comment]
@IP-Developer using `@entangle` only works inside `x-data` as Livewire parses it before the Alpine component is initialised. It does that by removing the entangle call, sets up watchers, and then assigns the Livewire property value to the Alpine property.

So trying to use entangle in `x-init` won't work.

But I'm not exactly clear on why you would need that. Any chance you can explain how/why you would use that, and what you mean by your Alpine components are bundled with Mix and why that stops you using entangle in `x-data`?

Thanks!

**Comment by IP-Developer** [comment]
@joshhanley I am aware that `@entangle` works. The problem is specifically with entanglement via `this.$wire.entangle()`. This function is documented, and by my judgement, there shouldn't be any problem with using it, as Alpine components always load after Livewire. Please correct me if I'm wrong (in that case it would be better to wrap `this.$wire.entangle()` in livewire hook?).

The reason I want to stick to `this.$wire.entangle()` is because all my Alpine components are bundled with Laravel Mix (and are pretty big actually), so I don't have access to the `@entangle` directive. An option would be to pass entanglements via `@entangle` directly to Alpine component constructor function, but this just creates more confusion as it's not self-explanatory in the JS file. So the best way to achieve that would be to use `this.$wire.entangle()` in an `init()` component method called by `x-init` (check the playground). I'm trying to avoid having inline scripts inside Livewire components as those are not cached or transpiled, and also makes it harder to third-party packages, as it forces me to assign everything to `window` so it can be accessible.

**Comment by joshhanley** [comment]
@IP-Developer `@entangle` just expands to `$wire.entangle()` so you can use `$wire.entangle()` in `x-data` without any issue but it won't work in `x-init`.

If it is documented as `this.$wire.entangle()` then that is an error, can you show me where that is so we can get it fixed?

If you are curious, this is the logic which parses entangle inside `x-data` which happens before the Alpine component is initialised (hence why won't work in init) https://github.com/livewire/livewire/blob/2f06b28be0aa0d5bf0a4598b4b571d7d1a24e5c1/js/component/SupportAlpine.js#L51

Ok thanks for sharing, that makes sense, but yeah sadly that won't work. 

To dynamically assign entangle would require changing the way `entangle` is initialised.

I would personally just pass through the Aline component constructor and maybe just document that, that is how it's running if that is confusing for others.

I use something like this

```html
<div x-data="something({ value: $wire.entangle('livewireValue') })">
```

```js
function something(config) {
  return {
    ...config,
    // other stuff
  }
}
```

But agree using the `...config` makes it harder to reason about what properties are available in the component. So sometime I use this instead

```js
function something(config) {
  return {
    value: config.value,
    // other stuff
  }
}
```

Hope this helps!

**Comment by IP-Developer** [comment]
@joshhanley to answer your last sentence, my Alpine components' logic are extracted to functions [(check x-data documentation)](https://github.com/alpinejs/alpine#x-data). All those functions are defined in my `app.js` file, which is then bundled/transpiled/polyfilled by Laravel Mix. A simple example of an extracted Alpine component in `app.js`:
```js
window.myComponent = () => 
{
    return { 
        name: 'test',
        init(name) 
        {
            this.name = name;
        }
    }
}
```
which is then used like so:
```html
<div x-data="myComponent()" x-init="init('something else')"></div>
```

So the exact thing I was trying to do is both having `name` property defined in Alpine component with a default value, and then entangle it to Livewire's property in `init()`.

**Comment by IP-Developer** [comment]
@joshhanley 

> If it is documented as `this.$wire.entangle()` then that is an error, can you show me where that is so we can get it fixed?

It is indeed, check the [Reference](https://laravel-livewire.com/docs/2.x/reference) page in Livewire's documentation.

I think getting it to work inside `x-init` would be a huge improvement, considering that Alpine components definition via Alpine.component() is coming in v3 (also magic __init() method), I think most developers will switch to defining components inside `app.js` and even loading them dynamically via webpack's `import()`.

Maybe passing `$wire` inside component function could be an option? So something like this would work:
```js
function myComponent($wire) 
{
    return {
        name: $wire.entangle('name')
    }
}
```

**Comment by joshhanley** [comment]
@IP-Developer ah yeah, thanks for the link! Yeah the option on that page `$wire.entangle('foo').defer` should actually be wrapped in `x-data` so it is clearer that is how it should be used, like the `x-data="{ foo: $wire.entangle('foo') }"` above it.

Yeah I think dynamic entangle assignment could be helpful.

So, I thought just using `name: this.$wire.entangle('name')` would work but it comes up with a `$wire` undefined error. But then I remembered using `name: @entangle('name')` works.

But looking at the expanded code for `@entangle`, it actually expands to `window.Livewire.find('<livewire-component-id>').entangle('name')`

So maybe instead of passing $wire through the constructor, you instead pass the Livewire component through using `@this` (which expands to `window.Livewire.find('...')`) and then make use of that Livewire object yourself like

```html
<div x-data="something(@this)">
```

```js
function myComponent(livewireComponent) 
{
    return {
        name: livewireComponent.entangle('name')
    }
}
```

Just tested it and it works. Hopefully that would make it clearer what is going on.

**Comment by IP-Developer** [comment]
@joshhanley yes, this is exactly what I came up to right now :) But `this.$wire.entangle()` still seems to be the best option for such cases (considering upcoming changes in Alpine, it would be perfect).

@calebporzio any thoughts on this?

**Comment by joshhanley** [comment]
@IP-Developer no worries 🙂
