### ISSUE TITLE
Pagination not populating querystring

### ISSUE THREAD

**Issue by ctschetter** [livewire/livewire#2686]
### Exact steps to reproduce
The route in web.php:
```
Route::get('/reviews/{slug}', ShowProfile::class);
```

ShowProfile:
```<?php

namespace App\Http\Livewire;

use App\Models\Profile;
use App\Models\ProfileReview;
use Livewire\Component;
use Livewire\WithPagination;

class ShowProfile extends Component
{
    use WithPagination;
    public $profile;


public function mount($slug)
    {
        $this->profile = Profile::where('name_slug', $slug)->orderBy('id', 'desc')->first();
    }

public function render()
    {
        $reviews = ProfileReview::where('profile_id', $this->profile->id)->orderBy('created_at', 'desc')->paginate(10);
        return view('livewire.show-profile', [
            'reviews' => $reviews
        ])->layout('layouts.search');
    }
}
```

And finally in show-profile.blade.php:
```
<div class="pt-6">
    {{ $reviews->links('vendor.livewire.tailwind') }}
</div>
```

The links appear fine, they page back and forth as you would expect, and manually changing the URL to include ?page=2 also works. The only problem is the URL does not change or ever show the page query.

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.35.1
- Alpine version: 2.8.1
- Browser: Chrome

**Comment by ctschetter** [comment]
I was able to get the query string to update properly by REMOVING 
```
use WithPagination;
```
and changing
```
{{ $reviews->links('vendor.livewire.tailwind') }}
```
to
```
{{ $reviews->links() }}
```
But the pagination templates are stock frrom the livewire:publish - I have not made any changes. Tried all of the above in a fresh project and the results are the same.

**Comment by joshhanley** [comment]
@ctschetter I have just run a test on Livewire 2.4.1 locally and pagination works fine for me and the query string updates.

Are you able to supply an example repo demonstrating the issue?

Also you don't need to specify `vendor.livewire.tailwind` in your links method to use the published pagination views, as it will use them automatically.

But you do need to use `use WithPagination;`, otherwise, as you said, you end up with full page loads.

Here is the component I'm using to test , its a full page component

web.php
```php
Route::get('/', Main::class);
```

main.php
```php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Main extends Component
{
    use WithPagination;

    public function render()
    {
        return view('livewire.main', ['users' => User::paginate(2)]);
    }
}
```

main.blade.php
```html

<div>
    <div>
        @foreach ($users as $user)
            <div>{{ $user->name }}</div>
        @endforeach
    </div>

    <div>{{ $users->links() }}</div>
</div>
```

Hope this helps!

**Comment by ctschetter** [comment]
Thanks @joshhanley - I figured it out. I had this in my head:
```
<meta name="referrer" content="no-referrer">
```
When I get rid of that it works fine.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@ctschetter ah good find! Thanks for sharing, hopefully it will help someone else if they experience this issue 🙂
