### ISSUE TITLE
Lifecycle hooks doesn't run after mutating a property

### ISSUE THREAD

**Issue by natanaelsinisalo** [livewire/livewire#2687]
### Description

This issue is related to #142. Couldn't use REOPEN since squishythejellyfish didn't seem to monitor it.

So I wasted 1.5h for debugging while trying to understand why my code didn't work and it turned out that update hooks doesn't run in the Livewire component class after mutating a property. I think there should be at least be a note on this in the [lifecycle hooks documentation](https://laravel-livewire.com/docs/2.x/lifecycle-hooks).

In the issue #142 there was [some discussion](https://github.com/livewire/livewire/issues/142#issuecomment-519598708) to maybe add some kind of $this->set('counter', $this->counter+1) implementation to overcome this if someone provides a realistic scenario where this kind of feature is needed, so here's one:

### The scenario

I started implementing data tables (by following the [Surge screencasts](https://laravel-livewire.com/screencasts/s7-intro)) into my app. Soon I ran into an issue where I needed to have more fields in the create/edit modal than my screen height was. It seems that the modal component was built in a way that doesn't support modal scrolling. So I refactored my modal to support scroll bar. So far so good.

But then I had a page where I had more content in the page itself than my monitor height was, so there was a scroll bar also in the body. Now I had two layers of scroll bars while opening the modal with a scroll bar in a page like that.

A common way to solve this issue is to disable the body scroll bar by toggling something like style="overflow-y: hidden;" in the body tag when opening/closing the modal.

I'm using Livewire to show/hide the modal (same as in the Surge example) so I started to implement the body scroll bar disabling with the `$this->dispatchBrowserEvent()` method.

The most logical place for this seems to be:

```
    public function updatedShowEditModal()
    {
        $this->dispatchBrowserEvent('disable-body-scroll', [
                'value' => $this->showEditModal
        ]);
    }
```

The modal itself has `show: @entangle($attributes->wire('model'))`, so it triggers this hook whenever I close the modal. Things gets problematic when using custom methods such as create() and edit() to handle the opening logic of the modal:

```
    public function create()
    {
        if ($this->user->getKey()) {
            $this->user = $this->makeBlankUser();
        }

        $this->showEditModal = true;
    }
```

But now since `$this->showEditModal = true;` doesn't trigger any lifecycle hooks, I have to call `$this->dispatchBrowserEvent()` manually in multiple methods (create(), edit() and save()) to achieve what I need.

I'm using a custom macro `$this->toggleDisableBodyScroll($bool);` to tidy up the code a little, but I would much rather use `$this->set('showEditModal', $this->showEditModal);` or `$this->toggle('showEditModal')` to avoid unnecessary repetition ☺️

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.35.1
- Alpine version: 2.8.1
- Browser: Firefox Developer Edition

**Comment by joshhanley** [comment]
@natanaelsinisalo yeah I agree, that tripped me up the first time. I'm sure a PR to the docs to add a warning would be welcome 🙂

In relation to preventing the body scroll, another simpler way to do that (rather than controlling from Livewire) is to use Alpine. Have a look at the Jetstream model and how it handles it https://github.com/laravel/jetstream/blob/9663d7eb4e58ec86f105efb07f712fb81e6c92f2/resources/views/components/modal.blade.php#L34-L38

Hope this helps!

**Comment by natanaelsinisalo** [comment]
@joshhanley thank you for your kind reply! 

I actually tried to achieve this with Alpine.js by myself. I haven't used it that much and I toyed around the implementation for 15 minutes before just implementing something that felt more familiar (and used some 2 hours while doing it 😅). Definitely going to refactor my codebase to use that Jetstream modal snippet instead.

And I definitely can create a PR to update the docs. I'm super busy these next few days but let's keep this issue open for a few more days before I find a calm moment to actually do the PR 🙂

**Comment by joshhanley** [comment]
@natanaelsinisalo ah yep, that happens 😆

Ok great 🙂

**Comment by natanaelsinisalo** [comment]
The PR for the docs update regarding this issue was merged today, so the core of this issue is now resolved.

I still hold the same opinion that it would be beneficial to be able to have something like `$this->set()` and `$this->toggle()` available inside the Livewire component class, but definitely understand that this might be a technically complex thing to achieve.

This is not in any way an acute thing, so closing this issue for now. I'm confident that this issue will be resolved in one way or another in the future if enough people feels the same way 🙂

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by 0l1v3r5** [comment]
> The PR for the docs update regarding this issue was merged today, so the core of this issue is now resolved.
> 
> I still hold the same opinion that it would be beneficial to be able to have something like `$this->set()` and `$this->toggle()` available inside the Livewire component class, but definitely understand that this might be a technically complex thing to achieve.
> 
> This is not in any way an acute thing, so closing this issue for now. I'm confident that this issue will be resolved in one way or another in the future if enough people feels the same way 🙂

Couldn't [this->syncInput()](https://github.com/livewire/livewire/blob/6c45c16952a23447474079613d87af38669b13f8/src/ComponentConcerns/HandlesActions.php#L19) be used to solve your problem?

**Comment by natanaelsinisalo** [comment]
@0l1v3r5 forgot to get back to you, but your suggestion worked.

I actually tried to dive into the source code of Livewire to see if there was an internal method like that available but it seems that I didn't take a close enough look. Of course it feels a little sketchy to use something undocumented like that because the compatibility might just break in some update without being mentioned in the changelog, but that's what the tests are for 🙂
