### ISSUE TITLE
"Typed property must not be accessed before initialization" while trying to test a component with a property binded directly to a model

### ISSUE THREAD

**Issue by natanaelsinisalo** [livewire/livewire#2688]
### Description

I know that there are several "Typed property must not be accessed before initialization" issues (most of them closed) in the issue tracker but none of them seems to be related to testing. I'm also open to hearing a better way to structure my components if there's a better pattern to achieve what I'm trying to do.

So I have this "team" section on my app that has routes like /team/{team}/whatever.

In the pages under the team section I'm using both full page and normal "small" livewire components. I'm passing the current team into the non-full page components like this:

```php
<livewire:team.user-table :team="$team />
```

And in the component class I'm setting that team as a property like this:

```php
class UserTable extends Component
{
    public Team $team;

    protected $rules = [
        'team.id' => 'required|integer',
    ];
}
```

The component itself works great and I'm able to use $this->team->id there without problem. But the problem starts when I'm trying to test this component like this:

```php
class TeamUserTableTest extends TestCase
{
    public function test_can_list_team_users()
    {
        $team = Team::find(3);

        Livewire::test('team.user-table')->set('team', $team);

        // etc.
    }
}
```

Now I get the error Typed property App\Http\Livewire\Team\UserTable::$team must not be accessed before initialization while running `php artisan test`.

I know that with most of the other (bool, array etc.) typed properties I would be able to set default values and things should work without any problems, but to my knowledge you can't set default values to properties whose type is an object.

So is this a bug and/or is there a better pattern to overcome this? 

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.35.1
- PHP version: 7.4.16

**Comment by joshhanley** [comment]
@natanaelsinisalo I think it has to do with the `Team` type hinting on the property, doesn't allow for null values.

But to replicate how route model binding works or just passing in parameters to a component in a test , you can pass an array of parameters as the second value in the `test` method https://laravel-livewire.com/docs/2.x/testing#all-testing-methods:~:text=Livewire%3A%3Atest('foo'%2C%20%5B'bar'%20%3D%3E%20%24bar%5D)%3B

For example

```php
Livewire::test('team.user-table', ['team' => $team);
```

Also another small note, you can use the class reference rather than string reference to components like this

```php
use App\Http\Livewire\Team\UserTable;

Livewire::test(UserTable::class, ['team' => $team);
```

Personally I find that better to have that IDE support for click through and refactoring.

Hope this helps!

**Comment by tomhatzer** [comment]
@natanaelsinisalo Did you try to make the $team variable nullable (additional checks in your component may be necessary to check if the variable is null)? This got rid of the message in my case.

```php
class UserTable extends Component
{
    public ?Team $team; // Make the Team nullable

    protected $rules = [
        'team.id' => 'required|integer',
    ];
}
```

**Comment by natanaelsinisalo** [comment]
@joshhanley thank you! I actually tried to pass the Team object as the second parameter for the Livewire::test method earlier and still got the error, but now it seems to work without any issues 🤷‍♂️ I'm ok with that though 😁

I also thought (after that failed experiment) that using the array syntax and using the `->set()` method are essentially doing the same thing. Now it all makes a lot more sense. I'll try to take a look if there is something I could provide to the docs to help others to avoid the same mistake in the future. I suggest that we keep this issue open for a few more days so I can have some time to (maybe) create a PR for the docs.

Also thanks for the class reference tip. That's a good one 👍

@tomhatzer that was a good suggestion. I didn't remember to try to make it nullable earlier. But now after trying it (while still trying to pass the Team object through the `->set()` method) the problem seemed to persist. It also didn't seem to make any difference when I tried it after I got my test working by passing the data as the second parameter of the Livewire::test method instead of using the `->set()` method. I'm definitely going to remember to try this again if I face similar issues in the future 🙂

**Comment by joshhanley** [comment]
@natanaelsinisalo no worries 🙂 

Nah `set()` actually happens as part of a simulation of a subsequent request, where as `test()` is the initialise request. So `set` is meant to be as if something was entered in an input field that has `wire:model`.

Ok sounds good!

**Comment by natanaelsinisalo** [comment]
The pull request that contained the docs update was merged today 🥳 Closing this issue since there should be now enough information (this issue + the docs update) to help others to avoid the same mistake I made 🙂

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
