### ISSUE TITLE
Wire click invalidates all data causing exception

### ISSUE THREAD

**Issue by greimers** [livewire/livewire#2689]
### Description
When I have a component that displays a list of Eloquent models and a LiveWire action is triggered inside this list, the objects in the array property get serialized to plain arrays and the component will throw an exception `Attempt to read property on array`.
This happens directly after an action event is triggered independent of any actual data changes taking place.

### Exact steps to reproduce

1. Create a LiveWire component that displays a list (array or collection) of Eloquent models (say users and their names) using a `@foreach`.
2. Add a button inside the `@foreach` that has a `wire:click="someMethod"`.
3. Navigate to the component and press the button. 

### Stripped-down, copy-pastable code snippets

**ListUsers.php**

    class ListUsers extends Component
    {
        public array $users;
    
        public function mount() {
            $this->users = User::all()->all();
        }
    
        public function doNothing() {
            \Log::debug('nothing: ');
        }
    
        public function render() {
            return view('livewire.list-users');
        }
    }

**list-users.blade.php**

    <div>
        
            @foreach ($users as $user)
        
                <div wire:key="{{ 'name'.$user->id }}">
                    {{ $user->name }}
                </div>
                <button wire:key="{{ 'button'.$user->id }}" wire:click="doNothing">Log</button>
            @endforeach
        
    </div>

**Result**
`Attempt to read property "id" on array (View: /Code/livewire-lists/resources/views/livewire/list-users.blade.php) `

**Workaround**
Call `$this->users = User::all()->all();` in the `doNothing()` method to update the data.
This create unnecessary DB queries, however.

**Context**
- Livewire version: 2.4.1
- Laravel version: 8.35.1
- PHP version: 8
- Alpine version: --
- Browser: Firefox

**Comment by joshhanley** [comment]
@greimers you need to remove the `array` type hint from your `$users` property if you want Livewire to rehydrate the eloquent collection. Then `User::all();`  should work.

At the moment it is rehydrating the collection as an array, thats why trying to access model properties using `->property` won't work.

Hope this helps!

**Comment by greimers** [comment]
Thanks @joshhanley 
Yes, using Collections solves the issue. 

Thanks also for your reply on issue #1054  pointing out that nested collections are not supported. 
Both together let me solve all collection issues I had with LiveWire.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by danielapedroso** [comment]
I am getting the same error but I don't have the array type hint. I have 3 selects and when the first has the value changed I emit an event to do a query using the option selected with wire:model, but then I get the error. I tried updating the data to see if it was working and the second select updates but I didn't want to do just be doing queries either.
Do you have any idea what is causing this?

**Comment by danielapedroso** [comment]
REOPEN

**Comment by joshhanley** [comment]
@danielapedroso can you open a new discussion with details of your issue and any relevant code so we can have a look? Thanks!
