### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#270]
**Describe the bug**
I have a simple Livewire view component called `document-viewer.php`. Inside this component, I have a Vue component:

```php
//File: document-viewer.php
<columns></columns>
```

Inside my `Columns.vue` component, I am listening for Livewire events:

```javascript
    export default {
        name: "Columns",

        props: ['originalcolumns'],
        data() {
            return {
                 columns: this.originalcolumns
            }
        },
        created() {
            window.livewire.on('columnWasAdded', column => {
                console.log(column)
            });
        },
        methods: {},

    }
```

As you can see, I use the `window.livewire.on` method to listen for events. However, looking at the console log, I get this error:

> [Vue warn]: Error in created hook: "TypeError: Cannot read property 'on' of undefined"

**Desktop (please complete the following information):**
 - Mac Os X, Chrome

**Additional context**
Livewire v. 0.3.4.

In my `app.js` file, I have declared this:

```
window.Vue = require('vue');
```

**Comment by oliverbj** [comment]
If I place the @livewireAssets *before* the `app/js` include in my head tag, like this:

```html
    <!-- Scripts -->
    @livewireAssets
    <script src="{{ asset('js/app.js') }}" defer></script>
```
Then I don't see the error ([Vue warn]: Error in created hook: "TypeError: Cannot read property 'on' of undefined") anymore. 

However then none of the Livewire methods works (`wire:click` etc.)

**Comment by ninthspace** [comment]
I've had a similar issue where I either get this error, or no custom Livewire component JavaScript rendering in a Blade stack depending on where I build the stack. To work around the error I wrapped it in an event listener:

```javascript
document.addEventListener('livewire:available', function () {
    window.livewire.on('someEvent', function () {
        // etc
    });
});
```

**Comment by oliverbj** [comment]
> I've had a similar issue where I either get this error, or no custom Livewire component JavaScript rendering in a Blade stack depending on where I build the stack. To work around the error I wrapped it in an event listener:
> 
> ```js
> document.addEventListener('livewire:available', function () {
>     window.livewire.on('someEvent', function () {
>         // etc
>     });
> });
> ```
Above does fix the error, but a new problem arises. I have this code:

```javascript
document.addEventListener('livewire:available', function () {
                window.livewire.on('columnWasAdded', function () {
                    this.columns.push({
                        position: column.position.toString()
                    });
                });
            });
```

And when adding the Livewire `on` method inside the addEventListener, I get this error:

> Uncaught (in promise) TypeError: Cannot read property 'push' of undefined

Even though the `this.columns`  is defined during render:

```javascript
props: ['originalcolumns'],    
data() {                                                    
    return {                                                                                     
        columns: this.originalcolumns,
    }                                                       
},                                                          
```

**Comment by ninthspace** [comment]
I think you need to bind this to the event listener, so the correct `this` is used within your function. Something like this:

```javascript
document.addEventListener('livewire:available', function () {
    window.livewire.on('columnWasAdded', column => {
        this.columns.push({
            position: column.position.toString()
        });
    });
}.bind(this));
```

**Comment by oliverbj** [comment]
Ah, gotcha! You are right, I need to bind `this` to the`addEventListener`. This is what I ended up with:

```javascript
document.addEventListener('livewire:available', function () {
                window.livewire.on('columnWasAdded', column => {
                    this.columns.push({
                        //do something.
                    });
                });
            }.bind(this));
```

Thank you @ninthspace - highly appreciated. I spent an entire day messing with this, trying to just get the `window.livewire.on` working (I swear, it was working just a few days ago :D)

Anyways, would love some more input - maybe from @calebporzio  - if there is a better a better way?

**Comment by calebporzio** [comment]
I can't think of anything off the top of my head - I'd have to set this up locally to help more. However, you can avoid that `.bind()` by just using arrow functions for the listener:

```
document.addEventListener('livewire:available', () => {
    window.livewire.on('columnWasAdded', column => {
        this.columns.push({
            //do something.
        });
    });
});
```

**Comment by jjjrmy** [comment]
Still having this issue even with above solution

**Comment by yaman3bd** [comment]
I solved the problem using: 
document.addEventListener('livewire:load', () => {
});
I think available it was in the old versions

**Comment by bagwaa** [comment]
> I solved the problem using:
> document.addEventListener('livewire:load', () => {
> });
> I think available it was in the old versions

this saved my bacon, thank-you!

**Comment by Todomed** [comment]
Add the code but it still doesn't work for me. this is my code:

@livewireScripts
<script type="text/javascript">
document.addEventListener('livewire:load', () => {
  window.livewire.on('pacienteStore', () => {
      $('#exampleModal').modal('hide');
  });
});
</script>

**Comment by rushiprasad** [comment]
> I solved the problem using:
> document.addEventListener('livewire:load', () => {
> });
> I think available it was in the old versions

Thanks, @yaman3bd, I was finding the solution for the past 1 hour.

**Comment by yaman3bd** [comment]
> Add the code but it still doesn't work for me. this is my code:
> 
> ```
> @livewireScripts
> <script type="text/javascript">
> document.addEventListener('livewire:load', () => {
>   window.livewire.on('pacienteStore', () => {
>       $('#exampleModal').modal('hide');
>   });
> });
> </script>
> ```

sorry for the late replay
I have tried it the same way you did it worked no problems
I think the problem in pacienteStore event maybe it not being fired or there is something wrong with "    $('#exampleModal').modal('hide');"
