### ISSUE TITLE
Model binding with Radio button

### ISSUE THREAD

**Issue by phamhuutruong7** [livewire/livewire#2705]
### Description

Recently I have a task like this. 
This is an update modal, it will display the options user already picked (in the past). 
Because the database set this column to boolean so it gonna be like this. 
```
<input wire:model="option" type="radio" value="0">No
<input wire:model="option" type="radio" value="1">Yes
<input wire:model="option" type="radio">null
```

The "option" default value when initiate will be null. 
I tried with value="", value="null", value="{{ null }}". Wire:model can't bind any of them, so it would not be "checked".
[See in the pictures]
![chrome_he5Fnz21VD](https://user-images.githubusercontent.com/19285094/113985935-f9c05500-984c-11eb-9138-6b38f9b81310.png)
![chrome_EpAd6LvXVF](https://user-images.githubusercontent.com/19285094/113995935-fb8f1600-9856-11eb-8679-b40488bd797d.png)

In the second line, wire:model is binded with value="1" so it appeared with checked.
In the second picture, wire:model is compared null == 0. (which returns true in php), so it has 2 checked in radio. 
I'm trying to find a way to bind it with the null. 
It is not allowed to set the database default value from null to any other value (like 2 or something).

- Livewire version: [2.4.2]
- Laravel version: [8.35.1]
- Browser: [Chrome]

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by ARSHADKHAN615** [comment]
checked property is not working for radio button in livewire when browser load or update time

**Comment by vovarpd** [comment]
Nullable boolean still not working. I should cast it to string.
