### ISSUE TITLE
Exceptions are different when thrown in tests

### ISSUE THREAD

**Issue by ash-jc-allen** [livewire/livewire#2706]
### Description
Hi! Apologies if I'm just barking up the wrong tree here and doing something wrong.

I have a component that is rendered inside a Blade view. In the ` mount() ` method of the component, I validate a field that is passed in. If the field is incorrect, I throw an ` \InvalidArgumentException `. This seems to work as expected.

But, if I try and do the same during testing, I seem to get a ` Facade\Ignition\Exceptions\ViewException ` instead. Is this just a limitation of the framework, or a bug, or am I approaching this wrong?

Cheers for any help in advance! :smile:

### Exact steps to reproduce

Livewire component (snippet):

```php
public function mount(): void
{
    if (! in_array($this->action, ['store', 'update'])) {
        throw new \InvalidArgumentException('The action is invalid.');
    }
}
```

How it's being called from the Blade view:
```
@livewire('store-update-records', ['action' => 'store'])
```

The test that is failing because the exception being thrown is a ` Facade\Ignition\Exceptions\ViewException `

```php
/** @test */
public function exception_is_thrown_if_the_action_is_invalid()
{
    $this->expectException(\InvalidArgumentException::class);
    $this->expectExceptionMessage('The action is invalid.');

    Livewire::test(StoreUpdateRecords::class, [
        'action' => 'INVALID',
    ]);
}
```

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: v2.4.0
- Laravel version: v8.31.0
- Alpine version: -
- Browser: -

**Comment by austenc** [comment]
Thanks for reporting this @ash-jc-allen. I'll see if I can reproduce it and get back to you.
