### ISSUE TITLE
History sync for components with optional route parameters is broken

### ISSUE THREAD

**Issue by nihilsen** [livewire/livewire#2710]
### Exact steps to reproduce

1. Make a full-page Livewire component with an optional route parameter. Include an action to set the parameter.

```PHP
class ComponentWithOptionalRouteParameter extends \Livewire\Component {
    public $parameter;

    public function mount(Parameter $parameter)
    {
        $this->parameter = $parameter;
    }

    public function setParameter($parameterID)
    {
        $this->parameter = Parameter::find($parameterID);
    }
}

Route::get('component/{parameter?}', ComponentWithOptionalRouteParameter::class);
```

2. Go to the component route without a parameter. In the above example, that would be `/component/`.
3. Invoke the action to change the parameter from null to anything non-null.
4. The address bar _should_ change to reflect the parameter being set, e.g. `/component/1`, but it stays as `/component/`

#2709 attempts to address this issue.

60b92b6d151d318539cac907cb3eb2aa3db20c1a provides failing tests to demonstrate this issue.

**Comment by calebporzio** [comment]
Thanks for the PR, this has been merged now.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
