### ISSUE TITLE
Livewire 1.3.7 package seems to be Livewire 2 on packagist

### ISSUE THREAD

**Issue by seliquity** [livewire/livewire#2719]
Livewire 1.3.7 is meant to be a minor update, but actually has several breaking changes and a diff of 1.3.6 vs 1.3.7 and 1.3.6 and 2.4.2 shows it's much closer to 2.4.2, so I'm assuming it's a mistake?

**Comment by calebporzio** [comment]
Wow, thank you for pointing this out.

Just deleted that release and re-tagged as 1.3.8

Please respond if it's fixed and we can close this. Thanks!

**Comment by seliquity** [comment]
All fixed with 1.3.8, thanks.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
