### ISSUE TITLE
Array of objects is converted to array of arrays on next request

### ISSUE THREAD

**Issue by hulkur** [livewire/livewire#2728]
### Description

I initialize a variable from DB as array of objects (QueryBuilder, get()->toArray()).
On next request the variable comes up as array of arrays.

### Stripped-down, copy-pastable code snippets

in component: called once on user input in updated method (`updatedFoo()`) 

```
$orgs = Organization::select(['id', 'type', 'name'])
            ->toBase()
            ->get()
            ->toArray();
```

in blade:

```
@foreach($orgs as $o)
     <option value="{{ $o->id }}">{{ $o->name }}</option>
@endforeach
```

First request it works, next request gives error "Attempt to read property "id" on array"

**Context**
- Livewire version: 2.4.2
- Laravel version: 8.37.0
- Alpine version: 2.8.2

**Comment by calebporzio** [comment]
What happens if you get rid of the "toArray' at the end?

**Comment by hulkur** [comment]
first request: collection of objects
next request: collection of arrays

**Comment by hulkur** [comment]
minimal test: 

component:

```
public $test = null;

public function mount()
{
    if (is_null($this->test)) {
        $a = new \stdClass(); $a->a = 1;
        $b = new \stdClass(); $b->a = 2;
        $this->test = collect([$a, $b]);
    }
}
```

in blade add: `@php dump($test) @endphp`

Variable $test is not touched anywhere else. 
On first request it is dumped as 

```
Illuminate\Support\Collection {#1607 ▼
  #items: array:2 [▶
    0 => {#1613 ▶
      +"a": 1
    }
    1 => {#1608 ▶
      +"a": 2
    }
  ]
}
```

On next request after some update:

```
Illuminate\Support\Collection {#632 ▼
  #items: array:2 [▶
    0 => array:1 [▶
      "a" => 1
    ]
    1 => array:1 [▶
      "a" => 2
    ]
  ]
}
```

**Comment by joshhanley** [comment]
@hulkur I'd expect that behaviour to happen as Livewire can't rehydrate stdObjects, as such they just end up as arrays. The reason for that is Laravel request object, when it runs json_decode, forces json objects to become arrays. See this issue laravel/framework#443

But it can do Eloquent collections without any issues. 

So my question is, why are you using `->toBase()` and `->toArray()`? Why don't you just use the following?

`$orgs = Organization::select(['id', 'type', 'name'])->get();`

This is one issue I found this week when helping someone else, was when using `->toBase()` and `->toArray()` together, is the base query will construct a collection of stdObjects, but when you call to array, it only converts the collection to an array, but won't convert the stdObjects to arrays (which is unexpected in my opinion). Hence why you are getting a mismatch.

If you do need it for whatever reason, there are two ways around it currently. Either convert all stdObjects to arrays as part of the query, so before and after the request you are only working with arrays; or you can use a hydrate hook to manually convert the rehydrated arrays back to stdObjects.

This is the first option
```php
$orgs = Organization::select(['id', 'type', 'name'])
            ->toBase()
            ->get()
            ->map(function($org) {
                return (array) $org;
            })
            ->toArray();
```

@calebporzio I've seen quite a few people run into issues with stdObjects. I wonder whether that is something we should support serialising and deserialising? Especially in a scenario like above with a custom select?

Would involve inspecting a collection to see if it contains stdObjects and keeping track of that as another meta type. Converting from array to stdObject is as simple as putting `(object)` cast in front of the array.

Hope this helps!

**Comment by hulkur** [comment]
this is exactly what I ended up doing.

```
            ->map(function($org) {
                return (array) $org;
            })
```

I use `toBase` when I don't need the full object but only few fields from it. Usually it's id and name for select.

**Comment by calebporzio** [comment]
Yeah, interesting. Supporting more non js data types of a bit of a never ending persuit.

I'd be interested in coming up with a better, recursive system that allows plugging in extra data type support.

This would be something for v3 I think.

I'm hesitant to keep tacking on to the current system.

Thoughts?

**Comment by nuernbergerA** [comment]
@calebporzio 

We could do some heavy lifting there and evaluate each variable on init and categorize them.

For arrays that contain non-js primitives, we can create a blueprint of the structure.

Maybe we can open a new feature request issue with a list of what is supported and what is missing?
