### ISSUE TITLE
wire:offline.class.remove does not seem to be working with 'block'.

### ISSUE THREAD

**Issue by rappasoft** [livewire/livewire#2729]
### Description

Disclaimer, wire:loading works fine by itself and it adds a `style="display:inline-block;"` but that is not what I want.

### Exact steps to reproduce

I'm attempting to show a block level tailwind alert on offline mode with this code:

```
<div wire:offline.class="block" wire:offline.class.remove="hidden" class="hidden">
    <div class="rounded-md bg-red-50 p-4 mb-4">
        <div class="flex">
            <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="text-sm font-medium text-red-800">
                    @lang('You are not connected to the internet.')
                </h3>
            </div>
        </div>
    </div>
</div>
```

However this particular bit:

```
<div wire:offline.class="block" wire:offline.class.remove="hidden" class="hidden">
```

Does not seem to be working, when I switch to offline, the `block` class gets added, but the `hidden` class does not get removed.

Judging by [this reply](https://github.com/livewire/livewire/issues/890#issuecomment-652090199), I should be able to do this.

Here is a video of it happening:

https://user-images.githubusercontent.com/6026504/115049791-1857c900-9ea9-11eb-810b-74bd9a5447fa.mov

I can't tell if i'm doing anything wrong, by the docs it would seem i'm using it correctly. 

Edit: Ironically with bootstrap classes it has the same issue, but actually shows.

```
<div wire:offline.class="d-block" wire:offline.class.remove="d-none" class="d-none d-block">
```

I have tailwind compiled to dev so I have all classes available. 

This is how the browser is interpreting each:

Tailwind:

<img width="312" alt="Screen Shot 2021-04-16 at 11 59 09" src="https://user-images.githubusercontent.com/6026504/115051868-463e0d00-9eab-11eb-834b-9fa2ae5bcce3.png">

Bootstrap:

<img width="319" alt="Screen Shot 2021-04-16 at 11 59 24" src="https://user-images.githubusercontent.com/6026504/115051884-4a6a2a80-9eab-11eb-8ff2-0c4e60ddc39f.png">

Regardless of that though, Livewire is just not removing the class.

**Context**
- Livewire version: 2.4.3
- Laravel version: 8.37.0
- Alpine version: 2.7.3
- Browser: Chrome

**Comment by nuernbergerA** [comment]
Hey @rappasoft 

currently its not possible to mix `wire:offline.class` and `wire:offline.class.remove` for the same DOM element.

**Comment by rappasoft** [comment]
@nuernbergerA thanks, I don't know why I was overcomplicating it and trying both. I was obviously getting unexplained results. I'll try your solution.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
