### ISSUE TITLE
window.livewire.restart() fails (in SPA mode) - rescan() works

### ISSUE THREAD

**Issue by lalov** [livewire/livewire#273]
I'am livewire for a component loaded in a popup, and have used window.livewire.restart() to make it work. After upgrading this is not working. 
The problem comes when the component emits events.

However; I can use window.livewire.rescan()

**To Reproduce**
1. Create a component
2. Add a button, and in the php event handler, add: 
$this->emit('menuUpdated');
3. In the browser javascript console, write: 
window.livewire.restart()
4. Click the button which calls the event. 

**Expected behavior**
Expect to have other components receive the event.

**Additional context**
Livewire version v0.3.5
Maybe the documentation for https://livewire-framework.com/docs/spa-mode/ should be updated to use window.livewire.rescan()

**Comment by calebporzio** [comment]
Updated the docs - thanks!
