### ISSUE TITLE
how store Array 

### ISSUE THREAD

**Issue by DalalYousef94** [livewire/livewire#2738]
how store Array  using livewire?

public $data=[
[
'section_type'=>'' ",
'type'   =>'' ",

]

];

**Comment by calebporzio** [comment]
Please provide a more clear question and code sample. There's not enough here to help

**Comment by olgunozoktas** [comment]
@DalalYousef94 As I understand, you need to learn how to put value to the named keys in the array.

You can use the following input field example as a reference point;

```html
<input type="text"  wire:model="data.type">
```

So, whenever you type something in the input field, it will be stored in the array key defined *type*.

**Comment by olgunozoktas** [comment]
@DalalYousef94 As I understand, you need to learn how to put value to the named keys in the array.

You can use the following input field example as a reference point;

```html
<input type="text"  wire:model="data.type">
```

So, whenever you type something in the input field, it will be stored in the array key defined *type*.

**Comment by KondorB** [comment]
Not sure what you meant, but I stumbled upon this issue and just want to warn you right ahead: `$data` is a reserved property in Livewire components, used internally, so you shouldn't use it for your own data and you also shouldn't tamper with it, or you may encounter some nasty heisenbugs.
