### ISSUE TITLE
 get the livewire components via ob_start()

### ISSUE THREAD

**Issue by AhmedHammouda** [livewire/livewire#2760]
Hi,
I am using livewire component to display notifications in my project like this "<livewire:notification />" however we want to use it in external (non-laravel) apps as well, so we use APIs for those apps to get the livewire components, via  ob_start(); capturing the generated HTML. Obstart does not process laravel blade instructions, so <livewire:notification /> does nothing. Is there an alternative way to include and process notifications in an external project?

Thank you.

**Comment by calebporzio** [comment]
Please move this to a discussion as it is not a bug

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by AhmedHammouda** [comment]
> I see this issue has been closed.

Thank you for your quick reply.
As you can see in the comment above,  @calebporzio asked me to move this to discussion so I did.
This is the discussion I create #2762
