### ISSUE TITLE
Blade Component is not refreshed

### ISSUE THREAD

**Issue by s1x** [livewire/livewire#2763]
### Description
For some reason my blade component is not refreshed correctly. If I don't use the blade component and past the HTML from the component directly into my livewire view it doest work without any problems.

Based on a variable ```$filterTopics``` I want to show the results of a specific query. The ```$filterTopics``` is correctly assigned and triggers different results. When using the ```x-dropdown``` blade component the ```$topic->id``` is not refreshed but stays the same as before. If I replace the component with the HTML code within the component, it works perfectly fine.

My components contain an a parent```<div>``` container. 

### Exact steps to reproduce
1. Change $filterTopics from NULL' to 'completed'
2. Observe HTML code still shows the old component

### Stripped-down, copy-pastable code snippets
Livewire Component
```php
    public function showTopics($filter = null)
    {
        $this->filterTopics = $filter;

        if($this->filterTopics === 'completed')
        {
            $topics = Topic::whereHas('answers', fn($query) => $query->whereCurrentUser())
                ->withCount(['answers' => fn($query) => $query->whereCurrentUser()->whereBox(3), 'questions'])
                ->with(['answers' => fn($query) => $query->whereCurrentUser(), 'questions'])
                ->get();
            $this->topics = $topics->reject(fn($item, $key) => $item->answers_count !== $item->questions_count);

        } else {
            $started = Topic::whereHas('answers', fn($query) => $query->whereCurrentUser())
                ->withCount(['answers' => fn($query) => $query->whereCurrentUser(), 'questions'])
                ->with(['answers' => fn($query) => $query->whereCurrentUser(), 'questions'])
                ->get();
            $this->topics = $started->reject(fn($item, $key) => $item->answers_count === $item->questions_count);
        }
    }
```
Livewire View
```blade
//...
            @forelse($topics ?? [] as $topic)
                <x-dropdown :menu-id="$topic->id">
//.. some code
                </x-dropdown>
```

**Context**
- Livewire version: 2.2.3
- Laravel version: 8.3.1
- Alpine version:  2.3.0
- Browser: Firefox

**Comment by s1x** [comment]
As usual, you ask the question. Re-visit your code and find the issue. The ```x-data``` is not considered as different in the DOM so I've had to add something to the template to make it unique. I've added ```id={{$menuId}}``` to the div element of the template. Afterwards it works fine.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
