### ISSUE TITLE
Validation on Collections seems to be ignored in testing, despite working on live pages

### ISSUE THREAD

**Issue by chillbram** [livewire/livewire#2782]
### Description
I'm using model binding on a Collection and while the functionality seems to work perfectly when visiting the site, validation doesn't seem to work in testing. Trying to test normal 'required' and 'email' validation rules, `Livewire::test()` continues execution after (what should be) an invalid `$this->validate()` and subsequently leaves an empty errorBag causing `->assertHasErrors()` to fail.

When following the steps in the test on the site directly (clicking on an addRow button and then nextStep button) results in two validation errors. The test, however, does not encounter these errors. From what I've tested this seems to be a problem specifically with Collection validation as adding a rule for a required string does trigger an error in the test and halts further execution. 

**Test**
```
/** @test */
    public function a_user_cannot_continue_with_empty_user_fields(){
        $this->userCreatorSetup();
        Livewire::test(UserCreator::class)
            ->call('addRow', '')
            ->call('nextStep')
            ->assertHasErrors(['users.0.email' => 'required']);
    }
```

**Livewire model**
```
public function rules()
    {
        return [
            'users.*.name' => ['required'],
            'users.*.email' => ['email', 'required'],
        ];
    }

public function nextStep()
    {
        $this->validate();

        [...]
        $this->step++;
    }
```

**Context**
- Livewire version: 2.4.3
- Laravel version: 8.39
- Browser: Firefox

**Comment by chillbram** [comment]
Despite not making any changes to the test or source code, I can no longer replicate this issue.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
