### ISSUE TITLE
Infinite loop when trying to dehydrate public prop with manualy setup relation

### ISSUE THREAD

**Issue by Briareos17** [livewire/livewire#2783]
### Description

I have list of cities, each of them has multiple filials of company.
In my logic I need both of cities and companes in independed colelctions but want to get them in one query, so I decidet to get all cities with they filials and then math through each filial and call `$city->filials->each->setRelation('city', $city)`.

An now I have looped relation of city and it filials.

### Exact steps to reproduce

- Make two models with hasMany relation (city has filials).
- Get all cities with filials `$cities = City::with('filials')->get()`
- Map through cities and setup relation for filials: `$cities->map(function ($city){ $city->filials->each->setRelation('city', $city)})`
- Extract filials in separate collection

### Stripped-down, copy-pastable code snippets

    $cities = Cache::tags(['city', 'country', 'clinic'])
            ->remember('home:cities', config('cache.cache_time'), function () use ($city) {
                return $city
                    ->with('clinics')
                    ->get()
                    ->map(function($city){
                        $city->clinics->each->setRelation('city', $city);

                        return $city;
                    });
            });

    $clinics = $cities->map(function($city){
        return $city->clinics;
    })->flatten();

**Context**
- Livewire version: [2.3]
- Laravel version: [8.38]
- Alpine version: [2.8.2]
- Browser: [Chrome latest]

**Comment by calebporzio** [comment]
Closing as this issue seems not related to livewire, but to Laravel. Reopen of I'm wrong. Thanks!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
