### ISSUE TITLE
autosize lost on component render

### ISSUE THREAD

**Issue by bastinald** [livewire/livewire#2785]
I'm trying to use `autosize` for a textarea: https://github.com/jackmoore/autosize

I can attach it to elements like this:

```javascript
import autosize from "autosize/dist/autosize";

Livewire.onLoad(() => {
    autosize(document.querySelectorAll('textarea'));
});
```

However when validation errors occur, the textarea loses autosize.

This also happens any time the component is re-rendered (say, when a prop changes).

I've tried adding this:

```javascript
Livewire.onError((message, statusCode) => {
    autosize(document.querySelectorAll('textarea'));
});
```

Which does not even keep autosize on the textarea after validation.

How do I ensure the textarea keeps autosize between renders?

**Comment by joshhanley** [comment]
@bastinald I would use the `message.processed` hook and run the autosize function in there (you will still need to keep the onLoad one for the initial load). That should run regardless if it was a re-render with or without a validation error.

See "Javascript Hooks" here https://laravel-livewire.com/docs/2.x/lifecycle-hooks

Hope this helps.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
