### ISSUE TITLE
Cannot read property 'match' of null: wire-directives.js (in function parseOutMethodAndParams)

### ISSUE THREAD

**Issue by michabbb** [livewire/livewire#2798]
### Description

okay, i try: i have a livewire component inside my page:

```html
<livewire:show-list/>
````

inside this component I have a list of items:

```html
@foreach($list as $item)
<div onclick="document.getElementById('{{'info_circle_'.$item->name}}').classList.add('animate-pulse');" wire:click="trigger('{{$item->name}}')">
   @if($active===$item->name)
      <button wire:click.prevent="findDates('{{$item->itemnr}}')" wire:loading.class="animate-pulse">Find</button>
      @livewire('show-dates', ['dates' => $dates,'itemnr' => $item->itemnr], key($item->itemnr))
   @endif
@endforech
```

the "trigger" function here sets `$active` = `$item->name` so that the new Button "Find" appears.
as soon as I click on "findDates" i get the error:

```
wire-directives.js:86 Uncaught TypeError: Cannot read property 'match' of null
    at Directive.parseOutMethodAndParams (wire-directives.js:86)
    at Directive.get (wire-directives.js:58)
    at node_initializer.js:204
    at Component.value (index.js:564)
    at HTMLDivElement.<anonymous> (node_initializer.js:196)
```

because:

![image](https://user-images.githubusercontent.com/3524595/116729718-cace7680-a9e7-11eb-8e01-c711913c3977.png)

`rawMethod` is empty.

my structure here is like a wizard, where a livewire component is inside a component that has a component inside, as further you go the more components are nested within each other:

- you get a list (top component)
- you click on a item (something gets loaded for that item)
- you choose again from the previews loaded data....
- and so on... 

like a wizard. i hope this is understandable in some way ;)

**AND**: even that error occurs, my script/site is working fine, everything gets loaded.

### Exact steps to reproduce

i don´t know, I hope my infos are helpful 🤷‍♂️ 

**Context**
- Livewire version: v2.3.17
- Laravel version: v8.9.0
- Alpine version: no idea
- Browser: Chrome (Canary)

**Comment by calebporzio** [comment]
Can you provide a repository to easily recreate the issue? Then others can more easily help you. I say this because my guess is this will only occur after nesting components

**Comment by supersophisticated22** [comment]
Same problem here with a for each loop and <li> After many hours I found a dirty fix. I added an empty <li> before the for each. Now works without a problem

**Comment by joshhanley** [comment]
@supersophisticated22 or @michabbb can either of you provide a repo that demonstrates the issue so we can investigate it?

Thanks! 🙂

**Comment by michabbb** [comment]
i try, i am quite busy at the moment, maybe this weekend....
