### ISSUE TITLE
Typed property App\Http\Livewire\Menu::$menu must not be accessed before initialization 

### ISSUE THREAD

**Issue by uarefans** [livewire/livewire#2829]
### Description
 Typed property App\Http\Livewire\Abcd::$menu must not be accessed before initialization 
**when copy and paste exactly documentation** https://laravel-livewire.com/docs/2.x/properties#nested-binding

**Context**
- Livewire version: [e.g. 2.4.4]
- Laravel version: [e.g. 8.12]
- Browser: [e.g. firefox]

[abcd.blade.txt](https://github.com/livewire/livewire/files/6437093/abcd.blade.txt)
[Abcd.txt](https://github.com/livewire/livewire/files/6437094/Abcd.txt)
[layouts.blade.txt](https://github.com/livewire/livewire/files/6437125/layouts.blade.txt)

error https://flareapp.io/share/dmknojb5

**Comment by joshhanley** [comment]
@uarefans the issue is you need to initalise `$menu` some how. You can't wire:model if there is no model in the property.

You can either use route model binding to access an existing model 

https://laravel-livewire.com/docs/2.x/rendering-components#route-model-binding

Or if you are trying to create a new one, use the null object pattern by creating an empty model in the mount method like

```php
public function mount() {
    $this->menu = Menu::make();
}
```

Hope this helps!

**Comment by uarefans** [comment]
`<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Menu;

class Abcd extends Component
{
    public Menu $menu;
`

im using php 8 and supposed to be 
The following component's $menu property will be automatically injected with no need for the mount() method.

**Comment by calebporzio** [comment]
Yeah, this could be a bug. This should work. Works you mind submitting a PR with a falling test case?

**Comment by joshhanley** [comment]
@uarefans are you talking about resolving the `$menu` model object from the container or using route model binding?

If it's route model binding, looking at your flare log, there was no ID passed in to the route to do the binding.

If it's resolving from the container, I haven't used that before, but wouldn't you need a way to specify what the container would resolve? It looks like Menu is an eloquent model, so I would think that it wouldn't know which model to resolve from the database without some form of binding? But I may be understanding that wrong 🙂

@calebporzio is there something I'm missing that should work, you think?

**Comment by uarefans** [comment]
@joshhanley thank you josh. this is my fault, cause using 

`Route::get('/menu', App\Http\Livewire\Abcd::class);`
not
`Route::get('/menu/{menu}', App\Http\Livewire\Abcd::class);`

@calebporzio i don't mind, i will support this package as i can but i need to learn more to submitting a PR with falling test. because this first time to me. and my issue closed too.

**Comment by calebporzio** [comment]
Glad it's resolved, thanks @joshhanley !!

**Comment by fanpero87** [comment]
Hello,
I'm confuse about this.

I have a livewire component that looks like this:
`
use App\Models\Account;

public Account $account;

public function rules()
    {
        return [
            'account.company_name' => 'required|unique:accounts|max:255',
            'account.domain_name' => 'required|unique:accounts|max:255',
            'account.account_name' => 'required|unique:accounts|max:255',
        ];
    }

public function save()
    {
        $this->validate();
        $this->account->save();
        $this->showCreateModal = false;
    }

public function render(){
return view('livewire.pages.clients.index', [ 'accounts' => Account:all()]);       
}
`
I have a table that shows me the data and below that a form with a modal to add a new company looks something like this:
`
<form wire:submit.prevent="save">
<x-modal wire:model.defer="showCreateModal">
<x-input wire:model="account.company_name" id="company_name"
                            type="text" name="company_name" :value="old('company_name')" required autofocus />
<x-input wire:model="account.domain_name" id="domain_name"
                                type="text" name="domain_name" :value="old('domain_name')" required autofocus />
<x-input wire:model="account.account_name" id="account_name"
                                type="text" name="account_name" :value="old('account_name')" required />
<x-button.secondary wire:click="$set('showCreateModal', false)">Cancel</x-button.secondary>
                <x-button.primary type="submit">Save</x-button.primary>
</x-modal>
</form>
`

The problem that I have is that If I do:

`
public function mount()
    {
        $this->account = Account::make();
    }`
 I got this error:
`
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'account.company_name' in 'where clause' (SQL: select count(*) as aggregate from `accounts` where `account`.`company_name` = Fake Company)
`
and If I don't have the mount function I got this:
`
Error
Typed property App\Http\Livewire\Pages\Clients\Index::$account must not be accessed before initialization
`

How can I bind my Models to Livewire?

**Comment by uarefans** [comment]
> Error
> Typed property App\Http\Livewire\Pages\Clients\Index::$account must not be accessed before initialization
> ```
> 
> How can I bind my Models to Livewire?

1. Without mount
2. Check your web routes and  /test/{account} not just /{account}, prefix /text/ (you can change whatever you named ) is required
