### ISSUE TITLE
CorruptComponentPayloadException with carriage returns in data

### ISSUE THREAD

**Issue by aztekrw** [livewire/livewire#283]
**Describe the bug**
Initial page loads fine. On any wire:model sending an update if any of the public fields has carriage returns in the data I get the error.

**To Reproduce**
eg:

data: 
address: "XXX XXX XX Avenue
↵Some End 
↵City

**Expected behavior**
Should handle these new lines in the data

**Desktop (please complete the following information):**
 - Browser  Google Chrome
Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by golam-sorwar** [comment]
<img width="1440" alt="Screenshot 2019-09-20 at 8 45 34 PM" src="https://user-images.githubusercontent.com/31072206/65336339-0425ea00-dbe8-11e9-95f2-9f0f632afbdf.png">
 I think same error

**Comment by aztekrw** [comment]
I trimmed the data, but left the new lines, and it worked.

$this->address = trim($location->address);

**Comment by golam-sorwar** [comment]
@aztekrw Thanks, it's working now

**Comment by lancepioch** [comment]
Because of the carriage returns, it seems like this is a Windows specific issue. However, carriage returns alone shouldn't break like this.

I think we should have a notice/warning for Windows and then try to get this resolved!

**Comment by calebporzio** [comment]
So what's the solution for this besides a warning? Is it a consequence of using json_encode? or the browser JSON.parse and re-stringifying thing? Or the fault of a middleware? Ideas?

**Comment by lancepioch** [comment]
I tested this on the latest version both manually inserting carriage returns via alt+013 and %0d (urldecode) and also with <textarea> on Windows. There are no exceptions and Livewire handles it correctly.

Note: 0xd is carriage return and 0xa is regular new line

\* If you change the textarea after page load, there are still no exceptions, HOWEVER, the carriage return is converted to a new line character. This is rather odd behavior, but I believe all browsers ignore carriage returns from user input by default. So I think this behavior fits with all current browsers.

Result:
![image](https://user-images.githubusercontent.com/1296882/76268526-b8720600-6244-11ea-9e03-b9f5f7e7959a.png)

Component:
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Abc extends Component
{
    public $text;

    public function mount()
    {
        $this->text = urldecode("tes%0dting%20this+ou%0at");
    }
}
```

View:
```html
<div>
    <div style="margin-left: 50px;">
        <textarea wire:model="text" placeholder="put data here"></textarea>
    </div>
    <div style="margin-left: 50px;">
        {{ $text }}
    </div>
    <div style="margin-left: 50px;">
        {{ urlencode($text) }}
    </div>
</div>
```

**Comment by aztekrw** [comment]
Thanks

I would close the ticket unless it pops up again.

**Comment by lancepioch** [comment]
@aztekrw Thanks, post here again if you encounter anymore issues with the latest versions!
