### ISSUE TITLE
Bootstrap grid problem

### ISSUE THREAD

**Issue by vasco-martins** [livewire/livewire#284]
I'm having a problem with bootstrap grid system and LiveWire. I think that LiveWire is breaking the grid system when I do a foreach. Anyone with the same problem?

**Comment by vitorarjol** [comment]
Can you provide some portion of your code / screenshots?

**Comment by lancepioch** [comment]
@vasco-martins Are you still having the issues with the latest version?

If so, could you please post some code to help us reproduce your issue?

**Comment by dbotman** [comment]
> I'm having a problem with bootstrap grid system and LiveWire. I think that LiveWire is breaking the grid system when I do a foreach. Anyone with the same problem?

Hi, 

I have the same problem with bootstrap grid and Livewire. Did you get this resolved? If so, how?
