### ISSUE TITLE
Classname in livewire-components.php

### ISSUE THREAD

**Issue by Fred7877** [livewire/livewire#2855]
### Description
When modifying the class_namespace in the configuration file with the value 'App.modules.directory.livewire.hierarchy-user', for example, the array key looks like this: app.modules.directory.livewire.hierarchy-user, which is not practical.
When modifying the class_namespace in the configuration file with the value 'App.modules.directory.livewire.hierarchy-user', for example, the array key looks like this: app.modules.directory.livewire.hierarchy-user, which is not practical.

### Exact steps to reproduce
Create a subdirectory in Http (Modules for example) and create a Livewire subdirectory
Execute the command php artisan livewire:discover and look into  bootstrap\cache\livewire-components.php file

### Stripped-down, copy-pastable code snippets
I would like to propose a modification in the LivewireComponentsFinder.php file in the build() method and change the return in this way return [Str::afterLast($class::getName(), '.') => $class];

**Context**
- Livewire version: [2.4.3]
- Laravel version: [ 8.36.2]

**Comment by calebporzio** [comment]
Interesting, thanks for following up. That does sound like a bug.

Do you feel about to open a pill request with at least a failing test?
