### ISSUE TITLE
Setup Github Sponsor or other way to donate mula

### ISSUE THREAD

**Issue by panda-madness** [livewire/livewire#286]
I really like the idea and the implementation of this project. I want to contribute, but I am too lazy to write code. Perhaps consider setting up a donation button? I'd at least send some beer money to help out.

**Comment by calebporzio** [comment]
Hey @panda-madness - thanks for the willingness to contribute! Too kind.

I applied for GitHub's sponsor program, so hopefully that goes through soon enough!

**Comment by calebporzio** [comment]
Hey @panda-madness - I have a GitHub sponsors profile set up now! https://github.com/sponsors/calebporzio
