### ISSUE TITLE
Wire:click working when element has disabled attribute

### ISSUE THREAD

**Issue by Javierko** [livewire/livewire#2872]
### Description
When element with wire:click is clicked and there is also `disabled` attribute, wire:click is still being fired even with disabled attribute.
Problem is probably on all elements except button.

### Exact steps to reproduce
Just make some basic livewire component and copy code below.

### Stripped-down, copy-pastable code snippets
```
<div wire:click="test(1)" wire:loading.attr="disabled" wire:target="test" x-data @alfa.window="console.log($event.detail.test)">
  Click me
</div>
<div wire:click="test(2)" wire:loading.attr="disabled" wire:target="test" x-data @alfa.window="console.log($event.detail.test)">
  Click me
</div>
```
```
public function test($number)
{
  $this->dispatchBrowserEvent('alfa', ['test' => $number]);
}
```

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.40.0
- Alpine version: 2.8.2
- Browser: MS Edge

**Comment by PH7-Jack** [comment]
Hello @Javierko 

The html **div** tag does not has **disabled** attribute, use **button** tag instead, or add **pointer-events: none** style in div
`wire:loading.class="pointer-events-none"`

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

**Comment by Javierko** [comment]
Hey @PH7-Jack,

thanks for replying on my issue. I tried it, it's a bit limiting but whatever.

**Comment by wizzymore** [comment]
I don't think this is limiting at all, i think this is pure html and js logic and behaviour.
Divs aren't meant to be clickable.

Take here another example from React, which does the exact same behavior because this is normal:
[codebox](https://codesandbox.io/embed/compassionate-hooks-ig84s?fontsize=14&hidenavigation=1&theme=dark&view=preview)

**Comment by Javierko** [comment]
Yes, I agree.

Problem is fixed by using `<button>` element instead.

Thanks guys.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
