### ISSUE TITLE
Intermittent unresolvable dependency when used with Laravel Octane

### ISSUE THREAD

**Issue by georgesa** [livewire/livewire#2878]
### Description

I get this error from time to time only with Livewire components. Not sure how to reproduce it or what causes it.

```
Illuminate\Contracts\Container\BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> $methods ]] in class Illuminate\Routing\Route
```

**Context**
- Livewire version: 2.4.4
- Laravel version: 8
- Octane version: 1.0.0
- Browser: All

**Comment by richan-fongdasen** [comment]
I also get the same intermittent error. At first, switching between Livewire routes didn't produce any error. The error occurs mostly when I move to a different Livewire route after updating the Livewire component's state a few times on the previous page.

**Context**

- Livewire version: 2.4.4
- Laravel framework version: 8.41.0
- Octane version: 1.0.0 (swoole)
