### ISSUE TITLE
a problem with livewire wire:key rendering.

### ISSUE THREAD

**Issue by jskorlol** [livewire/livewire#2885]
### Description

a problem with livewire wire:key rendering.

### Exact steps to reproduce

1. Randomize delete in the middle.
2. Then, delete the last item.
3. An error occurs.

1. Keep deleting the first one, or
2. If you keep deleting the last one
The problem does not arise.

If you delete the one in the middle, then delete the last one, you will have a problem. All "$value->id" will be fixed to the last deleted value.

The video looks fast, but even if it isn't fast, problems arise. (Intermittently)

### Stripped-down, copy-pastable code snippets

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    protected $listeners = ['refreshParent' => '$refresh', 'delete'];

    public $select = null;

    public function delete($id)
    {
        $item = \App\Models\Order::find($id);
        $item->delete();

        $this->emit('refreshParent')->self();
    }

    public function open($id)
    {
        $item = \App\Models\Order::find($id);
        $this->select = $item;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        $items = \App\Models\Order::where('state', 1)->orderBy('id', 'DESC')->paginate(10);

        return view('livewire.test', [
            'items' => $items
        ]);
    }
}
```

```html
<div>
    <div>
        {{ var_dump($select) }}
        <table class="table-fixed min-w-full">
            <thead>
            <tr>
                <th scope="col" class="px-3 py-2 sm:px-5 sm:py-3 bg-gray-50 text-left text-xs font-medium text-gray-800 uppercase tracking-wider whitespace-nowrap">
                    ID
                </th>
                <th scope="col" class="px-3 py-2 sm:px-5 sm:py-3 bg-gray-50 text-left text-xs font-medium text-gray-800 uppercase tracking-wider whitespace-nowrap">
                    NAME
                </th>
                <th scope="col" class="px-3 py-2 sm:px-5 sm:py-3 bg-gray-50 text-left text-xs font-medium text-gray-800 uppercase tracking-wider whitespace-nowrap">
                    DEL
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $key => $value)
                <tr wire:key="{{$value->id}}">
                    <td>{{ $value->id }}</td>
                    <td x-data x-on:click="$wire.call('open', '{{ $value->id }}')">NAME {{ $value->name }}</td>
                    <td wire:click="delete('{{ $value->id }}')">{{ $value->id }} DEL</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

```

![GIF 2021-05-19 오후 4-24-38](https://user-images.githubusercontent.com/12728472/118773698-0ad69a00-b8c0-11eb-9767-895c20386aed.gif)

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.42
- Alpine version: 2.3.2
- Browser: Chrome

**Comment by jskorlol** [comment]
This is no problem.

open sends the id value to the modal component,
When an event to close a modal or a delete process is performed
I had to clear the data in the modal.
(The problem occurred because the id value is stored in the modal)

Sorry.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
