### ISSUE TITLE
How to include a class to livewire component?

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [livewire/livewire#290]
Hello there,

I'm trying to use a class with helper functions in a livewire component. Like this:

```php
<?php
namespace App\Http\Livewire;

use Illuminate\Support\Facades\DB;
use Livewire\Component;
use App\Services\Pokemon as PokemonService;

class Search extends Component
{
    protected $pokemonService;

    public $searchInput;
    public $pokemon;

    public function __construct($id, PokemonService $pokemonService)
    {
        parent::__construct($id);
        $this->pokemonService = $pokemonService;
    }

    public function render()
    {
        $dbSearch = '%' . $this->searchInput . '%';
        $pokemonNames = DB::table('pokemon')
            ->where('name', 'like', $dbSearch)
            ->get()->toArray();

        if (strlen($this->searchInput) > 2) {
            $this->pokemon = $this->pokemonService->getData($pokemonNames);
        } else {
            $this->pokemon = [];
        }

        return view('livewire.search');
    }
}
```

In order to have access to the 'getData' function, I need to define the construct and parent construct. This results in this error:

```
Too few arguments to function App\Http\Livewire\Search::__construct(), 1 passed in /Users/jeba/Projects/jeroen/pokepocket/vendor/livewire/livewire/src/LivewireManager.php on line 74 and exactly 2 expected (View: /Users/jeba/Projects/jeroen/pokepocket/resources/views/search.blade.php)
```

Is it possible what I'm trying to do? Or is there another way to use public functions without making them static?

**Comment by jeroenbalk-adwise** [comment]
I tried it like this, with no success:

`
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\DB;
use Livewire\Component;
use App\Services\Pokemon as PokemonService;
use PokeAPI\Client;

class Search extends Component
{
    public $searchInput;

    public $pokemon;

    protected $pokemonService;

    public function mount()
    {
        $this->pokemonService = new Client();
    }

    public function render()
    {
        $dbSearch = '%' . $this->searchInput . '%';
        $pokemonNames = DB::table('pokemon')
            ->where('name', 'like', $dbSearch)
            ->get()->toArray();

        if (strlen($this->searchInput) > 2) {
            $this->pokemon = $this->pokemonService->getData($pokemonNames);
        } else {
            $this->pokemon = [];
        }

        return view('livewire.search');
    }
}
`

It's only possible to call static functions?

**Comment by calebporzio** [comment]
I'm surprised that didn't work? I'd love it if you could trivialize the example more so I can try it locally.

In the meantime, you can just new it up where you need it, or resolve it out of the container when you need it, OR you can make a method that news it up. 

But the protected property SHOULD do it. I'm surprised it doesn't.

**Comment by jeroenbalk-adwise** [comment]
When I try to create a new instance in the mount() method, I get an other which is related to the Symfony Cache managing classes. I'll create a repository today so you can try it yourself today.

**Comment by calebporzio** [comment]
Great, thanks!

**Comment by jeroenbalk-adwise** [comment]
Hey @calebporzio ,

I created a private repository and invited you to collaborate. It's pretty much a clean laravel installation with some livewire components. The search page contains a search component in which I'm trying to inject a helper class instance from the App/Services namespace.

Just pull the repo, create a db, run migrations and you're good to go.

Let me know if you need more information. I'm looking forward to fix this together!

**Comment by jeroenbalk-adwise** [comment]
Found anything on this yet? :)

Thx in advance

**Comment by lancepioch** [comment]
@jeroenbalk-adwise Are you able to try this with the latest full release of Livewire? If it's still an issue, invite me to the repo and I'll take a look into it
