### ISSUE TITLE
Wire:click not bound to every item

### ISSUE THREAD

**Issue by filipac** [livewire/livewire#2904]
### Description
I have a weird bug/problem with Livewire on a project. It is a quiz app and every time you answer a question you click next and another question in the flow appears. Here I encounter the weird bug.
I have 6 labels with `wire:click` on them, two of the labels do not have the `wire:click` event on them ONLY when I come from a previous question (the content of the component changes).
Here is the UI:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/271155/119629746-f8f07c00-be16-11eb-8fd3-4f9bea253737.png">
The LLC row and the last one do not have the wire:click event on them but if I refresh, the wire:click events are bound to those two too.
I use Firefox Developer tools and here is the proof that at re-render the events are not bound for the two labels:\

**At rerender**
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/271155/119630001-33f2af80-be17-11eb-8320-e95e3f6635ce.png">

**After refreshing the page**
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/271155/119630109-4cfb6080-be17-11eb-9e97-1c34519160a7.png">

You can see the little `event` tag after the label tag is not there, that shows that the events are not bound. But not sure why only for those two, what makes them special, all other <label>'s in other question work ok, the only time I encounter this bug is for this particular question.

### Exact steps to reproduce
I cannot share the whole code here but I can show you the exact page where it happens:
Visit this: https://vetted.qa-server.com/6cdbe3fc-96aa-4779-8f5c-472f1cd66ac9
If you load the page first time, clicking `LLC` or `loan is not a business entity or investment vehicle, for example real estate` it works the first time, but click back one time and next two times you arrive at the same page where clicking LLC or the last option does not do anything because the event is not bound there anymore.

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.43.0
- Alpine version: Not using alpine
- Browser: Firefox, Chrome

**Comment by filipac** [comment]
Please excuse my dumbness and that I've wasted an issue on this repo :))

If someone else stumbles upon this in the future the key here (pun intended) is to add a unique `wire:key` to every item in a loop. Dom diffing can cause this problem and indeed after I added wire:key to every `<label>` in the code above, the problem disappeared.

[Troubleshooting](https://laravel-livewire.com/docs/2.x/troubleshooting) docs mention this, but you know, 6 hours of debugging can save you from reading 5 minutes of documentation.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/271155/119632839-da3fb480-be19-11eb-97c3-d7dbead5e850.png">

Disaster avoided, Livewire docs to the rescue!

<img src="https://media.giphy.com/media/VvxtXb86Lwicw/giphy.gif"/>

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
