### ISSUE TITLE
Console error when using if/else to swap buttons

### ISSUE THREAD

**Issue by deanzod** [livewire/livewire#2909]
I want to have a button to turn on 'multi select' and display checkboxes. After clicking that button I want it to disappear and be replaced with a submit button. When doing this using if/else, the submit button throws a js error in the console. Without the else it works

Console error: `Cannot read property 'match' of null`

### Exact steps to reproduce
Create a button to set a boolean value
create another button to fire a function
put them in an if/else statement based on the boolean value
click button one, then click button 2 when it shows

Demo here:
https://laravelplayground.com/#/snippets/08b4712d-2a22-4fcf-af4d-c21be6e835a4

**Context**
- Livewire version: 2.2.4
- Laravel version: 8.29
- Browser: Chrome

**Comment by deanzod** [comment]
It turned out that `.prevent` was causing it - I don't know why but removing it removes the error

**Comment by nuernbergerA** [comment]
Wrap the condition with the buttons in a div or give both buttons a unique "ID" with wire:key

**Comment by deanzod** [comment]
> Wrap the condition with the buttons in a div or give both buttons a unique "ID" with wire:key

It's already wrapped and I did try giving keys. It seems to be a bug with .prevent on buttons

**Comment by deanzod** [comment]
> https://laravelplayground.com/#/snippets/37c5c545-798f-4ca8-bb60-8ea731c142e9

odd that I failed to get that working when I tried earlier. Thanks!
