### ISSUE TITLE
Support disabling background requests

### ISSUE THREAD

**Issue by tillkruss** [livewire/livewire#291]
https://github.com/livewire/livewire/commit/6de3988039b46461b82d871e4550dcaf6b4311e6 changed from no background requests to 5% reduced rate. It would be great to disable the polling in the background entirely, so the animations will occur when a user switches back to the tab.

**Comment by calebporzio** [comment]
Ah, yes. A PR for this would be great, and fairly trivial. Up for the task?

Here's what I think the API would look like:

```
<div wire:poll.hybernate>
```

What do you think?

**Comment by tillkruss** [comment]
Great API, but I'm slammed the next 2 weeks 😕
