### ISSUE TITLE
Property [$array.key] not found on component

### ISSUE THREAD

**Issue by geraldofebrian** [livewire/livewire#2914]
**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: [e.g. Chrome, Safari]

i have an issue with nested binding data. i'm developing form-wizard and consist of several states. So i tried the following:
```
public $state = [];
```
and in mount() function, i do the following:
```
$this->state = [
    'form_1' => [
        'attribute' => null,
        'another_attribute' => null,
    ],
    'form_2' => [
        'attribute' => null,
        'another_attribute' => null,
    ],
];
```
then i process the data from array as usual. i tried the validation and it works, but when i want to process the data from the state it thrown an error:

`Property [$state.form_1.attribute] not found on component: [component.class]`

did i miss something to be able to use this?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
