### ISSUE TITLE
Can access original filename

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#2918]
### Description
When you upload a file through Livewire you completely lose the original filename. There should be at least a way of accessing it even if for some reason we need to rename the temporary file.

**Comment by mokhosh** [comment]
This is really important when you upload multiple files at once, and they become totally undistinguishable.

**Comment by mokhosh** [comment]
Let's say you're uploading 30 files and attaching them to a "course" and then you want "students" to be able to download them. Filenames should make some sense, right?

**Comment by nuernbergerA** [comment]
Hey @mokhosh 

you can access the original filename from a `TemporaryUploadedFile` via `getClientOriginalName()`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by mokhosh** [comment]
@nuernbergerA That returns "blob" for me. I'm using filepond.

**Comment by mokhosh** [comment]
@nuernbergerA this might be related https://github.com/pqina/react-filepond/issues/125
