### ISSUE TITLE
Permission to use Laravel brand in url: https://laravel-livewire.com

### ISSUE THREAD

**Issue by tommica** [livewire/livewire#292]
Taylor has asked in the past to people not use laravel as part of the domain, so maybe it would be a good idea to confirm that it's ok? Or maybe you have already done it?

https://twitter.com/taylorotwell/status/1158396399949701127

**Comment by 2kodes** [comment]
@tommica 
I think he did. per [this twitter thread](https://twitter.com/calebporzio/status/1175044435475873793)

**Comment by calebporzio** [comment]
Thanks for checking in on this. I did confirm it was ok with him before I did it.
