### ISSUE TITLE
Modal with dynamic content.

### ISSUE THREAD

**Issue by Dandelosreyes** [livewire/livewire#294]
**Describe the bug**
The bug is about a modal. I created a modal using livewire. The modal have a dynamic content which can be updated thru the use of button. However upon clicking the button the modal disappear and the backshadow is stil there. MY expected output is that the modal will not hide and the content will be updated. 

Can anyone enlighten me on this matter? Or am i using the livewire wrong?
I'm also thinking about creating an event and emitting it. Then js will listen on it the and dom will be updated. But this one haven't tried it yet. And  i think this will work. Will update you guys about this solution. *I'm too lazy to do this haha. Hope you can help me out on this one.

**To Reproduce**
1. Create a modal with a dynamic content using livewire component.
2. Add a function to a button. 
3. Click the button and the modal will automatically hide.
Note: My button type is button.

**Expected behavior**
The expected behavior will be the said dynamic content will be updated and the modal will not hide.

Thanks!, 
Dan

**Comment by adrianschubek** [comment]
Can you provide some code or screenshots?

**Comment by faustbrian** [comment]
@Dandelosreyes could you provide a repository or gist with enough code to reproduce the issue? Also, is the modal purely in blade or is it a Vue component that has to be re-rendered?

**Comment by kdion4891** [comment]
This happened to me with bootstrap. Basically if you use `data-toggle="modal"` and `wire:click` on a button, it will flash the modal and then dissapear, and the backdrop will remain.

I'm not sure why the modal dissapears, so I've had to resort to using inline javascript to call `.modal('show')` with an emitted event to get it to work properly.

**Comment by Dandelosreyes** [comment]
Hi guys!
Sorry for not responding to your answers lately.
@kdion4891 yep I also used bootstrap and for this question. I think it has something to do at rendering the dom or something. Basically it resets all the class/styles to default after an event.  So I think that's the reason why the modal disappears. Correct me If I'm wrong.

**Comment by Dandelosreyes** [comment]
And I don't think that this is a bug haha sorry!
