### ISSUE TITLE
Typeahead not working in Livewire

### ISSUE THREAD

**Issue by isaacdarcilla** [livewire/livewire#2942]
### Description

I have this textbox with typeahead, it seems that after typing a few letters, the typeahead suggestions not showing anymore.

### Exact steps to reproduce

Custom.js

```js

$(document).ready(function () {
    var dataSource = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('region_name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        prefetch: {
            url: "https://api.jsonbin.io/b/60beeba24d024768b8f2388b"
        }
    });

    dataSource.initialize();

    $('.region').typeahead({
        highlight: true
    }, {
        displayKey: 'region_name',
        source: dataSource.ttAdapter()
    });

});
```

create-school.blade.php

```php
        <div class="mb-3 row">
            <label class="col-sm-3 col-form-label">Region</label>
            <div class="col-sm-9" id="region">
                <input wire:model="school_region" data-provider="region" class="region form-control" type="text" placeholder="Type and select region">
                @error('school_region') <span class="text-danger f-12 mt-1">{{ $message }}</span> @enderror
            </div>
        </div>

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: [e.g. 2.2.3]
- Laravel version: [e.g. 8.3.1]
- Alpine version: [e.g. 2.3.0]
- Browser: Chrome Latest

**Comment by nuernbergerA** [comment]
Hey @isaacdarcilla, check the example on the [docs](https://laravel-livewire.com/docs/2.x/alpine-js#creating-a-datepicker) on how to interact with such third-party stuff.

Cheers Adrian

**Comment by isaacdarcilla** [comment]
Resolved this by adding debounce property to model:

From

```html
<input wire:model="school_region" data-provider="region" class="region form-control" type="text" placeholder="Type and select region">
```

To

```html
<input wire:model.debounce.100s="school_region" data-provider="region" class="region form-control" type="text" placeholder="Type and select region
```

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
