### ISSUE TITLE
Method model bind

### ISSUE THREAD

**Issue by robsontenorio** [livewire/livewire#295]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would be nice if methods just get working with model bind, like routes binding.

```js
<button wire:click="remove(78)">
```

```php
function remove(User $user){
     $user->delete();
}
```

Ps: edited “removeUser” >> “remove”

@faustbrian

**Comment by faustbrian** [comment]
I feel like the implementation of this would add a lot of complexity as you would need to check all methods that exists on the class and their parameters to figure out if a matching method exists.

@calebporzio is this something that would be desired to have in Livewire?

**Comment by calebporzio** [comment]
Hmm, this is definitely something that might be nice at some point. For now, let's hold off on it to focus on stabilizing the core code and API.

Good suggestion though!
