### ISSUE TITLE
When using Route::is in a component view, emitting refresh on the component loses the Route::is

### ISSUE THREAD

**Issue by bastinald** [livewire/livewire#2959]
I have a navbar component that uses Route::is to set the active link color

The navbar has the user avatar image in it

When I update my avatar, I'm emitting $refresh so that the avatar image changes to the new one

It works good, except that the active link color (via Route::is) is lost

I guess because its thinking the request is coming from livewire and not an actual route

Does anyone know a quick fix for this?

**Comment by juno-w** [comment]
Hi @bastinald , show us your code :)

**Comment by joshhanley** [comment]
@bastinald yeah, due to subsequent requests using the `/livewire/messages` endpoint, `Route::is` won't work.

If I need url/ route information, I generally capture that information in the mount method and save it to a public property on the component. I can then access that to do my own checks against, to set nav link colours. But you would have to remove `Route::is` and do a check manually.

Hope it helps!

**Comment by bastinald** [comment]
> @bastinald yeah, due to subsequent requests using the `/livewire/messages` endpoint, `Route::is` won't work.
> 
> If I need url/ route information, I generally capture that information in the mount method and save it to a public property on the component. I can then access that to do my own checks against, to set nav link colours. But you would have to remove `Route::is` and do a check manually.
> 
> Hope it helps!

gotcha, thanks.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
