### ISSUE TITLE
Minimun Laravel Version

### ISSUE THREAD

**Issue by cloudstudio** [livewire/livewire#296]
Hello! I can't find in docs, what is the minimum version of Laravel required ? 

I use it in Laravel 6 in other project, and all right.

When I try to install in Laravel 5.7, I get this error and all project crash ( so I need come back all )

I don't know if is not compatible or maybe fix its posible?

![screenshot](https://user-images.githubusercontent.com/3589377/65583553-b6aad380-df7f-11e9-8ce4-772eae8b5e05.png)

Thanks in advance!

**Comment by deevus** [comment]
Had the same issue with Laravel 5.7

**Comment by devcircus** [comment]
That is a php function so it may be an issue with the php version.

**Comment by deevus** [comment]
I'm using PHP 7.2

**Comment by cloudstudio** [comment]
Yep, I try with PHP 7.2 / 7.3 , same problem.

So probably doesn't work with laravel 5.7

**Comment by calebporzio** [comment]
I'd love a PR to make Livewire compatible with older versions of Laravel and PHP. There is nothing rely on in newer versions. Anyone up for making it more backward compatible?

**Comment by morpheus7CS** [comment]
Hey all,

I have this to confirm the issue exists. But I propose raising the minimum Laravel version to `"^5.8"`. Here are my reasons why:

1) In order for Livewire to work with Laravel 5.7., it needs `"nesbot/carbon": "^2.0"`. 
If you indeed run the proposed command `./vendor/bin/upgrade-carbon`, it however, wants to upgrade both the `"nesbot/carbon": "^2.0"` and `"laravel/framework": "^5.8"`.

I'll try sumbitting another one to the laravel/frame

2) Laravel v. 5.7. has stopped getting security fixes on September 4th 2019.

I've also submitted a pull request for it.

**Comment by lancepioch** [comment]
The minimum version supported is currently Laravel 5.6.

Your 5.7 app should work now. Please double check and close this if so, thanks @cloudstudio!

**Comment by cloudstudio** [comment]
All right for me 💪
