### ISSUE TITLE
@entangle breaking when another prop placed above it in html

### ISSUE THREAD

**Issue by leecolarelli** [livewire/livewire#2966]
### Description
I have just found an issue where I was trying to use @entangle to show/hide a modal, and as soon as I placed an element with another prop/variable above the alpine x-data `x-data="{ modalOpen: @entangle('modalOpen') }"` component, the @entangle/x-show would break.

### Stripped-down, copy-pastable code snippets

blade file...
```
<div x-data="{ modalOpen: @entangle('modalOpen') }">

    <div x-show="modalOpen" class="fixed z-20 inset-0 overflow-y-auto" role="dialog" aria-labelledby="modal-title"
         aria-modal="true">
```

livewire component...
```
class RegisterUser extends Component
{
    public string|null $userType; // Property state for the user type
    public bool $modalOpen = false;
    public string $message = 'test';
```

This is working correctly. The modal is hidden on page load, and I have a button to show it.

However, as soon as I add `<h1>{{ $message }}</h1>` ABOVE the alpine component, the modal SHOWS on page load. I.e.

```
<h1>{{ $message }}</h1>

<div x-data="{ modalOpen: @entangle('modalOpen') }">

    <div x-show="modalOpen" class="fixed z-20 inset-0 overflow-y-auto" role="dialog" aria-labelledby="modal-title"
         aria-modal="true">
```

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.41.0
- Alpine version: 2.8.2
- Browser: Chrome

**Comment by leecolarelli** [comment]
Nevermind! Was fixed by only having one root element in the blade file!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
