### ISSUE TITLE
2.5.0 APP_DEBUG false stops Livewire

### ISSUE THREAD

**Issue by fabricecw** [livewire/livewire#2971]
### Description
After updating from Livewire 2.4.4 to 2.5.0, Livewire stops working when `APP_DEBUG` in the `.env` file is set to `false`.
We tried it with a fresh installation of Laravel 8 (v8.46.0).

If `APP_DEBUG` is set to `true`, everything comes back to normal. 
If we downgrade to Livewire 2.4.4, everything works fine.

Please note: We noticed this behavior a few minutes ago. We were not yet able to do further investigations but thought we need to report this issue asap.

### Exact steps to reproduce
1. Install a fresh Laravel project
2. Install Livewire
3. Make a new component and a Livewire method with a `dd()` 
4. Use a button in the component's blade and trigger the Livewire method

- If  `APP_DEBUG` in `.env` file is set to `true`, a modal opens with the DD
- If  `APP_DEBUG` in `.env` file is set to `false`, nothing happens (not even a Livewire request)

### Stripped-down, copy-pastable code snippets

**Context**
- Livewire version: 2.5.0
- Laravel version: 8.46.0
- Alpine version: -
- Browser: Crhome

**Comment by Restingo** [comment]
I can confirm this issue and just downgraded to 2.4.4. Please fix.

**Comment by marcandreappel** [comment]
I confirm, I downgraded and all components work again.

**Comment by nuernbergerA** [comment]
A PR is already open.

**Comment by fabricecw** [comment]
thanks @nuernbergerA !

**Comment by nuernbergerA** [comment]
@fabricecw props to @cubemastercodes i only confirmed the fix and informed @calebporzio

**Comment by nuernbergerA** [comment]
@fabricecw release is tagged. Please test it and close if the issue is resolved.

**Comment by fabricecw** [comment]
Everything works fine with the release. Thanks for the quick PR @cubemastercodes and @nuernbergerA for keeping everyone up to date!

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by relaypilot** [comment]
I am experiencing this issue after updating composer today, which pulled the [latest commit](https://github.com/livewire/livewire/commit/aba94bc2ac9c5651845676fbe9ac672ff3d0fc22).

        "laravel/framework": "^8.40",
        "laravel/jetstream": "^2.3",
        "livewire/livewire": "^2.5",

**Comment by andersondalmina** [comment]
I can confirm this issue. Looks like we lost the changes made to fix it on: https://github.com/livewire/livewire/pull/2970/files.
The new release is without these changes.

**Comment by andersondalmina** [comment]
I found this commit on `master`: https://github.com/livewire/livewire/commit/85e9d3cd28d987a471429776bf58688fcb44c12c
Looks like some IDE linter are removing the necessary `;`

**Comment by Restingo** [comment]
REOPEN

**Comment by Restingo** [comment]
Pls merge #3263

**Comment by nuernbergerA** [comment]
@Restingo please don't re-open issues, as livewire transitioned to discussions.

Caleb will merge this asap after he is awake.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by timmarner** [comment]
Am having the same problem livewire 3.2. if debug = true. I don't want to downgrade to 2.4 because of other dependences.

**Comment by PhiloNL** [comment]
> Am having the same problem livewire 3.2. if debug = true. I don't want to downgrade to 2.4 because of other dependences.

Can you check your browser console and see if livewire.js is loaded or if you get a 404?

**Comment by timmarner** [comment]
yes its 404.
