### ISSUE TITLE
Variable not updating.

### ISSUE THREAD

**Issue by larsvanherwijnen** [livewire/livewire#2980]
I'm trying to make a search function. But the variable is not updating like it should. I have tried other project on my pc and those  don't work either. But it work the exact same code works on a different pc.

form input 
![input](https://user-images.githubusercontent.com/77294984/122388341-175a1b00-cf70-11eb-9fbc-21b4abe94615.PNG)

The browser result.
![image](https://user-images.githubusercontent.com/77294984/122388580-4a041380-cf70-11eb-957b-0a1e007e370a.png)

The live component.
![image](https://user-images.githubusercontent.com/77294984/122388730-73bd3a80-cf70-11eb-8ea0-2779c845ea90.png)

Network tab of inspector
![image](https://user-images.githubusercontent.com/77294984/122389032-c8f94c00-cf70-11eb-8136-ee87f2e443d5.png)
![image](https://user-images.githubusercontent.com/77294984/122389060-d282b400-cf70-11eb-9519-d4fd0a5b8124.png)

''Test'' should be between the quotes under the input field. 
![image](https://user-images.githubusercontent.com/77294984/122389227-03fb7f80-cf71-11eb-8cda-a7a406fc1f15.png)

I hope some can help!
Thank you in advance.

**Context**
- Livewire version: [2.5.1]
- Laravel version: [8.47.0]
- Browser: [chrome]

**Comment by larsvanherwijnen** [comment]
This doens't work
![image](https://user-images.githubusercontent.com/77294984/122399792-69546e00-cf7b-11eb-9c91-55f8374dd166.png)
You need to use a div around it like this 
![image](https://user-images.githubusercontent.com/77294984/122400084-ade00980-cf7b-11eb-8b5b-22a6173377b6.png)

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
