### ISSUE TITLE
Echo EncryptedPrivate listener

### ISSUE THREAD

**Issue by JuanRangel** [livewire/livewire#2982]
We are moving over to livewire from Vue to handle our chat application and in doing so I realized that livewire does not support laravel echo's encrypted private channels. so this does not work 

```
public function getListeners()
{
    return ["echo-encryptedPrivate:conversation.{$this->conversation->id},NewReplyPosted" =>  "updateConversation"];
}
```

I created a pull request to add the encryptedPrivate listener here https://github.com/livewire/livewire/pull/2973

**Comment by JuanRangel** [comment]
#2973 adds the encryptedPrivate listener

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
