### ISSUE TITLE
[Vuetify 2] v-text-field  and wire:model

### ISSUE THREAD

**Issue by robsontenorio** [livewire/livewire#301]
**Describe the bug**

Well, dont know if a bug or has no support for Vuetify 2 components. I am getting a error: `TypeError: Cannot read property 'getAttributeNames' of null`.

**To Reproduce**

1. Fresh install Laravel 6 + Vuetify 2
2. Create a livewire component according example bellow
3. Hit "add user" button
4. User will be added and the list will be updated
5. See error

**Expected behavior**

No erros shown.

**Screenshots**
![Captura de Tela 2019-09-25 às 22 40 13](https://user-images.githubusercontent.com/118955/65651659-8433c180-dfe5-11e9-8afa-7a0b9b0c13a5.png)

**Desktop (please complete the following information):**

 - Chrome / OSX

**Additional context**

views/livewire/users.blade.php

```php
<div>
    <h2>Users</h2>
    @foreach ($users as $user)
    <p>
        - <strong>{{ $user->name }} / {{ $user->email}}</strong>
    </p>
    @endforeach
    <br>

    <v-text-field label="Name" wire:model="name"></v-text-field>
    <v-text-field label="E-mail" wire:model="email"></v-text-field>
    <v-btn wire:click="addUser">add user</v-btn>
</div>
```

Users.php

```php
<?php

namespace App\Http\Livewire;

use App\User;
use Livewire\Component;

class Users extends Component
{
    public $name = null;
    public $email = null;
    protected $users;

    public function mount()
    {
        $this->reset();
        $this->users = $this->getUsers();
    }

    public function reset()
    {
        $this->name = null;
        $this->email = null;
    }

    public function getUsers()
    {
        return User::orderBy('id')->get();
    }

    public function render()
    {
        return view('livewire.users', [
            'users' => $this->users
        ]);
    }

    public function addUser()
    {
        User::create([
            'name' => $this->name,
            'email' => $this->email,
            'password' => 'blah'
        ]);

        $this->users = $this->getUsers();
        $this->reset();
    }
}
```

**Comment by davidpiesse** [comment]
It may be that the ```name``` property is restricted, like ```id``` is...
