### ISSUE TITLE
/livewire/message/{componentName} throws 404

### ISSUE THREAD

**Issue by jacobsmith** [livewire/livewire#305]
**Describe the bug**
I have followed the instructions in the "Getting Started" guide but when I attempt to send any data back to the server (i.e., `wire:click="increment"`, etc.), I get a 404 that `{serverName}/livewire/message/counter` does not exist. I've also tried just `${serverName}/livewire/message`, `/livewire/message/abc`, etc. via cURL and that also returns a 404. I would expect that to return a "ModelNotFound" type exception if it were actually trying to look up those classes. It's like the service provider isn't mounting the routes?

**To Reproduce**
Not sure if it's just my machine or not.

**Expected behavior**
Requests to `/livewire/message/counter` get relayed to the Counter livewire component and are able to be handled.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional Context:**
I am able to view the component on first load (so rendering is working through livewire) but no interactions can take place.

Our application also makes use of `Route::group(['prefix' => '{company_slug}', function() { ...` to provide users company.com/acme/dashboard, etc. We have other top-level routes (status pages, etc.), so everything is not behind that prefix, but I wonder if that could be causing issues during registration of the routes.

**Comment by jacobsmith** [comment]
Okay, I've been digging in and was able to figure out a workaround:

Our app relies on a middleware that properly sets the company of the user based on the Route prefix (with additional security validation, don't worry (: ). Because of that, we needed our requests to go to `server.com/company-slug/livewire/message`. To accomplish that, I had to:

Manually add the route from within the Route group with the prefix to HttpConnectionHandler:

```
Route::group(['prefix' => '{company_slug}', function() {
    Route::post('livewire/message/{name}', '\Livewire\Connection\HttpConnectionHandler');

    ...rest of the routes
}
```

Then, in the page where I was using livewire, I needed to override the `livewire_app_url`, but only _after_ it was initialized, because our assets are served from the root path (all companies see the same assets, so those aren't "scoped" per company).

```
    @livewireAssets
    <script>
        document.addEventListener('livewire:available', function() {
            setTimeout(function() { window.livewire_app_url = '/{{ $company->slug }}'; }, 100);
        })
    </script>
```

At this point, livewire mounts "normally" (i.e., includes all of the JS and CSS scripts/tags/etc. that it does, but _then_ we change the `livewire_app_url` so that the `fetch` method in the HTTP Connection class will properly scope to the company slug.


Ideally, `livewire_app_url` would be a different setting than `livewire_assets_url` to account for a situation like this. I'm not sure if that sort of configuration would be welcome or not (I know the library is trying to be convention over configuration). If it is, I'd be willing to put together a PR splitting out those two variables since I do believe they represent distinct concepts, at least in this instance (though, admittedly, it is a routing scheme that isn't super widely used). I'll leave this issue open for further discussion, but feel free to close if it's not something the library is looking for now. Thanks!

**Comment by billriess** [comment]
I'm actually getting this same issue without prefixed routes.

**Comment by jacobsmith** [comment]
@billriess I'd suggest you double check what middleware are being added to that route. Livewire will re-use whatever middleware were present on the initial page load, so if there's an authentication/authorization middleware that's present, it may be expecting a header that Livewire isn't adding (or something like that). Putting breakpoints in our middleware is what finally got me to understand how it was flowing through our stack - hopefully that approach can be of use to you as well!

**Comment by billriess** [comment]
@jacobsmith thanks! I will look into that.

I think you raised some good concerns though. We're using Vapor and have different environments. I have not deployed anything with Livewire just yet because we just started integrating it but I wonder if it will respect how Vapor handles assets.

I did publish the Livewire config and set `'asset_url'  => config('app.asset_url', null),` so, in theory, it should work but I'm a little concerned with `livewire.app_url` as that would be different subdomains in our case.

I also am not using the "out-of-the-box" method for Livewire. I have updated the `livewire.view_path` in the config as well. Our app's `views.paths` loads from 2 places. Everything works great until I use something like `wire:poll`. Once I start using the JS I get 404s on the messages, as you did.

Again, I'll check out the middlewares we're running but I am logged in as an admin which should pass all gates.

**Comment by calebporzio** [comment]
Ok, I removed the "middleware mimicking" behavior in the latest release: v0.3.14

It now just uses "web" by default and allows you to configure this if you so choose.

This should remove a lot of these problems? If so, please close this issue. Thanks!

**Comment by jacobsmith** [comment]
I'll check on our application this afternoon. Thanks @calebporzio !

**Comment by billriess** [comment]
Hmm, I just updated to v0.3.14 and published the assets but I am still having the same issue. @calebporzio do you think this could be related to custom `livewire.view_path`?

`/livewire/message/crm.tabs.general` is throwing 404

**Comment by jacobsmith** [comment]
I took a look at our setup and realized that I've already manually mounted the livewire route because of some routing rules we have (route prefix) so I don't think I'm going to be able to help test this change. With that, though, I will close the issue because the issue was not with Livewire, but with our own app's routing and authorization rules.

**Comment by billriess** [comment]
I just wanted to add that my issue was due to cached routes... I feel dumb. :(
