### ISSUE TITLE
Add support to use LW in packages

### ISSUE THREAD

**Issue by bardh7** [livewire/livewire#306]
Hey @calebporzio,

Is there a possibility to use Liverwire in a package?

A simple example would be: `@livewire('packagename::counter')`
 
The component namespace would be smth like: `namespace Packagename\Http\Livewire;`

Would be cool if this could be configurable in `config/livewire.php` where in **class_namespace** and **view_path** you could add more than one namespace and more than one view path.

Thanks,
Bardhi

**Comment by calebporzio** [comment]
You can actually do this right now:

Inside the package's service provider: 

```php
public function boot()
{
    Livewire::component('packagename::counter', YourPackage/Counter::class);
}
```

Does that make sense?

**Comment by edgrosvenor** [comment]
@bardh7 I slapped this together to show you because it took me a little while to figure out last week. https://github.com/edgrosvenor/shareable-livewire

**Comment by calebporzio** [comment]
Nice touch with the namespaced `->loadViewsFrom()` in the service provider @edgrosvenor!

You can also use `View::file()` instead:
![image](https://user-images.githubusercontent.com/3670578/66006554-01938200-e47d-11e9-80f6-6b6297a25348.png)

**Comment by edgrosvenor** [comment]
I think I learned that trick from Marcel's course. I prefer it to View::file() because it's more natural for the guy who manages the sites that consume the packages I create. We're a two man shop and I do all the package work. So the more Laravel-like I keep things (loading views from the same place he does in the site), the less I hear from him on Slack. And nothing is more important than a quiet Slack channel.

**Comment by calebporzio** [comment]
Heh, true

**Comment by bardh7** [comment]
Hey guys, sorry for the late reply. Thanks for the tips and support. I didn’t have chance to test it, but this is what I was looking for. Thanks a ton.
Cheers

**Comment by edgrosvenor** [comment]
@bardh7 You're welcome. Hit me up if you run into any snags. I'm happy to help.

**Comment by yashiroiori** [comment]
Hi.
I use https://github.com/nWidart/laravel-modules to make modular app and I try to do add components into modulo
In the service provider add an component, render it's ok, but not work data binding, check in request are make to url 'livewire/message/{name}' but response 302 not found, how do to fix it??

**Comment by imard28** [comment]
@edgrosvenor how change the folder when generate files?

**Comment by shankhadevpadam** [comment]
> You can actually do this right now:
> 
> Inside the package's service provider:
> 
> ```
> public function boot()
> {
>     Livewire::component('packagename::counter', YourPackage/Counter::class);
> }
> ```
> 
> Does that make sense?

working like a charm.

**Comment by nuernbergerA** [comment]
You can find it also in the [docs](https://laravel-livewire.com/docs/package-dev)
