### ISSUE TITLE
How does persistence work?

### ISSUE THREAD

**Issue by jacobsmith** [livewire/livewire#307]
This is more of a general question / request for more documentation ( which I'd be happy to write once I understand it (: ).

So, I understand how to create livewire components, have them update dynamically, etc. ( I have a filterable / sortable table built with it and am loving the project so far!). My question, however, is how the data is persisted between requests.

As I understand it, this all goes over HTTP, which would be stateless. However, clearly we are holding state _somehow_ between requests. From what I can tell, it's even working with complex objects (i.e., those that couldn't just be serialized as JSON). I'm trying to get access to the full "state" of the component so I can return a full data-set in a streaming fashion. The approach I'm looking at would be to get the persisted state of the livewire Table component (which has a handle to a `$report` variable) and stream that response back over a typical Laravel Controller.

I see where anything marked `public` is serialized across, and that makes total sense. However, I also passed an instance of a `Report` object (which I hold a handle to with the `mount` function), and I still have access to that same instance, even between requests. _That_ is the magic I don't understand!

If someone can help explain how persistence works, I'd be super appreciative! Thanks 😄

**Comment by calebporzio** [comment]
Hey @jacobsmith,

I don't TOTALLY understand your question, but I can try to clarify.

You are correct in your understanding of public properties and how that state is passed back and forth.

The only piece of state that is persisted (and not stateless), are protected properties.

Protected properties are "dehydrated", but storing them in the app's cache, and getting them back out of the cache when the component is re-hydrated on the next request.

Does that make sense?

**Comment by jacobsmith** [comment]
I think so. So with a `protected` property in a Livewire component, the component will "dehydrate" that property by recording its class name, `public` properties, and `private` properties to the Cache. Then, on the next request, it will rehydrate by create a `new $class` and setting the `public` and `private` properties it stored from earlier.

Is that understanding correct?

Also, if it is, then only the first "level" of a protected property would be re-hydrated, correct?

```
class Library {
  protected $bookshelf;
}

class Bookshelf {
  protected $books;
}

class Book {
  protected $title;
}
```

```
  $library = new Library();
  $library->createBookshelf();
  $library->addBookToFirstBookshelf(new Book('1984'));
```

In this instance, if `$library` were a `protected` attribute on a Livewire component, it would not be able to recreate the Bookshelf because that is a complex object that wouldn't have been through the hydrate/rehydrate process. Is that understanding correct? (I'm not sure if this is even a realistic real-world scenario, I'm just trying to understand how the "flow" of information works.)

**Comment by calebporzio** [comment]
Sort of. Let me clarify.

When a component "dehydrates", it dehydrates the name, public property (and some other stuff) into the request it sends the the front-end. The front-end holds that state and sends it back for re-hydration on the next request. To further explain: if you don't set any protected properties, there will be NOTHING stored in the cache.

To your `$library` point, the library protected property will be preserved entirely in the cache upon dehydration and re-hydration. it will be restored exactly as it was stored (with the complex reference to books)

Does this make sense?

**Comment by jacobsmith** [comment]
@calebporzio Yes, thank you. I'm not used to working in a language where entire objects and dependencies can be stored in a cache between requests. I come from a Rails background and basically everything has to go through a `serialize -> cache -> next request -> deserialize previous data and instantiate new object (and dependencies)` process. I'm going to close this issue for now since I think it has helped me understand how things are working. Thanks for your responses!
