### ISSUE TITLE
Invalid payload. Middleware, name, checksum properties are sent as null values.

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#308]
**Describe the bug**

When rendering a component LiveWire puts elements on the root-div to be sent to the host in a later stadium. For example: wire:checksum, wire:middleware etc. etc.

The values of these data elements are sent back correctly when using livewire v0.3.4.
When upgrading to v0.3.10 these elements are sent back with `null` values.

```
actionQueue: [{type: "callMethod", payload: {method: "loadData", params: []}}]
checksum: null
children: null
data: null
gc: ["tYS3J4Dg2RWZp7cVun1n", "yGFe6ABTN9NgTvthqpKW", "DAT7Oa4sFHBNvI2GMiLu", "fC5h7V53iKRrKAVDSt8K",…]
id: "uefzk7nPTqGrW1cSrAlN"
middleware: null
name: null
```

If i look at the root div however, the data is present:
```
 <div wire:id="TY6Zi1XV6Szo9IDZkr2h" wire:data="{&quot;panelId&quot;:&quot;two&quot;,&quot;panelData&quot;:&quot;Hello two&quot;,&quot;loaded&quot;:false}" wire:name="dashboard-panel" wire:checksum="e40e7985aaba7e552683a5ff80f98bee0d4df53a3fe88809d1329a07c738f70b" wire:children="[]" wire:middleware="eyJpdiI6ImhQK1RGOVJnN1ZCeGlyTVU5NCtYWnc9PSIsInZhbHVlIjoiS1FQbGU1ZUJ2XC9GaTlHN251bHFSZ0V3SmxqQ2hPbDlQWWFMSFF2ZEtVOGpaa0NzY1kweWtOb0ZDOW91dWVYMHBCYjV3TFowclpCcEdxYmZhUkZLekVBPT0iLCJtYWMiOiIzYTMyNzI5ZTlhMTBjMTI1NDg4OWUxMWI3OGM4MDE0ZDkyMTE0OWExZjg4OTE5YmM4ZTZiZmM0OTNjZDhlM2I4In0=" wire:events="[]" class="col-sm-12 col-lg-6">
```

**To Reproduce**
Create a working livewire component with version 0.3.4 and upgrade to 0.3.10

Use Turbolinks. The issue cannot be reproduced with turbolinks disabled.

**Desktop (please complete the following information):**
- Chrome [latest]
- Windows
- Turbolinks

**Comment by ducopro** [comment]
It seems `window.livewire.restart()` has something to do with it...

**Comment by calebporzio** [comment]
Hey @ducopro, sorry - I think the turbolinks docs are stale now.

Here is the code that is working for me:

![image](https://user-images.githubusercontent.com/3670578/65987396-b749db00-e453-11e9-9637-390d23f2a71e.png)

Does that fix it for you? If so, I can update the docs.

**Comment by dave-alvarez** [comment]
Hi @calebporzio 

I'm having the same issue as @ducopro and interestingly, this is happening with or without turbolinks. My setup is exactly what you posted there.

**Comment by ducopro** [comment]
@calebporzio 

No this does not fix it. It is basically how my code is organized right now:
``` javascript
window.turbolinks = require("turbolinks");
window.turbolinks.start();

$(document).on('turbolinks:load', function () {

    // Load livewire resources again
    if (!window.livewire) {
        console.log('new livewire instance created');
        window.livewire = new Livewire()
        window.livewire.start()
    } else {
        console.log('Livewire instance restarted');
        window.livewire.restart()
    }

});
```

**Comment by calebporzio** [comment]
Try replacing `window.livewire.restart()` with `window.livewire.rescan()` and let me know if that fixed it.

**Comment by dave-alvarez** [comment]
fyi - Moving the composer package requirement to dev-master and swapping .restart() for .rescan() fixed the issue for me.

**Comment by ducopro** [comment]
Agree with @dave-alvarez 

Advancing to dev-master and replacing `.restart()` with `.rescan()` solved all problems.

**Comment by calebporzio** [comment]
Great, I updated the documentation.
