### ISSUE TITLE
Dynamic Repeating Components creates duplicated IDs & crashes

### ISSUE THREAD

**Issue by yotmv** [livewire/livewire#310]
**Describe the bug**
When repeating over a loop using a dynamic count for the number of repetitions, Livewire loses track at the first update and gives you only a single component.

**To Reproduce**
Two Basic Components: first is a text-input field, 2nd is a collection/repetition of inputs.

![textInput](https://user-images.githubusercontent.com/5964308/66008616-e1fc5980-e47c-11e9-9865-993d9502a582.jpg)

![DynamicForm](https://user-images.githubusercontent.com/5964308/66008589-c4c78b00-e47c-11e9-8316-a0e325b21c1d.jpg)

The view's are just as simple:

![view-input](https://user-images.githubusercontent.com/5964308/66008640-f04a7580-e47c-11e9-85f6-9ed707fb6e25.jpg)

![view-form](https://user-images.githubusercontent.com/5964308/66008638-ede81b80-e47c-11e9-8219-1903bc5da9b8.jpg)

Here is a picture showing the elements after pressing the button a few times.

![element-duplicated-ids](https://user-images.githubusercontent.com/5964308/66008739-4ae3d180-e47d-11e9-8a54-47f22625c7c5.jpg)

**Expected behavior**
If you hard-code the count, it runs the first time correctly.

![form-code-hardcode-count](https://user-images.githubusercontent.com/5964308/66008748-56cf9380-e47d-11e9-9e9a-613cf5b113e3.jpg)

![form-hardcode-count](https://user-images.githubusercontent.com/5964308/66008750-5a631a80-e47d-11e9-8b81-7a555ca79dd5.jpg)

![form-hardcode-elements-unique-ids](https://user-images.githubusercontent.com/5964308/66008753-5df6a180-e47d-11e9-81da-ffb39f2acfb5.jpg)

**Desktop (please complete the following information):**
 - Browser - Chrome

**Comment by ducopro** [comment]
See: https://laravel-livewire.com/docs/nesting-components/
and the section about keyed components.

**Comment by calebporzio** [comment]
Yes, thanks @ducopro - does that solve your problem? If not, re-open.
