### ISSUE TITLE
wire:offline not displaying when polling nested components

### ISSUE THREAD

**Issue by erikscheepers** [livewire/livewire#311]
**Describe the bug**
Displaying the offline message does not work when you are polling nested components

**To Reproduce**
Steps to reproduce the behavior (simplified, but working example):
```html
    @livewire('offline')
    @livewire('polling')
```
```php
class Polling extends Component
{
    public function mount()
    {
//
    }

    public function hydrate()
    {
//
    }

    public function render()
    {
        return view('livewire.polling');
    }
}
```
```html
<div wire:poll.1s>
    @for ($i=0; $i<10; $i++)
        <div>
            @livewire('counter', $i, key('alert_' . $i . '_' . microtime(true)))
        </div>
    @endfor
</div>
```
If you go offline the wire:offline component does not show. 
If you don't poll (but keep the nested components) everything is working as expected. Also when you do not nest another component the offline component is showing when expected.

**Expected behavior**
You expect the offline error message to show

**Desktop (please complete the following information):**
 - Chrome

**Comment by calebporzio** [comment]
Can you show the "@livewire('offline')" component? I'm a bit confused.

**Comment by erikscheepers** [comment]
Something like this:
```html
<div wire:offline>
    <div>{{ __(error.offline) }}</div>
</div>

**Comment by calebporzio** [comment]
The problem is that your "key()" in the "counter" component loop is too dynamic. Every time the component is polling, it is changing all the keys because of `microtime()`. Remove the microtime call, and everything will work properly.

**Comment by erikscheepers** [comment]
I used previous "workaround" to get the nested components updated. What is the best method to update nested components (and keep the wire:offline working)? Tried several things, but without success (for now).
```php
class MyAlerts extends Component
{
    public $alerts;

    protected $listeners = ['reloadAlerts' => 'reload'];

    public function reload()
    {
        $this->alerts = Alert::all()->toArray();
    }

    public function mount()
    {
        $this->alerts = Alert::all()->toArray();
    }

    public function hydrate()
    {
        $this->alerts = Alert::all()->toArray();
    }

    public function render()
    {
//        $this->alerts = Alert::all()->toArray();
        return view('livewire.my-alerts', ['alerts' => $this->alerts]);
    }
}
```
```html
<div class="row" wire:poll.1s>
{{-- <div class="row" wire:poll.1s.$refresh> --}}
{{-- <div class="row" wire:poll.1s.$emit('reloadAlerts')> --}}
    <div class="col-12">
        <div class="row" id="all_alerts_div">
            @foreach ($alerts as $alert)
                <div class="col-sm-4 col-md-3 col-lg-2">
                    @livewire('alert-status', $alert, key($alert['id']))
                </div>
            @endforeach
        </div>
    </div>
</div>
```
```php
class AlertStatus extends Component
{
    public $alert;

    public function mount($alert)
    {
        $this->alert = $alert;
    }

    public function render()
    {
        return view('livewire.alert-status');
    }

    public function goToAlarm()
    {
        if ($this->alert['alarm']) {
            $this->redirect(route('alarms.show', [$this->alarm['id']));
        }
    }
}
```
```html
<div>
    <div class="alert text-center" role="alert" wire:click="goToAlarm">
        <span style="display: block">{{ $alert['name'] }} - {{ $alert['address'] }}</span>
    </div>
</div>
```

**Comment by calebporzio** [comment]
I'm sorry, I'm confused, can you expound on the problem? And maybe provide a more isolated example? Thanks!

**Comment by erikscheepers** [comment]
Alerts are being updated by another application and their current status are being displayed using Livewire. I want to get them trom the database by one query and foreach them in the template. The hydrate retrieves the current alerts, but in the template the alerts seem te be cached because no updates are visible. Only dynamic keys show me the actual status of the alerts.

**Comment by erikscheepers** [comment]
Fixed this issue by removing the nesting. The `my-alerts` component now just blade-include's the previously nested component `alert-status`.
