### ISSUE TITLE
Document ability to have a listeners function on component instances

### ISSUE THREAD

**Issue by jacobsmith** [livewire/livewire#312]
**Is your feature request related to a problem? Please describe.**
I have multiple livewire components on the same page. It is a page with tabs, and each tabs shows a different interactive table for users to view historical data in their account. In an effort to keep the table component as stand-alone as possible, controls for the table are separate livewire components (some controls don't apply to certain tables, etc.).

The issue I ran in to was that all tables were responding to the change event, thus running many more queries and making responses more sluggish than they needed to be. I found that `listeners` can be declared as a function. With that, I've been able to connect each input with an `id` that the corresponding table can listen for.

```
class DateRangeSelector {
  mount($emitId) {
    $this->emitId = $emitId;
  }

  updatingDateRange($newVal) {
    ...update the value
    $this->emit($this->emitId . 'DateRangeChanged');
  }
}

class Table {
    mount($emitId) {
    $this->emitId = $emitId;
  }

listeners() {
  return [ $this->emitId . 'DateRangeChanged' => 'handleDateRangeChanged' ];
}
}
```

and then used like:

```
@livewire('date-range-selector', 'userReports')
@livewire('table', 'userReports')
```

**Describe the solution you'd like**
I'd like to know if this is an "approved" way of scoping things. If it is, I'd love for it to be documented (and would love to write it up!), but I wanted to make sure this was an intended feature and not something that was slated for removal any time soon.

**Describe alternatives you've considered**
Another way I thought about approaching this was to create a PR so that a component could return `null` or `false` from a function that was attached as a listener and that would stop the livewire cycle (presumably just returning a quick `204 Content Unchanged` response back to the client). With this approach, each component could decide for itself whether or not to respond to a given event. I would imagine that `emit` would still have to send some sort of metadata along with the request for a component to differentiate if it should respond or not.

```
class DateRangeSelector {
  mount($emitId) {
    $this->emitId = $emitId;
  }

  updatingDateRange($newVal) {
    ...update the value
    $this->emit('dateRangeChanged', $this->emitId);
  }
}

class Table {
  protected $listeners = [ 'dateRangeChanged' => 'handleDateRangeChanged' ];

    mount($emitId) {
      $this->emitId = $emitId;
    }

  public function handleDateRangeChanged($emitId) {
    if ($emitId !== $this->emitId) {
      return null; // halt the process here, no need to re-render this component instance
    }
  }
}
```

**Comment by calebporzio** [comment]
This is fine for now. There is an `->emitUp()` method available right now to only emit to parent elements. There are plans for `->emitSelf()` as well.
