### ISSUE TITLE
Errorbag removed after each field updated on a for, 

### ISSUE THREAD

**Issue by roni-estein** [livewire/livewire#319]
When using a livewire component to represent a form, after a form submission with validation errors, everything works as expected, however once you trigger any update, by changing any of the invalidated fields, the errorbag is removed, even though the form hasn't been re-submitted.

**To Reproduce**
1. Have a component with two elements. In my case I'm not even using a form though I would if there was any reason too. 

2. Add a submit method with validation.
3. after receiving the errors, alter one field. All the errors will disappear.

**Expected behavior**
I'd expect only the component data to change, and not update request, unless the an action was triggered by some intended submission. If I want css to change or resubmit the data automatically, it should be triggered.

**Screenshots**

<img width="806" alt="Screen Shot 2019-10-06 at 1 50 45 PM" src="https://user-images.githubusercontent.com/8517475/66274090-8d702a00-e840-11e9-9d9e-d2b867c741e2.png">

Changing any element, will remove errorbag

<img width="735" alt="Screen Shot 2019-10-06 at 1 50 57 PM" src="https://user-images.githubusercontent.com/8517475/66274114-cf00d500-e840-11e9-9b26-e5339158a18c.png">

**Desktop (please complete the following information):**
MacOS 10.14.6
Brave brower, like chrome

**Comment by roni-estein** [comment]
This is a lame fix, but I needed to get this project dealt with this weekend, so my workaround until there is a better solution is to add a `protected $hasBeenSubmitted = false;``

In my submit function I added
`$this->hasBeenSubmitted = true``

Then I added an updated function that checks it.

```
public function updated()
    {
        if ($this->hasBeenSubmitted) {
            $this->submit();
        }
    }
```

That triggers an update which gives me bag an updated error bag.

**Comment by wsamoht** [comment]
Same issue here.

I wonder if the error bag should be added to the response so they can be hydrated back on future updates. @calebporzio thoughts on this? Is there a better way to handle this as it stands right now?

**Comment by calebporzio** [comment]
Yeah, this is one of those things we definitely need to get straight (high priority).

We need to nail down exactly how Livewire should behave first.

@roni-estein & @wsamoht, how do you think Livewire should behave by default?

Do we agree that Livewire should preserve the error bag between property updates, but clear it after calling methods?

Would this be intuitive? Or confusing. You could still have real-time validation by validating inside property update hooks.

Also, YES, I would like to store the error bag in the request to persist it (I think).

**Comment by wsamoht** [comment]
Thanks @calebporzio!

Thinking this through, I see two ways of using Livewire to persist data back to the application/database. The first is property by property every time Livewire makes the update (no save button). The second is with a save or submit button which we are talking about here.

With the first option (persist property by property), you would need to use real-time validation so it doesn't seem to be an issue in this case. @roni-estein any reason not to use real-time validation or is it just preference? I mean, why not always run validation in the `updated` method disregarding whether or not there was already a "form submission"?

With the second option (persist using a save/submit), I would want the error messages to persist across property updates by default. Yes, they should clear when calling a method. You would need to explicitly call validation again in the method being called.

I think it is intuitive as that is how Laravel naturally works. Also, if you were doing JS validation, errors typically stay as you move from field to field unless the error is corrected.

A couple items to think about:
- How to handle errors created from calling a method and then separate validation when a property is updated. Should the error bags be merged or should subsequent errors overwrite anything previously? I would say they should overwrite otherwise it could get messy.
- There should be an easy way (a method on the component or something) to clear the error bag
- Should there be an option on the component to say persist or don't persist the error bag?

**Comment by roni-estein** [comment]
@calebporzio @wsamoht ,

Honestly, I was just playing around with livewire and this little useful project came up which is simply a set of dynamic forms, and some reporting options. So it was more to teach myself something while contributing something useful to a local community board at the same time. 

This project has no need for livewire. Laravel and Vue or just vanilla JS would suffice.

That being said, I really liked the feel of livewire for a dynamic form. I could see it being my goto solution. When I make dynamic (or interactive form in JS), depending on the target audience I often omit the "form" tag as several subforms often get pulled in, for example, adding an element to a large select without actually leaving the form via axios. Or some input modifies the upcoming questions or prefills data with simple element listeners. If I don't have those use cases, I would simply make a less interactive form through a regular laravel controller, and use the form tag to submit static datasets.

In this case I really enjoyed the `updatedFoo` idea which replaces my listeners.

Now I think the default behavior of livewire is fine, I can see it being confusing that changing each field has the potential to pass validation and submit the form. I write a block for that that I should have posted, where I don't block the validation errors from disappearing, but I DO block the form actually submitting unless the submit button was pressed. The reason for this is use case:

1. You fill in a form and submit it.
2. The data is returned with validation errors.
3. You update the validation errors, but realize you left out data on an optional field.

Consequence, your form in re-submitted and passes validation when you go to fill in that optional field.

I think the problem comes from the fact that I want the forms to not need any explanation and feel like they work exactly as expected. And the nice helper features just flow out of things you naturally feel like you should do.

Sorry that was a longwinded lead up. I think the solution might simply being using something like a renderless vue component idea to deal with what I might want at the time for a form.

I haven't used composition or arrays in livewire yet, but I might consider refactoring the form data props and submit behaviors as some sort of callback function so I can have make writing new forms a little easier by extracting re-usable behaviours.

This may be 100% not good idea for livewire, I've only spent a couple of days on it in total. But lots of the code I write in apps is spent on making forms as intuitive as possible and of course the actions each form takes. So I wouldn't want to re-write that logic in every component. I'll play around with it next weekend but I'm eager to see what mind blowing creative solutions you come up with over time.

Cheers.

**Comment by roni-estein** [comment]
Just a clarification, when I spoke about a renderless component I was thinking about implementing that concept in livewire. Not pushing vue dependancy on this.

**Comment by stefanbauer** [comment]
> Do we agree that Livewire should preserve the error bag between property updates, but clear it after calling methods?

I'd go exactly that way, with @wsamoht  suggestions:

- errors should overwrite always
- a method on the base class that allows clearing the bag
- an optional option to choose if the errors should be persisted

**Comment by calebporzio** [comment]
Ok, @stefanbauer, @roni-estein, and @wsamoht. I think I solved Validation in Livewire:

There are TWO validation scenerios I wanted to cover.

THE FIRST: normal, submit button, validation
```php
public function submit()
{
    $this->validate(['foo' => 'required|min:6', 'bar' => 'required|min:6']);
}
```

* A user fills in a input element (no error is shown)
* The user clicks the submit button (the appropriate validation error is shown)
* A user fixes the error in the input button (same error is still shown (despite Livewire data updates))
* The user clicks the submit button again
* The error dissapears

THE SECOND: real-time validation of individual fields
```php
public function updated($field)
{
    $this->validateOnly($field, ['foo' => 'min:6', 'bar' => 'min:6']);
}
```

* No validation errors are shown
* A user types in a "foo" field (`wire:model`ed of course),
* The "min:6" validation message shows until the min:6 is met
* The user can type in a different field (bar), and the "foo" validation error is still showing
* The user types past 6 characters for the "foo" field, and the error dissapears
* There can optionally be a "submit" button that a user can click and run a different set of validation on the form (the validation messages from that click will overwrite the "updated" hook ones).

Hopefully all this makes sense.

The validation messages are persisted now, AND there is a new method `$this->validateOnly` that can be used to selectively validate fields and not wipe out other field's validation messages from the error bag.

It's a lot to take in, but I think it's actually intuitive if you new to the problem and saw a simple demo.

Thoughts?

Also, if you could all putt down `dev-master` (the master branch) to test out this functionality and give me the thumbs up before I tag a release.

Thanks!

**Comment by stefanbauer** [comment]
This is something I really like so far and it sounds promising. I will give it a shot tomorrow. I think I can tell more as soon as I tried it out :) Thanks for your effort!

**Comment by stefanbauer** [comment]
I tried it out and here is my honest feedback:

First of all, I really like it and it works great. Two things I noticed though:

1. When using real-time validation like this

```php
public function updated($field)
{
    $this->validateOnly($field, ['foo' => 'min:6', 'bar' => 'min:6']);
}
```

and if you use required there is a strange behavior as of a UX perspective.

**How I would expect that it's working:**

- There is an empty form with 2 fields
- Focus the first field
- Tab to the next field
- Required validation should fire and error should be displayed

**How it is working at the moment:**

- There is an empty form with 2 fields
- Focus the first field
- Tab to the next field
- No error is shown
- Type something into it
- Leave the field
- Go back to the field and clear the field
- Leave the field
- Error is shown

Means: As soon as you have ever entered something and clean that field, then the required validation fails. If you never entered something, it doesn't fail.

2. Improvement

When you are using both, real-time validation and submit validation, you need the (same) rules two times. You could create something like a `rules()` method and use that on the two methods. What is if we create something like this:

- Check if there is an existing `rules()` method
- Check if there is an `updated()` method
- If there is a `rules()` method and no `updated()` method, we could automatically use the `rules()` method and fire off an updated method that does automatic validation against the rules defined in the `rules()` method.

With that, you have automatic real-time validation as soon as there exists a `rules()` method, without doing anything. `rules()` can be named whatever it should be. Could also something be like `validation()`.

Thoughts?

**Comment by wsamoht** [comment]
@calebporzio I like this solution! I haven't played with it too much but here are a few notes so far.

`validateOnly` doesn't work when validating an array because where you have `Arr::only($rules, $field)` field `items.0.name` doesn't match `items.*.name`.

With what @stefanbauer about real-time validation with required fields (#1), I believe this is because nothing changed so Livewire isn't doing anything (there is no request made to the server). Not sure how I feel about this. To fix it, I'd think Livewire would always have to do a request when a form field loses focus even if it hasn't changed increasing the number of requests. Or maybe only make the request if the value is empty.

With @stefanbauer improvement (#2), I don't think this is necessary. Instead of duplicating the rules, the developer can just create a method `getRules` which gets called in both places. I also don't really like the automatic real-time validation. What if I don't want real-time validation? I feel like if you want it, you explicitly set it up to do it with the `updated` method.

Example:
```php
public function updated($field)
{
    $this->validateOnly($field, $this->getRules());
}

public function submit()
{
    $this->validate($this->getRules());
}

private function getRules()
{
    return [
        'items.*.name' => 'required|string|max:50',
        'items.*.description' => 'required|string|max:100',
        'items.*.amount' => 'required|numeric|min:0',
    ];
}
```

**Comment by roni-estein** [comment]
I think this might be more of a docs thing than anything else at the moment. I'm not saying that revisiting this wouldn't be a good idea at some point, and perhaps taking advantage if using some wire:form or other clever implementation. But right now, anything is more or less achievable if you code around the system. So for example, if I want this to act like laravel, I can ignore calls unless the form submit method has been called.

If I want this to be vue-ish, I can get validation running on each field on each update. I think people jsut need some patterns to follow in the docs.

**Comment by TheOWler** [comment]
this issue is still present in livewire3, any possible fixes ?
i have it working fine on livewire 2 on a seprate project and on my current one this issue is still valid
