### ISSUE TITLE
Run a JavaScript from method

### ISSUE THREAD

**Issue by slava-vishnyakov** [livewire/livewire#320]
**Is your feature request related to a problem? Please describe.**
Basically, let's say I want to `alert('Incremented')` when user clicks "+" in Counter component.

**Describe alternatives you've considered**
I assumed having something like `@if($incremented) <script>alert('Incremented'); </script> @endif` in Blade template would work (assuming I set $incremented myself), but it is run only once, when component is first rendered. The only workaround for now I've found is `@if($incremented) <img src="bad://" onerror="alert(1)" id="Str::random(10)"> @endif`, which is really clumsy. Random is required to avoid DOM optimization (doesn't work otherwise).

**Describe the solution you'd like**
Probably the easiest solution would be something like:
```
public function increment() {
  $this->count++;
  $this->runJs('alert("1");');
}
```

EDIT: That *might* also help with some cases in #180 (modals, by using something like SweetAlert popup)

**Comment by davidpiesse** [comment]
Hi @slava-vishnyakov  Would you not want to put your JS logic as simple JS in the template?
This could be done with a script tag at the bottom of your blade file, with a function that is called on the onClick event.
It would seen fruitless to have JS sending back a request to PHP, for the PHP to then return JS.

Is there a use case why you would want to do that?

**Comment by slava-vishnyakov** [comment]
@davidpiesse Yes, the logic surely goes into Blade, no arguing with that.
The problem is that sometimes you want to call a specific JS function as a result of server-side call.

For example, let's say I want to post a comment to a site and it contains profanity. The site has a server-side logic to check if profanity is present. If it is present - I want to show a SweetAlert error popup, something like "You are not allowed to post that".

blade
```
<script src="sweetalert.js"></script>
```

Component:
```
public function addComment($comment) {
  if(Str::contains($comment, 'bad word')) {
    // call js SweetAlert.fire('You are not allowed to post that');
    return;
  }
  // ... otherwise just add and render as usual
}
```

Currently it's either not possible or I haven't found a way.

**Comment by mksav** [comment]
@slava-vishnyakov You can emit an event on the PHP side `$this->emit('sweet-alert', "You can't post that!");` and then listen for it in your javascript:
`<script>
window.livewire.on('sweet-alert', message => {
    alert(message);
    // or whatever alerting library you'd like to use
})
</script>`

**Comment by calebporzio** [comment]
What @mksav said. I hope to have a bit of a better way to do this soon.

**Comment by slava-vishnyakov** [comment]
@mksav @calebporzio Thank you! 👍 

I think that should be added to https://laravel-livewire.com/docs/inline-scripts/ , something like:

"Please note that your scripts will be run only once upon first render of the component. If you need to run a JavaScript function later - emit the event from the component and listen to for in JavaScript as described here(https://laravel-livewire.com/docs/events/)"

Because that's where I was searching for the answer of why my scripts don't run the second time.

**Comment by calebporzio** [comment]
Good call @slava-vishnyakov - is that something you'd be willing to PR to the docs? github.com/livewire/livewire-docs

**Comment by slava-vishnyakov** [comment]
@calebporzio Sure! Thanks!

**Comment by calebporzio** [comment]
@slava-vishnyakov - I went ahead and added a new feature to Livewire that should make this a little easier:

```
@this.on('some-event', callback())
```

You can read more about it here: https://laravel-livewire.com/docs/inline-scripts/ (towards the bottom of the page)

Would still love that PR though!

**Comment by slava-vishnyakov** [comment]
@calebporzio 
Awesome! Though, the PR is already there :) https://github.com/livewire/docs/pull/49

**Comment by yashiroiori** [comment]
> @slava-vishnyakov - I went ahead and added a new feature to Livewire that should make this a little easier:
> 
> ```
> @this.on('some-event', callback())
> ```
> 
> You can read more about it here: https://laravel-livewire.com/docs/inline-scripts/ (towards the bottom of the page)
> 
> Would still love that PR though!

Hi, good job.
I'm try to make an sweetalert but not work

This is the actions buttons into a table
![image](https://user-images.githubusercontent.com/17031855/67637958-7653b380-f8a5-11e9-9984-eb5dc54bb17e.png)

This is the inline-script
![image](https://user-images.githubusercontent.com/17031855/67637973-8ff4fb00-f8a5-11e9-9d1e-f1edbbdda78a.png)

But into documentacion say:
![image](https://user-images.githubusercontent.com/17031855/67637978-a56a2500-f8a5-11e9-9c01-696573cb7bde.png)

What's is wrong??
