### ISSUE TITLE
Option to store protected properties in browser

### ISSUE THREAD

**Issue by slava-vishnyakov** [livewire/livewire#321]
**Is your feature request related to a problem? Please describe.**
Currently the protected properties are stored in cache. If you have a reasonably popular site - your cache will explode with dozens of new cache items per each page visited by a robot or a human.

The bots can often be like 99% of visits to the site and they won't click any button. Therefore any state that I keep for them is useless. Even with users - most of them won't click anything, so again - most of the state I keep for them is useless waste of Redis memory.

**Describe the solution you'd like**
I'd like to be able to store everything client-side. Maybe something like

```
class MyComponent ... {
  use EncryptedClientStorage;
```

Basically, LiveWire can send something like `encrypt($protected)` to the browser and receive it back whenever a request goes back to LiveWire (just like it now sends `data`, `dirty`, it might send also `protected`, which will be decrypted server-side). 

Even though this is a trade-off (fatter network packets), but often having fatter packets is much more useful than having hundreds of gigabytes of RAM.

You can have hundreds of thousands of robots and humans on site and still not require any additional RAM. 

I don't expect majority (99.99% or something like that) of LiveWire widgets to receive any interactions in future, but still I have to keep data for each of them.

(P.S. That's actually how my current solution works, which is pretty similar to LiveWire. I'd like to use LiveWire on my current site, but my napkin-based calculations suggest that I would need hundreds of gigabytes of RAM to use LiveWire instead of my solution, which just sends all "protected" data encrypted to the user, for user to send it later back)

**Comment by calebporzio** [comment]
Hey @slava-vishnyakov, yes, that makes sense.

I think most Livewire usage is in a non-public, app context. Therefore, I believe caching is a good default. Also, when Livewire is used on public facing stuff prone to bot usage, I imagine people using protected properties less, but I know I could be wrong AND there are exceptions.

Anyhow, I agree, it would be nice to offer the option to use the AJAX  request to transported encrypted protected properties.

I suppose the only question is what is the best way to configure that option.

If it is per component, we would need a trait or something like you proposed. It could also be site-wide and configured in the config file.

Anyhow, I like it. Would you be willing to PR this feature?

**Comment by slava-vishnyakov** [comment]
Maybe we can have a config option, something like 
```
'protected_storage' => 'cache' / 'browser'
``` 

and also a base method 

```
protected function getProtectedStorage() { 
  return config('livewire.storage'); 
}
``` 

That way you could override it in your component like this:

```
protected function getProtectedStorage() { 
  return 'browser'; 
}
``` 

> Would you be willing to PR this feature?

@calebporzio I'll try.

**Comment by slava-vishnyakov** [comment]
Opened a Draft PR https://github.com/livewire/livewire/pull/323

**Comment by calebporzio** [comment]
Livewire no longer supports protected properties. Closing.
