### ISSUE TITLE
Mention the use of @livewire explicitly in the docs

### ISSUE THREAD

**Issue by kevindierkx** [livewire/livewire#324]
This is not a burning issue in any way, rather a nice improvement in my opinion. After reading through the docs starting with the "Installation" chapter, and skipping the "Quickstart", I was a bit confused how I actually render a Livewire component.

Afterwards I found out it was actually mentioned in the "Quickstart", I would propose to explicitly mention this in the 'elaborate' docs and maybe even combine it with the "The `mount()` method" chapter.

**Comment by roni-estein** [comment]
Why not make a PR to the docs?

**Comment by kevindierkx** [comment]
> Why not make a PR to the docs?

Sure thing, when I get the time will certainly look into it. ;)

**Comment by intellow** [comment]
This is in the Installation section now. This should be closed. https://laravel-livewire.com/docs/installation/

**Comment by kevindierkx** [comment]
> This is in the Installation section now. This should be closed. https://laravel-livewire.com/docs/installation/

@intellow This issue is about the use of `@livewire('component.name')` I don't see that on the installation page yet... 🤔

**Comment by intellow** [comment]
I see what you mean. Sorry I thought you were referring to @livewireAssets. To me I think it makes more sense in the Make Component page. I can submit a PR to the docs.

**Comment by kevindierkx** [comment]
@intellow No problem! I didn't have time for it yet, so be my guest. 😄

**Comment by intellow** [comment]
https://github.com/livewire/docs/pull/75

**Comment by intellow** [comment]
This was merged in the docs repo. This issue can be closed.
