### ISSUE TITLE
Route::livewire dependant on the order

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#327]
**Describe the bug**
I have below normal resource controller in Laravel registered in my `web.php` file:

```php
Route::resource('streams/{stream}/fields', 'Stream\FieldsController')->except(['create']);
```

Now, the `create` method is a Livewire component, so the above resource controller does not include this. I have a separate route for that:

```php
Route::livewire('streams/{stream}/fields/create', 'streams.fields.create')->layout('layouts.livewire.app')->name('fields.create');
```

Now, if I register the `Route::livewire` _after_ the `Route::resource`, I am encoutering a 404 Not Found page:

```php
Route::resource('streams/{stream}/fields', 'Stream\FieldsController')->except(['create']);
Route::livewire('streams/{stream}/fields/create', 'streams.fields.create')->layout('layouts.livewire.app')->name('fields.create');
```

However, if I register the `Route::livewire` _before_ the resource, like this:

```php
Route::livewire('streams/{stream}/fields/create', 'streams.fields.create')->layout('layouts.livewire.app')->name('fields.create');
Route::resource('streams/{stream}/fields', 'Stream\FieldsController')->except(['create']);
```

Then everything works and I can access the route.

**Comment by cbaconnier** [comment]
This is normal and not a livewire issue

```php
Route::resource('streams/{stream}/fields', 'Stream\FieldsController')->except(['create']);
```
The resource above will generate the routes below

```php
Route::get('streams/{streams}/fields', 'Stream\FieldsController@index')
Route::get('streams/{streams}/fields/{field}', 'Stream\FieldsController@show')
Route::patch('streams/{streams}/fields/{field}', 'Stream\FieldsController@update')
Route::delete('streams/{streams}/fields/{field}', 'Stream\FieldsController@destroy')
Route::store('streams/{streams}/fields', 'Stream\FieldsController@store')
```
Notice `streams/{streams}/fields/{field}` 

So when you request with the URI `/streams/1/fields/create` `create` will be interpreted as valid parameter and will hit your resource `Stream\FieldsController@show`

**Comment by calebporzio** [comment]
Sneaky, good call @cbaconnier - thanks a ton for looking into this!
