### ISSUE TITLE
Frontend Preset

### ISSUE THREAD

**Issue by davidpiesse** [livewire/livewire#331]
Create a frontend Preset for Laravel using Livewire.
Super simple as we have no extra dependencies outside Livewire.

- Create repo
- Create stubs for views (welcome, login, forgot, index)
- Create Preset installer

Main questions are
- What CSS framework (my vote is Tailwind via CDN)
- Logout via JS or Lw
- How many components do we create?

**Comment by roni-estein** [comment]
I’m not against this, but this is pretty site specific. Not just design wise but even in terms of how the forms would interact.

That being said a baseline like art:make auth is not a bad idea. If you like tailwind as the preset, which i use myself peerhaps using the form-presets from Adam Wathan would be a good starting point.

If any feedback comes from Caleb on this I’d be happy to submit a starter or and command that will at least get you part of the way there.

**Comment by calebporzio** [comment]
I'm torn on this.

I definitely like the idea of someone being able to type `php artisan preset livewire` and get basic scaffolding like you do with Vue.

As far as building and maintaining stubs for auth stuff... I'm not sure about that. Probably not something I want to officially support ATM. Or maybe I could put it under this namespace after I  see it and it looks good? Idk, it's a reasonable feature @davidpiesse, just not sure about it.

**Comment by davidpiesse** [comment]
Like pineapple pizza... 🍕

Fair enough. I will dig into the auth part. Ideally we are using stock
Laravel it's just the views we override.

**Comment by kdion4891** [comment]
I’m working on this. I’ll put it in my own repo and I can make a PR if Caleb likes it enough.

**Comment by calebporzio** [comment]
Frontend scaffolding is definitely in the future (stay tuned). Closing this.
