### ISSUE TITLE
Double-quotes not supported for $set

### ISSUE THREAD

**Issue by assertchris** [livewire/livewire#333]
`$set('step', 'repositories')` works as documented, while `$set("step", "repositories")` throws a `Livewire\Exceptions\MissingComponentMethodReferencedByAction` exception.

**Expected behavior**
I expect double quotes to work in the same way as single quotes, since they are interchangeable in PHP and JS.

**Comment by lancepioch** [comment]
@assertchris I just tested in the latest versions and this is working. The exception no longer exists too.

What I used:

```<button wire:click='$set("message", "Hello")'>Say Hi</button>```
