### ISSUE TITLE
Add self modifier for the click event

### ISSUE THREAD

**Issue by johnnyfreeman** [livewire/livewire#336]
**Is your feature request related to a problem? Please describe.**
Not a _problem_ per se. But here's use-case. When building a modal window, it's pretty common to dismiss when clicking the modal backdrop.

**Describe the solution you'd like**
I'd like to only trigger the click handler if `event.target` is the element itself, not one of it's children. Something like `wire:click.self="doSomething"`.

**Describe alternatives you've considered**
Writing a custom click handler.

**Comment by fakingfantastic** [comment]
@calebporzio ill take a crack at this if it's something you want to offer?

**Comment by fakingfantastic** [comment]
Let me know how that pull request treats you

**Comment by lancepioch** [comment]
@johnnyfreeman Does the latest version work with what you were expecting?

**Comment by johnnyfreeman** [comment]
@lancepioch Yes it does.

**Comment by lancepioch** [comment]
Awesome!
