### ISSUE TITLE
PHP 8 union type in mount method leads to "Call to undefined method ReflectionUnionType::isBuiltin()"

### ISSUE THREAD

**Issue by smares** [livewire/livewire#3375]
### Discussed in https://github.com/livewire/livewire/discussions/3345

<div type='discussions-op-text'>

<sup>Originally posted by **smares** July 16, 2021</sup>
The following code:

```
public function mount(array|object|null $categories = null)
{
    ...
}
```

Produces the following error:

> Livewire\ImplicitlyBoundMethod::getParameterClassName
> vendor/livewire/livewire/src/ImplicitlyBoundMethod.php:107
> **Call to undefined method ReflectionUnionType::isBuiltin()**

Running Livewire 2.5.5 with Laravel 8.5.22 / Framework 8.50.0.</div>

**Comment by fabio-ivona** [comment]
The same error occours for function with union type parameters, i.e:

```php
public function test_method(float|string $param){
    //...
}
```

I think a simple type check in order to prune `ReflectionUnionTypes` would solve this issue:

```
// ImplicitlyBoundMethod.php

public static function getParameterClassName($parameter)
    {
        $type = $parameter->getType();

        if($type === null){
            return null;
        }
        
        if(! $type instanceof \ReflectionNamedType){
            return null;
        }
        
        if($type->isBuiltin()){
            return null;
        }
       
        return $type->getName();
    }
```


another solution would be iterating over union types to search a valid class name:

```
// ImplicitlyBoundMethod.php

public static function getParameterClassName($parameter)
    {
        $type = $parameter->getType();

        if($type === null){
            return null;
        }

        if($type instanceof \ReflectionUnionType){
            foreach ($type->getTypes() as $union_type){
                if(!$type->isBuiltin()){
                    return $type->getName();
                }
                return null;
            }
        }else{
            return (! $type->isBuiltin()) ? $type->getName() : null;
        }
    }
```

@calebporzio what do you think? Can I open a PR to fix this?
