### ISSUE TITLE
Default asset_url to the app.asset_url ?

### ISSUE THREAD

**Issue by nie7321** [livewire/livewire#338]
**Is your feature request related to a problem? Please describe.**
I'm deploying on Vapor, which injects the `ASSET_URL` env var with my CloudFront domain. I have to explicitly wire this in a fresh Livewire install.

**Describe the solution you'd like**
The `app.assets_url` is already stock Laravel feature for any time you want to serve assets from a CDN.

It would make sense to me that `livewire.assets_url` would default to `app.assets_url`. In cases where it's null (e.g. most cases), Livewire gets a null and makes a relative path. 

**Describe alternatives you've considered**
Setting the livewire config to use my assets path, per the docs!

**Additional context**
Assuming that The Council of Livewire thinks this is a good idea, I can make the smol PR to change this 💯

**Comment by lancepioch** [comment]
Related to #385

**Comment by lancepioch** [comment]
#385 was merged, this should resolve any basic issues with running this on Laravel Vapor

@nie7321
