### ISSUE TITLE
Chrome Extension LanguageTool problem

### ISSUE THREAD

**Issue by dylanmichaelryan** [livewire/livewire#339]
**Describe the bug**
Hello,
if the extension languagetool is installed, textareas with wire:model are kinda broken. If you type something in the input field, the text will get removed after a few characters.

**To Reproduce**
1. Create textarea with wire:model
2. Install LanguageTool Chrome Extension
3. Try to type something in input or textarea

**Expected behavior**
The text should stay in the textarea and shouldn't be removed

**Screenshots**
https://streamable.com/bhv7u

**Comment by adrianschubek** [comment]
This doesn't seem to be related to Livewire.

**Comment by lancepioch** [comment]
Is this actually a bug with Livewire or with the Chrome extension?

If the extension is modifying data or state that Livewire needs, then I don't think the issue can be resolved on Livewire's end.

**Comment by cloudstudio** [comment]
Hello @lancepioch @calebporzio   I have the same problem with Grammarly (chrome extension) and only with Textarea, something weird, I try to debug, but I don't find anything relevant, really really weird, let me know if I can try something.

Thanks!

**Comment by lancepioch** [comment]
@cloudstudio @dylanmichaelryan If you try the same thing with incognito (no extensions), does it work again?

**Comment by madurapa** [comment]
@lancepioch this is still occurring with file upload if the form has textarea, working fine when the extension is disabled
