### ISSUE TITLE
RouteMiddleware on Post/Action

### ISSUE THREAD

**Issue by ServerJunge** [livewire/livewire#340]
Hi,

i love Liveware, but i have some routeMiddleware in my app.

In a livewire get request the routeMiddlewares are used, but how can I use a routeMiddleware on a liveware post/action? It only uses the default web middleware, but I  can not add my middleware to the web group because i only need it on some parts of the app.

Any ideas?

Thanks!

**Comment by wsamoht** [comment]
What is your middleware doing? If it is for authorization, your best bet will be using a Laravel Policy and then the `AuthorizesRequests` trait in the Livewire component.

https://laravel-livewire.com/docs/authorization/

**Comment by calebporzio** [comment]
Needs more info. Closing.
