### ISSUE TITLE
Not updating unless I manually set the component to poll

### ISSUE THREAD

**Issue by BrekiTomasson** [livewire/livewire#342]
**Describe the bug**
This is probably a conflict with something else in my system, but I can't for the life of me imagine what it could be. I installed Livewire as per usual and set up the counter example from the documentation, but it just doesn't work as advertised. I can see that things are being updated in the background, because if I set the component to poll every so often, the value _does_ change, but it doesn't happen automatically.

Are you aware of any conflicts with other Javascript libraries or similar? Do I need to inject the Livewire Javascript file into my Webpack workflow?

**Comment by jacobsmith** [comment]
Are you getting any JS error messages in your console?

**Comment by dave-alvarez** [comment]
I was having the same issue. The javascript portion of livewire is not initiating properly unless something like poll is used.

Obviously, I don't want to poll if I don't have to and setting a long duration for the poll function only fires for the first time once that long poll time has been reached. As a temporary fix, I am using a dummy function in the livewire php component and then calling that from the livewire blade file using the init directive which kickstarts everything:

`public function dummyFunction() {}`

`<div wire:init="dummyFunction">`

**Comment by BrekiTomasson** [comment]
Yup, @dave-alvarez - that did it! Thanks!

**Comment by lancepioch** [comment]
@BrekiTomasson Are you able to check if this is still the case with the latest release of Livewire? If it is, can you share the repo with me, maybe I can help drill down to the issue.
