### ISSUE TITLE
Error after canceling page reload

### ISSUE THREAD

**Issue by erikscheepers** [livewire/livewire#343]
**Describe the bug**
My issue is maybe a bit far fetched, but maybe the solution is not.
I use the `beforeunload`-functionality to give a warning when a user wants to reload (or close) the browser tab. If you want to stay on the page, you press `Cancel`. Then the polling stops and I get this error message:
>Uncaught (in promise) TypeError: Cannot read property 'receiveMessage' of undefined

The error originates from line:
https://github.com/livewire/livewire/blob/3d3e74312bd39097f99c7072bc641af74bd24be0/dist/livewire.js#L3054

**To Reproduce**
````html 
// layout.blade.php
@livewire('polling')
<script>
    $(window).on('beforeunload', function () {
        if (1===1) {
            return 'Your own message goes here...';
        }
    });
</script>
````
````php
// Polling.php
class Polling extends Component
{
    protected $thing = 0;

    public function mount()
    {
        $this->thing++;
    }

    public function hydrate()
    {
        $this->thing++;
    }

    public function render()
    {
        return view('livewire.polling', ['thing'=> $this->thing]);
    }
}
````
````html
// polling.blade.php
<div wire:poll.1s>
    {{ $thing }}
</div>
````

**Expected behavior**
I would expect the polling continues after you cancel moving away from the page. 

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by ryatkins** [comment]
I also have this error and it is happening when I'm emitting on an input field when it loses focus.  The error happens when I redirect to a new page while losing focus.

`onfocusout="window.livewire.emit('lostFocus')"`

**Comment by calebporzio** [comment]
Will be fixed in the next release. Thanks!
