### ISSUE TITLE
Adding rows generated JS error: 'getAttributeNames' of null

### ISSUE THREAD

**Issue by mbardelmeijer** [livewire/livewire#344]
**Describe the bug**
When implementing a simple livewire component, and adding new rows to an array, the 'getAttributesNames' of null error is triggered. See example below.

**To Reproduce**
1. Take the following component:

`app/Http/Livewire/Lines.php`   
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Lines extends Component
{
    public $name;
    public $rows = [];

    public function addRow()
    {
        $this->rows[] = [];
    }

    public function render()
    {
        return view('livewire.lines');
    }
}
```

`resources/views/livewire/lines.blade.php`   
```
<div>
    @foreach ($rows as $row)
        <div>{{ $loop->index }}</div>
    @endforeach
    <div>
        <input type="text" wire:model="name">

        <button href="" wire:click="addRow">add</button>
    </div>
</div>
```
2. Click on "add"
3. See a new row showing up
4. Click on "add" again
5. The Javascript error is triggered.

**Expected behavior**
Instead of the Javascript error, i expect a new row to be created.

**Additional context**
The issue goes away when wire:model connection of the input is removed.

I'm new to the whole Livewire experience so perhaps i'm implementing it wrong :)

Using `livewire/livewire` `0.3.17` on a Laravel 6.0 project.

The issue https://github.com/livewire/livewire/issues/345 is separate; we've tried this first in Twig and got this error, then checked with a blade implementation but it's the same. Doesn't seem connected.

**Comment by intellow** [comment]
I have an issue #328 where I'm getting the same error message. Caleb is at Full Stack EU but hopefully will be able to look at this soon.

**Comment by oliverbj** [comment]
I am getting the same error. 

For me it happens in cases where I try to use a `<select>` instead of an `<input>`. For example:

```html
<select wire:model="arguments.mode">
  <option value="opt1">Option 1</option>
  <option value="opt2">Option 2</option>
<select>
```

When changing the select option here, I get the error `getAttributeNames` error.

If I change above to a simple input, like below it works:

```html
<input wire:model="arguments.mode" type="text">
```

**Comment by oliverbj** [comment]
So I got this issue solved by adding a `wire:key` tag to my main `<div>` element. 

This issue is, at least for me, only present when I am using the `<select>` input _inside_ a nested component:

For example, I have a main component:

```html
<div>
  My livewire component.
  @foreach($users as $user)
     @livewire("nested.component", $user, key(encrypt($ser['id'])))
  @endforeach
</div>
```

Further, then inside the `nested.component`, I have this:

```html
<div class="bg-gray-800 text-white p-3 rounded-tl rounded-tr" wire:key="{{$user['id']}}">
  <select wire:model="arguments.mode">
    <option value="opt1">Option 1</option>
     <option value="opt2">Option 2</option>
  <select>
</div>
```

Notice the `wire:key="{{$user['id']}}"` tag on the first div. Adding this, fixed the `getAttributeNames of null` error.

**Comment by oliverbj** [comment]
Sorry, but above only fixed it partially. Sometimes the `getAttributeNames of null` error occurs, but I cannot figure out why and when.

**Comment by stefanbauer** [comment]
I am not sure, but I guess this may be closed. It should be solved on the new `dev-master` @calebporzio. Same error message was here #297

**Comment by calebporzio** [comment]
yep, someone can re-open if this is not the case, but should be.
