### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by yashiroiori** [livewire/livewire#347]
Hi.
There would be some possibility of being able to develop a base system by implementing the basic things needed for a system such as a BREAD, broadcast, modal, sweetalert, etc. to make it easier to use this package for new colleagues who find it and see how easy development is and have A real guide to implementation?

I can develop it in my spare time but I would like you to support me with the review to have a good implementation and that repo can be available to any user can help to add more features.

**Comment by calebporzio** [comment]
In the works. Thanks
