### ISSUE TITLE
livewire-tmp not cleaning up

### ISSUE THREAD

**Issue by Loots-it** [livewire/livewire#3471]
### Discussed in https://github.com/livewire/livewire/discussions/3470

<div type='discussions-op-text'>

<sup>Originally posted by **Loots-it** August  4, 2021</sup>
This folder is not cleaned up, not even after 24 hours (or more). I'm not using S3, just the local filesystem. I'm not sure what the problem is.

Because of this, my backups are getting too large. Of course there is no point in backing up the tmp files so I will have to exclude this folder anyway. But the tmp folder can get quite large in comparison to the other folders because the incoming photos aren't minified yet.

livewire: v2.5.5
laravel 8
php 8
using laravel forge</div>

**Comment by Loots-it** [comment]
This might have something to do with this issue: https://github.com/laravel/jetstream/issues/123

**Comment by Loots-it** [comment]
I looked at: https://www.youtube.com/watch?v=1I97BrpdPCg

When reading the documentation I thought the tmp files would be deleted automatically without any user interaction. But after watching this video I get that the files are only deleted when a new file upload is taking place. Am I right? To me personally this seems strange, if there are spikes in the amount of file uploads in a certain day and some days later someone wants to upload a new file, all the old files will be deleted in the same request. 

But anyway, after watching this video I can change the behavior if I want so if I'm right about the current behavior the issue can be closed. Although it would be a nice default feature if the tmp folder can be cleaned in a scheduled way, for example 2 times a day.

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
