### ISSUE TITLE
How to test that a component triggered an event via emit

### ISSUE THREAD

**Issue by linuxjuggler** [livewire/livewire#348]
Hey,

I have a component that triggers an event using `$this->emit`, what options do I have to test it?

Thanks

**Comment by calebporzio** [comment]
Curious why you closed this, I think Livewire needs an assertion for this kind of thing.

I just added it for you. It's called `assertEmitted($event)`. You can optionally pass in parameters to assert against params, or a callback to assert against a closure of your own.

Hope this helps you!

I'll have it available in the next release, and have it documented shortly.

**Comment by calebporzio** [comment]
Ok, the assertion has been tagged in a release and the feature is documented here: https://laravel-livewire.com/docs/unit-testing/#end-to-end-testing

**Comment by linuxjuggler** [comment]
Thank you @calebporzio

**Comment by linuxjuggler** [comment]
> Curious why you closed this, I think Livewire needs an assertion for this kind of thing.
> 
> I just added it for you. It's called `assertEmitted($event)`. You can optionally pass in parameters to assert against params, or a callback to assert against a closure of your own.
> 
> Hope this helps you!
> 
> I'll have it available in the next release, and have it documented shortly.

I want to try and go over the code today and see if I can do a PR to address it, after I noticed that it it not available. But you were faster than me.
