### ISSUE TITLE
Can't wire up Vue Web Components

### ISSUE THREAD

**Issue by edalzell** [livewire/livewire#349]
**Describe the bug**
With a Vue Date Picker web component, I can't bind the data via `wire`.

**To Reproduce**
1. `npm install v-calendar vue-custom-element`
2. Import/register everything
```
import Vue from 'vue';
import vueCustomElement from 'vue-custom-element'
import DatePicker from "v-calendar/lib/components/date-picker.umd";

Vue.use(vueCustomElement);

Vue.customElement('date-picker', DatePicker);
```
3. Create Livewire component
```
<div>
    <date-picker wire:model="foo"></date-picker>
    Date: {{ $foo }}
</div>

<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SalesFunnel extends Component
{
    public $foo;

    public function render()
    {
        return view('livewire.sales-funnel');
    }
}

```
4. Add component to page
```
@extends('layouts.app')

@section('content')
<div>
    @livewire('sales-funnel')
</div>
@endsection
```
5. Build and view page

**Expected behavior**
When a date is picked, it is displayed on the page

**Screenshots**
<img width="247" alt="image" src="https://user-images.githubusercontent.com/6069653/67920127-3d933300-fb60-11e9-9955-7e6a41248e0d.png">

**Comment by panda-madness** [comment]
Try wrapping your component into a proxy custom element, via [this](https://github.com/karol-f/vue-custom-element) library.

P.S. Statamic v3 when?! :)

**Comment by calebporzio** [comment]
Vue related issues should go here: https://github.com/livewire/vue

Closing.
