### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by ServerJunge** [livewire/livewire#351]
Hello,

I use Laravel/Livewire together with [Laravel/Stancl](https://github.com/stancl/tenancy).

But I get the following error in my google chrome console:

```
Uncaught (in promise) SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at livewire.js?id=a62f8bb756eb4903a6d4:3127
```

I just created a basic component/class with php artisan make:livewire invite

```
<div>
    <input type="text" wire:model="email">

    Hi! My email is {{ $email }}
</div>
```

```
<?php

namespace App\Http\Livewire\Users;

use Livewire\Component;

class Invite extends Component
{

    public $email;

    public function render()
    {
        return view('livewire.users.invite');
    }
}
```

I think it has something to do with the multitenancy package -> subdomain?

**Comment by ServerJunge** [comment]
I further nvestigated my problem and I think that the problem has something to do with the routes. Because when I have a subdomain the laravel/stancl package does use not the default routes/web.php but instead the routes/tenant.php.

Any idea how to fix this?

**Comment by ServerJunge** [comment]
When I add the Route to the default routes/web.php it works like charm. But not if I use the routes/tenant.php

**Comment by panda-madness** [comment]
@ServerJunge try adding the `web` middleware to your routes in tenant.php

**Comment by ServerJunge** [comment]
@panda-madness thank you for your answer. 

I think I found the source of the problem. See the following Telescope screenshots.In the first screenshot  I just return the index view with the livewire component and there are two middlewares attached (web and tenancy)

![image1](https://i.imgur.com/KapMvN3.png)

The second screenshot is the post method from the component. And there is only one middleware (web). 

![image2](https://i.imgur.com/PBwIZZ8.png)

Is it possible to attach the middleware to the post?

**Comment by ServerJunge** [comment]
It works now... But I don't know if it is really the best solution.

I created a new middlewareGroup -> 'livewire' and copied all entries from the 'web' group and change "PreventAccessFromTenantDomains::class" to "\Stancl\Tenancy\Middleware\InitializeTenancy::class"

https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#custom-groups

```
protected $middlewareGroups = [
        'web' => [
            \Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::class,
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            \Stancl\Tenancy\Middleware\PreventAccessFromTenantDomains::class,
            'throttle:60,1',
            'bindings',
        ],
        'livewire' => [
            \Stancl\Tenancy\Middleware\InitializeTenancy::class,
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

Then I changed the Livewire Config to recognize the new middleware group.

```
 /*
    |--------------------------------------------------------------------------
    | Livewire Endpoint Middleware Group
    |--------------------------------------------------------------------------
    |
    | This value sets the middleware group that will be applied to the main
    | Livewire "message" endpoint (the endpoint that gets hit everytime,
    | a Livewire component updates). It is set to "web" by default.
    |
    */

    'middleware_group'  => 'livewire',
```

After that I get another error.

```
BadMethodCallException
This cache store does not support tagging.
```

I googled it changed the CACHE_DRIVER from file to array in my .env file.

`CACHE_DRIVER=array`

And after that it works... But it feels a litte bit hacky...

**Comment by lancepioch** [comment]
This seems to be an issue with the default preset middleware group from stancl's package.

The correct solution seems to be what you said and replace the `PreventAccessFromTenantDomains` with `InitializeTenancy` class in your middleware group. You did this by just creating a whole new array, but you could just find and modify the previous entry in the array too.

**Comment by calebporzio** [comment]
Thanks @lancepioch
