### ISSUE TITLE
URL defaults are not respected when using pagination

### ISSUE THREAD

**Issue by grafxflow** [livewire/livewire#3549]
I am having the same problem but only in relation to pagination.

Here is the route.

```
Route::middleware('subdomain')->domain('{subdomain}.' . env('APP_DOMAIN', 'localhost'))->group(function () {
    Route::prefix('/news')->group(function() {
        Route::get('/{category}', Category::class)->name('category');
        Route::get('/{category}/{article}', Article::class)->name('article');
    });
});
```

Here is the middleware.

```
public function handle($request, Closure $next)
{
    URL::defaults(['subdomain' => request('subdomain')]);
    return $next($request);
}
```

### Discussed in https://github.com/livewire/livewire/discussions/2473

<div type='discussions-op-text'>

<sup>Originally posted by **Mecit** February  8, 2021</sup>
Hey there. I'm not sure if that's an issue or I have some conceptual misunderstanding, so I'm starting this as a discussion. 

I have a subdomain-based tenancy application and it uses a route level middleware that sets the default value for tenants. 

```
Route::middleware(App\Http\Middleware\SetDefaultTenantForRoutes::class)
     ->domain('{tenant}.' . config('app.url'))
    ...
```

And all the middleware does is to set the default tenant with `URL::defaults(['tenant' => $request->route('tenant')])` and that works just fine in a typical Laravel lifecycle. However, it seems I cannot use route redirections or url generations without having to set the tenant explicitly in Livewire components/views. e.g. in a Livewire component method `return redirect()->route('tenant:users')` throws a "missing required parameter" exception. As for views, I can use it with no parameters when a component first renders, but when the component updates, the same error occurs again. Any idea as to why Livewire doesn't pick the parameter up? It'd be quite cumbersome having to set the parameter every time I need to redirect a user or generate a link to a named route. 

</div>

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
