### ISSUE TITLE
Empty values when binding to Eloquent model

### ISSUE THREAD

**Issue by emildayan** [livewire/livewire#3550]
Cannot update company.email to an empty value. As soon as it becomes empty, it resets to default value (filled).

`use AuthorizesRequests;

    public Company $company;
    protected      $rules = [
        'company.name'  => ['required', 'string'],
        'company.email' => ['nullable', 'sometimes', 'email'],
    ];

    public function mount(Company $company)
    {
        $this->authorize('view', $company);
        $this->company = $company;
    }

    public function save()
    {
        $this->validate();
        $this->company->save();
        $this->company->wasUpdated();
    }

    public function render()
    {
        return view('livewire.company.details');
    }

    ------

    <form wire:submit.prevent="save" class="form">
        <x-input.text-simple wire:model="company.name" name="company.name" required/>
        <x-input.text-simple wire:model="company.email" name="company.email"/>
        
        <button wire:loading.class="loading" wire:target="save" type="submit">Save</button>
    </form>`

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
