### ISSUE TITLE
Adding cache to the s3 adapter breaks the temporary file preview

### ISSUE THREAD

**Issue by ricard-pons** [livewire/livewire#3574]
### Discussed in https://github.com/livewire/livewire/discussions/3573

<div type='discussions-op-text'>

<sup>Originally posted by **ricard-pons** August 24, 2021</sup>
To reproduce:

1. Fresh Laravel install
2. Use these library versions:
```
"league/flysystem-aws-s3-v3": "^1.0",
"league/flysystem-cached-adapter": "~1.0",
"livewire/livewire": "^2.5",
```

3. Set s3 temp file previews
`config(['livewire.temporary_file_upload.disk' => 's3'])`

4. Add cache to s3 adapter in `fillesystem.php`
```
's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'cache' => [
                'store' => 'redis',
                'expire' => 600,
                'prefix' => 's3:',
            ]
        ],
```

5. Upload a file

You get:
`Call to undefined method League\Flysystem\Cached\CachedAdapter::getClient()` in `vendor/livewire/livewire/src/GenerateSignedUploadUrl.php:24`.

Not sure about this, but maybe Livewire should check the "instance of" `FileUploadConfiguration::storage()->getDriver()->getAdapter()` and if its a CachedAdapter use $adapter->s3Client and if its not then continue working like now.

Thanks.

<img width="349" alt="Screenshot 2021-08-24 at 19 06 10" src="https://user-images.githubusercontent.com/15916288/130601611-2d7cb246-8ca1-427e-b699-cb968bdd97a4.png">

<img width="363" alt="Screenshot 2021-08-24 at 19 06 02" src="https://user-images.githubusercontent.com/15916288/130601606-6038ac6b-76ac-4147-9813-078ad1adb2fd.png">

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
