### ISSUE TITLE
Clicking a button while textarea is focused causes error

### ISSUE THREAD

**Issue by cihantas** [livewire/livewire#358]
**Describe the bug**
If an input field (a text area in my case) with a wire:model.lazy attribute is focused and a button with wire:click.prevent is clicked, the button click seems to be queued but not executed. You have to click once more, but then the function bound to the button is fired twice.

**To Reproduce**

1. Create the following view and component:

```blade
<div>
    @if($clicks === 0)
        <h1>0</h1>

        <textarea wire:model.lazy="firstTextArea" placeholder="Type something in me..."></textarea>
        <button type="button" wire:click.prevent="incClicks">Click Me</button>
    @endif

    @if($clicks === 1)
        <h1 style="color: green;">1</h1>
    @endif

    @if($clicks === 2)
        <h1 style="color: red;">2</h1>
    @endif
</div>
```

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class TestBug extends Component
{
    public $clicks = 0;
    public $firstTextArea;

    public function render()
    {
        return view('livewire.test-bug');
    }

    public function incClicks()
    {
        $this->clicks++;
    }
}
```

1. Focus the textarea and type something.
2. Click on the button once while the textarea is focused.
3. See that nothing happens. 🤡
4. Click the button again.
5. See the number 2.

**Expected behavior**
You should see the number 1, because `$clicks` should be `1` and the respective `@if` clause in the Blade template should be rendered.

**Screenshots**
![rcrd](https://user-images.githubusercontent.com/1579976/68607911-099a0500-04b2-11ea-8882-22cdc042cd2d.gif)

**Desktop (please complete the following information):**
- Browser: Chrome

**Additional context**
If you inspect the network requests in Chrome, during the reproduction, you can see that...

1. Clicking on the button for the first time also means that you're unfocusing the textarea which triggers a Livewire sync and seems to block the sync of the button click.
2. The second click causes another sync.

Beyond that:

If you unfocus the textarea before clicking the button, everything works as expected.

**Comment by cihantas** [comment]
After further research I found what I believe is a code part matching this issue:

https://github.com/livewire/livewire/blob/2daad5d54e2743174951af68bf383c90182afd3a/src/js/Component/index.js#L96-L103

**Comment by cihantas** [comment]
I was able to fix the issue temporarily by increasing the debounce to 75ms. I had no success with anything <50ms.

I'm curious: The debounce is used to avoid two separate action syncs, but if I set a low debounce only the first request is fired and the second action is only fired *if* there's a following event. Therefore I don't believe what I did solves the actual issue, but is just a temporary workaround.

**Comment by calebporzio** [comment]
Yes, this is a known issue. The problem is that `wire:click` is listening for a `click` event, which actually fires on `mouseup`. However, the `.lazy` fires on a `change` event, which happens when an input element looses focus (on the `mousedown`).

So to illustrate better, here's what's happening:

* The input element is currently focused
* The mouse goes "down" on the button
* The input element looses focus, firing a "change" event, and sending a livewire request to update the input
* The mouse goes "up" on the button (presumably while the network request is already happening), which queues that action for the next round-trip
* You click the button again, and it fires twice.

The fix:
Set `wire:click.prevent="inClicks"` to `wire:mousedown.prevent="inClicks"

That will fix your problem.

However, it's not "ideal".

Here are some options off the top of my head:
A) Just add docs near the ".lazy" modifier to warn about this issue
B) Default "click" to mousedown (definitely don't want to do this)
C) Somehow hook into the "change" event listener added by ".lazy", check if the mouse is currently down on a "wire:click" element, and wait to send the payload along.

A is quick and easy, but not ideal. B is just bad. C is good, but I can't exactly picture how to do it ATM.

Thoughts?

**Comment by cihantas** [comment]
Changing `wire:click` to `wire:mousedown` sadly didn't solve the problem for us. The UI behaves slightly different now, but the problem persists.

A, B, C are also non-ideal solutions IMO.

I quickly sat down with my team this morning and we extended the components queue by a worker (consumer), a simple interval that is registered in the constructor, which continuously calls `fireMessage` whenever no message is currently in transit and the queue contains items. Works like a charm. 

A downside might be battery / CPU consumption. Our interval is currently set to 250ms. We will very likely do some more research on this end, but were a bit under pressure.

Would love to send a pull request if this sounds like a solution you could live with.

**Comment by calebporzio** [comment]
Would a more elegant solution be to have some logic when any request comes back from the server that says:
* is there an action in the queue?
* fire it

what do you think?

**Comment by cihantas** [comment]
IMO that sounds even better, because:

- less complexity e.g. no interval to manage
- no delay between response and next action sync, compared to the interval 

We've thought about this, too, but were a bit under pressure and concerned we might miss something in the rush, like what if a request fails? 

This could actually fix the issue in a couple lines. 👏

**Comment by calebporzio** [comment]
Yeah, it actually opens the door for more possibilities as well.

It should definitely be implemented, and good call on the failed request gotcha - I'll try to add a test for that, or at least account for it.

Good stuff.

**Comment by calebporzio** [comment]
Ok, @cihantas, I have the change on the `dev-master` branch.

Pull it down and try it if you can.

1. I wasn't able to test the functionality (I tried hard, it's a really hard thing to unit test with the current setup)
2. I don't have any handling for failed initial requests. I'm not sure what the best way to handle them is. Things are broken anyways if something goes wrong, so idk... (I tested a quick example of a breakage, and it didn't act too wonky)

Let me know, thanks!

**Comment by cihantas** [comment]
Works. 👌

I'll see if I can add anything in the future regarding 1. and 2., but until then we can close the issue.

As always, thanks a lot for your hard work! I'm glad we were able to solve this issue.

**Comment by ben-demotic** [comment]
Could I ask if this issue was ever fixed?  It seems to still be a problem in the latest 2.4.4 version, i.e. if you have a textarea with wire:model.lazy, when you click submit the first time it fires the "change" event but doesn't "submit" the form.
