### ISSUE TITLE
Optional open tag for your IDE when creating a livewire component 

### ISSUE THREAD

**Issue by roni-estein** [livewire/livewire#359]
I'll probably do this in a bash script or make my own artisan command, however, in case anyone runs into this. I always run into the problem of having to sync folders in phpstorm when I add a file through an artisan command. So I normally strip out the filename or wrap the command and throw in a `pstorm <file(s)> `prompting phpstorm to sync and index only the generated file(s) right away.

It's always a little easier when an option comes right from the package though. Something like:

`php artisan make:livewire Example --ide=pstorm`

where pstorm is simply the terminal command, and it would just open the Component file and the view.

I'd be happy to contribute it if I'm not insane and this annoy's anyone else

**Comment by calebporzio** [comment]
I dont use Storm, so I'll wait for others to chime in. However, I typically don't add these types of things.
