### ISSUE TITLE
Undefined variable on extended layout

### ISSUE THREAD

**Issue by simongas** [livewire/livewire#360]
When I try to use a layout with some variables attached to it, livewire will throw an error. Undefined variable.

@extends('layouts.app', [
	'title' => 'Salas',
	'modalCreate' => true,
	'modalUpdate' => true,
])

Im calling this layout from a livewire view and will get the error undefined variable title. If I make a normal view instead it works fine.

 ErrorException (E_ERROR)
Undefined variable: title

**Comment by cosmicvibes** [comment]
I also have this problem. I have worked around it by pass the variables into the view on the livewire component render method.

**Comment by calebporzio** [comment]
Sorry, I'm confused. Mind giving a more full explanation with code pasted in? Thanks.

**Comment by lukasplevko** [comment]
Instead of making a global variable in the controller I made one in the method and passed it with the view and everything worked fine. Idk why it wont take the globals.

**Comment by simongas** [comment]
> 
> 
> Instead of making a global variable in the controller I made one in the method and passed it with the view and everything worked fine. Idk why it wont take the globals.

Yes that's one way to work around it.

**Comment by RomainMazB** [comment]
@thanosalexander 
I think your problem is described here in [a PR I've submitted](https://github.com/livewire/livewire/pull/1807) and could have solved it but had not been merged :/
