### ISSUE TITLE
Use component methods within blade

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#362]
I would like to make use of methods in the component class inside of the component's blade.
For example i find it better to have a method called `isSelected($id)` and use it in blade instead of doing the check `in_array($id, $selectedIds)` directly in blade 

The ideal way i see it is that when using `$this` inside of blade it will reference the class.

What i'm doing right now is i'm accessing the component class via the `$_instance` variable but i'm not sure if that is a bad thing or not ? Would that cause some problems in the future ?

I also tried passing a reference to the class via the render method something like this and it works
```php
public function render()
{
     return view('...', ['vm' => $this]);
}
```

I really would like to know what you think @calebporzio and are you open for maybe using the $this within blade ?

**Comment by calebporzio** [comment]
Intresting... Yeah, like you found, you can use `$_instance`, but it of course feels hacky.

I currently use `@this` to reference the javascript `this`, so it might be confusing.

However, I to kinda like exposing a `$this` for the current component from a Blade template.

I'd be open to a PR. I think I dig.

**Comment by shadoWalker89** [comment]
So the only possible way to make $this be bound to the component is if the when the blade.php file is included is done within a closure that re-bind the $this keyword to an object.
That is only possible if a new laravel View engine is added or overriding the laravel engine itself. Since we don't want to do the latter we must try adding custom engine for livewire.
But here is the catch, adding a new engine means using custom extension for livewire for example `file.blade.php` becomes `file.livewire.php` i don't know if that is worth it especially i know that you want livewire to be as close as possible to laravel.
Maybe it will be simpler to just pass a `$component` variable to each view within livewire to avoid this complex things and mention that in the docs ?

**Comment by calebporzio** [comment]
Yeah, that's all good thinking.
I'm down for a `$component`, but it REALLY would be nice to have `$this`

**Comment by calebporzio** [comment]
We can totally hack the engine instead of extending it. I already hack it a bit.

Not necessarily suggesting we do it, just sayin'

![image](https://user-images.githubusercontent.com/3670578/68724124-a4fda980-0588-11ea-9c76-5952a9537ebf.png)

**Comment by shadoWalker89** [comment]
That is what i meant by overriding the laravel engine, but i thought you wouldn't want something like that. (I didn't check your code to see that you were already using it)
I tried something locally and it worked, i'll be making a PR soon for you to check.

**Comment by shadoWalker89** [comment]
PR ready https://github.com/livewire/livewire/pull/364
