### ISSUE TITLE
Form and data assertions

### ISSUE THREAD

**Issue by roni-estein** [livewire/livewire#363]
**Is your feature request related to a problem? Please describe.**
Hey, using livewire a lot for forms, love it.  However, I've essentially stopped testing.

Are there any assertions like $response->assertSessionHasError() in livewire? Since it's handling validation?

If there aren't any, I'd be happy to contribute that, if someone would't mind pointing at a few starting place files to look at. I'd be happy to contribute it to the docs as well.

**Comment by calebporzio** [comment]
Ok, good call. Just added these two methods:

`$this->assertHasErrors()` and `$this->assertHasNoErrors()`

The usage is best demonstrated in the following test method you can find in (`tests/LivewireTestingTest.php`)

```php
        app(LivewireManager::class)
            ->test(ValidatesDataWithSubmitStub::class)
            ->call('submit')
            ->assertHasErrors('foo')
            ->assertHasErrors(['foo', 'bar'])
            ->assertHasErrors([
                'foo' => ['required'],
                'bar' => ['required'],
            ]);
```
and 
```php
        app(LivewireManager::class)
            ->test(ValidatesDataWithRealTimeStub::class)
            ->set('foo', 'bar-baz')
            ->assertHasNoErrors()
            ->set('foo', 'bar')
            ->assertHasErrors('foo')
            ->assertHasNoErrors('bar')
            ->assertHasErrors(['foo'])
            ->assertHasErrors([
                'foo' => ['min'],
            ])
            ->assertHasNoErrors([
                'foo' => ['required'],
            ])
            ->set('bar', '')
            ->assertHasErrors(['foo', 'bar']);
```

**Comment by calebporzio** [comment]
These methods are only on `dev-master` right now, will tag within a day or two.

**Comment by roni-estein** [comment]
Thanks! I think the problem is it's so easy to test right now visually that I'm deferring to it. But I hate coding without tests. Are there any contributions that we can do to help you? Docs? For example, are you a better editor than writer or awesome at both?

Some of us can generate some rough docs for this with examples to boot and submit them for you to edit. This might make doc creation a bit faster.

Let me know your thoughts and where you think we can be the most helpful.

**Comment by calebporzio** [comment]
Thanks a ton @roni-estein! The most helpful thing for me is triaging issues and commenting, fixing, closing them.

I think for this feature, I'm going to handle the docs because I have kind of a specific vision for them, but typically I'd say YES!

Thanks for being so willing to pitch in!
