### ISSUE TITLE
Confirm actions

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#366]
Hi,
I want to show a confirmation modal before performing dangerous actions like deleting something ...
I think currently this is not possible right now.
Is there a way to do this without making a server request ?

**Comment by shadoWalker89** [comment]
I was thinking if livewire could trigger some client actions, this is some pseudo code of how i imagine it ...

```php
<button wire:click.client="delete({{ $user->id }})">Delete</button>

<script>
livewire.actions.register('delete', function(id){
    if(confirm("Are you sure you want to delete this item ?"))
    {
         livewire.trigger('deleteMethodOnTheServer');
    }
});
</script>
```

**Comment by fra000** [comment]
Hi, in your button put this:

`<button onclick="confirm('Confirm delete?') || event.stopImmediatePropagation()" wire:click...>Delete</button>`.

This works for me.

**Comment by shadoWalker89** [comment]
Problem is that i'm not using confirm() in my real code. I just used it to in the pseudo code to explain my self.
What would work is `onclick="someFunction()"` and
```js
someFunction(event)
{
    event.stopImmediatePropagation();
    // Custom code, confirmation ....
}
```
The only problem i see it now is how can i trigger the action on the server, maybe caleb should add a new special action `$trigger('serverMethod')`

**Comment by calebporzio** [comment]
@shadoWalker89, if you do that `someFunction` thing. You can call a server method like so:
```js
function someFunction(event)
{
    event.stopImmediatePropagation();
    
    ...
    @this.call('delete')
}
```

It's documented in the "Inline Scripts" section of the docs.

https://laravel-livewire.com/docs/inline-scripts/

**Comment by shadoWalker89** [comment]
Thanks to both of you guys.
This works perfect, the only problem now is that the wire:loading using a target does not work any more.

**Comment by calebporzio** [comment]
Aaah, good point. I've been considering making tergets reference actions instead of refs, this is a good case for that.

**Comment by faustbrian** [comment]
@shadoWalker89 this can probably be closed now that 0.5 changed targets from references to actions?

**Comment by calebporzio** [comment]
Yep!

**Comment by mc0de** [comment]
@shadoWalker89 

my take in this:

```
// In livewire component
public function confirm($callback, ...$argv)
{
    $this->emit('confirm', compact('callback', 'argv'));
}

// In component's blade file
<button type="button" wire:click="confirm('delete', {{ $project->id }})">Delete</button>

// Script in component's blade file
<script>
Livewire.on('confirm', e => {
    if (!confirm('You sure?')) { return }
    @this[e.callback](...e.argv)
})
</script>
```

**Comment by tiago-pontomais** [comment]
> @shadoWalker89
> 
> my take in this:
> 
> ```
> // In livewire component
> public function confirm($callback, ...$argv)
> {
>     $this->emit('confirm', compact('callback', 'argv'));
> }
> 
> // In component's blade file
> <button type="button" wire:click="confirm('delete', {{ $project->id }})">Delete</button>
> 
> // Script in component's blade file
> <script>
> Livewire.on('confirm', e => {
>     if (!confirm('You sure?')) { return }
>     @this[e.callback](...e.argv)
> })
> </script>
> ```

Thank you very much

**Comment by itsmemanoj** [comment]
Very old but like I came to this, someone else might come too, Here is my solution
```
<div class="d-inline" x-data="{ confirmDelete:false }">
      <button x-show="!confirmDelete" x-on:click="confirmDelete=true"
          class="btn btn-danger btn-xs">Delete</button>

      <button x-show="confirmDelete" x-on:click="confirmDelete=false"  wire:click="delete({{ $user->id }})"
          class="btn btn-success btn-xs">Yes</button>
  
      <button x-show="confirmDelete" x-on:click="confirmDelete=false"
          class="btn btn-danger btn-xs">No</button>
</div>
```

**Comment by tiagofrancafernandes** [comment]
> Very old but like I came to this, someone else might come too, Here is my solution
> 
> ```
> <div class="d-inline" x-data="{ confirmDelete:false }">
>       <button x-show="!confirmDelete" x-on:click="confirmDelete=true"
>           class="btn btn-danger btn-xs">Delete</button>
> 
>       <button x-show="confirmDelete" x-on:click="confirmDelete=false"  wire:click="delete({{ $user->id }})"
>           class="btn btn-success btn-xs">Yes</button>
>   
>       <button x-show="confirmDelete" x-on:click="confirmDelete=false"
>           class="btn btn-danger btn-xs">No</button>
> </div>
> ```

Thank you too.
But 2 asks:
1. On "Yes" button may be is `x-on:click="confirmDelete=true" ` ?!
2. How I wil retrieve the x-data value? Only in project with AlpineJS?

**Comment by itsmemanoj** [comment]
> > Very old but like I came to this, someone else might come too, Here is my solution
> > ```
> > <div class="d-inline" x-data="{ confirmDelete:false }">
> >       <button x-show="!confirmDelete" x-on:click="confirmDelete=true"
> >           class="btn btn-danger btn-xs">Delete</button>
> > 
> >       <button x-show="confirmDelete" x-on:click="confirmDelete=false"  wire:click="delete({{ $user->id }})"
> >           class="btn btn-success btn-xs">Yes</button>
> >   
> >       <button x-show="confirmDelete" x-on:click="confirmDelete=false"
> >           class="btn btn-danger btn-xs">No</button>
> > </div>
> > ```
> 
> Thank you too.
> But 2 asks:
> 
> 1. On "Yes" button may be is `x-on:click="confirmDelete=true" ` ?!
> 2. How I wil retrieve the x-data value? Only in project with AlpineJS?

x-data="{confirmDelete:false}" means we are setting the initial value for confirmDelete variable to false.
then clicking on delete button, confirmDelete variables value will be updated to true.
Yes it works with AlpineJs. But if you this can be with livewire only too.
To use LIvewire only, you have to set a public variable in livewire controller confrimDelete = false.
then set wire:click in delete button to change the value of variable and if variable is true then show the confirm button

**Comment by tiagofrancafernandes** [comment]
> > > Very old but like I came to this, someone else might come too, Here is my solution
> > > ```
> > > <div class="d-inline" x-data="{ confirmDelete:false }">
> > >       <button x-show="!confirmDelete" x-on:click="confirmDelete=true"
> > >           class="btn btn-danger btn-xs">Delete</button>
> > > 
> > >       <button x-show="confirmDelete" x-on:click="confirmDelete=false"  wire:click="delete({{ $user->id }})"
> > >           class="btn btn-success btn-xs">Yes</button>
> > >   
> > >       <button x-show="confirmDelete" x-on:click="confirmDelete=false"
> > >           class="btn btn-danger btn-xs">No</button>
> > > </div>
> > > ```
> > 
> > 
> > Thank you too.
> > But 2 asks:
> > 
> > 1. On "Yes" button may be is `x-on:click="confirmDelete=true" ` ?!
> > 2. How I wil retrieve the x-data value? Only in project with AlpineJS?
> 
> x-data="{confirmDelete:false}" means we are setting the initial value for confirmDelete variable to false.
> then clicking on delete button, confirmDelete variables value will be updated to true.
> Yes it works with AlpineJs. But if you this can be with livewire only too.
> To use LIvewire only, you have to set a public variable in livewire controller confrimDelete = false.
> then set wire:click in delete button to change the value of variable and if variable is true then show the confirm button.
> 
> **_On "Yes" button may be is x-on:click="confirmDelete=true_**
> No, we need to hide buttons. ConfirmDelete=false will hide button after deleteing

Thank you very much!
