### ISSUE TITLE
Loading with a target doesn't work as it should

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#367]
**Describe the bug**
There is a problem is showing a loading indicator with a target when the button that triggers the actions contains a font icon.
If the button click is not over the icon the loading indicator show and only for the first time i use the button.
If the click is over the button it does not work not the first time not after.

**To Reproduce**
Over here i'm using a font awesome icon
```html
<div wire:loading wire:target="myRef">Loading</div>

<button wire:click="someAction" wire:ref="myRef">
    <i class="green large hand pointer outline icon pointer"></i>
</button>
```

**Expected behavior**
When i click the button any where even over the icon the loading indicator should appear.
I want also to mention that i tried the click.self and click.stop and both didn't make any difference

**Desktop (please complete the following information):**
 - Chrome Version 78.0.3904.97 (Official Build) (64 bits)

**Comment by calebporzio** [comment]
This should be fixed as the loading system no longer uses `wire:ref`s, the `wire:target` now targets Livewire actions instead.

Closing this for now. Re-open if I've mis-understood.

Thanks!

(Here's what that code example would be):
```php
<div wire:loading wire:target="someAction">Loading</div>

<button wire:click="someAction">
    <i class="green large hand pointer outline icon pointer"></i>
</button>
```
