### ISSUE TITLE
wire:loading not working with multiple wire:ref with same value

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#369]
**Describe the bug**
I have mutliple nodes using the same `wire:ref="session-loader"` and then use that ref on a `wire:target`
The loading div shows up only on the first interaction, after that it never shows.

**To Reproduce**
```html
<div wire:loading wire:target="session-loader">Loading</div>

<a wire:ref="session-loader">Pick</a>
<a wire:ref="session-loader">Unpick</a>
```

**Expected behavior**
Each time i interact with the nodes with wire:ref="session-loader" the loading div should appear

**Desktop (please complete the following information):**
 - Chrome Version 78.0.3904.97 (Official Build) (64 bits)

**Comment by calebporzio** [comment]
Loading has been changed in the latest release, here is the new way to accomplish that:
```
<div wire:loading wire:target="foo">Loading</div>

<a wire:click="foo">Pick</a>
<a wire:click="foo">Unpick</a>
```

Or if the click actions are different, then:
```
<div wire:loading wire:target="foo, bar">Loading</div>

<a wire:click="foo">Pick</a>
<a wire:click="bar">Unpick</a>
```

**Comment by henry25225** [comment]
But multiple targets don't work for target actions with specific parameters
`
<div wire:loading wire:target="increaseQuantity({{ $product['id'] }}), decreaseQuantity({{ $product['id'] }})"></div>
`
![image](https://user-images.githubusercontent.com/59507118/117913075-b1161480-b2ae-11eb-93d3-c208b0624a4f.png)

**Comment by drbornot** [comment]
> 
> 
> But multiple targets don't work for target actions with specific parameters
> 
> `<div wire:loading wire:target="increaseQuantity({{ $product['id'] }}), decreaseQuantity({{ $product['id'] }})"></div>`
> 
> ![image](https://user-images.githubusercontent.com/59507118/117913075-b1161480-b2ae-11eb-93d3-c208b0624a4f.png)

Hey there. Any solution on this? I'm facing the same

**Comment by argonzalez2016** [comment]
> > But multiple targets don't work for target actions with specific parameters
> > `<div wire:loading wire:target="increaseQuantity({{ $product['id'] }}), decreaseQuantity({{ $product['id'] }})"></div>`
> > ![image](https://user-images.githubusercontent.com/59507118/117913075-b1161480-b2ae-11eb-93d3-c208b0624a4f.png)
> 
> Hey there. Any solution on this? I'm facing the same

I am facing the same issue.

**Comment by marchershey** [comment]
bump
