### ISSUE TITLE
SPA mode/Turbolinks redirects

### ISSUE THREAD

**Issue by phoogkamer** [livewire/livewire#370]
Currently livewire performs a js redirect whenever a RedirectResponse is returned from the component, but if I understand correctly for Turbolinks to play nice with those you have to use Turbolinks.visit(). 

Is there a way to make Livewire perform this to have a real 'SPA-like' experience? Most of my Livewire forms redirect when they complete so this is quite a large part of my application.

**Comment by phoogkamer** [comment]
For now I used a workaround where I emit a 'redirect' event from the component with the url.

Then I just added this:
```
    document.addEventListener('livewire:load', function (event) {
        window.livewire.on('redirect', param => {
            Turbolinks.visit(param)
        })
    })
```

**Comment by calebporzio** [comment]
Ah yes, that makes sense.

It certainly would be fairly simple to detect if the page is using Turbolinks, and do the redirection that way.

I'm open to a PR like this.

Although, something like this may be better served as a plugin. But because I recommend Turbolinks in the Docs, this seems like a good solution for now.

**Comment by andonovn** [comment]
@phoogkamer Are you going for the PR? If not, I'd love to take over that.

**Comment by phoogkamer** [comment]
@andonovn Feel free. I would do it, but I'm time constrained at the moment. Let me know how it goes!

**Comment by bbcreation** [comment]
> For now I used a workaround where I emit a 'redirect' event from the component with the url.
> 
> Then I just added this:
> 
> ```
>     document.addEventListener('livewire:load', function (event) {
>         window.livewire.on('redirect', param => {
>             Turbolinks.visit(param)
>         })
>     })
> ```

phoogkamer  I have the same problem. Can you show me how you solved it specifically? I'm fresh in Livewire.

**Comment by andonovn** [comment]
> @andonovn Feel free. I would do it, but I'm time constrained at the moment. Let me know how it goes!

Turned out I also had very limited time lately. Going for the PR next week for sure, tho!

**Comment by andonovn** [comment]
> > For now I used a workaround where I emit a 'redirect' event from the component with the url.
> > Then I just added this:
> > ```
> >     document.addEventListener('livewire:load', function (event) {
> >         window.livewire.on('redirect', param => {
> >             Turbolinks.visit(param)
> >         })
> >     })
> > ```
> 
> phoogkamer I have the same problem. Can you show me how you solved it specifically? I'm fresh in Livewire.

Basically, there are two steps only involved.
1. Listen for an event. In the following example the event is being called `redirect`. Put the snippet in your main js file:
```
document.addEventListener('livewire:load', () => {
    window.livewire.on('redirect', url => Turbolinks.visit(url))
})
```
2. Fire the event from a Livewire component. Again, `redirect` is just the name of the component that we listen to from step 1. `/` is the URL where we want to redirect to, the same one we instruct Turbolinks to visit from step 1.
```
$this->emit('redirect', '/');
```

**Comment by ricardogobbosouza** [comment]
Hi @andonovn, @phoogkamer 
I created a PR https://github.com/livewire/livewire/pull/430

**Comment by calebporzio** [comment]
Thanks so much, this will be in the next release.

**Comment by TrentDPT** [comment]
How do we resolve this issue?  I have a simple Livewire Tabs in my homepage with Turbolinks running, and everytime I click a tab it reloads the entire page.  I'm not sure how to solve this.

**Comment by adamhopkinson** [comment]
@TrentDPT looks like support was added in v1 then removed in v2 and replaced with a plugin:

https://github.com/livewire/turbolinks
