### ISSUE TITLE
Bug into select with values like 01

### ISSUE THREAD

**Issue by yashiroiori** [livewire/livewire#371]
**Describe the bug**
When a select use this values:
"01":"01 - Efectivo",
"02":"02 - Cheque nominativo",
"03":"03 - Transferencia electrónica de fondos",
"04":"04 - Tarjeta de crédito",
"05":"05 - Monedero electrónico",
"06":"06 - Dinero electrónico",
"08":"08 - Vales de despensa",
"12":"12 - Dación en pago",

![image](https://user-images.githubusercontent.com/17031855/68999795-6f5c0780-088b-11ea-8eed-605d08f9cc03.png)

On choose value into select say:
![image](https://user-images.githubusercontent.com/17031855/68999760-f78ddd00-088a-11ea-94cb-df0ae7fea053.png)

But if use values without "0" into value:
"1":"01 - Efectivo",
"2":"02 - Cheque nominativo",
"3":"03 - Transferencia electrónica de fondos",
"4":"04 - Tarjeta de crédito",
"5":"05 - Monedero electrónico",
"6":"06 - Dinero electrónico",
"8":"08 - Vales de despensa",
"12":"12 - Dación en pago",

All work fine not error:
![image](https://user-images.githubusercontent.com/17031855/68999780-4b98c180-088b-11ea-87d7-1f11f82e9ac6.png)

**Comment by lancepioch** [comment]
I think this is related to #283 and has to do with you using accented characters (non ascii).

**Comment by calebporzio** [comment]
This issue needs more source code for reference and verification that this is still an issue. Closing for now.

**Comment by emanuelErazo1** [comment]
the solution is check in backend if sleec firts is null or empty, in result is true so set value var $this->var = value in front select option
