### ISSUE TITLE
Livewire null parameter bug

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#372]
**Describe the bug**
```php
class Foo
{
    public function mount($user = null, $options = [])
    {
    }
}
```

When i call it like this

```php
@livewire('foo', null, ['mode' => 'planner'])
```

I get `null` for both arguments `$user` and `$options`

When i call it like this

```php
@livewire('foo', '', ['mode' => 'planner'])
```

I get `empty string` for `$user` and `['mode' => 'planner']` for `$options`

If i remove the default null from `Foo::mount()` on the `$user`

```php
class Foo
{
    public function mount($user, $options = [])
    {
    }
}
```

And then call 

```php
@livewire('foo', null, ['mode' => 'planner'])
```

I'll get correct values `null` for `$user` and `['mode' => 'planner']` for `$options`

**Expected behavior**
Even when using a default value `null` in the `mount()` argument values should be mapped correctly and i shouldn't get `null` for the `$mode` argument

**Comment by calebporzio** [comment]
Gotcha, looks like an issue that wouldn't be too hard to fix. Would love A PR with tests

**Comment by shadoWalker89** [comment]
### Bug explanation
So this is what i found.
To resolve the dependencies you are using `resolveClassMethodDependencies()` of the following trait `Illuminate\Routing\RouteDependencyResolverTrait` from laravel framework. Now this method is then calling another method `resolveMethodDependencies()` on the same trait which contains the actual logic of resolving the parameters.

Let's assume i'm calling the component like this

```php
@livewire('foo', null, ['mode' => 'planner'])
```

If you check this line https://github.com/laravel/framework/blob/7ca29256b85a910585ab7492d22365c1c5a8e29b/src/Illuminate/Routing/RouteDependencyResolverTrait.php#L53
you will see that the laravel framework is using an `isset()` which of course when used with null it will return false. That line of code in laravel is checking if we have a null parameter and if a default value exists, if so it will add the default value in the parameters list.

So when the laravel method returns at this line (Now we are in livewire land)
https://github.com/livewire/livewire/blob/9f9dc2014cbabdc060795284a033128d2d1ca661/src/LivewireManager.php#L85

the `$parameters` variable will have the following value

```php
[null, null, ['mode' => 'planner']]
```
First null is the null from the original `$options` passed to the laravel `resolveClassMethodDependencies()`

Second null is added by laravel inside the `resolveClassMethodDependencies()` via `resolveMethodDependencies()`

Now in the next line when you mount the component, the mount method will take the two first values and ignore the third since the mount method definition has two arguments.

### More details
Now if you check where is laravel is using the `resolveClassMethodDependencies()` you will see it is used once when dispatching a controller
https://github.com/laravel/framework/blob/7ca29256b85a910585ab7492d22365c1c5a8e29b/src/Illuminate/Routing/ControllerDispatcher.php#L40

Also if you check where laravel is using the `resolveMethodDependencies()` method you will see it's used in 
https://github.com/laravel/framework/blob/7ca29256b85a910585ab7492d22365c1c5a8e29b/src/Illuminate/Routing/Route.php#L204

Both places are passing the first argument which is the equivalent to `$options` in livewire like this `$route->parametersWithoutNulls()`
This is the key thing, every time it's used, laravel is throwing out the null parameters. This does not apply to livewire because any would want to pass null the the first parameter and set a value for the second one like in this issue.

### Possible fix
1- Make a PR to laravel to use `array_key_exists()` instead of `isset()` and then update the places where they are using `$route->parametersWithoutNulls()` and passing the data as it is, which is very unlikely that will be accepted, i don't know why they are even doing it this way !!

2- Override the method `resolveMethodDependencies()` on livewire

3- IMHO the best way to go, copy the trait over from laravel and make the change in there, this will be also good for any future livewire specifics.

Let me know what you want to do

**Comment by calebporzio** [comment]
Yeah, I'm down with option 3. Thanks for such a thorough explanation.
