### ISSUE TITLE
Pass the entire response instead of the statusCode to window.livewire.onError

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#3731]
### Discussed in https://github.com/livewire/livewire/discussions/3730

<div type='discussions-op-text'>

<sup>Originally posted by **lucasromanojf** September 14, 2021</sup>
Hey!

I think that it would be better to pass the entire response to the window.livewire.onError callback instead of the statusCode only. 

The reason is that sometimes a different message is returned from backend for a same status code (e.g.: a JSON response with an error message that varies). So we can't show the correct message since we only have the statusCode.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
