### ISSUE TITLE
wire:loading.remove not reverted in case of request error

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#3732]
### Discussed in https://github.com/livewire/livewire/discussions/3728

<div type='discussions-op-text'>

<sup>Originally posted by **lucasromanojf** September 14, 2021</sup>
Describe the bug
- When a backend error happens, wire:loading.remove is not reverted from the element.

To Reproduce

- Implement the counter example
- Put a wire:loading.remove on + button
- Throw an exception from increment function
- Click the button that throws the exception (+)
- The + button will be hidden, an exception popup will be shown and, after closing it, the + button won't show back, and the user will need reload the page

Expected behavior

- It's expected that wire:loading.remove is reverted not only after request success, but after request errors too

Desktop (please complete the following information):

- OS: Windows 10 64 Bit
- Browser: Opera 78.0.4093.184 (64 bits)</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
