### ISSUE TITLE
UrlGenerationException on route parameter

### ISSUE THREAD

**Issue by afiqiqmal** [livewire/livewire#3747]
### Discussed in https://github.com/livewire/livewire/discussions/3746

<div type='discussions-op-text'>

<sup>Originally posted by **afiqiqmal** September 15, 2021</sup>
Step to reproduce
1 - From `merchant` => Go to page `merchant/1234567`
2 - From page `merchant/1234567` => click route `merchant`

It will throw `UrlGenerationException`

After i did some digging,

```
   protected function buildPathFromRoute($component, $route, $queryString)
    {
        // cause the problem
        $boundParameters = array_merge(
            $route->parametersWithoutNulls(),
            array_intersect_key(
                $component->getPublicPropertiesDefinedBySubClass(),
                array_flip($route->parameterNames())
            )
        );

        return app(UrlGenerator::class)->toRoute($route, $boundParameters + $queryString->toArray(), true);
    }
```

After i swap the position, its working

```
   protected function buildPathFromRoute($component, $route, $queryString)
    {
        $boundParameters = array_merge(
            array_intersect_key(
                $component->getPublicPropertiesDefinedBySubClass(),
                array_flip($route->parameterNames())
            ),
            $route->parametersWithoutNulls(),
        );

        return app(UrlGenerator::class)->toRoute($route, $boundParameters + $queryString->toArray(), true);
    }
```

```$route->parametersWithoutNulls()``` bring the correct value but it been replace by `array_intersect_key` during merge because of the null values
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
