### ISSUE TITLE
Validation rule confirmed bug

### ISSUE THREAD

**Issue by eckelarsson** [livewire/livewire#375]
**Describe the bug**
Just wiped up a simple registration form with password confirmation,
Added the validation rule "confirmed" and have the two fields "password" and "password_confirmation", when running real-time validation it doesn't match those two fields.

Switched to the rule "same:password_confirmation" and that rule works fine.

**Expected behavior**
The confirmed fields should match when validating.

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by stevebauman** [comment]
I just ran into this. You will have to name the public property with an underscore and `wire:model` the `password_confirmation` input:

**View**:
```php
<input wire:model="password" id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autofocus required autocomplete="new-password">

<input wire:model="password_confirmation" id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
```

**Component**:
```php
class ResetPasswordModal extends Component
{
    public $password;
    public $password_confirmation;

    public function save()
    {
        $validated = $this->validate([
            'password' => 'required|confirmed',
        ]);
    }

    public function render()
    {
        return view('livewire.reset-password-modal');
    }
}
```

Though I think the docs should explain the naming conventions to be used for the `model` attributes (such as using a hyphen / underscore), I'm still not really sure how Livewire handles these scenarios.

**Comment by DanHarrin** [comment]
Hi, looks like @stevebauman has addressed your issue well. If you would like to continue your discussion about possible improvements to make this better, please open a new [Discussion](https://github.com/livewire/livewire/discussions). Thank you!

**Comment by ghunti** [comment]
Hi all. Sorry to comment on a closed issue, but I think this might be relevant as I had the same problem as @eckelarsson . His issue was with `validateOnly` if I'm not mistaken and not with `validate` method.
I was having the same issue and found out that the "problem" is that you probably have something linke this in your blade template:
