### ISSUE TITLE
Cannot read property 'receiveMessage' of undefined

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#376]
Hey, finally had some time again to jump back into Livewire but ran into an odd issue with forms. Seems to happen in old applications and also a completely fresh Laravel installation.

```js
VM79 livewire.js:3287 Uncaught (in promise) TypeError: Cannot read property 'receiveMessage' of undefined
    at Connection.onMessage (VM79 livewire.js:3287)
    at Object.Connection.driver.onMessage (VM79 livewire.js:3271)
    at VM79 livewire.js:3142
```

```js
_Store__WEBPACK_IMPORTED_MODULE_1__["default"].findComponent(payload.id).receiveMessage(payload);
```

When placing some console logs the issue becomes more clear.

```json
{"componentsById":{},"listeners":{"listeners":[]},"livewireIsInBackground":false,"livewireIsOffline":false,"hooks":{"availableHooks":["componentInitialized","elementInitialized","elementRemoved","messageSent","messageFailed","responseReceived"],"bus":{"listeners":[]}}}
```

The `componentsById` property is empty so `findComponent` returns undefined. The questions is why it is undefined.

To rule out any issues with packages or middlewares I made sure to use a fresh Laravel installation just with Livewire but the same issue persists. I even tried to use the copy & paste contact form component from https://laravel-livewire.com/docs/input-validation/ but again the same issue.

P. S.: @calebporzio did you manage to setup GitHub Sponsors or alike.

**Comment by faustbrian** [comment]
Did some testing with the example from the docs and the issue seems to only occur when a form is using `wire:submit`.

If I place a button outside the form with `wire:click` it will call the method, the `$errors` variable is no longer empty, all errors are shown and the component is working as intended.

```blade
<div>
    {{-- This button works. --}}
    <button type="button" wire:click="submit">Save Contact</button>

    {{-- Submitting this form does not work. --}}
    <form wire:submit="submit">
        {{ $errors }}

        <input type="text" wire:model="name">

        @error('name')
            <span class="error">{{ $message }}</span>
        @enderror

        <input type="text" wire:model="email">

        @error('email')
            <span class="error">{{ $message }}</span>
        @enderror

        <button type="submit">Save Contact</button>
    </form>
</div>

```

**Comment by calebporzio** [comment]
@faustbrian - is this resolved? Why did you close it?

Also, no... not yet. Thanks for checking in though!
