### ISSUE TITLE
Issue with the last update

### ISSUE THREAD

**Issue by laraben** [livewire/livewire#3761]
### Discussed in https://github.com/livewire/livewire/discussions/3760

<div type='discussions-op-text'>

<sup>Originally posted by **laraben** September 15, 2021</sup>
Hi,

today i ran in some issue because of the update.

My app was working fine until i've updated livewire from 2.5 to 2.6

I couldn't find what was the issue for this so i've reverted the update and downgraded back to 2.5

Can someone tell me what could be the cause of this error?

<img width="725" alt="Schermafbeelding 2021-09-15 om 11 07 17" src="https://user-images.githubusercontent.com/34068668/133494772-f6fc69fa-0017-49a8-8702-43c3bedc7cfd.png">
<img width="766" alt="Schermafbeelding 2021-09-15 om 13 58 25" src="https://user-images.githubusercontent.com/34068668/133494735-6fdf5f9a-d104-4e8b-b673-74a8ad8a2686.png">

</div>

**Comment by richardkeep** [comment]
Did you try clearing cached views?

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
