### ISSUE TITLE
wire:ignore does not work with <x-slot> tags

### ISSUE THREAD

**Issue by victorelec14** [livewire/livewire#3784]
### Discussed in https://github.com/livewire/livewire/discussions/3783

<div type='discussions-op-text'>

<sup>Originally posted by **victorelec14** September 17, 2021</sup>
Hi,

I'm not sure if it's normal, but "wire:ignore" doesn't work with "x-slot" tags and gives me an exception.

If you put a "div" inside the "x-slot" tag it will work normal.

> <x-slot name="body" wire:ignore >

> 
> InvalidArgumentException
> Unable to locate a class or view for component [slot].

Thanks!
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
