### ISSUE TITLE
Allow components in any location

### ISSUE THREAD

**Issue by gjm** [livewire/livewire#379]
**Is your feature request related to a problem? Please describe.**
Right now all Livewire compoments must reside under `App\Livewire` (or some other root namespace). My has namespaces according do DDD domains and I would like to place related components under the correct namespace.

**Describe the solution you'd like**
It would be great if we can somehow register components in arbitrary locations:
```
Livewire::register('invoice', App\Admin\Components\Invoice::class);
Livewire::register('cart', App\Frontend\Components\ShoppingCart::class);
...
```

**Comment by harrysbaraini** [comment]
https://github.com/livewire/livewire/issues/306#issuecomment-537166211

**Comment by calebporzio** [comment]
Thanks @harrysbaraini, I believe you are correct. Here would be the way to do what you want to do:

```php
Livewire::component('invoice', App\Admin\Components\Invoice::class);
```

Closing for now. This should probably be documented if anyone cares to give it a go!
