### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by gjm** [livewire/livewire#380]
**Is your feature request related to a problem? Please describe.**
The only way to have dependencies inside components right now is to `new` tem up directly ou resolve them of the container. 

If I want to follow the dependency injection approach to get required dependencies I can't do it with Livewire..

**Describe the solution you'd like**
My suggestion is to be able to inject in the `mount` method wrapping it in the `call` method of the container. That way, when the component is initialized we could get the required dependencies. Maybe even extend this approach to all lifecycle methods...

**Comment by calebporzio** [comment]
Yeah, this has been requested before @gjm, but I actually thought it was implemented for the `mount` method, is this not the case?

**Comment by gjm** [comment]
@calebporzio Yes it actually is.

The problem it that `boot` gets called only once, when the component is initialized. If I use it to inject dependencies into my component I run into problems with some dependencies when the component gets serialized between calls to component actions, state updates, etc.

Is there a recommended way of doing DI in Livewire components? Is there some extra step I need to take to make the boot method DI work? Maybe tap into `hydrate`/`dehydrate` methods? Should I explicitly resolve out of the container?

**Comment by faustbrian** [comment]
@gjm would you have a specific example that could be used for reproduction of the issue to solve it?

**Comment by gjm** [comment]
@faustbrian since I've upgraded to PHP 7.4 the error changes but the problem persists. Lets say we have this simple (and fake) component:

```php
use Livewire\Component;
use Psr\Log\LoggerInterface;

class Foo extends Component
{
    protected LoggerInterface $logger;

    public function mount(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function render()
    {
        $this->logger->info('component rendered');
        return view('livewire.foo');
    }

    public function action()
    {
        $this->logger->info('action triggered');
    }
}
```

```html
<div>
    ...
    <button type="button" wire:click="action">
</div>
```

When the page renders, the log message is correctly shown but when the button is clicked I get:
```
Typed property App\Foo::$logger must not be accessed before initialization
```

The way I see it, the `LoggerInterface` instance is assigned on `mount` and called on `render` but after the ajax call the instance is no longer available.

Hope this helps.

**Comment by faustbrian** [comment]
This seems to be a quick and dirty fix but introduces other problems https://github.com/livewire/livewire/compare/master...faustbrian:patch-1. I am thinking how this could be best solved without adding too much overhead or ideally persisting the container resolutions.

For now your best bet is probably to do something like below with computed properties.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Psr\Log\LoggerInterface;

class Foo extends Component
{
    public function render()
    {
        $this->logger->info('component rendered');

        return view('livewire.foo');
    }

    public function action(): void
    {
        $this->logger->info('action triggered');
    }

    public function getLoggerProperty(): LoggerInterface
    {
        return resolve(LoggerInterface::class);
    }
}
```

@calebporzio are protected properties already persisted somewhere and I am overlooking that or would we need something like below code to initialise protected properties that are injected?

```php
<?php

namespace Livewire\ComponentConcerns;

trait HandlesActions
{
    // ...

    public function callMethod($method, $params = [])
    {
		$this->resolveProtectedMountPropertiesThatCanBeResolved();

		$this->{$method}(...$this->resolveActionParameters($method, $params));
    }

    protected function resolveProtectedMountPropertiesThatCanBeResolved()
    {
        $protectedClassProperties = collect(
            (new \ReflectionClass($this))->getProperties(\ReflectionProperty::IS_PROTECTED)
        )->pluck('name')->toArray();

        return collect((new \ReflectionMethod($this, 'mount'))->getParameters())
            ->mapWithKeys(function ($parameter) {
                $class = $parameter->getClass();

                return $class ? [$parameter->name => $parameter->getClass()->name] : [];
            })
            ->reject(function ($value, $key) use ($protectedClassProperties) {
                return !\in_array($key, $protectedClassProperties);
            })
            ->each(function ($class, $key) {
                $property = (new \ReflectionClass($this))->getProperty($key);
                $property->setAccessible(true);
                $property->setValue($this, app($class));
                $property->setAccessible(false);
            });
    }

    // ...
}
```

**Comment by nikolaystrikhar** [comment]
It would be great to be able to use DI!

**Comment by calebporzio** [comment]
You can use DI in the `mount` method and any action methods. Therefore, you can just inject the logger in the actions.

**Comment by bremg** [comment]
Why is this closed? DI is not working for me

**Comment by kolaente** [comment]
Just to bump this issue, the problem @gjm described is still an issue with the latest livewire version (2.5). @calebporzio How is this supposed to work? I can use `DI` in the `mount` function but not elsewhere?

**Comment by calebporzio** [comment]
are you positive you still can't? I thought you could - mind PRing a failing test?

**Comment by joshhanley** [comment]
@kolaente (and also @bremg) what method are you trying to use DI on?

As Caleb previously suggested, it works on `mount` and any action methods, which works for me.

What is meant by an action method, is if you say have a button with `wire:click="save"`, then `save` is the action method, so you should be able to use DI on the `save` method in your component class.

But that will only work when the action is called from Livewire's front end. If you manually call save in you code like `$this->save()` then you will need to pass the properties into the method yourself.

Hope this helps!

**Comment by kolaente** [comment]
@calebporzio @joshhanley I've been trying to do this:

```php
<?php

namespace App\Http\Livewire;

use App\SomeDependency;
use Livewire\Component;

class Foo extends Component
{
    private SomeDependency $dependency;
    public $value;

    public function mount(SomeDependency $dependency)
    {
        $this->dependency = $dependency;
    }

    public function bar()
    {
        $this->value = $this->dependency->whoop();
    }

    public function render()
    {
        return view('livewire.foo');
    }
}
```

```blade
<div>
    <button wire:click="bar">
        Click me!
    </button>

    Value: {{ $value }}
</div>
```

When I click the button, I get this:
![image](https://user-images.githubusercontent.com/13721712/129520211-d26023e0-c8ac-4e28-bd44-d918fa45d0b4.png)
https://flareapp.io/share/x5MqZGe5

Repo: https://github.com/kolaente/livewire-di-reproduction

I've just now realized you can use dependency injection on an action but not the way I tried to do it. I guess I'm too much used to injecting dependencies in the constructor of a class and then using it from there through class properties. 
I guess this is all working fine - sorry for the noise!

**Comment by joshhanley** [comment]
@kolaente no worries, glad you got it sorted 🙂

The reason loading it only into mount won't work is, mount is only called on the initial request. So when the request is finished, the component is deconstructed (as PHP doesn't have long running processes).

When a new request (action) is fired, it's fired from the front end, when the backend receives the request, a new instance of the component is created, but mount doesn't get run again, which is why the dependency is no longer in the protected property.

Hence to get around that you can use DI on the action methods, to access the dependancy when you need it.

Hope that makes sense!

**Comment by kolaente** [comment]
@joshhanley Makes sense, thanks for the explanation!

**Comment by joshhanley** [comment]
No worries! 🙂

**Comment by davide-casiraghi** [comment]
To me, it's not clear.
I would be grateful if somebody posts an example.

**Comment by joshhanley** [comment]
@davide-casiraghi which part isn't clear?

**Comment by davide-casiraghi** [comment]
Hi @joshhanley
I tried again and I managed. Thanks.

**Comment by Yszty** [comment]
What with 
![image](https://user-images.githubusercontent.com/23386525/178541541-3cef07b5-904c-4b22-ab85-b706f8f1a77c.png)
Working well.
