### ISSUE TITLE
please Solve problem Undefined array key "id"

### ISSUE THREAD

**Issue by saeedalaloul** [livewire/livewire#3800]
### Discussed in https://github.com/livewire/livewire/discussions/3799

<div type='discussions-op-text'>

<sup>Originally posted by **saeedalaloul** September 18, 2021</sup>
![Capture](https://user-images.githubusercontent.com/42633968/133888110-2c899085-84db-47ea-9b8d-65ba3e59b655.PNG)</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
