### ISSUE TITLE
Testing with prop $name conflict with Livewire\Testing\TestableLivewire name prop

### ISSUE THREAD

**Issue by eckelarsson** [livewire/livewire#381]
**Describe the bug**
```
$form = Livewire::test(MyForm::class);
$form->set('name', 'testing name');

$this->assertEquals('testing name', $form->name);
```

**Unit test output**
```
1) Tests\Feature\Form::livewire_form_test
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'testing name'
+'dS6VqTPZ2ngRNl4hFQUn'
```

```
Livewire\Testing\TestableLivewire^ {#326
  +name: "dS6VqTPZ2ngRNl4hFQUn" <--- This is the prop that will be tested.
  +id: "ByH0BEbqSa0muQ4uz1u5"
  +children: []
  +checksum: "11226a9b30ff8ec90f5558be00f878a8c634616c0ca84ddd5d0c7ad8bba22319"
  +prefix: "wire"
 
```

**Expected behavior**
It should collect the name prop from the data object of Livewire\Testing\TestableLivewire

```
Livewire\Testing\TestableLivewire^ {#326
+data: array:4 [
    "name" => "testing name"
  ]

```

**Comment by eckelarsson** [comment]
Forgot to write that you can ofc use the  $form->get('name') to collect from the data array, bu.. it's a common prop "name", so I think it will be beneficial to not have this conflict.

**Comment by calebporzio** [comment]
Yeah, I agree. `$name` is common enough, we should avoid it.

I actually think we moved to a strategy that doesn't use a property (the $this->getName() method).

But clearly there is still something using it. Do you feel capable of digging in a little and PRing this?

I'm happy to jump on a Zoom call to help you.

**Comment by faustbrian** [comment]
This seems to be only testing related because Livewire will assign `Str::random(20)` as a component name when tests are run.

**Comment by eckelarsson** [comment]
Sorry for the late answer @calebporzio, and thanks for the support on helping to try to do it. Seams that @faustbrian found a nifty solution for this, great job!

**Comment by calebporzio** [comment]
Ah yes, the solution here is:

`$component->assertSet('name', 'testing-name')` rather than calling `$component->name` and `$this->assertEquals`.

**Comment by calebporzio** [comment]
Also, I merged that PR, so either will work.
