### ISSUE TITLE
Livewire does not work on Vapor environments

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#382]
**Describe the bug**

*First issue:*

Livewire throws an error when used on Vapor environments. The error details can be seen here:

https://flareapp.io/share/KPgnkJma#F63

This happens because Livewire's manifest path points to "<app_root>/bootstrap/cache/livewire-components.php" but Vapor uses "/tmp/storage/bootstrap/cache".

*Second issue:*

Vapor assets are uploaded to S3 and served using Cloudfront. If I set "asset_url" Livewire config, the assets are loaded successfuly, but they start to use the same Cloudfront URL to call the "message" Livewire endpoints. On Vapor, the assets URL and the app URL will not be the same.

**To Reproduce**

Just upload an app using Livewire features to Vapor and the issues will happen.

**Expected behavior**

Having a "manifest_path" config prop inside "livewire.php" config file (which has the default but we can change) would solve *first issue* above quickly, but I'm not sure if this is the best solution.

A possible solution for the *second issue* above is having, in addition of the "asset_url" config, a "api_url" or "app_url" or something, which would allow loading assets from the "asset_url" but calling Livewire endpoints from "api_url" or "app_url".

**Comment by calebporzio** [comment]
Thanks for reporting this.

Do you feal capable of PRing fixes for this? It would be a big help.

**Comment by lucasromanojf** [comment]
Hey Caleb, sure, if my suggestions are OK, I can do them and submit a PR.

**Comment by lucasromanojf** [comment]
Issue solved through PR #385
