### ISSUE TITLE
Target class [view.engine.resolver] does not exist.

### ISSUE THREAD

**Issue by Namoshek** [livewire/livewire#384]
**Describe the bug**
When installing Livewire, the `php artisan package:discover` post-dump composer task fails with the error message:
> In Container.php line 806:
> Target class [view.engine.resolver] does not exist.

**To Reproduce**
Install Livewire with `composer require livewire/livewire`.

**Expected behavior**
The installation is successful.

**Additional context**
It is possible that this behavior has to do with me using a custom `ViewServiceProvider` which extends the default one. It is registered as last service provider in `config/app.php` (due to the alphabetical order).

The issue is most likely that the `LivewireServiceProvider` attempts to resolve another service from the container within the `register()` method, which is not allowed:

https://github.com/livewire/livewire/blob/5b3eecd6715172700f90e358e22d89b7744674fe/src/LivewireServiceProvider.php#L50-L61

`allowCertainExceptionsToBypassTheBladeViewHandler()` accesses said `view.engine.resolver`.

As I'm not too familiar with Livewire yet, I don't want to send a PR for something I don't know the consequences of.

**Workaround**
- Disabling auto-discovery of the `livewire/livewire` package using the `extra.laravel.dont-discover` property in `composer.json`.
- Registering `Livewire\LivewireServiceProvider::class` manually in `config/app.php`.

**Comment by calebporzio** [comment]
Yeah, I think you understand the problem exactly. Also, thanks for providing the work-around.

I'd love to hear your thoughts on a solution, and would welcome a PR!

**Comment by Namoshek** [comment]
As long as the service (or the custom blade compiler) which is being registered there is not used within the `boot()` method, there shouldn't be an issue when moving the method call to `allowCertainExceptionsToBypassTheBladeViewHandler()` into the `boot()` method. I did so locally and had no issue on a fresh installation, but that doesn't have to say anything. But as said, one shouldn't (have to) resolve services from the container in the `register()` method as it isn't guaranteed to work and also is a design flaw, so I don't see another solution anyway. 👍

**Comment by shadoWalker89** [comment]
I touched upon that in my comment in this PR I made https://github.com/livewire/livewire/pull/364 and in the PR I'm already adding the override necessary in the boot method, like I said in the comment if my PR is merged it's better to move the logic in the register method to the new CompilerEngine added by the PR.

**Comment by shadoWalker89** [comment]
caleb moved that code to the compiler engine class, if possible, can you check that your problem was resolved ?

**Comment by Namoshek** [comment]
Looks resolved to me:
```
root@77e55ec2d429:/var/www# composer require livewire/livewire
Using version ^0.5.0 for livewire/livewire
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing livewire/livewire (v0.5.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
[... packages removed for brevity ...]
Discovered Package: livewire/livewire
[... packages removed for brevity ...]
Package manifest generated successfully.
```

Thanks for handling it!

**Comment by calebporzio** [comment]
Great. np!

**Comment by faustbrian** [comment]
@Namoshek this can probably be closed?
