### ISSUE TITLE
Testing issue after upgrade

### ISSUE THREAD

**Issue by tabuna** [livewire/livewire#3842]
### Discussed in https://github.com/livewire/livewire/discussions/3841

<div type='discussions-op-text'>

<sup>Originally posted by **tabuna** September 22, 2021</sup>
I used version `2.6.3` And wrote the following tests:

```php
// ...
Livewire::test(Information::class)
        ->set('user.timezone', 'Europe/Gibraltar')
        ->call('send')
// ...
```

This test should check that the user could change some of his data through the component:

```php
class Information extends Component
{
    /** @var User */
    public User $user;

    /**
     * @return void
     */
    public function mount(Request $request)
    {
        $this->fill(['user' => $request->user()]);
    }

    /**
     * @param Request $request
     *
     * @return void
     */
    public function send(Request $request)
    {
        $request->user()
            ->fill($this->validate()['user'])
            ->save();
    }
}
```

I just wrote the property through the dot notation and checked if the model was updated (Some things were skipped on purpose). But as of version `2.6.4`, this code no longer works. That is, I cannot assign property in tests.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
