### ISSUE TITLE
Weglot Integration

### ISSUE THREAD

**Issue by dylanmichaelryan** [livewire/livewire#386]
**Describe the bug**
I was trying to include weglot (https://weglot.com) to my livewire project and ran into some issues

**To Reproduce**
1. Include weglot
2. Make for example a table where you can filter and paginate

**Expected behavior**
everything should be translated but instead if i paginate to the second page the text loaded through livewire isnt translated anymore

idk how complex this would be, but i think it would be great if this would work in the future

**Comment by dylanmichaelryan** [comment]
Actually i something is rerenderd the texts aren't translated anymore, so for example if i set a filter in my table and the whole things rerenders, the text wont be translated anymore

**Comment by calebporzio** [comment]
Hey @dylanmichaelryan, this makes sense if Weglot has no built-in way to detect DOM changes and keep things translated. If there is an API for this, you can use the following Livewire hook to run a sort of "refresh" on Weglot:

```
window.livewire.afterDomUpdate(() => {
    // Some code that tells Weglot to update itself after a DOM change
})
```

Going to close this for now. If you get something working, please follow up with the solution here.

Thanks!
