### ISSUE TITLE
Linked loading states on long running scripts. Multiple vs. single components

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#387]
I am unsure if this is a bug, a limitation within system, or something I have missed...

Below I have 2 ways of inserting 3 counters onto a page. In each case, there is a 1 second sleep on the increment function to simulate a long running script.

You can see from the animations that when we add multiple counters to the page in the same component there is a significant lag on the 3rd counter showing its loading `text-danger` class. 

When creating a single counter component and duplicating the component it is much smoother.

It is simple in this example to just use the multiple component method, but this may not always be the case. For example, what about a button that triggers a long running process in every row of a table?

Maybe this behaviour expected and separate components always the answer? 

Making additional nested components for things such as buttons does add complexity to something that is otherwise a very simple feature to implement with this package, so I just want to make sure I have not missed anything.

## Multiple buttons per component

![Kapture 2019-12-01 at 23 27 08](https://user-images.githubusercontent.com/20134485/69922196-1a76de80-1492-11ea-9788-ce04db7b69dc.gif)

```php
<div>
    @livewire('counter', key('counter1'))
</div>
```

```html
<div>
    <div style="text-align: center" class="d-inline-block p-5">
        <button wire:click="increment('a')" wire:ref="button-a">
            +
        </button>
        <h1 wire:loading.class="text-danger" wire:target="button-a">
            {{ $count['a'] ?? 0 }}
        </h1>
    </div>

    <div style="text-align: center" class="d-inline-block p-5">
        <button wire:click="increment('b')" wire:ref="button-b">
            +
        </button>
        <h1 wire:loading.class="text-danger" wire:target="button-b">
            {{ $count['b'] ?? 0 }}
        </h1>
    </div>

    <div style="text-align: center" class="d-inline-block p-5">
        <button wire:click="increment('c')" wire:ref="button-c">
            +
        </button>
        <h1 wire:loading.class="text-danger" wire:target="button-c">
            {{ $count['c'] ?? 0 }}
        </h1>
    </div>
</div>
```

## One button per component

![Kapture 2019-12-01 at 23 28 31](https://user-images.githubusercontent.com/20134485/69922228-717cb380-1492-11ea-9e80-7ebe819c8674.gif)

```php
<div>
    @livewire('counter', key('counter1'))
    @livewire('counter', key('counter2'))
    @livewire('counter', key('counter3'))
</div>
```

```html
<div style="text-align: center" class="d-inline-block p-5">
    <button wire:click="increment">+</button>
    <h1 >{{ $count }}</h1>
    <button wire:click="decrement">-</button>
</div>
```

**Comment by calebporzio** [comment]
Yes, this actually makes sense, and I think this is a side effect of the way livewire fundamentally works.

Component's update their data and perform logic on the server side. Ther can only be ONE request at any given time so there are no collisions are state management issues or anything. What you are hoping for is a single component that knows how to handle multiple updates in parralel.

You are right though, to achieve this, you will need multiple components. It's actually kind of a feature that each component is completely isolated and communicate with events so things like this are possible and the user has fine control over what functionality to group or isolate.

I know that's a lot of Livewire high level talk, and probably confusing. Feel free to ask me to expound on any given principle.

Until then, closing this for now and saying the solution is: seperate to multiple components when you need parrallel updates.

Thanks for such a well-formed issue!

**Comment by booni3** [comment]
@calebporzio Thanks for the update. That all makes sense. I expected as much it was a side effect of the system but just wanted to make sure.

Thanks for all your hard work on this!
