### ISSUE TITLE
 Livewire\Exceptions\ComponentNotFoundException

### ISSUE THREAD

**Issue by bedus-creation** [livewire/livewire#389]
I tried to change the default components directory, It couldn't resolve the components.

**To Reproduce**
1. Change the config
``` 
'class_namespace' => 'App\\Domain',
```
2. This is my components class
App\Domain\Settings\Components\PostIndex
3. 
```
Route::group(['namespace' => 'Settings/Components'], function () {
    Route::livewire('/home', 'PostIndex');
});
```
4. It says Components not found

**Comment by bedus-creation** [comment]
Same problem with view_path components
**To Reproduce**
1. change the default view_path
```
'view_path' => resource_path('views'),
```
2. I have livewire components in this directory 
```
views/settings/samanKoKisim/components/index
```
3. And I couldn't access
```
@livewire('settings.samanKoKisim.components.index')
```

**Comment by HenkMaller** [comment]
Did you run the `livewire:discover` command?

**Comment by faustbrian** [comment]
@bedus-creation as @HenkMaller said you'll need to run `php artisan livewire:discover` if you ever change the name or location of your components or views.

**Comment by faustbrian** [comment]
Should be safe to be closed after https://github.com/livewire/livewire/pull/429 @calebporzio @lancepioch
