### ISSUE TITLE
Error with CSP and livewireScripts

### ISSUE THREAD

**Issue by olezhkafp** [livewire/livewire#3895]
### Discussed in https://github.com/livewire/livewire/discussions/3894

<div type='discussions-op-text'>

<sup>Originally posted by **olezhkafp** September 28, 2021</sup>
Hi. I already read all closed issues related to this one, but looks like this is new error happned there.
I use https://github.com/spatie/laravel-csp package.
I've installed livewire and include it in blade using this code:

`<?php $nonce = ["nonce" => csp_nonce()] ?>`
`@livewireScripts($nonce)`

or in this way:

`@livewireScripts(['nonce' => csp_nonce()])`

if I just render `$nonce` variable - I see it in HTML:
`<div>{{print_r($nonce, true)}}</div>`

but, livewire scripts does not render it - there is just empty strings

![U85RN9IURLirUBVHXDO6Xw](https://user-images.githubusercontent.com/11082011/135074730-604c887a-a377-402f-89b0-653ae05d16b1.png)

PHP: 7.4.11
livewire verison: v2.6.7
laravel: v8.61.0
OS: windows 10

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
