### ISSUE TITLE
Add global helper function for Livewire components

### ISSUE THREAD

**Issue by panda-madness** [livewire/livewire#391]
**Is your feature request related to a problem? Please describe.**
Currently you need to use the `@livewire` blade directive to output components. Since it's a custom directive it is basically treated as a string in any IDE, and thus you don't get any help when you're working with real PHP variables.

**Describe the solution you'd like**
A simple global helper function which does the same thing as `@livewire` could be implemented to help with this issue. Usage could be something along the lines of:

```
...
{!! livewire('component-name', [$arg1, $arg2], $key) !!}
...
```

**Comment by calebporzio** [comment]
That's a good idea.

Unfortunately, it kind of has to be a blade directive, for specific reasons: the directive needs access to the variables inside the current  view's scope.

If you care to understand more, take a look at the `livewire()` method in this class: `src/LivewireBladeDirectives.php`

**Comment by mokhosh** [comment]
> Since it's a custom directive it is basically treated as a string in any IDE, and thus you don't get any help when you're working with real PHP variables.

Actually if you use phpstorm, you can define new blade directives and tell phpstorm exactly what kind of expressions will go inside the parentheses. Other ide's and text editors probably have similar options as well, almost everything is hackable if not configurable these days.

**Comment by calebporzio** [comment]
Good tip!

**Comment by anyb1s** [comment]
@mokhosh how do you set up your directive for Livewire?

I did it with a prefix `<?php \Livewire\Livewire::mount(`

**Comment by mokhosh** [comment]
Sounds about right.

**Comment by Algeneralo** [comment]
@anyb1s @mokhosh any help for how to support `@livewire` tag in phpStorm to use ide autocomplete and so on?

**Comment by anyb1s** [comment]
Hi @Algeneralo , this is how I use it.
![Screenshot 2020-06-01 at 16 28 17](https://user-images.githubusercontent.com/788796/83413715-000fc480-a425-11ea-8501-a8fb7ed488c8.png)

**Comment by anyb1s** [comment]
But now that blade components exist... I go with `<livewire:component-name/>`

**Comment by Algeneralo** [comment]
> Hi @Algeneralo , this is how I use it.
> ![Screenshot 2020-06-01 at 16 28 17](https://user-images.githubusercontent.com/788796/83413715-000fc480-a425-11ea-8501-a8fb7ed488c8.png)

I already did that, but the issue is that autocomplete is not working, it doesn't give me the list of available views
