### ISSUE TITLE
Use $emit outside a Livewire component

### ISSUE THREAD

**Issue by depsimon** [livewire/livewire#392]
**Describe the bug**

Here's my layout file.

```php
<body>
    <button onclick="window.livewire.emit('showGlobalDrawer')">Open</button>
    <button wire:click="$emit('showGlobalDrawer')">Open</button>

    @livewire('global-drawer')
</body> 
````

When I click on the first button, it does trigger the event.
When I click on the second button, it does not.

However, if I were to move the second button to a Livewire component, the event is triggered.

Is it not possible to use `$emit` outside of a Livewire component?

**Additional context**
Using `"livewire/livewire": "^0.4.0`

**Comment by calebporzio** [comment]
Hi @depsimon - that's correct. Livewire directives only work inside Livewire components. This way Livewire doesn't take over your entire front-end (only as much as you want it to).

Your `onclick=""` approach would be the best way, and should work just fine.
