### ISSUE TITLE
`render` via listeners results in NonPublicComponentMethodCall

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#393]
Prior to 0.5.0 it was possible to omit the `render` method from a component and use it for a listener. After 0.5.0 the `render` method has to be defined, which is somewhat inconvenient if you're not doing anything with the view other than rendering it.

**Before**
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SomeComponent extends Component
{
    protected $listeners = [
        'refreshSomething' => 'render',
    ];
}

```

**After**
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SomeComponent extends Component
{
    protected $listeners = [
        'refreshSomething' => 'render',
    ];

    public function render()
    {
        return view('livewire.some-component');
    }
}

```

@calebporzio is this a regression and could be caused by components now being macroable or is this an intended breaking change that went unnoticed?

**Comment by calebporzio** [comment]
Interresting, that surprises me that it worked before. Will investigate. Thanks for the clear example.

**Comment by calebporzio** [comment]
Long shot, but by any chance to you want to hop on a zoom call to screenshare and figure it out? If so, email me @ calebporzio@gmail.com or twitter DM me

**Comment by calebporzio** [comment]
I just put my local down to 0.4.0 and am getting that same error you are describing.

Like I suspected, calling "render" from a listener without a render function defined on the model itself didn't work even before this new release.

The recommended way to acheive what you want would be:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SomeComponent extends Component
{
    protected $listeners = [
        'refreshSomething' => '$refresh',
    ];
}
```

I confirmed that the above works without a render function.

If you don't like the different syntax, and would rather use `render` (which is valid reasoning), then I'd be open to a PR to support it.

Closing this for now, thanks @faustbrian!

**Comment by faustbrian** [comment]
I'll have a look next week and submit a PR when I get a chance :+1:

Do you think adding a note about how to rerender other components via events to the docs would be a good thing? Seems like a common use-case.

**Comment by booni3** [comment]
Interested in this... I am wondering if I have a similar issue here or if my implementation is wrong?

```php
use Livewire\Component;

class ThCell extends Component
{
    public $sortDir;

    protected $listeners = ['sort' => 'sort'];

    public function render()
    {
        return view('livewire.th-cell');
    }

    public function sorted($dir)
    {
         $this->sortDir = $dir;
         $this->render();
    }
}
```

Blade emitting event
```html
<th wire:click="$emit('sort', 'asc')">
    {{ $sortDir }}
</th>
```

inside parent component
```html
<table class="table table-striped">
    <thead class="text-primary">
    <tr>
        @livewire('th-cell')
    </tr>
    </thead>
...
```

I understand that child components are not reactive, but thought then when events were used then they would update. I can see the render method being fired but the DOM is not updated.

This issue seems to suggest that calling the render() method or the "$refresh" hook should do the job? I have tried both.
