### ISSUE TITLE
File upload always required

### ISSUE THREAD

**Issue by dfe-dev** [livewire/livewire#3948]
I have a Livewire component to perform basic CRUD operations, including the upload of a pdf file. create() and update() methods use the same form via a pop-up modal.

Uploading the file works fine. However, if I update the dataset without changing the file, the validation always fails, stating that the field must be a file. This means that the file upload is always required in order to pass validation.

**Comment by FaridAghili** [comment]
It's not Livewire related.

Use different validation rules for create and update, and make image validation nullable on update method. Then check for existence of the file and update in case of new file.

**Comment by dfe-dev** [comment]
You are right, Farid. 
Used the "nullable" validation, and now it works fine.
Thanks.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
