### ISSUE TITLE
SupportBrowserHistory.php rewrites component's public variables

### ISSUE THREAD

**Issue by almazdanilov** [livewire/livewire#3979]
Livewire v2.6.7
Laravel v8.62.0

Should public variables of component be rewritten by query string parameters?
As I understood the documentation of Livewire on https://laravel-livewire.com/docs/2.x/query-string
to achieve such abillity, we have to add to livewire component:
`protected $queryString = ['queryParamName'];`
But Features/SupportBrowserHistory.php rewrites component's public variable, if same parameter name written in query.

**/catalog?vendor=1**
```
class Catalog extends Component
{
    public $vendor = '';
    public function mount() {
        dd($vendor);
    }
}
```
This code returns 1.

SupportBrowserHistory.php, 39'th line of code does this.
`$component->$property = $decoded === null ? $fromQueryString : $decoded;`

Maybe I misunderstood something, and this behaviour is normal?

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
