### ISSUE TITLE
A way to update the url

### ISSUE THREAD

**Issue by matsava** [livewire/livewire#399]
**Is your feature request related to a problem? Please describe.**
I am building a dummy eshop to play with Livewire. 

The category page has some filters which I hope I can sync to the url. When visiting a category (e.g. `/category/phones?manufacturer=Apple`) the "Apple" manufacturer will be selected automatically.

This is handled by my code inside the `mount` method. 

What I actually want to do is update the url when the user selects another manufacturer. Therefore clicking on "Samsung" will basically trigger a url update. 

**Describe the solution you'd like**
Add a url() method on the component which will allow the developer to return the new url to be pushed to history by Livewire JS.

**Comment by chrypro** [comment]
For now I just did the following:

Emit an event that the url should change based on your conditions.
```
//SomeComponent.php
$this->emit('urlChange', 'https://ppissis.local/el/category/mobile-phones?test');
```
Listen for the event.
```
//some-component.blade.php
@push('footer-scripts')
    <script type="text/javascript">
        document.addEventListener('livewire:available', function () {
            window.livewire.on('urlChange', param => {
                history.pushState(null, null, param);
            })
        })
    </script>
@endpush
```

Feel free to close this feature request @calebporzio if there is no plan on adding it to the core.

**Comment by chrypro** [comment]
For now I just did the following:

Emit an event that the url should change based on your conditions.
```
//SomeComponent.php
$this->emit('urlChange', 'https://someurl.local/category/somecategory?test');
```
Listen for the event.
```
//some-component.blade.php
@push('footer-scripts')
    <script type="text/javascript">
        document.addEventListener('livewire:available', function () {
            window.livewire.on('urlChange', param => {
                history.pushState(null, null, param);
            })
        })
    </script>
@endpush
```

Feel free to close this feature request @calebporzio if there is no plan on adding it to the core.

**Comment by calebporzio** [comment]
Love it, there should be an api for this

**Comment by leMaur** [comment]
This is my solution!

In the Livewire Component:
```php
/** LivewireComponent.php */
public function updating($name, $value)
{
  $this->emit('urlChanged', http_build_query([$name => $value]));
}
```

In the blade file:
```php
/** view.blade.php */
<div>
  ...
</div>

@push('body_script') // this section name can be whatever you want...
  <script type="text/javascript">

    // waiting for DOM loaded
    document.addEventListener('DOMContentLoaded', function () {

      // listen for the event
      window.livewire.on('urlChanged', param => {

        // pushing on the history by passing the current url with the param appended
        history.pushState(null, null, `${document.location.pathname}?${param}`);
      });
    });
  </script>
@endpush
```

**Comment by calebporzio** [comment]
Nice @leMaur, so there's actually an API for this: https://laravel-livewire.com/docs/state-management/#update-query-string

**Comment by amir9480** [comment]
@calebporzio Hello. please check the link. It does not exist.

**Comment by matsava** [comment]
Just search on the docs man https://laravel-livewire.com/docs/properties#update-query-string

**Comment by matsava** [comment]
@amir9480 https://laravel-livewire.com/docs/properties#update-query-string

**Comment by pedzed** [comment]
What about non-query strings? That's not built-in, is it?

E.g. https://example.com/articles/10 rather than https://example.com/articles?id=10

If it's not, can this issue be reopened? If it is, how can I do that?

**Comment by pedzed** [comment]
> Emit an event that the url should change based on your conditions.
> 
> ```php
> //SomeComponent.php
> $this->emit('urlChange', 'https://someurl.local/category/somecategory?test');
> ```
> 
> Listen for the event.
> 
> ```blade
> //some-component.blade.php
> @push('footer-scripts')
>     <script type="text/javascript">
>         document.addEventListener('livewire:available', function () {
>             window.livewire.on('urlChange', param => {
>                 history.pushState(null, null, param);
>             })
>         })
>     </script>
> @endpush
> ```

Your code did not work, but thanks to @leMaur this works:
```html
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        window.livewire.on('urlChange', url => {
            history.pushState(null, null, url);
        });
    });
</script>
```

**Comment by elfeffe** [comment]
> What about non-query strings? That's not built-in, is it?
> 
> E.g. https://example.com/articles/10 rather than https://example.com/articles?id=10
> 
> If it's not, can this issue be reopened? If it is, how can I do that?

@pedzed How did you fix this?
I have categories on the left side and items on the right side.
I want to update URL using friendly URL's, and then update the right side with the items.
I don't pass querystring, instead I can pass the url, then I find the content using the slug.

**Comment by pedzed** [comment]
@elfeffe I'm not sure what part you didn't understand.

You emit the variable in PHP:
```php
$this->emit('urlChange', 'https://example.com/something/30/here');
```

And with this JavaScript code somewhere in your HTML document, it should redirect you to `urlChange`:
```html
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        window.livewire.on('urlChange', url => {
            history.pushState(null, null, url);
        });
    });
</script>
```

**Comment by elfeffe** [comment]
@pedzed You wanted to use
E.g. https://example.com/articles/10 rather than https://example.com/articles?id=10

How did you get that? How do you prevent the link click?
Because Livewire will pass the id as a query string, did you make it work like https://example.com/articles/10?

**Comment by booni3** [comment]
With v2, this would be great to get working with the new queryString functionality.

**Comment by stankiewiczpl** [comment]
To make it work with the url path, do not link to the controller only to the main component of the page:
`Route::get('/search/{category?}', \App\Http\Livewire\PageSearch ::class);`
Inside define


    class PageSearch extends Component

    {

    public $query;

    public $page;

    public $category;

    protected $queryString = [
        'query'=> ['except'=>''],
        'page' => ['except' => 1],
        'category'=> ['except'=>''],
    ];

    public function render()
    {
        return view('livewire.page-search');
    }

    }

And then, if you change the category parameter (eg Drop-down Filter), the route category parameter will change here
[https://github.com/livewire/livewire/blob/master/src/RenameMe/SupportBrowserHistory.php#L59](https://github.com/livewire/livewire/blob/master/src/RenameMe/SupportBrowserHistory.php#L59)

The important thing is to keep all parameters in the main component. Otherwise return url?category=xx. The easiest way to update another component is through events from main component to another components

**Comment by booni3** [comment]
So yeah... this just works! I added a quick PR to try and clear this up. It is great that is just works, but also not clear from the docs as it always talks about the query string only.

https://github.com/livewire/docs/pull/273

**Comment by rororomeda** [comment]
@stankiewiczpl
This works when I trigger the category parameter change manually. I can also navigate back and forth via the browser history button; the slot will update automatically, which is awesome.

But when I make a hard refresh with the new url, containing the updated category parameter, it doesn't work. The category isn't passed to the component via the router. So it always starts with the empty category parameter.

Any suggestions?

**Comment by Roardom** [comment]
For anyone making their way here in 2024 (v3), note that if you use `#[Url(history: true, except: '')]`, and initialize the property in the `mount()` method as mentioned in the documentation, the query string won't update to reflect the newly initialized properties. The query string will only update if `history: true` is removed from the attribute.

**Comment by Mrkbingham** [comment]
@Roardom Thank you!  That was the info I needed
