### ISSUE TITLE
Loading state not working when using ref & target

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#402]
**Describe the bug**
Loading state works for all buttons when I don't use ref and target, and doesn't work for any of them when I do.

**To Reproduce**
```php
@foreach($products as $product)
<button
    class="btn btn-success"
    wire:click="addToCart({{ $product->id }})"
    wire:ref="product{{ $product->id }}"
>
    <i class="fas fa-spinner fa-spin" wire:loading wire:target="product{{ $product->id }}"></i>
    @lang('shop.add_to_cart')
</button>
@endforeach
```

**Expected behavior**
See spinner for the button you clicked on.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome latest version

**Comment by adrianschubek** [comment]
`wire:ref` has been removed in [v0.5](https://github.com/livewire/livewire/releases/tag/v0.5.0)

**Comment by mokhosh** [comment]
Oh thanks, I forgot I red that in the release notes.

So, is there any way I can set loading on a specific button in the loop?
If I use the action (`addToCart`) all buttons will show the loading spinner while any item is being added to the cart.

**Comment by calebporzio** [comment]
Hey @mokhosh - that's a good call. Wondering what the best solution here is.

Thinking it'd be something like this:

A) `wire:target="addToCart"` would scope to all "addToCart" actions
B) `wire:target="addToCart({{ $product->id }})"` would scope to "addToCart" with the productId parameter.

What do you think?

**Comment by mokhosh** [comment]
Although it seems weird to include parameters as target, and something tells me we're breaking SOLID or DRY or some other set of rules somehow, I think we need to do this.

Firstly, because for some reason it seems like the obvious solution, and it was the only solution I thought I could try after I remembered there are no `ref`s in 0.5.
And more importantly, this doesn't work now:
```php
<button
    wire:click="addToCart({{ $product->id }})"
    wire:loading.attr="disabled"
>
```
I guess because it's trying to target `addToCart` with parameters which isn't supported.

**Comment by mokhosh** [comment]
What I did for now is I extracted items to a `ProductItem` component which holds its `productId` and doesn't need an attribute for its `addToCart` method.

But my biggest concern is efficiency.
I'm loading products in my main layout. And passing each product's Id to a component in a foreach loop.
Then in each component I store the Id and `find` the product from the database individually and every time it's needed.

**Comment by mokhosh** [comment]
OK, I changed the code to stop loading each model from the db individually. I pass the `product` and assign each of its attributes to a public property of my component.
But it's really hideous to assign like 12 properties in the `mount` method.

**Comment by calebporzio** [comment]
Ok, there's a lot of good stuff here.

1. Good catch on that bug (where `wire:click="foo('bar')" wire:loading.attr="disabled"` doesn't work). I fixed that, and it'll be available in `0.5.1` (which I will tag soon)
2. I still think the proper solution is to offer the ability to scope targets by param. Why do you think this seems wrong? It seems like a necessary feature. AND it allows you not have to create sub-components for every post.

**Comment by mokhosh** [comment]
I'm not sure, but I guess I'm used to designing and treating everything as a black box: Don't expose your data, don't sneak peek at other people's data. It felt like we're sniffing the parameters of a method to decide something.
Also, if we try to be exact here, what exactly is the `loading` element awaiting? a method? a method with specific parameters passed to it? or a specific call to server that should be identified with an id?

Ok, this was a therapy. I'm being too obsessive here. Go ahead man.

**Comment by mokhosh** [comment]
> But it's really hideous to assign like 12 properties in the mount method.

Also, can we make this easier? I guess it's a common scenario where we pass a model to a component and it's The Model for that component, and we would assign it to a public property but we can't so we assign all of its attributes to a dozen public properties.
should I open a feature request for this?

**Comment by calebporzio** [comment]
Adding loading target param scoping to the roadmap. Closing this.

**Comment by joemags-apps** [comment]
Facing same problem. The easiest would be to create a livewire component foreach product

**Comment by dhruva81** [comment]
> 
> 
> Adding loading target param scoping to the roadmap. Closing this.

Hi is this feature available now ?
