### ISSUE TITLE
Error during composer update to version 0.5.0

### ISSUE THREAD

**Issue by erikscheepers** [livewire/livewire#404]
**Describe the bug**
In one of my larger Livewire-projects I get an error during the postAutoLoadDump-phase of composer update. The only thing composer tries to do, is updating Livewire from 0.4.0 to version 0.5.0. In another, smaller, project the updating went without any issues.

**To Reproduce**
Bit difficult maybe to reproduce because updating my smaller project went without any issues. Any suggestions are welcome!

1. `composer update` project with livewire 0.4.0
2. Change version of livewire in composer.json to : `"livewire/livewire": "^0.5.0"`
3. Do `composer update` again

> Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
>   Illuminate\Contracts\Container\BindingResolutionException  : Target class [blade.compiler] does not exist.
>  at /project/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
    801| 
    802|         try {
    803|             $reflector = new ReflectionClass($concrete);
    804|         } catch (ReflectionException $e) {
> 805|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    806|         }
    807| 
    808|         // If the type is not instantiable, the developer is attempting to resolve
    809|         // an abstract type such as an Interface or Abstract Class and there is
  Exception trace:
  1   ReflectionException::("Class blade.compiler does not exist")
      /home/erik/Source/athena/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
  2   ReflectionClass::__construct("blade.compiler")
      /home/erik/Source/athena/vendor/laravel/framework/src/Illuminate/Container/Container.php:803

**Expected behavior**
Expect a flawlessly update to version 0.5.0, just like my other livewire project

**Comment by mikev032** [comment]
https://laracasts.com/discuss/channels/laravel/upgrade-to-58-class-bladecompiler-does-not-exist ?

**Comment by calebporzio** [comment]
Yeah, hmm - There's method in Livewire's service provider called: `registerViewCompilerEngine`, in the `boot()` method. This method registers Livewire's own blade engine, and references `$this->app['blade.compiler']`.

For some reason, in your app, `blade.compiler` isn't available yet when Livewire tries to do that.

If I had to guess, it's that you have another composer package installed that messes with `blade.compiler` or the loading order or something.

Do you get this same error if you try to load a page in the browser?

**Comment by erikscheepers** [comment]
It's strange that the error only shows when updating the livewire version. I did some more debugging and testing and found the cause:

I put my Blade directives in the register method of the AppServiceProvider. In the Laravel documentation boot is the lower and register the upper method. In my old version of this file (started this project in version 5.8), I didn't notice the [swap](https://github.com/laravel/laravel/commit/e0ae7914b9c0d2c2cb1ddee6782af2fcca4d7427#diff-80bda0ca3af455d6354e095203e0199a) and I put my directives in the lower (register) method

**Comment by calebporzio** [comment]
Gotcha, thanks for following up on that @erikscheepers!
