### ISSUE TITLE
Opt-in to have all public properties automatically passed to view?

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#405]
I understand the concern that led to removing automatic passing of public properties to views. You don't want us to be confused about when to use `$this->` and when to address a variable directly. That's ok, but it would be awesome to be able to get back that functionality if we're not easily confused, and we miss the good old days where "you would just name what you want and feel like you're writing vue code and not have `$this->` all over your beautiful blade code". Like through a trait or something, you know

```php
use PassesPublicPropertiesToViewAutomaticallyButHeyDontBeConfused
```

**Comment by calebporzio** [comment]
Your wish is my command:
```php
class YourComponent extends Component
{
    use PassPublicPropertiesToView;
```

(will be available in the next tagged release.)
