### ISSUE TITLE
Route model binding broken after v0.5

### ISSUE THREAD

**Issue by matsava** [livewire/livewire#408]
**Describe the bug**
After upgrading to v0.5 the route model binding is broken **on the second request**.

I have a CategoryPage component which looks like this:
```
class CategoryPage extends Component
{
    /** @var Category */
    protected $category;

    public function mount(Category $category)
    {
        $this->category = $category;
    }

    public function render()
    {
        return view('livewire.category-page', [
            'categoryName' => $this->category->name
        ]);
    }
}
```

The first time the page loads everything goes ok. When I interact with something, a checkbox for example and the component is called again I am getting an error:
```
Trying to get property 'name' of non-object
```
on this line 
```
 'categoryName' => $this->category->name
```

**To Reproduce**
I will try to reproduce this step by step in a clean repo if needed.

**Comment by adrianschubek** [comment]
Protected properties have been **removed** in v0.5. Use [Computed Properties](https://laravel-livewire.com/docs/computed-properties/) instead.

**Comment by matsava** [comment]
So the docs referring to Route Model Binding are outdated? 
https://laravel-livewire.com/docs/spa-mode/#route-model-binding

**Comment by matsava** [comment]
This feels wrong 😕 

In my case, I have a CategoryController which fetches the category and returns a view that contains the livewire component. 
Before I could just pass the $category object in the `mount` method and only run the query once.

Now I need to pass the id of the category, store it in a public property and retrieve it in a computed property so I essentially retrieve the same thing twice.

Is that right? Or am I missing something?

**Comment by mokhosh** [comment]
@matsava I had the same issue [here](https://github.com/livewire/livewire/issues/402).
Until we have a better solution, you can assign attributes of you `category` to public properties in your component, so that you have access to data without loading the model.

**Comment by calebporzio** [comment]
A) You can assign the model's properties as public properties and not load it twice.
B) You "could" store it temporarily for the first request, and fetch it for subsequent ones:
```php
class ShowCategory extends Component
{
    public $categoryId;

    public function mount($category)
    {
        $this->tmpCategory = $category;
        $this->categoryId = $category->id;
    }

    public function getCategoryProperty()
    {
        return $this->tmpCategory ?? Category::find($this->categoryId);
    }
}
```
C) You could use a "Castable" to do this for you automatically:
```php
class ShowCategory extends Component
{
    public $category;

    protected $casts = ['category' => CategoryModel::class];

    public function mount($category)
    {
        $this->category = $category;
    }
}

class CategoryModel implements Livewire\Castable
{
    public function cast($categoryId)
    {
        return Category::find($categoryId);
    }

    public function uncast($categoryModel)
    {
        return $category->id;
    }
}
```

I know none of these solutions feel as seemless and simple as just setting a protected property.

But the complexity that goes into that is just not worth it IMO. I think that feature is almost deceiving. Dare I say... too much magic. There are so many extra little "gotchas" that go along with it, I think I'd rather users understand how Livewire works (request to request, hydrating, and dhydrating), and them tailor their systems for that.

I know I haven't done a great job educating people on this, AND  I know the current solutions could probably be even better. BUT, hopefully you found something helpful here.

Great questions. Thanks.

**Comment by mokhosh** [comment]
> I know I haven't done a great job educating people on this, AND I know the current solutions could probably be even better. BUT, hopefully you found something helpful here.

*I* did.

Now that you got a little emotional at the end of this nice comment, I would say this: I love livewire, I love your attitude, and I feel a new level of good when I'm working with livewire or trying to improve it here.

And here's the criticism I didn't try to wrap in complements at all: please put all of your content in one place. That way even if you don't have time to organize it, other people will be able to contribute to the docs or make educational videos, create a body of content, and spread the word.

I've red and watched and listened to amazing content about livewire in your blog, on vimeo, in making livewire podcast, here in the issues, on some forum where you discussed the whole public-protected-hydration debate, conference videos on youtube, on twitter, and probably some other places I don't remember.

My suggestion is a Youtube channel for all past and future videos and podcasts.

I don't have any idea how to organize and get the most out of posts and comments right now. But the thought process and collaboration is just precious, I think.

**Comment by matsava** [comment]
Thank you @calebporzio for that 👍. 

I ended up storing it as an array after all
```
$this->category = $category->toArray()
```
