### ISSUE TITLE
Fill from eloquent model

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#409]
Thanks for the new `$this->fill([])` method. I see it can fill from arrays and simple objects with public properties. But it doesn't work with eloquent models passed as eloquent models which is probably the most important use case.

Maybe we can just check if the parameter is an eloquent object and call its `toArray`.

**Comment by mokhosh** [comment]
Also, this could raise another issue. If we wanna fill the `id` of that model too, it will interfere with livewire component's id property:

```
Livewire encountered corrupt data when trying to hydrate the [product-list-item] component. 
Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

Maybe:
1) we can rename the livewire `id` property to something like `_id` to be able to use it elsewhere. (Also `name` and `data` while we're at it?)
2) we can somehow tell the `fill` method where to put `id` of the model or certain other attributes, but this would add more work, and defeat the whole purpose.

**Comment by faustbrian** [comment]
@mokhosh could you open a separate issue for the id, name and data problem so it can be referenced in a PR?

**Comment by mokhosh** [comment]
@faustbrian [Sure](https://github.com/livewire/livewire/issues/417)

**Comment by faustbrian** [comment]
Can be closed as resolved via https://github.com/livewire/livewire/pull/414 @calebporzio @lancepioch @mokhosh

**Comment by mokhosh** [comment]
Yes, but also kind of obsolete, right? Because now we can have models and public properties and we don't have to fill anything with anything. (Unless someone likes to have model properties directly on the component for some reason.)

**Comment by faustbrian** [comment]
Don't think it's obsolete at all, your use-case must be very limited if you think so. You can't set properties on models and there are endless scenarios where you partially need data from a model on your component together with data that doesn't come from a model.

Having models as public properties and the need for filling from a model aren't mutually exclusive.

**Comment by calebporzio** [comment]
Very true
