### ISSUE TITLE
The future of Livewire is now (what?)

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#410]
> I know I haven't done a great job educating people on this, AND I know the current solutions could probably be even better. BUT, hopefully you found something helpful here.

Now that you got a little emotional at the end of [this nice comment](https://github.com/livewire/livewire/issues/408#issuecomment-564912987), I would say this: I love livewire, I love your attitude, and I feel a new level of good when I'm working with livewire or trying to improve it here.

And here's the criticism I didn't try to wrap in complements at all: please put all of your content in one place. That way even if you don't have time to organize it, other people will be able to contribute to the docs or make educational videos, create a body of content, and spread the word.

I've red and watched and listened to amazing content about livewire in your blog, on vimeo, in making livewire podcast, here in the issues, on some forum where you discussed the whole public-protected-hydration debate, conference videos on youtube, on twitter, and probably some other places I don't remember.

My suggestion is a Youtube channel for all past and future videos and podcasts.

I don't have any idea how to organize and get the most out of posts and comments right now. But the thought process and collaboration is just precious, I think.

**Comment by 2kodes** [comment]
@mokhosh  wouldnt the [public forum](https://forum.laravel-livewire.com/)  be a good place to aggregate this information ( links to videos, tutorials etc)?

**Comment by mokhosh** [comment]
Not really. Youtube is where people are. I wouldn't even know livewire forum existed if Caleb hadn't mentioned it in the 0.5 release.

**Comment by calebporzio** [comment]
@mokhosh - this is a really great point. Really glad you made and got me thinking about it.

What do you think about a "Blog" section on the site that acts as an aggregate of all things: new features, new videos, new podcast episodes, etc... Could have guest posts.

**Comment by mokhosh** [comment]
The idea is to check out one place, and be confident you haven't missed 80% of what you can learn about livewire, and not have to check all forum posts and github issues to see if someone have posted a comprehensive post about best practices or new ways you can use livewire.

I mean who could have thought you would post a *tutorial* that should have been somewhere in the docs, in a *closed* github [issue](https://github.com/livewire/livewire/issues/408#issuecomment-564912987)?

So I would say don't *add* a blog section. As *Rumi* once said: "We're here to aggregate, not to separate"! Just turn the *Building Livewire* podcast to a blog, and keep all the content there, or in the docs if it's here to stay.

But either way you're gonna upload videos somewhere, and embed them in blog posts. I think Youtube is a great platform for that. Youtube is one of the main places where people learn stuff and discover new things. Currently there are two or three tutorials about livewire on Youtube that just show you how to `composer require` livewire and define a simple component, which is ridiculous compared to how revolutionary it can be. If you just upload your blog's past video posts (which are awesome btw) to Youtube, there will be like 10 times the livewire content that is on there right now!

I don't wanna stress on the fact that you can make money on Youtube, but hey, you are really fun to listen to as well. I won't be surprised if you get a couple of hundred thousand subscribers in no time.

**Comment by calebporzio** [comment]
Good feedback @mokhosh - I will think about these things more and come up with a solution.
