### ISSUE TITLE
Model update event/listener

### ISSUE THREAD

**Issue by matsava** [livewire/livewire#412]
**Is your feature request related to a problem? Please describe.**
I have a usecase where I need to compare the old value and the new value of a property which is binded with `wire:model`. Is there any way I could somehow run code either before or after an update is performed on a binded public property?

**Describe the solution you'd like**
Possibly a method like `onAttributeUpdate(oldVal, newVal)` where attribute is the public property or even `onAttributeUpdate(attributeName, oldVal, newVal)`.

**Describe alternatives you've considered**
The only alternative I thought is using `wire:click` on the input instead, and handling the property updating myself but I thought maybe there is already a way to that so here we are 😄

**Comment by faustbrian** [comment]
Would `updatingFoo` and `updatedFoo` as documented at https://laravel-livewire.com/docs/lifecycle-hooks/ be of any use in your scenario?

**Comment by matsava** [comment]
I actually read the docs, not sure how I missed that :(

Will check them out, thanks!
