### ISSUE TITLE
Turbolinks browser back problem

### ISSUE THREAD

**Issue by ufukugurr** [livewire/livewire#413]
I used turbolinks but if you click browser back button page loading but doesn't work livewire.rescan() method. Also page in process doesn't work.

app.js
`require('./bootstrap');`
`var Turbolinks = require("turbolinks")`
`Turbolinks.start()`
`document.addEventListener('turbolinks:load', () => {`
`    window.livewire.rescan()`
`})`

my links

`<a href="test" data-turbolinks-action="advance">test</a>`

**Comment by calebporzio** [comment]
Turbolinks back button should be working now.

**Comment by hortigado** [comment]
I have the same error,  Cannot read property 'data' of null. When i back with back button turbolinks
