### ISSUE TITLE
Stop reserving common variable names

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#417]
Also, this could raise another issue. If we wanna fill the id of that model too, it will interfere with livewire component's id property:

```
Livewire encountered corrupt data when trying to hydrate the [product-list-item] component. 
Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

Maybe:
1) we can rename the livewire id property to something like _id to be able to use it elsewhere. (Also name and data while we're at it?)
1) we can somehow tell the fill method where to put id of the model or certain other attributes, but this would add more work, and defeat the whole purpose.

**Comment by faustbrian** [comment]
Relates to https://github.com/livewire/livewire/pull/401#issuecomment-562925960

@calebporzio if you have a naming convention or refactor like using an array to store all component state in mind I can work on a PR to resolve this issue.

**Comment by calebporzio** [comment]
Yeah, I think I'm actually going to tackle this @faustbrian - thanks for being willing!

**Comment by mokhosh** [comment]
This didn't happen, did it?
