### ISSUE TITLE
Indirect modification of overloaded element of Illuminate\Database\Eloquent\Collection has no effect

### ISSUE THREAD

**Issue by st693ava** [livewire/livewire#4180]
### Discussed in https://github.com/livewire/livewire/discussions/4160

<div type='discussions-op-text'>

<sup>Originally posted by **st693ava** November  6, 2021</sup>
I'am getting this error **_indirect modification of overloaded element of Illuminate\Database\Eloquent\Collection has no effect_**  everytime i type on a child related model after adding a new city (related model).

```php

namespace App\Http\Livewire;

use App\Models\City;
use App\Models\Country as ModelsCountry;
use Livewire\Component;

class Country extends Component
{
    public ModelsCountry $country;

    protected $rules = [
        'country.name' => 'required|string|max:255|min:4',
        'country.cities'=>'min:3',
        'country.cities.*.name'=>"required"
        
    ];

    public function addCity()
    {
        $this->country->cities->push(new City);        
    }

    public function save()
    {
        $this->validate();
        $this->country->save();
    }

    public function mount(ModelsCountry $country)
    {
        $this->country = $country;
        
    }
    
    public function render()
    {
        return view('livewire.country');
    }
}
```

```php 

<div class="">

    <x-ui::form.input-row name="country.name" label="Name" wire:model="country.name" />

    @foreach ($country->cities as $index => $city)
        <x-ui::form.input-row 
            name="country.cities.{{$index}}.name" 
            label="Name" wire:model="country.cities.{{$index}}.name" 
            wire:key="country.cities.{{$index}}.name"
        />

        
    @endforeach
        
    <x-ui::button.info wire:click="addCity" class="mt-4">Add City</x-ui::button.info>
    <x-ui::button.success wire:click="save" class="mt-4">Save</x-ui::button.success>
</div>


```

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
