### ISSUE TITLE
Pagination with tag a sometime not working ???

### ISSUE THREAD

**Issue by doanhung1996** [livewire/livewire#420]
**Describe the bug**
I'm using livewire with custom pagination tag a some page not working after click .

**To Reproduce**
1. Create custom pagination view with tag a to change page .
2. paginationView() set return section 1 view. 
3. Open browser click change page 
4. Some page not change after click .

**Expected behavior**
The page change correct.

**Desktop (please complete the following information):**
 - Browser chorme 
   Os: Ubuntu 18.04

**Comment by calebporzio** [comment]
Hey @doanhung1996 - please include code samples so we can help you better:

Specifically the following:
* Your custom pagination view
* The code you use to swap it in instead of the default

**Comment by doanhung1996** [comment]
Here is my pagination

```
@if ($paginator->hasPages())
    <ul class="options-middle tt-paginate">
        @if ($paginator->onFirstPage())
            <li class="disabled">
                <a href="javascript:void(0)">&lsaquo;</a>
            </li>
        @else
            <li class=""><a href="javascript:void(0)" wire:click="previousPage" aria-label="@lang('pagination.previous')">&lsaquo;</a></li>
        @endif

        @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
                <li class="">
                    <a href="javascript:void(0)">{{ $element }}</a>
                </li>
            @endif

            {{-- Array Of Links --}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="active"><a href="javascript:void(0)">{{ $page }}</a></li>
                    @else
                        <li class=""><a href="javascript:void(0)" wire:click="gotoPage({{ $page }})">{{ $page }}</a></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        @if ($paginator->hasMorePages())
            <li class=""><a href="javascript:void(0)" wire:click="nextPage" aria-label="@lang('pagination.next')">&rsaquo;</a></li>
        @else
            <li class="disabled"><a href="javascript:void(0)">&rsaquo;</a></li>
        @endif
    </ul>
@endif
```

**Comment by vanthao03596** [comment]
i have same issue @doanhung1996

**Comment by JellyBool** [comment]
Same issue here.

**Comment by linuxstreet** [comment]
The Livewire pagination is not working when using the default Laravel pagination views.

For example:
{{ $data->links('pagination::default') }}

will display the paginator correctly but clicking on the links will reload the entire page.

Laravel: 6.17.0
Tested in browsers:
- Chrome v80.0.3987.122
- Firefox 73

**Comment by telkins** [comment]
Has this been addressed...?  I feel like I'm having the same issue(s)....pagination seems to be quite inconsistent.

**Comment by sdiack** [comment]
Still seem to be getting inconsistent behaviour. 

Specifically:
- the `wire:click="previousPage"` doesn't seem to work for going 'back'

- all of the `wire:click="gotoPage({{ $page }})"` direct page links don't work when you're on a _later page_ than the one you're trying to select, except the link to page 1.

I'm using a slightly tailored custom pagination template - but basically reused [pagination-links.blade.php](https://github.com/livewire/livewire/blob/master/src/views/pagination-links.blade.php) that's part of the package as a base.

**Component**
```
namespace App\Http\Livewire;
use App\Healthcheck;
use Livewire\Component;
use Livewire\WithPagination;

class HealthchecksTable extends Component
{
    use WithPagination;
    public $rowsPerPage = 5;

    public function render()
    {
        return view('livewire.healthchecks-table', [
            'healthchecks' => Healthcheck::with('User')->paginate($this->rowsPerPage),
        ]);
    }
}
```

**Pagination called in view as**

`{{ $healthchecks->links('utilities.pagination') }}`

**Pagination view**
```
@if ($paginator->hasPages())
    <div>
        <span class="relative z-0 inline-flex shadow-sm">
        
            {{-- Previous Page Link --}}
            @if ($paginator->onFirstPage())
                <span>Blank</span>
            @else
                <button type="button" wire:click="previousPage">
                </button>
            @endif

            {{-- Pagination Elements --}}

            @foreach ($elements as $element)
                {{-- "Three Dots" Separator --}}

                @if (is_string($element))
                    <span>...</span>
                @endif

                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)

                        @if ($page == $paginator->currentPage())
                            <button type="button">
                            {{ $page }}
                            </button>
                        @else
                            <button type="button" wire:click="gotoPage({{ $page }})">
                            {{ $page }}
                            </button>
                        @endif
                    @endforeach
                @endif
            @endforeach

            {{-- Next Page Link --}}
            @if ($paginator->hasMorePages())
                <button type="button" wire:click="nextPage">
                    Next
                </button>                         
            @else
                <span>
                    Blank
                </span>                             
            @endif

        </span>
    </div>
@endif
```

Chrome 81.0.4044.92
Firefox 75

**Comment by vanthao03596** [comment]
any status on this ?

**Comment by mblarsen** [comment]
> will display the paginator correctly but clicking on the links will reload the entire page.

Yes, that’s expected and [covered in the docs ](https://laravel-livewire.com/docs/pagination). 

You can inspect the Livewire pagination template and use the knowledge from there to modify the original template. E.g. where to put ‘wire’ directives and such. 

I think your issue is not related to what others are describing.

**Comment by drfraker** [comment]
This may be a problem with diffing the DOM. I've recently run into the bug and it seemed to be alleviated by adding unique ID's to similar elements on the page. I'm not entirely sure if that was the solution, but it seemed to fix the problem.

**Comment by calebporzio** [comment]
I think @drfraker is right.

One of the most common causes of these types of issues is when there is a root level blade conditional:

![image](https://user-images.githubusercontent.com/3670578/85443694-93897080-b55f-11ea-8a80-ec32a8f4bbcf.png)

A solution to this would be to wrap the entire blade file in an element, sheltering the conditional from being tripped up with surrounding sibling elements.

If this doesn't make sense to you, you can learn more about this issue here: https://laravel-livewire.com/docs/troubleshooting

I'm going to close this for now, but I'm going to add a root element wrapper in the next major release (I don't want to mess with the layout without tagging a major release)

Hope this sounds good to everyone!
