### ISSUE TITLE
Mount with redirect route not working

### ISSUE THREAD

**Issue by tejalgandhi21** [livewire/livewire#4274]
public function mount($id,$dd){
        if($dd == 1){
            $this->delete($id);
        }

    }  

public function delete($id)
    {
        if($id){
            User::where('id',$id)->delete();
            session()->flash('message', 'Users Deleted Successfully.');
            return redirect()->back();
        }
    }

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open with a similar problem, see #4266.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
