### ISSUE TITLE
defer not working on select element

### ISSUE THREAD

**Issue by Bradzer** [livewire/livewire#4337]
### Discussed in https://github.com/livewire/livewire/discussions/4326

<div type='discussions-op-text'>

<sup>Originally posted by **Bradzer** December  2, 2021</sup>
The `defer` modifier seems not to work on my `<select>` element. Selecting a value updates the page and does not defer until next action. Here's the code made shorter for convenience:

**Component usage**
```blade
<LivewireComponent>
    <x-inputs.select-picker name="agency_id" class="select2" deferMode="defer" data-placeholder="Selectionner un magasin" label="Magasin" required />
</LivewireComponent>
```

**Component definition**
```blade
@props(['required', 'name', 'label', 'placeholder' => null, 'deferMode' => false])

<div class="form-group">
    <label for="{{ $name }}">{{ __($label) }} @isset($required) <x-required></x-required> @endisset</label>
    
    @if ($deferMode)
        <select wire:model.defer="{{ $name }}" id="{{ $name }}" {{ $attributes->merge(['class' => 'form-control '. validate($errors, $name)]) }} x-ref="{{ $name }}">
    @else
        <select wire:model.debounce.500ms="{{ $name }}" id="{{ $name }}" {{ $attributes->merge(['class' => 'form-control '. validate($errors, $name)]) }} x-ref="{{ $name }}">
    @endif
        
        @if(!$attributes->has('multiple'))
            <option value="">{{ $placeholder ?? "Selectionner un(e) ". $label }}</option>
        @endif
        {{ $slot }}
    </select>
    {!! validate_feedback($errors, $name) !!}
</div>
```
Is there anything wrong here ?

PS: `agency_id` is indeed a public property in the Livewire component class.

**Additional info**
Livewire version:  2.8.1</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
