### ISSUE TITLE
change default view_path in config should be effective on this line

### ISSUE THREAD

**Issue by NVD-R** [livewire/livewire#4379]
https://github.com/livewire/livewire/blob/f6b1726d1068a5b7315f03dc4e58d5763b928374/src/Component.php#L172

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, please open a discussion with a through description of the issue.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
