### ISSUE TITLE
The situation is as follows.

### ISSUE THREAD

**Issue by Xsaven** [livewire/livewire#4415]
The situation is as follows.
I use the Livewire component as a page, for this, my next design is indicated in the routes:
```
Route::get('/', \ComponentNamespace\AppContainerComponent::class);
```
in `ServiceProvider`
```
\Livewire::component('app-container', \ComponentNamespace\AppContainerComponent::class)
```
And when I am trying inside the template of this component, insert the other component of Livewire, it gives me an error:
```
BadMethodCallException
Method Illuminate\View\View::childHasBeenRendered does not exist. (View: /.../resources/views/widgets/main_sidebar.blade.php)
```
I sold a place where an error occurs, it turned out that in the variable `$_instance` is an instance of the `Illuminate\View\View` class:
![image](https://user-images.githubusercontent.com/1726771/146595408-f31e11fb-3210-4e57-b949-d412a5559b37.png)
And in the end, we can get something in the template variable and you will not give a check you do not:
![image](https://user-images.githubusercontent.com/1726771/146595645-d4567d0b-9f6c-417e-88e6-1960d447d6bd.png)

Fix please!

P.S.
So that, at the beginning of each template, where I use a Livevier component, I put the following design:
```
@php($_instance = $_instance instanceof \Illuminate\View\View ? null : $_instance)
```

PHP: v8.0
Laravel: v8.76.1
Livewire: v2.8.2

_Originally posted by @Xsaven in https://github.com/livewire/livewire/discussions/4409_

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and there is already a discussion open.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
