### ISSUE TITLE
Request check won't work if a Global Scope applied

### ISSUE THREAD

**Issue by OptimumTasarim** [livewire/livewire#4418]
### Discussed in https://github.com/livewire/livewire/discussions/4417

I applied a global scope to check the application's locale, but as you can guess I don't want to apply it for admin routes. Admin should see all models despite their locales.

So, here is the middleware for locale check:

```
class LocaleScope implements Scope
{
  public function apply(Builder $builder, Model $model)
  {
    if (! request()->routeIs('admin*')) {
      $builder->where('locale', session('locale'));
    }
  }
}
```

There is no problem once the livewire component is initialized. But if I update something in the component, the if statement in the global scope `if (! request()->outeIs('admin*'))` stops working, and global scope is applied for admin routes, too.

I could resolve this by checking the user's roles or privileges but this time admin user will see whole models in the frontend, and this will screw up the frontend. For example, the admin user will see all menu items from all locales in the navbar and the navbar will blow up.

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
