### ISSUE TITLE
@livewireStyles and @livewireScripts tags are not processed

### ISSUE THREAD

**Issue by danielzzz** [livewire/livewire#4431]
### Discussed in https://github.com/livewire/livewire/discussions/4429

<div type='discussions-op-text'>

<sup>Originally posted by **danielzzz** December 20, 2021</sup>
Hi, I have laravel 8.54
and "livewire/livewire": "^2.8",

but it seems that the tags to include livewire are not being processed. the rendered page just show the directives.

I have checked the forums for solutions but these did not work for me:
https://forum.laravel-livewire.com/t/resolved-livewirescripts-and-livewirestyles-showing-on-page/147/11
https://forum.laravel-livewire.com/t/working-on-local-but-not-on-staging/1201/5
.. and others

things I tried,
- composer dump-autoload (it discovers livewire, and livewire artisan commands do work)
- php artisan cache:clear (and view:clear, optimize:clear)
- removing manually bootstrap/cache files
- calling the directives with and without ()
- using the tags <livewire:styles /> and <livewire:scripts> - they are replaced with directives
- even tried to include the scripts and styles manually, but it's pointless as the component directives are not processed either.
- installing different versions (2.6, 2.7, 2.8)

please advice, thank you!
dan</div>

**Comment by danielzzz** [comment]
it seems that registerBladeDirectives() from LivewireServiceProvider is being called, but then somehow it's ignored in the layout.
I am not sure what else I could do to debug it...

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

Please copy your comment to the discussion, thanks! 🙂
