### ISSUE TITLE
Vue component disappears on re-render

### ISSUE THREAD

**Issue by Keyaku** [livewire/livewire#4488]
### Discussed in https://github.com/livewire/livewire/discussions/4487

<div type='discussions-op-text'>

<sup>Originally posted by **Keyaku** January  7, 2022</sup>
I'm running into the same issue from #388 (nearly 3 years old) using v2.8.2.

I need to update a livewire value from a Vue component; the issue comes up right after the value is updated, where all rendered components (not just Vue's) disappear. This is very frustrating, and none of the solutions in that thread seem to be of help.

A shortened version of my code:
```
<x-form.field name="schedule_days">
	<x-jet-label for="schedule_days" value="{{ __('Time Slots') }}" />
	<input disabled type="text" id="schedule_days" wire:model.lazy="schedule_days" value="{{ old('schedule_days', $plugin->schedule_days ?? null) }}"/>
	<template wire:key="vue_datepicker" wire:ignore.self>
		<div class="bg-white p-2 w-full border rounded">
			<v-date-picker v-model="selected.date" mode="dateTime"> {{-- code --}} </v-date-picker>
		</div>
	</template>
</x-form.field>
...
<script>
vue_datepicker = new Vue({
	el: '#vue_form',
	data: {
		selected: {},
		dates: [],
	},
	watch: {
		selected: function(){
			@this.schedule_days = JSON.stringify(this.dates);  // <--- causes re-render and the component disappears
		},
	},
});
</script></div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
