### ISSUE TITLE
Laravel 9 Jetstream With Livewire  error

### ISSUE THREAD

**Issue by alkoumi** [livewire/livewire#4638]
### Discussed in https://github.com/livewire/livewire/discussions/4637

<div type='discussions-op-text'>

<sup>Originally posted by **alkoumi** February  9, 2022</sup>
Laravel 9 Jetstream With Livewire =>  Livewire encountered corrupt data when trying to hydrate the [laravel.jetstream.http.livewire.update-profile-information-form] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.

when update any thing in user profile</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
