### ISSUE TITLE
Laravel 9 File Upload issue.

### ISSUE THREAD

**Issue by shaneburrell** [livewire/livewire#4642]
### Discussed in https://github.com/livewire/livewire/discussions/4631

<div type='discussions-op-text'>

<sup>Originally posted by **shaneburrell** February  8, 2022</sup>
After upgrading to Laravel 9 with new flysystem I get the following error on all file uploads.

Call to undefined method League\Flysystem\Filesystem::getAdapter()
/Users/williamburrell/yoda/yodalaravel/vendor/livewire/livewire/src/GenerateSignedUploadUrl.php#19
Error

    public function forS3($file, $visibility = 'private')
    {
        $adapter = FileUploadConfiguration::storage()->getDriver()->getAdapter();

        if ($adapter instanceof CachedAdapter) {
            $adapter = $adapter->getAdapter();

</div>

**Comment by shaneburrell** [comment]
FlySystem no longer used the getDriver()->getAdapter();

Look like this is the new way of getting an $adapter?

https://flysystem.thephpleague.com/v2/docs/adapter/aws-s3-v3/

/** @var Aws\S3\S3ClientInterface $client */
$client = new Aws\S3\S3Client($options);

// The internal adapter
$adapter = new League\Flysystem\AwsS3V3\AwsS3V3Adapter(
    // S3Client
    $client,
    // Bucket name
    'bucket-name',
    // Optional path prefix
    'path/prefix',
    // Visibility converter (League\Flysystem\AwsS3V3\VisibilityConverter)
    new League\Flysystem\AwsS3V3\PortableVisibilityConverter(
        // Optional default for directories
        League\Flysystem\Visibility::PUBLIC // or ::PRIVATE
    )
);

// The FilesystemOperator
$filesystem = new League\Flysystem\Filesystem($adapter);

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
