### ISSUE TITLE
Livewire scripts found but not working

### ISSUE THREAD

**Issue by sakhileb** [livewire/livewire#4643]
### Discussed in https://github.com/livewire/livewire/discussions/4640

<div type='discussions-op-text'>

<sup>Originally posted by **sakhileb** February  9, 2022</sup>
I have a simple form:

``` php
<form class="w-full" wire:submit.prevent="postComment">
     <textarea 
         type="text" 
         name="comment" 
         id="comment"
         wire:model.defer="newCommentState.body" 
         class="border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm mt-1 block w-full" 
         placeholder="Leave a comment!">
    </textarea>
    <button 
        type="submit" 
        class="justify-items-start btn rounded-full m-3">
        Comment
    </button>
</form>
```

and the Livewire Component:

``` php
public $newCommentState = [
    'body' => ''
];

public function postComment()
{
   dd($this->newCommentState);
}
```

All the above code is running on Livewire 2x and alpine 3x, and the @livewire scripts are included in the \layout\app.blade.php.

but for some reason when I click the submit button it reloads the page and appends a "?comment=" to the url.

I assumed the problem was the views being cashed so I ran php artisan view:clear and php artisan optimize:clear, yet that did not help. I also cleared my browser cache thinking that it would help but had no luck.

Can someone please enlighten on a solution to this problem, or point out what I might be doing wrong.

Thank you.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
