### ISSUE TITLE
We get error 419 (Session Expired)

### ISSUE THREAD

**Issue by espositodaniele** [livewire/livewire#4664]
We get error 419 if the page is inactive for a while, but also immediately when you visit the application and try to do something.

This happens on public page, we are not handling auth route and login, and fires this modal on session expired immediately after we update a public property on component with the `$set()` method that send back a post request or submitting a form.

I've also tried to increment the `SESSION_LIFETIME`.

_Originally posted by @espositodaniele in https://github.com/livewire/livewire/discussions/4663_

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
