### ISSUE TITLE
Not working with alpinejs@3.9 and livewire@2

### ISSUE THREAD

**Issue by sahakyanArt** [livewire/livewire#4760]
Not working with alpinejs@3.9 and livewire@2
Why are alpine inputs not updating?
 https://laravelplayground.com/#/snippets/fd7f4773-5312-466f-a217-9d842f617e99
_Originally posted by @sahakyanArt in https://github.com/livewire/livewire/issues/2063#issuecomment-1058237364_

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open #4762 we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
