### ISSUE TITLE
Complex form with dynamic validation of nested components is broken by PR #4319

### ISSUE THREAD

**Issue by JonathanH-UK** [livewire/livewire#4783]
### Discussed in https://github.com/livewire/livewire/discussions/4782

<div type='discussions-op-text'>

<sup>Originally posted by **JonathanH-UK** March 10, 2022</sup>
I've discovered that PR #4319 unfortunately breaks my code and at the moment I'm struggling to pin down the root cause. It is definitely from this specific PR - My form works fine under Livewire <= 2.8.0 but breaks with >= 2.8.2 

I upgraded LW from 2.7.x to 2.10.0 last month but this form is only used infrequently and isn't covered by a test (yeah, yeah, I know!) so it broke on the production site yesterday when an admin first tried to use it since the upgrade :-(

With v 2.8.2 of LiveWire I get the the following error when the validation fires:
```
500 ErrorException
Undefined array key "trainer"
```

I've shared the error from my Development site (i.e. Fake data)
https://flareapp.io/share/oPRKMWz7

I'm more than happy to discuss this, share more data and to test any patches/PRs. If I get an opportunity I may have another go at understanding how this PR breaks to see if I can suggest a fix but perhaps one of the LW devs will be able to spot the solution quicker  :pray: 

### Background Info

I've got a large form which covers each day of a week like this snippet:
![image](https://user-images.githubusercontent.com/15343370/157655577-304bebc3-3f46-401a-a32d-c2bbf390c010.png)

My validation may be a little unorthodox but I believe it is a valid use case - When the user selects a 'module' it validates the neighbouring 'trainee' and vice-versa so as to ensure that the user completes both fields:
![image](https://user-images.githubusercontent.com/15343370/157655693-4489a9ae-dced-4f78-a2d9-2cc5964be483.png)

I dynamically build my custom validation rules for this component like so:
```
    public function rules() {
        $rules['selected_week'] = 'required|not_in:0,null';
        foreach($this->values as $day => $rooms) {
            foreach ($rooms as $room => $timeslots) {
                foreach ($timeslots as $timeslot => $entries ) {
                    if ( array_key_exists('module',$entries) && $entries['module'] > 0 ) {
                        $rules["values.$day.$room.$timeslot.trainer"] = 'required|not_in:0';
                    }
                    if ( array_key_exists('trainer',$entries) && $entries['trainer'] > 0 ) {
                        $rules["values.$day.$room.$timeslot.module"] = 'required|not_in:0';
                    }
                }
            }
        }
        return $rules;
    }
```

And I'm using the `updated()` function to call validateOnly() against the opposite element:
```
    public function updated($propertyName)
    {
        \Log::warning($propertyName);
        if ( preg_match('/\.module$/',$propertyName) !== false ) {
            $trainer = preg_replace('/\.module$/', '.trainer', $propertyName);
            \Log::warning("Trainer $trainer");
            $this->validateOnly($trainer);
        }
        if ( preg_match('/\.trainer$/',$propertyName) !== false ) {
            $module = preg_replace('/\.trainer$/', '.module', $propertyName);
            \Log::warning("Module $module");
            $this->validateOnly($module);
        }
        $this->validateOnly($propertyName);
    }
```

e.g. The updated component is `values.Monday.zoom-1.morning.module` and I'm calling `validateOnly('values.Monday.zoom-1.morning.trainer')`

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
