### ISSUE TITLE
Page expired message after upgrade

### ISSUE THREAD

**Issue by joostvanhoof** [livewire/livewire#4798]
I've just upgraded to Laravel 9.4.1 and Livewire 2.10.4. I didn't change anything else, and I now get the following native browser message on every Livewire request, both on Safari and Chrome. I have ran `php artisan optimize:clear` and closed and reopened the tab as I thought it might be something with the session getting 'stuck' after the upgrade.

<img width="457" alt="Screenshot 2022-03-12 at 18 12 41" src="https://user-images.githubusercontent.com/5268113/158027817-2e0383a1-0642-4c0f-b72d-19115a1f556b.png">

The message seems a little different to what others have previously been reporting where it says 'due to inactivity'. That's not the case here.

**Update**
I don't know why but now the message does say 'due to inactivity'

<img width="455" alt="Screenshot 2022-03-12 at 19 58 02" src="https://user-images.githubusercontent.com/5268113/158031232-b4b91921-0aba-4349-9d31-eafaf90ef4aa.png">

In the network tab I can see the Livewire request gives a 419. As indicated I tried `php artisan optimize:clear` (which is `cache:clear`, `route:clear`, `view:clear` and `config:clear`) and tried changing the value `SESSION_COOKIE` in `config/session` so I'm sure that it's refreshed.

**Comment by Henriquex25** [comment]
I'm also having the same problem

**Comment by espositodaniele** [comment]
any solution about this?
