### ISSUE TITLE
Can't return file download from method

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#483]
My component represents a digital product. I'm using Spatie media library to attach files to my products. When I click on the *download* button, it should start downloading a file:

```php
// wire:click="download"

public function download()
{
    $files = Product::find($this->productId)->getMedia('download');
    return MediaStream::create($this->title)->addMedia($files);
}
```

These two lines work just fine if I put them in a normal controller, but not in livewire. Are there any workarounds?
The only quick fix that I can think of, and I don't like at all, is to redirect the user to another route that downloads the file, ugh.

**Comment by mokhosh** [comment]
I tried adding a route for downloading the file and redirecting to it. It starts downloading but the component just freezes. Nothing works, the loading state never ends, other buttons don't work either.

So, if we're not going to fix this fundamentally by adding support for file download responses, we need to see what's going on with this workaround.

**Comment by calebporzio** [comment]
Yeah, would you be able to investigate this further? It WOULD be good to support this case.

**Comment by mokhosh** [comment]
I did.

I think the problem is the way `handleResponse` in `Component/index.js` behaves when `redirectTo` is set. It just changes the url and returns (line 160) and the rest of the function is never executed if you redirect.
This is fine if you actually move to another page, but since when `Content Type` or `Disposition` is set in the response headers, the browser just starts downloading and keeps the current url without refreshing or anything, it gets messy, because livewire has said its goodbyes but the door is locked, which is really awkward.

I thought we could fix it one way or the other, but now I think we have to fix both problems:
1) keep doing what you were doing if the redirect is not actually changing the url, or at least do a refresh to get out of the freez
2) add a method for sending a file response

**Comment by mokhosh** [comment]
@lancepioch It's a bug report + a feature request, and an accepted call to collaboration. No questions.

**Comment by lancepioch** [comment]
Agreed, it's definitely a bug!

**Comment by intellow** [comment]
Jumping in here to say that I'm trying to use Livewire to download a file as well. I haven't come up with a good way to do this yet but will update if I find a solution.

**Comment by calebporzio** [comment]
Awesome, I think the answer to this will end up being the same as this question:

"How do I trigger a file download from an ajax response"

If there is a good answer to that. This is possible.

I'm going to let you all figure this out though, because I have other priorities ATM, thanks for pitching in!

**Comment by mokhosh** [comment]
@calebporzio looks like we have 3 options:

a) a more modern options that uses js to download the file but:
1. could use a lot of ram if the downloaded file is very large
2. doesn't supprt pre IE11 (which might not be a big caveat)

b) using cookies and iframes

c) using window.location
I have used this in my project and it works, but the problem is Livewire just freezes. (see this https://github.com/livewire/livewire/pull/491)


Here are a couple of links:
https://stackoverflow.com/questions/4545311
https://stackoverflow.com/questions/20830309
https://stackoverflow.com/questions/28165424
https://stackoverflow.com/questions/3499597

**Comment by xxdalexx** [comment]
Could an event do this? I don't know how that package works and what the MediaStream::create actually gives you. If it's an actual reference, I'm pretty sure something like this would work:
```
window.livewire.on('startDownload', link => {
    window.open(link,'_blank');
})
```
`$this->emit('startDownload', MediaStream::create($this->title)->addMedia($files))`

**Comment by mokhosh** [comment]
Yes, patterns similar to this do work. But the point is, when you work with laravel controllers, returning a file is as easy as returning a view, and that's not the case in livewire.

**Comment by xxdalexx** [comment]
You are always going to have to return the livewire view because of how it keeps state, why you get an error if you try to return anything other than a view, and probably will never change because that's how livewire was built to work.

But, there is a public property that exists on all components named $redirectTo, and if you assign a value to it, the livewire view will load first, and then try to hit that link. I don't think this was the intentional functionality of it, but it works, and won't break state if its a direct download link.

**Comment by mokhosh** [comment]
The world would be a different place if we all settled for the hard ways that are available.

**Comment by xxdalexx** [comment]
It would probably take a substantial rewrite of livewire's core to be able to type return instead of emit, but hey be the change you want to see in the world.

**Comment by calebporzio** [comment]
I think the best way to handle this right now is redirecting to a separate route in charge of downloading. I don't see an easy option here. Closing for now.

**Comment by oliverbj** [comment]
I am trying to do this as well from a Livewire component, but I cannot figure out a way to do it.

@calebporzio can you elaborate a bit on how to redirect to a separate route and start the download from there? I am not able to redirect from a Livewire component to a named route, whilst still including the files.

```php
//$files contains an array of files.
$this->redirectRoute('cars.show', ['car' => $this->car->id])->with(['files' => $files]);
```

Above gives me 

>  Call to a member function with() on null

**Comment by mokhosh** [comment]
I think you need something like this:
```php
// Livewire
$this->redirectRoute('cars.download', $this->car->id);

// web.php
Route::get('cars/download/{car}', 'CarFilesDownloader')->name('cars.download');

// CarFilesDownloader.php
public function _invoke(Car $car)
{
    return response()->download($car->zipped_files);
}
```
I wrote the code here with no intellisense, so tell me if I missed something.

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
@mokhosh  @xxdalexx 
if i had export excel file with givin array
how can i redirect it with my array ?
dont tell me to send it with the url by get method 😒

`$arr = [1,2,3,4];`
`
return Excel::download(new EncomesExport($arr), 'Encomes.xlsx');
`

**Comment by stancl** [comment]
Livewire could check if the returned response is a download response.

If yes, it could emit an event to the frontend, which would use `window.open` to visit a Livewire route which would trigger the download with the component's state & logic somehow 🤔

**Comment by alessandrobelli** [comment]
Not sure if it helps, but this works for me:
Livewire:
```php
    public function exportCsv()
    {

        $this->redirectRoute('download');
    }
```

web.php:
`Route::get('/admin/dashboard/download', 'TranslationController@download')->name('download');`

Controller:
```php
    public function download()
    {
        $translations = Translation::all();
        $filename = "en.csv";
        $handle = fopen($filename, 'w+');
        fputcsv($handle, array('Text', 'Language', 'Project', 'Translation'));
        foreach ($translations as $translation)
        {

            $row['Text'] = $translation->string;
            $row['Language'] = array_multidimensional_search(config('utilities.locales-list'), 'locale', 'en')[0]['isolanguagename'];
            $row['Project'] = $translation->project;
            $row['Translation'] = $translation->locales['en'];
            fputcsv($handle, array($row['Text'], $row['Language'], $row['Project'], $row['Translation']));
        }
        fclose($handle);
        $headers = array(
            'Content-Type' => 'text/csv',
        );
        return response()->download($filename, $filename, $headers);
    }
```

**Comment by booni3** [comment]
The redirect route method works... but seems to break the component from where the request was made.

i.e

1. Click download link
2. `$this->redirectRoute('download');` is called as in above example.
3. Click download link again. Now nothing happens. i.e. no requests are fired to the backend at all.
4. Refresh the page and it works again.

**Comment by lekeabiodun** [comment]
This works for me
Livewire:
    public function export()
    {
        $brands = Brand::all();
        $data = "Name, Code".PHP_EOL;
        foreach($brands as $brand) {
            $data .= $brand->name.", ".$brand->code.PHP_EOL;
        }
        Storage::disk("company")->put("export.csv", $data);
        session()->flash("success", "File exported successfully.");
        return redirect(Storage::disk("company")->url("export.csv"));
    }

**Comment by darviscommerce** [comment]
For fure use, this works fine in livewire force download

```
public function download(){

            $path       = public_path('Bla.pdf');
            $contents   = base64_decode('filecode');

            //store file temporarily
            file_put_contents($path, $contents);

            //download file and delete it
            return response()->download($path)->deleteFileAfterSend(true);
}
```

**Comment by stanleyume** [comment]
Easier method without saving the file. (Tested with Laravel 8)

```php
public function download() {
        $fileName = 'some_file.xlsx';
        $contents = 'Contents of the file';

        return response()->streamDownload(function() use($contents) { echo $contents; }, $fileName);
}
```

**Comment by mokhosh** [comment]
It's a pretty old issue, and your comment just reminds us how far livewire has come.

**Comment by stanleyume** [comment]
> It's a pretty old issue, and your comment just reminds us how far livewire has come.

@mokhosh  Well, I'm here because I had this same problem, as others probably would in future.

**Comment by mokhosh** [comment]
The fact that any of the purposed suggestions after July of 2020 work is because this feature was added to Livewire in v2.0. Try making your suggestions work on version v0.5.2 and then we'll talk 😄
