### ISSUE TITLE
Data binding doesn't sync if keydown event is used

### ISSUE THREAD

**Issue by kurucu** [livewire/livewire#487]
**Describe the bug**
If lazy data binding is used and the keydown event is used to submit changes, the changes are not always in sync.

**To Reproduce**
1. Use the following or similar code: `<input type="text" wire:model.lazy="name" wire:keydown.enter="updateModel">`
2. Type text and then hit enter - you may get spurious results
3. Type text and then submit via e.g. a button - all works

**Expected behavior**
The keydown event should allow model changes before its own action.

**Desktop (please complete the following information):**
 - macOS Catalina, Safari 13.0.3

**Additional context**
I'm guessing that the text box does not lose focus before the action is taken, so the lazy modifier is causing changes not to have propagated in time.

**Comment by calebporzio** [comment]
Yes, that's exactly the issue.

Not sure if there is a good fix on Livewire's end though.

If you want, you can do something like this:

`<input type="text" wire:click="updateModal($event.target.value)">` and update the property in that method after you pass along the value.
