### ISSUE TITLE
Livewire issues

### ISSUE THREAD

**Issue by m-sabry-flojics** [livewire/livewire#4873]
### Discussed in https://github.com/livewire/livewire/discussions/4863

<div type='discussions-op-text'>

<sup>Originally posted by **m-sabry-flojics** April  6, 2022</sup>
Hello,
We had some issues while using livewire with laravel.
Our laravel version is : 8.12 our livewire version is : ^2.3
Here are issues:
1- on select input wire change don't work while wire click exists only one of them working.
2- when changing a select value the other fields in form lost their values even there is no change method to do so or event run.
3- we had some issues with multiple environments different behavior in them ( local - staging - live ) although all have same livewire and laravel versions.

We have a question :
can we refer to specific blade file and link it to livewire component ( we get component not found when try so )
so what is right way to do so?</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
