### ISSUE TITLE
Render Component

### ISSUE THREAD

**Issue by fuentesbr** [livewire/livewire#4896]
### Discussed in https://github.com/livewire/livewire/discussions/4895

<div type='discussions-op-text'>

<sup>Originally posted by **fuentesbr** April 19, 2022</sup>
Hi,

I'm rendering a pagination component. At the beginning of this component there is an @include for the inclusion of the hero header:

```
@include('components.oneui.hero', [
         'title' => 'Athletes',
         'subtitle' => 'List of athletes registered in the system.',
         'breadcrumbs' => $oneui_breadcrumbs[request()->route()->getName()]
])

```

It renders normally on page load. But when I go to use pagination, it shows the following error message:

`Undefined array key "livewire.message"`

Detail: if I bring the code in components.oneui.hero to the component view, it also gives the same error, but if I don't do @foreach, it loads the second page without problems.

My code do component Hero:

```
<!-- Hero -->
<div class="bg-body-light" wire:ignore>
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2">
            <div class="flex-grow-1">
                <h1 class="h3 fw-bold mb-2">
                    {{ $title }}
                </h1>
                <h2 class="fs-base lh-base fw-medium text-muted mb-0">
                    {{ $subtitle }}
                </h2>
            </div>
            <nav class="flex-shrink-0 mt-3 mt-sm-0 ms-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    @foreach ($breadcrumbs as $name => $route)
                        @if(!$loop->last)
                            <li class="breadcrumb-item">
                                <a class="link-fx" href="{{ route($route) }}">{{ $name }}</a>
                            </li>
                        @else 
                            <li class="breadcrumb-item" aria-current="page">
                                {{ $name }}
                            </li>
                        @endif
                    @endforeach
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->
```

**Comment by fuentesbr** [comment]
It worked perfectly transforming a Laravel component into a Livewire component. \o/

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
