### ISSUE TITLE
Duplicated events listeners

### ISSUE THREAD

**Issue by wesleycavalcante** [livewire/livewire#4898]
### Discussed in https://github.com/livewire/livewire/discussions/4897

<div type='discussions-op-text'>

<sup>Originally posted by **wesleycavalcante** April 19, 2022</sup>
When I load the same component in a modal via ajax it registers duplicate event listeners (listed in getEventListeners) even by calling the rescan() function. Is there a way to clear the events of components that were removed from the DOM, so on the next attempt to load it the event listener would be registered again?

<img width="502" alt="Captura de Tela 2022-04-19 às 02 51 29" src="https://user-images.githubusercontent.com/30080815/163929749-c37f5857-5c6d-45c1-9540-88fcac24fa7d.png">
<img width="613" alt="Captura de Tela 2022-04-19 às 02 51 53" src="https://user-images.githubusercontent.com/30080815/163930302-66c391bc-db8d-4ece-8cbc-fda98bd3d620.png">
<img width="371" alt="Captura de Tela 2022-04-19 às 02 52 26" src="https://user-images.githubusercontent.com/30080815/163930866-37f37c08-ecf3-4b98-a7e2-1c48c7b6f0bc.png">

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
