### ISSUE TITLE
Livewire can't handle script tag templating inside loops

### ISSUE THREAD

**Issue by reneroboter** [livewire/livewire#4937]
### Discussed in https://github.com/livewire/livewire/discussions/4935

<div type='discussions-op-text'>

<sup>Originally posted by **reneroboter** May  3, 2022</sup>
Using script tag with type `text/template` currently not working with Livewire. 

Imagine you have the default counter example and extend it by loop that run until the current count. After the first request Livewire runs into a `Uncaught (in promise) SyntaxError: Unexpected token '<'`. 

This happen because at [node_initalizer](https://github.com/livewire/livewire/blob/master/js/node_initializer.js#L11) Livewire check if the current node is a script tag and throw the current node into JavaScripts `eval` function.

I would expect that Livewire checks here more if the current node is really JavaScript code :) 

I add a simple example of this bug. 

```blade
<div style="text-align: center">
    <button wire:click="increment">+</button>
    <h1>{{ $count }}</h1>
    @for ($i = 0; $i < $count; $i++)
        <script type="text/template">
            <div>Fancy Livewire stuff! 1</div>
        </script>
    @endfor
</div>
```

My current solution is to use template tags instead of script tags of type `text/template`. However I'm not sure if there where other situation where Livewire crash of this condition. What do you think? Does we need here a more explicit condition?

Greeting
René</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
