### ISSUE TITLE
Conditional Rendering of components

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#494]
I quite often find myself in situations where I need to conditionally render some Livewire components and those conditions aren't based on authorisation or policies so I need to pollute my blade views with those conditionals since there is no way to prevent the `render` method from being called as far as I know.

A solution proposal for this problem would be to implement a `renderWhen` method that would return a boolean and decide if we render the component or simply return nothing or an empty div.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class EnableTwoFactorAuth extends Component
{
    public function mount(User $user)
    {
        $this->user = $user;
    }

    public function renderWhen(): bool
    {
        return ! $this->user->uses_two_factor_auth;
    }
}
```

**Comment by imliam** [comment]
Absolutely love this idea. Another scenario that it'd be super useful for is when a component has the ability to delete itself without being in a parent "list" component - this would help with that.

**Comment by faustbrian** [comment]
I think in the same spirit we should probably also have a `mountWhen` method that could be used to decide if a component should be taken care off at all, for example you could return `Gate::allow(...)` from the `mountWhen` method and if it is false then Livewire could completely ignore any further treatment of that component.

**Comment by calebporzio** [comment]
I'm interested in this concept. But I haven't needed it myself.

Please provide concrete use-cases here with code samples to demonstrate the points before I consider merging the PR.

**Comment by faustbrian** [comment]
This is just some pseudo but it's based on a real application I've worked on in the past. You could say that these kind of checks should go into a policy/gate or simply throw a 401/403 but these kind of checks are only used exactly once. Usually I would simply not render that blade template so in the context of Livewire it would make the most sense to me to not render the component without having to pollute the view with all of those checks.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SomeThing extends Component
{
    public function mount(User $user)
    {
        $this->user = $user;
    }

    public function renderWhen(): bool
    {
		if ($this->user->onGenericTrial()) {
			return false;
		}

		if ($this->user->cancelled()) {
			return false;
		}

		if ($this->user->suspended()) {
			return false;
		}

		// now some class is called to perform some more checks like payment provider details, relationship to any teams, etc.

        return true;
    }
}
```

**Comment by faustbrian** [comment]
Found another example from an application I am working on there this would help to keep the view free from any conditionals.

```php
<?php

namespace App\Http\Livewire;

use App\Http\Livewire\Concerns\InteractsWithRelease;
use Livewire\Component;

class DeleteProject extends Component
{
    use InteractsWithRelease;

    public ?int $projectId = null;

    protected $listeners = ['deleteProject' => 'askForConfirmation'];

    public function askForConfirmation(int $id): void
    {
        $this->projectId = $id;
    }

    public function destroy(): void
    {
        $this->project->purge();

        $this->reset();
    }
    
    public function reset(): void
    {
        $this->projectId = null;

        $this->emit('refreshProjects');
    }
}
```

Because the `projectId` can be `null` I need to wrap my whole component in an `if` check to ensure it's not rendered.

```blade
<div>
    @if($this->projectId)
        ...
    @endif
</div>

```

**Comment by mattdfloyd** [comment]
I too like the idea of conditional rendering. As a countering thought, just to challenge how this is accomplished best!...

Could `render()` return `void` if a view shouldn't be rendered? This could be implemented similarly to #501 in `output()`:

```php
public function output($errors = null)
{
    ...

    $view = $this->render();

    if (is_null($view)) {
        return '<div></div>';
    }

    ...
}
```

And in the component:
```php
public function render()
{
    if (! $this->user->uses_two_factor_auth) {
        return;
    }

    return parent::render();
}
```

This would allow this concept to be accomplished without a change to the API since `render()` does not enforce a type.

With either direction: I could see a "Null Object" view could be beneficial instead of the `<div></div>`.

**Comment by calebporzio** [comment]
My gut tells me that this is the kind of feature that doesn't justify the complexity (and therefore future issues and gotchas) it adds to the core.

A) I personally would advocate handling conditional rendering in the parent view
B) Could you extend `Livewire\Component` and overwrite the `->output()` method to accomplish this for your own projects?

Either way, the usage doesn't seem great to me, and the implementation gives me the willies. I think I'd rather punt on this.

**Comment by valetto** [comment]
I think we can accomplish this via

`    public function mount()
    {
        // $this->skipRender(); 
        $main_slider = MediaSlider::where('name', 'home_page_slider')->first();
        if($main_slider)
        {
            $this->main_slides = $main_slider->slides->sortBy('order');
        }
        // @dd($this->main_slides);

        if(empty($this->main_slides))
        {
            $this->skipRender(); 
        }
    }`
