### ISSUE TITLE
Add more lifecycle hooks for more fine grained control

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#495]
We already have a few lifecycle hooks which are documented at https://laravel-livewire.com/docs/lifecycle-hooks/ but there isn't really a way to do something before or after they are called.

I would propose that more methods are added that allow a developers to have more fine grained access to the lifecycle of the component and what it does. For example https://vuejs.org/v2/api/#beforeMount and https://vuejs.org/v2/api/#mounted are common hooks that are used in Vue.js but with Livewire you should have to perform all of those things in the `mount` method where it would like this.

```php
<?php

namespace App\Http\Livewire;

class ManageAnnouncements extends Component
{
    public function mount(User $user): void
    {
        // pseudo beforeMount

		// mount

        // pseudo afterMount
    }
}
```

The same kind of `before/after` methods could be added for `hydrate` and `render`. They would be fairly simple to implement as we could simply check in the `__call` method if they exist and if they do call them.

There also aren't really any performance implications out of the box and it's up to the developer to use them responsibly, same as with vue.

**Comment by calebporzio** [comment]
No plans on extra hooks right now.

**Comment by uteqnl** [comment]
I really need this, so I can create conditional fields visibility behavior that syncs the fields visibility whenever the component is mounted and hydrated. And make this behavior available trough a Trait. Events would be even better.

Would it be ok if I create a pull request for this? Any other insights on this or how to pull this of without adding more lifehooks?

**Comment by uteqnl** [comment]
The best solution would be to make it possible to decorate the mount method or have some kind of composition optiona. This is currently not possibke because of the way the parameters are resolved in the LivewireManager.
