### ISSUE TITLE
The wrong div disappears when wire:ignore is applied to multiple divs

### ISSUE THREAD

**Issue by intellow** [livewire/livewire#496]
**Describe the bug**
I have 3 divs. Each has `wire:ignore` applied to them. The second div should show or disappear based on the value of a select in the first div. When the second div is supposed to disappear, the third div disappears.

**To Reproduce**

1. Create a new Laravel project and install Livewire
2. Create a component, add the following to the view:

```
<div>
    <div wire:ignore>
        <select wire:model="value">
            <option value="1">Yes</option>
            <option value="2">No</option>
        </select>
    </div>
    @if($this->value == 1)
    <!-- This should disappear but it does not -->
    <div wire:ignore>
        <input type="textarea" />
    </div>
    @endif
    <!-- This should not disappear but it does -->
    <div wire:ignore>
        <button>Click Me</button>
    </div>
</div>
```

3. Add the `$value` public property to the class.

```
use Livewire\Component;

class Select extends Component
{
    public $value;

    public function render()
    {
        return view('livewire.select');
    }
}
```

4. In the browser, when you change the select in the first div, the 3rd div disappears instead of the second one.

**Expected behavior**
I expect the 2nd div to disappear when the `$value` is 0.

**Desktop (please complete the following information):**
 - Latest version of Chrome on a Mac.

**Comment by intellow** [comment]
As a workaround, if you add `wire:key="unique_identifier"` to each div, everything works as you would expect.

The following code does work correctly.
```
<div>
    <div wire:ignore wire:key="first">
        <select wire:model="value">
            <option value="1">Yes</option>
            <option value="2">No</option>
        </select>
    </div>
    @if($this->value == 1)
    <div wire:ignore wire:key="second">
        <input type="textarea" />
    </div>
    @endif
    <div wire:ignore wire:key="third">
        <button>Click Me</button>
    </div>
</div>
```

**Comment by calebporzio** [comment]
I believe this issue is caused because morphdom is re-using one of those divs after you remove the middle one. BUT, it can't change it because of `wire:ignore`.

I think we should just stick with the adding `wire:key` where this is an issue.

`wire:ignore` will become less common with the first-party Alpine support available now.

Going to close this.
