### ISSUE TITLE
Feature Request: Add "assertRedirect" to testing methods

### ISSUE THREAD

**Issue by manogi** [livewire/livewire#500]
I have a Login component which works great. Livewire really is awesome. The component checks on submit if the admin logging in has only one or multiple accounts and redirects the admin either to their dashboard or to a “choose-account” page. It works great, and it’s just a few lines of code.

But I would like to have a test that tests exactly that (an admin with multiple accounts gets redirected to the “choose account” page). I dont seem to get it to work - see my code:

This is my test:

```
/** @test */
public function admin_with_multiple_accounts_is_redirected_to_choose_account_page()
{
    $admin = $this->newAdminWithMultipleAccounts();

    $loginForm = Livewire::test(LoginForm::class);

    $loginForm->set('email', $admin->email);
    $loginForm->set('password', 'password');

    $loginForm->call('submit');

    // Not working:
    // response()->assertRedirect(route('choose-account'));

    // Not working:
    // $this->assertRedirect(route('choose-account'));

    // Not working:
    // $loginForm->assertRedirect(route('choose-account'));
}
```

This is the method in my Livewire component which actually works, but I don’t seem to be able to test:

```
    protected function redirectLoggedUser(User $user)
    {
        if ($user->accounts->count() > 1) {
            return $this->redirect(route('choose-account'));
        }

        return $this->redirect(route('dashboard'));
    }
```

**Comment by faustbrian** [comment]
@manogi can be closed as of https://github.com/livewire/livewire/pull/503
