### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token { in JSON at position 431     at JSON.parse (<anonymous>)     at index.js:69:58

### ISSUE THREAD

**Issue by Masamitsu0922** [livewire/livewire#5010]
### Discussed in https://github.com/livewire/livewire/discussions/5009

<div type='discussions-op-text'>

<sup>Originally posted by **Masamitsu0922** June  2, 2022</sup>
Hi!
I'm Japanese and I'm not very good at English, so there may be strange sentences.

In the local is working normally but in the server i got this error.
```
 Uncaught (in promise) SyntaxError: Unexpected token { in JSON at position 431     at JSON.parse (<anonymous>)     at index.js:69:58
```
In addition, the above error occurs a few hours after deployment...
And redeploying will temporarily fix the problem ...

screenshot
<img width="1306" alt="スクリーンショット 2022-06-02 13 05 39" src="https://user-images.githubusercontent.com/67775645/171552321-153bf675-88ec-4092-801f-d42163c61465.png">

The contents of the "response" are as follows
```
"{"fingerprint":{"id":"Bz0M...","name":"components...","locale":"ja","path":"orders...","method":"GET","v":"acj"},"serverMemo":{"children":[],"errors":[],"htmlHash":"64a576a5","data":{"userName":null},"dataMeta":[],"checksum":"f0f0..."},"updates":[{"type":"callMethod","payload":{"id":"p25q","method":"searchUser...","params":[]}}]}{"effects":{"html":"<div wire:id="Bz0MXW6H2z0bSg7QZsas">n ...(Large html data...)...</div>n</div>n","dirty":[]},"serverMemo":{"htmlHash":"001c690a","checksum":"db52358aa07a4b2c0c520a1a8d02a3a3843153a6643fb3b424ddc138d1cb1b9b"}}"
```
The cause of the error was that the json of "fingerprint" and "effects" were concatenated and not in JSON format.
But I don't understand why it has become such a format.

<img width="573" alt="スクリーンショット 2022-06-02 13 05 10" src="https://user-images.githubusercontent.com/67775645/171552331-c9576ff0-fb2e-4c0e-a067-2ca63d1e3a00.png">

any ideas?

The current environment is as follows
```
PHP v8.1
Laravel v8.77.1
Livewire v2.8.2
```
I don't know if it's related, but I also have the following libraries installed
```
jeroennoten/laravel-adminlte v3.7.2
auth0/login v6.5
payjp/payjp-php v1.2
```

Similar to the phenomenon below. But had not resolved.
https://forum.laravel-livewire.com/t/uncaught-in-promise-syntaxerror-unexpected-token-in-json-at-position-1768/1111</div>

**Comment by parmonov98** [comment]
> 

Do you have the same environment software versions? I mean PHP and Server?

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
