### ISSUE TITLE
x-slot in child component

### ISSUE THREAD

**Issue by yassermohammad** [livewire/livewire#5018]
### Discussed in https://github.com/livewire/livewire/discussions/5017

<div type='discussions-op-text'>

<sup>Originally posted by **yassermohammad** June  7, 2022</sup>
Hello and thanks for good framework,
I have two childs component inside my parent component, here:
index.blade.php
![Screenshot from 2022-06-07 21-29-57](https://user-images.githubusercontent.com/34732441/172440633-1523dadb-9f17-4854-bdd9-12663bb5a250.png)

I added x-slot script tag which contains an event click listener on any button in the step-one like this
step-one.blade.php
![Screenshot from 2022-06-07 21-40-18](https://user-images.githubusercontent.com/34732441/172442396-14847bb7-d92e-4ef9-9c96-a09f477fb495.png)

I added a this script's name in the default layout view(I called it "master.blade.php") like this:
{{ $script ?? '' }}

but it does not attached to it,
how can I listen to click on the button in a child component by jquery script?</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
