### ISSUE TITLE
Conditional Mounting of components

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#502]
In the spirit of https://github.com/livewire/livewire/issues/494 we could also consider to add a `mountWhen` method. This would allow developers to completely disable the treatment of a component without having to pollute their views or multiple methods inside components with authorisation checks.

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class EnableTwoFactorAuth extends Component
{
    public function mount(User $user)
    {
        $this->user = $user;
    }

    public function mountWhen(): bool
    {
        return Gate::allows('update-post', $this->post);
    }
}
```

**Comment by ManojKiranA** [comment]
@faustbrian  What is the Key Difference between `mountWhen` and `renderWhen`

**Comment by faustbrian** [comment]
If `mountWhen` would return `false` it would completely disable your component while `renderWhen` would still create the instance of your component but not render anything until `renderWhen` returns true.

Basically it's either completely ignore the component or render it and react to things which could eventually lead to the component rendering.

**Comment by faustbrian** [comment]
Closing as it's in the same spirit as https://github.com/livewire/livewire/issues/494#issuecomment-570679502
