### ISSUE TITLE
@livewire(App\Http\Livewire\Counter::class) callable

### ISSUE THREAD

**Issue by caominhduc3108** [livewire/livewire#506]
I need to use some Livewire Components in my package 
So i think it much more clear and reuseable if we can call by blade directive by Component classname.

**Comment by calebporzio** [comment]
@caominhduc3108 - can't you already do this? Did you try?

**Comment by calebporzio** [comment]
Ah, I see - it's not currently possible, wouldn't be too hard to implement. Open to PRing?

**Comment by caominhduc3108** [comment]
@calebporzio I just some lines of code in LivewireManager@active.
With me Classname is more readable than Alias.

**Comment by calebporzio** [comment]
Merged PR, should be good
