### ISSUE TITLE
The given data was invalid.

### ISSUE THREAD

**Issue by isaacdarcilla** [livewire/livewire#5063]
### Discussed in https://github.com/livewire/livewire/discussions/5060

<div type='discussions-op-text'>

<sup>Originally posted by **isaacdarcilla** June 23, 2022</sup>
I have this 5MB image. When I try to upload it this occurs. (See screenshot)

![image](https://user-images.githubusercontent.com/22732118/175201443-b6775d4e-40a4-4232-a2c9-86c43697a658.png)

In my network tab in Chrome, 

I got this error in `livewire/upload-file?expires=1655954899&signature=f45d3d7534279d2d1f0d9207be25c03730cda4c0fa799cd955879430fbd58700` that says 'The given data was invalid. (See screenhot)

![image](https://user-images.githubusercontent.com/22732118/175202449-5069e6a9-c7dd-4824-8957-9ea8a7cf7061.png)

When I try to upload smaller image file size, it continue to upload without any error. But with bigger file size, the error above occurs.

Any help is appreciated.

</div>

**Comment by rizkyprasetya** [comment]
try increasing php maximum upload size

**Comment by timgavin** [comment]
Have you tried with another large image? I encountered something like this before and the jpg was actually bad/corrupted. When I tried with another file it worked.

**Comment by isaacdarcilla** [comment]
Yes tried those already and the error still exist.
