### ISSUE TITLE
BindingResolutionExeption: Target class [] does not exist.

### ISSUE THREAD

**Issue by ITHDevelopment** [livewire/livewire#5088]
### Discussed in https://github.com/livewire/livewire/discussions/5087

<div type='discussions-op-text'>

<sup>Originally posted by **ITHDevelopment** July  4, 2022</sup>
Simple. Fresh installation of livewire in a working laravel 8 project.
Composer.json file:
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

Followed the quickstart, this is the result when firing the `wire:click"increment"` event:
![livewire_issue](https://user-images.githubusercontent.com/71849483/177219229-9bcd9dad-9e0a-4d3d-b18f-00c11d02f0c8.png)
I have already spent a day researching and tweaking packages versions and files without success, so here i am.</div>

**Comment by ITHDevelopment** [comment]
Now i have upgrade the project to laravel 9 following the official laravel docs. Nothing still. Same error but now in index.php
![livewire_issue_laravel9](https://user-images.githubusercontent.com/71849483/177231684-10604cc5-c4e8-4da9-88e4-fcc9309018c9.png)

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
