### ISSUE TITLE
Pagination showing up even when search count is less than pagination count.

### ISSUE THREAD

**Issue by K2ouMais** [livewire/livewire#509]
**Describe the bug**
I have a search Input and I am showing a list of items in a list with a pagination count of 5 on each page.

The search only works when I am on page 1. If I go to another page and search something over the input the results dont get listed and the pagination still shows up even when the search count is small than the pagination count.

**Expected behavior**
I was expecting to see my results without pagination. If I press on the pagination i cant see the results of my search.

**Video**
 https://youtu.be/uWFiGDlw7cg (Take a look at 0:32)

*I am not sure if this is a bug or I am missing something out.*

Controller:
```
<?php

namespace App\Http\Livewire\Tags;

use App\Tag;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class TagEdit extends Component
{
    use WithPagination;

    public $searchInput;
    protected $searchList;
    protected $pagination = '5';

    /**
     * @param $id
     * @throws Exception
     */
    public function deleteTags($id): void
    {
        $deleteID = Tag::findOrFail($id);
        $deleteID->delete();
    }

    /**
     * @return Factory|View
     */
    public function render()
    {
        $this->searchList = Tag::where('schlagwort', 'like', '%' . $this->searchInput . '%')
            ->orderBy('created_at', 'desc')
            ->paginate($this->pagination);

        return view('livewire.tags.tag-edit', [
            'searchList' => $this->searchList,
        ]);
    }
}

```
View:
```
<div>
    <div class="text-left mb-5">
        <label for="labelSchlagwort" class="font-weight-bold">Schlagwort Suchen:</label>
        <input class="form-control" placeholder="Schlagwort Suchen" type="text" wire:model="searchInput">
    </div>

    @if($searchList->total() > 0)
        {{ $searchList->links() }}
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th scope="col" class="text-left">Schlagwort</th>
                <th scope="col" class="text-left">Angelegt am</th>
                <th scope="col" class="text-left"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($searchList as $searchedItem)
                <tr>
                    <td class="text-left">{{ $searchedItem->schlagwort }}</td>
                    <td class="text-left">{{ $searchedItem->created_at }}</td>
                    <td class="text-left">
                        <button class="btn btn-success">Editieren</button>
                        <button class="btn btn-danger" wire:click="deleteTags({{ $searchedItem->id }})">Löschen</button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $searchList->links() }}
    @endif
</div>

```

**Comment by ManojKiranA** [comment]
I think its not bug in in Livewire or i don't think it's a bug or Expected behaviuor.

So here is the situation:

1. You have 10 Records in the Table and You have paginated that Data as **15** as Perpage Data
 For Example : 
 `Post::query()->->paginate(15,['*'],'postPage');`

2. In this situation we won't have Pagination.

3. But What of the user manually Enters the url as  

`http://example.com/posts?postPage=5`

So in this situation there will be no data returned because we don't have data for 5th page so we need to jump to first page to see the data so it will display the pagination with first page url

This behaviour is followed in Laravel Not in the livewire i think.

If you think it is a bug kindly open a issue in laravel/framework Rrepo too.

Hope i have explained it

**Comment by K2ouMais** [comment]
The problem here is, the user is not typing the URL.

I am searching for a value and that result count is smaller than the wanted values on the page.

It still shows the pagination and the searched value dont show up.

I am not sure if this is a Livewire problem or if comes directly from Laravel Framework.

**Comment by K2ouMais** [comment]
This is what I found out.

When on page 1 and searching, it seems I get results in the Collection. This is working as expected here.

However when searching on a page > 1, seems that the Collection is empty.

It still has a total of 1 and the pagination shows up, but the Collection is definitly empty.

**Comment by linuxjuggler** [comment]
the simplest solution will be to reset your pagination when you are searching for something, this way you make sure it will always be on page one.

**Comment by K2ouMais** [comment]
Is there an easy way to reset pagination??

**Comment by nuernbergerA** [comment]
Set page to 1 everytime `$searchInput` gets updated

```php
public functon updatingSearchInput()
{
     $this->gotoPage(1);
}
```

**Comment by linuxjuggler** [comment]
you can pass the current page to the `paginate` function 

```php
public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
```

Check the function definition here https://github.com/laravel/framework/blob/795660e6b09e7be2fe7463ab0af6bb9f6cd0b2aa/src/Illuminate/Database/Eloquent/Builder.php#L716-L741

**Comment by ManojKiranA** [comment]
> The problem here is, the user is not typing the URL.

For Example if you are the **10th page** of the list and if you start searching for data it will start reducing but still the **page number remains the same** 

Even though User is not typing the url  the state will be preserved.

so you are still in **10th page even after searching**

**Comment by ManojKiranA** [comment]
> Set page to 1 everytime `$searchInput` gets

may be this will help you

**Comment by dircm** [comment]
The same behaviour is present in the calebporzio/laracasts-livewire-datatable demonstration.  Searching on a name after paging through past a number of pages will result in an empty list. 
 Starting the search from page 1 hides this behaviour.  @ManojKiranA sugestion is a sound one.  I'll give that a try in the laracasts-livewire-datatable soon.

**Comment by K2ouMais** [comment]
> Set page to 1 everytime `$searchInput` gets [updated](https://laravel-livewire.com/docs/lifecycle-hooks/)
> 
> ```
> public functon updatingSearchInput()
> {
>      $this->gotoPage(1);
> }
> ```

You just saved me a lot of work.

That works perfectly.

Thank you very much

**Comment by ManojKiranA** [comment]
I just Created a little handy function so that we can minimize the function 


```
public function updating($name, $value)
    {
        //list of Property changes in which that
        //page number needs to be set to 
        //first page

        $changePagintionToOne = [
            'search',
        ];

            if(in_array($name,$changePagintionToOne)):
                $this->gotoPage(1);
            endif;
        return;
    }
```

Hope its Helps.

**Comment by calebporzio** [comment]
Thanks for the good suggestions here. Closing this because I'm not sure this is something that the WithPagination can offer automatically. Let me know if you disagree.

**Comment by ManojKiranA** [comment]
if there is Some Property such as

```
public $resetPaginaation = [
        'updating' => ['search','blablah'],
        'updated' => ['someUpdatedProps','blablah'],
    ];
```

Just a Suggestion.

**Comment by calebporzio** [comment]
Hmm, I'd rather provide docs than add a new property. Would welcome a PR to the docs for this functionality in the "pagination" section.
