### ISSUE TITLE
Binding Inputs to Relationship Properties

### ISSUE THREAD

**Issue by benjibee** [livewire/livewire#5092]
## Description
Attempting to bind a model as a relation in a Livewire component doesn't work as expected if the relation is camel cased.

It seems that `toArray()` is called on model relations which by default converts these relations from camel case to snake case. This results in a mismatch when adding rules for these bound models

## Example
I have a `rentalCar` entity that has a relationship with `rentalCarReturnFee` entities.

```php
    public RentalCar $rentalCar;

    protected $rules = [
        'rentalCar.rentalCarReturnFees.*.fee' => ['required', 'int'],
        'rentalCar.rentalCarReturnFees.*.pick_up_location_id' => ['required'],
        'rentalCar.rentalCarReturnFees.*.drop_off_location_id' => ['required'],
    ];
```

Attempting to bind inputs in the Blade file is not working as expected.

```blade
@foreach($rentalCar->rentalCarReturnFees as $index => $rentalCarReturnFee)

    {{-- Works. --}}
    @dump($rentalCar->rentalCarReturnFees[$index]->fee)

    {{-- Not bound. --}}
     <input type="text" wire:model.lazy="rentalCar.rentalCarReturnFees.{{ $index }}.fee">

@endforeach
```

## Partial workaround

Changing both the rules and the model in the Blade file binds the data, but they no longer match the relation name and cannot be saved.

```php
    public RentalCar $rentalCar;

    protected $rules = [
        'rentalCar.rental_car_return_fees.*.fee' => ['required', 'int'],
        'rentalCar.rental_car_return_fees.*.pick_up_location_id' => ['required'],
        'rentalCar.rental_car_return_fees.*.drop_off_location_id' => ['required'],
    ];
```

Attempting to bind inputs in the Blade file is not working as expected.

```blade
@foreach($rentalCar->rentalCarReturnFees as $index => $rentalCarReturnFee)

    {{--Bound but cannot be updated. --}}
     <input type="text" wire:model.lazy="rentalCar.rental_car_return_fees.{{ $index }}.fee">

@endforeach
```

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
