### ISSUE TITLE
The livewire component can't re-render after submit with invalid data

### ISSUE THREAD

**Issue by HuyNguyen206** [livewire/livewire#5094]
### Discussed in https://github.com/livewire/livewire/discussions/5082

<div type='discussions-op-text'>

<sup>Originally posted by **HuyNguyen206** July  2, 2022</sup>
I have a livewire component that contains a form, when the user clicks on submit, it will update the data
But in case, the data is invalid, the livewire component seems can't rerender again
This is the code for view, update
![image](https://user-images.githubusercontent.com/30259638/176986021-c2df5803-0ac9-404f-bd25-f08457f60d9a.png)
![image](https://user-images.githubusercontent.com/30259638/176986026-704ccd0a-1fd9-4a47-bda5-72065347a3b4.png)

In the element in debug browser bar
![image](https://user-images.githubusercontent.com/30259638/176986042-a143c26b-d4cf-48f6-bc0f-f83f3e58de96.png)
I am not sure how to resolve it

Thanks in advance</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
