### ISSUE TITLE
route:cache does not work

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#51]
**Describe the bug**
Livewire route uses a closure. 

**To Reproduce**
type php artisan route:cache on the command line

**Additional context**
 php artisan route:cache
Route cache cleared!

   LogicException  : Unable to prepare route [livewire/livewire.js] for serialization. Uses Closure.

**Comment by dylanmichaelryan** [comment]
Still not working for me

**Comment by lancepioch** [comment]
@dylanmichaelryan Which version of Livewire are you using? Is it the exact same error?

**Comment by dylanmichaelryan** [comment]
Latest version of Livewire, same error yup

**Comment by lancepioch** [comment]
Regardless if this is still broken or not, we should add a test to confirm that the route caching works when using a livewire closure.

**Comment by calebporzio** [comment]
Re-opened. Would welcome a PR for the fix. Thanks!

**Comment by nuernbergerA** [comment]
@dylanmichaelryan i tried to reproduce your problem as followed:

1. ```composer create-project --prefer-dist laravel/laravel cachedroutes```
2. ```cd cachedroutes```
3. ```composer require livewire/livewire```
4. ```php artisan route:cache```

This will fail because laravel routes come with closures, after removing the default routes its cacheable. I assume its not an livewire related issue.

**Comment by chrysanthos** [comment]
> @dylanmichaelryan i tried to reproduce your problem as followed:
> 
> 1. `composer create-project --prefer-dist laravel/laravel cachedroutes`
> 2. `cd cachedroutes`
> 3. `composer require livewire/livewire`
> 4. `php artisan route:cache`
> 
> This will fail because laravel routes come with closures, after removing the default routes its cacheable. I assume its not an livewire related issue.

@dylanmichaelryan Just FYI, I think this wouldn't work without livewire installed since laravel comes with route closures included in the `routes/web.php` etc.

**Comment by thiagolcks** [comment]
Still not working here.

**Comment by cosmospham** [comment]
This error still exists

**Comment by nuernbergerA** [comment]
@thiagolcks  and @cosmospham
Please feel free to open a new issue with more details instead of posting in old and closed issues.

Make sure to include steps to reproduce and code if needed.

Cheers

**Comment by devcircus** [comment]
Yes, Laravel comes with a couple of sample routes as an example, that use closures. These must be removed or changed to not use closures if you want to cache your routes. Without third party libraries, php doesn't serialize closures. 

I believe there is an open PR on laravel right now that is considering options to cache closure-based routes.
