### ISSUE TITLE
Conditional content don't charge alpine

### ISSUE THREAD

**Issue by SamuelBoudine** [livewire/livewire#5187]
### Discussed in https://github.com/livewire/livewire/discussions/5186

<div type='discussions-op-text'>

<sup>Originally posted by **SamuelBoudine** August 18, 2022</sup>
Hello, so voila, I have a livewire component that contains an alpine.js component in an @if. My problem is that my x-data in my @if doesn't load even after my @if is true.

speed exemple : 

```html

@if($song)
       <div x-data="songData">
            @push('scripts')
        <script defer>
            document.addEventListener('alpine:init', () => {
                Alpine.data('songData', () => ({
                    variable1: 'hello',
                    fnnumero1(name) {
                        this.variable1 = name;
                    },
                }))
            })
        </script>
          ...
    @endpush
       </div>
@endif
```
error : Alpine Expression Error: songData is not defined
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
