### ISSUE TITLE
Defer Loading - On wire:init add ability to target that event for loading wire:target="init"

### ISSUE THREAD

**Issue by eckelarsson** [livewire/livewire#526]
**Is your feature request related to a problem? Please describe.**
When you do a defer loading `<div wire:init="getData">` I would like to be able to target a loading action just for that event. You don't always need a loading screen on other types of actions within that component.

**Describe the solution you'd like**
```
<div wire:init="getData">
    <div wire:loading wire:target="init">Loading...</div>
</div>
```

**Comment by calebporzio** [comment]
This is already possible, you can reference the action for the loading indicator:

```html
<div wire:init="getData">
    <div wire:loading wire:target="getData">Loading...</div>
</div>
```
