### ISSUE TITLE
alpine x-model on loop appending duplicates

### ISSUE THREAD

**Issue by marufdevops** [livewire/livewire#5371]
### Discussed in https://github.com/livewire/livewire/discussions/5370

<div type='discussions-op-text'>

<sup>Originally posted by **marufdevops** November 18, 2022</sup>
### Description:
when using alpine x-model with livewire it is appending duplicate value to alpine array when checked. 

###Implementation:
1. passing a protected paginated collection to view
![Screen Shot 2022-11-18 at 6 35 31 PM](https://user-images.githubusercontent.com/56079318/202706268-44766936-9063-4d19-860b-eb25e1e319e8.png)

2. initiating the component method to fetch actual data using wire:init and declaring a selectedUsers: [] alpine property
3. looping through the paginated collections with an input type checkbox binding it to selectedUsers. I have places wire:key within the loop
![Screen Shot 2022-11-18 at 6 40 24 PM](https://user-images.githubusercontent.com/56079318/202707166-8dee4c4c-0585-4150-8560-f7c4008b5077.png)
![Screen Shot 2022-11-18 at 6 40 09 PM](https://user-images.githubusercontent.com/56079318/202707246-bbb04a64-377c-4409-8f1e-0f79b3e2fb59.png)
4. It produces duplicates like this:
<img width="285" alt="Screen Shot 2022-11-18 at 6 44 04 PM" src="https://user-images.githubusercontent.com/56079318/202707918-7e876456-4933-46c4-ae06-f2e6719f12c4.png">

###Context 

- Livewire version: "livewire/livewire": "^2.10"
- Laravel version: "laravel/framework": "^9.0"
- alpinejs@3.8.1</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
