### ISSUE TITLE
AlpineJs directives not working after component is reloaded

### ISSUE THREAD

**Issue by pmartelletti** [livewire/livewire#544]
**Describe the bug**
Hi @calebporzio  - I'm currently experiencing a weird bug, but I'm not sure if should be raised here or in alpine, so apologize if raised in the wrong place.

So, basically, I have a livewire component that, as part of the HTML it renders, it has a tooltip that uses alpine x-show to display/hide on mouseover. Something like:

```html
<span class="inline-block cursor-pointer relative" x-data="{showTooltip: false}" @mouseenter="showTooltip = true" @mouseleave="showTooltip = false">
    <span x-show="showTooltip" class="absolute h-6 w-20 bottom-0 left-0 -mx-20 -my-1 text-white bg-gray-800 px-2 py-1 text-center text-xs font-semibold opacity-75 rounded ">
        {{ $priority }}
    </span>
</span>
```

The first time the page is rendered, everything works as expected. However, once the component is reloaded, all the spans that have x-show will ignore that showTooltip is false and show instead, and there's no way to hide them. 

I've tried hiding them by default with tailwinds, but then x-show won't work.

From the docs, I can see that:

> Please note that your scripts will be run only once upon the first render of the component. If you need to run a JavaScript function later - emit the event from the component and listen to it in JavaScript as described here)

Does that mean that alpine will work only the first time the component is rendered?

**Comment by cytRasch** [comment]
Same here.


The Livewire component:
```php
...

public $selectedLoan;

...

public function render()
{
       return view('livewire.admin.loan', [
           'employees'    => \App\Employee::with([
            'loans' => function ( $query )
            {

                $query->withoutGlobalScope('activeLoan')->where('active_from', $this->selectedLoan);
            }
           ])->get(),
       ]);
}
```

First part of the template where you can choose between some options:
```html
<select wire:model="selectedLoan"  class="form-select mt-1 block w-full">
    @foreach($activeValues as $value)
         <option value="{{ $value->active_from }}">{{ carbon($value->active_from)->format('d.m.Y') }}</option>
    @endforeach
</select>
```

The iteration and the alpine stuff:
```html

...

@foreach($employees as $employee)
     <tr class="{{ $loop->last ? '' : 'border-b' }}" x-data="{ edit: false }" x-bind:class="edit ? 'bg-gray-200' : ''" x-cloak>
        <td class="py-4 pl-2 pr-2">
             <span x-show="!edit" class="rounded-b bg-red-100 text-sm p-3 border-t-2 border-red-400 text-red-400 font-bold cursor-pointer">{{ __('missing') }} </span>
             <input x-show="edit" wire:change="setLoan($event.target.value, {{ $employee->id }})" class="p-2 bg-white m-0 rounded" type="text" placeholder="12,00"/>
         </td>
    </tr>
@endforeach
```

When changing the select field the employee part is re-rendered by Livewire with some new data and everything is hidden (beacause of ```x-cloak```) but the directives are not working anymore, too.

Hope there is a proper solution to get around with this.

**Comment by ryatkins** [comment]
I would like to be able to mix and match Livewire and Alpine as well, but I've had to resort to adding `wire:ignore` to my Alpine elements that don't require Livewire data.

@pmartelletti - can't this be easily turned into a Livewire controlled element instead?

Create a public property on your Livewire component and two methods to toggle the state:
`public $toolTip = false;`

```
<span class="inline-block cursor-pointer relative" 
            wire:mouseenter="showTooltip" 
            wire:mouseleave="hideTooltip">
  @if($this->toolTip)
    <span class="absolute h-6 w-20 bottom-0 left-0 -mx-20 -my-1 text-white bg-gray-800 px-2 py-1 text-center text-xs font-semibold opacity-75 rounded ">
        {{ $priority }}
    </span>
  @endif
</span>
```

**Comment by pmartelletti** [comment]
@ryatkins yeah, but that would mean I'd have to create a new livewire component. This is a table I'm rendering, so seems a bit stupid to render a "row" component, as it won't be doing much logic + I'd be losing the pagination ability that Livewire has built-in.

**Comment by ryatkins** [comment]
So where does $priority come from?
If it's not driven from your Livewire component, can you use `wire:ignore`?

**Comment by pmartelletti** [comment]
@ryatkins what I've posted here it's a blade partial, so basically that comes from doing `$incident->priority`. My livewire component has a list of incidents. So, yeah, priority is coming from livewire, unfortunately.

**Comment by ryatkins** [comment]
And you can't use that Livewire component to manage the state of that tool tip?

**Comment by ryatkins** [comment]
Agreed, I'd like to use Alpine for this as well.  Just hoping this could be a good path until Laravel/Alpine integration gets better sorted. 

If $priority is staying static, not changing on an Ajax call - what happens if you put wire:ignore on your parent span?

**Comment by pmartelletti** [comment]
@ryatkins @calebporzio I've fixed this by setting display: hidden using inline CSS to that div. I'm happy with this workaround for now. :)

**Comment by lucasromanojf** [comment]
I have the same issue with x-bind:class. After Livewire reloads, x-bind:class is ignored.

**Comment by dwyer14** [comment]
Wondering if this might be related to Vue components not working inside a Blade `@if` statement. The conditional I'm using (inside a Livewire component) is initially `false`. When Livewire updates so the `@if` is `true` the Vue component is never rendered. ie, it just sits in the dom as `<my-component>`.

**Comment by lucasromanojf** [comment]
> I have the same issue with x-bind:class. After Livewire reloads, x-bind:class is ignored.

UPDATE: If I put wire:ignore on my Alpine component, it works as expected and does not lose x-bind:class anymore.

**Comment by lucasromanojf** [comment]
I can confirm that this issue was solved for me by using https://github.com/livewire/alpine-plugin

Thanks @calebporzio !

**Comment by calebporzio** [comment]
Great!

**Comment by cytRasch** [comment]
Thanks @calebporzio. Great job. Keep going🤙🏼
