### ISSUE TITLE
[Feature] decouple JS part from laravel

### ISSUE THREAD

**Issue by zodman** [livewire/livewire#546]
I want to implement livewire on django or someone else could implement on rails

I know this is hard and hurt ...

**Comment by calebporzio** [comment]
Yeah, definitely going to be hard. I'd be willing to tweak the codebase to make this easier for you (like decoupling the JS more), but I'm not going to do any of that until there is a working version of Livewire working in another framework.

I think there is definitely potential here, but supporting other platforms is not really a goal for this project right now.

Closing for now, but feel free to ask questions here and I'll try to help you out.
