### ISSUE TITLE
Nested Component Reactivity Issue

### ISSUE THREAD

**Issue by idoko-emmanuel** [livewire/livewire#5475]
### Discussed in https://github.com/livewire/livewire/discussions/5474

<div type='discussions-op-text'>

<sup>Originally posted by **idoko-emmanuel** December 30, 2022</sup>
I'm trying to create roles using modals as nested component, the modal unmount from the DOM when I try to pass properties from my class to the component. I've used wire:ignore.self on the modal but I'm still getting the same error. I have done a search for similar discussion and couldn't find any help. This is an old project and I'm trying to implement livewire in it, I have implemented nested components in previous projects and it works fine. Can you please assist. 

I'm making use of  Bootstrap v3.3.7, jQuery v2.1.4, 

Below is my composer.json file

   {
            "name": "laravel/laravel",

          "description": "The Laravel Framework.",

          "keywords": ["framework", "laravel"],

          "license": "MIT",
          "type": "project",
          "require": {
              "php": "^7.3|^8.0",
              "fideloper/proxy": "^4.4",
              "laravel/framework": "9.0",
              "laravel/helpers": "^1.5",
              "laravel/tinker": "^2.5",
              "laravel/ui": "^3.3",
              "livewire/livewire": "^2.10",
              "pusher/pusher-php-server": "^7.0",
              "spatie/laravel-permission": "^5.7",
              "symfony/var-dumper": "^6.0"
          },
          "require-dev": {
              "filp/whoops": "~2.0",
              "fzaninotto/faker": "^1.9",
              "mockery/mockery": "^1.4.2",
              "phpunit/phpunit": "^9.3.3"
          },
          "autoload": {
              "classmap": [
                  "database",
                  "app/Http/DotEnvEditor"
              ],
              "psr-4": {
                  "App\\": "app/",
                  "Database\\Factories\\": "database/factories/",
                  "Database\\Seeders\\": "database/seeders/"
              }
          },
          "autoload-dev": {
              "psr-4": {
                  "Tests\\": "tests/"
              }
          },
          "scripts": {
              "post-root-package-install": [
                  "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
              ],
              "post-create-project-cmd": [
                  "@php artisan key:generate--ansi"
              ],
              "post-autoload-dump": [
                  "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
                  "@php artisan package:discover"
              ]
          },
          "extra": {
              "laravel": {
                  "dont-discover": [
                  ]
              }
          },   
          "config": {
              "preferred-install": "dist",
              "sort-packages": true,
              "optimize-autoloader": true
          },
          "minimum-stability": "dev",
          "prefer-stable": true
}

Below is my parent component

      <div>
       
          <div class="row">
              <div class="col-sm-12">
                  <div class="btn-group pull-right m-t-30 m-r-5">
                      <a href="{{url('/all-employee')}}" class="btn btn-default waves-effect">
                      All Employee
                      </a>
                  </div>
      
                  <h4 class="page-title">Assign roles </h4>
                  <ol class="breadcrumb">
                      <li>
                          <a href="{{url('/')}}">Home</a>
                      </li>
                      <li class="active">
                          Employee
                      </li>
                      <li class="active">
                          Assign roles
                      </li>
                  </ol>
              </div>
          </div>
          <div class="row">
              <div class="col-sm-12">
                  <div class="card-box">
                  <div class="card">
                      <div class="card-header"></div>
              
                      <div class="card-body">
                          
                          <a href="{{ url('/add-employee') }}" class="btn btn-primary btn-gold">Add New User</a>
                          <button type="button" class="btn btn-primary btn-gold" data-toggle="modal" wire:click="createrole">
                              Create Roles
                          </button>
              
                          <br /><br />
              
                          <style>
                              .card-modal{
                                  background-color: transparent;
                                  color: black;
                              }
                              .bg-gold{
                                  background-color: goldenrod;
                                  color: white;
                              }
                              tbody{
                                  color:black
                              }
                          </style>  
                      
              
                          <table class="table table-hover table-borderless">
                              <tr class="bg-gold ">
                                  
                                  <th class="text-center bg-gold">Role Names</th>
                                  <th class=" bg-gold">Number of users</th>
                                  <th class="bg-gold">
                                      Action
                                  </th>
                                  
                              </tr>
                              @foreach ($roles as $role)
                                  <tr >
                                  <td class="text-center">{{ ucfirst($role->name) }}</td>
                                  <td>{{ \App\User::role($role->name)->count()}}</td>
                                  <td>
                                          <button data-toggle="modal" id="smallButton" wire:click="editrole({{ $role->id }})" title="Edit">
                                              <i class="glyphicon glyphicon-edit"></I>
                                          </button>
      
                                          <button class="text-secondary" data-toggle="modal" id="mediumButton" data-target="#mRole" title="Manage">
                                              <i class="glyphicon glyphicon-cog"></I>
                                          </button>
                                          
                                          <button type="submit" title="delete">
                                              <i class="glyphicon glyphicon-trash text-danger"></I>
                                          </button>
                                  </td>
                              </tr> 
                              @endforeach  
                              <tr>
                                  <td colspan="100%" class="text-center text-muted py-3">{{ ("No Roles Found") }}</td>
                              </tr>
                              
                          </table>      
                                    
                          {{-- <livewire:modals.edit-role/> --}}
                          <br><br>
                          
                      </div>
                  </div>
                  </div>
              </div>
              </div>
          </div>
          </div>
          </div>     
          </div>
          </div>
          </div>
          </div>
          @push('modals')
              <livewire:modals.create-role />
          
              <livewire:modals.edit-role />
      
              <livewire:modals.manage-role />
          @endpush
</div>

below is my parent class 
                  <?php
                  
                  namespace App\Http\Livewire;
                  
                  use Livewire\Component;
                  use Spatie\Permission\Models\Role;
                  
                  class UserManagement extends Component
                  {
                      public function createrole()
                      {
                          $this->emitTo('modals.create-role','createRole');
                      }
                      public function editrole($id)
                      {
                          $this->emitTo('modals.edit-role','editRole', $id);
                      }
                      public function managerole($id)
                      {
                          $this->emitTo('modals.manage-role', $id);
                      }
                      public function render()
                      {
                          $roles = Role::all();
                          return view('livewire.user-management', compact('roles'));
                      }
                  }

Below is my child class
                <?php
                
                namespace App\Http\Livewire\Modals;
                
                use Livewire\Component;
                use Spatie\Permission\Models\Role;
                
                class EditRole extends Component
                {
                    protected $listeners = ['editRole'];
                
                    public $role;
                
                    public function editRole($id)
                    {
                        $this->role = Role::find($id);
                        $this->dispatchBrowserEvent('openModal', ['id' => '#eRole']);
                    }
                
                    public function render()
                    {
                        return view('livewire.modals.edit-role');
                    }
                }

Below is my child component

                
                <div wire:ignore.self class="modal fade" id="eRole" tabindex="-1" role="dialog" aria-labelledby="eRole" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                            @if($role) works @endif //This line causes the error
                            <div  class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="eRole">  </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="card-modal">
                                        <div class="card-header">Header</div>
                                
                                        <div class="card-body">
                                            <form method="POST" action="{{ ('#') }}">
                                                @csrf
                                
                                                <div class="form-group row">
                                                    <label for="title" class="required col-md-4 col-form-label text-md-right">Role Name</label>
                                
                                                    <div class="col-md-6">
                                                        <input id="title" type="text" class="form-control" name="role-name" value="" required autocomplete="role-name">
                                
                                                        
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>Error Message failed role name</strong>
                                                            </span>
                                                        
                                                    </div>
                                                </div>
                                
                                            </form>
                                        </div>
                                    </div> 
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Save changes</button>
                                </div>
                            </div>
                        
                    </div>
                </div>

And below is my event handler

           $(function(){ 
                    window.addEventListener('closeModal', event => {
                        $(event.detail.id).modal('hide');
                        $(event.detail.id).removeClass('in');
                    });
            
                    window.addEventListener('openModal', event => {
                        $(event.detail.id).on('shown.bs.modal', function () {
                            $(event.detail.id).addClass('in');
                            $(event.detail.id).removeClass('show');
                        }).modal('show');
                    });
                    $('.modal').on('click', '[data-dismiss="modal"]', function() {
                        $('.modal').modal('hide');
                    });
           });</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
