### ISSUE TITLE
How to deal with "dynamic input checkbox name"?

### ISSUE THREAD

**Issue by brocorp-dev** [livewire/livewire#549]
Hi guys, 

I've spend my afternoon to deal with "dynamic input checkbox name", I mean if a checkbox dynamically generated by a loop is checked or not. I don't know how to achieve that with Livewire.

Usually, with Laravel I do something (ugly) like that:

**view**
```
@foreach ($options as $option)
    <label for="option-{{ $option->id }}">
        <input type="checkbox" name="option-{{ $option->id }}">
        {{ $option->name }} - {{ $option->price }}€
    </label>
@endforeach
```

**controller**
```
foreach ($options as $option) {
    if ($request->input('option-' . $option->id) == "on") {
        $model->options()->attach($option->id);
    }
}
```

but with Livewire, I tried that, 'cause we need to "declare manually" public property and I thought putting up an array was a good idea for "dynamic property naming":

**resources / views /  livewire / subscription-create.blade.php**
```
@foreach ($office->options()->get() as $option)
    <label>
        <input type="checkbox" wire:model="option_value[{{ $option->id }}]">
            {{ $option->name }} - {{ $option->price }}€
    </label>
@endforeach
```

**App / Http / Livewire / SusbcriptionCreate.php**
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

use App\Office;

class SubscriptionCreate extends Component
{
    public $office_id = 1; // 
    public $option_value = []; 

    public function updated()
    {
        // the missing logic to retrieve $option_value and do some fancy stuff with it
    }

    public function render()
    {
        return view('livewire.subscription-create', [
            'office' => Office::active()->find($this->office_id),
        ]);
    }
}
```

but from this point, I have this error
```
**Livewire\Exceptions\PublicPropertyNotFoundException**
Unable to set component data. Public property [$option_value[1]] not found on component: [subscription-create]
```

So, I guess the public var $option_value = []; isn't enough, right? What I'm missing? 

Thanks for your help!
Fred

**Comment by snapey** [comment]
wire:bind on a checkbox seems to only return 1 or zero, and not an value set by attribute.

Working example https://forum.laravel-livewire.com/t/unable-to-get-checkbox-value/157/7?u=snapey

**Comment by brocorp-dev** [comment]
Hi @snapey, 

Thanks for your reply, the fact is I don't struggle with the value returned, but how to name correctly the wire:model. And I founded a response in your working example, the only way was to use the dot notation whit a key for the wire:model, just like this:


**resources / views / livewire / subscription-create.blade.php**
```
@foreach ($options_list as $key => $option_data)
<label for="option_{{ $option_data->id }}">
    <input type="checkbox" wire:model="options.{{ $option_data->id }}" id="option_{{ $option_data->id }}" >
    {{ $option_data->name }}
</label>
@endforeach
```


**App / Http / Livewire / SusbcriptionCreate.php**
```
<?php

namespace App\Http\Livewire;

use Illuminate\Database\Eloquent\Builder;

use Livewire\Component;

class SubscriptionCreate extends Component
{
    public $options = [];

    public function submit()
    {
        // some lot of stuff before

       foreach ($this->options as $key => $checked) {
            if ($checked) 
            { 
                $option = Option::find($key);
                $domiciliation->options()->attach($option->id); 
            }
        }
    }

    public function render()
    {
        return view('livewire.subscription-create', [
            'options_list' => Office::find($this->office_id)->options()->get(),
        ]);
    }
}
```

Works like a charm!
Thanks to you!

**Comment by sineld** [comment]
I wrote a helper function to handle this issue:

    if (!function_exists('array_to_dots')) {
        /**
         * Used to convert input['tr'] to input.tr dot notaion
         *
         * @param $array
         * @return string
         */
        function array_to_dots($array)
        {
            return str_replace(
                ['[', ']'],
                ['.', ''],
                $array
            );
        }
    }

Usage:

    'wire:model'.(isset($lazy) ? '.lazy': '') => array_to_dots($field),
