### ISSUE TITLE
Query string - ability to add paginator $page to $updatesQueryString

### ISSUE THREAD

**Issue by ryatkins** [livewire/livewire#552]
**Is your feature request related to a problem? Please describe.**
When pagination is enabled, need to be able to append $page to the query string

**Describe the solution you'd like**
protected $updatesQueryString = ['page'];

**Result**
?page=1

**Bonus**
Be able to register properties that when updated returns page back to 1 per this [issue](https://github.com/livewire/livewire/issues/509).  Perhaps it can be part of this [API](https://github.com/livewire/livewire/issues/550)

**Comment by calebporzio** [comment]
Yep, this is coming.

**Comment by ManojKiranA** [comment]
> Yep, this is coming.

```
User::query()
->paginate(10,['*'],'customPageName');
```

So while paginating `domain.com/users?customPageName=12` will be the url right??

**Comment by calebporzio** [comment]
The customPageName wouldn't work given the current WithPagination implementation. 

The original issue has been fixed, closing.
