### ISSUE TITLE
Livewire Message 404

### ISSUE THREAD

**Issue by striker4150** [livewire/livewire#5558]
### Discussed in https://github.com/livewire/livewire/discussions/5557

<div type='discussions-op-text'>

<sup>Originally posted by **striker4150** February 15, 2023</sup>
Hi guys,

This requires a bit of background explanation. I'm running Laravel 10 with Vite and Livewire. It's being run in a subdirectory, behind a reverse proxy (e.g. `http://www.mydomain.com/subdir/project` -> `http://192.168.x.x:8083/subdir/project/public`). Here are the configurations I made to do so:

Apache
```
ProxyPass /subdir/project http://192.168.x.x:8083/subdir/project/public
ProxyPassReverse /subdir/project http://192.168.x.x:8083/subdir/project/public
```

.env
```
APP_URL=http://www.mydomain.com/subdir/project
ASSET_URL=/subdir/project
LIVEWIRE_ASSET_URL=/subdir/project
```

vite.config.js
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    base: '/subdir/project/build/',
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});
```

AppServiceProvider.php
```php
/**
 * Bootstrap any application services.
 */
public function boot(): void {
    URL::forceRootUrl(config('app.url'));
}
```

I'm trying to use the Laravel-Table library's "Table" livewire component, but the livewire POST request to `http://www.mydomain.com/subdir/project/livewire/message/table` is 404'ing. Any ideas on what might be causing this? Everything else seems to be routed correctly, including `http://www.mydomain.com/subdir/project/livewire/livewire.js`.

![Network Requests](https://user-images.githubusercontent.com/8561358/219224112-f2d97e24-4f9b-483f-8c38-08521827db52.png)

![Website](https://user-images.githubusercontent.com/8561358/219224120-864fddf8-64fc-4cb6-8184-fdbdc38623e4.png)
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
