### ISSUE TITLE
CSV file with unicode characters stored as question marks ?

### ISSUE THREAD

**Issue by oitcode** [livewire/livewire#5563]
### Discussed in https://github.com/livewire/livewire/discussions/5562

<div type='discussions-op-text'>

<sup>Originally posted by **oitcode** February 18, 2023</sup>
I have below code to store the csv uploaded from front end.

```$this->filePath = `$this->members_file->store('csvImports');```

The file being uploaded is a csv file with many unicode utf-8 characters. However in the uploaded file all the unicode characters are stored as a question mark `?`. 

Please look into it. Or am i doing something wrong. Is there any parameter to store method to specify if characters as unicode?
</div>

**Comment by jamesautodude** [comment]
I believe you have to make sure your database is set to UTF-8 for it to accept that. Make sure your tables & main database is all UTF-8 including the columns

Unless you mean the file being put into laravels storage?

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by oitcode** [comment]
Yes I mean file is being put into laravels storage. When i check the file in the server by logging into it I see that all the characters are being stored as question marks.

Database utf8 is not an issue. Issue is with laravel storage.
