### ISSUE TITLE
Method `back()` doesn't work

### ISSUE THREAD

**Issue by kot13** [livewire/livewire#557]
**Describe the bug**
Method `back()` doesn't work

**To Reproduce**
1. Install latest Laravel and latest livewire (0.7.0)
2. Create livewire component `$ php artisan make:livewire test`
3. Update view `resources/views/livewire/test.blade.php`:
```
<div>
    <div>
        <button wire:click="test()">Test</button>
    </div>
</div>
```
4. Update component class `app/Http/Livewire/Test.php`:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public function render()
    {
        return view('livewire.test');
    }

    public function test()
    {
        back();
    }
}
```

**Expected behavior**
Redirect to previous page doesn't work.
Response:
```
{
	"id": "ChyHiUtwU7ZcxeewP5D5",
	"name": "test",
	"dom": "<div wire:id=\"ChyHiUtwU7ZcxeewP5D5\">\n    <div>\n        <button wire:click=\"test()\">Test<\/button>\n    <\/div>\n<\/div>\n",
	"fromPrefetch": false,
	"redirectTo": false,
	"dirtyInputs": [],
	"children": [],
	"data": [],
	"eventQueue": [],
	"dispatchQueue": [],
	"events": [],
	"checksum": "0ac48a19ca14208a88c7b30bf33dc9afdf5412c3a479deff0a2f5e289a011d36"
}
```

**Desktop (please complete the following information):**
 - Browser is any: FF, Chrome, Safari and etc.

**Comment by xxdalexx** [comment]
Not a bug, the docs https://laravel-livewire.com/docs/render-method/ state back() will not work in livewire. It uses the previous url stored in the session, so when you hit a livewire route, the previous is now the same page you have been on, so you're basically reloading the page trying to use it..

However, if you grab that session variable in your mount method, with something like `$this->previous = URL::previous();` and then do a `return redirect($this->previous);` in your back() method, it should work. It would have to be the mount() method on a component that is loaded in the initial page load. 

I haven't actually tested this, but I don't see why it wouldn't work.

**Comment by kot13** [comment]
Thanks for the advice!
I wonder why then a `redirect()` works?!

**Comment by xxdalexx** [comment]
It's not that the action itself doesn't work, It has to do with how laravel keeps track of what the last page was to be able to go back to that page. Simply Livewire screws that tracking up, so laravel doesn't know what that previous page is anymore.
