### ISSUE TITLE
A big integer with 19 digits rounded to the sixteenth digit during hydration

### ISSUE THREAD

**Issue by helloiamjohnsmith** [livewire/livewire#558]
**Describe the bug**
If one component has a big integer property with 19 digits, its integrity ruins when another component causing him to rerender. Because significant part of the number is lost.

**To Reproduce**
1. Install latest Laravel and latest livewire
2. Create two livewire components 
`$ php artisan make:livewire component-one`
`$ php artisan make:livewire component-two`
3. Update component ComponentOne view
```
<div>
    <button class="btn btn-success" wire:click="$emit('test')">Test</button>
</div>
```
4. Update ComponentTwo class
```
class ComponentTwo extends Component
{
    public $bigint;

    protected $listeners = ['test' => 'testBigint'];

    public function testBigint()
    {

    }

    public function mount()
    {
        $this->bigint = 1234567890123456789;
    }

    public function render()
    {
        return view('livewire.component-two')
            ->withBigint($this->bigint);
    }
}
```
5. Update ComponentTwo view
```
<div class="mt-4">
    Bigint is {{ $bigint }}
</div>
```
6. Create arbitrary view and put code below
```
@livewire('component-one')

@livewire('component-two')
```
7. Open that view and press the button. `CorruptComponentPayloadException` will be thrown.

**Expected behavior**
Component must succesfully be rendered and `$bigint`  property must be the same.

**Desktop (please complete the following information):**
Tested on latest Chrome and Firefox

**Additional context**
If you add some log to the `SecureHydrationWithChecksum` middleware, you can see that value of the `$bigint` property in `dehydrate()` is **1234567890123456789**, but in `hydrate()` it becomes **1234567890123456800** and this is the reason why integrity check fails.

**Comment by faustbrian** [comment]
I would expect this behaviour because Livewire has to fire the data through JavaScript and your number exceeds the JavaScript Number.MAX_SAFE_INTEGER. Even without Livewire you should use libraries to work with BigInts or at least wrap them as a string instead of treating them as numbers to avoid them being modified without that being wanted, especially if JavaScript is in play.

**Comment by helloiamjohnsmith** [comment]
Yes, that's right. For now, I will have to convert numbers to strings.

**Comment by jstoks** [comment]
This issue comes up when models have large integers as IDs. Is there a way to have livewire convert ids to string without adding compatibility code to the models themselves?
