### ISSUE TITLE
Issue with bootstrap/cache folder

### ISSUE THREAD

**Issue by CharlyMollard** [livewire/livewire#5584]
### Discussed in https://github.com/livewire/livewire/discussions/5583

<div type='discussions-op-text'>

<sup>Originally posted by **CharlyMollard** February 26, 2023</sup>
Hi, my laravel project give me an error that said `The C:\Travail\Web\_Servers\BARBOFUS\bootstrap\cache directory must be present and writable.`, to clear this error I have to manually remove the cache folder and recreate it empty after each branch creation. The error occure only on the pages that contains livewire code. I tried creating a new laravel 10 project, and as soon as I installed livewire, the same issue appeared. If I do the commande `php artisan cache:clear` I got a `Failed to clear cache. Make sure you have the appropriate permissions.`.  I used livewire before (like one month ago) on the same project, and I never had this problem, it appeared after I update livewire version, but I don't know how to know what version I had before.

- composer v2.5.4
- Laravel v9.52.4
- Livewire v2.12.1
- PHP v8.2.3.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
