### ISSUE TITLE
Allow for computed properties (eg: getFooAttribute)

### ISSUE THREAD

**Issue by google-mac** [livewire/livewire#56]
Currently we can use the Livewire API to get when a property is updated (via updatedFoo) and we can use that to set another property. Using this as a way to work with computed properties seems more like a side effect instead of a first-class computed property.

I propose that we utilize a similar convention as Laravel with `getFooAttribute()` as the getter, which returns the value of that computed property. I could see some issues on making sure it is not re-computed on every render, but perhaps someone knows a way to do this. Also, it would be nice if it was just set as a public property with no assignment, along with the accessor function. No extra config needed.

```php
class Capitalization extends Component
{
    public $input = '';
    public $output;

    public function render()
    {
        return view('livewire.capitalization');
    }

    // current way
    public function updatedInput($input)
    {
        $this->ouput = strtoupper($input);
    }

    /// proposed way
    public function getOutputAttribute()
    {
        return strtoupper($this->input);
    }
}
```

**Comment by davidpiesse** [comment]
Hi @google-mac 

This makes sense to consider. I'd like to see what @calebporzio thinks of aligning it with the main framework (I know it currently aligns more so with Vue).

I'd like to discuss who is the 'owner' or 'changer' for the data. Should it be thought of as:
* When a new input is received the output value is updated; or
* An input value is stored; and then when the output value is requested it is derived from the input value on-the-fly

I think that explains the current and proposed ways.

D

**Comment by faustbrian** [comment]
@calebporzio this can probably be closed since 0.5.0 now supports computed properties.

**Comment by google-mac** [comment]
I agree. Sweet deal!

**Comment by calebporzio** [comment]
Thanks @faustbrian
