### ISSUE TITLE
wire:click only sends the last parameter

### ISSUE THREAD

**Issue by snapey** [livewire/livewire#560]
When wire:click is actioned, the network request only sends whatever is last in the parameter list.

blade;
```
<button wire:click="confirmDelete('a','b','c')"
```

Network request;
```
{"id":"RML8hMYmFd3eM3TtGuAQ","data":[],"name":"grid","checksum":"1a5d8f51f2272d0333c88ba8dad91de5f980e9af5f2caa3bb2484a65537d37b4","children":[],"actionQueue":[{"type":"callMethod","payload":{"method":"confirmDelete","params":["c"]}}]}
```
Blade;
```
<button wire:click="confirmDelete('a','b')"
```
Network;
```
{"id":"LvxbRJT9gsKGGUcg8Y6l","data":[],"name":"grid","checksum":"f95896a5cf82e4025c93b1a80758eca83d97fe969e1f101c90856f16c6cb9032","children":[],"actionQueue":[{"type":"callMethod","payload":{"method":"confirmDelete","params":["b"]}}]}
```
The complete parameter list should be sent, but only the last parameter is present in the request params

Version 0.7.0

**Comment by nuernbergerA** [comment]
Should be fixed by #551

**Comment by nuernbergerA** [comment]
@snapey can you confirm if it works with the latest release?

**Comment by snapey** [comment]
Confirmed working in v0.7.2

I don't know if this is a problem or not, but there are no errors or warnings for different number of parameters on either side.

Eg, Method expects 2 parameters, client sent one / Method expects 1 parameter, client sent 2

**Comment by snapey** [comment]
Is it reasonable for me to expect this to be sent as an array plus a string to the component?
```
wire:click="addConditionRow(['a', 'b'], 'c')"
```
Throws js error
```
Uncaught SyntaxError: Unexpected end of input
    at directive.js:54
    at Array.map (<anonymous>)
    at ElementDirective.parseOutMethodAndParams (directive.js:54)
    at ElementDirective.get method [as method] (directive.js:20)
    at node_initializer.js:135
    at Component.callAfterModelDebounce (index.js:413)
    at HTMLButtonElement.handler (node_initializer.js:127)
```

**Comment by nuernbergerA** [comment]
@snapey should work since [v0.7.3](https://github.com/livewire/livewire/releases/tag/v0.7.3)

**Comment by lancepioch** [comment]
@snapey Does the latest version resolve your issue?

**Comment by snapey** [comment]
All good now. Sorry for the delay in replying.
