### ISSUE TITLE
Livewire full page component won't work with laravel 9

### ISSUE THREAD

**Issue by tom-bowern** [livewire/livewire#5609]
### Discussed in https://github.com/livewire/livewire/discussions/5608

<div type='discussions-op-text'>

<sup>Originally posted by **tom-bowern** March  9, 2023</sup>
Following the steps here - 
https://laravel-livewire.com/docs/2.x/rendering-components#page-components

I have the code in my routes/web.php
```
use App\Http\Livewire\Admin\Access;

 Route::middleware(['user.admin'])->prefix('/admin')->group(function () {
 Route::get('/access', [Access::class]);
});

```

Im getting an error: 
```
ReflectionException
PHP 8.1.10
9.52.0
Function () does not exist
```

Presumably due to the lack of a function being passed as expected in the laravel documentation

```
"laravel/framework": "^9.11",
"laravel/jetstream": "^2.8",
"laravel/sanctum": "^2.14.1",
"laravel/socialite": "^5.5",
"laravel/tinker": "^2.7",
"livewire/livewire": "^2.5"
```</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
