### ISSUE TITLE
wire:poll on toggle-able components

### ISSUE THREAD

**Issue by ohnotnow** [livewire/livewire#563]
**Is your feature request related to a problem? Please describe.**
Just a caveat - I'm just starting out with livewire, so I may be doing something very wrong.  I'm also loaded with a cold so my brain isn't exactly 100% either. Anyway ...

I have a 'status bar' component that users can toggle on and off. The status bar uses polling to update the status.  But when they toggle to hide it the polling continues. And if they open it again it starts polling twice.  Which quite quickly becomes a bit of an issue... ;-)

**Describe the solution you'd like**
Some way of disabling/controlling polling, like `wire:poll-if="open === true"` that would cancel whatever setInterval/setTimeout kind of thing that's going on.

**Describe alternatives you've considered**
This is what I have at the top of my component just now :
```html
<div>
  @if ($status && $open)
  <div class="box has-background-white-bis" wire:poll>
    <div class="columns">
      <div class="column">
        <span class="has-text-grey">Queue</span>
        ...
```
So I guess something like :
```html
<div wire:poll-if="$open === true">
  @if ($status && $open)
  <div ....
```
I've tried to think of ways of moving the `wire:poll` higher/lower in the tree, but I can't think of anything that would do the trick.  At the moment putting it outside of the `@if` will poll even if the component isn't visible, which isn't ideal either.

**Comment by calebporzio** [comment]
I think this is something that SHOULD be handled automatically by Livewire.

We can add the "disable polling" behavior in the following two places:
* on element removal (from morphdom hook)
* on component removal (from different morphdom hook or tearDown method or whatever)

The hard part will be removing the setInterval at the core of a polling setup. (right now we're not keeping track of them, and we would need to)

**Comment by ohnotnow** [comment]
https://github.com/livewire/livewire/pull/846 seems to have resolved this for my needs - thanks @calebporzio ! :-)
