### ISSUE TITLE
ComponentCacheManager is gone and protected properties are not persisted 

### ISSUE THREAD

**Issue by shadoWalker89** [livewire/livewire#566]
Hi,
I have built some components with livewire that rely one storing some data in protected properties and have them available for the lifespan of the component.
But now i see that the ComponentCacheManager is removed and in the docs, it says 

> protected and private properties DO NOT persist between Livewire updates. In general, you should avoid using them for storing state.

I also saw this thread on the forum https://forum.laravel-livewire.com/t/help-me-solve-the-hardest-problem-in-livewire-and-maybe-the-entire-world/22

I understand why caleb removed protected properties but i think that there is a lot of use cases where fetching data once and use them for the lifespan of the component is useful.

As a real use case i have a table with filters.
The options for each filter should only be loaded once. With no protected proprieties that persists between requests i'll have to load the options for each filter on each round trip between the client and the server which is no a good thing.

If we make an analogy with client side version of the component.
The first time i will load the options of all the filters and keep them stored in variables for future use and never fetch them again.

Could @calebporzio please think about this and maybe together we can find some other way to have  state persisted on the server for the life cycle of the component ?

**Comment by shadoWalker89** [comment]
https://forum.laravel-livewire.com/t/help-me-solve-the-hardest-problem-in-livewire-and-maybe-the-entire-world/22

**Comment by xxdalexx** [comment]
You can persist it yourself in the cache or session. I have a model I persist across a multi step form. I load it to a protected property in the mount and hydrate method, and save it in the render method.

Something like:

```
protected $post;

public function mount()
{
    $this->post = session()->get('post', new Post);
}

public function hydrate()
{
    $this->post = session()->get('post');
}

public function updated()
{
    $this->post->title = $whatever;
}

public function render()
{
    session(['post' => $this->post]);
    return view('livewire.post.create');
}
```

I have a majority of the logic in a trait since I'm using it across multiple components and have a couple of objects, but this is the jist of it, and haven't run into any breaking issues yet.

**Comment by shadoWalker89** [comment]
@xxdalexx Yeah that is a solution but using protected properties is so clean, do it manually clutters the component. Maybe it doesn't hurt too much for small components but when we are dealing with one with a lot of code, it will get messy.

**Comment by calebporzio** [comment]
yeah, no plans to add the protected property caching thing back as a first-class citizen.

There are lots of other ways you can do this. Creating your own custom caster is a good one. Maybe look into that.

I'm going to close this for now, but I still want to hear about your and others needs around this issue.

Thanks!

**Comment by xxdalexx** [comment]
@calebporzio I was under the impression you could only cast public properties. Is that wrong, or are you thinking of changing that?

**Comment by calebporzio** [comment]
No, you're right, it's only for public properties, but you "could" just make the property public and cast it in and out of the session or cache as if it were protected.
