### ISSUE TITLE
More information in javascript hooks

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#569]
Can we provide more information in `beforeDomUpdate` and `afterDomUpdate`?

Like what is this update triggered by? Is it a poll or other automatic things? Is it a user interaction? What kind of interaction? Or the ability to send some meta data to this hook from php, etc.

We might also think of more js hooks.

**Comment by calebporzio** [comment]
Yeah, I will make a note to improve this documentation for v1.0

**Comment by mokhosh** [comment]
@lancepioch @calebporzio Not sure if I was clear. This is a feature request, not a question.

Do `beforeDomUpdate` and `afterDomeUpdate` currently receive an `event` object or something that contains those information? I'm thinking about something like this:

```js
@this.on('beforeDomUpdate', (e) => {
  if (e.isTriggeredByPoll) return;
  if (e.isTriggeredByUserInteraction) // do something in this case
    console.log(e.informationProvidedFromPhpComponent);
});
```

**Comment by mokhosh** [comment]
Also note that I'm using `@this` and not `window.livewire.hook`. Can we do this per component?

**Comment by calebporzio** [comment]
Currently, there is no per-component "beforeDomUpdate" hook, BUT it does receive the current component as a parameter (`window.livewire.hook('beforeDomUpdate', (component) => {...} )`)

**Comment by calebporzio** [comment]
As far as detecting if the current response is from a poll, I'm not sure if that's possible. Feel free to look into it though and make a suggestion.

**Comment by mokhosh** [comment]
Well we have that information when we're sending the message to the component, right? We know why we're sending a message to the server. Can we keep track of it in the meta data that we send back and forth?

**Comment by calebporzio** [comment]
Closing this for now.
