### ISSUE TITLE
Lifewire sends post request on each character typed !

### ISSUE THREAD

**Issue by AEK-BKF** [livewire/livewire#575]
I have this form where I put three inputs :

<a href="https://ibb.co/nPyxvkq"><img src="https://i.ibb.co/Y0SHMj4/Screenshot-from-2020-01-31-23-51-10.png" alt="Screenshot-from-2020-01-31-23-51-10" border="0"></a>

In browser console I note that a post request is sent for each character I type !

<a href="https://ibb.co/c6vWCbw"><img src="https://i.ibb.co/Ht2cxNC/Screenshot-from-2020-01-31-23-50-50.png" alt="Screenshot-from-2020-01-31-23-50-50" border="0"></a>

What's wrong ?

**Comment by lucasromanojf** [comment]
Hey @AEK-BKF if you use wire:model.lazy="field" these requests will happen only on field blur. These requests are needed for updating the field value on backend (your component).

**Comment by AEK-BKF** [comment]
Hey ! Thanks for quick replay,
Ok I set it lazy, but it still sends request when I type something and leave the input to other one !
If we could send request only when I click submit.
Thanks.

**Comment by lucasromanojf** [comment]
This is the intended behavior, but there is another way. You can remove wire:model from your fields and submit form manually using Livewire's Javascript. Something like this (did not test):

`@this.call('yourSubmitMethod', <here you send an object with your form fields values as argument>)`

Then in your component:

`public function yourSubmitMethod($values) 
{
... 
} `

Not sure if it will work but feel free to try if you want

**Comment by kdion4891** [comment]
There is a solution here:

https://github.com/livewire/livewire/issues/313

**Comment by calebporzio** [comment]
Good suggestions above. Thanks!
