### ISSUE TITLE
Weird issue with inputs showing old/null data after refresh 

### ISSUE THREAD

**Issue by kdion4891** [livewire/livewire#579]
I've noticed this issue with `<select>`s too. Basically after the UI gets updated some weird glitch happens where the browser thinks something isn't what it should be. I don't know how to explain, so heres a video:

https://imgur.com/btqzuQE

Notice how the `c` input gets passed down in the UI even tho it is no longer in the data. I have no idea how to fix this.

Here is the HTML code that is output:

    <div class="form-row">
        <div class="col-md">
            <input type="text" class="form-control form-control-sm " autocomplete="" placeholder="test1" wire:model.lazy="form_data.owners.5e369147abed0.test1">
        </div>
        <div class="col-md">
            <input type="tel" class="form-control form-control-sm " autocomplete="" placeholder="test2" wire:model.lazy="form_data.owners.5e369147abed0.test2">
        </div>
        <div class="col-md">
            <input type="email" class="form-control form-control-sm " autocomplete="" placeholder="test3" wire:model.lazy="form_data.owners.5e369147abed0.test3">
        </div>
        <div class="col-md-auto">
            <button class="btn btn-sm btn-danger" wire:click="arrayRemove('owners', '5e369147abed0')"><i class="fa fa-trash"></i></button>
        </div>
    </div>

Heres the code for the add/remove buttons in my component:

    public function arrayAdd($field_name)
    {
        $this->form_data[$field_name][uniqid()] = [];
    }

    public function arrayRemove($field_name, $uniqid)
    {
        unset($this->form_data[$field_name][$uniqid]);
    }

The arrayRemove function simply unsets the `form_data.owners` array element at the given key. Like I said I noticed this happening with non-array properties as well before. I had a select and when I would change the value the browser would show an empty option as being selected, and I have no clue why.

**Comment by kdion4891** [comment]
I think this has to do with how livewire unsets empty array values entirely. For example, if you have a model with a multidimensional array, and any of those values are empty, it will completely remove the key for that value.

**Comment by kdion4891** [comment]
I figured it out. I wasn't passing the multidimensional array keys when the add button was pressed, so livewire didn't know what to expect. Its working properly now.

**Comment by calebporzio** [comment]
Great, thanks for following up. Closing this.

**Comment by onemoreahmad** [comment]
Hi @kdion4891, I have a same issue with a really simple form with two inputs, but still get the old/null value when I refresh the page. What do you mean by passing the multidimensional array keys when the add button was pressed ?
Thanks
