### ISSUE TITLE
[V3] Reset Property Doesn't Affect Client-Side

### ISSUE THREAD

**Issue by devajmeireles** [livewire/livewire#5817]
Hey, guys!

I opened a discussion here: https://github.com/livewire/livewire/discussions/5797, but I'm opening this issue just to call attention to this.

I don't know if this problem is just me, but I'm not able to reset the client-side properties, that is, visually. Please check the discussion for details and video demonstration.

Thankssss. ❤️

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
