### ISSUE TITLE
Uncaught (in promise) ReferenceError: yo is not defined

### ISSUE THREAD

**Issue by ziming** [livewire/livewire#584]
**Describe the bug**
I'm not sure why but $items->links() in my blade now got problem after I did a composer update / npm update

The html does render but when I click on 1 of the numbers in the pagination links of my livewire component, I get javascript console error:

Uncaught (in promise) ReferenceError: yo is not defined

I only tested it in chrome so far.

**Comment by ziming** [comment]
Update, it appears to work after I purged my cloudflare cache. Will observe and update you again.

**Comment by calebporzio** [comment]
Ah yes, you had an older version of the assets, but a newer version of the package.

**Comment by ziming** [comment]
Strange, after the latest composer update, my pagination links don't work again. I cleared cloudflare cache multiple times and waited a few hours. Still not working.
