### ISSUE TITLE
Livewire not initializing in IE11 and Edge

### ISSUE THREAD

**Issue by ruudschuurmans** [livewire/livewire#585]
**Describe the bug**
Hello! Thanks so much for this great package. 
It seems Livewire is not initalizing in IE11 and Edge. Tested in `IE11` and `Edge 42`. This seems to be related to the use of spread syntax in object literals (see additional context below).

**To Reproduce**
- Add `@livewireScripts` to your view
- Open application in IE11 or Edge
- Check console, the following error appears: 
`Expected identifier, string or number`

**Expected behavior**
I expected livewire to initalize

**Screenshots**
![image](https://user-images.githubusercontent.com/12184008/73687131-ad6a0a00-46c9-11ea-8f92-f4db5497d860.png)

It seems to have to do with this code snippet (according to Edge):
`PrefetchMessage.js`
![image](https://user-images.githubusercontent.com/12184008/73687609-b90a0080-46ca-11ea-959a-5065fdc59009.png)

**Desktop:**
 - IE11 or Edge 42 on Windows 10 (tested via browserstack) 

**Additional context**
My suspicion is that it has to do with the use of spread syntax in object literals (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals), it seems this is not supported by earlier versions of Edge and Internet Explorer 11. We might be able to "transpile" this problem away using Babel?

**Comment by ruudschuurmans** [comment]
I'm not a Babel expert, but this might be of help https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by calebporzio** [comment]
Yeah, that's probably right. I'd like Livewire to support those browsers, so I'd love it if someone can try to get this fixed and PR the fix. Thanks!

**Comment by ruudschuurmans** [comment]
I will try to fix this this week @calebporzio

**Comment by ruudschuurmans** [comment]
https://github.com/livewire/livewire/pull/586
There you go! @calebporzio :)

**Comment by lancepioch** [comment]
@ruudschuurmans Thank you for fixing this with your pr!
