### ISSUE TITLE
[Suggestion] WithInfiniteScroll

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#590]
Hello,
Thanks for great job.
With WithPagination we can have pagination but I think modern website now use infinite scroll.
I think WithInfiniteScroll is great job for livewire.

**Comment by AEK-BKF** [comment]
👍 +1

**Comment by calebporzio** [comment]
Yeah, I agree. I've thought about this since really early on and just always punted on it.

I'm interested to here more thoughts on what you think the API would be like for this?

**Comment by AndreSchwarzer** [comment]
I think this is somewhat related #79 

Definitvely a +1 from me for infinitScroll (for pagination)

**Comment by AndreSchwarzer** [comment]
Hey @calebporzio great talk.

Will the infinit scroll be only available on "project l" ?

Or are you sharing your solution to this.

I try to achieve this: 
like they did: hotukdeals.com
You can scroll, the paginated content is added to your list and it's kept track of how far you scrolled (page).

**Comment by ruudschuurmans** [comment]
I'm willing to work on a PR for this if nobody else is working on it already.

**Comment by AEK-BKF** [comment]
@ruudschuurmans  Yes please ^^'

**Comment by calebporzio** [comment]
Maybe start proposing potential APIs for this feature before PRing. Thanks!

**Comment by Algeneralo** [comment]
@calebporzio any updates here?

**Comment by calebporzio** [comment]
This feature is on the back burner for now
