### ISSUE TITLE
Issue: Nested Component with pagination

### ISSUE THREAD

**Issue by shahvirag** [livewire/livewire#591]
Nested component not working with pagination.
While loading component 2st time all root and nested component working fine.
After changing page root component not loading and some of (most of time last) nested component is not loading.

If you remove nested component everything working fine even pagination.

**To Reproduce**
1. Create listing component with pagination (e.g. Users List).
2. Create one more component which will include in each component. (e.g. Status (Active / Inactive)).
3. Load component. [Working fine]
4. Change Pages.

**Expected behavior**
Listing component should work fine even with nesting component.

**Screenshots**
![error chrom](https://user-images.githubusercontent.com/24240840/73911512-17f09500-48d8-11ea-8926-5b862353a364.png)

**Software**
 - PHP: 7.2.0
 - Laravel: 6.*
 - Livewire: 0.7.*

**Desktop (please complete the following information):**
 - Browser:  chrome, firefox

**Livewire Component**
![Listing](https://user-images.githubusercontent.com/24240840/73912332-40798e80-48da-11ea-88ac-f7a08ca59555.png)
![status](https://user-images.githubusercontent.com/24240840/73912337-44a5ac00-48da-11ea-96d4-c0f45a6807e7.png)

**Comment by calebporzio** [comment]
Can you post your .blade.php files? I imagine you left out a `key()` parameter when declaring the children. Also, could be `wire:key` in the foreach. Both are really important for nested component tracking and loops.

**Comment by shahvirag** [comment]
Listing View File.
![index_view](https://user-images.githubusercontent.com/24240840/73957609-9d9e3000-492c-11ea-9ff7-636c967dba2b.png)

**Comment by shahvirag** [comment]
Listing .blade.php file
![index_view](https://user-images.githubusercontent.com/24240840/73958117-6c722f80-492d-11ea-9403-8142bb746948.png)

Status .blade.php file
![status_view](https://user-images.githubusercontent.com/24240840/73958210-988db080-492d-11ea-915c-2ecf18339ae0.png)

**Comment by shahvirag** [comment]
@calebporzio 

`key()` is remaining. thanks for helping me out.

**Comment by calebporzio** [comment]
Great, np!

**Comment by Acatecatl** [comment]
it´s not work for me

**Comment by mohammad-reza-najafi** [comment]
I have problem  , I cant use pagination in nested compoentn .

**Comment by Saeeed-B** [comment]
@mohammad-reza-najafi @shahvirag 
Yes there is this problem there are only three solutions.
First, use wire: key = "{{$ loop-> index} در" in your circles.
Refer to the following link:
[https://laravel-livewire.com/docs/2.x/troubleshooting](https://laravel-livewire.com/docs/2.x/troubleshooting)
Second, do not use the nested component at all in pagination. Because the child component is not updated.
Three, update the child component after changing the page. That is, by changing the page, call an event that will lead to the update of the child component.

**Comment by joshhanley** [comment]
@mohammad-reza-najafi and @Saeeed-B there were some updates in the latest release v2.6 that fixed issues with pagination in nested components.

So I'd suggest upgrading to that first and seeing if that works.

Hope this helps!
