### ISSUE TITLE
Small Issue 

### ISSUE THREAD

**Issue by AEK-BKF** [livewire/livewire#592]
When we create new component with a name having first character Uppercase , it generates a blade name with first character dash '-' :
`php artisan livewire:make Login`

Output :` -Login.blade.php`

**Comment by ManojKiranA** [comment]
this is Defiinitely a Bug

**Comment by AEK-BKF** [comment]
**laravel/framework: ^6.2
livewire/livewire: ^0.7.2
PHP 7.3.4
Windows 10**

**Comment by calebporzio** [comment]
Yep, it seems like a bug to me too lol. Mostly, I recommend using kebab-case to generate and reference components. But this should not happen.

This is a good little bugfix for someone else to PR (pretty stacked with other things right now). Any takers?

**Comment by mathiasonea** [comment]
Strange, I just tackled this bugfix (livewire ^0.7.3, on MacOS Mojave) and it doesn't seem to be happening to me.
I am calling `php artisan livewire:make Login` and get the following files:

```
COMPONENT CREATED  🤙

CLASS: app/Http/Livewire/Login.php
VIEW:  resources/views/livewire/login.blade.php
```
And the files actually exist in those directories, so it created them correctly. Can anybody cross-check, if this issue still exists after the latest release?

**Comment by AEK-BKF** [comment]
I've upgraded to ^0.7.3 and the issue is fixed.
But I get this error :
`Exception  : The  directory must be present and writable.`
Even it creates both Controller and View !

**Comment by AEK-BKF** [comment]
For the error :
` Exception : The directory must be present and writable.`
I fixed it here :

[ Fixing : Exception : The directory must be present and writable.](https://github.com/livewire/livewire/issues/597#issuecomment-583714168)
