### ISSUE TITLE
Add the ability to rerender a livewire view within the component

### ISSUE THREAD

**Issue by intergalactisch** [livewire/livewire#595]
It would be awesome if a rendered Livewire-view could be rerendered from within a function in the component Class. 

To give an example, I have created the following Livewire button:

```php
<div>
    @if( $inventory )
        <button
            type="submit"
            class="py-2 px-4 bg-red-600 hover:bg-red-700 text-white rounded transition {{ $classes ?? '' }}"
            wire:click="deleteInventory"
        >
            Delete from inventory
        </button>
    @else
        <button
            type="submit"
            class="py-2 px-4 bg-theme hover:bg-theme-dark text-white rounded transition {{ $classes ?? '' }}"
            wire:click="addInventory"
        >
            Add to inventory
        </button>
    @endif
</div>
```
With a Livewire button component Class that contains this:

```php
public function addInventory()
    {
        // add
        InventoryCreate::dispatchNow($this->product);

        // redirect
        $this->redirect('/' . $this->product->path());
    }

    public function deleteInventory()
    {
        // authorize
        $this->authorize(InventoryPolicy::DELETE, $this->inventory);

        // delete
        InventoryDelete::dispatchNow($this->inventory);

        // redirect
        $this->redirect('/' . $this->product->path());
    }

    public function render()
    {
        return view('livewire.product-inventory-button');
    }
```
That is included in a blade "show" view like this:
```php
@auth
    @livewire('product-inventory-button', $product)
@endauth
```

The button is shown conditionally when the inventory is added or not. I now have to redirect to the 'parent' page, and do a full refresh in order to show the new status of the button. Is it possible to rerender the rendered view, instead of doing a full redirect? So something like `$this->render()->refresh()`?

**Comment by calebporzio** [comment]
Hey @intergalactisch I imagine what you're talking about is possible, but we will need more context to better answer that.

**Comment by intergalactisch** [comment]
@calebporzio Okido, I have edited the main question to hopefully give some more clarity 👍.

**Comment by xxdalexx** [comment]
You're code is correct in a way that it is being re-rendered when it should be to update the page. The problem is in your addInventory() method you are not updating/changing $this->inventory, so the if statement in your view is still reading false and jumping to the else section.

**Comment by intergalactisch** [comment]
@xxdalexx Nice, I did not know that! Thanks!
