### ISSUE TITLE
Cannot emit events from mount method

### ISSUE THREAD

**Issue by dylanmichaelryan** [livewire/livewire#598]
**Describe the bug**
If you try to run an event from the mount method, it won't work.

**To Reproduce**
1. Create Livewire Component
2. Create Mount Method
3. $this->emit('someRandomEventName')

**Desktop (please complete the following information):**
 - Chrome

The reason i am trying this is the following:
A user can create a project, and after the creation of the project the user gets redirected to his new project. And on this page i want to show a notification, and i for that i need to emit an event.

**Comment by mathiasonea** [comment]
Could you use a flash message instead?
Either self-handled by using session variables or via a package such as Jeffrey Way's  [laracasts/flash](https://github.com/laracasts/flash).
The message will be rendered by the server only for that single request and you don't need to throw an event in the mount method.

**Comment by dylanmichaelryan** [comment]
> Could you use a flash message instead?
> Either self-handled by using session variables or via a package such as Jeffrey Way's [laracasts/flash](https://github.com/laracasts/flash).
> The message will be rendered by the server only for that single request and you don't need to throw an event in the mount method.

Good point! Dont know why i havent thougt about that

**Comment by jjjrmy** [comment]
Hello I'm having the same issue, but Session Flash is not suitable for my case. #839

**Comment by devcircus** [comment]
I use session flash in redirects which works as expected. What causes flashing to not be suitable? Otherwise, you can use a client side flash messaging solution.

**Comment by jjjrmy** [comment]
> I use session flash for redirects which works as expected. What causes flashing to not be suitable? Otherwise, you can use a client side flash messaging solution.

I would like to trigger some javascript to run when the component is loaded.

**Comment by itsmemanoj** [comment]
Question still remains, can we use `$this->emit()` in `render()` or `mount()` method?
my case,
I need to pass a default value to the livewire component ( components are included in a blade and default value comes from laravel controller  ) but sometimes that value becomes null, and when the value is not null, I need to emit an event for others to listen.

**Comment by joshhanley** [comment]
@itsmemanoj emit won't work in the mount function or render function (during the first load) as Livewire's javascript isn't running yet. But it will work in the render function on subsequent requests.

Can you explain your use case some more? If the null value is coming from a parent component, can't it emit the event? Otherwise what components are you emitting the event to? Can't they receive a prop as well?

If you can provide some more details, I can see if there is a way to get what you're after working without using emit in mount.

**Comment by itsmemanoj** [comment]
@joshhanley here is the case,
i am passing a variable  from laravel controller to laravel blade and within this balde, i have included 4 livewire components,
like this 
@livewire(component1, ['keyword' => valueFromLaravelController])
@livewire(component2, ['keyword' => valueFromLaravelController])
@livewire(component3)
@livewire(component4)
but only 2 livewire components will receive the value. and when livewire components receives that value, i want to emit an event
for other components ( component 1 and component 2 );

How can i do that?

**Comment by keivantatari** [comment]
i need ask_id in mount() method,but it dont work...

   public $ask_id;
    public $products;
    public $votes;
    public $users;
   
   

    protected $listeners = ['askAdd'];

    public function askAdd(Ask $ask){

        $this->ask_id=$ask->id;
 
    }

    public function mount(){

        $this->products=Product::where('ask_id',$this->ask_id)->get();
        $this->votes=Vote::where('ask_id',$this->ask_id)->get();
        $this->users=User::all();
       
    }

**Comment by indigoram89** [comment]
+1

**Comment by webacers** [comment]
+1

**Comment by joserick** [comment]
+1 | $this->emit() not working in render() or mount(), any idea?

**Comment by ogradye** [comment]
+1

**Comment by ridxery** [comment]
I know its not the exactly for what you are looking for but you could use **wire:init** on the component `<div wire:init="$emit('foo')">` or call a public function `<div wire:init="myFunction"> `other than, wire:init will run once after the component loaded

**Comment by leewp14** [comment]
> @itsmemanoj emit won't work in the mount function or render function (during the first load) as Livewire's javascript isn't running yet. But it will work in the render function on subsequent requests.

Thank you for the clarification. Will be much better if information like this is being written in the docs.
