### ISSUE TITLE
Default query string 'page' applies to all paginators on page.

### ISSUE THREAD

**Issue by xxdalexx** [livewire/livewire#599]
The changes in [this commit](https://github.com/livewire/livewire/commit/6beffd1d6708f35e64f90d835bdd7e08a9b0baa2) do not work well if there is more than one pageinator in a page.

I don't know if doing something like the regular paginator with `$results->setPageName($name)`, or the ability to disable it per component would be a better fix.

**Comment by lancepioch** [comment]
I believe that this has been answered in #738
