### ISSUE TITLE
Issue: Nestead component loading attr.

### ISSUE THREAD

**Issue by shahvirag** [livewire/livewire#601]
**Describe the bug**
1. Listing is parent component.
2. Status button is another nested component.
Loading attribute `wire:loading.attr="disabled"` works first time perfectly.
second time `wire:loading.attr="disabled"` is there but not applied.

**To Reproduce**
1. Create listing page with live-wire component
2. Create another status change component (action on click) with live-wire its available for each row in listing.
3. Load page and list with status button..Click button first time to change status. loading content and attribute (disabled = true) both works fine,
4. Without refresh page click on change status again. This time loading content displays but attribute (disabled = true) not works.
5. For each rows 1st time works fine but 2nd time not works.

**Screenshots**
Loading state first time.
![loading_state_first_time](https://user-images.githubusercontent.com/24240840/74148507-9c6e4b00-4c2b-11ea-9be6-de19fd16ff50.png)

Loading state second time time.
![loading_state_second_time](https://user-images.githubusercontent.com/24240840/74148545-aee88480-4c2b-11ea-9af9-9154b8742d6f.png)

**Desktop (please complete the following information):**
 - Laravel 6.x
 - Livewire 0.7.x
 - Browser Chrome, Mozilla Firefox

**Code Snippet**
Listing blade file
![listing_view](https://user-images.githubusercontent.com/24240840/74150271-8cf10100-4c2f-11ea-9932-dbc0924e491c.png)

Status blade file:
![status_view_comp](https://user-images.githubusercontent.com/24240840/74150280-924e4b80-4c2f-11ea-8977-3ac7b5ed77d7.png)

Status class file:
![status_class](https://user-images.githubusercontent.com/24240840/74150287-967a6900-4c2f-11ea-80dd-24e64bbd4a12.png)

**Comment by calebporzio** [comment]
Try adding unique `wire:key` values to the buttons tags in the `@if($model->activated)`.

If not, try wrapping the conditional in a tag.

Some combination of those two should fix this.
