### ISSUE TITLE
Livewire and Vue DateTimePicker Component

### ISSUE THREAD

**Issue by bbcreation** [livewire/livewire#603]
Hi all. I'm having trouble passing data from a datatime picker to my component. Returns null from "scheduled_at". Im using https://mariomka.github.io/vue-datetime/.

I am not a specialist at Vuejs. What am I doing wrong?

```
<div id="app">
<input-taggable wire:model="scheduled_at" type="datetime" format="yyyy-MM-dd HH:mm:ss" class="form-input mt-1 block w-full text-xs" placeholder="{{ __('Date and time') }}"></input-taggable>
</div>
```

`@push('scripts')
    <script>
        new Vue({
            el: '#app'
        })
    </script>
@endpush`

**Comment by bbcreation** [comment]
I used bootstrap-timepicker converted to work with Tailwind. Vue trunks wanted to cooperate. You can close. Another question. Also related to this. As I click in the input is sent emit. It's always open the first tab made in aplinejs. How to block it?

**Comment by calebporzio** [comment]
For Vue integration topics, issues should be submitted here now: https://github.com/livewire/vue

Vue support has been moved to a third-party package in favor of built-in Alpine integration.
