### ISSUE TITLE
Cannot access https://laravel-livewire.com/

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#607]
**Describe the bug**
I cannot access the documentation website at: https://laravel-livewire.com/

**To Reproduce**
1. Go to https://laravel-livewire.com/

**Screenshots**

I get below error. I tried on multiple networks (and mobile roaming), and I always encounter the DNS issue.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/HBn6q.png

**Comment by vuthaihoc** [comment]
An alternative site for my team 😸 https://vuthaihoc.github.io/docs/build_production/docs/quickstart/

**Comment by oliverbj** [comment]
Thanks @vuthaihoc! What happened to the original one?

**Comment by linuxjuggler** [comment]
Mostly the domain was not renewed.

**Comment by ManojKiranA** [comment]
> I cannot access the documentation website at: https://laravel-livewire.com/

may be DNS issue. I hope its resolved now

**Comment by calebporzio** [comment]
No clue what happened there. I'm surprised because the docs are hosted with Netlify. I would think I wouldn't really have to worry about this kind of thing.

Closing for now.

Re-open if problem crops up again and I'll investigate.
