### ISSUE TITLE
Clear form after send

### ISSUE THREAD

**Issue by cloudstudio** [livewire/livewire#608]
I have a form with > 30 fields, could be nice clear all data after submit, now there is nothing to do this right ? 

Now I can do something like : 

$this->email=""
$this->name=""

But I have a lot of fields.

Thanks!

**Comment by ManojKiranA** [comment]
related to #594

**Comment by cloudstudio** [comment]
Thanks @ManojKiranA working perfect for me!

Have a good day!

**Comment by calebporzio** [comment]
Thanks for pointing to that @ManojKiranA, I'll be documenting this shortly.
