### ISSUE TITLE
[Help]  Clone inputs

### ISSUE THREAD

**Issue by ManojKiranA** [livewire/livewire#610]
It will be great if there is **Livewire plugin** or  **Alpinejs Plugin** to clone the html elements

**Comment by calebporzio** [comment]
More info please

**Comment by ManojKiranA** [comment]
I have been working on a shop management project.

On that while the sales to add multiple items there will be + button to add more products which means Product drop down and quantity check box will be clonned again so that based on number of products customer going to buy I need to clone those. 

For doing that I have tried. 

https://github.com/metallurgical/jquery-metal-clone

Which is not working properly



But if there is some first party plugin to support this that would be awesome.

**Comment by ManojKiranA** [comment]
Just found a repo https://github.com/kdion4891/laravel-livewire-forms

and I have implemented my own logic to clone inputs.
