### ISSUE TITLE
Scope session values to component

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#613]
In most of my Laravel applications I use some kind of package to flash messages to the session to display them to the user. I use the same pattern in my Livewire components, you probably remember seeing that during the consulting @calebporzio.

This works fine for the most part as long as you only have a single place where you display the flashed message and only 1 Livewire component per page. Now where it gets buggy is if you have multiple Livewire components on a single page and multiple of them include the blade view that is used to display the flashed message. If you have 10 components on a page and 7 of them include the blade view to show the flashed message you will see the flashed message 7 times.

@calebporzio could you think of an easy way to scope specific session values to a component to avoid leaking them and more importantly, would this even be a desired behaviour?

**Comment by cbaconnier** [comment]
I did a dedicated flash component that I use outside of components with a listener.
Then I can emit an event from a component or use `session()->flash('success, 'message')` from the controller.

https://gist.github.com/cbaconnier/e9d4a69e1fcb13d75d140ec7e29cc9dd

**Comment by calebporzio** [comment]
Yeah, interesting.

I've been using `session->flash('message'...` like you do @faustbrian and loving it (thanks for spearheading that)

As far as scoping per component, I've definitely needed that in the past and have hand-rolled my own "scoped" flash messages in a plain Blade app.

Here's something you *could do:

// Set the session message:
```php
session()->flash($this->id.'-message', 'some-message');
```

// Retrieve the message:
```php
@component('flash-messages', ['id' => $this->id])@endcomponent
```

You could make a helper in a trait like:

```php
trait WithFlashHelper {
  public function flash($message)
  {
    session()->flash($this->id.'-message', $message);
  }
}
```

and a companion include:
```html
<!-- Usage -->
@include('livewire-flash-message')

<!-- Implementation -->
<div>
  @if (session()->has($this->id.'-message'))
    {{ session($this->id.'-message') }}
</div>
```

How does this feel to you?

I'm hesitant to add this to core to avoid API bloat. But open to thoughts. Got em?

**Comment by faustbrian** [comment]
That's pretty much what I've been doing after noticing the issue of having the flash messages show up multiple times when you have multiple components that include the flash view.

Could this maybe be a plugin like alpine or sortable or are those plugins intended to be purely on the JavaScript end of things? If Livewire would offer some kind of session flashing that is component bound as a plugin we would avoid to bloat the core as that is a valid concern.

If you're hesitant to add a behaviour like this to the core or as a plugin (if even possible) I'll probably extract my solution into a `livewire-flash` package with some helpers as I use this approach with flashing messages across multiple projects.

**Comment by calebporzio** [comment]
Yeah, I'm actually absorbing the `alpine` plugin into the core. So right now that only plugin will be `sortable`.

I think there is definitely a place for good third-party plugins weather they be PHP OR JS.

I would love it if I didn't have to maintain it as well lol.

Go ahead and publish your plugin, maybe we can add a section to the docs or README to point people to it.

Shouldn't be TOO tough given the current "middleware" oriented architecture (that shouldgivbe you FULL flexibility), but let me know if you need something added to core to make this easier.

Interested to see how user-contributed plugins shake out.

Closing for now. Keep me posted, thanks @faustbrian

**Comment by faustbrian** [comment]
https://github.com/kodekeep/laravel-flash/commit/1ac57bf5f523433b57b01e064c8f2342b1b60a5b should solve it for me as I can now do `Flash::success('Hello World', $component->id);` and `Flash::hasMessage($component->id);` together with `Flash::getMessage($component->id);` inside my Livewire views to make sure I don't flash messages across components.

Just extracted that out of my private projects and no need for a Livewire specific package as this could also be useful to scope flashed messages to specific entities like a user or team.
