### ISSUE TITLE
Inverse of wire:loading. 

### ISSUE THREAD

**Issue by jgile** [livewire/livewire#615]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Inverse of the wire:loading directive.  Hide component while loading and show when not loading.

Similar to the the inverses already provided with class and attr.

**Comment by calebporzio** [comment]
`<div wire:loading.remove></div>`? shouldn't be too tough. Pretty stacked right now in prep for 1.0. Open to PR.

**Comment by xxdalexx** [comment]
I asked the same before, but I think the best way to do it:
`<div wire:loading.class="hide">` and then do a css class for hide that has `display: none;`
