### ISSUE TITLE
Cannot find parent element in DOM tree containing attribute: [wire:id].

### ISSUE THREAD

**Issue by ScripTech** [livewire/livewire#618]
I have a search method on my livewire component, and i have custom fields that i load on mount method depending on selected type. custom fields loads and render well. however when i search by using updateSearchString this issue comes out, 

**All browsers**
Usually this is caused by Livewire's DOM-differ not being able to properly track changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/42839422/74630668-be078f00-5163-11ea-803d-7185bc74ce05.png)

**Comment by calebporzio** [comment]
Did you figure it out? If so, please share your solution here for others to find when they encounter a similar problem. Thanks!

**Comment by mikev032** [comment]
Same issue here, what did you do to solve this issue? @ScripTech

**Comment by ScripTech** [comment]
My issue use case.
In my app I have a task tracker category and all trackers have core and custom fields enabled or not on tracker.

So I move from vue to livewire.
But what I need is to be able to call by default at least one selected tracker on creating new task and push all core and custom fields. With works well.  

However, my custom fields have label and I'd that ref to specific input for check box and radio buttons, since custom fields have different types os values and it's a reusable balde "component".

The issue comes when I select tracker  by default when  mounting the component.

*Solution*
My first solution was to unselected tracker from the select drop-down options and place an empty option (``<option value></option>``) before the trackers loop. And worked well. **But this was not what I need**

**Comment by ScripTech** [comment]
And I also moved some code to other component for livewire add its unique ID on the master div element.
Code that loads array.

Livewire documents suggest to have wire:key inside loops.

**Comment by cbaconnier** [comment]
I had a similar problem but solved it differently
With the given example, it couldn't find the `wire:id` and referenced the `<input />`
```
<div>
    @foreach($elements as $element)
         <p> {{ $element['name'] }}</p>
    @endforeach
    <div>
        <input wire:model="name" />
        <button> add </button>
    </div>
</div>
```
The issue was that the `div>input` is wrapped in the same div than the foreach. So Livewire loose the track. 

I solved the issue by wrapping the foreach

```
<div>
    <div>
        @foreach($elements as $element)
             <p> {{ $element->name }}</p>
        @endforeach
    </div>
    <div>
        <input wire:model="name" />
        <button> add </button>
    </div>
</div>
```
