### ISSUE TITLE
Validation errors are not flashed to session

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#621]
If a validation error happens in Livewire, the ViewErrorBag (or MessageBag?) is not flashed to session as Laravel validation normally does (check https://laravel.com/docs/master/validation#quick-displaying-the-validation-errors). This means that when validations occur inside Livewire components, we can't access "**session()->get('errors')**". 

This is a problem for new Laravel 7 components syntax. For example, when creating a custom input, I want to use the **@error** blade directive inside the component. For this to work, I need to set the error bag in a public $errors property, so it gets injected inside the component. Something like this:

```
class Input extends Component
{
    public string $name;
    public string $label;
    public string $type;
    public $errors;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(string $name, string $label, string $type = 'text')
    {
        $this->name = $name;
        $this->label = $label;
        $this->type = $type;
        $this->errors = session()->get('errors') :? new ViewErrorBag(); //This does not work, since session()->get('errors') is null
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.input');
    }
}
```

For now, we are doing this:

**Input.php (component class):**

```
class Input extends Component
{
    public string $name;
    public string $label;
    public string $type;
    public $errors;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(string $name, string $label, $errors, string $type = 'text')
    {
        $this->name = $name;
        $this->label = $label;
        $this->type = $type;
        $this->errors = $errors;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.input');
    }
}
```

input.blade.php (view):

```
...
<x-input name="email" type="email" label="E-mail" :errors="$errors"/> // Passing $errors on every component isn't a good solution
...
```

I tested and I can confirm that just changing the following code inside **Livewire\Component@output** method solves this issue. I submitted the PR #622 which does this:

```
public function output($errors = null)
{
        ...
        ...
        $errors = (new ViewErrorBag)->put('default', $errorBag); //<- add this

        $view->with([
            'errors' => $errors, //<- change this
            '_instance' => $this,
        ] + $this->getPublicPropertiesDefinedBySubClass());

        session()->flash('errors', $errors); //<- add this
        ...
        ...
}
```

Thanks!!

**Comment by mokhosh** [comment]
@lucasromanojf I'm currently using this work around:
```html
<x-input name="email" type="email" label="E-mail" :errors="$errors"/>
```
And my form is inside a modal that shows up when I try to edit a table row. But the problem is if I get error messages and cancel our, and then try to edit another row, the error messages from last validation are still there.
Is there anything we can do about this? Does the new method make any difference in this regard? Should I open another issue for this?

**Comment by lucasromanojf** [comment]
Hello @mokhosh I guess it is another problem. I think you need to find a way of reseting the validations once you have closed your modal. Livewire has a reset method (not documented yet) and a $refresh method also that you can try calling using Javascript on modal close/open. Just some tips, you could try if you want.

**Comment by lucasromanojf** [comment]
> Hello @mokhosh I guess it is another problem. I think you need to find a way of reseting the validations once you have closed your modal. Livewire has a reset method (not documented yet) and a $refresh method also that you can try calling using Javascript on modal close/open. Just some tips, you could try if you want.

@mokhosh Take a look here: https://laravel-livewire.com/docs/input-validation/

More specifically the "Direct Error Message Manipulation" section.

**Comment by mokhosh** [comment]
Thanks for taking the time @lucasromanojf 💐 
I was doing `$errors = new ErrorBag();` and passing that each time to my view to achieve the same effect, but this is way cleaner. Thanks.

**Comment by gjm** [comment]
@lucasromanojf the error bag is not passed to components. If I use `@component` blade directive the `$errors` variable is not the same error bag as the main view. If, instead, I use `@include` of the same template file the `$errors` is correctly populated.

**Comment by lucasromanojf** [comment]
@gjm this is Exactly what my PR, mentioned on this issue, fixes :)
Just waiting for it to be merged too

**Comment by calebporzio** [comment]
@lucasromanojf, thanks for PR. I'm willing to merge it if you merge with master so there are no conflicts.

In the future, if you can also make a new branch on your fork before PRing it should allow me to make changes and push to this PR (I could have resolved the conflicts for you if you did that.)

Thanks!

**Comment by calebporzio** [comment]
@lucasromanojf - sorry, that response was supposed to be on the PR.

**Comment by lucasromanojf** [comment]
Hey @calebporzio NP! I did a real mess on my master branch so I closed the PR #622 and created a new one, #646.

**Comment by jcergolj** [comment]
Is it possible that this solution doesn't work if you have a livewire compoment and inside it 2 nested laravel components?

**Comment by lancepioch** [comment]
@lucasromanojf Does your fix resolve the issue now that it's been merged, can the issue be closed?

**Comment by lucasromanojf** [comment]
> @lucasromanojf Does your fix resolve the issue now that it's been merged, can the issue be closed?

Sure, closing now, thanks!

**Comment by gjm** [comment]
@lucasromanojf @lancepioch The fix doesn't work for me! Maybe I'm doing something wrong?

In my component template I have something like:
```html
<input wire:model.lazy="username" type="text" class="form-control @error('username') is-invalid @enderror" />
<x-form-errors name="username" />
```
The `<x-form-errors>` is a Laravel 7 component that displays the errors for the element specified by the `name` attribute. It's something like this:

```blade
@foreach ($errors->get($name) as $error)
    <div class="invalid-feedback">{{ $error }}</div>
@endforeach
```
Inside the `<x-form-errors>` component the `$errors` variable is an empty bag while in the main component template it's correctly populated.

**Comment by jcergolj** [comment]
@gjm I have the same problem as your. It doesn't work for nested blade components.

**Comment by gjm** [comment]
@lucasromanojf please reopen this issue.

**Comment by merthurturk** [comment]
I've just opened PR #704 that fixes the issue of `$errors` not being available to nested components.

**Comment by lucasromanojf** [comment]
Fixed by #710

**Comment by lucasromanojf** [comment]
After PR #710, @error stopped working again inside blade components.

**Comment by lucasromanojf** [comment]
@calebporzio the PR #710 made @error directive inside blade components stop working again. Any ideas? Maybe Taylor could help with this.

**Comment by lucasromanojf** [comment]
Just confirmed that the $errors variable is an empty bag inside nested blade components too, just like the @error directive, after PR #710. Adding back "session()->flash('errors', $errors);" to Component@output method fixes the issue for both $errors and @error. I tested and confirmed this. 

@calebporzio this issue is very annoying so if we could address this as soon as possible, it would be great (please). We are currently building a (big) project using Livewire and it was working fine for us after my PR #646, and after the PR #710 reverted my PR, we started having problems with nested validations again. For now we fixed Livewire on version 1.0.3 on our composer.json.

**Comment by merthurturk** [comment]
@lucasromanojf Before PR #710 we were having the same issues. I've fixed the issue with PR #704 but PR #710 did a better job at it and made #704 obsolete. Right now we're at v1.0.8 on production and both @error and $errors working in nested components in our system (although haven't tested deep nested components). Could you please create a test that's failing for your use case and share it with a new PR? I would definitely be interested to take a look at it and do my best to fix the issue.

**Comment by lucasromanojf** [comment]
@merthurturk sure, I'll try to make a small project that reproduces this. Thanks for your help.

**Comment by lucasromanojf** [comment]
There was something in my project that was breaking $errors and @error somehow. I removed it and started working. Thanks @mokhosh and @calebporzio I'm sorry about the noise. My mistake.
