### ISSUE TITLE
Strange behavior when adding id attribute to component's DOM.

### ISSUE THREAD

**Issue by andresgcarmona** [livewire/livewire#623]
Is the **id** HTML attribute not allowed in Livewire components?. If you add the id attribute to some element in some places in the component's DOM and call a function in the component class It throws the following error:

![Screenshot from 2020-02-18 15-15-01](https://user-images.githubusercontent.com/757823/74778857-0d33e980-5262-11ea-9cea-20d06faf1224.png)

This is my component's code:

```blade
<div>
    <div class="row mt-3">
        <div class="col-sm-12 col-md-6">
            <div class="table-length">
                <label>Show
                    <select name="dt-responsive_length"
                                    aria-controls="dt-responsive"
                                    class="custom-select">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select> entries</label>
            </div>
        </div>
        <div class="col-sm-12 col-md-6">
            <div class="table-filter" id="tb-filter">
                <label>Search:<input type="search"
                                     class="form-control"
                                     placeholder=""
                                     aria-controls="dt-responsive"></label>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table nowrap w-100" role="grid" id="dt-responsive">
            <thead>
            <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="dt-responsive" rowspan="1" colspan="1"
                    style="width: 259px;" aria-label=" Name : activate to sort column descending" aria-sort="ascending">
                    Name
                </th>
                <th class="sorting" tabindex="0" aria-controls="dt-responsive"
                    rowspan="1" colspan="1" style="width: 378px;"
                    aria-label=" Position : activate to sort column ascending"> Country
                </th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th rowspan="1" colspan="1"> Name</th>
                <th rowspan="1" colspan="1"> Country</th>
            </tr>
            </tfoot>
            <tbody>
            @foreach($leagues as $l => $league)
                <tr role="row" class="{{ $l % 2 === 0 ? 'even' : 'odd' }}">
                    <td>{{ $league->name }}</td>
                    <td>{{ $league->country }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $leagues->links() }}
    </div>
```

Here I have an id **tb-filter** set, and another in the table **dt-responsive**. If I remove the **tb-filter** id everything works fine.

**Comment by ManojKiranA** [comment]
based on #623

**Comment by mikev032** [comment]
Also, happen when you are adding a `wire:key="{{ $loop->index }} "` for example

**Comment by xxdalexx** [comment]
If you add the missing </div> at the end, does that fix it?

**Comment by togglebroadband** [comment]
I've also noticed this one, was about to post an issue but spotted your one.

Same with me, added an ID to an input and couldn't submit any requests without this error if I changed that values input.

Tried adding the wire:id / wire:key etc but no luck. In the end just removed the ID but not ideal.

**Comment by mikev032** [comment]
Removing the ID / removing the  `wire:key` is causing weird behaviour, for example livewire losing track of the DOM

**Comment by togglebroadband** [comment]
> Removing the ID / removing the `wire:key` is causing weird behaviour, for example livewire losing track of the DOM

I have a text input that is using `wire:model` only. It was when I added a normal `id` tag that it started throwing that error. Removing that tag removes the issue, but PHPStorm doesn't like me for that missing label reference....

**Comment by andresgcarmona** [comment]
> If you add the missing `</div>` at the end, does that fix it?

Sorry i missed the closing div tag. I have it in my code and still throws the error.

**Comment by mikev032** [comment]
> > Removing the ID / removing the `wire:key` is causing weird behaviour, for example livewire losing track of the DOM
> 
> I have a text input that is using `wire:model` only. It was when I added a normal `id` tag that it started throwing that error. Removing that tag removes the issue, but PHPStorm doesn't like me for that missing label reference....

I was confirming your issue, not arguing  : )

**Comment by stefanbauer** [comment]
I can confirm that as well. @calebporzio you might take a look at it. Afaik it works in earlier versions.

**Comment by mikev032** [comment]
This is fixed with the latest version of the Vue plugin. 
`
<script src="https://cdn.jsdelivr.net/gh/livewire/vue@v0.2.x/dist/livewire-vue.js"></script>`

**Comment by lancepioch** [comment]
@stefanbauer @mikev032 @togglebroadband @andresgcarmona Are you using Vue? If so, can you try the latest livewire/vue release and see if it fixes it for you?

**Comment by andresgcarmona** [comment]
Hi, no I'am not using Vue in this project. I was just testing Livewire alone without any other library.

**Comment by calebporzio** [comment]
Can you reproduce this issue in a small, copy and past-able snippet?

**Comment by andresgcarmona** [comment]
I'm sorry, I'am indeed using Vue in this part of the project. Removing Vue from the page gets rid of the error, my bad. I'll use the plugin mentioned above. Thank you.

**Comment by jackcruden** [comment]
The default Laravel setup includes VueJS automatically and is triggering this issue as well. You may need to remove the default inclusion (at time of writing `"vue": "^2.5.17"`).

**Comment by togglebroadband** [comment]
> Can you reproduce this issue in a small, copy and past-able snippet?

Hey Caleb, is this fixable within Livewire itself as opposed to pulling in a CDN link to livewire-vue?

I've been looking at refactoring to Alpine but it's not in the current timeline for this project.

Thanks :D

**Comment by calebporzio** [comment]
Sry, you will have to pull in the plugin for support
