### ISSUE TITLE
Allow customizing exception handling behavior

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#625]
**Is your feature request related to a problem? Please describe.**
Currently, when an exception happens in a Livewire request, a modal is displayed with the response HTML. There is no (documented) way of overriding/customizing this.

**Describe the solution you'd like**
The goal of this ticket is to request a (official/documented) way of customizing the exception handling behavior in frontend.

**Describe alternatives you've considered**
For now, we are overriding the showHtmlModal function, like this:
```
window.livewire.connection.driver.showHtmlModal = function(response) {
    const json = JSON.parse(response);
    // Handle JSON response...
    // E.g.: alert(response.error);
};
```
And in the Laravel's **Handler.php** class, inside the **render** method, we are doing something like this:

```
$response = parent::render($request, $exception);
if ($response->getStatusCode() == 500) {
    if ($request->header('X-Livewire')) {
        return response()->json(['success' => false, 'status' => 500, 'error' => 'Internal server error'], 500);
    }
}
if ($response->getStatusCode() == 404) {
    if ($request->header('X-Livewire')) {
        return response()->json(['success' => false, 'status' => 404, 'error' => 'Page or resource not found'], 404);
    }
}
return $response;
```
For now this works, but maybe there is a better and more elegant solution.

**Additional context**
I am VERY involved with Livewire project and I want it to be great (more than it already is)! I am available for helping with anything you need.

**Comment by calebporzio** [comment]
What specifically do you want to be able to do or show instead of the modal? I could see the need for something like this, but I'd like to talk more about your specific needs.

**Comment by lucasromanojf** [comment]
> What specifically do you want to be able to do or show instead of the modal? I could see the need for something like this, but I'd like to talk more about your specific needs.

Hey @calebporzio for example, I am showing, instead of the default HTML modal, a Tailwind UI alert. Other people may want to just show a default Javascript alert, I don't know. This can be easily achieved by overriding the showHtmlModal function as shown above, but maybe you will want do do this customization in another way or, if not, just document this possibility.

**Comment by calebporzio** [comment]
This functionality has been addressed in this PR and will be available for the next tagged release: https://github.com/livewire/livewire/pull/1146
