### ISSUE TITLE
Vue components don't work inside livewire components

### ISSUE THREAD

**Issue by mikev032** [livewire/livewire#626]
**Describe the bug**
Let's say you have a livewire component inside a livewire component, in the included component vue components don't work anymore.

**To Reproduce**
1. Make 2 livewire components
2. include a livewire component in a livewire component
3. In the component include a Vue component

**Expected behavior**
The Vue component should work just like it should when it is included in a single livewire component

**Desktop**
 - Browser Chrome and tested on firefox

**Additional context**
The template is rendered, however, for example, a `v-for` is not working, and  a `v-on:click` on the Vue component is also not working, in my case, I have an array, and a click handler that pushes an item into the array

**Comment by lancepioch** [comment]
Can you please fill out the report?

**Comment by mikev032** [comment]
@lancepioch  Sorry mate, my bad. Edited it.

**Comment by mikev032** [comment]
Closed, moved to Vue plugin repo issues
