### ISSUE TITLE
Pagination view

### ISSUE THREAD

**Issue by martin-ro** [livewire/livewire#6270]
### Volt Version

v1.0.0-beta.2

### Laravel Version

10.17.1

### PHP Version

8.2

### Description

Seems like `usesPagination(view: 'components.pagination');` has no effect on what view is used for the pagination.

It's also not documented so not sure if that's even meant to be how to set the view.

### Steps To Reproduce

```php
<?php

use App\Models\User;
use App\Traits\WithPaginationAndScroll;
use function Livewire\Volt\{computed, state, usesPagination};

usesPagination(view: 'components.pagination');

$users = computed(fn() => User::paginate(50));

@volt
  <div>
	  <div class="max-w-7xl mx-auto py-12 space-y-6">
		  <h1 class="text-xl font-bold">Blog: {{ $this->getPage() }}</h1>
		  <ul>
			  @foreach($this->users as $user)
				  <li>
					  {{ $user->name }}
				  </li>
			  @endforeach
		  </ul>
  
		  <div>{{ $this->users->links() }}</div>
	  </div>
  </div>
@endvolt
```

**Comment by calebporzio** [comment]
This has been fixed and will be available in the next beta release
