### ISSUE TITLE
[v3]: Validation inside Form component - required_if don't work.

### ISSUE THREAD

**Issue by peroxovy** [livewire/livewire#6285]
### Discussed in https://github.com/livewire/livewire/discussions/6280

<div type='discussions-op-text'>

<sup>Originally posted by **peroxovy** August  8, 2023</sup>
Hello, I'm using Livewire 3 for tests and it seems that if I put inside the `FormComponent` Rules like:

```php
    #[Rule('required|string|exists:types,type_key')]
    public $type = 'text';

    #[Rule('required_if:type,text|string')]
    public $text;

    #[Rule('required_if:type,name|string')]
    public $name;
```
It seems  that it does not work properly. When I `dd($this->form);` inside the `Post` Livewire component I see all fields from form...

Currently I have `<select>` inside form, which is responsible for showing/hiding fields in it depending on `<select wire:model="type">` value:

` <x-forms.select-option :options="$types" wire:model.live="type" required/>`

Implementation how I show fields inside Component:

```html
@if($form->type == 'text')
<div class="p-2 block">
      <x-forms.label-text for="form.text">Text</x-forms.label-text>
      <x-forms.input-text wire:model.defer="form.text"/>
      <div>@error('form.text') {{ $message }} @enderror</div>
</div>
@endif
```
The inputs with rule value `required_if:` shows an error like : `The text field must be a string.` when I switch, to the `type` that shouldn't be taken into consideration.

This is how I done checking:
```php
class Post extends Component
{
    public FormComponent $form;

    public function render()
    {
        $types = app(GetAllTypesAsKeyValueArrayService::class)->execute();

        return view('livewire.post', ['types' => $types]);
    }

    public function store()
    {
        dd($this->form);
    }
```

F.e. I want to see 2 values passed to component, but I see all of them (let's say 5), with `null` value (filled inputs are okay with values).

In past Livewire versions, when I initialize `$rules = [ ]` array in single all things was working. Now with new version, when I want to separate the `form` logic and validation, problems come.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
