### ISSUE TITLE
Add Different Loading Attributes

### ISSUE THREAD

**Issue by ManojKiranA** [livewire/livewire#629]
**Is your feature request related to a problem? Please describe.**
No its Not a Problem.

**Currently Here is the List of Loading States in Livewire**

1. wire:loading
2.wire:loading wire:target="controlName"
3. wire:loading.class="classToAdd"
4. wire:loading.class.remove="classToRemove" 
5. wire:loading.attr="attributeName"

**Currently Suggesting following directives**

1. wire:initialLoad
2. wire:initialLoaded `or` wire:initialLoadCompleted
3.wire:loadingCompleted `or`  wire:loaded  (This is Inverse of  `wire:loading`)

**Comment by calebporzio** [comment]
No plans on adding these right now. Thanks
