### ISSUE TITLE
Vue components inside of blade @if statements do not work on reload.  

### ISSUE THREAD

**Issue by jgile** [livewire/livewire#631]
**Describe the bug**
The most basic of examples do not work if Vue component is within an @if statement.
If there is no @if statement, the component remains reactive on reload.
If the component is within the @if statement, it renders, but will never react to events.

ExampleComponent.vue
```
<template>
    <div class="container">      
        <button class="bg-blue-500" @click="clickEvent">Click Me</button>     
    </div>
</template>

<script>
    export default {
        methods: {
            clickEvent() {
                console.log('clickEvent');
            }
        }
    };
</script>

```

gride.blade.php
```
<div>
    <button wire:click="$set('show', {{ $this->show ? 'false' : 'true' }})">Toggle</button>

    <div>
        @if($this->show)
            <example-component></example-component>
        @endif
    </div>
</div>

```

Grid.php
```
<?php

namespace App\Http\Livewire\Tinker;

use Livewire\Component;

class Grid extends Component
{
    public $show = false;

    public function render()
    {
        return view('livewire.tinker.table');
    }
}

```

**To Reproduce**
1. Place a Vue component within an @if statement.
2. After livewire reloads, it will always lose reactivity.

**Expected behavior**
Vue components within @if statements function as normal.

**Desktop (please complete the following information):**
 - Chrome

**Comment by xxdalexx** [comment]
`wire:ignore` I think will fix it. https://laravel-livewire.com/docs/third-party-libraries/

**Comment by jgile** [comment]
`wire:ignore` does not change behavior in any way, unless i'm using it incorrectly.

Same behavior (no reactivity):
```
<div>
    <button wire:click="$set('show', {{ $this->show ? 'false' : 'true' }})">Toggle</button>

    <div>
        @if($this->show)
            <example-component wire:ignore></example-component>
        @endif
    </div>
</div>
```

Same behavior  (no reactivity):
```
<div>
    <button wire:click="$set('show', {{ $this->show ? 'false' : 'true' }})">Toggle</button>

    <div>
        @if($this->show)
            <div wire:ignore>
                <example-component ></example-component>
            </div>
        @endif
    </div>
</div>
```
Does not render at all:
```
<div>
    <button wire:click="$set('show', {{ $this->show ? 'false' : 'true' }})">Toggle</button>

    <div wire:ignore>
        @if($this->show)
            <example-component ></example-component>
        @endif
    </div>
</div>
```

**Comment by jgile** [comment]
On further inspection, I don't think it is even possible for this to work with the current hooks being used to add Vue support. 

The current "SupportVueJs.js" hook renders Vue components html but removes the bindings.

I could be wrong but I would think the nodes need to be mounted somewhere closer to render.  As of now it is mounting, firing Vue lifecycle hooks, and removing the bindings.

```
    store.registerHook('beforeDomUpdate', (component, mutableHtmlContainer) => {
        if (! window.Vue) return

        const div = document.createElement('div')
        div.innerHTML =  mutableHtmlContainer.html

        // At this point, bindings are intact.
        new window.Vue().$mount(div.firstElementChild) 

        // At this point the rendered html is added but the Vue binding are lost (I think).
        mutableHtmlContainer.html = div.firstElementChild.outerHTML 
    })
```

**Comment by mikev032** [comment]
Agreed  https://github.com/livewire/livewire/issues/626

**Comment by calebporzio** [comment]
Vue support has been moved to a third-party package in favor of built-in Alpine integration. Please submit Vue related issues here: https://github.com/livewire/vue
