### ISSUE TITLE
Cannot use static properties in Component class

### ISSUE THREAD

**Issue by rumansaleem** [livewire/livewire#632]
Mere declaration of a static property in Component class, throws ErrorException: Accessing static property `\App\Http\Livewire\SomeComponent::$staticProp` as non-static.

**To Reproduce**
1. Create a Livewire component,
2. Declare `public static $dummyProp = 'dummy';` in the component class
3. Open component in browser

**Expected behavior**
Static properties should be allowed on Component class

**Screenshots**
![Screenshot from 2020-02-24 00-18-46](https://user-images.githubusercontent.com/25204498/75117725-0cec8180-569a-11ea-8f76-96bc9a78b0b9.png)

**Comment by calebporzio** [comment]
Right now, you should be able to add it as a "protected static" property.

Does it need to be public? Are you planning on mutating it and it preserving its state across Livewire requests?

**Comment by rumansaleem** [comment]
No, it doesn't need to be public in my case and making it protected resolves the issue (though I solved it the other way using AlpineJs, I don't even remember why I was doing that 😅). But, I feel it should be fixed. 

I'd be happy to contribute, maybe we just need a check there for public static properties and using the reflection API to access the property value. (haven't yet looked deeper into the source code).

And by the way, thank you @calebporzio for this amazing framework. 👍

**Comment by calebporzio** [comment]
Great, glad your past it. Let's hold off on a fix and see if others hit this too. Thanks!

**Comment by mrashidtufail** [comment]
what if variable need to be public and we dont want to use alpinejs for a moment ?

**Comment by Netizens-Bhupendra** [comment]
how can I use static property data inside the livewire component?
