### ISSUE TITLE
Minify Livewire's payload

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#633]
**Is your feature request related to a problem? Please describe.**
Yes, when I try to read livewire's payload in the developer tools, there's too much white space and the actual data that I want is truncated in the view.

**Describe the solution you'd like**
Can we minify the payload? this boosts the speed, saves bandwidth, and makes debugging easier.

**Comment by Namoshek** [comment]
In combination with `white-space: pre` CSS, having all the white space (line breaks and indentation) may actually break the layout. I noticed that Chrome performs some sort of _cleanup_ for the first render of a page, but when Livewire replaces part of the DOM, Chrome _does not_ repeat this step and suddenly white space is rendered and causes interesting layout changes.

The following is basically a component with one button which acts as toggle. Initially, everything looks fine (but when refreshing the page, it is slightly noticeable that the layout is corrected by Chrome):
![1_ok](https://user-images.githubusercontent.com/8877609/81854254-f699e780-955d-11ea-8fae-00aa8ad535c4.png)

After triggering a toggle and forcing a re-render of the component DOM, the layout breaks:
![2_broken](https://user-images.githubusercontent.com/8877609/81854252-f568ba80-955d-11ea-9b3a-d80eecc66259.png)

Not sure if this is the only negative side-effect of the white space within the response or if there is actually more.

**Comment by calebporzio** [comment]
Livewire needs to preserve at least one breaks. Whitespace is difficult to strip out without altering text blocks.

I used to do some minifying, but it caused too many problems.

**Comment by Namoshek** [comment]
Can you elaborate on why Livewire needs at least one line break? Maybe we can come up with a good solution together.
