### ISSUE TITLE
Rule validation

### ISSUE THREAD

**Issue by Tresor-Kasenda** [livewire/livewire#6351]
### Discussed in https://github.com/livewire/livewire/discussions/6350

<div type='discussions-op-text'>

<sup>Originally posted by **Tresor-Kasenda** August 14, 2023</sup>
 #[Rule([
        'required',
        'integer',
        'exists:categories,id'
    ])]

 i would know how add a additional rule of ignore type  to the livewire validation system `Rule::unique('category', 'id')->ignore($this->id) `</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
