### ISSUE TITLE
Blade-x component scripts

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#637]
If you use blade-x to create a component that contains some script, the script will never run.
Let's say we want to create a `<select2 />` component with blade-x that contains the script necessary for initializing the select. If this was a livewire component we could just `@push` to the scripts stack at the end of our components and it would run after first render, but if you push to the stack script inside your blade-x component and use that in your livewire component it will never run.

Any ideas how to fix this?

**Comment by intellow** [comment]
I'm not sure how to fix your problem, but as an FYI you may want to look into upgrading to Laravel 7 when it comes out. It will provide a new blade component that will work well with Livewire, and then you probably will not need to use blade-x anymore.

**Comment by mokhosh** [comment]
I don't think they're radically different. If what I've understood from Taylor's tweets is correct, he's just integrating blade-x into Laravel.

**Comment by lancepioch** [comment]
I believe this may be fixed with #954 

If it hasn't with the latest Livewire version, let us know!
