### ISSUE TITLE
Too many modals when polling. Freezes browser and eventually whole system

### ISSUE THREAD

**Issue by rumansaleem** [livewire/livewire#639]
**Describe the bug**
When polling for a method, in case of errors the showHTMLModal function keeps adding new modal every single time. 

The problem here is that, too many modals overlaying on top of each other freezes the browser.

**To Reproduce**

1. Make a livewire component `PollOnError`
```php
<?php

namespace App\Http\Livewire;

use App\QuizSession;
use Livewire\Component;

class PollOnError extends Component
{
    public $session;

    public function render()
    {
        return view('livewire.poll-on-error');
    }

    public funcition errorOnPoll()
    {
           throw new Exception('CAUTION: It may freeze your system if left unnoticed');
           // comment out this line soon after a number of poll reaches, or your system may freeze.
    }
}
```
2. Make this component poll on the method `errorOnPoll` in your livewire template view:
```
<div wire:poll.2s="errorOnPoll">
      A new error modal after every 2 seconds.
</div>
```
3. Define a route for this component in `web.php`
```
Route::livewire('/poll-on-error', 'poll-on-error');
```
 
4. Open `/poll-on-error` in your browser.

**Expected behavior**
I don't know if there is the need of a new modal for every error, IMO only a single modal should be reused. 

![Screenshot from 2020-02-26 15-09-02](https://user-images.githubusercontent.com/25204498/75332173-f4eb4c80-58a9-11ea-9cbd-5f0185af3858.png)
Same modal is added for every poll request.

**Desktop (please complete the following information):**
 - Browser: Firefox 70.0

**Additional context**
I know that we can override `showHtmlModal` function to reuse only one modal. But, I wonder if this is a common problem and requires to be fixed in core?

**Comment by mhetreramesh** [comment]
I've sent a pull request which fixes this issue :fire: :+1:  Here https://github.com/livewire/livewire/pull/686

**Comment by lancepioch** [comment]
The pull request has been merged in the latest version, let us know if it's still an issue rumansaleem
