### ISSUE TITLE
Events for already removed components from the DOM

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#640]
**Describe the bug**
I am building an SPA using **only** livewire and a css-only framework. It is a refactoring of a bigger project and intended to see what problems arise on the way.

Individual components communicate  with each other using livewire events.

I use small livewire components as **brokers** to switch between a set of lover-level livewire components. The blade view of these brokers looks something like this:

```blade
@if($state == 'dashboard')
   @livewire('content-dashboard')
@elseif($state == 'list')
   @livewire('content-list')
@elseif($state == 'detail')
   @livewire('content-detail')
@endif
```

The corresponding component listens for a _changeContent_ event and renders the correct livewire component.

> This works as expected. However ..... what If the lower-level component also listens for events?

In some cases the event is dispatched for the lower level component, the broker component than switches to a different lower level component and after that data is received for the lower level component that was already removed from the DOM.

```javascript
index.js:23 Uncaught (in promise) TypeError: Cannot read property 'receiveMessage' of undefined
    at Connection.onMessage (index.js:23)
    at Object.Connection.driver.onMessage (index.js:9)
    at http.js:30

 onMessage(payload) {
        if (payload.fromPrefetch) {
            componentStore.findComponent(payload.id).receivePrefetchMessage(payload)
        } else {
            componentStore.findComponent(payload.id).receiveMessage(payload)

            dispatch('livewire:update')
        }
    }
```
As can be seen above, the findComponent method cannot retrieve the lower-level component anymore.

Quick and dirty solution would be to just add a check. Something like:
```javascript
 onMessage(payload) {

           component =  componentStore.findComponent(payload.id);
           if(component) {

               if (payload.fromPrefetch) {
                   component.receivePrefetchMessage(payload)
               }
               else {
                   component.receiveMessage(payload)
                  dispatch('livewire:update')
               }

           }
        
    }
```

However, i think it would be better if the event for the lower level component would not have been dipatched at all. That way we could spare ourselves an ajax call also.

Could someone shine a light on this situation?

**Just so you know .....**
Building an SPA using only livewire works. It needs some extra work to rebuild the laravel authentication system. But the workflow is clean and the code is maintanable. In my opinion it is a lot cleaner than combining livewire with turbolinks.

**Comment by calebporzio** [comment]
You can use `$this->emitUp` to only emit to parent components and not siblings, would that do it? or is it still an issue?

**Comment by ducopro** [comment]
Hi Caleb,

Yes, I am using emitUp now. That solves the problem. Using good/unique  *wire:key* syntax also sometimes does the trick.

For now we can close this issue.
