### ISSUE TITLE
[1.0.0] Removed wire:transition?

### ISSUE THREAD

**Issue by psos** [livewire/livewire#643]
Hello!,

Regarding wireframe upgrade to 1.0.0 and removal of the wire:transition option, I would like to ask about a suggested solution AlpineJS on the example of multilevel dropdown selects.

Currenty I used :
`@if($this->selectedVendorId > 0)`
`                <span">Model</span>`
`                <select wire:transition.fade.in wire:model="selectedModelId">`
`                    @foreach($models as $model)`
`                    <option value="{{ $model['id'] }}">{{ $model['name'] }</option>`
`                    @endforeach`
`                </select>`
`@endif`

My solution is:
``
`<div x-data="{  showSelectModel : {{ $this->selectedVendorId > 0 ? 'true' : 'false' }} }">`
....

` x-show.transition.fade.duration.200ms="showSelectModel"`

In my opinion it makes  overload of code. 
wire:transition directive was better to use.

Regards,
Pawel

**Comment by lancepioch** [comment]
We are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. If you still feel this is relevant, please create a discussion there, thanks a bunch!
