### ISSUE TITLE
Spacing issue in Javascript Output by LivewireManager::javascriptAssets

### ISSUE THREAD

**Issue by JacobHollis** [livewire/livewire#644]
Having updated to v1 livewire is no longer working on an azure instance of my app but works fine locally.

The error I am getting from azure lead me to find the function that outputs the livewire scripts is getting minified differently by the azure server such that there is no longer any space between the closure that has window.livewire.start();}) and the definition of var firstTime (lines 245 and 247 of LivewireManager.php).

This is how azure serves the script:
![Javascript as served from Azure](https://user-images.githubusercontent.com/41264948/75471356-10c61f80-598a-11ea-9f8f-e86b46ac4335.PNG)

And how it comes through locally:
![Javascript as served from Local](https://user-images.githubusercontent.com/41264948/75471453-32270b80-598a-11ea-8efd-3765f1466ea8.PNG)

I have managed to get my Azure instance working by inserting a random comment between the lines but I presume there is some better way of doing it!?

EDIT: Actually regardless of which server its on this error happens if APP_DEBUG is set to false because the minify method gets called which strips out the new lines so something needs to be inserted between 245 and 247 or this will always happen when serving the minified scripts

**Comment by lancepioch** [comment]
I believe #642 may resolve this issue for you when it's merged.

However for now, you can look into disabling minification.

**Comment by JacobHollis** [comment]
Ahh, yes that does fix it, thanks!
