### ISSUE TITLE
[TemporaryUploadedFile] $tmpFile = tmpfile() returns false and throws error (line 23)

### ISSUE THREAD

**Issue by valtermedeiros** [livewire/livewire#6440]
### Discussed in https://github.com/livewire/livewire/discussions/6439

<div type='discussions-op-text'>

<sup>Originally posted by **valtermedeiros** August 21, 2023</sup>
**Location**: src/Features/SupportFileUploads/TemporaryUploadedFile
```php
 public function __construct($path, $disk)
    {
        $this->disk = $disk;
        $this->storage = Storage::disk($this->disk);
        $this->path = FileUploadConfiguration::path($path, false);

        $tmpFile = tmpfile(); //<---------------------------------------------------------- THIS HERE : line 23

        parent::__construct(stream_get_meta_data($tmpFile)['uri'], $this->path);
    }
```

### Problem 
When "tmpfile()" on line 23 **returns false**, everything collapses, throwing this error:
stream_get_meta_data(): Argument #1 ($stream) must be of type resource, bool given

### Cause
tmpfile() returns false, and since it is a param after on stream_get_meta_data(), it fails and throws the error

### My fix was to use the Storage facade: 
$tmpFile = fopen(Storage::path($this->path),'r');
or
$tmpFile = fopen(storage()->path($this->path),'r');

```php
 public function __construct($path, $disk)
    {
        $this->disk = $disk;
        $this->storage = Storage::disk($this->disk);
        $this->path = FileUploadConfiguration::path($path, false);

        $tmpFile = fopen(Storage::path($this->path),'r'); //<---------------------------------------- FIXED

        parent::__construct(stream_get_meta_data($tmpFile)['uri'], $this->path);
    }
```

</div>

**Comment by PhiloNL** [comment]
Thanks for the issue but as you mentioned, there is already an ongoing bug report [here](https://github.com/livewire/livewire/discussions/6439).
