### ISSUE TITLE
New initial component parameters format with variadic parameters

### ISSUE THREAD

**Issue by mikemand** [livewire/livewire#645]
I haven't dug into the code to figure out how you are passing parameters from Blade to the component, so this may be a stupid question... If my component accepts a variable number of parameters, how do I handle this with the new array syntax? Or is the old syntax still supported? Are there plans in the future to remove the old syntax?

For example, I'm using @kdion4891's [Livewire Tables package](https://github.com/kdion4891/laravel-livewire-tables). One of my tables is for a relationship of a model so I need to pass that model to the component. Because of how PHP works, I cannot declare my component (which extends his table component) with parameters on the `mount` method because his doesn't have any parameters. I'm using `func_get_arg(0)` to grab the first parameter (which is my model) and this works fine in v0.7. But with the new array syntax, I don't have an actual variable to match the key of the array. How do I handle this? A simple array (`[$model]`)? Or with a numeric key (`[0 => $model]`)?

**Comment by mikemand** [comment]
I ran through as many variations I could think of, and I am unable to figure out how to deal with this. Simple arrays and numeric keys did not work, `func_get_arg()` complained about `Argument 0 not passed to function`.

I'm going to try with `func_get_args()` instead, and see if it will just grab all the parameters supplied. It's too bad I can't use [`$argv`](https://www.php.net/manual/en/reserved.variables.argv.php) here, huh? 😆

**Comment by ninthspace** [comment]
I would like to be able to extend components, so that common functionality can be self-contained, but mount parameters need to be identical. To work around this issue, I'm currently transferring common functionality into a trait, because you can override methods that are within traits without issue.

**Comment by mikemand** [comment]
So, I was able to extend @kdion4891's class with my own "base" class and put a parameter in my base `mount` method:

```php
public function mount(?Model $model = null)
{
	parent::mount();
}
```

Why it works using a class that extends a class that extends a class is a mystery known only to the PHP developers. I expected the same error* from when I extended his class directly, but I'm not looking a gift horse in the mouth.

*`Declaration of App\Http\Livewire\ExpensesTable::mount(App\User $user) should be compatible with Kdion4891\LaravelLivewireTables\TableComponent::mount()`
