### ISSUE TITLE
In nested components,  key() expects array. integer given error. When I try to pass other value for mount()

### ISSUE THREAD

**Issue by fahim152** [livewire/livewire#647]
As per documentation [here](https://laravel-livewire.com/docs/nesting-components/) , if we load a component inside a loop we've to use key( ) syntax and pass the id as param. But I tried and it gives error, expecting to pass array instead integer.  Point to be noted, I am passing an extra param here which is 'productList'. I must need that value for some other task. without that value , it is working fine, But just when I try to pass a value for mount() after key(), its giving error.

``` 
@livewire('user-profile', $user, key($user->id)) 

```
Logically we can pass other param by adding like:  
```
@livewire('user-profile', $user, key($user->id), 'param1', 'param2') 
```
Which will be passed in mount($userId, $param1, $param2);

here is my code snippet. 

```
<div>
    @foreach($products as $product)
        <div class="product-box white-bg mb-8" data-dusk="product"> 
             {{-- here im passing product id as param in key(),  'productList' is a static value for a variable of mount(). --}}
                @livewire('desktop.wish-list-add', $product, key($product->id), 'productList')

            <div class="product-content d-flex justify-content-between align-items-center p-5">
                ............... 

    @endforeach
    {{ $products->links() }}
</div>

```

Edit: see my comment below, regarding how to make it work ...

**Comment by fahim152** [comment]
Okay i think I found how to make it work, 

I've to write like this: 

```
@livewire('desktop.wish-list-add', 'productList', $product->id, key($product->id))

```

instead of this: 
```
@livewire('desktop.wish-list-add', $product, key($product->id), 'productList')

```

**Comment by lancepioch** [comment]
Thanks for the provided solution to users.

We are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. If you still feel this is relevant, please create a discussion there, thanks a bunch!
