### ISSUE TITLE
CSP content security policy nonce support

### ISSUE THREAD

**Issue by liepumartins** [livewire/livewire#650]
Modern web applications employ feature called Content-Security-Policy, which whitelists allowed scripts, styles, fonts, iframes and prevents execution/application of others.

**Describe the solution you'd like**
Modify directives `@livewireStyles` and `@livewireScripts` to accept an optional nonce parameter.
So the output instead of `<style></style>` becomes `<style nonce="hashvaluehere">...</style>` and respectively `<script nonce="hashvaluehere">...</script>`

**Describe alternatives you've considered**
One could copy the entire output of `@livewireStyles` and add the nonce manually.
However if this output changes, one has to update `layout.blade.php` each time it happens.
`@livewireScripts` is little trickier as it includes dynamic token, but idea is basically the same. And has same limitation about changes.

**Comment by liepumartins** [comment]
Another approach, suggested for same feature in another package.

Define in the package config a callback to the function that provides the nonce.

Example: popular csp package for laravel is https://github.com/spatie/laravel-csp, which has the `csp_nonce()` helper function, in this case config/livewire.php would be

```php
...
'csp_callback' => 'csp_nonce',
...
```

And modify the templates accordingly to include nonce, if the `csp_callback` value is provided.

**Comment by calebporzio** [comment]
The next version of Livewire will contain a way to specify a nonce in Livewire's generated inline script tag.

Here's the gist: `@livewireScripts(['nonce' => 'some-nonce'])`

Here's the PR: https://github.com/livewire/livewire/pull/1156

**Comment by sscotti** [comment]
I had to do something like:
```
<?php $nonce = ["nonce" => csp_nonce()] ?>
@livewireScripts($nonce)
```
 To get that to work, and for Styles, edit / override LiveWireManager.php
 
```
     protected function cssAssets()
    {
        $nonce = "";
        if (null !== csp_nonce()) $nonce = 'nonce = "' . csp_nonce() . '"';
        return '<style ' . $nonce  . '>[wire\:loading], . . . . .
```

**Comment by Enaah** [comment]
There is a space in front of the `nonce`-Attribute missing.

I just created a PR: https://github.com/livewire/livewire/pull/3393
