### ISSUE TITLE
Back button is not working when using Turbolinks and update query strings feature

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#652]
**Describe the bug**
Consider a project using Turbolinks. When we are on a page that is using the Livewire update query strings feature (e.g.: a crud index page), then we navigate to another page (e.g: a detail page), then hit the back button, the navigation bar gets updated with the last URL (including query string) but the page is not rendered, I mean, it keeps the current detail page active.

**To Reproduce**
1. On a project using Turbolinks, on a crud index page, change something that updates the query string (e.g.: search field or datatable sorting);
2. Click to view a record from the datatable. You will be redirected correctly to the detail page;
3. Hit the browser's back button;
4. The navigation bar will be updated with the previous URL (keeping the query string) but no redirection will happen.

**Expected behavior**
User should be redirected to the last visited page.

**Desktop (please complete the following information):**
 - Chrome Desktop

**Comment by lancepioch** [comment]
I believe this has been resolved with #957
