### ISSUE TITLE
Bug with Pagination Links

### ISSUE THREAD

**Issue by KarimQaderi** [livewire/livewire#653]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32425175/75585047-77306800-5a86-11ea-9b59-4c10d72b9a96.png)

**To Reproduce**
1. Click on 'Like Post'
1. Click on 'Link pagente ex 91'
4. See change link

```
class Demo2 extends ResourcePageLivewire
{
   public $name2 = 5;

    public function render()
    {
        return view('livewire')->with([
            'items' => Post::paginate(2)
        ]);
    }

    public function addLike()
    {
        $this->name2 += 5225;
    }
}
```

```
<div>
    {{ $name2 }}
    <button wire:click="addLike">Like Post</button>

    @foreach ($items as $item)
        {{$item->name}}
    @endforeach

    {{ $items }}
</div>
```

**Comment by GertjanRoke** [comment]
Hello, you should add the trait for pagination of Livewire it self.

As this:
```
use WithPagination;
```

This will replace the Laravel pagination links with the Livewire version, so it will also not do full page reload but only reload the component.

**Comment by KarimQaderi** [comment]
tnx
