### ISSUE TITLE
Forcing rerender of nested @livewire components

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#654]
I'm currently running into an issue with Livewire, nested components, and models. The issue can be seen in below GIF where the names change **(main component)** but the IDs stay static **(child component)** as they are rendered inside the modal component which contains a button. This will eventually result in a 404 on clicking delete on an entry because they IDs will be messed up.

This is obviously the expected behavior because these components are not reactive but would there be a way to force a rerender of those nested components without having to do a full page reload?

I currently circumvent this issue by copying the contents and functionality of the modal component into the list component but that ends up in copy-paste duplication in quite a few places.

**Component**
![Screen Recording 2020-02-29 at 9 06 28](https://user-images.githubusercontent.com/22145591/75603027-462a5480-5ad3-11ea-90f8-42e92ef5c78d.gif)	

**List Component**
```blade
<div>
	@foreach($this->tokens as $token)
		{{ $token->name }}
            
		@livewire('delete-personal-token', $token, key($loop->index))
	@endforeach
</div>
```

**Modal Component (emits an event to $refresh list component)**
```blade
<div>
    {{ $token->id }}
    
	<button class="ml-4 text-right text-red-800 hover:text-red-900 focus:outline-none">Delete</button>
</div>
```

**Comment by tiago-sb** [comment]
Hi @faustbrianhave,
Have not tested it but I’d say you should not use the $loop->index as a key. 
Try instead to use $token->id or some other property that uniquely identifies the token and that does not change depending on the position (in the list/loop) of the element.

**Comment by faustbrian** [comment]
I did try that as I realised shortly after that this might be the cause but the problem persists. Like I said in the OP I'm currently working around this by simply not having an extra livewire component but instead juts embedding the functionality into the main component.

**Comment by lancepioch** [comment]
We are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. If you still feel this is relevant, please create a discussion there, thanks a bunch!

**Comment by keevitaja** [comment]
@faustbrian did you find a solution?

**Comment by ninthspace** [comment]
I've just encountered the same problem even when using unique ids for the nested components. This might be because I render the components inside a slot which is part of a Blade component. Anyhow, it appears that because the id doesn't change Livewire doesn't see any reason to re-render anything.

What I did to solve it was use a different key that changes when the underlying model changes, e.g., inside the model:

```php
public function livewireKey()
{
    return md5("$this->id.$this->updated_at");
}
```

and then when rendering the nested components:

```html
<livewire:mycomponent :key="$instance->livewireKey()"/>

**Comment by ryanmortier** [comment]
@ninthspace Such a perfect solution. Thanks!

**Comment by baralogi** [comment]
> I've just encountered the same problem even when using unique ids for the nested components. This might be because I render the components inside a slot which is part of a Blade component. Anyhow, it appears that because the id doesn't change Livewire doesn't see any reason to re-render anything.
> 
> What I did to solve it was use a different key that changes when the underlying model changes, e.g., inside the model:
> 
> ```
> public function livewireKey()
> {
>     return md5("$this->id.$this->updated_at");
> }
> ```
> 
> and then when rendering the nested components:
> 
> ```
> <livewire:mycomponent :key="$instance->livewireKey()"/>
> ```

save my day! great thanks!
