### ISSUE TITLE
Put scripts in the head with defer attribute?

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#662]
**Is your feature request related to a problem? Please describe.**
Turbolinks suggests putting app scripts in the head tag with `defer` attribute. Also I don't know if this is the exact reason or not, but when I put scripts at the end of `body` Turbolinks takes a couple of seconds to go back in history, but when the scripts are in the `head` there is no lag.

I think there was a `defer` attribute on the livewire script tag when we were loading it with `@livewireAssets`. Is there any particular reason why it got deleted?

**Comment by calebporzio** [comment]
Yeah, there is a reason, but I don't think it's really that necessary anymore.

Was thinking about reverting to the "defer" strategy.

Curious, are you using @livewireScripts ? or are you loading the assets yourself?

**Comment by mokhosh** [comment]
Just for future reference, what was the reason?
I'm using @livewireScripts

Also, since this is about Turbolinks integration, I discovered that none of the new pages fetched by Turbolinks were functioning, and I had to refresh. What could I have been doing wrong?!

**Comment by lancepioch** [comment]
@mokhosh Is this still relevant with the latest version of Livewire?

Is so, then could you create a [Github Discussion](../discussions)? We are hoping that this will encourage and centeralize feedback relating to discussions like this.

**Comment by colinmac17** [comment]
I do believe this is still an issue. I am experiencing this on versions 1.1 https://github.com/livewire/livewire/issues/1022
