### ISSUE TITLE
Wrong pagination link for a list that just got paginated

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#663]
I've set pagination count to 10. I have 10 items in my list. I create another item and the pagination links show up but with wrong links (it's the route name). Is it only me or has this happened to anyone else?

**Comment by GertjanRoke** [comment]
Did you also add the trait to you component class?

```
use WithPagination;
```

Because that should replace the Laravel pagination links with the Livewire version.

**Comment by mokhosh** [comment]
Of course, how else would I get the links in the first place?

**Comment by GertjanRoke** [comment]
Your variable name and call the links method:
```
<div class="container">
    @foreach ($users as $user)
        {{ $user->name }}
    @endforeach
</div>

{{ $users->links() }}
```

And then your done.

**Comment by mokhosh** [comment]
@GertjanRoke Thanks for taking the time, but I have the links. Everything works just fine. The only problem is when I add the single item that makes the query builder start paginating the results, that's when I get incorrect link hrefs.

**Comment by GertjanRoke** [comment]
I would love to help you but then I need some code to see the thing you’re trying to solve.

**Comment by alexjustesen** [comment]
I'm having the same issue, latest version of Laravel 6.18 and Livewire 1.0.1.

Use in livewire view:
```php
@ foreach($foo as $bar)
    ...
@ endforeach

$foo->links();
```

User in livewire component:
```php
use Livewire\Component;
use Livewire\WithPagination;

use App\Foo;

class fooTable extends Component
{
    use WithPagination;

    public function render()
        $collection = Foo::query()
            ->when($search, function($query, $search) {
                return $query->where('name', 'like', '%'. $this->search .'%';
            )};
            ->paginate(10);

        return view('livewire.foo-table', ['foo' => $collection])
}
```

My pagination view is the standard Laravel pagination view updated to use Tailwind UI.

**Comment by GertjanRoke** [comment]
Apart from some typos in your example I don’t see anything wrong.. I will try to reproduce it.

**Comment by GertjanRoke** [comment]
Hmm.. works fine for me with Laravel 6.18 and Livewire 1.0.1
This is how it looks like:

Model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foo extends Model
{
    protected $guarded = [];
}
```

Component:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Foo as FooModel;
use Livewire\WithPagination;

class Foo extends Component
{
    use WithPagination;
    
    /**
     * @var string
     */
    public $search = '';
    
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function render()
    {
        $collection = FooModel::query()
            ->when($this->search, function($query) {
                return $query->where('name', 'like', '%'. $this->search .'%');
            })
            ->paginate(10);
        
        return view('livewire.foo', [
            'foo' => $collection
        ]);
    }
}
```

View:
```
<div>
    <input type="text" wire:model="search">
    
    @foreach($foo as $bar)
        <li>{{ $bar->name }}</li>
    @endforeach
    
    {{ $foo->links() }}
</div>
```

So if you have done it like this and it still isn't, I think you should try to `dump($collection)` and slowly debug what is going wrong.

**Comment by alexjustesen** [comment]
Did a dump of the collection this morning, in the options I'm getting a livewire message path instead of the expect page.

```json
#options: array:2 [▼
    "path" => "http://127.0.0.1:8080/livewire/message/foo-table"
    "pageName" => "page"
  ]
```

**Comment by GertjanRoke** [comment]
@alexjustesen hmm.. strange, it shows the page where the components are shown for me, is it maybe something you changed to the pagination view or did you add something to the `->links()` method?

If you would like to share that, I think the problem is maybe somewhere there, because you both said you had custom view for the pagination.

**Comment by mokhosh** [comment]
Same. This is the url that my pagination links have:
```
/livewire/message/admin.episodes?page=1
```
I also get this bug when I do something that causes a livewire back-and-forth on a paginated page. The links get messed up.

**Comment by alexjustesen** [comment]
I whipped up a quick repo to show the error, it can be found here: https://github.com/alexjustesen/livewire-pagination-error

**Comment by alexjustesen** [comment]
After more digging, looks like the issue comes up with overriding the pagination view, I've updated the repo to show the error.

**Comment by alexjustesen** [comment]
This issue was also reported in #420

**Comment by GertjanRoke** [comment]
Hey Alex, I was just looking at the pagination view you wanted to use and that is the problem.
Your using the normal http links instead of the wire:click function Livewire uses in there own view.

I will update this comment with a link to the original pagination view that Livewire uses in a sec.

**Comment by verdenkaf** [comment]
@GertjanRoke 

Thanks, was missing the wire:click as well, fully working with custom views now.

**Comment by GertjanRoke** [comment]
@mokhosh I'm just playing around with Livewire some more and I maybe ran into the same issue you have.

Do you use the `$this->fill([...])` method inside your component?

**Comment by dave-alvarez** [comment]
@GertjanRoke @mokhosh The WithPagination Trait and pagination-links blade view use wire:click buttons calling its methods nextPage(), previousPage() and gotoPage() in place of the normal $paginator->nextPageUrl() type of URL generation. 

Any pagination requests beyond the initial page load will now show the Livewire XHR request URLs if you try to use Laravel's paginator URL methods or something like the url() helper.

Because I'm adding some SEO-friendly link types for prev, next and canonical, what I'm doing for the time being is passing the route name to the Livewire pagination view generator:

`{{ $results->links('my-pagination-blade-view', ['routeName' => 'my-route-name']) }}`

Then in my own pagination blade view, I'm using this, which is inserted in the head of the page layout:

```
@if ($paginator->hasPages())

<link rel="canonical" href="{{ route($routeName) }}">

@unless ($paginator->onFirstPage())
<link rel="prev" href="{{ route($routeName, ['page' => $paginator->currentPage() - 1]) }}">
@endunless

@if ($paginator->hasMorePages())
<link rel="next" href="{{ route($routeName, ['page' => $paginator->currentPage() + 1]) }}">
@endif

@endif
```

**Comment by mokhosh** [comment]
> @mokhosh I'm just playing around with Livewire some more and I maybe ran into the same issue you have.
> 
> Do you use the `$this->fill([...])` method inside your component?

I do.

My components have gotten very complex by now. I have an abstract Livewire component that almost uses all of Livewire's features, then I have little components that inherit from that abstract component.

But the link you sent actually solved my problem:
https://github.com/livewire/livewire/blob/master/src/views/pagination-links.blade.php

I changed the default tailwind pagination views to use `wire:click` and everything is working so far.

**Comment by jetwes** [comment]
I have a strange behaviour here (livewire 1.0.12, even with the default livewire pagination): After clicking on a pagination link the same page is loaded, only after clicking a second time on the same link the correct page is loaded... any suggestions?

**Comment by jetwes** [comment]
[08-04-_2020_12-18-29.zip](https://github.com/livewire/livewire/files/4449827/08-04-_2020_12-18-29.zip)
See in the console...

**Comment by johncarter-** [comment]
If anyone needs the default vendor Laravel Tailwind pagination in Livewire format, I made a gist: https://gist.github.com/johncarter-/122c7135e8923949e455c3c480fee2df

**Comment by HectorRC920** [comment]
> I'm having the same issue, latest version of Laravel 6.18 and Livewire 1.0.1.
> 
> Use in livewire view:
> 
> ```
> @ foreach($foo as $bar)
>     ...
> @ endforeach
> 
> $foo->links();
> ```
> 
> User in livewire component:
> 
> ```
> use Livewire\Component;
> use Livewire\WithPagination;
> 
> use App\Foo;
> 
> class fooTable extends Component
> {
>     use WithPagination;
> 
>     public function render() {
>         $collection = Foo::query()
>             ->when($search, function($query, $search) {
>                 return $query->where('name', 'like', '%'. $this->search .'%';
>             )};
>             ->paginate(10);
> 
>         return view('livewire.foo-table', ['foo' => $collection]);
>     }
> }
> ```
> 
> My pagination view is the standard Laravel pagination view updated to use Tailwind UI.

You just need to wrap the foreach in a div like this...
<div>
    @ foreach($foo as $bar)
    ...
     @ endforeach

$foo->links();
</div>

**Comment by alexRoca** [comment]
I had the same problem, when executing some function in livewire the pagination was initialized to page 1 and it did not stay in the page where it was previously ... to solve it add this class

use WithPagination;

and in this part

$ users-> links ()

I placed it like this

$ users-> links ('pagination :: bootstrap-4')

and it was solved

**Comment by MrMooky** [comment]
This is still an issue with the latest version. Livewire switches the `$paginator->nextPageUrl()` with `https://url.test/livewire/message/...`. This is really annoying! 

I'm using `use WithPagination;` and a custom pagination template, which basically just looks like this:

```
@if ($paginator->hasPages())
    @if ($paginator->hasMorePages())
        <a href="{{ $paginator->nextPageUrl() }}" class="pagination__next"></a>
    @endif
@endif
```

The error occurs after the component was refreshed / changed.

**Comment by joshhanley** [comment]
@MrMooky did you customise the Livewire specific pagination templates or Laravel's ones? Livewire has different pagination templates, but it looks like you are using the Laravel one. Livewire's templates don't have `<a href`, instead they have buttons with `wire:click` on them.

> When using either method, instead of anchor tags in your pagination component, you should use wire:click handlers with the following methods:
>
> `nextPage` to navigate to the next page
> `previousPage` to navigate to the previous page
> `gotoPage($page)` to navigate to a specific page.

See the note here https://laravel-livewire.com/docs/2.x/pagination

You can also just publish Livewire's templates, using `php artisan livewire:publish --pagination` which already has this on them, and then customise from there.

Hope this helps!

**Comment by MrMooky** [comment]
@joshhanley I see, thanks. What's odd is that it works when loading the page initially, only the `$refresh` breaks it. Problem is, I am using https://infinite-scroll.com here and it seems there is no way to combine this with Livewire then when I am not able to use an `href` tag.

**Comment by joshhanley** [comment]
@MrMooky you could use `a` tags, just make sure you put the `wire:click` and any other Livewire stuff on them the same as the buttons in Livewire's view 🙂 you may also need to add `.prevent` to the wire:click to stop the page from following the link, but not sure if that will effect your scroll library.

**Comment by Loukili-Rachid** [comment]
this is the simplest solution is only to use this trait WithPagination

add this trait to your livewire class 

 use WithPagination;
 
like this example


class MusiqueCategorySingersDetail extends Component
{ 
    use WithPagination;

**Comment by sodexteam** [comment]
well , I had the same problem and this is the solution
1. add, in Component controller, the attribute -> protected $paginationTheme = 'bootstrap';
2. execute -> php artisan livewire:publish --pagination
3.  in component view use just this -> {{ $products->links() }}

Done !

Note : verify if reactive pagination is working , this is the key

**Comment by Dawwwid** [comment]
I had the same problem with a custom pagination view and using links (HREF) instead of `wire:click` calling its methods `nextPage()`, `previousPage()` and `gotoPage()`

To get around the problem and have seo-friendly links, I added this method to the Livewire controller:

```
/**
 * When "Paginators" enters into action, we override the function that solves the path of pagination urls
 */
public function updatingPaginators()
{
    $queries = $this->except([ 'page', 'paginators' ]);

    foreach($queries as $property => $value)
    {
        if(isset($this->queryString[ $property ]['except']) && $this->queryString[ $property ]['except'] === $value)
        {
            unset($queries[ $property ]);
        }
    }

    Paginator::currentPathResolver(function() use ($queries){
        return route('routeName', $queries);
    });
}
```
We will have to add the call to `updatingPaginators()` in `mount()` for initialization:
```
public function mount()
{
    $this->updatingPaginators();
    $this->hydrate();
}
```
I hope it can help!

**Comment by DanielSpindler** [comment]
you literally only have to " use WithPagination;" cant understand why u did write that much when livewire had this already documented back in the days...

**Comment by mokhosh** [comment]
@DanielSpindler thanks, this problem was solved years ago, and your suggestion was the first suggestion that was made here and it wasn't helpful.

cheers

**Comment by DanielSpindler** [comment]
@mokhosh no problem, just left it for people that run in to it in the future and dont want to read through most posts :)
