### ISSUE TITLE
Uncaught Component already initialized when using "simplebar"

### ISSUE THREAD

**Issue by thotam** [livewire/livewire#6664]
### Discussed in https://github.com/livewire/livewire/discussions/6049

<div type='discussions-op-text'>

<sup>Originally posted by **addtobag** July 28, 2023</sup>
I'm seeing this error message when clicking a wire:navigate link, has anyone come across the same?

<img width="810" alt="image" src="https://github.com/livewire/livewire/assets/77623201/5f7f6848-ec83-4b36-bc5f-1231d88a8bab">
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
