### ISSUE TITLE
Livewire v3 wire:ignore not working

### ISSUE THREAD

**Issue by bekovski** [livewire/livewire#6667]
I have the same problem with third party plugins. 
When I use `wire:ignore` it doesn't have the expected effect.

### Discussed in https://github.com/livewire/livewire/discussions/5813

<div type='discussions-op-text'>

<sup>Originally posted by **schonhoff** July 21, 2023</sup>
Hello,

I used some external javascript which is loading after Livewire init. In Livewire v2 I could just add `wire:ignore` to the parent node and it worked. Now it doesn't work and the documentation for Livewire v3 doesn't mention anything about `wire:ignore`. Was it removed? Is there another way for me to handle the situation?

The script I want to add is the google recaptcha.
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
