### ISSUE TITLE
[PHP] Drop PHP 7.1 and Laravel 5.x support

### ISSUE THREAD

**Issue by nuernbergerA** [livewire/livewire#669]
As you can see the overlap between [Laravel](https://laravel.com/docs/7.x/releases#support-policy) and [Livewire](https://github.com/livewire/livewire/blob/v1.0.1/composer.json#L14) supported Versions are only 6.x and beyond.

Since Laravel 6.x only supports `PHP >= 7.2.0` and 7.1 is also [EOL](https://www.php.net/supported-versions.php) we should move forward.

We therefore can tidyup our [github actions](https://github.com/livewire/livewire/blob/v1.0.1/.github/workflows/test.yml#L21) aside from obvious all the typehinting that comes with 7.2 and above.

I can open a PR for this.

**Comment by lancepioch** [comment]
One of the big selling points of Livewire is that you should be able to drop it in to your new or existing project super quick and easy. And also just be able to use it for one or maybe a couple of components.

For now I don't think that the newest features from PHP 7.2/7.3/7.4 will benefit users more than the dropping of Laravel 5.6/5.7/5.8.

**Comment by nuernbergerA** [comment]
Well then we should consider rewrite some latest PRs like #651 which is not 7.1 compatible. Or at least consider dropping PHP 7.1 support.

**Comment by lancepioch** [comment]
Agreed that should be fixed with a simple test to run through it.

**Comment by calebporzio** [comment]
Yes, I want to keep supporting old Laravel for now. You're right about the latest PR

**Comment by lancepioch** [comment]
@calebporzio @nuernbergerA I looked into the PHP_OS_FAMILY and it works fine because `symfony/polyfill-php72` is included as a dependency (because of `symfony/var-dumper`).
