### ISSUE TITLE
livewire.dispatchTo  not working livewirev3

### ISSUE THREAD

**Issue by elizdlt202** [livewire/livewire#6695]
I am having the same issue as the person below...

-----------

Hi all,

I'm looking to replace the following on v2 with the requirements for v3.

```x-on:click="window.livewire.emitTo('record.details', 'showModal', '1')"```

I can see in the docs for V3: https://livewire.laravel.com/docs/javascript

```Livewire.dispatchTo('dashboard', 'post-created', { postId: 2 });```

This does not work for me at all.

```x-on:click="Livewire.dispatchTo('records.details', 'showModal', { record: 1})"```

I even tried using the window.Livewire.dispatchTo but I can't seem to get it working.

**The blade file listing records**

```
<dix x-data>
    <div>
        @foreach($records AS $record)
            <button 
                type="button" 
                x-on:click="Livewire.dispatchTo('records.details', 'openModal', {record: '{{ $record->id }}'})">
                    View details
            </button>
        @endforeach
    </div>
    <livewire:records.details />
</div>
```

The records.details Livewire component located at App/Livewire/Records/Details

```
namespace App\Livewire\Records;

use Illuminate\Contracts\View\View;
use Livewire\Component;

class Details extends Component
{
    public bool $showModal = false;
    public ?int $recordId;

    public function getListeners() : array
    {
        return ['openModal', 'closeModal'];
    }

    public function openModal($data) : void
    {
        $this->recordId = $data[0];

        $this->showModal = true;
    }

    public function closeModal() : void
    {
        $recordId = null;
        
        $this->showModal = false;
    }

    public function render() : View
    {
        return view('records.details');
    }
}
```

**The blade file for the details component** 

```
<div x-data="{ show: @entangle('showModal') }">
    <div x-show="show" x-cloak>
        <p>Modal is open</p>
        <button type="button" wire:click="closeModal">Close modal</button>
    </div>
</div>
```

V2 - everything works fine using livewire.emitTo, V3 - no dice. Any feedback on where I'm going wrong would be much appreciated. 

**Passing data to the component method being called**

Related to this is passing data to the method. In V2 using emitTo, we could pass a string, int, array etc. but it seems in v3, you always have to pass an  object? Example:

v2:

```
public function openModal(int $recordId) : void
{
    $this->recordId = $recordId;

    $this->showModal = true;
 }
```

v3:

```
public function openModal($data) : void
{
    // doing a dd on $data always give an array where the keys are removed.
    // I would expect recordId to be $data['record'],  but this does not exist, so I have to use $data[0]
    $this->recordId = $data[0];

    $this->showModal = true;
}
```

Is it possible to pass  a single property as string/int/float/bool to the method of a component we are dispatching to?

Thanks for your time!

_Originally posted by @spicygorilla in https://github.com/livewire/livewire/discussions/6222_

**Comment by lokutus24** [comment]
hello,

From javascript Livewire.dispatchTo is not working.
Backend get not the event.

**Comment by psjavi** [comment]
Hi try this, I don't know why the first param should be empty. I fixed the same issue calling the component in this way:

`window.Livewire.dispatchTo('', 'my-livewire.my-component', 'myFunction', [params1, params2]);`

In the component I've got 

```
namespace App\Livewire\MyLivewire;
class MyComponent extends Component
{
    protected $listeners = ['myFunction'];
    public function myFunction($params1, $params2): void
    {
    }
}
```
