### ISSUE TITLE
Allow class_namespace to sit outside of \App

### ISSUE THREAD

**Issue by code-distortion** [livewire/livewire#672]
Hi there. I originally wrote a solution to the problem outlined below, but before posting I found an alternative solution here https://github.com/livewire/livewire/issues/306 which lets me do what I was trying to do.  I thought I'd still post this in case the solution I proposed is useful to someone else.  I'm happy to discuss it further, create a PR, paste the code, and if it's not useful feel free to close.

**ORIGINAL POST...**

Currently the root namespace for Livewire component classes must sit within the \App namespace. It will be useful in some circumstances to allow them to sit elsewhere.

**Example:**

_Laravel Modules_ is a package ( https://nwidart.com/laravel-modules/v6/introduction ) that lets you segregate your Laravel code with different concerns into their own directory structures (Console, Http, Routes, Tests etc. effectively their own App directory). It creates a /Modules directory and puts each module inside that,  however this is outside of the \App namespace.

Changing the _livewire.class_namespace_ config setting to 'Modules' for this situation will break Livewire's conversion between path names and component class namespaces.

**Desired outcome:**

I would like for Livewire to allow its component classes to sit outside of the App directory.

**Thoughts:**

A drawback of this would be if a user happened to set _livewire.class_namespace_ to '' (an empty string),  the LivewireComponentsFinder->getClassNames() method would loop through the files in /node_modles and /vendor when looking for Livewire component classes (slow and unnecessary).

**Alternatives:**

Leaving Livewire's components classes grouped together within App, as can be done now would work but would not take advantage of what Laravel Modules is trying to achieve.

It might be possible to update Laravel Modules so it puts its modules within /App/Modules.  I haven't explored this option.

**Proposed changes:**

I have made updates to the following files to get this to work. The changes don't break any tests:

- **LivewireComponentsFinder->getClassNames()** and
- **ComponentParser::generatePathFromNamespace($namespace)**

I updated them to take composer.json's _autoload.psr-4_ values in to account (similar to what **Illuminate\Foundation\Application->getNamespace()** does).

ComponentParser doesn't take advantage of the manifest file (/bootstrap/cache/livewire-components.php) like LivewireComponentsFinder does which would save this step,  however they both previously called Illuminate\Foundation\Application->getNamespace() which would parse composer.json anyway. So this is no worse than before.

**Comment by austenc** [comment]
Also just ran into this -- to tack on a little bit more, it might be advantageous to allow the user to specify multiple locations and namespaces -- so it would sort of cascade?

For example, the first namespace would be `Something\Outside\Livewire` and if the class isn't found there it would default to `App\Http\Livewire`. Would be useful in the case where you want to extend upon a Livewire component which is in a composer package.

**Comment by clnt** [comment]
@calebporzio @lancepioch 

I feel like this is quite the deal breaker for me, and most likely for many others too. Upon hoping to use Livewire to add some more life to my admin panel it does not work as expected, because I don't have my application structured like a 'typical' Laravel application. The same also goes for people mentioning the use of it in packages.

You have configuration options for changing the namespace, and location of views (which I only want to change to a single location), which works great, it creates the classes in the correct location then I return the view using my view namespace (and it renders in the DOM fine), even attaching the `wire:id` as shown in the attached image.

I have defined this component manually in a service provider using the `Livewire::component()` method as auto-discovery didn't seem to pick it up correctly.

However, upon trying to do anything such as simply echoing out what I am typing into the input box using `wire:model` - it just generates this console error every time.

I've even tried moving the view back to the default location and keeping the class in its namespaced location but the same fault still occurs. 

As a test, I have taken this exact code and placed it into a default Laravel project with no namespacing and everything works perfectly, and it was as easy to implement as you made it look in your Laracon Online talk.

It just feels like something isn't right here, even when looking at the source you utilise the configuration options in places like autodiscovery, it feels like this is something that has been thought about and should work? but it doesn't :(

Other than this gripe that I have, this seems damn awesome. I just wish I could use it.

![Screenshot 2020-03-11 at 20 06 55](https://user-images.githubusercontent.com/19330442/76461052-10407680-63d7-11ea-98de-eaa9f9e04341.png)

**Comment by lancepioch** [comment]
I think it might be a good idea to support this.

In the meantime, this may be a good alternative solution as it's usually more ideal to have App as the primary namespace: https://laravelshift.com/laravel-consolidate-custom-namespaces

**Comment by clnt** [comment]
@lancepioch 

Thanks for the response, yeah I think it is really important for Livewire to support this if you want it to be used as much and as accessible by everyone.

I shouldn't be forced to use the `App\` namespace though, and my configuration values that I am setting should just be honoured.

Let me give you an example, the `App\` namespace does exist in my app but that's where I leave all the core Laravel install stuff such as the default service providers etc, then I will say make a folder called `app/MyProject` - It's that folder I would then define a namespace of `MyProject\` in my composer autoload. Then put my Livewire components say somewhere like `MyProject\Admin\Http\Livewire` and this entire namespace what I am providing to the package with the configuration file so why isn't it being honoured. Now maybe this isn't the typical setup (some people refactor App completely), which would still have the same issue. Using things like `app()->namespace()` still returns `App\` for me so I am not sure if its something like that causing issue. I'd love to be able to submit a PR for this but unsure on the internals of the package and limited on time at the moment (like I am sure we all are). So right now I've either got the option of changing the entire namespace of my application or just using Vue which I didn't want to do for such simple components.

It honestly just makes the configuration options seem almost pointless to me, if you're going to use the default application structure then you may as well just leave the Livewire components in their default location.

It's like the whole `app\Models` debate, yeah its preference, but it's a very popular preference so ideally it should be configurable for example.

I just feel like Livewire is halfway there, you've got the config values! It just needs to use them and forget about `App`

**Comment by t-prod** [comment]
Hi,

I try to move Livewire Component in a Module => Laravel Modules is a package ( https://nwidart.com/laravel-modules/v6/introduction ) as said above :

In the boot method of the Module ServiceProvider I try this :
`Livewire::component('analytics', \Modules\Report\Http\Livewire\Analytics::class);`

app/Http/Livewire is not found

Any ideas ?

**Comment by calebporzio** [comment]
Ok, this is much harder than you might think. Here's the core problem:

> There's no dependable way to generate a file path from a PHP namespace.

Why does this matter?

When a user types `artisan make:livewire foo`, we need to know the file path of the Livewire folder to create the new file into.

That's the hard part.

The auto-resolution is much easier.

Let's say you do something like `@livewire('foo')`, and your config namespace is set to: `MyApp\Livewire`

We can use the following strategy:
* Studly case the component name `foo` -> `Foo`
* Append that to the configured namespace `MyApp\Livewire\Foo`
* If the class exists, use it, if not, don't

This strategy breaks down when there is class to check against.

Consider that strategy against the "make:livewire" example: `artisan make:livewire foo`
* Studly case the component name `foo` -> `Foo`
* Prepend the namespace `MyApp\Livewire\Foo`
* Now what? There is no PHP function like: `create_class($className)`

So you are left with brittle strategies that make me uncomfortable like checking the app's `composer.json` file for `autoload.psr-4` keys to map to paths. Assuming the namespace is in the project root, and others.

@clnt, I hope I've revealed to you a little bit about why this is this way.

I will add that the overwhelming majority of Laravel apps use the `App\\` namespace convention.

There is always `Livewire::component('foo', MyApp\Livewire\Foo::class)` which should make this a non-deal-breaker for you.

I'm open to other approaches, and coming up with more reliable ways to derive a path from a class namespace OR a different approach to auto-discovery entirely.

All this to say: it's much harder than it looks at first glance.

Cheers.

Closing for now.

**Comment by code-distortion** [comment]
Hi @calebporzio.  Thanks,  your response was quite detailed and I can see now that there's more to consider for this change to be implemented.

It might ruin your flagpole but it may be worth mentioning that _class_namespace_ needs to be within _App_ in the config comment (it might pre-empt some confusion):

``` php
    /*
    |--------------------------------------------------------------------------
    | Class Namespace
    |--------------------------------------------------------------------------
    |
    | This value sets the root namespace for Livewire component classes in
    | your application. This value effects component auto-discovery and
    | any livewire file helper commands, like `artisan make:livewire`.
    |
    | After changing this item, run: `php artisan livewire:discover`
    |
    */

    'class_namespace' => 'App\\Http\\Livewire',
```

**Comment by calebporzio** [comment]
Yeah, that's a great point. Will add that

**Comment by kevyworks** [comment]
Changing the `class_namespace` => 'Something\\Else\\' still created inside a directory `app\Something\Else\...` the meta could be adjusted a bit, maybe:

```php
<?php return array (
  'hello-world' => ['Something\\Else\\HelloWorld', '/something/else/livewire/hello-world.blade.php']
);
```

The package is high level enough why not use Command to be interactive like asking what is the namespace, and the location where to put the view file. Or a parameter `--view` and `--namespace` so `$ artisan make:livewire hello-world --namespace "Something\\Else" --view ./something/else/livewire`
