### ISSUE TITLE
wire:loading stops alpine.js @click event

### ISSUE THREAD

**Issue by code-distortion** [livewire/livewire#673]
There seems to be an issue in the way Livewire and Alpine.js interact with each other. I'm not sure if this is related to Livewire, Alpine.js, or just something that I'm doing wrong.

**Bug Description:**

I have a Livewire component containing a form in a modal that appears when the user clicks a button. In the modal they're presented with a confirmation where they can cancel (close the modal) or continue.  Then when they continue, the Livewire action occurs and the user can then click a new button to finally close the modal.

Alpine.js is used to handle the @click events to open and close the modal.

Both "close" buttons work however if I include **\<span wire:loading>Loading\</span>** in there,  nothing happens when the second "close" button is clicked.

Pressing ESC which does the same thing still works however.

**Steps to Reproduce:**

I have stripped the html/css etc right back to try and show it as clearly as possible:

```
<?php
// routes/web.php

Route::get('/', function () {
    return view('index');
});
```

```
// resources/views/index.blade.php
<html>
<head>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
    @livewireStyles
</head>
<body>
    @livewire('do-something')
    @livewireScripts
</body>
</html>
```

```
<?php
// app/Http/Livewire/DoSomething.php
namespace App\Http\Livewire;

use Livewire\Component;

class DoSomething extends Component
{
    public function doThatThing()
    {
        // ...

        session()->flash('message', 'Whatever it was it has been done.');
    }

    public function render()
    {
        return view('livewire.do-something');
    }
}

```

```
// resources/views/livewire/do-something.blade.php
<div x-data="{ show: false }">

    <button @click="show = true" type="button">
        Do Something
    </button>

    <div x-show="show"
         @keydown.escape.window="show = false"
         style="width: 300px; margin-top: 10px; padding: 10px; border: 1px solid #aaa;"
    >

        <form wire:submit.prevent="doThatThing" action="#">
            @csrf

            {{-- success message --}}
            @if (session()->has('message'))
                <p>
                    {{ session('message') }}
                </p>

                <button @click="show = false" type="button">
                    Close
                </button>

            {{-- confirmation dialogue --}}
            @else
                <p>
                    This will do something. Are you sure you want to continue?
                </p>

                <div>
                    <button @click="show = false" type="button">
                        Cancel
                    </button>
                    <button type="submit">
                        Do that thing
                    </button>

                    <!-- ADDING OR REMOVING THIS AFFECTS: @click="show = false"-->
                    <!-- PRESSING esc STILL WORKS HOWEVER -->
                    <span wire:loading>Loading</span>
                </div>
            @endif

        </form>

    </div>
</div>
```

**Expected Behaviour:**

I would have expected the second close button to work regardless of whether the **wire:loading** element was present or not.

**Browsers Tested:**
- "Firefox 73.0.1" (Windows)
- "Chrome Version 80.0.3987.106 (Official Build) (64-bit)" (Windows)

**Comment by calebporzio** [comment]
Thank you for providing such a thorough issue.

I created my own local instance and it looks like everything works fine.

![image](https://user-images.githubusercontent.com/3670578/85443085-de56b880-b55e-11ea-8081-18bfa66df75e.png)


I believe this has been fixed.

Re-submit if I'm wrong.

Thanks!
