### ISSUE TITLE
Reactive nested component parent parameters.

### ISSUE THREAD

**Issue by kdion4891** [livewire/livewire#677]
As per the docs:

> Nested components CAN accept data parameters from their parents, HOWEVER they are not reactive like props from a Vue component.

Is the only way to accomplish this via listeners so you have a pseudo parent-child reactive property?

**Comment by calebporzio** [comment]
I imagine there is a way to make this sort of thing possible, but there would be lots of issues I can see off the bat.

For example:
- would we re-fire the mount method when data changes? (we can't refire mount after the component has already been mounted)
- we would need to somehow track incoming state so we know when it changes, we could do this with a hash or something but would need to store it somewhere, it would either add size to the payloads or we could store it in the backend cache or session but I'm trying to avoid both of those things where possible.

For now, I'm going to close this as it's a little too much ATM.

If anyone has any other clever ideas or thinks this really should exist, chime in here so we can gauge interest.

Thanks!

**Comment by philipboeken** [comment]
Hi @calebporzio, I've created a [PR](https://github.com/livewire/livewire/pull/2905) which (partly) implements reactive properties by firing events from a HydrationMiddleware. Any thoughts?
