### ISSUE TITLE
wire:navigate shows "NULL" when navigating back x times.

### ISSUE THREAD

**Issue by StoneyEagle** [livewire/livewire#6777]
### Discussed in https://github.com/livewire/livewire/discussions/6776

<div type='discussions-op-text'>

<sup>Originally posted by **StoneyEagle** September 12, 2023</sup>
### Livewire version

3.0.2

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

1. Add 2 pages, one empty, one dashboard view with a basic tailwind page skeleton moved to the layout.
1. Use wire:navigate(.hover) in your links.
1. Add x amount of DOM nodes and, the more you add the quicker the result.
1. Navigate a bunch of times between the pages, and go back in history with the back button or with `history.back()`.

### Additional information

When navigating back in history there is a point where Livewire renders `NULL` in the page for every page further back.

The amount of times you can go back is relative to the amount of DOM nodes spawned in the document by your components and layout.

I can navigate back 29 times before seeing the NULL.
When I add 30000 `<div class="bg-auto-100 "></div>` nodes, I can only go back once before it shows the NULL the next time I go back. (extreme example to test my theory)

Adding the following does not indicate anything that may be wrong. 
```js 
document.addEventListener('livewire:initialized', function() {
    window.addEventListener('popstate', function(event) {
        console.log(Alpine.history);
        console.log('history state change', event);
    });
});
```

When I do NOT use wire:navigate the navigate back works as expected.

P.S. My friend who also uses the latest version of Livewire has the same issue and was the one pointing this out to me.
Please let me know if there is anything unclear or need me to help.

Example: 
![image](https://github.com/livewire/livewire/assets/45034970/ef9468af-4e97-4899-8a00-57094cc298b9)
![image](https://github.com/livewire/livewire/assets/45034970/066400f2-f34d-4b4b-9201-48f7488f38e6)
![image](https://github.com/livewire/livewire/assets/45034970/6451016e-ea6e-432e-a511-f1899b14be5b)

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
