### ISSUE TITLE
Throw an exception if there are more than one root element in component

### ISSUE THREAD

**Issue by michaellatham** [livewire/livewire#678]
It seems at the moment that if you have more than one root element in a component, the behaviour is such that the first element becomes reactive to livewire, but subsequent elements do not, although they are rendered on the page. This may cause issues trying to figure out why it's not working. In my case, I started with one root element as per the docs, but subsequently added another.

**Describe the solution you'd like**
Throw an exception if livewire detects more than one root element in the component. So that it's obvious to the developer why you're not getting expected behaviour.

**Describe alternatives you've considered**
Leaving it as it is, as it's documented that you should only have one root element. Having additional elements in a component not reactive in livewire might be desired behaviour.

**Additional context**
The way I can think of doing this is within the output method in the component class (php), using something like DOMDocument and counting the nodes. I don't know if this is a good idea or not. Any input welcome!

**Comment by calebporzio** [comment]
Yeah, it WOULD be nice if this was behavior by default, however, I wonder if it would incur a performance cost for every request.

I suppose if you did the work by somehow hooking into the blade compilation step, it would only incur a const at compile time which would be fine.

Would love for someone to take a crack at this.

**Comment by calebporzio** [comment]
I've decided to close this.

This would require extra parsing and would add load time and probably spawn other bugs.

Thanks!
