### ISSUE TITLE
Adding lazy nested components breaks functionality

### ISSUE THREAD

**Issue by andrew1601** [livewire/livewire#6836]
### Discussed in https://github.com/livewire/livewire/discussions/6835

<div type='discussions-op-text'>

<sup>Originally posted by **andrew1601** September 16, 2023</sup>
### Livewire version

3.0.4

### Which PHP version are you using?

PHP 8.2

### Repository URL

https://github.com/andrew1601/livewire-lazy-bug

### Steps To Reproduce

1. Create a new Laravel project
2. Install livewire
3. Create counter component
4. Create message component that sleeps for a while in `mount()` and provides a placeholder.
5. Nest the message component inside the counter component.
6. Functionality of counter component breaks

### Additional information

I don't know whether this is a bug or not, but if it's not, I can't figure out what I'm doing wrong.

Console output:

<img width="1500" alt="image" src="https://github.com/livewire/livewire/assets/6561258/a0538bbb-e6be-45f6-9a2c-320a212a8a0c">

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
