### ISSUE TITLE
Translation of computed property attributes to property methods should behave like Eloquent custom accessors

### ISSUE THREAD

**Issue by ninthspace** [livewire/livewire#684]
Currently, the conversion from a computed property accessor such as `$this->foo` only performs a `ucfirst` on the property name. See:

https://github.com/livewire/livewire/blob/639ee48304760903b832db852592becf0fa805d6/src/Component.php#L169

This means `$this->my_foo` translates to `getMy_fooProperty`, rather than the more expected `getMyFooProperty`, which is similar to how Eloquent would translate it if it was a custom accessor (as `getMyFooAttribute`)

**Comment by calebporzio** [comment]
Agreed, should be a simple enough PR. Feel capable? Thanks!

**Comment by ManojKiranA** [comment]
@calebporzio  Just a Simple question are you going to make a breaking change on this by removing existing behaviour or we need to support for Both 

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L453

**Comment by calebporzio** [comment]
This will be addressed in the next major version. It would be a breaking change to fix right now (which sounds odd I know, but it really would break a lot of people's apps and I don't want to do that in this version.)
