### ISSUE TITLE
Loading state targeting without parameters

### ISSUE THREAD

**Issue by tlaverdure** [livewire/livewire#685]
**Describe the bug**
Cannot target a specific action without providing it's parameters. This wouldn't be an issue if parameters were always static.

**To Reproduce**
```html
<script>
const doFoo = () => {
    document.getElementById('foo').dispatchEvent(
        new CustomEvent('foo', { detail: { foo: 'bar' }})
    );
};
</script>

<button onclick="doFoo">Click Foo</button>

<input id="foo" wire:foo="myAction($event.detail.foo)" >

<div wire:loading wire:target="myAction">
    Loading...
</div>
```

**Expected behavior**
I'd expect `wire-target="myAction"` to capture all `myAction` calls without having to provide the parameters.

**Comment by calebporzio** [comment]
Yeah, you're right, this should be the default behavior of Livewire.

Ideally, `wire:target="myAction" would scope to ANY params`, and `wire:target="myAction('param')"` would scope to that action with ONLY those params.

Do you feel capable of starting a PR for this? I would love it if this was a community contribution.

Thanks!

**Comment by tlaverdure** [comment]
I actually tried testing out again today and it seems to be working as I described. 😅

There is however a different thing that I'm noticing that I'm noticing that is related to loops. Basically, I'm trying to upload an image in a loop:

```
wire:image-upload="uploadImage({{ $item['id'] }}, $event.detail)"
```

Where `$event.detail` returns a base64encoded image from a `CusotmEvent`. The issue now is that the just using ` wire:target="uploadImage` shows a loading indicator for each item in the loop. Don't see a clear way to get around this yet since the target is based on the either action name or action name + params, which could be dynamic. I'll see if I can think of something...

**Comment by calebporzio** [comment]
This bug has been fixed and now Livewire is flexible enough to set loading on an action with any parameters.

However, there is the new problem you are describing for actions in a loop with different params, where you want to scope a loading indicator to specific params.

This will be addressed in the next major version.

Thank you.
