### ISSUE TITLE
Event Listener not working

### ISSUE THREAD

**Issue by rmitesh** [livewire/livewire#6859]
### Discussed in https://github.com/livewire/livewire/discussions/6730

<div type='discussions-op-text'>

<sup>Originally posted by **rmitesh** September  8, 2023</sup>
In Livewire 3 I have 2 components `ScreenA` and `ScreenB`.

I am sending `ScreenA`'s `Post` data to `ScreenB`

```php
class ScreenA extends Component
{
    public function send(): void
    {
        $post = Post::first();
        $this->dispatch('post-created', title: $post->title)->to(ScreenB::class);
    }
}
```

ScreenA View file

```html
<button wire:click="send">Send</button>
```

Screen B
```php
class ScreenB extends Component
{
    public function render()
    {
        return view('livewire.screen-b');
    }
    
    #[On('post-created')]
    public function listenAEvents($post): void
    {
        $this->data[] = $post;
    }
}

```
and in the screen-b view file I am displaying that data

```php
<ol>
    @foreach( $data as $value )
        <li>{{ $value }}</li>
    @endforeach
</ol>
```

anyone help me what wrong in the code?</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
