### ISSUE TITLE
Mount lifecycle is called twice and listener 4 times

### ISSUE THREAD

**Issue by OlrikNijmeijer** [livewire/livewire#6865]
### Discussed in https://github.com/livewire/livewire/discussions/6863

<div type='discussions-op-text'>

<sup>Originally posted by **OlrikNijmeijer** September 19, 2023</sup>
### Livewire version

3.0.5

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

I upgraded a project from livewire v2 to livewire v3.
After this i noticed that the mount function of a component is called twice.

Also when I create a link that dispatched an event, the listener is called 4 times.
This also happens when i create a new page with an empty layout.

**Component**
```
namespace App\Livewire\Pages\Portal;

use Livewire\Component;

class TestPage extends Component
{
	protected $listeners = ['doSomething'];

	public function mount()
	{
		dump('mount called');
	}

	public function render()
	{
		return view('livewire.pages.portal.test-page');
	}

	public function dispatchSomething()
	{
		$this->dispatch('doSomething');
	}

	public function doSomething(): void
	{
		dump('doSomething called');
	}
}
```

**Blade**
```
<div>
    <x-button wire:click="dispatchSomething" label="test button"/>
</div>
```

**Layout**
```
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="light">
<body>
{{$slot}}
</body>
</html>
```

This results in the following views:

**Dump in mount**

![Scherm­afbeelding 2023-09-19 om 14 48 02](https://github.com/livewire/livewire/assets/17452023/0591499c-1a21-444e-83cb-2f97bf4470df)

**Dump in listener**

![Scherm­afbeelding 2023-09-19 om 14 48 07](https://github.com/livewire/livewire/assets/17452023/f01ad10a-0d29-46d6-b4f2-6e753e9eb543)

I created a new Laravel project to try to reproduce this, but in the new project this problem does not appear.

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
