### ISSUE TITLE
Unable to retrieve minified file of livewire.js

### ISSUE THREAD

**Issue by wize-wiz** [livewire/livewire#6871]
### Discussed in https://github.com/livewire/livewire/discussions/6838

<div type='discussions-op-text'>

<sup>Originally posted by **wize-wiz** September 16, 2023</sup>
I've wondered why `livewire.js` is not minified when changing the environment to **production**. 

I figured that while `Livewire\Mechanisms\FrontendAssets\FrontendAssets::returnJavaScriptAsFile()` has [this](https://github.com/livewire/livewire/blob/c6779a499bbc786b18c043ec633fd98927d740be/src/Mechanisms/FrontendAssets/FrontendAssets.php#L71) line `return Utils::pretendResponseIsFile(__DIR__.'/../../../dist/livewire.js');` hardcoded, it can **never** return a minified file.

Is the [route callback](https://github.com/livewire/livewire/blob/c6779a499bbc786b18c043ec633fd98927d740be/src/Mechanisms/FrontendAssets/FrontendAssets.php#L47C14-L47C28) overwritten in a place somewhere else I haven't found yet? I can find no mention of `min.js` or `FrontendAssets::javaScriptRoute` being set anywhere else.

In the `livewire/dist` folder, there is a minified version available, of course :) 

 
</div>

I just figured `livewire/livewire.js` will never return a `dist/livewire.min.js` version in production mode, if it is hardcoded to always return `dist/livewire.js`. Is there any reason unknown to me which would explain its current behaviour?

Would the following be simple enough to tackle this simple problem:

```
    public function returnJavaScriptAsFile()
    {
        $ending = app()->isProduction() ? 'min.js' : 'js';
        
        return Utils::pretendResponseIsFile(__DIR__.'/../../../dist/livewire.' . $ending);
    }
```

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
