### ISSUE TITLE
Dynamic Set of Listeners for Laravel Echo

### ISSUE THREAD

**Issue by kornatzky** [livewire/livewire#692]
In Laravel Echo, one can dynamically define the set of channels, like:

`window.Echo.channel('user.’ + userId)
    .listen(‘SomeEvent’, (e) => {
        console.log(e);
        showResult(“waiting”);
    });`

How can on do it with Laravel Livewire?

**Comment by ninthspace** [comment]
Given that listeners can be dynamically created with `getListeners`, I would do something like this:

```php
class SomeComponent extends Component
{
    public $userId;

    protected function getListeners()
    {
        return ["echo:user.{$this->userId},someEvent" => 'someAction'];
    }
}
```
