### ISSUE TITLE
Livewire.dispatchTo not working

### ISSUE THREAD

**Issue by jamesRUS52** [livewire/livewire#6924]
### Discussed in https://github.com/livewire/livewire/discussions/6923

<div type='discussions-op-text'>

<sup>Originally posted by **jamesRUS52** September 25, 2023</sup>
### Livewire version

3.0.5

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

Emit event from pure JS

Livewire.dispatchTo('component-livewire', 'toggle')

### Additional information

it is look like a bug that method required first argument that not used in method code 

not working 
Livewire.dispatchTo('requests.requests.livewire.limits-livewire', 'requests.requests.livewire.limits-livewire', 'toggle')

but working with any fake arg in first argument

Livewire.dispatchTo('fake', 'requests.requests.livewire.limits-livewire', 'requests.requests.livewire.limits-livewire', 'toggle')

If I correct found the code the first arg not used

function dispatchTo(component, componentName, name, params) {
  let targets = componentsByName(componentName);
  targets.forEach((target) => {
    dispatchEvent(target.el, name, params, false);
  });
}

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by ojsoft** [comment]
I fell over this one also. Fixed it in calling the function as follows. But yes, either this is a bug in code or in the documentation.

`Livewire.dispatchTo('App\Livewire\ComponentLivewire', 'component-livewire', 'toggle')`

**Comment by PhiloNL** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
