### ISSUE TITLE
Querystring not URL encoded

### ISSUE THREAD

**Issue by lhilton** [livewire/livewire#694]
**Describe the bug**
Creating a basic live-search form, similar to the documentation example [from the docs](https://laravel-livewire.com/docs/properties/#update-query-string)

The text the user typed is not URL encoded values. For example, the space shows up as an actual space and not a `+` or a `%20`.

**To Reproduce**
1. Go to [docs](https://laravel-livewire.com/docs/properties/#update-query-string)
2. Implement the example code shown
3. Input a search parameter that includes a space.
4. See space be in querystring

**Expected behavior**
The querystring to be urlencoded

**Additional context**
I'm not sure if this is a bug or an as-designed feature. If it is as simple as "woops, we should probably do that", then I can implement the decode/encode logic in a PR. If it's more complicated, such as a desire to make it configurable, how should this be designed?

**Comment by lancepioch** [comment]
This is working for me on the latest version.

![694](https://user-images.githubusercontent.com/1296882/76267145-2a941c00-6240-11ea-8701-d735dc8ca994.gif)

**Comment by nuernbergerA** [comment]
It could be browser specific or even a server setting.
@lhilton What browser and livewire version are you using? How do you run your Laravel code?

**Comment by DanHarrin** [comment]
Hi, doesn't look like anyone else is facing this issue, so I'm going to close this due to lack of activity. If you can provide more information, such as a minimal, replicable code example to demonstrate your issue, then please open a new [Discussion](https://github.com/livewire/livewire/discussions). Thank you!
