### ISSUE TITLE
Docs: "see this guide (replace me!!!)" into "properties page"

### ISSUE THREAD

**Issue by IlCallo** [livewire/livewire#699]
**Describe the bug**
"see this guide (replace me!!!)" line (with no link to any guide) marks probably something missing.

**To Reproduce**
1. Go to https://laravel-livewire.com/docs/properties

**Expected behavior**
A guide link

**Screenshots**
![image](https://user-images.githubusercontent.com/10036108/76405075-e3b13e00-6387-11ea-876c-80c58fb1db91.png)

**Desktop (please complete the following information):**
 - Browser: all

**Comment by calebporzio** [comment]
This has been fixed, thanks. In the future please submit Documentation related issues to /livewire/docs repo. Thanks!
