### ISSUE TITLE
Docs: missing "$this->reset" example

### ISSUE THREAD

**Issue by IlCallo** [livewire/livewire#700]
**Describe the bug**
"$this->reset" example code is missing

**To Reproduce**
1. Go to https://laravel-livewire.com/docs/properties

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: all

**Comment by lancepioch** [comment]
Would you be open to creating a PR and adding one? https://github.com/livewire/docs/blob/master/resources/views/docs/properties.blade.php

**Comment by IlCallo** [comment]
I actually don't know how it works, that's why I notified the missing example :laughing: 
I was just lurking around the docs, didn't have time to finish them tho

Can you point me to the file in the codebase managing this feature?

**Comment by lancepioch** [comment]
Docs: https://github.com/livewire/docs/blob/295708697c03c40e7f690fff083a45c9721b283a/resources/views/docs/properties.blade.php#L91-L110

Test: https://github.com/livewire/livewire/blob/26b36828c8e994a7748f5afe06a85f4d5278fec4/tests/ResetPropertiesTest.php

Function: https://github.com/livewire/livewire/blob/26b36828c8e994a7748f5afe06a85f4d5278fec4/src/ComponentConcerns/InteractsWithProperties.php#L105-L118

**Comment by calebporzio** [comment]
Closing for now, welcome a PR to the /docs repo though. Thanks!
