### ISSUE TITLE
Custome route for update not working not working with latest livewire3

### ISSUE THREAD

**Issue by aliworld1010** [livewire/livewire#7040]
### Discussed in https://github.com/livewire/livewire/discussions/7039

<div type='discussions-op-text'>

<sup>Originally posted by **aliworld1010** October 10, 2023</sup>
### Livewire version

3.0

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

i am using livewire 3 + laravel project with th foldername testproj in "C:\xampp\htdocs"  

Project Path 
C:\xampp\htdocs\testproj 

I set my custom livewire path as per Installation livewire documentation :

Livewire::setScriptRoute(function ($handle) {
    return Route::get('/testproj/vendor/livewire/livewire/dist/livewire.js', $handle);
});

&

Livewire::setUpdateRoute(function ($handle) {
    return Route::post('/testproj/vendor/livewire/livewire/dist/update', $handle);
});

Results with php artisan serve ======works everything fine

Results with xampp =   http://localhost/testproj /public/user/profile
POST http://localhost/testproj /vendor/livewire/livewire/dist/update 404 (Not Found)  

so the update not working but the livewire,js is working ... but without update livewire is useless.

In simple words if i say .. someone install jetstream with livewire fresh project and try to publish in sub folder of xampp it will not work , even after setting custom route path

I need this project to be on subfolder of my root webfolder .. i can not publish at root folder as there are some other project is published there ... please help me i am strudgling to solve this for last 3 days and it is making me really think to use livewire or not... u guys have done amazing job i am sure u can help fixing this too

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
