### ISSUE TITLE
Bug with sorting

### ISSUE THREAD

**Issue by ElGittoJunior** [livewire/livewire#7041]
### Discussed in https://github.com/livewire/livewire/discussions/7038

<div type='discussions-op-text'>

<sup>Originally posted by **ElGittoJunior** October 10, 2023</sup>
### Livewire version

3.0.6 and 3.0.7

### Which PHP version are you using?

PHP 8.2

### Repository URL

https://github.com/ElGittoJunior/chirper-livewire-tutorial.git

### Steps To Reproduce

- I followed the official bootcamp.laravel.com tutorial for Livewire
- When I added editing functionality (https://bootcamp.laravel.com/livewire/editing-chirps), after clicking edit on a chirp in the dropdown menu the textbox appears, but the whole chirps list is sorted in reverse order. 
- If I save the chirp correct order is back, but when I press cancel its stays in the reverse order.

I noticed that its is working if i fix Livewire to 3.0.5, it also worked with 3.0.0 so I assume its working for versions 3.0.0-3.0.5

"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "3.0.5",
        "livewire/volt": "^1.0"
    },

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
