### ISSUE TITLE
Accessing properties before initialization (PHP 7.4)

### ISSUE THREAD

**Issue by gjm** [livewire/livewire#707]
**Describe the bug**

Having uninitialized typed properties in components triggers `ErrorException` saying **typed property must not be accessed before initialization**.

**To Reproduce**

* Create a component with an uninitialized typed property:

```php
class Foo extends Livewire\Component
{
    public string $bar;
    
    public function mount(string $bar)
    {
        $this->bar = $bar;
    }

    public function render()
    {
        return view('components.foo');
    }
}
```

* Use it in a view
```html
<x-foo bar="baz" />
```

**Expected behavior**
Component should be rendered successfully but an `ErrorException` is thrown:

`Typed property Foo::$bar must not be accessed before initialization`

**Aditional information**

When the component is constructed it calls the `ensureIdPropertyIsntOverridden` method which, in turn, calls the `getPublicPropertiesDefinedBySubClass` method in the `InteractsWithProperties` trait. This method tries to access the property and that triggers the error.

**Comment by basepack** [comment]
Can confirm this using the old `@livewire('foo', ['bar'=> 'baz']` syntax too.

**Comment by tanthammar** [comment]
confirmed, this gives an error
```php
public string $title;
public function mount()
{
        $this->title = trans('crud.account.title');
}
```
setting a default value removes the error
```php
public string $title = '';
public function mount()
{
        $this->title = trans('crud.account.title');
}
```

**Comment by yob-yob** [comment]
I don't know if e89b6a1 fixed this issue for **Binding Directly To Model Properties**
since I'm still getting an error on  `ComponentConcerns/HandlesActions.php:24`

this is how I implemented it

```
public Course $course;

    protected $rules = [
        'course.category' => 'required',
        'course.expiration' => 'required',
        'course.instructor' => 'required',
        'course.title' => 'required',
        'course.excerpt' => 'required',
        'course.description' => 'required',
        'course.price' => 'required',
    ];
```
How I used it
```
<x-slot name="form">
    <x-inputs.select-menu wire:model.defer="course.category"  />
    <x-inputs.select-menu wire:model.defer="course.expiration"/>
    <x-inputs.select-menu wire:model.defer="course.instructor"/>
    <x-inputs.textbox wire:model.defer="course.title" />
    <x-inputs.textarea wire:model.defer="course.excerpt" />
    <x-inputs.textarea wire:model.defer="course.description" />
    <x-inputs.textbox wire:model.defer="course.price" />
</x-slot>
```

**Comment by kurucu** [comment]
Reopen

**Comment by basepack** [comment]
@yob-yob if you not pass `course` as a parameter I think you still have to do initialization it in the `mount()` method:

```
public function mount()
{
    $this->course = new Course();
}

// this is not necessary anymore:

public function mount(Course $course)
{
    $this->course = course;
}
```

**Comment by mokhosh** [comment]
You seem to still get this error if you do `$this->reset()` which is even worse than getting it when you access before initialising it.

**Comment by NiekNijland** [comment]
I get this error when accessing $customerService in the following code example:

`
class Details extends Component
{
    /**
     * @var CustomerService
     */
    private CustomerService $customerService;

    public function mount(CustomerService $customerService)
    {
        $this->customerService = $customerService;
    }
}
`

**Comment by mokhosh** [comment]
@NiekNijland 1) why are you setting it to private, you know that won't retain state, right? 2) you don't need to assign if that's all you do in mount.

**Comment by NiekNijland** [comment]
@mokhosh 

1. I'm setting it to private because otherwise i'll run into this error:
 ```Livewire component's [superadmin.customers.edit.details] public property [customerService] must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.`

Setting it to protected doesn't change anything.

2. This code example is simplified, I use the functionality of $customerService in other functions in the livewire component that I have removed. This is the function that throws the error when its called:

```    public function toggleApiAccess()
    {
        $this->customer['api_access'] ^= 1;

        if($this->customer['api_access'])
            $this->customer['api_key'] = $this->customerService->generateApiKey();
    }`

I'm new to livewire so I might just be overlooking something stupid.

**Comment by mokhosh** [comment]
I assume `CustomerService` is an `Eloquent` model class?
And which version of Livewire are you using?

**Comment by NiekNijland** [comment]
@mokhosh 

CustomerService is a normal PHP class (service pattern) registered in a ServiceProvider. I want to inject this class with the typehinted parameter. This is working fine in my controllers. I watched the webinar on livewire at laracon last week and I thought it was mentioned there that the same can be done in a livewire component.

**Comment by mokhosh** [comment]
Ok then just inject it in the methods that you need it.
Because it won't persist between requests if you try to inject it in mount which happens only once and keep it in a private property.
