### ISSUE TITLE
Call to undefined method CompilerEngine::startLivewireRendering()

### ISSUE THREAD

**Issue by SUKOHI** [livewire/livewire#711]
I got an error like this when displaying a livewire component in Laravel 7.0.8.

```
Facade\Ignition\Exceptions\ViewException
Call to undefined method Facade\Ignition\Views\Engines\CompilerEngine::startLivewireRendering() (View: /path/to/my/laravel7x/resources/views/livewire.blade.php)
```

 I guess the order of loading classes is the problem because `IgnitionServiceProvider` is loaded after `LivewireServiceProvider` in my environment.

Is there a way to fix it?
Thank you!

**Comment by calebporzio** [comment]
It's very possibly a fixable bug.

In order to fix it though, we will need to be able to reproduce it. Unfortunately, there is not enough info in this issue to recreate the issue and better understand the problem.

It would be ideal if you could recreate the exact issue in a brand new Laravel install and post a link to it.

Re-open if you do that.

**Comment by ahallhognason** [comment]
I can confirm that I had the same issue installing an app. 
I was able to solve it by going to bootstrap/cache/packages.php and moving the 'facade/ignition' definition above the 'livewire/livewire' definition. 

Like so:
```php
  'facade/ignition' => 
  array (
    'providers' => 
    array (
      0 => 'Facade\\Ignition\\IgnitionServiceProvider',
    ),
    'aliases' => 
    array (
      'Flare' => 'Facade\\Ignition\\Facades\\Flare',
    ),
  ),
  'livewire/livewire' => 
  array (
    'providers' => 
    array (
      0 => 'Livewire\\LivewireServiceProvider',
    ),
    'aliases' => 
    array (
      'Livewire' => 'Livewire\\Livewire',
    ),
  ),
```

I don't know if this is exactly a problem for livewire to solve. I think it is likely a result of 'facade/ignition' being a dev dependency (and therefore being installed later) whereas 'livewire/livewire' is a full normal dependency.

**Comment by SUKOHI** [comment]
Thank you, ahallhognason!
I could solve my problem as you mentioned.

**Comment by ahallhognason** [comment]
I forgot to mention, I found a more permenant solution than adjusting your cache manually every time you composer update.

In your composer.json file, add "livewire/livewire" to the "dont-discover" array under extra.laravel, like so:
```php
    "extra": {
        "laravel": {
            "dont-discover": [
                "livewire/livewire"
            ]
        }
    },
```

Then, in your app config (config/app.php), add Livewire\LivewireServiceProvider.php to your providers array, like so:
```php
'providers' => [
        //...
        /*
         * Package Service Providers...
         */
        Livewire\LivewireServiceProvider::class,
        //...
]
```

**Comment by SUKOHI** [comment]
Thank you again, ahallhognason!

Oh, that's the answer.
I really appreciate you. :)

**Comment by EricBusch** [comment]
I had the same problem and @ahallhognason's answer fixed it.

**Comment by jltxwesley** [comment]
Had the same issue, in my case I don't use auto-discovery, so in order to get it working, I need to put them in below specific order:

```php
'providers' => [
    ...
    Facade\Ignition\IgnitionServiceProvider::class    
    Livewire\LivewireServiceProvider::class,
    ...
]
```

Didn't dig into it, but it's odd that the order matters.

**Comment by alessandrobelli** [comment]
Now I have this problem with Laravel Jetstream
Call to undefined method Facade\Ignition\Views\Engines\CompilerEngine::startLivewireRendering()

**Comment by alessandrobelli** [comment]
I have this problem as well.
I solved with a similar solution to @ahallhognason in  `bootstrap/cache/packages.php` by putting my package as the last one in the array. (I am using Livewire in my package as well).

**Comment by calebporzio** [comment]
Ok, I think we should pull request an additional check to Ignition:

https://github.com/facade/ignition/blob/7b34c40e1070e217e061cadcb651fd0c095663e0/src/IgnitionServiceProvider.php#L381

This way Livewire's blade compiler will be considered a "custom compiler" and not be overwritten by ignition.

Pinging @austenc

**Comment by austenc** [comment]
That was a promising lead, but unfortunately, it's not simple. 

Making the change to Ignition does seem to fix the issue, but it breaks Ignition's tests (and functionality?). Looks like specifying a Blade compiler is limited to one instance (whichever one comes last). Here's the code which causes the above behavior:
https://github.com/facade/ignition/commit/7af652bd4f50fc1290a0e8fdc8e2bb868abf4915

The tricky part is that the service container only wants one instance of a binding. It may be that Ignition or Livewire could use [Contextual Binding](https://laravel.com/docs/8.x/container#contextual-binding) to solve this problem.

**Comment by mitchjam** [comment]
@austenc Did you submit that commit as a PR to Ignition? If not, will you? If not, can I?

**Comment by austenc** [comment]
@mitchjam I did not. Unforunately the "fix" in my branch ends up breaking Ignition's functionality. Feel free to give it a shot!

**Comment by mitchjam** [comment]
@austenc Aww, shucks. We should pair on it one of these days.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
