### ISSUE TITLE
`livewire:init` does not work

### ISSUE THREAD

**Issue by amshehzad** [livewire/livewire#7120]
### Discussed in https://github.com/livewire/livewire/discussions/7091

<div type='discussions-op-text'>

<sup>Originally posted by **amshehzad** October 18, 2023</sup>
### Livewire version

v3.0.5

### Which PHP version are you using?

PHP 8.2

### Additional information

I tried to dispatch and event in `livewire:init` but the event didn't dispatched. I tried using `livewire:initialized` and it worked.

here is what I'm trying:

```
document.addEventListener('livewire:init', function () {
        Livewire.dispatch('modal.open', { component: 'modals.select-vehicle' })
```

the same worked with `livewire:initialized`

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
