### ISSUE TITLE
Page DOWN

### ISSUE THREAD

**Issue by rmunate** [livewire/livewire#7126]
### Discussed in https://github.com/livewire/livewire/discussions/7125

<div type='discussions-op-text'>

<sup>Originally posted by **rmunate** October 21, 2023</sup>
### Livewire version

3

### Which PHP version are you using?

PHP 8.2

### Repository URL

https://laravel-livewire.com/

### Steps To Reproduce

![Captura de pantalla 2023-10-21 a la(s) 7 54 04 a m](https://github.com/livewire/livewire/assets/91748598/9c8ced6c-dcde-41c4-828b-01a61211d037)

### Additional information

https://laravel-livewire.com/
500
SERVER ERROR

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by vladrusu** [comment]
That is the page for Livewire 2. Indeed, ATM is down.

This one is for version 3, which works:
https://livewire.laravel.com

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
