### ISSUE TITLE
Question: split tags / multiple tags for single component

### ISSUE THREAD

**Issue by joveice** [livewire/livewire#713]
I'm not sure how I can explain it but what I'm asking is if there is a better way to have elements that are split a bit from each other on the page.
I have a user search page, it has the input on top and the rows a bit lower down on the page.
Should I add the stuff between into the livewire component, or is there a way to split the input field and the foreach stuff using multiple tags, or some other magic stuff I have not found in the documentation?
(This is my first time using this package)

**Comment by calebporzio** [comment]
Hey @joveice, right now there is no way to reference different areas of the DOM from a single component.

You either need to wrap everything in a component, or keep them as separate components and use events to talk to each other.

**Comment by joveice** [comment]
Did not know that the events was for that, it will probably work perfectly for this :smile:
