### ISSUE TITLE
Custom input readonly after validation error

### ISSUE THREAD

**Issue by azurinspire** [livewire/livewire#716]
**Describe the bug**
Custom input component is left to readonly state after form submission if there is validation errors.

**To Reproduce**
1. Go to https://github.com/azurinspire/livewire-tel-input
2. clone, `composer install && php artisan serve`
3. Open in browser, click the green button and phone input is readonly

**Expected behavior**
Custom input is not readonly

**Desktop (please complete the following information):**
 - OSX + Firefox 73

**Additional context**
What I think happens: when custom component uses `wire:ignore` attribute, it is still set as `readonly` when form is submitting by this code: https://github.com/livewire/livewire/blob/73bd75b830005d0f412c7347cca6ff1b95229746/js/component/DisableForms.js#L31
But cleaning readonly attribute doesn't happen because the dom inside wire:ignore is not updated.

**Comment by codeduction** [comment]
I also ran into this issue today, What is the best approach to resolve this?

tell the js to ignore any inputs that are wire:ignore'd ?

**Comment by rodrigore** [comment]
Im also facing this issue using mapbox library. I try to use the geocoder plugin which contains an input which generated some custom dom.

In order to fix this problem I have to remove manually the readonly and other undesirable attributes with the afterDomUpdate hook.

I put this inside an script tag:

``` html
<div wire:ignore id="geocoder" class="geocoder"></div>
```


``` javascript
document.addEventListener("livewire:load", function(event) {
    window.livewire.hook('afterDomUpdate',  () => {
        document.getElementsByClassName('mapboxgl-ctrl-geocoder--input')[0].removeAttribute('readonly');
        document.getElementsByClassName('mapboxgl-ctrl-geocoder--button')[0].removeAttribute('disabled');
    });
});


```

I hope that this trick can help people like  @azurinspire @codeduction  and others.

**Comment by calebporzio** [comment]
Thanks! This issue will be fixed in the next release!
