### ISSUE TITLE
[Suggestion] Mobile Application

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#721]
Livewire make me suprise to building SPA and web component.
In laravel framework we miss one package and that is web to mobile ( apk file ).
If we make app with livewire which can compile to apk or ios pack all users use livewire.

Please think about it.
One code base for every thing, it is not important that we use cordova or phonegap just mobile ready after web.

**Comment by calebporzio** [comment]
I would love for there to be mobile offerings from Livewire. No plans at the moment though. Thanks.
