### ISSUE TITLE
[BUG] Invalid argument supplied for foreach() if using pagination

### ISSUE THREAD

**Issue by iqmal852** [livewire/livewire#722]
**Describe the bug**
Invalid argument error when we loop object from eloquent pagination.

**To Reproduce**

`App\Http\Livewire\HelloWorld`

```
class HelloWorld extends Component
{
    use WithPagination;

    public $companies;

    public function mount()
    {
        $this->companies = Company::paginate(25);
    }

    public function render()
    {
        return view('livewire.hello-world', [
            'companies' => Company::paginate(25)
        ]);
    }
}
```

In View File
`livewire/hello-world.blade.php`
```
<div>
    @foreach($companies as $company)
    @endforeach
</div>
```

**Expected behavior**
The foreach loop should working fine as documented in https://laravel-livewire.com/docs/pagination/

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
Laravel Framework version : 7.0
Livewire version : 1.0

**Comment by azurinspire** [comment]
Remove the `public $companies;` and it will work. If you pass collection in render as second parameter to the view, the same name should not be used as public property.

**Comment by nonso07** [comment]
> Remove the `public $companies;` and it will work. If you pass collection in render as second parameter to the view, the same name should not be used as public property.

Very good sir, I really find this helpful, this simple budge has stucked me for 2days.I think this should be specified in the documentation.

**Comment by that0n3guy** [comment]
Just for anyone else here... this is also the case for private and protected variables... not sure why.   I don't think it is supposed to be an issue with private/protected... but it defiantly is (v2.3.2)

**Comment by rafaelflorespereira** [comment]
What if I want to search for an element on the paginated array?

**Comment by joshhanley** [comment]
@rafaelflorespereira you would just add the search to your query in the render method. For example if you had a search macro setup, and had an input wired up to a property called $searchTerm, you could just use it like this:

```php
    public function render()
    {
        return view('livewire.hello-world', [
            'companies' => Company::search($this->searchTerm)->paginate(25)
        ]);
    }
```

Hope this helps!
