### ISSUE TITLE
[BUG] Artisan Error After Publish Config File

### ISSUE THREAD

**Issue by iqmal852** [livewire/livewire#723]
**Describe the bug**
I no longer able to run command`php artisan` once I publish the configuration file by using command `php artisan vendor:publish --tag=livewire:config`

**To Reproduce**
1. Install laravel version 7.0
2. Install LiveWire version 1.0
3. run command `php artisan vendor:publish --tag=livewire:config`
4. Next try run again `php artisan` u will receive error `Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given`.

There error coming from config `'asset_url'  => url('/'),` line `45`. If you comment that line everything works fine again

**Comment by calebporzio** [comment]
Good catch, fixed in the latest release: v1.0.7

**Comment by stevebauman** [comment]
Dang - this was my fault this got submitted into the core. I should have tested this more thoroughly.

My bad guys 😓
