### ISSUE TITLE
[IDEA] Cancelling requests instead of/as well as debounce

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#724]
When using axios/vue I used this technique quite a lot to ensure that results from old/irrelevant requests do not contaminate the front end.

For example, we have a content-editable div which is passing its contents to the livewire component. After we stop typing, we want some styling to be sent back to the front end. With a non-cancelling debounced request it is possible to:

- Type into the div
- Send this value to the livewire component class with something like `x-on:keyup="@this.set('query', $el.innerHTML)"` .
- Type a little more and then send the updated version.
- Receive back the first request to the front end and effectively overwrite the second.

If you are able to cancel the request whenever the editable div is updated, this is no longer possible. This is what I want to achieve:

![Kapture 2020-03-15 at 12 11 47](https://user-images.githubusercontent.com/20134485/76701205-ee850f00-66b6-11ea-8907-fe8acf29f3e4.gif)

What I currently have:

![Kapture 2020-03-15 at 15 03 57](https://user-images.githubusercontent.com/20134485/76704053-3b281480-66ce-11ea-8b71-c5a3a60e2915.gif)

To be clear, both of the above examples are typing into an editable div. We are trying to type "to:abc" in one continuous action. The above one works while the bottom livewire version is very glitchy.

I realise there are more issue than just this going on, but being able to cancel a request would get me much closer.

Additionally, If anyone has any suggestions on how we can better do this in livewire currently, it would be really appreciated!

**Comment by booni3** [comment]
I don't know enough about the internals to really comment on this, but I can see at least you are using the fetch method to send requests, which does have an abort method to it:

https://stackoverflow.com/questions/31061838/how-do-i-cancel-an-http-fetch-request

@calebporzio, do you think something like this could have wider use cases?

**Comment by lancepioch** [comment]
We are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. If you still feel this is relevant, please create a discussion there, thanks a bunch!
