### ISSUE TITLE
Nested components in the loop

### ISSUE THREAD

**Issue by bbcreation** [livewire/livewire#726]
I use the latest versions. I was on previous same problem.
In the loop I run: `<livewire:remove-modal :modal="$client" :key="$client->id">`

I have a search engine in this loop. Standard with examples.
If I search for something and then reduce the number of characters in the search, more records appear. At this point, one record (usually the last one) is not nested. And I get an error in the console.

```
index.js:20 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at new Component (index.js:20)
    at onNodeAdded (index.js:325)
    at callHook (morphdom.js:35)
    at handleNodeAdded (morphdom.js:168)
    at handleNodeAdded (morphdom.js:187)
    at handleNodeAdded (morphdom.js:187)
    at morphdom.js:430
    at morphEl (morphdom.js:242)
    at morphdom.js:355
    at morphEl (morphdom.js:242)
```

**Comment by breadthe** [comment]
I believe I ran into the same issue. Trying to build a tutorial demo featuring a list of items that can be filtered by Livewire. The list itself is a Livewire component; each item is also its own Livewire component that can be edited in place. Hopefully the attached gif can illustrate the problem.

![Kapture 2020-03-18 at 20 45 16](https://user-images.githubusercontent.com/17433578/77023672-822a3a00-695a-11ea-89af-ea23ed5b1f0d.gif)

**Comment by jacksegal** [comment]
@breadthe I had the same issue - worked for first interaction, but then stopped and threw that JS error.  It was caused by me not using `key` correctly - I was declaring a key on the Parent Component include and also within the Child Component (which created a duplicate key) - copy and paste error when I went from one Component, to a Parent Component with nested Child Components.  Might be worth checking your `key` to see if it's something similar (needs to be unique).

**Comment by bbcreation** [comment]
Unfortunately, I have unique keys. Can you show your loop in blade?

**Comment by WBDC** [comment]
Hi @breadthe 

I had the same JS error message. The wire:click worked the first time, and after throw the error it wanished all child components and showed that js error. 

My problem was that the child's route element was an <li> tag and not <div>
After I've changed to <div> it worked fine. 
I found the issue [here](https://github.com/livewire/livewire/issues/36)

I hope it helps resolving your issue too.

**Comment by breadthe** [comment]
@bbcreation @WBDC here's my loop (inside the parent component). The key is the model id so it's unique.

```
@foreach($widgets as $widget)
  <div class="flex items-center justify-between p-2 -mx-2 hover:bg-gray-100">
      @livewire('edit-name', compact('widget'), key($widget->id))
      // ...
@endforeach
```

Parent:
https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/widgets.blade.php#L42

Child:
https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/edit-name.blade.php

**Comment by WBDC** [comment]
> @bbcreation @WBDC here's my loop (inside the parent component). The key is the model id so it's unique.
> 
> ```
> @foreach($widgets as $widget)
>   <div class="flex items-center justify-between p-2 -mx-2 hover:bg-gray-100">
>       @livewire('edit-name', compact('widget'), key($widget->id))
>       // ...
> @endforeach
> ```
> 
> Parent:
> https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/widgets.blade.php#L42
> 
> Child:
> https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/edit-name.blade.php

The key definitely set once and the child's root tag is `div`. 

I know it sounds silly, but if you or other guys here have no other idea I would make a copy of the child and try to cut out "unnecessary" parts so it might help you to pin down the issue.

**Comment by bbcreation** [comment]
I know that the parent must be <div>,  just like Vue. Unfortunately I have done it there. The only difference is that I have it on the table...

**Comment by WBDC** [comment]
> I know that the parent must be
> 
> , just like Vue. Unfortunately I have done it there. The only difference is that I have it on the table...

I've tagged this issue on the other issue where Caleb seems like active. Hopefully he can shed some light on this for you. 

Sorry if I couldn't be any more help.

**Comment by bbcreation** [comment]
Thank you very much. You gave me a chance.

**Comment by jacksegal** [comment]
@breadthe - have you tried putting your child component within an empty div?  (so the alpine `<div>` isn't the root for livewire component)

**Comment by breadthe** [comment]
OK folks, I seem to have discovered part of the problem.

To recap, this produces the error (parent component):

```
@foreach($widgets as $widget)
  <div class="flex items-center justify-between p-2 -mx-2 hover:bg-gray-100">
      @livewire('edit-name', compact('widget'), key($widget->id))
       ...
@endforeach
```

If I move the `@livewire` directive right after the `@foreach`, it works as intended, though there is still some weirdness going on in my particular case (I'll take a stab at that later):

```
@foreach($widgets as $widget)
  @livewire('edit-name', compact('widget'), key($widget->id))

  <div class="flex items-center justify-between p-2 -mx-2 hover:bg-gray-100">
      // ...
@endforeach
```

**Comment by breadthe** [comment]
@ jacksegal thanks, your tip helped me arrive at my solution.
I have updated my [repo](https://github.com/breadthe/laravel-livewire-demo) - everything seems to work well now. Only issue is that there's additional nesting where I don't need it, and no nesting where I do need it.

[Parent view](https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/widgets.blade.php)
[Child view](https://github.com/breadthe/laravel-livewire-demo/blob/master/resources/views/livewire/edit-name.blade.php)

A minor annoyance is that this caused my layout to change. Basically I can't nest a *widget* and all its related *tags* under the same div. I suspect it has to do with the lack of reactivity between parent-child components. So when I filter something on the parent component (by typing something or selecting a tag), the change doesn't propagate to the child properly. For that reason I wasn't able to put the tags inside the child; I left them in the parent.

I guess it remains for Caleb to decide whether this whole discussion is an actual issue that needs to be fixed or maybe the documentation needs some additional clarification instead.

As it stands, it does appear that putting Alpine code in the root div of the child component will mess things up.

**Comment by bbcreation** [comment]
@breadthe  I reviewed your scripts a few times. Why do you have an alpine connection in head and body? As I added, just like you still in the body at the end and the `<div>` in the child everything started to work properly.

**Comment by breadthe** [comment]
@bbcreation thanks for that, I removed the duplicate script in the head. Silly mistake, I copy-pasted some code from footer to header and left the Alpine script in there. It didn't make a difference though, I had already fixed the underlying issue.

**Comment by bbcreation** [comment]
> @przeczytałem kilka razy sprawdziłem twoje skrypty. Dlaczego masz alpejskie połączenie głowy i ciała? Jak dodałem, tak jak ty na końcu w ciele iu `<div>`dziecka wszystko zaczęło działać poprawnie.

There is a TypeError again: Cannot read property 'data' of null, I don't know what I'm doing wrong.

**Comment by bbcreation** [comment]
> > @ przeczytałem kilka razy sprawdziłem twoje skrypty. Dlaczego masz alpejskie operacje głowy i ciała? Jak dodać ja, tak jak ty na końcu w ciele iu `<div>`dziecka wszystko zaczęło działać poprawnie.
> 
> Wystąpił błąd TypeError: Nie można odczytać właściwości „null” właściwości, nie wiem, co robię źle.

I added the key to `wire:key="{{$client->id}}"` `<tr>` in the loop and probably solved the problem. But the alpine must still be in body not in head. I'm testing all the time.

**Comment by jorgenb** [comment]
Any progress here? I am also getting this error with nested components after upgrading from v1.0.7 to v 1.0.12.

**Comment by bbcreation** [comment]
Problem solved. You have to wrap everything in `<div>` and add the keys to the right places. for example, you need to add a key to the first tag in the loop. Remember that nested must also have a `<div>` enclosure. Good luck.
