### ISSUE TITLE
Make Livewire component file and directory names and casing configurable

### ISSUE THREAD

**Issue by JunaidQadirB** [livewire/livewire#727]
**The Problem**
Whenever I generate a component, The component and its view file are created miles apart. and each with a different naming convention. 
Even if I have the option to change the paths for livewire components and views, Livewire is very opinionated.

**Examples:**

`Post.php` with `post.blade.php`
`Pages/About.php` with `pages/about.blade.php`

**My Solution**
When I run `livewire:make Post`,
it should create a Directory named **Post** and create `Post.php` and `Post.blade.php` inside the Post directory. This will make the components organized and easily navigatable.
 
At the moment I manually organize my components after generating them.

**UPDATE**

I've modified livewire for now to work the way I wanted
![live-wire-Peek 2020-03-15 23-59](https://user-images.githubusercontent.com/642353/76708509-2a50c080-6719-11ea-8543-5c22f6cc6a96.gif)

**Comment by baoanhng** [comment]
I think this maybe a good idea, because Livewire Components and Views are closely related. But since it depends on Laravel structure, will it be harder for application to scan for blade files? @JunaidQadirB

**Comment by JunaidQadirB** [comment]
No, it won't be because Laravel allows us to define custom view paths (via `config/view.php`) out-of-the-box.

**Comment by roni-estein** [comment]
If you are already able to change where you are storing files and it works for you. I have a suggestion. Perhaps write your own artisan command, that does whatever you want to accomplish. I do this regularly for tons of commands to deal with all sorts of situations. Just because something is convenient for you, doesn't mean it works for everyone else.

This isn't a criticism of the idea, just a plan to get exactly what you want without needing maintainers to deal with a ton of other non-package issues. If you need some guidance, or help don't hesitate to post what you have and what you want to accomplish.

**Comment by JunaidQadirB** [comment]
I agree with you. 
But it would be great if it is made configurable enough that if someone whats to change the way LiveWire names the components and views could easily do it via `config/livewire.php`

**Comment by jongravois** [comment]
IMHO, this is how frameworks become bloated (like Vue, Angular, etc) by becoming more and more less opinionated and attempting to handle edge cases. As frameworks become bloated, they are rejected and replaced by simpler and opinionated tools until they too become bloated.

**Comment by calebporzio** [comment]
Yeah, just going to keep things the way they are for now.

You are free to manually create and manage Livewire component files yourself, or make your own helper commands.

**Comment by JunaidQadirB** [comment]
Hi, here I am again. Seems like no matter how hard are I try, it's inconvenient for me to work with files of the same component miles apart in case of Livewire especially. because the component and iit's view are part of the same "domain" I want them to be under the same directory.

It would be great if someone can point me in the right direction to help me achieve my desired results (See OP) without touching Livewire source files.

If I fork my own modified Livewire, it would become obselete in a matter of weeks with the rapid development pace of Livewire.


One Idea is to create a new package that overrides Livewires commands, but I'm not certain if it would work but I'll give it a shot sometime next month.

Peace!

**Comment by uneekswatian** [comment]
You can simply use

`php artisan ivewire:make post.Post`

it will create the folder post and will put the view and controller as Post inside it.
