### ISSUE TITLE
AlpineJS deferral breaks minified version of script

### ISSUE THREAD

**Issue by nielspeen** [livewire/livewire#737]
The new code that defers loading of AlpineJS breaks the minified version of the Livewire script.

* // comment comments out all of the minified code after it.
* window.deferLoadingAlpine needs a semi-colon.

**Comment by bebo925** [comment]
I am having this same issue.  Oddly, it only happens with APP_DEBUG is turned on.

**Comment by calebporzio** [comment]
Fixed in v1.0.8, thanks!
