### ISSUE TITLE
Errorbag removed after each field updated on a form, same issue from #319 issue

### ISSUE THREAD

**Issue by TheOWler** [livewire/livewire#7377]
### Discussed in https://github.com/livewire/livewire/discussions/7376

<div type='discussions-op-text'>

<sup>Originally posted by **TheOWler** November 24, 2023</sup>
### Livewire version

v3

### Which PHP version are you using?

PHP 8.1

### Steps To Reproduce

this issue is still present in livewire3, any possible fixes ?
i have it working fine on livewire 2 on a seprate project and on my current one this issue is still valid
**THE ISSUE IS :**
When using a livewire component to represent a form, after a form submission with validation errors, everything works as expected, however once you trigger any update, by changing any of the invalidated fields, the errorbag is removed, even though the form hasn't been re-submitted.

To Reproduce

Have a component with two elements. In my case I'm not even using a form though I would if there was any reason too.

Add a submit method with validation.

after receiving the errors, alter one field. All the errors will disappear.

Expected behavior
I'd expect only the component data to change, and not update request, unless the an action was triggered by some intended submission. If I want css to change or resubmit the data automatically, it should be triggered.

Screenshots:
![image_2023-11-24_222309364](https://github.com/livewire/livewire/assets/90655021/b2250abb-9c34-46dc-a0a3-0dffbbdc0119)
Changing any element, will remove errorbag
![image](https://github.com/livewire/livewire/assets/90655021/90011c52-2717-40e4-ad9d-a75764d05536)

LINK to the old issue : [https://github.com/livewire/livewire/issues/319](url)

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
