### ISSUE TITLE
Content from @yield inside a Livewire view disappears from dom response

### ISSUE THREAD

**Issue by dhanyn10** [livewire/livewire#7395]
### Discussed in https://github.com/livewire/livewire/discussions/7382

<div type='discussions-op-text'>

<sup>Originally posted by **dhanyn10** November 26, 2023</sup>
### Livewire version

3.0

### Which PHP version are you using?

PHP 8.1

### Steps To Reproduce

same issue with https://github.com/livewire/livewire/issues/807
im calling the layout with
```php
@extends('components.layout')
@section('content')
...
{{$blogs->links()}}
...
@endsection
```
and load the page with livewire.
```php
use Livewire\WithPagination;
class Blogs extends Component
{
use WithPagination;
public function render()
    {
        $data = BlogsModel::where('status', 'published')->get();
         return view('livewire.blogs',[
            'blogs' => $data
        ]);
    }
}

### Additional information

_No response_

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
