### ISSUE TITLE
Browser renders livewire syntax to user and $message variable for validation is undefined

### ISSUE THREAD

**Issue by ReubenFrimpong** [livewire/livewire#742]
Using Laravel 5.7, trying out the [validation](https://laravel-livewire.com/docs/input-validation) feature of livewire however the syntax such as @error displays on my browser. Also when I try using the $message it complains of undefined variable.
Any help?

**Comment by ManojKiranA** [comment]
`error` blade directives won't because @calebporzio Sent a [PR](https://github.com/laravel/framework/pull/28062) on 5.8 Version.

You can still use 

**FOR CHECKING IF THE ERROR EXISTS**

```
@if ($errors->has('name'))
    <span>{{ $errors->first('name') }}</span>
@endif
```

So here is the Updated Code Snippet from the Docs.


```
<form wire:submit.prevent="submit">
    <input type="text" wire:model="name">

    @if ($errors->has('name'))
    <span class="error">{{ $errors->first('name') }}</span>
    @endif

    <input type="text" wire:model="email">

    @if ($errors->has('email'))
    <span class="error">{{ $errors->first('email') }}</span>
    @endif

    <button type="submit">Save Contact</button>
</form>

```

If possile i will send a PR to Docs.

**Comment by ReubenFrimpong** [comment]
Works...thanks

**Comment by calebporzio** [comment]
Thanks for providing the fix @ManojKiranA !
