### ISSUE TITLE
Livewire Incompatible with Vue after 1.0.8

### ISSUE THREAD

**Issue by intellow** [livewire/livewire#745]
I am getting the following error when trying to use Livewire on the same page where I have a Vue instance:

```Uncaught (in promise) 
Livewire Error:

Cannot find parent element in DOM tree containing attribute: [wire:id].
```

1. Fresh Laravel install, using vue scaffolding (npm install, npm run dev, add app.js to your view, all that jazz)
2. Add the livewire styles, scripts, and vue plugin `<script src="https://cdn.jsdelivr.net/gh/livewire/vue@v0.1.0/dist/livewire-vue.js"></script>`
3. Add a livewire component to the page. Wire:model up a text input and put it inside a div. Make sure to give it an id:

```html
<div>
    <div class="your-class">
        <input type="text" wire:model="description" id="description"/>
    </div>
</div>
```

3. Try to type in the input and you get the error.

![image](https://user-images.githubusercontent.com/40676515/76997869-09a78700-6922-11ea-97ac-cada6183411e.png)

Note: If you remove the id from the input element, everything works EXCEPT for after the first request is sent to the server, the text input is unfocused.up

![2020-03-18_14-11-31 (1)](https://user-images.githubusercontent.com/40676515/76998196-a9fdab80-6922-11ea-9399-d574827c8ceb.gif)

4. If you remove the surrounding div and just do this:

```html
<div>
      <input type="text" wire:model="description" id="description"/>
</div>
```
Then you get the same issue where the input is unfocused after the first api call.

Note: If you remove the id from the input element, then everything seems to work fine.

5. Lastly, if you go into your `resources/app.js` and comment out the Vue instance and run `npm run dev` then everything works just fine.

```
const app = new Vue({
    el: '#app',
});
```

I hope this is enough information to track down the issue. Again, this issue was not present in 1.0.7 and was introduced in 1.0.8.

**Comment by devcircus** [comment]
According to the upgrade guide for 1.0.8, Vue support was removed and made into a separate plugin. https://github.com/livewire/vue

**Comment by intellow** [comment]
All these problems occur with the plugin installed.

**Comment by lancepioch** [comment]
Can you make your issue on the https://github.com/livewire/vue repo

**Comment by tplessis** [comment]
Same here, with vue plugin installed. Works well with livewire 1.0.7.

**Comment by intellow** [comment]
This is fixed with the latest version of the vue plugin. As of right now it is 0.2.0.

`<script src="https://cdn.jsdelivr.net/gh/livewire/vue@v0.2.x/dist/livewire-vue.js"></script>`

Thanks @calebporzio for getting this worked out.
