### ISSUE TITLE
Route Caching on SPA examples aren't cachable

### ISSUE THREAD

**Issue by ragingdave** [livewire/livewire#746]
**Describe the bug**
When utilizing a livewire route like:

    Route::livewire('/home', 'counter')
        ->layout('layouts.app', [
            'title' => 'foo'
        ]);

The route becomes uncachable from laravel's eyes and running route:cache result in an exception that the route isn't cacheable.

**To Reproduce**
In a laravel +livewire configuration, use a route as above, then run `php artisan route:cache`. 

**Expected behavior**
Routes will be cached correctly without error.

**Screenshots**

**Comment by chrysanthos** [comment]
What's Laravel version are you using? Try updating to the latest (7.2.0) and see if the problem persists. I think most problems related to route caching are fixed now.

**Comment by georgeboot** [comment]
This has nothing to do with Laravel 7. In Laravel, you can't cache closure routes, and `Route::livewire()` resolves to a closure:

https://github.com/livewire/livewire/blob/af54a661d95ae5cc253ba3759105bfd9b522421e/src/Macros/RouterMacros.php#L25-L43

**Comment by georgeboot** [comment]
For anyone looking for a temp solution: create a simple controller and view:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;

class LivewireSPA extends Controller
{
    public function __call($method, $parameters)
    {
        $componentName = Str::kebab($method);

        return view('livewire-spa', compact('componentName'));
    }
}
```

```blade
@extends('layouts.app')

@section('content')

    @livewire($componentName)

@endsection
```

**Comment by calebporzio** [comment]
Laravel will be adding route closure caching in V8 I believe. This will work soon. Closing this.
