### ISSUE TITLE
Not Working Search ( with solution)

### ISSUE THREAD

**Issue by ricardosenabr** [livewire/livewire#749]
Hello guys!

First of all thanks for the excellent work on livewire.

I found a small bug.

When adding @livewire ('component) to the blade

This component cannot contain a comment at the top.

It stops the search from running in the view.

![WhatsApp Image 2020-03-20 at 01 32 01](https://user-images.githubusercontent.com/41302029/77163175-4a231400-6a8c-11ea-8cf6-a68fe23c46ab.jpeg)

**Comment by ninthspace** [comment]
This is a duplicate of #725.

**Comment by ricardosenabr** [comment]
ok!!

Sorry!
