### ISSUE TITLE
Dynamically/conditionally mounting components in runtime

### ISSUE THREAD

**Issue by mustafaaloko** [livewire/livewire#750]
I was loading a Livewire component inside an AlpineJS conditional `x-if` like below, once the condition evaluates to true, the dom for the component does load, but other functionalities don't work. I specifically checked model binding with `wire:model` which doesn't work.  Debugging through Livewire source code, I noticed that the component inside `x-if` doesn't get initialized at all (I mean after `x-if` evaluates to `true`). With `x-show` everything works fine, cause everything gets initalized on page load.

```laravel
...
<template x-if="open">
    @livewire('hello-world')
</template>
...
```

How can I mount/initialize components once they are dynamically added to the dom in runtime (not in initial page load)?

**Comment by calebporzio** [comment]
That's a great question. Can you just use x-if? Also, try `window.livewire.rescan()`

**Comment by mustafaaloko** [comment]
I had already tried that, didn't work. I tried `window.livewire.rescan()` both in the component which is inside `x-if` template and also to be sure in browser console too after the element showed up on the browser, but still, model binding doesn't work. Tried `window.livewire.restart()` too.

Also, I didn't get what you meant by just use `x-if`? I am already doing that.

**Comment by mustafaaloko** [comment]
Will still explore on my side to find a way for this.

**Comment by mustafaaloko** [comment]
So I just checked, `window.livewire.rescan()` works if the component is in root and not inside another component (not nested). But, it doesn't work for nested components.

**Comment by mustafaaloko** [comment]
I think I understood and found why it isn't working, based on `rescan()` source, it only checks for the root component elements with no parents, which somehow makes sense, cause if it finds any new component element inside the ones in the root, they will be added recursively once the root component object is created and is initialized, 

In my case, as there is no change in root component elements, it simply continues the loop and doesn't do anything about it, ignoring what changes might have happened inside the root component elements.

**Comment by calebporzio** [comment]
Sorry, I meant ‘x-show’

**Comment by mustafaaloko** [comment]
Well, in my specific scenario, I wanted to lazy load a few scripts (inside my Alpine component) only when the Livewire component (which is using the mentioned Alpine component inside itself) is rendered (e.g. on a modal view, or any other action). Do you have any suggestions to achieve that?

**Comment by calebporzio** [comment]
Lazy loading can be done using `wire:init` -> go here for more details: https://laravel-livewire.com/docs/defer-loading

**Comment by assoft** [comment]
Hey @calebporzio this is possible? or is there a way to do it?

app\Http\Livewire\Post\Base.php

```php
Class Base extends Component {
    public $view = "index";

    public function render()
    {
        return view('livewire.post.base');
    }

    public function updated($value)
    {
        if ($value === "view") {
            $this->render();
        }
    }
```

resources\livewire\post\base.blade.php

```php
<div>
    <select wire:model="view class="form-select">
        <option value="index">Index</option>
        <option value="edit">Edit</option>
    </select>
    <div class="view-area">
        @livewire("post.$view")
    </div>
</div>
```

**Comment by assoft** [comment]
> Hey @calebporzio this is possible? or is there a way to do it?
> 
> app\Http\Livewire\Post\Base.php
> 
> ```
> Class Base extends Component {
>     public $view = "index";
> 
>     public function render()
>     {
>         return view('livewire.post.base');
>     }
> ...
> ```

This is work :) 👍 
```php
    @switch($view)
            @case("create")
                @livewire("posts.create")
                @break
            @case("edit")
                @livewire("posts.edit")
                @break
            @default
                @livewire("posts.index")
        @endswitch
```

**Comment by abdosaeedelhassan** [comment]
hi, also i want to dynamic render render livewire component inside main component according to condition, i did it as follow
        <div x-data="{tab:'offer'}">
<div x-show="tab=='chatting'">
                    <livewire:asaydev-chatting-main group="offers" groupId="{{$order->id}}"
                                                    senderId="{{auth()->user()->id}}"
                                                    receiverId="{{$order->created_by==auth()->user()->id?$order->examined_by:$order->created_by}}"
                </div>
</div>

the above code already inside the main component, but not worked for me, in the browser inspect just display the livewire component as html tag, i need help, thank you

**Comment by devilstars** [comment]
I have the same issue with x-if (apline.js).
``` blade
<template x-if="$store.modalAuth.open">
    <div class="fixed inset-0 z-30"
         x-transition:enter="transition ease-out duration-100"
         x-transition:enter-start="opacity-0 transform"
         x-transition:enter-end="opacity-100 transform"
         x-transition:leave="transition ease-in duration-100"
         x-transition:leave-start="opacity-100 transform"
         x-transition:leave-end="opacity-0 transform">
       <livewire:auth.modals.login />
    </div>
</template>
```
```auth.modals.login``` is rendered correctly in the dom, but backend does nothing with it. No validation, no submit. It works just like a regular form without the livewire.
I had to replace ```x-if``` with ```x-show``` to make it working again.

**Comment by awizemann** [comment]
I am also having a similar issue. I am loading components dynamically, meaning that I am rendering one component view that has other components in it. They load, however they do not fire. If I emit the function again (it's a wire:click) they load just fine. Is there a way to tell the component that they need to render when I fire that event after the view is finished rendering? I have tried window.livewire.rescan() but that doesn't work.

**Comment by ehsantalkhouncheh** [comment]
i have a same issue i saved livewire component name in database like this @livewire('component_name') and when i try to load it as a content of page it doesn't render and shoe me just as a text anybody have a solution??

**Comment by divdax** [comment]
Same here with a different scenario. If i add a livewire component-tag with javascript to the DOM it would be cool if i can "rescan" the dom to render the component correctly.
