### ISSUE TITLE
Allow to override default MiddlewareGroup in Component

### ISSUE THREAD

**Issue by basepack** [livewire/livewire#751]
**Is your feature request related to a problem? Please describe.**
I have a webshop where every product has a complex calculator on it, (easy with awesome Livewire! ) this calculator has these functions on it:
-  `decrement` 
- `increment` 
- and three others, less used

The `decrement` and `increment` functions really only call a `calculation()` function of the `PriceCalculator` class. So, no need for the heavy expensive `web` middleware here with Session, Cookie and other more resource heavy stuff.

And as you can imagine, these `decrement` and `increment` functions will be fired 100s of times each minute to each second on busy moments in this webshop.

I do not want to rewrite my PriceCalculator in an AlpineJS or Vue component for these reasons:
- Keep it stupid simple with Livewire
- No code redundancy in PHP **and** JS
- No extra tests to write for the JS part (who loves to do that?)
- Like point one, buy also: less code to maintain

**Describe the solution you'd like**
Per `Livewire\Component` the possibility to do: 
`public $middlewareGroup = 'api'`

Or even per function:
`$this->middlewareGroup = 'api`
And only this function is using the `api` middlewareGroup.

**Describe alternatives you've considered**
Well, I did try:
```
public function hydrate()
{
    config(['livewire.middleware_group' => 'api']);
}
```
But that did not change the used middleware, as per Telescope request details.

**Comment by calebporzio** [comment]
Can you test the speed difference of using "api" vs "web"? Wondering how beneficial this feature would be.

**Comment by basepack** [comment]
I am running Lando (docker), and here are some runs from my own machine:

web | api
------------ | -------------
42 | 
 | 
 | 
 | 
 | 
 | 


Someone did a comparison in 2018, see here: https://medium.com/@laurencei/lumen-vs-laravel-performance-in-2018-1a9346428c01
Look at the second table, first two columns for a comparison.

**Comment by joveice** [comment]
I would love add the `auth` middleware on certain components.

**Comment by calebporzio** [comment]
Great, thanks for checking on the speed thing. Going to close this now. If someone wants to open a separate issue about the auth middleware, go for it. Thanks!

**Comment by joveice** [comment]
@calebporzio isn't that exactly this issue? To override the default middleware with something else?

**Comment by joveice** [comment]
Just noticed that if I call for user stuff inside the view my tests fails as it tries to render the view without the user.
Tried to add this
```
public function render()
    {
        if (!auth()->check()) {
            return abort(401);
        }
        return view('livewire.users.show.user-friendship-buttons',[
            'user' => $this->user,
        ]);
    }
```
But that fails with undefined index.
This is a perfect example for the option to add the middleware auth to the component, now I could add it to the default in the config, but I don't want all my components to be placed under auth as there are a few that are on pages guests can access and use.
