### ISSUE TITLE
Incorrect documentation on $updatesQueryString

### ISSUE THREAD

**Issue by tiago-sb** [livewire/livewire#752]
**Describe the bug**
Incorrect documentation regarding 
[Keeping A Clean Query String](https://laravel-livewire.com/docs/properties#clean-query-string)

**To Reproduce**
This didn't work for me:
```
protected $updatesQueryString = [
        'foo',
        ['search' => ['except' => '']],
        ['page' => ['except' => 1]],
    ];
```
This did:
```
protected $updatesQueryString = [
        'foo',
        'search' => ['except' => ''],
        'page' => ['except' => 1],
    ];

```

Happy to make a PR to correct this, if/once it is confirmed.

**Comment by calebporzio** [comment]
Would love a PR for this to the docs repo. Thanks! Closing this then.

**Comment by tiago-sb** [comment]
Done [PR#120](https://github.com/livewire/docs/pull/120)
