### ISSUE TITLE
Component with multiple root elements binds values only to the first root element

### ISSUE THREAD

**Issue by ddevdreamer** [livewire/livewire#754]
If you have multiple root elements in a component, only the bindings which are present inside the fist root element works since, <code>wire:initial-data</code> is attributed only to the first root element.

**To Reproduce**

```php

<?php

namespace App\Http\Livewire;

use Livewire\Component;

class MyComponent extends Component
{
    public$foo = 'Foo Element';
    public $bar = 'Bar Element';

    public function render()
    {
        return view('livewire.my-component');
    }
}

```
```blade
<div>
    First Element: <input wire:model="foo" type="text">
</div>

<div>
    Second Root Element: <input wire:model="bar" type="text">
</div>
```

**Expected behavior**
First Input box to be filled with value <code>Foo Element</code> & second input box to be filled with value <code>Bar Element</code>

![image](https://user-images.githubusercontent.com/12023205/77209275-f0176280-6b0e-11ea-9835-2cc4bb43167a.png)

**Thank you for this awesome framework 😍**

**Comment by mustafaaloko** [comment]
Actually you are supposed to have a single root element in a component. Please see https://laravel-livewire.com/docs/render-method. 

> Make sure your Blade view only has ONE root element.

You can add both your divs inside a single one and this will be solved.

**Comment by ddevdreamer** [comment]
> Actually you are supposed to have a single root element in a component, you can't have multiple. Please see https://laravel-livewire.com/docs/render-method.
> 
> > Make sure your Blade view only has ONE root element.
> 
> You can add both your divs inside a single one and this will be solved.

Thank you. I am aware of that. I already fixed my issues that way. @calebporzio has asked me to create an issue here regarding this [https://github.com/livewire/docs/pull/113](Pull Request)

**Comment by lancepioch** [comment]
#946 will throw an exception that should help users understand the issue, thanks
