### ISSUE TITLE
Multiple components for different sections in a specific route

### ISSUE THREAD

**Issue by yamakrane** [livewire/livewire#756]
Hi all,

adding Turbolinks to an app may let you want to render some new components and not others especially in a non nested architecture.

So I was thinking that maybe like vue-router it could be fun to add multiple components to different sections in a specific route. Like for example:

//web.php
Route::livewire('/home',[ 'component1','component2','component3'])
    ->sections(['section1','section1','section2']);

Route::livewire('/blog',['component4','component2'])
   ->sections(['section2','section1'])

==> HERE COMPONENT 2 SHOULDNT BE RERENDERED FOR EXAMPLE WHEN CHANGING PAGES

// app.blade.php
@yield('section1')
@yield('section2')
@yield('section3')

**Comment by calebporzio** [comment]
Interesting though. I personally have not needed something like this and haven't heard the same from others, so I'm going to close this.

Thank you for the idea though.

**Comment by yamakrane** [comment]
How do you do @calebporzio to keep a component alive even if you change the route ?
