### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null using jquery inputmask

### ISSUE THREAD

**Issue by theonly27** [livewire/livewire#757]
**Is your feature request related to a problem? Please describe.**
I'm getting error Uncaught TypeError: Cannot read property 'split' of null when I use jquery input mask (https://github.com/RobinHerbots/Inputmask) in the livewire component blade.

**Desktop (please complete the following information):**
 - Browser: Brave
 - OS: Windows 7

Any idea to fix this? thanks

Edit
Here's my source code

form.blade.php
```html
<div class="form-container">
<form> 
 <input type="text" class="form-control" wire:model="amount" id="amount" >
</form>
</div>
@push('script')
<script src="https://cdn.jsdelivr.net/npm/inputmask@5.0.4-beta.26/dist/jquery.inputmask.min.js"></script>
<script>
$("#amount").inputmask({
        alias: "numeric",
        groupSeparator: ',',
        digits: 3,
        digitsOptional: false,
        placeholder: '0'
   });
</script>
@endpush
```
Component
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Form extends Component
{

    public $amount;
    public function render()
    {
        return view('livewire.form');
    }
}
```

**Comment by lancepioch** [comment]
Please post a minimal example showing the bug because at first glance it seems like it might be an issue with the input, thanks!

**Comment by theonly27** [comment]
> Please post a minimal example showing the bug because at first glance it seems like it might be an issue with the input, thanks!

Edited my post, I don't have any complex properties for my input, please see my script above.

**Comment by theonly27** [comment]
Hello it seems I've fixed the issue, I just add ready function just like below.
```
$(document).ready(function() {  
 // code
});
```

**Comment by calebporzio** [comment]
Still will need more info, please post basic template code so we can see how to reproduce this.

**Comment by theonly27** [comment]
@calebporzio Hi, I updated my post with the basic template. thanks.

**Comment by theonly27** [comment]
Hello any work aroud for this? thanks

**Comment by theonly27** [comment]
Hi, it seems I solved the problem, 
in my blade I did something like this

```
 <input wire:ignore onchange="@this.set('amount', this.value);"  type="text" 
class="form-control"  id="amount" >
```

**Comment by ArthurYdalgo** [comment]
> Hi, it seems I solved the problem,
> in my blade I did something like this
> 
> ```
>  <input wire:ignore onchange="@this.set('amount', this.value);"  type="text" 
> class="form-control"  id="amount" >
> ```

Oh my... you just saved my day.

**Comment by marchantm** [comment]
> <input wire:ignore onchange="@this.set('amount', this.value);"  type="text" 
> class="form-control"  id="amount" >

Hi, not working for me. I put all code exactly like you. Any other tip?

**Comment by olgerng** [comment]
a mi me funcionó colocandolo de la siguiente forma:

<input wire:model.deboundance.800ms="amount" onchange="@this.set('amount', this.value);"  type="text" 
class="form-control"  id="amount" >

Me funciona perfectamente
