### ISSUE TITLE
handleViewException() must be an instance of Exception, instance of Error given

### ISSUE THREAD

**Issue by oliverbj** [livewire/livewire#761]
**Describe the bug**
I am trying to create a simple "Datepicker" component, where users can select a date from a calendar. 

I have this `Datepicker.php` component:

```php
class Datepicker extends Component
{

    public $monthDays;
    public $monthName;
    public $year = null;
    public $currentDate;
    public $selectedDate;
    
    public function mount()
    {
        $this->currentDate = Carbon::now()->toDateString();
        $this->selectedDate = Carbon::now()->toDateString();
        $this->build();

    }

    public function build(int $month = null)
    {
        $month = Carbon::now()->month;
        $this->year = Carbon::parse($this->currentDate)->year;

        $start = Carbon::parse($this->year .'-'. $month)->startOfMonth();
        $end = Carbon::parse($this->year .'-'. $month)->endOfMonth();

        //Set calendar
        $this->monthDays = CarbonPeriod::create($start, $end)->toArray();
       
    }

    public function selectDate($date)
    {
        $this->selectedDate = $date;
    }
 
   public function render()
    {
        return view('livewire.datepicker');
    }

}
```
In my `datepicker.blade.php`, I have a simple action called `selectDate`, where I want users to be able to select a specific date:

```html
    <div class="flex flex-wrap -mb-4 -mx-2">
    @foreach($monthDays as $date)
        <div class="w-1/5 text-left px-2 mb-3">
          <div wire:click="selectDate('{{ $date->toDateString() }}')">
                {{$date->day}}
            </div>
        </div>
    @endforeach
    </div>
```

So above simply prints out all the days in the current month. The then user can click on a date, and it will trigger the `selectDate()` method. 

However, when triggering this, I get below error:

> Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Livewire\CompilerEngine::handleViewException() must be an instance of Exception, instance of Error given, called in /Users/oliverbusk/Sites/gea/vendor/livewire/livewire/src/LivewireViewCompilerEngine.php on line 52

**Screenshots**
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/jTO1P.png

**Comment by calebporzio** [comment]
I think this was a bug related to using the word `date` as a parameter in an action (odd, I know). Should be fixed now. Closing this.
