### ISSUE TITLE
Livewire form input miss value when loading

### ISSUE THREAD

**Issue by jocket1** [livewire/livewire#7612]
### Discussed in https://github.com/livewire/livewire/discussions/7611

<div type='discussions-op-text'>

<sup>Originally posted by **jocket1** December 26, 2023</sup>
I have a form data and some input with type text
When I set the network of Chrome is slow 3g. The browser loading then I input some text after that it loads successfully then the text disappears. 
How to keep data when it loading 

https://github.com/livewire/livewire/assets/154584353/2c36e08c-bffa-4c54-b802-e6b91ffe337a

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
