### ISSUE TITLE
redirect()->away() does not work

### ISSUE THREAD

**Issue by nielspeen** [livewire/livewire#762]
**Describe the bug**

Documentation suggests that any Laravel redirection notation may be used, but the away() function does not work.

**To Reproduce**

1. Create a Livewire function that uses redirect()->away() instead of redirect()->to()

**Expected behavior**

A redirect mimicking Laravel's own redirect()->away() . (Essentially a redirect to the exact URL specified rather than what Laravel thinks the URL should be.)

Currently the call does nothing at all. No redirect, no error.

**Comment by nielspeen** [comment]
Work-around I'm using for now:

Directly set $this->redirectTo available through the PerformsRedirections trait. Then call an empty redirect();

**Comment by calebporzio** [comment]
I believe this wouldn’t be too difficult to PR to Livewire. Do you feel capable?

**Comment by nielspeen** [comment]
Looks like https://github.com/livewire/livewire/commit/9d051d75bced598f8a2880ffd625bc25b2024b2f broke the intent of Laravel's away() function. It now just uses to(), which in turn uses the UrlGenerator. away() should not use the UrlGenerator.

Resorting to my old work-around for now.
