### ISSUE TITLE
SPA mod with Pagination problem

### ISSUE THREAD

**Issue by abq0** [livewire/livewire#7623]
### Discussed in https://github.com/livewire/livewire/discussions/7607

<div type='discussions-op-text'>

<sup>Originally posted by **abq0** December 25, 2023</sup>
When enabling **SPA** mod ( wire:navigate ) and using **Pagination** , for some reason when I click on some element, it takes me to URL ( null ) for e.g. I have cards with sections names ( cars - food ... etc ) each section could contain comments so there's a @if checks there's a comment ? then add wire:navigate to the element if not add tooltip - no comment -  , so when I click some random element , it take's me to null URL ( http://localhost/null ) and other works fine!</div>

**Comment by PhiloNL** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by mauriciovictor** [comment]
Any solution ? same problem with me
