### ISSUE TITLE
Re-rendering points to default locale (Localisation)

### ISSUE THREAD

**Issue by fahadkhan1740** [livewire/livewire#765]
**Describe the bug**
Trying to validate in the updated() method. For English, it is working fine. But of other locales, the page re-renders to default locale.

**To Reproduce**
1. Create locale routes as `/en` and `/ar`.
2. Create an input field and add validation on `updated()`. 
3. When you get a validation error, despite having the `/ar` locale in the URI, the page turns English.

**Expected behavior**
It should stick to the locale while validation or `$refresh` from which the page was initially loaded.

**Screenshots**
Have a look at the URI. It is `/ar` but the validation is coming for`/en` instead of `/ar`
![image](https://user-images.githubusercontent.com/11314103/77472924-b6539e00-6e25-11ea-8130-646159143904.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by GertjanRoke** [comment]
Hello @fahadkhan1740, I looked into this issue and this doesn't work because I think your setting it based some `{locale}` key in the route and then somewhere call `app()->setLocale(request()->route('locale'))`.  

Well this works for normal `POST` calls because you maybe always prefix that route with that `{locale}` key, but the endpoint for Livewire only contains the name of the component.  
You could also add the `{locale}` to the component, but then you always need to add this property to every component.

So I played with this a bit in this example repo: https://github.com/GertjanRoke/livewire-examples/blob/master/app/Http/Livewire/LanguageValidation.php

But basically this is what I did:

I created a new middleware called `SetLocale` and added it into the `web` group inside `app/Http/Kernel.php`:
```php
/**
 * The application's route middleware groups.
 *
 * @var array
 */
protected $middlewareGroups = [
    'web' => [
        ...
        \App\Http\Middleware\SetLocale::class,
    ],
    ...
];
```

**SetLocale Middleware:**
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

class SetLocale
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure                  $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $locale = $request->route('locale') ?: Session::get('locale');

        if ($locale) {
            App::setLocale($locale);

            /**
             * We need to store the locale in the session because we don't want to pass it to each component we create.
             * Also because we fetch the locale from the route but the url for the Livewire API endpoint only
             * contains the component name.
             */
            Session::put('locale', $locale);
        }

        return $next($request);
    }
}
```

**Comment by marispro** [comment]
@GertjanRoke  Nice solution. But it doesn't work correct when somebody switches to another (second) language but then goes to previous page by clicking back button. 
Component will have new one (second) language, but rest of page stays on preivous language.

**Comment by GertjanRoke** [comment]
@marispro I’m curious how you switch the language then, because the setting of the locale and updating the session is first based on the url param and then when it calls the Livewire url it already should have fixed the session cache to the correct language.

So if you can share how you do it that would help me and maybe also others.

**Comment by marispro** [comment]
@GertjanRoke Example would be difficult right now. 
So when user clicks back button it doesn't make new request for page again, it just shows previous page last state, meanwhile having new locale in session.

**Comment by DanHarrin** [comment]
Hey @fahadkhan1740 @GertjanRoke @marispro. I've just submitted #1197 which should solve your issue. If you have a chance to confirm that it does, that'd be great! Many thanks

**Comment by GertjanRoke** [comment]
@DanHarrin I would love to check it! Do you know how I can get your changes locally? I already have an demo repo where I tested my solution.

**Comment by DanHarrin** [comment]
Hey @GertjanRoke, you should now be able to pull in the `dev-master` version of Livewire in your composer.json.

**Comment by GertjanRoke** [comment]
@DanHarrin I can confirm this works like a charm!! Great job!

For people who want to know how I switched the locale based on the route here is an example or go to the test repo I used at the bottom of this comment.

Create a middleware class that looks something like this:
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\App;

class SetLocale
{
    public function handle($request, Closure $next)
    {
        if ($request->route('locale')) {
            App::setLocale($request->route('locale'));
        }

        return $next($request);
    }
}
```

Then add it to your kernel class (App/Http/Kernel.php):
```php
...
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \App\Http\Middleware\SetLocale::class,
            // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            // I added it here, but place it wherever it makes sense for you.
            // You can also add it inside the routes/web.php file.
        ],
        ...
```


Route file:
```php
// Laravel routing options:
Route::view('{locale}/validation', 'language-validation'); // This are just examples
Route::get('{locale}/validation', 'FormController@index'); // This are just examples

// Livewire routing
Route::livewire('{locale}/validation', 'language-validation')->name('language-validation');
```

You can see a demo here: https://github.com/GertjanRoke/livewire-examples

**Comment by fahadkhan1740** [comment]
@DanHarrin thank you for your contribution

**Comment by mo3auya91** [comment]
I have a similar problem related to localization,
I created a blog using laravel 8 and livewire, there is a post pagination
the $posts->links() rendered the default pagination component, but the links dose not working in localization, it throws 404 modal, but when disable the localization middleware it works perfect.
<img width="1430" alt="Screenshot 2020-09-15 at 20 36 37" src="https://user-images.githubusercontent.com/6853643/93245653-46025580-f794-11ea-8eb8-45a2a67f2c15.png">
here are screenshots of the pagination component and the 404 modal shown when click on pagination buttons 
<img width="1439" alt="Screenshot 2020-09-15 at 20 36 28" src="https://user-images.githubusercontent.com/6853643/93245639-43076500-f794-11ea-9f9c-5392f7e92b94.png">

**Comment by DanDvoracek** [comment]
Similar issue here when installing mcamara localization package.

I am not sure if my problem is related to the Authorization guards in livewire.php config file, but what happens is basically that the component returns a 404 when it refreshes:

![Screenshot 2020-10-05 at 09 56 12](https://user-images.githubusercontent.com/1983331/95055736-01633d80-06f4-11eb-8cf9-534aa8ba1726.png)

First request seems ok, the second one fails. As you can see the locale param is passed the second time as well (not the first): http://project.test/**fr**/livewire/message/auth.login .

All the other routes work pretty fine so far, problem is really with the basic auth routes. Any hints on how to fix this ?

**Comment by DanDvoracek** [comment]
I may have found a way to make it all work. I needed to add the following ignored routes in the laravellocalization.php config file:

```
// URLs which should not be processed, e.g. '/nova', '/nova/*', '/nova-api/*' or specific application URLs
// Defaults to []
'urlsIgnored' => ['/livewire/message/auth.login', '/livewire/message/auth.register'],
```

Then I had to amend redirects in Login.php and Register.php. So far, the app behaves as expected.

**Comment by brielmayer** [comment]
When using [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization) I came with following solution.

Add route middleware 'localSessionRedirect':
`Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [
        'localeSessionRedirect'
    ]
], function () {
    require base_path('vendor/laravel/fortify/routes/routes.php');
    require base_path('vendor/laravel/jetstream/routes/livewire.php');

    // Dashboard
    Route::middleware(['auth:sanctum', 'verified'])->get('/', [DashboardController::class, 'index'])->name('dashboard');
});`

Create a middleware class that looks something like this:
`<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Session;

class SetLocale
{
    public function handle($request, Closure $next)
    {
        $locale = $request->route('locale') ?: Session::get('locale');
        if ($locale) {
            \LaravelLocalization::setLocale($locale);

            /**
             * We need to store the locale in the session because we don't want to pass it to each component we create.
             * Also because we fetch the locale from the route but the url for the Livewire API endpoint only
             * contains the component name.
             */
            Session::put('locale', $locale);
        }

        return $next($request);
    }
}`

Register middleware:
`protected $middlewareGroups = [
      'web' => [
          ...
          \App\Http\Middleware\SetLocale::class,
       ],
       ...
]
`
