### ISSUE TITLE
Unable to upload file greater than 2mb

### ISSUE THREAD

**Issue by MUHAMMADSiyab** [livewire/livewire#7652]
### Discussed in https://github.com/livewire/livewire/discussions/7610

<div type='discussions-op-text'>

<sup>Originally posted by **MUHAMMADSiyab** December 26, 2023</sup>
When i try to upload a file lesser than or equal to 2 megabytes, everything goes smooth, but when uploading greater than 2mb, it gives validation error of:

`file failed to upload`

livewire version: ^3.0
laravel version: ^10.10
php version: 8.1

config/livewire.php

```
 'temporary_file_upload' => [
        'disk' => null,    
        'rules' => ['required', 'file', 'max:12288'],      
        'directory' => null,   // Example: 'tmp'                  
        'middleware' => null,  // Example: 'throttle:5,1'         
        'preview_mimes' => [  
            'png', 'gif', 'bmp', 'svg', 'wav', 'mp4',
            'mov', 'avi', 'wmv', 'mp3', 'm4a',
            'jpg', 'jpeg', 'mpga', 'webp', 'wma',
        ],
        'max_upload_time' => 5,
    ];
```

CreateStory.php:

```
#[Rule(['video' => 'mimetypes:video/mp4,video/webm|max:12288'])]
public $video = "";
```

create-story.blade.php:

```
 <input type="file" name="video" id="video" wire:model.lazy="video"           
                    class="hidden" accept="video/*">
```

Also updated the php.ini and increased to post_max_size and upload size to 100mb
</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
