### ISSUE TITLE
Select2 doesn't get re-enabled after submit

### ISSUE THREAD

**Issue by backstageel** [livewire/livewire#766]
**Describe the bug**
I have a form with a selct2 input on it, I followed this guide to make select2 work: https://laravel-livewire.com/docs/third-party-libraries/#select2. But when clicking submit on the form, after the submit is done, all inputs get re-enabled except the Select2 input. It remains disabled, so i can't work on the form again.

**To Reproduce**
1. Create a form with a Select2 input
2. Submit the form
3. Notice that all inputs will get re-enabled after the submit is done, except the select2

**Expected behavior**
The select2, which is disabled with all other inputs, should also be re-enabled after the submit is done.

**Screenshots**
![image](https://user-images.githubusercontent.com/1692858/77503207-bffcf600-6e65-11ea-9aa9-f72f2b5eb97a.png)

The first input is the Select2 that remained disabled.

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by zuziaio** [comment]
//on component after submit
`$this->emit('reloadform');`

// on blade.php
```
        window.livewire.on('reloadform', component => {
            $('#type').prop('disabled', false);
        })
```

**Comment by lancepioch** [comment]
@backstageel Let us know if that solution didn't work and we can take a closer look.

**Comment by ShekhSaifuddin007** [comment]
@lancepioch please take a look at this https://github.com/livewire/livewire/issues/1890#issue-728293308
