### ISSUE TITLE
No synthesizer when spatie/laravel-translatable field is updated

### ISSUE THREAD

**Issue by PrzemekMikulski** [livewire/livewire#7680]
### Discussed in https://github.com/livewire/livewire/discussions/7589

<div type='discussions-op-text'>

<sup>Originally posted by **PrzemekMikulski** December 21, 2023</sup>
### Livewire version

v3.3

### Laravel version

v10.0

### Which PHP version are you using?

PHP 8.2

### Steps To Reproduce

It looks like there is a bug when using spatie/laravel-translatable. 

Property binding works well but after updating translatable field  we are getting error: No synthesizer found for key: "test".
We are using legacy_model_binding.

You can check it in attached repo.

### Repository or Wirebox URL

https://github.com/PrzemekMikulski/livewire3bug

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
