### ISSUE TITLE
Turbolinks with deferred loading, flickering components

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#770]
**Describe the bug**
I am using defer loading to load 5 components on a page and show a loading spinner while they go off an make 5 separate requests to the db. When using turbolinks, instead of being displayed with the loading icon when you first visit the page, you get the cache data from the last request.

> **WITHOUT TURBOLINKS: Going to the page first time from an external site/type address into bar**
Note the first thing the user sees when the page loads is the loading icon, fresh data is then pulled in once calculated.

Starting screen:
![Screenshot 2020-03-26 at 13 09 44](https://user-images.githubusercontent.com/20134485/77650256-1ac84780-6f63-11ea-9c02-620eddd7d4de.png)

GIF:
![Kapture 2020-03-26 at 12 50 50](https://user-images.githubusercontent.com/20134485/77648841-b1473980-6f60-11ea-91b4-1049acdf6510.gif)

> **WITH TURBOLINKS: Visting the page by clicking on the site navigation**
Old data is the first thing the user sees. Then the loading icon appears a fraction later and acts the same as above from here on.

Starting screen:
![Screenshot 2020-03-26 at 13 08 41](https://user-images.githubusercontent.com/20134485/77650181-fe2c0f80-6f62-11ea-8bea-cc298d307dcb.png)

GIF:
![Kapture 2020-03-26 at 12 49 46](https://user-images.githubusercontent.com/20134485/77648918-d63bac80-6f60-11ea-975b-f9086231e4fa.gif)

**Expected behaviour**
I would expect the loading icon to be the first thing the user sees, with or without turbolinks.

**Comment by calebporzio** [comment]
Closing because this isn't a Livewire issue. That is how Turbolinks behaves. You can disable Turbolinks cache on specific pages if you want, but that's out of Livewire's scope.
