### ISSUE TITLE
Same listener on two components causing duplicate echo listener call

### ISSUE THREAD

**Issue by liran-co** [livewire/livewire#771]
I have two components on the same page that need to listen to the same echo channel (the listener array on each Livewire component have the same values). However, this seems to be causing the listener function to be called twice on each component. Is this not supported? or is this a bug?

**Comment by fahim152** [comment]
As far as I understand livewire, when you listening an event it will be recognized globally.  So you cannot put same event name on both components listener. Otherwise when you emit that event it will be listen by everywhere you try to listen. 

 You can have unique naming convention for your events for different components listeners.

**Comment by liran-co** [comment]
Got it, interesting. The only problem with using multiple channels for the same event is increasing our Pusher usage significantly (it would double it).

Why does the event get emitted globally instead of only to listeners on the component?

**Comment by fahim152** [comment]
> Got it, interesting. The only problem with using multiple channels for the same event is increasing our Pusher usage significantly (it would double it).
> 
> Any idea why the event gets emitted globally instead of only to listeners on the component?

I suppose to keep everything wired Events are registered globally so it gets called from anywhere.

**Comment by lancepioch** [comment]
The team is looking into solutions to event handling now. Feel free to recreate this issue as a new [Github Discussion](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this.

**Comment by bjuppa** [comment]
I just ran into the same issue when I have a page with multiple Livewire components that all listen to the same Echo event. 

I can see that each Livewire request for those components contain as many identical `fireEvent` entries in the `updates` array as the number of listening components.

It doesn't seem to be a problem with multiple components listening for the same regular Livewire event, only with Echo... I guess they're handled by different logic?

Would it make sense for the client-side js to filter out identical events before the request?

**Comment by bjuppa** [comment]
A quick workaround I just did is to have one component on the page that listens for the Echo event, and fires a Livewire event that the other components can listen for.

**Comment by sfong22** [comment]
Was this issue ever picked up in a discussion? I have used @bjuppa workaround with great success but would be interested in reading more on these bindings.
