### ISSUE TITLE
@this.get() does not work with nested array elements, @this.set() however does.....

### ISSUE THREAD

**Issue by ducopro** [livewire/livewire#773]
**Describe the bug**
``` html
    <div x-data="{
            setType(type) {
                console.log('Set modeltype', '{{$model_type}}',type);
                @this.set('{{$model_type}}', type);
                console.log( 'Get after set',@this.get('{{$model_type}}') );
            },
        }"
         x-init="init()"
         class="btn-group d-flex"
         role="group"
         aria-label="link selector">
```

See the above code, a little piece of alpine.js within a livewire component

**To Reproduce**

```javascript
                console.log('Set modeltype', '{{$model_type}}',type);
                @this.set('{{$model_type}}', type);
                console.log( 'Get after set',@this.get('{{$model_type}}') );
```
*When model_ type = 'test'*
Everything works as expected

*When model_ type = 'test.nested.element'*
@this.get() only returns undefined
@this.set() works as expected

**Expected behavior**

Hopefully....get() could work with nested elements also :-)

**Comment by calebporzio** [comment]
Good call. I just added dot-notation support here: https://github.com/livewire/livewire/pull/1151

Will be available in the next release.

Thanks.
