### ISSUE TITLE
Chart.js Dynamic Chart Implementation (with possible solution)

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#774]
Not a bug... but I spent ages trying to get this working. Would like to share my solution and hopefully get some feedback from some/other ideas.

**Chart Library**
I am using the ConsoleTVs Chart connector library, with Chart.js 
- https://github.com/ConsoleTVs/Charts
- https://www.chartjs.org/

Setup and general usage are exactly the same as in the docs.

```php
$chart = new Chart();
$chart->labels($labels);
$chart->dataset('Orders', 'line', $orders)->options("**OPTIONS**");
$chart->setDefaultOptions();
```

**LIvewire Setup**
From the component, we just return the chart
```php
public function render()
{
    return view('livewire.chart-panel', [
        'chart' => $this->chart()
    ]);
}
```
Within blade, we pretty much keep it standard to the docs too, but ensure to add the wire:ignore on the chart container.
```blade
<div wire:ignore>
  {!! $chart->container() !!}
</div>

@push('scripts')
  {!! $chart->script() !!}
@endpush
```

**Making it reactive**
Finally, the part that makes the graph reactive with livewire (and the bit I am least sure about as being the best way... but it works!) as follows:

Somewhere within your livewire component, grab the graph labels, datasets and chart options (if any change) and emit them after any updates.
```php
$this->emit('labelsUpdated', json_encode($labels));
$this->emit('datasetsUpdated', json_encode($datasets));
$this->emit('optionsUpdated', json_encode($chart->options));
```
Finally, within the blade file, catch these emits and update Chart.js manually via their developer API methods. Note: the `Chart.helpers.each` method assumes we do not know what the id of the graph is. You can actually get this from the ConsoleTV library I believe...

```blade
<script>
  Livewire.on('labelsUpdated', data => {
    Chart.helpers.each(Chart.instances, function (instance) {
      instance.chart.data.labels = JSON.parse(data);
      instance.chart.update();
    })
  })

  Livewire.on('datasetsUpdated', data => {
    var data = JSON.parse(data);
    Chart.helpers.each(Chart.instances, function (instance) {
      instance.chart.data.datasets.forEach((dataset, key) => {
        dataset.data = data[key];
      });
      instance.chart.update();
    })
  })

  Livewire.on('optionsUpdated', data => {
    var data = JSON.parse(data);
    Chart.helpers.each(Chart.instances, function (instance) {
      instance.chart.options = data;
      instance.chart.update();
    })
  })
</script>
```

**Comment by theomessin** [comment]
I'm trying to do the same thing. I have to say that this solution is very very icky :nauseated_face: Is there really no other way of doing this?

**Comment by booni3** [comment]
@theomessin Yeah it does not feel great. Would love to see if you can find a better way. I was going to dive into some of the chart.js vue packages and see how they do it when I had time. e.g. https://vue-chartjs.org/ 

The above is working for now though.

**Comment by gotroch** [comment]
Thanks a lot for sharing this solution. 

Where do you put the chart setup? _function mount()_?

$this->emit part goes to _function updated()_ of Livewire component?

**Comment by tarikhagustia** [comment]
yea, that's wired but looks good for me 😂 good idea @booni3

**Comment by Te7a-Houdini** [comment]
@booni3 i faced something like that

**Comment by gbuckingham89** [comment]
I’ve written up my approach which is based on @booni3 ’s method, but expanded it to only generate the Chart object on the first render, then on subsequent renders only emit an event if the data has actually changed. It also uses the chat ID as suggested. 

https://www.georgebuckingham.com/laravel-livewire-chart-js-realtime/

If you just want to see the code, I’ve added it to a Gist: https://gist.github.com/gbuckingham89/b3ff459eed67e53d7b8737e05cda13be

**Comment by booni3** [comment]
I haven't had a chance to try this, but also check out:

https://github.com/fidum/laravel-dashboard-chart-tile

**Comment by TrentDPT** [comment]
> I’ve written up my approach which is based on @booni3 ’s method, but expanded it to only generate the Chart object on the first render, then on subsequent renders only emit an event if the data has actually changed. It also uses the chart ID from the Laravel Charts library as suggested.
> 
> https://www.georgebuckingham.com/laravel-livewire-chart-js-realtime/
> 
> If you just want to see the code, I’ve added it to a Gist: https://gist.github.com/gbuckingham89/b3ff459eed67e53d7b8737e05cda13be

hey @gbuckingham89, in your tutorial i didnt see you talk about a model for WanSpeedTest that gets referenced in the livewire chartData() with a query.  Is that a specific model that needed to be added?

**Comment by egin10** [comment]
How to set event onClick when I use chartjs with type bar ?
Any advice? Thank's!

**Comment by egin10** [comment]
How to set event onClick when I use chartjs with type bar ?
Any advice? Thank's!

**Comment by Lootfi** [comment]
You could use polling for this but any screen resize and the canvas starts flashing which is't good, but I think that's a chromium issue. And it's overkill unless you know your dashboard is expecting constant updates.

I will look into how [laravel-dashboard-chart-tile](https://github.com/fidum/laravel-dashboard-chart-tile) implemented it.
