### ISSUE TITLE
SPA Mode: Livewire actions not working.

### ISSUE THREAD

**Issue by djoks** [livewire/livewire#776]
"laravel/framework": "^7.0"
"livewire/livewire": "^1.0"
"php": "^7.3.11"

So I started my livewire app by creating a controller to render the livewire component and a route that calls the index method of my controller.

Then I saw a much shorter cleaner way of doing it, I could just use the livewire route helper and point my route directly to my component.

This worked, the view was rendered however after I noticed that everything else didn't work. wire:click, wire:submit.prevent all were not working.

I checked my console for errors but there were none.
I check page source to make sure livewire styles and scripts were being injected and yes they were.

So I changed back to using a controller to call my view that rendered the livewire components and then my all the livewire actions started working again.

Just to be clear I am not using Turbolinks yet. This was all without turbolinks.

**Comment by jgodstime** [comment]
Have you added @livewireScripts  to your app.blade.php file?

I was having issues $emit the event, this fixed it 

I fixed it i put the livewirescript before the javascript tag that fixed it

@livewireScripts

<script>

  window.livewire.on('postAdded', postId => {

      alert('A post was added with the id of: ' + postId);

  })

</script>

**Comment by djoks** [comment]
Yes I have already included @livewireScripts in my parent layout file.

**Comment by jgodstime** [comment]
Am also using Laravel 7.0, its working on my end

**Comment by DanHarrin** [comment]
Hi, doesn't look like anyone else is facing this issue, so I'm going to close this due to lack of activity. If you can provide more information, such as a minimal, replicable code example to demonstrate your issue, then please open a new [Discussion](https://github.com/livewire/livewire/discussions). Thank you!

**Comment by ousid** [comment]
I have the same problem too.

**Comment by djoks** [comment]
Never resolved this issue unfortunately.  Maybe you can try with the new version of Livewire (v2.0.0) and see if it has been resolved.

**Comment by Abdelraman** [comment]
Having the same issue + wire:model no longer works when navigating between pages, although it works when I refresh the page, but if navigating to a component from another component wire model binding and actions stops working.

**Comment by uneekswatian** [comment]
I am facing the same issue.

**Comment by Abdelraman** [comment]
was able to fix it by installing turbolinks 
https://github.com/turbolinks/turbolinks#installation-using-npm
and include in app.js
var Turbolinks = require("turbolinks")
Turbolinks.start();

then added  turbolinks adaptor at the end of page
https://laravel-livewire.com/docs/2.x/upgrading#turbolinks

**Comment by jwwb681232** [comment]
> was able to fix it by installing turbolinks
> https://github.com/turbolinks/turbolinks#installation-using-npm
> and include in app.js
> var Turbolinks = require("turbolinks")
> Turbolinks.start();
> 
> then added turbolinks adaptor at the end of page
> https://laravel-livewire.com/docs/2.x/upgrading#turbolinks

Thank you very much, I have solved it according to your method

**Comment by seunsekoni** [comment]
> was able to fix it by installing turbolinks
> https://github.com/turbolinks/turbolinks#installation-using-npm
> and include in app.js
> var Turbolinks = require("turbolinks")
> Turbolinks.start();
> 
> then added turbolinks adaptor at the end of page
> https://laravel-livewire.com/docs/2.x/upgrading#turbolinks

This approach also worked for me too. I am using Laravel version 8.41.0 with Livewire version 2.0

**Comment by hafidid-baha** [comment]
### just a simple hack

it assume that using `@section('content') `inside the livewire component makes things missy
so instead of `@yeild('content')` try to check for the current route name inside the `app.blade.php` file
and render the requierd component
```blade.php
@if (Route::currentRouteName()=="home")
    <livewire:comments />
@elseif(Route::currentRouteName()=="login")
    <livewire:login />
@elseif(Route::currentRouteName()=="register")
    <livewire:register />
@endif
```
_Notes:_

> don't forget to remove @section inside livewire components
> i am still using turbolinks to render spa behavior

- laravel : 8.46.0
- livewire : 2.4.4
