### ISSUE TITLE
Array support for input types other than checkboxes

### ISSUE THREAD

**Issue by mokhosh** [livewire/livewire#781]
**Expected behavior**
PHP let's you make arrays with any set of inputs that have the same name, not just checkboxes. But Livewire add support only for checkboxes in 0.2.10 https://github.com/livewire/livewire/issues/173
Can we get this for other inputs going?

**Additional context**
Let's say we want to have a json column for "product properties" in an online shop application, where the admin can set arbitrary labels and values for their products, and we want to let him add and remove elements with an array of simple input elements.
That's not currently possible with Livewire.

**Comment by calebporzio** [comment]
No plans for this right now. Let's see if there is more demand. Thanks!
