### ISSUE TITLE
Ajax calls firing, but view not changing when inputs are wired

### ISSUE THREAD

**Issue by colinmac17** [livewire/livewire#782]
**Describe the bug**
I have been following the data tables tutorial from laracasts (https://laracasts.com/series/guest-spotlight/episodes/3) and everything was working great, until I started trying to bind input to my Livewire component.

`<?php

namespace App\Http\Livewire;

use App\College;
use Livewire\Component;
use Livewire\WithPagination;

class CollegeSearch extends Component
{
    use WithPagination;

    public $perPage = 10;
    public $sortField = 'name';
    public $sortAsc = true;
    public $search = '';

    public function sortBy($field)
    {
        if($this->sortField === $field){
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function render()
    {
        return view('livewire.college-search', [
            'colleges' => College::where('name', 'LIKE', "%$this->search%")
                ->orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc')
                ->paginate($this->perPage),
        ]);
    }
}`

I have this in my college-search.blade.php filed
`<input type="text" wire:model="search">`

Livewire version: v1.0.10
Laravel version: 7.3.0

I am seeing the following error in Sentry:
- `TypeError: Cannot read property 'data' of null
  at new Component (/livewire/livewire.js:1:41209)
  at None (/livewire/livewire.js:1:123830)
  at Array.forEach (<anonymous>)
  at Livewire.value (/livewire/livewire.js:1:123778)
  at HTMLDocument.<anonymous> (/colleges/search:617:25)`

**To Reproduce**
1. I try to search in the above input
2. I check the network tab and see events firing, but nothing happening in the frontend
3. I see a `?` get added to the query string but nothing else (not sure if related)

**Expected behavior**
- When the input changes, my search query should fire and the paginated results should change

**Screenshots**
Watch this quick video of the issue:
https://www.loom.com/share/ab8ebadeff1d46309e4d1e377c59eb7b

**Desktop (please complete the following information):**
 - Crhome

**Additional context**

**Comment by colinmac17** [comment]
I found the issue: "Make sure your Blade view only has ONE root element."

:) Glad I found it before anyone had to waste time looking into it.

I'm gonna keep saying this - thanks so much for Livewire! This is simply awesome.

**Comment by nuernbergerA** [comment]
@redgluten You can open a feature request in a new issue
