### ISSUE TITLE
Problem running Livewire with fully qualified classses

### ISSUE THREAD

**Issue by colinhall17** [livewire/livewire#783]
I am creating a new package and decided to give Livewire a spin.  I came across an issue when using fully qualified name spaced components in a package.

As per the documentation site I created a component and used the blade directive like so

@livewire(Package\Livewire\Foo::class)

The initial page load works absolutely fine but any interactions with any Livewire action returns a 404 because it is sending a POST request to the following URL

https://domain.com/livewire/message/Package/Livewire/Foo

Which doesn't match to the route defined of 

https://domain.com/livewire/message/{name}

I could of course amend the config to point to the package Livewire components but didn't want to do this as the package could be added to an application already using Livewire

**Steps to Reproduce**
Create a package
Add Livewire
Create a component in Package\Livewire\Component
Add the Blade Directive in a view @livewire(Package\Livewire\Component)
Add some interaction and hit the action

**Expected behavior**
I would expect Livewire to return the component and update the DOM

**Desktop (please complete the following information):**
OS Windows 10 - Browser Firefox Developer Edition

**Comment by ninthspace** [comment]
I'm using FQNs too, primarily so I can include Livewire components dynamically. This problem doesn't happen on v1.0.9, but does on v1.0.10 or v1.0.11.

I suspect this change introduced the issue: https://github.com/livewire/livewire/pull/683

**Comment by colinhall17** [comment]
I'm thinking a

**Comment by theomessin** [comment]
Can confirm this just broke a bunch of stuff for us as well. @calebporzio this is a breaking change in a patch (that's been left like this two patches later). Can we please sort this out?

**Comment by godler** [comment]
You can make Livewire::component('component', Package/Http/Livewire/File::class) in any sevice provider. This method is avalible in livewire/src/LivewireManager.php. I don't know if it's proper way but it works fo me.

**Comment by colinhall17** [comment]
Thanks, will give it a try.

**Comment by calebporzio** [comment]
Ugh, sorry about this. I reverted the change in the latest release.

**Comment by calebporzio** [comment]
Note: @nuernbergerA

**Comment by calebporzio** [comment]
Please confirm everything is back to normal

**Comment by colinhall17** [comment]
@calebporzio Thanks, it now stops the 404, but I received a different error stating it cant find a folder in app\Http\Livewire\Class because ts in a package it doesnt have that folder.

So I got around that by using 

Livewire::component('component', Package\Http\Livewie\File::class)

But I'm now having issues between livewire and alpine. I think its because livewire is returning the component with the alpine code in it. And sometimes the returned component removes an element that had alpine code so alpine throws an error as a variable that was there is no longer there.

**Comment by calebporzio** [comment]
Hey there, glad it's fixed. Please open a separate issue with more details for the alpine thing
