### ISSUE TITLE
Livewire V3 not working with laravel MIX

### ISSUE THREAD

**Issue by iislamtaleb** [livewire/livewire#7853]
### Discussed in https://github.com/livewire/livewire/discussions/7848

<div type='discussions-op-text'>

<sup>Originally posted by **iislamtaleb** January 30, 2024</sup>
I am working on a project and needed to install the Mix plugin alongside Vite. However, I encountered an issue when creating new Livewire components after installing Laravel Mix, Livewire didn't work</div>
after that I have removed Mix and Install Vite again and I come to this issue

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147

**Comment by iislamtaleb** [comment]
![Capture d'écran 2024-01-30 224317](https://github.com/livewire/livewire/assets/148808316/5e366bb9-52f3-405a-a026-c80ee8598119)
![Capture d'écran 2024-01-30 224344](https://github.com/livewire/livewire/assets/148808316/bce204eb-da88-4942-aef0-49897f9233e2)
![Capture d'écran 2024-01-30 224402](https://github.com/livewire/livewire/assets/148808316/d0dc327d-c5b1-4938-8448-881c5678bd31)
