### ISSUE TITLE
AlpineJS Integration Does Not Work

### ISSUE THREAD

**Issue by djoks** [livewire/livewire#786]
"laravel/framework": "^7.0"
"livewire/livewire": "^1.0"
"php": "^7.3.11"

I just tried to use the alpinejs directives but nothing works.  No errors, I followed the docs and it says alpinejs comes with livewire out of the box.

None, absolutely done of the alpinejs directives work in my livewire components, no errors in my console either.

Eg.

```
<div x-data="{ open: false }">
    <button x-on:click="open = true">Edit Record</button>
    <div x-show="open">
        <div class="modal fixed w-full h-full top-0 left-0 flex items-center justify-center">
            <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"
                 x-on:click="open = false"></div>
            <div
                class="modal-container bg-white w-5/6 md:max-w-2xl mx-auto rounded shadow-lg z-50 overflow-y-auto cursor-auto">
                <div
                    class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
                </div>

                <div class="modal-content py-4 text-left px-6">

                    <!--Body-->
               
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by ducopro** [comment]
Maybe a stupid question but....

Did you install alpinejs following the instructions here?
https://github.com/alpinejs/alpine

**Comment by devcircus** [comment]
I believe it's the "out-of-the-box" wording in the docs that's tripping some people up. You still have to install alpine.

**Comment by djoks** [comment]
Yes, I assumed after reading the docs that alpinejs was already a part of livewire.  Guess they need to change the wording there a bit and make it less confusing. Thanks!

**Comment by devcircus** [comment]
yeah when I said "some people" I meant me. I fought with it for 30 minutes before I checked installed packages.
