### ISSUE TITLE
Apply middleware on form submit

### ISSUE THREAD

**Issue by pakogn** [livewire/livewire#787]
It would be great to apply the middlewares when executing a form submission, for example is really useful to sanitize strings like applying.

TrimStrings
ConvertEmptyStringsToNull

or what could be a good solution so when using forms with Livewire the strings still uniform?

**Comment by xxdalexx** [comment]
https://forum.laravel-livewire.com/t/preferred-way-to-trim-input/304

**Comment by m-a-k-o** [comment]
@pakogn Add ```\App\Http\Middleware\TrimStrings::class``` to web middleware group and inputs will be trimmed. 

Example:
```
'web' => [
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
    \Illuminate\Session\Middleware\StartSession::class,
    \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    \App\Http\Middleware\VerifyCsrfToken::class,
    \Illuminate\Routing\Middleware\SubstituteBindings::class,
    \App\Http\Middleware\TrimStrings::class,
],
```

Livewire is assigned to web middleware group.

![image](https://user-images.githubusercontent.com/6873535/78571606-ac1ea000-7826-11ea-844b-6bf569045f43.png)

**Comment by pakogn** [comment]
> @pakogn Add `\App\Http\Middleware\TrimStrings::class` to web middleware group and inputs will be trimmed.
> 
> Example:
> 
> ```
> 'web' => [
>     \App\Http\Middleware\EncryptCookies::class,
>     \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
>     \Illuminate\Session\Middleware\StartSession::class,
>     \Illuminate\View\Middleware\ShareErrorsFromSession::class,
>     \App\Http\Middleware\VerifyCsrfToken::class,
>     \Illuminate\Routing\Middleware\SubstituteBindings::class,
>     \App\Http\Middleware\TrimStrings::class,
> ],
> ```
> 
> Livewire is assigned to web middleware group.
> 
> ![image](https://user-images.githubusercontent.com/6873535/78571606-ac1ea000-7826-11ea-844b-6bf569045f43.png)

Yes, my fault, as I see the safe way to use the Request may be the mount method so it's a no sense what I'm saying since when submitting a form We are commonly using properties binded with the UI and not catching the request in some method. So it's our responsibility to sanitize our binded properties before touching the database.
