### ISSUE TITLE
Pagination not working with custom view

### ISSUE THREAD

**Issue by ndijkstra** [livewire/livewire#792]
**Describe the bug**
When I specify a custom view via the links() method or override the paginationView() method, Livewire doesn't replace the links.
**Additional context**
I'm using an own pagination view with tailwindui

**Comment by daikazu** [comment]
@ndijkstra  Without seeing your code I'm just making the assumption that you do not have the proper `wire:click="gotoPage({{ $page }})"`, `wire:click="previousPage"`,  and `wire:click="nextPage"` in your custom pagination blade template. 

Checkout Livewire's default [pagination view file](https://github.com/livewire/livewire/blob/master/src/views/pagination-links.blade.php) for an example. 

I was dealing with the same issue. Hope this helps.

**Comment by ndijkstra** [comment]
Thanks!
