### ISSUE TITLE
Livewire Test hydrates an integer to string (using BenSampo\Enum)

### ISSUE THREAD

**Issue by basepack** [livewire/livewire#793]
**Describe the bug**

I got an error while writing a test for a Livewire component: `BenSampo\Enum\Exceptions\InvalidEnumMemberException : Cannot construct an instance of PriceType using the value (string) `0`. Possible values are [0, 1]`

Turns out, Livewire hydrates the (int) 0 to a (string) "0" at some point when running a test.

**In the browser, the component behaves as expected.**

Given this setup:

**Enum PriceType.php**
```
<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class PriceType extends Enum
{
    const OptionOne =   0;
    const OptionTwo =   1;
    const OptionThree = 2;
}
```

**Model Product.php**
```
<?php

namespace App;

use BenSampo\Enum\Traits\CastsEnums;
use App\Enums\PriceType;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use CastsEnums;

    protected $enumCasts = [
        'price_type' => PriceType::class
    ];
}
```

**Livewire Component TestProduct.php**
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class TestProduct extends Component
{

    /** @var Product $product */
    public $product;

    public function mount( $product )
    {
        $this->product = $product;
        dump($this->product->price_type); // <--- Correct Pricetype dumped
    }

    public function hydrate()
    {
        dump($this->product->price_type); // <--- Error InvalidEnumMemberException '0'
    }

    public function addToCart(){
        //
    }

    public function render()
    {
        return view('livewire.test-product');
    }
}
```

**Migration create_products_table**
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProductsTable extends Migration
{

    public function up()
    {
        Schema::create( 'products', function ( Blueprint $table ) {
            $table->bigIncrements( 'id' );
            $table->tinyInteger( 'price_type' )->unsigned()->default( \App\Enums\PriceType::OptionOne() );
            $table->timestamps();
        } );
    }

    public function down()
    {
        Schema::dropIfExists( 'products' );
    }
}
```

**To Reproduce**
1. Run:
   - artisan make:enum PriceType
   - artisan make:model Product
   - artisan make:migration create_products_table
   - artisan make:livewire test-product
2. Run the test:
```
     /** @test */
    public function livewire_reproduce_error()
    {
        $product             = new Product;
        $product->price_type = PriceType::OptionOne();
        $product->save();

        Livewire::test( \App\Http\Livewire\TestProduct::class, [ 'product' => $product ] )
                ->call( 'addToCart' );
    }
```

3. Check the results
    - See the PriceType correctly shown in the `mount()` method. At this stage the $product->price_type = **0 (integer)** so `CastsEnums` can convert that to a PriceType Enum.
    - Then see it failing in the `hydrate()` method  at comment `// <--- Error InvalidEnumMemberException '0'`
At this stage the $product->price_type = **"0" (string)** so `CastsEnums` cannot use that and gives the error.

**Expected behavior**
I expect Livewire to hydrate an integer to (int) 0 instead of a (string) "0"

**Additional context**
Livewire and Laravel latest, PHP 7.4

**Comment by nuernbergerA** [comment]
Hi @basepack

What's the output from
```php
/** @test */
public function livewire_reproduce_error()
{
    $product             = new Product;
    $product->price_type = PriceType::OptionOne();
    $product->save();

    dd(json_decode(json_encode([ 'product' => $product ]), true));

    Livewire::test( \App\Http\Livewire\TestProduct::class, [ 'product' => $product ] )
        ->call( 'addToCart' );
}
```

**Comment by basepack** [comment]
@nuernbergerA I am back on the project, and here you go:

```
array:1 [
  "product" => array:4 [
    "price_type" => 0
    "updated_at" => "2020-04-27T14:13:10.000000Z"
    "created_at" => "2020-04-27T14:13:10.000000Z"
    "id" => 1
  ]
]
```

**Comment by nuernbergerA** [comment]
I assume it's js related

**Comment by basepack** [comment]
For now I fixed it to have  a default Laravel casting:
```
 public $casts = [
        'price_type'                        => 'integer',
];
```
Besides the EnumCasts of BenShampoo's package:
```
    protected $enumCasts = [
        'price_type' => PriceType::class
    ];
```

**Comment by mattharcourt** [comment]
This appears to be an issue with PDO returning a string value when Laravel fetches the model during the Livewire hydration.

See this Laravel [issue](https://github.com/laravel/framework/issues/3548#issuecomment-34982457). It and other searches point to Laravel's attribute casting (`protected $casts`) as the solution.

**Comment by basepack** [comment]
@mattharcourt I understand that this is related. However in this case, the casting goes correct everywhere in the code without `protected $casts` on the model. 

That line in my test proves it: `dd(json_decode(json_encode([ 'product' => $product ]), true));` results in:.

```
array:1 [
  "product" => array:4 [
    "price_type" => 0
    "updated_at" => "2020-04-27T14:13:10.000000Z"
    "created_at" => "2020-04-27T14:13:10.000000Z"
    "id" => 1
  ]
]
```

**Comment by nuernbergerA** [comment]
What happens if you fetch `product` from the DB?

```php
    dd(json_decode(json_encode([ 'product' => Product::first()]), true));
```

**Comment by basepack** [comment]
@nuernbergerA then indeed `"price_type" => "0"`!
