### ISSUE TITLE
Livewire javascript assets are not compiled

### ISSUE THREAD

**Issue by aliraza93** [livewire/livewire#794]
**Describe the bug**
I'm trying to use livewire on laravel 7 and ehen I add @livewireScripts in my blade directive, I get the following error:
livewire.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):51 Uncaught ReferenceError: Livewire is not defined  at (index):51

**Screenshots**
![1](https://user-images.githubusercontent.com/55763702/78655565-a3d66b80-78df-11ea-9a4a-c9ad965115fb.png)

And here's my code
![Untitled1](https://user-images.githubusercontent.com/55763702/78655745-dd0edb80-78df-11ea-9f74-4f8a6354cdba.png)

**Expected behavior**
It should compile the assets and I want to use livewire to get data from an api and serach that data accordingly
![1](https://user-images.githubusercontent.com/55763702/78655815-f0ba4200-78df-11ea-8785-5fd424e2431a.png)

**Comment by calebporzio** [comment]
Is your app on a non-normal root URL? Like `https://movie-app.com/app` or something?

**Comment by Sukaelan** [comment]
![Screen Shot 2020-05-02 at 4 30 08 PM](https://user-images.githubusercontent.com/28072396/80895303-91e4be80-8d0d-11ea-91cd-e125fb1c9151.png)

I get the same problem
Laravel 7
livewire v 1.0.14

**Comment by kenean-50** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/33159311/81965728-29f17a80-9621-11ea-912c-a82079c6ea8a.png)
 
I have the same problem with Laravel 7

**Comment by RicardoRamirezR** [comment]
I worked very well on my dev machine. Today I pushed my app to production and I got the same issue.

**Comment by kenean-50** [comment]
this fixed it for me

publish the livewire config to laravel config dir
`php artisan vendor:publish --tag=livewire:config`

and change the `asset_url` value in the config/livewire to the root or public dir of your app. Eg. `http://your-app/public`

**Comment by nuernbergerA** [comment]
Hey @aliraza93, does [this](https://github.com/livewire/livewire/issues/794#issuecomment-633703261) fix your problem?

**Comment by calebporzio** [comment]
@kenean-50 - Did you have to set `asset_url` to `http://your-app/public`? Why would public not be the root?

If for some reason your app isn't configured for `public` to be the root, these problems will happen and you'll have to use the asset_url setting to set a proper asset prefix.

I'm going to close this for now as it seems like a fixable edge-case problem for people with apps with odd URL configurations.

If anyone feels like I've missed something, re-submit with a reproducible issue.

**Comment by Yao228** [comment]
> this fixed it for me
> 
> publish the livewire config to laravel config dir
> `php artisan vendor:publish --tag=livewire:config`
> 
> and change the `asset_url` value in the config/livewire to the root or public dir of your app. Eg. `http://your-app/public`

Good for me

**Comment by Iversonweb** [comment]
> Here is my solution
> 
> First: Go to composer.json and add this line `@php artisan vendor:publish --force --tag=livewire-assets --ansi`
> ![image](https://user-images.githubusercontent.com/68370102/90951148-430c9180-e482-11ea-91b0-4ddf17ec78fa.png)
> 
> Second: run this command on terminal (or anything kind of this) `php artisan vendor:publish --tag=livewire:config`
> 
> Finally: change the `asset_url` value in the **config/livewire** to the root or public dir of your app. Eg. `http://your-app/public`
> ![image](https://user-images.githubusercontent.com/68370102/90951168-8404a600-e482-11ea-9502-277570dc571a.png)
> 
> Here is my Result:
> 
> ### **Before**:
> ![image](https://user-images.githubusercontent.com/68370102/90951189-b7473500-e482-11ea-92d7-59b0d7065040.png)
> ![image](https://user-images.githubusercontent.com/68370102/90951195-caf29b80-e482-11ea-9258-f5310f051817.png)
> 
> ### **After**:
> ![image](https://user-images.githubusercontent.com/68370102/90951203-e493e300-e482-11ea-9c17-72d6c01de769.png)
> ![image](https://user-images.githubusercontent.com/68370102/90951208-f1b0d200-e482-11ea-8754-ee38946c70fa.png)
> 
> Goodluck!

Please i did all of this but it affected my composer.json

**Comment by gearias** [comment]
I solved this problem changing "@livewireScripts" to "@livewireScript".

**Comment by aichasalhi** [comment]
i have same problem and i tried all solutions but any thing changes 

> I worked very well on my dev machine. Today I pushed my app to production and I got the same issue.

same for me any ideas to resolve it ???
