### ISSUE TITLE
`wire:model` doesnt allow for dot notation with an Eloquent model

### ISSUE THREAD

**Issue by paulrose** [livewire/livewire#795]
**Describe the bug**
`wire:model` doesnt allow for dot notation with an Eloquent model.

When trying to use `wire:model` with dot notation to access the models properties, nothing is returned. For example: `wire.model="post.title"` will not work. Feels janky to have to define each property you want to edit?

**To Reproduce**
1. Create a Laravel Model
2. Pass into your `mount()` and bind to a public prop
3. Attempt to use dot notation

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Chrome

**Additional context**
Dot notation works fine with arrays, just not Models

Maybe I'm going crazy here....but having to set each prop of your model seems a bit backward?

**Comment by calebporzio** [comment]
Hey @paulrose, for now, this is the desired behavior.

It's been talked about before, but right now I want to keep things explicit for security reasons.
