### ISSUE TITLE
Action 404 Not Found

### ISSUE THREAD

**Issue by Wulfheart** [livewire/livewire#796]
https://gist.github.com/Wulfheart/ac03ac8bae6c38cbc1e9fb3ac9eb4c1b

**Describe the bug**
Every action makes a 404 Error. I narrowed it down to an assignment in my Component Controller. It seems to be an object. 
`$this->documentation = $documentation;`

**To Reproduce**
For your convenience: I created a temporary github project from where you can clone it. Please note that I was forced to remove some names and relationships. But it should work fine except the bug. ;-)
Use these files in your laravel project:
https://gist.github.com/Wulfheart/ac03ac8bae6c38cbc1e9fb3ac9eb4c1b
Alternatively there is a minimalized repo at https://github.com/Wulfheart/dc_show.

**Expected behavior**
I'd like to see a message in my log files.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/25671390/78790489-e1ee9080-79ae-11ea-8906-7c87cb234a59.png)

**Desktop (please complete the following information):**
 - Browser Firefox

**Additional context**

The documentation model. Nothing really fancy.
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Documentation extends Model
{
    protected $fillable = ['customer_id', 'order'];

    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    }
}
```

**Comment by ManojKiranA** [comment]
if you are setting a Model as public property livewire is trying to hydrates all public props on every request so if the models not exists on DB its will show the `ModelNotFoundException`  so for now you can set those as protected property.

So here is fix for now

1. You can set that model property as private or protected
2.You can pass an actual model into livewire (Model::query()->inRandomOrder()->first())

**Comment by damcclean** [comment]
I'm also experiencing the same issue. I've created a Livewire component for a grid of items that I loop through. And in each of those items, I have update and destroy buttons which I want to hit my Livewire component's class, but it just returns a 404 error.

Here's the code I have for my blade component:

```
<button wire:click="update({{ $article->id }})">
  <img class="w-4 mx-1" src="/static/images/refresh.svg" alt="Regenerate article audio"/>
</button>

<button wire:click="destroy({{ $article->id }})">
  <img class="w-4 mx-1" src="/static/images/bin.svg" alt="Delete the article"/>
</button>
```

And here's what I'm doing in my component class...

```php
<?php

namespace App\Http\Livewire;

use App\Article;
use Livewire\Component;

class ArticleGrid extends Component
{
    public function render()
    {
        return view('livewire.article-grid', [
            'articles' => auth()->user()->articles->sortByDesc('updated_at'),
        ]);
    }

    public function update(Article $article)
    {
        // do something
    }

    public function destroy(Article $article)
    {
        // do something
    }
}
```

**Comment by GertjanRoke** [comment]
I question if this is supported, reading through the docs it says nothing about dependency injecting models on actions.

So for now you need to do it like this.
```php
public function update($id)
{
    $article = Article::findOrFail($id);
    ....
}
```

**Comment by damcclean** [comment]
> I question if this is supported, reading through the docs it says nothing about dependency injecting models on actions.
> 
> So for now you need to do it like this.
> 
> ```
> public function update($id)
> {
>     $article = Article::findOrFail($id);
>     ....
> }
> ```

Oh thanks, that fixed it. Must have just presumed it would work.

Sorry @Wulfheart for disturbing the thread.

**Comment by Wulfheart** [comment]
> I question if this is supported, reading through the docs it says nothing about dependency injecting models on actions.
> 
> So for now you need to do it like this.
> ```php
> public function update($id)
> {
>     $article = Article::findOrFail($id);
>     ....
> }
> ```

That's the workaround I figured out too. Unfortunately this adds some overhead to the application as there has to be a Database Call every reload.🤷‍♂️

**Comment by GertjanRoke** [comment]
I understand this is also something I struggled with when I started using Livewire.  
But think about it, it's not that different from when you do it with a javascript framework like Vue, it also needs to hit a JSON API that then also needs to fetch the record again from the database to do some actions after it.

I don't know if you're doing just a database update in that method because then you could do something like this:
```php
public function update($id)
{
    Article::where('id', $id)->update(['column' => 'new value']);
}
```

**Comment by emmanuel-nike** [comment]
I have exactly thesame issue,
Test.php 
`<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $sel;

    public function mount()
    {
        $this->sel = "Old Plan";
    }

    public function doSomething()
    {
        $this->sel = "hello world";
    }

    public function render()
    {
        return view('livewire.test');
    }
}
`
livewire.test.blade.php
`<div>
    {{ $sel }}
    <input wire:model="sel" type="text">
                        <button wire:click="$set('sel', 'Hello World')" class="btn btn-sm btn-primary"><i
                                class="fa fa-pencil-alt"></i></button>

</div>`

when the button is clicked or the input is edited I get a 404 popup error.

**Comment by emmanuel-nike** [comment]
> I have exactly thesame issue,
> Test.php
> 
> ```
> <?php
> 
> namespace App\Http\Livewire;
> 
> use Livewire\Component;
> 
> class Test extends Component
> {
>     public $sel;
> 
>     public function mount()
>     {
>         $this->sel = "Old Plan";
>     }
> 
>     public function doSomething()
>     {
>         $this->sel = "hello world";
>     }
> 
>     public function render()
>     {
>         return view('livewire.test');
>     }
> }
> ```
> 
> livewire.test.blade.php
> 
> ```
> <div>
>     {{ $sel }}
>     <input wire:model="sel" type="text">
>                         <button wire:click="$set('sel', 'Hello World')" class="btn btn-sm btn-primary"><i
>                                 class="fa fa-pencil-alt"></i></button>
> </div>
> ```
> 
> when the button is clicked or the input is edited I get a 404 popup error.

Sorry it was My Mistake, was at this for hours, The issue was wrong Apache config

**Comment by calebporzio** [comment]
We will be adding model dependency injection in the next major version. Currently, it isn't supported. Thanks!
