### ISSUE TITLE
select don't selected options use set value by function not by user

### ISSUE THREAD

**Issue by salahhusa9** [livewire/livewire#8027]
### Discussed in https://github.com/livewire/livewire/discussions/8026

<div type='discussions-op-text'>

<sup>Originally posted by **salahhusa9** February 26, 2024</sup>
I create a select `<select wire:model.live="selectedLiveBouquets">` , i have a btn with wire:click for selectAll options (it's multiple select) by call selectAll and set values in $selectedLiveBouquets, i print in view i see values of $selectedLiveBouquets but he don't selected (it's work in livewire 2)</div>

**Comment by PhiloNL** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
