### ISSUE TITLE
using vanilla javascript in input has wire:model Inaccessible after page updated?

### ISSUE THREAD

**Issue by mahdavi95** [livewire/livewire#805]
I coding and loving livewire more and more because i am Backend developer and don't like frontend distract me !
but i have issue when using vanilla js in some cases.

I using vanilla js on some inputs like textarea or select input for change behavior (such as use plugins like quill or trumbowyg in textarea or select2 in select inputs) and there is no problem in the first load, but after the first update, all JavaScripts fail. and not responding ...

how to fix that ?

**Comment by lancepioch** [comment]
I believe this has been resolved in the latest version. If it hasn't, can you post a small snippet that demonstrates it so we can take a closer look?
