### ISSUE TITLE
Translation inside Component does not work

### ISSUE THREAD

**Issue by MrWeb** [livewire/livewire#806]
I have a component with the function `showConfirm()` this sets a public property `msg` taking it from a i18n file (`resources/lang/{selected_lang}.json`) the translation does not work and I always get the default language (Italian).

I selected a second language (English) and the whole app translates fine, when I fire the `showConfirm()` action the text is in Italian while it should be in English:

`app/Http/Livewire/Confirm.php`
```
 public $btn_cancel;

 public function showConfirm($confirm)
 {
     $this->confirm = $confirm;
     $this->btn_confirm =  __('Confermo');
 }
```

`resources/views/livewire/bits/confirm.blade.php`
```
...
<button type="confirm" class="btn btn-block btn-primary">{{$btn_confirm}}</button>
...
```

`resources/lang/en.json`
```
...
"Confermo" : "Confirm"
...
```

If I place `{{__('Confermo')}}` in a blade file I do get the correct translation.
If I `dd(app()->getLocale())` in Livewire (just at the beginning of `showConfirm()` it returns 'it' while in any other blade file it returns the selected language.

I have a middleware which sets/retrieves the language and is the first middleware encapsulating everything else:

`routes/web.php`

```
Route::group(['middleware' => ['lang']], function () {

    Auth::routes();

    Route::get('/', function () {
        return redirect('/dashboard');
    });

    Route::group(['middleware' => ['auth']], function () {
    ...
    });

});
```

**Comment by GertjanRoke** [comment]
Hello @MrWeb, I added this comment a couple of days ago on an similar issue. Maybe this could save your day as well.

https://github.com/livewire/livewire/issues/765#issuecomment-612671273

**Comment by calebporzio** [comment]
We're going to try to fix localization soon with Livewire subsequent requests. I'm going to close this in favor of isolating the maintenance to issue #765 - Thanks!
