### ISSUE TITLE
callTraitHook with optional route parameter

### ISSUE THREAD

**Issue by jals-es** [livewire/livewire#8060]
### Discussed in https://github.com/livewire/livewire/discussions/7914

<div type='discussions-op-text'>

<sup>Originally posted by **DJBellis** February  8, 2024</sup>
### Livewire version

v3.4.4

### Laravel version

v10.43.0

### Which PHP version are you using?

PHP 8.1

### Steps To Reproduce

Make a component with `php artisan livewire:make TestComponent`
Make a route that has an optional parameter after a required parameter
```
use App\Livewire\TestComponent;
Route::get('test/component/{required}/{optional?}', TestComponent::class);
```

Add in a trait that has a mount hook

```
<?php

namespace App\Traits;

trait TestTrait
{
    public function mountTestTrait()
    {
    }
}
```

Update the component to use the trait and bind route values via a mount method

```
<?php

namespace App\Livewire;

use App\Traits\TestTrait;
use Illuminate\Support\View;
use Livewire\Component;

class TestComponent extends Component
{
    use TestTrait;
    public $required;
    public $optional;

    public function mount(string $required, ?string $optional = null): void
    {
    }

    public function render(): View
    {
        return view('livewire.test-component');
    }
}
```

Navigate to the route without the optional parameter `{local url}/test/component/required/`

The resulting error is:

```
Cannot use positional argument after named argument during unpacking
```

Which is thrown in 
https://github.com/livewire/livewire/blob/cc164742e74191213db6bee86b04ac9833302d01/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php#L129

When the trait mount method is called.  This seems to be because
[src/Drawer/ImplicitRouteBinding.php](https://github.com/livewire/livewire/blob/main/src/Drawer/ImplicitRouteBinding.php)

Resolves the default mount parameter required in it's 'named' "required" => {route value} and then the optional variable as a positional 0 => {default value}

From my `dd($params)` before the `wrap($this->component)->$method(...$params);`
```
array:2 [▼ // vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php:135
  "required" => "required"
  0 => null
]
```

So when the values are spread by https://github.com/livewire/livewire/blob/cc164742e74191213db6bee86b04ac9833302d01/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php#L135

The php error is thrown, because there's a named argument before an optional argument

### Repository or Wirebox URL

https://github.com/DJBellis/traitmountissue

### Additional information

Edited for clarity

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by jals-es** [comment]
Please, some feedback of this? It's a big issue for 3 weeks there is still no response.

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
