### ISSUE TITLE
Content from @yield inside a Livewire view disappears from dom response

### ISSUE THREAD

**Issue by lasseeee** [livewire/livewire#807]
**Describe the bug**
Content from `@yield('some-view)` inside a Livewire view disappears when the dom is returned via Livewire.

**To Reproduce**
1. Include a @yield inside the view.
2. Make Livewire reload the dom.

**Expected behavior**
The content inside the `@yield('some-view')`should show up as normally after the dom is returned via Livewire.

**Desktop (please complete the following information):**
 - Firefox v75.0
 - Livewire v1.0.12
 - Laravel v7.5.1

**Comment by calebporzio** [comment]
Closing this. Please re-submit with stripped down, copy and pastable, sample components.

**Comment by dhanyn10** [comment]
same issue with similar steps, im calling the layout with
```php
@extends('components.layout')
@section('content')
...
{{$blogs->links()}}
...
@endsection
```
and load the page with livewire.
```php
use Livewire\WithPagination;
class Blogs extends Component
{
use WithPagination;
public function render()
    {
        $data = BlogsModel::where('status', 'published')->get();
         return view('livewire.blogs',[
            'blogs' => $data
        ]);
    }
}
```

**Comment by dhanyn10** [comment]
@calebporzio

**Comment by joshhanley** [comment]
@dhanyn10 you shouldn't use `@extends` or `@section` within your component view, as Livewire controls the layout for you. Instead you should use the `view(...)->extends()` method in your render method.

Hope this helps!
