### ISSUE TITLE
Select Option state change

### ISSUE THREAD

**Issue by sadiqumar18** [livewire/livewire#808]
**select option state change**
i am currently having issue with two select option on my form, the first one fetches some services from an api and populate an array property in my component,
the second one is base on the first select option, it shows the list of plans after a user has selected the option above.

**Component Code**
```html
<div>
    <div class="auth-content">
                <div class="mb-4" >
                    <div class="row">
                    <div class="col-lg-4 col-xl-4 mt-3"></div>
                        <div class="col-lg-4 col-xl-4 mt-3 card">
                            <div class="p-5">
                                <div class="auth-logo text-center mb-4 ">
                                    <img class="rounded-circle" src="{{asset('assets/images/products/tv.jpg')}}" alt="">
                                </div>
                                <h1 class="mb-3 text-18"></h1>
                                <form wire:submit.prevent="pay">
                                 
                                    <div class="form-group">
                                        <label for="card">Card Number</label>
                                        <input wire:model="card" type="number"
                                            class="form-control form-control-rounded @error('card') is-invalid @enderror"
                                               autocomplete=""
                                            autofocus>
                                        @error('card')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="brand">Brand</label>
                                       
                                       <select id="brand" wire:model="brand" wire:change="getBrandPlans"  class="form-control @error('brand') is-invalid @enderror" id="exampleFormControlSelect1">
                                        <option value="">select brand</option>
                                        <@foreach ($brands as $brand)
                                        <option value="{{$brand}}">{{$brand}}</option>
                                        @endforeach
                                        </select>
                                        @error('brand')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="plans">Plans</label>
                                       <select   wire:model="plan" wire:change="getCustomerName"  class="form-control @error('plan') is-invalid @enderror" id="exampleFormControlSelect1">
                                         <option value="">select plan</option>
                                          @if (!empty($plans))
                                            @foreach ($plans as $key => $value)
                                            <option value={{$value->code}}>{{$value->name}}-{{$value->price}}</option>
                                            @endforeach 
                                        @else
                                        <option value="">select brand first</option>

                                        @endif
                                        
                                        </select>
                                        @error('plan')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="form-group ">
                                        
                                    </div>
                              <button type="submit" class="btn btn-rounded btn-primary btn-block mt-2" >Pay</button>

                                </form>
                            </div>
  
                        </div>
                        <div class="col-lg-4 col-xl-4 mt-3"></div>
                    </div>    
            </div>
    </div>
</div>
```
   

> ** Component Code **
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Http\Services\Ringo;

class Cardform extends Component
{
    public $brands = ['dstv', 'gotv', 'startimes'];
    public $plans; // = [];
    public $name = 'Aubakar Umar';
    public $card;
    public $brand;
    public $plan;
    public $disable = false;

    public function render()
    {
        return view('livewire.cardform');
    }

    public function pay()
    {
        $this->validate([
            'brand' => 'required',
            'plan' => 'required',
            'card' => 'required'
        ]);

        // dd($this->brand);
    }

    public function getBrandPlans()
    {
        if ($this->brand == "") {
            return;
        }

        $ringo = new Ringo();
        $this->plans = $ringo->getBouques($this->brand);
        //dd('change');
    }

    public function getCustomerName()
    {
        //dd($this->plans);
    }
}
```

**Error**

The plans keeps changing after the `getCustomerName` there by producing the error in the link: https://flareapp.io/share/LPdlLpPO#F47

**Comment by GertjanRoke** [comment]
@sadiqumar18 it look more of an issue that your plan model object doesn’t have the code attribute on it.

**Comment by sadiqumar18** [comment]
@GertjanRoke if you check the getcustomername method i have dump there that method is called when you click on any of the plan on the plan options
` public function getCustomerName()
    {
        //dd($this->plans);
    }`
the plan from 
`        $ringo = new Ringo();
        $this->plans = $ringo->getBouques($this->brand);`
is what i get when i use the dump command, when i comment the dump command thats when i have the error

**Comment by GertjanRoke** [comment]
Clear, but the error you shared said that the error is here:
```html
<option value={{$value->code}}>{{$value->name}}-{{$value->price}}</option>
```

And I think this is the problem because if you place a collection of laravel models into a public property it will be casted to an array.
So if you change all `$value->...` inside that loop into `$value[...]` it should work.

So if you could try that, that would be great!
If it still breaks I will try to reproduce it later today.

**Comment by sadiqumar18** [comment]
hello @GertjanRoke thanks but it didnt work, mind you `$this->plan` is an array of object so when i change it to what you suggested it gave a different error

[https://flareapp.io/share/VP6d605J#F47](url)

**Comment by GertjanRoke** [comment]
If you can, could you share some of the code that is returned from getBougues?  
I think there is something wrong in the thing that gets returned from that.

Maybe one of the objects is `null` or doesn’t contain a property called `code` in some cases or not at all

**Comment by ManojKiranA** [comment]
For Now i have Just Created a Minimal Class that Loads the dropdown based on first selected


**Component Code**

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Str;

class DepandDropDown extends Component
{

    public $startingAlphabet;

    public $nameOfCountry;

    public function getAlphabetListProperty()
    {
        $alphabetRange = range('A', 'Z');

        return collect($alphabetRange)->combine($alphabetRange)->toArray();
    }

    public function getNameListProperty()
    {
        if($this->startingAlphabet){
            return collect(json_decode(file_get_contents('https://restcountries.eu/rest/v2/all'),true))
                        ->pluck('name')
                        ->filter(function($value){
                            return Str::startsWith($value,$this->startingAlphabet);
                        })->toArray();
        }else{
            return [];
        }
        
    
    }

    public function render()
    {
        return view('livewire.depand-drop-down');
    }
}

```

**View**

```
<div>
    {!! Form::select('startingAlphabet', $this->alphabetList, null, ['wire:model' => 'startingAlphabet','class' => 'form-control', 'placeholder' => 'Choose Any Alphabet' ]) !!}
    <br>
    {!! Form::select('nameList', $this->nameList, $nameOfCountry, ['wire:model' => 'nameOfCountry','class' => 'form-control', ! $startingAlphabet ? 'disabled' : '' , 'placeholder' => ! $startingAlphabet ? 'Choose Alphabet First' : ' You Can Select Country' ]) !!}
</div>

```

Hope its helps

**Comment by sadiqumar18** [comment]
> If you can, could you share some of the code that is returned from getBougues?
> I think there is something wrong in the thing that gets returned from that.
> 
> Maybe one of the objects is `null` or doesn’t contain a property called `code` in some cases or not at all
``[
    {
        "code": "ACSSE36",
        "name": "DStv Access",
        "price": "1960.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "COFAME36",
        "name": "DStv Family",
        "price": "3920.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "COMPE36",
        "name": "DStv Compact",
        "price": "6664.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "COMPLE36",
        "name": "DStv Compact Plus",
        "price": "10437.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "PRWE36",
        "name": "DStv Premium",
        "price": "15484.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "PRWASIE36",
        "name": "DStv Premium Asia",
        "price": "17346.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "ASIAE36",
        "name": "Asian Bouqet",
        "price": "5292.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "FTAE36",
        "name": "DStv FTA Plus",
        "price": "1568.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "NNJ1E36",
        "name": "DStv Yanga Bouquet E36",
        "price": "2450.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    },
    {
        "code": "NNJ2E36",
        "name": "DStv Confam Bouquet E36",
        "price": "4410.000",
        "currency": "NGN",
        "topup_currency": "NGN",
        "isAddon": false
    }
]``

this is the json for when you select dstv

**Comment by GertjanRoke** [comment]
@sadiqumar18 Thanks, yeah that looks good, maybe you can test if it also fails inside a blade file outside a livewire component.

I don't think it's a livewire issue, but maybe I'm wrong.
