### ISSUE TITLE
Allow SPA Mode to also work with blade layout components

### ISSUE THREAD

**Issue by studnitz** [livewire/livewire#810]
**Is your feature request related to a problem? Please describe.**
I already like the [SPA mode](https://laravel-livewire.com/docs/spa-mode), which currently works with layout files, which `@yield('content')`. What I'd like even more is, if it could support Laravel Blade Components à la `<x-app-layout>`. 

**Describe the solution you'd like**
It would work the same way as the current way, only with blade components. You would create a blade component at `resources/components/app-layout.blade.php`, which has a default slot.

E.g.:
```blade
<html>
	<head>
    	<title>Some site</title>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
   	 	<livewire:styles />
	</head>

<body>
	<header>Header</header>
	<main>
        {{ $slot }}
	</main>
	<footer>Footer</footer>
	<livewire:scripts />
</body>
</html>
```

No further action would be required and you could use
```php
Route::livewire('/home', 'counter');
```
in your routes files and it would place the counter livewire component into the blade component `$slot` of the layout.

Ideally, you'd also be able to change the default layout component name. Maybe even the slot it mounts to (like it's already implemented with the layout files). 

One thing to consider would be what happens if there are both

- `resources/views/layouts/app.blade.php`
- `resources/components/app-layout.blade.php`

defined? An error thrown? Suggestions are welcome.

**Comment by DanHarrin** [comment]
Hi, I'm gonna close this thread for now. Feel free to submit a pull request for this feature and we can get it reviewed for you. If you would like to continue your conversation about this feature, please use [the discussions section](https://github.com/livewire/livewire/discussions) or the [Discord server](https://discord.gg/H884eyt). Many thanks!
