### ISSUE TITLE
Nested Set Model and Public Property

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#811]
I am using [Laravel NestedSets](https://github.com/lazychaser/laravel-nestedset) for a multi-level quiz. If I put the Quiz Model as a Public Property I get an error `ErrorException Maximum function nesting level of '512' reached, aborting!`.

I set it up to use nested components. There is a Quiz component that calls the sub-component from the question view:
**Quiz.php**
```
use App\Models\QuizDataSet as QuizSet;
private $quiz;
public $question; // this kills Livewire
protected $listeners = ['nextStep'];
class Quiz extends Component
{
    public function mount() {
        $this->quiz =  mQuiz::find(1)->QuizDataSet->descendants->toTree(); // Entire Quiz Tree
        $this->question = $this->quiz->first(); // First Question
    }
    public function render() {
        return view('components.quiz', [
            'question' => $this->question
        ]);
    }
```
**quiz.blade.php**
```
@livewire($question->objectable['component'], ['q' => $question], key($step))
// @livewire('custom-select, ['q' => $question], key($step))
```
**CustomSelect.php**
```
class CustomSelect extends Component
{
    public $question; // this kills Livewire
    public function mount($q) {
        $this->question = $q;
    }
    public function render() {
        return view('components.custom-select', [
            'question' => $this->question,
        ]);
    }
    public function answer($a) {
        $this->emit('nextStep', [
            'answer' => $a
        ]);
    }
```
**custom-select.blade.php**
```
<b>{{ $question->objectable['question'] }}</b>
@foreach ($question->descendants as $answer)
    <div wire:click="answer('{{ $answer }}')" wire:key="{{ $loop->index }}">
        {$answer->objectable['answer']}}
    </div>
@endforeach
```

Everything is fine mostly if I just use it as a private property except on Hydrate where it loses it's data. So I am not sure what to do about this case. 

I read this issue #488 and it seems the solution is to use a computed property, but that requires it to be public and again I get the above error.

I'm not really sure what to do or why I'm getting that maximum function nesting error. Any help would be appreciated.

**Comment by jjjrmy** [comment]
I tried a few more things and still running into the same issue. The issue is coming from the nested component on hydrate.

**Quiz.php**
```
use App\Models\QuizDataSet as QuizSet;
private $quiz;
public $question_id;
protected $listeners = ['nextStep'];
class Quiz extends Component
{
    public function mount() {
        $this->quiz =  mQuiz::find(1)->QuizDataSet->descendants->toTree(); // Entire Quiz Tree
        $this->question_id = $this->quiz->first()->id; // First Question
    }
    public function getQuestionProperty() {
        return QuizSet::descendantsAndSelf($this->question_id)->toTree()->first();
    }
    public function render() {
        return view('components.quiz');
    }
```

The other files are the same, the issue is still the same where if I make the $question property public anywhere (in this case I'm doing it in CustomSelect.php [sub component]). On hydrate is loses the property value if it's set to private and errors because the data is missing.

I'm thinking the only solution is to do `getQuestionProperty()` again in the sub components but that seems it will cause excessive queries and processing.

Still not sure what to do about this.

**Comment by GertjanRoke** [comment]
Hello, but it’s this the problem that you have to many nested components or am I misreading the error?
