### ISSUE TITLE
Volt's title method doesn't seem to work in full page component

### ISSUE THREAD

**Issue by MUHAMMADSiyab** [livewire/livewire#8151]
### Discussed in https://github.com/livewire/livewire/discussions/8150

<div type='discussions-op-text'>

<sup>Originally posted by **MUHAMMADSiyab** March 19, 2024</sup>
**Laravel version: ^10.10**
**Livewire version: ^3.4**
**Volt version: ^1.0**

Using Full Page Volt component doesn't apply title to the page using `title` method.

**blog-posts.blade.php**:

```
<?php

use App\Models\Post;
use Livewire\WithPagination;

use function Livewire\Volt\{state, layout, computed, uses, title};

uses([WithPagination::class]);

layout('components.layouts.home');
title('Blog');


$posts = computed(function () {
    return Post::latest()->simplePaginate(10);
});

?>

@foreach ($this->posts as $post)
    <article id="blog-post" class="mb-8 border-b p-2 pb-6 ">
        <header>
            <h3 class="text-xl md:text-3xl font-semibold"> {{ $post->title }}</h3>
        </header>
    </article>
 @endforeach
```

Layout contains title like this:

`<title>{{ config('app.name', 'Laravel') }}</title>`

The page still shows the default `Laravel` title</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
