### ISSUE TITLE
Use of unspecified config value

### ISSUE THREAD

**Issue by dododedodonl** [livewire/livewire#817]
**Describe the bug**
When registering the views, the name is set to `config('livewire.view-path', 'livewire')` [on line 117](https://github.com/livewire/livewire/blob/f9f2cb4d2a587a8b5414858fb07e5d1fea589d0b/src/LivewireServiceProvider.php#L117) of the LivewireServiceProvider.

This is probably not intended, as the same config value is not used in the WithPagination trait [on line 31](https://github.com/livewire/livewire/blob/f9f2cb4d2a587a8b5414858fb07e5d1fea589d0b/src/WithPagination.php#L31), and not defined in the default config file. Using this config value would break the loading of this view.

**Solution**
Remove the config value when registering the views, and set it to the now used `livewire`.

**Comment by mblarsen** [comment]
The lines referenced above:

https://github.com/livewire/livewire/blob/f9f2cb4d2a587a8b5414858fb07e5d1fea589d0b/src/LivewireServiceProvider.php#L115-L118

and

https://github.com/livewire/livewire/blob/f9f2cb4d2a587a8b5414858fb07e5d1fea589d0b/src/WithPagination.php#L29-L32
