### ISSUE TITLE
TrimStrings and ConvertEmptyStringsToNull middlewares do not work on Livewire

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/livewire#823]
**Describe the bug**
Laravel has 2 middlewares: TrimStrings, which trims strings sent in the request, and ConvertEmptyStringsToNull, which converts empty strings to null, as the name says. The point is that Livewire's public properties binded with wire:model are not trimmed nor converted to null when empty as Laravel does on default requests.

**To Reproduce**
1. Just bind a public property with wire:model in an input and add spaces. The property value will not be trimmed nor be converted to null.

**Expected behavior**
If using TrimStrings and ConvertEmptyStringsToNull middlewares, strings should be trimmed and converted to null when empty when sent to backend.

**Comment by mblarsen** [comment]
This seems to be on purpose to "avoid corruption of state":

https://github.com/livewire/livewire/blob/758a30ee08f9c2f4b8caf9ed11086c49e5b13036/src/LivewireServiceProvider.php#L73-L82

**Comment by lucasromanojf** [comment]
@mblarsen I see, maybe implementing a (optional) trait for this, which could be used in the component... anyway, this can be implemented inside project, but maybe this is something that would be cool to have on core. I could implement something in my project and if it works fine, make a PR

**Comment by mblarsen** [comment]
I don't full understand what this is refering to:

> but during Livewire requests, they can damage data properties. 

Perhaps look into that first? Apologies for not being more helpful :)

**Comment by lucasromanojf** [comment]
@mblarsen no worries, we are discussing solutions and this helps a lot too :)

The point is, if some middleware changes the request data sent before reaching the Livewire component, the checksum fails and Livewire throws a corrupt data error (something like this), because Livewire was expecting different data and it was modified before reaching Livewire. This is a security feature of Livewire, I guess.

But if the trimming/empty-to-null is done inside the component, the data won't be corrupted. This is why I was thinking about doing a trait to be used inside Livewire component (optional) that trims all public properties and also converts empty public properties strings to null.

**Comment by mblarsen** [comment]
@lucasromanojf Thanks for the explanation. Going with a trait makes sense.

**Comment by calebporzio** [comment]
Not trimming strings and converting to null is the desired behavior of Livewire.

You can add traits to bypass this and that's what I would recommend if you want to re-introduce this behavior.

Closing this. Thanks!

**Comment by that0n3guy** [comment]
@lancepioch did you ever create the trait that does this?  If so, mind sharing it?
> a trait to be used inside Livewire component (optional) that trims all public properties and also converts empty public properties strings to null.

**Comment by amirzpr** [comment]
I'm sharing this for anyone who looks for a solution.

To convert empty strings to `null`, just add this code to your Livewire component:

```php
public function updated($name, $value)
{
    if ( $value == '' ) data_set($this, $name, null);
}
```

It also works for **nested properties** and properties of **Eloquent model** type.

**Comment by ryanmortier** [comment]
I just ran into this today. I modified @amirzpr solution slightly. I have a `helpers.php` file with this function:

```php
if (!function_exists('filter_trim_and_null')) {
    function filter_trim_and_null($value)
    {
        if (!is_string($value)) {
            return $value;
        }

        $value = trim($value);

        return $value === '' ? null : $value;
    }
}
```

Then in my Livewire component I put this: 

```php
public function updated($name, $value)
{
    data_set($this, $name, filter_trim_and_null($value));
}
```

**Comment by ryanmortier** [comment]
@that0n3guy I went a step further and created a trait so I'll share it with you.

I created my trait in the `App\Http\Livewire;` namespace.

```php
<?php

namespace App\Http\Livewire;

trait TrimAndNullEmptyStrings
{
    public function updatedTrimAndNullEmptyStrings($name, $value)
    {
        if (is_string($value)) {
            $value = trim($value);
            $value = $value === '' ? null : $value;

            data_set($this, $name, $value);
        }
    }
}

Then in my component controller I simply used it:

```php
<?php

namespace App\Http\Livewire\Orders;

use App\Http\Livewire\TrimAndNullEmptyStrings;
use App\Models\Order;
use Livewire\Component;

class CreateOrder extends Component
{
    use TrimAndNullEmptyStrings;
}
```

It will automatically trim and null empty strings, you don't have to do anything in the component controller since it's just using the life cycle hook.

**Comment by amiranagram** [comment]
@that0n3guy I went a step further (🤣) and added exceptions because in some cases you want to keep some properties as empty strings.

```
trait ConvertEmptyStringsToNull
{
    /**
     * @var string[]
     */
    protected $convertEmptyStringsExcept = [
        //
    ];

    /**
     * @param string $name
     * @param mixed $value
     */
    public function updatedConvertEmptyStringsToNull(string $name, $value): void
    {
        if (! is_string($value) || in_array($name, $this->convertEmptyStringsExcept)) {
            return;
        }

        $value = trim($value);
        $value = $value === '' ? null : $value;

        data_set($this, $name, $value);
    }
}
```

**Comment by isometriq** [comment]
In case without hook is prefered, recursive function for dealing with arrays
```php
protected function cleanInput($input) {
    foreach ($input as &$value) {
        if (is_array($value)) {
            $value = $this->cleanInput($value);
        }
        else if (is_string($value)) {
            $value = trim($value);
            if ($value === '') {
                $value = null;
            }
        }
    }
    return $input;
}
```

**Comment by KondorB** [comment]
> @that0n3guy I went a step further (🤣) and added exceptions because in some cases you want to keep some properties as empty strings.
> 
> ```
> trait ConvertEmptyStringsToNull
> {
>     /**
>      * @var string[]
>      */
>     protected $convertEmptyStringsExcept = [
>         //
>     ];
> 
>     /**
>      * @param string $name
>      * @param mixed $value
>      */
>     public function updatedConvertEmptyStringsToNull(string $name, $value): void
>     {
>         if (! is_string($value) || in_array($name, $this->convertEmptyStringsExcept)) {
>             return;
>         }
> 
>         $value = trim($value);
>         $value = $value === '' ? null : $value;
> 
>         data_set($this, $name, $value);
>     }
> }
> ```

Don't know if it's because of the last update, but it seems like this method never gets called at all. It works if I rename it to just `updated`.

**Comment by amiranagram** [comment]
> 
> 
> > @that0n3guy I went a step further (🤣) and added exceptions because in some cases you want to keep some properties as empty strings.
> > ```
> > trait ConvertEmptyStringsToNull
> > {
> >     /**
> >      * @var string[]
> >      */
> >     protected $convertEmptyStringsExcept = [
> >         //
> >     ];
> > 
> >     /**
> >      * @param string $name
> >      * @param mixed $value
> >      */
> >     public function updatedConvertEmptyStringsToNull(string $name, $value): void
> >     {
> >         if (! is_string($value) || in_array($name, $this->convertEmptyStringsExcept)) {
> >             return;
> >         }
> > 
> >         $value = trim($value);
> >         $value = $value === '' ? null : $value;
> > 
> >         data_set($this, $name, $value);
> >     }
> > }
> > ```
> 
> Don't know if it's because of the last update, but it seems like this method never gets called at all. It works if I rename it to just `updated`.

I'm not sure but the name of the method needs to be `updatedNameOfTheTrait`. Same works for other lifecycle methods, like mount for example.

`updated` would be fine, but I don't like using it inside traits because if I use `updated` inside any component it will override the functionality that that trait provides.

**Comment by Christophvh** [comment]
> Not trimming strings and converting to null is the desired behavior of Livewire.
> 
> You can add traits to bypass this and that's what I would recommend if you want to re-introduce this behavior.
> 
> Closing this. Thanks!

Could you explain why this is desired behavior? so we understand the edge case?

**Comment by ryanmortier** [comment]
> @calebporzio Could you explain why this is desired behavior? so we understand the edge case? Because 'during Livewire requests, they can damage data properties.' is a bit vague.

I've noticed it becomes an issue if you're not utilizing `.defer` or `.lazy` because if you're typing something with spaces such as any sentence, as soon as you hit space it trims the space immediately.

**Comment by ryanmortier** [comment]
Ugh...

I've run into so many quirks and gotchas using a trait on the Livewire component when not using `.defer` that I'm considering trimming and converting strings on persisting to the database instead. Does anyone see any issues going with something like this?

**app/helpers.php**
```php
<?php

if (!function_exists('trim_string')) {
    function trim_string($value)
    {
        if (!is_string($value)) {
            return $value;
        }

        return preg_replace('~^[\s﻿]+|[\s﻿]+$~u', '', $value) ?? trim($value);
    }
}

if (!function_exists('convert_empty_string_to_null')) {
    function convert_empty_string_to_null($value)
    {
        return $value === '' ? null : $value;
    }
}

if (!function_exists('trim_string_and_convert_empty_string_to_null')) {
    function trim_string_and_convert_empty_string_to_null($value)
    {
        return convert_empty_string_to_null(trim_string($value));
    }
}
```

**app/Models/Model.php**
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as BaseModel;

class Model extends BaseModel
{
    protected static function booted()
    {
        parent::booted();

        static::saving(function ($model) {
            $model->forceFill(array_map('trim_string_and_convert_empty_string_to_null', $model->getAttributes()));
        });
    }
}
```

**Comment by Christophvh** [comment]
@ryanmortier yeah this seems like the best approach. It would be great if Livewire had an event 'submitting' or something just like we have the 'updating' events. so we can hook into the form action and do the trimming before it gets sent to the DB for all the changed fields instead of having to make mutators for all attributes, because those mutators are also triggered for non-livewire routes/actions which makes the app way slower.

**Comment by ryanmortier** [comment]
Anyone that decided to use the model saving event, beware it does weird things with `json` columns. Still looking for a better approach. Perhaps with Livewire v3 being deferred by default it will work better.

**Comment by robogito** [comment]
What about a validation rule?

```
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class TrimmedRule implements Rule
{
    /**
     * Determine if the validation rule passes.
     * Dont allow whitespases at begin & at the end of the string
     *
     * @param  string  $attribute
     * @param  mixed  $value
     */
    public function passes($attribute, $value): bool
    {
        return !preg_match('/^\s+|\s+$/', $value);
    }

    /**
     * Get the validation error message.
     */
    public function message(): string
    {
        return trans('Whitespace?');
    }
}
```

**Comment by harlacher** [comment]
> I've noticed it becomes an issue if you're not utilizing `.defer` or `.lazy` because if you're typing something with spaces such as any sentence, as soon as you hit space it trims the space immediately.

@ryanmortier Use `ltrim` instead?

```php
<?php

namespace App\Traits;

/**
 * Trait WireConvertEmptyStringsToNull
 */
trait WireConvertEmptyStringsToNull
{
    /**
     * @var string[]
     */
    protected array $convertEmptyStringsExcept = [
        //
    ];

    /**
     * @param string $name
     * @param mixed $value
     */
    public function updatedWireConvertEmptyStringsToNull(string $name, mixed $value): void
    {
        if (! is_string($value) || in_array($name, $this->convertEmptyStringsExcept)) {
            return;
        }

        $value = ltrim($value);
        $value = $value === '' ? null : $value;

        data_set($this, $name, $value);
    }
}
```

**Comment by lpoirothattermann** [comment]
Hi,

This need to be implemented natively.

For example, if you are using an input of type number that fire action on change, write some numbers in it and then deleting everything you just wrote. 
![Screenshot 2023-03-28 at 18 44 38](https://user-images.githubusercontent.com/68006124/228310577-286a7fbf-4f9c-47d5-ac05-e1e5685700ef.png)

When you will submit the form this will lead to be interpreted as an empty string in Laravel and your type declaration "?int" will throw error.

To prevent this you change the type declaration to "string", but later in your code when you will manually check to replace the empty string to null and convert your digit string to integer your IDE will cry because you are modifying the parameter type to something not expected by the type declaration.
![Screenshot 2023-03-28 at 18 29 01](https://user-images.githubusercontent.com/68006124/228307790-774a6c92-e8b2-4a69-a4e5-53bdcdcbcf8d.png)

This behavior makes type declaration totally useless.

**Comment by polycode-nz** [comment]
It's been a while, is there any better/native way to handle this in V3?

I was using one of the versions of the snippets above but found I can't clear/delete a casted date model property by submitting an empty date input. 

Setting it to null seems to set it back to a Carbon instance with a value of now.

**Comment by ryanmortier** [comment]
@polycode-nz I still use the trait but then I exclude fields like that from it and manually correct it in an updated hook.

E.g.
```php
class BinDimensionsComponent extends Component
{
    use TrimAndConvertEmptyStringsToNull;

    public $aeration_height = 0;

    protected $trimAndConvertEmptyStringsToNullExcept = ['aeration_height'];

    public function updatedAerationHeight($value)
    {
        $value = $this->trimAndConvertEmptyStringsToNull($value);

        $this->aeration_height = is_null($value) ? 0 : $value;
    }
}

**Comment by polycode-nz** [comment]
@ryanmortier Yeah gotta be the casts which is strange. Can't null just be null!

This whole thing is a weird situation. I get it for the live bindings why this happens but when you're doing whole forms this really feels like something that should be available opt-in in Livewire. 

It's been a year or so since I looked at this and my implementation is too basic. Thanks for your example, I'll head in that direction.

**Comment by fillobotto** [comment]
Needs to be reopened

**Comment by fillobotto** [comment]
This shoule definitely reopened
