### ISSUE TITLE
Awesome Livewire

### ISSUE THREAD

**Issue by Te7a-Houdini** [livewire/livewire#824]
Since we have [awosome-alpine](https://github.com/alpinejs/awesome-alpine) what about  to do the same for livewire

**Comment by jjjrmy** [comment]
yes would like this also, I have components to share!

**Comment by lancepioch** [comment]
This sounds like a great idea! Can you create a new [Github Discussion](../discussions) regarding this? We are hoping that this will encourage and centeralize feedback.

**Comment by Te7a-Houdini** [comment]
@lancepioch done
