### ISSUE TITLE
Livewire component's public property must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.

### ISSUE THREAD

**Issue by lovecoding-git** [livewire/livewire#825]
```
public function render()
    {
        return view('livewire.user', ['contacts'=>\App\User::paginate(5)]);
    }
```
This worked well.
But when I did as following, it showed error such as title.
```
public $contacts;

public function mount()
{
    $this->contacts = \App\User::paginate(5);
}
public function render()
{
     return view('livewire.user');
}
```

**Comment by calebporzio** [comment]
Yeah, I ran into this yesterday. The problem is that ::paginate() returns a "LengthAwarePaginator" instead of an "EloquentCollection", so Livewire doesn't know how to dehydrate it.

As a work around, you could convert the length aware paginator to an Eloquent Collection before setting as a property.

I will try to follow up with an example when I'm at my computer.

**Comment by syahnur197** [comment]
I'm having this issue as well, any ways to solve this issue?

**Comment by HowardF** [comment]
Appreciate an example to "convert the length aware paginator to an Eloquent Collection" or a reference.

**Comment by aarondfrancis** [comment]
Running into this as well, would love to figure out how to solve it.

**Comment by HDVinnie** [comment]
Also facing this issue.

**Comment by mauriciomateus** [comment]
Ran into the same issue. The reason to set the property is so that when you add a row, the table gets immediatly refreshed on the front end

**Comment by mohamedshuaau** [comment]
You could try something like this for now. At least until a solution is proposed.

In my case, I was getting an instance of my model from my index method in my controller. So like mentioned here, pagination is not an Eloquent Collection. You could do this instead.

```
//in my controller
public function index()
    {
        $data = app(Menu::class);
        return view('someview', compact('data'));
    }

//in my blade
<livewire:mycomponent :data="$data" />

//in my livewire component
public $data;

public function render()
    {
        return view('mycomponent', ['paginated' => $this->data->latest()->paginate(5)]);
    }

//finally in my component blade, loop
@foreach($paginated as $row)
  <p>{{$paginated->name}}</p>
@endforeach
```

Hope this helps someone

**Comment by IdrisN** [comment]
Thanks for the example @mohamedshuaau !

Shouldn't the data property throw a `PublicPropertyTypeNotAllowedException` since `latest()` only works on query builder objects which is not an allowed type for public properties.

At least that's what happens in my case.

**Comment by mohamedshuaau** [comment]
> Thanks for the example @mohamedshuaau !
> 
> Shouldn't the data property throw a `PublicPropertyTypeNotAllowedException` since `latest()` only works on query builder objects which is not an allowed type for public properties.
> 
> At least that's what happens in my case.

You’re right it would throw an error. But that is assuming you are doing latest() from your controller. Your public property will hold the model instance and you can use query builder when passing data over to the view. That would not throw the error. Can you drop code of what you are doing?

**Comment by nonso07** [comment]
> Thanks for the example @mohamedshuaau !
> 
> Shouldn't the data property throw a `PublicPropertyTypeNotAllowedException` since `latest()` only works on query builder objects which is not an allowed type for public properties.
> 
> At least that's what happens in my case.



> You could try something like this for now. At least until a solution is proposed.
> 
> In my case, I was getting an instance of my model from my index method in my controller. So like mentioned here, pagination is not an Eloquent Collection. You could do this instead.
> 
> ```
> //in my controller
> public function index()
>     {
>         $data = app(User::class);
>         return view('someview', compact('data'));
>     }
> 
> //in my blade
> <livewire:mycomponent :data="$data" />
> 
> //in my livewire component
> public $data;
> 
> public function render()
>     {
>         return view('mycomponent', ['paginated' => $this->data->latest()->paginate(5)]);
>     }
> 
> //finally in my component blade, loop
> @foreach($paginated as $row)
>   <p>{{$paginated->name}}</p>
> @endforeach
> ```
> 
> Hope this helps someone

Mine is returning an empty array.... please is there any other way 

//livewire coomponet
return view('livewire.post-job', ['postJob' => $this->postJob->latest()->paginate(5)]);
    }

// controller
$postJob = app(jobList::class);
        return view('adminPostJob')->with('postJob',$postJob);

//blade template
 @foreach($postJob as $postJobs)  
{{ $postJob->jobTitle}}
@endfeoreach

**Comment by mohamedshuaau** [comment]
@nonso07 where are you passing the livewire component data from? Where is “adminPostJob” view and how does it look like? Do you have any data currently in job lists table? Can you do a return of the same thing you are doing in livewire component inside your controller and see if you get a result?

Try running return $postJob->latest()->paginate(5); before returning your view inside your controller and see if you get anything. And confirm if you have data in that table and that the model/table is working fine

**Comment by nonso07** [comment]
> @nonso07 where are you passing the livewire component data from? Where is “adminPostJob” view and how does it look like? Do you have any data currently in job lists table? Can you do a return of the same thing you are doing in livewire component inside your controller and see if you get a result?
> 
> Try running return $postJob->latest()->paginate(5); before returning your view inside your controller and see if you get anything. And confirm if you have data in that table and that the model/table is working fine

Thank you very much for your time sir, I was able solve it  by not making the $postJob not to be a public function.. 
https://github.com/livewire/livewire/issues/722
the above link helped me.

**Comment by lubo1998** [comment]
I faced the same problem, but what I've done is:
```
$items_tpl = MyModel::Paginate(5);
$this->items = collect($items_tpl->items());
return view('livewire.index', ['items_tpl' => $items_tpl]);
```

and kept iterating over **$items** in the component.

**Comment by gtu-myowin** [comment]
The question itself has the answer and the OP mentioned it. Just move the pagination to the render method as follow

```php
<?php

namespace App\Http\Livewire\Blog;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Blog as ModelsBlog;

class Blog extends Component
{
    use WithPagination;

    // public $blogs;

    // public function mount()
    // {
    //     $this->blogs = ModelsBlog::paginate(10);
    // }

    public function render()
    {
        return view('livewire.blog.blog', [
            'blogs' => ModelsBlog::paginate(10)
        ]);
    }
}

```

Using `use WithPagination;` is optional. 
(Added my comment so that this could help future users who comes from Google search)

**Comment by komen205** [comment]
> The question itself has the answer and the OP mentioned it. Just move the pagination to the render method as follow
> 
> ```
> <?php
> 
> namespace App\Http\Livewire\Blog;
> 
> use Livewire\Component;
> use Livewire\WithPagination;
> use App\Models\Blog as ModelsBlog;
> 
> class Blog extends Component
> {
>     use WithPagination;
> 
>     // public $blogs;
> 
>     // public function mount()
>     // {
>     //     $this->blogs = ModelsBlog::paginate(10);
>     // }
> 
>     public function render()
>     {
>         return view('livewire.blog.blog', [
>             'blogs' => ModelsBlog::paginate(10)
>         ]);
>     }
> }
> ```
> 
> Using `use WithPagination;` is optional.
> (Added my comment so that this could help future users who comes from Google search)

It worked for me but you can't have
public ... on your livewire controller otherwise didnt work for me.

Also, set up new livewire pagination with 'php artisan livewire:publish --pagination'

and do:
            {{ $blogs->links('vendor.livewire.bootstrap') }}
on your view

**Comment by FernandoDefez** [comment]
I solved this problem this way:

`$this->products = Product::paginate(10);
        $links = $this->products;
        $this->products = collect($this->products->items());
        return view('livewire.admin.product.products-table', ['products' => compact($this->products), 'links' => $links]);`


And I use $links this way in my view

`@if($links->links())
            {{ $links->links() }}
        @endif`

**Comment by FernandoDefez** [comment]
I did the following:

![product](https://user-images.githubusercontent.com/49768478/117497820-95251280-af3e-11eb-930d-5d24059381be.png)

![products](https://user-images.githubusercontent.com/49768478/117497856-a0783e00-af3e-11eb-84b1-5a531c94981a.png)

At least it worked for me

**Comment by mreduar** [comment]
I would like to pass the paged data from the controller. Is this not possible? I mean, the livewire components are going to replace the logic in the controllers? I would like to keep my logic in the controllers and livewire for rendering only.

**Comment by bitwiseph** [comment]
Yes you can. you this way
SampleController
```php
class SampleController extends Controller{
    public function index(){
     $data='value to be passed';
     return view('livewire.view',compact('data'))
  }
}
```
Laravel Blade View
```html
<div class="container">
  <livewire:component-name data="{{ $data }}" />
</div>
```

Livewire Component on Http/Livewire/ComponentName
```php
class ComponentName extends Component{
   public $data; //this should declare
   public function render(){
     return view('livewire.view');
} 
}
```

Your Livewire view on views/livewire/view.blade.php
```html
  <div>
 {{ $data }} <!-- value from controller will display here -->
</div>
```

I hope this helps.

**Comment by mreduar** [comment]
@bitwiseph That's what I tried some time ago, and I got the issue error `Livewire component's public property must be of type: [numeric, string, array, null, or boolean]`. That's why I came here and asked the question. The problem seems to be when I pass the paged data to the livewire component. If it is a common data as in your example "a string" there should be no problem. 🤔

**Comment by gtu-myowin** [comment]
@mreduar Why would some one like to use Laravel's controller when Livewire give you a set of Controller (sort of) and a view compoment? I have developed fairly big and complex websites with Livewire and I haven't use Laravel's controllers in any of them. I would strongly encourage you to do so because if in this way you will have your logic and views component by component which is much cleaner than putting all logic in one big controller file.

**Comment by virla01** [comment]
> I did the following:
> 
> ![product](https://user-images.githubusercontent.com/49768478/117497820-95251280-af3e-11eb-930d-5d24059381be.png)
> 
> ![products](https://user-images.githubusercontent.com/49768478/117497856-a0783e00-af3e-11eb-84b1-5a531c94981a.png)
> 
> At least it worked for me

Thanks friend, it helped me, only that I have to order the columns and when I click it tells me:
BadMethodCallException
Method Illuminate \ Support \ Collection :: items does not exist.
any solution for this, maybe you already fixed it?

**Comment by LucasLermagne** [comment]
> I did the following:
> 
> ![product](https://user-images.githubusercontent.com/49768478/117497820-95251280-af3e-11eb-930d-5d24059381be.png)
> 
> ![products](https://user-images.githubusercontent.com/49768478/117497856-a0783e00-af3e-11eb-84b1-5a531c94981a.png)
> 
> At least it worked for me

thank you so much ^^

**Comment by alokVishu** [comment]
I have done the below.

```php
public $posts;

public function render()
    {
        $this->posts = Post::paginate(5)->all();
        return view('livewire.posts',[
            'pagination' => Post::paginate(5),
    ]);
```

it works for me.

**Comment by hhristovdev** [comment]
I was banging my head so long on this issue. 
Found the solution. 

As it says in the error  the properties in a **livewire** component can be only 
`[numeric, string, array, null, boolean]` types

so if we want a **different** type to be passed _(a collection for example)_ we will need to make it a **protected/private** property 

```php
    protected $items;

    public function mount()
    {
        $this->items = Product::paginate(20);
    }

    public function render()
    {
        return view('livewire.datatable',[
            'items'=>$this->items
        ]);
    }
```

**Comment by burfbari** [comment]
> 

Using `mount()` worked for me too.

However I kept the property `public` and used the parameter being passed to populate the property.

```
public $items;

    public function mount($items)
    {
        $this->items = $items;
    }
```

Setting it up in the render method was not required as I was passing it to the component through blade.

**Comment by jovan-trpcheski** [comment]
I had the same error and I wanted to have reusable component and pass data via blade, so the mentioned solutions wouldn't work for me because I must use the mount method. I came up with this solution which is basically setting the data as protected: 
Getting data from blade
` @livewire('index-posts', ['posts' => $posts])`

Liveware controller
`protected $posts;
    public function mount($posts)
    {
        $this->posts = $posts;

    }
    public function render()
    {
        return view('livewire.index-posts',['posts' => $this->posts]);
    }`

**Comment by desirerNdjog** [comment]
> Yeah, I ran into this yesterday. The problem is that ::paginate() returns a "LengthAwarePaginator" instead of an "EloquentCollection", so Livewire doesn't know how to dehydrate it.
> 
> As a work around, you could convert the length aware paginator to an Eloquent Collection before setting as a property.
> 
> I will try to follow up with an example when I'm at my computer.

i have the same probleme, please can you post the solution ?

**Comment by allayar27** [comment]
Livewire\Exceptions\PublicPropertyTypeNotAllowedException
Livewire component's [payment] public property [transactions] must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.  I get this error when I have try to paginate the data  . How I can using mount() with paginate

**Comment by anilthedev** [comment]
> ```
> public function render()
>     {
>         return view('livewire.user', ['contacts'=>\App\User::paginate(5)]);
>     }
> ```
> 
> This worked well. But when I did as following, it showed error such as title.
> 
> ```
> public $contacts;
> 
> public function mount()
> {
>     $this->contacts = \App\User::paginate(5);
> }
> public function render()
> {
>      return view('livewire.user');
> }
> ```

Make the $contacts as protected and pass the value in render method. The final code is as follows 


`protected $contacts;

public function mount()
{
    $this->contacts = \App\User::paginate(5);
}
public function render()
{
     return view('livewire.user', ['contacts' => $this->contacts]);
}`

in my case it worked

**Comment by sven-ahrens** [comment]
> > ```
> > public function render()
> >     {
> >         return view('livewire.user', ['contacts'=>\App\User::paginate(5)]);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This worked well. But when I did as following, it showed error such as title.
> > ```
> > public $contacts;
> > 
> > public function mount()
> > {
> >     $this->contacts = \App\User::paginate(5);
> > }
> > public function render()
> > {
> >      return view('livewire.user');
> > }
> > ```
> 
> Make the $contacts as protected and pass the value in render method. The final code is as follows
> 
> ```
> protected $contacts;
> 
> public function mount()
> {
>     $this->contacts = \App\User::paginate(5);
> }
> public function render()
> {
>      return view('livewire.user', ['contacts' => $this->contacts]);
> }
> ```
> 
> in my case it worked

Jup this worked for me too. Seems like a bug for me, that you have to manually call the mount method but if it works it works. Thanks for sharing :)

**Comment by lamkimphu258** [comment]
Hi all, this is my solution for this problem. Basically, I do not set paginate to livewire component property. Instead, I have property for filter and sort. Then before render, I run query to get data I want base on filter and sort property. In this  product list component, I filter by category to get product and sort it by title, price or created_at. This is my livewire `ProductList` component:

```
<?php

namespace App\Livewire;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Livewire\Attributes\Computed;
use Livewire\Component;
use Livewire\WithPagination;

class ProductList extends Component
{
    use WithPagination;

    public $categoryId = 1;

    public $sort = 'latest';

    public $sortColumn = 'created_at';

    public $sortOrder = 'desc';

    #[Computed]
    public function categories()
    {
        return ProductCategory::select('id', 'name')->get();
    }

    public function render(): View|Factory
    {
        return view(
            'livewire.product-list',
            [
                'products' => Product::select('id', 'title', 'price', 'thumbnail', 'slug')
                    ->where('category_id', $this->categoryId)
                    ->orderBy($this->sortColumn, $this->sortOrder)
                    ->paginate(15),
            ]
        );
    }

    public function updateSort()
    {
        switch ($this->sort) {
            case 'title_asc':
                $this->sortColumn = 'title';
                $this->sortOrder = 'asc';
                break;
            case 'title_desc':
                $this->sortColumn = 'title';
                $this->sortOrder = 'desc';
                break;
            case 'price_asc':
                $this->sortColumn = 'price';
                $this->sortOrder = 'asc';
                break;
            case 'price_desc':
                $this->sortColumn = 'price';
                $this->sortOrder = 'desc';
                break;
            default:
                $this->sortColumn = 'created_at';
                $this->sortOrder = 'desc';
        }
    }
}
```

This is my view
```
@pushOnce('styles')
@vite(['resources/scss/components/product-list.scss'])
@endPushOnce

<div>
    <div class="flex flex-col space-y-8 md:space-y-0 md:flex-row justify-between">
        <select name="categories" class='product-filter' wire:change="updateSort" wire:model="categoryId">
            @foreach($this->categories as $category)
            <option class="category-item" value="{{ $category->id }}" wire:key={{ $category->id }}>{{ $category->name }}</option>
            @endforeach
        </select>
        <select name="sort" class='product-filter' wire:change="updateSort" wire:model="sort">
            @foreach(['latest' => 'latest', 'title_asc' => 'title (a->z)', 'title_desc' => 'title (z->a)', 'price_asc' => 'price: low to high', 'price_desc' => 'price: high to low'] as $sortKey=>$sortItem)
            <option class="sort-item" value="{{ $sortKey }}" wire:key={{ $sortKey }}>{{ $sortItem }}</option>
            @endforeach
        </select>
    </div>
    <div class="product-container animate__animated">
        @foreach ($products as $productIndex => $product)
        <div class="product-card" wire:key={{ $product->id }}>
            <p class="product-title">{{ $product->title }}</p>
            <p class="product-price">$ {{ $product->price }} USD</p>
            <img class="product-image" src="{{ $product->thumbnail }}" alt="Product Thumbnail" />
            <x-button content="View details" type="secondary" link="{{ 'products/' . $product->slug }}"></x-button>
        </div>
        @endforeach

    </div>

    <div class="pagination">
        {{ $products->links() }}
    </div>
</div>
```

Hope this help.
