### ISSUE TITLE
Laravel Sweetalert not working on button click

### ISSUE THREAD

**Issue by abrardev99** [livewire/livewire#827]
Sweetalert Laravel not working on click action. Sweetalert configured perfectly as I tested it is working in controllers but not in Livewire component. any help will be appreciated 
```
    public function updateProfile(){
        toast('Profile Updated !','success');
    }
```

**Comment by GertjanRoke** [comment]
Hello @abrardev99, I didn’t know this package you are using but maybe this can help you out?

https://laravel-livewire.com/docs/events#in-js

You then have to move to using the javascript version of sweet alert but maybe you’re fine with that.
