### ISSUE TITLE
AlpineJS @click, Livewire conflict

### ISSUE THREAD

**Issue by tanthammar** [livewire/livewire#828]
**Describe the bug**
If I add an Alpine JS @click attribute to a Livewire Component. It breaks the Livewire component.

**To Reproduce**
Example:
In a blade (foreach loop) livewire component I have:
```
<tr  @click="window.location.href = '{{ route("app.bookon.show", ['bookon' => $row->uuid]) }}'">
```

it renders to this, and the link works as expected:
```
<tr @click="window.location.href = 'https://bookons.test/app/bookons/bkn-KxSGdsg_rkQ4dh45zSc-F'">
````
But the Livewire component breaks.

In Console I get the following error from Livewirejs:
```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@click' is not a valid attribute name.  

// morphAttrs.js:37 

export default function morphAttrs(fromNode, toNode) {
    var attrs = toNode.attributes;
    var i;
    var attr;
    var attrName;
    var attrNamespaceURI;
    var attrValue;
    var fromValue;

    // update attributes on original DOM element
    for (i = attrs.length - 1; i >= 0; --i) {
        attr = attrs[i];
        attrName = attr.name;
        attrNamespaceURI = attr.namespaceURI;
        attrValue = attr.value;

        if (attrNamespaceURI) {
            attrName = attr.localName || attrName;
            fromValue = fromNode.getAttributeNS(attrNamespaceURI, attrName);

            if (fromValue !== attrValue) {
                if (attr.prefix === 'xmlns'){
                    attrName = attr.name; // It's not allowed to set an attribute with the XMLNS namespace without specifying the `xmlns` prefix
                }
                fromNode.setAttributeNS(attrNamespaceURI, attrName, attrValue);
            }
        } else {
            fromValue = fromNode.getAttribute(attrName);

            if (fromValue !== attrValue) {
//this is row 37---->>>>>>>      fromNode.setAttribute(attrName, attrValue);
            }
        }
    }
```

Livewire v1.0.12
User-Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Comment by DanHarrin** [comment]
For this case, can't you just use an `<a>` tag? it does the same thing without JavaScript 😄

**Comment by ducopro** [comment]
Yes, i had the same problem.

I found a workaround by using `x-on:click` instead of `@click`

**Comment by tanthammar** [comment]
I also swapped all mine to x-on:click. Just thought I’d post it here as Livewire and Alpine are such close “buddies” :)

**Comment by tanthammar** [comment]
> For this case, can't you just use an `<a>` tag? it does the same thing without JavaScript 😄

I can’t wrap a tr with an a tag.

**Comment by jjrohrer** [comment]
I think I ran into the same issue when I was using `x-on:click` & `@click` (which, admittedly, sounds fishy).
I'm still facing challenges, but I think they are different ones.

I went from this...
```
        $html =<<<EOD
            <button
            x-on:click.prevent
            @click = "theOneModal.open('{$pageRoute}','{$modalTitle}', '{$enumCancelOkClose}', '{$primaryName}');"           
            >{$linkInnerHtml}</button>
```
to this... 
```
            $html =<<<EOD
            <button
            x-on:click.prevent="theOneModal.open('{$pageRoute}','{$modalTitle}', '{$enumCancelOkClose}', '{$primaryName}');"
            >{$linkInnerHtml}</button>

```
which made the 
`Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@click' is not a valid attribute name.  `
go away

**Comment by wrabit** [comment]
If you're @click / @anything is within a loop, add a unique wire:key="{{ $key }}" to the element.

**Comment by RyanGSampson** [comment]
I thought I was going crazy. Thank you!
