### ISSUE TITLE
Listen to livewire event from AlpineJS “component”

### ISSUE THREAD

**Issue by mtctonyhkhk2010** [livewire/livewire#830]
Is it possible to listen to livewire event from a AlpineJS “component” that is already inside a livewire view?
Like:
Inside a livewire component:
```
public function somethingUpdated($value)
    {
        $this->emit('somethingUpdated');
    }
```

And then in the livewire view:
```
<div>
<input type="text" x-data x-on:somethingUpdated="foo = 'bar'">
</div>
```

Something like that?
Thanks.

**Comment by mblarsen** [comment]
I have a case where I want a Livewire component to respond to a change in Alpine state. I don't know if this directly applies to your case. In my app I'm storing in the session if the user has chosen to collapse the sidebar. 

```html
<div x-data="initLayout()">
    <div class="sidebar" wire:model>
      <div @click="toggleSidebar(@this)">Sidebar</Sidebar>
    </div>
</div>
<script>
function initLayout() {
  return {
    sidebar: true,
    toggleSidebar(wire) {
      this.sidebar = !this.sidebar
      wire.call('persistSidebaroggle', this.sidebar)
    }
  }
}
</script>
```
and in the Livewire component:

```php

   public function persisSidebar($value)
   {
       // do what you want with the value past from front-end (alpine).
   }
```

When Livewire renders the component all instances of `@this` is effectively replaced with an object that lets you e.g. `call`, `get`, and `set` values on the Livewire component through the JS API.

This isn't listening in the traditional sense, but it gets the job done in my case. I'm not aware of any other way.

**Comment by GertjanRoke** [comment]
Hello @mtctonyhkhk2010, maybe this could solve you’re problem.

https://laravel-livewire.com/docs/events#in-js

PS I never used it but looking at the docs I think this is what you are looking for.

**Comment by mtctonyhkhk2010** [comment]
> 
> 
> Hello @mtctonyhkhk2010, maybe this could solve you’re problem.
> 
> https://laravel-livewire.com/docs/events#in-js
> 
> PS I never used it but looking at the docs I think this is what you are looking for.

Yea I know I can listen to event in the window.livewire object, but I tried to listen the same event inside a AlpineJS “component” and it doesn't work.

**Comment by GertjanRoke** [comment]
And you do that in the same way as the code snippet inside your initial post?

**Comment by mtctonyhkhk2010** [comment]
> 
> 
> And you do that in the same way as the code snippet inside your initial post?

Yes, I tried this:
```
<div>
  <input type="text" x-data x-on:somethingUpdated="foo = 'bar'">
</div>
```

and this:
```
<div>
  <input type="text" x-data x-on:window.livewire.somethingUpdated="foo = 'bar'">
</div>
```

Both don't work, nothing happened.

**Comment by GertjanRoke** [comment]
Thanks for sharing, but the `x-on` is for adding event listers on the element itself, not for listening for events on the `window` level.

So I tried it also for my self and this is the way to go:
```html
<div x-data="{ foo: 'bar' }" x-init="() => {
    window.livewire.on('somethingUpdated', () => {
        foo = 'baz'
    })
}">
    <input type="text" x-model="foo"/>
</div>
```

When you do this you shall see that it changes when the event is fired.
If you want to see it in action, I'm starting on building a repo with a lot of examples of all the issues I'm helping on and here you can see how I implemented it when testing this problem you are having.
https://github.com/GertjanRoke/livewire-examples/commit/149c9c0b4a046c53c379d6da023642ca99f2103c

**Comment by muzafferdede** [comment]
An example scenario for those who need:

PHP Livewire Component
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Listener extends Component
{
    public $name = 'Livewire';

    protected $listeners = ['change-name' => 'changeNameAndForwardToAlpine'];

    public function render()
    {
        return view('livewire.listener');
    }

    public function changeNameAndForwardToAlpine()
    {
        $this->name = 'Alpine';
        $this->dispatchBrowserEvent('name-changed',['name'=>$this->name]);
    }
}
```
Alpine + Livewire blade component as:

```php

<div x-data="{name:'{{ $name }}'}">
    <button wire:click="$emit('change-name')">
    <span @name-changed.window="name = $event.detail.name" x-text="name"></span>
</div>
```

So, using  `dispatchBrowserEvent` Alpine is able to listen to events and act on them.

**Comment by GertjanRoke** [comment]
There is also one in the link I shared, but cool to see that this is also an option that works!

Thanks @muzafferdede

**Comment by mtctonyhkhk2010** [comment]
> ```
> dispatchBrowserEvent
> ```

Thank you. Didn't know this method exist. It's not in the docs.

Also, may i ask why there is a `.window` after the event name?
I tried and it seems `.window` is needed to make it work correctly.

**Comment by muzafferdede** [comment]
`.window` is a modifier. The attribute pattern is like this: 
`[directive]:[event].[modifiers]`
and `@` used to be alias for `x-on:` so the full pattern become in the example above:
`x-on:click.window` as read as listen the click event on window object since it will bubble up to window.

**Comment by lancepioch** [comment]
Thanks a lot for the help guys!

**Comment by LaaHudra** [comment]
You can use now:
`$this->dispatchBrowserEvent('eventName');`

and then:
```
<script wire:ignore>
            document.addEventListener('eventName' ,....)
</script>
```
