### ISSUE TITLE
Why does Livewire's response include debug information when rendering a page?

### ISSUE THREAD

**Issue by wanhouchao** [livewire/livewire#8316]
### Discussed in https://github.com/livewire/livewire/discussions/8315

<div type='discussions-op-text'>

<sup>Originally posted by **wanhouchao** April 17, 2024</sup>

![image](https://github.com/livewire/livewire/assets/54433336/7282e23b-0020-47b9-a1eb-d470df03cd6d)

</div>
![image](https://github.com/livewire/livewire/assets/54433336/b98c3462-498c-4708-98b0-ace020d8f066)

**Comment by PhiloNL** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
