### ISSUE TITLE
Allow redirect from render() method

### ISSUE THREAD

**Issue by rosswintle** [livewire/livewire#832]
**Is your feature request related to a problem? Please describe.**

I'm building a clone of Cards Against Humanity in LiveWire. Several people will be connected to a `/game/{game}` route at a time and I'm using `wire:poll` to refresh their view of the game. Livewire is AMAZING for this.

But there comes a time at the end of a "round" of the game where a winning card has been chosen and I want all players to be sent to a different screen through the `wire:poll` action.

If I put a redirect in the `render()` method I get:

`"render" method on [App\Http\Livewire\Game] must return instance of [Illuminate\View\View]`

If I put a redirect in the `mount()` method then the whole page has to be properly reloaded to get the redirect.

**Describe the solution you'd like**

I'd like to be able to put a redirect in the `render()` method of a component so that a component using `wire:poll` can automatically redirect the user to a certain route when a particular condition is met.

**Describe alternatives you've considered**

I tried putting the redirect in the `mount()` method, but this requires a manual page reload.

I considered putting the redirect in the the controller that loads the view that contains the component, or just loading a different view from the controller, but this also would require a manual page reload.

I considered emitting an event but this would only affect the player clicking the button to initiate the event.

I can show a button to all users when this condition is met and they can click this to manual reload, this works as a workaround but I'd rather it happen automatically on poll.

I could not think of a way to allow player 2 to get redirected based on some action taken by player 1 when I'm `wire:poll`'ing for updates.

**Additional context**
Caleb built a Disney quiz app so I figure he must have done something like this. I'm pretty sure this request can be fulfilled by an already-existing feature of Livewire, but I have no idea what it is. I'm happy to take some guidance. OR maybe you think I should be able to redirect from `render()`?

**Comment by GertjanRoke** [comment]
I should say give the `hydrate` method a go.
This method gets run before any action or the render function.
I didn’t tested if it works, but maybe this can solve you problem.

**Comment by rosswintle** [comment]
I didn't test `hydrate`, but I did find a workaround with events.

I now have a render method that does:

```php
    public function render()
    {
        if ($this->game->round_complete) {
            $this->emit('concludeGame');
        }
        return view('livewire.game');
    }
```

and an event listener in JS:

```javascript
        <script>
            window.livewire.on('concludeGame', postId => {
                window.location='/game/' + {{ $game->id }} + '/conclude-round/';
            });
        </script>
```

But it kinda felt intuitive that I should be able to return a redirect from my render method and have this done for me. So I still hope it will be considered as an enhancement.

**Comment by nuernbergerA** [comment]
### Feature Request
`render()` should accept a `view` or `redirect`

**Comment by austenc** [comment]
@rosswintle 
There are two ways you might solve this issue: 
- Use a specific method when polling to do the redirect (instead of in `render`) -- `wire:poll="foo"`. Then do the redirect in there
- Utilize the `$this->redirect()` method in the render function, instead of the helper.

**Comment by rosswintle** [comment]
Thanks, @austenc  - will look into these options!

**Comment by mitchjam** [comment]
@austenc @calebporzio can this be closed?

**Comment by austenc** [comment]
Seems like this is something people would expect Livewire to support. That being said, perhaps support for redirects could be improved (and made more cohesive) within Livewire.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by torian257x** [comment]
REOPEN

**Comment by DanielCoulbourne** [comment]
> @rosswintle There are two ways you might solve this issue:
> 
> * Use a specific method when polling to do the redirect (instead of in `render`) -- `wire:poll="foo"`. Then do the redirect in there
> * Utilize the `$this->redirect()` method in the render function, instead of the helper.

Shout out Austin from 2020. A true king among men.
