### ISSUE TITLE
emitSelf is missing in the window.livewire object

### ISSUE THREAD

**Issue by mtctonyhkhk2010** [livewire/livewire#833]
**Describe the bug**
There is a `emitSelf `method in the doc, however the `emitSelf ` method is missing in the window.livewire object. Only `emit `and `emitTo `are exist.

**To Reproduce**
1. open devtools
2. type window.livewire in console
3. no emitSelf method can be found

**Expected behavior**
`emitSelf `method exist in the window.livewire object.

**Additional context**
livewire v1.0.12

**Comment by devcircus** [comment]
To me, emitSelf doesn't make sense on the global livewire object. It requires a component for context.

**Comment by mtctonyhkhk2010** [comment]
> 
> 
> To me, emitSelf doesn't make sense on the global livewire object. It requires a component for context.

I am having a situation that I have a list of nested components:
```
@foreach($item in $items)
    @livewire('item-handler', $item , key($item->id))
@endforeach
```

Inside each `item-handler` view, I have some event to emit back to the component itself, so I register a listener in the `item-handler` component. However, when a event is sent, all `item-handler`s in the list response to the event. What I wanted is, only the `item-handler` component that the user interacting to response, and i find out the `emitSelf ` method is missing.

The current workaround for the problem is, I also emit the key of the item so that I can check the origin of the event. But I wish there is a easier way to handle that.
Thanks.

**Comment by lancepioch** [comment]
We are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. If you still feel this is relevant, please create a discussion there, thanks a bunch!
