### ISSUE TITLE
Double Entry in DB when using Create() or Save() method

### ISSUE THREAD

**Issue by TechTailor** [livewire/livewire#834]
**Describe the bug**
When using the create() or save() method inside a livewire component, the action is storing double entries (of the same data) in the DB.

**To Reproduce**
1. Create a component with form.
2. Use create() or save() method to store the record in db.

**Expected behavior**
A single entry to be added to the DB for the model.

**Desktop (please complete the following information):**
 - Browser [chrome & safari] in localhost using XAMPP

**Using**
-> Laravel 7.x

**Additional context**
Here's the component in use - 
```
<?php

namespace App\Http\Livewire;

use Auth;
use App\Announcement;
use Livewire\Component;

class AddAnnouncement extends Component
{
    public $body;

    public function add()
    {
        $messages = [
            'body.required' => 'Announcement Message is required.',
            'body.max' => 'The announcement can only be 245 characters long.'
        ];

        $this->validate([
            'body' => 'required|max:245'
        ], $messages);

        Announcement::create(['body' => $this->body, 'user' => Auth::user()->first_name]);

        session()->flash('success', 'Announcement Added Successfully');
        return redirect()->route('index');
    }
    
    public function render()
    {
        return view('livewire.add-announcement');
    }
}
```

**Comment by TechTailor** [comment]
Same issue is occurring when using Auth::attempt() inside a livewire component (ends up firing the LoginSuccessful event twice).

**Comment by GertjanRoke** [comment]
Could you also add the content of the blade file? This would gives an better understanding of the situation. Thanks

**Comment by ducopro** [comment]
Are you working with browsersync? And maybe you have two tabs open in your browser??

**Comment by TechTailor** [comment]
Well I have tested with Chrome and Firefox (with Incognito aswell) and single tabs only. Not using browsersync. 

Here's the component file - 
```
<form wire:submit.prevent="add">
    @csrf
    <div class="card card-primary" style="margin-bottom:0px">
        <div class="card-header">
            <h4 class="text-primary">Add New Announcement</h4>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label>Message <small class="text-danger">*</small></label>
                <div class="input-group">
                    <input type="text" wire:model.lazy="body" class="form-control {{ $errors->has('body') ? ' is-invalid' : '' }}" placeholder="Type a message" name="body" id="body">
                </div>
                @error('body') <span class="error text-danger">{{ $message }}</span> @enderror
            </div>
        </div>
    </div>
    <div class="modal-footer bg-whitesmoke">
        <button type="submit" wire:click="add" class="btn btn-primary btn-shadow"><i class="fas fa-plus"></i> Add Announcement</button>
    </div>
</form>
```
So I've tried with this as well as creating new component following step by step from the docs, all entries as get created twice. (Tried using livewire for login using Auth::attempt(), ends up firing the LoginSuccessful event twice (since my activity logger listens for that event, entries are duped).

**Comment by GertjanRoke** [comment]
Remove the wire:click from the button, this is causing you the problem.

Because it’s also called on the form and if you also call it from a click event from the button it’s fired twice.

**Comment by TechTailor** [comment]
Well. This was an oopsie. Mixed up and combined stuff from 2 different docs. Feel so dump rn that I wasted so much time and didnt even notice that.

 Thanks for the help.  <3

**Comment by GertjanRoke** [comment]
No problem, we all have that sometimes! Good luck with coding 👋

**Comment by paulabhishek** [comment]
Here's my blade I'm having the same issue of duplicate enter in the DB.


<div>
@include('includes.header')
<div class="container mt-5">
	<h2>Order Form</h2>

	<form method="POST" action="/new-order" enctype="multipart/form-data" wire:submit.prevent="save">
		@csrf
		
		<div class="mb-3 ">
			<label for="customers_ID" class="form-label"> Customer ID</label>
			<input wire:model="customers_ID" type="number" class="form-control" wire:model.live="customers_ID">
			<div>
				@error('customers_ID') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>

		
		<div class="mb-3 ">
			<label for="placeDate" class="form-label">Place Date</label>
			<input wire:model="placeDate" type="date" wire:live="search" name="placeDate" class="form-control" id="placeDate">
			<div>
				@error('placeDate') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>

		
		<div class="mb-3">
			<label for="totalPrice" class="form-label">Total price</label>
			<input wire:model="totalPrice" type="number" name="totalPrice" class="form-control" id="totalPrice" >
			<div>
				@error('totalPrice') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>

		
		<div class="mb-3">
			<label for="customerMaterial" class="form-label">Customer Material</label>
			<input wire:model="customerMaterial" type="file" name="customerMaterial" class="form-control" id="customerMaterial">
			<div>
				@error('customerMaterial') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>

		
		<div class="mb-3">
			<label for="dueDate" class="form-label">Due Date</label>
			<input wire:model="dueDate" type="date"  wire:model="dueDate" name="dueDate" class="form-control" id="dueDate">
			<div>
				@error('dueDate') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>

		
		<div class="mb-3">
			<label for="orderNotes" class="form-label">Order Notes</label>
			<textarea  wire:model="orderNotes" type="text" name="orderNotes" class="form-control" id="orderNotes" placeholder="Enter additional Notes"></textarea>
			<div>
				@error('orderNotes') <span class="error">{{ $message }}</span> @enderror
			</div>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>

@include('includes.footer')
</div>
