### ISSUE TITLE
wire:model data binding not working with an inline component

### ISSUE THREAD

**Issue by dvplex** [livewire/livewire#835]
I am trying to recreate a simple reactivity with an inline component, but it's not working.

Here is my component:

namespace App\Http\Livewire;

use Livewire\Component;

class Search extends Component {
	public $search;
	public function render() {
		return <<<'blade'
		<div class="input-search input-search-dark">
			<i aria-hidden="true" class="input-search-icon fas fa-search ml-3"></i> 
			<input type="text" wire:model="search" class="form-control" placeholder="Search...">
		</div>
		<div>This is from search {{ $search }}</div>
blade;
	}
}
I see the Xhr request and a response, but the {{ $search }} variable isn't reactive.
Here is the response of the XHR:

{"id":"fMSqlfgI2MRPXRxDk738","name":"search","dom":"<div wire:id=\"fMSqlfgI2MRPXRxDk738\" class=\"input-search input-search-dark\">\n\t\t\t<i aria-hidden=\"true\" class=\"input-search-icon fas fa-search ml-3\"><\/i> \n\t\t\t<input type=\"text\" wire:model=\"search\" class=\"form-control\" placeholder=\"\u0422\u044a\u0440\u0441\u0435\u043d\u0435...\">\n\t\t<\/div>\n\t\t<div>This is from search adadadadd<\/div>","fromPrefetch":false,"redirectTo":false,"children":[],"dirtyInputs":[],"data":{"search":"adadadadd"},"eventQueue":[],"dispatchQueue":[],"events":[],"checksum":"894ebe390e9117331943266577da420992d20bcb19c87aa5424600d5a9ea272f"}

When the component isn't inline, there is no problem.

Cheers!

**Comment by calebporzio** [comment]
It's hard to understand your problem, but the following code works great:

```php
class Search extends Component
{
    public $search = '';

    public function render()
    {
        return <<<'blade'
            <div>
                Search is: {{ $search }}

                <input type="text" wire:model="search">
            </div>
        blade;
    }
}
```

**Comment by gearias** [comment]
I had the same problem. You should use a <div> element and put the other elements inside. (Sorry if my english is so bad).

**Comment by akii09** [comment]
yes @gearias  you are right
