### ISSUE TITLE
Payload value isn't sent in Internet Explorer 11

### ISSUE THREAD

**Issue by chrisrhymes** [livewire/livewire#836]
**Describe the bug**
When a model is updated the actionQueue[0].payload.value isn't sent when using IE11. The name of the model is set correctly but the value is missing from the payload object. 

For reference, I had to add a polyfill for `fetch` (using whatwg-fetch) and `prepend` from [MDN Webdocs](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend#Polyfill) for Livewire to work with IE11. 

**To Reproduce**
1. Create a text input with a wire:model, such as 'title', in a livewire blade view. 
2. Type a value into the input
3. A 500 error is returned

`[2020-04-20 10:32:29] local.ERROR: Undefined index: value {"userId":xx,"exception":"[object] (ErrorException(code: 0): Undefined index: value at project-path/vendor/livewire/livewire/src/HydrationMiddleware/PerformPublicPropertyFromDataBindingUpdates.php:14)`
4. The payload sent does not contain `value`

```
"actionQueue": [
    {
        "type": "syncInput",
        "payload": {
            "name": "title"
        }
    }
]
```

**Expected behavior**
The value for title model should be sent in the request

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Internet Explorer 11

**Additional context**
Looking through the JavaScript I can see it gets the value for each model in `dom_element.js` but I can't see any reason why it wouldn't get the value.

**Comment by chrisrhymes** [comment]
It seems that this is caused by IE11 always returning true for `e instanceof CustomEvent` in 'js/node_initializer.js' line 62 so it tries to return `e.detail` which is undefined, instead of the value from the input.

```js
const value = e instanceof CustomEvent
                ? e.detail
                : el.valueFromInput(component)
```

**Comment by lancepioch** [comment]
Thanks for the contribution!
