### ISSUE TITLE
Inline Javascript On Nested Component

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#839]
Hello,

I have a parent component that cycles through subcomponents. My issue is that some of the subcomponents types require some Javascript to function: https://codepen.io/jjjrmy/pen/GRpqLEZ

No matter what I’ve tried I cannot get the scripts to run as they are added to the page later when that component is called.

I found this doc but it’s not working for my use case: https://laravel-livewire.com/docs/inline-scripts/

`Please note that your scripts will be run only once upon the first render of the component. If you need to run a JavaScript function later - emit the event from the component and listen to it in JavaScript as described here)`

The scripts only seem to work if the component is active during first render. I have tried adding a trigger inside the nested component to run it’s own script but that also does not work.

Is the only solution to put all the required scripts inside an `app.js` file and call it from an emit?

**Comment by jjjrmy** [comment]
I've been playing around with it some more and it seems like it's not possible to run the `$this->emit()` in the `mount()` or `render()` functions.

**Comment by jjjrmy** [comment]
The`@push('scripts')` doesn't work at all if the component is not loaded on render.

**Comment by indigoram89** [comment]
+1

**Comment by jjjrmy** [comment]
I think this is a bug not a question?

**Comment by lancepioch** [comment]
You are right and this should be resolved with #954!
