### ISSUE TITLE
protected $updatesQueryString doesn't work with computed property

### ISSUE THREAD

**Issue by AshishDhamala** [livewire/livewire#840]
How do you show a computed property in a query string?

**Screenshots**
![image](https://user-images.githubusercontent.com/16821597/79833236-bc0fb580-83ca-11ea-9e23-c147cd871ad3.png)

- Browser [chrome]
- Laravel 6.16.0

**Comment by lancepioch** [comment]
Make the tag slut filter its own public variable.

**Comment by lancepioch** [comment]
Make the tag slug filter its own public variable. Let me know if that doesn't work.
