### ISSUE TITLE
Datepicker With livewire not working even after following livewire instructions here https://laravel-livewire.com/docs/third-party-libraries/

### ISSUE THREAD

**Issue by abrardev99** [livewire/livewire#844]
I'm using bootstrap DateTime picker lib in Laravel and Livewire. I follow all the instructions declared in livewire docs. and still, it is not setting date. 

Here is my code 
**Input**
```
<div wire:ignore>
     <input placeholder="Select Date" id="name" type="text" class="datetimepicker form-control @error('date') is-invalid @enderror" name="date" >
</div>
```
                        
**Input change event**
I have public date property in the livewire component. 

```
 $('.datetimepicker').on('change', function (e) {
            @this.set('date', e.target.value);
            });
```

**error** 
`Uncaught SyntaxError: Invalid or unexpected token at  @this.set('date', e.target.value)
`

**RESULTS**

date public property remains null.

**Comment by abrardev99** [comment]
Issue resolved. to work with it, it the input change event should be in component div.

**Comment by bryanbelardo** [comment]
Hi. I have the same problem on datepicker on laravel livewire it seems that livewire model can't get the data from datepicker plugin.
I solve it by using the normal input type="date".
Hope this helps. 👍

**Comment by vahnmarty** [comment]
> I solve it by using the normal input type="date".

`[type="date"]` does not work on Safari.
