### ISSUE TITLE
Component Key ID for $emitTo, like: $emitTo('order-item', {{ $order->id }}, 'eventName', params...)

### ISSUE THREAD

**Issue by basepack** [livewire/livewire#845]
**Is your feature request related to a problem? Please describe.**
- I got a long list of Livewire components **(list-item)** think a long table. 
- Each individual list-item component has a good bunch of markup, so its HTML heavy
- When I do a `EmitTo('list-item')` kind of event, _**they all reload :astonished:**_, so in my case 300 XHR calls are made in the background.

**Describe the solution you'd like**
Well... consider this beauty: 
```
$emitTo('component', 'componentID', 'eventName', params...)
```

And with `componentID` I mean the given key. For example`:key="$order->id"`, and **not** the random id's Livewire assigns, like `wire:id="ZnmQ6dpTXFtk5a1C2v2H"`.

So the end result could be:
```
$emitTo('order-item', {{ $order->id }}, 'refresh')
```

**Comment by mblarsen** [comment]
I was think of a similar use case. A have a survey form builder with lots of questions. Questions has an input put type, think widgets. When you select the type question component emits to a “singleton” type selector catalog component to present itself. Question ID included in event. Once the user selects the question type a second event is emitted, say “type selected”. Like you I have narrowed it down with emitTo question component. But there are just too many and all of them have to check if they are the question that initiated the type selector. 

So the pattern is:

1. Emit to start something 
2. Emit to get a reply back

I’m not sure how similar this is to your case. Anyway, I imagined an api like:

Initial event passes a specific Livewire token data type which is both stored in session and included in payload to browser. 

```php 
emit(“typeRequested”, Livewire::token(“question-type”))
```

Anyone listening to the event can store the token and later use it to “call back” or “reply to” the token owner. 

```
emitTo(“#question-type”, “typeSelected”, $selected);
```
(The hash-sign denotes a token rather than a component name)

So only one component needs update and on the plus side you don’t need to know the component ID.

Issues: 

- multiple use of same token (solution: last issuer wins or let Livewire pack and unpack a counter)
- multiple calls to same token (solution: ignore, fail?)

Was going to try to make a PR for this, but love to get your input the use case.

**Comment by basepack** [comment]
Well, in my use-case I want Livewire to be able to callable on their keys. Because the key is something that is known. The generated Livewire token is not actually.

So you create a bunch of components like this:

```
@foreach($this->orders as $order)
      <livewire:order-item :order="$order" :key="$order->id"/>
@endforeach
```

See the `:key` there. That is what you an I know. So now we should be able to:

In the component (PHP):
 ```
$this->emitTo('order-item', $order->id, 'doSomething', 'params')
```

In the blade file (Alpinejs/Livewire):
```
// Alpinejs
window.livewire.emitTo('order-item', {{ $order->id }}, 'doSomething', 'params');

// Livewire
<div wire:click="$emitTo('order-item', {{ $order->id }}, 'doSomething', 'params')">Click me</div>
```

So basically, from every order item, I could call another order item, if I only knew its id. This is very powerful and lifts the boundaries created by the Livewire tokens.

FYI, currently I have a workaround for, in this case, showing a modal outside the above shown loop. I **had to show the modal outside the loop** for performance optimization.
1) Supply the Livewire id (token) with an event: 
```
// Called from within the loop shown above
// {{ $this->id }} = Livewire generated token NOT the $order->id
wire:click="$emitTo('order.modal-payment', 'showModal', '{{ $this->id }}')
``` 

2) Set this id on the modal component:
```
public function showModal( $orderItemLivewireId, $otherParams )
{
    $this->orderItemLivewireId = $orderItemLivewireId;
}
```

3) Update the blade file to access this via Alpine:
```
<button class="gr-orange-button" x-on:click="open = false; window.livewire.find( '{{ $this->orderItemLivewireId }}' ).call('setPaid', false)">
         Set unpaid
</button>
```

4) Handle the event `setPaid` on the correct OrderItem component. So only one order-item is refreshed, and not all 1000 of them which is like a DDOS attack.

But in the above approach you will likely drain in issues like Alpine not registering events and Livewire incorrectly diffing the DOM and more fun stuff.

So if you can PR something to fix issues like this, that would be awesome!

**Comment by roni-estein** [comment]
I may have read this wrong but basically you have a list of elements and you want to trigger an event that is only responded to by the current component and not everyone in the list.
  

  
I’m on a mobile and search is not accessible but have you considered emitSelf? Or emitting to the parent component to handle it?
  

  
https://laravel-livewire.com/docs/events
  

  

  

 There is also a nested components video that deals with this on the screen casts.
  
  

  
  
>

**Comment by basepack** [comment]
@roni-estein thanks for stepping in! But no, that is not what we try to deal with here. 

It is about externally call a component by its key, and not by its random Livewire id/token

**Comment by roni-estein** [comment]
@basepack ouch the infamous "thanks for coming out" :) Sorry it was early, and I must have misread the intent before my coffee.  I hope you get it sorted out.

**Comment by basepack** [comment]
@roni-estein well the suggestion of raising the event to the parent was not bad at all, you could route events like that and the children will not reload. 

In this context it wouldn't work, but be assured we all have our 'before coffee' moments! 😁

**Comment by mblarsen** [comment]
@basepack I've implemented a version now that works a bit like this:

**My case with modal**
(no alpine needed)

```php
// Quesiton component (child of which there are many)
public function create()
{
    ...
    $this->emit('requestType', 'aParam', Token::for('typeSelected'), 'anotherParam');
}
```
The token is an object that in addition to the string knows `$this->id`. When Livewire dehydrates the event queue the object is "flattened" and the token is added to a `tokens` in the payload.

Then somewhere else you can refer to `Token::for('typeSelected')` but this time use `emitTo`:

```php
// Question type selector modal
protected $listeners = ['requestType'];

public function requstType($aParam, $anotherParam)  // Note: no values are passed about the token
{
   $this->open = true;
}

public function selectType($type_id) 
{
    $this->emitTo(Token::for('typeSelected'), $type_id);
}
```

As a result only one Question component is notified of the change. You don't have to set up special listeners. Adding the token is enough. You can add as many as you want.

```php
// Back in the Question component time to receive.

public function typeSelected($type_id)
{
    ...
}
```
If you want you can set up a specific listener where the event is the token name. But the above works without setting `$listeners`.

---

**Your case (as I've understood it)**

As far as I could tell you have may siblings that needs to communicate with each other, correct?

Tokens can be named anything so basically you could create one for each of your list items, e.g. `Token::for("eventName_". $item->id)`. The `$listeners` scheme won't work for this setup, so my thought was to add a kind of catch all `handleToken($token_name, ...$params)`.

However, in your case I'm not sure your trigger an event to begin with? Is it a two step process? I don't think so from re-reading your example. But the same approach can work, as long as we stick tokens in the payload. Then you don't have to worry about IDs and you should be able to do:

```php
// not
$emitTo('order-item', {{ $order->id }}, 'refresh')

// but
$emitTo('token#refreshOrderItem{{ $order-id }}')
// or from component
$this->emitTo(Token::for('refreshOrderitem'.$order->id))
```

So not a perfect fit for your case. I haven't looked into using keys yet. Maybe that has something too it. 

But at any cost it is really nice to be able to write pure Livewire without custom/hackish Aipline to ensure only one of may of a kind is updated. :)

**Comment by basepack** [comment]
@mblarsen this is actually genius! Sorry for my late response, was working on another project in the meantime. 

I also prefer the full PHP method, and to not have this logic in a Blade file with Alpine if possible.

To answer your first question, not only child -> child communication, but also a parent -> child communication path. Just to be able to only notify one child from whichever location that may be.

It is possible to see a more complete example of your Token usage? Because I have some questions left:
1) in your create() method, will every `emit` there reload the parent Livewire? Because in that case, all children will reload to if am not mistaken?
2) the `selectType()` method is just an action right? Which you fire on the parent component is I am correct?

On your next question: I trigger an event on a button click on a child element. That event will open an external modal component which has then to talk back to this child component. In my case I want to refresh the child component that initiated that modal.

All in all, this is in my case a doable approach and I will sure test this out to the detail with the next refactor.

**Comment by mblarsen** [comment]
> It is possible to see a more complete example of your Token usage? Because I have some questions left:
> 
>     1. in your create() method, will every `emit` there reload the parent Livewire? Because in that case, all children will reload to if am not mistaken?

No, Livewire works a bit different from other web frameworks. When you refresh the parent the children or not updated. (unless what build them changes of course).

>     2. the `selectType()` method is just an action right? Which you fire on the parent component is I am correct?

Yes, this is just an example action on my component.

> On your next question: I trigger an event on a button click on a child element. That event will open an external modal component which has then to talk back to this child component. In my case I want to refresh the child component that initiated that modal.

This is the same use case I'm working with.

Will the PR is working now, I'm about to try to refactor it in order to have a higher change of getting it merged at some point.

Thanks for your feedback :smile:

**Comment by calebporzio** [comment]
Thanks for the good input @mblarsen.

For now, I don't think we are going to add any new API for these cases (will consider it for the next major version (V2)).

However, I do recommend emitting event names WITH some unique ID that ONLY one specific child is listening for.
This is simple to do by registering dynamic listeners in the children using `protected function listeners()`.

Hopefully this makes sense.

I'm going to close this for now. 

Thanks everyone for weighing in.

**Comment by basepack** [comment]
@calebporzio this is actually a very nice approach which I did not think about. 

Shouldn't this be documented in the Livewire docs? If so, I can make a PR for that. 

Because targeting a single component out of a list 300, is very handy for the load of the webserver and the reactivity of the UI.

**Comment by mjerwin** [comment]
For anyone new coming across this, I've written a new blog post describing the solution of using a single event per component.

[https://www.matthewerwin.co.uk/blog/single-component-events-in-laravel-livewire](https://www.matthewerwin.co.uk/blog/single-component-events-in-laravel-livewire?utm_source=github&utm_campaign=livewire/livewire/issues/845)

**Comment by MDGDesign** [comment]
Thanks @mjerwin !
This solution works great.

Suggestion to add this to the Livewire Docs as a specific use case.
The one in the events page https://laravel-livewire.com/docs/2.x/events#event-listeners skipped my reading.

Special thanks for @calebporzio for this great package

**Comment by caolier** [comment]
Hi!,
I found this for calling a specific Id component in livewire. It's ok?
`$this->emit('postAdded'.$post_id, $params);`

[https://laracasts.com/discuss/channels/livewire/use-listeners-from-a-trait](url)
```
public function getListeners()
{
return $this->listeners + [
'postAdded'.$this->post->id => 'incrementPostCount',
];
}
```

**Comment by joshhanley** [comment]
@caolier yep! If it works for your needs, then use it 🙂
