### ISSUE TITLE
Throw friendly message if root element doesn't exist

### ISSUE THREAD

**Issue by beganovich** [livewire/livewire#848]
**Describe the bug**
If we don't have parent `<div>` or other element, unfriendly error will be thrown.

**To Reproduce**
1. Make Livewire component
2. Remove parent div element
3. Get: `Undefined offset: 1..` 

**Expected behavior**
Throw an error with friendly message.

**Desktop (please complete the following information):**
 - Any, it's backend, PHP issue.

**Additional context**
```php
ErrorException (E_ERROR)
Undefined offset: 1 (View: /home/benjamin/..)
```
Line of code that is causing error: https://github.com/livewire/livewire/blob/master/src/HydrationMiddleware/AddAttributesToRootTagOfHtml.php#L17

Note: I can send PR fixing this if you think its necessary.

**Comment by baoanhng** [comment]
Sure just go ahead. I think it is necessary and will help debugging a lot.

**Comment by DanHarrin** [comment]
Added in #946.
