### ISSUE TITLE
ErrorException: Undefined offset: 0 in view from vendor/livewire/livewire/src/ComponentConcerns/TracksRenderedChildren.php on line 12

### ISSUE THREAD

**Issue by colinmac17** [livewire/livewire#850]
**Describe the bug**
I have a livewire component that has a collection of tasks. When a new task is added, edited or deleted with an action,  I emit an event to refetch the tasks. When I added a loop that helps determine which edit view to show with the help of alpine I am running into a weird issue when adding the first task.

So my current count of tasks is 0, I try to add the first 1 and I run into an issue when (I believe) the event is emitted because when I remove the event I do not run into the 500.

Here is my code: https://gist.github.com/colinmac17/e1a6f9afde97f05c06a8a17e60b68af3

Here is a video of what is happening: https://www.loom.com/share/0ac9d46ac13a4f8fa962719e22c9c0d1

1) the saveTask method is called from my NewTask livewire component.
2) saveTask emits the showSavedTasks event on the Process component which should rerender the new task (now with a $tasks->count() = 1). I have confirmed that the count is 1 but I am running into the offset 0 error only when adding the first task. After that it is ok.

The issue is from the addition of this foreach:
`<div class="shadow overflow-hidden px-4 py-5 sm:p-6" x-show="state === 'edit'" id="newTaskContainer">
                    @foreach($tasks as $task)
                        <div wire:key="{{ $loop->index }}" x-show="state === 'edit' && taskToEdit === {{$task->id}}">
                            @livewire('edit-task', ['task' => $task], key($loop->index))
                        </div>
                    @endforeach
                </div>`

I tried following https://laravel-livewire.com/docs/troubleshooting and still no luck. I am hoping someone can spot a simple mistake I am making because I am sure I am at fault or that I am using Livewire wrong.

Here is the stack trace.
`ErrorException: Undefined offset: 0 (View: /Users/colinmcatee/dev/productiverecruit/resources/views/livewire/process.blade.php) in file /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/ComponentConcerns/TracksRenderedChildren.php on line 12

#0 /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/CompilerEngine.php(38): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/LivewireViewCompilerEngine.php(52): Livewire\CompilerEngine->handleViewException(Object(ErrorException), 1)
#2 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Livewire\LivewireViewCompilerEngine->evaluatePath('/Users/colinmca...', Array)
#3 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\Engines\CompilerEngine->get('/Users/colinmca...', Array)
#4 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#5 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#6 /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/Component.php(130): Illuminate\View\View->render()
#7 /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(29): Livewire\Component->output(Object(Illuminate\Support\ViewErrorBag))
#8 /Users/colinmcatee/dev/productiverecruit/vendor/livewire/livewire/src/Connection/HttpConnectionHandler.php(11): Livewire\Connection\ConnectionHandler->handle(Array)
#9 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\Connection\HttpConnectionHandler->__invoke('process')
#10 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(225): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Livewire\Connection\HttpConnectionHandler), '__invoke')
#11 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(182): Illuminate\Routing\Route->runController()
#12 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#13 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#30 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /Users/colinmcatee/dev/productiverecruit/app/Http/Middleware/Cors.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/colinmcatee/dev/productiverecruit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/colinmcatee/dev/productiverecruit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /Users/colinmcatee/dev/productiverecruit/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 /Users/colinmcatee/.composer/vendor/laravel/valet/server.php(158): require('/Users/colinmca...')
#46 {main}`

**Expected behavior**
I expect for the component to be rerendered with the first task showing.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: chrome 80

**Additional context**

**Comment by muzafferdede** [comment]
the event you are listening via Alpine is camelcase. As far as i know, you can't use camelcase.

```js
                taskListener(){
                    this.$el.addEventListener('taskSaved', (event) => {
                        this.updateState('display')
                    })
                }
```
might be related to that. Try to use `task-saved` instead. 

Another thing is, since you use `$this->dispatchBrowserEvent('taskSaved');` on Alpine side, you can listen for that event after you change it to 
`$this->dispatchBrowserEvent('task-saved');`
`@task-saved="//do your thing"`
or
`x-on:task-saved="//do your thing"`

Let me know if any result.
Good luck

**Comment by k-bon** [comment]
@colinmac17 Were you able to resolve this issue? I have a very similar scenario and am running into the same error.

**Comment by ahinkle** [comment]
@k-bon  @colinmac17  same here-- might be unrelated and tied to a recent release. were you able to find a solution?

**Comment by MSnoeren** [comment]
@k-bon @ahinkle I've had this issue today and was able to resolve it. In my case, I used a integer as key (which @colinmac17 also has). After updating the component containing the child components I received the offset error too.

My solution was to update all `wire:key` or `:key` attributes and force it into being a string at all times.

`:key="$model->getKey()"` to `:key="(string) $model->getKey()"`.
