### ISSUE TITLE
Documentation defer-loading

### ISSUE THREAD

**Issue by jakjr** [livewire/livewire#852]
Is this right?

This can be helpful in cases where you don't want to hold up the entire page load, but want to load some data **immediately _after_ the page load**.

https://laravel-livewire.com/docs/defer-loading

Wouldn't be **immediately _beforer_ the page load**.

**Comment by mblarsen** [comment]
No, it is correct. The posts are loaded conditionally based on the value of `readyToLoad`. At first it’s false so the template renders zero posts. 

Then once rendered and displayed the JS side triggers an update to `readyToLoad` setting it to true. At this point render() runs again but includes the posts this time.

**Comment by lancepioch** [comment]
Looks correct, thanks Michael!
