### ISSUE TITLE
Select with array options random disappearance

### ISSUE THREAD

**Issue by roni-estein** [livewire/livewire#860]
**Describe the bug**
Select options randomly disappearing typically when moving back to the first element although not exclusively, If I add the `@dump($options)` at the front, somehow it resolves.

**To Reproduce**
create an component LSelect

Component
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class LSelect extends Component
{
    
    public $name;
    public $options;
    public $value;
    
    public function mount($name, $options, $default='')
    {
        $this->value = $default;
        $this->name = $name;
        $this->options = $options;
    }
    
    public function render()
    {
        return view('livewire.l-select');//->withOptions($this->options);
    }
}

```

create the view
```blade
<div>
{{--  @dump($options)--}}
  <label class="block mt-2">
    <div class="form-label">{{ $name }}: @error('.$name.')<br>{{ $message }}@enderror</div>
    <select wire:model.lazy="value" name="{{ $name }}" id="{{ $name }}"
            class="form-select block w-full @error('.{{ $name }}.') error @enderror">
      @foreach($options as $key => $option)
        <option value="{{ $key }}" {{ $value === $key ? 'selected' : '' }} >{{ $option }}</option>
      @endforeach
    </select>
  </label>

{{--  <pre class="">--}}
{{--    Name: {{ $name }}--}}
{{--    Key: {{ $key }}--}}
{{--    Option {{ $option }}--}}
{{--    Value: {{ $value }}--}}
{{--    $options: {{ print_r($options) }}--}}
{{--  </pre>--}}
</div>
```

**Expected behavior**
Just have it behave as if it were a non livewire element. Not loosing state.

**Screenshots**
[movies.zip](https://github.com/livewire/livewire/files/4520695/movies.zip)

**Desktop (please complete the following information):**
Brave Browser
Macos
Laravel 6.18.10

**Additional context**
I originally had these right on the main form but they did the same thing. I've tried to boil this down to as simple a problem as I could to figure out a fix. I've tried pushing options as just regular view data (making the array private and including it on the render, but after the first load it will loose state.

**Comment by roni-estein** [comment]
This isn't a bug, I needed to sleep on this. I want to add @calebporzio this is super sneaky, and should be in the docs. The problem was this.

`<option value="{{ $key }}" {{ $value === $key ? 'selected' : '' }} >{{ $option }}</option>`

`{{ $value === $key ? 'selected' : '' }}`this int the way wire:model works. You don't need a check, and in fact it breaks it. Probably some weird conflicting blade vs JS! However since we are all blade people and this is the defacto blade behavior. Along with just about every other language. We default to it. And the weird part is it sometimes works. So we think we are doing something right. Lastly unlike the input, the select is actually in a different visual space than the option.

A quick example of this issue is probably worth while in the docs, and would save someone the headache after.

so just for posterity and if anyone searches this in the closed items (like I did and didn't find one) here it is:

```blade
        <label class="block mt-2">
          <div class="form-label">Delivery: @error('pickup')<br>{{ $message }}@enderror</div>
          <select wire:model.lazy="pickup" name="pickup" id="pickup"
                  class="form-select block w-full @error('pickup') error @enderror">
            @foreach($pickupOptions as $key=>$option)
              <option value="{{ $key }}">{{ $option['text'] }}</option>
            @endforeach
          </select>
        </label>
```

**Comment by roni-estein** [comment]
Just a clarification that `$option['text']`came from the way I structured the data and has nothing to do with the solution. I just had a different example on hand and pasted that.

**Comment by indigoram89** [comment]
I have the same problem and I think it is not correct behavior.

With your solution we don't have a default select value rendered on the server. So we have a delay in the browser when the default value is not the first option.

**Comment by indigoram89** [comment]
Please check the six-seconds video where I just reload the page with a select which not contains default value rendered on the server: [https://youtu.be/gvOp4A8NyEw](https://youtu.be/gvOp4A8NyEw)

The JS sets the value in the browser and it causes a delay. Sorry for my English =)

**Comment by indigoram89** [comment]
But if I set a default value in the server side (as in your first example with option[selected]). So when I change the value and then return the first value back - the select is empty.

One more short video to demonstrate it: [https://youtu.be/-DC2HJCSwSg](https://youtu.be/-DC2HJCSwSg)

**Comment by indigoram89** [comment]
So if we do not set a default value on the server side - we have a delay on the client.
And if we have a default value on the server side - we have an empty value after change it.

So I think it is a livewire's bug?

**Comment by ChrisThompsonTLDR** [comment]
This is definitely a bug.  This only occurs with the first option is selected.  The DOM is updated to show the first option selected, but the rendered option text is empty.

If you set `wire:ignore` on the `<select>` everything functions correctly.  This indicates it's something happening during the redraw of the DOM.

The DOM that is returned from a `wire:model` update has the correction `<option>` marked as `selected="selected"`.

![livewire-select-bug](https://user-images.githubusercontent.com/348801/82605946-6292d600-9b84-11ea-9624-4fe6e177598d.gif)

**Comment by pvankouteren** [comment]
Having the same issue as Chris, but not only on the first item.

`wire:ignore` indeed solves it for now

**Comment by ChrisThompsonTLDR** [comment]
@pvankouteren I opened a new bug issue as this one is closed and will likely never be seen/addressed.

https://github.com/livewire/livewire/issues/998

**Comment by roni-estein** [comment]
Hi Guys, sorry after I closed the issue it looks like I didn't get notified of updates.
Can you post the code segment of your selects? and the blade segement?

I have multiple selects all over the place that are not having any issues, perhaps I can try and put you code on one of my components and see if I can catch what's happening for you.

**Comment by SanderMuller** [comment]
I experienced this as well, only after reading this issue I understand what is happening.
Wire model handles setting the selected item, while you're used to manually having to set the selected attribute on the selected option. Doing so causing a conflict with livewire which sometimes makes it glitch out so no option will be visually selected, despite the DOM showing the correct selected attribute.

**Comment by abrardev99** [comment]
> This isn't a bug, I needed to sleep on this. I want to add @calebporzio this is super sneaky, and should be in the docs. The problem was this.
> 
> `<option value="{{ $key }}" {{ $value === $key ? 'selected' : '' }} >{{ $option }}</option>`
> 
> `{{ $value === $key ? 'selected' : '' }}`this int the way wire:model works. You don't need a check, and in fact it breaks it. Probably some weird conflicting blade vs JS! However since we are all blade people and this is the defacto blade behavior. Along with just about every other language. We default to it. And the weird part is it sometimes works. So we think we are doing something right. Lastly unlike the input, the select is actually in a different visual space than the option.
> 
> A quick example of this issue is probably worth while in the docs, and would save someone the headache after.
> 
> so just for posterity and if anyone searches this in the closed items (like I did and didn't find one) here it is:
> 
> ```
>         <label class="block mt-2">
>           <div class="form-label">Delivery: @error('pickup')<br>{{ $message }}@enderror</div>
>           <select wire:model.lazy="pickup" name="pickup" id="pickup"
>                   class="form-select block w-full @error('pickup') error @enderror">
>             @foreach($pickupOptions as $key=>$option)
>               <option value="{{ $key }}">{{ $option['text'] }}</option>
>             @endforeach
>           </select>
>         </label>
> ```

this is really helping.

**Comment by ANDRU23** [comment]
> This is definitely a bug. This only occurs when the first option is selected. The DOM is updated to show the first option selected, but the rendered option text is empty.
> 
> This only impacts the first option with a value. If a "placeholder" option with `value=""` doesn't seem to be impacted.
> 
> If you set `wire:ignore` on the `<select>` everything functions correctly. This indicates it's something happening during the redraw of the DOM.
> 
> The DOM that is returned from a `wire:model` update has the correction `<option>` marked as `selected="selected"`.
> 
> I have confirmed this happening on both Firefox and Chrome.
> 
> ![livewire-select-bug](https://user-images.githubusercontent.com/348801/82605946-6292d600-9b84-11ea-9624-4fe6e177598d.gif)

This was the solution to the issue I was trying to solve for two days without find any documentation about it. Thank you so much!

**Comment by Emokores256** [comment]
But do we just set `wire:ignore=[name]` or we just insert `wire:ignore` as it is?

**Comment by Loukili-Rachid** [comment]
i faced the same prblm , i fixed it by adding :key="{{ $key }}"
```
<x-inputs.group class="w-full lg:w-3/12">
                    <x-inputs.select name="content_id" wire:model="content_id">
                        <option></option>
                        @foreach ($content as $key => $label)
                            <option value="{{ $label->id }}" :key="{{ $key }}">
                                {{ $label->name }}
                            </option>
                        @endforeach
                    </x-inputs.select>
                </x-inputs.group>
```
