### ISSUE TITLE
Snapshot becomes null when component properties are set by test

### ISSUE THREAD

**Issue by domjanzsoo** [livewire/livewire#8603]
### Discussed in https://github.com/livewire/livewire/discussions/8602

<div type='discussions-op-text'>

<sup>Originally posted by **domjanzsoo** June 25, 2024</sup>
I have a form with some text fields and a file uploader. All works well, but I'm unable to write tests for the upload field.
Keep getting the following error:

![image](https://github.com/livewire/livewire/assets/40408231/c95697fb-c6be-49a3-b2ab-c9a0b482e549)

This is my component:

    <?php

    namespace App\Livewire\Users;

    use Livewire\Component;
    use Illuminate\Support\Facades\Hash;
    use App\Contract\UserRepositoryInterface;
    use App\Contract\PermissionRepositoryInterface;
    use App\Contract\RoleRepositoryInterface;
    use Exception;
    use Illuminate\Auth\Access\AuthorizationException;
    use Livewire\WithFileUploads;

    class Add extends Component
    {
    use WithFileUploads;

    private $userRepository;
    private $permissionRepository;
    private $roleRepository;

    public array $state = [
        'full_name'             => null,
        'email'                 => null,
        'password'              => null,
        'password_confirmation' => null,
        'verified'              => false,
        'profile_picture'       => null,
        'permissions'           => [],
        'roles'                 => []
    ];

    protected $rules = [
        'state.full_name'               => 'required',
        'state.email'                   => 'required|email|unique:users,email',
        'state.password'                => 'required|confirmed|min:6',
        'state.password_confirmation'   => 'required',
        'state.profile_picture'         => 'image|max:2048|nullable',
        'state.permissions'             => 'array',
        'state.roles'                   => 'array'
        
    ];

    protected $listeners = [
        'user-permissions' => 'handlePermissions'
    ];
    
    public function messages(): array
    {
        return [
            'state.full_name.required' => trans('validation.required', ['attribute' => 'name']),
            'state.email.required' => trans('validation.required', ['attribute' => 'email']),
            'state.email.unique' => trans('validation.unique', ['attribute' => 'user email']),
            'state.email.email' => trans('validation.email', ['attribute' => 'user email']),
            'state.password.required' => trans('validation.required', ['attribute' => 'password']),
            'state.password.min' => trans('validation.min.string', ['attribute' => 'password', 'min' => 6]),
            'state.password.confirmed' => trans('validation.confirmed', ['attribute' => 'password']),
            'state.profile_picture.image' => trans('validation.image', ['attribute' => 'profile picture']),
            'state.profile_picture.max' => trans('validation.max.file', ['max' => '2048', 'attribute' => 'profile picture'])
        ];
    }

    // public function updatedStatePassword(): void
    // {
    //     $this->validateOnly('state.password');
    // }

    // public function updatedStatePasswordConfirmation(): void
    // {
    //     $this->validateOnly('state.password');
    // }

    public function handlePermissions(array $selections): void
    {
        $this->state['permissions'] = [];

        foreach ($selections as $id => $selection) {
            if ($selection['selected'] && !in_array($id, $this->state['permissions'])) {
                array_push($this->state['permissions'], $id);
            }
        }
    }

    public function handleRoles(array $selections): void
    {
        $this->state['roles'] = [];

        foreach ($selections as $id => $selection) {
            if ($selection['selected'] && !in_array($id, $this->state['roles'])) {
                array_push($this->state['roles'], $id);
            }
        }
    }

    public function render()
    {
        return view('livewire.users.add', [
            'permissions'   => $this->permissionRepository->getAll(),
            'roles'         => $this->roleRepository->getAll()
        ]);
    }

    public function boot(
        UserRepositoryInterface $userRepository,
        PermissionRepositoryInterface $permissionRepository,
        RoleRepositoryInterface $roleRepository
    )
    {
        $this->userRepository = $userRepository;
        $this->permissionRepository = $permissionRepository;
        $this->roleRepository = $roleRepository;
    }

    public function addUser(): void
    {     
        if (!access_control()->canAccess(auth()->user(), 'add_user')) {
            throw new AuthorizationException(trans('errors.unauthorized_action', ['action' => 'add user']));
        }

        $validatedData = $this->validate();

        // dd($validatedData);

        try {
            $user = $this->userRepository->createUser(
                [
                    'name'      => $validatedData['state']['full_name'],
                    'email'     => $validatedData['state']['email'],
                    'password'  => Hash::make($validatedData['state']['password'])
                ],
                $validatedData['state']['permissions'],
                $validatedData['state']['roles']
            );

            if ($validatedData['state']['profile_picture']) {
                $profilePictureFileName = md5($user->id) . '.' . $validatedData['state']['profile_picture']->extension();
    
                $validatedData['state']['profile_picture']->storeAs('/avatar', $profilePictureFileName, $disk = config('filesystems.default'));
    
                $user->profile_photo_path = 'storage/avatar/' . $profilePictureFileName;
                $user->save();
            }

        } catch(Exception $exception) {
            $this->dispatch('toastr', ['type' => 'error', 'message' => $exception->getMessage()]);
        }

        $this->state['full_name'] = null;
        $this->state['email'] = null;
        $this->state['password'] = null;
        $this->state['password_confirmation'] = null;
        $this->state['profile_picture'] = null;
        $this->state['permissions'] = [];
        $this->state['roles'] = [];

        $this->dispatch('toastr', ['type' => 'confirm', 'message' => trans('notifications.successfull_creation', ['entity' => 'User'])]);
        $this->dispatch('user-permissions-submitted');
        $this->dispatch('user-roles-submitted');

        return;
    }
    }

and this is the test of the file upload

    /** @test */
    public function fails_with_oversized_profile_image()
    {
        $this->actingAs($this->userWithAddPermissionAccess);

        $this->assertEquals(3, User::count());

        Storage::fake('public');

        $profileImage = UploadedFile::fake()->create('blaa.jpg', 145412);
        
        Livewire::test(CreateUser::class)
            ->set('state', [
                'full_name' => 'Joe Doe',
                'email' => 'test.user@email.com',
                'password' => 'password',
                'password_confirmation' => 'password',
                'profile_picture' => $profileImage,
                'permissions' => [],
                'roles' => []
            ])
            ->call('addUser')
            ->assertHasErrors(['state.profile_picture' => 'max']);

        $this->assertEquals(3, User::count());
    }

After debugging I concluded, that the following happens: 
- at first render the fields are set to their initial values and both boot and render lifecycle methods run successfully, and that upload method of HandleComponents receives the right snapshot
- once all the properties set with the UploadedFile object included, the component re-runs the lifecycle methods and the snapshot passed to HandleComponents becomes null, which returns the error attached above.

without file the test runs with no problem.

My question is: When is that update method called? What is the purpose of it? Why the snapshot becomes null, when the file upload is included?

Thanks.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
