### ISSUE TITLE
checkbox with pagination

### ISSUE THREAD

**Issue by Iweb-tech** [livewire/livewire#8631]
### Discussed in https://github.com/livewire/livewire/discussions/8630

<div type='discussions-op-text'>

<sup>Originally posted by **Iweb-tech** July  5, 2024</sup>
hey there,
i am using laravel livewire 3 with pagination and checkbox . when i check the checkbox it set the value in array that is ok. but when i switch page to next it show checked checkbox which i have checked in previous page. Although server side value are remain same which i have checked. it should not be check in new page bcz that checkbox ids not exist in array.
pls help me with this.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
