### ISSUE TITLE
update options of second input select2 based on first input select2 when using wire:ignore

### ISSUE THREAD

**Issue by abrardev99** [livewire/livewire#864]
I'm using select2 for multiselect. Can someone suggest how to update options of second input select2 based on first input select2 when using wire:ignore. because wire:ignore blocking updates and when I remove wire:ignore selec2 removed from select input too.

**Comment by Santosh-NPL** [comment]
Same problem is mine also

**Comment by lancepioch** [comment]
Please see Adrian's comments in #883 

If that doesn't help you, post a more specific question or code sample so we can check it out, thanks
