### ISSUE TITLE
Livewire makes page freeze if request is large

### ISSUE THREAD

**Issue by RishabSwift** [livewire/livewire#866]
**Describe the bug**
After the page loads, I have an event that is emitted to fetch file content (text files). Depending on the size fo the text file (between 1KB - 2.5MB), the browser freezes during the duration of the request as it is fetching the file contents and returning it to the user.

It's likely because the request is synchronous as the whole browser is just waiting for the request to finish before the user can use the site.

**To Reproduce**
Emit an event, and in the Livewire method that listens for the event, try to read a text file that is > 1MB and return the content of the file to the user. It should freeze the browser while it's reading the file. It's worse if you're post-processing the content (e.g. using Highlight.js).

**Expected behavior**
The user should be able to interact with the page as they normally would, without the page freezing.

**Desktop (please complete the following information):**
 - Chrome, Safri

**Comment by calebporzio** [comment]
Livewire requests are synchronous and blocking.

If you have a request that will take a long time, I recommend isolating it to a dedicated component on a page.

Separate components shouldn't hold each other up. If this is the case, re-submit this issue with copy and pastable code so we can re-produce, but I imagine the right answer here is isolating a component.
