### ISSUE TITLE
Variables do not resolve through blade components on wire: directives

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#868]
**Describe the bug**
This works:
```php
<select wire:model="return_items.{{ $item->id }}" name="return_items" >
     <option>1</option>
     <option>2</option>
</select>
```

This does not work:
```php
<x-input-select wire:model="return_items.{{ $item->id }}" name="return_items">
    <option>1</option>
    <option>2</option>
</x-input-select>
```

With the `$return_items` key/value being set to `"{{ $item->id" }} => "2"` on Submit

**Comment by RishabSwift** [comment]
Have you tried `<x-input-select :wire:model="return_items.$item->id"> ` ?  Notice the colon `:` in front of `wire`. 

You can use the colon to pass in any PHP variables without the `{{ $var }}`

**Comment by booni3** [comment]
Thanks. I did actually try that first-up but I have just tried it again after promoting and realise I needed to quote it too.

The below works... but looks a bit messy!

```php
<x-input-select :wire:model.lazy="'return_items.'.$item->id" name="return_items">
    <option>1</option>
    <option>2</option>
</x-input-select>
```

**Comment by ManojKiranA** [comment]
> The below works... but looks a bit messy!

https://laravel.com/docs/7.x/blade#passing-data-to-components

While Passing Variables into Blade Components you must add `:` symbol before that attribute.

**Comment by dsazup** [comment]
Just run into this issue myself. Thought this is a bug. To achieve this:
`<button wire:click="selectPlan('plan_id')">`
I need to do:
`<x-button class="btn btn-primary" :wire:click="'selectPlan(\''.$plan['id'].'\')'"/>` which is not really nice. Which is not really nice 🤔

**Comment by calebporzio** [comment]
Ew, that is kinda gross. This is really a Laravel issue though. I don't see how Livewire could make this easier right?

Here's a maybe-not-nicer alternative:
```
<x-button :wire:click="sprintf('selectPlan(\'%s\')', $plan['id])"/>
```

It would be great if PHP had backticks like JS, then we could:
```
<x-button :wire:click="`selectPlan('{$plan['id]}')`"/>
```
... or something like that.

Another solution would be for Laravel to support Blade echo inside the binding syntax:
```
<x-button wire:click="selectPlan('{{ $plan['id] }}')"/>
```

This is what most people assume works at first.

Thoughts?

**Comment by calebporzio** [comment]
Btw, I asked Taylor and he said it's not possible (The including blade syntax without the binding)

I'm guessing this is because the template compilation is "during" the blade compilation step, so it would need to compile twice.

**Comment by bardh7** [comment]
@calebporzio this looks like a good solution 


> Another solution would be for Laravel to support Blade echo inside the binding syntax:
> 
> ```
> <x-button wire:click="selectPlan('{{ $plan['id] }}')"/>
> 
> // Much cleaner than:
> 
> <x-button :wire:click="'selectPlan(\''.$plan['id].'\')"/>
> ```
> 
> This is what most people assume works at first.
> 
> Thoughts?

**Comment by dsazup** [comment]
Looks like this might become a reality  🎉  https://github.com/laravel/framework/pull/32558

**Comment by calebporzio** [comment]
Haha yep!! Pretty excited!

**Comment by booni3** [comment]
https://blog.laravel.com/laravel-790-blade-component-improvements

Resolved. Such a fast turn-around on a resolution all the way into core. So impressed!!
