### ISSUE TITLE
Radio In Button Groups Not Work (Can not select radio with label)

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#869]
**Describe the bug**
I am using bootstrap v4 and I want to have radio button, But it wont work.
But when I use radio input it work fine.

**To Reproduce**
````
<div>
                    <div class="btn-group btn-group-toggle btn-lg btn-block" data-toggle="buttons">
                        <label class="btn btn-outline-primary btn-lg" for="rent">
                            <input type="radio" value="rent" id="rent" name="type" wire:model="type"> Rent Me
                        </label>
                        <label class="btn btn-outline-primary btn-lg" for="buy">
                            <input type="radio" value="buy" id="buy" name="type" wire:model="type"> Buy Me
                        </label>
                    </div>
    {{ $type }}
</div>
````

**Expected behavior**
type is null

**Screenshots**
There is no effect on {{ $type }}

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
I think there is problem with chose radio with label.

**Comment by DanHarrin** [comment]
Hey, please post your Livewire component class so we can check that over as well.

Also, is other Livewire functionality working for this component / on this page? Or is this the only thing that has been tried so far?

Thanks.

**Comment by shirazsoft** [comment]
@DanHarrin 
When I use:
````
<input type="radio" id="buy"><label for="buy">Buy</label>
````
It work well but when input is in label tag it won't work.

This is my livewire component 
````
public $type;
    public $duration;
    public $farm;
    public $text;

    protected $updatesQueryString = ['type', 'duration', 'farm'];

    public function mount()
    {
        $this->type = request()->query('type', $this->type);
        $this->duration = request()->query('duration', $this->duration);
        $this->farm = request()->query('farm', $this->farm);
    }

    public function render()
    {
        if($this->type == 'buy') {
            $plans = Plan::filter(['type'=> $this->type, 'farm' => $this->farm])->get();
        } else {
            $plans = Plan::filter(['type'=> $this->type, 'duration' => $this->duration, 'farm' => $this->farm])->get();
        }

        return view('livewire.panel-mine', compact('plans'));
    }
````

**Comment by DanHarrin** [comment]
I've just tested your code locally and it works fine for me.

Please check if you have any errors in your console, and ensure that you have `@livewireScripts` and `@livewireStyles` in your layout.

**Comment by shirazsoft** [comment]
@DanHarrin All other inputs and selects work fine in my component,  
````
                        <label class="btn btn-outline-primary btn-lg" for="rent">
                            <input type="radio" value="rent" id="rent" name="type" wire:model="type"> Rent Me
                        </label>
````
Not work please check it.

**Comment by DanHarrin** [comment]
Yup, that was what I checked and it worked fine for me. `$type` bound itself to the selected radio option fine, and the output value matched.

If you remove the classes from the `<label>`, does that make a difference? The only thing I can think of possibly happening is that Bootstrap could be doing something funky with the JS on this button.

**Comment by jjjrmy** [comment]
I am using hidden radio inside of a label and it works fine for me.

**Comment by lancepioch** [comment]
I believe these answers are sufficient.

However, we are trying out the new [Github Discussions](../discussions). We are hoping that this will encourage and centeralize feedback relating to discussions like this. So iff you still feel this is relevant, please create a discussion there, thanks a bunch!

**Comment by jafar690** [comment]
@shirazsoft remove `data-toggle="buttons"`

**Comment by altwaireb** [comment]
in your  Livewire component you need to boot this :

`public $type = [];`

**Comment by ambitionphp** [comment]
> @shirazsoft remove `data-toggle="buttons"`

this works for me however my radio options no longer show an active state. any suggestions to keep both?

**Comment by WhereIsLucas** [comment]
@ambitionphp 
A bit dirty, but simply add manually the active class when needed : 
``` Blade
<label class="btn btn-primary {{ $item->value == $options ? 'active' : '' }}" for="option{{ $loop->index }}">
    {{ $item->value }}
    <input type="radio" wire:model="options" name="option[{{ $loop->index }}]" value="{{ $item->value }}" id="option{{ $loop->index }}">
</label>
```

**Comment by fayzasalman** [comment]
> @ambitionphp A bit dirty, but simply add manually the active class when needed :
> 
> ```
> <label class="btn btn-primary {{ $item->value == $options ? 'active' : '' }}" for="option{{ $loop->index }}">
>     {{ $item->value }}
>     <input type="radio" wire:model="options" name="option[{{ $loop->index }}]" value="{{ $item->value }}" id="option{{ $loop->index }}">
> </label>
> ```

you saved my life thank u
