### ISSUE TITLE
Accessing private/protected properties before initialization

### ISSUE THREAD

**Issue by codedge** [livewire/livewire#871]
Hi,

I initialize a repository to run some action after a button inside a Livewire component has been clicked. The repository is injected via the `mount()` method.

```php
private CrawlDbRepository $crawlDbRepository;

public function mount(CrawlDbRepository $crawlDbRepository)
{
   $this->crawlDbRepository = $crawlDbRepository;
}

public function add()
{
    // Do sth...
    $stored = $this->crawlDbRepository->store($model);
}
```

In  my template I call the `add()` method onclick like this 

```
<button class="block mt-2 sm:mt-0 w-full sm:w-auto px-8 py-4 bg-yellow bg-blue-500 hover:bg-blue-800 text-white rounded sm:rounded-none sm:rounded-r"
                wire:click="add">
            Add
 </button>
```

When doing so I get the error
```
Error
Typed property App\Http\Livewire\AddCrawl::$crawlDbRepository must not be accessed before initialization 
```

I saw that the same error happened in #707  but after updating to the latest release I still get the error.

**Comment by tiago-sb** [comment]
Hi @codedge, @lancepioch 

Had the same error which was related to the use  of typed properties.
Changing
`private CrawlDbRepository $crawlDbRepository;`
to
`private $crawlDbRepository;`

probably solves the problem, however, in Livewire v1.0.14 this problem is gone and this works:

```
class ListEntry extends LivewireComponent
{
    public $model;
    public array $details;

    public function mount(Model $model)
    {
        $this->model = $model;
        $this->details = [];
    }
...

Note that (it seems that) **models cannot be typed** since they must be both the Model class and an array, given that livewire  maps back and forth between models and arrays - there's likelly and improvement to be made here.

**Comment by calebporzio** [comment]
Yep, typed properties are currently not supported.

Closing this.
