### ISSUE TITLE
Allow @this.get('property') to get nested values directly

### ISSUE THREAD

**Issue by asjsrep** [livewire/livewire#873]
**Is your feature request related to a problem? Please describe.**
Grouping certain properties into arrays/objects can be useful, e.g configuration settings or grouping form fields. Accessing the local JS data store is useful when wanting to keep server calls limited or interacting with liveware from external JS. Currently the get method does a direct array lookup: 

`  
get(name) {
        return this.data[name]
    }
`

Allowing a dot notation would enable fetching values in nested objects/arrays easier. E.g `get('parent.child1')` from `{data: parent: {child1: 1, child2: 2 }}` would return 1

**Describe the solution you'd like**
Changing the get method to something which recognises the dot access notation: E.g something like

`
get(name) {
  return name.split('.').reduce((o,i)=>o[i], this.data)
}
`

**Describe alternatives you've considered**
Splitting the name at the dot does mean variable names can't contain the '.' character without additional handling.

**Comment by ducopro** [comment]
Absolutely agree. I ran into this problem a couple of times also.

**Comment by calebporzio** [comment]
The next Livewire release will allow for dot-notation @this.get access. Good call. Thanks!
