### ISSUE TITLE
Capture all form data on change of any field from a dynamic form

### ISSUE THREAD

**Issue by supergirish** [livewire/livewire#879]
I have a dynamic form which has multiple fields like text fields, dropdowns and on change of any of these fields I have to make some calculations in the backend and update the calculated values on the frontend. 

Consider it a backoffice hotel booking page where a hotel staff wants to send a proposal to a client for multiple rooms with a future checkin and checkout date, adult, children count which all depends on the availability of rooms on those future dates. Now there are differnt kind of rooms like Type A, Type B and so on and these rooms have different prices on different dates which has to be calculated in the backend along with tax. Quantity of rooms along with the room type can be selected on the form and the calculation results need to be reflected on the page at the same time.

My page has this form on the left side and the right side shows the tax and other calculations as soon as I select the room type or the room quantity or the adult count or the checkin-checkout dates. I am not sure if I have to submit the full form data to the component on change of any field and how to attain this or should I send only the field that is changed and do the calculations.
The main concern is to show the right calculations and the availability based on the data in the database at that point of time. Any help will be appreciated. Thanks.

**Comment by ninthspace** [comment]
Assuming the form is a Livewire component, you can hook up all the relevant fields with `wire:model` attributes, and then use the `updated` method to work with the current state of that form. See: https://laravel-livewire.com/docs/lifecycle-hooks

**Comment by supergirish** [comment]
> Assuming the form is a Livewire component, you can hook up all the relevant fields with `wire:model` attributes, and then use the `updated` method to work with the current state of that form. See: https://laravel-livewire.com/docs/lifecycle-hooks
