### ISSUE TITLE
x-init="window.Livewire.on( ... not working

### ISSUE THREAD

**Issue by Ronan-Lenor** [livewire/livewire#8790]
### Discussed in https://github.com/livewire/livewire/discussions/8772

<div type='discussions-op-text'>

<sup>Originally posted by **Ronan-Lenor** August 22, 2024</sup>
i use Livewire v3.5.6 & i try to trigger a dispatch() event from a Livewire component.
but the global listener in x-init isn't working ?! 🤷‍♂️ (i didn't had this problem in the v2)

```php
class ExampleLivewire extends Component
...
    public function triggerEvent()
    {
        $this->dispatch('exampleEvent');
    }
```

```html
<button wire:click="triggerEvent">Click Me</button>

<!-- not working ??? -->
<div x-init="window.Livewire.on('exampleEvent', () => { alert(1); });"></div>

<!-- working ??? -->
<div x-init="null; window.Livewire.on('exampleEvent', () => { alert(1); });"></div>

<!-- work -->
<script>
    document.addEventListener('livewire:init', () => {
        window.Livewire.on('exampleEvent', () => { alert(2); });
    });
</script>

<!-- work, but i'm not sure it's the right way to do it for a global listener? -->
<div wire:init="on('exampleEvent', () => { alert(3); });"></div>

<!-- work, but it's not convenient to get the parameters sent by the dispatch() method 🤔 -->
<div x-init="document.addEventListener('exampleEvent', (event) => { console.log(event.__livewire.params) });"></div>
```

is it a bug ? is there alternatives ?

Thanks,</div>

**Comment by Ronan-Lenor** [comment]
see here: https://github.com/livewire/livewire/discussions/8773

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
