### ISSUE TITLE
wire.loading inline style display:inline-block

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#885]
I am trying to put a loading icon in my input, it requires display flex.

The wire:loading automatically applies the inline style display:inline-block
Is there any way to override this other than adding !important to a CSS class?

https://imgur.com/F7JoXwY

**Comment by jjjrmy** [comment]
Also happens on wire:offline.

This is a problem if you are using tailwinds as the inline style will always override it

**Comment by indigoram89** [comment]
+1

**Comment by capjjs** [comment]
try wrapping it in another div/span and apply wire:loading on that.

**Comment by calebporzio** [comment]
I'm not clear exactly on the scenario you are describing.

I would think that Livewire would only add display: none when the icon should be hidden and that would be the behavior you would want.

Anyhow, if wrapping the icon in a parent element with `wire:loading` is not an option, then please re-submit with clear code examples I can easily copy and paste.

Thanks!

**Comment by cdbessig** [comment]
I believe we are hitting the same issue.  The use case we have is that we want to display the loading icon centered in a table cell that spans 3 columns.  The display:inline is being attached to the tr element and throwing off all the formatting. 

`<tbody wire:init="loadSites">

                        <tr wire:loading>

                            <td colspan="3" class=" align-middle text-center items-center">

                                <div class="la-ball-pulse la-dark">

                                    <div></div>
                                    <div></div>
                                    <div></div>
                                </div>
                            </td>
                        </tr>
                        
                        @foreach($sites as $site)
                            @if($loop->odd)
                                <tr class="bg-white">
                            @else
                                <tr class="bg-gray-50">
                            @endif
                                    <td class="px-2 py-1 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ $site['something'] }}
                                    </td>
                                    <td class="px-2 py-1 whitespace-nowrap text-sm text-gray-500">
                                        {{ $site['else'] }}
                                    </td>
                                    <td class="px-2 py-1 whitespace-nowrap text-sm text-gray-500">
                                        {{ $site['here'] }}
                                    </td>
                                </tr>
                        @endforeach
                        </tbody>`

**Comment by joshhanley** [comment]
@cdbessig try to make use of toggling classes instead of using `wire:loading` on its own. https://laravel-livewire.com/docs/2.x/loading-states#toggling-classes

That way you could have a `hidden` class on the loading TR by default and remove it when loading.

Hope this helps!

**Comment by cdbessig** [comment]
@joshhanley thanks for your feedback.  This made me revisit it after settling for the left alignment.  I tried your approach and it cleaned up my code a bit, but ultimately what I found was I was missing the margin auto on the div inside the table to center it properly.

I also cleaned it up and moved this element to a tfoot to seperate it from the body

`<tbody wire:init="loadSites">
                        
                        @foreach($sites as $site)
                            @if($loop->odd)
                                <tr class="bg-white" wire:loading.class="hidden">
                            @else
                                <tr class="bg-gray-50" wire:loading.class="hidden">
                            @endif
                                    <td class="px-2 py-1 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ $site['Site (CM360)'] }}
                                    </td>
                                    <td class="px-2 py-1 whitespace-nowrap text-sm text-gray-500">
                                        {{ $site['Impressions'] }}
                                    </td>
                                    <td class="px-2 py-1 whitespace-nowrap text-sm text-gray-500">
                                        {{ $site['Clicks'] }}
                                    </td>
                                </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                            <tr class="hidden" wire:loading.class.remove="hidden" >
                                <td colspan="3" class=" align-middle text-center items-center">
                                    <div class="la-ball-pulse la-dark mx-auto">
                                        <div></div>
                                        <div></div>
                                        <div></div>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>`

So I guess I came back to say that this bug wasn't the cause for my issue and there was a solution unrelated to this issue.

Thanks!

**Comment by Football1995** [comment]
Perhaps a bit late, but if anyone is still searching for this issue.  

I found you can add the following to the HTML
`<div wire:loading.flex>...</div>`

Theres a few other options available see docs  [here](https://laravel-livewire.com/docs/2.x/loading-states)

**Comment by moizmasood10** [comment]
@Football1995 Thanks, was looking for this for a while. I don't know why this is not mentioned in the docs for v3 because I believe this is something every other person will run into when trying to center the loading animations.

**Comment by Linkedin-apishack2** [comment]
> [@Football1995](https://github.com/Football1995) Thanks, was looking for this for a while. I don't know why this is not mentioned in the docs for v3 because I believe this is something every other person will run into when trying to center the loading animations.





https://csser.space/questions/position-a-div-at-the-center-of-the-page-while-aligning-it-inline-with-another-div
