### ISSUE TITLE
Too few arguments to function Illuminate\View\Compilers\ComponentTagCompiler::__construct()

### ISSUE THREAD

**Issue by cao-minh-duc** [livewire/livewire#888]
**Describe the bug**
Too few arguments to function Illuminate\View\Compilers\ComponentTagCompiler::__construct(), 0 passed in .../vendor/livewire/livewire/src/LivewireServiceProvider.php on line 182 and at least 1 expected.

<img width="967" alt="Screenshot 2020-04-28 at 22 57 17" src="https://user-images.githubusercontent.com/17726941/80509581-d0901700-89a3-11ea-8e13-c2335609fc56.png">

I read this commit of laravel (https://github.com/laravel/framework/commit/3f537ca1c7cbf14af34dcf697801db75f2b173d3#diff-6a6ea7a2d1468b4ad89232932195b939) so I think reason it missing BladeCompiler in constructor.
T fix it i try app(LivewireTagCompiler::class) instead to use dependency injection.
<img width="964" alt="Screenshot 2020-04-28 at 23 02 37" src="https://user-images.githubusercontent.com/17726941/80510039-6035c580-89a4-11ea-8f5c-10e9354da441.png">

**Comment by taylorotwell** [comment]
Fixed by Laravel 7.9.2.

**Comment by bedus-creation** [comment]
I just encountered this problem.

**Comment by Te7a-Houdini** [comment]
@lancepioch this should be fixed by taylor so i think it should be closed now
