### ISSUE TITLE
wire:offline cannot Add & Remove CSS class

### ISSUE THREAD

**Issue by jjjrmy** [livewire/livewire#890]
This bug is related to #885 

By default `wire:offline` sets an inline style of `display: inline-block` to the element if you used by itself, as mentioned in the related issue. This is problematic when using Tailwind classes.

The solution would be to use `wire:offline.class` instead, but this will only add the included classes. So not possible to have the element hidden then shown when offline.

The best solution would be to combine `wire:offline.class` and `wire:offline.class.remove`, currently this does not work as only one can be used at a time.

```html
<div wire:offline.class="absolute block" wire:offline.class.remove="hidden" class="hidden">
    You Are Offline!
</div>
```

**Comment by calebporzio** [comment]
This has been fixed. The following snippet works perfectly:

```html
    <div wire:loading.class="absolute block" wire:loading.class.remove="hidden" class="hidden">
        I am loading!
    </div>
```
