### ISSUE TITLE
Question: Would a pull request adding type-hints be well received?

### ISSUE THREAD

**Issue by natepisarski** [livewire/livewire#895]
To make a long story short, my question boils down to:

If I were to submit a pull request which added type-hints across the project, would it be welcome? I know that typing can be a surprisingly controversial topic, so I just wanted to double-check with you Livewire maintainers before I did it. No behavior will change, and it will remain 7.1 compatible.

I also noticed this PR: #790 which references removing typehints, but it actually removed typecasts.

**The backstory**  
I'm making a fork of Livewire for my own personal use. It's going to be exactly this version, but with one giant change: support for Higher-Order Livewire components, and functional Livewire components. Analogs to React's [Higher-Order components](https://reactjs.org/docs/higher-order-components.html) and [Functional Components](https://reactjs.org/docs/components-and-props.html)

I've gone through the code and have found that it's actually feasible to do, but at great cost. It will be a ground-up rebuild of the livewire manager, and a smattering of changes all throughout the codebase. I won't open a PR for the function/higher-order work unless you guys would be interested, just because of HOW BIG of a change it will be.

Anyway, my first step is going to be adding type-hints across the codebase. If a type-hinting PR is welcome, I will not turn on `strict_types` and I will only type-hint parameters (not properties), to keep 7.1 compatibility. Since `strict_types` will stay off the typehints won't change the behavior whatsoever, and will only exist as guides for developers working with the code.

Things like `$request` won't be hinted because there are places where Symphony's `Request` and Laravel's `Request` both work.

**Comment by calebporzio** [comment]
Sounds like an interesting project, I'd be interested in hearing more about your ideas for higher order components. I'm just Curious.

As for the type hints. I don't think I'd merge that, so thanks for asking!

**Comment by natepisarski** [comment]
No problem at all. It works out for me because I get to try to enable `strict_types=1`!

I'll 100% write something up about the fork once I can get something concrete. The idea is to be able to use naked `function`'s as if they were a livewire class with a `render()`. Additionally, be able to call functions which return anonymous livewire components from the blade views. Thanks for your input
