### ISSUE TITLE
Conditionally applying wire:poll after first render

### ISSUE THREAD

**Issue by tonysm** [livewire/livewire#897]
It seems that the `wire:poll` property is only checked when the [component is initialized](https://github.com/livewire/livewire/blob/master/js/component/Polling.js#L6) (I assume first render). We can [turn it off](https://github.com/livewire/livewire/blob/master/js/component/Polling.js#L22) by conditionally removing the `wire:poll` property from our DOM element (which means the interval will still run, but nothing will be called).

If on the first render the DOM element doesn't have the `wire:poll` and in a subsequent render I add it (think of a "listen for events" kind of button), it doesn't work (for reasons I mentioned on the first paragraph).

Is this intended behavior? I'm adding an example code here:

<details>

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Lights extends Component
{
    public int $progress = 10;
    // If this starts as "true" and I turn off aftwards, it works as expected.
    public bool $partyMode = false;

    public function changeProgress(int $progress)
    {
        $this->progress = max(min($progress, 100), 0);
    }

    public function toggleParty()
    {
        $this->partyMode = !$this->partyMode;

        if ($this->partyMode) {
            $this->party();
        }
    }

    public function party()
    {
        $this->changeProgress(rand(0, 100));
    }

    public function render()
    {
        return <<<'blade'
        <div class="container text-center">
            <h1>Hello Lights Example</h1>
            <div class="w-100 progress" @if($partyMode) wire:poll="party" @endif>
                <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: {{ $progress }}%"
                    aria-valuenow="{{ $progress}}"
                    aria-valuemin="0"
                    aria-valuemax="100"
                >
                    {{ $progress }}%
                </div>
            </div>
            <div class="mt-2">
                <button wire:click="changeProgress(100)" class="btn btn-primary">On</button>
                <button wire:click="changeProgress(0)" class="btn btn-primary">Off</button>
                <button wire:click="toggleParty" class="btn btn-primary">Party ({{ $partyMode ? 'On' : 'Off' }})</button>
            </div>
        </div>
        blade;
    }
}
```

</details>

**Comment by tormjens** [comment]
I would love to hear some input on this. It would be awesome if you could start polling conditionally, and also stop polling when that condition is not met.

**Comment by calebporzio** [comment]
Polling has been enhanced to allow for these things.

You can easily conditionally poll anything by conditionally rendering an element with `wire:poll` on it, OR conditionally rendering the `wire:poll` attribute itself.

Thanks!
