### ISSUE TITLE
Universal wire:loading for livewire components

### ISSUE THREAD

**Issue by RishabSwift** [livewire/livewire#899]
Right now, we have loading states by `<div wire:loading>...</div>` which is great. But I am looking for a universal loading state where we can have one loader for all components or only the components we specify.

Sort of like `<div wire.loading.all>...</div>` would be a universal loader for components.

Also, is there a workaround for what I'm trying to achieve?

**Comment by Te7a-Houdini** [comment]
@RishabSwift
 can;t you use blade components & slots to extract that wire:loading . for example

```html
<!-- /resources/views/components/loading.blade.php -->
<div wire:loading>
    {{ $slot }}
</div>

<!-- /resources/views/livewire/posts.blade.php -->
<x-loading>
   posts are loading
</x-loading

``

**Comment by DanHarrin** [comment]
Hi, I'm gonna close this thread for now as it hasn't seen activity in a little while. Please feel free to use [the discussions section](https://github.com/livewire/livewire/discussions) or the [Discord server](https://discord.gg/H884eyt) to continue your conversation about this issue. Thanks!
