### ISSUE TITLE
New Template repo for quickly testing issues & code snippets

### ISSUE THREAD

**Issue by davidpiesse** [livewire/livewire#90]
Whilst trying to help on issues I am either creating a new app each time (time consuming) or using the same one again and again with new routes etc and creating a #mess#.

Is it possible to have a livewire-template repo that is a default Laravel build with Livewire installed and some basic routes and classes pre-built to get someone started tackling an issue. Basically all but the custom code ready to go?

It would be easier then to fork it if needs be for a specific issue rather than all trying to implement the same code in different apps.

PS. Happy to do the work on this if the others in the Livewire team think its useful 😄

**Comment by calebporzio** [comment]
I agree with this and will try to have something together in the near future

**Comment by davidpiesse** [comment]
Close this out when Fiddle arrives?

**Comment by davidpiesse** [comment]
Value add :D
