### ISSUE TITLE
`wire:model` not work with alpinejs `x-model`

### ISSUE THREAD

**Issue by mr-chetan** [livewire/livewire#9115]
### Discussed in https://github.com/livewire/livewire/discussions/9114

<div type='discussions-op-text'>

<sup>Originally posted by **mr-chetan** December 29, 2024</sup>
### Livewire version

3.5.18

### Laravel version

11.36.1

### Which PHP version are you using?

PHP 8.4

### What is the problem?

Live Model does not Update if I enter text on the second input but if I enter text on the first input it will update the Livewire model

### Code snippets

```blade
    <div class="" x-data="{
        text: '',
    }">
        <p>{{ $text }}</p>
        <br>
        <input type="text" x-model="text" wire:model.live="text" />
        <input type="text" x-model="text"/>
    </div>
```

### Wirebox URL

https://wirebox.app/b/4z6rg

### How do you expect it to work?

I need to be update the livewire text

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I have provided code samples as text and NOT images.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/livewire/livewire/discussions/3147
