### ISSUE TITLE
Artisan livewire:make livewire/with/slashes does not work

### ISSUE THREAD

**Issue by pedzed** [livewire/livewire#913]
Running this should work:
```bash
php artisan livewire:make livewire/with/slashes
```
But it gives an error because the generated class name is based on periods.

This works:
```bash
php artisan livewire:make livewire.without.slashes
```
But both ways should work, because that's for everything else in Laravel (config, routes, views, etc.). 

I prefer to use slashes. When using slashes, I would also expect the render template to use slashes:

```php
public function render()
{
    return view('livewire/livewire/with/slashes');
}
```

**Comment by pedzed** [comment]
This also applies to including livewire components.

This does not work:
```php
@livewire('livewire/with/slashes')
```

And unfortunately, it must be with periods:
```php
@livewire('livewire.without.slashes')
```

**Comment by muzafferdede** [comment]
#915 should fix this.
