### ISSUE TITLE
Emitted event parameter gets serialized before reaching JavaScript

### ISSUE THREAD

**Issue by pedzed** [livewire/livewire#914]
**The bug**
Objects get serialized into arrays when calling `$this->emit()` inside a Livewire component. However, this shouldn't be done until it needs to be passed down to JavaScript.

This bug can be divided into two very related issues: Eloquent objects (i.e. models) and non-Eloquent objects. While Eloquent models become a populated array, a non-Eloquent object always seems to be empty (`[]`).

**Reproducing**
1. Emit an event inside a Livewire component and pass an object as parameter.
  ```php
  $this->emit('myEvent', $someObject);
  ```
2. [Listen for the event](https://laravel-livewire.com/docs/events#event-listeners) on the server side.
3. `dd($someObject)` and see `[]` for a non-Eloquent model and a populated array for an Eloquent model.

**Expected behavior**
Both Eloquent and non-Eloquent objects should retain their state. An object should only be serialized when the emitted data gets passed down to JavaScript, because a PHP class will obviously not work in JavaScript. But before that, it should not be necessary to serialize it to an array. Serializing it immediately greatly limits the capabilities of event parameters.

**Comment by Te7a-Houdini** [comment]
@pedzed i think this won't be possible . cause what's happening is the variables are passed to JS

so what's happening behind the scenes .

- after you call $this->emit . livewire sends a  response to the browser like this screenshot . as you can see events array has postAdded and the [ara,s are serialized

- then another request will be sent with that event .

to summarize livewire sends serialized response to the browser and then the browser calls your app again

![Screenshot from 2020-05-03 09-28-35](https://user-images.githubusercontent.com/17250137/80908499-9ff00a80-8d20-11ea-8e60-b03a78aa6b36.png)

**Comment by pedzed** [comment]
Oh, I think I see the problem. So basically this is what happens:
```
+---------------------------------------+
| Server side                           |
| +-----------------------------------+ |
| | Emit to client                    | |
| +-----------------------------------+ |
|                   |                   |
|                   ᐁ                   |
| +-----------------------------------+ |
| | Serialize parameters              | |
| +-----------------------------------+ |
+---------------------------------------+
                    |
                    |
                    ᐁ
+---------------------------------------+
| Client side                           |
| +-----------------------------------+ |
| | Re-emit to server                 | |
| +-----------------------------------+ |
+---------------------------------------+
                    |
                    |
                    ᐁ
+---------------------------------------+
| Server side                           |
| +-----------------------------------+ |
| | Trigger Listener                  | |
| +-----------------------------------+ |
+---------------------------------------+
```
So it's in no way possible?

**Comment by Te7a-Houdini** [comment]
@pedzed yes exactly . also let's wait for @calebporzio maybe he can put some insights

**Comment by pedzed** [comment]
That would be very unfortunate, because that would go against DRY and I would have to double the amount of queries that need to be run.

If it's absolutely not possible (which sounds logical to me now), then still this should be improved, because as I mentioned, non-Eloquent models get serialized to an empty array.

Perhaps Livewire could allow for defining custom serializers and deserializers.

**Comment by devcircus** [comment]
This has come up a few times with me as well. So far I've been able to change the way I'm doing things to get it to work, like calling a method directly instead of emitting an event, but in some situations, that may not be possible.

**Comment by pedzed** [comment]
> I've been able to change the way I'm doing things to get it to work, like calling a method directly instead of emitting an event

Any idea how I can pass data to a parent component, alternatively to `$this->emitUp()`?

**Comment by calebporzio** [comment]
First, I'll say I think most newcomers over-use nesting Livewire components, then realize it's not like Vue and back out of the nesting hierarchies.

$this->emit() is the only way to communicate from parents to children (outside of deeper hackier ways).

Currently these are the limitations.

**Comment by lpoirothattermann** [comment]
Hi,

Still no way to make it work ? :(
