### ISSUE TITLE
How do we use transition effects with polling?

### ISSUE THREAD

**Issue by mhetreramesh** [livewire/livewire#916]
Seems like polling is simply replace dom of the component. I've a requirement to have different transition effect like slide:left on every poll.

I just wants to know is there a way to use [transitions](https://laravel-livewire.com/docs/css-transitions) with polling? or I'm I doing something wrong?

**Comment by DanHarrin** [comment]
Hi there, the transition API was [removed from v1.0.0](https://github.com/livewire/livewire/releases/tag/v1.0.0), we now recommend that you use [Alpine.js](https://github.com/alpinejs/alpine) for such behaviour.

Please feel free to use [the discussions section](https://github.com/livewire/livewire/discussions) or the [Discord server](https://discord.gg/H884eyt) to continue your conversation about this issue. Thanks!
