### ISSUE TITLE
File name is longer than the maximum allowed path length on this platform (4096)

### ISSUE THREAD

**Issue by hxnk** [livewire/livewire#918]
I'm running into an issue after deploying code to an Ubuntu server, that is similar to the issue described here: https://github.com/laravel/framework/issues/32254

It's suggested by dries, that the issue is caused by calling render() on a view where the template does not come from a file.

Render is being called here:
https://github.com/livewire/livewire/blob/aee1c2b71581a61e10978ccebbf5aca82cf5047b/src/Component.php#L130

The view template (not from a file) comes from here:
https://github.com/livewire/livewire/blob/aee1c2b71581a61e10978ccebbf5aca82cf5047b/src/LivewireBladeDirectives.php#L24

I get the same `File name is longer than the maximum allowed path length on this platform (4096)` error on Ubuntu (not on MacOS) as mentioned in https://github.com/laravel/framework/issues/32254, in case the rendered livewire content is relatively large. Smaller content doesn't give me problems.

`
file_exists(): File name is longer than the maximum allowed path length on this platform (4096): resources/views/&lt;div&gt; <here the entire rendered view is shown>
`

**Comment by hxnk** [comment]
I found the cause for this; it is not related to Livewire.

For reference; I was using [Laravel Blade Components](https://laravel.com/docs/master/blade#components) and returning the template as a string from the render method, instead of a blade view template. Some of them were pretty long and caused this error.

**Comment by f-liva** [comment]
There is any solution?

**Comment by dtokos** [comment]
Just stumbled onto this on my Ubuntu testing server. I'm generating large html tables using multiple builder classes.
In Laravel 8 you can return instance Htmlable for which Laravel provides HtmlString.

Not perfect solution, but it was good enough in my case.

https://github.com/laravel/framework/blob/5ab3464b8755293815e57c0de0829feaf7242aae/src/Illuminate/View/Component.php#L71-L73
