### ISSUE TITLE
Alpine does not initialise inside a blade conditional, after re-render.

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#920]
This applies to a page re-render only, after some logic is performed. For example:

```blade
<button wire:click="setModelToTrue()">click</button>

@if($model->itIsTrue())
<div x-data="{ open: false }">
  <button @click="open = true">Show More...</button>
  <ul x-show="open" @click.away="open = false">
    <li>
      <button wire:click="archive">Archive</button>
    </li>
    <li>
      <button wire:click="delete">Delete</button>
    </li>
  </ul>
</div>
@endif
```

On a page load/full refresh with "itIsTrue()" all works as expected. 

However, If we click the button to turn "it to true" dynamically, the re-render results in the alpine component not being initialized and the dropdown does not work.

I have tried livewire keys, element ID's, extra div elements (as in the troubleshooting section) but I just can't get anything working.

**Comment by booni3** [comment]
So I have found out that I can initialize the new Alpine component using:

```js
Alpine.discoverUninitializedComponents(function(el){ Alpine.initializeComponent(el) })
```

We could add an event listener and fire this when we expect a new element to be added... but I kind of feel this behaviour is not very nice or intuitive.

Is there another way? And if not should this be part of the core to make Alpine and Livewire play nice together?

**Comment by devcircus** [comment]
is there an instance in which we would not want alpine to discover uninitialized components?

**Comment by basepack** [comment]
Well, this issue do I also get a lot. The trick is to wrap a div around it like this:

```
<div>
     @if($model->itIsTrue())
        ...
    @endif
<div>
```

And in my instance I even had to go as crazy as below to get it working with a foreach:
```

<div>
     @if($this->order)

         <div id="update-status-{{ $this->order->id }}">

             @foreach(...)

                 <button x-on:click="open = false; window.livewire.find( '{{ $this->orderItemLivewireId }}' ).call('setStatus', '{{ $status}}');">
                       {{ $status}}
                 </button>

             @endforeach

        </div>
    @endif
<div>
```

In my instance, `window.livewire.find` would always call the `orderItemLivewireId ` which was first clicked. This happened multiple times now to me in my project.

But above code would solve it. My guest is that Alpine is not able to register x-on events correctly or something. I believe this is related in our case: https://github.com/alpinejs/alpine/issues/412 

Fun fact: before I got it working like above, I could even inspect the DOM, and see the **correct** `orderItemLivewireId`'s within those `livewire.find()` calls ... 
But whichever id was first called via the `livewire.find`, would fire always, even if the dom did not match. 

But I am pretty sure you could get it working with some unique id's here and there, and not having to resort to manually booting Alpine components.

**Comment by booni3** [comment]
The above issue is valid, but I think it is unrelated to this issue. Wrapping in DIVs is needed to ensure livewire works correctly, but wrapping in Divs does not make any difference (that I can find) to initialization of alpine components.
 
If you have an alpine component inside a blade conditional (even wrapped in divs) it will not initialize on re-render, but works fine on page load.

**Comment by basepack** [comment]
Ah, you are right. 

But it relates to each other to the nearly identical syntax where something goes wrong. In your case initializing the component and in my case I suppose the Alpine listeners/event registering have issues.

**Comment by roni-estein** [comment]
Until this is fixed, another simple work around, not better than the above, just super quick and simple, is to leave the component there on the page, and  toggle display: none.

Code example:
```
<x-input.date field="dateOfBirth" class="{{ ($this->type == 'refill' ? 'hidden': '') }}"/>
```

here is the blade component with the JS, I like flatpickr better than pickaday, it also doesn't use moment.js, but it doesn't work well on brave browser "right now", and date controls often behave weird on mobile devices, so the idea is if it's on a mobile device, just default to the device date implementation

```blade
@props([
  'field',
  'label'=> (isset($field) ? str($field)->snake()->replace('_',' ')->title() : ''),
  'placeholder' => 'your '. str($field)->snake()->replace('_',' '). ' ...',
  'error' => ($errors->has($field) ? 'error' : ''),
  'hasError' => $errors->has($field),
  'message' => ($errors->has($field) ? '<br>' . $errors->first($field) : ''),
])

@if(isMobile())
  <label class="block {{ $attributes->get('class') }}">
    <div class="form-label {{ $error }}">{{ $label }}:{!! $message !!}</div>
    <div class="relative w-full">
      <input type="date" wire:model.lazy="{{ $field }}" name="{{ $field }}" id="{{ $field }}"
             class="form-input-date block w-full pr-7 {{ $error }}"
             placeholder="{{ $placeholder }}" {{ $attributes->except('class') }}/>
      <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
        <svg class="{{ ($hasError ? 'text-red-400' : 'text-gray-400') }} fill-current h-4 w-4" viewBox="0 0 20 20">
          <path
            d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
            clip-rule="evenodd" fill-rule="evenodd"></path>
        </svg>
      </div>
    </div>
  </label>

@else

  <label
    x-data
    x-init="flatpickr($refs.input, {dateFormat: 'M d, Y'})"

    class="block {{ $attributes->get('class') }}">
    <div class="form-label {{ $error }}">{{ $label }}:{!! $message !!}</div>
    <div class="relative">
      <input type="text" wire:model.lazy="{{ $field }}" data-input
             x-ref="input"
             class="form-input block w-full {{ $error }}"
             placeholder="{{ $placeholder }}" {{ $attributes->except('class') }} />
      <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
        <svg class="{{ ($hasError ? 'text-red-400' : 'text-gray-400') }} fill-current h-4 w-4" viewBox="0 0 20 20">
          <path
            d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
            clip-rule="evenodd" fill-rule="evenodd"></path>
        </svg>
      </div>
    </div>
  </label>


@endif


@section('stylesheets')
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection
```

**Comment by jjjrmy** [comment]
Still having this issue!

![BrokenAlpine](https://imgur.com/bI0aR14)

**Comment by calebporzio** [comment]
I just tested the following blade view locally and it worked perfectly:

```html
<div>
    @if ($thingIsShown)
        <div x-data="{ open: false }">
            <button @click="open = true">Show More...</button>
            <ul x-show="open" @click.away="open = false">
                <li>
                <button wire:click="archive">Archive</button>
                </li>
                <li>
                <button wire:click="delete">Delete</button>
                </li>
            </ul>
        </div>
    @endif

    <button wire:click="showThing">foo</button>
</div>
```

Alpine should pick up the new component and initialize itself.

If you are on the latest version of both Livewire and Alpine AND can reproduce this issue in another way, please submit a new issue with simple, stripped-down, copy-pastable code so I can reproduce.

Thank you.

**Comment by jimbojsb** [comment]
@calebporzio I can confirm this works with your example, but also that it does not work in my codebase, using the latest Livewire and Alpine as of 7/19/20. The only material differences I can spot are that my component has a function-call style data provider, and an init method, and the init method is async (speaks to camera input). Putting an x-data on the Livewire parent div definitely causes the component initializer to run, but the x-shows and such on the child elements do not work.

The only thing that resolves this is this code, from @booni3 

`window.livewire.hook('afterDomUpdate', () => {
  window.Alpine.discoverUninitializedComponents((el) => {
    window.Alpine.initializeComponent(el)
  })
})`

**Comment by abishekrsrikaanth** [comment]
I have the similar issue when the whole component is refreshed using `@this.call('$refresh');` and the code inside `x-init`is never triggered.

**Comment by bnrosa** [comment]
I have the same issue, a component that does something on x-init based on what it receives from x-data, passing a Livewire property. Also, doing:
`document.addEventListener("livewire:load", function(event) {
        window.livewire.hook('afterDomUpdate', () => {
            window.Alpine.discoverUninitializedComponents((el) => {
                window.Alpine.initializeComponent(el);
            });
        });
    });
`
does not work for me.

**Comment by jassehomar** [comment]
@bnrosa same here this does not work for me. But the CSS "hidden" trick by @roni-estein works for me very well.

**Comment by bnrosa** [comment]
@jassehomar yeah, that's the workaround I ended up using.

**Comment by jimpeters** [comment]
I know this is an old issue so I'm just putting this out here as there isn't an example that breaks every time.  

Have you verified you are including @livewireScripts BEFORE including AlpineJS in your app layout?

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by Slowwie** [comment]
The solution of @booni3: 

```
window.livewire.hook('afterDomUpdate', () => {
  window.Alpine.discoverUninitializedComponents((el) => {
    window.Alpine.initializeComponent(el)
  })
})
```

Tries to initialize the alpine component but it fails to find the connected function: 

```
Uncaught ReferenceError: tagSelectTopic is not defined
    at eval (eval at saferEval (alpine.js:118), <anonymous>:3:36)
    at saferEval (alpine.js:118)
    at new Component (alpine.js:1416)
    at Object.initializeComponent (alpine.js:1861)
```
I really don't want to use a css hack for this. 

I write a select2 kind of searchable blade component using livewire and alpine and I want to share this with the community. 

The Component itself works fine - now I really need a way to make this conditionally available to complete it.

Livewire seems to not initialize javascript functions to the global scope when updating. 
Because the function is there when I inspect it inside the browser: 

```
       function tagSelect{{ucfirst($id)}}() {
            return {
                open: false,
                tags: [],
                textInput: document.getElementById('{{$id}}_textInput').value,
                focusSelect: null,
                addTag(tag) {
                    if (tag) {
```

The problem is, it's just not available. 

Is there any possiblity to get this working - maybe with hooks?

**Comment by roni-estein** [comment]
REOPEN

Hey just added some similar code in a blade component to another project and this is still an issue :(

Newest Livewire and alpine...

```blade
@if($attributes->has('long-running'))
  <span x-data="{ loading: false }">
    <button

      x-on:click="{ loading=true; }"
      x-bind:disabled="loading"
      type="{{ $type }}" {{ $attributes->merge(['class' => $colors[$color]]) }} {{ $attributes->except('class') }} >
      <span x-cloak x-show="loading"><x-icon.spinner/></span>
      <span class="px-2">{{ $slot }}</span>

    </button>
  </span>
@else
  <button
    type="{{ $type }}" {{ $attributes->merge(['class' => $colors[$color]]) }} {{ $attributes->except('class') }} >
    {{ $slot }}
  </button>
@endif
```
This works beautifully, if the component is visible on the page at the outset, however in some cases like a modal, that is added to the page with a @if loading is never set to false, and the button renders with the spinner and doesn't disable.

**Comment by Dimitris947** [comment]
This solution worked for me..
`document.addEventListener("DOMContentLoaded", () => {
            Livewire.hook('element.updated', (el, component) => {
                window.Alpine.discoverUninitializedComponents((el) => {
                    window.Alpine.initializeComponent(el)
                })
            })
        });`

This is add an listener for every time the DOM updates and the says to Alpine to initiate all the Uninitialized Components

**Comment by joostvanhoof** [comment]
I'm running into some similar issues with Livewire re-rendering the component. @Dimitris947 have you also used this with Alpine v3? Because I get `discoverUninitializedComponents is not a function`.

**Comment by booni3** [comment]
This does not work with V3... not sure what the solution is yet!

**Comment by adddz** [comment]
Having the same issues as well. I love Livewire and Alpine but they are not playing really nice together when it comes to conditionally rendering a Livewire component that has an Alpine component inside.

**Comment by joostvanhoof** [comment]
What I've ended up doing is adding a `wire:key` to the Alpine component which fixed the issue.

**Comment by adddz** [comment]
> What I've ended up doing is adding a `wire:key` to the Alpine component which fixed the issue.

Hi there. Could you post a code example please?

**Comment by joostvanhoof** [comment]
@adddz see below (note the `wire:key`). Note that this does not work when you define x-data outside the component as a function within `<script></script>`.

```
<div>
    @if ($thingIsShown)
        <div x-data="{ open: false }" wire:key="theThing">
            <button @click="open = true">Show More...</button>
            <ul x-show="open" @click.away="open = false">
                <li>
                <button wire:click="archive">Archive</button>
                </li>
                <li>
                <button wire:click="delete">Delete</button>
                </li>
            </ul>
        </div>
    @endif

    <button wire:click="showThing">foo</button>
</div>
```

**Comment by adddz** [comment]
> @adddz see below (note the `wire:key`). Note that this does not work when you define x-data outside the component as a function within `<script></script>`.
> 
> ```
> <div>
>     @if ($thingIsShown)
>         <div x-data="{ open: false }" wire:key="theThing">
>             <button @click="open = true">Show More...</button>
>             <ul x-show="open" @click.away="open = false">
>                 <li>
>                 <button wire:click="archive">Archive</button>
>                 </li>
>                 <li>
>                 <button wire:click="delete">Delete</button>
>                 </li>
>             </ul>
>         </div>
>     @endif
> 
>     <button wire:click="showThing">foo</button>
> </div>
> ```

Thanks man this works well. Any idea for generating a unique ID from within the Blade component to use as a wire key? In case you have the same component multiple times on the page.

**Comment by joostvanhoof** [comment]
@adddz couple of things you can do.

**If the component is in a loop**
You can use the `$loop` parameter that Laravel has available for you: `wire:key="{{ $loop->iteration }}"`. Or if you're looping over posts you can just use the model ID like so: `wire:key="{{ $post->id }}"`

**If the component is not in a loop and you're using the same component multiple times**
Just use something manual, like `wire:key="thing-1"` and `wire:key="thing-2"` etc.

I recently got weird behaviour because I had something within a blade `@if` statement. In that case it can help to wrap that `@if` statement in a `<div>`. Also see https://laravel-livewire.com/docs/2.x/troubleshooting

**Comment by adddz** [comment]
> @adddz couple of things you can do.
> 
> **If the component is in a loop**
> You can use the `$loop` parameter that Laravel has available for you: `wire:key="{{ $loop->iteration }}"`. Or if you're looping over posts you can just use the model ID like so: `wire:key="{{ $post->id }}"`
> 
> **If the component is not in a loop and you're using the same component multiple times**
> Just use something manual, like `wire:key="thing-1"` and `wire:key="thing-2"` etc.
> 
> I recently got weird behaviour because I had something within a blade `@if` statement. In that case it can help to wrap that `@if` statement in a `<div>`. Also see https://laravel-livewire.com/docs/2.x/troubleshooting

Thank you. I agree that if you don't set the `wire:key` and there's an `@if` conditional, some weird behavior might happen.

**Comment by skalero01** [comment]
> 👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.
> 
> I see this issue has been closed.
> 
> Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.
> 
> If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.
> 
> Re-opening actually helps us track which issues are a priority.
> 
> Reply "REOPEN" to this comment and we'll happily re-open it for you!
> 
> (More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

reopen

**Comment by mikebronner** [comment]
REOPEN

**Comment by BlueJ-D** [comment]
> I have only been able to get this to work using inline `x-data` attributes in Alpine 3.x, as mentioned above. Has anyone found a work-around that works with `<script>`-based `x-data` attributes?


What is your html structure? 

I just ran into this issue and was using :key from alpine inside a livewire @foreach didn't think to use wire:key! Thanks for the HU joostvanhoof.

Im using script based `x-data="function()"` with livewire conditionals inside a livewire loop and alpine binds on elements inside the conditionals. 
`wire:key="{{$model->id}}"` on the first container element inside the loop fixed the issue;

My structure is: 
```
<div x-data="function()">
    @forelse( $iterable as $iterab)
        @if
              <div x-bind:xxx="{ [function.bool] ? 'true' : 'false' }">....
```

**Comment by sawirricardo** [comment]
Can we reopen this? It seems this is still is an issue

**Comment by diazsasak** [comment]
> What I've ended up doing is adding a `wire:key` to the Alpine component which fixed the issue.

This worked for me thanks

**Comment by f-ricci** [comment]
The `wire:key` solution on the same element that defines the `x-data` attribute works but it kind of got buried in the conversation.

**Comment by aurawindsurfing** [comment]
I agree simply putting
```
wire:key="{{ rand() }}"
```

inside your component fixes this issue

**Comment by Maison-hub** [comment]
Same problem and for me this code works (livewire 2 and Alpine 3)

```js
window.livewire.hook('element.updated', (el, component) => {
    Alpine.start();
});
```
Put this in a js file after Livewire and alpine init.
