### ISSUE TITLE
file_get_contents failed to open  composer.json in production 

### ISSUE THREAD

**Issue by atmonshi** [livewire/livewire#922]
**Describe the bug**
livewire is requires the presence of composer.json in order to detect App namespace.

I have a deployment process that is cleaning the artefact files after it's deployed to the stage or production server. The file composer.json is not included in the artefact installed.

and I am getting the error 
`file_get_contents(/home/vagrant/site/composer.json): failed to open stream: No such file or directory`

**To Reproduce**
1. fresh laravel install
2. add livewire by Following the Quickstart in the doc and Create a component
3. visit / and make sure its works fine
4. run `$ mv composer.json composer.json.bak`  to simulate a production ENV
5. getting the error 
`file_get_contents(/home/vagrant/site/composer.json): failed to open stream: No such file or directory`

any one has any Idea around this ?

thank you .

**Comment by devcircus** [comment]
That is from laravel. Removing or renaming the composer.json file, in modern php applications, is not a standard or recommended practice. You will sooner or later run into problems.

**Comment by lancepioch** [comment]
This isn't Livewire specific. Maybe Laravel should look at the composer.lock instead. However, you'll have to create an issue there. I don't see anywhere in this repo that specifically requires a composer.json file to exist. For the time being you should simply not delete it during your build as it should do no harm to have it exist.
