### ISSUE TITLE
Components inside Modules 

### ISSUE THREAD

**Issue by rcristancho** [livewire/livewire#926]
Hi,

How do we use Laravel Livewire in large applications? In some small applications works wonderful, but in my large application we use the package [nwidar/laravel-modules](https://github.com/nWidart/laravel-modules) so we can separate the logic into small modules and inside this modules we need some components of Livewire to make a few operations.

In the documentation I read that you can put components inside folders, but I don't think that is the right approach.

**Comment by DanHarrin** [comment]
Hey there.

I'm not familiar with the `laravel-modules` package you mention, but you could try [publishing the Livewire config](https://laravel-livewire.com/docs/installation#publishing-config) and setting a custom namespace for components in each module.

Might be worth seeing if that helps with organization a bit?

**Comment by DanHarrin** [comment]
Hi again, I'm gonna close this for now. Please feel free to use [the discussions section](https://github.com/livewire/livewire/discussions) or the [Discord server](https://discord.gg/H884eyt) to continue conversation about this issue. Thanks!

**Comment by rcristancho** [comment]
@DanHarrin sorry the delay, but I tried that and works fine, some times the components doesn't work but establishing the namespace correctly and adding to Laravel::components works good
