### ISSUE TITLE
@this undefined on page refresh/direct navigation

### ISSUE THREAD

**Issue by rlcurrall** [livewire/livewire#929]
## Problem Description
I have noticed an issue with the `@this` Blade directive, where if you refresh the page you are currently on (or navigate directly to a page that uses this directive), this will result in in **undefined** rather than the desired Livewire component. This can be problematic when trying to setup a listener on a component.

### Example Code

**resources/views/livewire/sample.blade.php**
```blade
<div>
    <!-- Do your work, then step back. -->
</div>

@push('scripts')
<script>
    console.log(@this); /* Results in 'undefined' */

    /* Throws an error "Cannot read propery 'on' of undefined" */
    @this.on('event', () => { console.log('hello') });
</script>
@endpush
```

I have found a solution for this by utilizing the `onLoad` function of the global Livewire instance like so:

**resources/views/livewire/sample.blade.php**
```blade
<div>
    <!-- Do your work, then step back. -->
</div>

@push('scripts')
<script>
    window.livewire.onLoad(function () {
        console.log(@this) /* Results in the Livewire Component */

        /* Works as expected */
        @this.on('event', () => { console.log('hello') });
    });
</script>
@endpush
```

One thing I've noticed with this approach is that there are cases where the `onLoad` function is called before the livewire component is rendered on the page (usually when using the "SPA Mode"). so I ended up doing something like this:

```blade
<div>
    <!-- Do your work, then step back. -->
</div>

@push('scripts')
<script>
    const component = @this;
    const callback = () => { console.log('hello'); };

    if (component) {
        component.on('event', callback);
    } else {
        window.livewire.onLoad(() => {
            @this.on('event', callback);
        });
    }
</script>
@endpush
```

NOTE: Please let me know if an example repo would be more helpful to demo the issue than these code snippets.

**Comment by calebporzio** [comment]
This makes sense.

I recommend wrapping references to `@this` inside a DOMContentLoaded listener if they are loaded BEFORE the `@livewireScripts`:

```js
<script>
window.addEventListener('DOMContentLoaded', () => {...})
</script>
```

However, if you have your @stack('scripts') AFTER `@livewireScripts` in your template, everything should work!
