### ISSUE TITLE
Collection pivot data stripped during re-render

### ISSUE THREAD

**Issue by mscott83** [livewire/livewire#930]
**Describe the bug**
I'm trying to create a component based on Bootstrap's tabs. Each tab displays information about a relationship with another model. On the initial component load, I pass in a Collection which includes some pivot data. On first load, the related model's data is complete - everything is there including pivot data. However, if I click on another tab, something happens during the re-render and all of the pivot data is stripped out of the collection, just leaving the list of bare objects. This results in errors in my Blade view as the values I'm requesting no longer exist in the collection to be called. I have no idea why this is occurring. I'm not doing anything to modify the Collection within the component, i'm just reading values out of it.

**Expected behavior**
Moving between tabs should not result in the Collection being modified at all, it should just be as originally passed in.

**Comment by lancepioch** [comment]
Can you please post the minimum amount of code for the component and the view?

**Comment by mscott83** [comment]
The view:
`
<div>
    <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a wire:click.prevent="activeTab('Widget 1')" 
        class="nav-item nav-link {{$tab == 'Widget 1' ? 'active' : null}}" 
        id="nav-widget-1-tab" 
        data-toggle="tab" 
        href="#nav-widget-1" 
        role="tab">
            Widget 1
        </a>
        <a wire:click.prevent="activeTab('Widget 2')" 
        class="nav-item nav-link {{$tab == 'Widget 2' ? 'active' : null}}" 
        id="nav-widget-2-tab" 
        data-toggle="tab" 
        href="#nav-widget-2" 
        role="tab">
            Widget 2
        </a>
    </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade {{ $tab == 'Widget 1' ? 'show active' : null }}" id="nav-widget-1" role="tabpanel" aria-labelledby="nav-widget-1-tab">
        {{ $widgets }}
    </div>
    <div class="tab-pane fade {{ $tab == 'Widget 2' ? 'show active' : null }}" id="nav-widget-2" role="tabpanel" aria-labelledby="nav-widget-2-tab">Widget 2 tab content</div>
    </div>
</div>
`

**Comment by mscott83** [comment]
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class AirbaseUnits extends Component
{
    public $tab = "Widget 1";
    public $widgets;

    public function activeTab($name)
    {
        $this->tab = $name;
    }

    public function mount($widgets)
    {
        $this->widgets = $widgets;
    }
    
    public function render()
    {
        return view('livewire.factory-widgets', ['widgets' => $this->widgets]);
    }
}

**Comment by booni3** [comment]
```blade
Widget 1 Widget 2
{{ $widgets }}
Widget 2 tab content
```

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class FactoryWidgets extends Component
{
public $tab = "Widget 1";
public $widgets;

public function activeTab($name)
{
    $this->tab = $name;
}

public function mount($widgets)
{
    $this->widgets = $widgets;
}

public function render()
{
    return view('livewire.factory-widgets', ['widgets' => $this->widgets]);
}
}
```

**Comment by booni3** [comment]
You probably want to be changing tabs using Alpine rather than Livewire. When you change tabs in livewire you will be doing a re-render for each tab.

**Comment by booni3** [comment]
```blade
<div x-data="{ tab: 'foo' }">
    <button :class="{ 'active': tab === 'foo' }" @click="tab = 'foo'">Foo</button>
    <button :class="{ 'active': tab === 'bar' }" @click="tab = 'bar'">Bar</button>

    <div x-show="tab === 'foo'">Tab Foo</div>
    <div x-show="tab === 'bar'">Tab Bar</div>
</div>
```

https://github.com/alpinejs/alpine

**Comment by snapey** [comment]
From my observations, not because I know what is actually happening, the model with its relations is passed on the first render, but when re-hydrated in subsequent renders the model is re-queried using the class name and the primary key only.   I don't think it does anything with related models.

**Comment by calebporzio** [comment]
Livewire uses Laravel's internal system to serialize models and collections of models between requests. Here is the Laravel file itself: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php

In other words, Livewire uses the same mechanism Laravel uses to serialize model properties in queueable jobs.

This system DOES preserve loaded relationships, however, for a collection, it looks like it only references the first item in the collection to derive the relationships to load for all of them: 
![image](https://user-images.githubusercontent.com/3670578/86186568-69a7ef00-bb07-11ea-81a6-be15db5b74aa.png)

It's possible that you have different relationships for different items in the collection?

Either way, I would suggest making an issue in the Laravel repo for them to modify that file. I'd rather rely on Laravel's time-tested serialization system than roll my own.

Hope this helps.

Closing.

**Comment by anhofmann** [comment]
I don't know if this helps in this case. But I managed to get pivots working in Livewire by using a Model for my Pivot. Like this:

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;

class OrderTypeUser extends Pivot
{
    //
}
```

It is described here: https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models

**Comment by ItsMalikJones** [comment]
@anhofmann This works like a charm! Thanks!

**Comment by adddz** [comment]
> I don't know if this helps in this case. But I managed to get pivots working in Livewire by using a Model for my Pivot. Like this:
> 
> ```
> namespace App\Models;
> 
> use Illuminate\Database\Eloquent\Relations\Pivot;
> 
> class OrderTypeUser extends Pivot
> {
>     //
> }
> ```
> 
> It is described here: https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models

Hi there, do you mind explaining more how you were able to make it work after you create the intermediate model? How did you set your `wire:model` in the view and what your `save` method looks like in the Livewire component? Thank you.

**Comment by anhofmann** [comment]
Like this: 

```php
use App\Models\OrderTypeUser as OrderTypePivot;
use Livewire\Component;

class OrderTypeUser extends Component
{
    public OrderTypePivot $orderTypeUser;

    protected $rules = [
        'orderTypeUser.is_active' => 'bool',
    ];

 protected function save(): void
    {
        $this->orderTypeUser->save();
        $this->emitUp('checkActiveOrderTypeCount');
    }
}
```

**Comment by abdullahessam** [comment]
any update about that issue ?

**Comment by rashidabbas786** [comment]
What I observed, accessing the pivot table on first load is working fine. But when the component is rerendered, then it starts treating the `pivot` as the relation fo that model. Wich makes it to crash

**Comment by josegus** [comment]
> What I observed, accessing the pivot table on first load is working fine. But when the component is rerendered, then it starts treating the `pivot` as the relation fo that model. Wich makes it to crash

I managed to get pivots working in Livewire by using computed properties

**Comment by rashidabbas786** [comment]
> 

Great. Yes, that's what my friend suggested to me recently. That should work as the results are computed at the Model level.
