### ISSUE TITLE
Using HTML5 compliant attribute

### ISSUE THREAD

**Issue by MorganCarles** [livewire/livewire#933]
First thank's for you work. 

Is there any-possibility to define in the livewire config file the HTML attribute prefix to have an **HTML5 compliance**? 

Only those elements are valid HTML attributes : https://www.tutorialspoint.com/html5/html5_attributes.htm

so we've got errors on HTML5 validation using livewire components.

Perhaphs could you set in livewire config file an entry to customize this attribute?

```
  // in config/livewire.php
 'default_html_attribute' => 'wire', // by default to keep compatibility with previous versions, but could be changed to 'data-wire' if wanted
```

**Comment by calebporzio** [comment]
Good question.

No plans in adding this flexibility. As far as I know the attribute not being valid d html only causes validates to fail. Not browsers. All browsers support this syntax to my knowledge.

Good question though.

**Comment by MorganCarles** [comment]
Thank's for you answer. In fact, I think I'm too psychorigid, but, some clients needs an HTML validation when delivering a project, ans we'll cannot use this great package.

Have a nice day, good continuation :)

**Comment by DmitrijKunts** [comment]
If a web-resource needs organic traffic from Google, then the HTML 5 specification for pages is essential!

**Comment by calebporzio** [comment]
Is there evidence that `wire:` attributes hurt SEO?

**Comment by DmitrijKunts** [comment]
When you start a page with <! DOCTYPE html> this is an html 5 specification. But when the code on the page does not pass validation for Google, it is a signal that it is not HTML 5 and it is removing content with 2000 algorithms. And forget about semantic layout.
Buy some clean domains and experiment, here's the proof.

**Comment by Graphicfort** [comment]
Small tip for [basic navigate usage](https://livewire.laravel.com/docs/navigate#basic-usage) using [Vite](https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine)

change:
<pre>
&lt;nav&gt;
    &lt;a href="/" <b>wire:navigate</b>&gt;Dashboard&lt;/a&gt;
    &lt;a href="/posts" <b>wire:navigate</b>&gt;Posts&lt;/a&gt;
    &lt;a href="/users" <b>wire:navigate</b>&gt;Users&lt;/a&gt;
&lt;/nav&gt;
</pre>

to:
<pre>
&lt;nav&gt;
    &lt;a href="/" <b>data-wire="navigate"</b>&gt;Dashboard&lt;/a&gt;
    &lt;a href="/posts" <b>data-wire="navigate"</b>&gt;Posts&lt;/a&gt;
    &lt;a href="/users" <b>data-wire="navigate"</b>&gt;Users&lt;/a&gt;
&lt;/nav&gt;
</pre>

in app.js add **fix()** function just before **Livewire.start();** and to make the code working on every page call **fix()** function again with **livewire:navigated** event listener

app.js code:

<pre>
fix();

Livewire.start();

function fix() {
    document.querySelectorAll('[data-navigate=true]').forEach(link => {
        link.setAttribute('<b>wire:navigate</b>', '');
    });
};

document.addEventListener('livewire:navigated', () => {
    fix();
});
</pre>

**Comment by liamoreilly** [comment]
This is not really a solution. Such a first-party project should be producing valid HTML 5 - this is the point of a specification. We would hope all browsers work okay, but we can have more confidence if we produce webpages with valid HTML 5.
