### ISSUE TITLE
request()->session() throws error in tests

### ISSUE THREAD

**Issue by imliam** [livewire/livewire#936]
**Describe the bug**
If you have a Livewire component that uses the `request()->session()` method, it will throw an error in tests that use `Livewire::test()`

**To Reproduce**
Create a Livewire component that uses the `request()->session()` helper in some way:
```php
class ExampleComponent extends Component
{
    public function methodName()
    {
        request()->session()->put('foo', 'bar');
    }
}
```

Write a test that calls this method:
```php
/** @var test */
public function it_is_a_test()
{
    Livewire::test('example-component')->call('methodName');
}
```

You will get a `RuntimeException` when it gets to using the session method.
> "Session store not set on request."

This error comes from the `Illuminate\Http\Request::session()` method when it determines there is no session attached to the request.

**Workaround**
You can work around this problem by swapping `request()->session()` for `session()` inside the Livewire component:
```php
    public function methodName()
    {
        session()->put('foo', 'bar');
    }
```

**Expected behavior**
A session to be attached to the request, and to behave in the same way as using the `session()` global function.

**Comment by ryangjchandler** [comment]
Do any of the other `request()` helpers that are chained have the same problem. Does it still persist if you use the `Request` facade (I imagine it will since `request()` defers to it).

**Comment by cbaconnier** [comment]
@ryangjchandler I guess it will be the case.
I'm using the trait `Illuminate\Foundation\Auth\AuthenticatesUsers` in my Livewire component. It seems to works fine, but I get the error below too when running the tests
>  "Session store not set on request."

`AuthenticatesUsers` inject `Illuminate\Http\Request` and `$request->hasSession()` returns false

**Comment by devcircus** [comment]
As for as I know you can't use the standard laravel request in your livewire actions like this. Dump request() from an action to see details.

**Comment by cbaconnier** [comment]
@devcircus  Looks fine to me
It's been two day I did this and it's working fine. I had to override `validateLogin` and `attemptLogin` to use Livewire instead of the `$request` though

https://gist.github.com/cbaconnier/3947f908893e333e884aca945e3e95c0

This is the the result of `\Log::info($request);` , `$request->hasSession()` returns 1
```
[2020-06-09 15:34:41] local.INFO: array (
  'id' => 'bCMfG6imqkuXfprlRdDP',
  'data' => 
  array (
    'email' => 'john@example.org',
    'password' => 'password',
    'remember' => false,
  ),
  'name' => 'auth.login',
  'checksum' => '84be208268e3ba519bffce2b3897a78e63cb31478d144b53a54fedaf39ec1ead',
  'children' => 
  array (
  ),
  'actionQueue' => 
  array (
    0 => 
    array (
      'type' => 'syncInput',
      'payload' => 
      array (
        'name' => 'password',
        'value' => 'password',
      ),
    ),
    1 => 
    array (
      'type' => 'callMethod',
      'payload' => 
      array (
        'method' => 'login',
        'params' => 
        array (
        ),
      ),
    ),
  ),
  'errorBag' => 
  array (
    'email' => 
    array (
      0 => 'Ces identifiants ne correspondent pas à nos enregistrements',
    ),
  ),
)  
```

**Comment by calebporzio** [comment]
I'm not sure why that is happening in the tests.

However, I wouldn't recommend relying on the request() within Livewire component methods other than `mount()`.

I think `session()` and `Session::` are hands-down the best way to access the session.

Closing this. Thanks!
