### ISSUE TITLE
Handling file uploads

### ISSUE THREAD

**Issue by gwleuverink** [livewire/livewire#937]
On the time of writing this data binding on a file input is not supported. 
I notice more people hitting this roadblock and come up with some pretty crafty solutions of their own. 

The best way I found so far is actually handling the file outside of Livewire. Like described in issue #106. On the forum I also see people adopting this solution. 

While the workaround in issue 106 works well, it is less than ideal you have to leave Livewire to get file uploads to work. Especially showing real-time validation messages for the file upload felt a bit dirty, since the validation itself is handled outside of the component. 

--------------------

So i've been hacking away yesterday evening and devised a way to get file uploads to work, without ever having to leave the Livewire component.

I realize my solution is not ideal by any stretch of the word, but might be useful for someone until a first party solution is added to Livewire. So this issue is intended to help people who are struggling with file inputs and hopefully get some discussion going on how to improve the suggested workaround :)

## How it works
The Livewire component uses alpine in order to convert the selected file to a base64 string. This string is then emitted by Livewire event to the component.

_Just to clarify a little._ Any attempt to send the file back to the component as an object or form data of any kind fails. The Livewire component receives it as an empty array. That is why I opted to pas it as a string instead.

``` blade
<!--  Note that I have removed most tailwind classes for readability -->
<div>

    <label for="file">
        Profile picture
    </label>

    <!-- Shows a preview for the file & a delete button -->
    @if($file && !$errors->has('file'))
    <div class="relative" wire:key="preview">
        <img src="{{ $file }}" class="w-full -mb-2 rounded-md" />
        <button 
            wire:click="$set('file', '')" 
            type="button" 
            class="absolute right-0 top-0">
            delete
        </button>
    </div>
    @else

    <!-- The file input. The button hides a file input field and delegates click events to the input -->
    <div x-data="imageInput()" wire:key="file-input">
        <button @click="$refs.input.click()" type="button">
            Select file
        </button>
        <input 
            x-ref="input" 
            @change="set($refs.input.files[0])" 
            id="file" name="file" 
            type="file" 
            accept="image/png, image/jpeg" 
            class="cursor-pointer absolute block opacity-0 pin-r pin-t"
        >
    </div>
    
    @error('file') <div class="mt-1 text-red-500 text-sm">{{ $message }}</div> @enderror
    @endif

    @push('scripts')
    <script>
        const imageInput = function() {
            return {

                set: async function(file) {
                    livewire.emit('fileSelected', await this.convertBase64(file))
                },

                convertBase64(file) {
                    return new Promise((resolve, reject) => {
                        const reader = new FileReader();
                        reader.readAsDataURL(file);
                        reader.onload = () => resolve(reader.result);
                        reader.onerror = error => reject(error);
                    });
                }
            }
        }
    </script>
    @endpush
</div>
```

Then in the component class itself you can validate the file using [this package](https://github.com/crazybooot/base64-validation) (or roll it yourself). 
Using that package you can do file and image validation on base64 strings. Pretty nifty!

Install that package and continue to add the following code to your component:

``` php
use Livewire\Component;
use Illuminate\Support\Facades\Validator;

class SomeFormWithFileInput extends Component
{
    public $file = '';

    protected $listeners = ['fileSelected' => 'fileSelected'];


    public function fileSelected($file)
    {
        $validator = Validator::make(['file' => $file], [
            'file' => ['base64max:20']
        ]);

        if (!$validator->fails()) {
            $this->resetErrorBag('file');
            return $this->file = $file;
        }

        foreach ($validator->getMessageBag()->getMessages()['file'] as $message) {
            $this->addError('file', $message);
        };
    }

    //
}
```

That's it! Now you have real time validation for file inputs without ever having to leave Livewire!

Of course you still have to roll out your own logic for handling the file on form submit. I left that out on purpose.

## Closing
I think this solution is not ideal. File sizes are quite a bit bigger when encoded & i don't know if keeping files in Livewire state is safe (because of serialisation/deserialisation of potientially untrustworthy files). But I do think this beats having file input logic live within a different paradigm.

Hope @calebporzio comes with an out of the box solution!

**Comment by gwleuverink** [comment]
I realize this is not an issue, but decided to post here since I thought this is the first place people who are struggling with this would look.

**Comment by JayBizzle** [comment]
Fingers crossed 🤞 #958

**Comment by gwleuverink** [comment]
Nice! I’ll close this Issue as soon as that is merged.

**Comment by manuelgeek** [comment]
Awesome, saved me

**Comment by LarryBarker** [comment]
@gwleuverink How are you handling the storage of these files after they are converted to base64? I've tried decoding them and using the `Storage` facade but they seem to be corrupted 😭

**Comment by manuelgeek** [comment]
@LarryBarker 
You can do something like this;

```php
public function uploadBase64Img($img, $folder = '/upload/logo/')
    {
        if (!file_exists(public_path() . $folder)) {
            mkdir(public_path() . $folder, 0777, true);
        }

        $image_parts = explode(";base64,", $img);
        $image_type_aux = explode("image/", $image_parts[0]);
        $image_type = $image_type_aux[1];
        $image_base64 = base64_decode($image_parts[1]);
        $file = $folder . Str::random(10) . '. '.$image_type;

        file_put_contents(public_path() .$file, $image_base64);

        return $file ;
    }
```

**Comment by gwleuverink** [comment]
If it fails on something like this your file might be corrupt (assuming the file is a png)

‘’’ php
Storage::disk('local')->put("test.png", base64_decode($this->image));
‘’’

Caleb is working on a very comprehensive file upload integration. If you can wait you’d be wise to hold off on implementing it this way until that PR is merged.

**Comment by gwleuverink** [comment]
#958 was just merged. Closing this issue.

**Comment by GempitaRizki** [comment]
Thanks
