### ISSUE TITLE
Browser shows an empty select after update

### ISSUE THREAD

**Issue by osbre** [livewire/livewire#938]
**Describe the bug**

When i select value, select becomes blank, even if there are "selected" attribute. See screenshot(video?) below.

**To Reproduce**

<details>
<summary>TestComponent.php</summary>

```php
<?php

namespace App\Http\Livewire;

use stdClass;
use App\Order;
use Livewire\Component;
use Illuminate\Database\Eloquent\{Model, Builder};

class TestComponent extends Component
{
    public array $items = [];

    public function update()
    {
        $this->query()->find(array_keys($this->items))->each(function (Model $model) {
            $model->update($this->items[$model->id]);
        });
    }

    public function query(): Builder
    {
        return Order::query();
    }

    public function render()
    {
        $column = new stdClass();
        $column->title = 'Payment Type';
        $column->name = 'payment_type';
        $column->options = [
            'cash' => __('Cash'),
            'cashless' => __('Cashless'),
        ];

        return view('livewire.test-component', [
            'columns' => [
                $column,
            ],
            'rows' => $this->query()->orderBy('created_at', 'desc')->get(),
        ]);
    }
}
```

</details>

<details>
<summary>livewire/test-component.blade.php</summary>

```blade
<div>
    <hr>
    @foreach($rows as $model)
        @foreach($columns as $column)
        <select wire:model="{{ "items.{$model->getKey()}.{$column->name}" }}" wire:change="update">
            @foreach($column->options as $key => $title)
                <option @if($model->{$column->name} === $key) selected="selected"@endif value="{{ $key }}">
                    {{ $title }}
                </option>
            @endforeach
        </select>
        @endforeach
    @endforeach
</div>
```
</details>

<details>
<summary>Order.php</summary>

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'payment_type', // string
    ];
}
```

</details>

**Expected behavior**
Select shows me selected value.

**Screenshots**

![Peek 2020-05-08 12-36](https://user-images.githubusercontent.com/23292709/81393210-a0294500-9128-11ea-9ce5-56cd634dc368.gif)

**Desktop (please complete the following information):**
 - Browser Chrome 
```
Version 81.0.4044.122 (Official Build) Built on Ubuntu , running on elementary 5.1.4 (64-bit)
```

**Comment by booni3** [comment]
You can remove the `wire:change` becuase `wire:model` is already binding this value to the PHP variable. When you update the select this will update automatically. With wire:change I expect you are sending the request twice?

**Comment by osbre** [comment]
@booni3 Thanks! When i removed wire:change directory - bug is gone, but how can i process an incoming request to update data?

**Comment by booni3** [comment]
Please clarify what you mean by this? Wire model is a data binding so it will keep this input synced with php

**Comment by osbre** [comment]
I mean, how i can interact with the changed data?

I used `wire:change` to listen `<select>` changes, and store updated data in the database. (using `update` method, in my PHP-component).

**Comment by booni3** [comment]
Live wire has some updated hooks. Check the lifecycle section of the docs.

**Comment by osbre** [comment]
@booni3 Thank you!

Also link:
https://laravel-livewire.com/docs/lifecycle-hooks

**Comment by roni-estein** [comment]
remove the if in your option
```
@foreach($column->options as $key => $title)
    <option @if($model->{$column->name} === $key) selected="selected"@endif value="{{ $key }}">
```

if you just use `<option value="{{$key}}">{{$title}}</option>`you don't have to deal with any fancy work arounds. If you are trying to force the "selected value" in blade you are actually fighting against livewire itself. It's not well documented.

**Comment by barryvdh** [comment]
I'm having the same issue with a form library (symfony forms) which always sets the selected value. But this conflicts with the model binding and gives this result sometimes (randomly, like 1 in 5 times)
