### ISSUE TITLE
skip render when redirect is set

### ISSUE THREAD

**Issue by snapey** [livewire/livewire#940]
**Is your feature request related to a problem? Please describe.**
I have a component that renders a model.  In this component is a delete button. When the delete is hit, the function removes the model and sets the redirect.  Control then passes to the render() function which tries to render the now deleted model, resulting in an error.

**Describe the solution you'd like**
Issue a redirect without needing to render the full component.

**Describe alternatives you've considered**
I have a workaround that checks `$this->redirectTo` in the render method, ane immediately returns.  Unfortunately it also needs to return a view, and this must be populated with valid data even though it will not be seen.
```
    public function render()
    {
        if($this->redirectTo){
            return view('livewire.foodbanks.foodbank-card')->withFoodbank(new Foodbank());
        }

        // etc with the required render functionality
```

**Comment by jhoff** [comment]
I came across this as well. A slightly more efficient workaround is to override the `output()` method and return a simple string if `$this->redirectTo` is set:

```

    /**
     * Prevent render when redirecting
     *
     * @param Illuminate\Support\MessageBag $errors
     *
     * @return string
     */
    public function output($errors = null)
    {
        if ($this->redirectTo) {
            return '<div></div>';
        }

        return parent::output($errors);
    }
```

**Comment by calebporzio** [comment]
Ah interesting.

I think you're right. If an action before ->render() redirects, we should skip the rendering.

This would be a breaking change, so I will make a note to do this for V2.

Thanks!

**Comment by zepfietje** [comment]
Has this been implemented in V2? As far as I can see, I don't think so.

**Comment by SRWieZ** [comment]
Similarly we can't do redirections in mount() function in a full page component.

**Comment by yoeriboven** [comment]
Curious as well. Would be very useful to redirect before a user sees a page they shouldn't see.

**Comment by redbastie** [comment]
You can use `$this->skipRender()`

**Comment by zepfietje** [comment]
> You can use `$this->skipRender()`

This doesn't work for me, as it breaks rendering the page being redirected to.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by zepfietje** [comment]
REOPEN

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)

**Comment by joshhanley** [comment]
@chamilapj the fix has been merged but a release hasn't been tagged yet. Please test it once the next version has been released and let us know if you have any issues. Or you can pull in dev-master to test it's working as expected.

Hope this helps!
