### ISSUE TITLE
Slots in Livewire

### ISSUE THREAD

**Issue by bardh7** [livewire/livewire#941]
Hi,

Is it possible to do this in Livewire?

```
@livewire('modal')
    <p>Slot content here</p>
@endlivewire

// Laravel 7
<livewire:modal>
    <p>Slot content here</p>
</livewire>
```

Thanks.

**Comment by mblarsen** [comment]
AFAIK it is not possible. Someone else asked but I cannot find the issue + answer.

**Comment by mblarsen** [comment]
Found it here https://github.com/livewire/livewire/issues/68#issuecomment-599012420

**Comment by bardh7** [comment]
> Found it here [#68 (comment)](https://github.com/livewire/livewire/issues/68#issuecomment-599012420)

Thanks @mblarsen. According to @calebporzio, looks like we have to wait for this :)

**Comment by natedunn** [comment]
Given Caleb's response I am not sure we can expect this soon. Not even on the roadmap means I would be surprised to see it in v3. In the mean time I did find a (bloated) [work around](https://github.com/livewire/livewire/issues/68#issuecomment-695832256).

**Comment by mrspence** [comment]
Is this in the roadmap? :)
