### ISSUE TITLE
Ability to pass an array of components when emitTo

### ISSUE THREAD

**Issue by ezp127** [livewire/livewire#948]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to emit the same action to specific components and for that I have to call `emitTo` several times like so:
```
$this->emitTo('component-x', 'refreshMe');
$this->emitTo('component-y', 'refreshMe'); 
$this->emitTo('component-z', 'refreshMe'); 
```

**Describe the solution you'd like**
I would like to pass an array of components when they are performing the same action.
```
$this->emitTo(['component-x', 'component-y', 'component-z'], 'refreshMe');
```

**Comment by basepack** [comment]
Related: https://github.com/livewire/livewire/issues/845

**Comment by DanHarrin** [comment]
Hi, I'm gonna close this thread for now. Feel free to submit a pull request for this feature and we can get it reviewed for you. If you would like to continue your conversation about this feature, please use [the discussions section](https://github.com/livewire/livewire/discussions) or the [Discord server](https://discord.gg/H884eyt). Many thanks!
