### ISSUE TITLE
Events emitted on tests don't send the correct argument

### ISSUE THREAD

**Issue by adalessa** [livewire/livewire#953]
**Describe the bug**
Testing a component that expects an event to be emitted with parameters, the parameters are received on the method as only one on array format.
This happen just in the test not from the browser.

**To Reproduce**
Create a component, 
Create a listener for an event that expects a parameter
Create a test for the component in which emits the event with a parameter
See the error that the parameter receive is an array that contains the parameter sent

**Expected behavior**
The parameter should be the same that was send on the test.

**Additional context**
I found a fix for this. I am creating first the bug as the readme indicates before crating the PR.
The fix is in the trait of MakesCallsToComponent on the function emit is sending the $params variables to the "fireEvent"
        $this->fireEvent($event, $params);
To fix it just add the spread operation on $params
        $this->fireEvent($event, ...$params);

**Comment by thaisonle** [comment]
Also ran into this problem today. The emit testing method is sending the parameter wrapped in an array.

**Comment by adalessa** [comment]
I have created a PR https://github.com/livewire/livewire/pull/961 to solve this issue.
@thaisonle as a workaround I am using the "fireEvent" method.
