### ISSUE TITLE
AuthorizesRequests

### ISSUE THREAD

**Issue by dev-techguy** [livewire/livewire#955]
I do have followed this [https://laravel-livewire.com/docs/authorization](url) on how to authorize actions such as update and so and this is my code...

```php
<?php

namespace App\Http\Livewire\Auth\User;

use App\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Livewire\Component;

class Verify extends Component
{
    use AuthorizesRequests;

    /**
     * @param string $validation
     * @return Application|RedirectResponse|Redirector
     * @throws AuthorizationException
     */
    public function mount(string $validation)
    {
        $user = User::query()->findOrFail(decrypt($validation, true));
        $this->authorize('update', $user);

        $user->update([
            'email_verified_at' => now()
        ]);

        return redirect('/home');
    }

    public function render()
    {
        return view('livewire.auth.user.verify');
    }
}
```

On trying to update I get 

403 This action is unauthorized.

**Comment by dev-techguy** [comment]
Yeah got the problem forgot adding `email_verified_at` in the user model `$fillable`

**Comment by mblarsen** [comment]
Did you already create and enable a policy for your users model?

If you haven’t you’ll always get 403.

See here https://laravel.com/docs/7.x/authorization#creating-policies

**Comment by dev-techguy** [comment]
> Did you already create and enable a policy for your users model?
> 
> If you haven’t you’ll always get 403.
> 
> See here https://laravel.com/docs/7.x/authorization#creating-policies

I will check it out.

But on Livewire `https://github.com/livewire/livewire/issues/url` doesn't mention any of this.

**Comment by mblarsen** [comment]
I guess a bit of Laravel knowledge is assumed. But you are right the doc could mention that you have to put up your guards first.

**Comment by lancepioch** [comment]
Thanks Michael for the help, this issue is definitely Laravel specific
