### ISSUE TITLE
[Feature] Pagination events

### ISSUE THREAD

**Issue by mikemand** [livewire/livewire#959]
**Is your feature request related to a problem? Please describe.**
I would like to be able to scroll the page back to the top (of the table, of the page, of an element...) when paginating.

**Describe the solution you'd like**
My first thought would be to have an event fired when changing pages. This will allow developers to listen for this event and handle it however they want, and in whichever manner they require (Alpine, Vue, vanilla JS).

**Describe alternatives you've considered**
I've also considered having it just built right into Livewire so developers only have to set the element they want to scroll to via property (or maybe method?). I don't feel like this should be Livewire's responsibility, however.

**Comment by devcircus** [comment]
The methods that change pages are in the WithPagination trait. It maybe more simple if it was built in to livewire, but the way I handled it was to create a base PaginatedComponent that extends the livewire component. All of my components that need pagination, extend the PaginatedComponent. In there, I override the methods that change pages and dispatch an event.

**Comment by mikemand** [comment]
Hi @devcircus,

Do you have a single event or multiple (for the different pagination actions)? Would you mind sharing what you named your event(s)?

If this gets enough support, I'd be glad to make a PR to include the changes. Otherwise, I'll just do what you are doing and make a base component for my components that need pagination.

**Comment by devcircus** [comment]
My personal use-case is a single event for each page change. It doesn't account for which page we're going to, whether it was forwards or back, or which component fired the event. It is just a simple 'pagination.change' event, if needed though, you could send through the component name and the page.

I do the same thing with validation exceptions. When a validation exception is thrown in livewire, Livewire catches and handles the exception, so there's no easy way to run a custom method. The 'validate' and 'validateOnly' methods are also in a trait, so I just dispatch an event when the exception is thrown.

**Comment by calebporzio** [comment]
@devcircus, that's exactly what I would do if I needed that.

I'll leave it up to you to post more sample code here for others.

Thank you.

**Comment by JustSteveKing** [comment]
What is the best way to tap into the pagination change event when using both Livewire and Alpine? The current behaviour replaces the content inside the div which is fine, but it does not scroll back to the top of the containing div. Is there an easy way to do this at all? I only have the 1 paginating component on the page at the moment:

```html
<x-app-section>
    <livewire:commerce.range-list />
    <livewire:testimonial-list />
</x-app-section>
```

```php
class RangeList extends Component
{
    use WithPagination;

    public $active;

    public function mounted()
    {
        $this->active = null;
    }

    public function setActive(int $range)
    {
        $this->active = Range::with('tags')->find($range);
    }

    public function render()
    {
        return view('livewire.commerce.range-list', [
            'ranges' => Range::with('tags')->paginate(8)
        ]);
    }
}
```

**Comment by Norbertho** [comment]
> What is the best way to tap into the pagination change event when using both Livewire and Alpine? The current behaviour replaces the content inside the div which is fine, but it does not scroll back to the top of the containing div. Is there an easy way to do this at all? I only have the 1 paginating component on the page at the moment:
> 
> ```
> <x-app-section>
>     <livewire:commerce.range-list />
>     <livewire:testimonial-list />
> </x-app-section>
> ```
> 
> ```
> class RangeList extends Component
> {
>     use WithPagination;
> 
>     public $active;
> 
>     public function mounted()
>     {
>         $this->active = null;
>     }
> 
>     public function setActive(int $range)
>     {
>         $this->active = Range::with('tags')->find($range);
>     }
> 
>     public function render()
>     {
>         return view('livewire.commerce.range-list', [
>             'ranges' => Range::with('tags')->paginate(8)
>         ]);
>     }
> }
> ```

Hi, have you found the solution? I have the same issue.

**Comment by s1x** [comment]
> 
> 
> Hi @devcircus,
> 
> Do you have a single event or multiple (for the different pagination actions)? Would you mind sharing what you named your event(s)?
> 
> If this gets enough support, I'd be glad to make a PR to include the changes. Otherwise, I'll just do what you are doing and make a base component for my components that need pagination.

I was looking for an example too, so maybe this is helpful for other people who are looking for this I made a [gist](https://gist.github.com/s1x/bebedbc745b42748c8a9c6815ff6b73c). Make sure you add the event to your listeners.

**Comment by lucas-quinn-guru** [comment]
@s1x, This is great.  I've made a couple of adjustments.  

When `previousPage()` and `nextPage()` get called, it emits the `pageChanged` event and then calls the `setPage()` method **which also emits** the `pageChanged` event.  So, pageChanged() getsCalled twice.  You could remove the `$this->emit('pageChanged')` from `previousPage()` and `nextPage()` and it will still emit the event through the `setPage()` method.

Also, if I have more than one datatable on a page using different components, the `$this->emit('pageChanged');` would be fired from one datatable component and caught for all components which would get confusing.  So, I've made the change to where the `pageChanged()` method only gets called on within the component that it lives in without a global event and it doesn't have the delay of an event either.  (In this case, the only reason you would really need an event to be emitted would be to communicate with JavaScript on the frontend)

The only thing that you need in your class that extends PaginatedComponent is the method called `pageChanged()`.  But it doesn't matter with the code below if `pageChanged()` exists or not. 


```
use Livewire\Component;
use Livewire\WithPagination;

class PaginatedComponent extends Component
{
    use WithPagination;

    public function previousPage()
    {
        $this->setPage(max($this->page - 1, 1));
    }

    public function nextPage()
    {
        $this->setPage($this->page + 1);
    }

    public function setPage($page)
    {
        $this->page = $page;

        if( is_callable( self::class, 'pageChanged' ) ) {
            $this->pageChanged();
        }
    }

}
```

**Comment by maciek-szn** [comment]
> For anyone still wondering about this, in the latest 2.6 version you can hook into the pagination by adding methods to your component.
> 
>     * `updatedPaginators($page, $pageName)`
> 
>     * `updatingPaginators($page, $pageName)`

Thanks! Why it's still isn't mentioned in the docs? 🤔

**Comment by joshhanley** [comment]
@maciek-szn I think that is just an oversight. PR's are welcome to the docs! 🙂 https://github.com/livewire/docs
