### ISSUE TITLE
[Question] Move assets outside of LivewireManager - use mix

### ISSUE THREAD

**Issue by xorock** [livewire/livewire#960]
Currently, JS and CSS elements are embedded through the livewireStyles and livewireScripts directive. livewireStyles has 3 CSS rules, livewireScripts imports main js file + adds some lines of code. Is it possible to use Laravel mix to compile livewire assets?

**Comment by DanHarrin** [comment]
Hey, this behaviour is not supported out of the box with Livewire at the moment, and most people prefer the simplicity of `@livewireScripts` and `livewireStyles`. Feel free to open a new [discussion](https://github.com/livewire/livewire/discussions) to gather support for this feature. Many thanks!
