### ISSUE TITLE
Range slider not following value when wire model is added to input

### ISSUE THREAD

**Issue by sukhcha-in** [livewire/livewire#964]
**Describe the bug**
```
<input type="range" min="50" max="10000" step="50" value="50" wire:model="rangeSlider" />
```
The issue is that initial `value="50"` isn't working when `wire:model="rangeSlider"` is added to input. On page load/reload slider dragger remains in center instead of following given value.<br>

**To Reproduce**
1. Include this and see Slider grabber at center. **Doesn't work** 👎 
```
<input type="range" min="50" max="10000" step="50" value="50" wire:model="rangeSlider" />
```
2. Now include this one, slider grabber position at start. **Works Fine** 👍 
```
<input type="range" min="50" max="10000" step="50" value="50" />
```

**Expected behavior**
Range slider should be at start not in center because min is 50 and max is 10000 and value is 50

**Screenshots**
Doesn't Work:
![Oops](https://i.imgur.com/JBmmN01.png)
Works:
![Yay](https://i.imgur.com/xXMPBjV.png)

**Desktop (please complete the following information):**
 - Chrome macOS
 - Safari

**Additional context**
I thought `Alpine.js` might be causing this but no, I tried loading page after removing Alpine but no luck.<br>
Then I tried removing livewire scripts, and then it works fine.

**Comment by sukhcha-in** [comment]
Fixed it by giving initial value.
```
public $rangeSlider = 50;
```
I don't know what was causing that issue because HTML rendered is same in both cases :/

**Comment by roni-estein** [comment]
Just on a phone so I haven’t tried this,   but have you tried taking out the value =50 and leave in the wire model?
  

  
  
  

  
  
>

**Comment by DMJ-CV-91913** [comment]
doesn't work for me....

**Comment by djam90** [comment]
Why is this closed when it doesn't work?
