### ISSUE TITLE
Checkbox's value is ignored when provided, boolean used instead

### ISSUE THREAD

**Issue by ragulka** [livewire/livewire#965]
**Describe the bug**
When a [value is provided for a checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value), it's ignored when bound using `wire:model`. Instead fo sendign the actual value, a boolean `true/false` is sent.

**To Reproduce**
1. Create a checkbox `<input type="checkbox" wire:model="wantsCoffee" value="yes" />`
2. Click on the checkbox to trigger the AJAX request to backend
3. Inspect the request sent to the server :

```
"actionQueue": [{
    "type": "syncInput",
    "payload": {
        "name": "wantsCoffee",
        "value": true
    }
}]
```

**Expected behavior**
I would expect the `value` in the `payload` to be `"yes"`. This would follow the default browser behavior.

**Desktop:**
 - Browser: Firefox

**Comment by ahmedash95** [comment]
Hey @ragulka, I was able to reproduce it and purposed a fix. hope it gets merged soon :)

**Comment by calebporzio** [comment]
This has been fixed and will be in the next release.
