### ISSUE TITLE
Improve how the update method gets the input name attribute

### ISSUE THREAD

**Issue by HazJ** [livewire/livewire#966]
When creating a livewire component that uses the update method. The method automatically gets the input name attribute and appends it, but when your input name attributes contain underscores the format is a little different.
```
<input type="email" name="email">
updatedEmail
```
```
<input type="email" name="email_address">
updatedEmail_address
```
This to me looks really odd. Although changing the input name attribute to not contain an underscore is the simplest solution, I thought it might be nice to have the following:
- Automatically detect the underscore - email_address -> **updateEmailAddress**
- Be able to pass in the custom attribute name to the method - **updated("email_address")**

**Comment by lancepioch** [comment]
I think you're right and we should use camelCaseAllTheWay instead_of_snake_case.

**Comment by calebporzio** [comment]
This will be fixed in V2 of Livewire (I don't want to mess with this in the current version for fear of breaking existing apps.)

Current advice would be to camelCase the <input name=""> value
