### ISSUE TITLE
Allow contentEditable to be used as model

### ISSUE THREAD

**Issue by sukhcha-in** [livewire/livewire#970]
**Is your feature request related to a problem? Please describe.**
I would like to use `contentEditable` as an alternative to `input` field as a model. That would be cool :)

**Describe the solution you'd like**
Just allow models to be used on contentEditable

**Comment by sukhcha-in** [comment]
Used event emitter as an solution by listening to `keyup` event :)<br>
`window.livewire.emit('countChanged', input.innerHTML);`

**Comment by DanHarrin** [comment]
Cool, glad you found a solution!

**Comment by redbastie** [comment]
This is not a good solution because you are performing an HTTP request upon every keystroke.

**Comment by joshhanley** [comment]
@redbastie not ideal, but it depends on the OPs use case, it might work fine for their needs 🙂

As an alternative if anyway needs something better, you can create a blade component which is a div with contenteditable on it, and use Alpine to keep it in sync with Livewire using entangle, which essentially makes it act like a normal input with `wire:model` on the blade component.
