### ISSUE TITLE
File Uploads Validation Just Like Laravel does

### ISSUE THREAD

**Issue by dev-techguy** [livewire/livewire#972]
I tried to upload a file with laravel flow but it seems livewire doesn't understand that well.

Add the Feature Kindly...

**Comment by DanHarrin** [comment]
Hi, there is currently a pull request open for file upload support - #958. If you would like to see this feature complete, please contribute there. Thank you!

**Comment by dev-techguy** [comment]
Thanks...When will the feature be released.
