### ISSUE TITLE
wire:loading on an element with display flex does not work

### ISSUE THREAD

**Issue by capjjs** [livewire/livewire#976]
**Describe the bug**
wire:loading on an element that has display flex does not work. The element will always show even if it's not loading.

**To Reproduce**
add display:flex on an element with the wire:loading directive.

**Expected behavior**
I think wire:loading should wrap the element in another parent div and that parent div will be the one to trigger the show/hide.

**Comment by DanHarrin** [comment]
Hey, let's keep all discussion about this bug on #885. Feel free to submit a pull request if you find a nice solution. Many thanks!
