### ISSUE TITLE
Nested component unable to load after saving

### ISSUE THREAD

**Issue by jhayiwg** [livewire/livewire#983]
Hello,

First I wanted to say thank you for making this package.

I have an issue implementing a repeatable input section, the thing is adding and removing field section works but when I am trying to save it only loads the first field section. When I force reload the page, all the saved section values will display.

I tried adding $this->reset() from the submit action but still no luck. This is the preview https://d.pr/i/zcQRve

I hope you can help me with this.

Parent Component
`class Edit extends Component
{
    public $quiz_id;
    public $name;
    public $question;
    public $type = 'Multiple-Choice';
    public $options = [['is_answer'=>false, 'label'=>'']];
    protected $listeners = ['quiz_option_remove' => 'removeQuizOption', 'quiz_option_update' => 'updateQuizOption'];

    public $quiz_types;

    public function getQuizProperty()
    {
        return Quiz::find($this->quiz_id);
    }

    public function mount(Request $request, Quiz $quiz)
    {
        $this->init($quiz);
    }

    private function init(Quiz $quiz)
    {
        $this->quiz_id = $quiz->id;
        $this->name = $quiz->name;
        $this->question = $quiz->question;
        $this->type = $quiz->type;
        if( count((array) json_decode($quiz->options))  )
        $this->options = (array) json_decode($quiz->options);
        
        $this->quiz_types = QuizTypeEnum::list();
        
    }

    public function addOption(){
        array_push($this->options, ['is_answer'=>false, 'label'=>'']);
    }
    
    public function removeQuizOption($key){
        unset($this->options[$key]);
    }

    public function updateQuizOption($data){
        $this->options[$data['field_key']][$data['name']] = $data['value'];
    }

    public function submit()
    {
        $this->validate([
            'name' => 'required|min:6',
            'question' => 'required',
            'type' => 'required',
        ]);
        // Execution doesn't reach here if validation fails.
        $this->quiz->name = $this->name;
        $this->quiz->question = $this->question;
        $this->quiz->type = $this->type;
        if( count((array) json_decode($quiz->options))  )
        $this->options = (array) json_decode($quiz->options);
        $this->quiz->save();
        session()->flash('message', 'Post successfully updated.');
        $fresh = $this->quiz->fresh();
        $this->reset();
        $this->init($fresh);
    }

    public function render()
    {
        return view('livewire.admin.quiz.edit');
    }
}`

Parent Blade
`foreach( $options as $key_id => $json_option ) {
               $option = (array) $json_option ;
            ?>
            @livewire('admin.quiz.options.multiple-choice-item', 
                [
                    'key_id' => $key_id,
                    'is_answer' => $option['is_answer'] ?? false,
                    'label' => $option['label'] ?? ''
                ], key($key_id) )
   }`

Child Component
`class MultipleChoiceItem extends Component
{
    public $is_answer = false;
    public $label = '';
    public $key = 0;

    public function mount($is_answer, $label, $key_id)
    {
        $this->is_answer = $is_answer;
        $this->label = $label;
        $this->key = $key_id;
    }

    public function updated($name, $value)
    {
        $this->emitUp('quiz_option_update', [ 'name' => $name, 'value' => $value, 'field_key' => $this->key]);
    }
    
    public function render()
    {
        return view('livewire.admin.quiz.options.multiple-choice-item');
    }
}
`
Child Blade

`<tr>
    <td class="text-center"><input name="option[{{$key}}][is_answer]" wire:model="is_answer" type="checkbox" id="is_answer_{{ $key }}" /></td>
    <td><input type="text" name="option[{{$key}}][label]" wire:model="label" class="form-control" id="label_{{ $key }}" /></td>
    <td><button type="button" wire:click="$emitUp('quiz_option_remove', {{ $key }})" class="btn btn-primary">-</button></td>
< /tr>`

Request Response
`{
  "id": "jkKFEmqRY8DLWZGMhb7h",
  "name": "admin.quiz.edit",
  "dom": "<div wire:id=\"jkKFEmqRY8DLWZGMhb7h\">\n    <div class=\"alert alert-success\">\n        Post successfully updated.\n    </div>\n\n    <form wire:submit.prevent=\"submit\">\n        <div class=\"row\">\n            <div class=\"col-9\">\n                <div class=\"card\">\n                    <div class=\"card-header\">\n                        <h5 class=\"title\">Edit Quiz</h5>\n                    </div>\n                    <div class=\"card-body\">\n                            <div class=\"form-row\">\n                                <div class=\"col\">\n                                    <div class=\"form-group col-md-6\">\n                                        <label for=\"name\">Name</label>\n                                        <input type=\"text\" id=\"name\" class=\"form-control\" wire:model=\"name\">\n                                                                            </div>\n                                </div>\n                            </div>\n                            <div class=\"form-group col-md-12\">\n                                <label for=\"name\">Question</label>\n                                <textarea type=\"text\" class=\"form-control\" wire:model=\"question\"></textarea>\n                                                            </div>\n                            <div class=\"form-group col-md-12\">\n                                                                    <table class=\"table\">\n    <thead class=\" text-primary\">\n        <tr>\n            <th style=\"width:10%;\">Answer</th>\n            <th>Option</th>\n            <th>Action</th>\n        </tr>\n    </thead>\n    \n    <tbody>\n                    <tr wire:id=\"QsuZNS5L267ZGfh2ROI1\"></tr>                    <tr wire:id=\"acf1V2bDeAhaSrKMfEtq\"></tr>                    <tr wire:id=\"J1G5Uz3KLzKCG5gl3luF\"></tr>            </tbody>\n</table>\n<button type=\"button\" wire:click.prevent=\"addOption()\" class=\"btn btn-primary\">+</button>\n                                \n                            </div>\n                    </div>\n                </div>\n            </div>\n            <div class=\"col-3\">\n                <div class=\"card\">\n                    <div class=\"card-header\">\n                        <h5 class=\"title\"></h5>\n                    </div>\n                    <div class=\"card-body\">\n                        <div class=\"form-group\">\n                            <label for=\"name\">Type</label>\n                            <select wire:model=\"type\" class=\"form-control\">\n                                                                <option>Multiple-Choice</option>\n                                                                <option>Multiple-Answers</option>\n                                                                <option>True-Or-False</option>\n                                                                <option>Match-The-Pair</option>\n                                                                <option>Fill-In-The-Blanks</option>\n                                                                <option>Drag-Drop-Sort</option>\n                                                            </select>\n                                                </div>\n                        <div class=\"row\">\n                            <div class=\"col-md-12 text-right\">\n                                <button type=\"submit\" class=\"btn btn-info btn-round\">Save Changes</button>\n                            </div>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </form>\n</div>",
  "fromPrefetch": false,
  "redirectTo": false,
  "children": {
    "0": {
      "id": "QsuZNS5L267ZGfh2ROI1",
      "tag": "tr"
    },
    "2": {
      "id": "acf1V2bDeAhaSrKMfEtq",
      "tag": "tr"
    },
    "3": {
      "id": "J1G5Uz3KLzKCG5gl3luF",
      "tag": "tr"
    }
  },
  "dirtyInputs": [],
  "data": {
    "quiz_id": 17,
    "name": "Cum odit et accusantium soluta autem.",
    "question": "Culpa facilis nostrum sapiente perspiciatis distinctio. In consectetur ducimus nihil totam maiores fuga dolores aut. Ab occaecati nihil eaque a omnis molestiae perferendis iure.",
    "type": "Multiple-Choice",
    "options": {
      "0": {
        "label": "Porttitor placerat nulla necdfas a",
        "is_answer": true
      },
      "2": {
        "label": "Cursus vivamus vestibulum amet dui semper",
        "is_answer": false
      },
      "3": {
        "label": "Tristique posuere tincidunt inceptos diam a",
        "is_answer": false
      }
    },
    "quiz_types": {
      "Multiple-Choice": "Multiple-Choice",
      "Multiple-Answers": "Multiple-Answers",
      "True-Or-False": "True-Or-False",
      "Match-The-Pair": "Match-The-Pair",
      "Fill-In-The-Blanks": "Fill-In-The-Blanks",
      "Drag-Drop-Sort": "Drag-Drop-Sort"
    }
  },
  "eventQueue": [],
  "dispatchQueue": [],
  "events": [
    "quiz_option_remove",
    "quiz_option_update"
  ],
  "checksum": "50e583b784ef6231eed78a811f18035db007107b7c031846d0abc46347e805b8"
}`

- Livewire version: 1.1
- Laravel version: 7.0
- Browser: Chrome

**Comment by calebporzio** [comment]
Hi there, there is too much domain-code in this issue.

If you still have this problem, please reduce the issue to the smallest most generic component possible and re-post an issue.

Thank you.
