### ISSUE TITLE
Form request not being resolved as action parameter

### ISSUE THREAD

**Issue by sebastiansulinski** [livewire/livewire#990]
There seem to be an issue with form requests being injected to the component's action.
It appears to be connected to the use of `rescue()` helper within `Livewire\ComponentConcerns\HandlesActions::resolveActionParameters`.

Here's my setup:

```php
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProfileUpdateRequest extends FormRequest
{
    public function rules()
    {
        return [
            'username' => 'required|max:10',
            'about' => 'required',
        ];
    }
}
```

```php
namespace App\Http\Livewire

use Livewire\Component;
use App\Http\Requests\ProfileUpdateRequest;

class Profile extends Component
{
    public function update(ProfileUpdateRequest $request)
    {
         //...
    }
}
```

When `update()` method is invoked I get

> Argument 1 passed to App\Http\Livewire\Profile::update() must be an instance of App\Http\Requests\ProfileUpdateRequest, null given, called in /Users/sebastian/code/valet/livewire/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php on line 88

When I temporarily changed the guts of the `resolveActionParameters` by removing the `rescue()` helper wrap - it all works fine:

```php
protected function resolveActionParameters($method, $params)
{
    return collect((new \ReflectionMethod($this, $method))->getParameters())->map(function ($parameter) use (&$params) {
        if ($class = $parameter->getClass()) {
            return app($class->name);
        }
        return app($parameter->name);        
    });
}
```

It appears to be caused by the fact that the request throws an exception when validation fails, which is then catched by the `rescue()` helper. The problem persists even if we set 3rd argument to true (`$report = true`).

After going through the docs that seem to be intentional behaviour, but I'm not entirely sure why.

> You might be wondering if you can use Laravel's "FormRequest"s. Due to the nature of Livewire, hooking into the http request wouldn't make sense. For now, this functionality is not possible or recommended.

All component classes are under Http namespace and they are processing http requests therefore to me it does seem relevant to have this functionality available.

**Context**
- Livewire version: ^1.1
- Laravel version: ^7.0
- Browser: Chrome

**Comment by nuernbergerA** [comment]
Hey Sebastian,

this is actually not a bug.

Please visit the [docs](https://laravel-livewire.com/docs/input-validation) for more details
![image](https://user-images.githubusercontent.com/13331388/82469249-0ec0b800-9ac4-11ea-88b6-c21dbac1d7e1.png)

Feel free to open a [discussion](https://github.com/livewire/livewire/discussions)

**Comment by sebastiansulinski** [comment]
@nuernbergerA - cheers, yes - I've mentioned that in my original post. Any plans on adding this functionality? I really like having my validation logic separated from the actual action, plus you can do additional pre-validation work in the form request - putting all this into the component class would quickly bloat it.

**Comment by devcircus** [comment]
At the point an action is called, I don't think  the request exists in a way that could be utilized by form requests. 
That being said, you could still easily separate the validation logic to its own object and use it in a similar way.

**Comment by nuernbergerA** [comment]
What I did for existing projects with `FormRequest`'s was to just remove `extends FormRequest` and made `rules()` a `static` function.

In my new Livewire `component` I just call them.

```php
$this->validate(MyFormRequest::rules());
```

I hope this is works for you as well.

After we "reworked" DI we properly will discuss how to handle form-requests.

**Comment by sebastiansulinski** [comment]
Cheers - I think I will wait until this is implemented.
I'm at the cross roads at the moment - started building a brand new system and VueJs 3 isn't out yet plus there's no definite launch date - on the other hand I really like what Livewire has to offer, but there are a few things which aren't quite to my taste - form requests is what I've been using ever since I started working with Laravel and really like the functionality they provide out of the box. I would prefer to use existing functionality rather than code something additional that mimics it.

Out of interest - any particular reason why exceptions being suppressed from within `resolveActionParameters`?

**Comment by sebastiansulinski** [comment]
> What I did for existing projects with `FormRequest`'s was to just remove `extends FormRequest` and made `rules()` a `static` function.
> 
> In my new Livewire `component` I just call them.
> 
> ```
> $this->validate(MyFormRequest::rules());
> ```
> 
> I hope this is works for you as well.
> 
> After we "reworked" DI we properly will discuss how to handle form-requests.

Thanks @nuernbergerA - what I'll do for now is use your suggestion, but rather than converting `rules()` to static method  I will just inject it as I would with the actual form request.

```php
public function update(ProfileUpdateRequest $request)
{
    $this->validate($request->rules());

    // ...
}
```

Once / if - form requests will make its way later down the line, all I'll have to do is just extend the base class from within the given request.

**Comment by palokankare** [comment]
Hi,

there was a pull request to bring form requests like behaviour to Livewire.
#398

**Comment by sebastiansulinski** [comment]
@palokankare - thanks for that - I'm not sure the approach in that pull is quite what I was imagining. What I'm after is the injection and the original functionality of the request without the need for calling `$this->validate()` from within the component at all - giving the action method room to focus on what it's supposed to do knowing injected request already took care of all the validation - just like the original purpose of the form requests.

**Comment by DougThwaites** [comment]
In my case I generated a FormRequest as per usual which I will still use when finally saving the data but also then made a trait to pull in the rules and messages so i'm not duplicating anything.

**Trait**
`
<?php

namespace App\Http\Livewire\Traits;

trait HasFormRequest {

    public $rules = [];

    public $messages = [];

    public function mountHasFormRequest()
    {
        $this->formRequest = new $this->formRequest();
        $this->rules = $this->formRequest->rules();
        $this->messages = $this->formRequest->messages();
    }
}
`

**Component**
`
<?php

namespace App\Http\Livewire\Dashboard\Store\Edit\Content\Products;

use App\Http\Requests\Dashboard\UpdateStoreProductRequest;
use Livewire\Component;

class EditProduct extends Component
{
    use HasFormRequest;

    protected $formRequest = UpdateStoreProductRequest::class;

    ...
}
`

**Comment by alexandruu** [comment]
> 

December 2021 and still no will to incorporate in livewire the best practices from Laravel like Request Form. For me livewire seems to violate Single Responsibility Principle (at least) by adding in the component class all the logic from Request Form, Controller, View Composer etc.

**Comment by ahmedabdel3al** [comment]
@DougThwaites you can merge all public inputs in component to request then inject `FormRequest` as Parameter on the method 
it will work fine   
```
 public function updated(): void
    {
        request()->merge($this->all());
    }

    public function save(LoginRequest $loginRequest)
    {
    }
```
