### ISSUE TITLE
Actions ignore parameter default values

### ISSUE THREAD

**Issue by devcircus** [livewire/livewire#992]
### Description
If an action parameter has a default value, the value is ignored when the action is run.

### Steps to reproduce
```php
// in component

public function handleClick($first, $second = 'hello'): void
{
    dump($first);
    dump($second);
}
```

```html
<!-- in html -->
<div wire:click="handleClick('imasay')" class="cursor-pointer">Click Me</div>
```
### Result
```sh
"imasay"
null
```

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.9.2
- Browser: N/A

**Comment by devcircus** [comment]
Current workaround is to simply check if the value was provided:
```php
//...
$second = $second ?? 'hello';
dump($first);
dump($second);
```

Because PHP allows the method to continue based on the existence of the default value, the action will work as expected.

**Comment by nuernbergerA** [comment]
Hey Clayton,

Could you please include the payload that gets send via XHR?

---
This case should be covered by [this test](https://github.com/livewire/livewire/pull/924/files#diff-203eeff942cb37b066000cdd4538bcd3R36)

**Comment by devcircus** [comment]
```js
{
    actionQueue: [
        {
            type: "callMethod", 
            payload: {
                method: "handleClick", 
                params: ["imasay"]
            }
        }
    ],
    checksum: "f244734ce4b4cc0121c301fee1d2c8d786e83d6d69baf0aae89ea1893a19e035",
    children: {
        lXn5t8C: {id: "t1dhhpwEIduSHqoVAobx", tag: "div"}, 
        kPCScvy: {id: "9Ln6QpmLm8L8gPH3yh6P", tag: "div"}
    },
    data: {
        post: {
            class: "App\Models\Post", 
            id: "cb5eb458-95c2-4cb8-9e24-e0fa4cf1aeeb", 
            relations: []
        }
    },
    id: "dPRiS6yGcyVFrwfMeStp",
    name: "admin.posts.edit",
}
```

**Comment by devcircus** [comment]
A quick test like the one below shows that ```assertEquals``` loosely compares primatives, so in that test, ```''``` does indeed equal ```null```. So the test doesn't really test anything. Add any actual word and the test should fail.

```php
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTestStrict()
    {
        $this->assertEquals('', null); //----> passes
    }
```

**Comment by devcircus** [comment]
After more testing, Livewire explicitly passes null to the action for parameters with default values. When you explicitly pass null (and not just leave empty), the null overrides the default.

**Comment by nuernbergerA** [comment]
Wow, thanks for the detailed analysis.

I'll work on this now.

**Comment by devcircus** [comment]
No problem! I had pulled the repo down to tinker on it, then noticed what I [mentioned in your PR](https://github.com/livewire/livewire/pull/997#issuecomment-632025394). Sorry I didn't comment before you worked on the PR.
