### ISSUE TITLE
Selected dropdown option shows empty/blank text after wire:model update

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [livewire/livewire#998]
This is definitely a bug.  This only occurs when the first option is selected.  The DOM is updated to show the first option selected, but the rendered option text is empty.

This only impacts the first option with a value.  If there is a "placeholder" option with `value=""` doesn't seem to be impacted.

If you set `wire:ignore` on the `<select>` everything functions correctly.  This indicates it's something happening during the redraw of the DOM.

The DOM that is returned from a `wire:model` update has the correction `<option>` marked as `selected="selected"`.

I have confirmed this happening on both Firefox and Chrome.

![livewire-select-bug](https://user-images.githubusercontent.com/348801/82605946-6292d600-9b84-11ea-9624-4fe6e177598d.gif)

**Context**
- Livewire version: 1.1.0
- Laravel version: 7.12.0
- Browser: Firefox and Chrome

**Comment by ninthspace** [comment]
I've had this in various places. It only happens when you select an option further up from your original selection. The only way I fixed it (or worked around it) is to re-evaluate select tags after livewire has finished its DOM update, for example:

``` javascript
    document.addEventListener('livewire:load', function (event) {
        window.livewire.hook('afterDomUpdate', () => {
            const selectBoxes = document.querySelectorAll('select');
            selectBoxes.forEach(function (s) {
                const selectedOption = s.querySelector('option[selected]');
                if (selectedOption) {
                    s.value = selectedOption.value;
                }
            });
        });
    });

**Comment by JuanDeLeon** [comment]
I was running into this issue because I thought wire:model didn't "just work" by reading the docs. However, I finally came up with this, and it actually "just works" great.

`<select wire:model="city_id" class="block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
	@foreach($cities as $city)
		<option value="{{$city->id}}">{{ $city->name }}</option>
	@endforeach
</select>`

**Comment by SanderMuller** [comment]
I experienced this as well, only after reading this issue I understand what is happening.
Wire model handles setting the selected item, while you're used to manually having to set the selected attribute on the selected option. Doing so causing a conflict with livewire which sometimes makes it glitch out so no option will be visually selected, despite the DOM showing the correct selected attribute.

**Comment by ChrisThompsonTLDR** [comment]
@SanderMuller is 100% correct about the cause of this issue.

Removing the 'selected' from the `<select>` allows everything to work as expected.

I don't know that a code change is needed for this, but I would recommend some documentation be added about this behavior.

**Comment by vimalmistry** [comment]
Hi everyone. Sorry but I am facing same issue. I found reasonably interesting solution.

Just use
```html
<select  wire:loading.attr="disabled" ...
```

I hope it helps someone.
Thanks.

**Comment by jccjames422** [comment]
vimalmistry, this was a perfect solution for my issue.  Thanks!

**Comment by zvermafia** [comment]
without delving into the problem I found this: [Ignoring DOM-changes (using wire:ignore)](https://laravel-livewire.com/docs/2.x/alpine-js#ignoring-dom-changes)
